### PR TITLE
Made some Servlet related classes more welcoming to DI frameworks

### PR DESCRIPTION
**Pull request by Darsstar**
I've been working on the Vaadin-CDI plugin. [VaadinCDIServlet](https://github.com/Darsstar/cdi/blob/2.1/refactor/master/vaadin-cdi/src/main/java/com/vaadin/cdi/server/VaadinCDIServlet.java) is much cleaner when VaadinServletService can be proxied. It also enables Specialization, Interceptors and Delegators.

Haven't done the portlet variants, tomorrow I will try to find out if CDI and portlets mesh well together... first I need some sleep.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9658)

### CODE REVIEW

**Comment by Darsstar** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 194 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor4Q04Yke6p4vMWCvP:-Kor4Q05Kuf7_2eIK5Sa:b-t4x4tt) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinService.java#L194)):*
> ```Java
>      */
>     protected VaadinService() {
>         this.deploymentConfiguration = null;
> ```

Should be fine since it is private and this class always uses getDeploymentConfiguration(), which can be overridden.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 305 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor4FBCivm1QCkJT4O0:-Kor4FBCivm1QCkJT4O1:b-aiz61n) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L305)):*
> ```Java
>         readUiFromEnclosingClass(initParameters);
> 
>         readConfigurationAnnotation(initParameters);
> ```

The reason this method has to throw an ServletException.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 308 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor39HMGB8tI32aa1AJ:-Kor39HMGB8tI32aa1AK:bl7kqn2) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L308)):*
> ```Java
> 
>         // Read default parameters from server.xml
>         final ServletContext context = getServletConfig().getServletContext();
> ```

If someone has overridden getServletConfig() this might affect them.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 333 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor0uFixNeP5JGZZmkv:-Kor0oqY8V97YJiLXhB6:b-b3doqk) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L333)):*
> ```Java
>     protected VaadinServletService createServletService()
>             throws ServletException, ServiceException {
>         return createServletService(createDeploymentConfiguration());
> ```

This is to let the DI framework call createDeploymentConfiguration() when it is creating a service lazily.

---

*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 52 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor5tDid9BdvqOhGK1f:-Kor5tDid9BdvqOhGK1g:bdik3os) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServletService.java#L52)):*
> ```Java
>      */
>     protected VaadinServletService() {
>         this.servlet = null;
> ```

Should be fine since it is private and I made sure this class always uses getServlet(), which can be overridden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658)*

**Comment by hesara** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 194 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor4Q04Yke6p4vMWCvP:-KtFk90z0rcVa3nRLTlD:b1ig6ue) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinService.java#L194)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

Should be fine since it is private and this class always uses getDeploymentConfiguration(), which can be overridden.
</blockquote></details>

Perhaps the need to override (or otherwise intercept) getDeploymentConfiguration() could be mentioned in the javadoc of the method. This constructor could perhaps also be used by tests, although there it is usually fine to give a (mock) DeploymentConfiguration as a constructor parameter.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 191 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFky8BXezOu3NNNobc:-KtFky8BXezOu3NNNobd:bji6th5) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinService.java#L191)):*
> ```Java
>      * injection frameworks etc.
>      *
>      * @since 8.1
> ```

As this didn't make it to 8.1.0, could remove the version from the since tags and just leave the since tag without any version. That is flagged by our build so we can fill them in before release.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 305 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor4FBCivm1QCkJT4O0:-KtFmSD3iJHo_9Whx3gW:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L305)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

The reason this method has to throw an ServletException.
</blockquote></details>

OK

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 308 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor39HMGB8tI32aa1AJ:-KtFmTDHgLFF00naX3-i:b-8rnuby) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L308)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

If someone has overridden getServletConfig() this might affect them.
</blockquote></details>

What do you mean? Is there something special that merits a comment?

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 333 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor0uFixNeP5JGZZmkv:-KtFlWTAISNVmxpZKPn9:bs23gh7) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L333)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

This is to let the DI framework call createDeploymentConfiguration() when it is creating a service lazily.
</blockquote></details>

Could add a bit of javadoc, which could also mention this and have an empty since tag (see the comment above).

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 300 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFlhnsHBhiENOonIzl:-KtFlhnsHBhiENOonIzm:b-shnlz3) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServlet.java#L300)):*
> ```Java
>     }
> 
>     protected DeploymentConfiguration createDeploymentConfiguration() throws ServletException {
> ```

Should add javadoc, empty since tag (see the comment above).

This could probably also be overridden to simplify some tests.

Is it possible to override this method in a meaningful way for purposes other than tests, or is too much of what has to be called private?

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 326 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFmqt8TGRz8qLPuhGi:-KtFmqt8TGRz8qLPuhGj:b39mwg1) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServlet.java#L326)):*
> ```Java
>     }
> 
>     protected DeploymentConfiguration createDeploymentConfiguration(
> ```

(Ideally could add javadoc also for this method even though it was already there, as it becomes more relevant.)

---

*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 49 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFlDA1O5MVXfV2prtz:-KtFlDA1O5MVXfV2pru-:bb069tk) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServletService.java#L49)):*
> ```Java
>      * injection frameworks etc.
>      *
>      * @since 8.1
> ```

see my comment above about since tags

---

*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 52 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor5tDid9BdvqOhGK1f:-KtFko-ZGg_Kt3Fs1G1T:b4ri5ks) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServletService.java#L52)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

Should be fine since it is private and I made sure this class always uses getServlet(), which can be overridden.
</blockquote></details>

Like above, probably should mention the need to override getServlet() in the javadoc. That might also help avoid introducing more direct references to the field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658)*

**Comment by Darsstar** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 194 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor4Q04Yke6p4vMWCvP:-KtRXDCAazsyPwdHwcSu:b7u6an8) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinService.java#L194)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Perhaps the need to override (or otherwise intercept) getDeploymentConfiguration() could be mentioned in the javadoc of the method. This constructor could perhaps also be used by tests, although there it is usually fine to give a (mock) DeploymentConfiguration as a constructor parameter.
</blockquote></details>

Added javadoc to the new no-arg constructor and `getDeploymentConfiguration()`

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 191 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFky8BXezOu3NNNobc:-KtRWe8VqIpMW-dDcT7a:b8zwwkv) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinService.java#L191)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

As this didn't make it to 8.1.0, could remove the version from the since tags and just leave the since tag without any version. That is flagged by our build so we can fill them in before release.
</blockquote></details>

Removed version from `@since`

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 308 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor39HMGB8tI32aa1AJ:-KtGUfMkE40RehxDNShF:b57jrzr) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L308)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What do you mean? Is there something special that merits a comment?
</blockquote></details>

Just added it to be extremely thorough. Just because I think it should not be a concern for backward compatibility doesn't mean you agree. `getServletContext()` was being called on the instance passed into `init(ServletConfig)`. It is possible that someone was relying on it being a different object than is being returned by `getServletContext()`.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 333 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor0uFixNeP5JGZZmkv:-KtRadcQXeh_K9nG84j4:b-b6dyeb) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L333)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could add a bit of javadoc, which could also mention this and have an empty since tag (see the comment above).
</blockquote></details>

Added javadoc.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 300 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFlhnsHBhiENOonIzl:-KtGb-9BE5MH54wvuWDh:b-s9mpk8) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServlet.java#L300)):*
>Should add javadoc, empty since tag (see the comment above).

Done

>Is it possible to override this method in a meaningful way for purposes other than tests, or is too much of what has to be called private?

Other than overriding it to mark it as a producer I can't think of any.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 326 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFmqt8TGRz8qLPuhGi:-KtRaK8klzb7beH6S1N-:b-b6dyeb) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServlet.java#L326)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Ideally could add javadoc also for this method even though it was already there, as it becomes more relevant.)
</blockquote></details>

Added javadoc.

---

*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 49 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtFlDA1O5MVXfV2prtz:-KtRahF-qZqPr7Z_rhct:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServletService.java#L49)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see my comment above about since tags
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 52 at r3](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor5tDid9BdvqOhGK1f:-KtRaiS_ovlo_yuxNjjU:b-bdxyr4) ([raw file](https://github.com/vaadin/framework/blob/e7be6e1842d99c639c15da05444cbf3d3d08ebc6/server/src/main/java/com/vaadin/server/VaadinServletService.java#L52)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Like above, probably should mention the need to override getServlet() in the javadoc. That might also help avoid introducing more direct references to the field.
</blockquote></details>

Added javadoc to the new no-arg constructor and `getServlet()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 308 at r2](https://reviewable.io:443/reviews/vaadin/framework/9658#-Kor39HMGB8tI32aa1AJ:-KtVFpzh2qDZLdB6oXMs:b-aib34y) ([raw file](https://github.com/vaadin/framework/blob/b7f5e106704ac047f64ff11ade4e28c89f6f60a0/server/src/main/java/com/vaadin/server/VaadinServlet.java#L308)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

Just added it to be extremely thorough. Just because I think it should not be a concern for backward compatibility doesn't mean you agree. `getServletContext()` was being called on the instance passed into `init(ServletConfig)`. It is possible that someone was relying on it being a different object than is being returned by `getServletContext()`.
</blockquote></details>

This is possible in theory, but I think realistically it would only be a concern for some tests as the class wasn't very injection and interception friendly. If the validation build passes, I don't consider this a problem.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 303 at r4](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtVEdfFvOdpRoJmEaCi:-KtVEdfFvOdpRoJmEaCj:b-c1w34f) ([raw file](https://github.com/vaadin/framework/blob/52f5e2cf3144d2b35c1f420d50b233af5da17a50/server/src/main/java/com/vaadin/server/VaadinServlet.java#L303)):*
> ```Java
>     /**
>      * Creates a deployment configuration to be used for the creation of a
>      * {@link VaadinService}. Intended to be used by dependency Injection
> ```

(nit: inconsistent case for "dependency Injection")

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 309 at r4](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtVEQW5w8-2CFWgbcrK:-KtVEQW6KW3i6d96yPQZ:b-kc1h38) ([raw file](https://github.com/vaadin/framework/blob/52f5e2cf3144d2b35c1f420d50b233af5da17a50/server/src/main/java/com/vaadin/server/VaadinServlet.java#L309)):*
> ```Java
>      *
>      * @throws ServletException
>      *            if reading construction of the {@link Properties}
> ```

incomplete sentence, does not make sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658)*

**Comment by Darsstar** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 303 at r4](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtVEdfFvOdpRoJmEaCi:-KtWL3BLvv2LUZpE1oGU:b-7ql1td) ([raw file](https://github.com/vaadin/framework/blob/52f5e2cf3144d2b35c1f420d50b233af5da17a50/server/src/main/java/com/vaadin/server/VaadinServlet.java#L303)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(nit: inconsistent case for "dependency Injection")
</blockquote></details>

fixed

---

*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 309 at r4](https://reviewable.io:443/reviews/vaadin/framework/9658#-KtVEQW5w8-2CFWgbcrK:-KtWL08uPXw2D0QtZVKl:b-bjpj7a) ([raw file](https://github.com/vaadin/framework/blob/52f5e2cf3144d2b35c1f420d50b233af5da17a50/server/src/main/java/com/vaadin/server/VaadinServlet.java#L309)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

incomplete sentence, does not make sense
</blockquote></details>

Better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9658#-:-KtWLnbcLotkbtj85-4-:bnfp4nl)*

**Pull request merged**
