### PR TITLE
Improvements to detail row index handling.

### PR DESCRIPTION
**Pull request by Ansku**
- Escalator should notify when an existing details row is moved to a new
index.
- Grid and DetailsManagerConnector should update their internal indexing
when details manager index changes in Escalator.
- If TreeGrid has collapsed a row with open details, the row should
still have open details when it's expanded again.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)

### CODE REVIEW

**Review by ZheSun88 — DISMISSED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11345#-LUA1wnD20r_RsHSzoCS:-LUA1wnD20r_RsHSzoCT:b-ogq3cw) (no related file):*
the code looks fine. But i have a few observations after run the tests.

1) Does the test work under IE11? I tested locally, it doesn't work.  perhaps, we should run the IE11 tests by https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFramework_PullRequests_TestUITestIe11Edge&branch_VaadinFramework_PullRequests=pull%2F11345&tab=buildTypeStatusDiv;

2) with the `TreeGridDetailsManagerTest`, i can notice a short blinking when i open the details row, only if i click the row a bit faster.  

---

**Comment by Ansku** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/framework/11345#-LUA1wnD20r_RsHSzoCS:-LeqwGWQ7VYhDBGA9tp4:bnsxqwt) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

the code looks fine. But i have a few observations after run the tests.

1) Does the test work under IE11? I tested locally, it doesn't work.  perhaps, we should run the IE11 tests by https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFramework_PullRequests_TestUITestIe11Edge&branch_VaadinFramework_PullRequests=pull%2F11345&tab=buildTypeStatusDiv;

2) with the `TreeGridDetailsManagerTest`, i can notice a short blinking when i open the details row, only if i click the row a bit faster.  
</blockquote></details>

Added more tolerance to the test for IE and FireFox. There are a lot of issues left within TreeGrid even after this, some of which are addressed in pull request 11438 which builds on top of this one.

---

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)* status: 10 of 11 files reviewed, 7 unresolved discussions (waiting on @Ansku and @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 62 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMSFXe4MhJw8aiBW8w:-LiMSFXe4MhJw8aiBW8x:b-pg5fgt) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L62)):*
> ```
>  /* Registration for spacer index change handler. */
> ```
This type of javadocs bring no added value since it just repeats what is said by the variable name.
Could be removed or used to actually explain why it is needed here. Not blocking
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 200 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMSgn55SL0zXNzbRdW:-LiMSgn55SL0zXNzbRdX:b3p9qz5) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L200)):*
> ```
> remove spacer from old index and move to new index
> ```
This comment just confused me first, because it is not really removing the spacer but rather just updating book-keeping map.
Remove?
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 208 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMTba25lOJA_qtptn2:-LiMTba25lOJA_qtptn3:b-dr96wu) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L208)):*
> ```
>                             // no connector, make sure the new index doesn't
>                             // point to anything else either
> ```
When could this happen ?
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 227 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMUJNm9Sx6nuH0Z11y:-LiMUJNm9Sx6nuH0Z11z:b-hlkzu1) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L227)):*
> ```
>                             id = getDetailsComponentConnectorId(
>                                     event.getRowIndex());
> ```
If the spacer has been removed, could this be `null` ?
I'm presuming removing is handled anyway elsewhere, but just wondering if some corner case bug might be hiding here.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4985 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMWRbq8Z82RzRpB0u-:-LiMWRbq8Z82RzRpB0u0:bnwwuj4) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4985)):*
> ```
> public void setRowIndex(int rowIndex) {
> ```
Existence of this method implies that the spacers should be reused instead of being kept in the DOM ?
Why is this not happening ? 
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9444 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMZpK4279ZtDIea28I:-LiMZpK4279ZtDIea28J:b7dnz32) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9444)):*
> ```
>         boolean isVisible = isDetailsVisible(rowIndex);
>         boolean isVisibleInEscalator = escalator.getBody()
>                 .spacerExists(rowIndex);
> ```
I think you should add a clarifying comment for now that it is possible that the details _isVisible_ in Grid's logic but not in Escalator´s logic.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9454 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiM_WlG7wNLdfeZLLsk:-LiM_WlG7wNLdfeZLLsl:b1kvpxj) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9454)):*
> ```
> if (!visible)
> ```
Why this is kept ??? It is always executed if this line is reached

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)* status: 8 of 11 files reviewed, 7 unresolved discussions (waiting on @pleku and @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 62 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMSFXe4MhJw8aiBW8w:-LiO2Idv98H5CGKZG1w0:b-5n6s3n) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L62)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>  /* Registration for spacer index change handler. */
> ```
This type of javadocs bring no added value since it just repeats what is said by the variable name.
Could be removed or used to actually explain why it is needed here. Not blocking
</blockquote></details>

That's actually a regular comment and added for consistency since the one above had one too, but I reworked both to be a bit more informative.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 200 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMSgn55SL0zXNzbRdW:-LiMsJL1-wnuTWApfIix:bnk5zu) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L200)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> remove spacer from old index and move to new index
> ```
This comment just confused me first, because it is not really removing the spacer but rather just updating book-keeping map.
Remove?
</blockquote></details>

Updated it to a hopefully more informative version.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 208 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMTba25lOJA_qtptn2:-LiMwXdE8Yw6bR4GFvvg:b2q6ubc) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L208)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                             // no connector, make sure the new index doesn't
>                             // point to anything else either
> ```
When could this happen ?
</blockquote></details>

Can't remember and couldn't reproduce so I removed it altogether. Easy enough to put back if it turns out necessary.
___
*[client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java, line 227 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMUJNm9Sx6nuH0Z11y:-LiN3dka3CTBW7LGWwVo:be1umtz) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/connectors/grid/DetailsManagerConnector.java#L227)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>                             id = getDetailsComponentConnectorId(
>                                     event.getRowIndex());
> ```
If the spacer has been removed, could this be `null` ?
I'm presuming removing is handled anyway elsewhere, but just wondering if some corner case bug might be hiding here.
</blockquote></details>

I remember running into this if block (obviously, I didn't write it just for kicks) but I can't remember the circumstances and now I can't reproduce it so like above I removed it altogether for now. Never ran into the case where the id would have been null from both checks, though, or there would have been a check for both. The validation tests that I ran locally worked just fine even without, but it's easy enough to add back if it turns out necessary.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4985 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMWRbq8Z82RzRpB0u-:-LiNF9VsBlksGNe9oduz:bj4po8i) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4985)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> public void setRowIndex(int rowIndex) {
> ```
Existence of this method implies that the spacers should be reused instead of being kept in the DOM ?
Why is this not happening ? 
</blockquote></details>

That's what I thought too, initially, but in reality this is just for updating the logical index when other rows get added to or removed from above. Reusing doesn't actually work very well conceptually with either the old or new logic, because there is no spacer instance for every row by default. Each spacer is added when the details row is opened, and removed when it's closed. I did try to add experimental re-using at some point of working with the other pull request, but there was some internal index somewhere that I couldn't get to update properly so I gave up on it.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9444 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiMZpK4279ZtDIea28I:-LiNFtM82p7jNnMX_WzA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9444)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         boolean isVisible = isDetailsVisible(rowIndex);
>         boolean isVisibleInEscalator = escalator.getBody()
>                 .spacerExists(rowIndex);
> ```
I think you should add a clarifying comment for now that it is possible that the details _isVisible_ in Grid's logic but not in Escalator´s logic.
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9454 at r2](https://reviewable.io/reviews/vaadin/framework/11345#-LiM_WlG7wNLdfeZLLsk:-LiNHKZMBMjkGV_JFkHy:b-gqbaew) ([raw file](https://github.com/vaadin/framework/blob/46ea98ffe782fe5b6f6e68150e110c2b60c25800/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9454)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> if (!visible)
> ```
Why this is kept ??? It is always executed if this line is reached
</blockquote></details>

Oversight from refactoring, removed.

**Review by pleku — APPROVED** [review]
:lgtm:
(tests only looked through but not reviewed properly due to lack of time)

Fine to merge by me, or get someone else to review the test code properly.

> Reviewed 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345#-:-LjuA9909tGfV_XaNXbR:bb7edqs)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

**Review by pleku — APPROVED** [review]
> Dismissed @ZheSun88 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)* status: all files reviewed, 1 unresolved discussion

**Comment by pleku** [comment]
@Ansku your call to merge this if validation passes.

Any further validation failures for more extensive browser testing (IE11 & Firefox) will need to be fixed before this can be included in a stable FW 8 release.

**Review by pleku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11345)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
