### PR TITLE
Enhancement of Window component to limit the area over it can float

### PR DESCRIPTION
**Pull request by mdre**
The Window component acts as a top window floating over anything. When the browser area is small, in some cases due to the existence of browsers bars, the window height can  surpass the base of the browser and no scrollbar is showed. Normally in that area are the buttons associated with its operation and are out of focus.
Also, by floating over the menus, confuses users.
This patch create a WindowDesktop that allow you define an area over which the window can move.
Since WindowDesktop is implemented as a Panel with a CssLayout, when a Window float or surpass the bottom of the WD, it show a scrollbar so always you can show the window.
It's is implemented in a way that if you add the windows to the UI is have the old behavior, but if you add to a WindowsDesktop it limit the movements.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10403)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 4 files at r3.
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M9BTcH3ammcT4Gtkh:-L1M9BTcH3ammcT4Gtki:b-lce6rj) (no related file):*
Can you add a simple test UI in the `uitest` module that displays the usage and can be manually tested?

---

*[server/src/main/java/com/vaadin/ui/Window.java, line 13 at r3](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M9S-RPVrhYl4kGeQg:-L1M9S-RPVrhYl4kGeQh:b97euhu) ([raw file](https://github.com/vaadin/framework/blob/da50205433a335bfe2a9d4d0fb69532d8470b92a/server/src/main/java/com/vaadin/ui/Window.java#L13)):*
> ```Java
>  * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
>  * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
>  * License for the specific language governing permissions and limitations under
> ```

There are a lot of unnecessary changes in this file. Please make sure you're following the clean up and formatting conventions provided in the project.

---

*[server/src/main/java/com/vaadin/ui/WindowDesktop.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M6usTrc7LRpPbXFLj:-L1M6usTrc7LRpPbXFLk:boao9b6) ([raw file](https://github.com/vaadin/framework/blob/d978d05599aaf1080d3916211099c4d147bf223b/server/src/main/java/com/vaadin/ui/WindowDesktop.java#L41)):*
> ```Java
>  * @author Marcelo D. Ré {@literal <marcelo.re@gmail.com>}
>  */
> public class WindowDesktop extends Panel {
> ```

Missing class-level JavaDocs. Also all `public` and `protected` methods should have those (except when overriding).

---

*[server/src/test/java/com/vaadin/tests/server/components/WindowTest.java, line 42 at r3](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M7F0dwbMuqPrLZ_W3:-L1M7F0dwbMuqPrLZ_W4:b68hb22) ([raw file](https://github.com/vaadin/framework/blob/da50205433a335bfe2a9d4d0fb69532d8470b92a/server/src/test/java/com/vaadin/tests/server/components/WindowTest.java#L42)):*
> ```Java
>                 .addCloseListener(cl);
>         sendClose(window);
>         System.out.println("window: " + window);
> ```

`System.out` debugging should be removed.

---

*[shared/src/main/java/com/vaadin/shared/ui/window/WindowState.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M77tYvKF9vAXWew2a:-L1M77tYvKF9vAXWew2b:b-g1kqjy) ([raw file](https://github.com/vaadin/framework/blob/d978d05599aaf1080d3916211099c4d147bf223b/shared/src/main/java/com/vaadin/shared/ui/window/WindowState.java#L59)):*
> ```Java
>     @NoLayout
>     public String assistiveTabStopBottomText = "Bottom of Dialog";
>     
> ```

extra whitespace

---

*[shared/src/main/java/com/vaadin/shared/ui/windowdesktop/WindowDesktopState.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M7PfnoyqFZTovI9Rw:-L1M7PfnoyqFZTovI9Rx:b-xxsrev) ([raw file](https://github.com/vaadin/framework/blob/da50205433a335bfe2a9d4d0fb69532d8470b92a/shared/src/main/java/com/vaadin/shared/ui/windowdesktop/WindowDesktopState.java#L28)):*
> ```Java
>  */
> public class WindowDesktopState extends PanelState {
>     private final static Logger LOGGER = Logger.getLogger(WindowDesktopState.class .getName());
> ```

where is this used and why?

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_window.scss, line 102 at r3](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M7YlF53CSiTaVoijY:-L1M7YlF53CSiTaVoijZ:b-mbz7pf) ([raw file](https://github.com/vaadin/framework/blob/845daf7853762e81685f8ed0db6639c242f950fb/themes/src/main/themes/VAADIN/themes/valo/components/_window.scss#L102)):*
> ```SCSS
> 
>   .#{$primary-stylename}-draggingCurtain {
>     position: fixed !important;
> ```

Does the Drag&Drop still work with these style rules removed? Why is the `-draggingCurtain` block still here if not needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by mdre** [comment]
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1M9BTcH3ammcT4Gtkh:-L1M_gjUtYfBal6M34o3:blzjnyn) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Can you add a simple test UI in the `uitest` module that displays the usage and can be manually tested?
</blockquote></details>

Hi Teemu.
I'm writing the test. 
I see that there a lots of diff but mostly in the comments. I have changed some thing but really not too much. It's seems my IDE has fixed some parts... I'm not sure...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1RzIObgQX2kVHgKluK:-L1RzIObgQX2kVHgKluL:b-hm4weu) (no related file):*
Now that I look at this change more thoroughly it came to me that this could be done by subclassing inside a `Composite` to make a specific `Window` component. This way we'd not need to add special cases into the existing `Window` but override the relevant parts. The check in the `setParent` of `Window` looks a bit fragile to me.

The main idea in my suggestion is to have
```
class WindowDesktop extends Composite {
    class WindowPanel extends Panel { /* What ever is needed here */}
    class LimitedWindow extends Window {
        public void setParent(HasComponents parent) {
            if (parent instanceof WindowPanel) { /* set up */ } else { /* throw */ }
        } 
        /* Other changes if needed */
    }
    WindowDesktop() { setCompositeRoot(new WindowPanel()); }
    /* Provide specific API for WindowDesktop and nothing extra */
}
```

This way we reduce the amount of special casing around the WindowDesktop and don't need to provide any extra APIs that we don't want to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by mdre** [comment]
Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1RzIObgQX2kVHgKluK:-L1STDYCwGiFWc-u60U3:b-ylv3x7) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Now that I look at this change more thoroughly it came to me that this could be done by subclassing inside a `Composite` to make a specific `Window` component. This way we'd not need to add special cases into the existing `Window` but override the relevant parts. The check in the `setParent` of `Window` looks a bit fragile to me.

The main idea in my suggestion is to have
```
class WindowDesktop extends Composite {
    class WindowPanel extends Panel { /* What ever is needed here */}
    class LimitedWindow extends Window {
        public void setParent(HasComponents parent) {
            if (parent instanceof WindowPanel) { /* set up */ } else { /* throw */ }
        } 
        /* Other changes if needed */
    }
    WindowDesktop() { setCompositeRoot(new WindowPanel()); }
    /* Provide specific API for WindowDesktop and nothing extra */
}
```

This way we reduce the amount of special casing around the WindowDesktop and don't need to provide any extra APIs that we don't want to.
</blockquote></details>

I think WindowDesktop could be a Composite but I don't find a way to extends the Window component and get what I want. That was my first attempt.

IMO, I don't want to loose the access to the underlying panel. I think that that surface could be used to add more component if we want, so we need to add a getWindowPanel() in the API.

The real problem is the way is implemented the Window component. In particular, the VWindow. It is coded to be a top windows always. 
VWindow generate the js and if it not modified, i do not see any way to set the correct client parts of this. It position calculation must be padded to the container.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1RzIObgQX2kVHgKluK:-L1WNK5XoCHOlrkJDpmr:b72fciv) (no related file):*
<details><summary><i>Previously, mdre wrote…</i></summary><blockquote>

I think WindowDesktop could be a Composite but I don't find a way to extends the Window component and get what I want. That was my first attempt.

IMO, I don't want to loose the access to the underlying panel. I think that that surface could be used to add more component if we want, so we need to add a getWindowPanel() in the API.

The real problem is the way is implemented the Window component. In particular, the VWindow. It is coded to be a top windows always. 
VWindow generate the js and if it not modified, i do not see any way to set the correct client parts of this. It position calculation must be padded to the container.  

</blockquote></details>

That sounds like there are some customisations also needed on the client-side part. Can you guesstimate how much it would take to extract those parts into their own protected methods and overridden with a custom connector and an extended version of the `VWindow` class? 

The main trick in extending client side parts is:
```
1) Make your own server class
2) Make SomeGoodNameConnector extends WindowConnector
3) Add @Connector(package.to.my.new.Window) for the Connector class
4) Make SomeGoodNameForAWindow extends VWindow
5) Override Connector getWidget to return the new class, cast super.getWidget() to said class
6) Modify classes as needed
```

The API of the `Composite` is what ever you want to expose from it, so getting the `Panel` should not be a problem. Also you might want to just provide easy access to the parts of the Panel you want to access as custom API. `public void addComponent(Component c) { internalPanelLayout.addComponent(c); }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by mdre** [comment]
I have a Widget version of this component. I start making that, copying and
rewriting the original classes and it work but there some things that make
it float slow. After that, and knowing the code, I decide to fork the
framework and make the changes there and all work really well. We are using
the modified framework in a DEV server to test it and work as a charm.

If I found some time, I'll write a third widget version trying extends as
you say.

**Comment by mdre** [comment]
Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10403#-L1RzIObgQX2kVHgKluK:-L2RjLM_snrVHWS0-Atj:b-1327hj) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

That sounds like there are some customisations also needed on the client-side part. Can you guesstimate how much it would take to extract those parts into their own protected methods and overridden with a custom connector and an extended version of the `VWindow` class? 

The main trick in extending client side parts is:
```
1) Make your own server class
2) Make SomeGoodNameConnector extends WindowConnector
3) Add @Connector(package.to.my.new.Window) for the Connector class
4) Make SomeGoodNameForAWindow extends VWindow
5) Override Connector getWidget to return the new class, cast super.getWidget() to said class
6) Modify classes as needed
```

The API of the `Composite` is what ever you want to expose from it, so getting the `Panel` should not be a problem. Also you might want to just provide easy access to the parts of the Panel you want to access as custom API. `public void addComponent(Component c) { internalPanelLayout.addComponent(c); }`
</blockquote></details>

Hi again. Sorry for the delay but i'm currently in my vacation.
I have see and not found a way to implement this in a clear way without the modification needed en VWindow. 
This method:
      private Element getDraggingCurtain() 
      private void beginMovingWindow(Event event) 

could not be override. And the _windows.css shoud be modified. Without  this, it is no posible or I do not see a solution. A full write of a new the component it is not desirable. I think it could be confused to use. I really liked the behavior of windows in the old MS Visual FoxPro (RIP). There you can set a windows to be a top or subwindow just setting a property.

The rewrite of the WindowsDestop is in progress. I think your approach is better since is necessary to define what happening when a windows is minimized. I bar of windows like Windows, KDE or a left/right dock like Unity could be fine.

Have a nice day   

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10403)*

**Comment by elmot** [comment]
Review status: 1 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/WindowDesktop.java, line 96 at r6](https://beta.reviewable.io/reviews/vaadin/framework/10403#-L9dNyVlE_l2mGH7wwvI:-L9dNyVmCufgMr4QAbYl:biedhni) ([raw file](https://github.com/vaadin/framework/blob/ea2eda82367ead2377a1101ef55ba1df36ef55da/server/src/main/java/com/vaadin/ui/WindowDesktop.java#L96)):*
> ```Java
>     protected WindowDesktopState getState() {
>         return (WindowDesktopState)super.getState();
>         
> ```

extra spaces 

---

*[server/src/test/java/com/vaadin/tests/server/components/WindowTest.java, line 49 at r6](https://beta.reviewable.io/reviews/vaadin/framework/10403#-L9dO41YBM-54eL7_Bnt:-L9dO41YBM-54eL7_Bnu:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/ea2eda82367ead2377a1101ef55ba1df36ef55da/server/src/test/java/com/vaadin/tests/server/components/WindowTest.java#L49)):*
> ```Java
>         windowCloseListenerRegistration.remove();
>         sendClose(window);
>         System.out.println("end.");
> ```

To be removed

---

*[server/src/test/java/com/vaadin/tests/server/components/WindowTest.java, line 92 at r6](https://beta.reviewable.io/reviews/vaadin/framework/10403#-L9dO64D-IK6zeGt2BST:-L9dO64D-IK6zeGt2BSU:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/ea2eda82367ead2377a1101ef55ba1df36ef55da/server/src/test/java/com/vaadin/tests/server/components/WindowTest.java#L92)):*
> ```Java
> 
>     private static void sendClose(Window window) {
>         System.out.println("sendClose: w: "+window.getClass());
> ```

To be removed

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_window.scss, line 102 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10403#-L9dOFUC13FgqrHlQyS4:-L9dOFUC13FgqrHlQyS5:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/d978d05599aaf1080d3916211099c4d147bf223b/themes/src/main/themes/VAADIN/themes/valo/components/_window.scss#L102)):*
> ```SCSS
> 
>   .#{$primary-stylename}-draggingCurtain {
>     /*background: element;*/
> ```

To be removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10403)*

**Comment by pleku** [comment]
Thanks for the contribution. Sorry for the lack of activity from our side. I think this has been due to the latest review comments not being answered, but we could have fixed those ourselves too.

Now the problem is that I cannot easily checkout and test the change, since it appears the fork has been removed
```
mdre wants to merge 7 commits into vaadin:master from unknown repository
```
Currently there isn't anything we can do for this PR so closing it. Please reopen it if still valid.

**Pull request closed without merging**
