### PR TITLE
remove a & button styling from _global

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9607)

### CODE REVIEW

**Comment by hesara** [comment]
Rebased #9136 to be able to test it more extensively, as how tests are run has changed since its base change.

**Comment by hesara** [comment]
@knoobie please click the CLA button to accept the contributor license agreement so that we can merge this if tests pass.

**Comment by knoobie** [comment]
@hesara done! Thank you for the reminder.

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9607)*

**Pull request merged**
