### PR TITLE
Upgrade GWT version

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9056)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9056#-KhRhS3jzUL9kw5V32gE:-KhRhS3krXkiK4oi6CeZ:ba8rye7) (no related file):*
Please do not merge until gwt-2.7.0-vaadin5 is ready

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9056)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9056#-KhRhS3jzUL9kw5V32gE:-KjMhw6A7CDY9F6XB_kL:b-5awad7) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please do not merge until gwt-2.7.0-vaadin5 is ready
</blockquote></details>

Now it's ready.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9056)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9056)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9056)*

**Pull request merged**
