### PR TITLE
Juhopiirainen patch 2

### PR DESCRIPTION
**Pull request by juhopiirainen**
Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11571)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11571)* status: all files reviewed, 1 unresolved discussion (waiting on @juhopiirainen)

___
*[documentation/getting-started/getting-started-maven.asciidoc, line 49 at r7](https://reviewable.io/reviews/vaadin/framework/11571#-Lep98gG-32qoAQ65Pqf:-Lep98gG-32qoAQ65Pqg:b4n877y) ([raw file](https://github.com/vaadin/framework/blob/f62cf8d2ddd945aa657a474283bac686c8a6a150/documentation/getting-started/getting-started-maven.asciidoc#L49)):*
> ```AsciiDoc
> 
> [parameter]#archetypeArtifactId#:: The archetype ID.
> See the list of available archetypes in <<dummy/../../../framework/getting-started/getting-started-archetypes#getting-started.archetypes,"Overview of Maven Archetypes">>.
> ```

This link is still not working, because of the repo structure has been changed during the period.. so try with the following one  :

`dummy/../../../documentation/getting-started/getting-started-archetypes#`

**Comment by juhopiirainen** [comment]
Changed the URL. Lets see if this works.

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11571)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ZheSun88** [comment]
Tested, it works. :-)

**Pull request merged**
