### PR TITLE
Fix bookkeeping assertion error

### LINKED ISSUE #9584: "Bookkeepping failure" when changing Grid datasources
If server-side assertions are enabled, `Grid` explodes when changing data provider if scrolled down. 

Broken in the current `master` branch, but works in the `8.0` branch.

Example code:
```
public class ChangeContainer extends AbstractTestUI {
    private final Grid<Integer> grid = new Grid<>();
    private final NativeSelect<Integer> sizeSelector = new NativeSelect<>(
            "Row count");

    @Override
    protected void setup(VaadinRequest request) {
        sizeSelector.setItems(1000, 500, 250);
        sizeSelector.addValueChangeListener(event -> updateGridSize());
        sizeSelector.setValue(250);

        grid.addColumn(value -> value);

        addComponents(sizeSelector, grid);
    }

    private void updateGridSize() {
        int size = sizeSelector.getValue().intValue();
        grid.setItems(IntStream.range(0, size).mapToObj(Integer::valueOf));
    }
}
```

To reproduce:
1. Open test UI
2. Scroll sufficiently far down so that e.g. row 100 is visible.
3. Change the size to 500 in the dropdown
4. Kaboom

```
java.lang.AssertionError: Bookkeepping failure. No data object to match key
	at com.vaadin.data.provider.DataCommunicator.dropData(DataCommunicator.java:477)
	at com.vaadin.data.provider.DataCommunicator.access$000(DataCommunicator.java:60)
	at com.vaadin.data.provider.DataCommunicator$ActiveDataHandler.cleanUp(DataCommunicator.java:140)
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:434)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:342)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:311)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	at com.vaadin.launcher.ApplicationRunnerServlet.service(ApplicationRunnerServlet.java:160)
```

### PR DESCRIPTION
**Pull request by elmot**
Fix assertion error for stalled dropped keys

Fixes #9584

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9616)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9616#-KnrZgFOn6kNTE1euzES:-KnrZgFPsle8D8XZ4_HX:b-xcn9g3) ([raw file](https://github.com/vaadin/framework/blob/148ed3d4ac756e00087cf799d4dea06f375ac9d3/uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java#L21)):*
> ```Java
>         });
> 
>         Button buttonScroll = new Button("Scroll to #98", event -> {
> ```

(not used by test, instead scrolling differently - but can also leave here for manual testing)

---

*[uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/9616#-KnrZj_iAAC6NjStAQc7:-KnrZj_iAAC6NjStAQc8:b6pdcwu) ([raw file](https://github.com/vaadin/framework/blob/148ed3d4ac756e00087cf799d4dea06f375ac9d3/uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java#L39)):*
> ```Java
>         grid.setItems(IntStream.range(0, 500).mapToObj(Integer::valueOf));
>     }
> }
> ```

strange characters, missing EOL?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9616)*

**Comment by elmot** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9616#-KnrZgFOn6kNTE1euzES:-Knrc45nCz8rVHYvmi8V:bze7yxg) ([raw file](https://github.com/vaadin/framework/blob/148ed3d4ac756e00087cf799d4dea06f375ac9d3/uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java#L21)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not used by test, instead scrolling differently - but can also leave here for manual testing)
</blockquote></details>

The test is removed completely. 

---

*[uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/9616#-KnrZj_iAAC6NjStAQc7:-KnrcAS81JfUp0QsOvn2:bze7yxg) ([raw file](https://github.com/vaadin/framework/blob/148ed3d4ac756e00087cf799d4dea06f375ac9d3/uitest/src/main/java/com/vaadin/tests/data/GridChangeItems.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

strange characters, missing EOL?
</blockquote></details>

The test is removed completely. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9616)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9616)*

**Comment by focbenz** [comment]
Fixed two internal issues when we enabled Assertions -ea in our IDE:
`java.lang.AssertionError: Bookkeepping failure. No data object to match key`
Verified the problem is fixed with the 8.1.0.rc1 release. Thank you!

**Pull request merged**
