### PR TITLE
Fix missing HTML Tooltip for TreeItem

### PR DESCRIPTION
**Pull request by AkiValiaho**
Added a specific method with ContentMode parameter

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10677)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10677#-L6pwLxdYt8C8K_lNQK2:-L6pwLxeKmSK8LHALAS7:b8qsa04) (no related file):*
Change itself is reviewed and looks good. The formatting in the JavaDoc doesn't seem to be the same as the rest of the framework. Are you using IDEA or Eclipse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10677)*

**Comment by AkiValiaho** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10677#-L6pwLxdYt8C8K_lNQK2:-L6pxxTW6dUhZDosGGq3:b2sda7g) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Change itself is reviewed and looks good. The formatting in the JavaDoc doesn't seem to be the same as the rest of the framework. Are you using IDEA or Eclipse?
</blockquote></details>

Ohh, I'm using IDEA.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10677)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10677#-L6pwLxdYt8C8K_lNQK2:-L73dusEl_oXLe5HQH2t:bzdorxt) (no related file):*
<details><summary><i>Previously, AkiValiaho (Aki Väliaho) wrote…</i></summary><blockquote>

Ohh, I'm using IDEA.
</blockquote></details>

@elmot did you have some instructions on how to get the formatting to work with IDEA?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10677)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10677#-L6pwLxdYt8C8K_lNQK2:-L73xntKzNgxQ8GxN1Ob:b-agya2r) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@elmot did you have some instructions on how to get the formatting to work with IDEA?
</blockquote></details>

Not really

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 682 at r1](https://reviewable.io:443/reviews/vaadin/framework/10677#-L73xtmI0SvKNcozgGCb:-L73xtmI0SvKNcozgGCc:b-i7uiaj) ([raw file](https://github.com/vaadin/framework/blob/8f7034c7d07c10f02133b9280583f5b51fb5474a/server/src/main/java/com/vaadin/ui/Tree.java#L682)):*
> ```Java
>      *                             remove a previously set generator
>      * @param contentMode          how client should interpret textual values
>      */
> ```

Missing `@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10677)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10677#-L6pwLxdYt8C8K_lNQK2:-L7P--ayiylkpSfUyzc4:bcqk8jz) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Not really
</blockquote></details>

Finally got back on this. Formatted the file and added the missing since tag.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 682 at r1](https://reviewable.io:443/reviews/vaadin/framework/10677#-L73xtmI0SvKNcozgGCb:-L7P-4h6ZEmeLR5J1m2p:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f7034c7d07c10f02133b9280583f5b51fb5474a/server/src/main/java/com/vaadin/ui/Tree.java#L682)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Missing `@since`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10677)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10677#-:-L7UD_nbQhcC4iY73M9N:bnfp4nl)*

**Pull request merged**
