### PR TITLE
Fixes to displaying Grid in a detail row.

### LINKED ISSUE #7674: Grid in details row fails to render correctly with certain settings.
**Originally by @mstahv**

___
A client side exception is thrown and UI is not rendered correctly when a details row is opened with following code snippet:

```

        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        layout.setSpacing(true);

        Grid fg = new Grid();
        fg.setSizeFull();
        fg.addColumn("col1", String.class);
        fg.addColumn("col2", String.class);
        fg.addRow("Temp 1", "Temp 2");
        fg.addRow("Temp 3", "Temp 4");
        fg.setDetailsGenerator(new Grid.DetailsGenerator() {
            @Override
            public Component getDetails(RowReference rowReference) {
                Grid gd = new Grid();
                gd.setSizeFull();
                gd.addHeaderRowAt(0);
                gd.addColumn("Column 1", String.class);
                gd.addColumn("Column 2", String.class);
gd.getColumn("Column 2").setHidable(true);
                gd.addColumn("Column 3", String.class);
                gd.addColumn("Column 4", String.class);
                gd.addColumn("id", Integer.class);
                gd.addRow("Nicolaus Copernicus", "Nicolaus Copernicus",
                        "Nicolaus Copernicus", "Nicolaus Copernicus", 1543);
                gd.addRow("Nicolaus Copernicus", "Nicolaus Copernicus",
                        "Nicolaus Copernicus", "Nicolaus Copernicus", 1543);
                gd.addRow("Nicolaus Copernicus", "Nicolaus Copernicus",
                        "Nicolaus Copernicus", "Nicolaus Copernicus", 1543);
                gd.addRow("Nicolaus Copernicus", "Nicolaus Copernicus",
                        "Nicolaus Copernicus", "Nicolaus Copernicus", 1543);

                gd.getColumn("Column 2").setHidable(true);
                return gd;
            }
        });

        fg.addItemClickListener(new ItemClickListener() {
            @Override
            public void itemClick(ItemClickEvent event) {
                if (event.isDoubleClick()) {
                    Object itemId = event.getItemId();
                    fg.setDetailsVisible(itemId, !fg.isDetailsVisible(itemId));
                }
            }
        });

        layout.addComponent(fg);

        setContent(layout);

```

___
 Imported from https://dev.vaadin.com/ issue #19856

### PR DESCRIPTION
**Pull request by Ansku**
- Multiple headers shouldn't stack behind each other.
- Body rows shouldn't get stuck to default row height.
- Compatibility version's hidable row selector shouldn't try to
calculate row heights based on rows that haven't been added to DOM yet.

Fixes #7674

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11147)

### CODE REVIEW

**Comment by Ansku** [comment]
#11154 may or may not affect the need for isAutodetectingRowHeightLater() handling (might become irrelevant), but my vacation is just about to start so I don't have time to test these patches together.

**Comment by anasmi** [comment]
While Anna is on vacation this is the rebased version  https://github.com/vaadin/framework/pull/11155

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @Ansku and @tsuoanttila)

___
*[client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java, line 243 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhov6R0-YbMPRDA_D2:-LLhov6R0-YbMPRDA_D3:b-dlwpep) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java#L243)):*
> ```Java
>      * @return {@code true} if row height calculations have been scheduled
>      */
>     boolean isAutodetectingRowHeightLater();
> ```

since tag for new method. Also as per the guideline of Interfaces in V8 this should have `public` even though IDEA says it's not needed.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2120 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhpMDy151wg_Wtz1bO:-LLhpMDy151wg_Wtz1bP:b-76l6t9) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2120)):*
> ```Java
> 
>         public void autodetectRowHeightLater() {
>             autodetectingRowHeightLater = true;
> ```

Do we need a new variable for this? The calculation is still based on the state of `defaultRowHeightShouldBeAutodetected`. This code won't do anything when that is set to `false`.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/widget/escalator/RowContainer.java, line 237 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhphyw90IUuspsPKNN:-LLhphyw90IUuspsPKNO:bpb4pe4) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/compatibility-client/src/main/java/com/vaadin/v7/client/widget/escalator/RowContainer.java#L237)):*
> ```Java
>      * @return the actual DOM count of rows
>      */
>     public int getDomRowCount();
> ```

Is this change also reflected in the upcoming changes to V7? Since technically this in new public API, the `since` version number is kind of wrong.
___
*[uitest/src/main/java/com/vaadin/tests/widgetset/client/grid/EscalatorProxy.java, line 176 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhq91g1QhtAE_6GSGS:-LLhq91g1QhtAE_6GSGT:bp5agkv) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/uitest/src/main/java/com/vaadin/tests/widgetset/client/grid/EscalatorProxy.java#L176)):*
> ```Java
>         @Override
>         public boolean isAutodetectingRowHeightLater() {
>             return false;
> ```

why is this method not passing forward to the `rowContainer`?  I know it should not be called, but still.

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @tsuoanttila, @Ansku, and @elmot)

___
*[client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java, line 243 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhov6R0-YbMPRDA_D2:-LNyujgN2s-1w0whiH7H:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/client/src/main/java/com/vaadin/client/widget/escalator/RowContainer.java#L243)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

since tag for new method. Also as per the guideline of Interfaces in V8 this should have `public` even though IDEA says it's not needed.
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2120 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhpMDy151wg_Wtz1bO:-LNyulLhA09QH0LEpPQC:b6ztmxw) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2120)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Do we need a new variable for this? The calculation is still based on the state of `defaultRowHeightShouldBeAutodetected`. This code won't do anything when that is set to `false`.
</blockquote></details>

Yes we do, because the variable isn't for the use of this method, it's for knowing elsewhere (via that getter) that there is a check scheduled and there is no need to schedule another check if this one hasn't been processed yet. The unnecessary just-in-case check is what messes up the calculations.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/widget/escalator/RowContainer.java, line 237 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhphyw90IUuspsPKNN:-LNyvnte45RxUCj7wbsm:bs8xxwf) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/compatibility-client/src/main/java/com/vaadin/v7/client/widget/escalator/RowContainer.java#L237)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is this change also reflected in the upcoming changes to V7? Since technically this in new public API, the `since` version number is kind of wrong.
</blockquote></details>

@since added
___
*[uitest/src/main/java/com/vaadin/tests/widgetset/client/grid/EscalatorProxy.java, line 176 at r1](https://reviewable.io/reviews/vaadin/framework/11147#-LLhq91g1QhtAE_6GSGS:-LNyvtzn60zv8EaWO4M5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0ee4d095989ed7c92f3057b48def6177f82e8cac/uitest/src/main/java/com/vaadin/tests/widgetset/client/grid/EscalatorProxy.java#L176)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why is this method not passing forward to the `rowContainer`?  I know it should not be called, but still.
</blockquote></details>

Done.

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 2 of 12 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147#-:-LO23R6n6Y897DuJTp5v:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @tsuoanttila and @elmot)

**Review by Ansku — COMMENTED** [review]
Could you resolve the discussions, @elmot ?

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147#-:-LO26o8gCasMmp45111j:b-etkntr)* status: all files reviewed, 4 unresolved discussions (waiting on @tsuoanttila and @elmot)

**Review by ZheSun88 — APPROVED** [review]
> Dismissed @tsuoanttila from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147)* status: all files reviewed, 2 unresolved discussions (waiting on @elmot)

**Review by ZheSun88 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11147#-:-LOIHy_y4M16EHqdJMYI:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elmot)

**Pull request merged**
