### PR TITLE
Allow setting Upload button caption as HTML, move data to SharedState.

### LINKED ISSUE #11810: Add setButtonCaptionAsHtml method to Upload component
- Vaadin Framework version (e.g. 8.9.2)

Upload button component allows me to customize caption on the upload button only with strings. It is not possible to set arbitrary html into it. 

I want to be able to do this:
````java
Upload upload = new Upload(null, this::receiveUpload);
upload.setButtonCaptionAsHtml(true);
upload.setButtonCaption(VaadinIcons.UPLOAD.getHtml());
````

And see this on screen:
image

Normal buttons have such functionality.

### PR DESCRIPTION
**Pull request by Ansku**
Fixes #11810

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11940)

### CODE REVIEW

**Comment by Ansku** [comment]
Solution borrowed from #11811 with some minor tweaks, and communication about the relevant data moved to use the shared state instead of the old UIDL version.

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11940)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/ui/upload/UploadConnector.java, line 90 at r1](https://reviewable.io/reviews/vaadin/framework/11940#-M4DDSkjBXWPsN7Q0as8:-M4DDSkjBXWPsN7Q0as9:b-wm8q0s) ([raw file](https://github.com/vaadin/framework/blob/9bb4c57ad685adf8980e32e529e6a8a07b28534e/client/src/main/java/com/vaadin/client/ui/upload/UploadConnector.java#L90)):*
> ```Java
>                 upload.submitButton.setText(getState().buttonCaption);
>             }
>             if (getState().buttonStyleName != null) {
> ```

Won't this make it impossible to reset the button style name by setting it to null?

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11940)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[client/src/main/java/com/vaadin/client/ui/upload/UploadConnector.java, line 90 at r1](https://reviewable.io/reviews/vaadin/framework/11940#-M4DDSkjBXWPsN7Q0as8:-M4DR7aQ17VHEOEntuxl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9bb4c57ad685adf8980e32e529e6a8a07b28534e/client/src/main/java/com/vaadin/client/ui/upload/UploadConnector.java#L90)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

Won't this make it impossible to reset the button style name by setting it to null?
</blockquote></details>

Done.

**Review by OlliTietavainenVaadin — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11940)* status: all files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11940#-:-M4Dngo96bR3ZqlueTjY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
