### PR TITLE
Document how to handle cancelled file downloads.

### LINKED ISSUE #9014: Exception on aborting file download using FileDownloader
This Defect is based on https://github.com/vaadin/framework/issues/6217

When downloading a file using FileDownloader there happens an exception when aborting the download.
Please use the attached project in the zip file. Go to the UI class and replace the file name by a big file of your machine. optionally use bandwith limitation.

- Place a breakpoint in FileDownloader on line 162 (stream.writeResponse(request, response);)

- Start the Project and 

- click the button which triggers the download. 

- Cancel the download before it finishes. 

Be aware that Firefox and Chrome have download managers which already start the download before you chose to save or open it.
On cancelling there will be thrown an exception. In Tomcat it is a ClientAbortException which is from a Catalina library and extends an IOException. It might be that in other application servers also other exceptions are thrown.

My workaround for this is overwriting the method handleConnectorRequest as follows:

```

        @Override
        public boolean handleConnectorRequest(final VaadinRequest request, final VaadinResponse response, final String path) throws IOException {
            try {
                return super.handleConnectorRequest(request, response, path);
            }
            catch (final ClientAbortException ignored){ // Browsers are throwing exceptions on aborting downloads which don't really harm
                return true;
            }
        }
```

[vaadin-download.zip](https://github.com/vaadin/framework/files/893655/vaadin-download.zip)

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9014

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11079)

### CODE REVIEW

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11079)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @elmot)

___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 117 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHre_SZEgn4kpGOh_v5:-LHre_SZEgn4kpGOh_v6:b5em4n5) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L117)):*
> ```
> . In this case the exception
> ```
that
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 118 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHrdmj2-R5a_boEf9VE:-LHrdmj2-R5a_boEf9VF:b-u7nbys) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L118)):*
> ```
> but it the
> ```
It seems that something's wrong here.
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 119 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHrdyR28u5USm79XPdn:-LHrdkIQ4to1QJBeGYKN:bxhfuc5) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L119)):*
> ```
> but it the. To prevent
> ```
* them
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 137 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHreAznDzLGKpTRgzDD:-LHreAznDzLGKpTRgzDE:b-58c9un) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L137)):*
> ```
> of
> ```
* on

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11079)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @mehdi-vaadin)

___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 117 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHre_SZEgn4kpGOh_v5:-LHt3si2BuK-8Y-4C8ob:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L117)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> . In this case the exception
> ```
that
</blockquote></details>

Done.
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 118 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHrdmj2-R5a_boEf9VE:-LHt3tAsDG_AOOfqxrlc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L118)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> but it the
> ```
It seems that something's wrong here.
</blockquote></details>

Done.
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 119 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHrdyR28u5USm79XPdn:-LHt3vxv52W3_xYZd5Ki:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L119)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> but it the. To prevent
> ```
* them
</blockquote></details>

Done.
___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 137 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHreAznDzLGKpTRgzDD:-LHt3pS31O2aCThk5k4W:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L137)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> of
> ```
* on
</blockquote></details>

Done.

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11079)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

___
*[documentation/articles/LettingTheUserDownloadAFile.asciidoc, line 117 at r1](https://reviewable.io/reviews/vaadin/framework/11079#-LHre_SZEgn4kpGOh_v5:-LJIxrZQ6yZlKCVrvWlO:b7tivu9) ([raw file](https://github.com/vaadin/framework/blob/65d2baf0cf4293f2abe99b53059029dac42909e2/documentation/articles/LettingTheUserDownloadAFile.asciidoc#L117)):*
> ```
> It
> ```
'It' should be changed to 'In'

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11079#-:-LJIyooB9rBsUJDgCS1o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
