### PR TITLE
Remove outdated filtering concepts

### PR DESCRIPTION
**Pull request by Legioth**
withFilter is removed since filters are supposed to be set as state in
the data provider instead of by wrapping.

AppendabileFilterDataProvider is removed since the data provider is
supposed to do any appending when updating its own state instead of
through wrapping.

This is one of many steps towards #8245

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8289)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Needs manual rebase.

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8289)*

**Comment by Legioth** [comment]
Rebased

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8289#-:-KbA6D5tEExxbdXYXyNb:b9x2p3v)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8289)*

**Pull request merged**
