### PR TITLE
Fix client-side memory leak caused by Grid events

### LINKED ISSUE #7633: Grid object count increase when changing tabsheet
**Originally by _vincentcjl_**

___
When using object allocator in Chrome dev tools, I noticed that the Grid object count keeps increasing when changing tabs. The previous grid objects are not cleared. 

___
 Imported from https://dev.vaadin.com/ issue #19786

### PR DESCRIPTION
**Pull request by ahie**
Refactors AbstractGridKeyEvent, AbstractGridMouseEvent and their
descendants to follow the pattern used in other GWT DomEvents.

Fixes #7633

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9062)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2444 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhSQZnb3gbxujL6BLHT:-KhSQZncXnf1L0Fd_Q3M:b-qb2vw7) ([raw file](https://github.com/vaadin/framework/blob/cce07036b62034a68297e1f2c0724d8d2e783b5d/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2444)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         @Override
>         public Type<HANDLER> getAssociatedType() {
>             return associatedType;
>         }
</details>

Removing these from the Abstract base classes is a breaking change, but keeping the `associatedType` as constructed before causes two handlers to be registered.

Another solution to this issue would be to have all `getGrid()` methods in the events delegate to the `eventCell`s `getGrid()` and set the event cell's grid to null on detach. This way the `Grid` instance would be garbage collected, but the event objects created would still leak, since calling the `Type` constructor registers them internally in GWT's `DomEvent`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by hesara** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/grid/EventCellReference.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhXMOgtf0XBVp66kT65:-KhXMOguoCx4td0HpA5o:b737pol) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widget/grid/EventCellReference.java#L90)):*
> ```Java
>      *
>      * @since 7.5
>      * @return <code>true</true> if referenced cell is in the header,
> ```

(whitespace changes only - not a blocker)

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2320 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhXMp2e50hb8IK7p8qq:-KhXMp2e50hb8IK7p8qr:br18ds5) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2320)):*
> ```Java
>             extends KeyEvent<HANDLER> {
> 
>         public AbstractGridKeyEvent(Grid<?> grid, CellReference<?> targetCell) {
> ```

should this have a comment about why the parameters are not used, or should we remove the parameters or provide a no-params version and deprecate this version?

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2353 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_svx2llaBOB9k4QiC:-Kh_svx2llaBOB9k4QiD:bgff9in) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2353)):*
> ```Java
>         protected void dispatch(HANDLER handler) {
>             EventTarget target = getNativeEvent().getEventTarget();
>             if (Element.is(target) && getGrid() != null
> ```

could keep getGrid() result in local variable to avoid redundant calls

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2374 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_t-hxbZ0Dl0jXUeZY:-Kh_t-hxbZ0Dl0jXUeZZ:b-stkxiz) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2374)):*
> ```Java
>             extends MouseEvent<HANDLER> {
> 
>         public AbstractGridMouseEvent(Grid<?> grid,
> ```

see comment above about unused constructor parameters, maybe alternate constructor and deprecate this one

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2402 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_sdMypiPiRV2sgfzU:-Kh_sdMypiPiRV2sgfzV:bgff9in) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2402)):*
> ```Java
>          */
>         public CellReference<?> getTargetCell() {
>             if (getGrid() == null) {
> ```

could keep getGrid() result in local variable to avoid redundant calls

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2416 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_sjTKdw8D-l42nfgZ:-Kh_sjTKdw8D-l42nfg_:bgff9in) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2416)):*
> ```Java
>             }
> 
>             if (getGrid() == null) {
> ```

could keep getGrid() result in local variable to avoid redundant calls

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridClientMemoryLeak.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_tUCJqx9WoEqmGbCh:-Kh_tUCJqx9WoEqmGbCi:bbqt29k) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/uitest/src/main/java/com/vaadin/tests/components/grid/GridClientMemoryLeak.java#L10)):*
> ```Java
> import com.vaadin.ui.VerticalLayout;
> 
> public class GridClientMemoryLeak extends AbstractTestUI {
> ```

could have some comments about the issue and how to test for it as there is no automated test - maybe even a label in the UI about that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2444 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhSQZnb3gbxujL6BLHT:-Kh_tiNrqqRkTufYrygy:b-ged1dq) ([raw file](https://github.com/vaadin/framework/blob/cce07036b62034a68297e1f2c0724d8d2e783b5d/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2444)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

>         @Override
>         public Type<HANDLER> getAssociatedType() {
>             return associatedType;
>         }

Removing these from the Abstract base classes is a breaking change, but keeping the `associatedType` as constructed before causes two handlers to be registered.

Another solution to this issue would be to have all `getGrid()` methods in the events delegate to the `eventCell`s `getGrid()` and set the event cell's grid to null on detach. This way the `Grid` instance would be garbage collected, but the event objects created would still leak, since calling the `Type` constructor registers them internally in GWT's `DomEvent`.
</blockquote></details>

could also mention this as a one-lines in relnotes (though quite unlikely that anyone will ever run into this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by ahie** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2320 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhXMp2e50hb8IK7p8qq:-Kha1evDzTLQTFo-53H4:b-45jcej) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2320)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this have a comment about why the parameters are not used, or should we remove the parameters or provide a no-params version and deprecate this version?
</blockquote></details>

Deprecated and added comment. Replaced with no-args constructor.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2353 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_svx2llaBOB9k4QiC:-Kha1bYuWG7kOvn7BMOs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2353)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could keep getGrid() result in local variable to avoid redundant calls
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2374 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_t-hxbZ0Dl0jXUeZY:-Kha1e1J-HQbhURgRGj1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2374)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment above about unused constructor parameters, maybe alternate constructor and deprecate this one
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2402 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_sdMypiPiRV2sgfzU:-Kha2NntSnui0soYXjpW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2402)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could keep getGrid() result in local variable to avoid redundant calls
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2416 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_sjTKdw8D-l42nfgZ:-Kha2OweYPRaWF176BEn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2416)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could keep getGrid() result in local variable to avoid redundant calls
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridClientMemoryLeak.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-Kh_tUCJqx9WoEqmGbCh:-Kha2njpjnN-1iQnaELl:b44qmri) ([raw file](https://github.com/vaadin/framework/blob/08dcc9648dbbe777b03ee14f83a918eb2c5ee6fe/uitest/src/main/java/com/vaadin/tests/components/grid/GridClientMemoryLeak.java#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could have some comments about the issue and how to test for it as there is no automated test - maybe even a label in the UI about that
</blockquote></details>

Added instructional label to the UI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2320 at r2](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhaBvhpjQiP3ZxBUNCm:-KhaBvhpjQiP3ZxBUNCn:b-sxbf2c) ([raw file](https://github.com/vaadin/framework/blob/1af3ee8e0f48feb3a940c740c6ed166fdd23cc73/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2320)):*
> ```Java
>             extends KeyEvent<HANDLER> {
> 
>         public AbstractGridKeyEvent() {
> ```

Should this have @since? Should the subclasses call this constructor?

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2383 at r2](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhaC0G8v66aA0Sw93os:-KhaC0G8v66aA0Sw93ot:b-sxbf2c) ([raw file](https://github.com/vaadin/framework/blob/1af3ee8e0f48feb3a940c740c6ed166fdd23cc73/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2383)):*
> ```Java
>             extends MouseEvent<HANDLER> {
> 
>         public AbstractGridMouseEvent() {
> ```

Should this have @since? Should the subclasses call this constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by ahie** [comment]
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2444 at r1](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhSQZnb3gbxujL6BLHT:-Ki3s4NyJi_H8kGjwyK9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cce07036b62034a68297e1f2c0724d8d2e783b5d/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2444)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could also mention this as a one-lines in relnotes (though quite unlikely that anyone will ever run into this)
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2320 at r2](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhaBvhpjQiP3ZxBUNCm:-Ki3s5zYNBrUI3RkNYV4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1af3ee8e0f48feb3a940c740c6ed166fdd23cc73/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2320)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should this have @since? Should the subclasses call this constructor?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2383 at r2](https://reviewable.io:443/reviews/vaadin/framework/9062#-KhaC0G8v66aA0Sw93os:-Ki3s5KIKoF1h5HhKRmL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1af3ee8e0f48feb3a940c740c6ed166fdd23cc73/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2383)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should this have @since? Should the subclasses call this constructor?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9062#-:-Ki3y8A91ZztnCcQDbWS:bnfp4nl)*

**Comment by Snap252** [comment]
the new implementation of 

	com.vaadin.client.widgets.Grid.AbstractGridMouseEvent.getGrid()

will return null in subclasses of 

	com.vaadin.client.widgets.Grid<JsonObject>

so it is a major bug for us because clicks don't work any more

example:
class1:

	@Connect(EditorGrid.class)
	public class EditorGridClientConnector extends GridConnector {
	
		@Override
		public EditorClientGrid getWidget() {
			return (EditorClientGrid) super.getWidget();
		}
	}


class 2:

	import elemental.json.JsonObject;
	
	public class EditorClientGrid extends com.vaadin.client.widgets.Grid<JsonObject> {
		public EditorClientGrid() {
		}
	}

**Comment by Legioth** [comment]
@Snap252 I extracted your regression report into a separate ticket (https://github.com/vaadin/framework/issues/9603) since the work of this PR has already been included in a release.

**Pull request merged**
