### PR TITLE
Refactor editor API to use Binding instead of a component generator

### LINKED ISSUE #8366: Grid Editor row API is confusing
With 8.0.0.beta1, you need to take two completely separate steps for configuring the Grid editor row.
1. Configure `Binder` so that it knows how to move data to and from the edited row item. `grid.getEditor().getBinder().bind(nameField, Person::getName, Person.setName)`. This also requires duplicating the `Person::getName` getter that you've already configured for the column.
1. Configure the column to use the right editor component. `grid.getColumn("name").setEditorComponent(nameField)`.

It's far from obvious that how you should do the first step and there's nothing in the API or in the javadocs that guide you towards this. Omitting this step will give you an editor row with an empty text field that doesn't do anything.

Short of completely redesigning the entire concept, I'd propose these adjustments:
1. Replace `setEditorComponent(Component)` with `setEditorBinding(Binding<T, V>)`.
1. Add `setEditorComponent(HasValue<T> component,  Setter<T, V> setter)` as a shorthand for `setEditorBinding(getEditor().getBinder().bind(component, valueProvider, setter))`. Could also consider having this one named `setEditorBinding` to be in sync with the low level method, although "Component" in the name might be better from a discoverability point of view.
1. Consider making Grid throw or log a warning when the editor is opened if the binder contains binding that are not configured to be used by any column.
1. Make sure things are described in the javadocs and in /docs.

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #8366

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8368)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjV8MwhLAlzOZdIuGm:-KbjV8MwhLAlzOZdIuGn:b-fjcm5l) (no related file):*
Is there some documentation which needs to be updated ?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1564 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjSyYKq7JHqHh8Y1tP:-KbjSyYKq7JHqHh8Y1tQ:b-1b2szi) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/server/src/main/java/com/vaadin/ui/Grid.java#L1564)):*
>  You can create a binding in the same way as a regular {@link Binder}
>          * binding through <code>grid.getEditor().getBinder()</code>.

How can I create a binder using getters ?

My be create and set a binder using `setBinder()` ?

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjTl0jEpVXnCJlt7_g:-KbjTl0jEpVXnCJlt7_h:b-85t73s) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L221)):*
> ```Java
>                 .forEach(c -> {
>                     Binding<T, ?> binding = c.getEditorBinding();
>                     // Grid enforces that the field is a component
> ```

Then assert please.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridCheckBoxDisplay.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjUrP_cuF84659UBVV:-KbjUrP_cuF84659UBVW:b-d5ut6m) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/uitest/src/main/java/com/vaadin/tests/components/grid/GridCheckBoxDisplay.java#L46)):*
> ```Java
>         CheckBox doneField = new CheckBox();
> 
>         Binder<Todo> binder = grid.getEditor().getBinder();
> ```

How does it actually work ?
I don't see changes that updates `EditorImpl` implementation to create a binder automatically.
If it's not created and is not set by anyone there then where it is created ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8368)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 782 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjVlL93UQ5JUoMpXet:-KbjVlL93UQ5JUoMpXeu:b-cnn11v) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/server/src/main/java/com/vaadin/ui/Grid.java#L782)):*
> ```Java
> 
>         private final SerializableFunction<T, ? extends V> valueProvider;
>         private final Grid<T> grid;
> ```

This is not necessary since `getParent()` returns the same value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8368)*

**Comment by Legioth** [comment]
Review status: 7 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjV8MwhLAlzOZdIuGm:-KbkR6spunrYmZM_tMmD:bb6un1j) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is there some documentation which needs to be updated ?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1564 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjSyYKq7JHqHh8Y1tP:-KbkMOS6w7mKdHP0K72U:b-eowr3y) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/server/src/main/java/com/vaadin/ui/Grid.java#L1564)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  You can create a binding in the same way as a regular {@link Binder}
>          * binding through <code>grid.getEditor().getBinder()</code>.

How can I create a binder using getters ?

My be create and set a binder using `setBinder()` ?
</blockquote></details>

Clarified.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjTl0jEpVXnCJlt7_g:-KbkMg1-syv0K1n4xEY0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L221)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Then assert please.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridCheckBoxDisplay.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8368#-KbjUrP_cuF84659UBVV:-KbkMw0Y0v0FlojMrkE6:b-42j0b5) ([raw file](https://github.com/vaadin/framework/blob/6bd543ce38a42c42feb3e891128f29c84e2cbcd7/uitest/src/main/java/com/vaadin/tests/components/grid/GridCheckBoxDisplay.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

How does it actually work ?
I don't see changes that updates `EditorImpl` implementation to create a binder automatically.
If it's not created and is not set by anyone there then where it is created ?
</blockquote></details>

The `EditorImpl()` constructor did `setBinder(new Binder<>())` even before this patch. For some reason, some of the tests weren't written to take that into account.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8368)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8368)*

**Pull request merged**
