### PR TITLE
Provide a convenience method to get items set via setItems().

### LINKED ISSUE #8357: Make it feasible to later on find the items passed to setItems
The javadoc of all overloads of `HasItems.setItems` should be enhanced to describe how to get hold of those items later on, e.g. `((ListDataProvider<Person>) myListing.getDataProvider()).getItems()`. This also implies that `ListDataProvider.getItems()` should be introduced.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8357

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8475)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcNL6fcWZbaapfN1yzP:-KcNL6fcWZbaapfN1yzQ:bg3olu7) ([raw file](https://github.com/vaadin/framework/blob/114238839e5bb94298d47b93f522bd230b2f6928/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L76)):*
> ```Java
> 
>     /**
>      * Returns the underlying backend data.
> ```

backend is the wrong word. We do not have backend in this data provider

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcNL6fcWZbaapfN1yzP:-KcNMp9_SoXv_6PW8-I5:b-ht5lhf) ([raw file](https://github.com/vaadin/framework/blob/114238839e5bb94298d47b93f522bd230b2f6928/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L76)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

backend is the wrong word. We do not have backend in this data provider
</blockquote></details>

Reference to the existing field name. But will update it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcN_YrGLiuJhGgUegYl:b-183jp5) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
> ```Java
>      * Sets the data items of this listing.
>      * 
>      * @see #setItems(Collection)
> ```

This will in at least some cases link to `HasItems.setItems(Collection)` which doesn't have the relevant additional information.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcNlBGDmIeIOQvxs63_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This will in at least some cases link to `HasItems.setItems(Collection)` which doesn't have the relevant additional information.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcNlPGohgIOAnQeEYvM:bw1at1c) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So how are users now supposed to understand what the method means?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcNlri-w6Ui6tHk842o:b-qxgaa5) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
>So how are users now supposed

NOW ?

How they did suppose to understand it before ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcNmt5jGxxdgF4FlN4R:b-99c68o) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>So how are users now supposed

NOW ?

How they did suppose to understand it before ?
</blockquote></details>

"Now" was referring to the changes between r1 and r3. When the `@see` reference was removed, there are no chances at all to find the information.

Would it make sense to instead do all the explaining on the original method definitions here in `HasItems`? There would then not be any `getDataProvider()` to refer to.

That method could actually now be extracted from `HasDataProvider` and `HasFilterableDataProvider` since one of the last filtering changes I did actually made both variants have the same return type for the getter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcNqDysq-cNc-0NnXv6:b-jcweqg) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

"Now" was referring to the changes between r1 and r3. When the `@see` reference was removed, there are no chances at all to find the information.

Would it make sense to instead do all the explaining on the original method definitions here in `HasItems`? There would then not be any `getDataProvider()` to refer to.

That method could actually now be extracted from `HasDataProvider` and `HasFilterableDataProvider` since one of the last filtering changes I did actually made both variants have the same return type for the getter.
</blockquote></details>

Now I'm lost.

Moving javadoc from `HasDataProvider` has no sense since it's heavily relies on `getDataProvider()` method.

Do you suggest to move method `getDataProvider()` from `HasDataProvider` to `HasValue` ?
Then why do we need  `HasDataProvider` at all ?
 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcSe1009lZK58Iis_XI:b9vmtp9) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Now I'm lost.

Moving javadoc from `HasDataProvider` has no sense since it's heavily relies on `getDataProvider()` method.

Do you suggest to move method `getDataProvider()` from `HasDataProvider` to `HasValue` ?
Then why do we need  `HasDataProvider` at all ?
 
</blockquote></details>

the `getDataProvider()` method is extracted to the superinterface now as discussed.

Now I guess it's OK to have `@see`  here....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcSedxzFcjDQD9IOxBW:b-iqfrv) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

the `getDataProvider()` method is extracted to the superinterface now as discussed.

Now I guess it's OK to have `@see`  here....
</blockquote></details>

`@see` should work. Would be even better to have the same highly relevant description copied into each separate `setItems` method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcN_YrFMBwzChwfj7KX:-KcSfSYU7oVaskUOjM6o:b-52ymw0) ([raw file](https://github.com/vaadin/framework/blob/52744cf0b53130d7b5a860fb9a04f8a505c7de8d/server/src/main/java/com/vaadin/data/HasItems.java#L53)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`@see` should work. Would be even better to have the same highly relevant description copied into each separate `setItems` method.
</blockquote></details>

Done.
I have awesome copy/paste skills.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 223 at r4](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcSgNBgQlUpev5g5Aj1:-KcSgNBgQlUpev5g5Aj2:bmif9ma) ([raw file](https://github.com/vaadin/framework/blob/aeb99344d2fc2778bf40dc4dc091840dfd12b231/server/src/main/java/com/vaadin/ui/ComboBox.java#L223)):*
> ```Java
> 
>     /**
>      * Sets the data items of this component provided as a collection.
> ```

This change is lo longer needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 223 at r4](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcSgNBgQlUpev5g5Aj1:-KcSh0mtrKpHVIubUSFX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aeb99344d2fc2778bf40dc4dc091840dfd12b231/server/src/main/java/com/vaadin/ui/ComboBox.java#L223)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This change is lo longer needed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 223 at r4](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcSgNBgQlUpev5g5Aj1:-KcSlR4fdj94meKLuwtq:bpx4cqp) ([raw file](https://github.com/vaadin/framework/blob/aeb99344d2fc2778bf40dc4dc091840dfd12b231/server/src/main/java/com/vaadin/ui/ComboBox.java#L223)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The original clarification about  how filtering would work is however still needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 223 at r4](https://reviewable.io:443/reviews/vaadin/framework/8475#-KcSgNBgQlUpev5g5Aj1:-KcSlnQeBFajRAiI4S6n:baltlt6) ([raw file](https://github.com/vaadin/framework/blob/aeb99344d2fc2778bf40dc4dc091840dfd12b231/server/src/main/java/com/vaadin/ui/ComboBox.java#L223)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

The original clarification about  how filtering would work is however still needed.
</blockquote></details>

Missed that, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Comment by Legioth** [comment]
There are still some compilation errors caused by the strange class hierarchy abuse used in some of our unit tests

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475#-:-KcSmmqzySn5njVDj3sB:b-1came5)*

**Comment by Legioth** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8475)*

**Pull request merged**
