### PR TITLE
Validator severity

### PR DESCRIPTION
**Pull request by sknitelius**
Allow the specification of Validator Severity level.

Example:

binder.forField(...).withValidator(o -> ..., "My Info message", Severity.INFO);

Info and Warn levels are not considered to cause an invalid state,  so that binder.isValid() will return true even when there are Warnings or Info messages. 

Validation messages are mapped to the respective ErrorMessage.ErrorLevel.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9872)

### CODE REVIEW

**Comment by sknitelius** [comment]
Not sure whats causing the test error - when including Severity it works fine:

        Validator<Integer> ageValidator = Validator.from(age -> age >= 18,
                ctx -> {
                    Locale locale = ctx.getLocale().orElse(Locale.ENGLISH);

                    if (locale.getLanguage().equals("fi")) {
                        return finnishError;
                    } else if (locale.getLanguage().equals("en")) {
                        return englishError;
                    }
                    return notTranslatableError;
                }, Severity.ERROR);

This is obviously unacceptable to keep everything backwards compatible, hope that someone can help solve this.

**Comment by hesara** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG1ZCnPkIHW-rc8hrc:-KtG1ZCnPkIHW-rc8hrd:bgpsdur) (no related file):*
Added some comments based on a quick glimpse.
This should probably also be coordinated somehow to work well with https://github.com/vaadin/framework/pull/9817 (whose 7.7 version is at https://github.com/vaadin/framework/pull/9816 - possibly with more up-to-date changes).

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 268 at r2](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG186RqbIET5kjUQ9d:-KtG186RqbIET5kjUQ9e:b-5lwp2v) ([raw file](https://github.com/vaadin/framework/blob/6abee91d6f40eb28e18e05f741e176379e70a1ca/server/src/main/java/com/vaadin/data/Binder.java#L268)):*
> ```Java
>             return withValidator(Validator.from(predicate, message, Severity.ERROR));
>         }
>         
> ```

(extra whitespace on empty line here and in several other locations)

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2059 at r2](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG0u0uV1ZSA68zsa8w:-KtG0u0uV1ZSA68zsa8x:b62rbh8) ([raw file](https://github.com/vaadin/framework/blob/6abee91d6f40eb28e18e05f741e176379e70a1ca/server/src/main/java/com/vaadin/data/Binder.java#L2059)):*
> ```Java
>         HasValue<?> source = status.getField();
>         clearError(source);
>         //TODO clear INFO
> ```

address TODOs

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2061 at r2](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG0wQIvp3XAnX2HrEA:-KtG0wQJ7ZsrcKBXnkla:bhmxfhn) ([raw file](https://github.com/vaadin/framework/blob/6abee91d6f40eb28e18e05f741e176379e70a1ca/server/src/main/java/com/vaadin/data/Binder.java#L2061)):*
> ```Java
>         //TODO clear INFO
>         //TODO clear WARNINGS
>         if (status.hasMessage()) {
> ```

misusing hasMessage() for this might also cause some of the test failures

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 192 at r2](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG0hHcIu65J8I2ZJMK:-KtG0hHcIu65J8I2ZJML:b-5xo4cw) ([raw file](https://github.com/vaadin/framework/blob/6abee91d6f40eb28e18e05f741e176379e70a1ca/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L192)):*
> ```Java
>     }
>     
>     public boolean hasMessage() {
> ```

this sounds a bit strange - why is this needed here?

---

*[server/src/main/java/com/vaadin/data/SimpleResult.java, line 120 at r2](https://reviewable.io:443/reviews/vaadin/framework/9872#-KtG0Y3-6ROZQICLe9PH:-KtG0Y3-6ROZQICLe9PI:bpu2hql) ([raw file](https://github.com/vaadin/framework/blob/6abee91d6f40eb28e18e05f741e176379e70a1ca/server/src/main/java/com/vaadin/data/SimpleResult.java#L120)):*
> ```Java
>     @Override
>     public boolean isError() {
>         return message != null;
> ```

not symmetrical with the rest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9872)*

**Comment by hesara** [comment]
@wbadam is looking into #9817 to simplify and rework it, so it might make sense to wait with #9872 until that one goes forward.

**Comment by hesara** [comment]
There is a newer approach in #10099 that uses the error level support introduced in #9817.

**Comment by hesara** [comment]
Superceded by #10099.

**Pull request closed without merging**
