### PR TITLE
Fix NPE when detaching DragSource & DropTarget on client side

### LINKED ISSUE #9101: Client-side error when closing window with GridDragSource
Vaadin version: 8.1.0.alpha5

I have a `Window` with two `Grid` extended by `GridDragSource`.

When closing the `Window` I get the following javascript-exception:
```javascript
AppWidgetset-0.js:6163 Tue Apr 18 17:03:54 GMT+200 2017 com.vaadin.client.ApplicationConfiguration
SEVERE: (TypeError) : Cannot read property 'yb' of undefined
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'yb' of undefined
	at Unknown.Vgb(AppWidgetset-0.js)
	at Unknown.hSb(AppWidgetset-0.js)
	at Unknown.HSb(AppWidgetset-0.js)
	at Unknown.Kvb(AppWidgetset-0.js)
	at Unknown.lIb(AppWidgetset-0.js)
	at Unknown.eIb(AppWidgetset-0.js)
	at Unknown.LHb(AppWidgetset-0.js)
	at Unknown.MHb(AppWidgetset-0.js)
	at Unknown.rFb(AppWidgetset-0.js)
	at Unknown.eval(AppWidgetset-0.js)
	at Unknown.Rh(AppWidgetset-0.js)
	at Unknown.Uh(AppWidgetset-0.js)
	at Unknown.eval(AppWidgetset-0.js)
	at Unknown._f(http://localhost:8080/Project/VAADIN/vaadinPush.debug.js?v=8.1.0.alpha5)
	at Unknown._invokeFunction(http://localhost:8080/Project/VAADIN/vaadinPush.debug.js?v=8.1.0.alpha5)
	at Unknown._invokeCallback(http://localhost:8080/Project/VAADIN/vaadinPush.debug.js?v=8.1.0.alpha5)
	at Unknown._websocket.onmessage(http://localhost:8080/Project/VAADIN/vaadinPush.debug.js?v=8.1.0.alpha5)
```
After that the loading indicator flashes and the app needs to be reloaded.

Everything works fine without Drag'n'Drop functionality. 
When I extend the `Grid` with the `GridDragSource` the error occurs when closing the window.:
```java
GridDragSource<Task> dragSource = new GridDragSource<>(grid); 
```

### PR DESCRIPTION
**Pull request by pleku**
Fixes case where a TabSheet has a drag source component, and tab is changed, causing DragSourceExtensionConnector.getParent() to return null for some reason.

Closes #9101 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9341)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9341)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9341#-KkKL8eOWICjlhrnycZ4:-KkKL8eOWICjlhrnycZ5:b1h4mq8) (no related file):*
Blocking since adding a test UI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9341)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/framework/9341#-KkLGs0hmMFE7jgp2I4p:-KkLGs0hmMFE7jgp2I4q:besxfub) ([raw file](https://github.com/vaadin/framework/blob/17c5cfd7016e31bdf7a06b58ddcd1dd855401bb2/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L142)):*
> ```Java
>         removeDragListeners(dragSource);
> 
>         dragSourceComponentConnector.onDragSourceDetached();
> ```

not called anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9341)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9341)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/framework/9341#-KkLGs0hmMFE7jgp2I4p:-KkLITTkX28QKB4ZQLN1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/17c5cfd7016e31bdf7a06b58ddcd1dd855401bb2/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L142)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not called anywhere?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9341)*

**Pull request merged**
