### PR TITLE
Update DateTimeField failing screenshot

### PR DESCRIPTION
**Pull request by anasmi**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11300)

### CODE REVIEW

**Comment by ZheSun88** [comment]
From the test history of this test, https://teamcity.vaadin.com/project.html?projectId=Vaadin7Framework_ActiveProjects&testNameId=-8077863462660775815&tab=testDetails, you can see it passes for most of the times.. So i think update this screenshot will not make too much difference. 

let us run this build for a few more times, before we merge it.

**Comment by anasmi** [comment]
Then we just should add delay there. I can see the first picture for "second" and then this screenshot (the date is highlighted). Otherwise, it will be unstable always.

**Comment by anasmi** [comment]
But I agree, we can re-run the #11298 : )

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11300)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ZheSun88** [comment]
let's merge it then. green is shown three times in a row.

**Pull request merged**
