### PR TITLE
Add static helpers for creating callback data providers

### PR DESCRIPTION
**Pull request by Legioth**
Cannot overload the same create method for this purpose since it
conflicts with T... overload. Each case is instead given its own
descriptive but still discoverable method name.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8314)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 16 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 266 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFbMNuQQfbq9bfwEXW:-KbFbMNuQQfbq9bfwEXX:bivw9k) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L266)):*
> function that return the

function that returns the ...

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 287 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFbXnqbjbaalD-cGFK:-KbFbXnqbjbaalD-cGFL:bivw9k) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L287)):*
> function that return the

function that returns the ...

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridMultiSelectionModelTest.java, line 669 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFaY7e9lCnFa4Sp7_L:-KbFaY7f7UdnqyDgXumL:b-rd402j) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/test/java/com/vaadin/tests/components/grid/GridMultiSelectionModelTest.java#L669)):*
> ```Java
>                 DataProvider
>                         .fromCallbacks(
>                                 q -> IntStream
> ```

q to query. Same for below.

---

*[server/src/test/java/com/vaadin/ui/AbstractListingTest.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFarg0g5b-hEY39ZkB:-KbFarg0g5b-hEY39ZkC:b-tg8ack) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/test/java/com/vaadin/ui/AbstractListingTest.java#L119)):*
> ```Java
>                 DataProvider
>                         .fromCallbacks(
>                                 q -> Stream.of(ITEM_ARRAY).skip(q.getOffset())
> ```

Also again, q to query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8314)*

**Comment by denis-anisimov** [comment]
Reviewed 16 of 18 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8314)*

**Comment by Legioth** [comment]
Review status: 15 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 266 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFbMNuQQfbq9bfwEXW:-KbGGKWH_CcK8TG4S2_f:bxf12li) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L266)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> function that return the

function that returns the ...
</blockquote></details>

Done. Also fixing the same typo in `CallbackDataProvider` from which this was directly copy-pasted.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 287 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFbXnqbjbaalD-cGFK:-KbGGL37pwiJ5wjaH7GO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L287)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> function that return the

function that returns the ...
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridMultiSelectionModelTest.java, line 669 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFaY7e9lCnFa4Sp7_L:-KbGGiCu9N1-1cXQ0e6C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/test/java/com/vaadin/tests/components/grid/GridMultiSelectionModelTest.java#L669)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

q to query. Same for below.
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/ui/AbstractListingTest.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/8314#-KbFarg0g5b-hEY39ZkB:-KbGGilxEL0BDlOCihLr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b78bebf3c75409ef2863e92837c1463dd044fc3b/server/src/test/java/com/vaadin/ui/AbstractListingTest.java#L119)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Also again, q to query.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8314)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8314#-:-KbJ4DBAHC3k0pX5XT-A:bnfp4nl)*

**Pull request merged**
