### PR TITLE
Back port the fix for #8840 from 8.0 to 7.7 (#8840)

### PR DESCRIPTION
**Pull request by johannest**
Added a new test that verifies the fix for Vaadin 7.7, since Vaadin 8.0
version used TreeGrid not available for 7.7. Used customised
IndexedContainer (with ability to remove a range of rows) to enable
easy reproducibility of the issue.

Change-Id: Ie35814d2daf1940cccd7217c40d2c51454590220

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9108)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridRemoveCachedRowsTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/9108#-Ki51AihDn81n-7KnSNI:-Ki51AihDn81n-7KnSNJ:b-wjc8j0) ([raw file](https://github.com/vaadin/framework/blob/619029f8f505823941f9c3d4beec0b94427973f1/uitest/src/test/java/com/vaadin/tests/components/grid/GridRemoveCachedRowsTest.java#L27)):*
> MultiBrowserTest

`SingleBrowserTest` should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9108)*

**Comment by elmot** [comment]
Туувы ещ иу куифыув

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9108#-:-Ki5nCPux9Yv03aeckuJ:b9qmb4i)*

**Comment by elmot** [comment]
Needs to be rebased

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9108#-:-Ki5oPB6PdOtVyz9PdUR:b-cfk4sg)*

**Comment by ahie** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9108)*

**Comment by johannest** [comment]
Failed this somehow, I'll make a new one

**Pull request closed without merging**
