### PR TITLE
Fix JBoss 6 integration test

### PR DESCRIPTION
**Pull request by elmot**
WIP

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8427)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/servlet-containers/generic/pom.xml, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2igBFADMSZseLj7KQ:-Kc2igBFADMSZseLj7KR:b-blnugi) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L29)):*
> ```XML
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-compatibility-client-compiled</artifactId>
> ```

scope "provided"

---

*[test/servlet-containers/generic/pom.xml, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jL3NKm-WXtQkjzv9:-Kc2jL3NKm-WXtQkjzvA:bmdouf4) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L106)):*
> ```XML
>                 </configuration>
>                 <executions>
>                     <execution>
> ```

perhaps this could have a comment that it builds another WAR with an extra configuration file

---

*[test/servlet-containers/generic/pom.xml, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jRUH-3r7hZiBkZIV:-Kc2jRUH-3r7hZiBkZIW:b-ut381m) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L115)):*
> ```XML
>                             <classifier>jboss6</classifier>
>                             <webResources>
>                                 <resource>
> ```

does this exclude the old defaults? if so, perhaps could combine the two even if empty right now

---

*[test/servlet-containers/generic/pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jAlbk6RtFHGx9ujr:-Kc2jAlc4iKBTppdVp6D:b1qb2w9) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L133)):*
> ```XML
>                         <Bundle-Name>${project.name}</Bundle-Name>
>                         <Bundle-Version>${osgi.bundle.version}</Bundle-Version>
>                         <Import-Package>!com.vaadin.*,*</Import-Package>
> ```

(hard for me to be sure about these, but ok for now if test passes)

---

*[test/servlet-containers/generic/pom.xml, line 147 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2j3sR7JQiDLVbpfQq:-Kc2j3sR7JQiDLVbpfQr:bd5d6lg) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L147)):*
> ```XML
>                             <goal>bundle</goal>
>                         </goals>
>                 <configuration>
> ```

indentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8427)*

**Comment by hesara** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/servlet-containers/generic/pom.xml, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2igBFADMSZseLj7KQ:-Kc3FV5mOkWuxo4rYDbX:bpupsqb) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

scope "provided"
</blockquote></details>

actually not - was correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8427)*

**Comment by elmot** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/servlet-containers/generic/pom.xml, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jL3NKm-WXtQkjzv9:-Kc3HwnHGi65tWS3UTFO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L106)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

perhaps this could have a comment that it builds another WAR with an extra configuration file
</blockquote></details>

Done.

---

*[test/servlet-containers/generic/pom.xml, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jRUH-3r7hZiBkZIV:-Kc3GXh_lSsJ8E5YW6hX:b-vkma0u) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L115)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

does this exclude the old defaults? if so, perhaps could combine the two even if empty right now
</blockquote></details>

No, it does not. All the base resources are in the place.

---

*[test/servlet-containers/generic/pom.xml, line 133 at r1](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc2jAlbk6RtFHGx9ujr:-Kc3GgCgCCF64FPSAPw_:b-6jpqbq) ([raw file](https://github.com/vaadin/framework/blob/e411273273f20da5bbc64629e314ba5acd68fe99/test/servlet-containers/generic/pom.xml#L133)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(hard for me to be sure about these, but ok for now if test passes)
</blockquote></details>

Removed for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8427)*

**Comment by hesara** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/generic/pom.xml, line 33 at r2](https://reviewable.io:443/reviews/vaadin/framework/8427#-Kc3Jcm0LXVRWJKilb1R:-Kc3Jcm0LXVRWJKilb1S:b-qk9x6l) ([raw file](https://github.com/vaadin/framework/blob/0dfd48a1bc8519f531034d8f83d87113e5af1e65/test/servlet-containers/generic/pom.xml#L33)):*
> ```XML
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-client-compiled</artifactId>
> ```

does this really need both the compatibility widgetset and the default widgetset?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8427)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8427)*

**Pull request merged**
