### PR TITLE
Add a note about outdated theme doc files.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8041)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM5JfIzgRwOkuO8rCL:-KZM5JfIzgRwOkuO8rCM:b-k9j1u6) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
> ```AsciiDoc
> = Creating and Using Themes
> 
> _This section has not yet been updated to Vaadin Framework 8.0 version_
> ```

I'd suggest "... updated for Vaadin Framework 8."

---

*[documentation/themes/themes-fonticon.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM5WtY02u2A8tqqW6t:-KZM5WtZpg6ZfNowzGcN:b-ya81ng) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-fonticon.asciidoc#L10)):*
> ```AsciiDoc
> = Font Icons
> 
> _This section has not yet been updated to Vaadin Framework 8.0 version_
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM6KXbjr4BquNo04xI:-KZM6KXbjr4BquNo04xJ:b-fq32ly) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
> ```AsciiDoc
> = Creating and Using Themes
> 
> _This section has not yet been updated to Vaadin Framework 8.0 version_
> ```

Also, add * to both ends of the sentence, and make sure there is line break before and after this line, e.g:

=Header=

*_This section has not yet been updated to Vaadin Framework 8_*

content ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM6KXbjr4BquNo04xI:-KZM84zK-cBzUot5SKC_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Also, add * to both ends of the sentence, and make sure there is line break before and after this line, e.g:

=Header=

*_This section has not yet been updated to Vaadin Framework 8_*

content ...
</blockquote></details>

Done.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM5JfIzgRwOkuO8rCL:-KZM85Ut6j1VuCvt5VeU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'd suggest "... updated for Vaadin Framework 8."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/themes/themes-fonticon.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM5WtY02u2A8tqqW6t:-KZM8GFSnHEerTMf765O:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-fonticon.asciidoc#L10)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM6KXbjr4BquNo04xI:-KZM8nz9-0VvJfEZ3BlW:baobq21) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, but it has to be * first then _ and end with first _ and then *
`*_this section foobar_*`

I urge you to use atom editor or similar so you can see the preview when fixing things

---

*[documentation/themes/themes-fonticon.asciidoc, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM91Owgzy9oE3WiRaR:-KZM91Owgzy9oE3WiRaS:b2jnwy5) ([raw file](https://github.com/vaadin/framework/blob/4ee11dc1f61d1e0c4bd2532411875f84604d1692/documentation/themes/themes-fonticon.asciidoc#L10)):*
> ```AsciiDoc
> = Font Icons
> 
> _*This section has not yet been updated for Vaadin Framework 8.*_
> ```

Sorry, but it has to be * first then _ and end with first _ and then *
`*_this section foobar_*`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/themes/themes-creating.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM6KXbjr4BquNo04xI:-KZMFMgpkC2cDfYSt2ZM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d357cb181358f2dc431a8e2fd707f1e0a02817e/documentation/themes/themes-creating.asciidoc#L10)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sorry, but it has to be * first then _ and end with first _ and then *
`*_this section foobar_*`

I urge you to use atom editor or similar so you can see the preview when fixing things
</blockquote></details>

Done.

---

*[documentation/themes/themes-fonticon.asciidoc, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/8041#-KZM91Owgzy9oE3WiRaR:-KZMFNQ0QTNAKFAOLQb6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ee11dc1f61d1e0c4bd2532411875f84604d1692/documentation/themes/themes-fonticon.asciidoc#L10)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sorry, but it has to be * first then _ and end with first _ and then *
`*_this section foobar_*`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8041)*

**Pull request merged**
