### PR TITLE
Add ErrorLevel to Validators and results

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10099)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IRuZziRiJCu7ncxy:-Kv2IRuZziRiJCu7ncxz:b-whx2jy) (no related file):*
This patch is still Work In Progress, mostly here for initial comments and test build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Review status: 0 of 6 files reviewed at latest revision, 16 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 292 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IbN7OfHG96nLPe3P:-Kv2IbN7OfHG96nLPe3Q:b-nwbg82) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L292)):*
> ```Java
>         /**
>          * A convenience method to add a validator to this binding using the
>          * {@link Validator#from(SerializablePredicate, String)} factory method.
> ```

wrong Validator#from reference

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 313 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IiaLpDWF_89CS78W:-Kv2IiaLpDWF_89CS78X:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L313)):*
> ```Java
>          * @throws IllegalStateException
>          *             if {@code bind} has already been called
>          */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 375 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IuqHB0rySkL8MKi-:-Kv2IuqHB0rySkL8MKi0:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L375)):*
> ```Java
>          * @throws IllegalStateException
>          *             if {@code bind} has already been called
>          */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2050 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JZCu4D7kq3GODDeG:-Kv2JZCu4D7kq3GODDeH:b46gqz0) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L2050)):*
> ```Java
>      *            the validation error result
>      */
>     protected void handleError(HasValue<?> field, ValidationResult result) {
> ```

breaking change - should at least have a since tag and a mention in release notes

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2073 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JJ7LAsrZMAllvzqR:-Kv2JJ7LAsrZMAllvzqS:b-iqwvw0) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L2073)):*
> ```Java
>             status.getResult().ifPresent(result -> handleError(source, result));
>         } else {
>             // Show first non-error message.
> ```

not sure if I understand this branch correctly - might need to re-read after the other parts

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KKc_W-okuVi6A3rs:-Kv2KKc_W-okuVi6A3rt:bj1oel3) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L137)):*
> ```Java
>      *
>      * @param result
>      *            the related result object, may be {@code null}
> ```

could mention what null means

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Ji4KbtG-9Nag_AyP:-Kv2Ji4KbtG-9Nag_AyQ:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L140)):*
> ```Java
>      * @param source
>      *            field whose status has changed, not {@code null}
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KOhH74opaE9r8oF-:-Kv2KOhH74opaE9r8oF0:b-81fs9k) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L144)):*
> ```Java
>             Binding<?, TARGET> source) {
>         Objects.requireNonNull(source, "Event source may not be null");
>         Objects.requireNonNull(source, "Result may not be null");
> ```

remove this duplicate check

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 211 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JkHeRMxbOnNSHJfI:-Kv2JkHeRMxbOnNSHJfJ:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L211)):*
> ```Java
>      * status.
>      * 
>      * @return list of validation results
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jnyoys5Wh9aTgvNk:-Kv2Jnyoys5Wh9aTgvNl:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L92)):*
> ```Java
>      * @throws IllegalStateException
>      *             if the result represents success
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 141 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KbITeaUyHdPs_gzE:-Kv2KbITeaUyHdPs_gzF:b-sqa4mi) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L141)):*
> ```Java
>      *         {@code errorMessage} and {@code errorLevel}
>      * @throws NullPointerException
>      *             if {@code errorMessage} is null
> ```

(or errorLevel is null)

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jp2iIEd2EAYIp9sJ:-Kv2Jp2iIEd2EAYIp9sK:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L142)):*
> ```Java
>      * @throws NullPointerException
>      *             if {@code errorMessage} is null
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JrPeMPlkd3wTXvwC:-Kv2JrPeMPlkd3wTXvwD:bb9zmyk) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResultWrap.java#L26)):*
> ```Java
> import com.vaadin.server.SerializableFunction;
> 
> public class ValidationResultWrap<R> implements Result<R> {
> ```

javadoc and since tag

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 133 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JtjmRf35pZAYv5D0:-Kv2JtjmRf35pZAYv5D1:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Validator.java#L133)):*
> ```Java
>      *            the error level for failures from this validator, not null
>      * @return the new validator using the function
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 174 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jv6IYPILEnwcvouI:-Kv2Jv6IYPILEnwcvouJ:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Validator.java#L174)):*
> ```Java
>      *            the error level for failures from this validator, not null
>      * @return the new validator using the function
>      */
> ```

since tag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 6 files reviewed at latest revision, 16 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 292 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IbN7OfHG96nLPe3P:-Kvaucov2XUdvk_Mvelv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L292)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

wrong Validator#from reference
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 313 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IiaLpDWF_89CS78W:-KvaudJtPwaQBUvPSVqI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L313)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 375 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2IuqHB0rySkL8MKi-:-KvauiS4Euijd6ralqSa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L375)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2050 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JZCu4D7kq3GODDeG:-KvazYEjiZAhvO5qac5C:by9f9ou) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L2050)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

breaking change - should at least have a since tag and a mention in release notes
</blockquote></details>

Added since tag and release notes

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2073 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JJ7LAsrZMAllvzqR:-KvazZBUsqJ0YtYkqL1u:bkmbop1) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Binder.java#L2073)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not sure if I understand this branch correctly - might need to re-read after the other parts
</blockquote></details>

ValidationResult with `ErrorLevel` not defined (`!optional.isPresent()`) are successful. When `ErrorLevel`is `INFO` or `WARNING` it is not considered an error, but will still be shown to the user. This else-block is used to find the first such validation result in the list. If the `ValidationResult` is an Error it's handled in the if-block above (that one still needs some fine tuning).

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KKc_W-okuVi6A3rs:-Kvb-jSRLtHQak_kSLCs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L137)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could mention what null means
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Ji4KbtG-9Nag_AyP:-KvaxgJpY1OXYy3skD4m:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L140)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KOhH74opaE9r8oF-:-KvaxgbZgoaKM55G_SNl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L144)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

remove this duplicate check
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 211 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JkHeRMxbOnNSHJfI:-KvaxzEpxzcQaj8moqQp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L211)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jnyoys5Wh9aTgvNk:-KvayD5Ry8FNZHTcFsLa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L92)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 141 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2KbITeaUyHdPs_gzE:-KvazFtj4arEBGVeYvZx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L141)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(or errorLevel is null)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jp2iIEd2EAYIp9sJ:-KvazGAN9eI4sAKsr_U5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResult.java#L142)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValidationResultWrap.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JrPeMPlkd3wTXvwC:-KvazFOFgAl3vq5rFUpj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/ValidationResultWrap.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

javadoc and since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 133 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2JtjmRf35pZAYv5D0:-KvazULjsaEnzNeFYJTF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Validator.java#L133)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 174 at r1](https://reviewable.io:443/reviews/vaadin/framework/10099#-Kv2Jv6IYPILEnwcvouI:-KvazVj7ycnqPrkGWDpj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f656e5953e5a227ccd513d1b1150362a366944e/server/src/main/java/com/vaadin/data/Validator.java#L174)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r2.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r1, 4 of 6 files at r2, 1 of 2 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2076 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbRSGintGADXXV21Z8:-KvbRSGintGADXXV21Z9:bhisdhf) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/Binder.java#L2076)):*
> ```Java
>         HasValue<?> source = status.getField();
>         clearError(source);
>         if (status.isError()) {
> ```

this still needs a careful review

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 189 at r2](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbNStBRfA9RtAnEiir:-KvbNStBRfA9RtAnEiis:be9wz9p) ([raw file](https://github.com/vaadin/framework/blob/d7df41982d329aa1a15ffba1789a98fa9c0e8046/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L189)):*
> ```Java
>      */
>     public Optional<String> getMessage() {
>         return result.getMessage();
> ```

Handle the case where result is null.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbPkSy1kXizT7G_XxZ:-KvbPkSy1kXizT7G_Xx_:b-kls1sy) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L29)):*
> ```Java
> /**
>  * Represents the status of field validation. Status can be {@code Status.OK},
>  * {@code Status.ERROR} or {@code Status.RESET}. Status OK and ERROR are always
> ```

the third one is Status.UNRESOLVED

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 88 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbQVdkO5GBaDSpsFth:-KvbQVdkO5GBaDSpsFti:bxglv2v) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/ValidationResult.java#L88)):*
> ```Java
>     /**
>      * Returns optional error level for this validation result. Error level is
>      * not defined for successful validation results.
> ```

What makes the second sentence true? (probably ok)

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 131 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbQmwOy8qRYjZBeErM:-KvbQmwOy8qRYjZBeErN:b-vm8ag1) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/ValidationResult.java#L131)):*
> ```Java
>     /**
>      * Creates the validation result which represent a failure with the given
>      * {@code errorMessage} and {@code errorLevel}. Failures with
> ```

I think the name is not optimal as INFO and WARNING are not really failures.

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 114 at r2](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbP-KrkUM7dhkf6wVw:-KvbP-KrkUM7dhkf6wVx:b-vpss35) ([raw file](https://github.com/vaadin/framework/blob/d7df41982d329aa1a15ffba1789a98fa9c0e8046/server/src/main/java/com/vaadin/data/Validator.java#L114)):*
> ```Java
>      * it returns false or throws an exception,
>      * {@link ValidationResult#error(String)} is returned with the given message
>      * and error level {@link ErrorLevel#ERROR}.
> ```

not fixed error level ERROR but based on the parameter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by tsuoanttila** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatus.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbPkSy1kXizT7G_XxZ:-KvbVcEHsChxWTrF774p:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/BindingValidationStatus.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the third one is Status.UNRESOLVED
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 88 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbQVdkO5GBaDSpsFth:-KvbUf--6jqjZ2jIZgGP:b-hvb4e0) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/ValidationResult.java#L88)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What makes the second sentence true? (probably ok)
</blockquote></details>

That is a constraint from the `ValidationResult` interface to allow us to see a difference between "completely ok"  aka (validation passed, no errors of any level) and "not completely ok, but close enough" (aka `info` and `warning`)

---

*[server/src/main/java/com/vaadin/data/ValidationResult.java, line 131 at r3](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbQmwOy8qRYjZBeErM:-KvbUH4ipt5ZwCTHE4zD:b-fh8sal) ([raw file](https://github.com/vaadin/framework/blob/5f4b0d5ba1a8988336fde01d01d45a76f1317c2b/server/src/main/java/com/vaadin/data/ValidationResult.java#L131)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I think the name is not optimal as INFO and WARNING are not really failures.
</blockquote></details>

Technically we could have 5 methods here. `info`, `warning`, `error`, `critical` and `system` but I tried to come up with "close enough common name". Any suggestions on how to rename it ?

---

*[server/src/main/java/com/vaadin/data/Validator.java, line 114 at r2](https://reviewable.io:443/reviews/vaadin/framework/10099#-KvbP-KrkUM7dhkf6wVw:-KvbVQ5K4IhaOXxnUlFd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d7df41982d329aa1a15ffba1789a98fa9c0e8046/server/src/main/java/com/vaadin/data/Validator.java#L114)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not fixed error level ERROR but based on the parameter
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r4.
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10099#-:-KwAOaoHaFLzcqLJMnKp:bnfp4nl)*

**Pull request merged**
