### PR TITLE
URL encode file name in GlobalResourceHandler

### LINKED ISSUE #10747: Vaadin 7.7.13 StreamResource filename with '#' breaks download
To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version: 7.7.13
- Browser version: All
- Tomcat 8.5
- Description of the bug
As described in the forum: https://vaadin.com/forum/thread/17008991/17021057
We are on Vaadin 7.7.13, and our code for creating a StreamResource sets the filename parameter to a value like "Yozons #1234.pdf" as this was the file name uploaded into our system.  For downloading, when we create the StreamResource, the resulting connector URL is invalid and results in a 404.  If the '#' is removed from the file name, it works normally.

Below is our Tomcat access log showing that once the '#' was found in the filename, it just stopped the URL prematurely and thus gets a 404:

0:0:0:0:0:0:0:1 - - [13/Mar/2018:19:28:39 -0500] "GET /open-eSignFormsVaadin/ui/APP/global/0/legacy/0/Yozons%20 HTTP/1.1" 404 16049

Below is the same access log after renaming the file to remove the '#'.  This then works with a valid URL:

0:0:0:0:0:0:0:1 - - [13/Mar/2018:19:38:36 -0500] "GET /open-eSignFormsVaadin/ui/APP/global/0/legacy/0/Yozons%201234.pdf HTTP/1.1" 200 84639

The issue isn't the browser, it's the StreamResource that doesn't encode the filename correctly. I do not create the URL, just the filename for the StreamResource (that is, I do not specify any of the URL '/APP/globa/0/legacy/0/' either).

If I do a traditional download all using UTF-8 encoding, and set the content-disposition header filename="Yozons #123.pdf" there is no issue whatsoever. I can download the file with the '#' symbold from my vaadin app via other schemes without issue, just when I try to use a StreamResource.

It's only that StreamResource is not generating a useful URL when the filename contains a '#' symbol, which is not really weird as they are uploading and downloading files, and file names are not restricted to un-encoded URL characters. Nowhere in the documention does it suggest when I specify the filename param to StreamResource I should be specially encoding it, as StreamResource already encoded things like the space (%20), which I didn't do.

### PR DESCRIPTION
**Pull request by mcollovati**
Fixes #10747

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java, line 25 at r1](https://reviewable.io/reviews/vaadin/framework/10751#-LBdxcKC9ffWI2WzbVEi:-LBdxcKC9ffWI2WzbVEj:bn4z6g8) ([raw file](https://github.com/vaadin/framework/blob/aca235f0e1b55a5979b21cf51416a8a9914eb501/server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java#L25)):*
> ```Java
>         assertEncodedFilenameIsHandled("with spaces.txt", "with+spaces.txt");
>         assertEncodedFilenameIsHandled("with # hash.txt", "with+%23+hash.txt");
>         assertEncodedFilenameIsHandled("with # hash.txt", "with+%23+hash.txt");
> ```

Can you, please, add a couple of other tests, for semicolon, backslash, comma?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)*

**Comment by mcollovati** [comment]
*[server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java, line 25 at r1](https://reviewable.io/reviews/vaadin/framework/10751#-LBdxcKC9ffWI2WzbVEi:-LBwPo4C7yGqNkyd9kev:b22i6nh) ([raw file](https://github.com/vaadin/framework/blob/aca235f0e1b55a5979b21cf51416a8a9914eb501/server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java#L25)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Can you, please, add a couple of other tests, for semicolon, backslash, comma?
</blockquote></details>

Added test for semicolon and comma.
Backslash is not encoded in `ResourceRefernce.encodeFileName`

https://github.com/vaadin/framework/blob/6541b7bad2e41c57a7731611a3f2f7032a5ce947/server/src/main/java/com/vaadin/server/ResourceReference.java#L97-L103


Should I add a test to check that backslash is not encoded, like the following one?

`assertEncodedFilenameIsHandled("with \\ backslash.txt", "with+\\+backslash.txt");`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java, line 25 at r1](https://reviewable.io/reviews/vaadin/framework/10751#-LBdxcKC9ffWI2WzbVEi:-LByPrQy2jJthg-XJ78E:bxnffhw) ([raw file](https://github.com/vaadin/framework/blob/aca235f0e1b55a5979b21cf51416a8a9914eb501/server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java#L25)):*
<details><summary><i>Previously, mcollovati (Marco Collovati) wrote…</i></summary><blockquote>

Added test for semicolon and comma.
Backslash is not encoded in `ResourceRefernce.encodeFileName`

https://github.com/vaadin/framework/blob/6541b7bad2e41c57a7731611a3f2f7032a5ce947/server/src/main/java/com/vaadin/server/ResourceReference.java#L97-L103


Should I add a test to check that backslash is not encoded, like the following one?

`assertEncodedFilenameIsHandled("with \\ backslash.txt", "with+\\+backslash.txt");`



</blockquote></details>

I think yes. That is going to be a kind of documentation rather than a real test.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)*

**Comment by mcollovati** [comment]
*[server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java, line 25 at r1](https://reviewable.io/reviews/vaadin/framework/10751#-LBdxcKC9ffWI2WzbVEi:-LC0QWnWBOQqUd_Ybur1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aca235f0e1b55a5979b21cf51416a8a9914eb501/server/src/test/java/com/vaadin/server/GlobalResourceHandlerTest.java#L25)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I think yes. That is going to be a kind of documentation rather than a real test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10751#-LC347vP2P1rnYgwyp0L:-LC347vP2P1rnYgwyp0M:b-b0es4i) (no related file):*
Using of `URI` class this way looks a bit hackish to me, but it looks working under both Java 8 and 10, so, I would say 
:lgtm:

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10751)*

**Comment by mcollovati** [comment]
> Using of URI class this way looks a bit hackish to me, but it looks working under both Java 8 and 10, so, I would say

Usage of URI has been removed, now the patch only relies on `ResourceReference.encodeFileName`

**Pull request merged**
