### PR TITLE
Make all selected rows draggable

### LINKED ISSUE #8397: Grid selected rows should be draggable
Grabbing a selected row in Grid should start a drag operation for the whole selection.

It should first use the default browser behavior for the drag image.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves  #8397

If selection mode is `MULTI` and dragged row is selected, collect all other selected rows and create a json array of their drag data.

Is it a good idea to iterate through all the rows to look for selected ones? On the client side there doesn't seem to be a method that returns them.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8746)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-Kelqr6XsYY2-5WD1w6q:-Kelqr6XsYY2-5WD1w6r:b-7qkf1d) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L87)):*
> ```Java
>             ((NativeEvent) event).getDataTransfer()
>                     .setData(GridDragSourceExtensionState.DATA_TYPE_DRAG_DATA,
>                             dragData.toJson());
> ```

For the drag image generated by the browser, there is no difference in dragging a single or multiple rows ?

We should be able to make it somehow visible that now there is N amount of rows being dragged..

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-KelpixK6uhdWKTh_kmC:-KelpixLZjZ_QjeiNK_O:b-fmoz23) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L121)):*
> ```Java
>         int size = gridConnector.getDataSource().size();
>         for (int i = 0; i < size; i++) {
>             JsonObject row = gridConnector.getDataSource().getRow(i);
> ```

Not all the rows are available in the grid on client side. What happens if this row is outside of the currently cached rows range ? 

It seems that there will be a `null` returned by the data source, and then `SelectionModel.isItemSelected(JsonObject)` will be trying to fetch a value for a not defined item.

As we discussed, could possibly work around this by separately listening to selection changes on server side, and on multi selection the grid drag source extension should send all selected items itself to the client side ... I can't come up with a better option atm.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-Kelp9iUBisTdUmF24iA:-Kelp9iXwOm16ZhVEBxD:bb57t21) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L45)):*
> ```Java
>         dragSourceComponent.addColumn(Bean::getValue).setCaption("Value");
> 
>         dragSourceComponent.setSelectionMode(Grid.SelectionMode.MULTI);
> ```

Can you please add a "switch" to the UI to change between single and multiselection for grid ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by wbadam** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-KelpixK6uhdWKTh_kmC:-KfFpjvY6WPdRhYgdXkJ:bgxalah) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L121)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not all the rows are available in the grid on client side. What happens if this row is outside of the currently cached rows range ? 

It seems that there will be a `null` returned by the data source, and then `SelectionModel.isItemSelected(JsonObject)` will be trying to fetch a value for a not defined item.

As we discussed, could possibly work around this by separately listening to selection changes on server side, and on multi selection the grid drag source extension should send all selected items itself to the client side ... I can't come up with a better option atm.
</blockquote></details>

How to send items to client? RPC? Generator?

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-Kelp9iUBisTdUmF24iA:-KfFiRVOJWy1G1TSvWVq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L45)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you please add a "switch" to the UI to change between single and multiselection for grid ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-KelpixK6uhdWKTh_kmC:-KfFrvGiqjAi-xJTm2_p:bvv9xwm) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L121)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

How to send items to client? RPC? Generator?
</blockquote></details>

Actually, for now, lets just go with this approach:

When on multi select mode, when dragging selected rows, only the currently visible selected rows are being dragged. This REQUIRES that you update all the javadocs accordingly on the server side.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by wbadam** [comment]
Should it be possible to drag a single row when SelectionMode.NONE is set? Also, when a row is selected but the drag is originated from another row, which row should be dragged?

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-KelpixK6uhdWKTh_kmC:-KfGF6SqbFUUWaMw8cEm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L121)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Actually, for now, lets just go with this approach:

When on multi select mode, when dragging selected rows, only the currently visible selected rows are being dragged. This REQUIRES that you update all the javadocs accordingly on the server side.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746#-:-KfGF007Q5vdhUYzBsVE:b-xbgd9h)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8746#-KfGp2vor-ls44qiEuX-:-KfGp2vor-ls44qiEuX0:b-834kzr) (no related file):*
As discussed separately, it should work as:
- if the dragged row is selected, then drag all selected rows

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 31 at r3](https://reviewable.io:443/reviews/vaadin/framework/8746#-KfGo1rrcYcy8NKHQ5zk:-KfGo1rrcYcy8NKHQ5zl:brnp9ew) ([raw file](https://github.com/vaadin/framework/blob/6622334c06fa31e55665edb99431f3ad5618aced/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L31)):*
> ```Java
>  * <p>
>  * When selection mode is {@link com.vaadin.ui.Grid.SelectionMode#MULTI}, the
>  * currently visible rows are dragged.
> ```

Please highlight that ONLY the visible rows are added as drag data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8746#-KfGp2vor-ls44qiEuX-:-KfGFJ-25VauxGWoR3Rh:buj0jiz) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

As discussed separately, it should work as:
- if the dragged row is selected, then drag all selected rows
</blockquote></details>

Currently it's working just like that :+1: 

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 31 at r3](https://reviewable.io:443/reviews/vaadin/framework/8746#-KfGo1rrcYcy8NKHQ5zk:-KfH63XgS0x4xieKvNju:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6622334c06fa31e55665edb99431f3ad5618aced/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please highlight that ONLY the visible rows are added as drag data.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by wbadam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-Kelqr6XsYY2-5WD1w6q:-KfHS1BfP9ezAFrt2Bug:b2pqs9p) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L87)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

For the drag image generated by the browser, there is no difference in dragging a single or multiple rows ?

We should be able to make it somehow visible that now there is N amount of rows being dragged..
</blockquote></details>

It is possible to set `DataTransfer.setDragImage()` that accepts an `img` element. I prefer leaving the design to a UI designer.
Could also consider setting an image on single row drags.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/8746#-Kelqr6XsYY2-5WD1w6q:-KfLD7iejqIxOQceMwBh:bb46awr) ([raw file](https://github.com/vaadin/framework/blob/bb262ab3f955e1f88d663c21de0981c3b77695bb/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L87)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

It is possible to set `DataTransfer.setDragImage()` that accepts an `img` element. I prefer leaving the design to a UI designer.
Could also consider setting an image on single row drags.
</blockquote></details>

Created #8854 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8746)*

**Pull request merged**
