### PR TITLE
Add ACCEPT attribute to Upload

### LINKED ISSUE #2410: Support RFC 1867 accept attribute for file upload
**Originally by @hesara**

___
The RFC 1867 accept attribute enables defining which MIME types are selectable in a file upload dialog. While the browser support is limited, many newer versions of browsers do support it. We could add support for setting the attribute in the Upload component, with a warning that not all browsers respect it.

See http://en.wikipedia.org/wiki/File_select#Accept_attribute and the forum thread https://vaadin.com/forum/-/message_boards/view_message/428096 .

___
 Imported from https://dev.vaadin.com/ issue #8857

### PR DESCRIPTION
**Pull request by elmot**
Fixes #2410

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/screenshots, line 1 at r1](https://reviewable.io/reviews/vaadin/framework/10906#-LC3yioE0Vj5_PMlaPq3:-LC3yioE0Vj5_PMlaPq4:b-iluukf) ([raw file](https://github.com/vaadin/framework/blob/5b5792364a41ab8de28d90e26f42bbbe01ac1dac/tests/screenshots#L1)):*
> ```
> Subproject commit 129646ec7ced43eb88895f235cb356dacb6dc6c0
> ```

Revert changes to this file.

---

*[uitest/src/test/java/com/vaadin/tests/themes/valo/ImmediateUploadTest.java, line 81 at r1](https://reviewable.io/reviews/vaadin/framework/10906#-LC3ys7T1UsuWMFwyZHI:-LC3ys7U2FQ1r99nM96d:b-v8m076) ([raw file](https://github.com/vaadin/framework/blob/849472af72d27ea02f244635629ffab68b8944cf/uitest/src/test/java/com/vaadin/tests/themes/valo/ImmediateUploadTest.java#L81)):*
> ```Java
>     @Test
>     public void testAcceptAttribute()
>     {
> ```

formatting nit, ok to ignore (we should add the formatter plugin to uitest as well)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/screenshots, line 1 at r1](https://reviewable.io/reviews/vaadin/framework/10906#-LC3yioE0Vj5_PMlaPq3:-LC42NKk50obv1k3DXyo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5b5792364a41ab8de28d90e26f42bbbe01ac1dac/tests/screenshots#L1)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Revert changes to this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

---

*[uitest/src/test/java/com/vaadin/tests/resources/FrontendInitialResourceUITest.java, line 15 at r5](https://reviewable.io/reviews/vaadin/framework/10906#-LEmqIYW5lGk-GC_nV3Q:-LEmqIYW5lGk-GC_nV3R:bslem14) ([raw file](https://github.com/vaadin/framework/blob/9b104ee41ceb717336c013675257b2278d5155c0/uitest/src/test/java/com/vaadin/tests/resources/FrontendInitialResourceUITest.java#L15)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> public class FrontendInitialResourceUITest extends MultiBrowserTest {
> ```

Did you run this and following test on other browsers to see that those still work? If not, I'll run the full test set for this PR

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)*

**Comment by elmot** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

---

*[uitest/src/test/java/com/vaadin/tests/resources/FrontendInitialResourceUITest.java, line 15 at r5](https://reviewable.io/reviews/vaadin/framework/10906#-LEmqIYW5lGk-GC_nV3Q:-LEn4IwL2rujuyuunpjg:bqlspse) ([raw file](https://github.com/vaadin/framework/blob/9b104ee41ceb717336c013675257b2278d5155c0/uitest/src/test/java/com/vaadin/tests/resources/FrontendInitialResourceUITest.java#L15)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Did you run this and following test on other browsers to see that those still work? If not, I'll run the full test set for this PR
</blockquote></details>

Please do

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10906)*

**Pull request merged**
