### PR TITLE
Allow setting custom styles to DateField calendar date cells (#10304)

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10305)

### CODE REVIEW

**Comment by torok-peter** [comment]
Looks good to me but I would also like @tsuoanttila to have an approving look at it.

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305#-:-KyaSBv-JCNIg0aqLn5z:b-ul1hfh)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10305#-KyaTKLse317E09si0y1:-KyaTKLse317E09si0y2:b-ovrq6p) (no related file):*
I mean, wait for Teemu to approve it, you darned reviewer tool!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10305#-KyaTKLse317E09si0y1:-KytwR00K-v4lewK17pm:b2qk0wh) (no related file):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

I mean, wait for Teemu to approve it, you darned reviewer tool!
</blockquote></details>

I've taken a look and added my last comment in there about some API related things.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 847 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-Kytve-j9uarGx8byy-g:-Kytve-j9uarGx8byy-h:b-fcy3v5) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L847)):*
> ```Java
>      */
>     @SuppressWarnings("deprecation")
>     public void removeDateStyle(Date date) {
> ```

API Consistency question. Usually when we are using `remove` in an API, the counterpart is `add`. Should we use the setter and consider `null` to be remove? Or actually have `add` and `remove` methods with support for multiple stylenames for every date?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 827 at r3](https://reviewable.io:443/reviews/vaadin/framework/10305#-Kz8MUCcMvvbtV4rk01h:-Kz8MUCcMvvbtV4rk01i:b1j2rfh) ([raw file](https://github.com/vaadin/framework/blob/f1a68f156d9d6a8696143935df9e53a86d7807da/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L827)):*
> ```Java
>      *            determines which date cell to modify
>      * @param styleName
>      *            determines which custom style name to set to the date cell, if
> ```

could reformat to `the custom style names for given date; {@code null} to clear custom style names` (technically you can give `"foo bar baz"` and get three names here if I'm not mistaken). The word "determines" is a bit extra in both of these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 847 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-Kytve-j9uarGx8byy-g:-KzTcWmYtSSPorVlNEuB:b-87me3t) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L847)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

API Consistency question. Usually when we are using `remove` in an API, the counterpart is `add`. Should we use the setter and consider `null` to be remove? Or actually have `add` and `remove` methods with support for multiple stylenames for every date?
</blockquote></details>

Same question relating to the parameter type `Date` vs `T`

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzTc_S7U_hB9EO0iddl:b-u83j5w) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
> ```Java
>      */
>     @SuppressWarnings("deprecation")
>     public String getDateStyle(Date date) {
> ```

See question about `Date` vs `T`

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 831 at r4](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTcCkZA9TuVBtYc1Tr:-KzTcCk_Ch_rjm79ykws:b-q7geyv) ([raw file](https://github.com/vaadin/framework/blob/3f04aefe1d942cc3c10652b526067af94dca8cd3/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L831)):*
> ```Java
>      */
>     @SuppressWarnings("deprecation")
>     public void setDateStyle(Date date, String styleName) {
> ```

Should the date type be `T` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Legioth** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzY8HQWwTY_7NrNaT5j:bj90040) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

See question about `Date` vs `T`
</blockquote></details>

I believe we should use `LocalDate` and not  `T`. This is about setting a style for a specific day in the calendar, regardless of whether `T` is `LocalDate` or `LocalDateTime`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Ansku** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzY96mPU6vV4f7VBM9N:b-td0ir5) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I believe we should use `LocalDate` and not  `T`. This is about setting a style for a specific day in the calendar, regardless of whether `T` is `LocalDate` or `LocalDateTime`.
</blockquote></details>

It might make it a bit more of a hassle to have to use two different temporal types in relation to the same component, though. The dates are regardless converted to use midnight for the style handling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Legioth** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzYKQSGEW-65a2CxQYK:b-w8kcjy) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

It might make it a bit more of a hassle to have to use two different temporal types in relation to the same component, though. The dates are regardless converted to use midnight for the style handling.
</blockquote></details>

I don't see that there's any relationship between the two different temporal styles. One is for the value, the other is for configuration that is (assumingly) the same regardless of the value. On the contrary, I would find it very inconvenient that I'd have to define the time of the day when defining that e.g. Independence Day is styled in some other way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Ansku** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzYLzRSKHTsjdyHVRoi:b-sqm5vn) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I don't see that there's any relationship between the two different temporal styles. One is for the value, the other is for configuration that is (assumingly) the same regardless of the value. On the contrary, I would find it very inconvenient that I'd have to define the time of the day when defining that e.g. Independence Day is styled in some other way.
</blockquote></details>

I'm thinking of a use case where any day that has a time stamp in collectionX gets style X (logic along the lines of "this date has previously booked events"). Granted, it probably wouldn't be a huge issue to get just the date out of such use case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Legioth** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzYTG-DLU9cCsZBv7Ef:bt47ree) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I'm thinking of a use case where any day that has a time stamp in collectionX gets style X (logic along the lines of "this date has previously booked events"). Granted, it probably wouldn't be a huge issue to get just the date out of such use case.
</blockquote></details>

There are indeed cases when either alternative would be more convenient. I'd still go with `LocalDate` instead of  `T` because that's more correct from a semantic point of view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Ansku** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzYTtVVrGbpcPUosgBV:b-fm21aq) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

There are indeed cases when either alternative would be more convenient. I'd still go with `LocalDate` instead of  `T` because that's more correct from a semantic point of view.
</blockquote></details>

Fair enough. Does Teemu have anything to add, or shall I make the change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzYY0ImpxqSkGkSpPb1:bej0bnc) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Fair enough. Does Teemu have anything to add, or shall I make the change?
</blockquote></details>

Go ahead and make the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by Ansku** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 866 at r2](https://reviewable.io:443/reviews/vaadin/framework/10305#-KzTc_S7U_hB9EO0iddk:-KzciI2AcNc1C4zYf_16:b-3rqkey) ([raw file](https://github.com/vaadin/framework/blob/9ea7a231053362a7802de33a9442ad55e46cfcad/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L866)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Go ahead and make the change.
</blockquote></details>

Done, and also switched to use String handling instead of Date handling in the map as discussed with Leif in Slack.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 5 files at r5, 1 of 4 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10305#-L1NBL70j-Gk_SJBHroF:-L1NBL70j-Gk_SJBHroG:b2hc0p9) (no related file):*
Needs rebase/merge with `master`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10305#-L1NBL70j-Gk_SJBHroF:-L1RoudLrutQrkVi_jaU:b-896fix) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Needs rebase/merge with `master`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10305)*

**Pull request merged**
