### PR TITLE
Fix Firefox test issues

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 56 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1066 at r1](https://reviewable.io/reviews/vaadin/framework/11017#-LGOxyYc4-jCI9nuUYTj:-LGOxyYc4-jCI9nuUYTk:bbb48ue) ([raw file](https://github.com/vaadin/framework/blob/b9752c9e26b1b312b1285908c190f39e395246b4/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1066)):*
> ```Java
>             selectMenu(menuCaptions[i]);
>             new Actions(getDriver()).moveByOffset(
>                     getMenuElement(menuCaptions[i]).getSize().getWidth(), 0)
> ```

Is it moving to the top-rightmost pixel? Is it reliable enough? might be `moveByOffset(
                    getMenuElement(menuCaptions[i]).getSize().getWidth()-1, 1)`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 56 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1066 at r1](https://reviewable.io/reviews/vaadin/framework/11017#-LGOxyYc4-jCI9nuUYTj:-LGOydy13gNaOR7Szlip:bveppwx) ([raw file](https://github.com/vaadin/framework/blob/b9752c9e26b1b312b1285908c190f39e395246b4/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1066)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Is it moving to the top-rightmost pixel? Is it reliable enough? might be `moveByOffset(
                    getMenuElement(menuCaptions[i]).getSize().getWidth()-1, 1)`?
</blockquote></details>

Newer WebDrivers move to center of the element. Notification from Selenium when running test:
```
INFO: When using the W3C Action commands, offsets are from the center of element
Jul 02, 2018 10:53:14 AM org.openqa.selenium.interactions.Actions moveToElement
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 56 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1066 at r1](https://reviewable.io/reviews/vaadin/framework/11017#-LGOxyYc4-jCI9nuUYTj:-LGOz05oD1ruiNxv_Hkv:b-wqkqjz) ([raw file](https://github.com/vaadin/framework/blob/b9752c9e26b1b312b1285908c190f39e395246b4/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1066)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Newer WebDrivers move to center of the element. Notification from Selenium when running test:
```
INFO: When using the W3C Action commands, offsets are from the center of element
Jul 02, 2018 10:53:14 AM org.openqa.selenium.interactions.Actions moveToElement
```
</blockquote></details>

And this `moveByOffset` is there to move the mouse to the new opened submenu.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 56 of 56 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017#-:-LGP05Tm2qdb2lT55xgd:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11017)*

**Pull request merged**
