### PR TITLE
Java 10 compatibility step 1(Memory tests removed)

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10973)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10973#-LEPvvTCDbrUe0i0fo77:-LEPvvTCDbrUe0i0fo78:b2nhqqh) (no related file):*
WIP

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10973)*

**Comment by elmot** [comment]
Related to #10737

**Comment by elmot** [comment]
Java 10 (actually Java 9+) does not contain Nashorn API, and memory tests are not compilable anymore.
The change excludes those tests from whole compilation process for Java 10.
So it was decided to keep this PR open until those new memory tests are done (probably using java instrumentation API instead of Nashorn)

Also the project has quite tricky maven profiles system, better to review profiles, but that is another question.

**Review by elmot — COMMENTED** [review]
One can not sign a CLA under some email if the email does not exists anymore

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10973#-:-LimRicwENjG89zt3jtB:bfk8791)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot)

**Review by elmot — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10973#-:-LimS-UkALTwyMdldE0k:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot)

**Comment by TatuLund** [comment]
Unfortunately there has been too little attention towards this PR. I am closing this PR as outdated. The proposed idea may still be valid, but requires PR done against current master.

**Pull request closed without merging**
