### PR TITLE
Serve VAADIN files also from META-INF/resources

### LINKED ISSUE #8206: VAADIN doesn't work in web fragments
For larger web application it's handy to split it into several web fragments. Static resources in web fragments are put into the META-INF/resources folder instead of the root folder. However, there is a bug in VaadinServlet.isAllowedVAADINResourceUrl which makes this impossible:

> Blocked attempt to access a JAR entry not starting with /VAADIN/: jar:file:/blablabla/com.knime.enterprise.war/WEB-INF/lib/webportal-4.4.0.jar!/META-INF/resources/VAADIN/login.html 

The affected method should also allow /META-INF/resources/VAADIN in case it exists.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8206

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8286)

### CODE REVIEW

**Comment by Artur-** [comment]
Auto-test should preferably be added when merging into master, where there is a suitable module to add it.

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8286#-KawOK8R1KvFUZmiI32p:-KawOK8R1KvFUZmiI32q:b-o821os) (no related file):*
Please create a ticket for the test in the master. Otherwise it will be forgotten.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8286)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8286#-KawOK8R1KvFUZmiI32p:-KaxMT3yes8bux4NEro0:bb43067) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Please create a ticket for the test in the master. Otherwise it will be forgotten.
</blockquote></details>

Created #8300 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8286)*

**Comment by denis-anisimov** [comment]
Needs rebase (and license wth ? ).

**Comment by Artur-** [comment]
Just press the "Update branch"  button to rebase?

**Comment by denis-anisimov** [comment]
Wasn't enabled for me.....
Or may be I'm just blind.

**Comment by Artur-** [comment]
Ah sorry, for some reason the "Allow edits from maintainers" was not checked

**Pull request merged**
