### PR TITLE
Add events and functionality to Tree

### LINKED ISSUE #9215: Tree: some TreeGrid features are not supported
- [ ] `addItemClickListener()` (draft documentation is commented out)
- [ ] `setItemCollapseAllowedProvider()` (draft documentation is commented out)
- [ ] `setItemStyleGenerator()` (draft documentation is commented out)

### PR DESCRIPTION
**Pull request by tsuoanttila**
Closes #9215

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9318)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAo1pqagsByi9dyV3a:-KkAo1prhnPmE2lAnKUc:b-snzuls) ([raw file](https://github.com/vaadin/framework/blob/cbb4393847f02fdbdcd64528918aeacbdc5565e3/server/src/main/java/com/vaadin/ui/Tree.java#L61)):*
> ```Java
>      * into data objects.
>      *
>      * @since 8.1
> ```

Why removed since tag? Does javadoc get it from the nesting class?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAmCvC1RlLh8ZlTUy3:-KkAmCvDOVcBcT1E4F7G:b-cuds01) ([raw file](https://github.com/vaadin/framework/blob/628f4b59c4e0b2360f7c7157d4ae1250c500149b/server/src/main/java/com/vaadin/ui/Tree.java#L71)):*
> ```Java
>      *
>      * @param <T>
>      *            the tree bean type
> ```

"tree item type"?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAoB2Xfrd3ST7Ry8WG:-KkAoB2Xfrd3ST7Ry8WH:b-gyddc) ([raw file](https://github.com/vaadin/framework/blob/628f4b59c4e0b2360f7c7157d4ae1250c500149b/server/src/main/java/com/vaadin/ui/Tree.java#L75)):*
> ```Java
>      * @see ItemClick
>      * @see Registration
>      */
> ```

since tag?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAoEYA4kEKVkvE_kWq:-KkAoEYA4kEKVkvE_kWr:b-gyddc) ([raw file](https://github.com/vaadin/framework/blob/628f4b59c4e0b2360f7c7157d4ae1250c500149b/server/src/main/java/com/vaadin/ui/Tree.java#L92)):*
> ```Java
>      * 
>      * @param <T>
>      *            the data type of tree
> ```

since tag?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 213 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAlxWRfnh6ULD8ajom:-KkAlxWRfnh6ULD8ajon:bn4jjlj) ([raw file](https://github.com/vaadin/framework/blob/628f4b59c4e0b2360f7c7157d4ae1250c500149b/server/src/main/java/com/vaadin/ui/Tree.java#L213)):*
> ```Java
>         treeGrid.addCollapseListener(e -> fireCollapseEvent(
>                 e.getCollapsedItem(), e.isUserOriginated()));
>         treeGrid.addItemClickListener(
> ```

Always listening to these, even if no listeners? (probably ok)

---

*[uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAlXGUBQk8Gzu0BAzI:-KkAlXGUBQk8Gzu0BAzJ:bwrf3gt) ([raw file](https://github.com/vaadin/framework/blob/628f4b59c4e0b2360f7c7157d4ae1250c500149b/uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java#L71)):*
> ```Java
>         createIconMenu(componentMenu.addItem("Icons", null));
>         createCaptionMenu(componentMenu.addItem("Captions", null));
>         componentMenu.addItem("Item Click Listener", new Command() {
> ```

(could have a helper subclass of Command for such, but no need to do it right now)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9318)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkEo8YkSOX8FCZwr7m7:-KkEo8YkSOX8FCZwr7m8:buc3oha) (no related file):*
Fixing review comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9318)*

**Comment by pleku** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAo1pqagsByi9dyV3a:-KkEp3CBwaSg5y6El-tn:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/e788fa906b968a298414e60cbb15cc7d6389b8a1/server/src/main/java/com/vaadin/ui/Tree.java#L61)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why removed since tag? Does javadoc get it from the nesting class?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAmCvC1RlLh8ZlTUy3:-KkEoeuF-DdNbi2tYvLi:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/fac8a79ba4b1062fd0467d88a846cfb2a6c8274b/server/src/main/java/com/vaadin/ui/Tree.java#L71)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"tree item type"?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAoB2Xfrd3ST7Ry8WG:-KkEoi-D5cQ_VAILzMbQ:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/fac8a79ba4b1062fd0467d88a846cfb2a6c8274b/server/src/main/java/com/vaadin/ui/Tree.java#L75)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/9318#-KkAoEYA4kEKVkvE_kWq:-KkEokhGZvUHuWJZnKex:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/fac8a79ba4b1062fd0467d88a846cfb2a6c8274b/server/src/main/java/com/vaadin/ui/Tree.java#L92)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9318)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9318)*

**Pull request merged**
