### PR TITLE
Checkbox allow customizing of input and label classNames.

### PR DESCRIPTION
**Pull request by knoobie**
### Why? Use-case:

Integration of third party style/css, where we have to use custom styles for the checkbox's input and label element.

### WIP:
Open for dicussion, how I should write the server side for you. 

I don't think that copying getStyleNames and so on, is the best approach. 

### Missing things: 

- [x] Server Side Integration
- [x] Unit Tests
- [x] Client Side Tests

### Possible Server API:

> checkBox.addInputStyleName("custom-input-style");
> checkBox.addLabelStyleName("custom-label-style");

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)

### CODE REVIEW

**Comment by pleku** [comment]
I understand the use case, but are you sure that adding a class name to the label & input elements in DOM is enough to make it specific enough to override the `Checkbox` default styles ?

I think this could be easily made as an add-on instead of adding it to the core... but if you want to do it and are willing to write all the tests, sure.

The API design and semantics on how it works for the server side should be similar to the current API in component - see https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Component.java.
One thing would be to not bloat the `CheckBox` public API with all the different methods, but use another _configuration_ object for that, eg. `checkbox.getInputElement().addStyleName("my-pretty-checkbox);` and same for the label.

**Comment by knoobie** [comment]
Thanks Pekka!

> override the Checkbox default styles

My workflow would be to exclude the default vaadin styling of the checkbox via sass and only allow the external style - worked like a charm with other components in the past!

>`checkbox.getInputElement()`

That's a good idea! Gonna go with that.

**Comment by knoobie** [comment]
@pleku implementation ready for a first look

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: all files reviewed, 5 unresolved discussions (waiting on @knoobie)

___
*[client/src/main/java/com/vaadin/client/ui/VCheckBox.java, line 87 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-VPddB10M6IPnUZCw:-LU-VPddB10M6IPnUZCx:b-m4mcl) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/client/src/main/java/com/vaadin/client/ui/VCheckBox.java#L87)):*
> ```
>  public Element getCheckBoxElement()
> ```

I have a bit concern about this API naming, as, on the server side, we have separated the `input` and `label` elements, does it make sense to change this one to `getInputElement()` instead of `getCheckBoxElement()`. It feels a bit confusing with this name.  

This is not related to this patch though,  and the Javadoc explains `Gives access to the input element`. not blocking anything. 
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 13 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-Xyii9U3D1DGpwRGR:-LU-Xyii9U3D1DGpwRGS:bjz7e70) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L13)):*
> ```Java
> import com.vaadin.tests.util.MockUI;
> 
> import static org.junit.Assert.*;
> ```

Import individual classes separately instead of using wildcard
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 134 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-YWm5-gPsyl3PDr9a:-LU-YWm5-gPsyl3PDr9b:b5dye4q) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L134)):*
> ```Java
>         hasStyleNames.setStyleName("set-style multiple values");
>         assertEquals("set-style multiple values", hasStyleNames.getStyleName());
> ```

Add the test for `setStyleName(String style, boolean add)`
___
*[uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java, line 10 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-ZPfR5RY0H6rFbX_I:-LU-ZPfR5RY0H6rFbX_J:blvc93g) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java#L10)):*
> ```Java
> import org.openqa.selenium.WebElement;
> 
> import static org.junit.Assert.*;
> ```

Replace this wildcard with individual imports
___
*[uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java, line 34 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-ZZUX0Sk6NZfFOt2u:-LU-ZZUX0Sk6NZfFOt2v:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java#L34)):*
> ```Java
>         assertEquals("later-applied-input-class", inputElem.getAttribute("class"));
>     }
> }
> ```

new line

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: all files reviewed, 5 unresolved discussions (waiting on @knoobie)

___
*[client/src/main/java/com/vaadin/client/ui/VCheckBox.java, line 87 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-VPddB10M6IPnUZCw:-LU-iBmO12uMhVtFkeGQ:bbggi0r) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/client/src/main/java/com/vaadin/client/ui/VCheckBox.java#L87)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
>  public Element getCheckBoxElement()
> ```

I have a bit concern about this API naming, as, on the server side, we have separated the `input` and `label` elements, does it make sense to change this one to `getInputElement()` instead of `getCheckBoxElement()`. It feels a bit confusing with this name.  

This is not related to this patch though,  and the Javadoc explains `Gives access to the input element`. not blocking anything. 
</blockquote></details>

had a discussion in the team, to avoid the confusion, let us change this API name to `getInputElement()` correspondingly.

**Review by knoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/ui/VCheckBox.java, line 87 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-VPddB10M6IPnUZCw:-LU-recpANTjiS_JgqnN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/client/src/main/java/com/vaadin/client/ui/VCheckBox.java#L87)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

had a discussion in the team, to avoid the confusion, let us change this API name to `getInputElement()` correspondingly. 
</blockquote></details>

Done.
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 13 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-Xyii9U3D1DGpwRGR:-LU-rjLE14JBP7eRbOtl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L13)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Import individual classes separately instead of using wildcard
</blockquote></details>

Done.
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 134 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-YWm5-gPsyl3PDr9a:-LU-rkC0Eh4UWJmjfRuC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L134)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Add the test for `setStyleName(String style, boolean add)`
</blockquote></details>

Done.
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 145 at r14](https://reviewable.io/reviews/vaadin/framework/11372#-LU-rou_5y7vFrl0FYpB:-LU-rou_5y7vFrl0FYpC:b-jik2xb) ([raw file](https://github.com/vaadin/framework/blob/bbc43230b1457f948bc98f6e5275e7c098647c82/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L145)):*
> ```Java
>                 "multiple values", hasStyleNames.getStyleName());
> 
>         // FIXME? - should a null style be ignored? Currently it throws a NPE like the implemenation in Component
> ```

Do you want me to allow null here / create a ticket for it?
___
*[uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java, line 10 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-ZPfR5RY0H6rFbX_I:-LU-rm0X4mUFIPXk57rV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java#L10)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Replace this wildcard with individual imports
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java, line 34 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-ZZUX0Sk6NZfFOt2u:-LU-rmd96W8vS017Yl2f:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/uitest/src/test/java/com/vaadin/tests/components/checkbox/CheckboxInputValueElementTest.java#L34)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, 1 of 2 files at r11, 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @ZheSun88 and @knoobie)

___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 13 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-Xyii9U3D1DGpwRGR:-LU03M-y9lv26ouZBs1H:bf7elur) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L13)):*
> ```
> import org.apache.commons.lang.StringUtils;
> ```

I didn't notice this dependency in the first round review. I remembered that we are trying to avoid `apache Commons` and `Guava` dependency on the projects, though you still can find them.

If it is possible, let us use some other ways, okay?
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 145 at r14](https://reviewable.io/reviews/vaadin/framework/11372#-LU-rou_5y7vFrl0FYpB:-LU0-feR1bLVBpYyZF35:b-7demze) ([raw file](https://github.com/vaadin/framework/blob/bbc43230b1457f948bc98f6e5275e7c098647c82/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L145)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Do you want me to allow null here / create a ticket for it?
</blockquote></details>

I think it makes sense to ignore the null value when removing a style. But let us create a ticket for now. I think the `Component.java` should also have the same implementation. Thanks for that.

**Comment by knoobie** [comment]
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 13 at r7](https://reviewable.io/reviews/vaadin/framework/11372#-LU-Xyii9U3D1DGpwRGR:-LU0BJlBBW-Jp489ogEC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebcd3435335e2e5e16b8d49802952b5844661082/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L13)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> import org.apache.commons.lang.StringUtils;
> ```

I didn't notice this dependency in the first round review. I remembered that we are trying to avoid `apache Commons` and `Guava` dependency on the projects, though you still can find them.

If it is possible, let us use some other ways, okay?
</blockquote></details>

Done.

**Comment by knoobie** [comment]
___
*[server/src/test/java/com/vaadin/ui/CheckBoxTest.java, line 89 at r15](https://reviewable.io/reviews/vaadin/framework/11372#-LU0BTpK0Ncq9n58Ji_4:-LU0BTpK0Ncq9n58Ji_5:b-1pum3n) ([raw file](https://github.com/vaadin/framework/blob/4aeafa709b01bce2bc1eb10b0e08e58c98004398/server/src/test/java/com/vaadin/ui/CheckBoxTest.java#L89)):*
> ```Java
> 
>     @Test
>     @Ignore("Component#setStyleName(null, false) should not throw a NPE")
> ```

FYI - created a Ignored Test that can be enabled later, if you wanna fix it

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r12, 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @ZheSun88 and @knoobie)

___
*[client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java, line 173 at r1](https://reviewable.io/reviews/vaadin/framework/11372#-LU0EsEiBlRQOitTdQNC:-LU0EsEiBlRQOitTdQND:beljh67) ([raw file](https://github.com/vaadin/framework/blob/883142b00ad3f2a32d5f9a5ceab7490b0afcb161/client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java#L173)):*
> ```Java
>             // add new style names
>             for (String newStyle : serverSideStyes) {
>                 setWidgetStyleName(newStyle, true);
> ```

curious: is this removed on purpose?

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 2 files at r14, 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: all files reviewed, 1 unresolved discussion (waiting on @knoobie)

**Comment by knoobie** [comment]
___
*[client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java, line 173 at r1](https://reviewable.io/reviews/vaadin/framework/11372#-LU0EsEiBlRQOitTdQNC:-LU0KM_o2-F827E3TuSV:b-5hffug) ([raw file](https://github.com/vaadin/framework/blob/883142b00ad3f2a32d5f9a5ceab7490b0afcb161/client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java#L173)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

curious: is this removed on purpose? 
</blockquote></details>

It was removed, because "This is used to add / remove state related style names from the widget." - I don't want add the styles to the widget as well. See the client side test, where I check that the CheckBoxElement doesn't have the styles from the children elements.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: all files reviewed, 1 unresolved discussion (waiting on @knoobie)

___
*[client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java, line 173 at r1](https://reviewable.io/reviews/vaadin/framework/11372#-LU0EsEiBlRQOitTdQNC:-LU0M5QgEVgpAvPXE1D8:bdlv7ln) ([raw file](https://github.com/vaadin/framework/blob/883142b00ad3f2a32d5f9a5ceab7490b0afcb161/client/src/main/java/com/vaadin/client/ui/checkbox/CheckBoxConnector.java#L173)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

It was removed, because "This is used to add / remove state related style names from the widget." - I don't want add the styles to the widget as well. See the client side test, where I check that the CheckBoxElement doesn't have the styles from the children elements. 
</blockquote></details>

Thanks for letting me know. I think this patch is ready to go.  Thanks for the contribution. :-)

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11372)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
