### PR TITLE
Added loop and preload attributes for media elements, fixed null poster

### LINKED ISSUE #4409: com.vaadin.ui.Audio always preloads media, hanging ui
**Originally by _rsutton@asteriskit.com.au_**

___
need to be able to set the preload="none" option for the Audio component.

the ui becomes unresponsive while the Audio control downloads the entire media preemptively.

___
 Imported from https://dev.vaadin.com/ issue #12516

### LINKED ISSUE #5178: Add missing HTML5-Attributes for Video Component
**Originally by _buuzta_**

___
In the Video Component Class (or AbstractMedia.class) are missing attributes for the HTML5 video-tag.

- preload (auto, metadata or none) [Specifies if and how the author thinks the video should be loaded when the page loads]
* loop (true or false) [Specifies that the video will start over again, every time it is finished]

IMHO the preload attribute might be very important for many of the developers.

___
 Imported from https://dev.vaadin.com/ issue #13745

### LINKED ISSUE #7261: Video tag's poster attribute should not be rendered when a poster resource is not given
**Originally by _myucel_**

___
When a poster resource is not given to Video component, poster="null" is rendered in html 5 video tag. It causes unwanted requests to server such as /app/null. Since poster attribute is optional, I think, it shouldn't be rendered whenever it isn't provided explicitly.

___
 Imported from https://dev.vaadin.com/ issue #19178

### PR DESCRIPTION
**Pull request by kvalev**
Fixes #7261
Fixes #5178
Fixes #4409

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9161)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractMedia.java, line 210 at r1](https://reviewable.io:443/reviews/vaadin/framework/9161#-Kj7e-zt_WSGoWHqiQo3:-Kj7e-zt_WSGoWHqiQo4:b-mxgmkq) ([raw file](https://github.com/vaadin/framework/blob/b6e674d002b57883863f2a29596c54ec6bf4c3f9/server/src/main/java/com/vaadin/ui/AbstractMedia.java#L210)):*
> String preload

Could this be changed to an enum so that only valid values could be set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9161)*

**Comment by kvalev** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractMedia.java, line 210 at r1](https://reviewable.io:443/reviews/vaadin/framework/9161#-Kj7e-zt_WSGoWHqiQo3:-Kj9h8G3b5UEQLuDdKoJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b6e674d002b57883863f2a29596c54ec6bf4c3f9/server/src/main/java/com/vaadin/ui/AbstractMedia.java#L210)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> String preload

Could this be changed to an enum so that only valid values could be set?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9161)*

**Comment by kvalev** [comment]
Can you please take a look at let me know whether the PR is ok.

**Comment by hesara** [comment]
Sorry for the delay. This looks mostly ok (after a merge of the current branch contents), though we'd like to add some since tags to the javadoc and then port this also for master. If you can select the checkbox that allows project maintainers to make edits to the PR, we can take this from here.

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/PreloadMode.java, line 20 at r2](https://reviewable.io:443/reviews/vaadin/framework/9161#-Kqwj_YiZxxiZjpJUXNx:-Kqwj_YiZxxiZjpJUXNy:bjm524h) ([raw file](https://github.com/vaadin/framework/blob/8f3db2d7a382e5d6f6c158e9bcc04d6751a1fd9d/shared/src/main/java/com/vaadin/shared/ui/PreloadMode.java#L20)):*
> ```Java
> /**
>  * Enumeration that provides a hint to the browser how media should be preloaded.
>  */
> ```

this could either mention in the javadoc that the names must match the values used on the client, or provide a method to get the value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9161#-:-Kqwjjw4njFFYjHgQVxL:b-llmmkl)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9161#-:-Kr0e6BitcImY4TvC2y1:bnfp4nl)*

**Comment by kvalev** [comment]
Thanks for taking over and merging it.

**Pull request merged**
