### PR TITLE
Move TestBench API to the correct package

### LINKED ISSUE #9241: DateTimeFieldElement is missing
There is no `DateTimeFieldElement` in the TestBench API for Framework 8. For some reason the `uitest` module does contain one.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #9241

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9249)

### CODE REVIEW

**Comment by alvarezguille** [comment]
:lgtm_strong: 
I didn't want to mark files as reviewed to avoid confusion with repo owners

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9249#-:-Kjc39Iz4dZwLqUplC_K:b-66yusu)*

**Comment by ahie** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/TestDateField.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9249#-KjgqpVazw4_DNbC7ByT:-KjgqpVblxipuQvc3MdP:b-okktnx) ([raw file](https://github.com/vaadin/framework/blob/f10c0dcc7ebbafccbf0e037432dc2c75949e8e67/uitest/src/main/java/com/vaadin/tests/components/TestDateField.java#L26)):*
> ```Java
>  *
>  */
> public class TestDateField extends AbstractLocalDateField {
> ```

Is this change related?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9249)*

**Comment by Artur-** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/TestDateField.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9249#-KjgqpVazw4_DNbC7ByT:-Kjgs3_QXN7JSd-xG0S_:b-cmr8i8) ([raw file](https://github.com/vaadin/framework/blob/f10c0dcc7ebbafccbf0e037432dc2c75949e8e67/uitest/src/main/java/com/vaadin/tests/components/TestDateField.java#L26)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Is this change related?
</blockquote></details>

Yes, otherwise TestDateField is neither a `DateField`nor a `InlineDateField` but something undefined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9249)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9249#-:-KjgtwlppIpRhPx6fPKh:bnfp4nl)*

**Pull request merged**
