### PR TITLE
Improve expand and collapse of items in TreeGrid

### PR DESCRIPTION
**Pull request by ahie**
HierarchyMapper now correctly keeps expanded nodes expanded
if their parent is collapsed.

Adds API to collapse and expand multiple items from the
server, reducing the amount of round trips with multiple
item expands and collapses.

Fixes a race condition when expanding multiple items.
Only one expand or collapse request should be sent from
the client before waiting for a response, otherwise the
indexing in subsequent requests will be incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9159)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieaAtA94orT6Uf45Vz:-KieaAtA94orT6Uf45W-:b-c9iesn) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L283)):*
> testBench().disableWaitForVaadin();

Test ignored because this doesn't seem to have any effect. The following expands and collapses still wait for the round trip to happen.  Any pointers here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by tsuoanttila** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieaAtA94orT6Uf45Vz:-KiebJdBF5v-pWfx74Wl:b3os7o8) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L283)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> testBench().disableWaitForVaadin();

Test ignored because this doesn't seem to have any effect. The following expands and collapses still wait for the round trip to happen.  Any pointers here?
</blockquote></details>

Can you make the server-side UI delay the response by a couple of seconds? I think we have some examples of delayed responses from the server somewhere in our tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by hesara** [comment]
Reviewed 5 of 10 files at r1.
Review status: 5 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 460 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieiUQAoEdpl2BeZjhF:-KieiUQAoEdpl2BeZjhG:b9w615a) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/ui/TreeGrid.java#L460)):*
> ```Java
> 
>     /**
>      * Expands the given items.
> ```

I would expect expanding/collapsing a single item to be a common case. Would it make sense to use varargs instead of a Collection, which would give a compact syntax for single item operations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by hesara** [comment]
Reviewed 1 of 10 files at r1.
Review status: 6 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 179 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-Kihkd6Yl6Jt1WWzu5cr:-Kihkd6Yl6Jt1WWzu5cs:bvsnf7w) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L179)):*
> ```Java
>             @Override
>             public void setCollapsed(String key) {
>                 rowKeysPendingExpand.remove(key);
> ```

No other actions needed? No risk of race conditions?

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-Kihl2t-8zmSQXcj6VKU:-Kihl2t-8zmSQXcj6VKV:babctj5) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L206)):*
> ```Java
>             @Override
>             public void dataRemoved(int firstRowIndex, int numberOfRows) {
>                 rowAwaitingCollapse = false;
> ```

these flags are somewhat unclear to me based on what happens here and below - maybe add some comments, or use an enum for the state if not all the combinations can happen?

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihlOn6LgRp7meuHbEQ:-KihlOn6LgRp7meuHbER:b-pvzzhv) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L258)):*
> ```Java
>     private void setCollapsed(int rowIndex, boolean collapsed,
>             boolean userOriginated) {
>         if (isAwaitingRows()) {
> ```

No RPC, no event? Are these server initiated operations only?

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihmLAzaZ77Eao-MMRB:-KihmLAzaZ77Eao-MMRC:blhwnbt) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L165)):*
> ```Java
>         Stream<TreeLevelQuery> levelQueries = mapper.splitRangeToLevelQueries(
>                 requestedRows.getStart(), requestedRows.getEnd() - 1);
>         List<TreeLevelQuery> collected = levelQueries
> ```

making a defensive copy of a stream??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by ahie** [comment]
Review status: 5 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 179 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-Kihkd6Yl6Jt1WWzu5cr:-Kii3yYU7L7OyR5g8eK4:b-owg6rt) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L179)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

No other actions needed? No risk of race conditions?
</blockquote></details>

It might still be possible that there is an expand request for this key already going out. Added a check to the server that ignores such requests (`HierarchicalDataCommunicator.doExpand` ignores server originated expands that are no longer in its set of nodes to expand).

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-Kihl2t-8zmSQXcj6VKU:-KihyRNZuJ6YbV4ockZT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L206)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

these flags are somewhat unclear to me based on what happens here and below - maybe add some comments, or use an enum for the state if not all the combinations can happen?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihlOn6LgRp7meuHbEQ:-KihyUtTi1s2rM--wS4g:b-xk4rtd) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L258)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

No RPC, no event? Are these server initiated operations only?
</blockquote></details>

For both server and client. The given rowIndex will potentially be incorrect on the server if this is called multiple times before a response. For example indices 1 and 2 are expanded simultaneously, which instructs the server to insert the children at indices 2 and 3 respectively.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihmLAzaZ77Eao-MMRB:-KihudKeBmtPcQ2sc-qL:bwup3zp) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L165)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

making a defensive copy of a stream??
</blockquote></details>

These were for easier debugging of the stream's contents. Removed.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 460 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieiUQAoEdpl2BeZjhF:-Kii0TVem_lSaguFWS-V:b-aw0vl9) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/ui/TreeGrid.java#L460)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I would expect expanding/collapsing a single item to be a common case. Would it make sense to use varargs instead of a Collection, which would give a compact syntax for single item operations?
</blockquote></details>

Also has a one item overload. A varargs overload has the downside that if you want to expand/collapse a collection of items it would require the caller to first convert the collection to an array, and having all three seems excessive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by hesara** [comment]
Reviewed 1 of 10 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihlOn6LgRp7meuHbEQ:-KioL_U34JNEijwSeGS3:b-374ybt) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L258)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

For both server and client. The given rowIndex will potentially be incorrect on the server if this is called multiple times before a response. For example indices 1 and 2 are expanded simultaneously, which instructs the server to insert the children at indices 2 and 3 respectively.
</blockquote></details>

now, will not react to user input before the pending operations complete - might not be a real issue in many cases, but could add a comment to make that explicit

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 379 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioLw99j7BFsH09DXAe:-KioLw99j7BFsH09DXAf:b-1hpvnz) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L379)):*
> ```Java
> 
>     private void checkExpand(int firstRowIndex, int numberOfRows) {
>         if (rowKeysPendingExpand.isEmpty() || isAwaitingRowChange()) {
> ```

could add a comment about not reacting while pending changes

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 146 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioK58fapLbdG6-XhfH:-KioK58fapLbdG6-XhfI:bh13lrc) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L146)):*
> ```Java
>     private final TreeSet<TreeNode> nodes = new TreeSet<>();
> 
>     /** Nodes that have been previously expanded. */
> ```

could document this a bit more

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 350 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioNEJpOMI-LgV_9x6L:-KioNEJpOMI-LgV_9x6M:b-v9ahu0) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L350)):*
> ```Java
> 
>         Set<TreeNode> subTreeNodes = nodes
>                 .tailSet(collapsedNode).stream().filter(node -> collapsedNode
> ```

Could stop after the first false to avoid iterating through all other trees on the same level as the one of interest.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 460 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieiUQAoEdpl2BeZjhF:-KioO_eVIFjAHBh4dGQ5:bfd8xtt) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/ui/TreeGrid.java#L460)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Also has a one item overload. A varargs overload has the downside that if you want to expand/collapse a collection of items it would require the caller to first convert the collection to an array, and having all three seems excessive.
</blockquote></details>

(the two variants could be varargs and collection, which would implicitly also work for a single item)

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 456 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioOOt9WFRK6NmUcdr9:-KioOOt9WFRK6NmUcdrA:b-8eukqt) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/ui/TreeGrid.java#L456)):*
> ```Java
>         getDataCommunicator().setPendingExpand(item).ifPresent(key -> {
>             getRpcProxy(TreeGridClientRpc.class)
>                     .setExpanded(Arrays.asList(key));
> ```

could be Collections.singletonList(key), likewise below

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 493 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioPGueJrUADtWcgP5Z:-KioPGuflKg8hwwMv2cF:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/ui/TreeGrid.java#L493)):*
> ```Java
>         getDataCommunicator().collapseItem(item).ifPresent(key -> {
>             getRpcProxy(TreeGridClientRpc.class)
>                     .setCollapsed(Arrays.asList(key));
> ```

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by ahie** [comment]
Review status: 8 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KihlOn6LgRp7meuHbEQ:-KioY6f_amCjSAJ-2jsj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L258)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

now, will not react to user input before the pending operations complete - might not be a real issue in many cases, but could add a comment to make that explicit
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 379 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioLw99j7BFsH09DXAe:-KioY538oI2sAlLWW03E:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L379)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could add a comment about not reacting while pending changes
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 146 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioK58fapLbdG6-XhfH:-KioUUcSFzMAlDwgJW22:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L146)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could document this a bit more
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 350 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioNEJpOMI-LgV_9x6L:-KioVcAaUVG4pDgMzHtx:b-sbisri) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L350)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could stop after the first false to avoid iterating through all other trees on the same level as the one of interest.
</blockquote></details>

The ordering with respect to end indices is not guaranteed, so this cannot be done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 460 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieiUQAoEdpl2BeZjhF:-KioQjGAWxEMg63VedBr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/server/src/main/java/com/vaadin/ui/TreeGrid.java#L460)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(the two variants could be varargs and collection, which would implicitly also work for a single item)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 456 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioOOt9WFRK6NmUcdr9:-KioVt59TVpskLZDsdq0:b-uq04a6) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/ui/TreeGrid.java#L456)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could be Collections.singletonList(key), likewise below
</blockquote></details>

Now varargs, which delegated to the method with `Collection` signature.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 493 at r2](https://reviewable.io:443/reviews/vaadin/framework/9159#-KioPGueJrUADtWcgP5Z:-KioW0Cv5vi9LtulY81y:b-a1r2si) ([raw file](https://github.com/vaadin/framework/blob/f2bf6ac3397f23569cd7cef242b426e51455f878/server/src/main/java/com/vaadin/ui/TreeGrid.java#L493)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see above
</blockquote></details>

See comment for `expand`.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9159#-KieaAtA94orT6Uf45Vz:-Kiog5wI5u2MtKJm7tEm:bmpj0m9) ([raw file](https://github.com/vaadin/framework/blob/ebadf5e0cd711844217c8e150de8a9ce47b9c7ae/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L283)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Can you make the server-side UI delay the response by a couple of seconds? I think we have some examples of delayed responses from the server somewhere in our tests.
</blockquote></details>

The delayed data provider approach works but only for the first part of the test, since collapses don't require anything from the data provider. Now toggling the expands by executing javascript. Also split this test out to its own class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 484 at r3](https://reviewable.io:443/reviews/vaadin/framework/9159#-Kj6x5UDpDmuNoiijXCR:-Kj6x5UDpDmuNoiijXCS:b12bgri) ([raw file](https://github.com/vaadin/framework/blob/c920546d0f91b6f268100fc06cbb6204e2e18106/server/src/main/java/com/vaadin/ui/TreeGrid.java#L484)):*
> ```Java
>      *
>      * @param items
>      *            the collection of items to collapse
> ```

(not really a "collection" in the sense of Collection, but I guess this is reasonably clear)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9159)*

**Pull request merged**
