### PR TITLE
Reflect latest Tree API and styling changes to the documentation

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9334)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-tree.asciidoc, line 160 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGd-zhxLIIWwtzwvmT:-KkGd-zhxLIIWwtzwvmU:bju2uic) ([raw file](https://github.com/vaadin/framework/blob/4b92c9dffd8506945524de604deea7e555c85118/documentation/components/components-tree.asciidoc#L160)):*
> ```AsciiDoc
> [source, css]
> ----
> .v-tree8 {
> ```

@tsuoanttila please take another look at these

---

*[documentation/components/components-tree.asciidoc, line 201 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGck7wXQqz5AFH7JYG:-KkGck7wXQqz5AFH7JYH:b-5pl6c6) ([raw file](https://github.com/vaadin/framework/blob/46422df01b69f1b6a8c2780257a6968a6a5cd9df/documentation/components/components-tree.asciidoc#L201)):*
> ```AsciiDoc
> ----
> 
> The style names are prefixed with `v-tree-node-caption-`.
> ```

could have corresponding example for what this used to do, with the "leaf" style used in the new example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-tree.asciidoc, line 201 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGck7wXQqz5AFH7JYG:-KkGeCJ20o0M7ZokNSHN:bz0fil2) ([raw file](https://github.com/vaadin/framework/blob/46422df01b69f1b6a8c2780257a6968a6a5cd9df/documentation/components/components-tree.asciidoc#L201)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could have corresponding example for what this used to do, with the "leaf" style used in the new example
</blockquote></details>

It looks like advanced user topic, and advanced users most probably know  how to use styles. And there is an example in the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by tsuoanttila** [comment]
*[documentation/components/components-tree.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGp1d4_Oef_8KKm_9_:-KkGp1d5sLxOgWkqqRt4:b-yx9q1l) ([raw file](https://github.com/vaadin/framework/blob/4b92c9dffd8506945524de604deea7e555c85118/documentation/components/components-tree.asciidoc#L173)):*
> ```AsciiDoc
>     }
>   }
>   .v-grid-horizontal-scrollbar-deco { }
> ```

why would this be .v-grid ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by tsuoanttila** [comment]
*[documentation/components/components-tree.asciidoc, line 160 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGd-zhxLIIWwtzwvmT:-KkGpP1gLxs_TxrFxmQ1:b-nmvo9u) ([raw file](https://github.com/vaadin/framework/blob/4b92c9dffd8506945524de604deea7e555c85118/documentation/components/components-tree.asciidoc#L160)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@tsuoanttila please take another look at these
</blockquote></details>

Looks ok besides the one comment I had.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-tree.asciidoc, line 201 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGck7wXQqz5AFH7JYG:-KkKHA0ecBkj-fjBLZjz:b-2nkeev) ([raw file](https://github.com/vaadin/framework/blob/46422df01b69f1b6a8c2780257a6968a6a5cd9df/documentation/components/components-tree.asciidoc#L201)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

It looks like advanced user topic, and advanced users most probably know  how to use styles. And there is an example in the tests.
</blockquote></details>

I think a user who reads this does not necessarily know it, and definitely would get things done faster if there is an example that shows on which of the many above mentioned style names is the style added. However, not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGp1d4_Oef_8KKm_9_:-KkKNe8yManewUttblwr:b-yqw2l1) ([raw file](https://github.com/vaadin/framework/blob/4b92c9dffd8506945524de604deea7e555c85118/documentation/components/components-tree.asciidoc#L173)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why would this be .v-grid ?
</blockquote></details>

I've verified, and it's `v-tree8-horizontal-scrollbar-deco` actually.
The wholeline is removed - that is too deep into details IMHO.

---

*[documentation/components/components-tree.asciidoc, line 201 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGck7wXQqz5AFH7JYG:-KkKO2XgmR5LnwITpVS-:b-sl8jhk) ([raw file](https://github.com/vaadin/framework/blob/46422df01b69f1b6a8c2780257a6968a6a5cd9df/documentation/components/components-tree.asciidoc#L201)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I think a user who reads this does not necessarily know it, and definitely would get things done faster if there is an example that shows on which of the many above mentioned style names is the style added. However, not a blocker.
</blockquote></details>

Very basic example CSS added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9334#-KkGp1d4_Oef_8KKm_9_:-KkKXxmKz3UNTHELuAXd:b-pbdqz3) ([raw file](https://github.com/vaadin/framework/blob/4b92c9dffd8506945524de604deea7e555c85118/documentation/components/components-tree.asciidoc#L173)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I've verified, and it's `v-tree8-horizontal-scrollbar-deco` actually.
The wholeline is removed - that is too deep into details IMHO.
</blockquote></details>

Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9334)*

**Pull request merged**
