### PR TITLE
Introduce Searcher

### PR DESCRIPTION
**Pull request by Legioth**
A searcher is a stateful data provider wrapper that filters data by one
or many configurable search items. This helps avoid the pattern with
using Supplier<ActualFilterType> in data providers to support filtering
that originates from outside the listing component.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8123)

### CODE REVIEW

**Comment by Legioth** [comment]
https://github.com/vaadin/framework8-demo/pull/75 shows the impact of this patch on application code

**Comment by hesara** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_YW41CaDiV_38kdA9v:-K_YW41CaDiV_38kdA9w:b-ljkz3m) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L28)):*
> ```Java
> 
> /**
>  * {@link Searcher} supporting multiple search filters and further filtering
> ```

IIRC some tools use the first sentence/paragraph of javadoc as a plain text summary and might not be able to handle links etc. in it.

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z7QjtVr0TcLG9D-lb:-K_Z7QjtVr0TcLG9D-lc:bbwjtki) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L43)):*
> ```Java
>         AppendableFilterDataProviderWrapper<T, F> implements Searcher<T, F, F> {
> 
>     private Set<F> filters = new HashSet<>();
> ```

Unordered? Non-deterministic? Could the order matter e.g, by some filters crashing for some input that other filters would eliminate?

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ZBbOJIMURdINmszLC:-K_ZBbOJIMURdINmszLD:bpwykit) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L84)):*
> ```Java
>             clearFilters();
>         } else {
>             if (filters.size() == 1
> ```

optimization for a single special case - should we instead use the more generic "if (filters.contains(filter))"?

---

*[server/src/main/java/com/vaadin/data/provider/Searcher.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z15MIci4UyGV5ki5s:-K_Z15MJV-ChIAD_6GLm:bn6j80t) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/Searcher.java#L26)):*
> ```Java
>  * @param <T>
>  *            the type of data items provided by this data provider
>  * @param <F>
> ```

the last two parameters and the two kinds of filtering are rather unclear - perhaps need to add an explanatory paragraph above

---

*[server/src/main/java/com/vaadin/data/provider/Searcher.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1LsfrzmPA1Mn2cjY:-K_Z1Lsgh38FJgU2-S4c:b-vtbrtt) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/Searcher.java#L35)):*
> ```Java
>  *            data provider might something else.
>  */
> public interface Searcher<T, F, S> extends DataProvider<T, F> {
> ```

not quite sure about naming of the class and the method - would like another opinion on that

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1WIv65H9hlvi8jHn:-K_Z1WIv65H9hlvi8jHo:b-unzvlu) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L22)):*
> ```Java
> 
> /**
>  * {@link Searcher} implementation that doesn't support further filtering in
> ```

see comment about javadoc links and the first sentence/paragraph above

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1kM9q_WcPsnzf4f8:-K_Z1kM9q_WcPsnzf4f9:bth8sed) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L32)):*
> ```Java
>  *            data type
>  * @param <F>
>  *            filter type. Please note that this is only the type of
> ```

(this comment seems technically correct, but its full contents might not be that relevant for the user - probably all that matters is that it cannot be filtered further)

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z4QQMV2vb_OGws2z8:-K_Z4QQN0ihNS_479b9d:b7oeing) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L54)):*
> ```Java
>     @Override
>     public void searchBy(F filter) {
>         if (Objects.equals(this.filter, filter)) {
> ```

I can see this as an optimization, but if you use equals instead of "==" then maybe this should have a warning about the effective constraints on filter equality.

---

*[server/src/test/java/com/vaadin/data/provider/AppendableSearcherTest.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ZCsHwVGL39p35bYDA:-K_ZCsHwVGL39p35bYDB:b-ptytc0) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/test/java/com/vaadin/data/provider/AppendableSearcherTest.java#L78)):*
> ```Java
> 
>         searcher.searchBy(CONTAINS_O);
>         Assert.assertEquals("Re-setting the same filter should fire events", 1,
> ```

"should not"?

---

*[server/src/test/java/com/vaadin/data/provider/SingleFilterSearcherTest.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z57rWhs8f7Lkvg7Ov:-K_Z57rWhs8f7Lkvg7Ow:b-jwgdmq) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/test/java/com/vaadin/data/provider/SingleFilterSearcherTest.java#L70)):*
> ```Java
> 
>         searcher.searchBy(filter);
>         Assert.assertEquals("Re-setting the same filter should fire events", 1,
> ```

Is this text correct? Or should it be negated?

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z5bvVmNIZ-h0unnTF:-K_Z5bvVmNIZ-h0unnTG:b6pqpuc) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L34)):*
> ```Java
> import com.vaadin.ui.TextField;
> 
> public class SearcherUI extends AbstractTestUI {
> ```

Is there any test that uses the UI?

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z71bVlZTUn1qLd1d8:-K_Z71bWVkqz2tyr6aA0:bfkid45) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L74)):*
> ```Java
>         grid.addColumn(Person::getLastName).setCaption("Last name");
> 
>         ComboBox<Person> comboBox = new ComboBox<>("Combo box");
> ```

filtered always by the form info + optionally first name based on text in combo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8123)*

**Comment by Legioth** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_YW41CaDiV_38kdA9v:-Ka2BX3xab4xzAuFL0va:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

IIRC some tools use the first sentence/paragraph of javadoc as a plain text summary and might not be able to handle links etc. in it.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z7QjtVr0TcLG9D-lb:-Ka2BiQ4cThRIpqfiZsI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L43)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Unordered? Non-deterministic? Could the order matter e.g, by some filters crashing for some input that other filters would eliminate?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ZBbOJIMURdINmszLC:-Ka2DvEw-A12ofBPlGIF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/AppendableSearcher.java#L84)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

optimization for a single special case - should we instead use the more generic "if (filters.contains(filter))"?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/Searcher.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z15MIci4UyGV5ki5s:-Ka2P73KUK7jQWIYuUT-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/Searcher.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the last two parameters and the two kinds of filtering are rather unclear - perhaps need to add an explanatory paragraph above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/Searcher.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1LsfrzmPA1Mn2cjY:-Ka2DzAMXp6-OcmfIll1:b-fb3h5i) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/Searcher.java#L35)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not quite sure about naming of the class and the method - would like another opinion on that
</blockquote></details>

Renamed based various discussions

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1WIv65H9hlvi8jHn:-Ka2HlFNKvGgDZanezDz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment about javadoc links and the first sentence/paragraph above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z1kM9q_WcPsnzf4f8:-Ka2I1mQP01Y4wa29c7E:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L32)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this comment seems technically correct, but its full contents might not be that relevant for the user - probably all that matters is that it cannot be filtered further)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z4QQMV2vb_OGws2z8:-Ka2IaBHyQ5mUFX8q-3F:b-4vbj21) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/main/java/com/vaadin/data/provider/SingleFilterSearcher.java#L54)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I can see this as an optimization, but if you use equals instead of "==" then maybe this should have a warning about the effective constraints on filter equality.
</blockquote></details>

Done (in the javadocs of the parent type that defines this method).

---

*[server/src/test/java/com/vaadin/data/provider/AppendableSearcherTest.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ZCsHwVGL39p35bYDA:-Ka2Iv8z-2edlFW15-WW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/test/java/com/vaadin/data/provider/AppendableSearcherTest.java#L78)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"should not"?
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/SingleFilterSearcherTest.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z57rWhs8f7Lkvg7Ov:-Ka2J1Qbg8pgILrJnAPA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/server/src/test/java/com/vaadin/data/provider/SingleFilterSearcherTest.java#L70)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this text correct? Or should it be negated?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z5bvVmNIZ-h0unnTF:-Ka2J6Wrro2GDhCmNgH0:bsj6de2) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is there any test that uses the UI?
</blockquote></details>

No test. This is mainly here to show how the functionality is used. I'm confident that the the unit tests are enough to catch any regressions.

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ToZ4bz4f9fkfkT61h-r1-53:-Ka2Js7Xa7iPwh514hWq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L53)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Remove useless curly braces around statement and then remove useless return keyword [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1602)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_ToZ4bz4f9fkfkT61h-r1-60:-Ka2LASOvfdMw869SOeY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L60)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Remove useless curly braces around statement and then remove useless return keyword [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1602)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework/8123#-K_Z71bVlZTUn1qLd1d8:-Ka2L9K_9OGCqKns-Xvh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dabd7cf025a0a66b7894d9c7f7e43e4eedf55966/uitest/src/main/java/com/vaadin/tests/data/SearcherUI.java#L74)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

filtered always by the form info + optionally first name based on text in combo?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8123)*

**Comment by Legioth** [comment]
Review status: 0 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8123#-KaDREypxAUm8wFLnxuN:-KaDREyqDe0H0aMEYxzg:byya5cy) (no related file):*
This might not make sense with the new design after all, so no point in continuing with the review right now. I'll still leave this open if it turns out we want to continue along this route after all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8123)*

**Comment by Legioth** [comment]
Replaced by https://github.com/vaadin/framework/pull/8280

**Pull request closed without merging**
