### PR TITLE
Fix colorPicker tests

### PR DESCRIPTION
**Pull request by ZheSun88**
In IE11, the click-layer needs longer time to load.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11312)

### CODE REVIEW

**Comment by anasmi** [comment]
I have nothing against the change, but could we make it maybe 500ms? 2s is a lot of waiting time.
If it still fails with 500ms, then we can go with 2s.

**Comment by anasmi** [comment]
___
*[uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerUserColorChangeTest.java, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11312#-LSJ8Ing0mGWV0GJT2Ra:-LSJ8Ing0mGWV0GJT2Rb:bvfdh4m) ([raw file](https://github.com/vaadin/framework/blob/259c14e6228d46945fdb1a69e3420ab1520c2059/uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerUserColorChangeTest.java#L17)):*
> ```Java
>         // Open colorPicker
>         findElement(By.className("v-button-v-colorpicker ")).click();
>         sleep(2000);
> ```

Let's try smaller time first. Test runs ok, for me locally, so might be 2s is too much in this case, but I agree that we should increase time anyway

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11312)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerUserColorChangeTest.java, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11312#-LSJ8Ing0mGWV0GJT2Ra:-LSK89T0B7k43Yrz-WUz:br2d9ky) ([raw file](https://github.com/vaadin/framework/blob/259c14e6228d46945fdb1a69e3420ab1520c2059/uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerUserColorChangeTest.java#L17)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Let's try smaller time first. Test runs ok, for me locally, so might be 2s is too much in this case, but I agree that we should increase time anyway 
</blockquote></details>

okay, let use 500ms.

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
