### PR TITLE
Correctly write margin info for FormLayout into design files

### LINKED ISSUE #8800: Declarative for FormLayout with no margin is incorrect
The following test case works with Framework 7 but fails in Framework 8, since the default margins changed. The problem is in detecting the default margin and not writing the changes to declarative.

```
@Test
public void formLayoutMarginSerializationTest() throws IOException {
   ByteArrayOutputStream baos = new ByteArrayOutputStream();
   FormLayout formLayout = new FormLayout();
   formLayout.setMargin(false);
   Design.write(formLayout, baos);
   FormLayout serializedFormLayout = (FormLayout) Design.read(new ByteArrayInputStream(baos.toByteArray()));
   Assert.assertEquals(formLayout.getMargin(), serializedFormLayout.getMargin());
}
```

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8800

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8804)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractLayout.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8804#-KfAn82MXXarLlsQstNp:-KfAn82MXXarLlsQstNq:b-am6q0z) ([raw file](https://github.com/vaadin/framework/blob/b2f4845213b9dfea78f5c3621c96f8666185f9b2/server/src/main/java/com/vaadin/ui/AbstractLayout.java#L108)):*
> ```Java
>     protected void writeMargin(Element design, MarginInfo margin,
>             MarginInfo defMargin, DesignContext context) {
>         if (defMargin.getBitMask() == margin.getBitMask()) {
> ```

Are there any backwards compatibility issues with the changed behavior?

---

*[server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8804#-KfAn-_2HhYsyGNzCXCb:-KfAn-_2HhYsyGNzCXCc:b-xi6zbd) ([raw file](https://github.com/vaadin/framework/blob/b2f4845213b9dfea78f5c3621c96f8666185f9b2/server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java#L71)):*
> ```Java
>                     layout.getMargin());
> 
>             System.out.println("Write " + marginToTest);
> ```

Are these sysouts still here intentionally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractLayout.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8804#-KfAn82MXXarLlsQstNp:-KfAoQzl6Id9MN7m6pr9:bdu06uh) ([raw file](https://github.com/vaadin/framework/blob/b2f4845213b9dfea78f5c3621c96f8666185f9b2/server/src/main/java/com/vaadin/ui/AbstractLayout.java#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Are there any backwards compatibility issues with the changed behavior?
</blockquote></details>

There should not be any changed behavior? The old code assumed that the default margins were either "all on" or "all of", which is not the case for `FormLayout`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Comment by Artur-** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8804#-KfAn-_2HhYsyGNzCXCb:-KfAodxxzmgQTbdDrxOD:b32w12) ([raw file](https://github.com/vaadin/framework/blob/b2f4845213b9dfea78f5c3621c96f8666185f9b2/server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java#L71)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Are these sysouts still here intentionally?
</blockquote></details>

No

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Comment by Artur-** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8804#-KfAn-_2HhYsyGNzCXCb:-KfLJuRIxA6ITRjTfHJ9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b2f4845213b9dfea78f5c3621c96f8666185f9b2/server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java#L71)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

No
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8804)*

**Pull request merged**
