### PR TITLE
Notification to support addCloseListener (Fixes #888)

### LINKED ISSUE #888: Add clicklistener to notifications
**Originally by @Artur-**

___
In some cases it would be very useful to be able to show a notification, e.g. tray notification, and react if the user clicks on it. An example would be a messaging (e.g. mail) application where a tray notification is shown when a message arrives and if the user clicks on the notification the full message is shown in a popup. No event would be fired if the notification fades away by itself.

___
 Imported from https://dev.vaadin.com/ issue #3638

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10027)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
After a quick glance at the change, it seems to be going the right way. This is going to need a note in release notes (`all/src/main/templates/release-notes.html`) in the incompatible changes section. Keep up the good work!

There seems to be some missed layouting call in the test UI `VaadinIconSet`. Please check that one out to make sure it works, if you have trouble figuring out the issue with the layouting, we can help you with that.

There was also a timeout in your new test when waiting for expected condition:
```
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.vaadin.tests.extensions.NotificationCloseListenerTest$1@1d14d7d6 (tried for 10 second(s) with 500 MILLISECONDS interval)
...
at com.vaadin.tests.extensions.NotificationCloseListenerTest.closeListnerCalled(NotificationCloseListenerTest.java:32)
```

**Comment by tsuoanttila** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuTpJ2g39UAQC_x-bYx:-KuTpJ2g39UAQC_x-bYy:b-ta0h6v) ([raw file](https://github.com/vaadin/framework/blob/7c9ed1c8b25942e3845498c7525e818ffc3cae5e/uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java#L29)):*
> closeListnerCalled
Typo in test name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by hesara** [comment]
Reviewed 8 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VNotification.java, line 485 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUEKCDibLsABZ1TeFa:-KuUEKCDibLsABZ1TeFb:b-fx3ern) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/client/src/main/java/com/vaadin/client/ui/VNotification.java#L485)):*
> ```Java
>     public static VNotification showNotification(ApplicationConnection client,
>             boolean onlyPlainText, String iconUri, String caption,
>             String description, String style, int pos, int delay) {
> ```

It would be nice to have javadoc for this now, describing the parameters and e.g. whether null values are allowed or not, or what are the meanings of the pos values and the units of delay. Perhaps they can also be documented in the state class.

I'd also prefer "message" over "description" as the word "description" has mostly been used for tooltips in the framework, but that is not a blocker.

---

*[client/src/main/java/com/vaadin/client/ui/notification/NotificationConnector.java, line 54 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUF6jCBjOS4_D3XDbU:-KuUF6jCBjOS4_D3XDbV:bfulv6v) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/client/src/main/java/com/vaadin/client/ui/notification/NotificationConnector.java#L54)):*
> ```Java
> 
>         n.addCloseHandler(new CloseHandler<PopupPanel>() {
>             
> ```

(empty line with extra whitespace, and extra trailing whitespace a few lines down - not a blocker)

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 394 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUKw7VffgjbdldQM6W:-KuUKw7Wl1cab1rHElNG:b-c4xxjg) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L394)):*
> ```Java
>     public void show(Page page) {
>         // TODO: is there a better way than creating a JavaScript?
>         extend(page.getJavaScript().getUI());
> ```

Currently not, but I think you could add Page.getUI() (with an empty since tag) as the information is already there anyway and seems to be of use.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 399 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuULOwq0xy0ZaAkaz9g:-KuULOwq0xy0ZaAkaz9h:btoukt4) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L399)):*
> ```Java
>     @Override
>     protected void extend(AbstractClientConnector target) {
>         getState().caption = getCaption();
> ```

This class could also use shared state as the master for these, avoiding duplication of the information.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 402 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUM6LKa1GuF5MIJOoj:-KuUM6LKa1GuF5MIJOok:bwdf2b) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L402)):*
> ```Java
>         getState().description = getDescription();
>         getState().onlyPlainText = !isHtmlContentAllowed();
>         if (getIcon() != null) {
> ```

Unlike JsonPaintTarget.addAttribute(String, Resource), this approach does not register ConnectorResource subclasses to the resource handler here, and thus I'm not quite sure if they work. To check, and if they don't, we should look for the correct pattern to do it so that unregistering also happens correctly.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 550 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUNG65Qp-J-WcK0z5p:-KuUNG65Qp-J-WcK0z5q:b-wl12ya) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L550)):*
> ```Java
>          *
>          * @param e
>          *            Event containing
> ```

"Event containing"?

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUJ_CbJ25UVe1DC1Yy:-KuUJ_CbJ25UVe1DC1Yz:bz2t2gd) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L28)):*
> ```Java
>  * @since
>  */
> public class NotificationState extends SharedState {
> ```

(it would be nice to have javadoc about allowed values etc. but not a blocker)

---

*[shared/src/main/java/com/vaadin/shared/ui/ui/UIConstants.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUKGibtgUvaVwvuQoQ:-KuUKGibtgUvaVwvuQoR:b-zhkxf9) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/shared/src/main/java/com/vaadin/shared/ui/ui/UIConstants.java#L28)):*
> ```Java
> 
>     @Deprecated
>     public static final String NOTIFICATION_HTML_CONTENT_NOT_ALLOWED = "useplain";
> ```

Should also this be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
Review status: 5 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VNotification.java, line 485 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUEKCDibLsABZ1TeFa:-KuUjk7aMJopWpvC5M9W:b-v98rh4) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/client/src/main/java/com/vaadin/client/ui/VNotification.java#L485)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

It would be nice to have javadoc for this now, describing the parameters and e.g. whether null values are allowed or not, or what are the meanings of the pos values and the units of delay. Perhaps they can also be documented in the state class.

I'd also prefer "message" over "description" as the word "description" has mostly been used for tooltips in the framework, but that is not a blocker.
</blockquote></details>

I thought javadoc is not important for client-side, as I think server-side is more important. Anyhow, it is done.

Actually on the client-side `message` was previously there, but on Notification it is `.set/getDescription`, and because of confusion, it is changed to `description`.

If you think otherwise, I believe we should deprecate Notification `set/getDescription()` and use `set/getMessage()` instead.

---

*[client/src/main/java/com/vaadin/client/ui/notification/NotificationConnector.java, line 54 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUF6jCBjOS4_D3XDbU:-KuUkcg8zKSCwza4yOCw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/client/src/main/java/com/vaadin/client/ui/notification/NotificationConnector.java#L54)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(empty line with extra whitespace, and extra trailing whitespace a few lines down - not a blocker)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 394 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUKw7VffgjbdldQM6W:-KuUkhvqoNpXgZd4avF1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L394)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Currently not, but I think you could add Page.getUI() (with an empty since tag) as the information is already there anyway and seems to be of use.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 399 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuULOwq0xy0ZaAkaz9g:-KuUkjRre3Lbtinw2S4I:buahgqj) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L399)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This class could also use shared state as the master for these, avoiding duplication of the information.
</blockquote></details>

I hope I correctly understood.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 402 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUM6LKa1GuF5MIJOoj:-KuUkoB0UWQjoG2GRWrc:bju0ky1) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L402)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Unlike JsonPaintTarget.addAttribute(String, Resource), this approach does not register ConnectorResource subclasses to the resource handler here, and thus I'm not quite sure if they work. To check, and if they don't, we should look for the correct pattern to do it so that unregistering also happens correctly.
</blockquote></details>

To be verified...

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 550 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUNG65Qp-J-WcK0z5p:-KuUkrqA0Qlaps4bpI64:bikr38r) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L550)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"Event containing"?
</blockquote></details>

Well, that's the effect of copy & paste from `Window.java`.

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUJ_CbJ25UVe1DC1Yy:-KuUlG9_GaJJH6l7tvms:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(it would be nice to have javadoc about allowed values etc. but not a blocker)
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/ui/UIConstants.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUKGibtgUvaVwvuQoQ:-KuUlDB6anrtDFN3uEdH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/shared/src/main/java/com/vaadin/shared/ui/ui/UIConstants.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should also this be removed?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuTpJ2g39UAQC_x-bYx:-KuUlEBb_wtXjyrWO8uu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c9ed1c8b25942e3845498c7525e818ffc3cae5e/uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java#L29)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> closeListnerCalled
Typo in test name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
@tsuoanttila: thanks for your input.

The test case is now fixed, I will look into the `VaadinIconSet`

**Comment by hesara** [comment]
Reviewed 3 of 7 files at r4, 1 of 1 files at r5.
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 399 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuULOwq0xy0ZaAkaz9g:-KuZxMZt9nYx6R-oIlvD:b7svlrn) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L399)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I hope I correctly understood.
</blockquote></details>

What I meant was not having the fields caption, description etc. at all in Notification, but rather converting getCaption() to return getState(false).caption; and setCaption(caption) to do getState().caption = caption; etc. We've tried to avoid duplication of information that is in the state, but many old classes have not been migrated fully or at all to use the newer communication mechanisms. It is already very nice that this patch eliminates another chunk of the old UIDL based communication.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 402 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUM6LKa1GuF5MIJOoj:-KuZxntkToaGWzd0rAyK:b-vrtq3g) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L402)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

To be verified...
</blockquote></details>

To be checked...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 402 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuUM6LKa1GuF5MIJOoj:-KuZzCk9BIxRe7MCj7Bd:bn062z7) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L402)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

To be checked...
</blockquote></details>

I have made a fix, and the icon works using the patch, however unregistering it is beyond my humble knowledge.

I assume UI gets unregistering automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
Review status: 8 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Notification.java, line 399 at r3](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuULOwq0xy0ZaAkaz9g:-Ku_6RW04TKUP_WyjWtQ:bkcdooy) ([raw file](https://github.com/vaadin/framework/blob/c72d2a5f2a24e7dac053d42055b752fe9ac0f6c4/server/src/main/java/com/vaadin/ui/Notification.java#L399)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What I meant was not having the fields caption, description etc. at all in Notification, but rather converting getCaption() to return getState(false).caption; and setCaption(caption) to do getState().caption = caption; etc. We've tried to avoid duplication of information that is in the state, but many old classes have not been migrated fully or at all to use the newer communication mechanisms. It is already very nice that this patch eliminates another chunk of the old UIDL based communication.
</blockquote></details>

I didn't know this pattern, just committed two changes, to share the Icon as a "Resource", I hope that finishes everything!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by hesara** [comment]
This is starting to look quite good - one more minor comment below and we should fix the VaadinIconSet test, which I think might be failing due to a bug in GridLayout rather than in this patch. Anyway, we need to resolve it one way or another before merging this patch as this would make validation builds fail.

---

Reviewed 2 of 7 files at r4, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 54 at r8](https://reviewable.io:443/reviews/vaadin/framework/10027#-Ku_Oyiin3cvfy2HEjAS:-Ku_Oyiin3cvfy2HEjAT:b9svi22) ([raw file](https://github.com/vaadin/framework/blob/e30a9c77d2026868dc7c9d463669100b5968035a/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L54)):*
> ```Java
>      * The ordinal of the {@link Position}.
>      */
>     public int position;
> ```

One more minor simplification that can be done: the enum Position is in the shared package and can actually be used directly here, so no need to map from Position to an ordinal and back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027#-:-Ku_PHwXLF-aLcrvm44M:b-6aj6hz)*

**Comment by hesara** [comment]
Also, the default position of notifications looks incorrect in some tests, but that might get fixed by using Position directly in the state.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027#-:-Ku_Pqp8Hwo2QjXt1MOl:b-1per5p)*

**Comment by hesara** [comment]
:lgtm: as long as we get the tests to pass - I guess we can investigate the GridLayout issue at our end sometime soonish.

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027#-:-Ku_RuSu0d8aL9eszdfU:b20178n)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 54 at r8](https://reviewable.io:443/reviews/vaadin/framework/10027#-Ku_Oyiin3cvfy2HEjAS:-Ku_SehjngMYiltr7BWo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e30a9c77d2026868dc7c9d463669100b5968035a/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L54)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

One more minor simplification that can be done: the enum Position is in the shared package and can actually be used directly here, so no need to map from Position to an ordinal and back.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuTpJ2g39UAQC_x-bYx:-Ku_SttdekjE1orLZWgO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c9ed1c8b25942e3845498c7525e818ffc3cae5e/uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java#L29)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r10, 1 of 1 files at r11, 1 of 3 files at r14, 2 of 3 files at r16.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 55 at r16](https://reviewable.io:443/reviews/vaadin/framework/10027#-KucDK_on9jwFtQTBqql:-KucDK_on9jwFtQTBqqm:ba8i3h1) ([raw file](https://github.com/vaadin/framework/blob/b3d9e0a0fb3e85a99e4878e4ded63f6727bcbff4/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L55)):*
> ```Java
>      *            can not be {@code null}.
>      */
>     public Position position = Position.TOP_LEFT;
> ```

The default position should be what it used to be, i.e. Position.MIDDLE_CENTER. This will also fix some of the failing tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java, line 55 at r16](https://reviewable.io:443/reviews/vaadin/framework/10027#-KucDK_on9jwFtQTBqql:-KucH6bE5FtSA5KZJY52:bb33jtv) ([raw file](https://github.com/vaadin/framework/blob/b3d9e0a0fb3e85a99e4878e4ded63f6727bcbff4/shared/src/main/java/com/vaadin/shared/ui/notification/NotificationState.java#L55)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

The default position should be what it used to be, i.e. Position.MIDDLE_CENTER. This will also fix some of the failing tests.
</blockquote></details>

Done. Thanks for the hint.

---

*[uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10027#-KuTpJ2g39UAQC_x-bYx:-Ku_T1WRjXhyQ6FXE2RA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c9ed1c8b25942e3845498c7525e818ffc3cae5e/uitest/src/test/java/com/vaadin/tests/extensions/NotificationCloseListenerTest.java#L29)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r17.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by hesara** [comment]
I'm working on a fix for the GridLayout bug that turned out to be related to GridLayout not waiting until fonts have been loaded. I'll try to make a PR out of the fix ASAP.

**Comment by hesara** [comment]
GridLayout fix in #10077 - once that is merged, this PR can be updated with it to get validation to pass.

**Comment by hesara** [comment]
Please update this for the latest master to resolve the remaining test failure.

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027)*

**Comment by asashour** [comment]
I am not sure if this is fixed by #10077.

**Comment by hesara** [comment]
I'll take a look at this.

**Comment by hesara** [comment]
:lgtm: assuming tests now pass

---

Reviewed 2 of 3 files at r19, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10027#-:-Kv1pCWBdLTJzy-T4iQL:b7itzeq)*

**Pull request merged**
