### PR TITLE
Use StringBuilder .append() instead of creating a new one

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10241)

### CODE REVIEW

**Comment by pekam** [comment]
Why?
Personally I think this makes the code more complex and harder to read. And concatenating Strings with `+` is compiled into `StringBuilder::append()`-calls anyway.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241#-:-Kxg_6BZdfA5X7v2aQtH:b1tds1r)*

**Comment by asashour** [comment]
Let's take one example:

    buffer.append(remainingValue.substring(0, fitsLine) + "\n ");

This statement creates an 'internal' StringBuilder, which have `remainingValue.substring(0, fitsLine)` and then appends `\n`, then the value of the 'internal' StringBuilder.toString() is appended to the already used `buffer`.

However, with

    buffer.append(remainingValue.substring(0, fitsLine)).append("\n ");


There is no internal construction of a new StringBuilder, and the values are appended to the existingi `buffer`.

However, code readability is a valid point in some place.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241#-:-KxgfsR9LGAOxOc3_H6f:b-noh6px)*

**Comment by pekam** [comment]
Thanks, I see your point now, but I vote for readability over the slight performance improvement in this case.
So I'd like to have a third opinion. @tsuoanttila ?

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241#-:-KxgjN8CC8MdE9QHxtWL:b-bvma96)*

**Comment by asashour** [comment]
Another point:  as you know, if readability is of significant importance in a particular case, then `StringBuilder` wouldn't be used, but simple string concatenation (`string += another`) would be in place. But since `StringBuilder` is used, I guess it should be used to the maximum.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241#-:-Kxqbazxjslq19GEpmLC:b-snmqn8)*

**Comment by elmot** [comment]
Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA37rhGPa1N8VgPvhz:-KyA37rhGPa1N8VgPvi-:bnz6fpy) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java#L54)):*
> ```Java
>             linelen = 1;
>         }
>         buffer.append(remainingValue).append("\n");
> ```

This change makes little of sense, the code is executed only once during framework build, and does not affect FW performance at all.
However, we can accept this just to keep our code more clean

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA420akgJmXHoIRhRX:-KyA420akgJmXHoIRhRY:byeu3x7) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L154)):*
> ```Java
>                 content = WidgetUtil.escapeHTML(caption);
>             }
>             sb.append("<span>").append(content).append("</span>");
> ```

The code does not make any sense, because it is converted to JavaScript by GWT compiler(as long as all code under `client` package) and there is not such a thing like StringBuilder. And, thus, the code is never executed inside JVM. In the same time, from GWT point of view  better to convert to `"a"+"b"` style

---

*[client/src/main/java/com/vaadin/client/ui/VEmbedded.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA5HtJerBpANLXzhLZ:-KyA5HtJerBpANLXzhL_:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VEmbedded.java#L89)):*
> ```Java
>         if (state.classId != null) {
>             html.append("classid=\"")
>                     .append(WidgetUtil.escapeAttribute(state.classId))
> ```

See above

---

*[client/src/main/java/com/vaadin/client/ui/VFlash.java, line 198 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA5uLZlG-aqRanfvxR:-KyA5uLZlG-aqRanfvxS:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VFlash.java#L198)):*
> ```Java
>         if (codebase != null) {
>             html.append("codebase=\"")
>                     .append(WidgetUtil.escapeAttribute(codebase)).append("\" ");
> ```

See above

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 223 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6Q7icuS1cvFp3Rm0:-KyA6Q7icuS1cvFp3Rm1:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L223)):*
> ```Java
>             if (item.getChildCount() > 0) {
>                 String bgStyle = "";
>                 itemHTML.append("<span class=\"").append(getStylePrimaryName())
> ```

See above

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6hELsWaRHS6j7jV8:-KyA6hELsWaRHS6j7jV9:b-8te750) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java#L154)):*
> ```Java
>                 content = WidgetUtil.escapeHTML(caption);
>             }
>             sb.append("<span>").append(content).append("</span>");
> ```

1) See above
2) We keep compatibility packages unchanged until there are changes ported from V7.7 or any real bug fixes.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Comment by elmot** [comment]
Review status: 0 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/calendar/schedule/MonthEventLabel.java, line 100 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8AAoDnkBsNbAMCl-:-KyA8AApA5ELQ980seQn:b-rb6nsc) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/compatibility-client/src/main/java/com/vaadin/v7/client/ui/calendar/schedule/MonthEventLabel.java#L100)):*
> ```Java
> 
>         if (caption != null && time != null) {
>             html.append("<span class=\"").append(STYLENAME).append("-time\">");
> ```

See my comment to `VFilterSelect`

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/DefaultSQLGenerator.java, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8TcH66kWD52DzcHK:-KyA8TcH66kWD52DzcHL:b5x2z95) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/DefaultSQLGenerator.java#L107)):*
> ```Java
>         StatementHelper sh = getStatementHelper();
>         StringBuffer query = new StringBuffer();
>         query.append("SELECT ").append(toSelect).append(" FROM ")
> ```

We keep compatibility packages unchanged until there are changes ported from V7.7 or any real bug fixes. 

---

*[uitest/src/main/java/com/vaadin/tests/components/button/ButtonMouseDetails.java, line 19 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8pCAVt-V_FCvUox0:-KyA8pCAVt-V_FCvUox1:b-i5zqw4) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/button/ButtonMouseDetails.java#L19)):*
> ```Java
> 
>         // Modifier keys
>         str.append("ctrl=").append(event.isCtrlKey()).append(",\t");
> ```

This is test class, it does not affect framework performance, I'd prefer readability over optimization 

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 136 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyAAQsz-f7VzObkjBDH:-KyAAQsz-f7VzObkjBDI:b-i5zqw4) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L136)):*
> ```Java
>             StringBuilder builder = new StringBuilder();
>             builder.append('{');
>             builder.append("\"First Name\":");
> ```

This is test class, it does not affect framework performance, I'd prefer readability over optimization 

---

*[uitest/src/main/java/com/vaadin/tests/components/window/WindowCloseShortcuts.java, line 177 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyAATnzo2PDLV8Q6FQA:-KyAATnzo2PDLV8Q6FQB:b-i5zqw4) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/window/WindowCloseShortcuts.java#L177)):*
> ```Java
>         Collections.sort(names);
> 
>         sb.append('<').append(producedElem.tagName());
> ```

This is test class, it does not affect framework performance, I'd prefer readability over optimization 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Comment by elmot** [comment]
Review status: 0 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA37rhGPa1N8VgPvhz:-KyAAgaZmt9E5qDNRfvS:bj9pdl7) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java#L54)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This change makes little of sense, the code is executed only once during framework build, and does not affect FW performance at all.
However, we can accept this just to keep our code more clean
</blockquote></details>

Further optimization: `.append('\n')` - this does not call additional string array manipulations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Comment by asashour** [comment]
Review status: 0 of 14 files reviewed at latest revision, 11 unresolved discussions.

---

*[buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA37rhGPa1N8VgPvhz:-Kz4HPheu61l0ZUvk7oE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/buildhelpers/src/main/java/com/vaadin/buildhelpers/ManifestWriter.java#L54)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Further optimization: `.append('\n')` - this does not call additional string array manipulations
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA420akgJmXHoIRhRX:-Kz4JH5b2E-9Lwt89SyB:b-jhv7sl) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L154)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The code does not make any sense, because it is converted to JavaScript by GWT compiler(as long as all code under `client` package) and there is not such a thing like StringBuilder. And, thus, the code is never executed inside JVM. In the same time, from GWT point of view  better to convert to `"a"+"b"` style
</blockquote></details>

Then how about removing the `StringBuilder` at all

---

*[client/src/main/java/com/vaadin/client/ui/VEmbedded.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA5HtJerBpANLXzhLZ:-Kz4Kk2osbSKa168vQDR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VEmbedded.java#L89)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VFlash.java, line 198 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA5uLZlG-aqRanfvxR:-Kz4M_Dj4mO83Y36Z4HX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VFlash.java#L198)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 223 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6Q7icuS1cvFp3Rm0:-Kz4MZd4_FOhYd0z-79Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L223)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6hELsWaRHS6j7jV8:-Kz4N9q_6BqghNO9f3Dq:bywchyr) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java#L154)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

1) See above
2) We keep compatibility packages unchanged until there are changes ported from V7.7 or any real bug fixes.  

</blockquote></details>

Reverted, then should I make a PR against `7.7` branch? then later do it here.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/calendar/schedule/MonthEventLabel.java, line 100 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8AAoDnkBsNbAMCl-:-Kz4NNX-zF80Oe5MxvKx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/compatibility-client/src/main/java/com/vaadin/v7/client/ui/calendar/schedule/MonthEventLabel.java#L100)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See my comment to `VFilterSelect`
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/DefaultSQLGenerator.java, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8TcH66kWD52DzcHK:-Kz4NiPJVpb_9Vji6Yel:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/DefaultSQLGenerator.java#L107)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

We keep compatibility packages unchanged until there are changes ported from V7.7 or any real bug fixes. 
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/button/ButtonMouseDetails.java, line 19 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA8pCAVt-V_FCvUox0:-Kz4NqA9sWCoAPi1CtIi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/button/ButtonMouseDetails.java#L19)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This is test class, it does not affect framework performance, I'd prefer readability over optimization 
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 136 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyAAQsz-f7VzObkjBDH:-Kz4OSfiZ7alLGcn-KmK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L136)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This is test class, it does not affect framework performance, I'd prefer readability over optimization 
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/window/WindowCloseShortcuts.java, line 177 at r3](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyAATnzo2PDLV8Q6FQA:-Kz4PF2cD9PVTdN0ggvI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/29c4bf82f04a800fdf92acde0f88e8d93f3e1cae/uitest/src/main/java/com/vaadin/tests/components/window/WindowCloseShortcuts.java#L177)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This is test class, it does not affect framework performance, I'd prefer readability over optimization 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Comment by elmot** [comment]
Reviewed 1 of 14 files at r1, 1 of 1 files at r2, 3 of 11 files at r4, 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA420akgJmXHoIRhRX:-L4HCSEuz-AFS1dR98VR:b-r9sz8) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L154)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Then how about removing the `StringBuilder` at all
</blockquote></details>

That's fine.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/MSSQLGenerator.java, line 110 at r5](https://reviewable.io:443/reviews/vaadin/framework/10241#-L4HDNiiXUWZVsLlI4t_:-L4HDNiiXUWZVsLlI4ta:bg0uvz0) ([raw file](https://github.com/vaadin/framework/blob/2c3843d0b689f2cec4389eb73efff6600c43661d/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/MSSQLGenerator.java#L110)):*
> ```Java
>             }
>         }
>         query.append(") AS rownum, ").append(toSelect).append(" FROM ")
> ```

Please do not change compatibility packages

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6hELsWaRHS6j7jV8:-L4HC5D44P7b2QsW_RTL:blo5jtt) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java#L154)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Reverted, then should I make a PR against `7.7` branch? then later do it here.
</blockquote></details>

Please do not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA420akgJmXHoIRhRX:-L4R045KL_1odzTKDVq_:b-7sjwwc) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L154)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

That's fine.
</blockquote></details>

`StringBuilder` was removed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10241#-KyA6hELsWaRHS6j7jV8:-L4R6RgYjf39NZY4FSFD:b32w1t) ([raw file](https://github.com/vaadin/framework/blob/21a5c9cc9fbb19553f0b394cb388a9f7df1349c1/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java#L154)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please do not. 
</blockquote></details>

Ok

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/MSSQLGenerator.java, line 110 at r5](https://reviewable.io:443/reviews/vaadin/framework/10241#-L4HDNiiXUWZVsLlI4t_:-L4R6T2RMyC6dLo6Zi3Z:bwvyox4) ([raw file](https://github.com/vaadin/framework/blob/2c3843d0b689f2cec4389eb73efff6600c43661d/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/query/generator/MSSQLGenerator.java#L110)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please do not change compatibility packages
</blockquote></details>

Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10241)*

**Pull request closed without merging**
