### PR TITLE
Accessibility for MenuBar (#3922)

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10244)

### CODE REVIEW

**Comment by asashour** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1682 at r1](https://reviewable.io:443/reviews/vaadin/framework/10244#-KxD8XsnHRP9XXTIO_lT:-KxD8XsnHRP9XXTIO_lU:b-xehdnq) ([raw file](https://github.com/vaadin/framework/blob/275ce20db0d7fc7c69437f5bb59066a1f1558ada/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1682)):*
> ```Java
> 
>     private void selectLastItem() {
>         for (int i = 1; i <= items.size(); i++) {
> ```

Would it be better to be:

    for (int i = items.size() - 1; i >= 0; i--) {
        .... items.get(i);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by knoobie** [comment]
If you want to improve the accessibility for menubar, using ul/li instead of div would be the best way.

**Comment by Ansku** [comment]
I actually tried that, but the main difference I noticed was the styles breaking all over the place. But maybe I overlooked something?

**Comment by knoobie** [comment]
No, you are right - the style breaking change would be huge. 

It's just my recommendation because this was one of the main reasons why we can't use the menubar as navigation in our applications. (additional to all the missing aria-* for expanding etc.)

There should be an easy way to define a 'nav' around the menubar as well.

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10244#-Kz8DTSMwkPvg3QFb6qL:-Kz8DTSMwkPvg3QFb6qM:b-a7frzm) (no related file):*
Have you tested the UX of the navigation changes with some UX expert?

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1152 at r2](https://reviewable.io:443/reviews/vaadin/framework/10244#-Kz8D73UNww8o0fRxraH:-Kz8D73UNww8o0fRxraI:b-wxdqb8) ([raw file](https://github.com/vaadin/framework/blob/269613736e0744b46a6f11a3c1dc10c84f0478f0/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1152)):*
> ```Java
>         @SuppressWarnings("deprecation")
>         @Override
>         public com.google.gwt.user.client.Element getSubPartElement(
> ```

is this API needed and used somewhere ?

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1162 at r2](https://reviewable.io:443/reviews/vaadin/framework/10244#-Kz8D9TQKeXNVzS53UJo:-Kz8D9TQKeXNVzS53UJp:bt6vwj0) ([raw file](https://github.com/vaadin/framework/blob/269613736e0744b46a6f11a3c1dc10c84f0478f0/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1162)):*
> ```Java
>         @SuppressWarnings("deprecation")
>         @Override
>         public String getSubPartName(
> ```

Is this API needed and used somewhere ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by Ansku** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10244#-Kz8DTSMwkPvg3QFb6qL:-Kz8J0SYbbOqWwPdgUuT:bfl9hxn) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Have you tested the UX of the navigation changes with some UX expert?
</blockquote></details>

No, only discussed it with Jouni and tried to follow these for the most part: https://www.w3.org/TR/wai-aria-practices-1.1/#menu

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1162 at r2](https://reviewable.io:443/reviews/vaadin/framework/10244#-Kz8D9TQKeXNVzS53UJo:-Kz8IRtyFvZOMo0eLp9l:bl7nreg) ([raw file](https://github.com/vaadin/framework/blob/269613736e0744b46a6f11a3c1dc10c84f0478f0/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1162)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is this API needed and used somewhere ?
</blockquote></details>

Existing TB functionality breaks without it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10244#-KzOL_0441u4JB7H23oF:-KzOL_0441u4JB7H23oG:bv8oa3e) (no related file):*
Conflicts with master, can't be merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by asashour** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1735 at r4](https://reviewable.io:443/reviews/vaadin/framework/10244#-KzOfSk8nvU8sBoEzRw8:-KzOfSk9kcUBbJIi-0sZ:b-e3m04a) ([raw file](https://github.com/vaadin/framework/blob/6ca117ed93a63b9af9976b58401c7f4b0ade6748/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1735)):*
> ```Java
>     }
> 
> <<<<<<< HEAD
> ```

Compilation error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10244#-KzOL_0441u4JB7H23oF:-KzTM5O8sWnxmO_jhVE5:bkrkp0w) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Conflicts with master, can't be merged
</blockquote></details>

This patch could still use one extensive test that checks various aria attributes in the DOM. Can be added later as well, but would rather see at least the basics tested here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10244)*

**Comment by tsuoanttila** [comment]
Merged as part of #10259

**Pull request closed without merging**
