### PR TITLE
Refactor common methods in in-memory data providers

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9308)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkA8fvK_boH-Wd25HYQ:-KkA8fvLv0zZ08CMG_tY:bbmcvvc) (no related file):*
Pending javadocs and discussed renames to `TreeData`, `TreeDataProvider`, and `BackEndTreeDataProvider` 

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkA9COE4tE0bGs5XaDg:-KkA9COE4tE0bGs5XaDh:bmjnjkz) ([raw file](https://github.com/vaadin/framework/blob/a9bdb1bb3384b780f5414d91150e9f6708594d31/server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java#L31)):*
> ```Java
>  * A {@link DataProvider} for in-memory hierarchical data.
>  *
>  * @see HierarchyData
> ```

either this is removed or clarified why you should see this 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by pleku** [comment]
Reviewed 26 of 27 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkA8fvK_boH-Wd25HYQ:-KkCdQ3W9Rb1yv6q_tV0:b-mjc8n) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Pending javadocs and discussed renames to `TreeData`, `TreeDataProvider`, and `BackEndTreeDataProvider` 
</blockquote></details>

Also pending a full search for string _hierarchyData_ and there should be 0 results from the whole project (test classed can be ignored but not javadocs.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbBB_HHQJE769wVSh:-KkCbBB_HHQJE769wVSi:bb7462z) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L29)):*
> ```Java
> 
> /**
>  * TODO
> ```

TODO

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 44 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCb42V-n4E0UjN4Sjh:-KkCb42V-n4E0UjN4Sji:bb7462z) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L44)):*
> ```Java
>      * @return TODO
>      * @throws IllegalStateException
>      *             if TODO
> ```

TODO

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 61 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCb2yOXaJFsDyF21sl:-KkCb2yP34_v2mbiQv0L:bb7462z) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L61)):*
> ```Java
>      *            TODO
>      * @param childItemProvider
>      *            TODO
> ```

TODO

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 91 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbgRNBv1KT6MXL2L9:-KkCbgRNBv1KT6MXL2LA:bhrr8kg) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L91)):*
> HierarchyData

TreeData

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 127 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbe7i2tdkHvdo1GWM:-KkCbe7i2tdkHvdo1GWN:bhrr8kg) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L127)):*
> HierarchyData

TreeData

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 162 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbjyhkzrl--kY7nT9:-KkCbjyhkzrl--kY7nTA:bhrr8kg) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L162)):*
> HierarchyData

TreeData

---

*[server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCcGSVHoeqpQexidM3:-KkCcGSWhzsRkeP9hDO3:b-kiy2c5) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java#L29)):*
>  * {@link HierarchicalDataProvider} wrapper for {@link TreeData}.

This says absolutely nothing about why/when it is used. And the what is also pretty horrible "FOO wrapper for BAR"

---

*[server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java, line 54 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCcd-Fqn2B9BNxjunY:-KkCcd-GohRE_4gM4nfz:b-d23kgb) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java#L54)):*
> hierarchyData
>      *            the backing HierarchyData

TreeData

---

*[server/src/test/java/com/vaadin/tests/components/TreeTest.java, line 56 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCd9ClyqunMT8iyZD0:-KkCd9ClyqunMT8iyZD1:b-gfptq2) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/test/java/com/vaadin/tests/components/TreeTest.java#L56)):*
>  hierarchyData

---

*[server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridTest.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCdBignV0NHj-3rLDo:-KkCdBignV0NHj-3rLDp:bq6lxn6) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridTest.java#L28)):*
> hierarchyData

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java, line 23 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCdIolmaSAtrZ3r_dp:-KkCdIolmaSAtrZ3r_dq:bucndr6) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java#L23)):*
> hierarchyData 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by ahie** [comment]
Review status: 20 of 27 files reviewed at latest revision, 13 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbBB_HHQJE769wVSh:-KkF6e2s_rv1wNQh-8oj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 44 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCb42V-n4E0UjN4Sjh:-KkF6eS1yCn87u6ws9oE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L44)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 61 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCb2yOXaJFsDyF21sl:-KkF6f8ceyQ-tyAw-ieA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L61)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 91 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbgRNBv1KT6MXL2L9:-KkF6gQw66qIDANlDzJQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L91)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> HierarchyData

TreeData
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 127 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbe7i2tdkHvdo1GWM:-KkF6gpdGHUohMlpSJzT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L127)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> HierarchyData

TreeData
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 162 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCbjyhkzrl--kY7nT9:-KkF6hH9o_4EpXHBMoXd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L162)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> HierarchyData

TreeData
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkA9COE4tE0bGs5XaDg:-KkF6kj8C_VroAxDTb-o:b5j8j3h) ([raw file](https://github.com/vaadin/framework/blob/a9bdb1bb3384b780f5414d91150e9f6708594d31/server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

either this is removed or clarified why you should see this 
</blockquote></details>

These have also been changed in https://github.com/vaadin/framework/pull/9287.

---

*[server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java, line 54 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCcd-Fqn2B9BNxjunY:-KkF6vdXbiZ7U-4C82g5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/main/java/com/vaadin/data/provider/TreeDataProvider.java#L54)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> hierarchyData
>      *            the backing HierarchyData

TreeData
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/components/TreeTest.java, line 56 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCd9ClyqunMT8iyZD0:-KkF6xYuof1f3xnZsaAL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/test/java/com/vaadin/tests/components/TreeTest.java#L56)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  hierarchyData
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridTest.java, line 28 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCdBignV0NHj-3rLDo:-KkF6yNtQ4x6D56DXG61:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridTest.java#L28)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> hierarchyData
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java, line 23 at r3](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkCdIolmaSAtrZ3r_dp:-KkF6ynI1HvQFhrHimQn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31442b5eb89f309b07919b6e08040c6139b39187/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java#L23)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> hierarchyData 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by pleku** [comment]
Reviewed 2 of 27 files at r2, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 43 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF6lnOh1oEheomGAkf:-KkF6lnPHn4QjqFa-UZL:bb7462z) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L43)):*
> ```Java
>      * TODO
>      *
>      * @return TODO
> ```

TODO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by ahie** [comment]
Review status: 26 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java, line 43 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF6lnOh1oEheomGAkf:-KkF7qetwL0WFCFu5wdP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/HasHierarchicalDataProvider.java#L43)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by hesara** [comment]
Reviewed 3 of 6 files at r1, 20 of 27 files at r2, 7 of 7 files at r4.
Review status: 26 of 27 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java, line 47 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF86_iKRlGulgsNjqS:-KkF86_jTWIhayrLowvE:b-nj9g21) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java#L47)):*
> ```Java
> 
>     /**
>      *
> ```

javadoc missing

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java, line 186 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF8C3IPhlaTiK-S4Al:-KkF8C3IPhlaTiK-S4Am:b-nj9g21) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java#L186)):*
> ```Java
> 
>     /**
>      *
> ```

javadoc missing

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProviderHelpers.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/9308#-KjwOEgsol8BSkCTY4uk:-KjwOEgtohoXqv2lO2MQ:bwta2) ([raw file](https://github.com/vaadin/framework/blob/a9bdb1bb3384b780f5414d91150e9f6708594d31/server/src/main/java/com/vaadin/data/provider/InMemoryDataProviderHelpers.java#L35)):*
> ```Java
>  * @since 8.1
>  */
> class InMemoryDataProviderHelpers {
> ```

Should we make this more public, with javadoc still specifying "for internal use"? It might help some users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by ahie** [comment]
Review status: 26 of 27 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java, line 47 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF86_iKRlGulgsNjqS:-KkFAZJZO9K6nXqG3WKi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java#L47)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

javadoc missing
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java, line 186 at r4](https://reviewable.io:443/reviews/vaadin/framework/9308#-KkF8C3IPhlaTiK-S4Al:-KkFAXeEk9PsW7qtCcNZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/04af5be1dcd2083efb60d273894362c65fb4d7f0/server/src/main/java/com/vaadin/data/provider/InMemoryDataProvider.java#L186)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

javadoc missing
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryDataProviderHelpers.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/9308#-KjwOEgsol8BSkCTY4uk:-KkFBfhqwvBMrfx7pNpT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a9bdb1bb3384b780f5414d91150e9f6708594d31/server/src/main/java/com/vaadin/data/provider/InMemoryDataProviderHelpers.java#L35)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should we make this more public, with javadoc still specifying "for internal use"? It might help some users.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9308)*

**Pull request merged**
