### PR TITLE
Fix broken method signature of Grid.addColumn

### LINKED ISSUE #8129: Broken method signature of Grid.addColumn
The functionality implemented by #7974 was accidentally broken in 334fd4bcef760930651308ec94aeceaac6563c87 when resolving merge conflicts. The problem was not discovered since there was no automatic test for the feature.

Restore the method signature and ensure there's a test for the feature.

### PR DESCRIPTION
**Pull request by ahie**
Fixes #8129

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8180)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8180#-Ka2cwJkSaN4FJivyiSh:-Ka2cwJkSaN4FJivyiSi:b-p4kic6) ([raw file](https://github.com/vaadin/framework/blob/c5c298b3502531601b8e7f8926b3ab070713273e/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L38)):*
> ```Java
>         grid.addColumn(ValueProvider.identity()).setId("foo");
>         grid.addColumn(String::length, new NumberRenderer());
>         grid.addColumn(String::length);
> ```

Does it really test a feature ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180#-:-Ka2czEaEIsZ7M89YE3M:bnfp4nl)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8180#-Ka2cwJkSaN4FJivyiSh:-Ka2d2sSeJGxfoap04bc:b-46wm5a) ([raw file](https://github.com/vaadin/framework/blob/c5c298b3502531601b8e7f8926b3ab070713273e/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Does it really test a feature ?
</blockquote></details>

For me it does

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Comment by denis-anisimov** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8180#-Ka2cwJkSaN4FJivyiSh:-Ka2fguVr596e4J2WCpr:b-4wcanm) ([raw file](https://github.com/vaadin/framework/blob/c5c298b3502531601b8e7f8926b3ab070713273e/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L38)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

For me it does
</blockquote></details>

I would expect some tests that do something with the column : retrieve data, may be sort ......

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8180#-Ka2cwJkSaN4FJivyiSh:-Ka6BilAttFdblLKuT-a:bvwzsig) ([raw file](https://github.com/vaadin/framework/blob/c5c298b3502531601b8e7f8926b3ab070713273e/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L38)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would expect some tests that do something with the column : retrieve data, may be sort ......
</blockquote></details>

I agree with Denis. This only tests that the API can be used without compilation errors, but not that something sensible will be shown in the column.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Comment by ahie** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8180#-Ka2cwJkSaN4FJivyiSh:-Ka6wW3pvDCxKfLHiz-j:bufim0i) ([raw file](https://github.com/vaadin/framework/blob/c5c298b3502531601b8e7f8926b3ab070713273e/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L38)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I agree with Denis. This only tests that the API can be used without compilation errors, but not that something sensible will be shown in the column.
</blockquote></details>

Added tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8180)*

**Pull request merged**
