### PR TITLE
Binder with Nested Properties

### PR DESCRIPTION
**Pull request by chrosim**
@elmot Sorry for the second PR, Test is now included

Enabled Binder by enhancing BeanPropertySet to lazy create NestedPropertyDefinitions
Resolves: #8384

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8923)

### CODE REVIEW

**Comment by elmo** [comment]
I'm not a member of this project.

**Comment by hesara** [comment]
Minor issues to address and potential improvements, mostly looking ok to me.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzNotzV0dO7jNEWDgN:-KfzNotzV0dO7jNEWDgO:b-uij63z) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L190)):*
> ```Java
>     }
> 
>     private static class NestedBeanPropertyDefinition<T, V>
> ```

There is so much commonality with BeanPropertyDefinition that I'd consider extracting it to an abstract base class - which can still be here inside BPS.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 326 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzPcYctvULqGxRe33n:-KfzPcYctvULqGxRe33o:b44ne0x) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L326)):*
> ```Java
>                     String[] propertyChain = name.split("\\.");
>                     String parentProperty = Stream.of(propertyChain)
>                             .filter(item -> !item.equals(
> ```

If I understand correctly, the intention here is to skip the last element. However, this implementation can be problematic if multiple levels have properties with the same name (e.g. "person.father.father" to get the grandfather). Instead of an intermediate split and stream, I'd just use name.substring(0, name.lastIndexOf('.')) .

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzO4BDr3NpTLHal3Ms:-KfzO4BDr3NpTLHal3Mt:bmaxxm1) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L106)):*
> ```Java
>                 deserializedDefinition);
>     }
>     
> ```

extra whitespace here and below on some empty lines - I'd recommend using the "remove trailing whitespace" save action

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 131 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzR1EcYQiwfLJ7XWQh:-KfzR1EcYQiwfLJ7XWQi:b-jpjr8r) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L131)):*
> ```Java
>                 deserializedDefinition);
>     }
> ```

Ideally we would have some more simple tests especially for the edge cases (invalid property path, ...).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923#-:-KfzQs0oQIIFW8d3Qgj0:b-fg7bs1)*

**Comment by chrosim** [comment]
@hesara Abstraction is Done.
You were totaly right with this:
[https://reviewable.io/reviews/vaadin/framework/8923#-KfzPcYctvULqGxRe33n:-KfzPcYctvULqGxRe33o:b44ne0x]

Cleaned up the Test and added two more cases

**Comment by chrosim** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzNotzV0dO7jNEWDgN:-KgIlyke5EGFAibqHOUF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L190)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

There is so much commonality with BeanPropertyDefinition that I'd consider extracting it to an abstract base class - which can still be here inside BPS.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 326 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzPcYctvULqGxRe33n:-KgIm4Zd2RynziDuz_wC:begs9xy) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L326)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

If I understand correctly, the intention here is to skip the last element. However, this implementation can be problematic if multiple levels have properties with the same name (e.g. "person.father.father" to get the grandfather). Instead of an intermediate split and stream, I'd just use name.substring(0, name.lastIndexOf('.')) .
</blockquote></details>

Your were totaly right about it, fixed it with your suggestion

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzO4BDr3NpTLHal3Ms:-KgImGwLYzQuyKL8_uma:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L106)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace here and below on some empty lines - I'd recommend using the "remove trailing whitespace" save action
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 131 at r1](https://reviewable.io:443/reviews/vaadin/framework/8923#-KfzR1EcYQiwfLJ7XWQh:-KgImN2NduQdt1bhG_L7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96818df682b7065ecc4c764c3736f91bbdcdc764/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L131)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Ideally we would have some more simple tests especially for the edge cases (invalid property path, ...).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 141 at r2](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJ0ujOcqA-xPIx660h:-KgJ0ujPqNqbRRXdSb41:bymbino) ([raw file](https://github.com/vaadin/framework/blob/3c902ba4eb7ca13226f74e9a3fd83c4b65846e1a/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L141)):*
> ```Java
> 
>     @Test
>     public void testSerializeDeserialize_nestedPropertyDefinition_samePropertyNameOnMultipleLevels()
> ```

these tests don't really do any serialization/deserialization, so they could be named differently

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by chrosim** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 141 at r2](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJ0ujOcqA-xPIx660h:-KgJg70uJROCN9Xh6EXq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3c902ba4eb7ca13226f74e9a3fd83c4b65846e1a/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L141)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

these tests don't really do any serialization/deserialization, so they could be named differently
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJmAoxj5jT8r1pDDLu:-KgJmAoxj5jT8r1pDDLv:ba91ahl) (no related file):*
We should probably add documentation for this before merging - leaving a comment as a reminder. @chrosim if you have enabled the option to allow maintainers to make changes to your PR, the framework team can probably make those changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by chrosim** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJmAoxj5jT8r1pDDLu:-KgKTvVRA58LoL-Ax5OZ:bhejpps) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

We should probably add documentation for this before merging - leaving a comment as a reminder. @chrosim if you have enabled the option to allow maintainers to make changes to your PR, the framework team can probably make those changes.
</blockquote></details>

@hesara I think I did enable it.
But if I have seen it right, the documentation already says it is possible?
https://vaadin.com/docs/-/part/framework/datamodel/datamodel-forms.html#datamodel.forms.beans

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJmAoxj5jT8r1pDDLu:-KgNf26OnK7QAhOdOXE4:bu6a18p) (no related file):*
<details><summary><i>Previously, chrosim wrote…</i></summary><blockquote>

@hesara I think I did enable it.
But if I have seen it right, the documentation already says it is possible?
https://vaadin.com/docs/-/part/framework/datamodel/datamodel-forms.html#datamodel.forms.beans

</blockquote></details>

It does indeed look like the documentation already uses such a case although a sentence mentioning you can do so would not hurt.

However, while reading the documentation more carefully, I realized there is probably another issue: BeanValidationBinder tries to configure bean validation based on the top-level bean type rather than the nested property bean type.

This should probably be fixed so that it uses the correct bean type even in the nested case, and a test added for that. Can you take a look at it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by chrosim** [comment]
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJmAoxj5jT8r1pDDLu:-KgoZcBZki4MZLkpW70S:b-axv75g) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

It does indeed look like the documentation already uses such a case although a sentence mentioning you can do so would not hurt.

However, while reading the documentation more carefully, I realized there is probably another issue: BeanValidationBinder tries to configure bean validation based on the top-level bean type rather than the nested property bean type.

This should probably be fixed so that it uses the correct bean type even in the nested case, and a test added for that. Can you take a look at it?
</blockquote></details>

Fixed it for BeanValidationBinder and added a test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by simon-chromow** [comment]
@hesara @elmot Any progress here?

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8923#-KgJmAoxj5jT8r1pDDLu:-KhWvU3_fQGTxIdCFNzX:b-r2vd6l) (no related file):*
<details><summary><i>Previously, chrosim wrote…</i></summary><blockquote>

Fixed it for BeanValidationBinder and added a test
</blockquote></details>

Thanks, and sorry for the delay - I was out of the office for a while.

---

*[server/src/main/java/com/vaadin/data/PropertyDefinition.java, line 60 at r4](https://reviewable.io:443/reviews/vaadin/framework/8923#-KhWwUJyoJ3dXQrj2dq3:-KhWwUJyoJ3dXQrj2dq4:b-7t23m4) ([raw file](https://github.com/vaadin/framework/blob/b45a3a28875ddaacbfeb1ad94fdc6c75ee281165/server/src/main/java/com/vaadin/data/PropertyDefinition.java#L60)):*
> ```Java
>      * Gets the type of the class containing this property.
>      *
>      * @return the property type. not <code>null</code>
> ```

should have "@since 8.1" (or alternatively just "@since" that we'll fill in later) - this is an API change so even though not many people implement PropertyDefinition, this is technically a breaking change

---

*[server/src/test/java/com/vaadin/data/BeanBinderTest.java, line 70 at r4](https://reviewable.io:443/reviews/vaadin/framework/8923#-KhWvxF9Rf1LN5YW_lsW:-KhWvxF9Rf1LN5YW_lsX:b2ha9mg) ([raw file](https://github.com/vaadin/framework/blob/b45a3a28875ddaacbfeb1ad94fdc6c75ee281165/server/src/test/java/com/vaadin/data/BeanBinderTest.java#L70)):*
> ```Java
> 
>         private SubConstraint subfield;
>         
> ```

(some extra whitespace here and below on empty lines, not a blocker)

---

*[server/src/test/java/com/vaadin/data/BinderCustomPropertySetTest.java, line 62 at r4](https://reviewable.io:443/reviews/vaadin/framework/8923#-KhWwJxlnjrXsvpIiG9f:-KhWwJxlnjrXsvpIiG9g:b245fj) ([raw file](https://github.com/vaadin/framework/blob/b45a3a28875ddaacbfeb1ad94fdc6c75ee281165/server/src/test/java/com/vaadin/data/BinderCustomPropertySetTest.java#L62)):*
> ```Java
>             return String.class;
>         }
>         
> ```

(extra whitespace, not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by ahie** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/PropertyDefinition.java, line 60 at r4](https://reviewable.io:443/reviews/vaadin/framework/8923#-KhWwUJyoJ3dXQrj2dq3:-KhX0PxmP0cEVOIDLg8i:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b45a3a28875ddaacbfeb1ad94fdc6c75ee281165/server/src/main/java/com/vaadin/data/PropertyDefinition.java#L60)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should have "@since 8.1" (or alternatively just "@since" that we'll fill in later) - this is an API change so even though not many people implement PropertyDefinition, this is technically a breaking change
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8923)*

**Comment by rajesh-gupta** [comment]
I think there is still a bug while data binding from UI to bean. I am having a bean 

package my.vaadin.app.ui.presenter;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * The Class Paragraph.
 */
@XmlRootElement
public class Paragraph {

	/** The title. */
	private String title;

	/** The description. */
	private String description;

	/** The address. */
	private Address address;

	public Paragraph() {
	}

	public Paragraph(String title, String description, Address address) {
		this.title = title;
		this.description = description;
		this.address = address;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the address.
	 *
	 * @return the address
	 */
	public Address getAddress() {
		return address;
	}

	/**
	 * Sets the address.
	 *
	 * @param address the address to set
	 */
	public void setAddress(Address address) {
		this.address = address;
	}

	/**
	 * The Class Address.
	 */
	public static class Address {

		/** The apartment. */
		private String apartment;

		/** The street name. */
		private String streetName;

		public Address() {
		}

		public Address(String apartment, String streetName) {
			this.apartment = apartment;
			this.streetName = streetName;
		}

		/**
		 * Gets the apartment.
		 *
		 * @return the apartment
		 */
		public String getApartment() {
			return apartment;
		}

		/**
		 * Sets the apartment.
		 *
		 * @param apartment the apartment to set
		 */
		public void setApartment(String apartment) {
			this.apartment = apartment;
		}

		/**
		 * Gets the street name.
		 *
		 * @return the streetName
		 */
		public String getStreetName() {
			return streetName;
		}

		/**
		 * Sets the street name.
		 *
		 * @param streetName the streetName to set
		 */
		public void setStreetName(String streetName) {
			this.streetName = streetName;
		}

	}

}

I am binding each property of this bean to 4 TextField like below.
binder.forField(textField1).bind("title");
binder.forField(textField2).bind("description");
binder.forField(textField3).bind("address.apartment");
binder.forField(textField4).bind("address.streetName");

I am getting NullPointerException at binder.writeBean line
Paragraph paragraph = new Paragraph();
binder.writeBean(paragraph);

ExceptionTrace:
java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.data.BeanPropertySet.invokeWrapExceptions(BeanPropertySet.java:349)
	at com.vaadin.data.BeanPropertySet.access$200(BeanPropertySet.java:49)
	at com.vaadin.data.BeanPropertySet$NestedBeanPropertyDefinition.lambda$getGetter$f3cd9597$1(BeanPropertySet.java:220)
	at com.vaadin.data.Binder$BindingImpl.convertDataToFieldType(Binder.java:899)
	at com.vaadin.data.Binder$BindingImpl.initFieldValue(Binder.java:890)
	at com.vaadin.data.Binder$BindingImpl.access$100(Binder.java:763)
	at com.vaadin.data.Binder.lambda$setBean$1(Binder.java:1341)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.data.Binder.setBean(Binder.java:1341)
	at my.vaadin.app.MyUI.clickMeButtonClicked(MyUI.java:84)
	at my.vaadin.app.MyUI.lambda$0(MyUI.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1029)
	at com.vaadin.ui.Button.fireClick(Button.java:370)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1464)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ahie** [comment]
@rajesh-gupta Looks like the NPE thrown in your example is caused by `address` being null when a `Paragraph` is constructed with the default constructor.

**Comment by rajesh-gupta** [comment]
Thanks, after creating the address object, it start working.

**Pull request merged**
