### PR TITLE
Fix TreeData item removal, small improvements

### LINKED ISSUE #9614: Tree/TreeGrid 8.1 beta3 - not possible to delete visible and selected item. "could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?"
Attempts to delete selected item from Tree/TreeGrid leads to "could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?" exception. 

Didn't find a workaround (yet), but the working code to hunt the bug is below. Push the button and check the exception
```
       TreeData<String> treeData = new TreeData<>();
       treeData.addItem(null, "A");
       treeData.addItem("A", "B");
       Tree<String> tree = new Tree<>(new TreeDataProvider<>(treeData));
       l.addComponent(tree);
       tree.expand("A");
       tree.select("B");
//       ((SingleSelectionModel)tree.getSelectionModel()).setDeselectAllowed(true);
       
       Button br = new Button("XXX", ev -> {
//    	   tree.getSelectionModel().deselect("B");
//    	   tree.deselect("B");
    	   tree.getTreeData().removeItem("B");
    	   tree.getDataProvider().refreshAll();
    	   tree.select("A");
       });
       l.addComponent(br);
```

> java.lang.IllegalArgumentException: Item B could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?
> 	at com.vaadin.data.provider.TreeDataProvider.hasChildren(TreeDataProvider.java:75)
> 	at com.vaadin.data.provider.HierarchyMapper.generateData(HierarchyMapper.java:177)
> 	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:449)
> 	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:349)
> 	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:311)
> 	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
> 	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
> 	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
> 	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
> 	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
> 	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
> 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:524)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
> 	at java.lang.Thread.run(Thread.java:745)
> 
>

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9614

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9621)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 315 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6nkBRHurso2hIzlLT:-Ko6nkBRHurso2hIzlLU:by7a2en) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L315)):*
> ```Java
>     @Override
>     protected void dropAllData() {
>         if (mapper != null) {
> ```

Why isn't dropAllData() called without an explicit call from here? It is a DataGenerator.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 513 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6n50Bvq8BtFkKhj9e:-Ko6n50Bvq8BtFkKhj9f:bgi08ff) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L513)):*
> ```Java
>     @Override
>     public void destroyAllData() {
>         childMap.clear();
> ```

TBC if this breaks refresh where open nodes should be kept - probably not called in that case, so probably ok

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchicalCommunicatorTest.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6lV3Oznc7sz5SdTbH:-Ko6lV3Oznc7sz5SdTbI:b5tnlly) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchicalCommunicatorTest.java#L81)):*
> ```Java
>             dataProvider.refreshItem(item);
>         }
>         communicator.beforeClientResponse(false);
> ```

no assertion - would this throw in any case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9621)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6vE80dxgX-7Jn-0l2:-Ko6vE80dxgX-7Jn-0l3:b-wdqm65) ([raw file](https://github.com/vaadin/framework/blob/840e45b5dcc2c55f26d58cc8a6b9a3cf180507c5/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L97)):*
> ```Java
>      * @return the parent index
>      * 
>      * @throws IllegalArgumentException
> ```

does it no longer throw or just removed the documentation? If not, then should the throws be also removed from the method ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9621)*

**Comment by elmot** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 315 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6nkBRHurso2hIzlLT:-Ko77r-TLmOQtdLHey7j:brovq8k) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L315)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why isn't dropAllData() called without an explicit call from here? It is a DataGenerator.
</blockquote></details>

Yeah, that looks like a bit of overprotection. Removed.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6vE80dxgX-7Jn-0l2:-Ko77wv1tPDzoYuJVixl:btzy49j) ([raw file](https://github.com/vaadin/framework/blob/840e45b5dcc2c55f26d58cc8a6b9a3cf180507c5/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L97)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

does it no longer throw or just removed the documentation? If not, then should the throws be also removed from the method ?
</blockquote></details>

Good point. `throws` removed

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchicalCommunicatorTest.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6lV3Oznc7sz5SdTbH:-Ko782Cr8DzsL7byW-zV:b-bjiglu) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchicalCommunicatorTest.java#L81)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

no assertion - would this throw in any case?
</blockquote></details>

This line is a key point of the whole test. Without the fix it throws an assertion exception. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9621)*

**Comment by elmot** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 513 at r1](https://reviewable.io:443/reviews/vaadin/framework/9621#-Ko6n50Bvq8BtFkKhj9e:-Ko78i_eCZwS_oLF5YTS:b-epy1em) ([raw file](https://github.com/vaadin/framework/blob/08699559749a2acebff963783a0a8f35cf769719/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L513)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC if this breaks refresh where open nodes should be kept - probably not called in that case, so probably ok
</blockquote></details>

The map does not contain open/close list, only parent-child relationships? thus it should not be the case. And the method is called only during heavy operations like replacing the whole DataProvider

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9621)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9621)*

**Pull request merged**
