### PR TITLE
Add headers to community articles

### PR DESCRIPTION
**Pull request by hezamu**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10029)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/articles/AutoGeneratingAFormBasedOnABeanVaadin6StyleForm.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBGh1-X6vhFJA5sAG:-KuPBGh1-X6vhFJA5sAH:b8h3mem) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/AutoGeneratingAFormBasedOnABeanVaadin6StyleForm.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Auto Generating A Form Based On A Bean Vaadin6 Style Form
> ```

Vaadin 6

---

*[documentation/articles/CreatingACustomFieldForEditingTheAddressOfAPerson.asciidoc, line 3 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBN2Ku6y8Kih1gWyl:-KuPBN2Ku6y8Kih1gWym:b3g31xx) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/CreatingACustomFieldForEditingTheAddressOfAPerson.asciidoc#L3)):*
> ```AsciiDoc
> ---
> title: Creating A Custom Field For Editing The Address Of A Person
> order: 27
> ```

duplicate order number

---

*[documentation/articles/CreatingYourOwnConverterForString.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPB8SUqG3c8gD-aPxQ:-KuPB8SUqG3c8gD-aPxR:bfqzec5) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/CreatingYourOwnConverterForString.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Creating Your Own Converter For String
> ```

should the title be longer, or is this ok?

---

*[documentation/articles/MigratingFromVaadin7.0ToVaadin7.1.asciidoc, line 3 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBQOU_67bY9GfeDIN:-KuPBQOV-XKqzxvVkd9r:b3g31xx) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/MigratingFromVaadin7.0ToVaadin7.1.asciidoc#L3)):*
> ```AsciiDoc
> ---
> title: Migrating from Vaadin 7.0 to Vaadin 7.1
> order: 27
> ```

duplicate order number

---

*[documentation/articles/OfflineModeForTouchKit4MobileApps.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPAr_Towrn6RxX47FS:-KuPAr_Towrn6RxX47FT:b-hawzw0) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/OfflineModeForTouchKit4MobileApps.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Offline Mode For Touch Kit4 Mobile Apps
> ```

TouchKit 4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hezamu** [comment]
*[documentation/articles/AutoGeneratingAFormBasedOnABeanVaadin6StyleForm.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBGh1-X6vhFJA5sAG:-KuPNdEa7QsvfA-Mkxik:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/AutoGeneratingAFormBasedOnABeanVaadin6StyleForm.asciidoc#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Vaadin 6
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hezamu** [comment]
*[documentation/articles/CreatingACustomFieldForEditingTheAddressOfAPerson.asciidoc, line 3 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBN2Ku6y8Kih1gWyl:-KuPNft53XEqZmxjlbDF:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/CreatingACustomFieldForEditingTheAddressOfAPerson.asciidoc#L3)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

duplicate order number
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hezamu** [comment]
*[documentation/articles/CreatingYourOwnConverterForString.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPB8SUqG3c8gD-aPxQ:-KuPNhWyiOFIX2gVuQJL:b-py4k2v) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/CreatingYourOwnConverterForString.asciidoc#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should the title be longer, or is this ok?
</blockquote></details>

This is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hezamu** [comment]
*[documentation/articles/MigratingFromVaadin7.0ToVaadin7.1.asciidoc, line 3 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPBQOU_67bY9GfeDIN:-KuPNjYhxJ9d-mTjJx-O:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/MigratingFromVaadin7.0ToVaadin7.1.asciidoc#L3)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

duplicate order number
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hezamu** [comment]
*[documentation/articles/OfflineModeForTouchKit4MobileApps.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10029#-KuPAr_Towrn6RxX47FS:-KuPNkoSiUX6ilw73YpJ:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/b6e17229e89c3451868c2afbeee9402283649c19/documentation/articles/OfflineModeForTouchKit4MobileApps.asciidoc#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TouchKit 4
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10029#-:-KuSi5IaXF59qG7FPdjT:bnfp4nl)*

**Pull request merged**
