### PR TITLE
Fix KeyMapper refreshing to use correct values

### LINKED ISSUE #9470: DataProvider.refreshItem(item) seems to not work with Grid
In Vaadin 8.0.5,

As I know that only one item has changed in my DataProvider, I tried to call DataProvider.refreshItem(item) of my provider to provoke the refresh but nothing change. (FYI: I defined "Object getId(T item)" in the DataProvider)

It works has expected when I used DataProvider.refreshAll()

Thanks,

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9470

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9505)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/KeyMapper.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/9505#-KmBLQ58uc-k5zJ1k6u0:-KmBLQ58uc-k5zJ1k6u1:b-9shq76) ([raw file](https://github.com/vaadin/framework/blob/759f980ac5a4f8d7082c01fc966e7805e3043362/server/src/main/java/com/vaadin/server/KeyMapper.java#L130)):*
>   objectKeyMap.remove(e.getKey());
Why keyObjectMap is not updated? Should it not be here:
` keyObjectMap.remove(objectKeyMap.remove(e.getKey()));` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9505)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/server/KeyMapper.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/9505#-KmBLQ58uc-k5zJ1k6u0:-KmBQwnfq0jDfNn9AjJJ:bzhb6t4) ([raw file](https://github.com/vaadin/framework/blob/759f980ac5a4f8d7082c01fc966e7805e3043362/server/src/main/java/com/vaadin/server/KeyMapper.java#L130)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>   objectKeyMap.remove(e.getKey());
Why keyObjectMap is not updated? Should it not be here:
` keyObjectMap.remove(objectKeyMap.remove(e.getKey()));` here?
</blockquote></details>

The String key of the keyObjectMap is the same as the value and is immediately re-used to store the new version of the dataObject. Not really a point in removing something just to put it back immediately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9505)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/KeyMapper.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/9505#-KmBLQ58uc-k5zJ1k6u0:-KmRYky5y3WV-MKtKuZG:bvv0j62) ([raw file](https://github.com/vaadin/framework/blob/759f980ac5a4f8d7082c01fc966e7805e3043362/server/src/main/java/com/vaadin/server/KeyMapper.java#L130)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The String key of the keyObjectMap is the same as the value and is immediately re-used to store the new version of the dataObject. Not really a point in removing something just to put it back immediately.
</blockquote></details>

I am not 100% sure but it seems to me there might be another object with the same id provided by the DataProvider. 
In any case I'd prefer to have this code a little bit less fragile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9505)*

**Comment by hesara** [comment]
Probably superceded by #9535

**Comment by tsuoanttila** [comment]
Agreed.

**Pull request closed without merging**
