### PR TITLE
Fix ComboBox icon with ConnectorResource (Fixes #9041)

### LINKED ISSUE #9041: ComboBox StreamResource as Icon is not working
Vaadin Version: 8.1.0.alpha3

Setting a StreamResource as Icon of a ComboBox is not working. The image is not shown and I get the following warning:

15:14:59,690 WARNING [com.vaadin.server.ConnectorResourceHandler] (default task-46) GelitaNamePicker (3583) did not handle connector request for null/USERNAME_usericon.jpg

I think the problem is in the function ComboBox.updateSelectedItemIcon():
```java
private void updateSelectedItemIcon() {
        String selectedItemIcon = null;
        T value = getDataCommunicator().getKeyMapper().get(getSelectedKey());
        if (value != null) {
            Resource icon = getItemIconGenerator().apply(value);
            if (icon != null) {
                selectedItemIcon = ResourceReference
                        .create(icon, ComboBox.this, null).getURL();
            }
        }
        getState().selectedItemIcon = selectedItemIcon;
    }
```

The ResourceReference is created with "null" as key-parameter.
This leads to the following URI: app://APP/connector/2/3583/null/USERNAME_usericon.jpg

The code for setting the StreamResource as Icon:

```java
setItemIconGenerator(user-> {
	Resource r = new ThemeResource("../mytheme/img/profile-pic-300px.jpg");
	try {
		if(user.getPicSmall() != null){ 
			StreamResource.StreamSource imageSource = () -> new ByteArrayInputStream(user.getPicSmall());
			r = new StreamResource(imageSource, user.getUsrid() + "_usericon.jpg");
		}
	}catch(Exception ex){}
	return r;
});
```

The ThemeResource is shown as expected

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10137)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 8 files at r1, 1 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0Znf0Veov32rF1RkN:-Kw0Znf0Veov32rF1RkO:b-ybtiza) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/server/src/main/java/com/vaadin/ui/ComboBox.java#L254)):*
> ```Java
>             Resource icon = getItemIconGenerator().apply(data);
>             if (icon != null) {
>                 setResource(itemToKey(data), icon);
> ```

ConnectorResources should probably be registered in the state for the connector for them to work correctly - especially for things like StreamResource. To properly clean them up, the data generator should then also override destroyData() and destroyAllData() to handle cleanup of the icons, and if the icon changes at runtime, clean up the old one in refreshData() as well. The class TreeRenderer has an example of using connector resources with a DataGenerator (similar to the first version of this PR but going a bit further).

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0XeFjpg611zC9OJky:-Kw0XeFjpg611zC9OJkz:b-dtss5q) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java#L28)):*
> ```Java
> 
>         cb.setItemIconGenerator(item -> {
>             System.out.println(new File(
> ```

Is this System.out still needed?

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java, line 28 at r4](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0a-GFkVgYJAl275yR:-Kw0a-GFkVgYJAl275yS:b-3dhss8) ([raw file](https://github.com/vaadin/framework/blob/effab778d6e82d7e240a131daa16500f395007d4/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java#L28)):*
> ```Java
> 
>         cb.setItemIconGenerator(item -> {
>             return new FileResource(new File(
> ```

A StreamResource would probably be a more challenging case, which cannot be resolved just based on the requested URL but requires bookkeeping in the state.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResourceTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0KaiB-KF-gF_EpMzb:-Kw0KaiB-KF-gF_EpMzc:b-rg26is) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResourceTest.java#L25)):*
> ```Java
>         cb.openPopup();
> 
>         WebElement optionsList = getDriver()
> ```

this could use ComboBoxElement.getSuggestionPopup() or even ComboBoxElement.getPopupSuggestionElements() to iterate over.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10137)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0Znf0Veov32rF1RkN:-KwB65jtLoTvccyT7uos:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/server/src/main/java/com/vaadin/ui/ComboBox.java#L254)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

ConnectorResources should probably be registered in the state for the connector for them to work correctly - especially for things like StreamResource. To properly clean them up, the data generator should then also override destroyData() and destroyAllData() to handle cleanup of the icons, and if the icon changes at runtime, clean up the old one in refreshData() as well. The class TreeRenderer has an example of using connector resources with a DataGenerator (similar to the first version of this PR but going a bit further).
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0XeFjpg611zC9OJky:-KwB66gDrUoQZ_iBNbIX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this System.out still needed?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java, line 28 at r4](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0a-GFkVgYJAl275yR:-KwB67W-0CpiseoyvCrE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/effab778d6e82d7e240a131daa16500f395007d4/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResource.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

A StreamResource would probably be a more challenging case, which cannot be resolved just based on the requested URL but requires bookkeeping in the state.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResourceTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10137#-Kw0KaiB-KF-gF_EpMzb:-KwB6uZ31qEnk8_KuQSU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d35ab4be3693a85c3afa92225140f05002a02c3/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxItemIconConnectorResourceTest.java#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this could use ComboBoxElement.getSuggestionPopup() or even ComboBoxElement.getPopupSuggestionElements() to iterate over.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10137)*

**Comment by hesara** [comment]
Partial review as the new test is still failing, mostly looking ok.

---

Reviewed 1 of 5 files at r2, 6 of 7 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 107 at r6](https://reviewable.io:443/reviews/vaadin/framework/10137#-KwF-LSbAGpjYCH5ub2A:-KwF-LSbAGpjYCH5ub2B:b5piqo9) ([raw file](https://github.com/vaadin/framework/blob/1ba84c7db2a298617fa28ec3031656566c1bfe1b/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L107)):*
> ```Java
>         private final String key;
>         private final String caption;
>         private String resourceUrl;
> ```

This name doesn't in any way indicate that this is only for the icon - perhaps iconUrl or such would be clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10137#-:-KwF-r2Fek-J1pXA8fi2:bw6g23o)*

**Comment by asashour** [comment]
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 107 at r6](https://reviewable.io:443/reviews/vaadin/framework/10137#-KwF-LSbAGpjYCH5ub2A:-KxCKDL0jSdGrS0163fs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1ba84c7db2a298617fa28ec3031656566c1bfe1b/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L107)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This name doesn't in any way indicate that this is only for the icon - perhaps iconUrl or such would be clearer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10137)*

**Comment by tsuoanttila** [comment]
This most likely needs a merge with master.

**Pull request closed without merging**
