### PR TITLE
Add a maven plugin for formatting according to Eclipse settings

### PR DESCRIPTION
**Pull request by Legioth**
Running formatter:format will format all files in a submodule using an
embedded Eclipse compiler (based on Neon SR1 in the used version)
according to the regular formatting settings file.

I've also formatted all (non-compatibility) sources using the plugin to
verify that the formatting is indeed consistent with the formatting
output of the Eclipse Neon SR2 that we're currently suggesting as the
default IDE. This uncovered an issue with dangling single-line comments
that I've resolved by manually moving such comments to their own lines
instead. The issue has also been reported to the plugin maintainer.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8374)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 504 at r1](https://reviewable.io:443/reviews/vaadin/framework/8374#-KbkIS-HSHCYZe9ZypvX:-KbkIS-HSHCYZe9ZypvY:b83kmv6) ([raw file](https://github.com/vaadin/framework/blob/f59c370badcaedbf4afd8bd765a0417b8834908b/pom.xml#L504)):*
> ```XML
>                     </dependency>
>                 </dependencies>
>             </plugin>                 
> ```

Extra spaces. That's nice to have this in this particular PR. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8374)*

**Comment by Legioth** [comment]
Review status: 58 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 504 at r1](https://reviewable.io:443/reviews/vaadin/framework/8374#-KbkIS-HSHCYZe9ZypvX:-KbkKLuRh_U2oTgMBmRv:bd8831k) ([raw file](https://github.com/vaadin/framework/blob/f59c370badcaedbf4afd8bd765a0417b8834908b/pom.xml#L504)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra spaces. That's nice to have this in this particular PR. :)
</blockquote></details>

Oops. Fixed.

But the reasons those are there does kind of show why it would be a good idea to automatically enforce formatting – I didn't want to reformat the entire file since it caused lots of changes not related to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8374)*

**Comment by denis-anisimov** [comment]
Reviewed 58 of 59 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8374)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8374#-:-KbnqTJxPKApBYoro1vH:bnfp4nl)*

**Pull request merged**
