### PR TITLE
Fix NativeSelect inner component size.

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8737)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VNativeSelect.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8737#-KeIYh9zF8Cl6z4u4cAq:-KeIYhA-XxktORUpVyI6:b-pqufrn) ([raw file](https://github.com/vaadin/framework/blob/9a751d48796f62079cfb94c3ba62df58b6028737/client/src/main/java/com/vaadin/client/ui/VNativeSelect.java#L83)):*
> ```Java
>     @Override
>     public void setWidth(String width) {
>         super.setWidth(width);
> ```

Can this cause problems with custom themes, borders, padding, subpixel sizes etc.?  Would it be safer to use 100% as the size of the listBox and just set the size of the outer widget directly, or does that not work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by elmot** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VNativeSelect.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8737#-KeIYh9zF8Cl6z4u4cAq:-KeJaf1eaSNSwtYFpTPM:b9wp8iw) ([raw file](https://github.com/vaadin/framework/blob/9a751d48796f62079cfb94c3ba62df58b6028737/client/src/main/java/com/vaadin/client/ui/VNativeSelect.java#L83)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Can this cause problems with custom themes, borders, padding, subpixel sizes etc.?  Would it be safer to use 100% as the size of the listBox and just set the size of the outer widget directly, or does that not work?
</blockquote></details>

Good point. Reimplemented with 100% size

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by elmot** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8737#-KfkLROmA9MOu3c7BC2W:-KfkLROmA9MOu3c7BC2X:b-w9czut) (no related file):*
Do not merge this until fresh screenshots have been updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by hesara** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8737#-KfkLROmA9MOu3c7BC2W:-KfzjQTdNeDjz96DidPw:b-ediiz1) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Do not merge this until fresh screenshots have been updated
</blockquote></details>

Only VaadinIconSetTest seems to have screenshot issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by hesara** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VNativeSelect.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/framework/8737#-Kg-a7H79O-gMPfa4gvM:-Kg-a7H79O-gMPfa4gvN:bd5fb0w) ([raw file](https://github.com/vaadin/framework/blob/036a4ef06b20e0021197cc1aa0326c8cd48d57eb/client/src/main/java/com/vaadin/client/ui/VNativeSelect.java#L38)):*
> ```Java
>      */
>     public VNativeSelect() {
>         listBox.setWidth("100%");
> ```

Looking at the failed tests, it seems to me that the case of an undefined wide NativeSelect is causing issues. Most likely these two lines should be moved to the connector and only done when the size in the given direction is defined, and reset when the size in the given direction is undefined.

---

*[tests/screenshots, line 1 at r3](https://reviewable.io:443/reviews/vaadin/framework/8737#-Kg-aGkZ8eh5kUImd9h5:-Kg-aGkZ8eh5kUImd9h6:b-bl61yt) ([raw file](https://github.com/vaadin/framework/blob/036a4ef06b20e0021197cc1aa0326c8cd48d57eb/tests/screenshots#L1)):*
> ```
> Subproject commit b34376d7a98315719850d484124791ae9425cdb5
> ```

are these updates for this changeset, or unrelated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by elmot** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VNativeSelect.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/framework/8737#-Kg-a7H79O-gMPfa4gvM:-Kg0-JA75YjGt_gyTm-z:b-ivpywe) ([raw file](https://github.com/vaadin/framework/blob/036a4ef06b20e0021197cc1aa0326c8cd48d57eb/client/src/main/java/com/vaadin/client/ui/VNativeSelect.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Looking at the failed tests, it seems to me that the case of an undefined wide NativeSelect is causing issues. Most likely these two lines should be moved to the connector and only done when the size in the given direction is defined, and reset when the size in the given direction is undefined.
</blockquote></details>

I think it's better to fix the test. 
Undefined size of NativeSelect causes sudden component size changes because some random changes in the UI. In this particular test, the change is changed because of icon change somewhere else.

---

*[tests/screenshots, line 1 at r3](https://reviewable.io:443/reviews/vaadin/framework/8737#-Kg-aGkZ8eh5kUImd9h5:-Kg0-JgElGEBD0JSXHur:b8kuqab) ([raw file](https://github.com/vaadin/framework/blob/036a4ef06b20e0021197cc1aa0326c8cd48d57eb/tests/screenshots#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

are these updates for this changeset, or unrelated?
</blockquote></details>

All the screenshots related to VaadinIconSet are replaced due new NativeSelect width in the test
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by hesara** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VNativeSelect.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/framework/8737#-Kg-a7H79O-gMPfa4gvM:-KgEPKgau1KOuSR57eui:bk12czs) ([raw file](https://github.com/vaadin/framework/blob/036a4ef06b20e0021197cc1aa0326c8cd48d57eb/client/src/main/java/com/vaadin/client/ui/VNativeSelect.java#L38)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I think it's better to fix the test. 
Undefined size of NativeSelect causes sudden component size changes because some random changes in the UI. In this particular test, the change is changed because of icon change somewhere else.
</blockquote></details>

Added support for undefined width, but left the test with 100% - the test issues should not be due to NS but the other selects.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r4.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectWidthTest.java, line 22 at r6](https://reviewable.io:443/reviews/vaadin/framework/8737#-KgIllJLgWHKvmX8JVKD:-KgIllJMEuj1Bg3o0lLj:b42xwvg) ([raw file](https://github.com/vaadin/framework/blob/6f3586174db4ac75e15bef5030b59afa3f5fe5c4/uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectWidthTest.java#L22)):*
> @Ignore

Why is this test ignored?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by hesara** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectWidthTest.java, line 22 at r6](https://reviewable.io:443/reviews/vaadin/framework/8737#-KgIllJLgWHKvmX8JVKD:-KgJ-jEuQKinjRhnwLfa:b-886gsx) ([raw file](https://github.com/vaadin/framework/blob/6f3586174db4ac75e15bef5030b59afa3f5fe5c4/uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectWidthTest.java#L22)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> @Ignore

Why is this test ignored?
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by ahie** [comment]
Reviewed 1 of 3 files at r6.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8737)*

**Pull request merged**
