### PR TITLE
 Use Assert instead of MatcherAssert

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10177)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 36 of 173 files at r1, 7 of 17 files at r2.
Review status: 42 of 188 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10177)*

**Comment by tsuoanttila** [comment]
Review status: 42 of 188 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10177#-Kwda9eZ_33T27XBVbFw:-Kwda9e_1PzRS7NJrcV7:b-vmetev) (no related file):*
As @torok-peter mentioned to me face to face, the change from hamcrest to junit will result in seeing an `AssertionError: Assertion failed.` instead of the more descriptive message provided by hamcrest. As of right now since the tests are passing, it's not that much of a problem, but when someone makes a change that breaks something the test failure report will not tell what went wrong. To be able to merge this PR, we'd need a descriptive message to each of the changes assertions that describe the nature of  failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10177)*

**Comment by asashour** [comment]
Review status: 42 of 188 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10177#-Kwda9eZ_33T27XBVbFw:-Kwe9KjAAoe5XLDnLABi:b-ti970n) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

As @torok-peter mentioned to me face to face, the change from hamcrest to junit will result in seeing an `AssertionError: Assertion failed.` instead of the more descriptive message provided by hamcrest. As of right now since the tests are passing, it's not that much of a problem, but when someone makes a change that breaks something the test failure report will not tell what went wrong. To be able to merge this PR, we'd need a descriptive message to each of the changes assertions that describe the nature of  failure.
</blockquote></details>

Acknowledged.  I will make Hamcrest modifications have similar message as Hamcrest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10177)*

**Comment by asashour** [comment]
Review status: 39 of 184 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10177#-Kwda9eZ_33T27XBVbFw:-Kx7g4cNMuneOICDaWW-:b9uipr4) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Acknowledged.  I will make Hamcrest modifications have similar message as Hamcrest.
</blockquote></details>

Some Hamcrest usage were reverted, in which it shows a message better than done by `Assert`. Having an `Assert` in those cases makes the code not very nice.

On the other hand, some Hamcrest usage was removed, specially `is`, because the message printed in this case is similar to the `Assert` one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10177)*

**Pull request closed without merging**
