### PR TITLE
Simplify lambda expressions

### PR DESCRIPTION
**Pull request by asashour**
And remove unneeded 'return' keyword.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10198)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 83 of 83 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/treegrid/TreeGridConnector.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiIB9upcFT3Muq33pl:-KwiIB9upcFT3Muq33pm:b-ap93f0) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/client/src/main/java/com/vaadin/client/ui/treegrid/TreeGridConnector.java#L69)):*
> ```Java
>         registerRpc(FocusRpc.class, (rowIndex, cellIndex) -> 
>             getWidget().focusCell(rowIndex, cellIndex)
>         );
> ```

Pull this up to the end of previous line

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 757 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiJBH_cvj4e0kW4ypF:-KwiJBH_cvj4e0kW4ypG:buoeqb8) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L757)):*
> ```Java
>     private void attachDataProviderListener() {
>         dataProviderUpdateRegistration = getDataProvider()
>                 .addDataProviderListener(event -> getUI().access(() -> {
> ```

Here I would prefer the original version, as to me it is slightly more readable. The 2nd level lambda is so long, it would make sense to factor it out into a named method though, and then your change would be fine.

---

*[server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiKAz0Yio3uPbKR6su:-KwiKAz0Yio3uPbKR6sv:bw90yad) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java#L70)):*
> ```Java
> 
>         service.addServiceDestroyListener(
>                 (ServiceDestroyEvent event) -> destroy());
> ```

Do we need the explicit parameter type here?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4577 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiKkMgcp5oNS1Ur9n4:-KwiKkMgcp5oNS1Ur9n5:bryrp0d) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/ui/Grid.java#L4577)):*
> ```Java
>         /*
>          * thenComparing is defined to return a serializable comparator as long
>          * as both original comparators are also serializable
> ```

This comment is now breaking the flow of code, it should be moved before the previous line

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiLf3M8kxc1TaJFS-A:-KwiLf3M8kxc1TaJFS-B:b-kxeypb) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L90)):*
> ```Java
>      *            Map containing all types and corresponding data from the
>      *            {@code
>      *         DataTransfer} object.
> ```

Your code formatter doesn't give up :-D
Pull this up to the end of previous line and we're good.

---

*[server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNOnOp2gtNUoWhM0P:-KwiNOnOp2gtNUoWhM0Q:b-hu7kar) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java#L32)):*
> ```Java
>         addComponent(customField);
> 
>         ok.addClickListener((ClickEvent event) -> Notification.show("OK"));
> ```

`ClickEvent` and parenthesis could be removed I think

---

*[server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNVPufWNe_pn5JSQd:-KwiNVPufWNe_pn5JSQe:bps1s89) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java#L35)):*
> ```Java
> 
>         CaNCEL.addClickListener(
>                 (ClickEvent event) -> Notification.show("cancel"));
> ```

here too

---

*[server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNgANIYuwq_bLwzjG:-KwiNgANIYuwq_bLwzjH:b-2guby3) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java#L26)):*
> ```Java
>         Button b = new Button();
>         AtomicInteger counter = new AtomicInteger(0);
>         b.addClickListener((ClickEvent event) -> counter.incrementAndGet());
> ```

same here

---

*[server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNhU946kBg_tFdVWB:-KwiNhU946kBg_tFdVWC:bji28bi) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java#L66)):*
> ```Java
>     private void addClickListener(Button b) {
>         clicked = false;
>         b.addClickListener((ClickEvent ev) -> clicked = true);
> ```

and here

---

*[server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java, line 225 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNn9AIRn85RfNG8nR:-KwiNn9AIRn85RfNG8nS:b-yq3btr) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java#L225)):*
> ```Java
>         final boolean[] eventFired = new boolean[1];
>         ui.addComponentAttachListener(
>                 (ComponentAttachEvent event) -> eventFired[0] = event
> ```

and here?

---

*[server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java, line 238 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNohyIvrX-gkrcw3G:-KwiNohyIvrX-gkrcw3H:b-yq3btr) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java#L238)):*
> ```Java
>         final boolean[] eventFired = new boolean[1];
>         ui.addComponentDetachListener(
>                 (ComponentDetachEvent event) -> eventFired[0] = event
> ```

and here?

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragAndDropCardShuffle.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiT9lfwSvp_A_MCSWx:-KwiT9lfwSvp_A_MCSWy:b-3fzaei) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/main/java/com/vaadin/tests/dnd/DragAndDropCardShuffle.java#L134)):*
> ```Java
> 
>         dragSource
>                 .addDragEndListener(event -> log(event.getComponent().getValue()
> ```

That line wrap looks stupid IMHO, the above is better

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiTki9puv-uYuDkyuG:-KwiTki9puv-uYuDkyuH:bi6f3s9) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L90)):*
> ```Java
>                         public void streamingFinished(StreamingEndEvent event) {
>                             gridItems
>                                     .add(new FileParameters(event.getFileName(),
> ```

another pointless line wrap, please remove

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiUWMcNyJzIFlHtOK2:-KwiUWMcNyJzIFlHtOK3:b-feg8jb) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L25)):*
> ```Java
> 
>     private static final Predicate<TestBenchElement> THEME_RESOURCE = e -> e
>             .isElementPresent(By.tagName("img"))
> ```

line break at the wrong place, please reformat; also below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198)*

**Comment by asashour** [comment]
All the files are automatically formatted, according to `VaadinJavaConventions.xml` with Eclipse Oxygen, on `Save Actions`.

I guess I should stick to what the team uses, if it uses the Formatter, then we should follow it, otherwise there is no point to manually do changes, and then someone will auto-reformat later.

If the team doesn't use formatter, then I won't as well.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198#-:-KwiZ0SqLfIZtAkQwcPs:b-d2ugdu)*

**Comment by torok-peter** [comment]
The team is using the formatter, however formatting across different IDEs is a controversial topic. We are currently reworking our formatting guidelines and may make these public once we fell it is ready for that.

Till then, you could make sure that the `Format all lines` option on the `Save Actions` tab is unchecked; preferably use the `Format edited lines` instead, to minimize conflicts.

IMHO the Eclipse formatter is not 100% perfect, sometimes it makes the code less readable. In these cases, I would prefer manual adjustment. But I will ask @teemusa's opinion on this.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198#-:-Kwiduhx5qOvjnchr5dq:b-2f0tzh)*

**Comment by asashour** [comment]
> IMHO the Eclipse formatter is not 100% perfect, sometimes it makes the code less readable. In these cases, I would prefer manual adjustment.


In other projects, Checkstyle can be used for all formatting checks, regardless of the IDE.  Currently Checkstyle and Java warnings are around 43k, which I guess need focus (either to fix them or changes the issues severity).

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198#-:-KwimwDI9MRnvtlXr-3o:budnpm2)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/treegrid/TreeGridConnector.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiIB9upcFT3Muq33pl:-KwjcEnyd4t4OttfmdLh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/client/src/main/java/com/vaadin/client/ui/treegrid/TreeGridConnector.java#L69)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Pull this up to the end of previous line
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 757 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiJBH_cvj4e0kW4ypF:-KwjcRLgiONafc2zmpiy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L757)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Here I would prefer the original version, as to me it is slightly more readable. The 2nd level lambda is so long, it would make sense to factor it out into a named method though, and then your change would be fine.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java, line 70 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiKAz0Yio3uPbKR6su:-KwjcXcdER_IxQsdAJut:bkgu9vl) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/server/communication/PushRequestHandler.java#L70)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Do we need the explicit parameter type here?
</blockquote></details>

No, some people put it if it not intuitive.Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4577 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiKkMgcp5oNS1Ur9n4:-Kwjd0i2CCvVt_eCtpcV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/ui/Grid.java#L4577)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This comment is now breaking the flow of code, it should be moved before the previous line
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiLf3M8kxc1TaJFS-A:-KwjdYCeCo8en8VfCJ9j:b64r8ur) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L90)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Your code formatter doesn't give up :-D
Pull this up to the end of previous line and we're good.
</blockquote></details>

Done.File revert, then only needed changes applied.

---

*[server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNOnOp2gtNUoWhM0P:-Kwje8vRn_Mh-anbF2z9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java#L32)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

`ClickEvent` and parenthesis could be removed I think
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNVPufWNe_pn5JSQd:-KwjeA1pHtUUPPz82RBn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/design/designroot/ExtendedDesignWithEmptyAnnotation.java#L35)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNgANIYuwq_bLwzjG:-KwjeI_3U-cKoM1B9QS1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java#L26)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNhU946kBg_tFdVWB:-KwjeJ6BANsQIsov2uhz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/button/ButtonClickTest.java#L66)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java, line 225 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNn9AIRn85RfNG8nR:-KwjeRoWgfCu45lU9EOU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java#L225)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

and here?
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java, line 238 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiNohyIvrX-gkrcw3G:-KwjeVY7A2nDuCzRYWvq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/server/src/test/java/com/vaadin/tests/server/component/window/AttachDetachWindowTest.java#L238)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

and here?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragAndDropCardShuffle.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiT9lfwSvp_A_MCSWx:-KwjeoQEmlUA5wJvXhEZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/main/java/com/vaadin/tests/dnd/DragAndDropCardShuffle.java#L134)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

That line wrap looks stupid IMHO, the above is better
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiTki9puv-uYuDkyuG:-Kwjf58et1pId3jr9W1l:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L90)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

another pointless line wrap, please remove
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10198#-KwiUWMcNyJzIFlHtOK2:-KwjfY2g3WhlfsFJY5bB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1d722cbad884347fd1cd6ea7de26523c07cc1cb2/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L25)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

line break at the wrong place, please reformat; also below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10198#-:-KwjmuNoKryyJoKGv28I:bnfp4nl)*

**Pull request merged**
