### PR TITLE
Create StringToUuidConverter.java

### LINKED ISSUE #11051: String-to-UUID Converter.
[This issue parallels one posted to Vaadin Flow 10, [Issue # 4400](https://github.com/vaadin/flow/issues/4400).]

Vaadin 8 Framework offers several handy implementations of [`Converter`](https://vaadin.com/download/release/8.4/8.4.5/docs/api/com/vaadin/data/Converter.html) such as `StringToBooleanConverter` and `StringToIntegerConverter`. 

I suggest adding another for the common type [`java.util.UUID`](https://docs.oracle.com/javase/10/docs/api/java/util/UUID.html) for [Universally unique identifier (UUID)](https://en.wikipedia.org/wiki/Universally_unique_identifier
) values. UUID values are common in enterprise apps for generating identifiers without needing a central registration authority. 

The 128 bits of a UUID are canonically presented as five groups of hexadecimal digits separated by a hyphen, such as `ab664df2-8859-11e8-9a94-a6cf71072f73`, as discussed [in Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), the [`java.util.UUID::toString`](https://docs.oracle.com/javase/10/docs/api/java/util/UUID.html#toString()) JavaDoc, and the [RFC 4122](https://tools.ietf.org/html/rfc4122) spec.

The implementation is utterly simple, with only two core lines of code:

    String s = myUuid.toString() ;

and 

    UUID myUuid = UUID.fromString( s ) ;

Attached is a single _StringToUuidConverter.java.txt_ file, my take on an implementation. (GitHub would not accept .java, so I appended .txt to the file name.)

[StringToUuidConverter.java.txt](https://github.com/vaadin/framework/files/2195959/StringToUuidConverter.java.txt)

### PR DESCRIPTION
**Pull request by basil-bourque**
Implements the `Converter` interface, to support converting back-and-forth between `String` and `UUID` (a type built into Java 5 and later).

Fixes #11051 

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @basil-bourque)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11387#-LU4myEtBTd4vHKE1yT-:-LU4myEtBTd4vHKE1yT0:b1q6b6x) (no related file):*
Hi Thanks for the contribution :-)

---
___
*[server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java, line 39 at r1](https://reviewable.io/reviews/vaadin/framework/11387#-LU4q01mEvJTj0EBccZB:-LU4q01n1yb4kq9W9kuP:burolmq) ([raw file](https://github.com/vaadin/framework/blob/3ede6e4d9a88a2a4757f5a9e2fd8174b42671afb/server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java#L39)):*
> ```
> @since 13.0
> ```

Leave this since tag empty, please. By the way, Framework 8 is not following the platform versions. 

By the way, you should run the code formatter for your code to follow the Vaadin Java Conventions (https://github.com/vaadin/framework/blob/master/eclipse/VaadinJavaConventions.xml), there will be some extra spaces removing and brace usage changes.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @basil-bourque)

___
*[server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java, line 61 at r1](https://reviewable.io/reviews/vaadin/framework/11387#-LU4sU8S4hhzS8y4OSHK:-LU4sU8S4hhzS8y4OSHL:b-m7dcr) ([raw file](https://github.com/vaadin/framework/blob/3ede6e4d9a88a2a4757f5a9e2fd8174b42671afb/server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java#L61)):*
> ```
>  * @since 8.4
> ```
leave this one empty too.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @basil-bourque)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11387#-LU4myEtBTd4vHKE1yT-:-LU5nCCDEVn5ymAF2dwG:byehlby) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Hi Thanks for the contribution :-)
</blockquote></details>

Could you add some tests for this converter? You can find similar tests from this package https://github.com/vaadin/framework/tree/master/server/src/test/java/com/vaadin/tests/data/converter 

---

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pleku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: all files reviewed, 1 unresolved discussion (waiting on @basil-bourque)

___
*[server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java, line 39 at r1](https://reviewable.io/reviews/vaadin/framework/11387#-LU4q01mEvJTj0EBccZB:-Lc4r76E518g5U2qehx2:blj2nuk) ([raw file](https://github.com/vaadin/framework/blob/3ede6e4d9a88a2a4757f5a9e2fd8174b42671afb/server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java#L39)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> @since 13.0
> ```

Leave this since tag empty, please. By the way, Framework 8 is not following the platform versions. 

By the way, you should run the code formatter for your code to follow the Vaadin Java Conventions (https://github.com/vaadin/framework/blob/master/eclipse/VaadinJavaConventions.xml), there will be some extra spaces removing and brace usage changes.
</blockquote></details>

@zhesun88 can you remove the version ? (e.g. in github IDE)

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: all files reviewed, 1 unresolved discussion (waiting on @pleku)

___
*[server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java, line 39 at r1](https://reviewable.io/reviews/vaadin/framework/11387#-LU4q01mEvJTj0EBccZB:-Lc57iqpDzVvfhEgs0Xp:bkd4gg2) ([raw file](https://github.com/vaadin/framework/blob/3ede6e4d9a88a2a4757f5a9e2fd8174b42671afb/server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java#L39)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

@zhesun88 can you remove the version ? (e.g. in github IDE)
</blockquote></details>

It has been removed in the `r2`. together with the tag below.

```
New commits in r2 (8547ca5) at 2019-04-02 12:29:03Z by anasmi:

fd27178 by  pleku: Formatting cleanup, remove sinces
```

**Review by pleku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11387)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java, line 39 at r1](https://reviewable.io/reviews/vaadin/framework/11387#-LU4q01mEvJTj0EBccZB:-Lc66DpL2NuCKBgZuCls:b-ytthi8) ([raw file](https://github.com/vaadin/framework/blob/3ede6e4d9a88a2a4757f5a9e2fd8174b42671afb/server/src/main/java/com/vaadin/data/converter/StringToUuidConverter.java#L39)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

It has been removed in the `r2`. together with the tag below.

```
New commits in r2 (8547ca5) at 2019-04-02 12:29:03Z by anasmi:

fd27178 by  pleku: Formatting cleanup, remove sinces
```
</blockquote></details>

how wonderful of me, but reviewable truly sucks

**Pull request merged**
