### PR TITLE
Redesign user-defined column identifiers for Grid

### PR DESCRIPTION
**Pull request by tsuoanttila**
Closes vaadin/framework8-issues#494

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7983)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 790 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxd9y760qvtvAuK3zL:-KYxd9y760qvtvAuK3zM:b27702z) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L790)):*
> ```Java
> 
>         @Override
>         public void contextClick(int rowIndex, String rowKey, String columnId,
> ```

For clarity, `columndId` could be renamed `internalId`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 837 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxd1_KBWGTQDYgWSRQ:-KYxd1_KBWGTQDYgWSRR:b-yrsbv3) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L837)):*
> ```Java
> 
>         @Override
>         public void columnVisibilityChanged(String id, boolean hidden) {
> ```

For clarity, `id` could be renamed `internalId`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 847 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxd8NZxgj5tFTRx0wX:-KYxd8NZxgj5tFTRx0wY:b-yrsbv3) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L847)):*
> ```Java
> 
>         @Override
>         public void columnResized(String id, double pixels) {
> ```

For clarity, `id` could be renamed `internalId`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 998 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxcv4yXkIo0xJX6rgZ:-KYxcv4yXkIo0xJX6rg_:b-5b5wqg) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L998)):*
> ```Java
>         private SerializableFunction<T, Component> componentGenerator;
> 
>         private String id;
> ```

For clarity, this could be named as `userDefinedId`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1150 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxdHJXuSzgHrwBTOqs:-KYxdHJXuSzgHrwBTOqt:bbuuodc) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L1150)):*
> ```Java
> 
>         /**
>          * Returns the identifier used with this Column in communication.
> ```

Update javadocs to mention that this is an internal ID.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1154 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxdMLBgAXXg9HJ0n0Z:-KYxdMLBgAXXg9HJ0n0_:b-pcb0kw) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L1154)):*
> ```Java
>          * @return the identifier string
>          */
>         public String getInternalId() {
> ```

Maybe this should be `protected` instead of public ?

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxefu04bKiTZWPahnF:-KYxefu04bKiTZWPahnG:bzbr33m) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L173)):*
> ```Java
> 
>         /**
>          * Returns the cell in this section that corresponds to the given column
> ```

user given column id

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 177 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxeeMK8Gl9Ff72V1ct:-KYxeeML_UbI6tL4ANdl:bzbr33m) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L177)):*
> ```Java
>          *
>          * @param columnId
>          *            the id of the column
> ```

user given column id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by pleku** [comment]
Reviewed 4 of 6 files at r2.
Review status: 18 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by tsuoanttila** [comment]
Review status: 17 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 998 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxcv4yXkIo0xJX6rgZ:-KZ0ds2YABvQf2YQLt3p:b1yux15) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L998)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

For clarity, this could be named as `userDefinedId`
</blockquote></details>

I was thinking if it breaks the java introspection if it's named differently than it's getter and setter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by Legioth** [comment]
Review status: 17 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 998 at r1](https://reviewable.io:443/reviews/vaadin/framework/7983#-KYxcv4yXkIo0xJX6rgZ:-KZ0gvqpGjN4Tm5hRvgP:buin6mz) ([raw file](https://github.com/vaadin/framework/blob/f74b8f9a55eb701793378d3409cd5068c712ade2/server/src/main/java/com/vaadin/ui/Grid.java#L998)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I was thinking if it breaks the java introspection if it's named differently than it's getter and setter.
</blockquote></details>

Java introspection doesn't are about private members at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by pleku** [comment]
Reviewed 2 of 6 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7983)*

**Pull request merged**
