### PR TITLE
Introduce reference item and fetch items relative to it

### LINKED ISSUE #10317: TreeGrid loads all data from the data provider when scroll position changes
For fetching hierarchical data (for TreeGrid) the HierarchyMapper is used. Method

`public Stream<T> fetchItems(Range range)`

is invoked every time the current scroll position of the Tree(Grid) changes. What happens is that the hierarchy is retrieved, and then in memory stream operations are done to skip to and limit the correct amount of data shown like this:

`return getHierarchy(null).skip(range.getStart()).limit(range.length());`

 This will effectively for every scroll position change load ALL data from the backing data provider. Needless to say this will slow down any lazy loading intended hierarchical grids to crawl if there's more than trivial amount of data.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #10317

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10378)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-Kzybd3bRQs5rJsymOAj:-Kzybd3bRQs5rJsymOAk:b-3u7ira) (no related file):*
This PR is work in progress, needs more testing, better cache handling and further optimisation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-Kzybd3bRQs5rJsymOAj:-L-BW2DpIjz5FMf0kXnS:b-bj8vzs) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

This PR is work in progress, needs more testing, better cache handling and further optimisation.
</blockquote></details>

What is the current status? Can I test it out and review it? Or is it still in progress?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-Kzybd3bRQs5rJsymOAj:-L-GYqd4f7Kwayapq0C6:b-d4etj5) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What is the current status? Can I test it out and review it? Or is it still in progress?
</blockquote></details>

I added some more javadoc and some optimisation. Still need to work on clearing cache properly, but otherwise please review if you have time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 677 at r3](https://reviewable.io:443/reviews/vaadin/framework/10378#-L-Ga_lS4e7EaV7Fs-tM:-L-Ga_lS4e7EaV7Fs-tN:b-xfj4pk) ([raw file](https://github.com/vaadin/framework/blob/736f47257b0f72a58c85b57554800675e63d9ec5/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L677)):*
> ```Java
>             siblingIndex.put(id, index++);
>             parentMap.put(id, parent);
>         }
> ```

It should be enough to keep the items of _currently visible range_, _expanded_ and _selected_ items, but it's hard to determine which ones are those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-Kzybd3bRQs5rJsymOAj:-L-X_PFfix93bLL51zvW:bszfju0) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

I added some more javadoc and some optimisation. Still need to work on clearing cache properly, but otherwise please review if you have time.
</blockquote></details>

Test still fails in some cases when adding/removing items, because reference is not up to date. I'll investigate if `DataCommunicator#activeData` can be used to track current items.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-Kzybd3bRQs5rJsymOAj:-L-kslRNKug1Su5Gr3UY:bfhbqdg) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Test still fails in some cases when adding/removing items, because reference is not up to date. I'll investigate if `DataCommunicator#activeData` can be used to track current items.
</blockquote></details>

Patch now passes tests, please proceed with the review when you have time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-L4kZp4PeG1I8G4YcRXS:-L4kZp4PeG1I8G4YcRXT:bexgu7h) (no related file):*
Can you shortly describe the benefit we gain from the use of the reference item and how does it affect the flow of fetching new items? I did read through the code but not sure if I caught everything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10378#-L4kZp4PeG1I8G4YcRXS:-L4kjNhdyiuR1AJJD9Ke:b-ephln3) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Can you shortly describe the benefit we gain from the use of the reference item and how does it affect the flow of fetching new items? I did read through the code but not sure if I caught everything.
</blockquote></details>

The purpose of the patch is to reduce overhead of fetching all of the hierarchy when data is lazily loaded and all we need is a subset of the data or the index of a specific item.

The introduction of a reference item in a large data set helps traversing the tree more efficiently as it allows fetching items around the reference item such that
- if we are looking for an item after or before the reference, there is no need to fetch all items from index zero, but rather it is possible to fetch reference's children/siblings/parent etc.
- items can be fetched iteratively with a deep search until the required number of items are found

It is important to position the reference item well because the amount of work needed is proportional to the required items' distance from the reference.

Ideally we would know which items are present on the client and would use them as reference since in most cases (but not exclusively) fetch is performed before or after the client's data set.

The two main methods are `fetchItemsAfter()` and `fetchItemsBefore()` that fetch items after or before the reference item, respectively.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by tsuoanttila** [comment]
Merge conflict, please rebase.

**Comment by wbadam** [comment]
@tsuoanttila let me know if you need help with this, I'll have some time this week

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r15.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10378)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r14, 1 of 2 files at r15.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 677 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L-Ga_lS4e7EaV7Fs-tM:-L82qUqcEJ9dAAqGiTtx:b-tas4es) ([raw file](https://github.com/vaadin/framework/blob/736f47257b0f72a58c85b57554800675e63d9ec5/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L677)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

It should be enough to keep the items of _currently visible range_, _expanded_ and _selected_ items, but it's hard to determine which ones are those.
</blockquote></details>

FYI you're blocking this comment @wbadam

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 360 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kYobs7Dnn3t4cZA0b:-L4kYobt39AXCVCDEXPR:b-bq3h27) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L360)):*
> ```Java
>                     referenceItemIndex - range.getStart()).stream()
>                             .limit(range.length())
>                             .collect(Collectors.toList()));
> ```

rather than collect, do `.forEach(items::add)`. No need to wrap into a List in the middle of this operation.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 364 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kZQK9FQvyU4tSnRaX:-L4kZQK9FQvyU4tSnRaY:b-89urs2) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L364)):*
> ```Java
>             // Add the reference item to the list
>             if (range.contains(referenceItemIndex)) {
>                 items.add(referenceItem);
> ```

Does this work well when the reference item is updated through `DataProvider::refreshItem`? 

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 372 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kYxAdoZz-sA8MxUpz:-L4kYxAdoZz-sA8MxUq-:b1t71ae) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L372)):*
> ```Java
>                             .skip(Math.max(0,
>                                     range.getStart() - referenceItemIndex - 1))
>                             .collect(Collectors.toList()));
> ```

same thing with the collect.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 360 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kYobs7Dnn3t4cZA0b:-L8FN08W249r8mOEAjxc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L360)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

rather than collect, do `.forEach(items::add)`. No need to wrap into a List in the middle of this operation.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 372 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kYxAdoZz-sA8MxUpz:-L8FN0z26I3L08l8IRiq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L372)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

same thing with the collect.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 364 at r14](https://beta.reviewable.io/reviews/vaadin/framework/10378#-L4kZQK9FQvyU4tSnRaX:-L8_dE0j0tbbjAlnsVwp:b-4ft65n) ([raw file](https://github.com/vaadin/framework/blob/a25342d179359787f4db1bbb48d194312c25f2de/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L364)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Does this work well when the reference item is updated through `DataProvider::refreshItem`? 
</blockquote></details>

Reference item might needs to be reset also in that case. I'll do some tests and see what I can come up with

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10378)*

**Comment by wbadam** [comment]
Hi @tsuoanttila, what's the status of this one, is this issue still outstanding? Seems like there is need for rebasing again, so I'll wait until you confirm.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10378#-:-LBtJGgu1tkxefVYBhRi:bvlzhlw)*

**Comment by tsuoanttila** [comment]
This was used in a custom build for the project where the issue was raised from. They said it does help a bit but it's still major problem even with the fix. I think we might need to get back to the drawing board with this issue. Checking up with the project and others involved on the topic.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10378#-:-LBuMyboBpCNyigQh1Xs:b-bkmhbr)*

**Comment by pleku** [comment]
Since this is not working well enough, we're closing this PR.

**Pull request closed without merging**
