### PR TITLE
Make it possible for grid drop target to accept dragged data when grid is empty

### LINKED ISSUE #9068: Make it possible for GridDropTarget to accept dragged data when Grid is empty
Currently drop event listeners are added to rows and so an empty Grid cannot accept them.
Perhaps add listeners to the Grid body element when no rows are present.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #9068 
Replaces PR #9090

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9332)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkGUr6kWR8HKEzvhQzX:-KkGUr6kWR8HKEzvhQzY:b-l4y4nu) (no related file):*
Consider changing method to `public Optional<T> getDropTargetRow()` in `GridDropEvent` since it is not certain any more that a drop target row exists

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkGUr6kWR8HKEzvhQzX:-KkGbDnMVs0H6SR_K6uO:b2nign6) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Consider changing method to `public Optional<T> getDropTargetRow()` in `GridDropEvent` since it is not certain any more that a drop target row exists
</blockquote></details>

yes

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 171 at r1](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkGb0aO5H-D5lCZW0a3:-KkGb0aO5H-D5lCZW0a4:bs98fqz) ([raw file](https://github.com/vaadin/framework/blob/aa3b35d09228f0dfb45dde1a115a439736e22014/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L171)):*
> ```Java
>                     dataProvider.refreshAll();
> 
>                     boolean droppedOntoRow = event.getDropTargetRow() != null;
> ```

Yes I think you should make it optional, please remember to update the docs example code snippet too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Comment by wbadam** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 171 at r1](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkGb0aO5H-D5lCZW0a3:-KkHkkLFk6ety41a3pzc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa3b35d09228f0dfb45dde1a115a439736e22014/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L171)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Yes I think you should make it optional, please remember to update the docs example code snippet too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 339 at r2](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkHodDnxiLhONE5ssp1:-KkHodDnxiLhONE5ssp2:b-klzshq) ([raw file](https://github.com/vaadin/framework/blob/b9a62a278572390c8a432b6e1b2d4906453e1dc0/documentation/advanced/advanced-dragndrop.asciidoc#L339)):*
> ==== CSS Style Rules

I think you should include the added style name  .#{$primary-stylename}-body-droptarget` here too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Comment by wbadam** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 339 at r2](https://reviewable.io:443/reviews/vaadin/framework/9332#-KkHodDnxiLhONE5ssp1:-KkHxmy93FH3r5lFy6cK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b9a62a278572390c8a432b6e1b2d4906453e1dc0/documentation/advanced/advanced-dragndrop.asciidoc#L339)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ==== CSS Style Rules

I think you should include the added style name  .#{$primary-stylename}-body-droptarget` here too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9332)*

**Pull request merged**
