### PR TITLE
Wrong constructor in Grid.java (#9944)

### PR DESCRIPTION
**Pull request by JenoDK**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10075)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
:lgtm: after the CLA has been signed.

If you want to make it Even Better :tm: add a quick unit test to for example `com.vaadin.tests.server.component.grid.GridTest` that constructs a Grid with the class instance and a specific `DataCommunicator` and assert that `Grid::getDataCommunicator` returns the same instance.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10075#-:-KusVH86lJaeRmt5Dn5e:b-5965c8)*

**Comment by JenoDK** [comment]
> If you want to make it Even Better ™️ add a quick unit test to for example com.vaadin.tests.server.component.grid.GridTest that constructs a Grid with the class instance and a specific DataCommunicator and assert that Grid::getDataCommunicator returns the same instance.

Did not want to change visibility of

`protected Grid(Class<T> beanType, DataCommunicator<T> dataCommunicator)`

**Comment by hesara** [comment]
@JenoDK please also click the CLA button on the PR page in GitHub and accept the license agreement so we can integrate your contributions when they pass review.

**Comment by JenoDK** [comment]
I signed it, but it still shows up as unsigned in this pull request.

https://i.imgur.com/bdJVaPi.png

**Comment by hesara** [comment]
Could it be that the user name / e-mail you use in your commits is not linked to your GitHub account? I tried to force re-checking of PRs in CLA Assistant, but that didn't help.

**Comment by JenoDK** [comment]
@hesara Ah my bad, I probably committed using my work e-mail. I'll sort it out tomorrow at work.

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10075)*

**Comment by tsuoanttila** [comment]
Thanks for this patch @JenoDK!

Next time please make your Pull Request based on the `master` branch and targeting the `vaadin/framework` `master`. We will pick appropriate changes to the correct version branches.

I will pick this change immediately to `master` after this merge, so no need to worry about it.

**Comment by JenoDK** [comment]
@tsuoanttila No problem!

> Next time please make your Pull Request based on the master branch and targeting the vaadin/framework master.

Noted for next time.

**Pull request merged**
