### PR TITLE
Add helper for Grid row DnD

### PR DESCRIPTION
**Pull request by pleku**
Moved from #10036 since I was not able to push to that fork.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10255)

### CODE REVIEW

**Comment by pleku** [comment]
Comments on r1 are in https://reviewable.io/reviews/vaadin/framework/10036#-  all marked done except UITest

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255#-:-KxIEwSZJLVYNWPARPc0:b8uhmwr)*

**Comment by asashour** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHiWGMrpoer0dUGpQ:-KxIHiWGMrpoer0dUGpR:buo9nmt) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L35)):*
> ```Java
>  * @param <T> The Grid bean type.
>  * @author Stephan Knitelius
>  * @since 8.1
> ```

Same here

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHtbPMHsnr_JubKjn:-KxIHtbPMHsnr_JubKjo:bwyxmoh) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L154)):*
> ```Java
>     }
> 
>     public void setGridTargetWriter(GridTargetWriter<T> gridTargetWriter) {
> ```

Javadoc

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 158 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHvdTsQ7qEtzksz8M:-KxIHvdUdlDb7coZ5aGy:bwyxmoh) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L158)):*
> ```Java
>     }
> 
>     public void setGridSourceWriter(GridSourceWriter<T> gridSourceWriter) {
> ```

Javadoc

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 162 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHwR46HAnGx_KE5c3:-KxIHwR46HAnGx_KE5c4:bwyxmoh) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L162)):*
> ```Java
>     }
> 
>     public void setGrid(GridDropTargetIndex<T> gridDropTargetIndex) {
> ```

Javadoc

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDropTargetIndex.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHTT2b_DMJ-K1M5Kv:-KxIHTT3sN91GcXdGErz:b1utdhv) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDropTargetIndex.java#L25)):*
> ```Java
>  * Used to calculate the target index of the dropped items.
>  * 
>  * @author Stephan Knitelius
> ```

I don't think we have `@author` with developer name, in other places

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDropTargetIndex.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIHaQq16Yvok3wCcVo:-KxIHaQq16Yvok3wCcVp:b-m45jfv) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridDropTargetIndex.java#L26)):*
> ```Java
>  * 
>  * @author Stephan Knitelius
>  * @since 8.1
> ```

Should have empty version

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridSourceWriter.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxII1OW0YkqWxNwZoos:-KxII1OW0YkqWxNwZoot:buo9nmt) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridSourceWriter.java#L28)):*
> ```Java
>  * 
>  * @author Stephan Knitelius
>  * @since 8.1
> ```

Same here

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridTargetWriter.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxII3dkD5oIvNdOkZot:-KxII3dkD5oIvNdOkZou:buo9nmt) ([raw file](https://github.com/vaadin/framework/blob/8b97e0524a871bf0194757a2d1133c6ea805c5b8/server/src/main/java/com/vaadin/ui/components/grid/GridTargetWriter.java#L27)):*
> ```Java
>  * 
>  * @author Stephan Knitelius
>  * @since 8.1
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by asashour** [comment]
All points are resolved in `r2`, with a possibly hint about `@author` with author name

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255#-:-KxIJ2ZRWhGcdyAAExh0:bqk02xb)*

**Comment by pleku** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 369 at r2](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIXuRE3Qi3fJEq3of3:-KxIXuRE3Qi3fJEq3of4:b-29iaap) ([raw file](https://github.com/vaadin/framework/blob/a718de8bae7dc1c56695fd90fcd52f4ce984c048/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L369)):*
> ```Java
>                     .getDataProvider();
>             List<T> targetItems = new ArrayList<>(listDataProvider.getItems());
>             targetItems.addAll(index, droppedItems);
> ```

This explodes currently when the source and target grids are the same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by pleku** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 369 at r2](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIXuRE3Qi3fJEq3of3:-KxIYLlf5VRPGv6UHDdA:baeavat) ([raw file](https://github.com/vaadin/framework/blob/a718de8bae7dc1c56695fd90fcd52f4ce984c048/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L369)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This explodes currently when the source and target grids are the same
</blockquote></details>

And when `addItemsToEnd` has been set to `true` and dragging between two grids

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by tsuoanttila** [comment]
Reviewed 8 of 9 files at r2, 1 of 5 files at r3.
Review status: 6 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/DropIndexCalculator.java, line 24 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSOMpAqE12E0u2VUr4:-KxSOMpAqE12E0u2VUr5:b-sxutxg) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/DropIndexCalculator.java#L24)):*
> ```Java
>  * grid.
>  *
>  * @author Stephan Knitelius
> ```

So it's decided to keep the second `@author` in the JavaDocs?

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 185 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSQ6CjoS0YRRHo3FTb:-KxSQ6Ckiinmbh91SDrd:bhj8oc1) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L185)):*
> ```Java
>      *            the target drop handler to set, or {@code null} to remove
>      */
>     public void setTargetGridDropHandler(
> ```

mismatch of method name and field name. Which name should we use?

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 195 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSQesXfg6abnz5YU32:-KxSQesXfg6abnz5YU33:b2ss7xm) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L195)):*
> ```Java
>      * @return target grid drop handler
>      */
>     public TargetDataProviderUpdater<T> getTargetGridDropHandler() {
> ```

see comment above

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 294 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSR6ps32aT8Kpa89Az:-KxSR6ptWaFpPDVmfA7F:b6mtw8c) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L294)):*
> ```Java
>      */
>     public void setAddItemsToEnd(boolean addItemsToEnd) {
>         this.addItemsToEnd = addItemsToEnd;
> ```

Instead of having mystical boolean controls, should we provide couple of basic implementations of DropIndexCalculator and make the user use those instead of  `if (crypticBoolean) { behaveDifferently(); }`

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 324 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSRa2wh0zul1zsu1EH:-KxSRa2wh0zul1zsu1EI:bxfzz7t) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L324)):*
> ```Java
>      */
>     public void setRemoveItemsFromSource(boolean removeFromSource) {
>         this.removeFromSource = removeFromSource;
> ```

Same question as with the addItemToEnd, rather have a DragSourceUpdated that does not remove stuff (no-op). Yes I know this is a "main feature" but still, controlling wether to call a user defined custom solution based on a boolean without direct correlation is a bit iffy.

<em>Note: Notes are not that easy to find and you lose sight of them if there's one in every method.</em>

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSZTQIri64WnNbeQkP:-KxSZTQIri64WnNbeQkQ:b-au0y6b) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
> ```Java
>             Collection<T> droppedItems) {
>         Grid<T> target = getGridDropTarget().getGrid();
>         if (targetDataProviderUpdater == null) {
> ```

I'd still want to have this as "never null" and have some basic implementation determined during construction. Preferrably throwing if non-matching data providers.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 380 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSZm7_OlT9PNboHFNG:-KxSZm7_OlT9PNboHFNH:b-w7rdgc) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L380)):*
> ```Java
> 
>     private int calculateDropIndex(GridDropEvent<T> event) {
>         if (getDropIndexCalculator() == null) {
> ```

default implementation vs. "if null do stuff"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by pleku** [comment]
Review status: 6 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/DropIndexCalculator.java, line 24 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSOMpAqE12E0u2VUr4:-KxlUuS4lt7bF5gnjX0B:b-nsjmuk) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/DropIndexCalculator.java#L24)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

So it's decided to keep the second `@author` in the JavaDocs?
</blockquote></details>

Done. We should stick to the FW used practice in these files too

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 185 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSQ6CjoS0YRRHo3FTb:-KxlV1gtYaMS3VtNWnSu:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L185)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

mismatch of method name and field name. Which name should we use?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 195 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSQesXfg6abnz5YU32:-KxlWqh3tn5ZpJbZL_jH:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L195)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 294 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSR6ps32aT8Kpa89Az:-KxlYI8XjGOS69lAK-z2:btxy055) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L294)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Instead of having mystical boolean controls, should we provide couple of basic implementations of DropIndexCalculator and make the user use those instead of  `if (crypticBoolean) { behaveDifferently(); }`
</blockquote></details>

I agree. I think this brings very little value and much more confusion and complexity, I removed it as it can be easily achieved with the drop data source updater.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 324 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSRa2wh0zul1zsu1EH:-KxlikCs5Ba77lBGVmLB:by2r5dh) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L324)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Same question as with the addItemToEnd, rather have a DragSourceUpdated that does not remove stuff (no-op). Yes I know this is a "main feature" but still, controlling wether to call a user defined custom solution based on a boolean without direct correlation is a bit iffy.

<em>Note: Notes are not that easy to find and you lose sight of them if there's one in every method.</em>
</blockquote></details>

Agree. It is gone.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSZTQIri64WnNbeQkP:-KxlYiuq5vlTqwySlCjW:b9sn15x) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd still want to have this as "never null" and have some basic implementation determined during construction. Preferrably throwing if non-matching data providers.
</blockquote></details>

IMO there are discoverability issues with _default implementations_ in comparison to having _default behavior_. And looking at the behavior on usage:
- `setFoo(null)` to always explode
  - need to read and discover there is something like `setFoo(new DefaultTargetDataProviderUpdater());` you should use instead
- `setFoo((null)` to use the default working data provider. This is what I expect in most cases when `null` is accepted, _to revert to default_. If you're not reading the javadocs, you though just trusting it works and not necessarily thinking. 
For me the default implementation in this case just doesn't seem more sensible.

The whole use case of switching data provider from in-memory to lazy is quite rare, but there probably are some. We could even make it so that you need to remove the `GridDragger` and set a new one when changing data providers, but I don't think that is a better option.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 380 at r3](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxSZm7_OlT9PNboHFNG:-Kxl_fBo4gShGiWQQvQ5:bop92cg) ([raw file](https://github.com/vaadin/framework/blob/14c8ddb2e64cd0237b73b9fd6c3c810d6f42d9e2/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L380)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

default implementation vs. "if null do stuff"
</blockquote></details>

Same reasoning as with `TargetDataSourceUpdater` and `SourceDataProviderUpdater`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by pleku** [comment]
Review status: 0 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 369 at r2](https://reviewable.io:443/reviews/vaadin/framework/10255#-KxIXuRE3Qi3fJEq3of3:-Kxnw01BVeOJVoXcJFy5:bwpkdzb) ([raw file](https://github.com/vaadin/framework/blob/a718de8bae7dc1c56695fd90fcd52f4ce984c048/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L369)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

And when `addItemsToEnd` has been set to `true` and dragging between two grids
</blockquote></details>

Fixed and tests added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 9 files at r2, 5 of 9 files at r5, 3 of 5 files at r6, 7 of 7 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 277 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqci-cmP7GaPR93IUo:-Kxqci-cmP7GaPR93IUp:bvn7nm9) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L277)):*
> ```Java
>      * @return the currenytly dragged items or {@code null}
>      */
>     public Set<T> getDraggedItems() {
> ```

public?

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqdv7nvr0HzdgJOqRZ:-Kxqdv7nvr0HzdgJOqR_:b-ejwbug) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
> ```Java
>         // can potentially have something else than a list
>         if (index != Integer.MAX_VALUE && targetItems instanceof List) {
>             ((List<T>) targetItems).addAll(index, droppedItems);
> ```

I have a feeling that the whole add to specific index is going to run into problems when there filtering or sorting involved. The indices provided by grid will have absolutely no correlation with the real indices in the data set.

To be completely honest, I'd suggest the default to be always "drop to end" and if you want something else, you implement it yourself. This will reduce the amount of surprises to the user.

What does it mean if all items are sorted by a criteria and rows are dragged on a row. Does the user want the data to be dropped after the specific row or in that index in the original data set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 71 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxr1-U4TxEACwRvMTVb:-Kxr1-U4TxEACwRvMTVc:b-1jikih) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L71)):*
> ```Java
>      */
>     public GridDragger(Grid<T> grid) {
>         this(grid, grid, DropMode.BETWEEN);
> ```

Call `this(grid, DropMode.BETWEEN)` instead of the two Grid constructor. Might want to take Grid and List and do some special magic. See comment in the next constructor.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 89 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxr15R8uaHzUuR7jtKg:-Kxr15R972ljJs5pcYZ5:bv6l2mr) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L89)):*
> ```Java
>      *            DropMode to be used.
>      */
>     public GridDragger(Grid<T> grid, DropMode dropMode) {
> ```

The more I think of this issue, this should be a special case of this GridDragger that should get the backing data as a list, construct it's own list data provider and register the custom updaters to make it work. It's kind of surprising and unintuitive that using Set instead of a List as the backing data, everything gets messed up.

Provided we get the Grid and the data in a List we can manage the lifecycle and data content in the scope of this Constructor. This would simplify the default case and make this specific issue, well, specific.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by pleku** [comment]
Waiting for #10290 and #10296

**Comment by tsuoanttila** [comment]
Waiting is done, please rebase

**Comment by pleku** [comment]
Done

---

Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 71 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxr1-U4TxEACwRvMTVb:-Ky00cpEQqGErj4hTnLJ:b8ilz05) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L71)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Call `this(grid, DropMode.BETWEEN)` instead of the two Grid constructor. Might want to take Grid and List and do some special magic. See comment in the next constructor.
</blockquote></details>

Yes for the first, no for the second.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 89 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxr15R8uaHzUuR7jtKg:-Ky00er2tm7E-Qx5eFyd:b-gzl943) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L89)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The more I think of this issue, this should be a special case of this GridDragger that should get the backing data as a list, construct it's own list data provider and register the custom updaters to make it work. It's kind of surprising and unintuitive that using Set instead of a List as the backing data, everything gets messed up.

Provided we get the Grid and the data in a List we can manage the lifecycle and data content in the scope of this Constructor. This would simplify the default case and make this specific issue, well, specific.
</blockquote></details>

Using the discussed approach:
1) using a valid list data provider - this is fine
2) using a NON-list data provider with custom updaters and calculator - this if fine
3) everything else - explosion 

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 277 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqci-cmP7GaPR93IUo:-Ky02-wGNFS1ZfZrK8aF:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L277)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

public?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255#-:-KyzBJDj1pIasGcb69KB:bb6un1j)*

**Comment by pleku** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqdv7nvr0HzdgJOqRZ:-KyzBmjBcGhImtePjZAn:b7jq11a) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I have a feeling that the whole add to specific index is going to run into problems when there filtering or sorting involved. The indices provided by grid will have absolutely no correlation with the real indices in the data set.

To be completely honest, I'd suggest the default to be always "drop to end" and if you want something else, you implement it yourself. This will reduce the amount of surprises to the user.

What does it mean if all items are sorted by a criteria and rows are dragged on a row. Does the user want the data to be dropped after the specific row or in that index in the original data set?
</blockquote></details>

Still need to fix this to take `DropMode#ON_GRID` into account and then always drop to the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 9 files at r2, 3 of 9 files at r5, 4 of 9 files at r10, 1 of 5 files at r11, 4 of 7 files at r13, 8 of 8 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragEndEvent.java, line 60 at r14](https://reviewable.io:443/reviews/vaadin/framework/10255#-KyzIzH7Llm90Z7JqdOX:-KyzIzH7Llm90Z7JqdOY:b-p52pef) ([raw file](https://github.com/vaadin/framework/blob/46f01fa2fe6d8873470825c745dd0ab85e896f9f/server/src/main/java/com/vaadin/ui/components/grid/GridDragEndEvent.java#L60)):*
> ```Java
>      * @return an unmodifiable set of items that were being dragged.
>      */
>     public List<T> getDraggedItems() {
> ```

Return type change should be mentioned in release notes

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqdv7nvr0HzdgJOqRZ:-KyzKFDwl3RqAo0gzDvD:b-f0vg0p) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Still need to fix this to take `DropMode#ON_GRID` into account and then always drop to the end.
</blockquote></details>

You were still doing something to this? Or should we split the follow up into a new PR?

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragStartEvent.java, line 64 at r14](https://reviewable.io:443/reviews/vaadin/framework/10255#-KyzJn_9tnGB6Kk_8Q8w:-KyzJn_9tnGB6Kk_8Q8x:bprb7np) ([raw file](https://github.com/vaadin/framework/blob/46f01fa2fe6d8873470825c745dd0ab85e896f9f/server/src/main/java/com/vaadin/ui/components/grid/GridDragStartEvent.java#L64)):*
> ```Java
>      * @return an unmodifiable list of items that are being dragged.
>      */
>     public List<T> getDraggedItems() {
> ```

return type changed, release notes mention

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Comment by pleku** [comment]
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragEndEvent.java, line 60 at r14](https://reviewable.io:443/reviews/vaadin/framework/10255#-KyzIzH7Llm90Z7JqdOX:-KyzTN7wDYnJV0lX3Y4Q:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46f01fa2fe6d8873470825c745dd0ab85e896f9f/server/src/main/java/com/vaadin/ui/components/grid/GridDragEndEvent.java#L60)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Return type change should be mentioned in release notes
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java, line 364 at r8](https://reviewable.io:443/reviews/vaadin/framework/10255#-Kxqdv7nvr0HzdgJOqRZ:-KyzTNwP3L3GzL3sHLSc:b-ajeug) ([raw file](https://github.com/vaadin/framework/blob/d58a1b7d4decf08bff01d066a7d80431cbdc93a7/server/src/main/java/com/vaadin/ui/components/grid/GridDragger.java#L364)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

You were still doing something to this? Or should we split the follow up into a new PR?
</blockquote></details>

Actually it was a NOOP since the drop target row is always empty, and then it is dropped to the end 

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragStartEvent.java, line 64 at r14](https://reviewable.io:443/reviews/vaadin/framework/10255#-KyzJn_9tnGB6Kk_8Q8w:-KyzRX6hYlTj2YHcnMW2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46f01fa2fe6d8873470825c745dd0ab85e896f9f/server/src/main/java/com/vaadin/ui/components/grid/GridDragStartEvent.java#L64)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

return type changed, release notes mention
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10255)*

**Pull request merged**
