### PR TITLE
Use .toLowerCase and .toUpperCase(Locale.ROOT)

### PR DESCRIPTION
**Pull request by asashour**
It is recommended to always use a `Locale` for `String.toLowerCase()` and `.toUpperCase()`.

Locale.ROOT is preferred over Locale.ENGLISH as recommended [here](https://dzone.com/articles/policemans-horror-default) and [here](https://garygregory.wordpress.com/2015/11/03/java-lowercase-conversion-turkey/).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10182)

### CODE REVIEW

**Comment by jreznot** [comment]
As I see, it is not required in case of simple names of enumerations, a lot of lines are changed for this case

**Comment by tsuoanttila** [comment]
@Legioth do you have an opinion on the use of locales here?

**Comment by torok-peter** [comment]
Reviewed 106 of 106 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ComputedStyle.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdL_OJx05V5McpbpTq:-KwdLY3C7c3NJfdqgzkf:b-kl3p3a) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/ComputedStyle.java#L83)):*
> ```Java
>         }
>     
>         if(cs.getPropertyValue) {
> ```

Could also add the missing space after `if` while you're at it :-)

---

*[client/src/main/java/com/vaadin/client/ComputedStyle.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdLOgVkxMJlsQD827S:-KwdLOgVkxMJlsQD827T:bl6xlbu) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/ComputedStyle.java#L84)):*
> ```Java
>     
>         if(cs.getPropertyValue) {
>     
> ```

Remove extra whitespace and new lines

---

*[client/src/main/java/com/vaadin/client/CSSRule.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdNOHucfpQZKq3gfU0:-KwdNOHucfpQZKq3gfU1:bxgzbf7) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/CSSRule.java#L67)):*
> ```Java
>     return null;
>     
>     selector = selector.toLowerCase('en');
> ```

Use `Locale.ROOT` as everywhere else

---

*[client/src/main/java/com/vaadin/client/CSSRule.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdNSLIM98ZVXoqT-Yj:-KwdNSLIM98ZVXoqT-Yk:b-2guby3) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/CSSRule.java#L90)):*
> ```Java
>     var r = theRules[i];
>     if(r.type == 1 || sheet.imports) {
>     var selectors = r.selectorText.toLowerCase('en').split(",");
> ```

same here

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPo56Yt0vW7juHLRn:-KwdPo56Yt0vW7juHLRo:b-34gl4m) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L98)):*
> ```Java
>      * @param mouseEventDetails
>      *            mouse event details object containing information about the
>      *            drop event
> ```

Undo the extra whitespace and new line

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPzLmt8egpwerLOht:-KwdPzLmt8egpwerLOhu:b-2guby3) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L175)):*
> ```Java
>      *
>      *                 // Otherwise cancel the event
>      *                 "return false;");
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10182)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ComputedStyle.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdL_OJx05V5McpbpTq:-Kwe-ZoV3PgT0IGtuub1:bkyq1vo) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/ComputedStyle.java#L83)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could also add the missing space after `if` while you're at it :-)
</blockquote></details>

Done. Eclipse formatter ignores JavaScript in comments. Other places also changed.

---

*[client/src/main/java/com/vaadin/client/ComputedStyle.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdLOgVkxMJlsQD827S:-Kwe-j-PfOQ5XNSa2pv5:b-kulu5g) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/ComputedStyle.java#L84)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Remove extra whitespace and new lines
</blockquote></details>

Done.Eclipse formatter automatically adds those.

---

*[client/src/main/java/com/vaadin/client/CSSRule.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdNOHucfpQZKq3gfU0:-Kwe0_tDZFa2orQonqCo:b8fkuk7) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/CSSRule.java#L67)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Use `Locale.ROOT` as everywhere else
</blockquote></details>

This is `JavaScript`, and doesn't support `Locale.ROOT` on the client-side.

---

*[client/src/main/java/com/vaadin/client/CSSRule.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdNSLIM98ZVXoqT-Yj:-Kwe0fBvrPzXZRzruEvd:b8fkuk7) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/client/src/main/java/com/vaadin/client/CSSRule.java#L90)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

same here
</blockquote></details>

This is `JavaScript`, and doesn't support `Locale.ROOT` on the client-side.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPo56Yt0vW7juHLRn:-Kwe0rZrJFnbQ3HqEKyA:b2owgx2) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L98)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Undo the extra whitespace and new line
</blockquote></details>

Reverted, but I believe it shouldn't, since this is the correct formatting of the file (by Eclipse)

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPzLmt8egpwerLOht:-Kwe102dc1LptTZNG3GS:b2owgx2) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L175)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Reverted, but I believe it shouldn't, since this is the correct formatting of the file (by Eclipse)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10182)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPo56Yt0vW7juHLRn:-KweAIYfiOx47eO77Y-r:bu4u5f3) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L98)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Reverted, but I believe it shouldn't, since this is the correct formatting of the file (by Eclipse)
</blockquote></details>

You're right, it seems that some files (including this one) should be reformatted properly, but we shall handle that in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10182#-:-KweAYHNn96IJBHYbvZ7:bnfp4nl)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/10182#-KwdPo56Yt0vW7juHLRn:-KweBl60UjnLj3mXF2KX:b-y72wuc) ([raw file](https://github.com/vaadin/framework/blob/575fb46775621ee5b78aac22329a407b07c9bfbf/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L98)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

You're right, it seems that some files (including this one) should be reformatted properly, but we shall handle that in a separate PR.
</blockquote></details>

Let me know if I should raise such PR. I have few items on my list, but since they are huge, the team prefers someone internal to do it.

E.g. rename 2016 to 2017, remove extra `else` after `return `in `if () {retrurn } else {return}`, formatting source code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10182)*

**Comment by asashour** [comment]
Your were faster, thanks.

**Comment by torok-peter** [comment]
Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10182)*

**Pull request merged**
