### PR TITLE
Change default suggestion popup width in ComboBox

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/91)

### CODE REVIEW

**Comment by ahie** [comment]
This is only an initial commit to gather a record of failing tests.

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKjGr71eLDO7DRYFo:-KYIKjGr9VWMhLRlfVm1:b-dqjz9h) (no related file):*
Screenshots should be updated.

---

*[shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKmfX2yf5KcI99gaJ:-KYIKmfX1djg0RcrkTIR:b-za34p6) ([raw file](https://github.com/vaadin/framework/blob/19799bf66704d52128d0011af72d2ed46b5ad419/shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java#L63)):*
> ```Java
>      */
>     @DelegateToWidget
>     public String suggestionPopupWidth = "100%";
> ```

I'm pretty sure that this change requires mention in the javadoc of the API methods which set and get this value in the `ComboBox` class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by hesara** [comment]
Screenshot updates needed at least for ComboBoxLargeIconsTest, ComboboxSelectedItemTextTest and ValoThemeUITest. Remember to update also the submodule reference in the framework project.

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKmfX2yf5KcI99gaJ:-KYN4EhX86KxjVg2KE_x:bim5a7) ([raw file](https://github.com/vaadin/framework/blob/19799bf66704d52128d0011af72d2ed46b5ad419/shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java#L63)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I'm pretty sure that this change requires mention in the javadoc of the API methods which set and get this value in the `ComboBox` class.
</blockquote></details>

probably also merits a mention of the change in class level javadoc for ComboBox

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKmfX2yf5KcI99gaJ:-KYN4e-T1FlP-1cX8fFa:biyxx9m) ([raw file](https://github.com/vaadin/framework/blob/19799bf66704d52128d0011af72d2ed46b5ad419/shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java#L63)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

probably also merits a mention of the change in class level javadoc for ComboBox
</blockquote></details>

Also please mention `100%` of what it this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by ahie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKjGr71eLDO7DRYFo:-KYOAUB53OMPtw6eWtpG:bggmcy7) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Screenshots should be updated.
</blockquote></details>

Screenshots updated for the tests mentioned by Henri, except for ValoThemeUITest which didn't require updates.

---

*[shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/91#-KYIKmfX2yf5KcI99gaJ:-KYOAgPh6YtZpxJbICUO:b-cdlxz8) ([raw file](https://github.com/vaadin/framework/blob/19799bf66704d52128d0011af72d2ed46b5ad419/shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java#L63)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Also please mention `100%` of what it this.
</blockquote></details>

Javadocs for get/setPopupWidth updated. Also what `100%` means is already documented well enough in my opinion (both in the ComboBox methods as well as here).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 447 at r2](https://reviewable.io:443/reviews/vaadin/framework/91#-KYOEPbS9edx-F4xwvd3:-KYOEPbS03AyElYzqtaV:bn16a85) ([raw file](https://github.com/vaadin/framework/blob/dd907713602049cb170f2b0c14bd43be80647145/server/src/main/java/com/vaadin/ui/ComboBox.java#L447)):*
> set to "100%"
100% if what ? (yes, it's mentioned above but please do it one more time as a note : so the width of the popup is the same as combobox width))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 447 at r2](https://reviewable.io:443/reviews/vaadin/framework/91#-KYOEPbS9edx-F4xwvd3:-KYOHzfa8ues8KoDUYCk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dd907713602049cb170f2b0c14bd43be80647145/server/src/main/java/com/vaadin/ui/ComboBox.java#L447)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> set to "100%"
100% if what ? (yes, it's mentioned above but please do it one more time as a note : so the width of the popup is the same as combobox width))
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/91)*

**Pull request merged**
