### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by Ansku**
- updated screenshots for Firefox and IE
- updated Firefox version number

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12147)

### CODE REVIEW

**Review by johannest — COMMENTED** [review]
> Reviewed 311 of 311 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12147)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johannest — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12147#-:-MLpv7zUCz2LRSCmifVj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johannest** [comment]
Looks good to me

**Review by johannest — APPROVED** [review]
Looks good to me

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12147#-:-MMozx3wBzAhMOVH8u6C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
