### PR TITLE
Delete CheckboxRenderer

### PR DESCRIPTION
**Pull request by elmot**
Fixes vaadin/framework8-issues#551

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8003)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1N9qZqHEIBXMSoTvA:bg3vybg) (no related file):*
@legioth is it OK to make checkbox-renderer read only 

---

*[server/src/main/java/com/vaadin/ui/renderers/CheckBoxRenderer.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1NN7tiW2TaTmxdscd:-KZ1NN7tiW2TaTmxdsce:b-azzwvq) ([raw file](https://github.com/vaadin/framework/blob/eaf76900d8b68e7f20216e794eb10b115fe56923/server/src/main/java/com/vaadin/ui/renderers/CheckBoxRenderer.java#L21)):*
> ```Java
> 
> /**
>  * A renderer that displays boolean valued grid columns as checkboxes.
> ```

Could mention here that it is read-only and user cannot change the value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1PgvPcgeQENfojdsA:b-r5v60s) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

@legioth is it OK to make checkbox-renderer read only 
</blockquote></details>

That feels like a terrible compromise.

I'd say it's better to completely remove this renderer than to provide something that doesn't live up to its purpose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1Q829XuVfKncEOcJh:b-f3ezhc) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

That feels like a terrible compromise.

I'd say it's better to completely remove this renderer than to provide something that doesn't live up to its purpose.
</blockquote></details>

I don't think this is a compromise. 
I'd agree if it requires read-only styling but using read-only checkboxes for boolean values is quite often.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1RPKa2lSO4qwjINTu:b-ndsoq9) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I don't think this is a compromise. 
I'd agree if it requires read-only styling but using read-only checkboxes for boolean values is quite often.
</blockquote></details>

It's a gigantic compromise. If I want readonly checkboxes, then I can just as well use a `HtmlRenderer`.

Let's just remove this experiment from the project. We don't have a simple demo that uses it. We can always add it back later on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1WyG3Fi3TZOoh1JSA:b99iqbc) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

It's a gigantic compromise. If I want readonly checkboxes, then I can just as well use a `HtmlRenderer`.

Let's just remove this experiment from the project. We don't have a simple demo that uses it. We can always add it back later on.
</blockquote></details>

Well, yes. We can add that renderer back if there is any demand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1N9qZqHEIBXMSoTv9:-KZ1aeBJRIaqapFkBcNT:bddbnpg) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Well, yes. We can add that renderer back if there is any demand.
</blockquote></details>

CheckboxRenderer deleted

---

*[server/src/main/java/com/vaadin/ui/renderers/CheckBoxRenderer.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8003#-KZ1NN7tiW2TaTmxdscd:-KZ1aYxbL3ByB3JeRsRp:b-tnhc8e) ([raw file](https://github.com/vaadin/framework/blob/eaf76900d8b68e7f20216e794eb10b115fe56923/server/src/main/java/com/vaadin/ui/renderers/CheckBoxRenderer.java#L21)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could mention here that it is read-only and user cannot change the value.
</blockquote></details>

Deleted completely

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8003)*

**Pull request merged**
