### PR TITLE
Add Navigator testing to Spring Boot test

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch adds a new UI with PushStateNavigation to the Spring Boot test as well as a separate test using a custom context path.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10174)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This PR contains the commit from #8507 and some improvements on top of it.

**Comment by hesara** [comment]
partial review

---

Reviewed 6 of 14 files at r1, 7 of 13 files at r2, 15 of 20 files at r3.
Review status: 26 of 31 files reviewed at latest revision, 27 unresolved discussions.

---

*[test/spring-boot-subcontext/pom.xml, line 68 at r2](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF68jd9Xsc-s0eJ_87:-KwF68jd9Xsc-s0eJ_88:b4pw73) ([raw file](https://github.com/vaadin/framework/blob/adea1077a36210f1fe3584523b09c9324bdc5a72/test/spring-boot-subcontext/pom.xml#L68)):*
> ```XML
>             </plugin>
> 
>             
> ```

Would it be easier to do this with jetty.skip?

---

*[test/spring-boot-subcontext/src/main/java/com/example/CustomSpringNavigator.java, line 16 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6Qet90FVrvhbxYzf:-KwF6Qet90FVrvhbxYzg:bpydgfr) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/CustomSpringNavigator.java#L16)):*
> ```Java
>     @Override
>     public void init(UI ui, ViewDisplay display) {
>         // FIXME: Should be in Spring plug-in
> ```

(to address this, perhaps after merging the initial version of the tests)

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 194 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5jz9C-8Vq-snIQbt:-KwF5jz9C-8Vq-snIQbu:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L194)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 20 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6bp_Xwj1cfaOUfDT:-KwF6bp_Xwj1cfaOUfDU:b-pi00gl) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L20)):*
> ```Java
> 
>     @Bean
>     ServletRegistrationBean servlet() {
> ```

(not sure if there is a better way to do this)

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5eYQyS5QFl4ZLOM5:-KwF5eYQyS5QFl4ZLOM6:btkirc0) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L10)):*
> ```Java
> 
>     public String sayHello() {
>         return "Hello number " + counter++ + "from bean with same scope as view"
> ```

see comments in other ViewGreeter

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5d6Nhwb-OKJRChWG:-KwF5d6Nhwb-OKJRChWH:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java, line 58 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6lbZNYJoye21OBE-:-KwF6lbZNYJoye21OBE0:b-tvgy5k) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java#L58)):*
> ```Java
>     @Override
>     public String getUiRootPath() {
>         // FIXME: Should be handled by Spring plug-in
> ```

to address the FIXME, perhaps after merging the initial version of the tests

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6k_hL744xffzCAeU:-KwF6k_hL744xffzCAeV:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java#L62)):*
> ```Java
>                 + getClass().getAnnotation(SpringUI.class).path();
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/RootPathUI.java, line 18 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6tm8dX-eNkdwum7e:-KwF6tm8dX-eNkdwum7f:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/RootPathUI.java#L18)):*
> ```Java
>         navigationBar.addComponent(label);
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/SubPathUI.java, line 22 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6ypxtwBx7852L0Ot:-KwF6ypxtwBx7852L0Ou:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/SubPathUI.java#L22)):*
> ```Java
>         navigationBar.addComponent(label);
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/DefaultView.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF72vv-aykhs4zH-GJ:-KwF72vv-aykhs4zH-GK:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/DefaultView.java#L33)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/UIScopedView.java, line 35 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF74XV_uW254rnqj_0:-KwF74XV_uW254rnqj_1:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/UIScopedView.java#L35)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/ViewDisplayPanel.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7AvCKvozLHkgxO06:-KwF7AvCKvozLHkgxO07:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/ViewDisplayPanel.java#L26)):*
> ```Java
>     }
> 
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/ViewScopedView.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7LJMtnJtOC_9cASD:-KwF7LJNZSXYQDg0LBxJ:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/ViewScopedView.java#L34)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot-subcontext/src/test/java/com/example/VaadinSpringBootPushStateNavigatorIT.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7UCVjz42zF5jTTUD:-KwF7UCVjz42zF5jTTUE:bu9anmk) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/test/java/com/example/VaadinSpringBootPushStateNavigatorIT.java#L9)):*
> ```Java
>         extends VaadinSpringBootURIFragmentNavigatorIT {
> 
>     @Ignore("PushState navigation is partially broken with Spring.")
> ```

to remember to address this

---

*[test/spring-boot/src/main/java/com/example/CustomSpringNavigator.java, line 16 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7aVSD0MVXRFM2rDI:-KwF7aVSD0MVXRFM2rDJ:b-nnmpw1) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/CustomSpringNavigator.java#L16)):*
> ```Java
>     @Override
>     public void init(UI ui, ViewDisplay display) {
>         // FIXME: Should be in Spring plug-in
> ```

to address this, perhaps after merging the initial versions of the tests

---

*[test/spring-boot/src/main/java/com/example/DemoApplication.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF562bPlayMjZRoWkl:-KwF562bPlayMjZRoWkm:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/DemoApplication.java#L183)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5BkfoYkK8W0ysGFV:-KwF5BkfoYkK8W0ysGFW:b11pnw) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L10)):*
> ```Java
> 
>     public String sayHello() {
>         return "Hello number " + counter++ + "from bean with same scope as view"
> ```

space missing from last part of concatenation; not sure if toString() is quite correct here

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF57DGP43riq29shiU:-KwF57DGP43riq29shiV:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7n4gxq6FCoMH9dvM:-KwF7n4gxq6FCoMH9dvN:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java#L62)):*
> ```Java
>                 + getClass().getAnnotation(SpringUI.class).path();
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/ui/RootPathUI.java, line 18 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7p2zSid8UtlOfztR:-KwF7p2zSid8UtlOfztS:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/RootPathUI.java#L18)):*
> ```Java
>         navigationBar.addComponent(label);
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/ui/SubPathUI.java, line 22 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7rgbj5cTk2HrbNA-:-KwF7rgbj5cTk2HrbNA0:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/SubPathUI.java#L22)):*
> ```Java
>         navigationBar.addComponent(label);
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/view/DefaultView.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7tumbRg0E21A4xQI:-KwF7tumbRg0E21A4xQJ:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/DefaultView.java#L33)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/view/UIScopedView.java, line 35 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7wyMw4Fcn65qabGu:-KwF7wyMw4Fcn65qabGv:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/UIScopedView.java#L35)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/view/ViewDisplayPanel.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7zFMrmAIAkf0AhEl:-KwF7zFMrmAIAkf0AhEm:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/ViewDisplayPanel.java#L26)):*
> ```Java
>     }
> 
> }
> ```

missing NL

---

*[test/spring-boot/src/main/java/com/example/view/ViewScopedView.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF80LrrbTy5VVHJBYL:-KwF80LrrbTy5VVHJBYM:b-p4d7cz) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/ViewScopedView.java#L34)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

missing NL

---

*[test/spring-boot/src/test/java/com/example/VaadinSpringBootPushStateNavigatorIT.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF84NNsz9PUa5Zyp4_:-KwF84NNsz9PUa5Zyp4a:bu9anmk) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/test/java/com/example/VaadinSpringBootPushStateNavigatorIT.java#L9)):*
> ```Java
>         extends VaadinSpringBootURIFragmentNavigatorIT {
> 
>     @Ignore("PushState navigation is partially broken with Spring.")
> ```

to remember to address this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10174#-:-KwF8Ft30u-wo0a7TeTQ:buoa2ho)*

**Comment by tsuoanttila** [comment]
Review status: 7 of 31 files reviewed at latest revision, 26 unresolved discussions.

---

*[test/spring-boot-subcontext/pom.xml, line 68 at r2](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF68jd9Xsc-s0eJ_87:-KwF8KQ8tf48wpI2QzQN:bb7sa0c) ([raw file](https://github.com/vaadin/framework/blob/adea1077a36210f1fe3584523b09c9324bdc5a72/test/spring-boot-subcontext/pom.xml#L68)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Would it be easier to do this with jetty.skip?
</blockquote></details>

yes.

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 194 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5jz9C-8Vq-snIQbt:-KwF8bubM7KrLf2XGGdF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L194)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5eYQyS5QFl4ZLOM5:-KwF9lcC7i3FhcuEaRI0:b-teei0n) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comments in other ViewGreeter
</blockquote></details>

Spaces fixed. Not sure about toString.

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5d6Nhwb-OKJRChWG:-KwF8nn5SiJTzt4Vct1I:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L13)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6k_hL744xffzCAeU:-KwF8shXU0sxKQoYoE4C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/AbstractSpringUI.java#L62)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/RootPathUI.java, line 18 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6tm8dX-eNkdwum7e:-KwF8vb2IbmEgGuJlcUg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/RootPathUI.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/ui/SubPathUI.java, line 22 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF6ypxtwBx7852L0Ot:-KwF8y5-F47E-r4x2HL8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/ui/SubPathUI.java#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/DefaultView.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF72vv-aykhs4zH-GJ:-KwF9HBxUK07VRr5J-5o:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/DefaultView.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/UIScopedView.java, line 35 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF74XV_uW254rnqj_0:-KwF9IEqy6jC51b_z-nz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/UIScopedView.java#L35)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/ViewDisplayPanel.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7AvCKvozLHkgxO06:-KwF9Irw6qQKQ4vb-pte:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/ViewDisplayPanel.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot-subcontext/src/main/java/com/example/view/ViewScopedView.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7LJMtnJtOC_9cASD:-KwF9JgEAP_3cgqRacrv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot-subcontext/src/main/java/com/example/view/ViewScopedView.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/DemoApplication.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF562bPlayMjZRoWkl:-KwF9NV8EsWyeVxdN4p9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/DemoApplication.java#L183)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF5BkfoYkK8W0ysGFV:-KwF9SQ_zQcwRs1hgC6h:b-686lw9) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

space missing from last part of concatenation; not sure if toString() is quite correct here
</blockquote></details>

Spaces fixed. Not sure what to do about the toString though.

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF57DGP43riq29shiU:-KwF9SFupR4pATcdlRQh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5db256bd820242d3652f22806b2b190a33c7976a/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L13)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7n4gxq6FCoMH9dvM:-KwF9cXQcLE_IaTV73WG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java#L62)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/ui/RootPathUI.java, line 18 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7p2zSid8UtlOfztR:-KwF9dJxFnY_Vg67voqu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/RootPathUI.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/ui/SubPathUI.java, line 22 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7rgbj5cTk2HrbNA-:-KwF9e94wqtnHPZmTFEU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/ui/SubPathUI.java#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/view/DefaultView.java, line 33 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7tumbRg0E21A4xQI:-KwF9esox-s3ZQhnkkyH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/DefaultView.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/view/UIScopedView.java, line 35 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7wyMw4Fcn65qabGu:-KwF9fYw7vMDVocBuiwq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/UIScopedView.java#L35)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/view/ViewDisplayPanel.java, line 26 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF7zFMrmAIAkf0AhEl:-KwF9gBU4B0RsmzuQtcj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/ViewDisplayPanel.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---

*[test/spring-boot/src/main/java/com/example/view/ViewScopedView.java, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwF80LrrbTy5VVHJBYL:-KwF9grlO-OFRcOqomp0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8fb8e3d476fa027a4bb655b10af90d2f43adc2ae/test/spring-boot/src/main/java/com/example/view/ViewScopedView.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing NL
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10174)*

**Comment by hesara** [comment]
Reviewed 21 of 22 files at r4.
Review status: 28 of 31 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10174)*

**Comment by tsuoanttila** [comment]
Added an issue to vaadin/spring about the remaining `FIXME`s and the `@Ignored` test.

---

Review status: 28 of 31 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10174#-:-KwFPzQjagkHaHuvqK68:b-uwnq1d)*

**Comment by tsuoanttila** [comment]
Related issue vaadin/spring#236

**Comment by hesara** [comment]
Reviewed 2 of 13 files at r2, 2 of 20 files at r3, 1 of 22 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java, line 58 at r4](https://reviewable.io:443/reviews/vaadin/framework/10174#-KwFS-55xhX69EocHTjP:-KwFS-55xhX69EocHTjQ:bpgazsb) ([raw file](https://github.com/vaadin/framework/blob/b7f81e36f4f78a8cff743eb64185803f8c0fd44e/test/spring-boot/src/main/java/com/example/ui/AbstractSpringUI.java#L58)):*
> ```Java
>     @Override
>     public String getUiRootPath() {
>         // FIXME: Should be handled by Spring plug-in
> ```

(to address later)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10174)*

**Pull request merged**
