### PR TITLE
Fixes NPE when grid is sorted by column with null values

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8327)

### CODE REVIEW

**Comment by elmot** [comment]
WIP

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327#-:-KbJarVa0s5Ssagv471U:b2nhqqh)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 823 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKB197usKbfrZZJFEW:-KbKB197usKbfrZZJFEX:bh5ws8m) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L823)):*
> ```Java
>                     @SuppressWarnings("unchecked")
>                     Comparable<V> valueA = (Comparable<V>) valueProvider.apply(a);
>                     V valueB = valueProvider.apply(b);
> ```

This becomes too big for lambda especially inside `if` block.
The logic has no any relation to the CTOR logic .
Should be extracted either into separate class or as a method reference.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 825 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKBN40FJvrfEG2SR0W:-KbKBN40FJvrfEG2SR0X:bcl5vau) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L825)):*
> ```Java
>                     V valueB = valueProvider.apply(b);
>                     if (valueA == null) {
>                         return valueB == null ? 0 : 1;
> ```

It makes an assumption about comparison implementation.
It shouldn't.
Instead if should check whether the `valueB` is `null` or not. If it's `null` then they are the same.
If it's not then `valueB.compareTo()` should be used.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 827 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKBvmd7eKD03JxAf_d:-KbKBvmd7eKD03JxAf_e:b-d9bz05) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L827)):*
> ```Java
>                         return valueB == null ? 0 : 1;
>                     } else {
>                         if (valueB == null) return -1;
> ```

This should disappear after the correction for above. Otherwise it requires `{}` block around.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCNtMVpo_W6B-bTJR:-KbKCNtMVpo_W6B-bTJS:b-umjfpt) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L848)):*
> ```Java
>         @SuppressWarnings("unchecked")
>         private static int compareNumbers(Number a, Number b) {
>             if (a == null) {
> ```

And here again the same thing as above.
The logic should be used only if `Number` is not  `Comparable` otherwise it should delegate.
And this method most likely can be refactored to reuse the logic for above.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCpAsN20bFwq9ajCf:-KbKCpAsN20bFwq9ajCg:b-ea02wa) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java#L13)):*
> ```Java
> import org.junit.Test;
> 
> public class GridNullValueSort {
> ```

Tests for `null` value which is considered as "last" by the comparison are needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 823 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKB197usKbfrZZJFEW:-KbLaAROz89tnX4M2mj2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L823)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This becomes too big for lambda especially inside `if` block.
The logic has no any relation to the CTOR logic .
Should be extracted either into separate class or as a method reference.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 825 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKBN40FJvrfEG2SR0W:-KbLaDxVLVw4c5Xjyddd:bx6zi1) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L825)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It makes an assumption about comparison implementation.
It shouldn't.
Instead if should check whether the `valueB` is `null` or not. If it's `null` then they are the same.
If it's not then `valueB.compareTo()` should be used.
</blockquote></details>

That was my first idea, but it might break `Comparable` contract `compare(a,b)=-compare(b,a)`
Rewritten using standard Java implementation

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 827 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKBvmd7eKD03JxAf_d:-KbLamImXAH7iu3To7Jw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L827)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This should disappear after the correction for above. Otherwise it requires `{}` block around.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCNtMVpo_W6B-bTJR:-KbLanrysqu9J_L7IBIp:btoz0ef) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L848)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

And here again the same thing as above.
The logic should be used only if `Number` is not  `Comparable` otherwise it should delegate.
And this method most likely can be refactored to reuse the logic for above.
</blockquote></details>

Done completely different way.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCpAsN20bFwq9ajCf:-KbLaxcqCDShj9yStJ5d:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java#L13)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Tests for `null` value which is considered as "last" by the comparison are needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCNtMVpo_W6B-bTJR:-KbP-n5ahnvMQPS261O-:b-ddiy98) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L848)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done completely different way.
</blockquote></details>

It again considers `null` as the biggest......
Is it intentionally ?
I'm not sure.

Very minor: it's a bad code style to modify method parameters.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 838 at r2](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbOkkmBOle1F1D_x-FQ:-KbOkkmBOle1F1D_x-FR:b-x34x24) ([raw file](https://github.com/vaadin/framework/blob/6625862f4670d9b704a117fb04c4c14109077073/server/src/main/java/com/vaadin/ui/Grid.java#L838)):*
> ```Java
>         @SuppressWarnings("unchecked")
>         private static int compareComparables(Object a, Object b) {
>             return ((Comparator) Comparator.nullsLast(Comparator.naturalOrder())).compare(a, b);
> ```

This again considers a `null` value in the hardcoded way.
Well, the `Comparable` contract assumes that `null` is invalid argument for `compareTo`. So it seems we should hardcode it anyway.

But why it's the  "last" ? It means that `null` is greater than non-null.
I would expect that it's actually the opposite...

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3213 at r2](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbP0FU4XvKp1-GkF6X7:-KbP0FU4XvKp1-GkF6X8:b-60ja2j) ([raw file](https://github.com/vaadin/framework/blob/6625862f4670d9b704a117fb04c4c14109077073/server/src/main/java/com/vaadin/ui/Grid.java#L3213)):*
> ```Java
>     }
> 
>     protected SerializableComparator<T> createSortingComparator() {
> ```

Now it's protected and needs javadoc.

The option is to make it private......

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCpAsN20bFwq9ajCf:-KbP0WOFwS7GNo1fqJeQ:biwzhqy) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java#L13)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well, I'm not sure that ASC and DES are required here since it's already tests for different functionality.

Originally I meant that `null` can be considered by `Comparable`  as the first or the last item (inside it's impl).
And that has been requested to test.
But since `Comparable`  shouldn't accept `null` then it already is not important.

But this is minor for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327)*

**Comment by elmot** [comment]
Fixes #8282 

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCNtMVpo_W6B-bTJR:-KbPXXQP5YfJSApHskBN:by1dgex) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/main/java/com/vaadin/ui/Grid.java#L848)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It again considers `null` as the biggest......
Is it intentionally ?
I'm not sure.

Very minor: it's a bad code style to modify method parameters.
</blockquote></details>

Yes, intentionally, that is the original issue author demand. If any other customer wants to adjust the behavior, explicit Comparator might be set for that.

Codestyle fixed

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 838 at r2](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbOkkmBOle1F1D_x-FQ:-KbPXQ0v9rlO45DPEmWz:b-rgpuu4) ([raw file](https://github.com/vaadin/framework/blob/6625862f4670d9b704a117fb04c4c14109077073/server/src/main/java/com/vaadin/ui/Grid.java#L838)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This again considers a `null` value in the hardcoded way.
Well, the `Comparable` contract assumes that `null` is invalid argument for `compareTo`. So it seems we should hardcode it anyway.

But why it's the  "last" ? It means that `null` is greater than non-null.
I would expect that it's actually the opposite...
</blockquote></details>

Look at the original issue. That was the customer demand.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3213 at r2](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbP0FU4XvKp1-GkF6X7:-KbPYvUz0vOYL2-Mfb6h:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6625862f4670d9b704a117fb04c4c14109077073/server/src/main/java/com/vaadin/ui/Grid.java#L3213)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Now it's protected and needs javadoc.

The option is to make it private......
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbKCpAsN20bFwq9ajCf:-KbPZ8r2ETOX19rHLhfW:b5dflp8) ([raw file](https://github.com/vaadin/framework/blob/e0911163984062db0667530069b04d5d2b804850/server/src/test/java/com/vaadin/tests/components/grid/GridNullValueSort.java#L13)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Well, I'm not sure that ASC and DES are required here since it's already tests for different functionality.

Originally I meant that `null` can be considered by `Comparable`  as the first or the last item (inside it's impl).
And that has been requested to test.
But since `Comparable`  shouldn't accept `null` then it already is not important.

But this is minor for now.
</blockquote></details>

Let's have a comprehensive tests set here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327#-:-KbPTvxwZrSw0kB3lq8n:b7oy8y3)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 838 at r2](https://reviewable.io:443/reviews/vaadin/framework/8327#-KbOkkmBOle1F1D_x-FQ:-KbPbdNl8Nurs8mNaFuN:bmctigb) ([raw file](https://github.com/vaadin/framework/blob/6625862f4670d9b704a117fb04c4c14109077073/server/src/main/java/com/vaadin/ui/Grid.java#L838)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Look at the original issue. That was the customer demand.
</blockquote></details>

OK, true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8327)*

**Comment by denis-anisimov** [comment]
False positive test failure because this should go through:
https://github.com/vaadin/framework/pull/8319

either restart the build or review the PR above, merge and rebase on top of it.

**Pull request merged**
