### PR TITLE
Update Chrome version, snapshots and fix tests

### PR DESCRIPTION
**Pull request by ZheSun88**
Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)

### CODE REVIEW

**Review by Ansku — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 103 of 107 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 200 of 200 files at r9, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: all files reviewed, 6 unresolved discussions (waiting on @ZheSun88)

___
*[documentation/components/components-overview.asciidoc, line 66 at r7](https://reviewable.io/reviews/vaadin/framework/11684#-LlGQ1OzEUg9bxc1_rGv:-LlGQ1OzEUg9bxc1_rGw:b-vhusc1) ([raw file](https://github.com/vaadin/framework/blob/f48baa29aedecd52c1f9c87ae816147d9114224a/documentation/components/components-overview.asciidoc#L66)):*
> ```
> Field Components:: allow user to edit a value in the UI. All extend [classname]#AbstractField#. Field components are described in detail in
> ```
Was the removal of this intentional?
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line 0 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlH0A4T1Uo_r36c6leR:b-wss110) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L0)):*
TwinColSelect buttons definitely aren't supposed to droop like that.
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png, line 0 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0k7-2rvAurIZE5HU:-LlH0k7-2rvAurIZE5HV:b5o4von) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png#L0)):*
TwinColSelect buttons drooping and other things overlapping.
___
*[uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png, line 0 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH1_f-9473hu5Aebfd:-LlH1_f-9473hu5Aebfe:b-8rvfxe) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png#L0)):*
TwinColSelect buttons drooping.
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 20 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvoIq7ZgimAqM_bdY:-LlGvoIr3b5USBLn9KmQ:bkmw7sn) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L20)):*
> ```
> expectedCondition(int element1, int element2)
> ```
Not very informative name, perhaps `smallerOrEquals`. I would also go with `elementCoordinate1` or `elementPosition1` or something, since element being an `int` is just weird
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlGvtPB8BWODg_28XCI:b-xfywp2) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
> ```
> "There should be no overlaps between two elements"
> ```
The assertion error is going to read "...waiting for There should be no overlaps between two elements", perhaps "the coordinates of the inspected elements to not overlap". The comment should also have a space before the `...`, even if that looks a bit weird, since it indicates that the returned string doesn't need a space at the beginning. You might also mention what the given parameters were for the sake of easier debugging.

**Review by ZheSun88 — COMMENTED** [review]
created ticket for the separate screenshot investigation, so that this wont block other patches.
this similar fix is needed for 8.9 branch

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684#-:-LlHC1LN4QRarSl7Szg_:bteam3z)* status: 200 of 202 files reviewed, 6 unresolved discussions (waiting on @Ansku)

___
*[documentation/components/components-overview.asciidoc, line 66 at r7](https://reviewable.io/reviews/vaadin/framework/11684#-LlGQ1OzEUg9bxc1_rGv:-LlH7gP5BU2IDXr3x5Nq:b5qls5v) ([raw file](https://github.com/vaadin/framework/blob/f48baa29aedecd52c1f9c87ae816147d9114224a/documentation/components/components-overview.asciidoc#L66)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> Field Components:: allow user to edit a value in the UI. All extend [classname]#AbstractField#. Field components are described in detail in
> ```
Was the removal of this intentional?
</blockquote></details>

done. This change is not from this PR. the current master is missing the content also. 
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlH7vcMCx4u_nD-xYa4:b5trogo) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

TwinColSelect buttons definitely aren't supposed to droop like that.
</blockquote></details>

issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0k7-2rvAurIZE5HU:-LlH9-aaEkcYvPN1p9rn:b-n22ex0) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

TwinColSelect buttons drooping and other things overlapping.
</blockquote></details>

 issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
___
*[uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH1_f-9473hu5Aebfd:-LlH92ka-2iGC1MkONLL:b5trogo) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

TwinColSelect buttons drooping.
</blockquote></details>

issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 20 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvoIq7ZgimAqM_bdY:-LlH9mRDD6bj_qXjAr70:b4sy2au) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L20)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> expectedCondition(int element1, int element2)
> ```
Not very informative name, perhaps `smallerOrEquals`. I would also go with `elementCoordinate1` or `elementPosition1` or something, since element being an `int` is just weird
</blockquote></details>

refactored
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlHBowV73iUbkJZ9x5j:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> "There should be no overlaps between two elements"
> ```
The assertion error is going to read "...waiting for There should be no overlaps between two elements", perhaps "the coordinates of the inspected elements to not overlap". The comment should also have a space before the `...`, even if that looks a bit weird, since it indicates that the returned string doesn't need a space at the beginning. You might also mention what the given parameters were for the sake of easier debugging.

</blockquote></details>

Done.

**Review by Ansku — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: all files reviewed, 5 unresolved discussions (waiting on @Ansku and @ZheSun88)

___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlHG62z2tHDX8so9bCz:b-b9cmqq) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
</blockquote></details>

And this particular Chrome update broke these few tests in an unacceptable way, not just by switching things around by a few pixels or changing their shade a bit like usual. It needs to be dealt with just the same as any non-screenshot test breaking needs to be dealt with, this is what these tests are _for_. Maybe it's just a matter of timing, maybe it's only broken when you run it through TestBench, I haven't tried running them so I don't know, but the new screenshots display a state that is not acceptable and shouldn't be listed as the expected state. It needs to be investigated and fixed, not just declared as the new normal. The old screenshots are a much better reference for what things are supposed to look like at these points of running the tests and shouldn't be replaced with these clearly broken versions.
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0k7-2rvAurIZE5HU:-LlHJcyl7aBPLotzzJ-A:b-u71nf3) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png#L)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

 issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
</blockquote></details>

See my answer above.
___
*[uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH1_f-9473hu5Aebfd:-LlHJfhj4ANLt5AyBLup:b-u71nf3) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png#L)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

issue related to screenshot taken which varies between chrome versions.  new ticket has been created https://github.com/vaadin/framework/issues/11685.
</blockquote></details>

See my answer above.
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlHCmSr2SctM0C2j2kl:bog6sr0) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You misunderstood a bit, the returned String _doesn't_ need the space in the beginning, the comment above it needs the space to signify it. 

I actually meant entering the values in the comment -- like when you get an error from assertEquals the stacktrace shows you the expected and actual, so you don't need to step through the test with a breakpoint to figure out what actually went wrong -- is it off by just one pixel or did something really unexpected happen and one of your compared values is off by hundreds from what you meant it to be. You can have any amount of parameters (or none) on an ExpectedCondition and they can be anything, so they aren't included in the error message by default. It's fine to have the element description there as well, of course.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: all files reviewed, 5 unresolved discussions (waiting on @Ansku and @ZheSun88)

___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlHKo924OmIs0KehBEo:b-cnmpue) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

And this particular Chrome update broke these few tests in an unacceptable way, not just by switching things around by a few pixels or changing their shade a bit like usual. It needs to be dealt with just the same as any non-screenshot test breaking needs to be dealt with, this is what these tests are _for_. Maybe it's just a matter of timing, maybe it's only broken when you run it through TestBench, I haven't tried running them so I don't know, but the new screenshots display a state that is not acceptable and shouldn't be listed as the expected state. It needs to be investigated and fixed, not just declared as the new normal. The old screenshots are a much better reference for what things are supposed to look like at these points of running the tests and shouldn't be replaced with these clearly broken versions.
</blockquote></details>

I will replace those tests with code tests just like what I have stated in the ticket. 

the chrome update doesn't break it. you can test with your machine too. This might be your first time to dealing with screenshot update after new chrome version, but this has happened many times before. 

just for a reference and you can see the buttons you referred are located correctly.. 


the reason for this screenshot failure can be a timing issue that screenshot is taken too early, but this needs to be investigated separately instead of here. 
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlHN3k67POL4G7TuG4J:bgh6q3f) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

You misunderstood a bit, the returned String _doesn't_ need the space in the beginning, the comment above it needs the space to signify it. 

I actually meant entering the values in the comment -- like when you get an error from assertEquals the stacktrace shows you the expected and actual, so you don't need to step through the test with a breakpoint to figure out what actually went wrong -- is it off by just one pixel or did something really unexpected happen and one of your compared values is off by hundreds from what you meant it to be. You can have any amount of parameters (or none) on an ExpectedCondition and they can be anything, so they aren't included in the error message by default. It's fine to have the element description there as well, of course.
</blockquote></details>

so you mean the `// waiting for...` should be `// waiting for ...`?
i am confused

**Review by Ansku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: all files reviewed, 5 unresolved discussions (waiting on @Ansku and @ZheSun88)

___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlHQ5cIC0irxYoWj9Bu:bi8l8cu) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

I will replace those tests with code tests just like what I have stated in the ticket. 

the chrome update doesn't break it. you can test with your machine too. This might be your first time to dealing with screenshot update after new chrome version, but this has happened many times before. 

just for a reference and you can see the buttons you referred are located correctly.. 


the reason for this screenshot failure can be a timing issue that screenshot is taken too early, but this needs to be investigated separately instead of here. 
</blockquote></details>

It doesn't matter, mark the tests ignored or mute them if they are in your way and you don't want to add delays, but don't update the screenshots with broken ones. That is the wrong fix.
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlHQzBG43tdNSV9QgFx:b-vxpdwh) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

so you mean the `// waiting for...` should be `// waiting for ...`?
i am confused 
</blockquote></details>

Yes, exactly. It looks weird, but when it's there, the next person who uses an old tests as a reference is less likely to add the unnecessary space at the beginning of the returned String.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: 198 of 199 files reviewed, 5 unresolved discussions (waiting on @Ansku)

___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0A4T1Uo_r36c6leQ:-LlVHn6X97v-fJoDXCOu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_changeIcon_ANY_Chrome__allVaadinIcons-switch.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

It doesn't matter, mark the tests ignored or mute them if they are in your way and you don't want to add delays, but don't update the screenshots with broken ones. That is the wrong fix.
</blockquote></details>

Done.
___
*[uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH0k7-2rvAurIZE5HU:-LlVHml1AeZ-htliKpMJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/VaadinIconSetTest-checkScreenshot_initial_ANY_Chrome__allVaadinIcons.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

See my answer above.
</blockquote></details>

Done.
___
*[uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png, line  at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlH1_f-9473hu5Aebfd:-LlVHmGG3PIgISJoeJ3C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/reference-screenshots/chrome/ValoThemeUITest-selects_ANY_Chrome__selects.png#L)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

See my answer above.
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlVGOH8C6cYnq8C7JH2:bb7f2mf) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Yes, exactly. It looks weird, but when it's there, the next person who uses an old tests as a reference is less likely to add the unnecessary space at the beginning of the returned String.
</blockquote></details>

done

**Review by Ansku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: 198 of 199 files reviewed, 1 unresolved discussion (waiting on @Ansku and @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlVLAfj0g3-I-IHFwzj:bhyhrde) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

done
</blockquote></details>

The returned value still has the extra space and the parameters don't get mentioned yet.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: 198 of 199 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlVOlcW19dAvJ-IT6WE:b-bax2dr) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

The returned value still has the extra space and the parameters don't get mentioned yet.
</blockquote></details>

check full diff please

**Review by Ansku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: 198 of 199 files reviewed, 1 unresolved discussion (waiting on @Ansku and @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlVPO_wDLILcP4y7oxB:bwilzgs) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

check full diff please
</blockquote></details>

I hate Reviewable defaults :P  Still can't see the position1 and position2 mentioned in the full diff.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: 198 of 199 files reviewed, all discussions resolved (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java, line 31 at r11](https://reviewable.io/reviews/vaadin/framework/11684#-LlGvtPB8BWODg_28XCH:-LlVRFFqDZ3H37RPu0Uu:b-7xvu7b) ([raw file](https://github.com/vaadin/framework/blob/e25afb6daa6efd44c657e86d7517413e430e8a0c/uitest/src/test/java/com/vaadin/tests/fonticon/GridLayoutOnFontLoadTest.java#L31)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

I hate Reviewable defaults :P  Still can't see the position1 and position2 mentioned in the full diff.
</blockquote></details>

check now

**Review by Ansku — APPROVED** [review]
> Reviewed 1 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11684)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
