### PR TITLE
Update release note for 8.8 releases

### PR DESCRIPTION
**Pull request by ZheSun88**
Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11541)

### CODE REVIEW

**Comment by anasmi** [comment]
@ZheSun88 Do you think we could also mention that click on Slider can now also change its value, if specified?

**Comment by ZheSun88** [comment]
@anasmi oh, I thought that is a bug fix, isn't it?

**Comment by anasmi** [comment]
I don't know :D There was, at least, API change.

@pleku , what do you think?

**Comment by ZheSun88** [comment]
@anasmi oh, just had a look on that change. Yeah. I will add them into the enhancement

**Review by pleku — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11541#-:-LcAgerw4PQlp3f53wKU:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ZheSun88)

**Review by pleku — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11541)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pleku and @ZheSun88)

**Review by pleku — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11541)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pleku and @ZheSun88)

**Review by pleku — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11541)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZheSun88)

**Pull request merged**
