### PR TITLE
Show drop hints when dropping in empty Grid

### PR DESCRIPTION
**Pull request by pleku**
Also makes sure that the drop location and target row in GridDropEvent return something sensible in that case.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9353)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9353#-KkPDDBXtm8pa2pf_tOA:-KkPDDBXtm8pa2pf_tOB:bxquzpp) (no related file):*
Still needs cross browser verification 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by hesara** [comment]
Reviewed 3 of 4 files at r1, 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 343 at r1](https://reviewable.io:443/reviews/vaadin/framework/9353#-KkPefledMO_UI1qoyN-:-KkPeflfy7dH1DWGHggl:b-7e2iw8) ([raw file](https://github.com/vaadin/framework/blob/d0657fbb412987e56a4dd633c0031805aa62dd31/documentation/advanced/advanced-dragndrop.asciidoc#L343)):*
> ```AsciiDoc
> ----
> 
> The _drop location_ property in the [classname]#GridDropEvent# specifies the dropped location in relative to grid row the drop happened on. Possible options are `ON_TOP`, `ABOVE` and `BELOW`, when the drop happened on top of a row. If the grid is empty, or if there was empty space after the last row in grid and the [classname]#DropMode.ON_TOP# was used, then the drop location `EMPTY` will be used. Then the [methodname]#getDropTargetRow# will also return an empty optional.
> ```

Document empty drop behavior in other drop modes as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by pleku** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 343 at r1](https://reviewable.io:443/reviews/vaadin/framework/9353#-KkPefledMO_UI1qoyN-:-KkPx3-DNfDqsLMtSU09:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d0657fbb412987e56a4dd633c0031805aa62dd31/documentation/advanced/advanced-dragndrop.asciidoc#L343)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Document empty drop behavior in other drop modes as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 347 at r3](https://reviewable.io:443/reviews/vaadin/framework/9353#-KkQ1BhSyCTEaNMc1_hv:-KkQ1BhSyCTEaNMc1_hw:b58rtoy) ([raw file](https://github.com/vaadin/framework/blob/101399213cf8adc89257bb183ae50f60346b0ec0/documentation/advanced/advanced-dragndrop.asciidoc#L347)):*
> ```AsciiDoc
> If the grid is empty, or if there was empty space after the last row in grid and the [classname]#DropMode.ON_TOP# was used, then the drop location `EMPTY` will be used. If the drop modes [classname]#DropMode.BETWEEN# or [classname]#DropMode.ON_TOP_OR_BETWEEN# are used, then the location can be `EMPTY` only when the grid was empty; otherwise the drop happened ´BELOW´ the last row. When the drop location is `EMPTY`, the [methodname]#getDropTargetRow# method will also return an empty optional.
> 
> If the 
> ```

If the ???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by pleku** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 347 at r3](https://reviewable.io:443/reviews/vaadin/framework/9353#-KkQ1BhSyCTEaNMc1_hv:-KkQENzLLEKSAMBWVpEX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/101399213cf8adc89257bb183ae50f60346b0ec0/documentation/advanced/advanced-dragndrop.asciidoc#L347)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

If the ???
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9353)*

**Pull request merged**
