### PR TITLE
Always return a fresh copy of BeanPropertySet from cache

### LINKED ISSUE #10590: Adding a nested property to a grid changes the columns generated by the Grid(Class) constructor
This is an issue since Vaadin 8.3.0
After adding a column to a grid with `Grid#addColumn(String)` method, the next time the constructor is called, it will generate the added column itself. This can break the grid when the page is refreshed (IllegalStateException: There already is a column for xyz.abc), or when a second grid is created later on, after the addColumn method has been called.

Here is a unit test which shows the breaking behaviour

```
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import com.vaadin.ui.Grid;

public class VaadinIssue10243AddNestedColumnTwiceBreaks {

   /**
    * This shows that Issue 10243 is still broken.
    * See:https://github.com/vaadin/framework/issues/10243
    */
   @Test
   public void testIssue10243() {
       Grid<Person> grid1 = new Grid(Person.class);
       grid1.addColumn("address.street");
       Grid<Person> grid2 = new Grid(Person.class);
       Assertions.assertThrows(IllegalStateException.class, () -> grid2.addColumn("address.street"));

   }

   class Person {
       public Address address;

       public Address getAddress() {
           return address;
       }
   }

   class Address {
       public String street;

       public String getStreet() {
           return street;
       }
   }
}
```

### LINKED ISSUE #10634: Adding nested properties to Binder and Grid is cached forever
```java
 public void testIssue10243() {
       Grid<Person> grid1 = new Grid(Person.class);
       grid1.addColumn("address.street");
       Grid<Person> grid2 = new Grid(Person.class);
       grid2.addColumn("address.street");
   }
```
Produces an exception. 
Other effects of the bug:
 - Opening of two grid instances defined with bean class and a nested property produce exceptions.
 - Page reload with a grid defined with bean class and a nested property  produces exception.

See #10590, #10272

### PR DESCRIPTION
**Pull request by elmot**
Fixes #10634
Fixes #10590
Fixes #10272

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10635)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 59 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10635#-L7iLrbGEz-npF2FQk6c:-L7iLrbGEz-npF2FQk6d:b-zefgz7) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L59)):*
> ```Java
>      */
>     private static class SerializedPropertySet implements Serializable {
>         private final InstanceKey instanceKey;
> ```

Should this be type with `<?>` ?

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 301 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10635#-L7iM1Cg-Fddz6BK-eY8:-L7iM1Cg-Fddz6BK-eY9:b-cofub1) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L301)):*
> ```Java
>     }
> 
>     private static final ConcurrentMap<InstanceKey, BeanPropertySet<?>> INSTANCES = new ConcurrentHashMap<>();
> ```

`InstanceKey<?>` ?

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 41 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10635#-L7iMDvX02GBOy8BE-iM:-L7iMDvX02GBOy8BE-iN:bp6ozlz) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L41)):*
> ```Java
> 
> import static com.vaadin.data.PropertyFilterDefinition.getDefaultFilter;
> import static org.junit.Assert.*;
> ```

I'd rather use specific imports than a catch-all

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 131 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10635#-L7iMbkY2jVJE9MtXhof:-L7iMbkY2jVJE9MtXhog:bojp6v4) ([raw file](https://github.com/vaadin/framework/blob/fd4dedf921f6cf0f80bfedac8474562b41325e56/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L131)):*
> ```Java
>                 address.getPostalCode(), postalCode);
> 
>         assertSame("Deserialized instance should be the same as in the cache",
> ```

Why is this check removed?

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospection.java, line 10 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10635#-L7iMnEC3f_YjjJkzgQm:-L7iMnEC3f_YjjJkzgQn:b-d7albh) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/test/java/com/vaadin/data/PropertyRetrospection.java#L10)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> 
> public class PropertyRetrospection {
> ```

Test class name not ending in `Test`. I wonder if surefire is catching it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10635)*

**Comment by elmot** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/10635#-L7iLrbGEz-npF2FQk6c:-L83FSoK0fhHAt6YrzkY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L59)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should this be type with `<?>` ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 301 at r2](https://reviewable.io:443/reviews/vaadin/framework/10635#-L7iM1Cg-Fddz6BK-eY8:-L83FT7pRJFeYkxKGnbH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L301)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`InstanceKey<?>` ?
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/framework/10635#-L7iMDvX02GBOy8BE-iM:-L83Fn7nU9RXSwbto3Ji:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L41)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd rather use specific imports than a catch-all
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BeanPropertySetTest.java, line 131 at r2](https://reviewable.io:443/reviews/vaadin/framework/10635#-L7iMbkY2jVJE9MtXhof:-L83GwEq1HRhQKasGL35:bay5x3w) ([raw file](https://github.com/vaadin/framework/blob/fd4dedf921f6cf0f80bfedac8474562b41325e56/server/src/test/java/com/vaadin/data/BeanPropertySetTest.java#L131)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is this check removed?
</blockquote></details>

The point of the patch is to make fresh copies when getting cached sets, so those sets are never the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10635)*

**Comment by elmot** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/10635#-L7iMnEC3f_YjjJkzgQm:-L83L1dV-NiEW1HCa_go:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef8980bf1215fb6b4624026a656e2e7fbe0a0851/server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java#L10)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Test class name not ending in `Test`. I wonder if surefire is catching it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10635)*

**Comment by tsuoanttila** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java, line 12 at r3](https://reviewable.io:443/reviews/vaadin/framework/10635#-L87faXOFKkorNk2uAid:-L87faXOFKkorNk2uAie:b-dh2tqf) ([raw file](https://github.com/vaadin/framework/blob/23fc0ccf357ffc5637733048b67fb480a4df2450/server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java#L12)):*
> ```Java
> public class PropertyRetrospectionTest {
> 
>     @SuppressWarnings("unused")
> ```

Why are the suppress warnings here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10635)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java, line 12 at r3](https://reviewable.io:443/reviews/vaadin/framework/10635#-L87faXOFKkorNk2uAid:-L8BfYbNmVn3E2OmFos4:bwch0pd) ([raw file](https://github.com/vaadin/framework/blob/23fc0ccf357ffc5637733048b67fb480a4df2450/server/src/test/java/com/vaadin/data/PropertyRetrospectionTest.java#L12)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why are the suppress warnings here?
</blockquote></details>

Those properties are used implicitly, some language checkers (ex. IDEA's) paint them yellow as unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10635)*

**Pull request merged**
