### PR TITLE
Add mouse event details to Tree.ItemClick

### PR DESCRIPTION
**Pull request by hesara**
This provides a way to get the mouse button clicked as requested
in #9335.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9599)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9599#-KnhpBtAmpeyevBv9YfO:-KnhpBtB09g0LGEwunHM:b-qocrr7) ([raw file](https://github.com/vaadin/framework/blob/1a1786701a9f9161229361d143d6766087320ee7/server/src/main/java/com/vaadin/ui/Tree.java#L116)):*
> ```Java
>          */
>         protected ItemClick(Tree<T> source, T item,
>                 MouseEventDetails mouseEventDetails) {
> ```

The parameter is not javadoced

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9599)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9599#-KnhpBtAmpeyevBv9YfO:-KnhqVeOeEjpmiWK3frD:bb6ywmx) ([raw file](https://github.com/vaadin/framework/blob/1a1786701a9f9161229361d143d6766087320ee7/server/src/main/java/com/vaadin/ui/Tree.java#L116)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The parameter is not javadoced
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9599#-:-Knhq_icQVXYf_HiHPI1:bnfp4nl)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9599#-KnhpBtAmpeyevBv9YfO:-KniH_T-6h85ObYiKTwX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1a1786701a9f9161229361d143d6766087320ee7/server/src/main/java/com/vaadin/ui/Tree.java#L116)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9599)*

**Comment by pinonpierre** [comment]
There is an issue.
I updated to 8.1.0.rc1 and event of addItemClickListener is not emitted on right click.

**Pull request merged**
