### PR TITLE
Clean connector tracker after each access block to stop memory leaks

### LINKED ISSUE #9303: Memory leak when updating the UI and no server visits or push take place
#7748 fixes a memory leak in ConnectorTracker when updating the UI without any updates going to the client. There are however more similar issues still in `ConnectorTracker`. 

Whenever you unregister a component, it gets added to the `unregisteredConnectors` set. This set, and related data structures, is cleaned only after a UIDL update is sent to the client. If there is no UIDL update sent, the `unregisteredConnectors` set will keep growing as long as you remove components from the UI.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #9303

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9305)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/VaadinSession.java, line 1017 at r1](https://reviewable.io:443/reviews/vaadin/framework/9305#-Kjv-r6q1ptFTY496kBo:-Kjv-r6rp6nILH1fNQqp:byb404u) ([raw file](https://github.com/vaadin/framework/blob/611d96274f5396a4b84a228819611a930f193cda/server/src/main/java/com/vaadin/server/VaadinSession.java#L1017)):*
> ```Java
>                     }
>                     try {
>                         ui.getConnectorTracker().cleanConnectorMap();
> ```

`cleanConnectorMap` is a quite expensive operation since it iterates all registered connectors in order to do some sanity checks. IIRC, the session will be locked and unlocked a couple of times for a regular round-trip, so it might make sense to split `cleanConnectorMap` into one part that prevents regular memory leaks and another that also does the sanity checks, and then only run the sanity checks once per round trip.

---

*[server/src/test/java/com/vaadin/ui/UITest.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/9305#-KjuzHili8w5reNMGHhZ:-KjuzHili8w5reNMGHh_:b-3qhaam) ([raw file](https://github.com/vaadin/framework/blob/611d96274f5396a4b84a228819611a930f193cda/server/src/test/java/com/vaadin/ui/UITest.java#L186)):*
> ```Java
>         ui.setContent(createContent());
>         session.unlock();
>         Assert.assertEquals(0, getUnregisteredConnectors(ui).size());
> ```

This way of testing will fail to catch regressions if a new collection is introduced. Could instead test that connectors are actually garbage collected using `WeakReference` similar to e.g. `CurrentInstanceTest.testRestoreWithGarbageCollectedValue()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinSession.java, line 1017 at r1](https://reviewable.io:443/reviews/vaadin/framework/9305#-Kjv-r6q1ptFTY496kBo:-Kjv8F0Gc3WuIHw8glCz:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/611d96274f5396a4b84a228819611a930f193cda/server/src/main/java/com/vaadin/server/VaadinSession.java#L1017)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`cleanConnectorMap` is a quite expensive operation since it iterates all registered connectors in order to do some sanity checks. IIRC, the session will be locked and unlocked a couple of times for a regular round-trip, so it might make sense to split `cleanConnectorMap` into one part that prevents regular memory leaks and another that also does the sanity checks, and then only run the sanity checks once per round trip.
</blockquote></details>

Done

---

*[server/src/test/java/com/vaadin/ui/UITest.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/9305#-KjuzHili8w5reNMGHhZ:-Kjv8JS-ukaS-feL1197:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/611d96274f5396a4b84a228819611a930f193cda/server/src/test/java/com/vaadin/ui/UITest.java#L186)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This way of testing will fail to catch regressions if a new collection is introduced. Could instead test that connectors are actually garbage collected using `WeakReference` similar to e.g. `CurrentInstanceTest.testRestoreWithGarbageCollectedValue()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Legioth** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 272 at r2](https://reviewable.io:443/reviews/vaadin/framework/9305#-KjvF8YkC19_3A55EPfY:-KjvF8YlL190ZUIymU5E:b-67gd8i) ([raw file](https://github.com/vaadin/framework/blob/96ad148721112d2b52c32db3e3d8bb53bc1d62ed/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L272)):*
> ```Java
>         GlobalResourceHandler globalResourceHandler = uI.getSession()
>                 .getGlobalResourceHandler(false);
>         while (iterator.hasNext()) {
> ```

This is the potentially expensive iteration of all registered connectors that I was referring to. I wouldn't see the assert parts as any issue since those would not be run in regular production environments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 272 at r2](https://reviewable.io:443/reviews/vaadin/framework/9305#-KjvF8YkC19_3A55EPfY:-KjvJQu_zTu5vDvqpEtv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96ad148721112d2b52c32db3e3d8bb53bc1d62ed/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L272)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This is the potentially expensive iteration of all registered connectors that I was referring to. I wouldn't see the assert parts as any issue since those would not be run in regular production environments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Legioth** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305#-:-KjvMLDC8mvCzMPqSkPZ:bnfp4nl)*

**Comment by Artur-** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 308 at r3](https://reviewable.io:443/reviews/vaadin/framework/9305#-Kjv_cSE-uZC_hihDCqX:-KjvfT6VXnXFAa00E3iO:b1ndxsa) ([raw file](https://github.com/vaadin/framework/blob/3d671d1b18f39e8bd8427efbe0bde9d443140644/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L308)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So where from `cleanConnectorMap()` is now invoked ? It seems that is not anymore happening at least from this method, since no call to `VaadinSession.unlock()`
</blockquote></details>

When the session is unlocked, which always happens after the UIDL is written (when response handling is done or a background thread access block is finished)

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 272 at r3](https://reviewable.io:443/reviews/vaadin/framework/9305#-KjvZsG9qxHNcEB-0RQ9:-Kjvfn4-UOrqlAFWCeE3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3d671d1b18f39e8bd8427efbe0bde9d443140644/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L272)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add "This should only be called by the framework."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1415 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF0Wp07Q1qfBdJMVRN:-KkF0Wp1PrQvCgx-e5dS:b-7zrm0a) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/server/src/main/java/com/vaadin/server/VaadinService.java#L1415)):*
> ```Java
> 
>                 // Check that connector tracker is in a consistent state here to
>                 // avoid doing it multiple times for a single request
> ```

So this is now on purpose done after inactive UI's have been cleaned or the session has been dropped ? For latter, it is also a NOOP since no UI's left

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1k7uJn2zKVhWiScQ:-KkF1k7uJn2zKVhWiScR:b-p583cf) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L30)):*
> ```Java
>         Button button = new Button(BUTTON_CAPTION);
>         button.addClickListener(e -> {
>             Runtime.getRuntime().gc();
> ```

Why * 4 ? Isn't that like a very unlucky number ?

(please clarify why so can be understood by someone later)

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 62 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1v2GUEracBQDLq3Q:-KkF1v2GUEracBQDLq3R:b-ul7t5k) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L62)):*
> ```Java
>             Runtime.getRuntime().gc();
>             Runtime.getRuntime().gc();
>             Runtime.getRuntime().gc();
> ```

Is this a fake *4 ? 

(please clarify why so can be understood by someone later)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 6 of 7 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 25 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1gdUCuWX4OkBvfC3:-KkF1gdUCuWX4OkBvfC4:bp03w6r) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L25)):*
> ```Java
>     protected void init(VaadinRequest vaadinRequest) {
> 
>         System.out.println("Vaadin version: "
> ```

(I guess this is unnecessary, but doesn't hurt too much in the test)

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1rw-CNY3RDQj_Uyi:-KkF1rw-CNY3RDQj_Uyj:bdw0srk) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L30)):*
> ```Java
>         Button button = new Button(BUTTON_CAPTION);
>         button.addClickListener(e -> {
>             Runtime.getRuntime().gc();
> ```

(feels quite "random" to do 4 * gc() + 500 ms delay here, and 5 * gc() + 500 ms delay below, and there is no guarantee about what the gc() calls do though probably ok on the JVMs we use with the settings we use)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1415 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF0Wp07Q1qfBdJMVRN:-KkF9iOJ1LiGi7wlbqQk:bjehvq9) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/server/src/main/java/com/vaadin/server/VaadinService.java#L1415)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So this is now on purpose done after inactive UI's have been cleaned or the session has been dropped ? For latter, it is also a NOOP since no UI's left
</blockquote></details>

This is done at the end of each request. If there are no UIs then it's a no-op for sure. 

Previously it was done at the end of UIDL writing but now when cleaning the connector tracker is postponed to until the session is unlocked, this validation must be done even after that. To avoid doing it at the end of every access block, it's placed here.

It would be enough to do it for the UI which the request related. Not sure if we can get that reliably here - or if it matters.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by Artur-** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 25 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1gdUCuWX4OkBvfC3:-KkFu1GE_jts3OPRfBqS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I guess this is unnecessary, but doesn't hurt too much in the test)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1k7uJn2zKVhWiScQ:-KkFu_IOb7fwRujzwjSV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L30)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why * 4 ? Isn't that like a very unlucky number ?

(please clarify why so can be understood by someone later)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1rw-CNY3RDQj_Uyi:-KkFu_pviMWU_21jooQQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(feels quite "random" to do 4 * gc() + 500 ms delay here, and 5 * gc() + 500 ms delay below, and there is no guarantee about what the gc() calls do though probably ok on the JVMs we use with the settings we use)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 62 at r5](https://reviewable.io:443/reviews/vaadin/framework/9305#-KkF1v2GUEracBQDLq3Q:-KkFuaLazoKxRzcPFIeM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3a787f8b0a6aa8b6dd38662e41d26d9c843f8cb2/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L62)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is this a fake *4 ? 

(please clarify why so can be understood by someone later)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9305)*

**Pull request merged**
