### PR TITLE
Update getting-started-scala.asciidoc

### PR DESCRIPTION
**Pull request by serragnoli**
As per recommendation of Fredrik Rönnlund following my post on https://dzone.com/articles/working-vaadin-with-scala

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9418)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2buVUmDyaPgvzn5mt:-Kl2buVUmDyaPgvzn5mu:bn1crba) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L23)):*
> ```AsciiDoc
> _Note that at this point you could import the project to and IDE like IntelliJ._
> 
> * You now should have the Vaadin Java project under the directoy `ui`. Since we are doing Scala, delete the `java` directory in `${project_home}/src/main/` and create an empty `scala` directory in the same place. 
> ```

directoy -> directory

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a_U-09YZDYq15AVM:-Kl2a_U-09YZDYq15AVN:b-m0r6l6) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L35)):*
> ```AsciiDoc
>   </dependency>
>  </dependencies>
>  <plugins>
> ```

this is a bit misleading as the "plugins" section should be inside the "build" section, and the example has the root level "project" directly above it

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2bCzMpDdKJLSToo_L:-Kl2bCzMpDdKJLSToo_M:b5tui63) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L58)):*
> ```AsciiDoc
> 
> * Create the following class in the new-created `scala` directory.
> ```scala
> ```

I'm not sure if all our documentation build tools handle this syntax for all the languages mentioned (xml, bash, scala), or if we should use the syntax
"
[source, scala]
----
...
----
"

@artur- might know better

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a0RBIQURe37_GRkG:-Kl2a0RBIQURe37_GRkH:b-uaf9df) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L110)):*
> ```AsciiDoc
> * Go to `localhost:8080` from the web browser and the page should be working:
> 
> image::https://cloud.githubusercontent.com/assets/4601281/26378300/da317d92-400b-11e7-9118-fd2b3b9cc942.png[]
> ```

we probably want to put the related images in the same repo as the documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2bCzMpDdKJLSToo_L:-Kl3AC1c1DgYvJqLC9yP:bfcqmdj) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L58)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm not sure if all our documentation build tools handle this syntax for all the languages mentioned (xml, bash, scala), or if we should use the syntax
"
[source, scala]
----
...
----
"

@artur- might know better

</blockquote></details>

Sorry, don't know

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Comment by serragnoli** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2buVUmDyaPgvzn5mt:-Kl4u3PlAjdCMAESdnzd:b-l6pazc) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

directoy -> directory
</blockquote></details>

Is this comment related to the repetition of the word "directory"?

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a_U-09YZDYq15AVM:-Kl4u7S_H5UAi9SOaxEQ:borbvnc) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L35)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this is a bit misleading as the "plugins" section should be inside the "build" section, and the example has the root level "project" directly above it
</blockquote></details>

Agreed. I've removed the misleading part and split the xml in two units.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2bCzMpDdKJLSToo_L:-Kl4uMlQ13d5IDIjHdfH:b-dx8h3c) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L58)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Sorry, don't know
</blockquote></details>

I chose that syntax because the original one '[source, scala]'  looked bad in the GitHub preview tool.
I've left it as it as until we know the syntax cannot be handled.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a0RBIQURe37_GRkG:-Kl4uqAnTitlmTOrk8tF:b38epwn) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L110)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

we probably want to put the related images in the same repo as the documentation
</blockquote></details>

Is that something I can do myself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2buVUmDyaPgvzn5mt:-KlIBtMYZrPoC1A1tlEv:b-3jbic9) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L23)):*
<details><summary><i>Previously, serragnoli (Fabio Serragnoli) wrote…</i></summary><blockquote>

Is this comment related to the repetition of the word "directory"?
</blockquote></details>

no, there is a typo in the word early in the sentence

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2bCzMpDdKJLSToo_L:-KlIEuy57SCuXdwW-vYu:b-vko0kq) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L58)):*
<details><summary><i>Previously, serragnoli (Fabio Serragnoli) wrote…</i></summary><blockquote>

I chose that syntax because the original one '[source, scala]'  looked bad in the GitHub preview tool.
I've left it as it as until we know the syntax cannot be handled.
</blockquote></details>

Somebody (from Vaadin) needs to try to build the paper book/PDF with these to test these, then.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a0RBIQURe37_GRkG:-KlIC5QhJaOU8Z7wVB9_:bgpzxmd) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L110)):*
<details><summary><i>Previously, serragnoli (Fabio Serragnoli) wrote…</i></summary><blockquote>

Is that something I can do myself?
</blockquote></details>

Yes - there is an img folder under getting-started, and the other getting-started documents use the correct syntax for referencing these. Note that we sometimes need custom syntax/path for the book build tools to work etc. and these might not be 100% the same as GitHub preview format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Comment by serragnoli** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2buVUmDyaPgvzn5mt:-KlPDBOx6ROiS3Ws4ku-:bvfxd7z) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

no, there is a typo in the word early in the sentence
</blockquote></details>

Seen it now.
Done.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 110 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2a0RBIQURe37_GRkG:-KlPNEYqKUVkC9u5qPN0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L110)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Yes - there is an img folder under getting-started, and the other getting-started documents use the correct syntax for referencing these. Note that we sometimes need custom syntax/path for the book build tools to work etc. and these might not be 100% the same as GitHub preview format.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/getting-started/getting-started-scala.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/9418#-Kl2bCzMpDdKJLSToo_L:-Kqwm5If6xEVJy0TzssS:b-dfnept) ([raw file](https://github.com/vaadin/framework/blob/39b1e1aa52f981ad218866afb7431d23b265a919/documentation/getting-started/getting-started-scala.asciidoc#L58)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Somebody (from Vaadin) needs to try to build the paper book/PDF with these to test these, then.
</blockquote></details>

Merging this and testing the documentation build after merge, will fix if necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9418)*

**Pull request merged**
