### PR TITLE
Make it possible to drop things between Grid rows

### LINKED ISSUE #8401: Make it possible to drop things between Grid rows
There should be some default styling shown between the rows that would get the drop.

Needs UX design.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves  #8401

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8979)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsnIDFpnVFRq9gP4vR:-KgsnIDFpnVFRq9gP4vS:b52agl9) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L24)):*
> ```Java
> 
> /**
>  * Server side drop event on an HTML5 drop target {@link Grid} row.
> ```

Please remove "Server side"

```
Event fired whenever there has been a drop on top of a Grid row.
 
```

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsniknlEV-XUNB8QdX:-KgsniknlEV-XUNB8QdY:bo56vy5) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L37)):*
> ```Java
> 
>     /**
>      * Creates a server side Grid row drop event.
> ```

remove server side

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsn9oAlTK0DvEZDO91:-Kgsn9oAlTK0DvEZDO92:b-tgfkvg) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L55)):*
> ```Java
>         super(target, dataTransferText, dragSourceExtension);
> 
>         dropTargetRow = target.getDataCommunicator().getKeyMapper()
> ```

Again, please move this to the caller instead of the constructor of an event object

---

*[server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsnyX3kW3UTDrEC60D:-KgsnyX3kW3UTDrEC60E:bmev6i2) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java#L42)):*
> ```Java
>      * @param target
>      *         Grid to be extended.
>      */
> ```

Missing `@param dropLocation`

---

*[server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsrT0MatLgrVkqpJKo:-KgsrT0MatLgrVkqpJKp:b-geajae) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java#L89)):*
> ```Java
>     protected void registerDropTargetRpc(Grid<T> target) {
>         registerRpc((GridDropTargetExtensionRpc) (dataTransferText, rowKey) -> {
>             GridDropEvent<T> event = new GridDropEvent<>(target,
> ```

This makes no distinction between the drop positions ?

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsrY_t_Y11oT2dilFy:-KgsrY_t_Y11oT2dilFz:b-f9nzj9) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java#L41)):*
> ```Java
>      *
>      */
>     ON_TOP_OR_BETWEEN_ROWS
> ```

This probably should not be here yet

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsqxb5-c_v7-_PU1GI:-Kgsqxb5-c_v7-_PU1GJ:b-psz18n) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L61)):*
> ```Java
> 
>         GridDropTargetExtension<Bean> dropTarget = new GridDropTargetExtension<>(
>                 dropTargetComponent, DropLocation.BETWEEN_ROWS);
> ```

Can you make this into something that can be easily switched from the test UI ? E.g. using a RadioButtonGroup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsv8N32swCLD8GMi0J:-Kgsv8N32swCLD8GMi0K:b9vgv0q) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L64)):*
> ```Java
>         dropTarget.addGridDropListener(event -> {
>             log(event.getDataTransferText() + ", targetId=" + event
>                     .getDropTargetRow().getId());
> ```

Also I'd like to be able to verify the drop location easily in the test ui, e.g. from the event ....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Comment by wbadam** [comment]
Review status: 1 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsnyX3kW3UTDrEC60D:-KgwqBs2iSFx6SSqatJ1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java#L42)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Missing `@param dropLocation`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java, line 89 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsrT0MatLgrVkqpJKo:-KgwqJy7wXHYQL6vmOz8:b-yaxz9a) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/ui/GridDropTargetExtension.java#L89)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This makes no distinction between the drop positions ?
</blockquote></details>

No because the feature wasn't finished. Don't ask why.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsrY_t_Y11oT2dilFy:-KgwqV9aU94uFjp6kESj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java#L41)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This probably should not be here yet
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsqxb5-c_v7-_PU1GI:-KgwyZ-NKDA_iwkenTzA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L61)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you make this into something that can be easily switched from the test UI ? E.g. using a RadioButtonGroup
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsv8N32swCLD8GMi0J:-KgwybKcx_b5qCS0D5AX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L64)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Also I'd like to be able to verify the drop location easily in the test ui, e.g. from the event ....
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsnIDFpnVFRq9gP4vR:-Kgsxd6kx13n6Jb-KraX:bklylkg) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L24)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please remove "Server side"

```
Event fired whenever there has been a drop on top of a Grid row.
 
```
</blockquote></details>

Removed the file

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-KgsniknlEV-XUNB8QdX:-KgsxfdjFUzNoKQrOU9P:bklylkg) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L37)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

remove server side
</blockquote></details>

Removed the file

---

*[server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgsn9oAlTK0DvEZDO91:-Kgwq3tisu0yHjeikPZ6:bklylkg) ([raw file](https://github.com/vaadin/framework/blob/4d7fb1f8b2b41d587d5d67868133e6a51a83b290/server/src/main/java/com/vaadin/event/dnd/grid/GridDropOnRowEvent.java#L55)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Again, please move this to the caller instead of the constructor of an event object
</blockquote></details>

Removed the file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Comment by pleku** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx4xXBMdAbEvj8ZOKl:-Kgx4xXBMdAbEvj8ZOKm:b-hmtare) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java#L19)):*
> ```Java
> 
> /**
>  * Defines possible drop locations within a Grid row.
> ```

mayhaps remove "possible" ?

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx3vdxUw_gs5xKyGCp:-Kgx3vdxUw_gs5xKyGCq:bn5vxw9) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L23)):*
> ```Java
>  * @author Vaadin Ltd.
>  * @since
>  */
> ```

Whatever you choose this to be, it should be wise to mention and add `@since` that points to the `GridDropEvent` getter for the actual location that was dropped on

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx2xu2mQsn8GFyq3vs:-Kgx2xu2mQsn8GFyq3vt:bfrqxpi) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L24)):*
> DropLocationAllowed

Really don't like this name... linguistically speaking it probably should be `AllowedDropLocation` and that too feels a bit bad. At least it is probably not used elsewhere than in the constructor or the setter..

Other options could be `DropMode` or `DropTargetMode`, `DropSpot`...

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx481tyUOVlszjLFnA:-Kgx481tyUOVlszjLFnB:b-nemjbb) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L30)):*
> ```Java
>      * row.
>      */
>     BETWEEN_ROWS,
> ```

Mayhaps these could be simplified by removing the suffix, to be `BETWEEN`, `ON_TOP` (and later `ON_TOP_AND_BETWEEN`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx4xXBMdAbEvj8ZOKl:-Kgx5vOgenI4TGI9bL7M:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocation.java#L19)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

mayhaps remove "possible" ?
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx3vdxUw_gs5xKyGCp:-KgxAzXjhWFCVOmRt_Uf:b-1a7g17) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L23)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Whatever you choose this to be, it should be wise to mention and add `@since` that points to the `GridDropEvent` getter for the actual location that was dropped on
</blockquote></details>

You mean `@see`, right? Cannot reference from client to server so I put reference on `GridDropTargetExtension#setDropMode()`'s javadoc

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx2xu2mQsn8GFyq3vs:-Kgx6GODcWe7PaMJXQHE:b-tt785s) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L24)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> DropLocationAllowed

Really don't like this name... linguistically speaking it probably should be `AllowedDropLocation` and that too feels a bit bad. At least it is probably not used elsewhere than in the constructor or the setter..

Other options could be `DropMode` or `DropTargetMode`, `DropSpot`...
</blockquote></details>

It _is_ horrible. `DropMode`, I think, is a good name and I believe and was discussed previously

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx481tyUOVlszjLFnA:-KgxBR0PG5ZEIgs7nrXX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropLocationAllowed.java#L30)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Mayhaps these could be simplified by removing the suffix, to be `BETWEEN`, `ON_TOP` (and later `ON_TOP_AND_BETWEEN`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/DropMode.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/8979#-Kgx3vdxUw_gs5xKyGCp:-Kh69OPjfEhR_VqhEP70:biupj53) ([raw file](https://github.com/vaadin/framework/blob/ad95d9dabcd6c75e0907eef59de9b90473e3710b/shared/src/main/java/com/vaadin/shared/ui/grid/DropMode.java#L23)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

You mean `@see`, right? Cannot reference from client to server so I put reference on `GridDropTargetExtension#setDropMode()`'s javadoc
</blockquote></details>

Yeah I meant `@see DropLocation` , `@see GridDropEvent#getDropLocation()` but it is not necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8979)*

**Pull request merged**
