### PR TITLE
Javadoc typo

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10056)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYv6qZnqu46lyKqCkc:-KuYv6qZnqu46lyKqCkd:b14ojni) (no related file):*
"iff" was not a typo but a shorthand for "if and only if". However, such shorthands should be avoided in documentation and in most cases, a simple "if" should be used in javadocs as you have converted them here, but a few cases do seem to need an explicit "... and only if". I'll try to mark those I feel need some such clarification.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1746 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ2ILhhfq13knEYQgu:-KuZ2ILhhfq13knEYQgv:b4hi6am) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1746)):*
> ```Java
>          *            the row element to check for if it is or has elements that
>          *            can be frozen
>          * @return <code>true</code> if this the given element, or any of its
> ```

(broken sentence)

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5939 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYwzfYnHNktwkrvmPb:-KuYwzfYnHNktwkrvmPc:bjfnuhg) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5939)):*
> ```Java
>      * headers, body or footer).
>      *
>      * @return <code>true</code> if header, body or footer has rows && there
> ```

(should use "and" instead of "&&")

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java, line 5924 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ-f2k-p39ZiCqJpB3:-KuZ-f2k-p39ZiCqJpB4:b5hwxdr) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java#L5924)):*
> ```Java
>      * headers, body or footer).
>      *
>      * @return <code>true</code> if header, body or footer has rows && there
> ```

should replace "&&" with "and"

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 418 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYvRHDVLomWXoMoCL_:-KuYvRHDVLomWXoMoCLa:bafhw3e) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L418)):*
> ```Java
> 
>         /**
>          * if one item is added, gives its index.
> ```

Use "If and only if" or something like that here for clarity, fix capitalization.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java, line 457 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ0MZPZou1SoHryDFT:-KuZ0MZQydUrcxyPhux7:b35fcyp) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java#L457)):*
> ```Java
>      *            True if caller is sure that repaint is not needed.
>      * @param ignoreReadOnly
>      *            True if if the read-only check should be ignored
> ```

"if if" => "if"

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java, line 999 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ0Svz2afm3INZIFL6:-KuZ0Sw-Ox0OJZe45o1W:ba0rlyz) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java#L999)):*
> ```Java
>      * because the field otherwise visually forget the user input immediately.
>      *
>      * @return true if the invalid values are allowed.
> ```

should really remove the word "the"

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractTextField.java, line 433 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ1GLI7eDbadudcP9q:-KuZ1GLI7eDbadudcP9r:b-hoqaqc) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractTextField.java#L433)):*
> ```Java
>              * change is coming from the client side.
>              *
>              * if there is both value change and textChangeEvent in same
> ```

fix capitalization

---

*[server/src/main/java/com/vaadin/event/dd/acceptcriteria/AcceptCriterion.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYvuJ22Ohvik7bSI_-:-KuYvuJ22Ohvik7bSI_0:b-69j813) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/server/src/main/java/com/vaadin/event/dd/acceptcriteria/AcceptCriterion.java#L63)):*
> ```Java
> 
>     /**
>      * This needs to be implemented if criterion does some lazy server side
> ```

here I'd use "if and only if"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056)*

**Comment by asashour** [comment]
Review status: 28 of 34 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYv6qZnqu46lyKqCkc:-KuZEGXqotgJNbFMtqSs:bh0yzg6) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"iff" was not a typo but a shorthand for "if and only if". However, such shorthands should be avoided in documentation and in most cases, a simple "if" should be used in javadocs as you have converted them here, but a few cases do seem to need an explicit "... and only if". I'll try to mark those I feel need some such clarification.
</blockquote></details>

Forgive my ignorance, and thanks for your tolerance.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1746 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ2ILhhfq13knEYQgu:-KuZFXKteJgDD4t_v5ZG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1746)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(broken sentence)
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 5939 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYwzfYnHNktwkrvmPb:-KuZFY6djP67uT2S11cW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L5939)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(should use "and" instead of "&&")
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java, line 5924 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ-f2k-p39ZiCqJpB3:-KuZF_C3tLxFyR-eJ7qg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java#L5924)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should replace "&&" with "and"
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 418 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYvRHDVLomWXoMoCL_:-KuZFlL6jO4kOW4UoIyw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L418)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Use "If and only if" or something like that here for clarity, fix capitalization.
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java, line 457 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ0MZPZou1SoHryDFT:-KuZFtLr-PikE-YVG9e2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java#L457)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"if if" => "if"
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java, line 999 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ0Svz2afm3INZIFL6:-KuZGAfzKxHij2fMnsa4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractField.java#L999)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should really remove the word "the"
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractTextField.java, line 433 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ1GLI7eDbadudcP9q:-KuZGYn7BdXBgaG9zCzg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractTextField.java#L433)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

fix capitalization
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dd/acceptcriteria/AcceptCriterion.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYvuJ22Ohvik7bSI_-:-KuZGiZo44xhLVXyRnB3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/server/src/main/java/com/vaadin/event/dd/acceptcriteria/AcceptCriterion.java#L63)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

here I'd use "if and only if"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuYv6qZnqu46lyKqCkc:-KuZLvZQ0BMlEFF_RWbi:bg0lby4) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Forgive my ignorance, and thanks for your tolerance.
</blockquote></details>

We really should not have used such a shorthand in general documentation, so it is rather our fault. Thank you for improving the documentation (and many other things) for everybody.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1746 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ2ILhhfq13knEYQgu:-KuZLgKPHLYqsq8wfiJY:b-rv2i1j) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1746)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Apparently also the previous sentence could use some fixing - what I meant was "... if this the given element..." where I guess "this" can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056)*

**Comment by asashour** [comment]
Review status: 33 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1746 at r1](https://reviewable.io:443/reviews/vaadin/framework/10056#-KuZ2ILhhfq13knEYQgu:-KuZNtHGLaX5F5BiLeNS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269099405775a6db3ec11a683ab1a33c0285de82/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1746)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Apparently also the previous sentence could use some fixing - what I meant was "... if this the given element..." where I guess "this" can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056#-:-KuZOuFL_wFDkkb6GdmG:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 13 of 19 files at r4, 5 of 6 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10056)*

**Pull request merged**
