### PR TITLE
Fix HTML tags inside code in javadoc

### PR DESCRIPTION
**Pull request by asashour**
Change `{@code }` to `<code>`, because Eclipse auto formatting doesn't handle HTML tags inside `{@code}`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10160)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWw_CuPoIMBVa2YhL:-KwdWw_CuPoIMBVa2YhM:b-xrg7k0) (no related file):*
Based on a quick test the Eclipse formatter messes up only specific HTML tags. `table` and `tr` seem to be on the list of failing things. For others, I'd rather have the `{@code <...>}` since it's a bit easier to read.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1135 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWjaDEwHu9TPR58-N:-KwdWjaDEwHu9TPR58-O:bc6mser) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1135)):*
> ```Java
>          * The table section element (<code>&lt;thead&gt;</code>,
>          * <code>&lt;tbody&gt;</code> or <code>&lt;tfoot&gt;</code>) the rows
>          * (i.e. <code>&lt;tr&gt;</code> tags) are contained in.
> ```

Only the <tr> needs to be changed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6320 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWqpNQSkt0HoSI0cK:-KwdWqpNQSkt0HoSI0cL:b-pjr914) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6320)):*
> ```Java
>     /**
>      * Adds the given role as 'role="$param"' to the
>      * <code>&lt;table /&gt;</code> element of the grid.
> ```

remove " /"

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java, line 1129 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWvTFOr17y1eMfMju:-KwdWvTFOr17y1eMfMjv:bc6mser) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java#L1129)):*
> ```Java
>          * The table section element (<code>&lt;thead&gt;</code>,
>          * <code>&lt;tbody&gt;</code> or <code>&lt;tfoot&gt;</code>) the rows
>          * (i.e. <code>&lt;tr&gt;</code> tags) are contained in.
> ```

Only the <tr> needs to be changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1135 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWjaDEwHu9TPR58-N:-Kwd_qWS_6mDdXaA6Tr-:b-91ar1k) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1135)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Only the <tr> needs to be changed.
</blockquote></details>

`<tr>`. Thanks Reviewable.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java, line 1129 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWvTFOr17y1eMfMju:-Kwd_xYl6vL9sr7yHYSl:b-91ar1k) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java#L1129)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Only the <tr> needs to be changed.
</blockquote></details>

`<tr>`. Thanks Reviewable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by asashour** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1135 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWjaDEwHu9TPR58-N:-Kwe5K4JTbQDhGw5TN4r:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1135)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<tr>`. Thanks Reviewable.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6320 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWqpNQSkt0HoSI0cK:-Kwe5iUz-au5N7q3lKDa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6320)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

remove " /"
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java, line 1129 at r1](https://reviewable.io:443/reviews/vaadin/framework/10160#-KwdWvTFOr17y1eMfMju:-Kwe5YuiWEFBY-xRy_bi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6f88674c658f5bc2d4df8e2dc05e6e6528aa6a3/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Escalator.java#L1129)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<tr>`. Thanks Reviewable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by torok-peter** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 6797 at r2](https://reviewable.io:443/reviews/vaadin/framework/10160#-Kwe7pzNTF8M8yNS9V2C:-Kwe7pzOQOgOrLrZhCv1:b-qzzy18) ([raw file](https://github.com/vaadin/framework/blob/cb2e5fe4c7aedd86e587befa9a1edf5b645552fb/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L6797)):*
> ```Java
>      * 
>     <table />
>      * } element of the grid.
> ```

Please fix this one too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by asashour** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 6797 at r2](https://reviewable.io:443/reviews/vaadin/framework/10160#-Kwe7pzNTF8M8yNS9V2C:-Kwe959B4xvFNicXDRLT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cb2e5fe4c7aedd86e587befa9a1edf5b645552fb/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L6797)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Please fix this one too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10160#-:-KweBGQ9LPCaL7rq9ap8:bnfp4nl)*

**Pull request merged**
