### PR TITLE
WIP tree documentation

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9184)

### CODE REVIEW

**Comment by ahie** [comment]
Could also add a mention of `Tree` to the hierarchical data chapter in this patch. Currently only `TreeGrid` is mentioned there.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184#-:-Kj8-oDtWGR3fPPrH_7m:b-8r5sji)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[documentation/components/chapter-components.asciidoc, line 51 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-Kj8jeaa83DOSLD0Tr2E:-Kj8jeabTlyGd3ETDbdU:b-qutjpq) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/chapter-components.asciidoc#L51)):*
> ```AsciiDoc
> include::components-treegrid.asciidoc[leveloffset=+2]
> 
> include::components-tree.asciidoc[leveloffset=+2]
> ```

when inserting between items, the order fields of later chapters (menubar, ..., embedded) probably need to be updated

---

*[documentation/components/components-tree.asciidoc, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBlLeS_16tCk7n5WMB:-KjBlLeS_16tCk7n5WMC:bmbehm) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L28)):*
> ```AsciiDoc
> 
> [[figure.components.tree]]
> //TODO add the screenshot
> ```

add screenshot - Tree and theme now in master

---

*[documentation/components/components-tree.asciidoc, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBl_7etFr3wUw_TB8b:-KjBl_7etFr3wUw_TB8c:b-vp9way) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L44)):*
> ```AsciiDoc
> 
> The [methodname]#setItems# method in [classname]#Tree# can be used to set the root level items. Internally
> an [classname]#InMemoryHierarchicalDataProvider# with [classname]#HierarchyData# is used. If at any time you want to modify the in-memory data in the tree, you may do it as follows
> ```

the example doesn't really show modification of data IMO, just initial data

---

*[documentation/components/components-tree.asciidoc, line 66 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBln0AaEtAaqFmFTtA:-KjBln0AaEtAaqFmFTtB:by62byy) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L66)):*
> ```AsciiDoc
> ----
> 
> The result was shown in <<figure.components.tree>> in a practical situation, with the [classname]`Tree` wrapped inside a [classname]`Panel`.
> ```

Is this still the case, or does the TreeGrid of the Tree provide scrolling?

---

*[documentation/components/components-tree.asciidoc, line 69 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBltf9MFrE7MBgCvsD:-KjBltf9MFrE7MBgCvsE:b-rizmgo) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L69)):*
> ```AsciiDoc
> [classname]`Tree` itself does not have scrollbar, but [classname]`Panel` can be used for the purpose.
> 
> The caption and the icon of tree items is generated by the [classname]#ItemCaptionGenerator# and the [classname]#IconGenerator#, set with
> ```

set with ???

---

*[documentation/components/components-tree.asciidoc, line 76 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBm03RJwEZ0s2x6oz2:-KjBm03RJwEZ0s2x6oz3:b-m4rawe) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L76)):*
> ```AsciiDoc
> [classname]#Tree# supports single selection mode, you can use [methodname]#asSingleSelect()# to access the selection
> object, which supports selection listeners and data binding. For more details, see link:<<dummy/../../../framework/datamodel/datamodel-selection.asciidoc#datamodel.selection,"Selecting Items">>.
> The [classname]#Tree# supports also a shortcut method [methodname]#addSelectionListener()#
> ```

... also supports the shortcut method [methodname]#addSelectionListener()# . (end sentence with full stop)

---

*[documentation/components/components-tree.asciidoc, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBmHj-ZdzQUTFOhNgj:-KjBmHj-ZdzQUTFOhNgk:b-x47jd) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L79)):*
> ```AsciiDoc
> 
> ////
> todo not implemented yet.
> ```

should probably create a ticket about this feature and enabling its docs

---

*[documentation/components/components-tree.asciidoc, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBmQNSTCB4GZ8GHj8f:-KjBmQNSTCB4GZ8GHj8g:b-gjgcas) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L108)):*
> ```AsciiDoc
> // in the visible hierarchy, nothing will be shown.
> tree.expand(childProject);
> // Expands the root project. If child project now becomes
> ```

TBC that this works (should work)

---

*[documentation/components/components-tree.asciidoc, line 130 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBp_xV3vgOCtoWeEJ2:-KjBp_xV3vgOCtoWeEJ3:bb3y830) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L130)):*
> ```AsciiDoc
> 
> ////
> todo not implemented yet
> ```

create ticket for the feature and completing related docs

---

*[documentation/components/components-tree.asciidoc, line 156 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBpjFFYi_mS_OLZLgn:-KjBpjFFYi_mS_OLZLgo:be5trap) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L156)):*
> ```AsciiDoc
> 
> ////
> todo styling documentation
> ```

to update and enable once we have the new class names etc.

---

*[documentation/datamodel/datamodel-hierarchical.asciidoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBpxyi6ffZDsQvhSgA:-KjBpxyi6ffZDsQvhSgB:b-mqjxo6) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/datamodel/datamodel-hierarchical.asciidoc#L15)):*
> ```AsciiDoc
> That data can be populated by on-demand from a back end by implementing the [interfacename]#HierarchicalDataProvider# interface. If you have the data available in-memory on the server,
> you use the collection style API of [classname]#HierarchyData# and then pass it to a [classname]#InMemoryHierarchicalDataProvider#. This chapter introduces the hierarchical data providers and how they work.
> For using them with the components you should see <<dummy/../../../framework/components/components-tree.asciidoc#components.tree,"Tree">>
> ```

order not the same as above, so not really "respectively"; probably needs manual merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by hesara** [comment]
Reviewed 10 of 11 files at r3.
Review status: 11 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by elmot** [comment]
Review status: 10 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[documentation/components/chapter-components.asciidoc, line 51 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-Kj8jeaa83DOSLD0Tr2E:-KjC01rPv9GlRvDejLBX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/chapter-components.asciidoc#L51)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

when inserting between items, the order fields of later chapters (menubar, ..., embedded) probably need to be updated
</blockquote></details>

Done.

---

*[documentation/components/components-tree.asciidoc, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBlLeS_16tCk7n5WMB:-KjCIiUpM83aoFnbVtWY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

add screenshot - Tree and theme now in master
</blockquote></details>

Done.

---

*[documentation/components/components-tree.asciidoc, line 69 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBltf9MFrE7MBgCvsD:-KjCFGLjKdouSJhKDwlM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L69)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

set with ???
</blockquote></details>

Done.

---

*[documentation/components/components-tree.asciidoc, line 76 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBm03RJwEZ0s2x6oz2:-KjC31Hgh2s7lzruBza4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L76)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... also supports the shortcut method [methodname]#addSelectionListener()# . (end sentence with full stop)
</blockquote></details>

Done.

---

*[documentation/components/components-tree.asciidoc, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBmHj-ZdzQUTFOhNgj:-KjC3YRGGFz7nFLxz_tV:b-43qd4i) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L79)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should probably create a ticket about this feature and enabling its docs
</blockquote></details>

See #9215

---

*[documentation/components/components-tree.asciidoc, line 130 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBp_xV3vgOCtoWeEJ2:-KjC42ZQzkcoRb8zumiK:b-43qd4i) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L130)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

create ticket for the feature and completing related docs
</blockquote></details>

See #9215

---

*[documentation/datamodel/datamodel-hierarchical.asciidoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBpxyi6ffZDsQvhSgA:-KjCIdEIVRubKd8tnzaB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/datamodel/datamodel-hierarchical.asciidoc#L15)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

order not the same as above, so not really "respectively"; probably needs manual merge
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by elmot** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/components/components-tree.asciidoc, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBl_7etFr3wUw_TB8b:-KjDd576B-o3eqQtN4Ou:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L44)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the example doesn't really show modification of data IMO, just initial data
</blockquote></details>

Done.

---

*[documentation/components/components-tree.asciidoc, line 66 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBln0AaEtAaqFmFTtA:-KjDbhpsI80App7sXtv8:b-n4x5mo) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L66)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this still the case, or does the TreeGrid of the Tree provide scrolling?
</blockquote></details>

Not, it is not, the statement is removed.

---

*[documentation/components/components-tree.asciidoc, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjBmQNSTCB4GZ8GHj8f:-KjDbKQVMcaw0ZslNmUX:bvxv5cg) ([raw file](https://github.com/vaadin/framework/blob/d1ffd0fa1c18d970fc15da95909ff10fc3e186e9/documentation/components/components-tree.asciidoc#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC that this works (should work)
</blockquote></details>

Yes, that works, and we have both examples and tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 168 at r5](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjGr-dAlL06lYcV2BBP:-KjGr-dAlL06lYcV2BBQ:b-q01j9v) ([raw file](https://github.com/vaadin/framework/blob/8ad6d34f267712138902a8778dc2c28646c47f30/documentation/components/components-tree.asciidoc#L168)):*
> ```AsciiDoc
> 
> ////
> todo styling documentation
> ```

we can either publish the tree documentation and then update the theming part in a separate commit, or update this first and then publish the documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[documentation/components/components-tree.asciidoc, line 168 at r5](https://reviewable.io:443/reviews/vaadin/framework/9184#-KjGr-dAlL06lYcV2BBP:-KjH21SGiPmbi0P61fMZ:b9p60bm) ([raw file](https://github.com/vaadin/framework/blob/8ad6d34f267712138902a8778dc2c28646c47f30/documentation/components/components-tree.asciidoc#L168)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

we can either publish the tree documentation and then update the theming part in a separate commit, or update this first and then publish the documentation
</blockquote></details>

Let's do that in the separate commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9184)*

**Pull request merged**
