### PR TITLE
fix: don't serve directories as static files

### PR DESCRIPTION
**Pull request by Ansku**
Modified cherry-picks of https://github.com/vaadin/flow/pull/11072 and
https://github.com/vaadin/flow/pull/11147

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)

### CODE REVIEW

**Review by edler-san — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)* status: all files reviewed, 4 unresolved discussions (waiting on @Ansku)

___
*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 1368 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsD2VS953ygpIVX0Im:-McsD2VS953ygpIVX0In:bj73deg) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/main/java/com/vaadin/server/VaadinServlet.java#L1368)):*
Maybe extract the value of `openFileSystems.computeIfPresent(fileURI,  (key, value) -> value + 1)` to a new variable to improve readability of the statement like you did in L1385.
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>             if (openFileSystems.computeIfPresent(fileURI,
>                     (key, value) -> value + 1) != null) {
>                 // Get filesystem is for the file to get the correct provider
>                 return FileSystems.getFileSystem(resourceURI);
>             }
> ```
</details>

___
*[server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java, line 19 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsFH2d6KQXjEbYar9v:-McsFH2d6KQXjEbYar9w:b-16he4g) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java#L19)):*
> ```Java
> 
>     // Singleton instance
>     private static volatile WarURLStreamHandlerFactory instance = null;
> ```

`volatile` not needed or need unclear
___
*[server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java, line 48 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsFOlI-QlQoZiTYyhO:-McsFOlI-QlQoZiTYyhP:bc2ygne) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java#L48)):*
> ```Java
>     }
> 
>     private WarURLStreamHandlerFactory(boolean register) {
> ```

Method must be synchronized if you want a Singleton. I recommend using an Enum singleton instead. (https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/)

**Review by edler-san — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)* status: all files reviewed, 4 unresolved discussions (waiting on @Ansku)

___
*[server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java, line 19 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsFH2d6KQXjEbYar9v:-McsSQ1p92qIzR86s3X2:bn7bxea) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java#L19)):*
<details><summary><i>Previously, edler-san wrote…</i></summary><blockquote>

`volatile` not needed or need unclear
</blockquote></details>

Used for double-checked locking later on.
___
*[server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java, line 48 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsFOlI-QlQoZiTYyhO:-McsRZl_D4Q3Runv9Xvp:bp7yd9w) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/test/java/com/vaadin/server/WarURLStreamHandlerFactory.java#L48)):*
<details><summary><i>Previously, edler-san wrote…</i></summary><blockquote>

Method must be synchronized if you want a Singleton. I recommend using an Enum singleton instead. (https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/)
</blockquote></details>

It is synchronised in the calling method.

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @edler-san and @sonatype-lift[bot])

___
*[server/src/main/java/com/vaadin/server/VaadinServlet.java, line 1368 at r2](https://reviewable.io/reviews/vaadin/framework/12325#-McsD2VS953ygpIVX0Im:-McsVO7zCP62FTxOeNGX:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/984821fd4f6ae7be0b5ba4f3a84c194c8595ad54/server/src/main/java/com/vaadin/server/VaadinServlet.java#L1368)):*
<details><summary><i>Previously, edler-san wrote…</i></summary><blockquote>

Maybe extract the value of `openFileSystems.computeIfPresent(fileURI,  (key, value) -> value + 1)` to a new variable to improve readability of the statement like you did in L1385.

> ```
>             if (openFileSystems.computeIfPresent(fileURI,
>                     (key, value) -> value + 1) != null) {
>                 // Get filesystem is for the file to get the correct provider
>                 return FileSystems.getFileSystem(resourceURI);
>             }
> ```

</blockquote></details>

Done
___
*[server/src/main/java/com/vaadin/server/VaadinServletService.java, line 253 at r1](https://reviewable.io/reviews/vaadin/framework/12325#-McPiqnqh6oo45c5pZiu-r1-253:-McsVa1nANTeitJfkfLj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bf8c8d005ec7b7f72fed145bd9ee2e026b2c5356/server/src/main/java/com/vaadin/server/VaadinServletService.java#L253)):*
<details><summary><i>Previously, sonatype-lift[bot] wrote…</i></summary><blockquote>

*FormatString:*  extra format arguments: used 0, provided 1
(at-me [in a reply](https://help.sonatype.com/lift) with `help` or `ignore`)
</blockquote></details>

Done.

**Review by edler-san — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)* status: all files reviewed, 1 unresolved discussion (waiting on @sonatype-lift[bot])

**Review by Ansku — COMMENTED** [review]
> Dismissed @sonatype-lift[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ansku)

**Pull request merged**
