### PR TITLE
Ensure that HeaderRow is not null in Grid

### LINKED ISSUE #10485: Grid has wrong width if no header
Vaadin Framework 8.2.0

A grid without header (by grid.removeHeaderRow(0)) doesn't apply width settings, both on single columns then in whole grid.
The following code works on Vaadin 8.7.1

```
capGrid.setItems(capabilities);
capGrid.removeHeaderRow(0);
capGrid.setColumns("name");
capGrid.getColumn("name").setExpandRatio(1).setWidth(200);
capGrid.setSizeFull():
```

image

### PR DESCRIPTION
**Pull request by anasmi**
Fix #10485

If header row is not present, than there is no need to make SelectAllCheckbox visible. Otherwise, NPE is thrown on the client side and widths is not applied properly.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11165)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11165)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @anasmi)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 10 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLib2-VCKTKk3Xifr0m:-LLib2-VCKTKk3Xifr0n:b-o9qsk2) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L10)):*
> ```Java
> import static org.junit.Assert.assertTrue;
> 
> public class GridColumnWidthWithoutHeaderTest extends MultiBrowserTest {
> ```

SingleBrowserTest is enough I think
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 24 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLib8HX6nPe8HZuD7uY:-LLib8HX6nPe8HZuD7uZ:be135qn) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L24)):*
> ```
> THREASHOLD
> ```
Typo

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11165)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @elmot and @anasmi)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 19 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLibG9q3QN727mQKLX7:-LLibG9q3QN727mQKLX8:b9ft0bw) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L19)):*
> ```Java
>         GridElement grid = $(GridElement.class).first();
>         int columnsWidth = getColWidthsRounded(grid);
>         // int gridWrapperWidth=
> ```

dead code to be removed
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLibKEOCl8OJmWAuNPr:-LLibKEOCl8OJmWAuNPs:bwwvxah) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L21)):*
> ```Java
>         // int gridWrapperWidth=
>         // getDriver().findElement(By.className("v-grid-tablewrapper")).getSize().getWidth();
>         System.out.println(grid.getSize().getWidth());
> ```

please remove `println`s, use assert message instead

**Review by anasmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11165)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @elmot and @anasmi)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 10 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLib2-VCKTKk3Xifr0m:-LLmxJGG64R5WErxdeKk:b499q7j) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L10)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

SingleBrowserTest is enough I think
</blockquote></details>

Changed
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 19 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLibG9q3QN727mQKLX7:-LLmxKS8BhWsvWfrsFKT:b9n1skk) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L19)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

dead code to be removed
</blockquote></details>

(I suppose it's an older version of WIP? Was removed before)
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLibKEOCl8OJmWAuNPr:-LLmxQfx6B6H-OJ7-zZW:b9n1skk) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L21)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

please remove `println`s, use assert message instead
</blockquote></details>

(I suppose it's an older version of WIP? Was removed before)
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java, line 24 at r1](https://reviewable.io/reviews/vaadin/framework/11165#-LLib8HX6nPe8HZuD7uY:-LLmxS0Y43iI1w8vAfyg:b-886gsx) ([raw file](https://github.com/vaadin/framework/blob/71d8a7d83bcdf8c5d6c9634bbd1ebc1c5ee82192/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnWidthWithoutHeaderTest.java#L24)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> ```
> THREASHOLD
> ```
Typo
</blockquote></details>

Fixed

**Review by elmot — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11165#-:-LLn83na7hWkGMEYhOFe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
