### PR TITLE
Grid Editor: make Tab key skip read-only/disabled fields

### LINKED ISSUE #11584: Grid editor tabs to disabled/readonly fields
Vaadin 8.8.1; Building on issue https://github.com/vaadin/framework/issues/10970 the issue is unfortunately not completely fixed - if the editor cell has a field which is either disabled or read-only, it will still be focused with tab/shift+tab. Please find an example app attached which reproduces the issue.
[vaadin8-app.zip](https://github.com/vaadin/framework/files/3191448/vaadin8-app.zip)
The `col0` and `col1` columns should not be focusable with tab since they contain components that are disabled or read-only.

### PR DESCRIPTION
**Pull request by mvysny**
Fixes #11584

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mvysny)

___
*[client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java, line 218 at r1](https://reviewable.io/reviews/vaadin/framework/11586#-Lg24A2EERQp7Wh8NSK7:-Lg24A2EERQp7Wh8NSK8:b-773nde) ([raw file](https://github.com/vaadin/framework/blob/7b86bde779fcfb0643d13e3e0190cc104905e265/client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java#L218)):*
> ```Java
>      *         column.
>      */
>     protected int findNextEditableColumnIndex(Grid<T> grid, int startingWith) {
> ```

do we really need to change the access modifiers?

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mvysny and @ZheSun88)

**Review by mvysny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java, line 218 at r1](https://reviewable.io/reviews/vaadin/framework/11586#-Lg24A2EERQp7Wh8NSK7:-Lg2EkKEDoyPu3sskvVQ:bmfjbwf) ([raw file](https://github.com/vaadin/framework/blob/7b86bde779fcfb0643d13e3e0190cc104905e265/client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java#L218)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

do we really need to change the access modifiers?
</blockquote></details>

It's not necessary strictly speaking; but having the method protected would allow extensions such as https://vaadin.com/directory/component/gridfastnavigation-add-on override only parts of the algorithm, instead of fully reimplementing the whole algorithm.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: all files reviewed, 1 unresolved discussion (waiting on @mvysny)

___
*[client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java, line 218 at r1](https://reviewable.io/reviews/vaadin/framework/11586#-Lg24A2EERQp7Wh8NSK7:-Lg2Jenn4g8SgUvFTyfV:bg7igkv) ([raw file](https://github.com/vaadin/framework/blob/7b86bde779fcfb0643d13e3e0190cc104905e265/client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java#L218)):*
<details><summary><i>Previously, mvysny (Martin Vysny) wrote…</i></summary><blockquote>

It's not necessary strictly speaking; but having the method protected would allow extensions such as https://vaadin.com/directory/component/gridfastnavigation-add-on override only parts of the algorithm, instead of fully reimplementing the whole algorithm.
</blockquote></details>

:lgtm: 
___
*[client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java, line 130 at r3](https://reviewable.io/reviews/vaadin/framework/11586#-Lg2KFmz0LOaO3A-ezKm:-Lg2KFn-Cfod98GATWrd:b-22bq3t) ([raw file](https://github.com/vaadin/framework/blob/791624852997b7190db7d8460245d5ca386fe9c6/client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java#L130)):*
> ```Java
>     }
> 
>     public static class Delta {
> ```

could we add some javadoc for this class?

**Comment by mvysny** [comment]
Thank you! Yeah, the `Delta` class was a bit shady. I've refactored it to a more meaningful `CursorMoveDelta` (or a `CursorMoveDirection` would be even better).

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: all files reviewed, 1 unresolved discussion (waiting on @mvysny)

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11586)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
