### PR TITLE
Updated IE screenshots

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12266)

### CODE REVIEW

**Review by edler-san — COMMENTED** [review]
> Reviewed 74 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ansku)

**Review by edler-san — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12266)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java, line 32 at r2](https://reviewable.io/reviews/vaadin/framework/12266#-MYJhHiF4wAvC9RNl29-:-MYJhHiF4wAvC9RNl290:b-tkc6uv) ([raw file](https://github.com/vaadin/framework/blob/7f627a11fb20942ea7bc5a676a52fc0e8b98dd6e/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java#L32)):*
> ```Java
> 
>         findElement(By.id("test-button")).click();
>         sleep(100);
> ```

Isn't sleep rather unreliable?

**Comment by Ansku** [comment]
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java, line 32 at r2](https://reviewable.io/reviews/vaadin/framework/12266#-MYJhHiF4wAvC9RNl29-:-MYJiZbJ4SEsgDlWLd86:b-o0jrp8) ([raw file](https://github.com/vaadin/framework/blob/7f627a11fb20942ea7bc5a676a52fc0e8b98dd6e/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java#L32)):*
<details><summary><i>Previously, edler-san wrote…</i></summary><blockquote>

Isn't sleep rather unreliable?
</blockquote></details>

That's why waitUntil, because it does it repeatedly rather than relying on a fixed amount.

**Review by edler-san — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12266)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java, line 32 at r2](https://reviewable.io/reviews/vaadin/framework/12266#-MYJhHiF4wAvC9RNl29-:-MYJjoQUBAY1Dql0sWvA:baowjji) ([raw file](https://github.com/vaadin/framework/blob/7f627a11fb20942ea7bc5a676a52fc0e8b98dd6e/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldEventOrderTest.java#L32)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

That's why waitUntil, because it does it repeatedly rather than relying on a fixed amount.
</blockquote></details>

Omg, I read the left side as new. >_< My bad. :lgtm:

**Pull request merged**
