### PR TITLE
Make it possible to upload files by dropping them onto a drop target

### LINKED ISSUE #8891: When listing files in UI, I want the user to be able to DnD files on top of the listing, to get them uploaded to the application
This `HTML5FileDropTargetExtension extends DropTargetExtension` should replace the old feature for accepting drops for files from desktop. Similarly to the old one, the file should be automatically uploaded and the user can use the receiver to decide what to do with the file.

This sample should be replaced with the new one: http://demo.vaadin.com/sampler-77/#ui/drag-drop/drag-from-desktop

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #8891

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9277)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIdtKZdQzjG1oxKwi:-KjlIdtKZdQzjG1oxKwj:b-aq2wed) (no related file):*
Missing documentation

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIfH-iW2-v0OiLOCQ:-KjlIfH-iW2-v0OiLOCR:bni47gk) (no related file):*
Pending manual testing

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjieHO4VuzbrH7pcmgX:-KjieHO4VuzbrH7pcmgY:b-65fpuz) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L37)):*
> to accept

what does this mean ?

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjieMaQCi05IJaPGzhX:-KjieMaQCi05IJaPGzhY:b-q8p00k) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L38)):*
> Client side counterpart of {@link FileDropTarget}.

Is this really needed ?

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlDjqPC1Bv0xdb7FbJ:-KjlDjqPC1Bv0xdb7FbK:b-d7gver) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L130)):*
> ```Java
>         }
> 
>         event.preventDefault();
> ```

If the drop is handled on this level, should add `event.stopPropagation()` ?

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 182 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlE6vZPT5OapcNC81Q:-KjlE6vZPT5OapcNC81R:b-9bxfy9) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L182)):*
> ```Java
>         }
> 
>         // TODO Make it detect folders on all browsers
> ```

So is folder upload now supported on any browser ? Is there a ticket for this TODO ?

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlHs7BaxCLuBy_73-M:-KjlHs7BaxCLuBy_73-N:b-72sdy7) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java#L28)):*
> ```Java
>     private String name;
>     private long size;
>     private String mime;
> ```

Why are these not final and getters removed ?

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIPRqhsfvVFznQZxM:-KjlIPRry5cq4hPDBxmI:b-v17b25) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L37)):*
> ```Java
>     protected void setup(VaadinRequest request) {
> 
>         Label dropArea = new Label("Drop files here");
> ```

How bout adding also a Grid and making it a file drop target, you could log a new row for each stream event for each file ?

Just for better testing

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIG4WCI2COEdLF8bA:-KjlIG4WCI2COEdLF8bB:b2nific) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L96)):*
> ```Java
>     }
> 
>     private void setStyle() {
> ```

wtf

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIHk_aJOkOP8nauP3:-KjlIHk_aJOkOP8nauP4:b-yt14py) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L116)):*
> ```Java
>     @Override
>     protected String getTestDescription() {
>         return "Shuffle cards with pure HTML5 drag and drop";
> ```

please update

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIzTb9HD0Y3wAEM8b:-KjlIzTb9HD0Y3wAEM8c:b-quzc01) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java#L25)):*
> ```Java
>  * @since 8.1
>  */
> public class FileParameters {
> ```

needs to be serializable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Comment by wbadam** [comment]
Review status: 6 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIdtKZdQzjG1oxKwi:-Kjm39gfP6KUjlatXcET:bqvwjo3) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Added doc

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjieHO4VuzbrH7pcmgX:-Kjm5MPcOzGTFmx9sQvN:b6g7c11) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L37)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> to accept

what does this mean ?
</blockquote></details>

Rephrased. 

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjieMaQCi05IJaPGzhX:-Kjm41yekp5LbXRY9r5o:b-agya2r) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L38)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Client side counterpart of {@link FileDropTarget}.

Is this really needed ?
</blockquote></details>

Not really

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlDjqPC1Bv0xdb7FbJ:-Kjm5WwmLPRIlL-7_zV6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L130)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

If the drop is handled on this level, should add `event.stopPropagation()` ?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java, line 182 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlE6vZPT5OapcNC81Q:-KjlpgB7jOwXNgzL2IGh:brbr3rt) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/client/src/main/java/com/vaadin/client/extensions/FileDropTargetConnector.java#L182)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So is folder upload now supported on any browser ? Is there a ticket for this TODO ?
</blockquote></details>

Nope, it isn't supported on any browser, this code tries to detect folders so they wouldn't be uploaded as files. Code and todo message copied from `VHtmlDragEvent`.

There is no certain way of detecting a folder that I know of, some browsers on some systems may let them through.

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIzTb9HD0Y3wAEM8b:-Kjm65cPm4ATgTmn2rYp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java#L25)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

needs to be serializable
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlHs7BaxCLuBy_73-M:-Kjm7bfVtPNmf8CEuJno:bisk2g1) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/shared/src/main/java/com/vaadin/shared/ui/dnd/FileParameters.java#L28)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why are these not final and getters removed ?
</blockquote></details>

`FileParameters` needs a zero argument constructor, perhaps because it is on the client side?

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIPRqhsfvVFznQZxM:-KjmFEMNdt2y3u_yyyc7:botntlx) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L37)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

How bout adding also a Grid and making it a file drop target, you could log a new row for each stream event for each file ?

Just for better testing
</blockquote></details>

Added the grid.

There is an additional issue, Grid is only updated on next client interaction and not at the end of the upload.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIG4WCI2COEdLF8bA:-KjmFAp8pbrEgK1yPZkg:bs8d0kk) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L96)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

wtf
</blockquote></details>

Must've been copy paste

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIHk_aJOkOP8nauP3:-KjmFAP4SGvMoEvwn8Lc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L116)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

please update
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 286 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmPvuBW51c9w1VFQnV:-KjmPvuBW51c9w1VFQnW:bhauam1) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L286)):*
> ```AsciiDoc
> (((range="endofrange", startref="term.advanced.dragndrop")))
> 
> == Drag and Drop Files
> ```

Question: Is it possible to somehow filter the files already on the client side ?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 288 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmNvJat1g0RL1OgxeT:-KjmNvJat1g0RL1OgxeU:bvvx5wn) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L288)):*
> `FileDropTarget` 

replace with [classname]#FileDropTarget# without the  `

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 290 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOBVSs7l6ZhLtvsb1:-KjmOBVSs7l6ZhLtvsb2:bs44eoo) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L290)):*
> dropped files

the dropped files

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 290 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOEyUZA95eX0bg8ja:-KjmOEyUZA95eX0bg8jb:b-vrwc19) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L290)):*
> `FileDropEvent`

again use [classame]#FileDropEvent#

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 291 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOM9pJftlnlyBkykd:-KjmOM9pJftlnlyBkyke:bhtvebc) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L291)):*
> Here

Where ? Do you mean the handler ? Like "In the handler you can..."

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 299 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmPlF7_9fAeE1mC6UG:-KjmPlF8mMtXsBoDy5gF:b-8ro3au) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L299)):*
> ```AsciiDoc
> Label dropArea = new Label("Drop files here");
> FileDropTarget<Label> dropTarget = new FileDropTarget<>(dropArea, event -> {
>     List<Html5File> files = event.getFiles();
> ```

Please add empty line above this

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 349 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOsOuJj18QCn8GPIj:-KjmOsOuJj18QCn8GPIk:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L349)):*
> ```AsciiDoc
>     }
> });
> ----
> ```

new line

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIPRqhsfvVFznQZxM:-KjmQDzr16EZNjD57jAk:b-8ggh8j) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L37)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Added the grid.

There is an additional issue, Grid is only updated on next client interaction and not at the end of the upload.
</blockquote></details>

Ok so that would require using push(), I wonder what would happen then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 286 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmPvuBW51c9w1VFQnV:-KjmbUGY46_PY9YS1kxa:bc2u3ez) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L286)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Question: Is it possible to somehow filter the files already on the client side ?
</blockquote></details>

The information about the files are known on the client, such client side feature could be implemented similar to the acceptance criteria.

It may not make sense though since on the first server RPC only the files' properties are sent and the actual upload starts only when a stream variable is assigned for the certain files.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 288 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmNvJat1g0RL1OgxeT:-KjmcFL0jQ7dCZAl4pck:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L288)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> `FileDropTarget` 

replace with [classname]#FileDropTarget# without the  `
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 290 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOBVSs7l6ZhLtvsb1:-KjmcNDfaBSzRRNrXGEd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L290)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> dropped files

the dropped files
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 290 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOEyUZA95eX0bg8ja:-KjmcW0gCWZCtNegUSJ_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L290)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> `FileDropEvent`

again use [classame]#FileDropEvent#
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 291 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOM9pJftlnlyBkykd:-KjmcemcLJ86wVteE9Ll:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L291)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Here

Where ? Do you mean the handler ? Like "In the handler you can..."
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 299 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmPlF7_9fAeE1mC6UG:-KjmcjfZ4K2MUVHonmam:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L299)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add empty line above this
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 349 at r2](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjmOsOuJj18QCn8GPIj:-Kjmcv10TBsSaQRTgV0i:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f41c74bf5e6f9da58a00946d1d63db10e4b948a/documentation/advanced/advanced-dragndrop.asciidoc#L349)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/9277#-KjlIPRqhsfvVFznQZxM:-Kjmd-a5Z8SQuVbvcbdT:b-t9jx1r) ([raw file](https://github.com/vaadin/framework/blob/96d8b5d8f5fd1ee9439588beb8ca78716ab2753b/uitest/src/main/java/com/vaadin/tests/dnd/Html5FileDragAndDropUpload.java#L37)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Ok so that would require using push(), I wonder what would happen then
</blockquote></details>

Another option perhaps is to RPC the server when the XHR finished

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9277)*

**Pull request merged**
