### PR TITLE
Updated instructions on how to run TB3+ tests with Intellij; added Qu…

### PR DESCRIPTION
**Pull request by mvysny**
…ickStart to quickly set up testing environment

I've updated the README-TESTS.md since I found the original one confusing; it was also not referenced from README.md.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @mvysny)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-3e9d1PWvCl4fL_sZ:-Lf-3e9d1PWvCl4fL_s_:b-4lwz8s) (no related file):*
Thank you so much for this update. this is definitely a big benefit to our contributors. :hugs: 
only a few changes should be made on top of the current version, all others look fine for me

---
___
*[README-TESTS.md, line 13 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-11Xf53xYF9Sx_Wdi:-Lf-11Xf53xYF9Sx_Wdj:blqtxfe) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L13)):*
> ```
> ?restartApplication
> ```

highlight this one would be better to understand.. especially when the question mark `?` and the `restartApplication` on two different lines.
___
*[README-TESTS.md, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-1Jb_3-YAaNGsH7R9:-Lf-1Jb_3-YAaNGsH7RA:b-kcofoj) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L17)):*
> ```
> The test logic is present in the TB3+ tests
> ```

grammar mistake, `presents` or `is presenting`
___
*[README-TESTS.md, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-1Wj2CeSqk7L5yFPr:-Lf-1Wj2CeSqk7L5yFPs:b57s9m1) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L17)):*
> ```
> they need
> ```

i guess you mean the `test logic`, so it should be `it needs` 
___
*[README-TESTS.md, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-2ciR72kuePJx24lG:-Lf-2ciS8s1PKfN1YbKc:b7qgt96) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L54)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> ## Setup before running any tests from your IDE
> 
> Before running any tests from your IDE you need to
> 1. copy `uitest/eclipse-run-selected-test.properties` to `work/eclipse-run-selected-test.properties`
> 2. edit `work/eclipse-run-selected-test.properties`
>     1. Define `com.vaadin.testbench.screenshot.directory` as the directory where you checked out the screenshots repository (this directory contains the “references” subdirectory)
>     2. Set `com.vaadin.testbench.deployment.url=http://localhost:8888/`
>     3. Set `com.vaadin.testbench.runLocally=chrome` to only run tests on Chrome. On Ubuntu you can then install Chrome driver easily:
>        `sudo apt install chromium-chromedriver`
> 
> > Note: the file is named `eclipse-*` but it applies to all IDEs.
> ```
</details>



does it look better if we move this section before the instructions for IDEs and command line? not blocking
___
*[README-TESTS.md, line 59 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-3M471RH8ByYBRceC:-Lf-3M471RH8ByYBRceD:bwzk1zy) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L59)):*
> ```
>     3. Set `com.vaadin.testbench.runLocally=chrome` to only run tests on Chrome. On Ubuntu you can then install Chrome driver easily:
>        `sudo apt install chromium-chromedriver`
> ```

you would also need this 

```
By default using @RunLocally annotation in Framework tests is not allowed. In order to run a test locally, you need to uncomment the line com.vaadin.testbench.allowRunLocally=true in work/eclipse-run-selected-test.properties.
```
in this step, right?

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)* status: all files reviewed, 6 unresolved discussions (waiting on @mvysny)

**Review by mvysny — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)* status: all files reviewed, 6 unresolved discussions (waiting on @mvysny and @ZheSun88)

___
*[README-TESTS.md, line 13 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-11Xf53xYF9Sx_Wdi:-Lf-j5h65c-F9CuEBupp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L13)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> ?restartApplication
> ```

highlight this one would be better to understand.. especially when the question mark `?` and the `restartApplication` on two different lines.
</blockquote></details>

Done.
___
*[README-TESTS.md, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-1Wj2CeSqk7L5yFPr:-Lf-j4Fm-AMcxs6I-ExU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L17)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> they need
> ```

i guess you mean the `test logic`, so it should be `it needs` 
</blockquote></details>

Done.
___
*[README-TESTS.md, line 17 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-1Jb_3-YAaNGsH7R9:-Lf-j53b8fRJQJcFnul_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L17)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> The test logic is present in the TB3+ tests
> ```

grammar mistake, `presents` or `is presenting`
</blockquote></details>

Done.
___
*[README-TESTS.md, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-2ciR72kuePJx24lG:-Lf-icDC0KN_lmg0Yb16:b-alidwb) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L54)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> ## Setup before running any tests from your IDE
> 
> Before running any tests from your IDE you need to
> 1. copy `uitest/eclipse-run-selected-test.properties` to `work/eclipse-run-selected-test.properties`
> 2. edit `work/eclipse-run-selected-test.properties`
>     1. Define `com.vaadin.testbench.screenshot.directory` as the directory where you checked out the screenshots repository (this directory contains the “references” subdirectory)
>     2. Set `com.vaadin.testbench.deployment.url=http://localhost:8888/`
>     3. Set `com.vaadin.testbench.runLocally=chrome` to only run tests on Chrome. On Ubuntu you can then install Chrome driver easily:
>        `sudo apt install chromium-chromedriver`
> 
> > Note: the file is named `eclipse-*` but it applies to all IDEs.
> ```


does it look better if we move this section before the instructions for IDEs and command line? not blocking
</blockquote></details>

I'd suggest to keep this below the instructions on how to run Jetty, since the config references the local server (the http://localhost:8888 part)
___
*[README-TESTS.md, line 59 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-3M471RH8ByYBRceC:-Lf-j7BgC_xnbHdbH5kb:b1dbrbi) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L59)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
>     3. Set `com.vaadin.testbench.runLocally=chrome` to only run tests on Chrome. On Ubuntu you can then install Chrome driver easily:
>        `sudo apt install chromium-chromedriver`
> ```

you would also need this 

```
By default using @RunLocally annotation in Framework tests is not allowed. In order to run a test locally, you need to uncomment the line com.vaadin.testbench.allowRunLocally=true in work/eclipse-run-selected-test.properties.
```
in this step, right?
</blockquote></details>

Hmmm, actually funny thing - I've left the setting commented out on my machine and it still works. I wonder if these instructions have been made obsolete by some past change?

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)* status: all files reviewed, 2 unresolved discussions (waiting on @mvysny)

___
*[README-TESTS.md, line 59 at r1](https://reviewable.io/reviews/vaadin/framework/11580#-Lf-3M471RH8ByYBRceC:-Lf-jkYq1wG75cZ0SxZ9:bk7csv) ([raw file](https://github.com/vaadin/framework/blob/1a19c021a4ad4e0076c032267111380b3d377fa5/README-TESTS.md#L59)):*
<details><summary><i>Previously, mvysny (Martin Vysny) wrote…</i></summary><blockquote>

Hmmm, actually funny thing - I've left the setting commented out on my machine and it still works. I wonder if these instructions have been made obsolete by some past change?
</blockquote></details>

really? you checked this file `work/eclipse-run-selected-test.properties` not the one in `uitest` folder.

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11580)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
