### PR TITLE
Add back possibility to store any type of data in the dataTransfer object

### PR DESCRIPTION
**Pull request by wbadam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9319)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 312 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCeeFzYxLbZW8dcAgx:-KkCeeFzYxLbZW8dcAgy:b91et65) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L312)):*
> List<String> types

Why is this needed ??? Isn't this the same as the _keySet_ from the Map ?

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCfAsjh8L31mj3_C00:-KkCfAsjh8L31mj3_C01:bbk3yz6) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L180)):*
> ```Java
>      * set for the client side draggable element using {@code
>      * DataTransfer.setData(type, data)} method.
>      *
> ```

Please add
```
<p>
You can use different types of data to support dragging to different targets. Accepted types depend on the drop target and those can be platform specific. See https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types for examples on different types.
<p>
<em>NOTE: IE11 only supports type ' text', which can be set using {@link #setDataTransferText(String data)}</em>
```

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 237 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChYbJX6ijF9BdGB2e:-KkChYbJX6ijF9BdGB2f:b4yex68) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L237)):*
> ```Java
>      * Sets data for this drag source element. The data is set for the client
>      * side draggable element using the {@code DataTransfer.setData("text",
>      * data)} method.
> ```

Please add a comment that this is the only cross browser supported type, because IE11 doesn't support anything else.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 241 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChdIhbCoAdO2ucgDP:-KkChdIhbCoAdO2ucgDQ:bo8aqy4) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L241)):*
> ```Java
>      * @param data
>      *            Data to be set for the client side draggable element.
>      */
> ```

Add `@see #setDataTransferData(String type, String data)`

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 275 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChJYuybgFpx35LKn9:-KkChJYuybgFpx35LKnA:bopoxhy) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L275)):*
> ```Java
>      * Clears all data for this drag source element.
>      */
>     public void clearDataTransferData() {
> ```

Is this method really needed ? Do you have an example use case for it ?

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCiMsj3tXTUeqULP0E:-KkCiMsj3tXTUeqULP0F:b-thtjig) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L73)):*
> in the client side

I thought you'd learn by now not to mention "client side" in server side docs

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCiaJOKRiJExY797PO:-KkCiaJOKRiJExY797PP:b-sjksvz) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java#L59)):*
>  public List<String> types = new ArrayList<>();

Again, why is this here ? duplicate of the map's _keySet_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 312 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCeeFzYxLbZW8dcAgx:-KkEO-haxIWJ68jajJ1Y:bfumc7i) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L312)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> List<String> types

Why is this needed ??? Isn't this the same as the _keySet_ from the Map ?
</blockquote></details>

We want to preserve the drag source's order of  data. It cannot be guaranteed that the map on the client side preserves that order (I think). By keeping a list of types, we can always create a linked map on the server that contains the data in the same order as it was set on the drag source.

Order of data may be important if the drop target want to decide what to do with the given data. The order tells a preference.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 180 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCfAsjh8L31mj3_C00:-KkEPv177qVB1CfiVI1h:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L180)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add
```
<p>
You can use different types of data to support dragging to different targets. Accepted types depend on the drop target and those can be platform specific. See https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types for examples on different types.
<p>
<em>NOTE: IE11 only supports type ' text', which can be set using {@link #setDataTransferText(String data)}</em>
```
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 237 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChYbJX6ijF9BdGB2e:-KkERYuwH1eaR_KDMXeg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L237)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add a comment that this is the only cross browser supported type, because IE11 doesn't support anything else.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 241 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChdIhbCoAdO2ucgDP:-KkERZBNZDMnlcQz5rMP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L241)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Add `@see #setDataTransferData(String type, String data)`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 275 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkChJYuybgFpx35LKn9:-KkERfHg6g4SbM9Kba5Q:b-h8japv) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L275)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is this method really needed ? Do you have an example use case for it ?
</blockquote></details>

Well if the dev, for some reason, doesn't know what data types are set, it is easier to clear out everything.

I originally added this method because it exists in `DataTransfer` in JS.

Should I remove it?

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCiMsj3tXTUeqULP0E:-KkESJl_XzrTqSWYdzvP:b-bu5vqq) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L73)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> in the client side

I thought you'd learn by now not to mention "client side" in server side docs
</blockquote></details>

:D
Copy paste from `getDataTransferText()`

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCiaJOKRiJExY797PO:-KkET3zWiF6Dzl81BP_D:b1fw9mp) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java#L59)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  public List<String> types = new ArrayList<>();

Again, why is this here ? duplicate of the map's _keySet_
</blockquote></details>

Does the map's keyset preserve order?

DataTransfer is using a similar method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 312 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCeeFzYxLbZW8dcAgx:-KkEfwp3oZajqHjnSlh0:b9zs1oj) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L312)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

We want to preserve the drag source's order of  data. It cannot be guaranteed that the map on the client side preserves that order (I think). By keeping a list of types, we can always create a linked map on the server that contains the data in the same order as it was set on the drag source.

Order of data may be important if the drop target want to decide what to do with the given data. The order tells a preference.
</blockquote></details>

I thought the order does not matter, but the types. E.g. first the receiver checks for the most specific type, e.g. _text/html_ and then if that gives nothing just use _text/plain

If you needed to preserve the types so badly, why not just use LinkedHashMap then ? Or is it not working properly, there used to be issues, e.g. (https://groups.google.com/forum/#!topic/google-web-toolkit/RmQ1UJ-JJV4)

The biggest culprit is: it is impossible for the app developer to know the order of the items in the Map since there is only the `getData(String)` in `DropEvent`, so no way to iterate, and it is not even mentioned anywhere that there is some preserved order.

Just nuke it, can be added later on if anyone needs it.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 37 at r2](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEj4JZgrHzs-yzb92c:-KkEj4JZgrHzs-yzb92d:bd6vnxu) ([raw file](https://github.com/vaadin/framework/blob/9e3726ac69f1f14b7bdb6b73392295b216c2a226/documentation/advanced/advanced-dragndrop.asciidoc#L37)):*
> hello

For clarity it might be wise to use the exact same text, e.g. "hello receiver", but

I think using "text/html" and "text/plain" would be much more nicer examples, where the html would be the label in html, e.g. `<label>hello receiver</label>`(I know that is not the vaadin label).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 127 at r2](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEjfMLm17Ce-VvXOvD:-KkEjfMMj1cNkq77DhYN:b-mvorx5) ([raw file](https://github.com/vaadin/framework/blob/9e3726ac69f1f14b7bdb6b73392295b216c2a226/documentation/advanced/advanced-dragndrop.asciidoc#L127)):*
>        // get transfer text
>         String message = event.getDataTransferText();
>         Notification.show("DropEvent with data transfer text: " + message);
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         // get possible transfer data of other type
>         String jsonData = event.getDataTransferData("application/json");
>         if (jsonData != null) {
>             Notification.show("Also has JSON: " + jsonData);
>         }
</details>

I think you could change the ordering so that first it tries to fetch e.g. "text/html" and the fallbacks to "text"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 312 at r1](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkCeeFzYxLbZW8dcAgx:-KkEt3clrgwJR91OV3NZ:bs3469d) ([raw file](https://github.com/vaadin/framework/blob/7a17901f6e3444c8a3fe7383552f83db56f2890c/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L312)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I thought the order does not matter, but the types. E.g. first the receiver checks for the most specific type, e.g. _text/html_ and then if that gives nothing just use _text/plain

If you needed to preserve the types so badly, why not just use LinkedHashMap then ? Or is it not working properly, there used to be issues, e.g. (https://groups.google.com/forum/#!topic/google-web-toolkit/RmQ1UJ-JJV4)

The biggest culprit is: it is impossible for the app developer to know the order of the items in the Map since there is only the `getData(String)` in `DropEvent`, so no way to iterate, and it is not even mentioned anywhere that there is some preserved order.

Just nuke it, can be added later on if anyone needs it.
</blockquote></details>

As discussed, added `getDataTransferData()` to the drop event.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 37 at r2](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEj4JZgrHzs-yzb92c:-KkEoU4y9aTgcQEKOUMy:b-hfghm4) ([raw file](https://github.com/vaadin/framework/blob/9e3726ac69f1f14b7bdb6b73392295b216c2a226/documentation/advanced/advanced-dragndrop.asciidoc#L37)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> hello

For clarity it might be wise to use the exact same text, e.g. "hello receiver", but

I think using "text/html" and "text/plain" would be much more nicer examples, where the html would be the label in html, e.g. `<label>hello receiver</label>`(I know that is not the vaadin label).
</blockquote></details>

Sounds good

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 127 at r2](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEjfMLm17Ce-VvXOvD:-KkEt1G-xK26x22FHVcH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9e3726ac69f1f14b7bdb6b73392295b216c2a226/documentation/advanced/advanced-dragndrop.asciidoc#L127)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>        // get transfer text
>         String message = event.getDataTransferText();
>         Notification.show("DropEvent with data transfer text: " + message);
>  
>         // get possible transfer data of other type
>         String jsonData = event.getDataTransferData("application/json");
>         if (jsonData != null) {
>             Notification.show("Also has JSON: " + jsonData);
>         }

I think you could change the ordering so that first it tries to fetch e.g. "text/html" and the fallbacks to "text"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 36 at r3](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEz7uxjaYBo4qEJ09u:-KkEz7uxjaYBo4qEJ09v:bl9uzr1) ([raw file](https://github.com/vaadin/framework/blob/f7129644901b368f51b94673a932f31dc4368efa/documentation/advanced/advanced-dragndrop.asciidoc#L36)):*
>  (in this case JSON data)

Not true anymore

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 92 at r3](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEzizJk80Cc5mLaBcK:-KkEzizJk80Cc5mLaBcL:b-ehoyyf) ([raw file](https://github.com/vaadin/framework/blob/f7129644901b368f51b94673a932f31dc4368efa/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L92)):*
> reserves

preserves

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 36 at r3](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEz7uxjaYBo4qEJ09u:-KkF-VtTXs630bRpq_x0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f7129644901b368f51b94673a932f31dc4368efa/documentation/advanced/advanced-dragndrop.asciidoc#L36)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  (in this case JSON data)

Not true anymore
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 92 at r3](https://reviewable.io:443/reviews/vaadin/framework/9319#-KkEzizJk80Cc5mLaBcK:-KkF-rlZ8zL4qlcU5OAu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f7129644901b368f51b94673a932f31dc4368efa/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L92)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> reserves

preserves
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9319)*

**Pull request merged**
