### PR TITLE
Overload AbstarctComponent.setDescription() with content mode parameter

### LINKED ISSUE #8185: Change setDescription to not render the text as HTML by default
`AbstractCompnent.setDescription(String description)` should set the provided text as `innerText` in the DOM.

Also add `AbstractCompnent.setDescription(String description, ContentMode contentMode)` that can be used to explicitly set the text to be used as `innerHtml` in those cases where it's desired.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8185

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8252)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagE9T-6HCWJCIRgaXE:b-h93bdo) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
> ```Java
>                 if (description != null && !description.equals("")) {
>                     TooltipInfo info = new TooltipInfo(description,
>                             ContentMode.TEXT, null, this);
> ```

Change in compatibility package? Should there be a copy of the old TooltipInfo in the compatibility package?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java, line 280 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagDjO4ZF63DGBIh8MS:-KagDjO4ZF63DGBIh8MT:b-6pf3iw) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java#L280)):*
> ```Java
>         if (description != null) {
>             tooltipMap.put(treeNode, new TooltipInfo(description,
>                     ContentMode.TEXT, null, treeNode));
> ```

Change in compatibility package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagHH64tDmJzZfliyJp:b-quxmnl) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Change in compatibility package? Should there be a copy of the old TooltipInfo in the compatibility package?
</blockquote></details>

Well...........
Probably the old behavior can be kept (so I should use ContentMode.HTML) for compatibility.
But there is no any point to copy `TooltipInfo`. 
I can do this of course. But there is only one usacase  of this class: the `getTooltipInfo()` in the `AbstractComponentConnector`.
Here the code stores the instance to return it in the end via the mentioned method.

But the `getTooltipInfo()` is in the main module and has to return main`TooltipInfo`.
So there is no any point to copy `TooltipInfo`since it can't be used.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java, line 280 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagDjO4ZF63DGBIh8MS:-KagLf_QNLizIhRKVrh9:bjft02v) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java#L280)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Change in compatibility package.
</blockquote></details>

Same as above:
the behavior is set back to use HTML content type.
But I can't do anything with the code itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by Legioth** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagWOji1JcIJyfkYIVM:bp09e3r) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Well...........
Probably the old behavior can be kept (so I should use ContentMode.HTML) for compatibility.
But there is no any point to copy `TooltipInfo`. 
I can do this of course. But there is only one usacase  of this class: the `getTooltipInfo()` in the `AbstractComponentConnector`.
Here the code stores the instance to return it in the end via the mentioned method.

But the `getTooltipInfo()` is in the main module and has to return main`TooltipInfo`.
So there is no any point to copy `TooltipInfo`since it can't be used.
</blockquote></details>

What about leaving the old constructors as deprecated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagZL8exhuuH840thk-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What about leaving the old constructors as deprecated?
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java, line 280 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagDjO4ZF63DGBIh8MS:-KagZnvxPhrZuYpb5I_R:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/tree/TreeConnector.java#L280)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Same as above:
the behavior is set back to use HTML content type.
But I can't do anything with the code itself.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by Legioth** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagdYTJwMGAfQCFETyd:b-zb4n7t) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Then please revert all changes to this file, as well as the other modified file from `compatibility-client`. Including the current changes that remove redundant generic types will only make it more difficult to merge future changes from 7.7 to master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 94 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 5802 at r1](https://reviewable.io:443/reviews/vaadin/framework/8252#-KagE9SzHf6cVo8qHhnz:-KagkFo-cN1ObWkR-gpW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27aee393c25bbba6be7c756be8c1b1c734ab4f58/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L5802)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Then please revert all changes to this file, as well as the other modified file from `compatibility-client`. Including the current changes that remove redundant generic types will only make it more difficult to merge future changes from 7.7 to master.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Comment by ahie** [comment]
Reviewed 90 of 95 files at r1, 3 of 5 files at r2, 4 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8252)*

**Pull request merged**
