### PR TITLE
tiny change in wording

### PR DESCRIPTION
**Pull request by octavian-nita**

### CODE REVIEW

**Review by denis-anisimov — APPROVED** [review]

**Comment by denis-anisimov** [comment]
We have to integrate it via Gerrit.
I've create a patch based on the change: https://dev.vaadin.com/review/14762

**Comment by denis-anisimov** [comment]
You will need to sign CLA so we can accept your contribution.

**Comment by octavian-nita** [comment]
Hi guys,

I haven't used Gerrit so far nor was aware of the CLA part... I will do as instructed as soon as I figure it all.

Regards,
Tavi

**Comment by octavian-nita** [comment]
Hi Denis, guys,

I finally managed to find a bit of time to dig and have signed that CLA --
not extremely intuitive, I must say... Never mind, did it now.

Best regards,
Octavian

**Pull request merged**
