### PR TITLE
Add more context information to criteriaScript in GridDropTargetConnector

### PR DESCRIPTION
**Pull request by vt512**
When using drag and drop in Grids and TreeGrids a criteriaScript can be specified.
However, this criteriaScript only gets an event as input parameter.
It would be helpful if the criteriaScript would get more information:
- the DropLocation
- the targetElement which is used as a base for the DropLocation

This change provides a protected method in DropTargetExtensionConnector
which decides, if the drop is allowed by the criteriaScript.
This method is overriden in GridDropTargetConnector to
provide the both parameters dropLocation and targetElement.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11321)

### CODE REVIEW

**Comment by pleku** [comment]
Hi and thanks for the contribution!

I took an initial look on the PR and it looks fine, but could you however add a TestUI with an example script that we can use to validate the feature works and how it used ? Something that uses the `targetElement` and `DropLocation`. That would help us out.
You can use eg. any of the existing Grid DnD UIs, or just create a new one based on eg. https://github.com/vaadin/framework/blob/master/uitest/src/main/java/com/vaadin/tests/components/grid/AbstractGridDnD.java

**Comment by vt512** [comment]
Hi Pekka!

I just added a simple UI for testing the criteriaScript. I hope this helps.
Unfortunately I don't know how to add an automated Test for DnD Testing.

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11321)* status: all files reviewed, 1 unresolved discussion (waiting on @vt512)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11321#-LSR4tcm3ZEm5iV3cT_y:-LSR4tcm3ZEm5iV3cT_z:bqfl7wu) (no related file):*
Hi. Sorry for the delay, but the PR looks fine now. Just need to test it with all the supported devices.

If everything works smoothly, we'll merge it and release it in 8.7.0.alpha1 within a week.

---

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11321)* status: all files reviewed, 1 unresolved discussion (waiting on @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11321#-LSR4tcm3ZEm5iV3cT_y:-LStBvJL09tZsvMTdOtE:b-5otpe7) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Hi. Sorry for the delay, but the PR looks fine now. Just need to test it with all the supported devices.

If everything works smoothly, we'll merge it and release it in 8.7.0.alpha1 within a week.
</blockquote></details>

I have tested the patch on windows/Mac, they work as expected. 

---

**Review by pleku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11321)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
