### PR TITLE
Add explicit handling of ctrl-a

### LINKED ISSUE #11678: TwinColSelect: ctrl+a doesn't work in Firefox or IE11/Edge
Focusing a listed item and pressing ctrl+a doesn't select all items in Firefox, IE11, or Edge. Works as expected on Chrome. Tested on Win7 and Win10. Can be reproduced in [sampler](https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/list-builder).

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes https://github.com/vaadin/framework/issues/11678

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11693)

### CODE REVIEW

**Review by Ansku — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11693)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Ansku and @TatuLund)

___
*[uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectCtrlATest.java, line 22 at r2](https://reviewable.io/reviews/vaadin/framework/11693#-Lm3uF-m-duT60Hc2BVl:-Lm3uF-m-duT60Hc2BVm:brxyltm) ([raw file](https://github.com/vaadin/framework/blob/6c84d352ec54480e3b76be950ad129c6e1555d31/uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectCtrlATest.java#L22)):*
> ```
> getTwinColElement()
> ```
Wouldn't it be easier to just save that to a variable instead of searching for it three times?

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11693)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectCtrlATest.java, line 22 at r2](https://reviewable.io/reviews/vaadin/framework/11693#-Lm3uF-m-duT60Hc2BVl:-Lm3zdtLCcH-qpYjPZ5x:b-zbc3na) ([raw file](https://github.com/vaadin/framework/blob/6c84d352ec54480e3b76be950ad129c6e1555d31/uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectCtrlATest.java#L22)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> getTwinColElement()
> ```
Wouldn't it be easier to just save that to a variable instead of searching for it three times?
</blockquote></details>

yeah, that can be more efficient. Done

**Review by Ansku — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11693)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ZheSun88** [comment]
this needs to be cherry-picked to 8.9 branch.. as a new feature.

**Pull request merged**
