### PR TITLE
Fix combo box suggestion popup height

### LINKED ISSUE #10214: Bad height of Choice list in Combobox when page length is 0
Hi,

In Vaadin 8.1.5 and I think in previous 8 releases, there is an issue about the height of Choice list in Combobox when page length is 0 because the height of the list is greater than the height of the window.

```
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        VerticalLayout layout = new VerticalLayout();
        setContent(layout);

        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setPageLength(0);
        comboBox.setItems(IntStream.range(0, 1000).mapToObj(i -> "Item number " + String.valueOf(i)).collect(Collectors.toList()));

        layout.addComponent(comboBox);
    }
```

capture

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #10214

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10256)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 878 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMh8ZKZiPvNLhv4_Mu:-KxMh8ZKZiPvNLhv4_Mv:b-izzg6o) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L878)):*
> ```Java
>                             + menuStyle.getIntProperty("paddingBottom")
>                             + menuStyle.getIntProperty("paddingTop")
>                             + popupStyle.getIntProperty("marginTop")
> ```

why is only the margin of popup style taken into account? Should padding be also handled? 

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java, line 15 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMhEapN7W3huruswLz:-KxMhEapN7W3huruswM-:b-z3lhc1) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java#L15)):*
> ```Java
> 
>     @Override
>     protected void setup(VaadinRequest request) {
> ```

could you add some custom theme option to this test as well to enable testing with arbitrary margins and paddings on various different things?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Comment by wbadam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 878 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMh8ZKZiPvNLhv4_Mu:-KxModyCaQ24JN3fVnQY:b-oca812) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L878)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why is only the margin of popup style taken into account? Should padding be also handled? 
</blockquote></details>

Actually only because there is no padding on the popup in Valo styles. I now added to make it future-proof.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java, line 15 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMhEapN7W3huruswLz:-KxMrTfjLTGbMGRFqy1J:b-8qxbt5) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java#L15)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

could you add some custom theme option to this test as well to enable testing with arbitrary margins and paddings on various different things?
</blockquote></details>

Would you like me to add request parameters that change theming of the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r4.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java, line 15 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMhEapN7W3huruswLz:-KxMtNw81MWnguKVs_wP:bvp8zzu) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java#L15)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Would you like me to add request parameters that change theming of the test?
</blockquote></details>

some kind of small test theme might be the easiest approach. and then using `theme=my-test-theme` in the URL should be easy. can be passed as a parameter to the test method `openTestURL`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Comment by wbadam** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java, line 15 at r3](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxMhEapN7W3huruswLz:-KxNpZcH9gy-J8MLepj_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9b1725aca8e40e30bec0d68ccc65e432549a764c/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxHeight.java#L15)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

some kind of small test theme might be the easiest approach. and then using `theme=my-test-theme` in the URL should be easy. can be passed as a parameter to the test method `openTestURL`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxgVWmqn0P8QLtRGlup:-KxgVWmqn0P8QLtRGluq:b69ddcf) (no related file):*
Testing manually to see the make sure the test works correctly. Other than that looks fine by me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10256#-KxgVWmqn0P8QLtRGlup:-KxglZ1Tabd3crItSM--:bgbigij) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Testing manually to see the make sure the test works correctly. Other than that looks fine by me.
</blockquote></details>

OK seems to be working.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10256)*

**Pull request merged**
