### PR TITLE
setCaption of Panel did not honor setCaptionAsHtml

### LINKED ISSUE #11521: Potential XSS vulnerability with Panel caption
[panel-xss.zip](https://github.com/vaadin/framework/files/3022302/panel-xss.zip)

- Vaadin Framework version: 8.0.0-8.7.1
- Browser version: Any

- Description of the bug

1. Panel interprets caption as HTML by default.
2. Panel interprets caption as HTML even if we set `captionAsHtml` to `false` explicitly.

- Minimal reproducible example

UI code:
```java
@Theme("mytheme")
public class MyUI extends UI {
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        Panel panel = new Panel();
        panel.setWidth("200px");
        panel.setHeight("200px");

        panel.setCaption("<b>BOLD CAPTION</b><img src=x onerror=\"alert('persistent XSS attack');\">");

        // even if we set captionAsHtml to false explicitly
        panel.setCaptionAsHtml(false);

        panel.setContent(new VerticalLayout());
        
        setContent(panel);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

- Expected behavior

Panel must show caption `<b>BOLD CAPTION</b>`.

- Actual behavior

It interprets caption as HTML and triggers passed JS code.

Panel XSS

Relates to: https://github.com/cuba-platform/cuba/issues/1993

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes #11521

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11523)

### CODE REVIEW

**Review by anasmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11523)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TatuLund)

___
*[client/src/main/java/com/vaadin/client/ui/VPanel.java, line 133 at r1](https://reviewable.io/reviews/vaadin/framework/11523#-LbMIHf012EXMsscZDKm:-LbMIHf012EXMsscZDKn:b-rqofg2) ([raw file](https://github.com/vaadin/framework/blob/6726edd7c48253b29599be2ab173c5c73eeb1745/client/src/main/java/com/vaadin/client/ui/VPanel.java#L133)):*
> ```Java
> 
>     /** For internal use only. May be removed or replaced in the future. */
>     public void setCaption(String text, boolean captionAsHtml) {
> ```

While fix itself seems good to me, test is still required. If it's not possible to add automated one, at least, UI test.

**Comment by TatuLund** [comment]
___
*[client/src/main/java/com/vaadin/client/ui/VPanel.java, line 133 at r1](https://reviewable.io/reviews/vaadin/framework/11523#-LbMIHf012EXMsscZDKm:-LbR_yCO50OrdXA8qrJH:b-d8epw2) ([raw file](https://github.com/vaadin/framework/blob/6726edd7c48253b29599be2ab173c5c73eeb1745/client/src/main/java/com/vaadin/client/ui/VPanel.java#L133)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

While fix itself seems good to me, test is still required. If it's not possible to add automated one, at least, UI test. 
</blockquote></details>

I added test

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11523)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VPanel.java, line 133 at r1](https://reviewable.io/reviews/vaadin/framework/11523#-LbMIHf012EXMsscZDKm:-LbRa1K768QREvvWj26r:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6726edd7c48253b29599be2ab173c5c73eeb1745/client/src/main/java/com/vaadin/client/ui/VPanel.java#L133)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

I added test
</blockquote></details>

Done.

**Review by anasmi — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11523)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
