### PR TITLE
Added utility method Binder#asRequired() 

### PR DESCRIPTION
**Pull request by sknitelius**
At the moment you can only define fields as required with a message.
`binder.asRequired("");`

Often a message is irrelevant for required Fields hence the additional method:
`binder.asRequired();`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9873)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 491 at r1](https://reviewable.io:443/reviews/vaadin/framework/9873#-KtFxEXxOEYTRVhIBtK2:-KtFxEXxOEYTRVhIBtK3:b-24cqe7) ([raw file](https://github.com/vaadin/framework/blob/d2c5f619be206c844711a6be3cdc604eecc1d7e4/server/src/main/java/com/vaadin/data/Binder.java#L491)):*
> ```Java
>          * <ol>
>          * <li>the required indicator is visible</li>
>          * <li>the field value is validated for not being empty*</li>
> ```

The javadoc for asRequired() has been reformulated for clarity, so please update this change on top of the current master. As the change is so small, the easiest way might be to re-implement the change on top of current master and to close this PR.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 511 at r1](https://reviewable.io:443/reviews/vaadin/framework/9873#-KtFxBnlPWZNBQZ0fyl4:-KtFxBnlPWZNBQZ0fyl5:b-jxeoxs) ([raw file](https://github.com/vaadin/framework/blob/d2c5f619be206c844711a6be3cdc604eecc1d7e4/server/src/main/java/com/vaadin/data/Binder.java#L511)):*
> ```Java
>             return asRequired(context -> "");
>         }
>         
> ```

(extra whitespace on an empty line)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9873)*

**Comment by sknitelius** [comment]
Will do later tonight.

**Comment by hesara** [comment]
@sknitelius there are still some open issues, need for a merge/rebase/redoing the PR on master, and no tests for this. Will you still work on this?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9873#-:-KvS4TsKM7-vaV2R3-Sm:b-ibv1oy)*

**Comment by sknitelius** [comment]
@hesara I am currently a bit over streched, Teemu contacted me and said that he would happily take over these issues. Think I granted all the required rights.

**Comment by hesara** [comment]
Ok, I'll see these with Teemu then.

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9873)*

**Pull request merged**
