### PR TITLE
WIP: API review changes

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9287)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 10 of 11 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjmU8iBTuvWC94nv-ex:-KjmU8iBTuvWC94nv-ey:baoqqbb) ([raw file](https://github.com/vaadin/framework/blob/20e1bd1b5b33a65fa6e79cf16c636aaef9696348/client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java#L97)):*
> ```Java
>     /**
>      * Set the style name prefix for the node, expander and cell-content
>      * elements.
> ```

could perhaps mention that this only changes the settings, not actual active style names

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java, line 54 at r1](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjmUzq_wqMEz9IaUW0B:-KjmUzq_wqMEz9IaUW0C:bg9pj57) ([raw file](https://github.com/vaadin/framework/blob/b5da856bdbe9961151a265db1058c7ee1393bcff/server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java#L54)):*
> ```Java
>      * Constructs a new InMemoryHierarchicalDataProvider.
>      * <p>
>      * All changes made to the given HierarchyData object will also be visible
> ```

Shouldn't this still be expressed in some way (also telling what are the limitations)?

---

*[shared/src/main/java/com/vaadin/shared/ui/composite/CompositeState.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjmVekRNsTnT5qfib8S:-KjmVekRNsTnT5qfib8T:b-wp8dj8) ([raw file](https://github.com/vaadin/framework/blob/20e1bd1b5b33a65fa6e79cf16c636aaef9696348/shared/src/main/java/com/vaadin/shared/ui/composite/CompositeState.java#L21)):*
> ```Java
> 
> /**
>  * Shared state for Composite.
> ```

should perhaps mention that this isn't really used on the client side, but rather CompositeConnector.getState() does some tricks to show the composition root component state

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
Review status: 18 of 19 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: 20 of 21 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3942 at r6](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9raG_uote2FqN9-G:-Kjq9raG_uote2FqN9-H:b-70qde5) ([raw file](https://github.com/vaadin/framework/blob/e48c65a25b9760b3e360285a941fdf69ebeedd41/server/src/main/java/com/vaadin/ui/Grid.java#L3942)):*
> ```Java
>      * @param providers
>      *            list of {@link DeclarativeValueProvider}s to store the data of
>      *            each column to
> ```

@since as AFAIK these were exposed in 8.1

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4002 at r6](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9xWB7mBuYGDc2XcP:-Kjq9xWB7mBuYGDc2XcQ:bk3o8og) ([raw file](https://github.com/vaadin/framework/blob/e48c65a25b9760b3e360285a941fdf69ebeedd41/server/src/main/java/com/vaadin/ui/Grid.java#L4002)):*
> ```Java
>      *            data to
>      * @param designContext
>      *            the design context
> ```

@since as above

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 293 at r5](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9LVfJPGZZMBJvtu9:-Kjq9LVfJPGZZMBJvtuA:b-ytqev1) ([raw file](https://github.com/vaadin/framework/blob/254c6fa74e09bc9a3ac10c1aa8ac66a30c3ead91/server/src/main/java/com/vaadin/ui/TreeGrid.java#L293)):*
> ```Java
>             throw new IllegalArgumentException("No column found for given id");
>         }
>         getColumn(id).setHidden(false);
> ```

(it might be good for this to be implemented by calling the method above to reduce duplication - not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Review status: 19 of 21 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 95 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvQyOiL0_BshmoJN8K:-KjvQyOiL0_BshmoJN8L:b-ixtdlb) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L95)):*
> ```Java
>     /**
>      * Creates a new {@code TreeGrid} using the given
>      * {@code HierarchicalDataProvider}.
> ```

Does the comment from the no-args constructor apply here as well?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 106 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvR26AsqABKoS-rT5F:-KjvR26B9iZUDBeNxHC6:b-ixtdlb) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L106)):*
> ```Java
> 
>     /**
>      * Creates a {@code TreeGrid} using the given in-memory data.
> ```

Does the comment from the no-args constructor apply here as well?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 119 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvQdylI16rOWXtXhhv:-KjvQdymVHSF312XgdN0:borpsj5) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L119)):*
> ```Java
> 
>     /**
>      * Creates a grid using a custom {@link PropertySet} implementation and
> ```

Creates a TreeGrid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r2, 6 of 6 files at r8, 2 of 2 files at r11.
Review status: 19 of 25 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/LocalDateRendererConnector.java, line 18 at r9](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjvd3u5M3gwvV9WmG3-:-Kjvd3u6R2X3-_zP2CT3:bfosuhu) ([raw file](https://github.com/vaadin/framework/blob/da597abfe2f7121ae8ca0a2c418e4af1389b2d5e/client/src/main/java/com/vaadin/client/connectors/LocalDateRendererConnector.java#L18)):*
> ```Java
> package com.vaadin.client.connectors;
> 
> import com.vaadin.client.connectors.grid.TextRendererConnector;
> ```

TRC of 8.0 is now in a different package, but we can't really move it. How many of the renderer connectors are in each of the locations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 2 of 5 files at r12, 3 of 4 files at r14.
Review status: 22 of 31 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ItemCollapseAllowedProvider.java, line 34 at r14](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkEmFTBT0SE1_2C8Net:-KkEmFTBT0SE1_2C8Neu:b-umg7ht) ([raw file](https://github.com/vaadin/framework/blob/a636d42d93f025a0ca9f085324aba827e544f3c7/server/src/main/java/com/vaadin/ui/ItemCollapseAllowedProvider.java#L34)):*
> ```Java
>  */
> @FunctionalInterface
> public interface ItemCollapseAllowedProvider<T> extends SerializablePredicate<T> {
> ```

(related changes might conflict with #9318)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 2 of 5 files at r12.
Review status: 24 of 31 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/LocalDateRendererConnector.java, line 18 at r9](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjvd3u5M3gwvV9WmG3-:-KkFAcBSYJ7ID5kIkTae:b-93cynk) ([raw file](https://github.com/vaadin/framework/blob/da597abfe2f7121ae8ca0a2c418e4af1389b2d5e/client/src/main/java/com/vaadin/client/connectors/LocalDateRendererConnector.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TRC of 8.0 is now in a different package, but we can't really move it. How many of the renderer connectors are in each of the locations?
</blockquote></details>

These seem to be a real mess for the old and new renderer connectors, and also e.g. ComponentRendererConnector is a part of the picture. Also, there are base two different base classes for the connectors which probably must not be moved as other renderers outside the framework may inherit them.

Should probably really move all the concrete renderer connectors (or at least all the new ones) to a new package.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6230 at r14](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkF92kqpuSmZXjRCivt:-KkF92kqpuSmZXjRCivu:bjs0lj4) ([raw file](https://github.com/vaadin/framework/blob/a636d42d93f025a0ca9f085324aba827e544f3c7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6230)):*
> ```Java
>     }
> 
>     private String getFocusPrimaryStyleName() {
> ```

(could also eliminate this now)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r10.
Review status: 26 of 31 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/AbstractBackEndHierarchicalDataProvider.java, line 43 at r14](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkFGz-OWCNbzg7WBSMJ:-KkFGz-OWCNbzg7WBSMK:bx9dals) ([raw file](https://github.com/vaadin/framework/blob/a636d42d93f025a0ca9f085324aba827e544f3c7/server/src/main/java/com/vaadin/data/provider/AbstractBackEndHierarchicalDataProvider.java#L43)):*
> ```Java
>     private List<QuerySortOrder> sortOrders = new ArrayList<>();
> 
>     private HierarchicalQuery<T, F> mixInSortOrders(
> ```

(should have some comment or javadoc as what this is doing is not immediately obvious (concatenate non-conflicting own sort orders to the query sort orders?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by pleku** [comment]
Review status: 23 of 32 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java, line 31 at r17](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkFTWcii7em5YpBs8KF:-KkFTWcii7em5YpBs8KG:byylcw8) ([raw file](https://github.com/vaadin/framework/blob/43ad4e2f620bcafcca7ce33f2d43ac79b97a8fbe/server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java#L31)):*
>  * A {@link DataProvider} for in-memory hierarchical data.

The javadoc states absolutely nothing about why or when this class should be used, and the why is not even that clear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by ahie** [comment]
Review status: 17 of 33 files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6230 at r14](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkF92kqpuSmZXjRCivt:-KkFVEFsBl8EbnV0H-35:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/a636d42d93f025a0ca9f085324aba827e544f3c7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6230)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could also eliminate this now)
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3942 at r6](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9raG_uote2FqN9-G:-KkFVsthZiIJCZlluie_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e48c65a25b9760b3e360285a941fdf69ebeedd41/server/src/main/java/com/vaadin/ui/Grid.java#L3942)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since as AFAIK these were exposed in 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4002 at r6](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9xWB7mBuYGDc2XcP:-KkFVtKt0LpNXQiA4135:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e48c65a25b9760b3e360285a941fdf69ebeedd41/server/src/main/java/com/vaadin/ui/Grid.java#L4002)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since as above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/ItemCollapseAllowedProvider.java, line 34 at r14](https://reviewable.io:443/reviews/vaadin/framework/9287#-KkEmFTBT0SE1_2C8Net:-KkFW8ARf1J2AANDPGnR:badd8np) ([raw file](https://github.com/vaadin/framework/blob/a636d42d93f025a0ca9f085324aba827e544f3c7/server/src/main/java/com/vaadin/ui/ItemCollapseAllowedProvider.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(related changes might conflict with #9318)
</blockquote></details>

#9318 changes merged to this PR

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 293 at r5](https://reviewable.io:443/reviews/vaadin/framework/9287#-Kjq9LVfJPGZZMBJvtu9:-KkFWufOLwBD1nJU6t9R:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/254c6fa74e09bc9a3ac10c1aa8ac66a30c3ead91/server/src/main/java/com/vaadin/ui/TreeGrid.java#L293)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(it might be good for this to be implemented by calling the method above to reduce duplication - not a blocker)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 95 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvQyOiL0_BshmoJN8K:-KkFiXH-X3WGeeQJiOxP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L95)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does the comment from the no-args constructor apply here as well?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 106 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvR26AsqABKoS-rT5F:-KkFWXKX3rFQVrn603k3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L106)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does the comment from the no-args constructor apply here as well?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 119 at r7](https://reviewable.io:443/reviews/vaadin/framework/9287#-KjvQdylI16rOWXtXhhv:-KkFWiCCYoUnwaDe6Qug:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cbade611e87698c3029ffe017f6858cec094d602/server/src/main/java/com/vaadin/ui/TreeGrid.java#L119)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Creates a TreeGrid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9287)*

**Comment by hesara** [comment]
Superceded by #9326, #9327 and a later change (to be made) to move renderer connector classes.

**Pull request closed without merging**
