### PR TITLE
 Use lambda with Listeners

### PR DESCRIPTION
**Pull request by asashour**
Changed in `client` and `server` projects.

`compatibility` projects are not changed.

Some changes in `uitest` are done, but not all since the number is huge, could be done later.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10222)

### CODE REVIEW

**Comment by pekam** [comment]
We try to avoid one-letter variable names. In the case of event listeners it's not that important, since anyone understands that `e` is the event. But while working on these, could you unify the code to use `event` in the listeners that you've edited?

---

Review status: 0 of 141 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10222#-:-KxNEY0f8ttrcdS7RgaM:b-dt9svn)*

**Comment by pekam** [comment]
Reviewed 16 of 140 files at r1, 200 of 200 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 109 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNXg4wJsvLo_WU0Oie:-KxNXg4wJsvLo_WU0Oif:b-hwtyji) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L109)):*
> ```Java
>     public JsonObject getItem(Element element) {
>         return optionsToItems.entrySet().stream()
>                 .filter(event -> event.getKey().getElement().isOrHasChild(element))
> ```

These are not events, their type is `Map.Entry`

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 273 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNYjFSaXHy3ROL_2VK:-KxNYjFSaXHy3ROL_2VL:b-apc6m) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VDateField.java#L273)):*
> ```Java
>         rpc.update(bufferedDateString,
>                 bufferedResolutions.entrySet().stream().collect(Collectors
>                         .toMap(event -> event.getKey().name(),
> ```

not events, but entries

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 124 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNYIYclcrePOsVuYFb:-KxNYIYclcrePOsVuYFc:b-apc6m) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L124)):*
> ```Java
>     private Optional<JsonObject> tryGetItem(Element element) {
>         return optionsToItems.entrySet().stream()
>                 .filter(event -> event.getKey().getElement().equals(element))
> ```

not events, but entries

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNdsNCSKD9Tiuijibu:-KxNdsNCSKD9Tiuijibv:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L105)):*
> ```Java
>             status) -> {
>         String message = status.getFieldValidationErrors().stream()
>                 .filter(event -> event.getMessage().isPresent()
> ```

not events

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 107 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNe3fRYSe9wVQPhhXm:-KxNe3fRYSe9wVQPhhXn:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L107)):*
> ```Java
>                 .filter(event -> event.getMessage().isPresent()
>                         && fieldToColumn.containsKey(event.getField()))
>                 .map(event -> fieldToColumn.get(event.getField()).getCaption() + ": "
> ```

not events

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNe-ONhwYoSgO910vP:-KxNe-ONhwYoSgO910vQ:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L112)):*
> ```Java
> 
>         String beanMessage = status.getBeanValidationErrors().stream()
>                 .map(event -> event.getErrorMessage())
> ```

not events

---

*[server/src/test/java/com/vaadin/data/BinderTestBase.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNeKvoY3dyKSrGpvgv:-KxNeKvoY3dyKSrGpvgw:b5594po) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/test/java/com/vaadin/data/BinderTestBase.java#L54)):*
> ```Java
>     protected Converter<String, Integer> stringToInteger = Converter.from(
>             Integer::valueOf, String::valueOf,
>             event -> NOT_NUMBER_ERROR_MESSAGE);
> ```

Looks like this is not an event listener, but `SerializableFunction<Exception,String>`

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNjJCahSVReRzA7H9X:-KxNjJCahSVReRzA7H9Y:b-ch0bfr) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L59)):*
> ```Java
> 
>         if (!isElementPresent(UIElement.class)) {
>             waitUntil(event -> isElementPresent(UIElement.class), 10);
> ```

not an event

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkAwKDl5DcxBX9ByY:-KxNkAwKDl5DcxBX9ByZ:b-ch0bfr) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java#L83)):*
> ```Java
>         assertEquals(0, getServerCounter());
>         getServerCounterStartButton().click();
>         waitUntil(event -> getServerCounter() > 1, 10);
> ```

not an event

---

*[test/widget-set-testutil/src/main/java/com/vaadin/test/widgetset/AbstractTestWidgetSetUI.java, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkR1IwZ1mWHrWIFJH:-KxNkR1IwZ1mWHrWIFJI:bti0qbs) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/widget-set-testutil/src/main/java/com/vaadin/test/widgetset/AbstractTestWidgetSetUI.java#L22)):*
> ```Java
>         Button button = new Button("Click Me");
>         button.addClickListener(
>                 e -> new Label("Thanks " + name.getValue() + ", it works!"));
> ```

use `event` instead of `e`

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 465 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkdrrUyUCU4O61Q20:-KxNkdrrUyUCU4O61Q21:b-ch0bfr) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L465)):*
> ```Java
>                 .findElement(By.className("v-grid-sidebar-content"))
>                 .findElements(By.className("column-hiding-toggle")).stream()
>                 .filter(event -> event.getText().equals(toggleCaption))
> ```

not an event

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkgMHcyTa6XyYPQOE:-KxNkgMHcyTa6XyYPQOF:b-ch0bfr) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L468)):*
> ```Java
>                 .findAny();
>         if (toggleButton.isPresent()) {
>             toggleButton.ifPresent(event -> event.click());
> ```

not an event

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxTextFieldEventOrder.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNwveugiuLgEs_3E5P:-KxNwveugiuLgEs_3E5Q:b-77ftw2) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxTextFieldEventOrder.java#L19)):*
> ```Java
>         textField.addValueChangeListener(event ->
>         // or just select.requestRepaint()
>         select.addItem(Long.valueOf(select.size() + 1).toString())
> ```

comment and code got reordered here

---

*[uitest/src/main/java/com/vaadin/tests/components/table/KeyboardNavigationWithChangingContent.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxOD9xKviCEDZFARVi1:-KxOD9xKviCEDZFARVi2:bgxzsb3) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/table/KeyboardNavigationWithChangingContent.java#L35)):*
> ```Java
>         getLayout().addComponent(t);
>         getLayout().addComponent(new Button("Change elements and selection",
>                 e-> {
> ```

`event` instead of `e`

---

*[uitest/src/main/java/com/vaadin/tests/components/table/LargeSelectionCausesNPE.java, line 120 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxODMxmyB8sAueOHT5A:-KxODMxmyB8sAueOHT5B:bgxzsb3) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/table/LargeSelectionCausesNPE.java#L120)):*
> ```Java
>         };
> 
>         Button.ClickListener clickListener = e-> {
> ```

`event` instead of `e`

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 25 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxOE-6ghIJD7cq9R_hG:-KxOE-6ghIJD7cq9R_hH:b6qjqr6) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L25)):*
> ```Java
> 
>     private static final Predicate<TestBenchElement> THEME_RESOURCE =
>             event -> event.isElementPresent(By.tagName("img"))
> ```

not event (same for the two below this one)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10222)*

**Comment by asashour** [comment]
Thanks for your feedback, I hope this is merged first before the "handlers with lambda PR",  so I can fix the conflicts (with incorrect names) before you spend time reviewing it.

---

Review status: 203 of 213 files reviewed at latest revision, 16 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 273 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNYjFSaXHy3ROL_2VK:-KxOG68YSuM1MwGW-CJ0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VDateField.java#L273)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events, but entries
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNdsNCSKD9Tiuijibu:-KxOGSiwlpHI6o5KDC7z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L105)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 107 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNe3fRYSe9wVQPhhXm:-KxOGT36uDfVxadPWqSB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L107)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNe-ONhwYoSgO910vP:-KxOG_7NFcWYG-RnlnRr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L112)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BinderTestBase.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNeKvoY3dyKSrGpvgv:-KxOGfsHz07eG7Hso0mY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/server/src/test/java/com/vaadin/data/BinderTestBase.java#L54)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Looks like this is not an event listener, but `SerializableFunction<Exception,String>`
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkAwKDl5DcxBX9ByY:-KxOH-p_gXlFSzoyR9dm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java#L83)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not an event
</blockquote></details>

Done.

---

*[test/widget-set-testutil/src/main/java/com/vaadin/test/widgetset/AbstractTestWidgetSetUI.java, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkR1IwZ1mWHrWIFJH:-KxOH6W7E36dCzXu-HCc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/widget-set-testutil/src/main/java/com/vaadin/test/widgetset/AbstractTestWidgetSetUI.java#L22)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

use `event` instead of `e`
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 465 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkdrrUyUCU4O61Q20:-KxOHBGVhtKsnn8dz4JK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L465)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not an event
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 468 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNkgMHcyTa6XyYPQOE:-KxOHEcWxXqTEfE-OL6K:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L468)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not an event
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxTextFieldEventOrder.java, line 19 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNwveugiuLgEs_3E5P:-KxOHQop7NzAt8FAxQ11:bormsi8) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxTextFieldEventOrder.java#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

comment and code got reordered here
</blockquote></details>

Done.Eclipse formatting issue.

---

*[uitest/src/main/java/com/vaadin/tests/components/table/KeyboardNavigationWithChangingContent.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxOD9xKviCEDZFARVi1:-KxOHkiFx4ZjjLeA3lre:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/table/KeyboardNavigationWithChangingContent.java#L35)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

`event` instead of `e`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/table/LargeSelectionCausesNPE.java, line 120 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxODMxmyB8sAueOHT5A:-KxOHsQwLTxPb4uSgYMD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/main/java/com/vaadin/tests/components/table/LargeSelectionCausesNPE.java#L120)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

`event` instead of `e`
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 25 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxOE-6ghIJD7cq9R_hG:-KxOHzYQjmDXhmYSbQfK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L25)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not event (same for the two below this one)
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 109 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNXg4wJsvLo_WU0Oie:-KxOFtBcRt3mfTPx-Eze:bc6zol3) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L109)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

These are not events, their type is `Map.Entry`
</blockquote></details>

Reverted, or should I make it `entry`?

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 124 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNYIYclcrePOsVuYFb:-KxOGQDMPtZdvO0-isHD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L124)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events, but entries
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNjJCahSVReRzA7H9X:-KxOGpN32K0ArWz2bAd0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L59)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not an event
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10222#-:-KxOJ-VeLmpjWTKkreAC:b-kdzk4g)*

**Comment by pekam** [comment]
:lgtm: and thanks for the heads up!

---

Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 109 at r2](https://reviewable.io:443/reviews/vaadin/framework/10222#-KxNXg4wJsvLo_WU0Oie:-KxOKCzN3cIqMzaMSIZo:b-aehxzx) ([raw file](https://github.com/vaadin/framework/blob/83579bb74cb77b0ed3fa4c7a0bd3009a2735dac0/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L109)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Reverted, or should I make it `entry`?
</blockquote></details>

It's fine for me since this PR doesn't relate to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10222#-:-KxOKYhskj4Tm4p-qjnU:bog2edw)*

**Pull request merged**
