### PR TITLE
Add item descriptions to Tree

### LINKED ISSUE #9803: Vaadin 8.1 Tree setItemDescriptionGenerator
Since version 8 I don't find a replacement method for the missing setItemDescriptionGenerator() method on the vaadin tree. Is there another possibility to create a tooltip on an single tree item?

In my opinion the setItemDescriptionGenerator just got lost without a replacement method.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9803

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9840)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 600 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowVwLzmDQ-7wX2aBY:-KrowVwMe96zGbykoH5-:b-fhnqnu) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L600)):*
> ```Java
> 
>     /**
>      * Sets the description generator that is used for generating descriptions
> ```

could mention that description == tooltip

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 606 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowQ7BBnTcQLENUAnS:-KrowQ7BBnTcQLENUAnT:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L606)):*
> ```Java
>      *            the item description generator to set, or <code>null</code> to
>      *            remove a previously set generator
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 656 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowSx7swCi05j-Cz2W:-KrowSx7swCi05j-Cz2X:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L656)):*
> ```Java
>      *
>      * @return the item description generator
>      */
> ```

since tag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9840)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 600 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowVwLzmDQ-7wX2aBY:-Ks2mXXXJd7apoVAFIt_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L600)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could mention that description == tooltip
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 606 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowQ7BBnTcQLENUAnS:-Ks2mV1KWK3HxTLXEshM:b-dvevv2) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L606)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Added empty since tag.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 656 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowSx7swCi05j-Cz2W:-Ks2mX1DqakxwDJofMWr:b-dvevv2) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L656)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Added empty since tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9840)*

**Comment by hesara** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 606 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowQ7BBnTcQLENUAnS:-Ks2nx8V1IkqChqELGmj:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L606)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Added empty since tag.
</blockquote></details>

OK

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 656 at r1](https://reviewable.io:443/reviews/vaadin/framework/9840#-KrowSx7swCi05j-Cz2W:-Ks2nyn-dN0BC8xNg33L:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/e92ec41396c83d1e7e8ccca9ebf97651be1b49b2/server/src/main/java/com/vaadin/ui/Tree.java#L656)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Added empty since tag.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9840)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9840)*

**Pull request merged**
