### PR TITLE
Replace Listing with HasDataProvider and HasFilterableDataProvider

### PR DESCRIPTION
**Pull request by Legioth**
The type parameters of the Listing interface does in practice mean that
it isn't useful for anything. This patch replaces that interface with
separate types for components that require filterable data providers and
components that support any kind of data provider.

The setItem methods are extracted to a common interface that is also
directly implemented by AbstractListing.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8122)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 20 of 24 files at r1.
Review status: 20 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasDataProvider.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSHkmlmanmdyv5FnT:-K_YSHknHn2QSwtoixcy:btmpib) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasDataProvider.java#L41)):*
> ```Java
>      * @return the data provider, not null
>      */
>     DataProvider<T, ?> getDataProvider();
> ```

FW8 convention is still to use the keyword "public" for interface methods - also applies to other interfaces

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSamhszkwaUX55jQp:-K_YSamhszkwaUX55jQq:b-5dxzo) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L34)):*
> ```Java
>  * @see HasDataProvider
>  */
> public interface HasFilterableDataProvider<T, F> extends HasItems<T> {
> ```

I guess this means that a subclass of a class implementing HasDataProvider cannot implement HasFilterableDataProvider - but probably not a common issue and the equivalent restriction was there for typing reasons already before.

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSZ3qaXQ4a02pJ9sA:-K_YSZ3qaXQ4a02pJ9sB:b-3jbcpf) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L41)):*
> ```Java
>      * @return the data provider, not null
>      */
>     DataProvider<T, F> getDataProvider();
> ```

see comment in HasDataProvider

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YTAv3rgaQh1EJvT3G:-K_YTAv4X6kIFu34FtDs:behbyhf) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasItems.java#L37)):*
> ```Java
> public interface HasItems<T> extends Component, Serializable {
>     /**
>      * Sets the data items of this component provided as a collection.
> ```

could probably mention a bit more about the contract, e.g. changes to the collection if we promise anything such, or mention those in overridden javadoc if component specific

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122)*

**Comment by Legioth** [comment]
Review status: 20 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasDataProvider.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSHkmlmanmdyv5FnT:-K_YxDOD4S-b7o00T1Qu:b50bciq) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasDataProvider.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

FW8 convention is still to use the keyword "public" for interface methods - also applies to other interfaces
</blockquote></details>

Was OK in `Listing` from which this was copied, but I'll nevertheless fix it here.

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSamhszkwaUX55jQp:-K_YxaNaZ1g2fbMCfLAe:b-xc3qki) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I guess this means that a subclass of a class implementing HasDataProvider cannot implement HasFilterableDataProvider - but probably not a common issue and the equivalent restriction was there for typing reasons already before.
</blockquote></details>

Clarification added to the javadocs.

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSZ3qaXQ4a02pJ9sA:-K_YxI7GGSU5P6NY18zS:b50bciq) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment in HasDataProvider
</blockquote></details>

Was OK in `Listing` from which this was copied, but I'll nevertheless fix it here.

---

*[server/src/main/java/com/vaadin/data/HasItems.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YTAv3rgaQh1EJvT3G:-K_Yy3XKNzVG7Y9ej8xY:b50bciq) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasItems.java#L37)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could probably mention a bit more about the contract, e.g. changes to the collection if we promise anything such, or mention those in overridden javadoc if component specific
</blockquote></details>

Was OK in `Listing` from which this was copied, but I'll nevertheless fix it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122)*

**Comment by hesara** [comment]
Reviewed 1 of 24 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSamhszkwaUX55jQp:-K_ZE2KdGd8UY8_q885P:b-b1q0c1) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L34)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Clarification added to the javadocs.
</blockquote></details>

In practice, this means that one cannot e.g. make a FilterableGrid that implements this interface. Might not be an issue.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 226 at r2](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_ZDHwv4kcv9Yw1fv-M:-K_ZDHwv4kcv9Yw1fv-N:b-rt6my5) ([raw file](https://github.com/vaadin/framework/blob/3683769be152e4f03239011b85e81a9e37938241/server/src/main/java/com/vaadin/ui/ComboBox.java#L226)):*
> ```Java
> 
>     @Override
>     public void setItems(@SuppressWarnings("unchecked") T... items) {
> ```

if this is deleted, no more default caption filter - is this desired

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_YSamhszkwaUX55jQp:-K_ZEsMoA-xBAyVu-dus:b-uhn3mp) ([raw file](https://github.com/vaadin/framework/blob/2f894d25475fccb518b8ba5b111d4ce9edf47289/server/src/main/java/com/vaadin/data/HasFilterableDataProvider.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In practice, this means that one cannot e.g. make a FilterableGrid that implements this interface. Might not be an issue.
</blockquote></details>

That doesn't change with this patch since `implements Listing<T, DataProvider<T, ?>>` also prevented that. 

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 226 at r2](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_ZDHwv4kcv9Yw1fv-M:-K_ZFkhOKHIwMhoD5oXO:b-ti5h54) ([raw file](https://github.com/vaadin/framework/blob/3683769be152e4f03239011b85e81a9e37938241/server/src/main/java/com/vaadin/ui/ComboBox.java#L226)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

if this is deleted, no more default caption filter - is this desired
</blockquote></details>

Deleting the code here doesn't change anything since the default implementation of this method delegates to the `setItems(Collection<T>)` overload that still sets a caption filter.

On the contrary, this new design fixes that bug that the caption filter was not used for the `setItems(Stream<T>)` overload since that method was not explicitly overridden in `ComboBox`, and the unsafe cast in the old default method in `Listing` didn't make the problem obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 226 at r2](https://reviewable.io:443/reviews/vaadin/framework/8122#-K_ZDHwv4kcv9Yw1fv-M:-Ka61syBcJzJLuhq3UVU:b-7l3ba0) ([raw file](https://github.com/vaadin/framework/blob/3683769be152e4f03239011b85e81a9e37938241/server/src/main/java/com/vaadin/ui/ComboBox.java#L226)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Deleting the code here doesn't change anything since the default implementation of this method delegates to the `setItems(Collection<T>)` overload that still sets a caption filter.

On the contrary, this new design fixes that bug that the caption filter was not used for the `setItems(Stream<T>)` overload since that method was not explicitly overridden in `ComboBox`, and the unsafe cast in the old default method in `Listing` didn't make the problem obvious.
</blockquote></details>

ping?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122)*

**Comment by hesara** [comment]
Documentation to be updated if needed (coordinated with the BoV printing), apart from that looks an ok step to me

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122#-:-Ka668yXjlGPObAoUh9V:b-cgbaon)*

**Comment by Legioth** [comment]
Rebased. Verified that "listing" is not used as a technical term in any documentation text.

---

Review status: 17 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122#-:-KaBoaCUYIUBQVQTqsCc:bcvclpa)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 14 of 24 files at r1, 3 of 4 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8122#-:-KaHvDPYXAx2CbZwGUSN:bnfp4nl)*

**Pull request merged**
