### PR TITLE
Use style name for drag source according to convention

### PR DESCRIPTION
**Pull request by wbadam**
No ticket for this one (yet), just created for review and discussion.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9091)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KhlmH_fUFW_gTkvlnYX:bltkxqk) (no related file):*
 The idea is that all style names should follow the convention `v-widgetname-stylename` and would also be nice to have a pattern across dnd classes.

This implementation adds `-dragsource` suffix to the draggable element and is overridable. Should consider if the widget's main element should have some sort of style name, perhaps the same suffix.

Similar approach is implemented in #9090 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KiE59V3AtQxvK1As3Va:b-pc18eh) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

 The idea is that all style names should follow the convention `v-widgetname-stylename` and would also be nice to have a pattern across dnd classes.

This implementation adds `-dragsource` suffix to the draggable element and is overridable. Should consider if the widget's main element should have some sort of style name, perhaps the same suffix.

Similar approach is implemented in #9090 
</blockquote></details>

Does this affect any standard theme, test theme or the sampler?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjC8ZTMBO8jiI3PZKtW:byznl1z) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this affect any standard theme, test theme or the sampler?
</blockquote></details>

It actually effects the rule `user-select: none`. It is mentioned in the docs that setting such rule may be needed.

With this new style name it is not possible to apply such rule on the framework level as the style name is different for each component.

It may not be important to set it on framework level as most components wouldn't be effected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjCDVWBb3_EcdsNQaZH:b-kiz9iu) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

It actually effects the rule `user-select: none`. It is mentioned in the docs that setting such rule may be needed.

With this new style name it is not possible to apply such rule on the framework level as the style name is different for each component.

It may not be important to set it on framework level as most components wouldn't be effected.
</blockquote></details>

Please add back the `v-draggable` to accompany the suffixed style name, and then in the documentation PR you mention these both

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjCHDKmqSEza4LHENO0:b-ethm8r) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add back the `v-draggable` to accompany the suffixed style name, and then in the documentation PR you mention these both
</blockquote></details>

In this case just disregard this PR

Will update doc next

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjCHXSjtQTPsO2hVIrK:b2jqi9t) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

In this case just disregard this PR

Will update doc next
</blockquote></details>

Why ???
I see it as the primary style + suffix, e.g. `v-label-dragsource` is for component specific styling
And `v-draggable` is for all components 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjCJ81vWVq8wqWM00OF:b8xhiav) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why ???
I see it as the primary style + suffix, e.g. `v-label-dragsource` is for component specific styling
And `v-draggable` is for all components 
</blockquote></details>

I missed the word _accompany_, will add back `v-draggable` so elements would have both style names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9091#-KhlmH_fUFW_gTkvlnYW:-KjCRH2qxVagTXmHrr3B:b-d5cuek) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

I missed the word _accompany_, will add back `v-draggable` so elements would have both style names.
</blockquote></details>

Thus this has no effect on current samples or such

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9091)*

**Pull request merged**
