### PR TITLE
Small docs fix

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10749)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/components/components-grid.asciidoc, line 961 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10749#-L8gFiuM3HdHxZHXXdTA:-L8gFiuM3HdHxZHXXdTB:b8y9af) ([raw file](https://github.com/vaadin/framework/blob/44c5526d04cf9ab385170f51164301845bf073f3/documentation/components/components-grid.asciidoc#L961)):*
> ```AsciiDoc
> 
> You set a [interfacename]#StyleGenerator# to a grid with
> [methodname]#setStyleGenerator()#. A lambda gets a
> ```

I'd put an emphasis that this is `The lambda` that the user provides (not sure how to word it though)

---

*[documentation/components/components-grid.asciidoc, line 962 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10749#-L8gFgAf38YQH8SOzV7t:-L8gFgAf38YQH8SOzV7u:bqaxpar) ([raw file](https://github.com/vaadin/framework/blob/44c5526d04cf9ab385170f51164301845bf073f3/documentation/components/components-grid.asciidoc#L962)):*
> date item
what date item is this talking about?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10749)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10749)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 961 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10749#-L8gFiuM3HdHxZHXXdTA:-L99OVSJ9QTqkaCK_wGl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/44c5526d04cf9ab385170f51164301845bf073f3/documentation/components/components-grid.asciidoc#L961)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd put an emphasis that this is `The lambda` that the user provides (not sure how to word it though)
</blockquote></details>

Done.

---

*[documentation/components/components-grid.asciidoc, line 962 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10749#-L8gFgAf38YQH8SOzV7t:-L99OVJ14xHPXoi0aoTW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/44c5526d04cf9ab385170f51164301845bf073f3/documentation/components/components-grid.asciidoc#L962)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> date item
what date item is this talking about?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10749)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10749)*

**Pull request merged**
