### PR TITLE
Ensure Upload is properly reset after an upload is interrupted (#9635)

### LINKED ISSUE #9635: Vaadin 7.7.10 Upload does not work when using the same file again, when previous update was interrupted
Upload does not work when using the same file again, when previous update was interrupted. Tested in Chrome using Tomcat 7. Uploading a big file and interrupting the process then leads to inability to upload the same file right after that.

Trying to upload another(different) file works fine and also after that uploading of the first file works as expected. 

Was not able to reproduce in Firefox/ IE, only Chrome. 

Also running the below code on jetty server in Chrome doesn't do anything on cancel button click. Works fine in other browsers
Vaadin version : 7.7.10

Also there was an older ticket about similar issue which is closed as resolved, but it was updated with similar issues after being closed also.

[ https://github.com/vaadin/framework/issues/4212 ]

Example to reproduce:
`	  

            final VerticalLayout layout = new VerticalLayout();
            Upload upload = new Upload();
		upload.setImmediate(true);
		Button cancel = new Button("Cancel upload");
		cancel.setEnabled(false);
		cancel.addClickListener(event -> {
			System.out.print("Cancel button");
			upload.interruptUpload();
		});

		Label name = new Label("nothing uploaded");
		Label numBytes = new Label();
		upload.setReceiver((filename, mime) -> {
			return new OutputStream() {
				long c = 0;

				@Override
				public void write(int b) throws IOException {
					c++;
				}

				@Override
				public void close() throws IOException {
					super.close();
					numBytes.setValue("Finished: read " + c + " at " + new Date());
				}

			};
		});
		upload.addStartedListener(ev -> {
			name.setValue(ev.getFilename());
			numBytes.setValue("started");
			cancel.setEnabled(true);
			UI.getCurrent().setPollInterval(1000);
		});
		upload.addProgressListener((bytes, total) -> numBytes.setValue("received " + bytes + " of " + total));
		upload.addFinishedListener(ev -> cancel.setEnabled(false));

		layout.addComponent(upload);
		layout.addComponent(name);
		layout.addComponent(numBytes);
		layout.addComponent(cancel);

		setContent(layout);`

### PR DESCRIPTION
**Pull request by Ansku**
Fixes #9635

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10265)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 230 at r1](https://reviewable.io:443/reviews/vaadin/framework/10265#-KxgSO2Qoy--K-_eNe6O:-KxgSO2Qoy--K-_eNe6P:bes0bz6) ([raw file](https://github.com/vaadin/framework/blob/1c91a14cff5e1e73606c18446167cfc4a08bd726/client/src/main/java/com/vaadin/client/ui/VUpload.java#L230)):*
> ```Java
>              */
>             cleanTargetFrame();
>             rebuildPanel();
> ```

Does calling this method reset the selected file or is it cleared already when the upload button is hit ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10265)*

**Comment by Ansku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 230 at r1](https://reviewable.io:443/reviews/vaadin/framework/10265#-KxgSO2Qoy--K-_eNe6O:-Kxgxmb2cGV6RMMosW17:b-ffr1y7) ([raw file](https://github.com/vaadin/framework/blob/1c91a14cff5e1e73606c18446167cfc4a08bd726/client/src/main/java/com/vaadin/client/ui/VUpload.java#L230)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Does calling this method reset the selected file or is it cleared already when the upload button is hit ?
</blockquote></details>

That replaces the element in order to clear the previous selection, yes. Normally that is done when the upload is finished, so in the case of interruption it needs to be done separately. This method is only called from two locations, one with the explicit purpose of cleaning up after interruption, and the other just after setting submitted = false; so that this particular section is never reached.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10265)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10265)*

**Comment by tsuoanttila** [comment]
Please rebase or merge with `master`

**Comment by Ansku** [comment]
Local merge failed catastrophically, rebased version in a new branch with new pull request: https://github.com/vaadin/framework/pull/10522

**Pull request closed without merging**
