### PR TITLE
Use StandardCharsets.UTF_8

### PR DESCRIPTION
**Pull request by asashour**
Which was introduced in Java 7, so `compatibility` projects weren't modified.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10113)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 11 of 22 files at r1.
Review status: 11 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 329 at r1](https://reviewable.io:443/reviews/vaadin/framework/10113#-KvBLh_MiceyxyOLIBRJ:-KvBLh_MiceyxyOLIBRK:bzgdu4b) ([raw file](https://github.com/vaadin/framework/blob/e137a802fe3d205a31ab0c8d5f960e40869b8a36/server/src/main/java/com/vaadin/server/BootstrapHandler.java#L329)):*
> ```Java
>             try {
>                 encodedString = URLEncoder.encode(queryString,
>                         UTF_8.toString());
> ```

Charset.name() would be semantically more correct here and elsewhere, even though toString() happens to return the name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10113)*

**Comment by asashour** [comment]
Review status: 11 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 329 at r1](https://reviewable.io:443/reviews/vaadin/framework/10113#-KvBLh_MiceyxyOLIBRJ:-KvBPrvochjeT6Pqwruj:b-4heaqc) ([raw file](https://github.com/vaadin/framework/blob/e137a802fe3d205a31ab0c8d5f960e40869b8a36/server/src/main/java/com/vaadin/server/BootstrapHandler.java#L329)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Charset.name() would be semantically more correct here and elsewhere, even though toString() happens to return the name
</blockquote></details>

Done. I actually started with `.name()`, but then thought `.toString()` would be more commonly used with other classes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10113)*

**Comment by hesara** [comment]
:lgtm: but probably needs a merge due to a conflict

---

Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10113#-:-KvBQL9Pc7bi-mQpKw7d:bljerw1)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10113#-:-KvCES-4VV2mgH65DOvm:bnfp4nl)*

**Pull request merged**
