### PR TITLE
fix: use time-constant comparison for CSRF tokens

### PR DESCRIPTION
**Pull request by TatuLund**
This hardens the framework against a theoretical timing attack based on
comparing how quickly a request with an invalid CSRF token is rejected.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12188)

### CODE REVIEW

**Comment by TatuLund** [comment]
Picked from: https://github.com/vaadin/flow/commit/292b3a0b1d68b34d9b824e5afe62deb7b32e1ebb

**Review by Ansku — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12188)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by AdamGold** [comment]
Hey! when are you planning to release this?

**Comment by TatuLund** [comment]
> Hey! when are you planning to release this?

@AdamGold in the best possible speed.

**Pull request merged**
