### PR TITLE
Some cleanup to themes module

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8526)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8526#-KdZoHqTePKwx_G0YPqu:-KdZoHqTePKwx_G0YPqv:bsruxvu) ([raw file](https://github.com/vaadin/framework/blob/f325248c4dca0e7d0b3000b694ea2f16e3b4705f/themes/pom.xml#L20)):*
> ```XML
>         
>         <dependency>
>             <groupId>com.vaadin</groupId>
> ```

we seem to have slightly mixed practices about this, but in general project internal dependencies are expressed with ${project.groupId} within the framework POMs whereas e.g. references to add-ons that are not within the project should be more explicit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8526)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8526#-KdZoHqTePKwx_G0YPqu:-KdZtQmsN3av6QJza0Lg:b-7pii0w) ([raw file](https://github.com/vaadin/framework/blob/f325248c4dca0e7d0b3000b694ea2f16e3b4705f/themes/pom.xml#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

we seem to have slightly mixed practices about this, but in general project internal dependencies are expressed with ${project.groupId} within the framework POMs whereas e.g. references to add-ons that are not within the project should be more explicit
</blockquote></details>

Corrected to make in line with other common practice, despite of the fact that `  <groupId>${project.groupId}</groupId>` breaks dependency inheritance in certain situations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8526)*

**Comment by hesara** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8526#-KdZoHqTePKwx_G0YPqu:-KdyyS_IgeFw12QRV8fA:b-dco4o9) ([raw file](https://github.com/vaadin/framework/blob/f325248c4dca0e7d0b3000b694ea2f16e3b4705f/themes/pom.xml#L20)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Corrected to make in line with other common practice, despite of the fact that `  <groupId>${project.groupId}</groupId>` breaks dependency inheritance in certain situations.
</blockquote></details>

I think the last change is the opposite of what I proposed - project internal changes are now using the explicit com.vaadin even though they should be the same as project.version, and external ones are using project.groupId even though they should be explicit because they technically can change not to match the framework project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8526)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8526#-KdZoHqTePKwx_G0YPqu:-Ke33euKTC_TbZ_-sgiE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f325248c4dca0e7d0b3000b694ea2f16e3b4705f/themes/pom.xml#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I think the last change is the opposite of what I proposed - project internal changes are now using the explicit com.vaadin even though they should be the same as project.version, and external ones are using project.groupId even though they should be explicit because they technically can change not to match the framework project
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8526)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8526)*

**Pull request merged**
