### PR TITLE
Make compatibility aliases for isRequiredIndicatorVisible()

### LINKED ISSUE #8337: Make compatibility aliases for isRequiredIndicatorVisible()
`isRequiredIndicatorVisible()` must have v7-compatible `isRequired()` aliases in legacy classes

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8337

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8372)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8372#-KbjqrabnJJw6yotiUlI:-KbjqrabnJJw6yotiUlJ:b-qe4xg6) ([raw file](https://github.com/vaadin/framework/blob/946f5292273d34611a543eec4575c3fddf724524/compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java#L52)):*
> ```Java
>      * {@link #isRequiredIndicatorVisible()}, and is left for legacy reasons.
>      * 
>      * @deprecated Use {@link #isRequiredIndicatorVisible()} instead.
> ```

The whole class is deprecated, so this is unnecessary 

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/8372#-KbjqzRbXT23WfnIP5gA:-KbjqzRcDyruQoFRDOfN:b-ya81ng) ([raw file](https://github.com/vaadin/framework/blob/946f5292273d34611a543eec4575c3fddf724524/compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java#L56)):*
> ```Java
>      * @return true if required indicator should be shown
>      */
>     @Deprecated
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8372)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8372#-KbjqrabnJJw6yotiUlI:-Kbjs_kYyH-u85w69Jue:bsuylq8) ([raw file](https://github.com/vaadin/framework/blob/946f5292273d34611a543eec4575c3fddf724524/compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java#L52)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

The whole class is deprecated, so this is unnecessary 
</blockquote></details>

It's javadoc tag explaining what should be used instead.
The class has just @Deprectated annotation.

I can remove it. But are you really sure ?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/8372#-KbjqzRbXT23WfnIP5gA:-KbjsWV16hfNFp3-uHTn:b-kxidqw) ([raw file](https://github.com/vaadin/framework/blob/946f5292273d34611a543eec4575c3fddf724524/compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java#L56)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Added by eclipse automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8372)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/8372#-KbjqzRbXT23WfnIP5gA:-Kbjz9hZpQP-vlMJ7JpC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/946f5292273d34611a543eec4575c3fddf724524/compatibility-client/src/main/java/com/vaadin/v7/client/ui/AbstractFieldConnector.java#L56)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Added by eclipse automatically.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8372)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8372)*

**Pull request merged**
