### PR TITLE
(Re)introduce server side sort for Grid.

### PR DESCRIPTION
**Pull request by denis-anisimov**
vaadin/framework8-issues#557

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7997)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridSortingTest.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/7997#-KZ0ZMu2WAUn9YuzQ7Rq:-KZ0ZMu3AgcW--2x7uha:b3z758x) ([raw file](https://github.com/vaadin/framework/blob/5a67640a63daf11f00a7f4de967e5363fe7a2d19/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridSortingTest.java#L17)):*
> ```Java
> import com.vaadin.testbench.parallel.Browser;
> 
> @RunLocally(Browser.PHANTOMJS)
> ```

This annotatoin breaks validation build. please remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7997)*

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7997)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridSortingTest.java, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/7997#-KZ0ZMu2WAUn9YuzQ7Rq:-KZ0n8onzJOEnI1y3T_Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5a67640a63daf11f00a7f4de967e5363fe7a2d19/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridSortingTest.java#L17)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This annotatoin breaks validation build. please remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7997)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7997#-:-KZ0sksjkkBrZXPuoHs9:bnfp4nl)*

**Pull request merged**
