### PR TITLE
Unlock panel caption div hacking

### LINKED ISSUE #10119: Unlock panel caption div hacking
Caption existence is detected in a plain code, moving that to a separate protected method might simplify VPanel subclassing and tweaking.

### PR DESCRIPTION
**Pull request by elmot**
Fixes #10119

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10120)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwiZxR3_7NK11PIgFuO:-KwiZxR4tKfnSSt1LoDZ:b-iwoqk9) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L176)):*
> ```Java
>     }
> 
>     /***
> ```

One extra `*`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10120)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZYQ_k4oI6qe2Kz7g:-KwsZYQ_k4oI6qe2Kz7h:b-w8wi5b) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L176)):*
> ```Java
>     }
> 
>     /***
> ```

Extra * is still there

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 177 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZ_QswKjFOsgkDjLb:-KwsZ_QswKjFOsgkDjLc:bthhwlb) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L177)):*
> ```Java
> 
>     /***
>      * Detects if caption div should be visible.
> ```

Add one empty space between the javadoc text and the return

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZeCgGTQcvPOwdn0K:-KwsZeCgGTQcvPOwdn0L:b-f3b9rw) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L178)):*
> ```Java
>     /***
>      * Detects if caption div should be visible.
>      * @return true if caption div should be shown
> ```

`{@code true}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10120)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZYQ_k4oI6qe2Kz7g:-KwtV9em11q1NK4EirbJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L176)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Extra * is still there
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 176 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwiZxR3_7NK11PIgFuO:-KwtV9qfdFVTVdydXciP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L176)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

One extra `*`
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 177 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZ_QswKjFOsgkDjLb:-KwtVAHdXpHhF7lqdvqq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L177)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Add one empty space between the javadoc text and the return
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/10120#-KwsZeCgGTQcvPOwdn0K:-KwtVAiINfzZIVVNZsk3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c41af7a4acafafad479c71444bbdeb209a2017b/client/src/main/java/com/vaadin/client/ui/panel/PanelConnector.java#L178)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`{@code true}`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10120)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10120#-:-KwtjiNgTE7i4gwcLIZ8:bnfp4nl)*

**Pull request merged**
