### PR TITLE
Layout defaults

### PR DESCRIPTION
**Pull request by elmot**
First draft to find what which tests are affected

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/100)

### CODE REVIEW

**Comment by ahie** [comment]
This PR shouldn't include the removal of InheritableThreadLocal. Should probably also run the full modern browsers tests for this.

---

Review status: 0 of 53 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100#-:-KYXl7Br3hBynzFL13zd:b-3tmu0h)*

**Comment by hesara** [comment]
Reviewed 2 of 7 files at r1, 36 of 37 files at r2.
Review status: 38 of 44 files reviewed at latest revision, 5 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/MarginInfo.java, line 156 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmTgPjzMfDTtzDiScd:-KYmTgPjzMfDTtzDiSce:b-cg53zy) ([raw file](https://github.com/vaadin/framework/blob/dd18d1dd5970a1704ec0f2ea9add611a3a897fd7/shared/src/main/java/com/vaadin/shared/ui/MarginInfo.java#L156)):*
> ```Java
>      * @since 8.0.0
>      *
>      * @return true if all edges have margins enabled
> ```

different parts of javadoc and implementation seem to be inconsistent with each other

---

*[uitest/src/main/java/com/vaadin/tests/components/splitpanel/SplitPanelWithMinimumAndMaximum.java, line 20 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmUHlnVo-6shF3lb0e:-KYmUHloH9bQQm5eEkSh:b3t25bq) ([raw file](https://github.com/vaadin/framework/blob/dd18d1dd5970a1704ec0f2ea9add611a3a897fd7/uitest/src/main/java/com/vaadin/tests/components/splitpanel/SplitPanelWithMinimumAndMaximum.java#L20)):*
> ```Java
>         TabSheet tabs = new TabSheet();
> 
>         VerticalLayout verticalLayout = new VerticalLayout();
> ```

(the old names did make sense even though at first they sound different than the type, but I guess this change is ok.)

---

*[uitest/src/main/java/com/vaadin/tests/layouts/layouttester/HLayout/HCaption.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmVBY5GbiXkQpLJhTK:-KYmVBY5GbiXkQpLJhTL:b-37uxej) ([raw file](https://github.com/vaadin/framework/blob/8bd92c97083f3a14b226d409c8647d63afa6d6ab/uitest/src/main/java/com/vaadin/tests/layouts/layouttester/HLayout/HCaption.java#L23)):*
> ```Java
> public class HCaption extends BaseCaption {
> 
>     /**
> ```

(unrelated but ok change)

---

*[uitest/src/main/java/com/vaadin/tests/layouts/layouttester/HLayout/HComponentSizing.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmVEhtJWJUJDmFna_g:-KYmVEhtJWJUJDmFna_h:b-37uxej) ([raw file](https://github.com/vaadin/framework/blob/8bd92c97083f3a14b226d409c8647d63afa6d6ab/uitest/src/main/java/com/vaadin/tests/layouts/layouttester/HLayout/HComponentSizing.java#L29)):*
> ```Java
> public class HComponentSizing extends BaseComponentSizing {
> 
>     /**
> ```

(unrelated but ok change)

---

*[uitest/src/main/java/com/vaadin/tests/layouts/layouttester/VLayout/VCaption.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmVHl4UZWVK63VFNY7:-KYmVHl4UZWVK63VFNY8:b-37uxej) ([raw file](https://github.com/vaadin/framework/blob/8bd92c97083f3a14b226d409c8647d63afa6d6ab/uitest/src/main/java/com/vaadin/tests/layouts/layouttester/VLayout/VCaption.java#L29)):*
> ```Java
> public class VCaption extends BaseCaption {
> 
>     /**
> ```

(unrelated but ok change)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100)*

**Comment by hesara** [comment]
Reviewed 3 of 7 files at r1, 1 of 37 files at r2, 13 of 13 files at r3, 7 of 7 files at r4.
Review status: 62 of 64 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java, line 54 at r4](https://reviewable.io:443/reviews/vaadin/framework/100#-KYnM7vmD1SKJ5J08i1W:-KYnM7vmD1SKJ5J08i1X:b92wqru) ([raw file](https://github.com/vaadin/framework/blob/303a7f891d925fc27e16e2a18f71051a2c029064/server/src/test/java/com/vaadin/tests/server/component/DeclarativeMarginTestBase.java#L54)):*
> ```Java
>                                 boolean bottom, boolean left) {
>         String s = "<" + componentTag + " ";
>         String suffix = defaultMargin ? "=false " : " ";
> ```

(no quotes around the value, but I guess this is ok)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100)*

**Comment by hesara** [comment]
Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100)*

**Comment by hesara** [comment]
Looks ok in review but Ilia to submit only when separate browser tests have been run and checked.

**Comment by elmot** [comment]
"Modern browsers" is run over the change, it has a bunch of failures, but all of them look unrelated to this PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[shared/src/main/java/com/vaadin/shared/ui/MarginInfo.java, line 156 at r2](https://reviewable.io:443/reviews/vaadin/framework/100#-KYmTgPjzMfDTtzDiScd:-KYnep5m3svEnMU1xO2-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dd18d1dd5970a1704ec0f2ea9add611a3a897fd7/shared/src/main/java/com/vaadin/shared/ui/MarginInfo.java#L156)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

different parts of javadoc and implementation seem to be inconsistent with each other
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/100#-:-KYnePbmeEY2VjISPF9N:b-if4gmy)*

**Pull request merged**
