### PR TITLE
Add flush() implementation to DateField

### LINKED ISSUE #10488: DateField not submitted on Return
This is an issue in both 8.2.0 and 8.1.7
It works in 7.7.10

The following code has a textfield, a date field and a button. The button has Enter as shortcut.
When writing something in the textfield, it is submitted when I press Enter.
When writing something in the date field, it is *not* submitted when I press Enter.
It *is* submitted if I tab out of the field before pressing Enter, or if I click the button.

``` java
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        final TextField name = new TextField();
        name.setCaption("Type your name here:");

        final DateField dateField = new DateField("Date of birth");  
        
        Button button = new Button("Click Me");
        button.setClickShortcut(KeyCode.ENTER, 0);
        button.addClickListener(e -> {
            layout.addComponent(new Label("Thanks " + name.getValue() + ", it works! Your Date of birth is: " + dateField.getValue()));
        });
        
        layout.addComponents(name, dateField, button);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

Edit: I should add that in 8.1.7 it fails with both the regular version and the v7 compatibility version.
I have not tested the compatibility version in 8.2.
I have tested with Chrome 63.0, Edge 40 and Firefox 57.0

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #10488

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10518)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10518#-L2_a-iUakqWr85ZDEhb:-L2_a-iUakqWr85ZDEhc:b-74gkfs) (no related file):*
Need to implement the same for compatibility component

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10518)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10518)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10518#-:-L4FR5FQJgy66xAw69Hd:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 5 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10518)*

**Pull request merged**
