### PR TITLE
Use enhanced for loop instead of Iterator.

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10100)

### CODE REVIEW

**Comment by hesara** [comment]
Quickly reviewed non-compatibility parts first.

---

Reviewed 22 of 50 files at r1.
Review status: 22 of 50 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv63dIcXaYUzu2nTiR7:-Kv63dIdVnpwdVKXq3Tq:bpl39tw) ([raw file](https://github.com/vaadin/framework/blob/cb91ab76eecbf85ad598fc5054fa2ec5ab3308f6/client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java#L61)):*
> ```Java
>     }
> 
>     private final ArrayList<ShortcutAction> actions = new ArrayList<>();
> ```

(this will probably conflict with the change to use interfaces instead of implementations)

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv663SatCWyQdSCd2Zi:b-rumfs) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
> ```Java
>     @Override
>     public void focus() {
>         for (Widget widget : this) {
> ```

This is just finding the first widget in this, if any, and I don't find the enhanced for loop clearer or semantically more correct than the iterator based solution. As the logic is split over multiple lines and that makes it less obvious for a reader, I think a comment here would be in order whichever solution is used.

---

*[server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv64zqRqkrMoY_2r42r:-Kv64zqRqkrMoY_2r42s:b-e07uql) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java#L121)):*
> ```Java
>         }
> 
>         List<Field> nonSerializableFunctionFields = new ArrayList<>();
> ```

(some probable conflicts with the change to use interface instead of implementation)

---

*[uitest/src/main/java/com/vaadin/tests/components/composite/CompositeChainUI.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv6722acNkT97fKkiw8:-Kv6722acNkT97fKkiw9:bg887ve) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/uitest/src/main/java/com/vaadin/tests/components/composite/CompositeChainUI.java#L83)):*
> ```Java
>         if (component instanceof HasComponents) {
> 
>             for (Component content : (HasComponents) component) {
> ```

Like in my other comment, this is just finding the first sub-component in component, and I think a comment about that would be in order (regardless of which solution is used) as this is not so obvious on the first glance. Code is read a lot more than it is written, and often without the full context at first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100#-:-Kv67_8LT5wf4yN7WboO:b2gr098)*

**Comment by asashour** [comment]
Review status: 22 of 50 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv63dIcXaYUzu2nTiR7:-Kv6Dcpuzc9Fz1aqWDt7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cb91ab76eecbf85ad598fc5054fa2ec5ab3308f6/client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java#L61)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this will probably conflict with the change to use interfaces instead of implementations)
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv6DzJ_TF2dhE5Nwg_C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This is just finding the first widget in this, if any, and I don't find the enhanced for loop clearer or semantically more correct than the iterator based solution. As the logic is split over multiple lines and that makes it less obvious for a reader, I think a comment here would be in order whichever solution is used.
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv64zqRqkrMoY_2r42r:-Kv6EApCeDoBwrblAl3e:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java#L121)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(some probable conflicts with the change to use interface instead of implementation)
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/composite/CompositeChainUI.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv6722acNkT97fKkiw8:-Kv6EaGkPb2on1fPEpRc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/uitest/src/main/java/com/vaadin/tests/components/composite/CompositeChainUI.java#L83)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Like in my other comment, this is just finding the first sub-component in component, and I think a comment about that would be in order (regardless of which solution is used) as this is not so obvious on the first glance. Code is read a lot more than it is written, and often without the full context at first.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r2.
Review status: 22 of 50 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by pwilkin** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv77sP2sMfPvMpr2xn5:biy9fq6) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe use stream().findFirst().orElse(null)? Probably the clearest way in Java 8 to implement "first, if any".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by asashour** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv78Yy0ktqEsfvAXsJ9:brffcsh) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, pwilkin (Piotr Wilkin) wrote…</i></summary><blockquote>

Maybe use stream().findFirst().orElse(null)? Probably the clearest way in Java 8 to implement "first, if any".
</blockquote></details>

Good idea, I will try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by asashour** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv79rjuRwVW5K1nXk-I:bjp6zbo) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Good idea, I will try.
</blockquote></details>

Not currently possible, because `HasWidgets` is not a `Collection`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by pwilkin** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv7HNP9m54h8EO6zeQr:btkeg7i) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Not currently possible, because `HasWidgets` is not a `Collection`.
</blockquote></details>

Argh :/ you can try StreamSupport.stream(spliterator(), false).findFirst().orElse(null), but don't know if "more elegant" applies any longer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by asashour** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv7Kok-AHFtUI6YP5yX:bd2y1tr) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, pwilkin (Piotr Wilkin) wrote…</i></summary><blockquote>

Argh :/ you can try StreamSupport.stream(spliterator(), false).findFirst().orElse(null), but don't know if "more elegant" applies any longer.
</blockquote></details>

Thanks for the hint, but I guess:

        Widget firstChild = StreamSupport.stream(spliterator(), false)
                .findFirst().orElse(null);
        if (firstChild instanceof Focusable) {
            ((Focusable) firstChild).setFocus(true);
        }

Is not more readable than:

        // focus the first child
        for (Widget widget : this) {
            if (widget instanceof Focusable) {
                ((Focusable) widget).setFocus(true);
            }
            break;
        }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by pwilkin** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv7kUh7dtMYWVDhC6AR:b-ruue) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Thanks for the hint, but I guess:

        Widget firstChild = StreamSupport.stream(spliterator(), false)
                .findFirst().orElse(null);
        if (firstChild instanceof Focusable) {
            ((Focusable) firstChild).setFocus(true);
        }

Is not more readable than:

        // focus the first child
        for (Widget widget : this) {
            if (widget instanceof Focusable) {
                ((Focusable) widget).setFocus(true);
            }
            break;
        }

</blockquote></details>

I beg to differ. Generally using "break" as a control mechanism should be avoided whenever possible. Creating a fake loop to iterate just over the first element is a very obfuscated way of doing just that. 

My proposed code, while not necessarily elegant, at least makes it clear from the semantic side what is going on: you pick the first element from the iterable, if any, and then operate on it if any was selected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by pwilkin** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv7l0njyf6RkWwKU-7b:biglzyp) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, pwilkin (Piotr Wilkin) wrote…</i></summary><blockquote>

I beg to differ. Generally using "break" as a control mechanism should be avoided whenever possible. Creating a fake loop to iterate just over the first element is a very obfuscated way of doing just that. 

My proposed code, while not necessarily elegant, at least makes it clear from the semantic side what is going on: you pick the first element from the iterable, if any, and then operate on it if any was selected.
</blockquote></details>

However, I have no idea if StreamSupport (and generally streams) are supported in client-side code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by asashour** [comment]
Review status: 14 of 49 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-Kv8Pdvv_6qWvVNzUUeo:b-8llp9d) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, pwilkin (Piotr Wilkin) wrote…</i></summary><blockquote>

However, I have no idea if StreamSupport (and generally streams) are supported in client-side code.
</blockquote></details>

I see your point, it has been reverted to Iterator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 24 of 50 files at r1, 12 of 19 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java, line 61 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBeiCuzCa-ZUJPqLHs:-KvBeiCuzCa-ZUJPqLHt:bm74tov) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java#L61)):*
> ```Java
>     }
> 
>     private final ArrayList<ShortcutAction> actions = new ArrayList<>();
> ```

(might need merge)

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroup.java, line 270 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBf3kefrKsB1K5v8Fd:-KvBf3kefrKsB1K5v8Fe:bebhdyv) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroup.java#L270)):*
> ```Java
>     @Override
>     public void focus() {
>         for (Widget w : panel) {
> ```

should also this use an iterator

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 7552 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBfOAKYcYlwawRrZcz:-KvBfOAKYcYlwawRrZd-:b-8k5qtb) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L7552)):*
> ```Java
>             // get the row type this way to make dd work in derived
>             // implementations
>             for (Widget w : scrollBody) {
> ```

should also this use an iterator as not really looping over all widgets but logically more like an if statement

---

*[server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerHistory.java, line 112 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvC8W_XqdPPcnt80NC_:-KvC8W_XqdPPcnt80NCa:b-u0ixb7) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerHistory.java#L112)):*
> ```Java
> 
>         // Check that the color does not already exist
>         boolean exists = false;
> ```

this, too, could be replaced with `boolean exists = colorHistory.contains(color);`

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 1027 at r2](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv6epd0IGBm0AB0th91:-Kv6epd0IGBm0AB0th92:b-iettr6) ([raw file](https://github.com/vaadin/framework/blob/0f423fb506ffd7aece4037323aa830f17aa6a4a1/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L1027)):*
> ```Java
>                     .entrySet()) {
>                 nc.items.put(entry.getKey(),
>                         new HashMap<Object, Object>(entry.getValue()));
> ```

TBC that the change from HashTable to HashMap does not break anything

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100#-:-KvC9JBJp5IgmD0Preb4:bnfp4nl)*

**Comment by hesara** [comment]
Ah, didn't notice I actually still had some comments open, though not necessarily blockers.

---

Reviewed 1 of 19 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100#-:-KvC9XJ7dI-an9NQaGJf:b-mx94f0)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java, line 61 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBeiCuzCa-ZUJPqLHs:-KvCGbNEHZwnI_iWtXrP:b-10h9bb) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/client/src/main/java/com/vaadin/client/ui/ShortcutActionHandler.java#L61)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(might need merge)
</blockquote></details>

I have issues with merge (due to `screenshots` submodule), in both command line and EGit, and I guess 'rebase' will make you review everything again.

Since github doesn't complain about conflicts, this can be automatically handled.

 I would investigate this submodule issue later.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroup.java, line 270 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBf3kefrKsB1K5v8Fd:-KvCHlIDUsAMknHiwPI2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroup.java#L270)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should also this use an iterator
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 7552 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvBfOAKYcYlwawRrZcz:-KvCHmifNDGDG3g3xsE_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L7552)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should also this use an iterator as not really looping over all widgets but logically more like an if statement
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerHistory.java, line 112 at r6](https://reviewable.io:443/reviews/vaadin/framework/10100#-KvC8W_XqdPPcnt80NC_:-KvCI6tAiMX_DKYttK6L:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d6b78432bd932ee657fecbbe3196a4e4e96c9ce8/server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerHistory.java#L112)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this, too, could be replaced with `boolean exists = colorHistory.contains(color);`
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 1027 at r2](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv6epd0IGBm0AB0th91:-KvCIa4olDJhlhJ6jRhj:blmjzdp) ([raw file](https://github.com/vaadin/framework/blob/0f423fb506ffd7aece4037323aa830f17aa6a4a1/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L1027)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC that the change from HashTable to HashMap does not break anything
</blockquote></details>

I am not following, there is no type change was done from `HashTable` to `HashMap`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 1027 at r2](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv6epd0IGBm0AB0th91:-KvCKelCWofOUTjkAFYo:b-jrdasz) ([raw file](https://github.com/vaadin/framework/blob/0f423fb506ffd7aece4037323aa830f17aa6a4a1/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L1027)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I am not following, there is no type change was done from `HashTable` to `HashMap`. 
</blockquote></details>

In the latest revision (unlike r2), there is no such change. Marking this as resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100#-:-KvCKtCrvaKBVZKmM_72:bnfp4nl)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/framework/10100#-Kv663SatCWyQdSCd2Zh:-KvCKyqCLbizPpz63KdI:bk5dsnu) ([raw file](https://github.com/vaadin/framework/blob/ef83d6146200412384465377b3d1e44f34fbc393/client/src/main/java/com/vaadin/client/widgets/ChildFocusAwareFlowPanel.java#L146)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I see your point, it has been reverted to Iterator.
</blockquote></details>

@pwilkin please mark your comment as non-blocking in Reviewable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10100)*

**Comment by pwilkin** [comment]
Done.

**Pull request merged**
