### PR TITLE
Fixing upload handler error handling

### PR DESCRIPTION
**Pull request by TatuLund**
For some reason stream variable cleanup did not use UI.getCurrent(), despite current UI was set earlier in handleRequest, what I see specifically for this purpose. So I chanted this. This will address also issue #7289

Furthermore there was TODO in handle request about error handling. I interpreted this to refer to possible corner case, that UI is not found via session. In this case it is more appropriate throw IOException with clearer note and abort, than let NPE happen (ref. https://stackoverflow.com/questions/56653755/npe-while-using-multiplefileupload ) .

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)

### CODE REVIEW

**Comment by TatuLund** [comment]
Probably fixes https://github.com/vaadin/framework/issues/7512 too

**Comment by TatuLund** [comment]
And https://github.com/vaadin/framework/issues/7504

**Comment by ZheSun88** [comment]
One extra question: have you verified the two tickets mentioned in your comments?

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ZheSun88)

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)* status: all files reviewed, 1 unresolved discussion (waiting on @TatuLund)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11630#-LiDFBAA0s5bVVciXhlD:-LiDFBAA0s5bVVciXhlE:b-sopkyo) (no related file):*
> One extra question: have you verified the two tickets mentioned in your comments?

---

**Review by TatuLund — COMMENTED** [review]
Yes

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630#-:-LiDFrpj5b0yaVH8E1em:b2nhswy)* status: all files reviewed, 1 unresolved discussion (waiting on @TatuLund)

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11630#-LiDFBAA0s5bVVciXhlD:-LiDFwIpEv2YnOG1qCuH:b-896fix) (no related file):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

> One extra question: have you verified the two tickets mentioned in your comments?
</blockquote></details>

Done.

---

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11630)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
