### PR TITLE
Support using multiple @JavaScript and @StyleSheet annotations on a class

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8293)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/8293#-Kb9mzAaAVrCpLwOv4v0:-Kb9mzAaAVrCpLwOv4v1:bcozep5) ([raw file](https://github.com/vaadin/framework/blob/8df63ba98ff8b7e62abb0ad188b1e0f06c190752/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java#L28)):*
> style sheet

JavaScript?

---

*[uitest/src/main/java/com/vaadin/tests/components/javascriptcomponent/JavaScriptPreloading.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/8293#-Kb9n5pUKwXJB9YJE1iM:-Kb9n5pUKwXJB9YJE1iN:b-9bpsfh) ([raw file](https://github.com/vaadin/framework/blob/cb264dacfe74cba1266b54df8ce8c6ded1510004/uitest/src/main/java/com/vaadin/tests/components/javascriptcomponent/JavaScriptPreloading.java#L31)):*
> ```Java
>     }
> 
>     @JavaScript({ "js_label.js", "wholly_different.js" })
> ```

No corresponding test for StyleSheet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Comment by Artur-** [comment]
Review status: 0 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/8293#-Kb9mzAaAVrCpLwOv4v0:-KbA3RQ0quq_ibJYT778:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8df63ba98ff8b7e62abb0ad188b1e0f06c190752/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> style sheet

JavaScript?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/javascriptcomponent/JavaScriptPreloading.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/8293#-Kb9n5pUKwXJB9YJE1iM:-KbA6YyijM4NvsengZFv:b-8b11j9) ([raw file](https://github.com/vaadin/framework/blob/cb264dacfe74cba1266b54df8ce8c6ded1510004/uitest/src/main/java/com/vaadin/tests/components/javascriptcomponent/JavaScriptPreloading.java#L31)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

No corresponding test for StyleSheet?
</blockquote></details>

Added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Comment by Artur-** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8293#-KbA_y5MhiXBVCrGznTs:-KbA_y5MhiXBVCrGznTt:bbv29ui) (no related file):*
Waiting for #8291 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Comment by ahie** [comment]
Reviewed 6 of 12 files at r1, 8 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8293#-KbA_y5MhiXBVCrGznTs:-KbF7Oy_fkN97ELof715:bi28129) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Waiting for #8291 
</blockquote></details>

Assuming that the refactorings done for `BootstrapHandler` and `UidlWriter` in #8301 will be applied on top of this, :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8293#-KbA_y5MhiXBVCrGznTs:-KbFHCzkMtt04N0ae796:b38rh3w) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Assuming that the refactorings done for `BootstrapHandler` and `UidlWriter` in #8301 will be applied on top of this, :lgtm:
</blockquote></details>

Yes, after some additional changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8293#-KbA_y5MhiXBVCrGznTs:-KbFgQtqyiZUCDVkL_Pe:b-6gk8b7) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Yes, after some additional changes
</blockquote></details>

Why is this a blocker?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8293)*

**Pull request merged**
