### PR TITLE
Make HierarchicalDataCommunicator reset when encountering changes

### PR DESCRIPTION
**Pull request by ahie**
Additionally this patch fixes an issue with client
and server caches getting out of sync during resets.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9275)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 907 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlHDSMEcDMT_2qw5ju:-KjlHDSMEcDMT_2qw5jv:bg2hw21) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L907)):*
> ```Java
>     protected void resetDataAndSize(int newSize) {
>         size = newSize;
>         indexToRowMap.clear();
> ```

(Invalidates selection etc. but I guess we cannot do much better here.) Not calling onDropFromCache anymore, should it?

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlGQO0RbC2FDeJ1nT8:-KjlGQO0RbC2FDeJ1nT9:b-scy4ur) ([raw file](https://github.com/vaadin/framework/blob/87e7887bc02f1e4c7cddbb981d3b042d83e7c41e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L382)):*
> ```Java
>         getClientRpc().removeRows(collapsedRowIndex + 1,
>                 collapsedSubTreeSize);
>         // FIXME seems like a slight overkill to do this just for refreshing
> ```

is this comment no longer valid?

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 425 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlGZFhNaCgZKibeBGg:-KjlGZFhNaCgZKibeBGh:bsgq6xf) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L425)):*
> ```Java
>         int expandedNodeSize = doSizeQuery(expandedItem);
>         if (expandedNodeSize == 0) {
>             reset();
> ```

(I guess for some applications this might be quite drastic and requires accurate size queries for the children of all shown nodes, hard to say how strong an impact this might have on different applications. Nevertheless, probably better than before.)

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl4seRCGs0hEhQHC58:-Kjl4seRCGs0hEhQHC59:benq5d2) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java#L99)):*
> ```Java
>             HierarchicalQuery<T, SerializablePredicate<T>> query) {
>         if (!hierarchyData.contains(query.getParent())) {
>             throw new IllegalArgumentException("The queried item "
> ```

Do these exceptions (here and above) end up somewhere where the application can catch them, or just where the framework internally calls these methods? On the other hand, should it be possible in the in-memory case without concurrent modifications? Or is this always and only a programmer error?

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl5AC6Tnw5YGzS6b0M:-Kjl5AC6Tnw5YGzS6b0N:bnbf6n8) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java#L29)):*
> ```Java
>         @Override
>         public boolean hasChildren(String item) {
>             if (!hierarchyData.contains(item)) {
> ```

see comment above - needing to override these to return false rather than throwing an exception seems to suggest catching the exceptions is problematic

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl8cRttOHCYbPiRX9K:-Kjl8cRttOHCYbPiRX9L:be8ov9f) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java#L57)):*
> ```Java
>         // Item removed from hierarchy. when encountering less children than
>         // expected, should reset:
>         grid.expandWithClick(0);
> ```

everything collapsed and selection lost on reset?

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl8EtXw1gWIcCy8_eF:-Kjl8EtXw1gWIcCy8_eG:bc066g1) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java#L96)):*
> ```Java
>         grid.collapseWithClick(1);
>         // reset should get triggered here
>         grid.expandWithClick(1);
> ```

collapsing everything on reset? resetting selection?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9275)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 907 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlHDSMEcDMT_2qw5ju:-KjlQDii1WwtWUXSuhNK:b-x9yrxf) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L907)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Invalidates selection etc. but I guess we cannot do much better here.) Not calling onDropFromCache anymore, should it?
</blockquote></details>

`dropFromCache`, `onDropFromCache` is used to inform the server of invalidated data, since a reset originates from the server there should be no need for that.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlGQO0RbC2FDeJ1nT8:-KjlQfPNRKzJMbHai49y:btpiyq6) ([raw file](https://github.com/vaadin/framework/blob/87e7887bc02f1e4c7cddbb981d3b042d83e7c41e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L382)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this comment no longer valid?
</blockquote></details>

Adding these comments back. 

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 425 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlGZFhNaCgZKibeBGg:-KjlMwPj4nKxSMSohrgp:b-rc7715) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L425)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I guess for some applications this might be quite drastic and requires accurate size queries for the children of all shown nodes, hard to say how strong an impact this might have on different applications. Nevertheless, probably better than before.)
</blockquote></details>

A full reset is done here to be consistent with other cases where the expected data differs from the actual data.

---

*[server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl4seRCGs0hEhQHC58:-KjlLzDCsLwPD-Cm-NhX:b-aigltc) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/server/src/main/java/com/vaadin/data/provider/InMemoryHierarchicalDataProvider.java#L99)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Do these exceptions (here and above) end up somewhere where the application can catch them, or just where the framework internally calls these methods? On the other hand, should it be possible in the in-memory case without concurrent modifications? Or is this always and only a programmer error?
</blockquote></details>

`InMemoryHierarchicalDataProvider` could be set up to listen to changes in `HierarchyData` and call `refreshAll` automatically, but since `ListDataProvider` does not automatically refresh on changes neither should its hierarchical equivalent in my opinion.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl5AC6Tnw5YGzS6b0M:-KjlKOESj8Z-plQuEBZJ:bkwepgn) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchy.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment above - needing to override these to return false rather than throwing an exception seems to suggest catching the exceptions is problematic
</blockquote></details>

These are overridden to not throw to test how `HierarchicalDataCommunicator` handles unexpected return values. Simulates a custom `HierarchicalDataProvider` that makes these assumptions.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl8cRttOHCYbPiRX9K:-KjlL03w1iECDKt3VJHh:bb77ufg) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java#L57)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

everything collapsed and selection lost on reset?
</blockquote></details>

Yes.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-Kjl8EtXw1gWIcCy8_eF:-KjlLpICuztBXXXmsf5S:bb77ufg) ([raw file](https://github.com/vaadin/framework/blob/e885f02234e984311516124dd694262edc30013e/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridChangingHierarchyTest.java#L96)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

collapsing everything on reset? resetting selection?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9275)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/9275#-KjlGQO0RbC2FDeJ1nT8:-KjmRl-1zCWz5lNA6dqq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/87e7887bc02f1e4c7cddbb981d3b042d83e7c41e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L382)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Adding these comments back. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9275)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9275)*

**Pull request merged**
