### PR TITLE
Include Framework Element API for TestBench in the project

### PR DESCRIPTION
**Pull request by Artur-**
This makes it possible to use the latest Element classes in the
framework tests and to simplify the build process.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8014)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 81 of 81 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5tENp9931LM6Dtte0:-KZ5tENp9931LM6Dtte1:b-wg5gdv) (no related file):*
It's up to you to decide what you would like to fix.
Nothing major.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSelectElement.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5puQj4WKIyzcoOarU:-KZ5puQkJFs_XQiLjH8p:b-ifrcp1) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSelectElement.java#L28)):*
> ```Java
>      */
>     @Override
>     public void clear() {
> ```

Should this throw an exception then instead of delegating to super ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/AccordionElement.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5qKSorl2tzu0BinVD:-KZ5qKSorl2tzu0BinVE:bm5d6tb) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/AccordionElement.java#L28)):*
> ```Java
>         // Only difference in using Accordion vs. TabSheet is CSS class name for
>         // items
>         byTabCell = By.className("v-accordion-item");
> ```

I would avoid this kind of "magic".

If it's possible:
- Two CTORs in `TabSheetElement`: default one and accepting this `byTabCell` as a parameter.
- private final `byTabCell` in  `TabSheetElement`.
- default CTOR here which just calls non-default ctor of  `TabSheetElement`.

Up to you do it if it's feasible. 

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CalendarElement.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5qx708ACUavleYkHa:-KZ5qx71HsE5sEYT2vx6:b-caske6) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/CalendarElement.java#L27)):*
> ```Java
> @ServerClass("com.vaadin.ui.Calendar")
> @Deprecated
> public class CalendarElement extends AbstractComponentElement {
> ```

Not sure : should it contain any javadoc `@deprecated` about reason why ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ListSelectElement.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5rjZF5O2-ofaW8g2k:-KZ5rjZGzIcEjYS6ZxE1:b-u328n4) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/ListSelectElement.java#L93)):*
> ```Java
>      */
>     @Override
>     public void clear() {
> ```

Throw ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/NativeSelectElement.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5rqyDMjCnGizaA-EO:-KZ5rqyDMjCnGizaA-EP:b-u328n4) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/NativeSelectElement.java#L53)):*
> ```Java
>      */
>     @Override
>     public void clear() {
> ```

Throw ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5rxrHYYpAsCvZfaYY:-KZ5rxrHYYpAsCvZfaYZ:b-e6fgyx) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L29)):*
> ```Java
> @ServerClass("com.vaadin.ui.OptionGroup")
> @Deprecated
> public class OptionGroupElement extends AbstractSelectElement {
> ```

Anything about why it's deprecated ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5s0h32-dIxOafXuYe:-KZ5s0h32-dIxOafXuYf:b-u328n4) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java#L92)):*
> ```Java
>      */
>     @Override
>     public void clear() {
> ```

Throw ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/PopupDateFieldElement.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5s73hgTNOVI7-AIJ3:-KZ5s73hgTNOVI7-AIJ4:b8zwny0) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/PopupDateFieldElement.java#L21)):*
> ```Java
> 
> @ServerClass("com.vaadin.ui.PopupDateField")
> @Deprecated
> ```

javadoc why ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ProgressIndicatorElement.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sEOXH8r1fqXx8QkO:-KZ5sEOXH8r1fqXx8QkP:b38854j) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/ProgressIndicatorElement.java#L21)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/SelectElement.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sJK1QNBS-eHprXCo:-KZ5sJK1QNBS-eHprXCp:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/SelectElement.java#L21)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sNnCaXMMbbKhc0Wu:-KZ5sNnCaXMMbbKhc0Wv:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L30)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableHeaderElement.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sTB9W1CmVhQMIL1H:-KZ5sTB9W1CmVhQMIL1I:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TableHeaderElement.java#L21)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableRowElement.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sWkBaoFz-au56n64:-KZ5sWkBaoFz-au56n65:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TableRowElement.java#L26)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TabSheetElement.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sbwjsnuELSwRSu_U:-KZ5sbwjsnuELSwRSu_V:bexp1on) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TabSheetElement.java#L35)):*
> ```Java
>     // a locator that does not lead to selecting tabs from a contained inner
>     // TabSheet (#13735)
>     protected org.openqa.selenium.By byTabCell = By
> ```

private final and non-default CTOR ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TreeElement.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sklat2r4SFudA1uW:-KZ5sklat2r4SFudA1uX:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TreeElement.java#L26)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableElement.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5snymsshzRoSD8pVs:-KZ5snymsshzRoSD8pVt:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableElement.java#L22)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableRowElement.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5sqi_9AQdPeS8OgZT:-KZ5sqi_9AQdPeS8OgZU:b-y9ka2x) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableRowElement.java#L23)):*
> @Deprecated
javadoc ?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5t2POI6czx0Fye2hb:-KZ5t2POI6czx0Fye2hc:b15aa4a) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java#L25)):*
> ····
What is this ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5tENp9931LM6Dtte0:-KZ5t_kZiC8AbE7HObGf:bobs1tv) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's up to you to decide what you would like to fix.
Nothing major.
</blockquote></details>

Good comments. I will not fix anything inside the Element classes themselves in this PR as they are just moved from the TestBench project but can make another PR once this is merged and possible build etc issues are resolved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5t2POI6czx0Fye2hb:-KZ5uQ_ap0IRadPnbA5U:b-hh6ec4) ([raw file](https://github.com/vaadin/framework/blob/570523f9054d4152ee6a058d4bd7deb844f8e758/testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ····
What is this ?
</blockquote></details>

This should be fixed I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by denis-anisimov** [comment]
Reviewed 18 of 19 files at r2.
Review status: 80 of 81 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 19 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5zTCi4yz_fAGCijIg:-KZ5zTCi4yz_fAGCijIh:blnnpd5) (no related file):*
To do final review and merge after 8.0.0.beta1 and final approval.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014)*

**Comment by hesara** [comment]
:lgtm: - will merge this and then address any remaining issues later in separate PRs if necessary.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8014#-KZ5zTCi4yz_fAGCijIg:-KZ_bq20cL8Ca4DwQqqn:b-amfjp2) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

To do final review and merge after 8.0.0.beta1 and final approval.
</blockquote></details>

Looks ok to merge - I'll update build configurations etc. after merging this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8014#-:-KZ_bzVnolUHyfhZ0KBr:b-er6yvn)*

**Pull request merged**
