### PR TITLE
Add maven based server tests for Wildfly 10 and Jetty 9

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch refactors parts of the generic integration test mess
into two dependencies and individual modules for different servers.

There is now a commmon approach for making configurations for the
remaining server tests still executed through an Ant build script.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10116)

### CODE REVIEW

**Comment by hesara** [comment]
This patch breaks the history of many fixes by making copies of them rather than moving them and then depending on one more Maven artifact on the Ant side. If that is not a problem, the reviewed parts look mostly ok to me - some of the Java files I assume were copied and didn't review in detail.

Some cleanup can probably be done once most of the servers have been converted.

---

Reviewed 33 of 34 files at r1.
Review status: 33 of 34 files reviewed at latest revision, 14 unresolved discussions.

---

*[test/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLJGYBnm1W2oCAKXHi:-KvLJGYBnm1W2oCAKXHj:b-knbqco) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L25)):*
> ```XML
>         <sonar.skip>true</sonar.skip>
> 
>         
> ```

(this parameter and its comment are not 100% clear to me just from this)

---

*[test/pom.xml, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLJSeZHlcER5rBwrm_:-KvLJSeZHlcER5rBwrma:bdoodv9) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L123)):*
> ```XML
>         <module>servlet-containers/karaf</module>
> 
> 	
> ```

tabs here and below

---

*[test/pom.xml, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLRsT_8YHplSmqbvrD:-KvLRsT_8YHplSmqbvrE:b-wsdyas) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L175)):*
> ```XML
>                     <version>2.5.1</version>
>                     <configuration>
>                         <skip>${install.skip}</skip>
> ```

overridden in other modules?

---

*[test/pom.xml, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLRfBgEdHJH6o7WpPj:-KvLRfBgEdHJH6o7WpPk:b6eu3bg) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L258)):*
> ```XML
>                     <systemPropertyVariables>
>                         <phantomjs.binary.path>${phantomjs.binary}</phantomjs.binary.path>
>                         <server-name>${server.name}</server-name>
> ```

is this resolved late enough?

---

*[test/pom.xml, line 263 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLK-qKZUbTcw1m6k4Q:-KvLK-qKZUbTcw1m6k4R:b-luhz2d) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L263)):*
> ```XML
>                     </systemPropertyVariables>
>                     
>                     <testFailureIgnore>true</testFailureIgnore>
> ```

I'm not sure if this is the best way to handle this, though not sure exactly how this will affect things.

---

*[test/servlet-containers/generic-tests/pom.xml, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLQV4Wea73iQJCHHlU:-KvLQV4Wea73iQJCHHlV:b-ulbngr) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-tests/pom.xml#L39)):*
> ```XML
> 
>         <plugins>
>             
> ```

TODO comment?

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLMFTZFWo9itrOl4ua:-KvLMFTZFWo9itrOl4ub:b-ermup4) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L140)):*
> ```Java
> 
>     protected String getContextPath() {
>         return "/demo";
> ```

I know this was just copied here, but is "/demo" really the best context path?

---

*[test/servlet-containers/generic-ui/pom.xml, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLO6LDU7jIMY2DXrST:-KvLO6LDU7jIMY2DXrSU:b-9arbja) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-ui/pom.xml#L23)):*
> ```XML
>         <dependency>
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-compatibility-server</artifactId>
> ```

does this module need anything from the compatibility side anymore?

---

*[test/servlet-containers/generic-ui/src/main/java/com/vaadin/tests/integration/ServletIntegrationUI.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLOFPqkgl_AG4N1V-1:-KvLOFPqkgl_AG4N1V-2:b-inzhl) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-ui/src/main/java/com/vaadin/tests/integration/ServletIntegrationUI.java#L49)):*
> ```Java
> 
>         final Grid<Country> grid = new Grid<>();
>         // TODO ImageRenderer does not support ClassResource
> ```

is this still true

---

*[test/servlet-containers/jetty9/pom.xml, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLQH0Lo18s0yXi4LSR:-KvLQH0Lo18s0yXi4LSS:b-unpzjf) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/jetty9/pom.xml#L60)):*
> ```XML
>             <plugin>
>                 <groupId>org.eclipse.jetty</groupId>
>                 <artifactId>jetty-maven-plugin</artifactId>
> ```

As this is supposed to test one particular Jetty version, I think it would make more sense to have the version explicit here (even if based on an inherited property with "9" in the name) rather than inherited.

---

*[test/servlet-containers/wildfly10/pom.xml, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPBOBvEJLPoflJVrM:-KvLPBOBvEJLPoflJVrN:b-4pax58) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L11)):*
> ```XML
>         <relativePath>../..</relativePath>
>     </parent>
>     <artifactId>vaadin-test-widfly10-server</artifactId>
> ```

widfly -> wildfly

---

*[test/servlet-containers/wildfly10/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPEQ_BqpwgwHHaoUP:-KvLPEQ_BqpwgwHHaoUQ:blia5t2) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L12)):*
> ```XML
>     </parent>
>     <artifactId>vaadin-test-widfly10-server</artifactId>
>     <name>Vaadin Widlfly 10 Test</name>
> ```

Widlfly -> Wildfly

---

*[test/servlet-containers/wildfly10/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPd05n-H9RuNm1WqG:-KvLPd05n-H9RuNm1WqH:b7u2pwl) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L20)):*
> ```XML
> 
>     <dependencies>
>         
> ```

(not really getting the WAR but just its contents that this module packages as a WAR)

---

*[test/servlet-containers/wildfly10/pom.xml, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPqAmvWxEpnOzZad0:-KvLPqAmvWxEpnOzZad1:b-cvc4rm) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L71)):*
> ```XML
>                         </goals>
>                         <configuration>
>                             <name>demo.war</name>
> ```

(I assume this causes the correct context path to be used for this module.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116#-:-KvLOrybetM5aQa_Rf5_:brv6o4f)*

**Comment by hesara** [comment]
Reviewed 24 of 25 files at r3, 22 of 24 files at r5, 1 of 1 files at r6.
Review status: 26 of 33 files reviewed at latest revision, 15 unresolved discussions.

---

*[test/servlet-containers/generic/ivy.xml, line 120 at r6](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvWk3Wq8sNHaqReRdNh:-KvWk3Wq8sNHaqReRdNi:b-psbn00) ([raw file](https://github.com/vaadin/framework/blob/883819c8d6cead6d2a4a36327670dd7828182a24/test/servlet-containers/generic/ivy.xml#L120)):*
> ```XML
>             rev="${vaadin.version}" conf="build-provided -> default" />
>         <dependency org="com.vaadin" name="vaadin-test-server-tests"
>             rev="8.2-SNAPSHOT" conf="build-provided -> default" />
> ```

Are the new modules listed for the correct resolver in ivysettings.xml ?

---

*[test/servlet-containers/generic-ui/src/main/resources/com/vaadin/tests/integration/se.gif, line 0 at r2](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvWjl6xSYEIscoZAkY4:-KvWjl6xSYEIscoZAkY5:bfh5ax9) ([raw file](https://github.com/vaadin/framework/blob/9c2fd024bccfb7810cc32f025039aa4e52b579e0/test/servlet-containers/generic-ui/src/main/resources/com/vaadin/tests/integration/se.gif#L0)):*
Static resources deleted? Is there another copy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by tsuoanttila** [comment]
*[test/servlet-containers/generic-ui/src/main/resources/com/vaadin/tests/integration/se.gif, line  at r2](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvWjl6xSYEIscoZAkY4:-KvWmgeVe5ZXBM-EICjE:boj4zn4) ([raw file](https://github.com/vaadin/framework/blob/9c2fd024bccfb7810cc32f025039aa4e52b579e0/test/servlet-containers/generic-ui/src/main/resources/com/vaadin/tests/integration/se.gif#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Static resources deleted? Is there another copy?
</blockquote></details>

Forgot to move them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by tsuoanttila** [comment]
Review status: 26 of 36 files reviewed at latest revision, 16 unresolved discussions.

---

*[test/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLJGYBnm1W2oCAKXHi:-KvWmkuVKuzSAXFxU4XA:b-1fdaiw) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this parameter and its comment are not 100% clear to me just from this)
</blockquote></details>

Needs documentation in README on how to use it instead of extensive comment in pom.xml.

---

*[test/pom.xml, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLJSeZHlcER5rBwrm_:-KvWic_XONzZJyzoIbhF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L123)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

tabs here and below
</blockquote></details>

Done.

---

*[test/pom.xml, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLRsT_8YHplSmqbvrD:-KvWfMODsc-ALkhd3Ilt:blmqrra) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L175)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

overridden in other modules?
</blockquote></details>

Overridable from command line. This makes it possible to test an individual package manually by installing the dependencies one by one with `-Dinstall.skip=false`. Need to write instructions before merge.

---

*[test/pom.xml, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLRfBgEdHJH6o7WpPj:-KvWfY7MiTgiFfOYxPEM:bb77ufg) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L258)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this resolved late enough?
</blockquote></details>

Yes.

---

*[test/pom.xml, line 263 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLK-qKZUbTcw1m6k4Q:-KvWf_h9_842PyFBIny1:b7kxd01) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L263)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm not sure if this is the best way to handle this, though not sure exactly how this will affect things.
</blockquote></details>

Test failures will be reported by failsafe as normal and teamcity should pick them up. This is to get results from all the servers even if some of them fail.

Most of this failsafe block should be moved to a different pom file though.

---

*[test/servlet-containers/generic/ivy.xml, line 120 at r6](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvWk3Wq8sNHaqReRdNh:-KvWmuhNMfxevfLE2VzO:b-nlnk18) ([raw file](https://github.com/vaadin/framework/blob/883819c8d6cead6d2a4a36327670dd7828182a24/test/servlet-containers/generic/ivy.xml#L120)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Are the new modules listed for the correct resolver in ivysettings.xml ?
</blockquote></details>

Need to check. Alternative approach would be to extract the test files from the jar to the location where they used to be. That might be easier and safer since these dependencies are not installed to local maven.

---

*[test/servlet-containers/generic-tests/pom.xml, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLQV4Wea73iQJCHHlU:-KvWigebHOp5wllpuWRU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-tests/pom.xml#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TODO comment?
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLMFTZFWo9itrOl4ua:-KvWgEdRJRJfH4cPnsYq:bqc8pv) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L140)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I know this was just copied here, but is "/demo" really the best context path?
</blockquote></details>

Definitely not, but that has been used in the Ant builds, not sure how to safely change before we have gotten rid of the ant thingie.

---

*[test/servlet-containers/generic-ui/pom.xml, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLO6LDU7jIMY2DXrST:-KvWiiZ0cmqqUxSwxiem:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-ui/pom.xml#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

does this module need anything from the compatibility side anymore?
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-ui/src/main/java/com/vaadin/tests/integration/ServletIntegrationUI.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLOFPqkgl_AG4N1V-1:-KvWmMXmykm4IHC9LgDm:bgtr0bo) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/generic-ui/src/main/java/com/vaadin/tests/integration/ServletIntegrationUI.java#L49)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this still true
</blockquote></details>

I don't remember if we have done anything to that.

---

*[test/servlet-containers/jetty9/pom.xml, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLQH0Lo18s0yXi4LSR:-KvWjNNPXe7vNX2wrFTD:ba02vb5) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/jetty9/pom.xml#L60)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

As this is supposed to test one particular Jetty version, I think it would make more sense to have the version explicit here (even if based on an inherited property with "9" in the name) rather than inherited.
</blockquote></details>

This should be done so that the plugin configuration should be shared through a parent pom.xml to all tested jetty versions with predefined properties for version numbers, and the configuration in an individual test would be just enabling the correct plugins and setting the version number.

---

*[test/servlet-containers/wildfly10/pom.xml, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPBOBvEJLPoflJVrM:-KvWj1x2ltkBUiOgEVJ0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L11)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

widfly -> wildfly
</blockquote></details>

Done.

---

*[test/servlet-containers/wildfly10/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPEQ_BqpwgwHHaoUP:-KvWj3f4PrTFfEVjbtSm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L12)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Widlfly -> Wildfly
</blockquote></details>

Done.

---

*[test/servlet-containers/wildfly10/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPd05n-H9RuNm1WqG:-KvWjJS5QfARRTHtj24c:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not really getting the WAR but just its contents that this module packages as a WAR)
</blockquote></details>

Done.

---

*[test/servlet-containers/wildfly10/pom.xml, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLPqAmvWxEpnOzZad0:-KvWjItkVNnCnOLlODA6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/wildfly10/pom.xml#L71)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I assume this causes the correct context path to be used for this module.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
Reviewed 1 of 24 files at r5, 6 of 6 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
Review status: 29 of 42 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/servlet-containers/pom.xml, line 18 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-Kv_xpEo7SQ3ZFoNBNOY:-Kv_xpEo7SQ3ZFoNBNOZ:b-g1kqjy) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/pom.xml#L18)):*
> ```XML
>         <module>generic-tests</module>
>     </modules>
>     
> ```

extra whitespace

---

*[test/servlet-containers/pom.xml, line 90 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-Kv_xKdt-qoL8F0f012d:-Kv_xKdt-qoL8F0f012e:by31e51) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/pom.xml#L90)):*
> ```XML
>                 <activeByDefault>true</activeByDefault>
>             </activation>
>             <modules>
> ```

Should these profiles also include generic-ui and generic-tests or not?

---

*[test/servlet-containers/generic/pom.xml, line 54 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-Kv_xZpns0plmObt9J_c:-Kv_xZpns0plmObt9J_d:b-g1kqjy) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/generic/pom.xml#L54)):*
> ```XML
>                 </executions>
>             </plugin>
>         
> ```

extra whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
Reviewed 7 of 12 files at r9, 2 of 3 files at r11, 1 of 2 files at r12, 1 of 1 files at r13.
Review status: 40 of 42 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[test/servlet-containers/jetty9/pom.xml, line 15 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaGcx6iEQ8Huvmee4G:-KvaGcx6iEQ8Huvmee4H:bhsi4me) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/jetty9/pom.xml#L15)):*
> ```XML
>     <properties>
>         <jetty.skip>false</jetty.skip>
>         
> ```

Anyway, could make it explicit here so that the jetty9 test does not change if we change what is used for tests that do not care about Jetty version in the parent POM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by tsuoanttila** [comment]
Review status: 40 of 42 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[test/servlet-containers/pom.xml, line 18 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-Kv_xpEo7SQ3ZFoNBNOY:-KvaKlWhRiY90-uUXqN1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/pom.xml#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.

---

*[test/servlet-containers/generic/pom.xml, line 54 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-Kv_xZpns0plmObt9J_c:-KvaKuUq_68651F_mN3K:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/generic/pom.xml#L54)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.

---

*[test/servlet-containers/jetty9/pom.xml, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLQH0Lo18s0yXi4LSR:-KvaP1zub6dqC0XAZhJd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/servlet-containers/jetty9/pom.xml#L60)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This should be done so that the plugin configuration should be shared through a parent pom.xml to all tested jetty versions with predefined properties for version numbers, and the configuration in an individual test would be just enabling the correct plugins and setting the version number.
</blockquote></details>

Done.

---

*[test/servlet-containers/jetty9/pom.xml, line 15 at r13](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaGcx6iEQ8Huvmee4G:-KvaOuVCEjcK8ZBMWxWa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/633584277067b9d05cd60773374eb41f7ac16c0c/test/servlet-containers/jetty9/pom.xml#L15)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Anyway, could make it explicit here so that the jetty9 test does not change if we change what is used for tests that do not care about Jetty version in the parent POM.
</blockquote></details>

Done.

---

*[test/servlet-containers/generic/ivy.xml, line 120 at r6](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvWk3Wq8sNHaqReRdNh:-KvaP1a6CShP6lBOaRlM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/883819c8d6cead6d2a4a36327670dd7828182a24/test/servlet-containers/generic/ivy.xml#L120)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Need to check. Alternative approach would be to extract the test files from the jar to the location where they used to be. That might be easier and safer since these dependencies are not installed to local maven.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
Reviewed 1 of 12 files at r9, 1 of 2 files at r10, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvLJGYBnm1W2oCAKXHi:-KvaQPPwdhsVTwSGy4GC:boig7lt) ([raw file](https://github.com/vaadin/framework/blob/091eeccbac216b3338af8e7d629a8de2f054fa57/test/pom.xml#L25)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Needs documentation in README on how to use it instead of extensive comment in pom.xml.
</blockquote></details>

readme still missing

---

*[test/servlet-containers/jetty9/pom.xml, line 15 at r14](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaPbyTpkWG6jEVtOHg:-KvaPbyTpkWG6jEVtOHh:b-h4fkn2) ([raw file](https://github.com/vaadin/framework/blob/d509469dc500c97f4f401fe3736b72a6c373db6e/test/servlet-containers/jetty9/pom.xml#L15)):*
> ```XML
>     <properties>
>         <jetty.skip>false</jetty.skip>
> 	<jetty.version>9.3.21.v20170918</jetty.version>
> ```

tab to spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/README.md, line 9 at r15](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaS4qE2ZHvgEyp61EK:-KvaS4qE2ZHvgEyp61EL:bzif22s) ([raw file](https://github.com/vaadin/framework/blob/f011d6b2a216d5b86a5b3b70afb8db5aae4e60fd/test/README.md#L9)):*
> ```Markdown
> To validate a given Vaadin Version, run `mvn clean verify -Dvaadin.version=VERSIONNUMBER`.
> 
> ## Server testing 
> ```

(trailing space)

---

*[test/README.md, line 17 at r15](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaRoNThtc6cJiC1gHI:-KvaRoNThtc6cJiC1gHJ:b-srw00c) ([raw file](https://github.com/vaadin/framework/blob/f011d6b2a216d5b86a5b3b70afb8db5aae4e60fd/test/README.md#L17)):*
> ```Markdown
> ## Running an individual test locally
> 
> To install dependencies for testing an individual module locally, run `mvn clean install -Dintall.skip=false` in the dependency module.
> ```

"install.skip"; what does "dependency module" mean here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by tsuoanttila** [comment]
Review status: 41 of 43 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/README.md, line 9 at r15](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaS4qE2ZHvgEyp61EK:-KvaUJ0JF9O7liEb7_2Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f011d6b2a216d5b86a5b3b70afb8db5aae4e60fd/test/README.md#L9)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(trailing space)
</blockquote></details>

Done.

---

*[test/README.md, line 17 at r15](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvaRoNThtc6cJiC1gHI:-KvaUIlC-EglTbYo6u8u:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f011d6b2a216d5b86a5b3b70afb8db5aae4e60fd/test/README.md#L17)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"install.skip"; what does "dependency module" mean here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Comment by hesara** [comment]
:lgtm: as a first step

---

Reviewed 1 of 24 files at r5, 1 of 1 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116#-:-KvaUt6eLQobGFImPK5V:b-npx29y)*

**Comment by tsuoanttila** [comment]
Running a full build of this change in TeamCity, ETA 25minutes.

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 4 of 24 files at r5, 6 of 6 files at r19.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116#-:-KvbHvTU_SlvDWGUeo2i:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/pom.xml, line 58 at r14](https://reviewable.io:443/reviews/vaadin/framework/10116#-KvcQ2UBMqtsEZ0DU-qX:-KvcQ2UBMqtsEZ0DU-qY:b-23ontw) ([raw file](https://github.com/vaadin/framework/blob/d509469dc500c97f4f401fe3736b72a6c373db6e/test/servlet-containers/pom.xml#L58)):*
> ```XML
>                 </plugin>
>             </plugins>
>         </pluginManagement>
> ```

I assume the needed plugins are activated in the sub-projects.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10116)*

**Pull request merged**
