### PR TITLE
Fixes invalid user visible value in certain cases

### LINKED ISSUE #7902: ComboBox is not refreshed when "scrollToSelectedItem" is set to false
**Originally by _lorenzo.benvenuti_**

___
Hi,

I was testing the correction of ticket https://dev.vaadin.com/ticket/19221 and I discovered another problem: when a value is set programmatically to a ComboBox with "scrollToSelectedItem" option disabled, sometimes the ComboBox is not refreshed. I guess it has something to do with the position of the item in the Container. To reproduce the issue you can use the attached UI and perform the following steps:

1. Select "Item 0" in the ComboBox
2. Write "50" in the TextField and click "Set value"
3. Write 0 in the TextField and click "Set value"

As yuo can see the "ValueChangeEvent"  is triggered, the ComboBox value is "0" but the component on the screen still displays "50".

Thank you,

lorenzo

___
 Imported from https://dev.vaadin.com/ issue #20448

### PR DESCRIPTION
**Pull request by mstahv**
closes #7902

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8115)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VFilterSelect.java, line 2608 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBJjfhIeQOJtqJSPd:-K_TBJjfhIeQOJtqJSPe:bhqy5sl) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/client/src/main/java/com/vaadin/client/ui/VFilterSelect.java#L2608)):*
> ```Java
>         explicitSelectedCaption = selectedCaption;
>         if (selectedCaption != null) {
>             selectedOptionKey = null;
> ```

Could this cause problems in the cases related to null selection (see all references to selectedOptionKey)? Not sure if there i a problem.

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBSqqbDD2moZYb8BO:-K_TBSqqbDD2moZYb8BP:biyw8o5) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java#L32)):*
> ```Java
>         s.setValue(selection);
>         addTestComponent(s);
>         
> ```

whitespace here and below not consistent with the project formatting settings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115)*

**Comment by mstahv** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VFilterSelect.java, line 2608 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBJjfhIeQOJtqJSPd:-K_U1TSrzifr6-WNanhI:b-ir5386) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/client/src/main/java/com/vaadin/client/ui/VFilterSelect.java#L2608)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could this cause problems in the cases related to null selection (see all references to selectedOptionKey)? Not sure if there i a problem.
</blockquote></details>

Can't see what problems would this cause, selectedOptionKey is not known if explicitlySelectedCaption is used. It was just (in some rare cases left to client side state -> causing the bug).

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBSqqbDD2moZYb8BO:-K_U0hP1JfjVIfVuIodX:b-8gcz8e) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java#L32)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

whitespace here and below not consistent with the project formatting settings
</blockquote></details>

Is there somewhere formatting guidelines? How should one make Eclipse do this automatically?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115)*

**Comment by mstahv** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VFilterSelect.java, line 2608 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBJjfhIeQOJtqJSPd:-K_UecwUgFPtXcdy4oQA:b-8es03f) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/client/src/main/java/com/vaadin/client/ui/VFilterSelect.java#L2608)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Can't see what problems would this cause, selectedOptionKey is not known if explicitlySelectedCaption is used. It was just (in some rare cases left to client side state -> causing the bug).
</blockquote></details>

Should I click done button here as well. This Reviewable is just so difficult...

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8115#-K_TBSqqbDD2moZYb8BO:-K_UeYbZot0IZAlJ7gbC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4575acd0db66ca1c6a7d6bcf37738bb409f18246/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxScrollingToPageDisabled.java#L32)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Is there somewhere formatting guidelines? How should one make Eclipse do this automatically?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115)*

**Comment by pleku** [comment]
Please rebase on top of 7.7, that should trigger a new validation build that should pass, the failure has been a JDK version error in built system.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115#-:-Ka6wqsM8IxY6AWkfFOU:bdec08e)*

**Comment by mstahv** [comment]
How do I do the rebase thing? Can't somebody from the core team do the rebasing?

**Comment by pleku** [comment]
Haven't tested, but something like
1. Go to your clone directory
2. switch to the PR branch
3. `git remote add framework git@github.com:vaadin/framework.git
4. `git fetch framework`
5. `git rebase framework/7.7` (or if you're PRing against master, then use that)
6. `git push --force`

https://robots.thoughtbot.com/keeping-a-github-fork-updated

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115#-:-KaCqR8uOvftdVk1N7p7:b-d8ovm5)*

**Comment by pleku** [comment]
> Go to your clone directory
> switch to the PR branch
> `git remote add framework git@github.com:vaadin/framework.git
> git fetch framework
> git rebase framework/7.7 (or if you're PRing against master, then use that)
> git push --force
> 
> https://robots.thoughtbot.com/keeping-a-github-fork-updated

If this works, it probably should be added to the contributing guide

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115#-:-KaCrjcrroASoMHvviuO:bz93atx)*

**Comment by hesara** [comment]
It is safer to use --force-with-lease instead of --force .

**Comment by mstahv** [comment]
Did this but also noticed the checkbox "Allow edits from maintainers." which is now checked. These rebases should really be so that you guys to that instead of requiring community contributors to do that.

**Comment by pleku** [comment]
For maintainers to be able to rebase, that checkbox should be checked yes. Added that instruction to the contribution guide. Then we can just click on the button in github/reviewable to update branch.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8115#-KaELiV0R8PK8n6mNRar:-KaELiV1FIspvuhvR-Of:b-2mfgyo) (no related file):*
There is no automated test for this on purpose or was it just left out ?
No new modern browser test failures for this patch, old browsers test build still running

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115#-:-KaEG8YOH9GodE6yng0x:bjrkxhh)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8115#-KaELiV0R8PK8n6mNRar:-KaLdWpkfs5XRnIAzr_J:b-elwxab) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

There is no automated test for this on purpose or was it just left out ?
No new modern browser test failures for this patch, old browsers test build still running
</blockquote></details>

There were no new related test failures for old browsers. But the question still is, was there suppose to be a test for this fix and it was accidentally left out or ? There is a test-ui updated however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115)*

**Comment by mstahv** [comment]
IIRC there was only a test-ui for this (and related issues), now selenium scritps.

**Comment by tsuoanttila** [comment]
Added a test for the one case where I could break the ComboBox before the patch. @hesara please review

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8115#-KaELiV0R8PK8n6mNRar:-KtLC1C7NBZle85k7Fqw:b-jf2vyh) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

There were no new related test failures for old browsers. But the question still is, was there suppose to be a test for this fix and it was accidentally left out or ? There is a test-ui updated however.
</blockquote></details>

test added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8115)*

**Pull request merged**
