### PR TITLE
Fix Firefox 45 tests (click issues, screenshots)

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8533)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1006 at r1](https://reviewable.io:443/reviews/vaadin/framework/8533#-KcbMkIHuiiYAKaaeZnt:-KcbMkIHuiiYAKaaeZnu:b-vrj10o) ([raw file](https://github.com/vaadin/framework/blob/97118ab4f06af5db1f25e543028b0ce1f887b4fd/uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1006)):*
> ```Java
>     }
> 
>     protected void clickElement(WebElement element) {
> ```

Is this a problem only and solely in the framework as the fix is made to a framework class and not in `ComboBoxElement`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8533)*

**Review by tsuoanttila — APPROVED** [review]
LGTM

**Comment by tsuoanttila** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1006 at r1](https://reviewable.io:443/reviews/vaadin/framework/8533#-KcbMkIHuiiYAKaaeZnt:-KcbOGqSkO87HagAzzaj:b-pa2akv) ([raw file](https://github.com/vaadin/framework/blob/97118ab4f06af5db1f25e543028b0ce1f887b4fd/uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1006)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is this a problem only and solely in the framework as the fix is made to a framework class and not in `ComboBoxElement`?
</blockquote></details>

We might want to move it to TB API part later if the Firefox does not get fixed soon by Selenium. This also affects other components than ComboBox.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8533)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1006 at r1](https://reviewable.io:443/reviews/vaadin/framework/8533#-KcbMkIHuiiYAKaaeZnt:-KcbPPfoHaVd6nTUrHCK:byualxi) ([raw file](https://github.com/vaadin/framework/blob/97118ab4f06af5db1f25e543028b0ce1f887b4fd/uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1006)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What needs to be fixed in Selenium? Is there an issue?
</blockquote></details>

apparently WebElement.click() does not work if there is something covering the element (e.g. some kind of overlay/... from Valo) - also affects any clicks for "raw" WebElements

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8533)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1006 at r1](https://reviewable.io:443/reviews/vaadin/framework/8533#-KcbMkIHuiiYAKaaeZnt:-KcbQWBjJdF2gj0QkOtF:b-1mt4y9) ([raw file](https://github.com/vaadin/framework/blob/97118ab4f06af5db1f25e543028b0ce1f887b4fd/uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1006)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

apparently WebElement.click() does not work if there is something covering the element (e.g. some kind of overlay/... from Valo) - also affects any clicks for "raw" WebElements
</blockquote></details>

I think the web driver specs say that you should not be able to click something which the user is not able to click.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8533)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1006 at r1](https://reviewable.io:443/reviews/vaadin/framework/8533#-KcbMkIHuiiYAKaaeZnt:-KcbRholjGGckbxfc002:b-op0xdj) ([raw file](https://github.com/vaadin/framework/blob/97118ab4f06af5db1f25e543028b0ce1f887b4fd/uitest-common/src/main/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1006)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

The user is able to click these, and the clicks work with all other web drivers than Firefox - also others have found this inconsistency.
</blockquote></details>

Alright, is there a Selenium issue about it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8533)*

**Pull request merged**
