### PR TITLE
JspIntegrationTest as a separate module

### PR DESCRIPTION
**Pull request by elmot**
Part of vaadin/framework8-issues#539

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8228)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 8 of 9 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH-engolTZ6ZHlCXEg:-KaH-engolTZ6ZHlCXEh:b1w6lvc) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/pom.xml#L14)):*
> ```XML
>     <name>vaadin-test-jsp-integration</name>
>     <packaging>war</packaging>
>     <properties>
> ```

almost everything in this POM is inherited from the parent and should not be specified again here - see the other submodule POMs that tend to be about 30-40 lines

---

*[test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH2Fva7O6--Anft7Jj:-KaH2Fva7O6--Anft7Jk:b-wuuh2f) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml#L6)):*
> ```XML
>     xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
> 
>     
> ```

Are some of the settings/servlets here now unnecessary in uitest or not? Probably not yet.

---

*[test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH2QoAHHDddTsSqkSH:-KaH2QoAHHDddTsSqkSI:b-npnm7l) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml#L57)):*
> ```XML
>     </servlet-mapping>
> 
>     <welcome-file-list>
> ```

probably should be removed if works without this

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH0KqFcWo9mV8g4TPi:-KaH0KqFcWo9mV8g4TPj:b-mdslo4) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L31)):*
> ```Java
> import static org.junit.Assert.assertNotEquals;
> 
> @RunLocally(Browser.PHANTOMJS)
> ```

The other test modules actually use a plain TestBenchTestCase as the superclass, and set up the driver explicitly rather than using @RunLocally. I guess that would work here as well. Not necessarily a blocker, though.

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH1wgYOBLaNBmRMikX:-KaH1wgYOBLaNBmRMikY:b-9yazpg) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L45)):*
> ```Java
>         // Open a new UI
>         getDriver().get(primaryUIUrl);
>         sleep(1000);
> ```

Are the sleeps really necessary? Any better alternative for them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by elmot** [comment]
Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH-engolTZ6ZHlCXEg:-KaHgZwG4lQauqLL71oY:b-vzgw2x) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/pom.xml#L14)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

almost everything in this POM is inherited from the parent and should not be specified again here - see the other submodule POMs that tend to be about 30-40 lines
</blockquote></details>

Parent for the project is vaadin-test, but not ui-test. 
Some cleanup is done, but there is plenty of not yet ported stuff.
 I'm gonna refactor that in following patches. 

---

*[test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH2Fva7O6--Anft7Jj:-KaHh9wGxBTgCFTir7li:by8cgan) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml#L6)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Are some of the settings/servlets here now unnecessary in uitest or not? Probably not yet.
</blockquote></details>

The only one servlet for the moment. Done.

---

*[test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH2QoAHHDddTsSqkSH:-KaHh3CBEAV_rbl_XSY5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/main/webapp/WEB-INF/web.xml#L57)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

probably should be removed if works without this
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH0KqFcWo9mV8g4TPi:-KaHh54BPGc6NBWkSgGC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L31)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

The other test modules actually use a plain TestBenchTestCase as the superclass, and set up the driver explicitly rather than using @RunLocally. I guess that would work here as well. Not necessarily a blocker, though.
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaH1wgYOBLaNBmRMikX:-KaHh6oDOiHQNNBrXdS4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/269c408882f18dadfd94e7745e27a4207f103c43/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L45)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Are the sleeps really necessary? Any better alternative for them?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaM9fqhrJa7z_UvJ3xQ:-KaM9fqj0q6KVLjU8g2u:b-dx9q21) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L21)):*
> ```XML
>         <dependency>
>             <groupId>${project.groupId}</groupId>
>             <artifactId>vaadin-server</artifactId>
> ```

Unnecessary and comes from parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 32 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaM9kFHvDJL9Bwr6w6H:-KaM9kFHvDJL9Bwr6w6I:b-dx9q21) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L32)):*
> ```XML
>         <dependency>
>             <groupId>${project.groupId}</groupId>
>             <artifactId>vaadin-themes</artifactId>
> ```

Unnecessary and comes from parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 49 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMATfFJvD-JpbdpoGO:-KaMATfFJvD-JpbdpoGP:bzdmbm8) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L49)):*
> ```XML
>         <plugins>
>             <plugin>
>                 <groupId>org.eclipse.jetty</groupId>
> ```

Jetty is configured in parent, why reconfigured here ? 
If there is something parameter that should be modified, port etc. you should add those as properties and override them for this module

---

*[test/servlet-containers/jsp-integration/pom.xml, line 80 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMAqPfSftPKNk-xBkL:-KaMAqPfSftPKNk-xBkM:b-xy5tsm) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L80)):*
> ```XML
> 
>             <plugin>
>                 <artifactId>maven-install-plugin</artifactId>
> ```

unnecessary, comes from parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 88 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDhe-cgj5MlPWv-PL:-KaMDhe-cgj5MlPWv-PM:b-ulxrgd) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L88)):*
> ```XML
>                 <artifactId>maven-deploy-plugin</artifactId>
>                 <configuration>
>                     <skip>true</skip>
> ```

why is this skipped ? because you just copied from uitest ? it is enabled in parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 92 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDnKU19yPf02V3Vo6:-KaMDnKU19yPf02V3Vo7:b-ulxrgd) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L92)):*
> ```XML
>             </plugin>
>             <plugin>
>                 <artifactId>maven-surefire-plugin</artifactId>
> ```

why is this skipped ? because you just copied from uitest ? it is enabled in parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDwaIPMkHBHqYtULA:-KaMDwaIPMkHBHqYtULB:b-ulxrgd) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L101)):*
> ```XML
>                 <artifactId>animal-sniffer-maven-plugin</artifactId>
>                 <configuration>
>                     <skip>true</skip>
> ```

why is this skipped ? because you just copied from uitest ? it is enabled in parent

---

*[test/servlet-containers/jsp-integration/pom.xml, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMBOjNFAQ5d8BGDwpy:-KaMBOjNFAQ5d8BGDwpz:bh7ekgl) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L105)):*
> ```XML
>             </plugin>
>             <plugin>
>                 <groupId>org.sonatype.plugins</groupId>
> ```

this can be now removed since it is not configured for parent, so no need to specifically skip it

---

*[test/servlet-containers/jsp-integration/pom.xml, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDbdYQhqKzyGtazQX:-KaMDbdYQhqKzyGtazQY:b-tbz8lr) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L112)):*
> ```XML
>             </plugin>
>             <plugin>
>                 <artifactId>maven-javadoc-plugin</artifactId>
> ```

unnecessary

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMEBmF9nR3alPujMi5:-KaMEBmF9nR3alPujMi6:blf2r52) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L34)):*
> ```Java
> public class JSPIntegrationIT extends TestBenchTestCase {
> 
>     private static final String URL_PREFIX = "http://localhost:7888/";
> ```

would be good if the port would read from a system parameter, rather than hardcoded here and pom.xml

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by elmot** [comment]
Review status: 6 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaM9fqhrJa7z_UvJ3xQ:-KaNSOBiojKL0l36_HQY:b5kb128) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L21)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Unnecessary and comes from parent
</blockquote></details>

Not yet. Will be refactored in next patch.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 32 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaM9kFHvDJL9Bwr6w6H:-KaNSUZIxqB4Dj8-Q-lW:b5kb128) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Unnecessary and comes from parent
</blockquote></details>

Not yet. Will be refactored in next patch.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 49 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMATfFJvD-JpbdpoGO:-KbEaaKm9WL3jBq-Pisk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L49)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Jetty is configured in parent, why reconfigured here ? 
If there is something parameter that should be modified, port etc. you should add those as properties and override them for this module
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 80 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMAqPfSftPKNk-xBkL:-KbEabH7kEcQ7NYMBoI8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L80)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

unnecessary, comes from parent
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 88 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDhe-cgj5MlPWv-PL:-KbEabw4Av9VTcs2rb5M:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L88)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

why is this skipped ? because you just copied from uitest ? it is enabled in parent
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 92 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDnKU19yPf02V3Vo6:-KbEabjFBZpz3KVTyVsi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L92)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

why is this skipped ? because you just copied from uitest ? it is enabled in parent
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDwaIPMkHBHqYtULA:-KbEacPtnE_2itwSaWLY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L101)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

why is this skipped ? because you just copied from uitest ? it is enabled in parent
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMBOjNFAQ5d8BGDwpy:-KbEackqhQiyPkIXFvcb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L105)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

this can be now removed since it is not configured for parent, so no need to specifically skip it
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/pom.xml, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMDbdYQhqKzyGtazQX:-KbEadSjmAcjoDfZ5k0M:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/pom.xml#L112)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

unnecessary
</blockquote></details>

Done.

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMEBmF9nR3alPujMi5:-KbEahirHCN7t3awEjYF:b-pfieu0) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

would be good if the port would read from a system parameter, rather than hardcoded here and pom.xml
</blockquote></details>

Might be a bit later in order to parallelize tests , but not in this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by hesara** [comment]
Reviewed 1 of 3 files at r3.
Review status: 7 of 9 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/framework/8228#-KaMEBmF9nR3alPujMi5:-KbKiGMUSzWufPzNDo6Q:b-b80m6p) ([raw file](https://github.com/vaadin/framework/blob/4cd2592540c094c788ee6afb88ca51479b4b3145/test/servlet-containers/jsp-integration/src/test/java/com/vaadin/tests/integration/JSPIntegrationIT.java#L34)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Might be a bit later in order to parallelize tests , but not in this PR
</blockquote></details>

To do later if needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Comment by hesara** [comment]
some fine-tuning can be done later

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228#-:-KbKiNPGstX37aMWZwIu:b-erx3d0)*

**Comment by ahie** [comment]
Reviewed 5 of 9 files at r1, 2 of 5 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8228)*

**Pull request merged**
