### PR TITLE
Added Note about TextField in Header cell

### LINKED ISSUE #9089: Inline icon not displayed in textfield in grid header
Using Vaadin 8.0.5, inline icons are not shown in TextFields in Grid header cells.

In the attached project, there are two TextFields, configured the same way to have an inline icon. One is added to a Grid header cell, the other to the main layout. Only the TextField in the main layout shows the icon correctly. The TextField in the grid header cell is indented like an icon should be there, but there is no icon shown.
[gridicontest.zip](https://github.com/vaadin/framework/files/923249/gridicontest.zip)

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes https://github.com/vaadin/framework/issues/9089

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11858)

### CODE REVIEW

**Comment by Ansku** [comment]
___
*[documentation/components/components-grid.asciidoc, line 727 at r1](https://reviewable.io/reviews/vaadin/framework/11858#-LxzEgaMD7EJEZvk9-WR:-LxzEgaMD7EJEZvk9-WS:bydm2pi) ([raw file](https://github.com/vaadin/framework/blob/402d4ba77118390cf94e1664cad28f5d4b951561/documentation/components/components-grid.asciidoc#L727)):*
> ```
> Note, when you use cell.setComponent(textField), the TextField will be rendered in compact mode
> without caption and icon. If you need override this behavior, you need to wrap the TextField e.g.
> into HorizontalLayout.
> ```
Both instances of TextField should be wrapped in `[classname]#TextField#`, similarly for HorizontalLayout. The method should be wrapped in `[methodname]#setComponent(textField)#`.

**Comment by Ansku** [comment]
___
*[documentation/components/components-grid.asciidoc, line 727 at r1](https://reviewable.io/reviews/vaadin/framework/11858#-LxzEgaMD7EJEZvk9-WR:-Ly4EtgH4o7mdjeDL_mh:b-i0kxxd) ([raw file](https://github.com/vaadin/framework/blob/402d4ba77118390cf94e1664cad28f5d4b951561/documentation/components/components-grid.asciidoc#L727)):*
> ```
> cell.[methodname]#setComponent(textField)#
> ```
I meant that the `cell.` could be dropped altogether, having only part of it formatted looks weird and the method is just referenced in the previous paragraph so I don't think it really needs the clarification. And now that I think about it, the `textField` should also probably be `TextField` within a methodname block. If you want to keep the full code block, perhaps `` `cell.setComponent(textField)` `` would work better than a methodname block.

I also just realised that there should probably be `====` before and after the paragraph to define the note block. As in
```
[NOTE]
====
Note, when you use...
====
```

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11858)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[documentation/components/components-grid.asciidoc, line 727 at r1](https://reviewable.io/reviews/vaadin/framework/11858#-LxzEgaMD7EJEZvk9-WR:-Ly40_hY5Rs3ylntK3Vm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/402d4ba77118390cf94e1664cad28f5d4b951561/documentation/components/components-grid.asciidoc#L727)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> Note, when you use cell.setComponent(textField), the TextField will be rendered in compact mode
> without caption and icon. If you need override this behavior, you need to wrap the TextField e.g.
> into HorizontalLayout.
> ```
Both instances of TextField should be wrapped in `[classname]#TextField#`, similarly for HorizontalLayout. The method should be wrapped in `[methodname]#setComponent(textField)#`.
</blockquote></details>

Done.

**Review by Ansku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11858)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund)

___
*[documentation/components/components-grid.asciidoc, line 727 at r3](https://reviewable.io/reviews/vaadin/framework/11858#-Ly9pCkg2dke3-azw2Ce:-Ly9pCkg2dke3-azw2Cf:b6euoco) ([raw file](https://github.com/vaadin/framework/blob/6b58fd24c07101a0b9d9a88e1466b569f9b6e88d/documentation/components/components-grid.asciidoc#L727)):*
> ```
> If you need override this behavior
> ```
need to

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11858)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[documentation/components/components-grid.asciidoc, line 727 at r3](https://reviewable.io/reviews/vaadin/framework/11858#-Ly9pCkg2dke3-azw2Ce:-LyEWnR0--GrFdUHkfeg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e3e705f9503eb33133479ecf9f4c9fe5bf625f22/documentation/components/components-grid.asciidoc#L727)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

> ```
> If you need override this behavior
> ```
need to
</blockquote></details>

Done.

**Review by Ansku — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11858#-:-LyTbvhG1c_CS_eMTv4h:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by Ansku — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11858)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
