### PR TITLE
Fix context menu missing box-shadow for Runo on Chrome

### PR DESCRIPTION
**Pull request by pleku**
For Runo theme on Chrome, background image was overlapping box-shadow for ContextMenu. Verified by `RunoThemeTest.testTheme(Windows_Chrome_40)` screenshot that has been broken.

This fix should be imported to FW 8 compatibility runo theme too.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7966)

### CODE REVIEW

**Review by jouni — COMMENTED** [review]
Code looks fine, haven’t looked at the end result. Can you add before and after screenshots to the conversation?

**Comment by pleku** [comment]
@jouni sorry forgot:
original
broken

**Comment by jouni** [comment]
I’m not following 100% what the problem is and how `background-clip: content-box;` fixes that. It just seems like box-shadow is missing, that Chrome has either problem with parsing the CSS or rendering it.

**Comment by jouni** [comment]
I don’t have any objections to merge this change if all the test pass, as I don’t see this causing any regressions.

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7966#-KYsVAHuSoADNg4GtEpB:-KYwCnImxeAs4w79FZi6:b-o6ym0k) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I'll run the browser tests for this change before merging it to verify no regressions caused.
</blockquote></details>

Running modern browsers test confirmed that issue was fixed and there were no regressions (modern or old browsers).  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7966)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7966)*

**Pull request merged**
