### PR TITLE
Add push info and karaf feature

### PR DESCRIPTION
**Pull request by Flamenco**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9716)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptcD8ABa_zLWg0DIck:-KptcD8ABa_zLWg0DIcl:bx3n3l9) (no related file):*
Really nice addition for the documentation.

 I have a recollection that it's hardly possible to enable websockets under Karaf at least. Can you please check if it does or does not work and add the notice into the documentation?

---

*[documentation/advanced/advanced-osgi.asciidoc, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptczTruCHg6CcJmv4H:-KptczTruCHg6CcJmv4I:b-fyfhh2) ([raw file](https://github.com/vaadin/framework/blob/2105ff75e2ceaededea2a0bdcfec97ec8dac403d/documentation/advanced/advanced-osgi.asciidoc#L206)):*
> ```AsciiDoc
> [source, xml]
> ----
> <features name="vaadin-osgi" xmlns="http://karaf.apache.org/xmlns/features/v1.0.0">
> ```

This karaf feature looks very promising, actually it addresses #9384 but we need more documentation how to use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
I can confirm that websockets work on all major browsers using Vaadin 7, 8, and 8.1 and OSGi.  I have been using OSGi since Vaadin 7.  We switched our production server to 8.1 last week, and hence my contribution.  It was nice to remove our classloader hacks and custom servlets to get this working.

The caveat is that the Atmosphere and Jetty don't always get along well with certain version combinations, and Karaf has a baked in Jetty version when using Pax-Web that you can't override.  You can use Karaf 4.1.0 and enable JSR356, or Karaf 4.1.1+ and _disable_ JSR356.

We are using a custom Karaf built off the current 4.2-SNAPSHOT.  We started by rebuilding Karaf and forcing it to use pax-web 4.0.2.  That used a version of Jetty that worked with the _enable JSR356_ trick mentioned in various places.  But as stated, there are ways to get this working using the newer Jetty, and we managed to pull that off with a few days effort.

I think the best way to go about this is have a couple of working sample projects.

Anyway, Karaf features are by far the best way to convey the OSGi dependency chain.  I suggest we publish the feature in a repo.  Then the user can get up and running by:

- download and extract karaf <= 4.1.0
- ./bin/karaf (start karaf)
- repo-add <the-feature-repo-url>
- feature:install vaadin-osgi-sample-with-push

And the sample feature would be something like this:

```
<feature name='vaadin-osgi-sample-with-push'>
     <feature>vaadin-osgi-with-push</feature>
    <bundle>vaadin-osgi-push-sample</bundle>
</feature>
```

or the non push version

```
<feature name='vaadin-sample'>
     <feature>vaadin-osgi</feature>
    <bundle>vaadin-osgi-sample</bundle>
</feature>
```

**Comment by Flamenco** [comment]
> This karaf feature looks very promising, actually it addresses #9384 but we need more documentation how to use that.

I think that a link  [https://karaf.apache.org/manual/latest/provisioning](https://karaf.apache.org/manual/latest/provisioning)  is all that is needed for documentation :)

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptczTruCHg6CcJmv4H:-KpxinjwYafrI8lYYL-B:b-rqgdiw) ([raw file](https://github.com/vaadin/framework/blob/2105ff75e2ceaededea2a0bdcfec97ec8dac403d/documentation/advanced/advanced-osgi.asciidoc#L206)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This karaf feature looks very promising, actually it addresses #9384 but we need more documentation how to use that.
</blockquote></details>

How to use the Karaf feature?  Or push with OSGi?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptcD8ABa_zLWg0DIck:-Kpxj07KMe5uMX-3lIA0:bpw5ok8) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Really nice addition for the documentation.

 I have a recollection that it's hardly possible to enable websockets under Karaf at least. Can you please check if it does or does not work and add the notice into the documentation?
</blockquote></details>

Please see my previous response for confirmation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptczTruCHg6CcJmv4H:-KpyiXVgRdbpB1tAN_sP:b-y0dy7y) ([raw file](https://github.com/vaadin/framework/blob/2105ff75e2ceaededea2a0bdcfec97ec8dac403d/documentation/advanced/advanced-osgi.asciidoc#L206)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

How to use the Karaf feature?  Or push with OSGi?
</blockquote></details>

Karaf feature, I mean

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9716#-KptczTruCHg6CcJmv4H:-KpyxtBvZznG88-eCjTr:b-3n3wh) ([raw file](https://github.com/vaadin/framework/blob/2105ff75e2ceaededea2a0bdcfec97ec8dac403d/documentation/advanced/advanced-osgi.asciidoc#L206)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Karaf feature, I mean
</blockquote></details>

OK.  Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-KpzxlYkC9SRnScwucmt:beo7l2i) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
> ```AsciiDoc
> 
> When using push with any container, it is important that your version of Jetty/Tomcat is compatible with Vaadin's
> port of Atmosphere.  The server log will report errors and the browser console will display a fallback warning
> ```

Also the fallback to long polling will happen. Also I am not sure if the whole push will work  if there are incompatibilities of certain type.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 209 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kpzy8S_51nt1bgUaVh-:-Kpzy8S_51nt1bgUaVh0:b-wo7jwz) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L209)):*
> ```AsciiDoc
> [source]
> ----
> > feature:repo-add file:vaadin-feature.xml
> ```

Is it possible to use https urls here? We might deploy the file to somewhere and keep it siple and up-to date.
(not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-Kq-3XnwzrH2FbZ06zWr:bqjhfsv) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Also the fallback to long polling will happen. Also I am not sure if the whole push will work  if there are incompatibilities of certain type.
</blockquote></details>

You just need to configure Atmosphere with the correct server init params.  Without a good match however, Atmosphere will fall back to long polling sometimes, and freak out other times...  It all comes down to Jetty breaking API in a minor version release...

Can I upload screenshots on reviewable?  My console log shows push loaded, and the websocket log shows the frames coming in.  Anyway, compatibility issues between Jetty and Atmosphere are not related to OSGi, so I don't see why they should even be documented on this page.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 209 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kpzy8S_51nt1bgUaVh-:-Kq-6chT6lb0MZVbXBze:b-esfop2) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L209)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Is it possible to use https urls here? We might deploy the file to somewhere and keep it siple and up-to date.
(not a blocker)
</blockquote></details>

There are no urls except for the Karaf namespace URI.  Did I miss something?  Besides that, you Vaadin guys should decide on where you will publish the feature, and then you can remove it from this page and just post the URL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-Kq1ReW0j2UxGTw81NEV:b-tslsis) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

You just need to configure Atmosphere with the correct server init params.  Without a good match however, Atmosphere will fall back to long polling sometimes, and freak out other times...  It all comes down to Jetty breaking API in a minor version release...

Can I upload screenshots on reviewable?  My console log shows push loaded, and the websocket log shows the frames coming in.  Anyway, compatibility issues between Jetty and Atmosphere are not related to OSGi, so I don't see why they should even be documented on this page.
</blockquote></details>

My comment was a suggestion for the text but not an objection.

For me, push does not seem working. I don't think we can really publish non-working stuff.

And yes, you can upload pictures. Just use copy-paste


---

*[documentation/advanced/advanced-osgi.asciidoc, line 235 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kx8ZC1xNT5afVotaF5I:-Kx8ZC1xNT5afVotaF5J:bhk5k0u) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L235)):*
> version="8.1.0" 
Should not be here. Karaf does not parse feature file with version here.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 257 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kx8_StOt--31ImjrMeZ:-Kx8_StOt--31ImjrMe_:b-aroz5e) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L257)):*
> 2.4.11.vaadin1
`2.4.11.vaadin2` already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-Kx8cHyyPaBSNw-YcvrO:b-fl28on) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

My comment was a suggestion for the text but not an objection.

For me, push does not seem working. I don't think we can really publish non-working stuff.

And yes, you can upload pictures. Just use copy-paste



</blockquote></details>

Perhaps I can help you getting your websockets to work.

1. What version of Jetty are you using?
2. What annotations are using using for your Servlet and UI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-Kx9c3vn2GBul2G868PZ:b-gby7rt) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

Perhaps I can help you getting your websockets to work.

1. What version of Jetty are you using?
2. What annotations are using using for your Servlet and UI?
</blockquote></details>

1.  9.3.14

2.Servlet:
```
    @Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/myapp1/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
```
UI
```
    @Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/myapp1/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-KxTSueTz-tX2tJgObgk:b4rvd1z) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

1.  9.3.14

2.Servlet:
```
    @Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/myapp1/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
```
UI
```
    @Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/myapp1/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
```
</blockquote></details>

My servlet is the same as yours.
```
    @org.osgi.service.component.annotations.Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/*", name = "MyUiServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = true)
```
My UI 
```
@Push
@Theme("mytheme")
@Widgetset("tv.twelvetone.vaandroid.core.MyAppWidgetset")
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui")
```

Your UI does not have the @Push annotation....  Also @Component, @WebServlet,  and @VaadinServletConfiguration are only for the servlet methinks.

Also, I published the theme and widgetset as DS components and used the relevant annotations.  (We use Kotlin here...)

```
package tv.twelvetone.vaandroid.core

import com.vaadin.osgi.resources.OsgiVaadinTheme
import com.vaadin.osgi.resources.OsgiVaadinWidgetset
import com.vaadin.ui.themes.ValoTheme
import org.osgi.service.component.annotations.Component

@Component
class MyTheme : ValoTheme(), OsgiVaadinTheme {
    override fun getName() = "mytheme"

}

@Component
class MyWidgetset : OsgiVaadinWidgetset {
    override fun getName() = "tv.twelvetone.vaandroid.core.MyAppWidgetset"
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 235 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kx8ZC1xNT5afVotaF5I:-KxTaztts0DXm2eLWxXY:b-ng56pf) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L235)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> version="8.1.0" 
Should not be here. Karaf does not parse feature file with version here.
</blockquote></details>

Did you set your features version?

Karaf will parse it if you properly set the version to 1.3.0 in the xml
```
<features name='VaadinFeatures="http://karaf.apache.org/xmlns/features/v1.3.0">
```

---

*[documentation/advanced/advanced-osgi.asciidoc, line 257 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-Kx8_StOt--31ImjrMeZ:-KxTakbv6YQVbmVA-1uO:b9fc1ia) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L257)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> 2.4.11.vaadin1
`2.4.11.vaadin2` already
</blockquote></details>

I would version the feature then and include one for each vaadin-atmosphere release then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 198 at r2](https://reviewable.io:443/reviews/vaadin/framework/9716#-KpzxlYkC9SRnScwucms:-KxYUlqMGdXOV242MedE:b-x3vh9u) ([raw file](https://github.com/vaadin/framework/blob/295900cbe564d34ef3dc913e0ece7531c62b71f1/documentation/advanced/advanced-osgi.asciidoc#L198)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

My servlet is the same as yours.
```
    @org.osgi.service.component.annotations.Component(service = VaadinServlet.class)
    @WebServlet(urlPatterns = "/*", name = "MyUiServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = true)
```
My UI 
```
@Push
@Theme("mytheme")
@Widgetset("tv.twelvetone.vaandroid.core.MyAppWidgetset")
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui")
```

Your UI does not have the @Push annotation....  Also @Component, @WebServlet,  and @VaadinServletConfiguration are only for the servlet methinks.

Also, I published the theme and widgetset as DS components and used the relevant annotations.  (We use Kotlin here...)

```
package tv.twelvetone.vaandroid.core

import com.vaadin.osgi.resources.OsgiVaadinTheme
import com.vaadin.osgi.resources.OsgiVaadinWidgetset
import com.vaadin.ui.themes.ValoTheme
import org.osgi.service.component.annotations.Component

@Component
class MyTheme : ValoTheme(), OsgiVaadinTheme {
    override fun getName() = "mytheme"

}

@Component
class MyWidgetset : OsgiVaadinWidgetset {
    override fun getName() = "tv.twelvetone.vaandroid.core.MyAppWidgetset"
}
```

</blockquote></details>

FYI:  We just upgraded from vaadin 8.1.3 to 8.1.6 and all is well.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9716)*

**Comment by pleku** [comment]
Apologies for the inactivity.

We're updating the PR context to version 8.7 and testing it. We will merge this PR if things still work, like they should.

**Comment by ZheSun88** [comment]
This PR is trying to push the content into a person branch, which is not targeting the master.

**Comment by Flamenco** [comment]
This PR is 2 years old and Karaf versions have changed.

**Comment by TatuLund** [comment]
Unfortunately there has been too little attention towards this PR. I am closing this PR as outdated. The proposed idea may still be valid, but requires PR done against current master.

**Pull request closed without merging**
