### PR TITLE
Use non-Generic SortOrder in Query.

### LINKED ISSUE #8215: Remove pointless type parameter from SortOrder from the Query API
`Query.getSortOrders()` is currently defined to return `List<SortOrder<String>>`.  The `<String>` part there is completely redundant in this context. The API should be simplified to not expose the type parameter.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8215

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8239)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagAjBgBt-tKu1tSB0B:-KagAjBgBt-tKu1tSB0C:b-n9uycb) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L21)):*
> ```Java
> 
> /**
>  * Sorting information for one field.
> ```

Sorting information for a {@link Query}.

Or something along those lines.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagATVGA-PceJdHjStd:-KagATVGA-PceJdHjSte:bg3zk2y) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L25)):*
> ```Java
>  * @see Query
>  */
> public class QuerySortOrder extends SortOrder<String> {
> ```

The javadoc for getSorted should probably be overridden to be more specific.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagAln26dOBsJLBz1Zi:-KagAln26dOBsJLBz1Zj:b-6j93sj) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L28)):*
> ```Java
> 
>     /**
>      * Constructs a field sorting information
> ```

Constructs sorting information for usage in a {@link Query}.

---

*[server/src/main/java/com/vaadin/data/provider/Sort.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-Kag9PWvW5jI1J8gTIAZ:-Kag9PWvW5jI1J8gTIA_:b-t7zcl4) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/Sort.java#L44)):*
> ```Java
>      * @see #build()
>      */
>     public static class SortBuilder implements Serializable {
> ```

Should this be renamed now that it is no longer generic? Removing the generics also means this can't be used for example in building a grid sort order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8239)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagAjBgBt-tKu1tSB0B:-KagUEhrn-uS38XG8Itc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L21)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Sorting information for a {@link Query}.

Or something along those lines.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagATVGA-PceJdHjStd:-KagUXgWf_-2c40yxWfW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L25)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

The javadoc for getSorted should probably be overridden to be more specific.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-KagAln26dOBsJLBz1Zi:-KagUb0rn7lT-EJI0c6b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/QuerySortOrder.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Constructs sorting information for usage in a {@link Query}.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/Sort.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-Kag9PWvW5jI1J8gTIAZ:-KagUlWr9BG3ZyS-qa6X:bqdir3h) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/Sort.java#L44)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should this be renamed now that it is no longer generic? Removing the generics also means this can't be used for example in building a grid sort order.
</blockquote></details>

I don't know.....
Technically I don't see a reason to rename.

Grid uses  a `SortOrder<T>` as DTOs only. So the builder has no any sense there.
There are should be two different classes for this actually but it has no sense to have both of them since they contain the same data.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8239)*

**Comment by ahie** [comment]
Needs rebase, otherwise :lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/Sort.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/8239#-Kag9PWvW5jI1J8gTIAZ:-KaqvW0eyT6QqZf2eD28:b-lrrlv2) ([raw file](https://github.com/vaadin/framework/blob/b794ec4c7ba220baad845a681c0817f9b7af2192/server/src/main/java/com/vaadin/data/provider/Sort.java#L44)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't know.....
Technically I don't see a reason to rename.

Grid uses  a `SortOrder<T>` as DTOs only. So the builder has no any sense there.
There are should be two different classes for this actually but it has no sense to have both of them since they contain the same data.
</blockquote></details>

Now a separate issue, https://github.com/vaadin/framework/issues/8259

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8239#-:-Kaqvc3LE7bMZbn67_6C:btey29k)*

**Comment by ahie** [comment]
Reviewed 5 of 12 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8239)*

**Pull request merged**
