### PR TITLE
Add Vaadin Spring dependency version to BOM

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch adds a smoke test that check that a basic
Vaadin UI loads and communication works.

Fixes vaadin/framework8-issues#524

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/112)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlmWckAaAl8FqfVFGA:-KYlmWckAaAl8FqfVFGB:b6cff0z) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/bom/pom.xml#L12)):*
> ```XML
>     <artifactId>vaadin-bom</artifactId>
>     <packaging>pom</packaging>
>     <version>8.0-SNAPSHOT</version>
> ```

NIT: I wouldn't mind moving the FW version to be the first property in `<properties>`

---

*[test/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlmrnoL5Du3YEPgR5A:-KYlmrnoL5Du3YEPgR5B:b-m8a2xu) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/pom.xml#L15)):*
> ```XML
>     <packaging>pom</packaging><properties>
>         <failOnMissingWebXml>false</failOnMissingWebXml>
>         <vaadin.testbench.version>5.0.0.alpha1</vaadin.testbench.version>
> ```

What if we moved this to the BOM right away too, or is that the next PR ?

---

*[test/spring-boot-test/.gitignore, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlncC_i2a4LPyf_qTI:-KYlncC_i2a4LPyf_qTJ:b9frbzw) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/.gitignore#L24)):*
> ```
> dist/
> nbdist/
> .nb-gradle/
> ```

NIT: Is this file really needed or could these things be in the top level .gitignore ? Or just at a higher level so no need to duplicate

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo6shAGwRRNzL3GKF:-KYlo6siC18OeAc2pHSv:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L29)):*
> ```Java
>                 e -> Notification.show(NOTIFICATION_TEXT)));
>     }
> }
> ```

new line

---

*[test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo9bI1Zfpk8hM9sco:-KYlo9bI1Zfpk8hM9scp:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java#L45)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlmWckAaAl8FqfVFGA:-KYmfp9ZkaepwBuLcaKC:bowii6e) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/bom/pom.xml#L12)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: I wouldn't mind moving the FW version to be the first property in `<properties>`
</blockquote></details>

should be ${project.version}

---

*[test/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlmrnoL5Du3YEPgR5A:-KYmfrsI3iiP8pWAsAkM:b8b5krc) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/pom.xml#L15)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

What if we moved this to the BOM right away too, or is that the next PR ?
</blockquote></details>

Next PR (one step at a time)

---

*[test/spring-boot-test/.gitignore, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlncC_i2a4LPyf_qTI:-KYmfvQfEg0F3HVtgTqX:bj28mg9) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/.gitignore#L24)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: Is this file really needed or could these things be in the top level .gitignore ? Or just at a higher level so no need to duplicate
</blockquote></details>

the .gitignore in this case was generated by start.spring.io, could use some clean up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by tsuoanttila** [comment]
*[bom/pom.xml, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlmWckAaAl8FqfVFGA:-KYmiibGAW_lpZA1o07q:b2fk7e3) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/bom/pom.xml#L12)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should be ${project.version}
</blockquote></details>

This was a different file than I thought it was. I'm not sure if this version can be set using a property. Since it's the version for the created artifact (vaadin-bom).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
Reviewed 3 of 7 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[bom/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6wmvLXXXkOGgOddf:-KYr6wmvLXXXkOGgOddg:b-52har) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L16)):*
> ```XML
>     <description>Vaadin Framework (Bill of Materials)</description>
>     <url>http://vaadin.com</url>
>     
> ```

extra whitespace?

---

*[bom/pom.xml, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr5G_aOOwi4_Z_YiPA:-KYr5G_aOOwi4_Z_YiPB:b-ftlvoe) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L100)):*
> ```XML
>             <dependency>
>                 <groupId>com.vaadin</groupId>
>                 <artifactId>vaadin-spring-boot-starter</artifactId>
> ```

We should probably also have vaadin-spring-boot explicitly listed. Otherwise, a transitive dependency to it e.g. from vaadin4spring (which doesn't necessarily use the starter) could mess up dependency versions.

---

*[bom/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6z1j2rNR20FbhOE_:-KYr6z1j2rNR20FbhOEa:b-52har) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L108)):*
> ```XML
>                 <version>${vaadin.spring.version}</version>
>             </dependency>
>             
> ```

extra whitespace?

---

*[test/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6D41AxZ72JdRuoPR:-KYr6D41AxZ72JdRuoPS:b-78c5vw) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/test/pom.xml#L16)):*
> ```XML
>         <failOnMissingWebXml>false</failOnMissingWebXml>
>         <vaadin.testbench.version>5.0.0.alpha1</vaadin.testbench.version>
>         <skip.jetty.plugin>false</skip.jetty.plugin>
> ```

Is this directly configuring the jetty plugin, or do is this used directly? What overrides this?

---

*[test/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr5ejjR4cEYdXK8o3P:-KYr5ejk2O99eRVHOrkM:bx5pnm2) ([raw file](https://github.com/vaadin/framework/blob/474057c6a77dded2ffc6cc131c3053341c8959ee/test/pom.xml#L108)):*
> ```XML
>             </plugin>
>             <plugin>
>                 <groupId>com.github.klieber</groupId>
> ```

Is moving this down relevant for this change?

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6dPPfjayiqlsfOWa:-KYr6dPPfjayiqlsfOWb:b-89f2yz) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L27)):*
> ```Java
>     protected void init(VaadinRequest request) {
>         setContent(new Button("Click Me!",
>                 e -> Notification.show(NOTIFICATION_TEXT)));
> ```

This could also at least test basic injection of a service that returns the text or something (ideally more, like views).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[bom/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6wmvLXXXkOGgOddf:-KYrJFdtfWtTiZB2HXW9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace?
</blockquote></details>

Done.

---

*[bom/pom.xml, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr5G_aOOwi4_Z_YiPA:-KYrJGezWekG28GPyXQZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L100)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

We should probably also have vaadin-spring-boot explicitly listed. Otherwise, a transitive dependency to it e.g. from vaadin4spring (which doesn't necessarily use the starter) could mess up dependency versions.
</blockquote></details>

Done.

---

*[bom/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6z1j2rNR20FbhOE_:-KYrJHEYo5A50eYooUAX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/bom/pom.xml#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace?
</blockquote></details>

Done.

---

*[test/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6D41AxZ72JdRuoPR:-KYrHSXtvYyfEHljh-f6:b-5lgi5o) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/test/pom.xml#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this directly configuring the jetty plugin, or do is this used directly? What overrides this?
</blockquote></details>

Not used anymore. I was testing some different approaches on how to disable the jetty for testing. Will be removed.

---

*[test/pom.xml, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr5ejjR4cEYdXK8o3P:-KYrHabQc21pr_neK_EC:b25wqoh) ([raw file](https://github.com/vaadin/framework/blob/474057c6a77dded2ffc6cc131c3053341c8959ee/test/pom.xml#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is moving this down relevant for this change?
</blockquote></details>

Not relevant. reverting.

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo6shAGwRRNzL3GKF:-KYrHq3hz9hBMN5BW6AI:btijm8t) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

new line
</blockquote></details>

There is already a newline, do we need another?

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6dPPfjayiqlsfOWa:-KYrJlWKGxfCYRAjn7Pe:bi89uu6) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L27)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This could also at least test basic injection of a service that returns the text or something (ideally more, like views).
</blockquote></details>

Do we want to make the improvements in the test now, or do we make ticket out of expanding the test?

---

*[test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo9bI1Zfpk8hM9sco:-KYrHwkPlpl7tm-s4hBX:b-q64pkt) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java#L45)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

new line
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by pleku** [comment]
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo6shAGwRRNzL3GKF:-KYrKPoLSBAGclXCjHJi:b9thca0) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L29)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

There is already a newline, do we need another?
</blockquote></details>

Why are you commenting on resolved comments for previous patch sets ?

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/112#-KYr6dPPfjayiqlsfOWa:-KYrKG012LPiMkPyc1tk:b-tkebzg) ([raw file](https://github.com/vaadin/framework/blob/efb24a6a9ee8c98ba4b4965750a1e3ee0ffe610d/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Do we want to make the improvements in the test now, or do we make ticket out of expanding the test?
</blockquote></details>

Not a priority IMO at this moment. In ideal world we could have all the features tested, but we're not yet there ...

---

*[test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo9bI1Zfpk8hM9sco:-KYrKYRHKGg3R-xUeGre:b9thca0) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java#L45)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Why are you commenting on resolved comments for previous patch sets ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/spring-boot-test/src/main/java/com/example/DemoApplication.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo6shAGwRRNzL3GKF:-KYrNNmst4tZVKQTRfY0:baum8xf) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/main/java/com/example/DemoApplication.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why are you commenting on resolved comments for previous patch sets ?
</blockquote></details>

For some reason it showed it to me in the latest patch set, not sure why. Thanks Reviewable.

---

*[test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/112#-KYlo9bI1Zfpk8hM9sco:-KYrNUlmmdz-HtaBCAss:b-q64pkt) ([raw file](https://github.com/vaadin/framework/blob/17f2f592609e6c9cc5e713956e2eef321017fe1c/test/spring-boot-test/src/test/java/com/example/SpringBootSmokeTest.java#L45)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why are you commenting on resolved comments for previous patch sets ?
</blockquote></details>

See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/pom.xml, line 12 at r3](https://reviewable.io:443/reviews/vaadin/framework/112#-KYrP5VStZQUP8d7Z7rH:-KYrP5VStZQUP8d7Z7rI:b-3f22jf) ([raw file](https://github.com/vaadin/framework/blob/998dccc8f52fc9b62f16ff809559c109c61e2981/test/pom.xml#L12)):*
> ```XML
>     <artifactId>vaadin-test</artifactId>
>     <name>vaadin-test</name>
>     
> ```

extra whitespace (could also be edited out in GH UI)

---

*[test/pom.xml, line 15 at r3](https://reviewable.io:443/reviews/vaadin/framework/112#-KYrPFgUVnJ_pLEGV3wr:-KYrPFgUVnJ_pLEGV3ws:b-p1r1zc) ([raw file](https://github.com/vaadin/framework/blob/998dccc8f52fc9b62f16ff809559c109c61e2981/test/pom.xml#L15)):*
> ```XML
>     <packaging>pom</packaging><properties>
>         <failOnMissingWebXml>false</failOnMissingWebXml>
>         <vaadin.testbench.version>5.0.0.alpha1</vaadin.testbench.version>
> ```

where is this used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
Reviewed 9 of 10 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bom/pom.xml, line 8 at r4](https://reviewable.io:443/reviews/vaadin/framework/112#-KYsnYR44VW7Jim_thjt:-KYsnYR44VW7Jim_thju:b-iyvhz2) ([raw file](https://github.com/vaadin/framework/blob/fe39b2501b51380652fc0c2fc789d6a80ffa09ad/bom/pom.xml#L8)):*
> ```XML
>         <artifactId>vaadin-parent</artifactId>
>         <version>1.0.0</version>
> 	<relativePath />
> ```

whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/112#-:-KYwrSTmnxUJtHCVYec7:bnfp4nl)*

**Pull request merged**
