### PR TITLE
Rename SerializableBiConsumer into Setter

### PR DESCRIPTION
**Pull request by elmot**
---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7992)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7992#-KYyxIUCpf9yKB4LXDeS:-KYyxIUCpf9yKB4LXDeT:bj80fw8) (no related file):*
Fix the commit message, remove the misc. part completely.

Always try to be more specific, if it is impossible, probably patch has too many things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7992)*

**Comment by elmot** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7992#-KYyxIUCpf9yKB4LXDeS:-KYz2CXEuT-UbtPyvDay:b-896fjx) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Fix the commit message, remove the misc. part completely.

Always try to be more specific, if it is impossible, probably patch has too many things.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7992)*

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/Setter.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/7992#-KZ0fqyZb2X01aMMR5nW:-KZ0fqyZb2X01aMMR5nX:bq08677) ([raw file](https://github.com/vaadin/framework/blob/40134fddf3b87c96a9d9bb66b205e55cb882c14b/server/src/main/java/com/vaadin/server/Setter.java#L25)):*
> ```Java
> 
> /**
>  * The function to write the field value to the bean property
> ```

NIT: the first The is unnecessary since there is no qualifier, e.g. "the field value, "the type of the target bean", but when it is just "function".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7992)*

**Comment by pleku** [comment]
Needs rebase

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7992#-:-KZ0gJawzu5ww6a51pyP:b-apz0tw)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7992)*

**Pull request merged**
