### PR TITLE
Expired session: use 403 Forbidden instead of 410 Gone

### LINKED ISSUE #4417: Heartbeat should respond 404, not 410, when session expired
**Originally by @jdahlstrom**

___
`HeartbeatHandler` currently sends 410 Gone if the session is expired. This is arguably semantically wrong, as a user agent is within its rights to assume that the resource uniquely identified by the URI (and only the URI - cookies don't matter) will never be available again and any future requests to the same URI should not be made. A 404 Not Found should be returned instead.

___
 Imported from https://dev.vaadin.com/ issue #12526

### PR DESCRIPTION
**Pull request by ghost**
Use 403 Forbidden instead of 410 Gone or 404 Not Found when a session is expired. Note that one 410 Gone has already been changed to 404 Not Found in #11556, but the corresponding client code was not adjusted. Since the client code already treats 404 specially, I've decided to use 403 instead (as has been earlier suggested in #4417), even though 404 would be more fitting for this error.

I've also added no-caching headers when 403 is now sent (i.e. when 410 was sent before).

Fixes #4417, updates #11556.

**Check when you have completed**
[ ] Valid tests for the pull request
[x] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11859)

### CODE REVIEW

**Comment by ffdybuster** [comment]
I've patched this (and #11556) into the latest released Vaadin 7.7 JARs and rebuild our app with that, and it seems to work fine. At least I cannot reproduce the heartbeat caching with Safari anymore...

**Comment by TatuLund** [comment]
Thanks for your contribution. We will review it. 

At quick glance at least the ticket references in the comments are wrong they should be

https://github.com/vaadin/framework/issues/3226

and 

https://github.com/vaadin/framework/issues/4167

**Comment by ffdybuster** [comment]
@TatuLund the ticket numbers are apparently from the old ticketing system (https://dev.vaadin.com/). Should these be updated also in the original comments, which were copied (and adjusted) by #11556 and this PR? These are https://github.com/vaadin/framework/pull/11859/files#diff-8c63a75131409798ae94bfc088628bc6R63-R69

**Comment by ffdybuster** [comment]
@TatuLund ping

**Comment by TatuLund** [comment]
@ffdybuster 
> the ticket numbers are apparently from the old ticketing system

Yes, transition was done couple of years of ago.

> Should these be updated also in the original comments

That would be preferred for sake of maintenance.

**Comment by ffdybuster** [comment]
@TatuLund thanks! I've updated the PR to adjust all these issue numbers.

**Comment by ffdybuster** [comment]
@TatuLund is there a chance you can review this soon?

**Comment by felixfontein** [comment]
@TatuLund is there a chance this will get reviewed somewhen?

**Review by Ansku — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11859#-:-M4O_mlWAoT_b3Zok4HV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by felixfontein** [comment]
@TatuLund @Ansku thank you very much for your feedback, reviewing and merging! :)

**Pull request merged**
