### PR TITLE
Call error handler for exceptions in UI.init()

### LINKED ISSUE #4995: Exceptions during initial view change not handled properly
**Originally by @jdahlstrom**

___
Exceptions during `UI.doInit()` are not handled by the `ErrorHandler` mechanism but are simply propagated to the servlet. This is especially a problem if the initial `Navigator.navigateTo` call throws. It's not completely clear how this should be handled - any custom UI error handler might work in an unexpected way if the UI is not completely initialized yet. On the other hand, at least after `UI.init` is run it should be safe to use the normal mechanism, and this would resolve the mentioned navigator issue.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #4995

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8055)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQApCMKksN0OsIimpF:b-gqsc4e) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
> ```Java
>         UI.setCurrent(ui);
> 
>         Exception initException = null;
> ```

`Throwable` then

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 222 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQAs9lbOIzqGO3u_-d:-KZQAs9lbOIzqGO3u_-e:b5cmpyr) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L222)):*
> ```Java
>         session.addUI(ui);
>         if (initException != null) {
>             ui.getSession().getCommunicationManager()
> ```

Communication manager is able to handle `Throwable`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQJHlPuqsSR0uTqYXx:b-httw1x) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`Throwable` then
</blockquote></details>

Why would we want to handle e.g. `OutOfMemoryError` or `ThreadDeath`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQKJsjlOV9Jf9MOPoi:b5fpzo5) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why would we want to handle e.g. `OutOfMemoryError` or `ThreadDeath`?
</blockquote></details>

- I personally don't see a big difference between `ThreadDeath` and `IndexOutOfBoundsException`. Both means some errors in the code logic.
- User is able to create his own (e.g. `Error`)  `Throwable`with special semantic. For some reason it can be not an exception.
- Why does CommunicationManager accepts `Throwable` and not an `Exception` only ?

Don't have a strong preference actually. But if you are going to catch `Exception` then I think it should be `Throwable` (just more logical for me).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQLxM_iq_HEDxGbZDk:bpnynkp) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

- I personally don't see a big difference between `ThreadDeath` and `IndexOutOfBoundsException`. Both means some errors in the code logic.
- User is able to create his own (e.g. `Error`)  `Throwable`with special semantic. For some reason it can be not an exception.
- Why does CommunicationManager accepts `Throwable` and not an `Exception` only ?

Don't have a strong preference actually. But if you are going to catch `Exception` then I think it should be `Throwable` (just more logical for me).
</blockquote></details>

I meant: I'm just suggesting and "ask" questions. It's up to you to consider this or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQMkUTfjv2tzcw41UX:bb7yy5s) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I meant: I'm just suggesting and "ask" questions. It's up to you to consider this or not.
</blockquote></details>

https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions. The ThreadDeath error, though a "normal" condition, is also a subclass of Error because most applications should not try to catch it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQMTLlBCh8Y8NaauaE:b9so0c3) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I meant: I'm just suggesting and "ask" questions. It's up to you to consider this or not.
</blockquote></details>

Most `Throwable` types that are not also `Exception` are thrown for problems that the application cannot or shouldn't try to recover from, and therefore it's also seen as good practice to not even try to catch them. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQN6-CX5ZFiQN7qalT:b-tul1q) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Most `Throwable` types that are not also `Exception` are thrown for problems that the application cannot or shouldn't try to recover from, and therefore it's also seen as good practice to not even try to catch them. 
</blockquote></details>

OK.
Still don't see an answer to the question "Why does CommunicationManager accepts Throwable and not an Exception only ?".
But unblocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQPYqHrfJsnvy6qbzH:b-cy5r5y) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK.
Still don't see an answer to the question "Why does CommunicationManager accepts Throwable and not an Exception only ?".
But unblocking.
</blockquote></details>

`CommunicationManager` accepts `Throwable` because nobody pointed out the dangers of catching `Throwable` when that method was implemented, and nobody has had a big enough reason to change it since then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8055#-KZQApCMKksN0OsIimpE:-KZQRmqArlW4LW3bolK2:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/86d0899869a2babf4a87d1136a473f3bdaa29c5a/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L214)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`CommunicationManager` accepts `Throwable` because nobody pointed out the dangers of catching `Throwable` when that method was implemented, and nobody has had a big enough reason to change it since then.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8055)*

**Comment by Artur-** [comment]
Ugh, I retargeted this for 7.7 but apparently now this patch has 17 contributors...

**Comment by Artur-** [comment]
Fixed test problems

**Pull request merged**
