### PR TITLE
Add initial implementation of TreeGrid

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8572)

### CODE REVIEW

**Comment by ahie** [comment]
WIP. At least keyboard navigation still needs fixes.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572#-:-Kd0AE_gz57ZHca_Lvvs:bt14y8i)*

**Comment by Artur-** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd0VnW5Scy3Cv8HNh_Y:-Kd0VnW5Scy3Cv8HNh_Z:b-7lbx7k) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L45)):*
> ```Java
>      */
>     @Override
>     public Escalator getEscalator() {
> ```

This was done for Grid in 7.7 already and should thus be in Grid instead. See https://github.com/vaadin/framework/blob/7.7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6901

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by ahie** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd0VnW5Scy3Cv8HNh_Y:-Kd0_HE9pl2Cb38LC-vQ:b-1nwo2n) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L45)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This was done for Grid in 7.7 already and should thus be in Grid instead. See https://github.com/vaadin/framework/blob/7.7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6901
</blockquote></details>

7.7.7 commits have not yet been merged to master. Blocked this for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by ahie** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 291 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd54glDkAJ37tW-oPhb:-Kd54glEidNdWtIOnFCK:b-q3mmwd) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L291)):*
> ```Java
>                             } else if (depth > 0) {
>                                 // jump to parent
>                                 getWidget().focusCell(parentIndex,
> ```

This behavior has been removed for now. Sending the parent index from the server for every item just for this functionality doesn't seem worth it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by pleku** [comment]
Reviewed 5 of 16 files at r1, 4 of 9 files at r2.
Review status: 9 of 16 files reviewed at latest revision, 19 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 291 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd54glDkAJ37tW-oPhb:-KdQK2NIIRZ57Oiyf4u7:b-o7r04n) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L291)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

This behavior has been removed for now. Sending the parent index from the server for every item just for this functionality doesn't seem worth it.
</blockquote></details>

What behavior ? Why is not this visible in the code ?

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQHb_mVVf2L0nyR2Fb:-KdQHb_mVVf2L0nyR2Fc:b-yvhr43) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L112)):*
> ```Java
>     }
> 
>     private HierarchyRenderer hierarchyRenderer;
> ```

Please move members to top before instance methods

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 166 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQIkHBssLYMujUyzU5:-KdQIkHBssLYMujUyzU6:b-6t374n) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L166)):*
> ```Java
>         
>         // FocusEventHandler is initially 5th in the list of browser event handlers
>         browserEventHandlers.@java.util.List::set(*)(5, eventHandler);
> ```

This is so fragile it is killing me, can we change this `int` to as an constants to Grid widget where the listener is added, and pass it from there to this method ?

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 191 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQJNnGS3DrZxqZfY8W:-KdQJNnGS3DrZxqZfY8X:bs2lv0h) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L191)):*
> ```Java
>      * cells.
>      */
>     private class CellFocusEventHandler
> ```

NIT: Not sure if this could be refactored to a separate class for clarity, seems to need only the Grid widget, which should be available in the event

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 289 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQKEgJkIqRevvNrANu:-KdQKEgKqr1hCkwvr0Ag:bqf0jtm) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L289)):*
> ```Java
>         }
>     }
> }
> ```

NIT: newline

---

*[client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java, line 90 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQNQhcKSOEO3CKEmbx:-KdQNQhcKSOEO3CKEmby:b6ii1mx) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java#L90)):*
> ```Java
>         }
> 
>         // inner cell
> ```

I have no idea what these if-else does, can you please clarify it a bit in this comment ? I know I could dig into the code, but just a brief reference comment would be nice since the current means from little to nothing

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdP9V9M5kRZqWBbWvXJ:-KdP9V9M5kRZqWBbWvXK:bs5hijb) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L53)):*
> ```Java
>             hierarchyData.put(TreeGridCommunicationConstants.ROW_COLLAPSED,
>                     getDataProvider().isCollapsed(item));
>             hierarchyData.put(TreeGridCommunicationConstants.ROW_LEAF,
> ```

I think being a leaf node should exclude being collapsed.. 

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 66 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAA98PVNuieb1BATY:-KdPAA98PVNuieb1BATZ:bqslyfu) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L66)):*
> ```Java
>             public void toggleCollapse(String rowKey) {
>                 T item = getDataCommunicator().getKeyMapper().get(rowKey);
>                 toggleExpansion(item);
> ```

I hate it that there is mix of terms, using both collapse and expansion. Should just pick one.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPALRq8UepgMfviTxa:-KdPALRq8UepgMfviTxb:b-pn1hni) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L74)):*
> ```Java
>     @Override
>     public void setItems(Collection<T> items) {
>         throw new UnsupportedOperationException();
> ```

NIT: could for the time being also mention why there is UsOE, e.g. "Not implemented", might save a few seconds from some early testers

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAUZ5681z2wguUpxu:-KdPAUZ5681z2wguUpxv:bwzr33f) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L79)):*
> ```Java
>     @Override
>     public void setItems(Stream<T> items) {
>         throw new UnsupportedOperationException();
> ```

Same NIT as above

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAVXMBkI2V4p0u4js:-KdPAVXMBkI2V4p0u4jt:bwzr33f) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L84)):*
> ```Java
>     @Override
>     public void setItems(T... items) {
>         throw new UnsupportedOperationException();
> ```

Same NIT as above

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 90 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAcEv7xw842TyXd2V:-KdPAcEv7xw842TyXd2W:b-2plx5o) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L90)):*
> ```Java
>     public void setDataProvider(DataProvider<T, ?> dataProvider) {
>         if (!(dataProvider instanceof HierarchicalDataProvider)) {
>             throw new RuntimeException(
> ```

Use `IllegalArgumentException` instead

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 96 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBmFvusv-HGoFgbkp:-KdPBmFwDTgPd5e6ET6Z:bqkw7s2) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L96)):*
> ```Java
>     }
> 
>     public void setHierarchyColumn(String id) {
> ```

javadocs

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 96 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBn7qlGXua1EgJT40:-KdPBn7qlGXua1EgJT41:bf0xpp0) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L96)):*
> ```Java
>     }
> 
>     public void setHierarchyColumn(String id) {
> ```

What is shown by default when this is not set ?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 99 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAkcl5OhGdow21ntc:-KdPAkcl5OhGdow21ntd:b-2plx5o) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L99)):*
> ```Java
>         Objects.requireNonNull(id, "id may not be null");
>         if (getColumn(id) == null) {
>             throw new RuntimeException("No column found for given id");
> ```

Use `IllegalArgumentException` instead

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQGlXDxM6J1SAD9pAr:-KdQGlXDxM6J1SAD9pAs:bmmc0fl) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L101)):*
> ```Java
>             throw new RuntimeException("No column found for given id");
>         }
>         getState().hierarchyColumnId = getInternalIdForColumn(getColumn(id));
> ```

Discussed this a bit, concluded that by default, the column that is set as the hierarchical column, could be made as _not hidable_ and not _currently hidden_.

It could be possible for the developer to make the column hidable and hidden if he explicitly wants to, but by default the column showing the hierarchical data should be not those.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 136 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBGijVRnJIYE-9sB4:-KdPBGijVRnJIYE-9sB5:b-uchcu6) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L136)):*
> ```Java
>         // check it here
>         if (!(dataProvider instanceof HierarchicalDataProvider)) {
>             return null;
> ```

The javadocs currently say that never `null`

Could throw IllegalStateException with message for now, I find it better

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPCDuvNvTK3bxWQELT:-KdPCDuvNvTK3bxWQELU:bqf0jtm) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L60)):*
> ```SCSS
>     display: inline-block;
>   }
> }
> ```

NIT: newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by pleku** [comment]
Reviewed 3 of 16 files at r1, 2 of 9 files at r2.
Review status: 14 of 16 files reviewed at latest revision, 21 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 286 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQYypDVd02AQFJ2zB7:-KdQYypDVd02AQFJ2zB8:bey7oeq) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L286)):*
> ```Java
>                 }
>             }
>             event.setHandled(false);
> ```

uhm, can you please revert this check to be a canceling one, e.g. `if (check) return`. Reduces the nesting and improves readability of the method

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/HierarchyRendererCellReferenceWrapper.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQZUvtrF9x-ZzsSxQF:-KdQZUvtrF9x-ZzsSxQG:b-4vfjhd) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/widget/treegrid/HierarchyRendererCellReferenceWrapper.java#L29)):*
> ```Java
>  * @since 8.1
>  */
> public class HierarchyRendererCellReferenceWrapper
> ```

Can you please clarify why this is needed

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataProvider.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQ_hixj3dfYL6Qwj1h:-KdQ_hixj3dfYL6Qwj1i:b-kth8sh) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/data/provider/HierarchicalDataProvider.java#L26)):*
> ```Java
>  * @param <F>
>  */
> public interface HierarchicalDataProvider<T, F> extends DataProvider<T, F> {
> ```

Very much against this, will have to see if we just remove this or do it in another PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by pleku** [comment]
Reviewed 2 of 9 files at r2.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by ahie** [comment]
Review status: 9 of 16 files reviewed at latest revision, 22 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 291 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd54glDkAJ37tW-oPhb:-KdQfNdnsjW0KlC4IszI:b8gjssy) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L291)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

What behavior ? Why is not this visible in the code ?
</blockquote></details>

Removed code between r1 and r2. Jump to parent was removed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQHb_mVVf2L0nyR2Fb:-KdQelu_pEb0oTESnKV_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L112)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please move members to top before instance methods
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 166 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQIkHBssLYMujUyzU5:-KdR0-c3_gu7El0Vy2tl:bt6agnf) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L166)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is so fragile it is killing me, can we change this `int` to as an constants to Grid widget where the listener is added, and pass it from there to this method ?
</blockquote></details>

All of the 6 browser event handlers are added without an index to the grid widget. Should they all have a constant as well? And once the array is modified the constants become useless. Further refactoring in `Grid` is probably needed. 

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 191 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQJNnGS3DrZxqZfY8W:-KdQiH2R6nQ9xfw_WnZd:bsikg77) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L191)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: Not sure if this could be refactored to a separate class for clarity, seems to need only the Grid widget, which should be available in the event
</blockquote></details>

Seeing that `Grid`'s own `CellFocusEventHandler` is also a nested private class I don't see a good reason to change this unless both are changed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 286 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQYypDVd02AQFJ2zB7:-KdQijpuMwpgpqUx8lJ4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L286)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

uhm, can you please revert this check to be a canceling one, e.g. `if (check) return`. Reduces the nesting and improves readability of the method
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 289 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQKEgJkIqRevvNrANu:-KdQjE1z8Gg5PZwl4q11:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L289)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: newline
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java, line 90 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQNQhcKSOEO3CKEmbx:-KdQsCJrZh6osRfio69N:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java#L90)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I have no idea what these if-else does, can you please clarify it a bit in this comment ? I know I could dig into the code, but just a brief reference comment would be nice since the current means from little to nothing
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/HierarchyRendererCellReferenceWrapper.java, line 29 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQZUvtrF9x-ZzsSxQF:-KdQsfpGITsqvrSeV6pM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/client/src/main/java/com/vaadin/client/widget/treegrid/HierarchyRendererCellReferenceWrapper.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you please clarify why this is needed
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdP9V9M5kRZqWBbWvXJ:-KdQpLXxBoP7qOt2mVZv:bs7wumx) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L53)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think being a leaf node should exclude being collapsed.. 
</blockquote></details>

Done. 

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 66 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAA98PVNuieb1BATY:-KdR-dKQV1pun0TmZt0A:bqcaybe) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L66)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I hate it that there is mix of terms, using both collapse and expansion. Should just pick one.
</blockquote></details>

Changed `toggleExpansion` to `toggleCollapse` in `TreeGrid`. Could be changed the other way around though?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPALRq8UepgMfviTxa:-KdQnXx8F-B4zHg5JJdQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L74)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: could for the time being also mention why there is UsOE, e.g. "Not implemented", might save a few seconds from some early testers
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAUZ5681z2wguUpxu:-KdQnYRY3WRuwI4pvfY6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L79)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Same NIT as above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAVXMBkI2V4p0u4js:-KdQnekAM88k5ndjofI1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L84)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Same NIT as above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 90 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAcEv7xw842TyXd2V:-KdQnjj-ss1McZAN3eRy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L90)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Use `IllegalArgumentException` instead
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 96 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBn7qlGXua1EgJT40:-KdQnljEUpeHa5ByGXqQ:b-lze2bj) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L96)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

What is shown by default when this is not set ?
</blockquote></details>

The first column is used.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 96 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBmFvusv-HGoFgbkp:-KdQq_UYvcSdp-1kCDcQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L96)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

javadocs
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 99 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPAkcl5OhGdow21ntc:-KdQpD3MiGWtgcygWp4u:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L99)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Use `IllegalArgumentException` instead
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdQGlXDxM6J1SAD9pAr:-KdR1LwXzEtPZxS83_TO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L101)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Discussed this a bit, concluded that by default, the column that is set as the hierarchical column, could be made as _not hidable_ and not _currently hidden_.

It could be possible for the developer to make the column hidable and hidden if he explicitly wants to, but by default the column showing the hierarchical data should be not those.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 136 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBGijVRnJIYE-9sB4:-KdQo0pmpKzTQU4DpH1_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L136)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

The javadocs currently say that never `null`

Could throw IllegalStateException with message for now, I find it better
</blockquote></details>

Done.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPCDuvNvTK3bxWQELT:-KdQtC_7-hMQ6z6SXik7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L60)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by ahie** [comment]
Review status: 9 of 16 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 136 at r2](https://reviewable.io:443/reviews/vaadin/framework/8572#-KdPBGijVRnJIYE-9sB4:-KdR4TYLpbdb_cmVLoEw:by3dhzc) ([raw file](https://github.com/vaadin/framework/blob/03803c607c5b97cf9339bd085fda3fa291505931/server/src/main/java/com/vaadin/ui/TreeGrid.java#L136)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Apparently `StateGetDoesNotMarkDirtyTest.testGetDoesntMarkStateDirty` test fails if you throw in a getter. Adding this to the exclude list and a comment here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by pleku** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by ahie** [comment]
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8572#-Kd0VnW5Scy3Cv8HNh_Y:-Kd_BOnP2OkJg4os-4Xn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/42a4d827c47c1221befa50ff44c1717828c008a1/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L45)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

7.7.7 commits have not yet been merged to master. Blocked this for now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8572)*

**Pull request merged**
