### PR TITLE
Add APIs to inform components of stale objects in DataProvider

### PR DESCRIPTION
**Pull request by tsuoanttila**
Related to vaadin/framework8-issues#287

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8271)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamyxVjyvr-GB894Omi:-KamyxVjyvr-GB894Omj:b-3dbw1n) (no related file):*
Should also refresh the instance in the key mapper so that e.g. `RendererClickEvent.getItem()` can return the non-stale instance after a refresh, but this can also be done as a separate PR as long as you make sure it will be done.

There were also discussions about doing an internal refresh for any item that we receive from `DataProvider.fetch` based on the assumption that it will always be less stale than anything that is currently being recorded. Was this idea abandoned for some reason, or is that also the topic of another PR?

---

*[server/src/main/java/com/vaadin/data/provider/AbstractDataProvider.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamtZqTSy6b-pTNIxhj:-KamtZqTSy6b-pTNIxhk:b-zi9prk) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/AbstractDataProvider.java#L50)):*
> ```Java
>      *            the function to get an identifier from an item
>      */
>     protected AbstractDataProvider(ValueProvider<T, Object> identifierGetter) {
> ```

Why not make the `getId` method abstract instead? This is an abstract class that already has abstract methods (inherited from the interface), so leaving one more method as abstract would be more logical and more flexible than doing the same through a constructor parameter. Using a callback instance has its place in `BackEndDataProvider` that is already based on callbacks, but I don't think it makes any sense here.

Why do we force developers to explicitly define a getter when there's a safe default (i.e. `t -> t`)  that works reasonably in in most cases?

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvHjhv0i_IK7Dw3nH:-KamvHjhv0i_IK7Dw3nI:b-5nf9fv) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L552)):*
> ```Java
>                         refresh(item);
>                     } else {
>                         getUI().access(() -> reset());
> ```

What's the logic for handling some events with `access` and others without it?

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvYYGQJapqED8yOsn:-KamvYYGQJapqED8yOso:b-ldz42r) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L106)):*
> ```Java
>      * framework to determine equality between two items.
>      * <p>
>      * Default is to use item itself as its own identifier. If the item has
> ```

If there is a defined default, then why isn't it also defined as a `default` method in the interface?

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvR7UKdYGJjwI91y1:-KamvR7UKdYGJjwI91y2:btuh80r) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L107)):*
> ```Java
>      * <p>
>      * Default is to use item itself as its own identifier. If the item has
>      * {@link Object#equals} implemented in a way that it can be compared to
> ```

Both `equals` and `hashCode` is most likely needed in practice.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 111 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamwIMtkNGSNhFdmb5e:-KamwIMugAoXxe_31Z4R:bil69xb) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L111)):*
> ```Java
>      *
>      * @param item
>      *            the item to get identifier for
> ```

Is null allowed?

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamwJfTRBBDNTJrLFZ-:-KamwJfTRBBDNTJrLFZ0:bil69xb) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L112)):*
> ```Java
>      * @param item
>      *            the item to get identifier for
>      * @return the identifier for given item
> ```

Is null allowed?

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvxtAGCf1abq9Zepx:-KamvxtAGCf1abq9Zepy:b-334ju2) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L216)):*
> ```Java
>      */
>     protected boolean selectionContainsId(Object id) {
>         return selection.stream().map(getGrid().getDataProvider()::getId)
> ```

Extract the `DataProvider` to a field so that those getters don't have to be called separately for each item in the list.

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 482 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kamx9Yt7qw7xFo-Arue:-Kamx9Yt7qw7xFo-Aruf:b-xfn5pp) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L482)):*
> ```Java
>         Object refreshId = getGrid().getDataProvider().getId(item);
>         for (int i = 0; i < selection.size(); ++i) {
>             if (getGrid().getDataProvider().getId(selection.get(i))
> ```

Don't call `getGrid().getDataProvider()` separately for each iteration.

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 484 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamweWqbOxsQXEJh9En:-KamweWqbOxsQXEJh9Eo:b-8aeb3n) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L484)):*
> ```Java
>             if (getGrid().getDataProvider().getId(selection.get(i))
>                     .equals(refreshId)) {
>                 selection.remove(i);
> ```

Use `selection.set(i, item);` which is `O(1)` instead of two `O(n)` operations for removing and inserting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 18 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamyxVjyvr-GB894Omi:-KapyuLLHbFgL1iMys_V:b-ig2nx9) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Should also refresh the instance in the key mapper so that e.g. `RendererClickEvent.getItem()` can return the non-stale instance after a refresh, but this can also be done as a separate PR as long as you make sure it will be done.

There were also discussions about doing an internal refresh for any item that we receive from `DataProvider.fetch` based on the assumption that it will always be less stale than anything that is currently being recorded. Was this idea abandoned for some reason, or is that also the topic of another PR?

</blockquote></details>

Internal refresh can be done in either this patch or a follow up PR, does not make that much of a difference anyway. I did the key mapper updating already, waiting for me to push it.

---

*[server/src/main/java/com/vaadin/data/provider/AbstractDataProvider.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamtZqTSy6b-pTNIxhj:-Kapz9BqLe8UjepsBnE_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/AbstractDataProvider.java#L50)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Why not make the `getId` method abstract instead? This is an abstract class that already has abstract methods (inherited from the interface), so leaving one more method as abstract would be more logical and more flexible than doing the same through a constructor parameter. Using a callback instance has its place in `BackEndDataProvider` that is already based on callbacks, but I don't think it makes any sense here.

Why do we force developers to explicitly define a getter when there's a safe default (i.e. `t -> t`)  that works reasonably in in most cases?

</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 552 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvHjhv0i_IK7Dw3nH:-KapzA_04BHqSDJ12j_4:b-1rf81h) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L552)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What's the logic for handling some events with `access` and others without it?
</blockquote></details>

All should be in access to make sure markAsDirty actually functions correctly.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvYYGQJapqED8yOsn:-KapzGBG_kutiY351Qm1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L106)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

If there is a defined default, then why isn't it also defined as a `default` method in the interface?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvR7UKdYGJjwI91y1:-Kaq-c7PVGxMFSQ7zBF5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L107)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Both `equals` and `hashCode` is most likely needed in practice.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 111 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamwIMtkNGSNhFdmb5e:-KapzGhm2t57tBo7k0xU:b2nhky0) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L111)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Is null allowed?
</blockquote></details>

No.

---

*[server/src/main/java/com/vaadin/data/provider/DataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamwJfTRBBDNTJrLFZ-:-KapzS0dhqqigGw-O-X3:b2nhky0) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L112)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Is null allowed?
</blockquote></details>

No.

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamvxtAGCf1abq9Zepx:-KapzanbhzxTQTJgqBxA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L216)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Extract the `DataProvider` to a field so that those getters don't have to be called separately for each item in the list.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 482 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kamx9Yt7qw7xFo-Arue:-KapzWfhgjCiuZoS9iWz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L482)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Don't call `getGrid().getDataProvider()` separately for each iteration.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java, line 484 at r1](https://reviewable.io:443/reviews/vaadin/framework/8271#-KamweWqbOxsQXEJh9En:-KapzWVfxYNebuVI9C8U:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee90b0a3e13a6185e5bfe9817f807cdb8244ab01/server/src/main/java/com/vaadin/ui/components/grid/MultiSelectionModelImpl.java#L484)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Use `selection.set(i, item);` which is `O(1)` instead of two `O(n)` operations for removing and inserting.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by Legioth** [comment]
:lgtm:

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271#-:-KavHZf-u3uZ886EQLiG:bnfp4nl)*

**Comment by Legioth** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-Kaw9X5Zrlb2A06oNBN0:b-od2aww) (no related file):*
Should also update `documentation/datamodel/datamodel-providers.asciidoc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by ahie** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kb9Evq0trSSWb1uH9U1:-Kb9Evq1p-KiRdbgz6Ir:bb04pr5) ([raw file](https://github.com/vaadin/framework/blob/b673adb91d6d76a488efd1c2f03d0ee5e431338f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L74)):*
> sizeCallback

identifierGetter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 74 at r2](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kb9Evq0trSSWb1uH9U1:-Kb9kjLfs_kEoa7aHx0y:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b673adb91d6d76a488efd1c2f03d0ee5e431338f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L74)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> sizeCallback

identifierGetter
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 18 files at r1, 12 of 13 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-Kb9l4fl5y6-B6Xu-gRO:bspbnsl) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Should also update `documentation/datamodel/datamodel-providers.asciidoc`
</blockquote></details>

So we had a long discussion with a design provided by Leif for this feature.
Is it totally ruined and ignored ?

I don't remember the whole details but here the simplest way is chosen which I kind of dislike a lot (in the perfect world).
The main concerns at least were:
- No one ever can rely on `equals` and 'hash` implementation (for objects that are not under your control) in the API design
- Default `t->t` is bad because it will be WTH (why it doesn't work ?) and above reasons.

The contract via API to avoid WTH described above has to be explicitly defined to support "refresh" functionality .
That what the document was about.

Is it so that decision has been made to forget about those issues ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-Kb9vw1P5uWDVtUykyfQ:bwi0iux) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

So we had a long discussion with a design provided by Leif for this feature.
Is it totally ruined and ignored ?

I don't remember the whole details but here the simplest way is chosen which I kind of dislike a lot (in the perfect world).
The main concerns at least were:
- No one ever can rely on `equals` and 'hash` implementation (for objects that are not under your control) in the API design
- Default `t->t` is bad because it will be WTH (why it doesn't work ?) and above reasons.

The contract via API to avoid WTH described above has to be explicitly defined to support "refresh" functionality .
That what the document was about.

Is it so that decision has been made to forget about those issues ?
</blockquote></details>

This implementation is basically a subset of the stuff that I designed a couple of months ago.

The idea is that we either require all users to always explicitly define something with guaranteed equality semantics, or alternatively we hope that it's close enough in most cases and just provide a way of doing something custom in other cases. Today the assumption is that such a default is good enough in so many cases that it wouldn't be worthwhile to force all developers to explicitly define something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-Kb9ws0AC6qqMRRcBypw:beftjxl) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This implementation is basically a subset of the stuff that I designed a couple of months ago.

The idea is that we either require all users to always explicitly define something with guaranteed equality semantics, or alternatively we hope that it's close enough in most cases and just provide a way of doing something custom in other cases. Today the assumption is that such a default is good enough in so many cases that it wouldn't be worthwhile to force all developers to explicitly define something.
</blockquote></details>

OK......
I can accept that.

But just for the record: I'm as an application developer would be swearing a lot because of this implementation.
It would happen quite soon after (almost any) project start: since there is no `equals` and `hash` contract explicitly defined it means that once it changed it breaks the application. And since it's too easy to change those methods it will introduce a lot of confusion which _cannot be easily detected_ (that's the most important thing). 
(I can decide to change those methods because of writing Unit tests e.g.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-KbA8jfTBRiZd7G_kh-t:b-pt2g88) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK......
I can accept that.

But just for the record: I'm as an application developer would be swearing a lot because of this implementation.
It would happen quite soon after (almost any) project start: since there is no `equals` and `hash` contract explicitly defined it means that once it changed it breaks the application. And since it's too easy to change those methods it will introduce a lot of confusion which _cannot be easily detected_ (that's the most important thing). 
(I can decide to change those methods because of writing Unit tests e.g.)
</blockquote></details>

It might make sense to force the users of BackEndDataProvider to provide the ID method, just to make sure it does not go unnoticed. The default will most likely not work in their case anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8271#-Kaw9X5Ye3O0WvQqRnNR:-KbA90MCbX1SbkXNRzSv:bc3adxz) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

It might make sense to force the users of BackEndDataProvider to provide the ID method, just to make sure it does not go unnoticed. The default will most likely not work in their case anyway.
</blockquote></details>

The default will work in **all** cases with immutable data. Please don't make that case more complex than necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 363 at r4](https://reviewable.io:443/reviews/vaadin/framework/8271#-KbAhC7ZpLAdug3hssO6:-KbAhC7_ZXy-yElk-3D1:b-4gqezi) ([raw file](https://github.com/vaadin/framework/blob/fe76a08b3bca7d27e07a943373f6ea3371247c94/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L363)):*
> ```Java
>         DataProvider<T, ?> dataProvider = internalGetDataProvider();
>         Object id = dataProvider.getId(item);
>         return selection.stream().map(i -> dataProvider.getId(i))
> ```

Let's avoid single letter variables.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 7 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 363 at r4](https://reviewable.io:443/reviews/vaadin/framework/8271#-KbAhC7ZpLAdug3hssO6:-KbF8oyH_gQ8suYyoxtL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fe76a08b3bca7d27e07a943373f6ea3371247c94/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L363)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Let's avoid single letter variables.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 389 at r7](https://reviewable.io:443/reviews/vaadin/framework/8271#-KbFyG5Hrxv9fpAgjksO:-KbFyG5Hrxv9fpAgjksP:boxnmxq) ([raw file](https://github.com/vaadin/framework/blob/0cd9c48f7dd76f4f102de6c60895c0d11e393d4d/documentation/datamodel/datamodel-providers.asciidoc#L389)):*
> ```AsciiDoc
> For example Spring Data gives you new instances with every request, and making changes to the repository will make old instances of the same object "stale".
> In these cases you should inform any interested component by calling `dataProvider.refreshItem(newInstance)`. This will work out of the box, if your beans have
> good equals and hashCode implementations. Since that is not always the case, the user of a `CallbackDataProvider` can give it a `ValueProvider` that will provide 
> ```

The way that you mean "good" is actually "bad" for me.
Let's avoid "good" or "bad" here.

If it's a short mention then it can be "appropriate" otherwise: methods are based on "id" ONLY (or something like this).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 385 at r7](https://reviewable.io:443/reviews/vaadin/framework/8271#-KbJXdze-6_FFN8Rz3HO:-KbJXdzfSjxr7KEGPfXe:b-lc4ex7) ([raw file](https://github.com/vaadin/framework/blob/0cd9c48f7dd76f4f102de6c60895c0d11e393d4d/documentation/datamodel/datamodel-providers.asciidoc#L385)):*
> ```AsciiDoc
> === Refreshing
> 
> All data providers support have the `refreshAll`and `refreshItem` methods. These methods can be used when data in the backend has been updated.
> ```

This introduction doesn't give any indication for why it would be necessary to use `refreshAll` or `refreshItem`. This means that as a reader, I might just as well skip the entire section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by Legioth** [comment]
Review status: 25 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 389 at r7](https://reviewable.io:443/reviews/vaadin/framework/8271#-KbFyG5Hrxv9fpAgjksO:-KbJik4h26_cISIpzXOl:bu31gtd) ([raw file](https://github.com/vaadin/framework/blob/0cd9c48f7dd76f4f102de6c60895c0d11e393d4d/documentation/datamodel/datamodel-providers.asciidoc#L389)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The way that you mean "good" is actually "bad" for me.
Let's avoid "good" or "bad" here.

If it's a short mention then it can be "appropriate" otherwise: methods are based on "id" ONLY (or something like this).
</blockquote></details>

Rephased

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Comment by denis-anisimov** [comment]
Needs rebase.

**Comment by denis-anisimov** [comment]
Reviewed 7 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8271)*

**Pull request merged**
