### PR TITLE
Change Upload to be in immediate mode by default

### PR DESCRIPTION
**Pull request by pleku**
Fixes vaadin/framework8-issues#547

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/111)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm: - note, though, that the semantics of old declarative files with v-upload without overridden immediate mode will change

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111#-:-KYXtLsbPc91qZq0Ek6h:b-73kujr)*

**Comment by Legioth** [comment]
Wouldn't a proper migration update old declarative files to use `<vaadin7-upload>` instead, and thus not cause any changes?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111#-:-KYYEuv89jjLgpcw73k4:b7vtvfi)*

**Comment by pleku** [comment]
@legioth that is what will happen yes.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111#-:-KYYI7T4M9Pj-jjgftGH:b-xmtqu5)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Upload.java, line 1126 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmOj6PHySfvfHIuIn5:-KYmOj6PHySfvfHIuIn6:brsbk79) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/server/src/main/java/com/vaadin/ui/Upload.java#L1126)):*
> ```Java
>      * <p>
>      * If the upload is in immediate mode, it displays only a Vaadin button
>      * which triggers both: the selecting of the file to upload, and starts the
> ```

I'd say something like "... lets the user select the file to upload and then immediately starts the upload."

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmP4DN4PNgXHbIZJNC:-KYmP4DN4PNgXHbIZJND:b5v99jx) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java#L38)):*
> ```Java
>     protected void setup(VaadinRequest request) {
> 
>         // by default is in immediate mode (since 8.0ßs)
> ```

I wouldn't use the esszet character here

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmPCSuMY2fJZ2mFhoO:-KYmPCSuMY2fJZ2mFhoP:boi4dva) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java#L45)):*
> ```Java
>         Upload immediateUpload = new Upload();
>         immediateUpload.setId("upload");
>         immediateUpload.setImmediateMode(false);
> ```

rename variables as they no longer reflect the reality

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Upload.java, line 1126 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmOj6PHySfvfHIuIn5:-KYnK-7sed6ez7jOGF3g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/server/src/main/java/com/vaadin/ui/Upload.java#L1126)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd say something like "... lets the user select the file to upload and then immediately starts the upload."
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmP4DN4PNgXHbIZJNC:-KYnK2Rv4gm0UDzgMDgU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I wouldn't use the esszet character here
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java, line 45 at r2](https://reviewable.io:443/reviews/vaadin/framework/111#-KYmPCSuMY2fJZ2mFhoO:-KYnKAdheLvzAOIxEbTb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f0a8a7cc541070dfeabd45052b93926cfbb47e36/uitest/src/main/java/com/vaadin/tests/themes/valo/ImmediateUpload.java#L45)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

rename variables as they no longer reflect the reality
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/111#-:-KYnKj_MsmQ07NTW49pE:bnfp4nl)*

**Pull request merged**
