### PR TITLE
Grid hides horizontal scroll after resize if it had non zero scroll position (#19189)

### PR DESCRIPTION
**Pull request by jreznot**
Fixes issues: 
* https://dev.vaadin.com/ticket/19189
* https://dev.vaadin.com/ticket/20254
* https://dev.vaadin.com/ticket/19622

### CODE REVIEW

**Comment by denis-anisimov** [comment]
The patch requires a test.
Will you provide a test or we should take care about it ?

**Comment by jreznot** [comment]
Sorry, I can't implement test with Scrolling using TestBench. But if you just open the commit you will see the actual problem not only with Scrolling and Scrollbar size but also with resource management. 

Test case is described here: https://dev.vaadin.com/ticket/20254#comment:5

**Comment by denis-anisimov** [comment]
OK, thanks, I will look what to do with that.

**Comment by denis-anisimov** [comment]
We are still using Gerrit for Framework. 
I cannot merge your patch using Pull request.
I've updated your original code and added a test.
It's here: https://dev.vaadin.com/review/14761
Could you please let me know whether you have signed contribution agreement ?
We need it to accept the code.
Let's proceed further in https://dev.vaadin.com/review/14761.
Thanks.

**Comment by denis-anisimov** [comment]
Will keep it open util it's integrated.

**Comment by jreznot** [comment]
I've signed CA ~ 2013 year, please see my Gerrit profile.

**Comment by jreznot** [comment]
Huh! I see really nice (vaadin contributor) badge on my messages (header) in this topic. You can detect guys that have already commited to Vaadin using these badges.

**Comment by denis-anisimov** [comment]
Yes, I see that you have signed CA.
"vaadin contributor" doesn't relate to CLA as I understand.

**Pull request closed without merging**
