### PR TITLE
Pull request template candidate

### PR DESCRIPTION
**Pull request by jtomass**
Initial candidate.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10813)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5YhPBFr86LcpcyG5:-L9p5YhQEbsPg4f8TCiw:b-4i0ors) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
> ```Markdown
> Please confirm that your pull request provides enough information so that we can review your pull request.
> 
> - Does your PR follow our contributing guidelines?  
> ```

Link to guidelines?

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5cA07d1vfBA0nqg7:-L9p5cA07d1vfBA0nqg8:b-n9e09n) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L5)):*
> ```Markdown
> 
> - Does your PR follow our contributing guidelines?  
> - Does your PR have the required tests?  
> ```

Link to testbench?

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5fzDAA4x4fbtn4lo:-L9p5fzDAA4x4fbtn4lp:b-716y78) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L6)):*
> ```Markdown
> - Does your PR follow our contributing guidelines?  
> - Does your PR have the required tests?  
> - What issue or behavior does your PR fix?  
> ```

- Does the pull request description describe what is fixed by the change
- Does the pull request description contain a link to the fixed issue

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5zLc3lODpkQBixhm:-L9p5zLc3lODpkQBixhn:bw1tzru) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L7)):*
> ```Markdown
> - Does your PR have the required tests?  
> - What issue or behavior does your PR fix?  
> ```

I think we also need to list at least some formatting requirements/tips

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Comment by jtomass** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5YhPBFr86LcpcyG5:-L9pxHbn4P2ZuCdzrxnu:b15ptgb) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Link to guidelines?
</blockquote></details>

Added from repository

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5cA07d1vfBA0nqg7:-L9pxXZwCUzEHuQYD9wO:bdn90my) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L5)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Link to testbench?
</blockquote></details>

Should rather be added to contributing

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5fzDAA4x4fbtn4lo:-L9pxb8k1eDUSCVcAfYL:bb3p1fd) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L6)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

- Does the pull request description describe what is fixed by the change
- Does the pull request description contain a link to the fixed issue
</blockquote></details>

Replaced.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 7 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5zLc3lODpkQBixhm:-L9pxe3p0laCzU7TUxvT:b-twfjdp) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L7)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I think we also need to list at least some formatting requirements/tips
</blockquote></details>

Should also be rather added to contributing.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Comment by jtomass** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9p5YhPBFr86LcpcyG5:-L9v2iV4-2ksk-5iHfD0:b7hd0ph) ([raw file](https://github.com/vaadin/framework/blob/1522b3323280e9c2ddbdcd459788788b83b2236d/.github/PULL_REQUEST_TEMPLATE.md#L4)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Well, this is a template, It does not work as documentation, thus md-style links do not work, the PR author does nol see them as formatted text. IMHO the template should be like:

```text
<Here be a short description, for example "Better events handling in Grid">

Fixes #<here be an issue number>
---- Check and then cut here ----
[ ] Tests are done
[ ] Contributing guidelines implemented  
```

</blockquote></details>

Forgot about the md. 
Overhauled the template to a different style.
Not sure in the end if we need a better link than just point to the contributing, its sitting in the root of the repository after all. I could be wrong also about that.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813#-:-L9yuUzqACyPT6fXND5a:bnfp4nl)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 1 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9zHoISEF1ni6nAp5JQ:-L9zHoITD9oJn-jraqnV:bpih1hy) ([raw file](https://github.com/vaadin/framework/blob/766ae2392f7d22f404c4d8481169544d10ff2bf7/.github/PULL_REQUEST_TEMPLATE.md#L1)):*
> ```Markdown
> Thanks for submitting a pull request!  
> ```

extra spaces in every line

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 9 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9zHubK2vgoaNgAZiSA:-L9zHubK2vgoaNgAZiSB:b-m4dl98) ([raw file](https://github.com/vaadin/framework/blob/766ae2392f7d22f404c4d8481169544d10ff2bf7/.github/PULL_REQUEST_TEMPLATE.md#L9)):*
> ```Markdown
> 
> **Check when you have completed**  
> [ ] Valid tests for the pull requests  
> ```

Why plural `requests`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Comment by jtomass** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 9 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10813#-L9zHubK2vgoaNgAZiSA:-LA3ZWnq9nmSE8ljWVCq:b-ze8enu) ([raw file](https://github.com/vaadin/framework/blob/766ae2392f7d22f404c4d8481169544d10ff2bf7/.github/PULL_REQUEST_TEMPLATE.md#L9)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why plural `requests`?
</blockquote></details>

Have to admin that it's an honest oversight.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10813)*

**Pull request merged**
