### PR TITLE
Fix making components visible by push

### LINKED ISSUE #9905: Push issues on layout visibility change (8.1.0+)
I've been experiencing a bug when using Push with every 8.1.x version so far.
I've tried using all Push modes and transport options. Same results.

I tried getting help [on the forum](https://vaadin.com/forum#!/thread/16544362), but no one has answered so far.

Everything works as expected if I use Vaadin 8.0.7.
When using 8.1.x, every time a Layout is hidden, pushed and made visible again, an exception is thrown on client side console and the DOM gets deformed/corrupted.

`com.vaadin.client.communication.MessageHandler
SEVERE: Error sending hierarchy change events
com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : bx(...) is null`

No server side exceptions are thrown.

If it helps, what I'm doing is this:
- View loads a Grid with entities.
- When an element in the Grid is selected, a Layout is shown (which allows editing the entity). This Layout is animated.
- If an element in the Grid is selected after this, the Layout is hidden and UI.getcurrent().push() is called in order to hide it on the client side.
- The Layout if filled with the information from the selected element in the Grid and is set visible again. This is when the client exception is thrown and DOM gets broken.
- If I hide a Button, Label or other Components and use Push, it works as expected. This bug seems to affect Layouts only.

Regards.

### PR DESCRIPTION
**Pull request by hesara**
Fix connector tracker cleanup for the case where a component is
hidden by a request and is made visible again by push.

This fixes a regression caused by #9305.

Fixes #9905

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9934)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 271 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLgLd8EqqR1I5e7_JX:-KtLgLd8EqqR1I5e7_JY:b-g6gw62) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L271)):*
> ```Java
>      *
>      * @param force
>      *            true to force cleaning
> ```

{@code true}

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLgIaFKCFvBs-AHmUd:-KtLgIaFKCFvBs-AHmUe:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L272)):*
> ```Java
>      * @param force
>      *            true to force cleaning
>      */
> ```

since tag

---

*[uitest/src/main/java/com/vaadin/tests/push/MakeComponentVisibleWithPush.java, line 104 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLh7wR33tbWplv_Y3w:-KtLh7wR33tbWplv_Y3x:b-4yr6dt) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/uitest/src/main/java/com/vaadin/tests/push/MakeComponentVisibleWithPush.java#L104)):*
> ```Java
>     }
> 
> }
> ```

newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9934)*

**Comment by hesara** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 271 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLgLd8EqqR1I5e7_JX:-KtLmXNecpLuDXyenlzE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L271)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

{@code true}
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLgIaFKCFvBs-AHmUd:-KtLmXlgHfbHpzsAI8LL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L272)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/push/MakeComponentVisibleWithPush.java, line 104 at r1](https://reviewable.io:443/reviews/vaadin/framework/9934#-KtLh7wR33tbWplv_Y3w:-KtLmYj6zAH2hRzJZJM5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/763eac97cc8ca287a89616160a6ec481bbd0d037/uitest/src/main/java/com/vaadin/tests/push/MakeComponentVisibleWithPush.java#L104)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9934)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9934#-:-KtM6coF4cotgFnHRpWv:bnfp4nl)*

**Comment by hesara** [comment]
Marking this with milestone 8.2.0.alpha1 for now, but we can probably also pick this to 8.1.x.

**Pull request merged**
