### PR TITLE
Re-enable the Atmosphere heartbeat interceptor (#6457)

### PR DESCRIPTION
**Pull request by peholmst**
It appears this is no longer a problem and a customer needs this functionality. Still waiting for confirmation from the Atmosphere team since the ticket is still open on their side.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9877)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
@Artur- how should one go about testing this feature? can it be tested automatically somehow? How do we make sure this won't break any existing stuff?

**Comment by Artur-** [comment]
https://github.com/Atmosphere/atmosphere-javascript/issues/141

I would guess:
1. Use long polling
2. Enable Atmosphere heartbeat
3. Wait for heartbeat to close the connection
4. Check that the app still works

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/9877)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Artur-)

**Review by elmot — APPROVED** [review]
Rebased, tested, works.
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/9877#-:-LLinzhu4dE-2Z_wFdiy:bvnhwja)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Artur-)

**Pull request merged**
