### PR TITLE
Use autoboxing between primitive types and Object wrappers

### PR DESCRIPTION
**Pull request by asashour**
Also, better string concatenation.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10043)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 136 of 180 files at r1.
Review status: 136 of 180 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ9lJf_1MYeR9TLDoX:-KuZ9lJf_1MYeR9TLDoY:b-5v2fin) (no related file):*
I don't really like auto-boxing and auto-unboxing much except in the most trivial cases as it saves a few characters at the time of writing code but costs a lot more when reading code (which happens a lot more) by forcing the reader to think about types, conversions etc. Furthermore, it easily introduces hard to spot bugs.

Did a partial review with some comments.

---

*[client/src/main/java/com/vaadin/client/LayoutManager.java, line 233 at r1](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ5HU_tfAJ2mbluY4V:-KuZ5HU_tfAJ2mbluY4W:b-emqcwp) ([raw file](https://github.com/vaadin/framework/blob/875574de67834ca01723395c1c3410efb6309f49/client/src/main/java/com/vaadin/client/LayoutManager.java#L233)):*
> ```Java
>             count = 0;
>         } else {
>             count++;
> ```

This will not work as it does not update the Integer type variable value.

---

*[server/src/main/java/com/vaadin/server/VaadinSession.java, line 899 at r1](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ756hptPWucAhwfoB:-KuZ756hptPWucAhwfoC:b7fzu84) ([raw file](https://github.com/vaadin/framework/blob/875574de67834ca01723395c1c3410efb6309f49/server/src/main/java/com/vaadin/server/VaadinSession.java#L899)):*
> ```Java
>         uIs.remove(id);
>         String embedId = ui.getEmbedId();
>         if (embedId != null && id == embedIdMap.get(embedId)) {
> ```

(this happens to work as both are converted to int, but I feel this code is a lot more fragile than the previous code with explicit types - a small change above could make this a comparison of object references rather than of ints)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by asashour** [comment]
Review status: 136 of 180 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/LayoutManager.java, line 233 at r1](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ5HU_tfAJ2mbluY4V:-KuZBfvPHU7uNmx5cYqs:b-uv9xcl) ([raw file](https://github.com/vaadin/framework/blob/875574de67834ca01723395c1c3410efb6309f49/client/src/main/java/com/vaadin/client/LayoutManager.java#L233)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This will not work as it does not update the Integer type variable value.
</blockquote></details>

I tested before committing, and the below code prints `2` on the server-side. Need to check on the client-side.

    Integer i = 1;
    i++;
    System.out.println(i);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by asashour** [comment]
Review status: 136 of 180 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ9lJf_1MYeR9TLDoX:-KuZDRpoUBPYGq1l76Au:b-273voe) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't really like auto-boxing and auto-unboxing much except in the most trivial cases as it saves a few characters at the time of writing code but costs a lot more when reading code (which happens a lot more) by forcing the reader to think about types, conversions etc. Furthermore, it easily introduces hard to spot bugs.

Did a partial review with some comments.
</blockquote></details>

As always, you lead the way.

Please close this PR if you think otherwise, or point out the places to be reverted.

---

*[server/src/main/java/com/vaadin/server/VaadinSession.java, line 899 at r1](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ756hptPWucAhwfoB:-KuZDN7dODtD6lJexIvZ:bp3aow6) ([raw file](https://github.com/vaadin/framework/blob/875574de67834ca01723395c1c3410efb6309f49/server/src/main/java/com/vaadin/server/VaadinSession.java#L899)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this happens to work as both are converted to int, but I feel this code is a lot more fragile than the previous code with explicit types - a small change above could make this a comparison of object references rather than of ints)
</blockquote></details>

Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by asashour** [comment]
Review status: 136 of 180 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/LayoutManager.java, line 233 at r1](https://reviewable.io:443/reviews/vaadin/framework/10043#-KuZ5HU_tfAJ2mbluY4V:-KucbpzA3Lu_vsnbeFsn:b-ssu5iy) ([raw file](https://github.com/vaadin/framework/blob/875574de67834ca01723395c1c3410efb6309f49/client/src/main/java/com/vaadin/client/LayoutManager.java#L233)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I tested before committing, and the below code prints `2` on the server-side. Need to check on the client-side.

    Integer i = 1;
    i++;
    System.out.println(i);

</blockquote></details>

I tested on the client side, and it also works fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by hesara** [comment]
Reviewed 14 of 180 files at r1, 2 of 20 files at r3, 10 of 28 files at r4, 31 of 35 files at r5.
Review status: 158 of 179 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by hesara** [comment]
Reviewed 10 of 180 files at r1, 3 of 28 files at r4, 4 of 35 files at r5.
Review status: 174 of 179 files reviewed at latest revision, 12 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java, line 81 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb880dpO1GRVxf1kC8:-Kvb880dpO1GRVxf1kC9:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java#L81)):*
> ```Java
>                         try {
>                             layout.getPosition(component)
>                                     .setTopValue((float) (clientY - top));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java, line 83 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8dtuIad3ht3Rvxhv:-Kvb8dtuIad3ht3Rvxhw:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java#L83)):*
> ```Java
>                                     .setTopValue((float) (clientY - top));
>                             layout.getPosition(component).setLeftValue(
>                                     (float) (clientX - left));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java, line 105 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8fMfgUAqKoHdNo04:-Kvb8fMgO88ythQWZUny:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java#L105)):*
> ```Java
>                         try {
>                             layout.getPosition(component)
>                                     .setTopValue((float) (clientY - top));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java, line 107 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8frFuFP4PrGyivlm:-Kvb8frFuFP4PrGyivln:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java#L107)):*
> ```Java
>                                     .setTopValue((float) (clientY - top));
>                             layout.getPosition(component).setLeftValue(
>                                     (float) (clientX - left));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java, line 365 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8gtWfkMRANbhEuA2:-Kvb8gtWfkMRANbhEuA3:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java#L365)):*
> ```Java
>                 l.addComponent(fileIcon);
>                 ComponentPosition position = l.getPosition(fileIcon);
>                 position.setTop((float) ((y++ / 5) % 5 * 100),
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java, line 367 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8hfp9ykvQSM6ZQF2:-Kvb8hfqLb7VTPgcdt3J:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java#L367)):*
> ```Java
>                 position.setTop((float) ((y++ / 5) % 5 * 100),
>                         UNITS_PIXELS);
>                 position.setLeft((float) (x++ % 5 * 100), UNITS_PIXELS);
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java, line 89 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8inLE0z6LLuBMskh:-Kvb8inLE0z6LLuBMski:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java#L89)):*
> ```Java
>                 try {
>                     root.getPosition(component)
>                             .setTopValue((float) (clientY - top));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java, line 91 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8jOBER3v3o_IZkb2:-Kvb8jOBER3v3o_IZkb3:b-bdxd49) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java#L91)):*
> ```Java
>                             .setTopValue((float) (clientY - top));
>                     root.getPosition(component)
>                             .setLeftValue((float) (clientX - left));
> ```

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.

---

*[uitest/src/main/java/com/vaadin/tests/serialization/SerializerTest.java, line 90 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb97WlrOFXQ_QjGgEe:-Kvb97WmWgX4z2hAmdAx:b-b3cfop) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/serialization/SerializerTest.java#L90)):*
> ```Java
>                 false };
> 
>         rpc.sendByte((byte) 5, (byte) -12,
> ```

I'd keep this file untouched, as the explicit boxing is intentionally there for testing certain cases and making it implicit makes it easy to accidentally make the test not check what it should.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 58 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb9r5AflM8Z5e8EXAq:-Kvb9r5AflM8Z5e8EXAr:b8unjex) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L58)):*
> ```Java
> 
>                 SimpleTestBean firstValue = generics.values().iterator().next()
>                         .get(1).get(0);
> ```

I'd also revert the change here, as having an object as a map key and an int as a list index is clearer to the reader.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 126 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-KvbA9NcGvzvhoyuuCqo:-KvbA9NcGvzvhoyuuCqp:b-jqslg0) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L126)):*
> ```Java
>             @Override
>             public void sendLong(long value, Long boxedValue, long[] array) {
>                 rpc.sendLong(array[0], value,
> ```

I believe also here and in the calls below in this file, the explicit boxing was intentional to make it clear what we are testing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by asashour** [comment]
Review status: 173 of 175 files reviewed at latest revision, 12 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java, line 81 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb880dpO1GRVxf1kC8:-Kvjdijd6ODgZ9dDWqdk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java#L81)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java, line 83 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8dtuIad3ht3Rvxhv:-KvjdkFIC7ofm_7ar6R4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptAnythingWindow.java#L83)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java, line 105 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8fMfgUAqKoHdNo04:-Kvjdo_ILmSmHu0L07rM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java#L105)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java, line 107 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8frFuFP4PrGyivlm:-Kvjdp8OrSjHut-P2Sox:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/AcceptFromComponent.java#L107)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java, line 365 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8gtWfkMRANbhEuA2:-Kvje1LWEYEzGI2dSgAZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java#L365)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java, line 367 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8hfp9ykvQSM6ZQF2:-Kvje1kNu_HbRs5A1unI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DDTest6.java#L367)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java, line 89 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8inLE0z6LLuBMskh:-Kvje8MioP6urW5DEcIp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java#L89)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java, line 91 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb8jOBER3v3o_IZkb2:-Kvje8lQcKY1kuKtIQQh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/dd/DragDropPane.java#L91)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In these, we'd rather keep Float.valueOf than add a dummy cast and auto-boxing.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/serialization/SerializerTest.java, line 90 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb97WlrOFXQ_QjGgEe:-KvjeYYoAN5RKbXBuF_x:b9fmotc) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/serialization/SerializerTest.java#L90)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd keep this file untouched, as the explicit boxing is intentionally there for testing certain cases and making it implicit makes it easy to accidentally make the test not check what it should.
</blockquote></details>

All reverted, and upper casing 'L' at the end.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 58 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-Kvb9r5AflM8Z5e8EXAq:-Kvjeyl3B9T264k6sFNP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L58)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd also revert the change here, as having an object as a map key and an int as a list index is clearer to the reader.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 126 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-KvbA9NcGvzvhoyuuCqo:-KvjfMMlE1EJECHG1OZo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L126)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I believe also here and in the calls below in this file, the explicit boxing was intentional to make it clear what we are testing here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by tsuoanttila** [comment]
Reviewed 4 of 6 files at r6.
Review status: 174 of 175 files reviewed at latest revision, 8 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 126 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-KvbA9NcGvzvhoyuuCqo:-KwdKOULo9fdSF9n7Wsp:bpvq5u2) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L126)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The intentional boxing of the following methods should still be reverted.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 142 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdK_l5IKdglnpiQpWC:-KwdK_l5IKdglnpiQpWD:b-s8ti2p) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L142)):*
> ```Java
>             @Override
>             public void sendInt(int value, Integer boxedValue, int[] array) {
>                 rpc.sendInt(array.length, array[0],
> ```

intentional boxing of `array[0]`

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 150 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKgRXoe7r-0gGG9D8:-KwdKgRXoe7r-0gGG9D9:b-c3gn3z) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L150)):*
> ```Java
>                     float[] array) {
>                 Arrays.sort(array);
>                 rpc.sendFloat(boxedValue, value, array);
> ```

intentional boxing of `value`

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 156 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKkMrncPiwXluHDko:-KwdKkMrncPiwXluHDkp:bhll0aa) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L156)):*
> ```Java
>             public void sendDouble(double value, Double boxedValue,
>                     double[] array) {
>                 rpc.sendDouble(value + boxedValue, value - boxedValue,
> ```

intentional boxing of `value - boxedValue.doubleValue()`

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 169 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKppQI1385D4YNgNT:-KwdKppQI1385D4YNgNU:b-c3gn3z) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L169)):*
> ```Java
>                     char[] array) {
>                 rpc.sendChar(Character.toUpperCase(boxedValue.charValue()),
>                         value, new String(array).toLowerCase().toCharArray());
> ```

intentional boxing of `value`

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 187 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKrqYMvoJK5drcFbU:-KwdKrqYMvoJK5drcFbV:bkwa4zi) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L187)):*
> ```Java
>                     inverseArray[i] = !array[i];
>                 }
>                 rpc.sendBoolean(boxedValue == Boolean.TRUE, !value,
> ```

intentional boxing of `!value`

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 222 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKu4lr1IcrRM_yltx:-KwdKu4lr1IcrRM_ylty:b-5enhzp) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L222)):*
> ```Java
>                 for (int[] array : primitiveArrayList) {
>                     updatedObjectArrayList
>                             .add(new Integer[] { array.length, array[0] });
> ```

intentional boxing of the Integer array individual values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Comment by asashour** [comment]
Review status: 174 of 175 files reviewed at latest revision, 8 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 126 at r5](https://reviewable.io:443/reviews/vaadin/framework/10043#-KvbA9NcGvzvhoyuuCqo:-KwivX2tG8h8F7Bfw2-X:btdsfzr) ([raw file](https://github.com/vaadin/framework/blob/f123913e181f12efcc585573aafae4a2519ca705/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L126)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The intentional boxing of the following methods should still be reverted.
</blockquote></details>

I see.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 142 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdK_l5IKdglnpiQpWC:-KwiyttVh_Pct5KwoWiZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L142)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of `array[0]`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 150 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKgRXoe7r-0gGG9D8:-KwizMgJ7VIanPK5-HAX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L150)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of `value`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 156 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKkMrncPiwXluHDko:-KwizM5fO264Wr8DPeKz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L156)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of `value - boxedValue.doubleValue()`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 169 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKppQI1385D4YNgNT:-KwizVGyTkVTXkhWpyv9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L169)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of `value`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 187 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKrqYMvoJK5drcFbU:-KwizaC1Mk6SMdbJnG-B:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L187)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of `!value`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java, line 222 at r6](https://reviewable.io:443/reviews/vaadin/framework/10043#-KwdKu4lr1IcrRM_yltx:-Kwiztl8tP45pi_xIRMS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9d741dfab9446097c976c17986981aa7ee704bac/uitest/src/main/java/com/vaadin/tests/widgetset/client/SerializerTestConnector.java#L222)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

intentional boxing of the Integer array individual values.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10043)*

**Pull request closed without merging**
