### PR TITLE
Hide DataGenerator from Column API

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9351)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2019 at r1](https://reviewable.io:443/reviews/vaadin/framework/9351#-KkLPAQ1Y9KEMPJTDCFy:-KkLPAQ1Y9KEMPJTDCFz:b-kqco3p) ([raw file](https://github.com/vaadin/framework/blob/082584fd130e4053dbda7873be8c8c518f2a345f/server/src/main/java/com/vaadin/ui/Grid.java#L2019)):*
> protected

Could this be private instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9351)*

**Comment by ahie** [comment]
This change should probably be mentioned in the release notes, otherwise :lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9351#-:-KkLUzWrMEqXwsBPDlxH:bislcd7)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2019 at r1](https://reviewable.io:443/reviews/vaadin/framework/9351#-KkLPAQ1Y9KEMPJTDCFy:-KkLVBgmMJUOOE6bBqIp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/082584fd130e4053dbda7873be8c8c518f2a345f/server/src/main/java/com/vaadin/ui/Grid.java#L2019)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> protected

Could this be private instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9351)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9351)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9351)*

**Pull request merged**
