### PR TITLE
Provide declarative support for Grid.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#390

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7961)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 9 of 13 files at r1, 3 of 3 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYqxC0zI476Bg6NZKyu:by29vp6) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
> ```Java
> 
>     /**
>      * Writes the component own only state to the given design.
> ```

Don't understand this line, component own only ?.  Only AbstractListing´s state ? 

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 279 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqx_FDTa2ho8ssrh0Y:-KYqx_FDTa2ho8ssrh0Z:b-20a2bc) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L279)):*
> ```Java
>      * <p>
>      * Whereas {@link #writeDesign(Element, DesignContext)} writes all the state
>      * (including state from superclass) this method writes only own component
> ```

replace "only own component state" with "only the state at this level."

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 356 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxv-pLxhQgBQGDHLc:-KYqxv-pLxhQgBQGDHLd:bwe4xwo) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L356)):*
> ```Java
> 
>     /**
>      * Reads the component own only state from the given design.
> ```

replace "the component own only state" with "the component's state at this level"

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1810 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr5Y5gSLVARCQCMqtP:-KYr5Y5gSLVARCQCMqtQ:b-hogwqd) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1810)):*
> ```Java
>             ColumnState defaultState = new ColumnState();
> 
>             DesignAttributeHandler.writeAttribute("column-id", attributes,
> ```

Not sure if this should be just "identifier". Probably not a part of this since the Column API will change a bit.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1813 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqyTh2cQNJUrzIHY1p:-KYqyTh2cQNJUrzIHY1q:b36502c) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1813)):*
> ```Java
>                     getId(), null, String.class, designContext);
> 
>             // Sortable is a special attribute that depends on the container.
> ```

depends on the data provider ?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1867 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqztadQYCbqJVe7tl8:-KYqztaeDQe7sr8Jlhvs:b-z8gx01) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1867)):*
> ```Java
>             }
>             if (design.hasAttr("editable")) {
>                 setEditorComponentGenerator(t -> new Label(Optional
> ```

please use a proper name instead of `t`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1867 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr-K0dAFwp1sXBxgUt:-KYr-K0dAFwp1sXBxgUu:bt5zt1q) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1867)):*
> ```Java
>             }
>             if (design.hasAttr("editable")) {
>                 setEditorComponentGenerator(t -> new Label(Optional
> ```

Could this actually be a TextField directly since doing a `toString` to the value ? Or why it is a Label instead ?

I guess the old V7 Grid used the field factory to produce something there, which we don't support.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3499 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr2IyG-CLNIQrA947F:-KYr2IyG-CLNIQrA947G:b8ksx8o) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L3499)):*
> ```Java
>         }
> 
>         SelectionMode mode = getSelectionMode();
> ```

Not sure if we should write the value of the selectAllCheckboxVisible (which will be renamed) when selection `MultiSelectionModelImpl` is used

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr958oh_hQE0BnQCtp:-KYr958oh_hQE0BnQCtq:b-y9is2c) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L72)):*
> ```Java
>                         + "<col column-id='id' sortable>" + "</colgroup><thead>"
>                         + "<tr default><th plain-text coulmn-ids='generatedColumn0'>Generated Column0</th>"
>                         + "<th plain-text coulmn-ids='id'>Id</th></tr>"
> ```

column-id ?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 106 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr995NS3ZRnwRk_UMz:-KYr995NS3ZRnwRk_UN-:bacuf2e) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L106)):*
> ```Java
>                 + "<col column-id='id' sortable>"
>                 + "<col column-id='mail' sortable>" + "</colgroup><thead>"
>                 + "<tr default><th plain-text coulmn-ids='generatedColumn0'>Generated Column0</th>"
> ```

column-id ?

just do a string find &replace search in this file with "coulmn-ids" -> "column-id" to fix all places

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Review status: 12 of 13 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1810 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrB1j8mEaRas-1wlFK:-KYrB1j8mEaRas-1wlFL:b4974oi) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1810)):*
> ```Java
>             ColumnState defaultState = new ColumnState();
> 
>             DesignAttributeHandler.writeAttribute("column-id", attributes,
> ```

should mention in the release-notes.html in the breaking changes section, in the declarative format subsection, that `property-id` is no longer used, and that `column-id` replaces it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Review status: 12 of 13 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3483 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrPv4QPz3iJCmbS8ZD:-KYrPv4QPz3iJCmbS8ZE:b4x0n68) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L3483)):*
> ```Java
>     protected void doWriteDesign(Element design, DesignContext designContext) {
>         Attributes attr = design.attributes();
>         DesignAttributeHandler.writeAttribute("readonly", attr, isReadOnly(),
> ```

"readonly" -> "selection-read-only"

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3499 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr2IyG-CLNIQrA947F:-KYrQHEVQWDr2qg9htgT:be7mcyh) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L3499)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure if we should write the value of the selectAllCheckboxVisible (which will be renamed) when selection `MultiSelectionModelImpl` is used
</blockquote></details>

Apparently not an issue for now 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by denis-anisimov** [comment]
Review status: 12 of 13 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYrAxvX_aAhUiLzUH8o:bk8a6ul) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Don't understand this line, component own only ?.  Only AbstractListing´s state ? 
</blockquote></details>

The method is `protected` . Each component should deicide how to write its own state (subclass own state, not  an`AbstarctListing`).
The default implementation propose some way of doing that (including behavioural approach) but it can be totally overridden (this what a `Grid` does).
This is what I'm trying to say.
Apparently I'm not able to do that good enough. You are more than welcome to suggest better wording here.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 279 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqx_FDTa2ho8ssrh0Y:-KYrIm0BRli1BXOxmu5U:b-2tf2o5) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L279)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

replace "only own component state" with "only the state at this level."
</blockquote></details>

It's not about a state at this level. That's the problem (see above).

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 356 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxv-pLxhQgBQGDHLc:-KYrIy4n9sCz2m78LWu2:b-o8rr23) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L356)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

replace "the component own only state" with "the component's state at this level"
</blockquote></details>

Same here. Not at this level.
See above.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1810 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr5Y5gSLVARCQCMqtP:-KYrJMPL8G_QjYtTQo72:b-uj92s1) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1810)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure if this should be just "identifier". Probably not a part of this since the Column API will change a bit.
</blockquote></details>

I don't know. It becomes consistent with references to it.
There are attributes in header rows and footer rows that refer to this one. Having just "identifier" here makes it a bit more confusing to understand references.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1810 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrB1j8mEaRas-1wlFK:-KYrRfw1XbtlPuFV2nVj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1810)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

should mention in the release-notes.html in the breaking changes section, in the declarative format subsection, that `property-id` is no longer used, and that `column-id` replaces it
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1813 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqyTh2cQNJUrzIHY1p:-KYrRolaUFGMxjEg_VJl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1813)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

depends on the data provider ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1867 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqztadQYCbqJVe7tl8:-KYrRvXWnoGOmZDgro69:b-5bpf2l) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1867)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

please use a proper name instead of `t`
</blockquote></details>

It has been a question for me which name to use.......
As a result: this is just a copy from the `setEditorComponent(Component)` method.

Is `item` good enough ?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1867 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr-K0dAFwp1sXBxgUt:-KYrSLFvz_zMk7ro_wt1:b-6x0qtx) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1867)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could this actually be a TextField directly since doing a `toString` to the value ? Or why it is a Label instead ?

I guess the old V7 Grid used the field factory to produce something there, which we don't support.
</blockquote></details>

Most likely.
I just need this call because otherwise I will get an exception because of absence an editor.
I would say this is out of the scope of this patch.....

I'm not really sure what's the best here: `TextField` allows to change a value (which in some cases will be something totally wrong because of the nature of an item) and can be confusing. `Label` doesn't allow to change a value. So it's not confusing in that regard. But it will be confusing in the designer preview because editor is not an editor.

Well. I think it should be `TextField` , you are right. We are going to support only `String`s as inline data. `TextField` works perfectly for them. It is not supposed to used anyway for other items.

By the way the editor should show not an item but its converted value ( via valueprovider ). Corrected.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3483 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrPv4QPz3iJCmbS8ZD:-KYrV_rZ6nidmO6u9p1w:b-1y579t) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L3483)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

"readonly" -> "selection-read-only"
</blockquote></details>

I would say : selection-allowed.

Added to release-notes.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr958oh_hQE0BnQCtp:-KYrWgdT4HDBeXDly9qP:bg35ls1) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L72)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

column-id ?
</blockquote></details>

No. Not a typo at all.

See `StaticRow` design impl.
It was a nice surprise to me to implement this from scratch: previously there was a reference to a `Grid` available somehow.
Not anymore and I have to address somehow the columns. That's the way.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 106 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr995NS3ZRnwRk_UMz:-KYrXOSqRZ2CwsExbqlx:bemje9p) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L106)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

column-id ?

just do a string find &replace search in this file with "coulmn-ids" -> "column-id" to fix all places
</blockquote></details>

Sure .
No.
See above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYrndyE3fP540VUNxt1:b-83x38j) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The method is `protected` . Each component should deicide how to write its own state (subclass own state, not  an`AbstarctListing`).
The default implementation propose some way of doing that (including behavioural approach) but it can be totally overridden (this what a `Grid` does).
This is what I'm trying to say.
Apparently I'm not able to do that good enough. You are more than welcome to suggest better wording here.
</blockquote></details>

So overriding methods should call `super.doWriteDesign(..)` ? In that case:

```java
/**
  * Writes the components state to the given design.
  * <p>
  * This method should always write the state for the level it is implemented only; when overriding this method, remember to call the {@code super} method.
  *<p>
  ...
 */
```

Or if not, then I don't understand how this is necessarily different from `writeDesign` or why this should be `protected` instead of `private`. It just adds confusion currently if the purpose cannot be even described.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1867 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr-K0dAFwp1sXBxgUt:-KYrqK5x5BPHYsnX18DS:b-h94fjh) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/Grid.java#L1867)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Most likely.
I just need this call because otherwise I will get an exception because of absence an editor.
I would say this is out of the scope of this patch.....

I'm not really sure what's the best here: `TextField` allows to change a value (which in some cases will be something totally wrong because of the nature of an item) and can be confusing. `Label` doesn't allow to change a value. So it's not confusing in that regard. But it will be confusing in the designer preview because editor is not an editor.

Well. I think it should be `TextField` , you are right. We are going to support only `String`s as inline data. `TextField` works perfectly for them. It is not supposed to used anyway for other items.

By the way the editor should show not an item but its converted value ( via valueprovider ). Corrected.
</blockquote></details>

I don't think the editor component is ever used if the column is not editable, so TextField should be safe.

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 191 at r3](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrr1zLKM79rE1Sdoym:-KYrr1zLKM79rE1Sdoyn:b-nfmh3m) ([raw file](https://github.com/vaadin/framework/blob/19d668d9b7adbec1dfe415788e628538a4a2fb14/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L191)):*
> ```Java
> 
>                 String columnIdsString = DesignAttributeHandler.readAttribute(
>                         "coulmn-ids", element.attributes(), "", String.class);
> ```

`column-ids` , not `coulmn-ids`

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr958oh_hQE0BnQCtp:-KYrqdw6Do2rlf98W6FY:b-j3vx0n) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L72)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No. Not a typo at all.

See `StaticRow` design impl.
It was a nice surprise to me to implement this from scratch: previously there was a reference to a `Grid` available somehow.
Not anymore and I have to address somehow the columns. That's the way.

</blockquote></details>

It can't be `coulmn-ids`that doesn't mean or imply anything else than it is a typo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYrrOP0NaG1cracB-xg:b5cp49f) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So overriding methods should call `super.doWriteDesign(..)` ? In that case:

```java
/**
  * Writes the components state to the given design.
  * <p>
  * This method should always write the state for the level it is implemented only; when overriding this method, remember to call the {@code super} method.
  *<p>
  ...
 */
```

Or if not, then I don't understand how this is necessarily different from `writeDesign` or why this should be `protected` instead of `private`. It just adds confusion currently if the purpose cannot be even described.
</blockquote></details>

It's up to subclass to decide what to do with this method.

`writeDesign` takes care about:
- writing attributes from the super implementation (this logic should be preserved to avoid handle each attribute by hand).
- writes "read-only" attribute (it just has sense here since it's available right here).
- defines a behavior via template methods how to write structure.

All those things works fine for any Listing except a `Grid`.

`Grid` has its own logic for "readOnly" (that was the first reason to change default `writeDesign` behavior from here).
Also it actually doesn't use behavioral template methods like `writeItems`/`writeItem`.

The problem is: I cannot easily override `writeDesign` since I HAVE to call `super.writeDesign()` in the `Grid`. But it does things that I don't want : ( described above: readonly and structure).

So instead, I've extracted logic which is common for all listing into `doWriteDesign()` so that it can be overridden.
Subclasses decides do they want to call `super.doWriteDesign()` or not.
`Grid` totally overrides it and doesn't call `super.doWriteDesign()`.
So it has all the behavior inherited from `AbstractComponent.writeDesign` and doesn't have behavior from `AbstractListing.doWriteDesign()`.

Any better suggestion ?
Or final  javadoc suggestions ?

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 191 at r3](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrr1zLKM79rE1Sdoym:-KYruBRXbP_qz_y5riuM:b-ka2o6z) ([raw file](https://github.com/vaadin/framework/blob/19d668d9b7adbec1dfe415788e628538a4a2fb14/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L191)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

`column-ids` , not `coulmn-ids`
</blockquote></details>

Oh, crap !
Thanks !
Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 72 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr958oh_hQE0BnQCtp:-KYruHLig9olJlEBF6xD:ba1zdj9) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L72)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

It can't be `coulmn-ids`that doesn't mean or imply anything else than it is a typo.
</blockquote></details>

Missed that. I thought you are complaining about plural vs. singular.
Thanks.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 106 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYr995NS3ZRnwRk_UMz:-KYruTFlBgc9ELu_J7Ob:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L106)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sure .
No.
See above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Review status: 12 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYrwGmcrtAELzqbQ79n:brpa14o) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's up to subclass to decide what to do with this method.

`writeDesign` takes care about:
- writing attributes from the super implementation (this logic should be preserved to avoid handle each attribute by hand).
- writes "read-only" attribute (it just has sense here since it's available right here).
- defines a behavior via template methods how to write structure.

All those things works fine for any Listing except a `Grid`.

`Grid` has its own logic for "readOnly" (that was the first reason to change default `writeDesign` behavior from here).
Also it actually doesn't use behavioral template methods like `writeItems`/`writeItem`.

The problem is: I cannot easily override `writeDesign` since I HAVE to call `super.writeDesign()` in the `Grid`. But it does things that I don't want : ( described above: readonly and structure).

So instead, I've extracted logic which is common for all listing into `doWriteDesign()` so that it can be overridden.
Subclasses decides do they want to call `super.doWriteDesign()` or not.
`Grid` totally overrides it and doesn't call `super.doWriteDesign()`.
So it has all the behavior inherited from `AbstractComponent.writeDesign` and doesn't have behavior from `AbstractListing.doWriteDesign()`.

Any better suggestion ?
Or final  javadoc suggestions ?
</blockquote></details>

Gotcha. How about:
```java
Writes listing specific state into the given design.

This method is separated from {@link writeDesign(Element, DesignContext)} to be overridable in subclasses that need to replace this, but still must be able to call {@code super.writeDesign(...)}.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 313 at r4](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrxdwo1m_F2ST9qS_N:-KYrxdwo1m_F2ST9qS_O:bb7x1ix) ([raw file](https://github.com/vaadin/framework/blob/3e11a22f89460cbb4392c84d47bad8870dd6db07/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L313)):*
> ```Java
> 
>     @SuppressWarnings("unchecked")
>     public void valueSingleSelectSerialization() throws InstantiationException,
> ```

Thought that this is `@Test` but apparently it is triggered from another test method ? Just move this there or make private to not force people to think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 276 at r2](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYqxC0ymFwHaFHhKXfU:-KYs06XIb0-S6mJ0_Qty:b-fjpg5f) ([raw file](https://github.com/vaadin/framework/blob/1c6d3df142d32f4fb04a91a644bd47d013b5bbd4/server/src/main/java/com/vaadin/ui/AbstractListing.java#L276)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Gotcha. How about:
```java
Writes listing specific state into the given design.

This method is separated from {@link writeDesign(Element, DesignContext)} to be overridable in subclasses that need to replace this, but still must be able to call {@code super.writeDesign(...)}.
```
</blockquote></details>

Whatever you say.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 313 at r4](https://reviewable.io:443/reviews/vaadin/framework/7961#-KYrxdwo1m_F2ST9qS_N:-KYs0m0yL8wyeMDs-mq1:b-ksl8i0) ([raw file](https://github.com/vaadin/framework/blob/3e11a22f89460cbb4392c84d47bad8870dd6db07/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L313)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Thought that this is `@Test` but apparently it is triggered from another test method ? Just move this there or make private to not force people to think
</blockquote></details>

`valueSerialization`

The attempt to have unify method names: `valueSerialization` is inherited and has to be implemented.
But in which way ? ( there are different modes ). So it just delegates to the `valueSingleSelectSerialization` and there is also `valueMultiSelectSerialization`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7961)*

**Pull request merged**
