### PR TITLE
Correctly reset DataCommunicator when its DataProvider is changed

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8138)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 434 at r1](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_dgOrzk9GgkbXyjUma:-K_dgOrzk9GgkbXyjUmb:bylr5hd) ([raw file](https://github.com/vaadin/framework/blob/c02ef0a7df7fc2c4a0513eaa41ba90db1825b0d4/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L434)):*
> ```Java
>     @Override
>     protected List<T> readItems(Element design, DesignContext context) {
>         Set<T> selected = new HashSet<>();
> ```

This code is almost completely duplicated in `AbstractSingleSelect`. Would it make sense to provide a protected method in the super type that does all the common parts (returning the set of selected items), and then only doing the selection updating separately?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by ahie** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 434 at r1](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_dgOrzk9GgkbXyjUma:-K_hyJZICJTW4g4rph2j:b-umi852) ([raw file](https://github.com/vaadin/framework/blob/c02ef0a7df7fc2c4a0513eaa41ba90db1825b0d4/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L434)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This code is almost completely duplicated in `AbstractSingleSelect`. Would it make sense to provide a protected method in the super type that does all the common parts (returning the set of selected items), and then only doing the selection updating separately?
</blockquote></details>

There doesn't seem to be a clean way to do this with the current hierarchy since `AbstractListing` by itself doesn't handle selections. Additionally `Grid`, which implements item reading in a completely different manner, inherits `AbstractListing`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by pleku** [comment]
Reviewed 5 of 10 files at r1, 2 of 2 files at r2.
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataGenerator.java, line 63 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jUrVHzrJH9BOTFSSX:-K_jUrVHzrJH9BOTFSSY:b-mt5f9w) ([raw file](https://github.com/vaadin/framework/blob/62ddc7416fd7dcf3f6c75050d0c2e60a9e134d9d/server/src/main/java/com/vaadin/data/provider/DataGenerator.java#L63)):*
> ```Java
>      * method should clean up any unneeded information stored for items.
>      */
>     public default void destroyAllData() {
> ```

Why empty default instead of forcing people to do something ?

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 377 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jWUc87Ri3fjpyuVnF:-K_jWUc87Ri3fjpyuVnG:b-w4dyvs) ([raw file](https://github.com/vaadin/framework/blob/6ef75bda79099953f85e1c48a0e833a6ed258acf/server/src/main/java/com/vaadin/ui/AbstractListing.java#L377)):*
> ```Java
>                 new DeclarativeIconGenerator<>(getItemIconGenerator()));
> 
>         List<T> readItems = readItems(design, context);
> ```

Why this change ?
Is readItems really used even here now ? For Grid returns an empty list.
Should the return type be something else than a list since it is not used anywhere ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by ahie** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataGenerator.java, line 63 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jUrVHzrJH9BOTFSSX:-Ka1QXFbbANmRPIuG_HP:bu1gaii) ([raw file](https://github.com/vaadin/framework/blob/62ddc7416fd7dcf3f6c75050d0c2e60a9e134d9d/server/src/main/java/com/vaadin/data/provider/DataGenerator.java#L63)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why empty default instead of forcing people to do something ?
</blockquote></details>

Would make `DataGenerator` no longer a functional interface. Many DataGenerators don't need to perform any cleanup, for example the `DataGenerator` in `ComboBox`that generates style and icon information.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 377 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jWUc87Ri3fjpyuVnF:-Ka1TjhuzVUoqlDpsgiB:b-ss7nds) ([raw file](https://github.com/vaadin/framework/blob/6ef75bda79099953f85e1c48a0e833a6ed258acf/server/src/main/java/com/vaadin/ui/AbstractListing.java#L377)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why this change ?
Is readItems really used even here now ? For Grid returns an empty list.
Should the return type be something else than a list since it is not used anywhere ?
</blockquote></details>

Order of operations. Without this change `readDesign` would assign selections before actually being populated with the items. The return type was not changed to keep API changes minimal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by denis-anisimov** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 377 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jWUc87Ri3fjpyuVnF:-Ka1izJuuFfudxsQ_Z2E:b-n2n4be) ([raw file](https://github.com/vaadin/framework/blob/6ef75bda79099953f85e1c48a0e833a6ed258acf/server/src/main/java/com/vaadin/ui/AbstractListing.java#L377)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Order of operations. Without this change `readDesign` would assign selections before actually being populated with the items. The return type was not changed to keep API changes minimal.
</blockquote></details>

I think this is the case where we can change the return type.
The return type has no sense anymore and it's just confusing.
So I vote to remove return type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by pleku** [comment]
Reviewed 3 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 377 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jWUc87Ri3fjpyuVnF:-Ka6LzM5BFDzQqxXR32C:b7vrd2g) ([raw file](https://github.com/vaadin/framework/blob/6ef75bda79099953f85e1c48a0e833a6ed258acf/server/src/main/java/com/vaadin/ui/AbstractListing.java#L377)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I think this is the case where we can change the return type.
The return type has no sense anymore and it's just confusing.
So I vote to remove return type.
</blockquote></details>

Not necessarily part of this patch, but since you touched it, could change it to be less confusing. Up to Aleksi to decide whether it is done here or in a separate patch

---

*[uitest/src/main/java/com/vaadin/tests/data/ReplaceDataProvider.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-Ka6rK75JMBqyTRwf514:-Ka6rK75JMBqyTRwf515:bqeu00) ([raw file](https://github.com/vaadin/framework/blob/62ddc7416fd7dcf3f6c75050d0c2e60a9e134d9d/uitest/src/main/java/com/vaadin/tests/data/ReplaceDataProvider.java#L47)):*
> ```Java
>         grid.setItems(listOfClasses);
> 
>         Button btn = new Button("change value");
> ```

Can you please add another test, that changes the dataprovider and also selects something immediately, e.g. row 2 ? Just to make sure that the selection works 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by ahie** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 377 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-K_jWUc87Ri3fjpyuVnF:-Ka70nwgSFShT-cCupwW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6ef75bda79099953f85e1c48a0e833a6ed258acf/server/src/main/java/com/vaadin/ui/AbstractListing.java#L377)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not necessarily part of this patch, but since you touched it, could change it to be less confusing. Up to Aleksi to decide whether it is done here or in a separate patch
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/ReplaceDataProvider.java, line 47 at r2](https://reviewable.io:443/reviews/vaadin/framework/8138#-Ka6rK75JMBqyTRwf514:-Ka70oVLesf8ouF5iR9r:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/62ddc7416fd7dcf3f6c75050d0c2e60a9e134d9d/uitest/src/main/java/com/vaadin/tests/data/ReplaceDataProvider.java#L47)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you please add another test, that changes the dataprovider and also selects something immediately, e.g. row 2 ? Just to make sure that the selection works 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8138)*

**Pull request merged**
