### PR TITLE
Automatic test for OSGi/karaf

### LINKED ISSUE #8594: Automatic framework testing against OSGi (karaf)

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9480)

Fixes #8594

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 12 of 17 files at r1.
Review status: 12 of 17 files reviewed at latest revision, 15 unresolved discussions.

---

*[.gitignore, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxSXfsGhX673yzynmm:-KpxSXfsGhX673yzynmn:b-bw4qgx) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/.gitignore#L18)):*
> ```
> # Persisted scss cache files
> uitest/src/main/themes/VAADIN/themes/**/styles.scss.cache
> test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/resources/VAADIN/themes/karaftesttheme/styles.css
> ```

this should probably be a few lines up as this is not related to the comment above

---

*[test/pom.xml, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxShmR2ytu67i4PplB:-KpxShmR2ytu67i4PplC:b-9f18or) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/pom.xml#L95)):*
> ```XML
> 
>     <modules>
>         <module>servlet-containers/karaf</module>
> ```

(I'd move this down so that one starts to get general test results earlier; OTOH should reorder the whole set of modules so not a blocker)

---

*[test/servlet-containers/karaf/pom.xml, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTAWqMQeCZDG4q3i7:-KpxTAWqMQeCZDG4q3i8:bukgue4) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L11)):*
> ```XML
>         <relativePath>../..</relativePath>
>     </parent>
>     <artifactId>karaf</artifactId>
> ```

this is not really a good artifact ID as we might want to use the name later for something more publishable - other modules use something like vaadin-test-xyz

---

*[test/servlet-containers/karaf/pom.xml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTi2s5bgd6o0rD-nC:-KpxTi2s5bgd6o0rD-nD:bn8fkv2) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L21)):*
> ```XML
>     </modules>
> 
>     <prerequisites>
> ```

this is only meant for Maven plug-ins even though it wasn't well documented in the past - see http://blog.soebes.de/blog/2015/04/04/maven-prerequisites/

---

*[test/servlet-containers/karaf/pom.xml, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTd92sZNXGa2XKS9K:-KpxTd92sZNXGa2XKS9L:bazpvf1) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L26)):*
> ```XML
> 
>     <properties>
>         <vaadin.version>8.1-SNAPSHOT</vaadin.version>
> ```

most of these parameters are inherited from the parent POM and should not be repeated here

---

*[test/servlet-containers/karaf/README.md, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxULVj-RcYrzqZeYus:-KpxULVj-RcYrzqZeYut:bggk94m) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/README.md#L25)):*
> ```Markdown
> in `karaf-run` module
> * Karaf console is available via ssh at `127.0.0.0:8101` port, username/password is `karaf/karaf` 
> * To stop background karaf process , run `karaf:client@karaf-client-shutdown`
> ```

missing "mvn" or something from the command?

---

*[test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUZLubzhPtKAYBvf7:-KpxUZLubzhPtKAYBvf8:bvcjiy0) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml#L9)):*
> ```XML
>     <modelVersion>4.0.0</modelVersion>
>     <build>
>         <plugins>
> ```

(this could alternatively be done with a profile in the main POM - but the current solution is probably ok for testing)

---

*[test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUTor7CGKNHJpGfi0:-KpxUTor7CGKNHJpGfi1:b-t0aj0c) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml#L21)):*
> ```XML
>         </plugins>
>     </build>
> </project>
> ```

(missing EOL)

---

*[test/servlet-containers/karaf/karaf-run/pom.xml, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUo8LiMj64Rkwe5nJ:-KpxUo8MNd-nwdboXoul:b-t0aj0c) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/pom.xml#L123)):*
> ```XML
>         </plugins>
>     </build>
> </project>
> ```

(missing EOL)

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/bnd.bnd, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUwIMyi4Z3BCOA7F6:-KpxUwIMyi4Z3BCOA7F7:b2kv30j) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/bnd.bnd#L6)):*
> ```
> Export-Package: com.vaadin.test.osgi.myapplication1
> Import-Package: *
> Web-ContentPath: /myapp1
> ```

missing EOL

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/java/com/vaadin/test/osgi/myapplication1/MyUI.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxV5iIa99dL9OXMKJt:-KpxV5iIa99dL9OXMKJu:b-qk2i24) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/java/com/vaadin/test/osgi/myapplication1/MyUI.java#L22)):*
> ```Java
> public class MyUI extends UI {
> 
> 	@Override
> ```

whitespace to spaces

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/resources/VAADIN/themes/karaftesttheme/styles.scss, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxV9dNwWl4obYoAI2n:-KpxV9dNwWl4obYoAI2o:b2kv30j) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/resources/VAADIN/themes/karaftesttheme/styles.scss#L12)):*
> ```SCSS
> .karaftesttheme {
>   @include karaftesttheme;
> }
> ```

missing EOL

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd, line 4 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVUWJ5crP1KdbPCS8:-KpxVUWJ5crP1KdbPCS9:bye710q) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd#L4)):*
> ```
> Bundle-Version: ${project.version}
> Bundle-SymbolicName: ${project.groupId}.${project.artifactId}
> Export-Package: com.vaadin.test.osgi.myapplication2
> ```

the "2" does not seem to match the UI class (just myapplication)

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVE4gZj19vt4QXeF3:-KpxVE4gZj19vt4QXeF4:b2kv30j) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd#L6)):*
> ```
> Export-Package: com.vaadin.test.osgi.myapplication2
> Import-Package: *
> Web-ContentPath: /myapp2
> ```

missing EOL

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/src/main/java/com/vaadin/test/osgi/myapplication/MyUI.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVGf5VPfKhOV5XH6m:-KpxVGf5VPfKhOV5XH6n:bhejbel) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/src/main/java/com/vaadin/test/osgi/myapplication/MyUI.java#L19)):*
> ```Java
> public class MyUI extends UI {
> 
> 	@Override
> ```

whitespace as spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Comment by hesara** [comment]
Review status: 12 of 17 files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxViIHlddHFJICMc71:-KpxViIHlddHFJICMc72:b7u9q2z) (no related file):*
Partial review done + could use Karaf "feature" file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Comment by elmot** [comment]
Review status: 3 of 17 files reviewed at latest revision, 16 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxViIHlddHFJICMc71:-KqMbLRvgcMyOmbOu5ay:bljesg) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Partial review done + could use Karaf "feature" file?
</blockquote></details>

Karaf feature - good idea but I'd prefer to make that in a separate PR. Let's do MVP first.

---

*[.gitignore, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxSXfsGhX673yzynmm:-KqMdHD8mCaJKLjIZhEO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/.gitignore#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this should probably be a few lines up as this is not related to the comment above
</blockquote></details>

Done.

---

*[test/pom.xml, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxShmR2ytu67i4PplB:-KqMdafMjmi9qnqKzKAO:b-7qa2pw) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/pom.xml#L95)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I'd move this down so that one starts to get general test results earlier; OTOH should reorder the whole set of modules so not a blocker)
</blockquote></details>

Moved down. Actually I just forgot to move that down.

---

*[test/servlet-containers/karaf/pom.xml, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTAWqMQeCZDG4q3i7:-KqMe-pX8rWX1OxLzJOe:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L11)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this is not really a good artifact ID as we might want to use the name later for something more publishable - other modules use something like vaadin-test-xyz
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/pom.xml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTi2s5bgd6o0rD-nC:-KqMe3uq7dDAEWqH_gVT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L21)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this is only meant for Maven plug-ins even though it wasn't well documented in the past - see http://blog.soebes.de/blog/2015/04/04/maven-prerequisites/
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/pom.xml, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxTd92sZNXGa2XKS9K:-KqMeNocT97s_brJqsiO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/pom.xml#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

most of these parameters are inherited from the parent POM and should not be repeated here
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/README.md, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxULVj-RcYrzqZeYus:-KqMpxcjtMPknPXwQ5md:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/README.md#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing "mvn" or something from the command?
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUZLubzhPtKAYBvf7:-KqMhvZwT2Y1CpxdjYBi:bcdv2) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml#L9)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this could alternatively be done with a profile in the main POM - but the current solution is probably ok for testing)
</blockquote></details>

Reusing the same pom does not look good for me. I'd prefer to have absolutely vanilla karaf running from a separate file without any dependencies or properties inherited by mistake.

---

*[test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUTor7CGKNHJpGfi0:-KqMiLLF5rPhXfB3PN71:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/karaf-run-pom.xml#L21)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(missing EOL)
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/karaf-run/pom.xml, line 123 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUo8LiMj64Rkwe5nJ:-KqMiMBuEvdackDtZAXx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/karaf-run/pom.xml#L123)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(missing EOL)
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/bnd.bnd, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxUwIMyi4Z3BCOA7F6:-KqMpzaF-1mVWiUx6SlK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/bnd.bnd#L6)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing EOL
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/java/com/vaadin/test/osgi/myapplication1/MyUI.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxV5iIa99dL9OXMKJt:-KqMincfGH0PFmE7MMMd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/java/com/vaadin/test/osgi/myapplication1/MyUI.java#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

whitespace to spaces
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/resources/VAADIN/themes/karaftesttheme/styles.scss, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxV9dNwWl4obYoAI2n:-KqMitqhGf8ceUd-N_LM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle1/src/main/resources/VAADIN/themes/karaftesttheme/styles.scss#L12)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing EOL
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd, line 4 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVUWJ5crP1KdbPCS8:-KqMjGNo3t7x-c3_3-Ig:b-36ng69) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd#L4)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the "2" does not seem to match the UI class (just myapplication)
</blockquote></details>

Done. Not required at all.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVE4gZj19vt4QXeF3:-KqMitZ7wQKLYMJSbGG3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/bnd.bnd#L6)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing EOL
</blockquote></details>

Done.

---

*[test/servlet-containers/karaf/vaadin-karaf-bundle2/src/main/java/com/vaadin/test/osgi/myapplication/MyUI.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/9480#-KpxVGf5VPfKhOV5XH6m:-KqMjNEo1A0YKp4MSxwh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8179605f14196ca8b2649e0d7833b4992ae2c8e8/test/servlet-containers/karaf/vaadin-karaf-bundle2/src/main/java/com/vaadin/test/osgi/myapplication/MyUI.java#L19)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

whitespace as spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Comment by hesara** [comment]
Reviewed 10 of 13 files at r2.
Review status: 13 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Comment by hesara** [comment]
Reviewed 1 of 17 files at r1, 3 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/karaf/karaf-run/pom.xml, line 80 at r2](https://reviewable.io:443/reviews/vaadin/framework/9480#-KqNMmMBEafH6_zeCrgI:-KqNMmMCPqoRMVj1qtMX:b-h9eorg) ([raw file](https://github.com/vaadin/framework/blob/f0c62fbe0b84d1fea2cd3ccd04b908a5a1ffbc19/test/servlet-containers/karaf/karaf-run/pom.xml#L80)):*
> ```XML
>                                 <command>bundle:install -s mvn:com.vaadin/vaadin-themes/${vaadin.version}</command>
>                                 <command>
>                                     <![CDATA[bundle:install -s file:./../vaadin-karaf-bundle1/target/vaadin-karaf-bundle1-${project.version}.jar]]></command>
> ```

Why is CDATA escaping needed here and below but not above? (not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/servlet-containers/karaf/karaf-run/pom.xml, line 80 at r2](https://reviewable.io:443/reviews/vaadin/framework/9480#-KqNMmMBEafH6_zeCrgI:-KqNNz72y5Y4uNAHeFB_:b2ony8o) ([raw file](https://github.com/vaadin/framework/blob/f0c62fbe0b84d1fea2cd3ccd04b908a5a1ffbc19/test/servlet-containers/karaf/karaf-run/pom.xml#L80)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why is CDATA escaping needed here and below but not above? (not a blocker)
</blockquote></details>

Auto-formatters always are breaking the line because of length.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9480)*

**Pull request merged**
