### PR TITLE
Add missing [source, java] to the  java code blocks in documentation

### PR DESCRIPTION
**Pull request by anasmi**
Adding missing ```[source, java]``` to the examples containing java code blocks

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)

### CODE REVIEW

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: all files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[documentation/clientsideapp/clientsideapp-entrypoint.asciidoc, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11381#-LTvPh_B83KWbwqDiCwa:-LTvPh_B83KWbwqDiCwb:bjyxhof) ([raw file](https://github.com/vaadin/framework/blob/9ee5d54b291dbed7d185c817f1f8461fc3c75b98/documentation/clientsideapp/clientsideapp-entrypoint.asciidoc#L54)):*
> ```
> [source, java]
>

is this  a xml file ?

**Comment by anasmi** [comment]
@zhe 
No, asciidoc format, 
`To enable syntax highlighting in the output, set the style on the block to source and specify the source language in the second attribute position`
Taken from here: 

https://asciidoctor.org/docs/asciidoc-writers-guide/

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @anasmi)

___
*[documentation/clientsideapp/clientsideapp-entrypoint.asciidoc, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11381#-LTvPh_B83KWbwqDiCwa:-LTvW3DV1AZoYhX4DsYA:btiuuzm) ([raw file](https://github.com/vaadin/framework/blob/9ee5d54b291dbed7d185c817f1f8461fc3c75b98/documentation/clientsideapp/clientsideapp-entrypoint.asciidoc#L54)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> [source, java]
>

is this  a xml file ?
</blockquote></details>

What i mean is that the following code is not `java` code, if you want to highlight it, that should be `[source, xml]` ?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
"-//Google Inc.//DTD Google Web Toolkit 1.7.0//EN"
"http://google-web-toolkit.googlecode.com/svn/tags/1.7.0/distro-source/core/src/gwt-module.dtd">
<module>
    <!-- Builtin Vaadin and GWT widgets -->
    <inherits name="com.vaadin.Vaadin" />
 
    <!-- The entry-point for the client-side application -->
    <entry-point class="com.example.myapp.client.MyEntryPoint"/>
</module>
```
___
*[documentation/clientsideapp/clientsideapp-loading.asciidoc, line 14 at r2](https://reviewable.io/reviews/vaadin/framework/11381#-LTvWScx9bLsMUBHdKgh:-LTvWScx9bLsMUBHdKgi:b7xj6cb) ([raw file](https://github.com/vaadin/framework/blob/56e15daf9773f3dd2f9691af4c80cdfc5de0a753/documentation/clientsideapp/clientsideapp-loading.asciidoc#L14)):*
> ```AsciiDoc
> follows:
> 
> [source, java] 
> ```

and here is the same.

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: all files reviewed, 2 unresolved discussions (waiting on @anasmi)

**Review by anasmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @ZheSun88)

___
*[documentation/clientsideapp/clientsideapp-entrypoint.asciidoc, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11381#-LTvPh_B83KWbwqDiCwa:-LTvYCrD6rmyzIxWMU9-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9ee5d54b291dbed7d185c817f1f8461fc3c75b98/documentation/clientsideapp/clientsideapp-entrypoint.asciidoc#L54)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

What i mean is that the following code is not `java` code, if you want to highlight it, that should be `[source, xml]` ?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
"-//Google Inc.//DTD Google Web Toolkit 1.7.0//EN"
"http://google-web-toolkit.googlecode.com/svn/tags/1.7.0/distro-source/core/src/gwt-module.dtd">
<module>
    <!-- Builtin Vaadin and GWT widgets -->
    <inherits name="com.vaadin.Vaadin" />
 
    <!-- The entry-point for the client-side application -->
    <entry-point class="com.example.myapp.client.MyEntryPoint"/>
</module>
```
</blockquote></details>

Done.
___
*[documentation/clientsideapp/clientsideapp-loading.asciidoc, line 14 at r2](https://reviewable.io/reviews/vaadin/framework/11381#-LTvWScx9bLsMUBHdKgh:-LTvYFmrBsBUkeTNj1FG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/56e15daf9773f3dd2f9691af4c80cdfc5de0a753/documentation/clientsideapp/clientsideapp-loading.asciidoc#L14)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and here is the same. 
</blockquote></details>

Done.

**Comment by anasmi** [comment]
Yes, you are correct. Sorry for that. Have misunderstood your comment first

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: all files reviewed, 2 unresolved discussions (waiting on @ZheSun88)

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11381)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
