### PR TITLE
Allow grid columns to optionally shrink to be narrower than contents

### LINKED ISSUE #8548: There should be an option to make Grid fit columns into available space
It seems like Grid always interprets the natural width of columns as the strict minimum. If you have a `Grid` which is 1000px wide and have two columns with natural width "200px" and "1000px" you will always end up with a horizontal scrollbar. Even if you use `setMinimumWidth` on the "1000px" column to set minimum to "1px", it will become 1000px wide.

There should be a way to make grid always use the defined width and contract/expand columns to make them fit without a horizontal scrollbar

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8548

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9430)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1190 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2ZDwL3Ko1kqNHsnXi:-Kl2ZDwL3Ko1kqNHsnXj:bengxsb) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1190)):*
> ```Java
>         int clientWidth = getClientWidth(element);
>         int scrollWidth = getScrollWidth(element);
>         return scrollWidth > clientWidth;
> ```

The previous variant was more informative. Sometimes it's useful to know the real widths difference without rerunning the whole test under debugger. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by pleku** [comment]
Reviewed 4 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1514 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2PCs48E2bb_7uY4qN:-Kl2PCs48E2bb_7uY4qO:b-dp2xuw) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1514)):*
> (first N rows)

What does this refrain to ? What is N and why ? Does it mean that is calculated from the initially rendered rows ?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1518 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2PnHM4nrr1RwTJ0mr:-Kl2PnHM4nrr1RwTJ0ms:b-gc5rfx) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1518)):*
> * if necessary to the minimum width defined by
>  * {@link #setMinimumWidth(double)} <em>when it is set to expand</em>.

It will shrink if necessary (when not enough space I guess), but only _when it is set to expand_ ? It will shrink only when it is set to expand ? I know this is true, but it does sound so confusing.. as the whole expand thing is

How bout:
`If this is set to false and the column has been set to expand with #setExpandRatio(int), then the column will shrink if necessary to the minimum width defined by #setMinimumWidth(double)`. Or something even better

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1536 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2QK8402pMd5WdZcT2:-Kl2QK8402pMd5WdZcT3:b-jyymzw) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1536)):*
> ```Java
> 
>             getState().contentsDefineMinimumWidth = contentsDefineMinimumWidth;
>             getGrid().markAsDirty();
> ```

If the old value is the same as the new one, isn't this unnecessary and could be avoided ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2ltJmCyJTPfe0gScJ:-Kl2ltJmCyJTPfe0gScK:b6uttiu) (no related file):*
Since the old behaviour can be though of as a design error and this API is not discoverable at all (don't have any better naming suggestions), can you please add a mention of this method to the `components-grid.asciidoc` documentation file on the chapter `[[components.grid.columns.width]]`, and even an example snippet would be awesome

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1514 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2PCs48E2bb_7uY4qN:-Kl2mOixXDP7iq76wbUn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1514)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> (first N rows)

What does this refrain to ? What is N and why ? Does it mean that is calculated from the initially rendered rows ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1518 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2PnHM4nrr1RwTJ0mr:-Kl2nC7yhqXCXXP7a4O3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1518)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> * if necessary to the minimum width defined by
>  * {@link #setMinimumWidth(double)} <em>when it is set to expand</em>.

It will shrink if necessary (when not enough space I guess), but only _when it is set to expand_ ? It will shrink only when it is set to expand ? I know this is true, but it does sound so confusing.. as the whole expand thing is

How bout:
`If this is set to false and the column has been set to expand with #setExpandRatio(int), then the column will shrink if necessary to the minimum width defined by #setMinimumWidth(double)`. Or something even better
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1536 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2QK8402pMd5WdZcT2:-Kl2n7i0ro5gkFZTqspW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/server/src/main/java/com/vaadin/ui/Grid.java#L1536)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

If the old value is the same as the new one, isn't this unnecessary and could be avoided ?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 1190 at r1](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2ZDwL3Ko1kqNHsnXi:-Kl2o2UUumoMm2U_SUWH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/146ae3568f1377efa2c788504ce458ad88633894/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L1190)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The previous variant was more informative. Sometimes it's useful to know the real widths difference without rerunning the whole test under debugger. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by Artur-** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl2ltJmCyJTPfe0gScJ:-Kl2pqxoIVvROn5Bi3OH:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Since the old behaviour can be though of as a design error and this API is not discoverable at all (don't have any better naming suggestions), can you please add a mention of this method to the `components-grid.asciidoc` documentation file on the chapter `[[components.grid.columns.width]]`, and even an example snippet would be awesome
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by pleku** [comment]
Reviewed 2 of 3 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 350 at r2](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl3z8D8-7uY5SNhK4ga:-Kl3z8D8-7uY5SNhK4gb:b-7mpg6y) ([raw file](https://github.com/vaadin/framework/blob/33cd9fe560bde668ae483bf31b94f3e8525263c0/documentation/components/components-grid.asciidoc#L350)):*
> ```AsciiDoc
> that the minimum width of an expanded column by default is based on the contents
> of the column (the initially rendered rows). To allow the column to become
> narrower than this, use [methodname]#setContentsDefineMinimumWidth(false)#.
> ```

Please add `(included in 8.1)` after the method reference, as we discussed this could be included in next 8.1 beta 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by Artur-** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 350 at r2](https://reviewable.io:443/reviews/vaadin/framework/9430#-Kl3z8D8-7uY5SNhK4ga:-Kl3zmyIpb9_RfKJ5raR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/33cd9fe560bde668ae483bf31b94f3e8525263c0/documentation/components/components-grid.asciidoc#L350)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add `(included in 8.1)` after the method reference, as we discussed this could be included in next 8.1 beta 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by Legioth** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1533 at r3](https://reviewable.io:443/reviews/vaadin/framework/9430#-KlNcpYk_n9AcEMZloE-:-KlNcpYk_n9AcEMZloE0:bcgrrvh) ([raw file](https://github.com/vaadin/framework/blob/e9d21cff255a1c01b4cd9a35aa5f9522208ec389/server/src/main/java/com/vaadin/ui/Grid.java#L1533)):*
> ```Java
>          * @since
>          */
>         public Column<T, V> setContentsDefineMinimumWidth(
> ```

I'm not sure about the name here. I'd at the very least suggest naming this so that the developer has a chance of discovering this method through the IDE by using the existing `setMinimumWidth` method.

It might be easier to use an enum value instead of `boolean` since the actual value can then also convey meaning in addition to only the method name. The drawback is that the code gets more verbose.

Some ideas:
```
column.setMinimumWidthMode(MinimumWidthMode.CONTENT); 
column.setMinimumWidthMode(MinimumWidthMode.CONFIGURATION);

column.setMinimumWidthFromContent(true);
column.setMinimumWidthFromContent(false);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by Artur-** [comment]
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1533 at r3](https://reviewable.io:443/reviews/vaadin/framework/9430#-KlNcpYk_n9AcEMZloE-:-KlNfkFqdPARx9gYStR7:b-9ojjt5) ([raw file](https://github.com/vaadin/framework/blob/e9d21cff255a1c01b4cd9a35aa5f9522208ec389/server/src/main/java/com/vaadin/ui/Grid.java#L1533)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'm not sure about the name here. I'd at the very least suggest naming this so that the developer has a chance of discovering this method through the IDE by using the existing `setMinimumWidth` method.

It might be easier to use an enum value instead of `boolean` since the actual value can then also convey meaning in addition to only the method name. The drawback is that the code gets more verbose.

Some ideas:
```
column.setMinimumWidthMode(MinimumWidthMode.CONTENT); 
column.setMinimumWidthMode(MinimumWidthMode.CONFIGURATION);

column.setMinimumWidthFromContent(true);
column.setMinimumWidthFromContent(false);
```
</blockquote></details>

Changed to `setMinimumWidthFromContent`, as `setMinimumWidthFromCOntent(false)` sounds much more understandable than `setMinimumWidthMode(MinimumWidthMode.CONFIGURATION);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Comment by elmot** [comment]
LGTM but we need to review naming and version timeline 

---

Reviewed 1 of 3 files at r2, 1 of 6 files at r4.
Review status: 3 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430#-:-KlIflY6Y9uISwneeds7:b-ia5uo9)*

**Comment by elmot** [comment]
Reviewed 5 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9430)*

**Pull request merged**
