### PR TITLE
implement focus handing in RadioButtonGroup, fixes #10429

### LINKED ISSUE #10429: RadioButtonGroup.focus() does not focus the RadioButtonGroup
RadioButtonGroup.focus() does not focus the RadioButtonGroup

Vaadin Framework version 8.1.7

TestCase
		CheckBox cb = new CheckBox("CB");
		RadioButtonGroup<String> rbg = new RadioButtonGroup<>("Radios");
		rbg.setItems("Test1", "Test2", "Test3");
		rbg.setSelectedItem("Test2");
		rbg.setItemCaptionGenerator(item -> "Option " + item);
		rbg.focus();
		final VerticalLayout footerLayout = new VerticalLayout(cb, rbg);

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Fixes #10429 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10440)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 246 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qY4jRXfsNu_6IoQf:-L44qY4jRXfsNu_6IoQg:b-iurfxv) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L246)):*
> ```Java
>     public void focus() {
>         // If focus is set on creation, need to wait until options are populated
>         Scheduler.get().scheduleDeferred(new Command() {
> ```

use `() -> { /* code */ }`lamda instead of `new Command()`

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 284 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qh2Aqe8AvruPwW_v:-L44qh2Aqe8AvruPwW_w:bd6splp) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L284)):*
> ```Java
>     public void focus() {
>         // If focus is set on creation, need to wait until options are populated
>         Scheduler.get().scheduleDeferred(new Command() {
> ```

Lambda over `new Command`

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 26 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qQXMCrFfm97Kx1jc:-L44qQXMCrFfm97Kx1jd:bip6jn0) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L26)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

remove empty javadoc

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 34 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rE7N8KRTFkSOi9aM:-L44rE7N8KRTFkSOi9aN:b-qysclx) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L34)):*
> ```Java
>     @Override
>     protected void setup(VaadinRequest request) {
>         CheckBox cb = new CheckBox("CB");
> ```

What is the use of the CheckBox?

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 35 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44r8BZCJsa4ycCxpq3:-L44r8BZCJsa4ycCxpq4:b-wf98au) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L35)):*
> ```Java
>     protected void setup(VaadinRequest request) {
>         CheckBox cb = new CheckBox("CB");
>         CheckBoxGroup<String> rbg = new CheckBoxGroup<>("CheckBoxes");
> ```

rename variable to `cbg`

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rBRe2nYJfa7IYMZT:-L44rBRe2nYJfa7IYMZU:b-523rjo) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L40)):*
> ```Java
>         rbg.setItemCaptionGenerator(item -> "Option " + item);
>         rbg.focus();
>         CheckBoxGroup<String> rbg2 = new CheckBoxGroup<>("No selection");
> ```

`cbg2`. Also is this used in part of the test ?

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 46 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qS22wNiryhAQFZzS:-L44qS22wNiryhAQFZzT:b-1m9ux7) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L46)):*
> ```Java
>     }
> 
> }
> ```

missing newline

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 26 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qlbP-tQBAOZZniZS:-L44qlbP-tQBAOZZniZT:b-kvich3) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L26)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

remove empty javadoc block

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 34 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rHUXuYQVx_fe9eWn:-L44rHUXuYQVx_fe9eWo:br81qvw) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L34)):*
> ```Java
>     @Override
>     protected void setup(VaadinRequest request) {
>         CheckBox cb = new CheckBox("CB");
> ```

What is the use of this CheckBox?

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44sJ8QUvDmEV33AqTR:-L44sJ8QUvDmEV33AqTS:b-mj16wq) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L40)):*
> ```Java
>         rbg.setItemCaptionGenerator(item -> "Option " + item);
>         rbg.focus();
>         RadioButtonGroup<String> rbg2 = new RadioButtonGroup<>("No selection");
> ```

Is this used as part of the test?

---

*[uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java, line 37 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44sgkbzc4hYSyNzxmz:-L44sgkbzc4hYSyNzxn-:b-scsrhz) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java#L37)):*
> ```Java
>         WebElement focused = getFocusedElement();
>         assertNotNull(
>                 "No focused element found in RadioButtonGroup after initial focus()",
> ```

Multiple mentions of RadioButtonGroup even though this is the CheckBoxGroup test

---

*[uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java, line 42 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44t3xjCuMihqIT7e5V:-L44t3xjCuMihqIT7e5W:b-ywi74a) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java#L42)):*
> ```Java
>                 .first();
>         Boolean isChild = (Boolean) executeScript(
>                 "return (arguments[0].querySelector(\"#gwt-uid-12\") == arguments[1]);",
> ```

Might be cleaner to use `checkBoxGroup.isElementPresent(By.id(focused.getAttribute("id")));`. Also double check that the element is not in the second CBG?

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java, line 30 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44uP5gOVgW06WFF4_e:-L44uP5gOVgW06WFF4_f:bee2fp4) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java#L30)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> public class RadioButtonGroupFocusTest extends MultiBrowserTest {
> ```

Should these tests also test the focus moving with the button? 

Should we do some refactoring to use some test base and provide protected methods for specifying how to check focus correctness?

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java, line 42 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44tLwrCNxXapIa4inq:-L44tLwrCNxXapIa4inr:b-5s7chd) ([raw file](https://github.com/vaadin/framework/blob/b5e52a0b86b590b8e810fa5fdaf60f4d806717f5/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java#L42)):*
> ```Java
>                 RadioButtonGroupElement.class).first();
>         Boolean isChild = (Boolean) executeScript(
>                 "return (arguments[0].querySelector(\"#gwt-uid-12\") == arguments[1]);",
> ```

See comment about using Selenium API instead of JavaScript to test. To make sure it's the selected one `rbge.findElement(By.className("v-select-option-selected")).findElements(By.id(focused.getAttribute("id"))).size() > 0`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 7 files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 246 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qY4jRXfsNu_6IoQf:-L4AaJppfZXOtwevmMRe:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L246)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

use `() -> { /* code */ }`lamda instead of `new Command()`
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 284 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qh2Aqe8AvruPwW_v:-L4AaTPmcf2waIhc5rAx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L284)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Lambda over `new Command`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 26 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qQXMCrFfm97Kx1jc:-L4Aa_hjI4bUVyfxNe-Q:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L26)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

remove empty javadoc
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 34 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rE7N8KRTFkSOi9aM:-L4AaaB8qhQbH3AVp1Nn:b3ys3lw) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L34)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What is the use of the CheckBox?
</blockquote></details>

Making sure the focus is set on the correct component (not the first one). Probably not needed really, I'll take it away.

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 35 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44r8BZCJsa4ycCxpq3:-L4Aaz5ELQeNTnV1vghk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

rename variable to `cbg`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rBRe2nYJfa7IYMZT:-L4Abghz542J8tn2mVx7:b-kkb9ml) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L40)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`cbg2`. Also is this used in part of the test ?
</blockquote></details>

No, getting rid of it.

---

*[uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java, line 46 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qS22wNiryhAQFZzS:-L4AbrcFDx8gAWlV_10_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocus.java#L46)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

missing newline
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 26 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44qlbP-tQBAOZZniZS:-L4AbvKxtuM5PeiUJ_ol:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L26)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

remove empty javadoc block
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 34 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44rHUXuYQVx_fe9eWn:-L4AbwLvr4hfGVeXoQYJ:b-j2ui4f) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L34)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What is the use of this CheckBox?
</blockquote></details>

See above, removed

---

*[uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44sJ8QUvDmEV33AqTR:-L4BRFOvrlFBYkDLsygg:bpiarnt) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/main/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocus.java#L40)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is this used as part of the test?
</blockquote></details>

Is now.

---

*[uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java, line 37 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44sgkbzc4hYSyNzxmz:-L4Ac6CZAXme4pW7xqOL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java#L37)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Multiple mentions of RadioButtonGroup even though this is the CheckBoxGroup test
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java, line 42 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44t3xjCuMihqIT7e5V:-L4BRGt0Rz5sZFV3OQl0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/test/java/com/vaadin/tests/components/checkboxgroup/CheckBoxGroupFocusTest.java#L42)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Might be cleaner to use `checkBoxGroup.isElementPresent(By.id(focused.getAttribute("id")));`. Also double check that the element is not in the second CBG?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java, line 30 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44uP5gOVgW06WFF4_e:-L4BRBSMK7bpGhOz2XmA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should these tests also test the focus moving with the button? 

Should we do some refactoring to use some test base and provide protected methods for specifying how to check focus correctness?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java, line 42 at r4](https://reviewable.io:443/reviews/vaadin/framework/10440#-L44tLwrCNxXapIa4inq:-L4BRChA3h8igT31WYu9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8f47863bafe0c2f9483c6007c131f72418c19de2/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupFocusTest.java#L42)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

See comment about using Selenium API instead of JavaScript to test. To make sure it's the selected one `rbge.findElement(By.className("v-select-option-selected")).findElements(By.id(focused.getAttribute("id"))).size() > 0`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 7 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/FocusTest.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/10440#-L4BjSlKKqHBSf-6mvLz:-L4BjSlKKqHBSf-6mvM-:bgu9d8i) ([raw file](https://github.com/vaadin/framework/blob/6ce1c5864c88ce3804671c17ac26e84debb5565e/uitest/src/test/java/com/vaadin/tests/components/FocusTest.java#L30)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> public class FocusTest extends MultiBrowserTest {
> ```

add `abstract`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 7 files at r5.
Review status: 1 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/FocusTest.java, line 30 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10440#-L4BjSlKKqHBSf-6mvLz:-L4FM1-K1PmMe-l3EqyG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6ce1c5864c88ce3804671c17ac26e84debb5565e/uitest/src/test/java/com/vaadin/tests/components/FocusTest.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

add `abstract`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10440)*

**Comment by elmot** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 248 at r6](https://reviewable.io:443/reviews/vaadin/framework/10440#-L4uOqsehmga7upu0GMy:-L4uOqsehmga7upu0GMz:b-pft5q2) ([raw file](https://github.com/vaadin/framework/blob/6875f54363bf801b5a67d77c1307d9dc58898b00/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L248)):*
> ```Java
>             // focus on first item (if found)
>             if (getWidget().getWidgetCount() > 0) {
>                 VCheckBox cb = (VCheckBox) getWidget().getWidget(0);
> ```

What if the first CB is disabled? Or several ones? Or all?
Also the code fragment might be refactored and unified with RadioButtonGroup

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 294 at r1](https://reviewable.io:443/reviews/vaadin/framework/10440#-L4uOKTfXagOjhNBi9UH:-L4uOKTfXagOjhNBi9UI:bna3wd6) ([raw file](https://github.com/vaadin/framework/blob/a2ae508a7a7ed8c67a2e1bd081b75f00aeac2c75/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L294)):*
> ```Java
>                 // otherwise focus the first one
>                 if (getWidget().getWidgetCount() > 0) {
>                     RadioButton first = (RadioButton) getWidget().getWidget(0);
> ```

What if the first RB is disabled? Or several ones? Or all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 248 at r6](https://reviewable.io:443/reviews/vaadin/framework/10440#-L4uOqsehmga7upu0GMy:-L58FymoFe3Th10VQ0qi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d19c8afb1966c364d0abf5eeead85625b82cef0d/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L248)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What if the first CB is disabled? Or several ones? Or all?
Also the code fragment might be refactored and unified with RadioButtonGroup
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 294 at r1](https://reviewable.io:443/reviews/vaadin/framework/10440#-L4uOKTfXagOjhNBi9UH:-L58Fwyr5SWrYVmW4c5Q:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a2ae508a7a7ed8c67a2e1bd081b75f00aeac2c75/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L294)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What if the first RB is disabled? Or several ones? Or all?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by elmot** [comment]
Reviewed 3 of 7 files at r5, 1 of 1 files at r6, 3 of 3 files at r7.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Comment by elmot** [comment]
Reviewed 1 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10440)*

**Pull request merged**
