### PR TITLE
Add API support for setting server side drag data

### LINKED ISSUE #8894: When a drag has started, I want to set drag data that is stored on the server side and available on drop event on the same UI, so that I don't have to parse JSON data to figure out what data was dropped
It would be very convenient to be able to easily set / get the dropped data in server side, when dragging within the same UI, instead of having to make it as e.g. JSON data.

```java
class DragSourceExtension...

public void setDragData(Object object) { ... }
```

```java
class DropEvent...

public Optional<Object> getDragData() { ... }
```

It should work when the drag has already started, e.g.
```java
dragSource.addDragStartListener(event -> dragSource.setDragData(myGrid.getSelectedItems()));
```
Then I can just fetch the dropped items easily
```java
dropTarget.addDropListener(event -> {
  event.getDragData().ifPresent(data -> handleDroppedItems((Set<MyBean>)data));
});
```

Javadocs and documentation should highlight that this data is only for
- server side data
- within the same UI

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #8894

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8915)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfriTbEvzmgZ_ShvuPq:-KfriTbEvzmgZ_ShvuPr:bp0bqlt) (no related file):*
Should add the mention of this API to the documentation

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfriADSvAzOFOS4tnEY:-KfriADSvAzOFOS4tnEZ:b-c5dr04) ([raw file](https://github.com/vaadin/framework/blob/e60a759c1ce9d31d15243760c2ed31d2da58ab74/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L156)):*
> is available throughout the drag event on the server side

ITYM "is available in the drop event, if the drop was on a component in the same UI".

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfribofAUt-gJDf99Ip:-KfribofAUt-gJDf99Iq:b-n03m8i) ([raw file](https://github.com/vaadin/framework/blob/e60a759c1ce9d31d15243760c2ed31d2da58ab74/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L115)):*
> ```Java
>      * @return Optional server side drag data if set and the drag source and the
>      * drop target are placed in the same UI, otherwise empty {@code Optional}.
>      */
> ```

Please add `@see DragSourceExtension#setDragData(Object)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8915)*

**Comment by wbadam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfriTbEvzmgZ_ShvuPq:-KftvSCWZKDEcPX3eBsj:b-py1s5q) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should add the mention of this API to the documentation
</blockquote></details>

Extended docs, please take a look

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfriADSvAzOFOS4tnEY:-Kftps5XNyKfzzU1mRSg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e60a759c1ce9d31d15243760c2ed31d2da58ab74/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L156)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> is available throughout the drag event on the server side

ITYM "is available in the drop event, if the drop was on a component in the same UI".
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfribofAUt-gJDf99Ip:-Kftpr6VRzXbFwtZCujB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e60a759c1ce9d31d15243760c2ed31d2da58ab74/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L115)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add `@see DragSourceExtension#setDragData(Object)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8915)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuYiJK1XWCxo7cpQ1f:-KfuYiJK1XWCxo7cpQ1g:b-a65x6r) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L53)):*
> ```AsciiDoc
> ----
> 
> It is possible to transfer any Object as server side data to the drop target if both the drag source and drop target are placed in the same UI.
> ```

Please add a mention that this is available via `DropEvent.getDragData()`

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuYqRvXNVHRe1EAYe-:-KfuYqRvXNVHRe1EAYe0:b-tkbrxv) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L59)):*
> ```AsciiDoc
> dragSource.addDragStartListener(event ->
>     dragSource.setDragData(myObject);
> );
> ```

Please add the `DragEndListener` where you clear the data too!

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 102 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZ4aV5CyquBDgAGQ5:-KfuZ4aV5CyquBDgAGQ6:b3s4fn) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L102)):*
> ```AsciiDoc
>         Notification.show("DropEvent with data transfer: "+ message);
> 
>         // handle possible server side drag data
> ```

I would clarify:

`// handle possible server side drag data, if the drag source was in same UI`

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 157 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZSpF0vbyJwFEIO4w:-KfuZSpF0vbyJwFEIO4x:b-16cc3d) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L157)):*
> placed

Seems weird, would just remove this

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZWV8E93jA58Kn0-2:-KfuZWV8E93jA58Kn0-3:biv1iyq) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L169)):*
>  placed

Again just remove

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 109 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZqvJ_O3VCliG2nzB:-KfuZqvJ_O3VCliG2nzC:b-rzn4sv) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L109)):*
> This data is set

It is not set automatically. "This data can be set during the drag start event on the server side..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8915)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 53 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuYiJK1XWCxo7cpQ1f:-KfuenGMKy2Kb-VXSjC7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L53)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add a mention that this is available via `DropEvent.getDragData()`
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuYqRvXNVHRe1EAYe-:-KfufTDqI6mjzPZD__ek:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L59)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please add the `DragEndListener` where you clear the data too!
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 102 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZ4aV5CyquBDgAGQ5:-Kfufa55RYjfKvM5fz5t:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/documentation/advanced/advanced-dragndrop.asciidoc#L102)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I would clarify:

`// handle possible server side drag data, if the drag source was in same UI`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 157 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZSpF0vbyJwFEIO4w:-KfufmlUajyCB0fdoARt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L157)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> placed

Seems weird, would just remove this
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZWV8E93jA58Kn0-2:-Kfufs_0MT89O5qM-2bC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L169)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  placed

Again just remove
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 109 at r2](https://reviewable.io:443/reviews/vaadin/framework/8915#-KfuZqvJ_O3VCliG2nzB:-KfugATHQC18N-XSvX3C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/524c906f85f8c373dd6e2ee04f699bfefff92d36/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L109)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> This data is set

It is not set automatically. "This data can be set during the drag start event on the server side..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8915)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8915)*

**Pull request merged**
