### PR TITLE
Fix 9310 tree design Part II

### LINKED ISSUE #9310: New Tree component theme
## Selection styles

The selection styles should encapsulate the whole item instead of only the caption.

### Incorrect (current):
screen shot 2017-05-12 at 13 16 56

### Correct:
screen shot 2017-05-12 at 13 16 40

## Focus styles

The focus styles should also wrap the whole row, not just the caption.

#### Non-selected row focused
screen shot 2017-05-12 at 13 36 16

#### Selected row focused
screen shot 2017-05-12 at 13 36 04

#### Non-selected row focused
screen shot 2017-05-12 at 13 34 16

#### Selected row focused
screen shot 2017-05-12 at 13 34 24

Here’s a working CSS snippet for the focus styles (color and border-radius values should be replaced with variables and/or computed values):

```css
.v-tree8-rowmode-cell-focused::after {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  box-sizing: border-box;
  width: 100%;
  height: 100%;
  border: 2px solid transparent;
  box-shadow: inset 0 0 0 1px #197de1;
  border-radius: 4px;
}

.v-tree8-row-selected .v-tree8-rowmode-cell-focused::after {
  box-shadow: inset 0 0 0 1px #fff;
}
```

## Row height 
The row height should be 28px by default (currently 37px), like in the old tree component. You can copy the computation from the old version. A similar Sass variable should be exposed for the new tree: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree.scss#L5

## Item icons

If an item has an icon, an extra white space character is added to the item caption. This should be done using CSS margins instead, by wrapping the caption in a new `span` element (which allows more fine-grained control for a theme developer to align the caption and the icon): https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/connectors/tree/TreeRendererConnector.java#L54

The resulting HTML should be like this:

```html
<div class="gwt-HTML v-tree8-cell-content">
  <span class="v-icon Vaadin-Icons"></span>
  <span class="v-captiontext>Desktops</span>
</div>
```

After this change, the white space is automatically provided by the Valo theme: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/shared/_global.scss#L304-L305

## Other issues

- The `$v-tree8-border-radius` for the new tree should be computed instead of hardcoded to `3px`: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L3

- `$v-grid-cell-padding` used but not available – this line should be removed: https://github.com/vaadin/framework/blob/master/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L39

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9310

Please do not merge before #9390

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9401)

### CODE REVIEW

**Comment by elmot** [comment]
---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9401#-:-Kkl7zjUmHpkmSxdxWw6:b-4k2dzf)*

**Comment by hesara** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss, line 7 at r3](https://reviewable.io:443/reviews/vaadin/framework/9401#-KkoVl5GgjGOG7rs9ri2:-KkoVl5HDvXyCQNRUNFX:bx1r338) ([raw file](https://github.com/vaadin/framework/blob/a4f90a85f345cc181d4fd7f13f0728f9680b5834/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L7)):*
> ```SCSS
>   @include valo-treegrid($primary-stylename);
> 
>   $tree-sel-bg: $v-grid-row-selected-background-color;
> ```

should this be inside or outside the mixin?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9401)*

**Comment by jouni** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss, line 7 at r3](https://reviewable.io:443/reviews/vaadin/framework/9401#-KkoVl5GgjGOG7rs9ri2:-Kkoj9Zk01ra17c-eTKK:b-824bv1) ([raw file](https://github.com/vaadin/framework/blob/a4f90a85f345cc181d4fd7f13f0728f9680b5834/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L7)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this be inside or outside the mixin?
</blockquote></details>

I assume it’s just used as a shorter variable name internally in the mixin, so it should be inside.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss, line 54 at r3](https://reviewable.io:443/reviews/vaadin/framework/9401#-Kkojha97iYMLfF6Tz3a:-Kkojha97iYMLfF6Tz3b:b-kwa1vk) ([raw file](https://github.com/vaadin/framework/blob/a4f90a85f345cc181d4fd7f13f0728f9680b5834/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L54)):*
> ```SCSS
> 
>     $tree-sel-focus-border-color: adjust-color($tree-sel-bg, $lightness: -8%, $saturation: -8%);
>     $tree-sel-focus-box-shadow: inset 0 0 0 1px lighten($v-app-background-color, 8%);
> ```

These are unnecessary variables. The focused row/cell should not have any extra border, and the box shadow can be the same color as the sel-bg. When a selected cell is focused, then we add another box-shadow which is a contrast color of the sel-bg color (you can use valo-font-color to compute that color).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9401)*

**Comment by jouni** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9401#-:-Kkp7jEfXbDcpOmSmfN-:bnfp4nl)*

**Comment by hesara** [comment]
LGTM for the other parts (though see non-blocking comments - could maybe create a ticket about configurable row height), and marking the SCSS file as reviewed primarily based on Jouni's LGTM.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 211 at r1](https://reviewable.io:443/reviews/vaadin/framework/9401#-Kkp79oZFHUMDzCDWIHR:-Kkp79oZFHUMDzCDWIHS:b-tfpmc2) ([raw file](https://github.com/vaadin/framework/blob/9572e3314c3f6b65abf10cfba0c0e0438b9911a3/server/src/main/java/com/vaadin/ui/Tree.java#L211)):*
> ```Java
>         }
>         treeGrid.setPrimaryStyleName("v-tree8");
>         treeGrid.setRowHeight(28);
> ```

(hard coded, but I guess ok for now - could expose this for modifications)

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss, line 16 at r4](https://reviewable.io:443/reviews/vaadin/framework/9401#-Kkp7fxjufT2teZrrK6r:-Kkp7fxjufT2teZrrK6s:b-83xd5z) ([raw file](https://github.com/vaadin/framework/blob/382f6b9441b18e7e448e197f4d1eedb1664c4e8d/themes/src/main/themes/VAADIN/themes/valo/components/_tree8.scss#L16)):*
> ```SCSS
>     background-color: transparent;
>     border: 0;
>     line-height: 28px;
> ```

(hard coded, matching Tree Java class - ideally would be somehow configurable)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9401#-:-Kkp8U0AZUBIEV1MhlXu:b1vkyq7)*

**Pull request merged**
