### PR TITLE
Avoid using Guava API in the documentation

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8231)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[documentation/components/components-grid.asciidoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/8231#-KaHTrA1N5OZAhTe7V_H:-KaHTrA1N5OZAhTe7V_I:b48iltk) ([raw file](https://github.com/vaadin/framework/blob/6f093a63738c7a49b2ab57fa0c1f911c3b83fa4f/documentation/components/components-grid.asciidoc#L633)):*
> ```AsciiDoc
>       // Filter the list of items
>       List<String> filteredList =
>         Arrays.asList(personList.filter(persons,
> ```

is the result of filter() an Iterable or an array?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-grid.asciidoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/8231#-KaHTrA1N5OZAhTe7V_H:-KaHW6UUIIScasxaPauW:b-y9no0v) ([raw file](https://github.com/vaadin/framework/blob/6f093a63738c7a49b2ab57fa0c1f911c3b83fa4f/documentation/components/components-grid.asciidoc#L633)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is the result of filter() an Iterable or an array?
</blockquote></details>

Hard to say since `personList` is not declared as a variable here. I'll just leave this one unchanged since it's inside the filtering section that is currently commented out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-grid.asciidoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/8231#-KaHTrA1N5OZAhTe7V_H:-KaHZ7uWmV5fB2NdUM1j:b-rpepiy) ([raw file](https://github.com/vaadin/framework/blob/6f093a63738c7a49b2ab57fa0c1f911c3b83fa4f/documentation/components/components-grid.asciidoc#L633)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Hard to say since `personList` is not declared as a variable here. I'll just leave this one unchanged since it's inside the filtering section that is currently commented out.
</blockquote></details>

This will go to the public documentation site soon after merged - might feel like a bit strange a comment, but I hope this gets updated soon. I'll remove my blocker as I'll be away, but others can decide on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/components/components-grid.asciidoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/8231#-KaHTrA1N5OZAhTe7V_H:-KaHhYIEYuTvnnKRZpol:b-uu9wx0) ([raw file](https://github.com/vaadin/framework/blob/6f093a63738c7a49b2ab57fa0c1f911c3b83fa4f/documentation/components/components-grid.asciidoc#L633)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This will go to the public documentation site soon after merged - might feel like a bit strange a comment, but I hope this gets updated soon. I'll remove my blocker as I'll be away, but others can decide on this.
</blockquote></details>

Just to clarify: The entire Filtering section is currently commented out and should be rewritten before it's made visible anywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8231)*

**Pull request merged**
