### PR TITLE
Fixing autocompletion issue with ComboBox on newer Chrome versions

### PR DESCRIPTION
**Pull request by TatuLund**
Newer Chrome versions do not work with random number hack to prevent auto completion, but it finally supports autocomplete=off.

Fixes https://github.com/vaadin/framework/issues/11437

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)

### CODE REVIEW

**Comment by knoobie** [comment]
Would it be worth to investigate if the random number can be removed for all browsers?

**Comment by TatuLund** [comment]
> Would it be worth to investigate if the random number can be removed for all browsers?

Maybe.

Note, it seems that support for autocomplete=off is not yet perfect in Chrome. But I assume that it works better than random number.

https://bugs.chromium.org/p/chromium/issues/detail?id=928305&can=1&q=component%3AUI%3EBrowser%3EAutofill. S

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)* status: all files reviewed, 1 unresolved discussion (waiting on @TatuLund)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11472#-La-CfQ7Bu9RH-y9nac4:-La-CfQ7Bu9RH-y9nac5:b-cu62sw) (no related file):*
The fix is fine, but I think we should add a test in case later there is something wrong that we even don't know. 

you can add a very simple IT test for `chrome` browser:

UI: add a `ComboBox` 

Test: 
```
WebElement input = findElement(By.className("v-filterselect-input"));
assertEquals("autocomplete attribute should be off on Chrome", "off", input.getAttribute("autocomplete") );
```

or it would be better that you can add a test for multi-browsers, for other browsers, you can check the value is not equal to `off`, as the attribute should be a random number. 

---

**Comment by TatuLund** [comment]
I think the proposed method for test case is not working. In the past Chrome did show auto completion even when attribute was off, so assessment of attribute is useless.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)* status: all files reviewed, 1 unresolved discussion (waiting on @TatuLund)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11472#-La-CfQ7Bu9RH-y9nac4:-La-Hsm_3DdhMRdW5gaQ:bxcoyor) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

The fix is fine, but I think we should add a test in case later there is something wrong that we even don't know. 

you can add a very simple IT test for `chrome` browser:

UI: add a `ComboBox` 

Test: 
```
WebElement input = findElement(By.className("v-filterselect-input"));
assertEquals("autocomplete attribute should be off on Chrome", "off", input.getAttribute("autocomplete") );
```

or it would be better that you can add a test for multi-browsers, for other browsers, you can check the value is not equal to `off`, as the attribute should be a random number. 
</blockquote></details>

if there is no autocompletion attribute, there should be an error thrown from the `findElement()` method right?
and on the other hand, currently, the chrome shows this attribute and this test works. so this test is used for testing the current chrome but not the former one maybe and informing us Chrome is doing some changes with this attribute in the future. 

---

**Comment by TatuLund** [comment]
I meant that even if our testing of the attribute value passes, it really does not tell anything for sure how Chrome works. I.e. the auto completion popup may still appear there.

**Comment by TatuLund** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/framework/11472#-La-CfQ7Bu9RH-y9nac4:-LbWwx_iAbh5Ezxpm7v6:b-m3u2dy) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

if there is no autocompletion attribute, there should be an error thrown from the `findElement()` method right?
and on the other hand, currently, the chrome shows this attribute and this test works. so this test is used for testing the current chrome but not the former one maybe and informing us Chrome is doing some changes with this attribute in the future. 
</blockquote></details>

Automated test cannot be done since the autocomplete popup in Chrome is not a dom element that could be detected.

---

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11472#-La-CfQ7Bu9RH-y9nac4:-LbWx6Ud4z9BOkoSHI6o:b-896fix) (no related file):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Automated test cannot be done since the autocomplete popup in Chrome is not a dom element that could be detected.
</blockquote></details>

Done.

---

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11472)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
