### PR TITLE
Update example for Comparator in grid

### PR DESCRIPTION
**Pull request by anasmi**
Fixes https://github.com/vaadin/framework/issues/10337

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10833)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 61 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10833#-LAT07UA9witUNNmrBYQ:-LAT07UA9witUNNmrBYR:b-a7tl3m) ([raw file](https://github.com/vaadin/framework/blob/7e36f76bfdabc43fa3c8d1ef1ddcace7109dea8d/documentation/datamodel/datamodel-providers.asciidoc#L61)):*
> ```AsciiDoc
> [source, java]
> ----
> grid.addColumn("Name", Person::getName)
> ```

This line is also wrong.
Use 
```java
grid.addColumn( Person::getName).setCaption("Name")
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Comment by anasmi** [comment]
*[documentation/datamodel/datamodel-providers.asciidoc, line 61 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10833#-LAT07UA9witUNNmrBYQ:-LATA13CDEp_GJ2V2RAu:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/7e36f76bfdabc43fa3c8d1ef1ddcace7109dea8d/documentation/datamodel/datamodel-providers.asciidoc#L61)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This line is also wrong.
Use 
```java
grid.addColumn( Person::getName).setCaption("Name")
```
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 61 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10833#-LATElt96t4K_U0r5T7Y:-LATElt96t4K_U0r5T7Z:bsk0g13) ([raw file](https://github.com/vaadin/framework/blob/b2d8f9d12eecf98b7fc69957c5a398f0fb379811/documentation/datamodel/datamodel-providers.asciidoc#L61)):*
> ```
> addColumn("Name", Person::getName)
> ```
!st parameter to be removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Comment by anasmi** [comment]
*[documentation/datamodel/datamodel-providers.asciidoc, line 61 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10833#-LATElt96t4K_U0r5T7Y:-LATKzO8CpxfxzovbjLh:b-896fjx) ([raw file](https://github.com/vaadin/framework/blob/b2d8f9d12eecf98b7fc69957c5a398f0fb379811/documentation/datamodel/datamodel-providers.asciidoc#L61)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> ```
> addColumn("Name", Person::getName)
> ```
!st parameter to be removed.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10833)*

**Pull request merged**
