### PR TITLE
Replacement guide javadocs for deprecated classes, part two

### PR DESCRIPTION
**Pull request by elmot**
Partial fix for #8682

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8719)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 16 of 26 files at r1.
Review status: 16 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-KeIU2MyB5MQpIahG8Ko:b-e44l86) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
> ```Java
>  * @since 7.4
>  *
>  * @deprecated As of 8.0, no replacement available.
> ```

could probably mention Binder withConverter, as that is helpful for the users unlike a plain "no replacement available" message

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUCTdQys3LXNPu2w1:-KeIUCTdQys3LXNPu2w2:b2ss7xm) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java#L41)):*
> ```Java
>  * @author Vaadin Ltd
>  *
>  * @deprecated As of 8.0, no replacement available.
> ```

see comment above

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUGLmH83TGljmuOzb:-KeIUGLmH83TGljmuOzc:b2ss7xm) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java#L39)):*
> ```Java
>  * @since 7.4
>  *
>  * @deprecated As of 8.0, no replacement available.
> ```

see comment above

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/BeanValidator.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUMzB94AKm0-Bstaa:-KeIUMzB94AKm0-Bstab:b-shw5yv) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/validator/BeanValidator.java#L48)):*
> ```Java
>  * @author Henri Sara
>  *
>  * @deprecated, see {@link BeanValidationBinder}
> ```

and the new BeanValidator (I think it can also be used explicitly outside a BeanValidationBinder)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by elmot** [comment]
Review status: 16 of 26 files reviewed at latest revision, 4 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-KeIbLOgATOFuos8aiff:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could probably mention Binder withConverter, as that is helpful for the users unlike a plain "no replacement available" message
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUCTdQys3LXNPu2w1:-KeIb_Txv998DUcRo5TU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUGLmH83TGljmuOzb:-KeIbe9Z8LgyoYqYvmm4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment above
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/BeanValidator.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUMzB94AKm0-Bstaa:-KeId6xVJ9ZAbttBAKpV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/validator/BeanValidator.java#L48)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

and the new BeanValidator (I think it can also be used explicitly outside a BeanValidationBinder)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by hesara** [comment]
Reviewed 2 of 26 files at r1, 1 of 4 files at r2.
Review status: 19 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ConverterFactory.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/8719#-KertD05uBV8Fqj44bqM:-KertD05uBV8Fqj44bqN:b-3hklw5) ([raw file](https://github.com/vaadin/framework/blob/8ef351c47f0140e3e63abe403fbab4569b997f9d/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ConverterFactory.java#L28)):*
> ```Java
>  * @since 7.0
>  *
>  * @deprecated As of 8.0, no replacement available.
> ```

... - provide explicit converters for Binder

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ReverseConverter.java, line 33 at r2](https://reviewable.io:443/reviews/vaadin/framework/8719#-KersTXpZpQVK1twWQFC:-KersTXq0Fj9jwNJTUfi:bxup8b5) ([raw file](https://github.com/vaadin/framework/blob/8ef351c47f0140e3e63abe403fbab4569b997f9d/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ReverseConverter.java#L33)):*
> ```Java
>  * @since 7.0
>  *
>  * @deprecated As of 8.0, no replacement available.
> ```

... no direct replacement ...

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-Kerr_muK90DABrOSyUd:b-9fp874) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

might -> could

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUCTdQys3LXNPu2w1:-KerrcAdkrB1Guc_aMJt:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java#L41)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

see above

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUGLmH83TGljmuOzb:-KerrddDdxzDUTYlWHG9:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java#L39)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by elmot** [comment]
Review status: 19 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ConverterFactory.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/framework/8719#-KertD05uBV8Fqj44bqM:-KesWKwWyk_aIW4maex_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8ef351c47f0140e3e63abe403fbab4569b997f9d/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ConverterFactory.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... - provide explicit converters for Binder
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ReverseConverter.java, line 33 at r2](https://reviewable.io:443/reviews/vaadin/framework/8719#-KersTXpZpQVK1twWQFC:-KesWZJ5gXwCXAX9xtVm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8ef351c47f0140e3e63abe403fbab4569b997f9d/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/ReverseConverter.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... no direct replacement ...
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-KesXha3WIkVMaLF96ZL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

might -> could
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUCTdQys3LXNPu2w1:-KesXlAVtWjpEo-tAQaW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToCollectionConverter.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIUGLmH83TGljmuOzb:-KesXltATb0dHIq327TK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToEnumConverter.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by hesara** [comment]
Reviewed 3 of 6 files at r3.
Review status: 21 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-KfGBH0ZsvAYryqz_guS:b2675ch) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, "can" would be more correct

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/CompositeValidator.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/framework/8719#-KfGBUBJhVkse5FcUfIq:-KfGBUBJhVkse5FcUfIr:b-cgnn53) ([raw file](https://github.com/vaadin/framework/blob/01432275f09b559ca4ffe45d2d6ec6ba7f839661/compatibility-server/src/main/java/com/vaadin/v7/data/validator/CompositeValidator.java#L38)):*
> ```Java
>  * @since 3.0
>  *
>  * @deprecated As of 8.0, no replacement available. See {@link Binder#forField(HasValue)},
> ```

instead of this, mention chaining of validators

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/NullValidator.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/8719#-KfGBgY8K9mC_oY6uFTE:-KfGBgY8K9mC_oY6uFTF:b4kafof) ([raw file](https://github.com/vaadin/framework/blob/01432275f09b559ca4ffe45d2d6ec6ba7f839661/compatibility-server/src/main/java/com/vaadin/v7/data/validator/NullValidator.java#L29)):*
> ```Java
>  * @since 3.0
>  *
>  * @deprecated As of 8.0, no replacement available. See {@link Binder.BindingBuilder#withNullRepresentation(Object)}
> ```

maybe instead or in addition to this, just refer to the normal validation mechanism

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by elmot** [comment]
Review status: 20 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8719#-KeIU2MxRtRJTABkPCiy:-KfGMkpVXV2j1g3fKcwf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c7f6affb45d0a70e510b305865fa5b54e00ee36/compatibility-server/src/main/java/com/vaadin/v7/data/util/converter/StringToByteConverter.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

actually, "can" would be more correct
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/CompositeValidator.java, line 38 at r3](https://reviewable.io:443/reviews/vaadin/framework/8719#-KfGBUBJhVkse5FcUfIq:-KfGOwmYR0osMfwhvL-j:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/01432275f09b559ca4ffe45d2d6ec6ba7f839661/compatibility-server/src/main/java/com/vaadin/v7/data/validator/CompositeValidator.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

instead of this, mention chaining of validators
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/validator/NullValidator.java, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/8719#-KfGBgY8K9mC_oY6uFTE:-KfGOxIZVhXGwPS3dh_1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/01432275f09b559ca4ffe45d2d6ec6ba7f839661/compatibility-server/src/main/java/com/vaadin/v7/data/validator/NullValidator.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

maybe instead or in addition to this, just refer to the normal validation mechanism
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8719)*

**Pull request merged**
