### PR TITLE
8.0.3 cherry picks

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8856)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 297 of 305 files at r1.
Review status: 284 of 292 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8856)*

**Comment by hesara** [comment]
Reviewed 5 of 305 files at r1.
Review status: 289 of 292 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8856)*

**Comment by hesara** [comment]
Reviewed 1 of 305 files at r1.
Review status: 290 of 292 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8856)*

**Comment by tsuoanttila** [comment]
Reviewed editor event changes. The added bean in the event is a huge improvement and should be included even if it could be considered a breaking change. No user should've called new EditorSaveEvent(editor) in their code. :lgtm: 

---

Reviewed 2 of 305 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8856#-:-KfMSAb_ojdXIesJJwUX:b-8nh2nk)*

**Pull request merged**
