### PR TITLE
Improved Binder#hasChanges JavaJoc

### PR DESCRIPTION
**Pull request by mstahv**
JavaDoc now more explicitly states that hasChanges is not designed to work with setBean.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8912)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1936 at r1](https://reviewable.io:443/reviews/vaadin/framework/8912#-KfqIifNmsWgG8xB5hLf:-KfqIifNmsWgG8xB5hLg:b-5l733z) ([raw file](https://github.com/vaadin/framework/blob/250f966657f7126d0d52df7f925947e64a4f86d1/server/src/main/java/com/vaadin/data/Binder.java#L1936)):*
> ```Java
> 
>     /**
>      * Check whether any of the bound fields' values have uncommitted changed
> ```

uncommitted changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8912)*

**Comment by mstahv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1936 at r1](https://reviewable.io:443/reviews/vaadin/framework/8912#-KfqIifNmsWgG8xB5hLf:-KfqO3Xy7h9gfbJD3FEa:b-81rpic) ([raw file](https://github.com/vaadin/framework/blob/250f966657f7126d0d52df7f925947e64a4f86d1/server/src/main/java/com/vaadin/data/Binder.java#L1936)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

uncommitted changes
</blockquote></details>

Ough, removed the obsolete "values" as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8912)*

**Comment by mstahv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1936 at r1](https://reviewable.io:443/reviews/vaadin/framework/8912#-KfqIifNmsWgG8xB5hLf:-KfqOB4fmZ7sl6tbsnJy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/250f966657f7126d0d52df7f925947e64a4f86d1/server/src/main/java/com/vaadin/data/Binder.java#L1936)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Ough, removed the obsolete "values" as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8912)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8912)*

**Pull request merged**
