### PR TITLE
Add @FunctionalInterface annotation to interfaces where applicable

### PR DESCRIPTION
**Pull request by ahie**
Closes vaadin/framework8-issues#548

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7954)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 27 of 28 files at r1, 10 of 10 files at r2.
Review status: 37 of 38 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmRXThz-VF_njmblVT:-KYmRXThz-VF_njmblVU:b1sgf8a) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/event/FieldEvents.java#L44)):*
> ```Java
>      * @see FocusEvent
>      */
>     @FunctionalInterface
> ```

I think notifiers shouldn't be functional interfaces as it is (almost) never their main role.

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmRgOjiDNRlHm6eYag:-KYmRgOjiDNRlHm6eYah:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/event/FieldEvents.java#L70)):*
> ```Java
>      * @see BlurEvent
>      */
>     @FunctionalInterface
> ```

see above

---

*[server/src/main/java/com/vaadin/server/Page.java, line 332 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmQMf9oAwar9rEUEuC:-KYmQMfAK1_FCkWeZDZJ:bhl7zdn) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/server/Page.java#L332)):*
> ```Java
> 
>     @FunctionalInterface
>     private static interface InjectedStyle extends Serializable {
> ```

(private and doesn't really require @FunctionalInterface, but probably won't hurt either)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7954)*

**Comment by elmot** [comment]
Reviewed 27 of 28 files at r1, 2 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmSNOxqAXTyuC0qZsY:-KYmSNOxqAXTyuC0qZsZ:bjq2rhg) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/ui/declarative/Design.java#L79)):*
> ```Java
>      * @since 7.4.1
>      */
>     @FunctionalInterface
> ```

IMHO we do not want our customers to make lambdas from this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7954)*

**Comment by elmot** [comment]
Reviewed 1 of 28 files at r1, 8 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7954)*

**Comment by ahie** [comment]
Review status: 36 of 37 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 44 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmRXThz-VF_njmblVT:-KYmf4fwRRhTsZo7sKvr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/event/FieldEvents.java#L44)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I think notifiers shouldn't be functional interfaces as it is (almost) never their main role.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 70 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmRgOjiDNRlHm6eYag:-KYmf4yEydmsTfqB2wRm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/event/FieldEvents.java#L70)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 79 at r2](https://reviewable.io:443/reviews/vaadin/framework/7954#-KYmSNOxqAXTyuC0qZsY:-KYmfbXyEb6dJpHvGWKd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/95106e87af2ea71e44710d48ddfb2c0f27991e75/server/src/main/java/com/vaadin/ui/declarative/Design.java#L79)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

IMHO we do not want our customers to make lambdas from this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7954)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7954#-:-KYmkpUn7OtN5UgUPOYn:bnfp4nl)*

**Pull request merged**
