### PR TITLE
Fix ComboBoxClosePopupRetainTextTest

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9399)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxClosePopupRetainTextTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/9399#-KkkIZyqDTdx9zAL4usv:-KkkIZyqDTdx9zAL4usw:b7atq2d) ([raw file](https://github.com/vaadin/framework/blob/58d54c7d851f06d2128aa1a0593012220af5c02c/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxClosePopupRetainTextTest.java#L43)):*
> ```Java
>         // Uses #clickElement instead of ComboBoxElement#openPopup() due to an
>         // issue with the firefox driver
>         clickElement(cb.findElement(By.vaadin("#button")));
> ```

should we fix ComboBoxElement.openPopup() instead of doing local hacks?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399)*

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxClosePopupRetainTextTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/9399#-KkkIZyqDTdx9zAL4usv:-KkkQ7wCcav2gf7Vv8QN:b-5q3f6j) ([raw file](https://github.com/vaadin/framework/blob/58d54c7d851f06d2128aa1a0593012220af5c02c/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxClosePopupRetainTextTest.java#L43)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should we fix ComboBoxElement.openPopup() instead of doing local hacks?
</blockquote></details>

Added the workaround directly to the element, although it looks like AbstractTB3Test#clickElement was introduced for precisely these kinds of workarounds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399)*

**Comment by hesara** [comment]
:lgtm: assuming this doesn't break any other tests (but this should rather fix things)

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399#-:-KkkTl24vfGF1f-jSdGk:bubrp27)*

**Comment by hesara** [comment]
Started complete test build on Firefox only for this

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399#-:-KkoJbv4zvw34SDOdfge:b7ct9a)*

**Comment by hesara** [comment]
This caused some test failures on r2d2 (build 154059) - we might want to revert to the first local workaround after all

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399#-:-KkotV35AZ_yAGcJXiRE:bf2ny72)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9399#-KkozQ_Jiv-_xwdEJeeL:-KkozQ_Jiv-_xwdEJeeM:b-be8mbj) (no related file):*
Need to revert to old localized workaround or fix other tests affected by the fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9399#-KkozQ_Jiv-_xwdEJeeL:-KkpFG0nEiDFba2OXveF:b-896fix) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Need to revert to old localized workaround or fix other tests affected by the fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399#-:-KkpFedFOeoepZLP6SMt:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9399)*

**Pull request closed without merging**
