### PR TITLE
Do not wait for icons to load before interacting with a combo box

### PR DESCRIPTION
**Pull request by Artur-**
Icon load detection code does not handle error events so broken images
will cause tests to fail forever. In other cases also, it seems very
rare to need icons to be loaded before interacting with a combo box. If
there really are use cases for this, it would be better to have a method
to query if all icons are loaded so that special tests can use this method.

Fixes https://github.com/vaadin/testbench/issues/916

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9717)

### CODE REVIEW

**Comment by alvarezguille** [comment]
:lgtm:
but maybe someone from FW team wants to review VComboBox changes

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717#-:-KpopzM2_Oab1igvWaQX:bw5ui96)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-KpxeKGcClsmZ9_YZUV8:b-5rb2vn) (no related file):*
My main concern is whether this will make screenshot tests less reliable, and perhaps result in references for new screenshot tests to be taken too early. This mostly affects framework testing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-Kr64DkVhhmKuY7n3mPL:b-qtqf0g) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

My main concern is whether this will make screenshot tests less reliable, and perhaps result in references for new screenshot tests to be taken too early. This mostly affects framework testing.
</blockquote></details>

It might do that. It sounds like there should be another way to wait for everything to stabilize, something which should be called before actually taking a screenshot and not before every action. 

If it's only a potential problem for framework testing, then it can be fixed in the corresponding test classes when it actually becomes a problem (by waiting for the onload or similar in the actual test)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-Kr9vkN9GRayfM7QgOw4:b-f5c3iq) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It might do that. It sounds like there should be another way to wait for everything to stabilize, something which should be called before actually taking a screenshot and not before every action. 

If it's only a potential problem for framework testing, then it can be fixed in the corresponding test classes when it actually becomes a problem (by waiting for the onload or similar in the actual test)?
</blockquote></details>

Needs rebase. 

In my opinion this could be taken in more or less as is and fix the tests to wait for the event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-Kr9xgZh1bdZvU-iuJjH:b-sylqrb) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Needs rebase. 

In my opinion this could be taken in more or less as is and fix the tests to wait for the event.
</blockquote></details>

Might not even need a rebase. My bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-KrFP2ZdXMbe18_DKPc5:b9o0x7a) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Might not even need a rebase. My bad.
</blockquote></details>

Based on a quick search, these framework tests might (or might not) be affected, potentially becoming unstable:
- ComboBoxLargeIconsTest
- ComboBoxClickIconTest
- FontIconsTest
- VaadinIconSetTest
- LegacyComponentThemeChangeTest
- ValoThemeUITest
- ComboBoxItemStyleGeneratorTest
- ComboBoxClosePopupRetainTextTest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9717#-KpxeKGcClsmZ9_YZUV7:-KrFxZiBBTVpIybLeqi9:bcsnqpo) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Based on a quick search, these framework tests might (or might not) be affected, potentially becoming unstable:
- ComboBoxLargeIconsTest
- ComboBoxClickIconTest
- FontIconsTest
- VaadinIconSetTest
- LegacyComponentThemeChangeTest
- ValoThemeUITest
- ComboBoxItemStyleGeneratorTest
- ComboBoxClosePopupRetainTextTest
</blockquote></details>

Narrowed down the set of potentially problematic tests, ran some tests on them - no problems seen after merging in master, although there could be some issue with taking initial screenshots from such tests. Will run a full build, probably ok to merge if build green.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9717)*

**Pull request merged**
