### PR TITLE
Make BeanBinderPropertySet exclude Object properties

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8306)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Needs manual rebase.

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java, line 161 at r1](https://reviewable.io:443/reviews/vaadin/framework/8306#-KbAnm2mUsM2vzxfbFOE:-KbAnm2mUsM2vzxfbFOF:b-h5fe42) ([raw file](https://github.com/vaadin/framework/blob/10344b222762d85506b78b77a43763e1d521f794/server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java#L161)):*
> ```Java
>         try {
>             definitions = BeanUtil.getBeanPropertyDescriptors(beanType).stream()
>                     .filter(descriptor -> !"class".equals(descriptor.getName()))
> ```

Shouldn't it exclude all `Object` "properties" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8306)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java, line 161 at r1](https://reviewable.io:443/reviews/vaadin/framework/8306#-KbAnm2mUsM2vzxfbFOE:-KbEobBbWMVVwTgt6Wek:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/10344b222762d85506b78b77a43763e1d521f794/server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java#L161)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Shouldn't it exclude all `Object` "properties" ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8306)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8306)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8306)*

**Pull request merged**
