### PR TITLE
Picked changes on top of 8.3.0.beta1

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10531)

### CODE REVIEW

**Comment by wbadam** [comment]
Are all these other commits here on purpose? Changed files seem to be only for the Notification patch.

---

Reviewed 4 of 4 files at r1.
Review status: 4 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10531#-:-L2eeOaW_DaVMGSPbpJf:b-s3hnsz)*

**Comment by tsuoanttila** [comment]
It may be you've only reviewed the first change alone. Click on the "File matrix" button at the top of the page in the "Changes" box to show all files and revisions.

---

Review status: 4 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10531#-:-L2eqveDT32gIrjiEcST:bs24ti8)*

**Comment by wbadam** [comment]
Ok, I see it now, not the most intuitive UI...

---

Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 8 of 8 files at r5, 3 of 3 files at r6, 5 of 5 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2075 at r7](https://reviewable.io:443/reviews/vaadin/framework/10531#-L2ewqlmtBK1f1X4WbsJ:-L2ewqlmtBK1f1X4WbsK:b-gv2u90) ([raw file](https://github.com/vaadin/framework/blob/531320c5051b7f72c9d96c7826b5cd4f9dcaae67/server/src/main/java/com/vaadin/ui/Grid.java#L2075)):*
> ```Java
>         public Column<T, V> setWidgetEventsAllowed(
>                 boolean widgetEventsAllowed) {
>             if (getState(false).widgetEventsAllowed != widgetEventsAllowed) {
> ```

Was this just an unnecessary optimisation?

---

*[tests/screenshots, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/10531#-L2euYTTsiwFBazaRlZ8:-L2euYTTsiwFBazaRlZ9:b-h9mm8i) ([raw file](https://github.com/vaadin/framework/blob/9554a3cada55abc17a3ba4ce0302e3e49980e3b5/tests/screenshots#L1)):*
> ```
> Subproject commit a70c038dcdf9b95d984d5fa7d54acf3f49c45132
> ```

Do I just need to believe that this is correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10531#-:-L2et0tKU8cQB-x7gSi8:b-4evuhe)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2075 at r7](https://reviewable.io:443/reviews/vaadin/framework/10531#-L2ewqlmtBK1f1X4WbsJ:-L2sy5v1l0mf7LHGW1h8:bb77ufg) ([raw file](https://github.com/vaadin/framework/blob/531320c5051b7f72c9d96c7826b5cd4f9dcaae67/server/src/main/java/com/vaadin/ui/Grid.java#L2075)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Was this just an unnecessary optimisation?
</blockquote></details>

Yes.

---

*[tests/screenshots, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/10531#-L2euYTTsiwFBazaRlZ8:-L2syB4YNxD2LSOE0i_6:b-2nod5h) ([raw file](https://github.com/vaadin/framework/blob/9554a3cada55abc17a3ba4ce0302e3e49980e3b5/tests/screenshots#L1)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Do I just need to believe that this is correct?
</blockquote></details>

Related commit is https://github.com/vaadin/vaadin-screenshots/commit/a70c038dcdf9b95d984d5fa7d54acf3f49c45132 containing a bunch of fixed screenshots

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10531)*

**Comment by wbadam** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10531#-:-L2t85He7FBDAogHpG9Z:bnfp4nl)*

**Pull request merged**
