### PR TITLE
Adding getRowIndex() to Grid's ItemClickEvent

### PR DESCRIPTION
**Pull request by TatuLund**
Certain API's in Grid assume row index as parameter instead of item. Hence it would be convenient to get the row index from ItemClickEvent.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10754)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 402 at r2](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8WVUF8axOXGz-ryO_N:-L8WVUF8axOXGz-ryO_O:b-52h9b) ([raw file](https://github.com/vaadin/framework/blob/c7a961f873fca13880deeaf51f2304417556e75d/server/src/main/java/com/vaadin/ui/Grid.java#L402)):*
> ```Java
>             return mouseEventDetails;
>         }
>         
> ```

extra whitespaces

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8WUzATZx1kA-oPWZzh:-L8WUzATZx1kA-oPWZzi:b4iwjd8) ([raw file](https://github.com/vaadin/framework/blob/c7a961f873fca13880deeaf51f2304417556e75d/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java#L10)):*
> ```Java
> public class GridEventListenersTest extends GridBasicsTest {
> 
> 	@Test
> ```

File needs to be formatted.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java, line 25 at r2](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8W_PK6N8HC6wxGl5sd:-L8W_PK6N8HC6wxGl5se:b9d665b) ([raw file](https://github.com/vaadin/framework/blob/c7a961f873fca13880deeaf51f2304417556e75d/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java#L25)):*
> ```Java
> 		grid.getCell(row, 2).click();
> 		String logRow = getLogRow(0);
> 		Assert.assertTrue("Log row did not contain index "+row, logRow.endsWith("Index "+row));
> ```

This test is failing at some point for some reason. Please run locally to verify the issue and fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10754)*

**Comment by TatuLund** [comment]
Fixed

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10754#-:-L8WayT720nzLV-EXa4B:b-886gsx)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 5 files at r2, 1 of 2 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 114 at r6](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8au7vyLjIZtr_niStB:-L8au7vyLjIZtr_niStC:b-psopj0) ([raw file](https://github.com/vaadin/framework/blob/b2d14be79131f3df502f4fed3f997389c8668265/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L114)):*
> ```Java
>             getRpcProxy(GridServerRpc.class).itemClick(rowKey, columnId,
>                     MouseEventDetailsBuilder
>                             .buildMouseEventDetails(mouseEvent),rowIndex);
> ```

nitpick: space missing between `,` and `rowIndex`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 355 at r6](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8auBB_atFwjwdfhRle:-L8auBB_atFwjwdfhRlf:b-u574am) ([raw file](https://github.com/vaadin/framework/blob/b2d14be79131f3df502f4fed3f997389c8668265/server/src/main/java/com/vaadin/ui/Grid.java#L355)):*
> ```Java
>          * Creates a new {@code ItemClick} event containing the given item and
>          * Column originating from the given Grid.
>          *
> ```

Missing `@param` for all parameters of the constructor, not mandatory to fix.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 409 at r6](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8auGIhKbYsq0QlUpwM:-L8auGIhKbYsq0QlUpwN:bvtpdmz) ([raw file](https://github.com/vaadin/framework/blob/b2d14be79131f3df502f4fed3f997389c8668265/server/src/main/java/com/vaadin/ui/Grid.java#L409)):*
> ```Java
>          */
>         public int getRowIndex() {
>         	return rowIndex;
> ```

tab instead of space

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/GridServerRpc.java, line 44 at r6](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8auOT17HUOvHzDNGYf:-L8auOT2cIrUxVV9VZik:bwhrmu0) ([raw file](https://github.com/vaadin/framework/blob/b2d14be79131f3df502f4fed3f997389c8668265/shared/src/main/java/com/vaadin/shared/ui/grid/GridServerRpc.java#L44)):*
> ```Java
>      *            column internal id identifying the clicked property
>      * @param details
>      *            mouse event details
> ```

`@param`

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/10754#-L8WUzATZx1kA-oPWZzh:-L8auXG9vGMEe2IAYqnc:bscar77) ([raw file](https://github.com/vaadin/framework/blob/c7a961f873fca13880deeaf51f2304417556e75d/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridEventListenersTest.java#L10)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

File needs to be formatted.
</blockquote></details>

Still tabs instead of spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10754)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 5 files at r2, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10754)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10754)*

**Pull request merged**
