### PR TITLE
Add possiblity to customize drag data for each row

### LINKED ISSUE #8396: Grid row should be draggable
It should be possible to make any Grid Row a drag source, so that grabbing it will start drag.

For now, the row based drag data can be the key of the row.

For `DropEvent` inside the application, the source should be the Grid component.

### PR DESCRIPTION
**Pull request by wbadam**
resolves #8396

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8706)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hM-3uvYPisejkjEP:-Ke7hM-3uvYPisejkjEQ:b-xw85ek) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L80)):*
> each items

_each item_

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hWF3EOwYejzj52dQ:-Ke7hWF3EOwYejzj52dR:b-mi93hb) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L95)):*
> ```Java
>      *         Function to be executed on row data generation.
>      */
>     public void setDragDataGeneratorCallback(
> ```

Please remove the _Callback_  suffix from the naming, we haven't used that for any of the other callbacks in the FW 8.0, simply _Generator_ or _Provider_  is enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8706)*

**Comment by wbadam** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hM-3uvYPisejkjEP:-Ke7sHixtG43LB6f8_Pc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L80)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> each items

_each item_
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hWF3EOwYejzj52dQ:-Ke7qCMaYNtPw-5lFOXy:b-clq1kv) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L95)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please remove the _Callback_  suffix from the naming, we haven't used that for any of the other callbacks in the FW 8.0, simply _Generator_ or _Provider_  is enough
</blockquote></details>

Done.

Is getter needed for this generator?

Also, is `setNewEscalatorRowCallback()` a proper name in the connector class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8706)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hWF3EOwYejzj52dQ:-KeIAQzte2edxVlOv_kj:b2rswjs) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L95)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Done.

Is getter needed for this generator?

Also, is `setNewEscalatorRowCallback()` a proper name in the connector class?
</blockquote></details>

Might be needed for some reason and no harm in adding it since there is the setter so should be a getter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8706)*

**Comment by wbadam** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8706#-Ke7hWF3EOwYejzj52dQ:-KeIGNEhyuoR8pox9m9K:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2226bca6cc14230e90518b72ee007bf24502b8fb/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L95)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Might be needed for some reason and no harm in adding it since there is the setter so should be a getter
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8706)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8706)*

**Pull request merged**
