### PR TITLE
Update tests for new Chrome

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11150)

### CODE REVIEW

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @elmot and @tsuoanttila)

___
*[uitest/src/test/java/com/vaadin/tests/components/uitest/ThemeTest.java, line 193 at r1](https://reviewable.io/reviews/vaadin/framework/11150#-LLF3mPn7pqqTHRvcngO:-LLF3mPn7pqqTHRvcngP:b4bfl21) ([raw file](https://github.com/vaadin/framework/blob/6000942bf9bfeb08a3895f046ced3e4f917c3806/uitest/src/test/java/com/vaadin/tests/components/uitest/ThemeTest.java#L193)):*
> ```
> Thread.sleep(200);
> ```
Can we use `waitForElementPresent` instead of sleep?

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @elmot and @tsuoanttila)

___
*[uitest/src/test/java/com/vaadin/tests/components/uitest/ThemeTest.java, line 193 at r1](https://reviewable.io/reviews/vaadin/framework/11150#-LLF3mPn7pqqTHRvcngO:-LLF4Q0IDb8d-ZsFRe9o:btsdkl6) ([raw file](https://github.com/vaadin/framework/blob/6000942bf9bfeb08a3895f046ced3e4f917c3806/uitest/src/test/java/com/vaadin/tests/components/uitest/ThemeTest.java#L193)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> Thread.sleep(200);
> ```
Can we use `waitForElementPresent` instead of sleep?
</blockquote></details>

That is not going to help. Tests failed because all the elements were always shown but sometimes focus was not at the proper element. Looks like some timings were changed or refocusing elements became deferred.

**Review by mehdi-vaadin — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @tsuoanttila)

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150#-:-LLF5zAvCpsWC2vul1hA:bnfp4nl)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @tsuoanttila)

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @elmot and @tsuoanttila)

___
*[uitest/src/test/java/com/vaadin/tests/components/upload/InterruptUploadTest.java, line 28 at r2](https://reviewable.io/reviews/vaadin/framework/11150#-LLF8AYOCAoT20Gzj-q0:-LLF8AYOCAoT20Gzj-q1:b1m3q13) ([raw file](https://github.com/vaadin/framework/blob/53e6f71b8343f992c20d392aea928b29a83071da/uitest/src/test/java/com/vaadin/tests/components/upload/InterruptUploadTest.java#L28)):*
> ```
> Schedule  upload cancel in a second
> ```
Schedule upload cancel in two seconds
___
*[uitest/src/test/java/com/vaadin/tests/extensions/ResponsiveLayoutUpdateTest.java, line 26 at r3](https://reviewable.io/reviews/vaadin/framework/11150#-LLFADnJ3LGt6D0rn-Ak:-LLFADnJ3LGt6D0rn-Al:be5turk) ([raw file](https://github.com/vaadin/framework/blob/583c3363dc2a471679b30d64a60d48d7159aedf4/uitest/src/test/java/com/vaadin/tests/extensions/ResponsiveLayoutUpdateTest.java#L26)):*
> ```
> waitUntil(input -> panelElement.getSize().getWidth() < 500);
> ```
It seems that this line does nothing since the width is either 200 or 300.

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11150#-:-LLFEUuD3dzcC55dIQYV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tsuoanttila)

___
*[uitest/src/test/java/com/vaadin/tests/components/upload/InterruptUploadTest.java, line 28 at r2](https://reviewable.io/reviews/vaadin/framework/11150#-LLF8AYOCAoT20Gzj-q0:-LLFEKfu5hYAugNrFf5W:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/53e6f71b8343f992c20d392aea928b29a83071da/uitest/src/test/java/com/vaadin/tests/components/upload/InterruptUploadTest.java#L28)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> Schedule  upload cancel in a second
> ```
Schedule upload cancel in two seconds
</blockquote></details>

OK

**Pull request merged**
