### PR TITLE
Pick changes for 8.2.0.beta1

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10345)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 68 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10345#-KzTfCCp43D_nB4VpO30:-KzTfCCp43D_nB4VpO31:b-1mmzqb) (no related file):*
Keeping this open for a moment still to see if there are still some changes we should take in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Comment by ahie** [comment]
Reviewed 3 of 3 files at r1.
Review status: 3 of 68 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Comment by ahie** [comment]
Reviewed 29 of 29 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 5 of 5 files at r5, 23 of 23 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10345#-KzTfCCp43D_nB4VpO30:-KzU7Go2kFv4Ld0RUelm:b32w0x) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Keeping this open for a moment still to see if there are still some changes we should take in.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Comment by ahie** [comment]
Reviewed 9 of 9 files at r7.
Review status: 75 of 77 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10345)*

**Pull request merged**
