### PR TITLE
Documented minimal set of OSGi bundles

### LINKED ISSUE #9383: OSGi documentation: what is the minimal set of vaadin bundles to be deployed with an applicatoin?

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9383

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9489)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Going to need a second opinion from someone who knows a bit more on this, but looks ok for me when a couple of typos are fixed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1eucQo0Y_ptG2Jor:-Km_1eucQo0Y_ptG2Jos:biakmzn) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L39)):*
> osgi
OSGi

---

*[documentation/advanced/advanced-osgi.asciidoc, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1QyYGm6Dk1h6N5pc:-Km_1QyZhvIgqkbWI2Sn:b1cg0ud) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L172)):*
>  ho 
to

---

*[documentation/advanced/advanced-osgi.asciidoc, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1TYZ8QO-5Oj1Bumr:-Km_1TY_wjRwSBpNqJqo:bn87bk9) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L172)):*
> unsing
using

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489#-:-Km_1vRsy8LoojusMD39:b-4lxcog)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1eucQo0Y_ptG2Jor:-KmeWn2JhxfVEvBlgmJY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L39)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> osgi
OSGi
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1QyYGm6Dk1h6N5pc:-KmeWnJdHXySV8iE7Ca5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L172)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

>  ho 
to
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9489#-Km_1TYZ8QO-5Oj1Bumr:-KmeWtVj7O_heMkdeOL-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/48b991f576794a60c52aaa7b7a80a556ab130f9a/documentation/advanced/advanced-osgi.asciidoc#L172)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> unsing
using
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-Ah6tOjD407GWbEuA:-Kn-Ah6uOjboF2Nad6-t:b-ekrz4f) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L22)):*
> ```AsciiDoc
> [[advanced.osgi.servlet.maven]]
> == Minimal Vaadin Project For OSGi
> Vaadin application for OSGi should be a valid bundle, i.e. it should bepackaged as a `.jar` file, and it should have proper OSGi manifest inside.
> ```

be packaged; ... have a proper OSGi manifest ...

---

*[documentation/advanced/advanced-osgi.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-Ao6DNiY_7dpsX43Q:-Kn-Ao6DNiY_7dpsX43R:bgpq2lr) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L23)):*
> ```AsciiDoc
> == Minimal Vaadin Project For OSGi
> Vaadin application for OSGi should be a valid bundle, i.e. it should bepackaged as a `.jar` file, and it should have proper OSGi manifest inside.
> The easiest way to convert regular maven-based Vaadin application into valid OSGi bundle contains five steps:
> ```

... into a valid OSGi bundle consist of five steps:

---

*[documentation/advanced/advanced-osgi.asciidoc, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-AwEIOYfMahvIKGEK:-Kn-AwEIOYfMahvIKGEL:blp7abn) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L30)):*
> ```AsciiDoc
>     <packaging>jar</packaging>
> ----
> * For change scope for all vaadin dependencies from default to `provided`, like this:
> ```

"For change scope" -> "Change the scope" ?

---

*[documentation/advanced/advanced-osgi.asciidoc, line 161 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-BJOMddTRGbypUGVY:-Kn-BJOMddTRGbypUGVZ:b-sejnjc) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L161)):*
> ```AsciiDoc
> == Deployment to OSGi container.
> 
> In order to have your application running under OSGi container, you need to have Vaadin framework parts deployed, and then the application bundle can be deployed and started.
> ```

parts -> bundles?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-Ah6tOjD407GWbEuA:-Kn-OyHNSBaqdCXnNQnV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

be packaged; ... have a proper OSGi manifest ...
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-Ao6DNiY_7dpsX43Q:-Kn-PFBTIag3bVmC9492:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... into a valid OSGi bundle consist of five steps:
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-AwEIOYfMahvIKGEK:-Kn-PFqQfJLT_gFSVG2V:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"For change scope" -> "Change the scope" ?
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 161 at r2](https://reviewable.io:443/reviews/vaadin/framework/9489#-Kn-BJOMddTRGbypUGVY:-Kn-PYcb9xBrydaTQFia:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9165b7fe4ab41ef4425d1e036a5a5b9ff516040/documentation/advanced/advanced-osgi.asciidoc#L161)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

parts -> bundles?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489)*

**Comment by hesara** [comment]
:lgtm: - @tsuoanttila to remove his blockers

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9489#-:-KpxWAD2Bku2gFJZyd_G:b-ybhq2k)*

**Pull request merged**
