### PR TITLE
Fix recursive menu hiding

### PR DESCRIPTION
**Pull request by elmot**
Fixes incorrect keyboard handling in ContextMenu addon

Fixes https://github.com/vaadin/context-menu/issues/76

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10817)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10817#-L9uEsMy745crpSK_rxZ:-L9uEsMy745crpSK_rx_:b4uio0e) (no related file):*
The PR is blocked untill all the manual testing is done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10817)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10817)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10817#-L9uEsMy745crpSK_rxZ:-LAMwFPDDc-OBUlcn8r5:b-x0qgw2) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The PR is blocked untill all the manual testing is done
</blockquote></details>

A manual testing of ContextMenu shows that the fix works. I have just started a full verification build to be sure if nothing else is broken

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10817)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10817#-L9uEsMy745crpSK_rxZ:-LANs_vg4IP4yvGHOXzt:b-nb23z3) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

A manual testing of ContextMenu shows that the fix works. I have just started a full verification build to be sure if nothing else is broken
</blockquote></details>

I see no regressions in the validation build.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10817)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10817)*

**Pull request merged**
