### PR TITLE
Always calculate Escalator max row count the same way

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8740)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8740#-Kec1AafuQ1AxKFct6s9:-Kec1AagYiuxvqmqzDgk:b-guria3) ([raw file](https://github.com/vaadin/framework/blob/cfbc69078187ce30472b2e38e87cbaa642a836d9/uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java#L71)):*
> ```Java
>         grid.getColumn("Button1").setRenderer(new ButtonRenderer());
>         grid.getColumn("col1").setWidth(1600);
>         grid.getColumns().forEach(new Consumer<Column>() {
> ```

requires java 8, and the patch is for Vaadin 7.7

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8740)*

**Comment by Artur-** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8740#-Kec1AafuQ1AxKFct6s9:-Kec4qmNavXUTPFYUPx5:b-7ri22i) ([raw file](https://github.com/vaadin/framework/blob/cfbc69078187ce30472b2e38e87cbaa642a836d9/uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java#L71)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

requires java 8, and the patch is for Vaadin 7.7
</blockquote></details>

Strange that validation said it was ok...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8740)*

**Comment by tsuoanttila** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8740#-Kec1AafuQ1AxKFct6s9:-Kec7w6ciIO954RMLYhS:b-de2yvt) ([raw file](https://github.com/vaadin/framework/blob/cfbc69078187ce30472b2e38e87cbaa642a836d9/uitest/src/main/java/com/vaadin/tests/components/grid/HideGridColumnWhenHavingUnsuitableHeight.java#L71)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Strange that validation said it was ok...
</blockquote></details>

This is exactly the reason we've discussed moving validation towards Travis.. There are still some problems with it though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8740)*

**Comment by hesara** [comment]
:lgtm: - will run test builds in 7.7 branch after merging this and some unrelated test fixes

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8740#-:-KecLqPTdUsWBbXAW-pQ:bh0eck)*

**Pull request merged**
