### PR TITLE
Use simple class names

### PR DESCRIPTION
**Pull request by asashour**
I hope the compatibility packages changes are not much.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10030)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 41 of 42 files at r1.
Review status: 41 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/ColumnProperty.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10030#-KuSmL0EGrp17US7E6R3:-KuSmL0FW40Hg_0q7IPz:botjzgj) ([raw file](https://github.com/vaadin/framework/blob/2d63777849c91bba96e52a828439f6c9f19fb921/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/ColumnProperty.java#L175)):*
> ```Java
>                  */
>                 long millis = 0;
>                 if (newValue instanceof Date) {
> ```

these changes break things as the imported Date class was java.sql.Date

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10030)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/ColumnProperty.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10030#-KuSmL0EGrp17US7E6R3:-KuSwF8eNp4by6iJQL0X:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/2d63777849c91bba96e52a828439f6c9f19fb921/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/ColumnProperty.java#L175)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

these changes break things as the imported Date class was java.sql.Date
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10030)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10030)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10030#-:-KuSxrKdZh7tCmC3sob4:bnfp4nl)*

**Pull request merged**
