### PR TITLE
Add columns with a presentation value provider

### PR DESCRIPTION
**Pull request by heruan**
This allows decoupling the column *semantic* type from the *presentation* type. For example:

```java
public class Group {
    private String name;
    private Double privilegeLevel;
    /* getters and setters */
}

public class User {
    private String name;
    private Group group;
    /* getters and setters */
}

Grid<User> grid = new Grid<>();
grid.addColumn(User::getName);
grid.addColumn(User::getGroup, Group::getName);
```
the `addColumn(ValueProvider<T, V> valueProvider, ValueProvider<V, P> presentationProvider)` is a new method to add a column which type is `V`, but the type the renderer will encode is `P`. In the example, the last column will be a `Column<User, Group>` but it uses a `TextRenderer` to encode the `Group`'s name.

This avoids the need to have custom renderers for every column whose type is an object, but also can be used with an explicit renderer, for example:

```java
Grid<User> grid = new Grid<>();
grid.addColumn(User::getName);
grid.addColumn(User::getGroup, Group::getPrivilegeLevel, new ProgressBarRenderer());
```

This also permits using editors components like this (see https://github.com/vaadin/framework/issues/8656):

```java
ComboBox<Group> groups = new ComboBox<>();
groups.setItemCaptionGenerator(Group::getName);
groups.setDataProvider(/* groups */);

Grid<User> grid = new Grid<>();
grid.addColumn(User::getName)
        .setEditorComponent(new TextField(), User::setName);
grid.addColumn(User::getGroup, Group::getName)
        .setEditorComponent(groups, User::setGroup);
```

I think this also may be useful when #8625 completes, i.e. having a component as the presentation type:

```java
Grid<User> grid = new Grid<>();
grid.addColumn(User::getName, name -> new CustomLabel(name));
grid.addColumn(User::getGroup, Group::getName);
```

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8806)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8806#-Kf5iI0ozFhLNsAsR2NG:-Kf5iI0ozFhLNsAsR2NH:b-xx6fnu) (no related file):*
I'm slightly sceptical about this approach for a couple of reasons:
* There are already quite many different variants of `addColumn`. Introducing two more would further add to the complexity and confusion.
* Passing two different `ValueProvider` instances to the same method might be confusing.
* Making the second `ValueProvider` accept the return value of the first `ValueProvider` does, from a semantic point of view, mean that it's not a "value provider", but rather a "converter".

One alternative approach that I've been considering is to introduce a "converting renderer" that wraps some existing render but adds a conversion callback "in front of" it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8806)*

**Comment by heruan** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8806#-Kf5iI0ozFhLNsAsR2NG:-Kf60aPcNcT-Lsm0GcCd:b5siug0) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'm slightly sceptical about this approach for a couple of reasons:
* There are already quite many different variants of `addColumn`. Introducing two more would further add to the complexity and confusion.
* Passing two different `ValueProvider` instances to the same method might be confusing.
* Making the second `ValueProvider` accept the return value of the first `ValueProvider` does, from a semantic point of view, mean that it's not a "value provider", but rather a "converter".

One alternative approach that I've been considering is to introduce a "converting renderer" that wraps some existing render but adds a conversion callback "in front of" it.
</blockquote></details>

I understand your concerns, and the "wrapped renderer" was my first approach. Problem is the wrapped renderer fails somewhere causing the grid to display a gray box instead of rows and columns. I guess it's something related to the extension hierarchy of the renderer, I tried to override `setParent` to add the wrapped renderer to the hierarchy but it still doesn't work. Any ideas?

I like the idea of a "value converter", which may be a better "wrapped renderer" and achieve the same usability without touching the grid. I'll keep investigating on the wrapped renderer and commit a new approach to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8806)*

**Comment by heruan** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8806#-Kf5iI0ozFhLNsAsR2NG:-Kf6Hpl4fagw2cJv_zJF:bw0djfw) (no related file):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

I understand your concerns, and the "wrapped renderer" was my first approach. Problem is the wrapped renderer fails somewhere causing the grid to display a gray box instead of rows and columns. I guess it's something related to the extension hierarchy of the renderer, I tried to override `setParent` to add the wrapped renderer to the hierarchy but it still doesn't work. Any ideas?

I like the idea of a "value converter", which may be a better "wrapped renderer" and achieve the same usability without touching the grid. I'll keep investigating on the wrapped renderer and commit a new approach to this PR.
</blockquote></details>

Of course the simple reason why a wrapping renderer won't work is that it lacks its client-side counterpart. This would be a nice generic renderer:

```java
public class ValueConverter<T, V, C> extends AbstractRenderer<T, Object> {

    private ValueProvider<V, C> valueProvider;

    private Renderer<? super C> renderer;

    public ValueConverter(ValueProvider<V, C> valueProvider) {
        this(valueProvider, new TextRenderer());
    }

    public ValueConverter(ValueProvider<V, C> valueProvider, Renderer<? super C> renderer) {
        super(Object.class);
        this.valueProvider = valueProvider;
        this.renderer = renderer;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JsonValue encode(Object value) {
        if (value == null) {
            return this.renderer.encode(null);
        } else {
            return this.renderer.encode(this.valueProvider.apply((V) value));
        }
    }
}
```

… if only it could inherit the wrapped renderer connector and widget.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8806)*

**Comment by heruan** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8806#-Kf5iI0ozFhLNsAsR2NG:-Kf6R-R5lzDhDc4Nzw8k:bw6wsoq) (no related file):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

Of course the simple reason why a wrapping renderer won't work is that it lacks its client-side counterpart. This would be a nice generic renderer:

```java
public class ValueConverter<T, V, C> extends AbstractRenderer<T, Object> {

    private ValueProvider<V, C> valueProvider;

    private Renderer<? super C> renderer;

    public ValueConverter(ValueProvider<V, C> valueProvider) {
        this(valueProvider, new TextRenderer());
    }

    public ValueConverter(ValueProvider<V, C> valueProvider, Renderer<? super C> renderer) {
        super(Object.class);
        this.valueProvider = valueProvider;
        this.renderer = renderer;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JsonValue encode(Object value) {
        if (value == null) {
            return this.renderer.encode(null);
        } else {
            return this.renderer.encode(this.valueProvider.apply((V) value));
        }
    }
}
```

… if only it could inherit the wrapped renderer connector and widget.
</blockquote></details>

I really think the grid should provide a method to add a column with a *provide-convert-render* value presentation chain. Wrapping the conversion phase into a render won't work and won't permit the use of existing renderers.

I've updated to PR trying to address your original concerns with the introduction of a `ValueConverter` functional interface, which will also avoid confusion on choosing the right method overloading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8806)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8806#-Kf5iI0ozFhLNsAsR2NG:-KfAfKJdGsK5Qce_7Lmn:bg1gbgs) (no related file):*
<details><summary><i>Previously, heruan (Giovanni Lovato) wrote…</i></summary><blockquote>

I really think the grid should provide a method to add a column with a *provide-convert-render* value presentation chain. Wrapping the conversion phase into a render won't work and won't permit the use of existing renderers.

I've updated to PR trying to address your original concerns with the introduction of a `ValueConverter` functional interface, which will also avoid confusion on choosing the right method overloading.
</blockquote></details>

A wrapping renderer would either require a client side counterpart or some custom server-side logic that uses the renderer instance in different ways depending on its type. Either alternative would have some slightly ugly aspects.

Defining a separate `ValueConverter` type should definitely help making the different overloads easier to use.

I'll leave final judgement about this PR to the team that actually maintains the Framework. They'll also have to determine how to deal with automatic testing and external documentation for this functionality. Ping @pleku.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8806)*

**Comment by tsuoanttila** [comment]
I was looking at this change in addition to a recent change regarding changing the renderer of a column. The columns should somehow either store the presentation type, so that the renderer can still be changed, or the converter needs to be given again when ever you want to change the renderer. At least that's what it looks like for me. So the question in my head is, what is the actual reason for providing the concept of presentation type and its conversion?

If the reason is mostly the editor component, I'd say we should add an overload of the .setEditorComponent that is typed to edited value type, accepting a HasValue<E>, ValueProvider<E> and a Setter<T, E>. This way we could provide the editor component with custom type without making the concept of the Column any more complex.

How does this sound for you @heruan and @Legioth ?

**Comment by heruan** [comment]
Thank you @tsuoanttila for the feedback. This idea originated from the use of the editor component, but then I thought that having the column typed on the semantic instead of the presentation would be more elegant. Consider this:

```java
Grid<User> grid = new Grid<>();
Column<User, Group> column1 = grid.addColumn(User::getGroup);
Column<User, String> column2 = grid.addColumn(user -> user.getGroup().getName());
```
Here we know that `column1` will render a `Group`, and as you anticipate we can later change how the `Group` will be rendered; in `column2` instead, we restrict the rendering to a string and we can't access other field other than `name`.

That's why I see a missing piece here, i.e. the bridge between the semantic (column) and the presentation (renderer) which in the current implementation are coincident, but in my opinion should be decoupled.

Wouldn't be nice to be able to do this?

```java
Column<User, Group> column1 = grid.addColumn(User::getGroup);
column1.setRenderer(Group::getName, new TextRenderer<>());
// ... later on
Function<Group, Component> generateButton = group ->
    new Button(group.getName(), click -> navigator.navigateTo("groups/" + group.getId());
column1.setRenderer(generateButton, new ComponentRenderer<>());


```

**Comment by Legioth** [comment]
Now when we have `Column.setRenderer` for changing the renderer after the column has been created, it might make sense to provide an additional overload of that method while still not adding yet another overload of `addColumn`.

This approach would allow using the suggested `Function<Group, Component> generateButton` while still avoiding the confusion of an `addColumn` overload that accept multiple lambda parameters.

**Comment by tsuoanttila** [comment]
Ok, I think I get your point on the semantics of the column. It might be more correct to consider the column type of Group rather than String in this case, also makes sorting implementations much nicer with in-memory data. So basically what we do need to provide is the .setRenderer with custom type PRESENTATION that takes the renderer and the converter. This is missing from the patch. Can you rebase it on top of master and implement this missing feature?

**Comment by pinonpierre** [comment]
I have the same issue.

In my project, I need to format my value in html. After that, I have no way to sort the value if I use "addColumn(ValueProvider" because I don't want to sort on html code!

**Comment by hesara** [comment]
Was this superceded by #9553?

**Comment by pinonpierre** [comment]
@Legioth 
It's strange to answer my comment by editing my own comment?

See above "pinonpierre commented on 29 May • edited by Legioth"

**Comment by tsuoanttila** [comment]
Obsolete since #9553 was merged. Thanks @heruan for the idea and most of the code!

**Pull request closed without merging**
