### PR TITLE
Add declarative support to Tree

### LINKED ISSUE #9838: Declarative support is missing in Tree (Vaadin 8.1)
Please support declarative format for new **Tree** component introduced in Vaadin 8.1

### PR DESCRIPTION
**Pull request by ahie**
Closes #9838

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9881)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 944 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgXtmkBgM8Bzjjr10c:-KsgXtmkBgM8Bzjjr10d:b-i6yd69) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L944)):*
> ```Java
>         itemElement.attr("item", serializeDeclarativeRepresentation(item));
> 
>         if (parent != null) {
> ```

Would it make sense to actually store a hierarchy in the design rather than parent links? I guess this is like this for consistency with TreeGrid.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 946 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgX0Xl98ErZ9wvuqZn:-KsgX0Xl98ErZ9wvuqZo:b-kww5c4) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L946)):*
> ```Java
>         if (parent != null) {
>             itemElement.attr("parent",
>                     serializeDeclarativeRepresentation(parent));
> ```

Do we have any guarantees that the serialized representation (toString()) is as unique as the item itself? What problems occur if it isn't? Is this any different from how Grid handles this?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 958 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgXkLk0OIeFUbl-zea:-KsgXkLk0OIeFUbl-zeb:beheyg9) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L958)):*
> ```Java
> 
>         String text = getItemCaptionGenerator().apply(item);
>         itemElement.text(Optional.ofNullable(text).map(Object::toString)
> ```

How does this compare with how other data components serialize their captions?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 985 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgaDChc2bJ66HUrAp3:-KsgaDChc2bJ66HUrAp4:bqj53cx) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L985)):*
> ```Java
> 
>         DeclarativeIconGenerator<T> iconGenerator = new DeclarativeIconGenerator<>(
>                 item -> null);
> ```

icon generator not set for the Tree?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1026 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgabkAZYtlaqBzH72H:-KsgabkAZYtlaqBzH72I:b-gyddc) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L1026)):*
> ```Java
>      * @throws ClassCastException
>      *             if type {@code T} is not a {@link String}
>      * @return deserialized item
> ```

since tag?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgadlNX8BLIQ1lmdEg:-KsgadlNX8BLIQ1lmdEh:b-gyddc) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L1046)):*
> ```Java
>      * @param item
>      *            a data item
>      * @return string representation of the {@code item}.
> ```

since tag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 944 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgXtmkBgM8Bzjjr10c:-Ksgcz4jHiHyVyda_y27:bvkmfct) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L944)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Would it make sense to actually store a hierarchy in the design rather than parent links? I guess this is like this for consistency with TreeGrid.
</blockquote></details>

Consistency with `TreeGrid` and the fact that this enables nodes with html content.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 946 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgX0Xl98ErZ9wvuqZn:-KsgdD4Ldik2ScuPIx55:b-fjt2zr) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L946)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Do we have any guarantees that the serialized representation (toString()) is as unique as the item itself? What problems occur if it isn't? Is this any different from how Grid handles this?
</blockquote></details>

This is the same as `Grid`. Could consider generating a random UUID for all items.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 958 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgXkLk0OIeFUbl-zea:-KsgcRtA089BqISvNiCV:bofkxe4) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L958)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

How does this compare with how other data components serialize their captions?
</blockquote></details>

This is the same for other data components. Although it probably should not use `encodeForTextNode` since that will serialize a `Tree` with html content incorrectly. Also, adding the content mode serialization and deserialization in the next patch.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 985 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgaDChc2bJ66HUrAp3:-Ksgbz2z5ebmKm51wiCa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L985)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

icon generator not set for the Tree?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1026 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgabkAZYtlaqBzH72H:-KsgbxxveZYKFOAETF5m:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L1026)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgadlNX8BLIQ1lmdEg:-KsgbyEXIi09erbv_0QN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/47809b011c47dd938237c9399b5f2f6b7bf00884/server/src/main/java/com/vaadin/ui/Tree.java#L1046)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881)*

**Comment by ahie** [comment]
Tests still WIP.

---

Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881#-:-Ksge7yNPMPMuC0LKEPP:bb41q24)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 927 at r3](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgjDNhIOXl6l4hTk57:-KsgjDNhIOXl6l4hTk58:bqpkb66) ([raw file](https://github.com/vaadin/framework/blob/240961c41dfc626093b757c4e99c5ef9d7b62fe8/server/src/main/java/com/vaadin/ui/Tree.java#L927)):*
> ```Java
>         }
>         DesignAttributeHandler.writeAttribute("content-mode", attrs,
>                 renderer.getState(false).mode, ContentMode.TEXT,
> ```

Why is there no getContentMode()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 927 at r3](https://reviewable.io:443/reviews/vaadin/framework/9881#-KsgjDNhIOXl6l4hTk57:-Ksh1kiy63Dn-QJx4DDf:b32w0x) ([raw file](https://github.com/vaadin/framework/blob/240961c41dfc626093b757c4e99c5ef9d7b62fe8/server/src/main/java/com/vaadin/ui/Tree.java#L927)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should probably be added in a separate patch.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9881)*

**Pull request merged**
