### PR TITLE
Use proper UTF-8 encoding for Content-Disposition filenames

### LINKED ISSUE #7468: StreamResource messes with filenames while downloading
**Originally by _lohmann@zad-northeim.de_**

___
When you use special characters in a filename to download content (e.g. via Filedownloader) it gets messed up in the URL and in the "Save file"-Dialog.

Assuming you have the code
```
Button button = new Button("Click me");
StreamResource resource = new StreamResource(new StreamSource() {
  @Override
  public InputStream getStream() {
    return new ByteArrayInputStream("Just some text".getBytes());
  }
}, "Umlauts like ÄÜÖäüö are dangerous + cool! 100%?.txt");

FileDownloader downloader = new FileDownloader(resource);
downloader.extend(button);
```

### Expected behaviour
The filename to save should be "Umlauts like ÄÜÖäüö are dangerous + cool! 100%?.txt"
or at least as "*" and "?" are dangerous "Umlauts like ÄÜÖäüö are dangerous + cool! 100%_.txt"

### Actual behaviour
The filename is "Umlauts+like+ÄÜÖäüö+are+dangerous+++cool!+100%_.txt" So there are "+" instead of spaces.

### Background
The culprit is DownloadStream.getContentDispositionFilename(String filename) as it uses URLEncoder.encode() which is not applicable here.

According to the API https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html it **MUST NOT** be used for URL encoding. The name is *definitely* misleading here. It is for application/x-www-form-urlencoded but not for URIs, or MIME-field-values.

According to RFC 2231 all special characters in MIME-field-values should be encoded by percent-encoding, even the "+". URLEncoder does not do this. http://tools.ietf.org/html/rfc2231
It is used in the code to set the filename of the Content-Disposition header.

Even in cases of using URLEncoder in URIs is broken, as special characters have to be endoded differently based on their occurence in different URI parts.

Please see https://web.archive.org/web/20151218094722/http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding for a more in depth explanation and background.

### Solution
Remove URLEncoder in the DownloadStream.getContentDispositionFilename(). Some tests verify that the encoding is not necessary at all (yes, it violates the RFCs then), but it works with Chromium, Chrome, Firefox and IE out-of-the-box.
Better is to replace URLEncoder with a working implementation.

___
 Imported from https://dev.vaadin.com/ issue #19527

### PR DESCRIPTION
**Pull request by Legioth**
Fixes #7468

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/6607)

### CODE REVIEW

**Comment by Legioth** [comment]
Original review in https://dev.vaadin.com/review/#/c/13152/

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/6607#-:-KYdVj10oeXBwLcUuXNP:b-qhnw5u)*

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYllr2u1FMe-RJcIbCp:-KYllr2u1FMe-RJcIbCq:b-vuzpn5) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L26)):*
> ```Java
>  * @since
>  */
> public class EncodeUtil {
> ```

Needs to white-list this in `ClassesSerializableTest`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/6607)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYlxkPSXRAonGurqNXX:-KYlxkPSXRAonGurqNXY:b-5tee21) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L27)):*
> ```Java
>  */
> public class EncodeUtil {
>     private static final Charset utf8 = Charset.forName("UTF-8");
> ```

Remove please.

`StandardCharsets.UTF_8`

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYlyN2O8awiVAn7aWqW:-KYlyN2O8awiVAn7aWqX:b-mjh1nt) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L53)):*
> ```Java
> 
>                 byte[] utf8Bytes = cpAsString.getBytes(utf8);
>                 for (byte b : utf8Bytes) {
> ```

`for` inside `if-else` inside `for`.
Please extract to separate method.

And please don't use one-letter variable name (`b`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/6607)*

**Comment by Legioth** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYllr2u1FMe-RJcIbCp:-KYo6H9amj3xn-9nK8WT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L26)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Needs to white-list this in `ClassesSerializableTest`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYlxkPSXRAonGurqNXX:-KYo6IrU28dniHl1qZRo:b6fafrf) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Remove please.

`StandardCharsets.UTF_8`
</blockquote></details>

This patch is for 7.7 that uses Java 6

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYlyN2O8awiVAn7aWqW:-KYo7l3vbIjtNWLVbZs-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`for` inside `if-else` inside `for`.
Please extract to separate method.

And please don't use one-letter variable name (`b`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/6607)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/util/EncodeUtil.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/6607#-KYlxkPSXRAonGurqNXX:-KYr3LzQzBaunHd7vftM:bvrzghc) ([raw file](https://github.com/vaadin/framework/blob/ca1e3d5ee379412d1926178522c7a9bda143d3f2/server/src/main/java/com/vaadin/util/EncodeUtil.java#L27)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This patch is for 7.7 that uses Java 6
</blockquote></details>

I must have been blind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/6607)*

**Pull request merged**
