### PR TITLE
Fix toggling of WeekNumbers for DateTimeField. (#8405)

### PR DESCRIPTION
**Pull request by caalador**
Fix togging of week numbers in calendar popup.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8468)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 631 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMXTgD2SnKSHZT2WHz:-KcMXTgD2SnKSHZT2WI-:b-o94ava) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L631)):*
> ```Java
>     }
> 
>     public void setShowISOWeekNumbers(boolean showISOWeekNumbers) {
> ```

Will this be called when there is no effective change, or only when the value really changes?  If there are redundant calls, could reduce re-renders to only happen when the value changes.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java, line 536 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMXfoEj_Q97QNyMEM4:-KcMXfoEj_Q97QNyMEM5:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java#L536)):*
> ```Java
>     public void setShowISOWeekNumbers(boolean showISOWeekNumbers) {
>         this.showISOWeekNumbers = showISOWeekNumbers;
>         if(initialRenderDone) {
> ```

see above

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMXM2KW--XhRIXClYs:-KcMXM2KW--XhRIXClYt:b-1m9ux7) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java#L108)):*
> ```Java
>         popupButton.click();
>     }
> }
> ```

missing newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8468)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMYMJFgBlljVx6T1Ay:-KcMYMJFgBlljVx6T1Az:bs0c14q) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java#L39)):*
> ```Java
> 
>     @Test
>     public void testToggleWeekNumbers_rederedCorrectly() {
> ```

rendered

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8468)*

**Comment by caalador** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMYMJFgBlljVx6T1Ay:-KcMkAypexjYtWO8CD7C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

rendered
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8468#-KcMXM2KW--XhRIXClYs:-KcMkBGGyljx6EgALy27:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/230f7e2d6ab19821760f254926a8023070086a03/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldWeekDaysTest.java#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

missing newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8468)*

**Comment by hesara** [comment]
OK if validation build passes

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8468#-:-KcMkSzTyynAK80BkVRt:bxtbdlg)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8468#-:-KcNl45VLe_Q1ZKeADwH:bnfp4nl)*

**Pull request merged**
