### PR TITLE
Add update checker

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8654)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_ryipkGU0qoQUdUV3:-Kd_ryipkGU0qoQUdUV4:brlqfwr) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L36)):*
> ```Java
>     public static final String ANONYMOUS_ID = loadFirstLaunch();
> 
>     // TODO what should this say?
> ```

Would leave as is to be compatible with old checks

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_ruQOTz3oqq3I7Lnp:-Kd_ruQOTz3oqq3I7Lnq:b-wstay2) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L93)):*
> ```Java
>             }
>         }
> ```

Update LAST_PING?

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_sQjrTORSpHxavbtC:-Kd_sQjsfuVkKLEZtiKb:b-ve8o1n) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L113)):*
> ```Java
>         Throwable caught;
>         InputStream is = null;
>         try {
> ```

Could use commons-io to simplify this a lot?

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_sUxcTk6gsN_zwTk0:-Kd_sUxcTk6gsN_zwTk1:bpp6stj) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L144)):*
> ```Java
>                         + caught.getMessage());
> 
>         return;
> ```

not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8654)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8654)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_ryipkGU0qoQUdUV3:-KddqNCzJ5apB4m2shEA:b23n0io) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L36)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Would leave as is to be compatible with old checks
</blockquote></details>

Changing comment accordingly

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_ruQOTz3oqq3I7Lnp:-KddqZxcEiN3f0tBuljG:bwa6ff4) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L93)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Update LAST_PING?
</blockquote></details>

Adding update of last ping to the end of the method

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_sQjrTORSpHxavbtC:-KddrrfLR-RWJxC7VT8H:bj4nyc6) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L113)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Could use commons-io to simplify this a lot?
</blockquote></details>

Simplified somewhat with IOUtils

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8654)*

**Comment by hesara** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/8654#-Kd_sUxcTk6gsN_zwTk0:-Kddsg4UOigp8fZlRQgB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/87f339fa15fcc86c1cbd254dbf6f0f3dc53d9cbc/client-compiler/src/main/java/com/vaadin/tools/ReportUsage.java#L144)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8654)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8654)*

**Pull request merged**
