### PR TITLE
Call "destroy" instead of "destory" in JavaScriptRenders

### LINKED ISSUE #8162: AbstractJavaScriptRenderer: typo in destory
Vaadin 7.7.6: there is a typo in AbstractJavaScriptRenderer's javadoc which states that the Connector must have the `destory` method. The typo is however present in the client-side code as well, as Vaadin really expects the JavaScript Connector to have the `destory` method - if it's not present, browser will show the following error:

```
Mon Jan 09 06:21:50 GMT+200 2017 com.vaadin.client.widgets.Grid
SEVERE: Error destroying cell in column 0com.google.gwt.core.client.JavaScriptException: (TypeError) : a.destory is not a function
	at Unknown.pXb(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.xXb(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.gxd(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.Lqd(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.bsd(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.Rqd(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.Mwd(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.pYb(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.FYb(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.t9b(com.vaadin.DefaultWidgetSet-0.js)
```

### PR DESCRIPTION
**Pull request by Artur-**
For backwards compatibility, calls "destory" if no "destroy" exists

Fixes #8162

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8263)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Will trigger a full test build.

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8263#-:-KaqvxGgR-CCP6xSI_wA:bhjdnil)*

**Comment by Artur-** [comment]
What were the results of the full test build?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8263#-:-KbFh2dK5lR4tYIHQQhV:b-l0kv6j)*

**Comment by hesara** [comment]
Needs a rebase and possibly test build

**Comment by Artur-** [comment]
Rebase done, review done. Anything else needed?

**Pull request merged**
