### PR TITLE
Fix valdiation builds to use correct browser

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch introduces the changes to pom files forgotten
in the previous commit.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

---

*[pom.xml, line 539 at r1](https://reviewable.io/reviews/vaadin/framework/11000#-LFvF_ACBh-FXS5CkUlD:-LFvF_ACBh-FXS5CkUlE:b-ka47qd) ([raw file](https://github.com/vaadin/framework/blob/2cee16d75d077493f543859189528e663b3cfa4e/pom.xml#L539)):*
> ```XML
>                                     <pluginExecutionFilter>
>                                         <groupId>
>                                             net.revelc.code.formatter
> ```

aren't those settings inherited from parent?

---

*[uitest/pom.xml, line 35 at r1](https://reviewable.io/reviews/vaadin/framework/11000#-LFvEeBL4qGQ1Roqs2i1:-LFvEeBL4qGQ1Roqs2i2:b-4tlb1) ([raw file](https://github.com/vaadin/framework/blob/dee4a2caa80066bcdd031ec445c8bf80ba313ab9/uitest/pom.xml#L35)):*
> ```XML
>     <prerequisites>
>         
>         <maven>3.1</maven>
> ```

We need even higher maven version. let's advance it and, possibly, move to the parent
Might be done in a separate PR, not a blocker

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

---

*[pom.xml, line 539 at r1](https://reviewable.io/reviews/vaadin/framework/11000#-LFvF_ACBh-FXS5CkUlD:-LFvFzzP667ODY_t2YQR:b-85hr60) ([raw file](https://github.com/vaadin/framework/blob/2cee16d75d077493f543859189528e663b3cfa4e/pom.xml#L539)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

aren't those settings inherited from parent?
</blockquote></details>

this is the `vaadin-root` pom.xml. These formatters are not configured in the `vaadin-parent`. 

---

*[uitest/pom.xml, line 35 at r1](https://reviewable.io/reviews/vaadin/framework/11000#-LFvEeBL4qGQ1Roqs2i1:-LFvGHUSARhnRQs8qDv9:bkleda2) ([raw file](https://github.com/vaadin/framework/blob/dee4a2caa80066bcdd031ec445c8bf80ba313ab9/uitest/pom.xml#L35)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

We need even higher maven version. let's advance it and, possibly, move to the parent
Might be done in a separate PR, not a blocker
</blockquote></details>

Should be in the `vaadin-root` pom and not in this yes. Can add it there, need to check what is the limit.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by elmot** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[uitest/pom.xml, line 35 at r1](https://reviewable.io/reviews/vaadin/framework/11000#-LFvEeBL4qGQ1Roqs2i1:-LFvMw1z1UgE-hK03prn:b-iv68we) ([raw file](https://github.com/vaadin/framework/blob/dee4a2caa80066bcdd031ec445c8bf80ba313ab9/uitest/pom.xml#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should be in the `vaadin-root` pom and not in this yes. Can add it there, need to check what is the limit.
</blockquote></details>

3.3 I think. Or we can just set latest used for CI - 3.5.3. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[uitest/src/test/java/com/vaadin/tests/components/popupview/PopUpViewInTabsheetTest.java, line 21 at r2](https://reviewable.io/reviews/vaadin/framework/11000#-LFvjSLxAyjlNBQ6_5IZ:-LFvjSLxAyjlNBQ6_5I_:b81i2um) ([raw file](https://github.com/vaadin/framework/blob/82b899ac7257ac5a9cf86b4f6fbbf38a4040dde7/uitest/src/test/java/com/vaadin/tests/components/popupview/PopUpViewInTabsheetTest.java#L21)):*
> ```Java
> 
>     @Test
>     @Ignore("Fix was based on TabSheet reattach hack, test broken by #10988")
> ```

And what do we do with the test?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by tsuoanttila** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/popupview/PopUpViewInTabsheetTest.java, line 21 at r2](https://reviewable.io/reviews/vaadin/framework/11000#-LFvjSLxAyjlNBQ6_5IZ:-LFvkeWK4H9hwezN3Lfv:b8g99m1) ([raw file](https://github.com/vaadin/framework/blob/82b899ac7257ac5a9cf86b4f6fbbf38a4040dde7/uitest/src/test/java/com/vaadin/tests/components/popupview/PopUpViewInTabsheetTest.java#L21)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

And what do we do with the test?
</blockquote></details>

@anasmi is looking for the origin of the ticket, should be fixed as this is a regression of sorts (I think)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r3, 10 of 10 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/11000)*

**Pull request merged**
