### PR TITLE
Fix problem with re-opening the popup (#8446)

### PR DESCRIPTION
**Pull request by caalador**
Fixed problem that disables opening of popup
after closing it by clicking the datefield-button.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8451)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldPopupTest.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHwWp2cNzyRheFiZe9:-KcHwWp2cNzyRheFiZeA:b-y5gasu) ([raw file](https://github.com/vaadin/framework/blob/00ed246210ca4345ba1d1ddd530aaebec5d160dc/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldPopupTest.java#L58)):*
> ```Java
> 
>     private void assertThatPopupIsInvisible() {
>         // ExpectedConditions.invisibilityOfElementLocated doesn't work
> ```

(I wonder whether it would make sense to generalize this in AbstractTB3Test, although wait for not displayed is not the most common one)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHyoBZvAshXFHh4UgC:-KcHyoBZvAshXFHh4UgD:bsmyy5g) (no related file):*
The FW8 code is a migration of the V7 code.
Does V7 have the same issue ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHyoBZvAshXFHh4UgC:-KcHzgnVDtQjnbK6xTXe:b-wsixg8) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The FW8 code is a migration of the V7 code.
Does V7 have the same issue ? 
</blockquote></details>

I'll try to test the issue on V7 also.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldPopupTest.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHwWp2cNzyRheFiZe9:-KcI-EYSA_9SBHvPOT8h:b4okclk) ([raw file](https://github.com/vaadin/framework/blob/00ed246210ca4345ba1d1ddd530aaebec5d160dc/uitest/src/test/java/com/vaadin/tests/components/datefield/DateTimeFieldPopupTest.java#L58)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I wonder whether it would make sense to generalize this in AbstractTB3Test, although wait for not displayed is not the most common one)
</blockquote></details>

This is used in DateFieldPopupClosingTest and this test so the need to have it available for all usage may not be the greatest. No other popup test seems to use the same style of waiter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHyoBZvAshXFHh4UgC:-KcI11A-sm47hcWFQUXv:b6yonq9) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I'll try to test the issue on V7 also.
</blockquote></details>

The same problem happens in V7 PopupDateField also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHyoBZvAshXFHh4UgC:-KcI1vdJMs32i4JkX1zt:bdsrniz) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The same problem happens in V7 PopupDateField also.
</blockquote></details>

Then 
- this should be migrated into 7.7 branch
- compatibility DateField should be updated in the master as well.

Please either create a new issue against V7 or just make one more PR for 7.7
(and this one should be also updated for compatibility).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8451#-KcHyoBZvAshXFHh4UgC:-KcIH5U9lHDbt56CRkuD:bb7f2mf) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Then 
- this should be migrated into 7.7 branch
- compatibility DateField should be updated in the master as well.

Please either create a new issue against V7 or just make one more PR for 7.7
(and this one should be also updated for compatibility).
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8451)*

**Pull request merged**
