### PR TITLE
Replaced Grid's internal size calculation fix with an indexing fix.

### LINKED ISSUE #11044: Grid and TreeGrid render rows on top of each other while being resized
Seems to be an older issue, but is still happening with Vaadin 8.4.5:

When you first scroll to the bottom of a grid and then resize it by dragging, something breaks with the indexing and it renders two rows on top of each other. It's easiest to reproduce by putting a Grid inside a VerticalSplitPanel, but seems to be happening just as well by resizing the whole browser window with a single Grid instance in it. The exact same thing happens also with a TreeGrid when it's been expanded and scrolled to the bottom.

Steps to reproduce with the MyUI example UI below:
1. Scroll the upper grid to the bottom so that you can see the 100th row
2. Drag the split bar up so that the last item visible is number 94
3. Slowly drag the split bar down, and see that the row below 94 is now 96. With any luck you can actually see the row 96 being put on top of row 95.

Scrolling up and then back down fixes the situation.

The expected behaviour is for Grid to keep the rows properly rendered even while resizing.

Here's the sample UI, should be a straight drop in for a single module Vaadin archetype project, and below it a screenshot showing the issue in effect:
```
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        layout.setSizeFull();
        setContent(layout);

        Grid<TestBean> grid1 = buildGrid();
        Grid<TestBean> grid2 = buildGrid();
        
        VerticalSplitPanel split = new VerticalSplitPanel(grid1, grid2);
        split.setSizeFull();
        
        layout.addComponent(split);
        layout.setExpandRatio(split, 1);
    }

    private Grid<TestBean> buildGrid() {
        Grid<TestBean> grid = new Grid<>(TestBean.class);
        grid.setSizeFull();
        grid.getColumn("value").setHidable(true).setHidden(true);
        TestBean folder = new TestBean(true);
        List<TestBean> list = new ArrayList<>();
        for (int i = 1; i <= 100; i++) {
        	list.add(new TestBean(false, i + " new item " + (i * 42)));
        }
        grid.setItems(list);
        return grid;
    }
    
    public class TestBean {
        private String name = "name";
        private String value = "value";
        private boolean folder = false;

        public TestBean(boolean inFolder) {
            folder = inFolder;
        }

        public TestBean(boolean inFolder, String inName) {
            folder = inFolder;
            name = inName;
        }

        public String getName() {
            return name;
        }

        public void setName(String inName) {
            name = inName;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String inValue) {
            value = inValue;
        }

        public void setFolder(boolean inFolder) {
            folder = inFolder;
        }

        public boolean isFolder() {
            return folder;
        }
        
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

screen shot 2018-07-12 at 11 24 06

### PR DESCRIPTION
**Pull request by Ansku**
- More lightweight, and fixes things for any custom implementations of
Escalator as well.

Fixes #11044

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11154)

### CODE REVIEW

**Comment by pleku** [comment]
This has been already marked as fixed in 8.5.1 with #11046, so this is apparently supposed to be the better fix for it.

**Comment by TatuLund** [comment]
> so this is apparently supposed to be the better fix for it

Yes, exactly. This patches the actual problem in Escallator.

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11154)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridScrolledToBottomTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11154#-LLU4GSY-YlhQKh5kSz_:-LLU4GSY-YlhQKh5kSza:bfguig1) ([raw file](https://github.com/vaadin/framework/blob/08a978a22c5f310cb48c8ef0f1c2f694683664ca/uitest/src/test/java/com/vaadin/tests/components/grid/GridScrolledToBottomTest.java#L21)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> public class GridScrolledToBottomTest extends MultiBrowserTest {
> ```

Need to manually test and verify that the test actually does reproduce the issue consistently.

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11154)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridScrolledToBottomTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11154#-LLU4GSY-YlhQKh5kSz_:-LNikNdH5h6MEL5haMJQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/08a978a22c5f310cb48c8ef0f1c2f694683664ca/uitest/src/test/java/com/vaadin/tests/components/grid/GridScrolledToBottomTest.java#L21)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Need to manually test and verify that the test actually does reproduce the issue consistently.
</blockquote></details>

Done.

**Review by Ansku — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11154#-:-LNilMI5-0jNgzuOl01v:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by Ansku — COMMENTED** [review]
> Dismissed @tsuoanttila from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11154)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @tsuoanttila)

**Review by Ansku — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11154)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
