### PR TITLE
Prevent killing UI if heartbeats are pending

### LINKED ISSUE #9663: Heartbeats blocked during long run request
Used Vaadin Version: 7.7.10

We had several bugs because Vaadin UI and Session have been removed, because of not received Heartbeats. In fact, the Heartbeats have been send, but during processing a long running request Hearbeats are not processed until the long running request has finished.

1.	Start long running request
2.	Hearbeats will be send, but not received/processed
3.	End of long running request
4.	Kill of UI by Vaadin
5.	Hearbeats are processed (but it’s to late, because UI and Session have been invalidated.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9663

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10371)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1369 at r1](https://reviewable.io:443/reviews/vaadin/framework/10371#-KzhELYTIbj5wBY2XyXw:-KzhELYTIbj5wBY2XyXx:blbuxib) ([raw file](https://github.com/vaadin/framework/blob/c6fbcc761742e8bd6f8a226c78e44a4878f8f9b9/server/src/main/java/com/vaadin/server/VaadinService.java#L1369)):*
> ```Java
> 
>         // Check for long running tasks
>         if (ui.getSession().hasLock()) {
> ```

I don't think this should ever be called without holding the lock, so you can instead just assert that the lock is held.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1369 at r1](https://reviewable.io:443/reviews/vaadin/framework/10371#-KzhELYTIbj5wBY2XyXw:-KzhGp6mv62XQIv6QOPK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c6fbcc761742e8bd6f8a226c78e44a4878f8f9b9/server/src/main/java/com/vaadin/server/VaadinService.java#L1369)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I don't think this should ever be called without holding the lock, so you can instead just assert that the lock is held.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1373 at r1](https://reviewable.io:443/reviews/vaadin/framework/10371#-KzhFs21DhKNGZvwYeRk:-KzhFs21DhKNGZvwYeRl:b6hby61) ([raw file](https://github.com/vaadin/framework/blob/c6fbcc761742e8bd6f8a226c78e44a4878f8f9b9/server/src/main/java/com/vaadin/server/VaadinService.java#L1373)):*
> ```Java
>             if (lockInstance instanceof ReentrantLock) {
>                 if (((ReentrantLock) lockInstance).hasQueuedThreads()) {
>                     // UI has queued threads.
> ```

It's obvious that the UI has queued threads, the method call above checks for them. 

This could rather say something like "If somebody else is trying to access session, we will leave all UIs alive and defer a possible kill decision until the other session access has ended (and this method is called again)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1373 at r1](https://reviewable.io:443/reviews/vaadin/framework/10371#-KzhFs21DhKNGZvwYeRk:-KzhHY0RFR3eIhan4mEo:b-6k7805) ([raw file](https://github.com/vaadin/framework/blob/c6fbcc761742e8bd6f8a226c78e44a4878f8f9b9/server/src/main/java/com/vaadin/server/VaadinService.java#L1373)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's obvious that the UI has queued threads, the method call above checks for them. 

This could rather say something like "If somebody else is trying to access session, we will leave all UIs alive and defer a possible kill decision until the other session access has ended (and this method is called again)"
</blockquote></details>

and actually it's the session which has queued threads, not the UI :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1373 at r1](https://reviewable.io:443/reviews/vaadin/framework/10371#-KzhFs21DhKNGZvwYeRk:-KzhO-8EO5sHAA_1tf-g:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/c6fbcc761742e8bd6f8a226c78e44a4878f8f9b9/server/src/main/java/com/vaadin/server/VaadinService.java#L1373)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

and actually it's the session which has queued threads, not the UI :)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Comment by torok-peter** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10371)*

**Pull request merged**
