### PR TITLE
Updated release notes for 8.0

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8601)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[all/src/main/templates/release-notes.html, line 391 at r1](https://reviewable.io:443/reviews/vaadin/framework/8601#-KdBA4y3oAipQnulCgU9:-KdBA4y46s52WIZg_0TV:b4kd492) ([raw file](https://github.com/vaadin/framework/blob/43249797f354e6f66a57e1bb5d910c57c53f8c24/all/src/main/templates/release-notes.html#L391)):*
> filees

files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8601)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/framework/8601#-KdBA58OsRIWhJfHMMt3:-KdBA58PbWWmmVr6dIuj:b-t344m6) ([raw file](https://github.com/vaadin/framework/blob/43249797f354e6f66a57e1bb5d910c57c53f8c24/all/src/main/templates/release-notes.html#L377)):*
> ```HTML
>             <tt>com.vaadin.v7.Vaadin7WidgetSet</tt> which can be used instead of
>             <tt>DefaultWidgetSet</tt>. Note that the widgetset compilation for
>             <tt>Vaadin7WidgetSet</tt> compilation may requires at least 1G of memory.
> ```

may requires; are there still instructions for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8601)*

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 377 at r1](https://reviewable.io:443/reviews/vaadin/framework/8601#-KdBA58OsRIWhJfHMMt3:-KdBCbVAFfqUhneCgfvO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43249797f354e6f66a57e1bb5d910c57c53f8c24/all/src/main/templates/release-notes.html#L377)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

may requires; are there still instructions for this?
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 391 at r1](https://reviewable.io:443/reviews/vaadin/framework/8601#-KdBA4y3oAipQnulCgU9:-KdBChv6NMUJc5vERYE8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43249797f354e6f66a57e1bb5d910c57c53f8c24/all/src/main/templates/release-notes.html#L391)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> filees

files
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8601)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8601#-:-KdBD10bg5ELr7rA13hn:bnfp4nl)*

**Pull request merged**
