### PR TITLE
Fix removal of hidden Grid columns

### LINKED ISSUE #8018: Removing a hidden column throws a client side exception
Hello I want to describe an issue with the grid that occur when updating the content of container underneath it. Therefor you can find an example Vaadin application attached.

Steps to reproduce:

1. Start Application and uses "Update Grid" button to fill data into grid.
2. Show and Hide columns multiple times. => Work fine.
3. Now update content of grid again by pressing  "Update Grid" button
4. Then some columns are empty now, which is not expected, because container has data for it. This might be an issue.
Note: As an workaround you can hide and show the grid again and then all columns are filled again.

It seems like that for reproducing this issue the prerequisite is that there has to be at least one column which is always hidden. 

You can reproduce this issue with Vaadin version 7.7.5 & 7.7.6.

[GridWithDynamicHidableColumnsUI.zip](https://github.com/vaadin/framework/files/656847/GridWithDynamicHidableColumnsUI.zip)

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8018

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8071)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6471 at r1](https://reviewable.io:443/reviews/vaadin/framework/8071#-KZ_OPvUgCoKK_CikXo4:-KZ_OPvUgCoKK_CikXo5:bn57raz) ([raw file](https://github.com/vaadin/framework/blob/c48c2061050d308eaa69698d6cd6790ee9cedaaf/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6471)):*
> ```Java
>             // Hidden columns are not included in Escalator
>         } else {
>             escalator.getColumnConfiguration().removeColumns(visibleColumnIndex,
> ```

`getEscalator()` please since there is such method and it's overridable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8071)*

**Comment by ahie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6471 at r1](https://reviewable.io:443/reviews/vaadin/framework/8071#-KZ_OPvUgCoKK_CikXo4:-KZaOFDNEhEyQub4hlNd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c48c2061050d308eaa69698d6cd6790ee9cedaaf/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6471)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`getEscalator()` please since there is such method and it's overridable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8071)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8071)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8071)*

**Pull request merged**
