### PR TITLE
Fixing an NPE in MPR

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
In MPR, there are cases when before the initialization of the `UI`, we need to access `Page.location` indirectly and since it is not initialized we get an NPE. To resolve it, the `location` is set to an empty string as its default value in the ctor of `Page`.

Related to https://github.com/vaadin/multiplatform-runtime/issues/26

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11330)

### CODE REVIEW

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11330)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11330#-LRvfPZ43QdfVQjX1ZO3:-LRvfPZ50nb-X_wHr4p1:bt5xr56) (no related file):*
I started a separate Integration and Servers test for this PR https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFramework_PullRequests_TestIntegrationAndServers&branch_VaadinFramework_PullRequests=pull%2F11330&tab=buildTypeStatusDiv

we can merge it after all tests are passed

---

**Comment by TatuLund** [comment]
I assume the same fix is needed for Vaadin 7 as well?

**Comment by ZheSun88** [comment]
That is behavior change for FW.. a discussion is going on

**Comment by mehdi-vaadin** [comment]
To avoid any side effect in the framework, we used another approach inside MPR. So, this PR is closed.

**Pull request closed without merging**
