### PR TITLE
Clicking on DateField pop-up should select Month/Year

### LINKED ISSUE #8447: DateField with Resolution.MONTH: Selection of current month not possible
...or at least its not easy/intuitive.

To reproduce:
-https://demo.vaadin.com/sampler/#ui/data-input/dates/popup-date-field
-delete value/set to null
-select Resolution MONTH
-try to select the current month;) You can only enter it by hand or go back and forth with the arrows. Or is there another possibility?

Imo, it would be obvious/intuitive to also select a month by clicking on the blue month label, not only by navigating with the arrows.

Vaadin version 7.7.6

### PR DESCRIPTION
**Pull request by anasmi**
In Year/Month Resolution DateField should select the value, when user clicks on pop-up

Fixes #8447

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)

### CODE REVIEW

**Comment by anasmi** [comment]
@pleku Could you take a look into this? This is a behavior change fix

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: all files reviewed, 2 unresolved discussions (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 595 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1I98FDNp9i_L32dAV:-Lc1I98FDNp9i_L32dAW:b-ccimvs) ([raw file](https://github.com/vaadin/framework/blob/f1449cb6b259cd8a71062b10834263356ff55c96/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L595)):*
> ```
> Event.sinkEvents(monthYearElement, Event.ONCLICK);
> ```

There should probably also be some visual indication to the user that the month label is actually clickable, you know, basic UX.
I would go for now just to adding the style `cursor: pointer` 
___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 600 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1I2l59RxSLXiiKEuN:-Lc1I2l6D3kepbdrcwRg:bpoih13) ([raw file](https://github.com/vaadin/framework/blob/f1449cb6b259cd8a71062b10834263356ff55c96/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L600)):*
> ```
> selectFocused();
> ```
What does this mean if the resolution is not month ? Should I be able to still select something by clicking the month when the resolution is something else ?
(please answer in code and not here)

I see now from the test that it should also work for clicking the year, but my main concern is the resolutions that are more granular than month (day ..)

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: all files reviewed, 2 unresolved discussions (waiting on @anasmi)

___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 52 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1JgPP0_95auCydru9:-Lc1JgPP0_95auCydruA:b-cwpm76) ([raw file](https://github.com/vaadin/framework/blob/f1449cb6b259cd8a71062b10834263356ff55c96/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L52)):*
> ```
>         String dateValue = new StringBuilder().append(now.getMonth().getValue())
>                 .append("/").append(now.getYear()).toString();
> ```
Are you sure this test is not now independent on the system locale ? I'm guessing so with format `M/yyyy` but just wanted to make sure (non-blocking)

**Review by anasmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 595 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1I98FDNp9i_L32dAV:-LcAXlIUCpwd5RNkF_yL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/49cda970300e15739138398d79411f078c50065b/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L595)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> Event.sinkEvents(monthYearElement, Event.ONCLICK);
> ```

There should probably also be some visual indication to the user that the month label is actually clickable, you know, basic UX.
I would go for now just to adding the style `cursor: pointer` 
</blockquote></details>

Done.
___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 600 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1I2l59RxSLXiiKEuN:-LcAXnB54QtK4X40pimP:boi4grt) ([raw file](https://github.com/vaadin/framework/blob/49cda970300e15739138398d79411f078c50065b/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L600)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> selectFocused();
> ```
What does this mean if the resolution is not month ? Should I be able to still select something by clicking the month when the resolution is something else ?
(please answer in code and not here)

I see now from the test that it should also work for clicking the year, but my main concern is the resolutions that are more granular than month (day ..)
</blockquote></details>

It was my fault not thinking about it. Added check to handle clicks, only if resolution is less than month.
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 52 at r2](https://reviewable.io/reviews/vaadin/framework/11531#-Lc1JgPP0_95auCydru9:-LcAXxrlBWq87Wbog68k:bijx474) ([raw file](https://github.com/vaadin/framework/blob/49cda970300e15739138398d79411f078c50065b/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L52)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         String dateValue = new StringBuilder().append(now.getMonth().getValue())
>                 .append("/").append(now.getYear()).toString();
> ```
Are you sure this test is not now independent on the system locale ? I'm guessing so with format `M/yyyy` but just wanted to make sure (non-blocking)
</blockquote></details>

Added Zone. It should address the problem (I think it still could be the problem)

**Comment by anasmi** [comment]
@pleku , could you take a look?

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: all files reviewed, 3 unresolved discussions (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 586 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdoEBw-5y3s0J7Q3fv:-LhdoEBw-5y3s0J7Q3fw:b1t5b1i) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L586)):*
> ```
>  e -> {
> ```
No. One. Letter. Variables.
`event -> {`
___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 608 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdnJuSAntTd1ltke99:-LhdnJuSAntTd1ltke9A:b7p4jly) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L608)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         if (!isBelowMonth(getResolution())) {
>             monthYearElement.getStyle().setCursor(Style.Cursor.POINTER);
>         } else {
>             monthYearElement.getStyle().setCursor(Style.Cursor.DEFAULT);
>         }
> ```
</details>

If it is done like this, it cannot be overridden in css (easily).

This should go to the base theme for the component (that all other themes are based on).
So when there is month resolution, there should be some class names or something in DOM that allows you to trigger the `custor: pointer` for month year element.
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 64 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdobKr-Rsh-nrQVw0Z:-LhdobKr-Rsh-nrQVw0_:bsdygwu) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L64)):*
> ```
> sleep(100);
> ```
These sleeps show that the _wait for Vaadin_  feature is not working correctly for the widget... 
These should not be needed and instead the widget should report its status correctly implenting the `CanWaitForVaadin` ... 

Not complying might cause there to be lots broken tests for _slower browsers_

**Comment by anasmi** [comment]
___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 608 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdnJuSAntTd1ltke99:-LhiTdRc1BZ-nvV92PZ-:byi8g39) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L608)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>         if (!isBelowMonth(getResolution())) {
>             monthYearElement.getStyle().setCursor(Style.Cursor.POINTER);
>         } else {
>             monthYearElement.getStyle().setCursor(Style.Cursor.DEFAULT);
>         }
> ```
If it is done like this, it cannot be overridden in css (easily).

This should go to the base theme for the component (that all other themes are based on).
So when there is month resolution, there should be some class names or something in DOM that allows you to trigger the `custor: pointer` for month year element.
</blockquote></details>

Switched to CSS. Any better suggestions on naming?

**Comment by anasmi** [comment]
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 64 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdobKr-Rsh-nrQVw0Z:-LhiTkNnB4rRza3ObZjq:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L64)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> sleep(100);
> ```
These sleeps show that the _wait for Vaadin_  feature is not working correctly for the widget... 
These should not be needed and instead the widget should report its status correctly implenting the `CanWaitForVaadin` ... 

Not complying might cause there to be lots broken tests for _slower browsers_
</blockquote></details>

Done

**Review by anasmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 586 at r3](https://reviewable.io/reviews/vaadin/framework/11531#-LhdoEBw-5y3s0J7Q3fv:-LhiTxisDJKqVOnzFs_R:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/460b330580a9786e2a54db16413ca3fc46273839/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L586)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
>  e -> {
> ```
No. One. Letter. Variables.
`event -> {`
</blockquote></details>

Done.

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: all files reviewed, 2 unresolved discussions (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 606 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho0nA6D370As7UJYvc:-Lho0nA77aI8U8eGcJxN:b-4cxg6k) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L606)):*
> ```
> monthYearElement.addClassName("header-below-month");
> ```
Should this class name be removed at some point too ???

Now it just keeps adding it. If the element is regenerated all the time (i'm too lazy to search for that tidbit), then might make sense to add a comment in code
___
*[themes/src/main/themes/VAADIN/themes/valo/components/_datefield.scss, line 483 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho1Tdk53PEC0tv1Xqn:-Lho1Tdl0dA5iDpM5LAm:bxus719) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/themes/src/main/themes/VAADIN/themes/valo/components/_datefield.scss#L483)):*
> ```
> header-below-month
> ```
I don't understand this naming at all, it feels like the name is about "the location of the element", when it should describe more "what state is the element in to get this class name".

Isn't the feature only for month resolution, so it should be "resolution-month" ???
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 31 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho14r4CaErRvcjft59:-Lho14r4CaErRvcjft5A:b3zypw6) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L31)):*
> ```
> waitForElementNotPresent
> ```
This is not what I meant with the `waitForVaadin` feature, but never mind... probably good enough for now

**Review by anasmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @pleku)

___
*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 606 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho0nA6D370As7UJYvc:-LhoOhpo3eDlOdFl1o-I:br0g9h3) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L606)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> monthYearElement.addClassName("header-below-month");
> ```
Should this class name be removed at some point too ???

Now it just keeps adding it. If the element is regenerated all the time (i'm too lazy to search for that tidbit), then might make sense to add a comment in code
</blockquote></details>

Header is regenerated every time its opened. I will add the comment there, but it's not written by me this way. 
___
*[themes/src/main/themes/VAADIN/themes/valo/components/_datefield.scss, line 483 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho1Tdk53PEC0tv1Xqn:-LhoOtkC13i5DyXLHOeZ:b-29rzcm) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/themes/src/main/themes/VAADIN/themes/valo/components/_datefield.scss#L483)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> header-below-month
> ```
I don't understand this naming at all, it feels like the name is about "the location of the element", when it should describe more "what state is the element in to get this class name".

Isn't the feature only for month resolution, so it should be "resolution-month" ???
</blockquote></details>

it's for every resolution below the month: both month and year. But ,indeed, naming is inconsistent after previous change. renamed to `header-month-year`
___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java, line 31 at r4](https://reviewable.io/reviews/vaadin/framework/11531#-Lho14r4CaErRvcjft59:-LhoR4xWBLqrSs28YxEO:bh7jhxu) ([raw file](https://github.com/vaadin/framework/blob/060a445d20dd158b251db2ae13c58ad25e5285fb/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldMonthResolutionClickTest.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> ```
> waitForElementNotPresent
> ```
This is not what I meant with the `waitForVaadin` feature, but never mind... probably good enough for now
</blockquote></details>

It will timeout in ten seconds if an expectation is not met, which is an error in tests,so replaced it. I can do it the way you wanted if you say so.

**Review by pleku — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pleku — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11531#-:-Lhoy7Fk7iI-St1J2ldn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
