### PR TITLE
Build report changes for Vaadin Framework 8.1

### PR DESCRIPTION
**Pull request by hesara**
* Use only one staging repository
* Move "Close milestone" to a later step

Note that these changes only apply to 8.1+.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8823)

### CODE REVIEW

**Comment by hesara** [comment]
first report already tested with builds from the PR branch

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/GenerateBuildTestAndStagingReport.py, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8823#-Kf70ohqFWv06J1rx7dJ:-Kf70ohrnHclzwAmBJ63:b-yzb9yq) ([raw file](https://github.com/vaadin/framework/blob/9a47721d9762207afdaeb2aa612c2af38e10c631/scripts/GenerateBuildTestAndStagingReport.py#L124)):*
> ```Python
> 
> 
> allowedArtifacts = completeArtifactNames([ 'vaadin-maven-plugin', 'vaadin-archetypes', 'vaadin-archetype-application', 'vaadin-archetype-application-multimodule', 'vaadin-archetype-application-example', 'vaadin-archetype-widget', 'vaadin-archetype-liferay-portlet', 'vaadin-root', 'vaadin-shared', 'vaadin-server', 'vaadin-client', 'vaadin-client-compiler', 'vaadin-client-compiled', 'vaadin-push', 'vaadin-themes', 'vaadin-compatibility-shared', 'vaadin-compatibility-server', 'vaadin-compatibility-client', 'vaadin-compatibility-client-compiled', 'vaadin-compatibility-themes', 'vaadin-testbench-api', 'vaadin-bom' ], args.version)
> ```

is BOM published to the same staging as other artifacts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8823)*

**Comment by hesara** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/GenerateBuildTestAndStagingReport.py, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8823#-Kf70ohqFWv06J1rx7dJ:-KfAZdGIP905RZl_LgHz:b-46lb26) ([raw file](https://github.com/vaadin/framework/blob/9a47721d9762207afdaeb2aa612c2af38e10c631/scripts/GenerateBuildTestAndStagingReport.py#L124)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

is BOM published to the same staging as other artifacts?
</blockquote></details>

Yes, the 8.1 build publishes everything including the BOM in the same staging repository. The build conf step for the BOM has comments about disabling that step if we need to make a synchronized framework+addon release, but at least the alphas will publish the BOM together with the rest for simplicity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8823)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8823#-:-KfAeGSzb3mNvzlgxpj1:bnfp4nl)*

**Pull request merged**
