### PR TITLE
Remove unnecessary width calculation on Grid initial render

### LINKED ISSUE #8678: Vaadin 8 Grid is 5 times slower than Vaadin 7 to render columns
- Upgraded Vaadin 7.7.7 to Vaadin 8.0.0 in my project. 
And now rendering of grids is very slow.
In my application performance has gone from 1.5 Sec to 8 Sec to render 80 columns, 
even when there is no data to show.
This makes migrating to 8.0.0 imposible

- Is there any work around for this?

- I'm using Vaadin version 8.0.0
- Minimal reproducible example
Add this grid to UI

		Grid<String> grid = new Grid<>();
		grid.setSizeFull();
		for (int i = 0; i < 80; i++) {
			grid.addColumn(row -> "novalue").setCaption("Column_" + i).setWidth(200);
		}

### PR DESCRIPTION
**Pull request by hesara**
Do not calculate column widths unnecessarily, especially for columns
with fixed width.

Fixes #8678

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8848)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8848#-KfGpGsAGyDFdL8SOF13:-KfGvovt6rZbcq0hlku7:beznsob) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

can be reviewed but needs full test build before submitting this
</blockquote></details>

Also missing some basic tests for the UIs. I think there is a load time check feature somewhere in TestBench.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1336 at r1](https://reviewable.io:443/reviews/vaadin/framework/8848#-KfGvPBZVA1gtR0FalYa:-KfGvPBZVA1gtR0FalYb:b8d7ijs) ([raw file](https://github.com/vaadin/framework/blob/6a4293029f04cae0b0287b6ce82214746b20bf05/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1336)):*
> ```Java
>                 if (rows == numberOfRows) {
>                     Scheduler.get().scheduleFinally(() -> {
>                         if (initialColumnSizesCalculated) {
> ```

You could use "initialColumnSizesScheduled" or similar instead of tracking the calculation, and avoid scheduling multiple times. Just a note, not really an issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8848)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8848)*

**Comment by hesara** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8848#-KfGpGsAGyDFdL8SOF13:-KfKxLaHYZ9yeiA45jdJ:bqcnfm7) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Also missing some basic tests for the UIs. I think there is a load time check feature somewhere in TestBench.
</blockquote></details>

Updated IE11 screenshot and added basic test classes (results need to be checked in test output).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8848)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8848)*

**Comment by abishekram** [comment]
I found this issue still exists in vaadin 7.7.11.Unnecessary width calculation on Grid initial render is still happening. Will it be fixed there ? or Can I make same changes these and create a pull request for next milestone?

**Comment by tsuoanttila** [comment]
@abishekram looks like the code is mostly touching the Escalator so the same fix should work in V7 as well. Pick the changes, test it out, and if it works, make a PR! We'll definitely review it.

**Pull request merged**
