### PR TITLE
Grid tests migration. Next round.

### LINKED ISSUE #8373: Migrate Grid UI v7 tests P5
Proceed with migrating Grid tests from v7 to v8.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8373

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8412)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 12 of 22 files at r1.
Review status: 8 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridGeneratedPropertiesTest.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8412#-Kbu5CviyRwfylHKOy6M:-Kbu5CviyRwfylHKOy6N:bg7g31p) ([raw file](https://github.com/vaadin/framework/blob/139ad852a661deb4c57945ea1f25f19604480cdc/uitest/src/test/java/com/vaadin/tests/components/grid/GridGeneratedPropertiesTest.java#L33)):*
> ```Java
> 
> @TestCategory("grid")
> @RunLocally(Browser.PHANTOMJS)
> ```

RunLocally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412)*

**Comment by denis-anisimov** [comment]
Review status: 8 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridGeneratedPropertiesTest.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8412#-Kbu5CviyRwfylHKOy6M:-Kbu6EHUsArpJX0fcTLK:byeaq04) ([raw file](https://github.com/vaadin/framework/blob/139ad852a661deb4c57945ea1f25f19604480cdc/uitest/src/test/java/com/vaadin/tests/components/grid/GridGeneratedPropertiesTest.java#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

RunLocally?
</blockquote></details>

Always forget about it.
Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412)*

**Comment by hesara** [comment]
Reviewed 6 of 22 files at r1, 1 of 1 files at r2.
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridGeneratedProperties.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/8412#-KbxvuzkU0-nBNMhEyqD:-KbxvuzkU0-nBNMhEyqE:b-gstqgl) ([raw file](https://github.com/vaadin/framework/blob/aad927826f103e781e3054c19cd2bec98ba09fd1/uitest/src/main/java/com/vaadin/tests/components/grid/GridGeneratedProperties.java#L38)):*
> ```Java
> 
> /**
>  * Smoke tests for v7 generated properties in Grid
> ```

no longer in v7 package but comment about v7 smoke test?

---

*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridEditorUI.java, line 0 at r2](https://reviewable.io:443/reviews/vaadin/framework/8412#-Kbxw05aH6XhWoHAVLD6:-Kbxw05aH6XhWoHAVLD7:bk3put3) ([raw file](https://github.com/vaadin/framework/blob/aad927826f103e781e3054c19cd2bec98ba09fd1/uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridEditorUI.java#L0)):*
Removed? Isn't this used in GridEditorUITest?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412)*

**Comment by denis-anisimov** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridGeneratedProperties.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/8412#-KbxvuzkU0-nBNMhEyqD:-KbxwDZH__gCPm5j4DFv:b9fgdt1) ([raw file](https://github.com/vaadin/framework/blob/aad927826f103e781e3054c19cd2bec98ba09fd1/uitest/src/main/java/com/vaadin/tests/components/grid/GridGeneratedProperties.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

no longer in v7 package but comment about v7 smoke test?
</blockquote></details>

v7 package should be removed at some point as I understand.....
Currently tests in v7 package are not executed at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412)*

**Comment by denis-anisimov** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridEditorUI.java, line  at r2](https://reviewable.io:443/reviews/vaadin/framework/8412#-Kbxw05aH6XhWoHAVLD6:-Kbxwb3RFZz9nVR7TCmc:b-nfsc0c) ([raw file](https://github.com/vaadin/framework/blob/aad927826f103e781e3054c19cd2bec98ba09fd1/uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridEditorUI.java#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Removed? Isn't this used in GridEditorUITest?
</blockquote></details>

This UI has been already migrated.
For some reason it hasn't been removed.
It just removes it from v7 package.
The test for it is moved outside of v7 package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 3 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8412#-:-KbyRFH2nhd2p3eHsHdj:bnfp4nl)*

**Pull request merged**
