### PR TITLE
Wait unitl loading indicator disappears.

### LINKED ISSUE #8318: Fix PopupDateTimeFieldStatesTest
The  `PopupDateTimeFieldStatesTest` test is unstable.
It periodically fails.
The reason is screenshots difference.
The original screenshot doesn't contain "progress bar" on the top which may appear on the validation screenshot (or may not).

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8318

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8319)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTG_h53gEmnBh9fXW:-KbGTG_h53gEmnBh9fXX:b2nhky0) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L13)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> @RunLocally(Browser.PHANTOMJS)
> ```

No.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTLhtFGQDY6jP8aiO:-KbGTLhtFGQDY6jP8aiP:b-xybt6n) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
> ```Java
>         openTestURL();
> 
>         // wait until loading indicator becomes invisible
> ```

If this is needed, the TestBench integration is fundamentally broken

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTLhtFGQDY6jP8aiO:-KbGZB9GS8R3yQIjfQjc:b-lvatbm) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

If this is needed, the TestBench integration is fundamentally broken
</blockquote></details>

Then it's broken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTLhtFGQDY6jP8aiO:-KbJFlyrhdeZyV8t790C:b1o7r4f) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Then it's broken.
</blockquote></details>

The underlying problem is likely that `Valo` uses an animation when hiding the loading indicator. The framework assumes that the loading indicator is gone after calling `VLoadingIndicator.hide()` but this is not the case.

Not sure if this should be fixed so that `isActive()` always waits for the loading indicator to really disappear (something like this "fix" but done in the framework) or if this should be a special case only for `compareScreen`, which is the only place is matters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTG_h53gEmnBh9fXW:-KbJQsy5dIK8N92mb9NY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L13)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

No.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbGTLhtFGQDY6jP8aiO:-KbJQvTfIWtN84flCw_6:b-2zgvgy) ([raw file](https://github.com/vaadin/framework/blob/4b84af4f57ba61aa25ec56b9f536f81618152075/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The underlying problem is likely that `Valo` uses an animation when hiding the loading indicator. The framework assumes that the loading indicator is gone after calling `VLoadingIndicator.hide()` but this is not the case.

Not sure if this should be fixed so that `isActive()` always waits for the loading indicator to really disappear (something like this "fix" but done in the framework) or if this should be a special case only for `compareScreen`, which is the only place is matters
</blockquote></details>

Should it be in the framework or in TB ?

Anyway I need this test fixed somehow right now. Otherwise it produces a lot of false-positive validation results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Execution timeout for a build validation is the result of the "proper fix" in the FW .
So I would consider this as a separate issue. Right now it's important to avoid false-positives.

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 484 at r2](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbP6VqvGqmgsR8Nqhx0:-KbP6VqvGqmgsR8Nqhx1:bcofx18) ([raw file](https://github.com/vaadin/framework/blob/69ef5db629e9cc8ffb6e061062664e03c17e4482/client/src/main/java/com/vaadin/client/ApplicationConnection.java#L484)):*
> ```Java
>             }
>         }
>     
> ```

There are only whitespace changes in this file

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbP6dreLiXQ7r3YffTl:-KbP6dreLiXQ7r3YffTm:bdnom84) ([raw file](https://github.com/vaadin/framework/blob/69ef5db629e9cc8ffb6e061062664e03c17e4482/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
> ```Java
>         WebElement loadingIndicator = findElement(
>                 By.className("v-loading-indicator"));
>         waitUntil(driver -> {
> ```

Is this needed when you have changed the theme to `tests-valo-disabled-animations`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 484 at r2](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbP6VqvGqmgsR8Nqhx0:-KbP725OWEc_-yNyz90D:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/69ef5db629e9cc8ffb6e061062664e03c17e4482/client/src/main/java/com/vaadin/client/ApplicationConnection.java#L484)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

There are only whitespace changes in this file
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java, line 23 at r2](https://reviewable.io:443/reviews/vaadin/framework/8319#-KbP6dreLiXQ7r3YffTl:-KbP73ZHU7MQ6S9ynPTI:bcxiusg) ([raw file](https://github.com/vaadin/framework/blob/69ef5db629e9cc8ffb6e061062664e03c17e4482/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateTimeFieldStatesTest.java#L23)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is this needed when you have changed the theme to `tests-valo-disabled-animations`?
</blockquote></details>

I still see animated loading indicator......
So I assume yes. But I cannot be sure since I cannot reproduce it locally. It should be remote run where it can be seen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8319)*

**Comment by denis-anisimov** [comment]
Looks like is not relevant anymore

**Pull request closed without merging**
