### PR TITLE
Fix initially selected CheckBox rendering in Safari

### LINKED ISSUE #10859: Checked checkbox on a tabsheet gets unchecked when navigating away and back to the tab
- Tested and reproducible on Vaadin Framework version 7.7.13 and 8.2.0
- Issue only appears in Safari (tested with Safari version 11.1) (no issues on chrome and firefox)
- Web container: Tomcat 7.0.40
- Description of the bug: I've for a tabsheet with 2 tabs, on the first tab I've a checkbox (checked). When the application loads, the first tab is visible and the checkbox is checked. When I navigate to the second tab and navigate back to the first tab, the checkbox is unchecked. The issue only appears on Safari. I could not reproduce the issue on chrome, neither on firefox.
- Expected behavior: I expected the checkbox on the first tab to still be checked.
- Actual behavior: The checkbox on the first tab is unchecked

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #10859

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11024)

### CODE REVIEW

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11024)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by kvalev** [comment]
Do you plan on backporting this fix to Vaadin 7?

**Comment by tsuoanttila** [comment]
@koendecock if you have the time to do it, you should cherry-pick the change to the `7.7` branch of the framework repository. Once it actually makes it way to the Framework 7, the same change should also be applied to the compatibility repo as well.

But the main question is: Why are you using the CheckBox from V7? What is the V8 version missing that prevents you from using that one instead?

**Comment by koendecock** [comment]
I'v no experience in contributing to the framework. So I've no idea how to cherry pick the change to 7.7.
I'm planning to modify my application to use the v8 controls but there is currently no time to do this.

**Comment by tsuoanttila** [comment]
Now that I look at it, it seems that the fix itself was picked to 7.7 but was it not applied to the compatibilty version..

**Comment by koendecock** [comment]
Hi, thanks for checking. But how can this fix than become part of the compatibitily version?

**Comment by koendecock** [comment]
Hi,

can someone from the Vaadin community cherry pick en merge this fix into the VCheckBox for the v7 compatibility package for vaadin 8 as well?

Thanks in advance
Gr, Koen

**Pull request merged**
