### PR TITLE
Restore all current instance values after running access tasks

### PR DESCRIPTION
**Pull request by Legioth**
Fixes vaadin/framework8-issues#593

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8131)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1863 at r1](https://reviewable.io:443/reviews/vaadin/framework/8131#-K_Z2Vqmbts2t-f0fdvC:-K_Z2Vqmbts2t-f0fdvD:bdumw4m) ([raw file](https://github.com/vaadin/framework/blob/89249b3bc96c85d44fb348c606276d7c7601e79b/server/src/main/java/com/vaadin/server/VaadinService.java#L1863)):*
> ```Java
> 
>         FutureAccess pendingAccess;
>         Map<Class<?>, CurrentInstance> oldInstances = CurrentInstance
> ```

Add a comment why this is done in two steps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131)*

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1863 at r1](https://reviewable.io:443/reviews/vaadin/framework/8131#-K_Z2Vqmbts2t-f0fdvC:-K_Z4PSc_GKtQSWbrZ6U:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/89249b3bc96c85d44fb348c606276d7c7601e79b/server/src/main/java/com/vaadin/server/VaadinService.java#L1863)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Add a comment why this is done in two steps
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131#-:-K_cjPT1G2-AJl_zdWV3:bnfp4nl)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1863 at r1](https://reviewable.io:443/reviews/vaadin/framework/8131#-K_Z2Vqmbts2t-f0fdvC:-K_cjdyOq3jVCxfU1MOP:b-saxr4k) ([raw file](https://github.com/vaadin/framework/blob/89249b3bc96c85d44fb348c606276d7c7601e79b/server/src/main/java/com/vaadin/server/VaadinService.java#L1863)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The comment does not tell why, only what

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1863 at r1](https://reviewable.io:443/reviews/vaadin/framework/8131#-K_Z2Vqmbts2t-f0fdvC:-K_dmX8KeudaRTYgmIUo:bjik7ej) ([raw file](https://github.com/vaadin/framework/blob/89249b3bc96c85d44fb348c606276d7c7601e79b/server/src/main/java/com/vaadin/server/VaadinService.java#L1863)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The comment does not tell why, only what
</blockquote></details>

What do you want me to write here instead?

To me, what's written there now quite strongly implies that the reason for dumping separately is that setCurrent doesn't dump everything that is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1863 at r1](https://reviewable.io:443/reviews/vaadin/framework/8131#-K_Z2Vqmbts2t-f0fdvC:-K_fBzqNv-5UN_qX6APW:b-seglqg) ([raw file](https://github.com/vaadin/framework/blob/89249b3bc96c85d44fb348c606276d7c7601e79b/server/src/main/java/com/vaadin/server/VaadinService.java#L1863)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What do you want me to write here instead?

To me, what's written there now quite strongly implies that the reason for dumping separately is that setCurrent doesn't dump everything that is needed.
</blockquote></details>

I was looking for why something is needed which is not dumped by `setCurrent`, i.e. the whole reason for creating this patch. But at least now it is explicit that we can't use what `setCurrent` returns - for whatever reason

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8131)*

**Pull request merged**
