### PR TITLE
Change VSlider to use Event.ONKEYDOWN with Firefox 65+

### LINKED ISSUE #11502: Up and Down arrows do not work in Firefox 65
## Description of the bug

Navigation arrows do not work in UI components with Firefox 65.

Affected UI components:

- MenuBar
- Slider
- V7 Tree
- Table
- V7 Slider
- Calendar

Vaadin Framework version 8.0.* - 8.7.*
Browser version: Firefox 65.0+

## Minimal reproducible example

1. Open UI with Table / Slider / MenuBar component
2. Hit Up/Down arrow button in Table or in MenuBar (or left/right in Slider)

- Expected behavior

Arrow buttons should change selected row / value of component.

- Actual behavior

Nothing happens.

## Proposed fixes

We need to disable old workaround with key press event handlers for Firefox 65+:

https://github.com/cuba-platform/vaadin/commit/4d2df4a51afe3756bbc232b5758854c2a237e8e0

https://github.com/cuba-platform/vaadin/commit/83b786529e42c8b2b10348647587e48ddc384fe9

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes #11502

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11506)

### CODE REVIEW

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11506#-:-Laz7p7L4XOpkoqVarVr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Enerccio** [comment]
This fixed on the slider, why didn't you fix EVERY component that was listed in the original bug report? Wtf

**Comment by OlliTietavainenVaadin** [comment]
@Enerccio This particular pull request is for Slider. There are other PR:s for other components: 

https://github.com/vaadin/framework/pull/11505
https://github.com/vaadin/framework/pull/11507
https://github.com/vaadin/framework/pull/11508
https://github.com/vaadin/framework/pull/11509

**Comment by Enerccio** [comment]
was it regressed then? I can see this in the 7.7.17 maven build:

` /*
         * Firefox auto-repeat works correctly only if we use a key press
         * handler, other browsers handle it correctly when using a key down
         * handler
         */
        if (BrowserInfo.get().isGecko()) {
            scrollBodyPanel.addKeyPressHandler(navKeyPressHandler);
        } else {
            scrollBodyPanel.addKeyDownHandler(navKeyDownHandler);
        }`

https://mvnrepository.com/artifact/com.vaadin/vaadin-client/7.7.17 check the build here

**Comment by OlliTietavainenVaadin** [comment]
@Enerccio this particular fix was included in the 7.7.18 Extended Support release.

**Pull request merged**
