### PR TITLE
Check class name type on Grid cell mouse over

### LINKED ISSUE #10192: Mouse over SVG in Grid cell throws exception
When there is an SVG image in a Grid's cell, moving the mouse over the cell throws the following exception.

```
SEVERE: (TypeError) : this$static.indexOf is not a function
com.google.gwt.core.client.JavaScriptException: (TypeError) : this$static.indexOf is not a function
	at Unknown.java_lang_String_$indexOf__Ljava_lang_String_2Ljava_lang_String_2I(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_vaadin_client_widgets_Grid_$isOrContainsInSpacer__Lcom_vaadin_client_widgets_Grid_2Lcom_google_gwt_dom_client_Node_2Z(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_vaadin_client_widgets_Grid_onBrowserEvent__Lcom_google_gwt_user_client_Event_2V(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_google_gwt_user_client_DOM_dispatchEvent__Lcom_google_gwt_user_client_Event_2Lcom_google_gwt_dom_client_Element_2Lcom_google_gwt_user_client_EventListener_2V(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_google_gwt_user_client_impl_DOMImplStandard_dispatchEvent__Lcom_google_gwt_user_client_Event_2V(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_google_gwt_core_client_impl_Impl_apply__Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.com_google_gwt_core_client_impl_Impl_entry0__Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2(com.vaadin.DefaultWidgetSet-0.js)
	at Unknown.<anonymous>(com.vaadin.DefaultWidgetSet-0.js)
```

The reason is that in `Grid#isOrContainsInSpacer()` method `Element.className` parameter is of type `SVGAnimatedString` in case of an `SVGElement` according to [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/className#Notes).

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #10192

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10194)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Minor method placement related issue. Other than that, :lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9338 at r1](https://reviewable.io:443/reviews/vaadin/framework/10194#-KwdznGCheiX2w2h25jB:-KwdznGD-hvYtiWpH0NV:b16yyqx) ([raw file](https://github.com/vaadin/framework/blob/df4cce4f116340c3f27e40a464b4dd1a0d78578a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9338)):*
> ```Java
>     }
> 
>     private native boolean isString(Object obj) /*-{
> ```

As this is more of a `WidgetUtil` type method that we might want to use in some other context as well, I'd move this implementation to the mentioned `WidgetUtil` class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194#-:-Kwe-1mZ4VcYwCvIL_vS:b-5creuu)*

**Comment by wbadam** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 9338 at r1](https://reviewable.io:443/reviews/vaadin/framework/10194#-KwdznGCheiX2w2h25jB:-Kwe2gjiyyVbFNnOFfIL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/df4cce4f116340c3f27e40a464b4dd1a0d78578a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L9338)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

As this is more of a `WidgetUtil` type method that we might want to use in some other context as well, I'd move this implementation to the mentioned `WidgetUtil` class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194)*

**Comment by tsuoanttila** [comment]
@torok-peter please review the formatting

---

Reviewed 2 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194#-:-KweDMa_qOg0U4D2KbeS:b-ye1je9)*

**Comment by torok-peter** [comment]
Reviewed 2 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridSvgInCell.java, line 32 at r3](https://reviewable.io:443/reviews/vaadin/framework/10194#-KwiEoAOehYxqfq55jj3:-KwiEoAOehYxqfq55jj4:bjcodfm) ([raw file](https://github.com/vaadin/framework/blob/de77e51fdc082181cdd52d8d3b2b840715bd11db/uitest/src/main/java/com/vaadin/tests/components/grid/GridSvgInCell.java#L32)):*
> ```Java
>         DataObject data = new DataObject();
>         data.setSvg(
>                 "<svg width=\"100%\" height=\"20px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><polygon id=\"bar_background_blue\" stroke=\"gray\" fill=\"#D6D6D6\" points=\"0 0,59 0,66 7,59 14,0 14\"></polygon><rect id=\"bar_blue\" x=\"1\" y=\"1\" width=\"0px\" height=\"13\" fill=\"#7298C0\"></rect></svg>");
> ```

Wrap this into multiple lines, preferably at tag ends, to make it more readable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194)*

**Comment by wbadam** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridSvgInCell.java, line 32 at r3](https://reviewable.io:443/reviews/vaadin/framework/10194#-KwiEoAOehYxqfq55jj3:-KwiOg9v1EylroxRv7R4:b-8b3qom) ([raw file](https://github.com/vaadin/framework/blob/de77e51fdc082181cdd52d8d3b2b840715bd11db/uitest/src/main/java/com/vaadin/tests/components/grid/GridSvgInCell.java#L32)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Wrap this into multiple lines, preferably at tag ends, to make it more readable
</blockquote></details>

Done. Formatted with Eclipse

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194)*

**Comment by torok-peter** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194#-:-Kwiabx7Uezd19G45UuP:bnfp4nl)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10194)*

**Pull request merged**
