### PR TITLE
Value context with hasvalue

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8944)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/components/components-fields.asciidoc, line 177 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDD2jhU2Jizy5RwJZN:-KgDD2jiB1s26mT2chro:b-iqpz5) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/documentation/components/components-fields.asciidoc#L177)):*
> ```AsciiDoc
> validator from a boolean function and an error message. If the application requires
> more sophisticated validation diagnostics (ex. locale-specific), there is
> [methodname]#withValidator# method, which uses boolean function and [classname]#ErrorMessageProvider#.
> ```

... there is the method withValidator ... a boolean function and an ErrorMessageProvider. The ErrorMessageProvider ... based on the locale of the validation and the source component value, which are provided in the ValueContext. 

(Is the value really provider, or rather a way to access it? Are we sure what we get from there is really the value? Do we have access to the value that caused the validation to fail? At least with date and textual inputs, the actual failing value might not be available from the component, it is only in some events or in the parameter to ADF.handleUnparsableDate() and implicitly in the error message it creates. - These comments are not necessarily blockers, but we should probably decide on these.)

---

*[server/src/main/java/com/vaadin/data/ValueContext.java, line 61 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDDl_fKPIs1wYK2dWK:-KgDDl_gv5dPQLuvc92I:bfpqvau) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/data/ValueContext.java#L61)):*
> ```Java
> 
>     /**
>      * Constructor for {@code ValueContext}.
> ```

could mention that the component is also used as HasValue if it implements the interface

---

*[server/src/main/java/com/vaadin/data/ValueContext.java, line 148 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDCz77o5W8z4Bl5unZ:-KgDCz77o5W8z4Bl5un_:b-771jzi) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/data/ValueContext.java#L148)):*
> ```Java
>     /**
>      * Returns an {@code Optional} for the {@code HasValue} used in the value
>      * conversion.
> ```

could mention in which cases this is or isn't available

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 687 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDDsm7UigBySrruGOj:-KgDDsm7UigBySrruGOk:b-j197rt) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L687)):*
> ```Java
>             RangeValidator<T> validator = getRangeValidator();
>             ValidationResult result = validator.apply(value,
>                     new ValueContext(this,this));
> ```

space missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8944)*

**Comment by elmot** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/components/components-fields.asciidoc, line 177 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDD2jhU2Jizy5RwJZN:-KgxBGIw95jcNmRMB2h3:bruyib4) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/documentation/components/components-fields.asciidoc#L177)):*
Corrected.
>Is the value really provider?  Are we sure what we get from there is really the value?
I suppose that HasValue to be a real component (or a grid selection), and the real value, entered by the user, should be accessible with that. 
> actual failing value
You mean some intermediate value in the conversion chain? I don't think it's required to compose the error message.

ADF breaks our idea of conversion-validation, but, I am afraid, we can't  review the component in sake of API consistency.

In some cases, HasValue might be not available or relevant, and in this case getHasValue should return an empty optional.

---

*[server/src/main/java/com/vaadin/data/ValueContext.java, line 61 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDDl_fKPIs1wYK2dWK:-KgtVo79ZynWIoGzYuJm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/data/ValueContext.java#L61)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could mention that the component is also used as HasValue if it implements the interface
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValueContext.java, line 148 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDCz77o5W8z4Bl5unZ:-KgxDXiaw_ddhMsbqP3H:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/data/ValueContext.java#L148)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could mention in which cases this is or isn't available
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 687 at r2](https://reviewable.io:443/reviews/vaadin/framework/8944#-KgDDsm7UigBySrruGOj:-KgtVF__z-Wp6NW07Kit:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/46adca83ff861c14bb3659b780a08af3fde188e0/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L687)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

space missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8944)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-fields.asciidoc, line 176 at r4](https://reviewable.io:443/reviews/vaadin/framework/8944#-Knm_Un7I7ncrxHqd18L:-Knm_Un7I7ncrxHqd18M:bex6014) ([raw file](https://github.com/vaadin/framework/blob/7b003981d0ece6f60c24291a5a6eb2231b3a7a71/documentation/components/components-fields.asciidoc#L176)):*
> ```AsciiDoc
> declaration. There is also an [methodname]#withValidator# overload that creates a
> validator from a boolean function and an error message. If the application requires
> more sophisticated validation diagnostics (ex. locale-specific), there is a
> ```

I'd use "e.g."

---

*[server/src/test/java/com/vaadin/data/ValueContextTest.java, line 68 at r4](https://reviewable.io:443/reviews/vaadin/framework/8944#-KnmY9mLVAhyKhLjfNGW:-KnmY9mMin_eQ3ClLo0c:brpdyls) ([raw file](https://github.com/vaadin/framework/blob/7b003981d0ece6f60c24291a5a6eb2231b3a7a71/server/src/test/java/com/vaadin/data/ValueContextTest.java#L68)):*
> ```Java
>         setLocale(null);
>         ValueContext fromComponent = new ValueContext(new CheckBox(), textField, Locale.CANADA);
>         Assert.assertEquals(textField, fromComponent.getHasValue().get());
> ```

(could also test that this uses the explicitly given locale)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8944)*

**Comment by elmot** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-fields.asciidoc, line 176 at r4](https://reviewable.io:443/reviews/vaadin/framework/8944#-Knm_Un7I7ncrxHqd18L:-KnmcHpjPQVRqONYvs4b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7b003981d0ece6f60c24291a5a6eb2231b3a7a71/documentation/components/components-fields.asciidoc#L176)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd use "e.g."
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/ValueContextTest.java, line 68 at r4](https://reviewable.io:443/reviews/vaadin/framework/8944#-KnmY9mLVAhyKhLjfNGW:-KnmcKJ-FThaXQ9RWDDk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7b003981d0ece6f60c24291a5a6eb2231b3a7a71/server/src/test/java/com/vaadin/data/ValueContextTest.java#L68)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could also test that this uses the explicitly given locale)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8944)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8944)*

**Pull request merged**
