### PR TITLE
Fix missing v-disabled for RadioButtonGroup and CheckBoxGroup options

### LINKED ISSUE #9258: Disabled RadioButtonGroup/CheckBoxGroup is not in grey tint.
Hi,

In Vaadin 8.0.5, disabled RadioButtonGroup is not in grey tint when the component is disabled.

Thanks,

### PR DESCRIPTION
**Pull request by pleku**
Fixes #9258

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10332)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 43 at r2](https://reviewable.io:443/reviews/vaadin/framework/10332#-Kz88WNLUgi5JTs0jd7u:-Kz88WNLUgi5JTs0jd7v:bcp9z2q) ([raw file](https://github.com/vaadin/framework/blob/8429482aca8a0794e3e0a6d20ffdae97e99f4573/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L43)):*
> ```Java
>  * @since 8.0
>  */
> @RunLocally(Browser.PHANTOMJS)
> ```

This should be removed or fixed.
`java.lang.AssertionError: @RunLocally annotation is not allowed by default in framework tests. See file uitest/eclipse-run-selected-test.properties for more information.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10332)*

**Comment by caalador** [comment]
Reviewed 1 of 4 files at r4.
Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10332)*

**Comment by pleku** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 194 at r4](https://reviewable.io:443/reviews/vaadin/framework/10332#-KzB4d4lsh8DIY2MmtUY:-KzO_rilN4EygtE8pPnr:b-wua5zr) ([raw file](https://github.com/vaadin/framework/blob/6979bfdf8804dd560d8a23eacd6b0ac2681e57d6/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L194)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should this use the `boolean enabled` from above?
</blockquote></details>

The read-only should not effect the disabled style name

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 161 at r4](https://reviewable.io:443/reviews/vaadin/framework/10332#-KzB4Wu2XwHEoWNUEhFD:-KzO_wXRbt9AEozj1oif:b-wua5zr) ([raw file](https://github.com/vaadin/framework/blob/6979bfdf8804dd560d8a23eacd6b0ac2681e57d6/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L161)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should this use the `boolean enabled` from above?
</blockquote></details>

The read-only should not effect the disabled style name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10332)*

**Comment by caalador** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10332)*

**Pull request merged**
