### PR TITLE
Rewrite HierarchyMapper to consistently handle changes

### LINKED ISSUE #9448: TreeGrid Sort and Refresh Should Maintain Expansion State
8.1.0.beta1

I have a requirement where I need to refresh items within my `TreeGrid` hierarchy in response to user-initiated events (adds, updates, deletes). After refreshing these items, I need them to display in sorted order (instead of having new items appear at the bottom), however sorting clears the state of item expansion. 

```java
HorizontalLayout buttons = new HorizontalLayout();
TreeGrid<String> tree = new TreeGrid<>();
TreeData<String> data = new TreeData<>();
tree.setDataProvider(new TreeDataProvider<>(data));
tree.addColumn(String::toString);
for (String root : new String[]{"First", "Second", "Third"}) {
	data.addItem(null, root);
	for (String child : new String[]{"1", "2", "3"}) {
		data.addItem(root, root + " - " + child);
	}
}
Button sort = new Button("Sort", e -> tree.sort(tree.getColumns().get(0)));
Button refresh = new Button("Refresh", e -> tree.getDataProvider().refreshAll());
content.addComponent(tree);
content.addComponent(buttons);
buttons.addComponent(sort);
buttons.addComponent(refresh);
```

### LINKED ISSUE #9449: TreeGrid Expand and Sort Produce Inconsistent State and Error
8.1.0.beta1

When attempting to track expanded nodes and re-expand after sorting, the expand method appears to have no effect.

```java
class MyTreeGrid<T> extends TreeGrid<T> {
    private static final long serialVersionUID = 5137316344382298358L;
    private Set<T> expanded = new HashSet<>();
    MyTreeGrid() { 
        super();
        addExpandListener(e -> expanded.add(e.getExpandedItem()));
        addCollapseListener(e -> expanded.remove(e.getCollapsedItem()));
    }
    @Override
    public void sort(Column<T, ?> columns) {
        super.sort(columns);
        super.expand(expanded);
    }
}
HorizontalLayout buttons = new HorizontalLayout();
MyTreeGrid<String> tree = new MyTreeGrid<>();
TreeData<String> data = new TreeData<>();
tree.setDataProvider(new TreeDataProvider<>(data));
tree.addColumn(String::toString);
for (String root : new String[]{"First", "Second", "Third"}) {
    data.addItem(null, root);
    for (String child : new String[]{"1", "2", "3"}) {
        data.addItem(root, root + " - " + child);
    }
}
Button sort = new Button("Sort", e -> tree.sort(tree.getColumns().get(0)));
content.addComponent(tree);
content.addComponent(buttons);
buttons.addComponent(sort);
```

Additionally, using the example above, performing the following clicks produces incorrect data in the tree and the error below.

1. Expand "First", "Second" and "Third"
2. Click Sort button
3. Expand "Third"
4. Click Sort button
    a. Notice that the "Second" child items are displayed underneath the "First - 1" item
5. Click Sort button

```
...
Caused by: java.lang.IllegalArgumentException: Invalid row index 8 when tree grid size of 3
	at com.vaadin.data.provider.HierarchicalDataCommunicator.doExpand(HierarchicalDataCommunicator.java:421)
	at com.vaadin.ui.TreeGrid$1.setNodeCollapsed(TreeGrid.java:137)
	... 44 more
```

### LINKED ISSUE #9465: Cannot expand row on TreeGrid when first column has a NumberRenderer
If I set a NumberRenderer to a the first column of a TreeGrid, when I load the page, I see the arrow to expand the row, but when I click it it disappears entirely. It works OK without the NumberRenderer. 

I'm using v 8.1.0.beta1

### LINKED ISSUE #9490: TreeGrid - ArrayIndexOutOfBoundsException when expanding node
Hello,

In some occasions I get the following exception when trying to expand a node with one or more children:

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.vaadin.data.provider.HierarchicalDataCommunicator.lambda$doPushRows$1(HierarchicalDataCommunicator.java:181)
	at com.vaadin.data.provider.HierarchyMapper.reorderLevelQueryResultsToFlatOrdering(HierarchyMapper.java:505)
	at com.vaadin.data.provider.HierarchicalDataCommunicator.lambda$doPushRows$3(HierarchicalDataCommunicator.java:193)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.vaadin.data.provider.HierarchicalDataCommunicator.doPushRows(HierarchicalDataCommunicator.java:184)
	at com.vaadin.data.provider.HierarchicalDataCommunicator.loadRequestedRows(HierarchicalDataCommunicator.java:154)
	at com.vaadin.data.provider.HierarchicalDataCommunicator.sendDataToClient(HierarchicalDataCommunicator.java:105)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:310)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:111)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1528)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

I have created a minimal example([tree-grid-issue.zip](https://github.com/vaadin/framework/files/1055098/tree-grid-issue.zip)) that helps reproduce the problem. I have also included the log after running the maven project using `jetty:run`.

To reproduce after starting up simply start expanding a node and its sub-nodes until you hit the error

### PR DESCRIPTION
**Pull request by tsuoanttila**
Expanded/collapsed information based on items and their ids, avoid using indexes where possible.

Fixes #9449 
Fixes #9490
Fixes #9448 
Fixes #9465

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9496)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 9 files at r1, 1 of 4 files at r2.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-KmeYBktg-Epyy8W4daN:bapewiw) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
> ```Java
>      *            the index of the item
>      */
>     public void collapse(T item, Optional<Integer> index) {
> ```

This method has an extra parameter, with kind of data duplication. I believe, this method has to be here but should it be public and be included into  public API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-KmemtSPo1Dt1hae2jTr:b-suthx4) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This method has an extra parameter, with kind of data duplication. I believe, this method has to be here but should it be public and be included into  public API?
</blockquote></details>

It is a method for the tree grid to do expansion when it already knows the index. it's merely an optimisation of the most basic type. If we know the index, we don't need to go through the whole tree to find it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Reviewed 2 of 9 files at r1, 1 of 4 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 203 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmefrM0xNQ_WmckyXCk:-KmefrM0xNQ_WmckyXCl:be2xspu) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L203)):*
> ```Java
>      *            the index of the item
>      */
>     public void expand(T item, Optional<Integer> index) {
> ```

See my comment about collapse(,)

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java, line 224 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmenWBhudqUA8_vXkKt:-KmenWBhudqUA8_vXkKu:bdbowwa) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java#L224)):*
> ```Java
>         List<Node> collect = mapper.fetchItems(range)
>                 .collect(Collectors.toList());
>         System.err.println(collect.stream().map(Object::toString)
> ```

Should be removed or moved to Logger.debug or commented out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-Kmeo1YdlwA-0DPxdtJS:b-qk3w46) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

It is a method for the tree grid to do expansion when it already knows the index. it's merely an optimisation of the most basic type. If we know the index, we don't need to go through the whole tree to find it out.
</blockquote></details>

Why it's public? The method is gonna be really confusing for an app developer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-KmepsBOKOPojh4qJFS2:b2elw8y) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why it's public? The method is gonna be really confusing for an app developer
</blockquote></details>

Any API of DataCommunicator is most likely confusing for the app developer since this is framework internals.

If you can please come up with the correct visibility level to keep it accessible from the component but hidden from the app developer, and I'll happily make the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-KmerDOtVMcOmyM8XcMC:bymc46l) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Any API of DataCommunicator is most likely confusing for the app developer since this is framework internals.

If you can please come up with the correct visibility level to keep it accessible from the component but hidden from the app developer, and I'll happily make the change.
</blockquote></details>

Well, if it's not possible to protect that with access modifiers, we might use special naming to give a chance to a developer not to be confused. Most probably those methods were named doExpand/doCollapse exactly because of that.

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-Kmep770H5GS8cmoGrp0:-Kmep771nmG0AkpcjabN:b-rgo3oe) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java#L155)):*
> ```Java
> 
>         // Construct a sorted version of test data with correct filters
>         List<List<Node>> levels = new ArrayList<>();
> ```

Looks it like it's easier to manually build the expected result (not a blocker)

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java, line 196 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeqF9m8P5JB2wDBFIw:-KmeqF9m8P5JB2wDBFIx:b-6h414e) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java#L196)):*
> ```Java
>     public void fetchWithFilter() {
>         expand(testData.get(0));
>         Node expandedNode = testData.get(2 + LEAF_COUNT); // Expand second node
> ```

confusing name (NaB)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by tsuoanttila** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 169 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmeYBktg-Epyy8W4daM:-KmetUglAHRf_Y_gVkw5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L169)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Well, if it's not possible to protect that with access modifiers, we might use special naming to give a chance to a developer not to be confused. Most probably those methods were named doExpand/doCollapse exactly because of that.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 203 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmefrM0xNQ_WmckyXCk:-KmetV9pisKiJIBCBRb-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L203)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See my comment about collapse(,)
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-Kmep770H5GS8cmoGrp0:-KmetFtv2BsbcVq1pBEM:bk0kphr) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java#L155)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Looks it like it's easier to manually build the expected result (not a blocker)
</blockquote></details>

I parameterised it on purpose and made this since, I knew I'd run into interesting things with the filtering and this way it was easier to test how it actually behaves.

---

*[server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java, line 224 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmenWBhudqUA8_vXkKt:-KmetROekqcY-OxEabjR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/test/java/com/vaadin/data/provider/hierarchical/HierarchyMapperWithDataTest.java#L224)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Should be removed or moved to Logger.debug or commented out
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Reviewed 1 of 4 files at r2, 2 of 3 files at r3.
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmethGeTHUPKo4fkGAA:-KmethGfK5NJMyauZsnC:b-bf7fjg) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L101)):*
> ```Java
>      */
>     public Integer getParentIndex(int target) throws IllegalArgumentException {
>         List<T> flatHierarchy = getHierarchy(null).collect(Collectors.toList());
> ```

This code may be optimized. There is no need to build the full list and then go through that. Its enough to iterate through Ts until the actual item is found.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 117 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-Kmev64yj8qjyCGD0zSv:-Kmev64yj8qjyCGD0zSw:bu8l73j) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L117)):*
> ```Java
>      *             if given target index is not found
>      */
>     public T getParent(int target, List<T> list)
> ```

Confusing method made in sake of optimization, the same case as doCollapse/doExpand

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 151 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmevlGxzntZwdmywMWz:-KmevlGxzntZwdmywMX-:bu8l73j) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L151)):*
> ```Java
>      * @return range of rows added by expanding the item
>      */
>     public Range expand(T item, Optional<Integer> position) {
> ```

Confusing method made in sake of optimization, the same case as doCollapse/doExpand

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 171 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmevqmzTt5uIbZ9TT99:-KmevqmzTt5uIbZ9TT9A:bu8l73j) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L171)):*
> ```Java
>      * @return range of rows removed by collapsing the item
>      */
>     public Range collapse(T item, Optional<Integer> position) {
> ```

Confusing method made in sake of optimization, the same case as doCollapse/doExpand

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by tsuoanttila** [comment]
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 101 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmethGeTHUPKo4fkGAA:-Kmf894N-TaVH3hXgKc4:b-d7v0ur) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L101)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This code may be optimized. There is no need to build the full list and then go through that. Its enough to iterate through Ts until the actual item is found.
</blockquote></details>

An optimized solution for this is pretty much as complex as the getHierarchy implementation. Yes, it can be optimised, but should not be done in this patch. This patch is big enough as it is. Added a TODO comment to it.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 117 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-Kmev64yj8qjyCGD0zSv:-Kmf8biwmUGdzmjSY8Oi:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L117)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Confusing method made in sake of optimization, the same case as doCollapse/doExpand
</blockquote></details>

Removed

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 151 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmevlGxzntZwdmywMWz:-Kmf7sWm3ySiekH0aAKZ:bko705l) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L151)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Confusing method made in sake of optimization, the same case as doCollapse/doExpand
</blockquote></details>

The only way to access this class is to instantiate it yourself or access a private method of hierarchical data communicator. Not an API facing an app developer. Changed similarly any way.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 171 at r2](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmevqmzTt5uIbZ9TT99:-Kmf87O4KcIemdn4bWtm:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/0e85432cf60dfa9da9f9b0271a2cbbf436ef903e/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L171)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Confusing method made in sake of optimization, the same case as doCollapse/doExpand
</blockquote></details>

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 376 at r4](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmfEJADDbM_WR5JR7qO:-KmfEJADDbM_WR5JR7qP:b-n10vfv) ([raw file](https://github.com/vaadin/framework/blob/4e9d18135aaa8cb9171be0478b2d99c67becaeeb/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L376)):*
> ```Java
>      *            the item id
>      */
>     private void removeChildren(Object id) {
> ```

This method can be simplified, optimized and implemented without recursion, based on pool of items to be removed. Array-based LIFO structure is most optimal for that, I think. 
Nevertheless I don't think this is a blocker, because I don't think this method is gonna be called too often.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 406 at r4](https://reviewable.io:443/reviews/vaadin/framework/9496#-KmfFEjqifSmIEnZFTrl:-KmfFEjqifSmIEnZFTrm:b-litzy5) ([raw file](https://github.com/vaadin/framework/blob/4e9d18135aaa8cb9171be0478b2d99c67becaeeb/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L406)):*
> ```Java
>         }
> 
>         final List<Object> collect = getHierarchy(null).map(provider::getId)
> ```

Building of the full list of IDs is not the most effective way to do this. NaB.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9496)*

**Pull request merged**
