### PR TITLE
Send view width as width and not height

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8984)

### CODE REVIEW

**Comment by elmot** [comment]
Is that fix for something? Is there any test broken?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8984#-:-KgtQ4bOpsAIKeh_OT55:bqgdoi9)*

**Comment by elmot** [comment]
I have started a full uitest run against this PR. Let's see what happens.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8984#-:-KgtQMY5v0__9JhRm78g:blzdbo4)*

**Comment by Artur-** [comment]
In the end this fixes nothing it seems, as the values are not used in https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/UI.java#L178

If somebody overrides the Rpc or starts using the value in the future they will be correct though

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8984#-:-KguP5LGQJTEr7ZcvJNj:b-e71l5)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8984#-:-Kh1obimYJPYqikJ7j_z:bnfp4nl)*

**Pull request merged**
