### PR TITLE
AbstractDateField.formatDate() to be abstract

### PR DESCRIPTION
**Pull request by asashour**
Remove invalidDateString paramter, as it can be deduced

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10186)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 5 of 10 files at r1, 1 of 1 files at r2, 5 of 8 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 269 at r4](https://reviewable.io:443/reviews/vaadin/framework/10186#-Kw_QCyq6y7HS2m9TsCw:-Kw_QCyq6y7HS2m9TsCx:bn8e7z1) ([raw file](https://github.com/vaadin/framework/blob/855669f457185fec3c748b2cb30595af63cdd03a/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L269)):*
> ```Java
>      * @since
>      */
>     protected void updateBufferedResolutions() {
> ```

kind of a change to a semi-public API, might be worth of notice in release notes.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java, line 57 at r4](https://reviewable.io:443/reviews/vaadin/framework/10186#-Kw_S5JtRBUk1AGJbw1H:-Kw_S5JtRBUk1AGJbw1I:b-12k0am) ([raw file](https://github.com/vaadin/framework/blob/f42e0cc6f2c8623d3acb0033222cd6360e5f521a/client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java#L57)):*
> ```Java
>         R resolution = widget.getCurrentResolution();
>         return resolutions.collect(Collectors.toMap(Function.identity(),
>                 res -> res == null ? null
> ```

The `res` can't be null anymore with the changes in this patch? Or was it already changed earlier?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 269 at r4](https://reviewable.io:443/reviews/vaadin/framework/10186#-Kw_QCyq6y7HS2m9TsCw:-Kw_bn_CY0EBlqud_rDZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/855669f457185fec3c748b2cb30595af63cdd03a/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L269)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

kind of a change to a semi-public API, might be worth of notice in release notes.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java, line 57 at r4](https://reviewable.io:443/reviews/vaadin/framework/10186#-Kw_S5JtRBUk1AGJbw1H:-Kw_apQ2zt4XhB8VVfjL:b2zzsc4) ([raw file](https://github.com/vaadin/framework/blob/f42e0cc6f2c8623d3acb0033222cd6360e5f521a/client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java#L57)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The `res` can't be null anymore with the changes in this patch? Or was it already changed earlier?
</blockquote></details>

Actually, it wasn't change by this patch. The reason is `VDateField.getResolutions()`, returns stream of `doGetResolutions()`, which doesn't return `null` values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10186#-Kw_loS1vq22bDspLWU_:-Kw_loS1vq22bDspLWUa:b-fyq7th) (no related file):*
Need to go through this change again with another pair of eyes in case I missed something (quite a few changes in the same patch). Will do so tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by torok-peter** [comment]
Reviewed 5 of 10 files at r1, 1 of 1 files at r2, 4 of 8 files at r3, 5 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 256 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweX8wvbf6AGs5KtzHH:-KweX8wvbf6AGs5KtzHI:b2dj5mh) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L256)):*
> ```Java
>         bufferedDateString = text.getText();
>         updateBufferedResolutions();
>         sendBufferedValues();
> ```

Now `sendBufferedValues()` must be called explicitly every time after `updateBufferedResolutions()`; if it is forgotten somewhere in a future call, we have a bug. Moreover, if anyone has overridden the original `updateDateVariables()` in a fork, this breaks their code. And even after they figure out that they must rename their overridden method, if they call `sendBufferedValues()` from it, they have a bug too.

A nicer solution is suggested: extract these two calls into a `protected final` template method `updateDateVariables()` to ensure that
* both are called always, in the correct order, as well as
* Javadoc is added to explain the change and alert anyone who might have overridden the original `updateDateVariables()` that they should rename their override too as well as remove any call to `sendBufferedValues()` from it.

Please also update the release notes accordingly.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 260 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweDFj3_Hu7oY5xl9Lw:-KweDFj3_Hu7oY5xl9Lx:b-m87i05) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L260)):*
> ```Java
> 
>     /**
>      * Updates {@link #updateBufferedResolutions()} to send a response to the
> ```

Javadoc refers to this method itself

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 435 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweEyvHCbexFEkouOY5:-KweEyvHCbexFEkouOY6:b-4cmrel) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L435)):*
> ```Java
>         } else {
>             date = getIsoFormatter().parse(isoDate);
>         }
> ```

Could be further simplified as
```
         Date date = null;
         if (isoDate != null) {
             date = getIsoFormatter().parse(isoDate);
         }
```


---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 438 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KwefiNKKXd4jRMMNnXl:-KwefiNKKXd4jRMMNnXm:bz4nnl7) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L438)):*
> ```Java
>         setDate(date);
>         updateBufferedResolutions();
>         sendBufferedValues();
> ```

Replace with call to the new `updateDateVariables()` as above

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 70 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweP0o87KCs21tZgknb:-KweP0o87KCs21tZgknc:b-od52d8) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VDateField.java#L70)):*
> ```Java
>      * to the server through {@link #sendBufferedValues()}.
>      * 
>      * The key is the resolution name e.g. "HOUR", "MINUTE".
> ```

Update Javadoc

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 76 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweG1bUufufuHoR5NJb:-KweG1bUufufuHoR5NJc:b-82ll2w) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VDateField.java#L76)):*
> ```Java
>      * @since
>      */
>     protected Map<Enum<?>, Integer> bufferedResolutions = new HashMap<>();
> ```

Use `R` as the key type

---

*[client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java, line 129 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweSMi2u-Fw8AhxTauh:-KweSMi2u-Fw8AhxTaui:bofhy4h) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java#L129)):*
> ```Java
>             if (resolution.compareTo(SECOND) <= 0) {
>                 bufferedResolutions.put(SECOND, currentDate.getSeconds());
>             }
> ```

This code only sets resolutions if the current date is not null. The old code also cleared resolutions if the date was null. Would that make any observable difference?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by asashour** [comment]
Review status: 14 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 256 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweX8wvbf6AGs5KtzHH:-KwiEhe8UkFTTbsx-S49:b-75htfa) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L256)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Now `sendBufferedValues()` must be called explicitly every time after `updateBufferedResolutions()`; if it is forgotten somewhere in a future call, we have a bug. Moreover, if anyone has overridden the original `updateDateVariables()` in a fork, this breaks their code. And even after they figure out that they must rename their overridden method, if they call `sendBufferedValues()` from it, they have a bug too.

A nicer solution is suggested: extract these two calls into a `protected final` template method `updateDateVariables()` to ensure that
* both are called always, in the correct order, as well as
* Javadoc is added to explain the change and alert anyone who might have overridden the original `updateDateVariables()` that they should rename their override too as well as remove any call to `sendBufferedValues()` from it.

Please also update the release notes accordingly.

</blockquote></details>

I am with you that the changes are not backward compatible, and that's why `updateDateVariables()` was removed.

This change comes after the previous [AbstractDateField not to be a LegacyComponent](https://github.com/vaadin/framework/commit/dd5597d9014032cc366d4b70405e007b1876c350), in which `getClient().updateVariable` was used, but it is the old way to communicate parameters.

I made a new commit that does what you suggest, but having `updateAndSendBufferedValues()`.

The release note already has:
`VAbstractTextualDate`.`updateDateVariables()` is now `updateBufferedResolutions()`.

Should I add something else?

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 260 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweDFj3_Hu7oY5xl9Lw:-KwiGTbDQz9fV3YlFfc1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L260)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Javadoc refers to this method itself
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 435 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweEyvHCbexFEkouOY5:-KwiGdTmPKgbJ7gFQJKc:b-lswts0) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L435)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could be further simplified as
```
         Date date = null;
         if (isoDate != null) {
             date = getIsoFormatter().parse(isoDate);
         }

</blockquote></details>

Done. Noting that now, setting can happen twice, but readability is a factor as well.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 438 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KwefiNKKXd4jRMMNnXl:-KwiGwextQYW99-90_Fs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L438)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Replace with call to the new `updateDateVariables()` as above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 70 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweP0o87KCs21tZgknb:-KwiH8usLuasZ30qearx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VDateField.java#L70)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Update Javadoc
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 76 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweG1bUufufuHoR5NJb:-KwiH8fjjXrkM3h9HBmN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VDateField.java#L76)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Use `R` as the key type
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java, line 129 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweSMi2u-Fw8AhxTauh:-KwiHSw8vncFwCqYki_1:bn286n6) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java#L129)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This code only sets resolutions if the current date is not null. The old code also cleared resolutions if the date was null. Would that make any observable difference?
</blockquote></details>

I believe it doesn't matter, because at the server side, we get all resolutions, and check if have a value or `null`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*
<!-- Sent from Reviewable.io -->

**Comment by torok-peter** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 256 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweX8wvbf6AGs5KtzHH:-Kwic18JUUj012Ck8onc:b-9p4p1w) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L256)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I am with you that the changes are not backward compatible, and that's why `updateDateVariables()` was removed.

This change comes after the previous [AbstractDateField not to be a LegacyComponent](https://github.com/vaadin/framework/commit/dd5597d9014032cc366d4b70405e007b1876c350), in which `getClient().updateVariable` was used, but it is the old way to communicate parameters.

I made a new commit that does what you suggest, but having `updateAndSendBufferedValues()`.

The release note already has:
`VAbstractTextualDate`.`updateDateVariables()` is now `updateBufferedResolutions()`.

Should I add something else?


</blockquote></details>

Need to discuss naming with @teemusa

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 255 at r6](https://reviewable.io:443/reviews/vaadin/framework/10186#-KwibjnhAFtGTW9LrWK2:-KwibjnhAFtGTW9LrWK3:bb0kyxi) ([raw file](https://github.com/vaadin/framework/blob/827191ab90a3830baeb14c31c6bc3c779fe56454/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L255)):*
> ```Java
>         // always send the date string
>         bufferedDateString = text.getText();
>     }
> ```

Missing a call to `updateAndSendBufferedValues()` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by asashour** [comment]
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 255 at r6](https://reviewable.io:443/reviews/vaadin/framework/10186#-KwibjnhAFtGTW9LrWK2:-KwifyTLg-zBOWXgL27-:buketii) ([raw file](https://github.com/vaadin/framework/blob/827191ab90a3830baeb14c31c6bc3c779fe56454/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L255)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Missing a call to `updateAndSendBufferedValues()` here?
</blockquote></details>

Indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by tsuoanttila** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 256 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweX8wvbf6AGs5KtzHH:-KwslmSHWdp61a14_PPz:b9r4du5) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L256)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Need to discuss naming with @teemusa
</blockquote></details>

if it is not possible to recreate the functionality of the old `updateDateVariables`, then it needs to be removed. Is the `release-notes.html` still referring to the correct method name? If yes, then I'd consider this discussion resolved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by asashour** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 256 at r5](https://reviewable.io:443/reviews/vaadin/framework/10186#-KweX8wvbf6AGs5KtzHH:-KwsobLGT0Jd6hbILuhU:b-wujxgb) ([raw file](https://github.com/vaadin/framework/blob/4d88f8d8ac5eab16bcc8aa61969db95f41c41ec5/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L256)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

if it is not possible to recreate the functionality of the old `updateDateVariables`, then it needs to be removed. Is the `release-notes.html` still referring to the correct method name? If yes, then I'd consider this discussion resolved.
</blockquote></details>

Release note had the correct name, but mention of the second newly introduced method is now added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Comment by torok-peter** [comment]
Reviewed 1 of 3 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10186)*

**Pull request merged**
