### PR TITLE
Add API for running BindingValidationStatusHandlers

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch adds an API to Binding for accessing the validation status handlers as well as a helper APIs to BinderValidationStatus.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9966)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 986 at r1](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtoiywenJNBvekshLJw:-KtoiywenJNBvekshLJx:b-86sb9l) ([raw file](https://github.com/vaadin/framework/blob/3af1c573a73717e46717d0600b26b66d044e4193/server/src/main/java/com/vaadin/data/Binder.java#L986)):*
> ```Java
> 
>         private void notifyStatusHandler(BindingValidationStatus<?> status) {
>             statusHandler.statusChange(status);
> ```

Why doesn't this use getValidationStatusHandler()? Are there other locations that don't use it?

---

*[server/src/main/java/com/vaadin/data/BinderValidationStatus.java, line 195 at r1](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtogPUASM7Jk9U-v6fD:-KtogPUASM7Jk9U-v6fE:bpu84om) ([raw file](https://github.com/vaadin/framework/blob/3af1c573a73717e46717d0600b26b66d044e4193/server/src/main/java/com/vaadin/data/BinderValidationStatus.java#L195)):*
> ```Java
> 
>     /**
>      * Notifies resolved validation statuses to handlers in bindings.
> ```

could document the filter used, and why

---

*[server/src/main/java/com/vaadin/data/BinderValidationStatusHandler.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9966#-Ktog5Dxye7r0i4huRGa:-Ktog5Dxye7r0i4huRGb:b5yb4tn) ([raw file](https://github.com/vaadin/framework/blob/3af1c573a73717e46717d0600b26b66d044e4193/server/src/main/java/com/vaadin/data/BinderValidationStatusHandler.java#L25)):*
> ```Java
>  * <p>
>  * {@link Binder#setValidationStatusHandler(BinderValidationStatusHandler)
>  * Register} an instance of this class to be able to customize validation status
> ```

(unnecessary changes to this file - not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 133 at r2](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtpgaR0IGX2wvS9wZ17:-KtpgaR0IGX2wvS9wZ18:b-5tma9b) ([raw file](https://github.com/vaadin/framework/blob/a244ce6801cede9ffadfdea149f11aae9bd34f3e/server/src/main/java/com/vaadin/data/Binder.java#L133)):*
> ```Java
>          * 
>          * @return the validation status handler for this binding
>          */
> ```

since tags for all the new methods

---

*[server/src/main/java/com/vaadin/data/BinderValidationStatus.java, line 196 at r2](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtpglLOMAKaQny9yiS9:-KtpglLOMAKaQny9yiSA:bhcssov) ([raw file](https://github.com/vaadin/framework/blob/a244ce6801cede9ffadfdea149f11aae9bd34f3e/server/src/main/java/com/vaadin/data/BinderValidationStatus.java#L196)):*
> ```Java
>      * Notifies all validation status handlers in bindings.
>      * 
>      * @see #notifyBindingValidationStatusHandlers(SerializablePredicate)
> ```

since tags for new methods

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 133 at r2](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtpgaR0IGX2wvS9wZ17:-Ktzz9bYfTVERl9oDUrz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a244ce6801cede9ffadfdea149f11aae9bd34f3e/server/src/main/java/com/vaadin/data/Binder.java#L133)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tags for all the new methods
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BinderValidationStatus.java, line 196 at r2](https://reviewable.io:443/reviews/vaadin/framework/9966#-KtpglLOMAKaQny9yiS9:-KtzzDBB520Vufao28Ox:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a244ce6801cede9ffadfdea149f11aae9bd34f3e/server/src/main/java/com/vaadin/data/BinderValidationStatus.java#L196)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tags for new methods
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9966#-:-KuOEAcdJogSeUYrkSob:bnfp4nl)*

**Pull request merged**
