### PR TITLE
For each enhancement

### PR DESCRIPTION
**Pull request by asashour**
Also, on iterating a `Map`, it is better to iterate with Map.Entry, so no extra search is done for the `value`.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10018)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 16 of 19 files at r1.
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 4403 at r1](https://reviewable.io:443/reviews/vaadin/framework/10018#-KuNfb-8SpPrW1A2Ocsd:-KuNfb-8SpPrW1A2Ocse:b-wufuvl) ([raw file](https://github.com/vaadin/framework/blob/7f1056903836f86bfb7d997580a01f9c7b2687fa/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L4403)):*
> ```Java
>                 if (columnIndex < 0) {
>                     columnIndex = 0;
>                     for (Widget widget : tHead) {
> ```

This fails to increment columnIndex which is used below. (Apparently no test in the validation build caught this, but this can break things.)

---

*[uitest/src/main/java/com/vaadin/tests/TestBench.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/10018#-KuNgOrXK3CSoKlZWwXQ:-KuNgOrXK3CSoKlZWwXR:b18ifk5) ([raw file](https://github.com/vaadin/framework/blob/7f1056903836f86bfb7d997580a01f9c7b2687fa/uitest/src/main/java/com/vaadin/tests/TestBench.java#L114)):*
> ```Java
>         menu = new Tree("Testables", testables);
> 
>         for (final Class<?> testable : itemCaptions) {
> ```

Shouldn't this be itemCaptions.keySet()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10018)*

**Comment by asashour** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 4403 at r1](https://reviewable.io:443/reviews/vaadin/framework/10018#-KuNfb-8SpPrW1A2Ocsd:-KuNnUsBEpStR_ITb3TW:bb7c8sd) ([raw file](https://github.com/vaadin/framework/blob/7f1056903836f86bfb7d997580a01f9c7b2687fa/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L4403)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This fails to increment columnIndex which is used below. (Apparently no test in the validation build caught this, but this can break things.)
</blockquote></details>

My mistake, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10018)*

**Comment by asashour** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/TestBench.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/10018#-KuNgOrXK3CSoKlZWwXQ:-KuNnYjBq3NFBzRXSTgT:be05fkg) ([raw file](https://github.com/vaadin/framework/blob/7f1056903836f86bfb7d997580a01f9c7b2687fa/uitest/src/main/java/com/vaadin/tests/TestBench.java#L114)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Shouldn't this be itemCaptions.keySet()?
</blockquote></details>

`itemCaptions` is changed to Set (in previously second commit) instead of Map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10018)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 19 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10018#-:-KuO46Cz38806O9u5m8_:bnfp4nl)*

**Pull request merged**
