### PR TITLE
Handle UnparsableDateString correctly

### PR DESCRIPTION
**Pull request by anasmi**
Handle UnparsableDateString correctly when the same value entered more than once in DateField

Force update value in the state to reset the previous selected value with rigth presentation in the dateField text field

Resolves : https://github.com/vaadin/framework/issues/10681

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10803)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 124 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p2zWF6UPYuXN3mVNL:-L9p2zWF6UPYuXN3mVNM:b-tzptwf) ([raw file](https://github.com/vaadin/framework/blob/eefc25d19153b80fa8c208e47e8290957bd74c24/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L124)):*
> ```Java
>                                     dateString);
>                             parsedDate.ifOk(v -> {
>                                 if (!setValue(v, true)
> ```

Please comment how does it work

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 124 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p2zWF6UPYuXN3mVNL:-L9rosaZ3wUmEJOaEHVM:b-855xoa) ([raw file](https://github.com/vaadin/framework/blob/eefc25d19153b80fa8c208e47e8290957bd74c24/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L124)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please comment how does it work
</blockquote></details>

You are calling setValue first. If it's executed and value is set it returns true, so loop is not proceed. setValue can also return false. Either cb is readonly or the value is the same is before(which is the case I am trying to resolve). If setValue is false and isDifferentValue is false, then manually saying to force update state, which will call the onStateChange, which is not called otherwise and which we need to update representation on client side in cb.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldUnparsableDateString.java, line 63 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p3_EcB86mtgP9zlwd:-L9s16VCCl3o2HgPlTx1:bq8sqge) ([raw file](https://github.com/vaadin/framework/blob/eefc25d19153b80fa8c208e47e8290957bd74c24/uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldUnparsableDateString.java#L63)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

ddMMyy?
</blockquote></details>

I think year is handled by appendValueReduced and then added to the formatted day + month . Also modifying the original code example (to use ddMMyy) doesn't work. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by anasmi** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldUnparsableDateStringTest.java, line 26 at r6](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p3vhh-OhxwOBj2TQo:-L9s1_xv85tJ63IQ6Yyq:bss4a1b) ([raw file](https://github.com/vaadin/framework/blob/54074e02336c6da3ed3025744a0dff62ac69df72/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldUnparsableDateStringTest.java#L26)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Too long, I think. Even if it's necessary to wait.
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 124 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p2zWF6UPYuXN3mVNL:-L9zKXg0459DWOKKn2eg:b-cnsz19) ([raw file](https://github.com/vaadin/framework/blob/eefc25d19153b80fa8c208e47e8290957bd74c24/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L124)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

You are calling setValue first. If it's executed and value is set it returns true, so loop is not proceed. setValue can also return false. Either cb is readonly or the value is the same is before(which is the case I am trying to resolve). If setValue is false and isDifferentValue is false, then manually saying to force update state, which will call the onStateChange, which is not called otherwise and which we need to update representation on client side in cb.
</blockquote></details>

First of all, I mean comment in the code. The trick should be documented.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 124 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10803#-L9p2zWF6UPYuXN3mVNL:-LABhLxrCBLQDZb2wb-g:b-896fjx) ([raw file](https://github.com/vaadin/framework/blob/eefc25d19153b80fa8c208e47e8290957bd74c24/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L124)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Ups,sorry. will do
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10803)*

**Pull request merged**
