### PR TITLE
Add presentation concept to Grid Columns and Renderers

### LINKED ISSUE #8656: Grid cell value using value-providers
Given the awesome enhancements in FW8 `Grid`, I was surprised to see missing a quite common use case about adding columns:

```java
ComboBox<Group> groupBox = new ComboBox<>();
groupBox.setItemCaptionGenerator(Group::getName);
groupBox.setItems(groups);

Grid<User> grid = new Grid<>();
grid.addColumn(User::getGroup)
// .setValueGenerator(Group::getName) --> this is missing, value will be Group.toString()!
.setEditorComponent(groupBox, User::setGroup);
```

I really hope the next release will support this!

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch changes Grid Columns, so they can be different types in value and presentation. A presentation provider can be given when setting the renderer for a column. This provider takes the value of the column on a row and chooses what to present for this value. Using this approach it is easier to have an editor for the actual backing data instead of the presentation of it.

Fixes #8656

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9553)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
@heruan please take a look at the change. I picked your original change. I did not want to provide yet another minimal interface for the "`ValueConverter`", but re-used the `ValueProvider` for it.

**Comment by heruan** [comment]
@tsuoanttila I agree, I formerly used `ValueProvider` indeed. It looks great!

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 904 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzsx_fiK0eVE1zTu53:-Kmzsx_fiK0eVE1zTu54:b-cn5ht1) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L904)):*
> ```Java
>          *            the presentation renderer, not <code>null</code>
>          * @param <P>
>          *            the presentation type
> ```

@since 8.1, and maybe add back old constructor calling this one with the same value as both providers

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1011 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmztIl0BUz61z-fm5RB:-KmztIl0BUz61z-fm5RC:bl88obb) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1011)):*
> ```Java
> 
>         @SuppressWarnings("unchecked")
>         private <P> JsonValue generateRendererValue(T item,
> ```

Would it make sense for this to be overridable (with javadoc and @since)? I guess that can also be opened later, though.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1903 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmztcPKzW8liD0ChXhS:-KmztcPKzW8liD0ChXhT:b-a3iml6) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1903)):*
> ```Java
>          */
>         public Column<T, V> setRenderer(Renderer<? super V> renderer) {
>             return this;
> ```

doesn't set anything, no warning etc.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1912 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzuOiMEmf6zThGpA9q:-KmzuOiMEmf6zThGpA9r:bjsgvld) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1912)):*
> ```Java
>          *
>          * @param presentationProvider
>          *            the function to get presentations for this column values,
> ```

"this column values" -> "the value of this column"? Also, I think the javadoc could be a bit more explicit about what the presentation provider is and what it maps to what and how not to use a separate one

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2564 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzunmU34XYeMREDo0-:-KmzunmU34XYeMREDo00:bwt7c2a) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2564)):*
> ```Java
>      *            the value provider
>      * @param presentationProvider
>      *            the value presentation provider
> ```

could add info that it maps the value from value provider to a value to pass to the (text) renderer

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2571 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv6imjF6SM1-WjqYY:-Kmzv6imjF6SM1-WjqYZ:bptolne) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2571)):*
> ```Java
>      *
>      * @return the new column
>      */
> ```

@since 8.1

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2585 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzuv_B0YhzGYHlgyL_:-Kmzuv_B0YhzGYHlgyLa:b-qairaf) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2585)):*
> ```Java
>      *            the value provider
>      * @param presentationProvider
>      *            the value presentation provider
> ```

could add info that this maps the value from the value provider to a value to pass to the renderer, and why one might want to use this method

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2596 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv4EfM5jm5I3HFe6v:-Kmzv4EfM5jm5I3HFe6w:bptolne) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2596)):*
> ```Java
>      *
>      * @see AbstractRenderer
>      */
> ```

@since 8.1

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2639 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv9qRgKsnv2icA7As:-Kmzv9qRgKsnv2icA7At:b-alj2x0) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2639)):*
> ```Java
>      *            the column presentation type
>      *
>      * @since 8.0.3
> ```

8.1 now with changed API? Should this have a note that the API has changed, and a mention in release notes (minor breaking change)?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4111 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzvKfxWJlopLsWBOIk:-KmzvKfxWJlopLsWBOIl:b-ygyxev) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L4111)):*
> ```Java
>             } else {
>                 DeclarativeValueProvider<T> provider = new DeclarativeValueProvider<>();
>                 column = createColumn(provider, t -> t, new HtmlRenderer());
> ```

here using t->t, and above ValueProvider.identity() - consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn3VHM9z2Cr6y0PlY9V:-Kn3VHMAISQx-jZG7MYh:b-hbet69) (no related file):*
How is anyone supposed to review this when there isn't a single example of how the new functionality is supposed to be used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by heruan** [comment]
@Legioth see #8656 for an example. The idea is to decouple a column semantic-type from the actual rendered type.

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn3VHM9z2Cr6y0PlY9V:-Kn471Fhv3aKqjVEBjra:bjzw79t) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

How is anyone supposed to review this when there isn't a single example of how the new functionality is supposed to be used?
</blockquote></details>

Adding an example

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 904 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzsx_fiK0eVE1zTu53:-Kn4775sA4HgCahejgUH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L904)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1, and maybe add back old constructor calling this one with the same value as both providers
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1011 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmztIl0BUz61z-fm5RB:-Kn43S__TuoXUPdQy1ke:b-l17p1l) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1011)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Would it make sense for this to be overridable (with javadoc and @since)? I guess that can also be opened later, though.
</blockquote></details>

I'd vote for opening later, since this is already highly customisable by the user through value provider, presentation provider and the renderer.

If the user wants to have even more extra stuff to the client-side, he should use DataGenerator through an extension and not bundle it to the column communication logic.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1903 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmztcPKzW8liD0ChXhS:-Kn41eWLsVTpX1u2XYIa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1903)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

doesn't set anything, no warning etc.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1912 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzuOiMEmf6zThGpA9q:-Kn43jdprjedM0mSXkjK:btasstz) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L1912)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"this column values" -> "the value of this column"? Also, I think the javadoc could be a bit more explicit about what the presentation provider is and what it maps to what and how not to use a separate one
</blockquote></details>

Added a short description of the presentation provider to the javadoc.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2564 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzunmU34XYeMREDo0-:-Kn43q4fYT74bAC7oeau:b4co67v) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2564)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could add info that it maps the value from value provider to a value to pass to the (text) renderer
</blockquote></details>

Forced to String, added link and see to alternative method for non-string renderers.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2571 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv6imjF6SM1-WjqYY:-Kn47CvqaKQF3pARcqSv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2571)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2585 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzuv_B0YhzGYHlgyL_:-Kn44J8T1dBmgwhIurpP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2585)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could add info that this maps the value from the value provider to a value to pass to the renderer, and why one might want to use this method
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2596 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv4EfM5jm5I3HFe6v:-Kn44K2i98vSiTNsVKtt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2596)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2639 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv9qRgKsnv2icA7As:-Kn46o-1sxF5gClGnLLE:b-xdh4b1) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2639)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

8.1 now with changed API? Should this have a note that the API has changed, and a mention in release notes (minor breaking change)?
</blockquote></details>

Needs a release notes mention. if someone has overridden the old one and now suddenly they can no longer use it reliably.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4111 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-KmzvKfxWJlopLsWBOIk:-Kn47-PeivzoKAXGWA82:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L4111)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

here using t->t, and above ValueProvider.identity() - consistency?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2639 at r2](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kmzv9qRgKsnv2icA7As:-Kn4PRhnMNh1cCySbvHf:bd21657) ([raw file](https://github.com/vaadin/framework/blob/7d87c8a725b135dbb3890140d3fdeca90866b2dc/server/src/main/java/com/vaadin/ui/Grid.java#L2639)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Needs a release notes mention. if someone has overridden the old one and now suddenly they can no longer use it reliably.
</blockquote></details>

release notes mention still missing

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 914 at r3](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn4OiMbsh1Gfc5wxL9-:-Kn4OiMbsh1Gfc5wxL90:bv1kjj) ([raw file](https://github.com/vaadin/framework/blob/8fd6ff8393804602998f173bc28299e62f902618/server/src/main/java/com/vaadin/ui/Grid.java#L914)):*
> ```Java
>          *            <code>null</code>
>          * @param presentationProvider
>          *            the function to get presentations for this column values,
> ```

(perhaps this could refer to the more complete documentation in setRenderer())

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn4WvzfixyRwFjqJqN3:-Kn4WvzgjVD7EqfE_jfb:bch0sov) (no related file):*
Overall concept and API: :lgtm:
Test coverage and BoV documentation: :shit:

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java, line 58 at r3](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn4Vy3IfopCcjvRhICK:-Kn4Vy3IfopCcjvRhICL:bz7qf1z) ([raw file](https://github.com/vaadin/framework/blob/8fd6ff8393804602998f173bc28299e62f902618/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java#L58)):*
> ```Java
> 
>         @Override
>         public boolean isReadOnly() {
> ```

Unrelated remark: Should we introduce something similar to the FW7 `CustomField` that would take care of this kind of boilerplate for custom `HasValue` implementations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/screenshots, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/9553#-Knc22mKMIbSWu4Zl-8a:-Knc22mKMIbSWu4Zl-8b:b-30kbhh) ([raw file](https://github.com/vaadin/framework/blob/7a880bf4168c3f99247a6b9a74beeb341c8e6bd8/tests/screenshots#L1)):*
> ```
> Subproject commit 3537feedbe098f6a5efa70e1d8c5eecae5446f29
> ```

not quite the latest revision, so probably should not alter this to avoid merge conflicts (but could use this for running UI tests once)

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java, line 58 at r3](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn4Vy3IfopCcjvRhICK:-Knc1QE7fS6xYe5fuIXN:bgmolv5) ([raw file](https://github.com/vaadin/framework/blob/8fd6ff8393804602998f173bc28299e62f902618/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java#L58)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Unrelated remark: Should we introduce something similar to the FW7 `CustomField` that would take care of this kind of boilerplate for custom `HasValue` implementations?
</blockquote></details>

That could be nice, but not in the context of this PR - please create a ticket.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnPresentationTest.java, line 13 at r5](https://reviewable.io:443/reviews/vaadin/framework/9553#-Knc1Z9WsYTLbr39FSdo:-Knc1Z9WsYTLbr39FSdp:b-srok7e) ([raw file](https://github.com/vaadin/framework/blob/7a880bf4168c3f99247a6b9a74beeb341c8e6bd8/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnPresentationTest.java#L13)):*
> ```Java
> 
> /**
>  * (c) elmot on 24.6.2017.
> ```

should probably use Vaadin copyright message if any explicit here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by elmot** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 914 at r3](https://reviewable.io:443/reviews/vaadin/framework/9553#-Kn4OiMbsh1Gfc5wxL9-:-Knc5L8qHAMainIgndw7:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/8fd6ff8393804602998f173bc28299e62f902618/server/src/main/java/com/vaadin/ui/Grid.java#L914)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(perhaps this could refer to the more complete documentation in setRenderer())
</blockquote></details>

Done

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnPresentationTest.java, line 13 at r5](https://reviewable.io:443/reviews/vaadin/framework/9553#-Knc1Z9WsYTLbr39FSdo:-Knc2t6oMKh6rtm8Kqj0:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/7a880bf4168c3f99247a6b9a74beeb341c8e6bd8/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnPresentationTest.java#L13)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should probably use Vaadin copyright message if any explicit here
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by elmot** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/screenshots, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/9553#-Knc22mKMIbSWu4Zl-8a:-KncAe_jI9GrdSZPFtV-:b-2zvwed) ([raw file](https://github.com/vaadin/framework/blob/7a880bf4168c3f99247a6b9a74beeb341c8e6bd8/tests/screenshots#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not quite the latest revision, so probably should not alter this to avoid merge conflicts (but could use this for running UI tests once)
</blockquote></details>

Rebased on top of latest master

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9553#-:-KndPbyR49GcTuFi8QJk:bnfp4nl)*

**Pull request merged**
