### PR TITLE
Add methods to remove Bindings from Binder

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9932)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This might need documentation update as well.

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2396 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGyOS8jcDTW5oAY4ts:-KtGyOS8jcDTW5oAY4tt:b-5tma9b) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2396)):*
> ```Java
>      * @param field
>      *            the field to remove from bindings
>      */
> ```

since tags for all the new methods

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2398 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGygZtAreKXeT8NhLT:-KtGygZtAreKXeT8NhLU:b-o84qhx) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2398)):*
> ```Java
>      */
>     public void removeBinding(HasValue<?> field) {
>         Objects.requireNonNull(field, "Field can't be null");
> ```

(could avoid contractions like can't here and below)

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2400 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGyVSo1zcZW7D0Lwql:-KtGyVSpPuEeShdp1j9Y:bm2rlts) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2400)):*
> ```Java
>         Objects.requireNonNull(field, "Field can't be null");
>         bindings.stream().filter(binding -> field.equals(binding.getField()))
>                 .findFirst().ifPresent(this::removeBinding);
> ```

Can there be multiple bindings for a HasValue? If so, could do forEach() instead.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2412 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGywDi9_0heG1xl5V2:-KtGywDi9_0heG1xl5V3:bauumkt) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2412)):*
> ```Java
>         Objects.requireNonNull(binding, "Binding can't be null");
>         if (bindings.remove(binding)) {
>             boundProperties.entrySet().stream()
> ```

or boundProperties.entrySet().removeIf(entry -> entry.getValue().equals(binding))
(should not be significantly slower unless a huge number of bindings is used)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9932)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2396 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGyOS8jcDTW5oAY4ts:-KtH2LNx1j031pnoXlEP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2396)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tags for all the new methods
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2398 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGygZtAreKXeT8NhLT:-KtH2MJbL89j4PB51UxF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2398)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could avoid contractions like can't here and below)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2400 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGyVSo1zcZW7D0Lwql:-KtH2N9ZY-ep9jW_L8Ys:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2400)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Can there be multiple bindings for a HasValue? If so, could do forEach() instead.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2412 at r1](https://reviewable.io:443/reviews/vaadin/framework/9932#-KtGywDi9_0heG1xl5V2:-KtH2Pf_Tuxoo8OQeOBx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/022206b9663afb0c83bfdb8a5575c3fc9edf156f/server/src/main/java/com/vaadin/data/Binder.java#L2412)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

or boundProperties.entrySet().removeIf(entry -> entry.getValue().equals(binding))
(should not be significantly slower unless a huge number of bindings is used)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9932)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9932)*

**Comment by knoobie** [comment]
Thank you so much for the pr! I hope we see this feature in the upcoming release.

**Comment by pwilkin** [comment]
This looks potentially dangerous. You're removing the binding, but not the respective registration for the value change listener nor the `Binder` within the `Binding` - I can imagine that this can yield very confusing behavior since the following sequence:

```
bind field A to bean B's property X via binder C
unbind field A from binder C
set value to field A
```

will still (as far as I read the code) call the X property's setter on bean B (since `getBinder()` for the `Binding` still returns the binder from which the binding was reportedly removed). It looks like this:

```
public void removeBinding(Binding<BEAN, ?> binding) {
```

is missing a `binding.unbind()`, which would remove the `Binder` association and remove the `Registration`.

**Pull request merged**
