### PR TITLE
Add properties for XVFB cluster testing

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[uitest/eclipse-run-selected-test.properties, line 10 at r1](https://reviewable.io/reviews/vaadin/framework/10863#-LBUsVQFCUx5jTjP7I6B:-LBUsVQFCUx5jTjP7I6C:b-88p0ad) ([raw file](https://github.com/vaadin/framework/blob/1c2f99d2ecf68f3a1a2a87438eda648a1b8455f1/uitest/eclipse-run-selected-test.properties#L10)):*
> ```INI
> ;
> ; For both TestBench 2 and 4
> ;
> ```

Here is a small mistake in the file. Actual line comment symbol in .properties file is `#` but we use weird semicolon. Since you are touching the file, can you fix that also?

---

*[uitest/src/test/java/com/vaadin/tests/tb3/PrivateTB3Configuration.java, line 74 at r1](https://reviewable.io/reviews/vaadin/framework/10863#-LBUtHr985y9y62YsqQy:-LBUtHr985y9y62YsqQz:b-tqu9uv) ([raw file](https://github.com/vaadin/framework/blob/df03e84fe6b0bf8ea5e892e116d19fea17deca96/uitest/src/test/java/com/vaadin/tests/tb3/PrivateTB3Configuration.java#L74)):*
> ```Java
>                     properties.getProperty(PHANTOMJS_PATH));
>         }
>         if (properties.containsKey(BROWSER_FACTORY)) {
> ```

DRY principle is badly broken here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[uitest/eclipse-run-selected-test.properties, line 30 at r2](https://reviewable.io/reviews/vaadin/framework/10863#-LBbABc9CzxHK3tM1Pvy:-LBbABc9CzxHK3tM1Pvz:baaetws) ([raw file](https://github.com/vaadin/framework/blob/9ede720dc9f72914282cefd9f39556997936bb55/uitest/eclipse-run-selected-test.properties#L30)):*
> ```INI
> #
> # Running local instance of XVFB testing cluster. Uncomment all lines below. 
> # Fill in the full path for uitest folder and remember to comment out the other screenshot folder.
> ```

Paths need a note about windows \\

---

*[uitest/eclipse-run-selected-test.properties, line 34 at r2](https://reviewable.io/reviews/vaadin/framework/10863#-LBbA964EQ2lXxGxT6Z0:-LBbA964EQ2lXxGxT6Z1:bidcdq2) ([raw file](https://github.com/vaadin/framework/blob/9ede720dc9f72914282cefd9f39556997936bb55/uitest/eclipse-run-selected-test.properties#L34)):*
> ```
> Reference
> ```
Should be Error

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10863#-:-LBfHs9UDKK1KtjUHJHx:bnfp4nl)*

**Pull request merged**
