### PR TITLE
Unlock and refactor some API to create a new ContextMenu

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)

### CODE REVIEW

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: all files reviewed, 2 unresolved discussions (waiting on @elmot and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 239 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83TEqBFrVmAryIk6p:-LH83TErE3lnb9eiaoAw:bzd4lpm) ([raw file](https://github.com/vaadin/framework/blob/78b9e10f3210669bf6df7572aec5fe8c08762264/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L239)):*
> ```Java
>      * For internal use only. May be removed or replaced in the future.
>      *
>      * @param separator
> ```

missing explanations for params.
___
*[client/src/main/java/com/vaadin/client/ui/VOverlay.java, line 75 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83elZ7a2hNkQ2j7sF:-LH83elZ7a2hNkQ2j7sG:b-kg7abc) ([raw file](https://github.com/vaadin/framework/blob/ceb9593f5d08814dd0dfe4d83030fc403078b5cd/client/src/main/java/com/vaadin/client/ui/VOverlay.java#L75)):*
> ```Java
>      * TODO this is a strange pattern that we should get rid of when possible.
>      */
>     protected static VOverlay current;
> ```

This is no longer used in the FW ?

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: all files reviewed, 2 unresolved discussions (waiting on @elmot and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/ui/VOverlay.java, line 75 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83elZ7a2hNkQ2j7sF:-LH86uZj7hg8_5-Cryb7:b-n6cevw) ([raw file](https://github.com/vaadin/framework/blob/ceb9593f5d08814dd0dfe4d83030fc403078b5cd/client/src/main/java/com/vaadin/client/ui/VOverlay.java#L75)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This is no longer used in the FW ?
</blockquote></details>

Looks like it was copy-paste mistake from Overlay.java (the field overlaps one from it). I do not see any usages of it.

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @tsuoanttila and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 239 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83TEqBFrVmAryIk6p:-LH87z8mCre2cGyhAHa_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/78b9e10f3210669bf6df7572aec5fe8c08762264/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L239)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

missing explanations for params.
</blockquote></details>

Done.

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 239 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83TEqBFrVmAryIk6p:-LH8ELyzDosEAopzzyvB:b9goa75) ([raw file](https://github.com/vaadin/framework/blob/78b9e10f3210669bf6df7572aec5fe8c08762264/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L239)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Formatting seems off, did you run the formatting plugin ?

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 239 at r1](https://reviewable.io/reviews/vaadin/framework/11041#-LH83TEqBFrVmAryIk6p:-LH8IrrU83OtKiXAsLqg:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/78b9e10f3210669bf6df7572aec5fe8c08762264/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L239)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Formatting seems off, did you run the formatting plugin ?
</blockquote></details>

Done

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mehdi-vaadin)

**Pull request merged**
