### PR TITLE
Make some of dnd's javadoc clearer according to Artur's feedback

### PR DESCRIPTION
**Pull request by wbadam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9146)

### CODE REVIEW

**Comment by hesara** [comment]
Please rebase the changes to fix the validation issue

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/9146#-KicxPBLwYRbcGKD_dcY:-KicxPBLwYRbcGKD_dcZ:b-13jau5) ([raw file](https://github.com/vaadin/framework/blob/cef15bbcf9e3626e15827d6f01129361da6789b6/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L53)):*
> ```Java
>      * action, that is the dropEffect value of the last dragenter or dragover
>      * event. The value depends on the drag source's effectAllowed parameter,
>      * the drop target's dropEffect parameter, and it's drag over and drop
> ```

its, and prefer of-genitive in documentation when not talking about persons (I'll make these changes directly in GH if I have the permission)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9146)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/9146#-KicxPBLwYRbcGKD_dcY:-Kicy552uC9Hsf_9q4su:b-17koc2) ([raw file](https://github.com/vaadin/framework/blob/cef15bbcf9e3626e15827d6f01129361da6789b6/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L53)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

its, and prefer of-genitive in documentation when not talking about persons (I'll make these changes directly in GH if I have the permission)
</blockquote></details>

apparently, the "allow project maintainers to make edits" is not enabled for this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9146)*

**Comment by wbadam** [comment]
Thanks, did the rebase

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/9146#-KicxPBLwYRbcGKD_dcY:-Kid-a_1XzdfqBgWoXv5:bcyfzbr) ([raw file](https://github.com/vaadin/framework/blob/cef15bbcf9e3626e15827d6f01129361da6789b6/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L53)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

apparently, the "allow project maintainers to make edits" is not enabled for this PR
</blockquote></details>

Ticked the allow edit box, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9146#-:-Kid-ZV6Itu9g5Xl6I78:bkl5a0m)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9146)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9146#-:-Kij3NAiMNqI3Nl52vig:bnfp4nl)*

**Pull request merged**
