### PR TITLE
add API to enable assistive device only text for grid - fixes 10561

### LINKED ISSUE #10561: grid checkbox label for assistive label / accessibility should be opt-in from grid
To improve grid performance it would be better to disable the accessibility text "Selects row number <x>." instead of just moving them 2000 pixels out of sight if you do not need the assitive text. Also copy and pasting areas from the grid would contain the otherwise not visible (English) assistive text.

*Background*
To have nice CSS styled checkboxes we use the CSS before/after pseudo elements that the Vaadin uses also for normal checkboxes in the valo theme.
The temp fix for the accessibility label needed for screenreaders introduced with #10223 in the Vaadin grid in V.8.1.7 / V.8.2.x also breaks custom styled checkboxes that are contained in the same label.

*Problem and Workaround*
Also the checkboxes are moved outside the view area and need to be corrected by adding back the missing 2000 pixels on x and y axis.

*Suggestion*
Add a server-side option to enable the accessibility option on the grid which might improve rendering performance.

*Additional remarks*
Also as knoobie mentioned in #10223 i18n is missing

### PR DESCRIPTION
**Pull request by knoobie**
If you find a better name, please let me know. fixes #10561

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10567)

### CODE REVIEW

**Comment by knoobie** [comment]
Can somebody with testbench experience look at the tests? I kinda have no idea what fails here. My little sampler project with the same code works fine local.

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L4H6axzWYbHfNID8Ho9:b2ty32p) (no related file):*
Some thoughts about the patch:
 - Manipulations with style names  almost do not make sense, nowadays browsers work with extra styles pretty efficiently.
 - the patch affects a lot of stuff having very application-specific functionality, the patch requires extensive manual testing etc. In the same time, all of that might be done at the application level by subclassing Grid and couple of it's components.
 - The patch only disables accessibility stuff, and I'd prefer a patch which makes another thing in the same time - i18n of those aria labels, and some kind of API for it. But that requires some API design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by knoobie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L4HBHGhah3_QwIsbFsy:be51uyv) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Some thoughts about the patch:
 - Manipulations with style names  almost do not make sense, nowadays browsers work with extra styles pretty efficiently.
 - the patch affects a lot of stuff having very application-specific functionality, the patch requires extensive manual testing etc. In the same time, all of that might be done at the application level by subclassing Grid and couple of it's components.
 - The patch only disables accessibility stuff, and I'd prefer a patch which makes another thing in the same time - i18n of those aria labels, and some kind of API for it. But that requires some API design.

</blockquote></details>

The only point of this patch is to disable the accessibility stuff by default. That's the default case of Vaadin in 7.x til 8.1.6. The accessibility feature was added by me in October 2017 and published in 8.1.7 as minor addition because we thought it won't hurt anybody. So this is just a regression pull request to ensure that 99% of the user base won't have to deal with it and the 1% that is really concernd about accessibility and not so much about styling can use this API to enable it. 

Adding a aria-label instead of adding the text in the label is a bad idea for screenreader - see my initial comments in #10223 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by knoobie** [comment]
At failing test, even after reworking it: Could it be possible that phantomjs can't find the text of the label because it's not "visible" (Because of the css)?

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L4jb4glDrYIWnB7JjrQ:b-pbjxli) (no related file):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

The only point of this patch is to disable the accessibility stuff by default. That's the default case of Vaadin in 7.x til 8.1.6. The accessibility feature was added by me in October 2017 and published in 8.1.7 as minor addition because we thought it won't hurt anybody. So this is just a regression pull request to ensure that 99% of the user base won't have to deal with it and the 1% that is really concernd about accessibility and not so much about styling can use this API to enable it. 

Adding a aria-label instead of adding the text in the label is a bad idea for screenreader - see my initial comments in #10223 
</blockquote></details>

Ok, I mean i18n for "assistive labels"  in general, not necessarily arila-label. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by knoobie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L4kGL9Nf3H7vqwNqitS:bswitb5) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Ok, I mean i18n for "assistive labels"  in general, not necessarily arila-label. 
</blockquote></details>

Sure let me know if you have something in mind.  I think most of the user would like to have something like setAssistiveMultiselectCheckboxLabel(SerializableFunction<T, String> method) - where T is Grid<T>. But I have no idea how to integrate this properly in the client side of Grid, sorry.  For the "select all" checkbox would it be way simpler "setAssistiveMultiselectSelectAllCheckBoxLabel(String name)" - long name.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L58GT_FVz-07QrqKuq4:b-5n8o9w) (no related file):*
Sorry for some delay.
 - Just a generic idea - do we add accessibility features on per component basis or do we implement some generic facility for it? (most probably per component but I have to ask)
- What are other parts of the Grid/Treegrid/Tree to be enriched with those labels? Any common API for it? For instance, how do we add the accessibility to Tree node expand element? any labels or aria-labels there?

>setAssistiveMultiselectCheckboxLabel(SerializableFunction<T, String> method)

I'd prefer something like `setRowSelectAssistiveLabelProvider(SerializableBiFunction<Integer,T, String> method)` 
A little bit shorter, more informative and follows other name conventions. First parameter is a row number (zero based, taking sorting into account). With this parameter a developer can generate either 'Row 1 select', 'First row select', 'John Smith row select'.

How to implement: most probably we need to add another `DataGenerator` which composes the label at server side and then adds that to row data json object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by knoobie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L58bkUsmCA6IU9--tIn:byd48d8) (no related file):*
> - Just a generic idea - do we add accessibility features on per component basis or do we implement some generic facility for it? (most probably per component but I have to ask)

That's a wonderful generic idea. Sounds good on paper! The problem is that every component needs his own kind of API  on different "sub"-components. For Example Grid needs it for rows, checkboxes etc. and the DateField for the Popup. 

> - What are other parts of the Grid/Treegrid/Tree to be enriched with those labels? Any common API for it? For instance, how do we add the accessibility to Tree node expand element? any labels or aria-labels there?

That's a huge question you are asking here! Currently I would only add this to the checkboxes otherwise sightless users can't tell what to do with them. A checkbox without a label can mean anything. 

Anything else depends on how much time you want to invest in a "legacy" component. Your new Vaadin Grid does a really good job to address most of the accessibility concerns I had.  So it would be more future-proof to look for an enrichment of the Grid API that could be used for Vaadin Grid as well to minimize the effort for developer migrate from 8 to 10.  Anything we add here should be part of 10 as well or should have a replacement. 

> I'd prefer something like setRowSelectAssistiveLabelProvider(SerializableBiFunction<Integer,T, String> method)

I would prefer the same. Sounds reasonable! I forgot about the BiFunction here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L5OfJZuLAEQBpSihsmI:b-ia5fk5) (no related file):*
> Anything we add here should be part of 10 as well or should have a replacement.

File tickets to Vaadin Grid repo about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by knoobie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L5PcDi49XXdi68V5Z0W:bri7o1i) (no related file):*
> File tickets to Vaadin Grid repo about that.

Okay, should be done after we are finished here and the changes are merged. 

I was trying to implement your mentioned DataGenerator and the methods needed - beginning with the server side of Grid. Currently DataGenerator only allows Function of T, so there is no way to add a BiFunction of T, Integer in it. Thats kinda problematic for this usecase, or? I followed the way how DescriptionGenerator is implemented. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567)*

**Comment by elmot** [comment]
@knoobie, you may skip PhantomJS tests. We are seriously thinking of throwing it away.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L5TME1vCYEgCOsJs0jC:b-mzyodq) (no related file):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

> File tickets to Vaadin Grid repo about that.

Okay, should be done after we are finished here and the changes are merged. 

I was trying to implement your mentioned DataGenerator and the methods needed - beginning with the server side of Grid. Currently DataGenerator only allows Function of T, so there is no way to add a BiFunction of T, Integer in it. Thats kinda problematic for this usecase, or? I followed the way how DescriptionGenerator is implemented. 
</blockquote></details>

Yeah, it might be problematic to find both object and _proper_ index. You may push your existing changes, I will try to find a way to help you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567#-:-L5TLx6eO4sQV_E3kwd7:b-un9ym7)*

**Comment by knoobie** [comment]
Removed execution of UI Tests

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10567#-L4H6axzWYbHfNID8Ho8:-L5TRT4g5ib5I2dBOuyu:b-uzzls8) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Yeah, it might be problematic to find both object and _proper_ index. You may push your existing changes, I will try to find a way to help you.
</blockquote></details>

Thanks for the help! Added my current draft for you. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10567#-:-L5TRMBs2qe4HjNwX4M_:b2aotld)*

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
Tests for testing`RowSelectAssistiveLabelGenerator` should also be added.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10567#-:-LLe84RGD_FaXUnA9ZRe:b-qu0vic)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @elmot, @knoobie, and @mehdi-vaadin)

___
*[client/src/main/java/com/vaadin/client/widget/grid/selection/MultiSelectionRenderer.java, line 649 at r4](https://reviewable.io/reviews/vaadin/framework/10567#-LLe8PZ4Ae5dDE946blp:-LLe8PZ4Ae5dDE946blq:bhrdkrx) ([raw file](https://github.com/vaadin/framework/blob/7482aa3ddae41fd079057b95423bf4b532d84cf9/client/src/main/java/com/vaadin/client/widget/grid/selection/MultiSelectionRenderer.java#L649)):*
> ```
> // this should be a temp fix.
> ```
This comment can be removed.
___
*[client/src/main/java/com/vaadin/client/widget/grid/selection/MultiSelectionRenderer.java, line 650 at r4](https://reviewable.io/reviews/vaadin/framework/10567#-LLdt53A26OPkox_kIJe:-LLdt53A26OPkox_kIJf:b-ks3o4k) ([raw file](https://github.com/vaadin/framework/blob/7482aa3ddae41fd079057b95423bf4b532d84cf9/client/src/main/java/com/vaadin/client/widget/grid/selection/MultiSelectionRenderer.java#L650)):*
> ```
> checkBox.setText("Selects row number " + getDOMRowIndex(cell) + ".");
> ```
It seems that the text generated by `RowSelectAssistiveLabelGenerator` should be used here.
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 3021 at r4](https://reviewable.io/reviews/vaadin/framework/10567#-LLe7lFh1yO3D_v9lVg8:-LLe7lFh1yO3D_v9lVg9:b-9wqzbv) ([raw file](https://github.com/vaadin/framework/blob/7482aa3ddae41fd079057b95423bf4b532d84cf9/client/src/main/java/com/vaadin/client/widgets/Grid.java#L3021)):*
> ```
> selectAllCheckBox.setText("Selects all rows of the table.");
> ```
This text should also be provided by `RowSelectAssistiveLabelGenerator`.
___
*[server/src/main/java/com/vaadin/ui/Grid.java, line 2507 at r4](https://reviewable.io/reviews/vaadin/framework/10567#-LLdtk4S9lLG_jNJZIXA:-LLdtk4S9lLG_jNJZIXB:b-dx6b23) ([raw file](https://github.com/vaadin/framework/blob/7482aa3ddae41fd079057b95423bf4b532d84cf9/server/src/main/java/com/vaadin/ui/Grid.java#L2507)):*
> ```
> json.put(GridState.JSONKEY_ROWSELECTASSISTIVELABEL, rowSelectAssistiveLabel);
> ```
It's not used anywhere.

**Pull request closed without merging**
