### PR TITLE
Updated migration related documentation

### LINKED ISSUE #8581: Depracated classes should refer to replacements
Vaadin version: 8.0.0.rc1

I tried to get rid of the deprecated com.vaadin.v7.OptionGroup. It was really hard to find out the actual class that replaced it. All classes that have depracated annotation in them, should contain javadoc to guide users to a replacement.

### PR DESCRIPTION
**Pull request by pleku**
More detailed information on compatibility components.
Mention vaadin:upgrade8 target in migration guide.

Fixes #8581

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8602)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 24 of 29 files at r1.
Review status: 24 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Upload.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/8602#-KdBBo1cZvFi_FHyWG9a:-KdBBo1cZvFi_FHyWG9b:bdque7n) ([raw file](https://github.com/vaadin/framework/blob/79302e600bdbdab2d761e98d99b80946476abd38/compatibility-server/src/main/java/com/vaadin/v7/ui/Upload.java#L78)):*
> ```Java
>  *
>  * @deprecated As of 8.0 replaced by {@link com.vaadin.ui.Upload} that is by
>  *             default in immediate mode, instead of reusing immediate concept,
> ```

"immediate concept" sounds a bit strange, but not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8602)*

**Comment by ahie** [comment]
Reviewed 19 of 29 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Calendar.java, line 120 at r1](https://reviewable.io:443/reviews/vaadin/framework/8602#-KdBB2tL8XGzXS9T6ShD:-KdBB2tM1m0YhQY3sTsI:bflmpwj) ([raw file](https://github.com/vaadin/framework/blob/79302e600bdbdab2d761e98d99b80946476abd38/compatibility-server/src/main/java/com/vaadin/v7/ui/Calendar.java#L120)):*
> no replacement available

Perhaps change to "no replacement available in the core framework"?

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/CheckBox.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8602#-KdBCJwgG2IDGf5kulu6:-KdBCJwgG2IDGf5kulu7:b-ts3f27) ([raw file](https://github.com/vaadin/framework/blob/79302e600bdbdab2d761e98d99b80946476abd38/compatibility-server/src/main/java/com/vaadin/v7/ui/CheckBox.java#L39)):*
>  * @deprecated As of 8.0 replaced by a new version based on the new data binding
>  *             API

Could use the same format as the rest, for consistency.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/PopupDateField.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8602#-KdBC-g3HE7zClm16t9R:-KdBC-g4n1_3QgT025Ui:bt275tz) ([raw file](https://github.com/vaadin/framework/blob/79302e600bdbdab2d761e98d99b80946476abd38/compatibility-server/src/main/java/com/vaadin/v7/ui/PopupDateField.java#L39)):*
>  * @deprecated As of 8.0, use {@link com.vaadin.ui.DateField} or
>  *             {@link DateTimeField} instead.

Could mention LocalDate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8602)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/CheckBox.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8602#-KdBCJwgG2IDGf5kulu6:-KdBEiywEY_KZukT_p3R:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/79302e600bdbdab2d761e98d99b80946476abd38/compatibility-server/src/main/java/com/vaadin/v7/ui/CheckBox.java#L39)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

>  * @deprecated As of 8.0 replaced by a new version based on the new data binding
>  *             API

Could use the same format as the rest, for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8602)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 29 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8602#-:-KdBGt0Fgdnq9H2wrvyG:bnfp4nl)*

**Pull request merged**
