### PR TITLE
Fix Grid.addColumn without renderer to accept any type

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes vaadin/framework8-issues#500

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7974)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2490 at r1](https://reviewable.io:443/reviews/vaadin/framework/7974#-KYspRI5JUSq8rHzTFms:-KYspRI5JUSq8rHzTFmt:b-t8n8s2) ([raw file](https://github.com/vaadin/framework/blob/0f982a09362dbb44cd77bd3a1a648128ddfb7d68/server/src/main/java/com/vaadin/ui/Grid.java#L2490)):*
> ```Java
>     /**
>      * Adds a new text column to this {@link Grid} with a value provider. The
>      * column will use a {@link TextRenderer}. Value is converted to String
> ```

The value ... to a String ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7974)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2493 at r1](https://reviewable.io:443/reviews/vaadin/framework/7974#-KYsqjWhdRXeToWNZxeN:-KYsqjWhdRXeToWNZxeO:b-uodeyf) ([raw file](https://github.com/vaadin/framework/blob/0f982a09362dbb44cd77bd3a1a648128ddfb7d68/server/src/main/java/com/vaadin/ui/Grid.java#L2493)):*
> ```Java
>      * using {@link Object#toString()}. Identifier for the column is generated
>      * automatically.
>      *
> ```

Could mention how this automatic conversion affects sorting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7974)*

**Comment by ahie** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7974#-:-KYwCpUJB4qW6tkIxGH8:bnfp4nl)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7974)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/ui/Grid.java, line 2493 at r1](https://reviewable.io:443/reviews/vaadin/framework/7974#-KYsqjWhdRXeToWNZxeN:-KYwu5fDA_qR6hfbFD1k:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0f982a09362dbb44cd77bd3a1a648128ddfb7d68/server/src/main/java/com/vaadin/ui/Grid.java#L2493)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could mention how this automatic conversion affects sorting.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7974)*

**Comment by Legioth** [comment]
And where's the test?

**Comment by Legioth** [comment]
> And where's the test?

The answer is "nowhere". And that's the reason why this feature has apparently been accidentally removed without anyone noticing.

**Pull request merged**
