### PR TITLE
Changed retrieval of names of nested properties (#10159)

### PR DESCRIPTION
**Pull request by schaerl**
The getName() function in NestedBeanPropertyDefinition will return only the top level name, which causes problems when adding a nested property that has the same name as a non-nested (e.g "value" & "sub.value")

This change should fix this behaviour by changing the return value of "getName()" of NestedBeanPropertyDefinition and introducing a function "getTopLevelName()" that only returns the last part of the full name for where it's needed

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10271)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzP-L7tDNdURVw4YJW:-KyzP-L7tDNdURVw4YJX:b-kig6yl) (no related file):*
For the merge conflict it should be ok to remove the `useLongFormName` usage all together.

Also if you could resign the CLA.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzP9v_DwolYNBjDc9a:-KyzP9v_DwolYNBjDc9b:bre805n) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L108)):*
> ```Java
>     private abstract static class AbstractBeanPropertyDefinition<T, V>
>             implements PropertyDefinition<T, V> {
>         protected final PropertyDescriptor descriptor;
> ```

Leave as private.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 255 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzOGzWM9_PDRqZfd-k:-KyzOGzXzVzjXossm0Wk:bjvs4w4) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L255)):*
> ```Java
>         @Override
>         public String getName() {
>             return parent.getName() + "." + descriptor.getName();
> ```

Instead of changing the visibility of the descriptor use `super.getName()` here as it returns descriptor.getName()

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 260 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzOY6CHLHOr_p-Q87Z:-KyzOY6CHLHOr_p-Q87_:b-jkt1hh) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L260)):*
> ```Java
>         @Override
>         public String getTopLevelName() {
>             return descriptor.getName();
> ```

use `super.getName()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by schaerl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzP9v_DwolYNBjDc9a:-KyztjHGPZwFViWt0LNc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L108)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Leave as private.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 255 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzOGzWM9_PDRqZfd-k:-KyztxiXp2_1liRVFtHa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L255)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Instead of changing the visibility of the descriptor use `super.getName()` here as it returns descriptor.getName()
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 260 at r1](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzOY6CHLHOr_p-Q87Z:-Kyzty1H_NGXm7_FnvHt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/27025d35019c3fa37cd3814f28cd468c450ef0cd/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L260)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

use `super.getName()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by schaerl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10271#-KyzP-L7tDNdURVw4YJW:-Kz-8XgC5T7t2lN3F_UK:bx4nh62) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

For the merge conflict it should be ok to remove the `useLongFormName` usage all together.

Also if you could resign the CLA.

</blockquote></details>

Done and done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by caalador** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10271#-KzTZ4c21WBDOA00vT91:-KzTZ4c21WBDOA00vT92:b-execg2) (no related file):*
Sorry I got overrun and sidetracked and now there was a change in `BeanPropertySet`.
It should not  create any need for changes just that you need to resolve the merge conflict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by schaerl** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10271#-KzTZ4c21WBDOA00vT91:-KzU73RusLvUrdBHA1MI:bb6un1j) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Sorry I got overrun and sidetracked and now there was a change in `BeanPropertySet`.
It should not  create any need for changes just that you need to resolve the merge conflict.

</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10271)*

**Pull request merged**
