### PR TITLE
Move old stuff to compatibility

### LINKED ISSUE #10851: com.vaadin.util.FileTypeResolver.getIcon(..) uses non-existent theme resources in Vaadin 8
The class com.vaadin.util.FileTypeResolver is mostly used as helper by FilesystemContainer, which is in compatibility package. Furthermore FileTypeResolver uses icons from Runo theme, which are not in Vaadin 8, hence producing broken icons. Vaadin Framework version:  8.3.3

### PR DESCRIPTION
**Pull request by elmot**
Fixes #10851

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10858#-LBLLNy0DysJ7Azy6aIT:-LBLLNy12PP-bWLXBeQO:b-41ex47) (no related file):*
I'd rather move the whole class rather than have it partly moved.. since the other part is in compatibility package, it causes different API on the two implementations and kinda beats the point of the whole compatibility package..

How is it used in Vaadin 8 ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10858#-LBLLNy0DysJ7Azy6aIT:-LBUmrRg0Lpjr551869Q:b-lzwyau) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd rather move the whole class rather than have it partly moved.. since the other part is in compatibility package, it causes different API on the two implementations and kinda beats the point of the whole compatibility package..

How is it used in Vaadin 8 ?
</blockquote></details>

There is no two implementations actually.
In FW8 FiletypeResolver resolves extension->mimeType for different types of resources. I have no clue why the same class resolves (resolved) also mime->icon, which mapping is used only in FilesystemContainer. 

If we've implemented FilesystemDataProvider  I would also insist to have that mapping somewhere nearby the data source, but not in any general utility class.

On the other hand, my approach breaks general 7->8 migration path, so I'll, most probably, make two FiletypeResolvers: normal one with ext->mime mapping and it's subclass mime->icon in compat. package.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/framework/10858#-LBLLNy0DysJ7Azy6aIT:-LBUtxTqCtfW8ALmabjG:bej2six) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

There is no two implementations actually.
In FW8 FiletypeResolver resolves extension->mimeType for different types of resources. I have no clue why the same class resolves (resolved) also mime->icon, which mapping is used only in FilesystemContainer. 

If we've implemented FilesystemDataProvider  I would also insist to have that mapping somewhere nearby the data source, but not in any general utility class.

On the other hand, my approach breaks general 7->8 migration path, so I'll, most probably, make two FiletypeResolvers: normal one with ext->mime mapping and it's subclass mime->icon in compat. package.
</blockquote></details>

Please do the subclassing thing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Comment by tsuoanttila** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java, line 58 at r2](https://reviewable.io/reviews/vaadin/framework/10858#-LBVC85KELc6iDy4hy76:-LBVC85KELc6iDy4hy77:bipw0j3) ([raw file](https://github.com/vaadin/framework/blob/9172946485bb0b4678653bb071470d5673af8d1f/server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java#L58)):*
> ```Java
>             "com\\.vaadin\\.event\\.FieldEvents", //
>             "com\\.vaadin\\.util\\.FileTypeResolver",
>             "com\\.vaadin\\.util\\.FileTypeResolver",
> ```

Why is the same row twice?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Comment by elmot** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java, line 58 at r2](https://reviewable.io/reviews/vaadin/framework/10858#-LBVC85KELc6iDy4hy76:-LBVuI_cD9VKPd6LWvKX:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/9172946485bb0b4678653bb071470d5673af8d1f/server/src/test/java/com/vaadin/tests/server/ClassesSerializableTest.java#L58)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is the same row twice?
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10858)*

**Pull request merged**
