### PR TITLE
Fixes a Grid issue that breaks sorting.

### PR DESCRIPTION
**Pull request by duffrohde**
When multi-select has been enabled and disabled a number of times, sorting on the first column in a Grid is broken.
Unregistering a click handler on the header solves the problem.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10999)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duffrohde)

---

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10999#-LFucGOkBuddyeF90MYK:-LFucGOkBuddyeF90MYL:b17s6gz) (no related file):*
Requires testing

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10999)*

**Review by duffrohde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10999)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @duffrohde)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10999#-LFucGOkBuddyeF90MYK:-LFzttML2gi0vP5wvmCT:b-am7g76) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Requires testing
</blockquote></details>

Added a test demonstrating the bug and validating the fix

---

**Comment by elmot** [comment]
We are fixing tests for a new testing environment, that's why validation does not pass. We'll let you know when it's ready to rebase your pull request.

**Review by OlliTietavainenVaadin — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10999)* status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10999)* status: all files reviewed, 1 unresolved discussion (waiting on @duffrohde)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/10999#-LLnBw_5BvplOQBkOal4:-LLnBw_69-Q3u_wgO7pM:bwe7701) (no related file):*
Grid is quite fragile thing, I think we need to run our UI tests with this patch. The PR is blocked until it's done.

---

**Comment by elmot** [comment]
Did anyone run the tests?

**Review by pleku — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> Dismissed @elmot from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/10999#-:-LbPBrGx2msmIwGbLm1R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by pleku** [comment]
If build passes, up to you @OlliTietavainenVaadin to merge this for `7.7` or close.

**Pull request merged**
