### PR TITLE
Remove references to Firebug and the firebug chapter from the documentation

### PR DESCRIPTION
**Pull request by freducom**
Firefox has a build in inspector nowadays.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/63)

### CODE REVIEW

**Comment by elmot** [comment]
@freducom , why here, not in our gerrit? Please https://github.com/vaadin/vaadin/blob/master/CONTRIBUTING.md

**Comment by hesara** [comment]
We're on GitHub now, so reopening the PR.

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/63)*

**Comment by pleku** [comment]
@freducom SIGN IT! SIGN IT! SIGN THE AGREEMENT! NOW PLEASE

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/63#-:-KYE8oZA-HPIDTnijHz4:brd5nnd)*

**Comment by hesara** [comment]
This change probably needs a rebase

**Comment by hesara** [comment]
As the branch of the PR is in a separate fork, only @freducom can click the "Update branch" button in GitHub which might allow this change to be merged.

**Comment by hesara** [comment]
Superceded by #7977

**Pull request closed without merging**
