### PR TITLE
Code cleanup: Move dependency loading logic to a separate class

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8290)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 634 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9GyChCEyOZ_TbmCaz:-Kb9GyChCEyOZ_TbmCb-:b-k0hkv2) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L634)):*
> ```Java
>      *            the command to run
>      */
>     public static void runWhenDependenciesLoaded(Command c) {
> ```

The single character could be renamed to 'command' or the like when adding the JavaDoc.

---

*[client/src/main/java/com/vaadin/client/DependencyLoader.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9GnrSHBpvw8EV2lME:-Kb9GnrTxaYBz5ifOFP2:b-2nfdc6) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/DependencyLoader.java#L156)):*
> ```Java
>     }
> 
> }
> ```

New Line at end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8290)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/DependencyLoader.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9tfzQEhzewt2DRwp7:-Kb9tfzQEhzewt2DRwp8:b-oh7agd) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/DependencyLoader.java#L49)):*
> ```Java
>      *            The ApplicationConnection for this instance
>      */
>     public void setConnection(ApplicationConnection connection) {
> ```

Most likely can be completely ignored since it's done this way everywhere in the FW.
But this method is a part of open API which means:
- it can be called at any moment
- it can be called by anyone
(and of course "Only used internally." doesn't prevent anyone from doing this).

One way to solve this (but quite verbose):
- Use `DependencyLoaderFactory` instead of `DependencyLoader`
- declare method like `createDependencyLoader(ApplicationConnection)`.
- `DependencyLoader`  can be declared as an interface or abstract class which is based on `ApplicationConnection` somehow given to it.
- Implement `DependencyLoaderFactory` appropriately ( so there is no public setter, e.g. it can be given via CTOR).
- Now `DependencyLoaderFactory` can be used in GWT.create instead of `DependencyLoader`.
- Create `DependencyLoader` by the `createDependencyLoader(ApplicationConnection)` from the factory instance.

Not blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8290)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 634 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9GyChCEyOZ_TbmCaz:-KbA2WpjoygWizQXOT0x:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L634)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

The single character could be renamed to 'command' or the like when adding the JavaDoc.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/DependencyLoader.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9tfzQEhzewt2DRwp7:-KbA2pI6NSZKfQBJzZwM:b-of4r2y) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/DependencyLoader.java#L49)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Most likely can be completely ignored since it's done this way everywhere in the FW.
But this method is a part of open API which means:
- it can be called at any moment
- it can be called by anyone
(and of course "Only used internally." doesn't prevent anyone from doing this).

One way to solve this (but quite verbose):
- Use `DependencyLoaderFactory` instead of `DependencyLoader`
- declare method like `createDependencyLoader(ApplicationConnection)`.
- `DependencyLoader`  can be declared as an interface or abstract class which is based on `ApplicationConnection` somehow given to it.
- Implement `DependencyLoaderFactory` appropriately ( so there is no public setter, e.g. it can be given via CTOR).
- Now `DependencyLoaderFactory` can be used in GWT.create instead of `DependencyLoader`.
- Create `DependencyLoader` by the `createDependencyLoader(ApplicationConnection)` from the factory instance.

Not blocking.
</blockquote></details>

This is consistent with other classes. Added checks for parameter and state.

---

*[client/src/main/java/com/vaadin/client/DependencyLoader.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8290#-Kb9GnrSHBpvw8EV2lME:-KbA2xXQdD104UxS_w6f:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/254dc0a06b2bf983ee848e0c291de2ac1649cfcf/client/src/main/java/com/vaadin/client/DependencyLoader.java#L156)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

New Line at end of file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8290)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8290)*

**Pull request merged**
