### PR TITLE
Make focus circulate in modal dialog to improve accessibility

### LINKED ISSUE #8855: Modal Window isn't fully accessible - WCAG 2.0 - 2.1.2 No Keyboard Trap
The current implementation of all **modal** windows act as keyboard trap and don't comply to the [WCAG 2.0 - 2.1.2 No Keyboard Trap](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html#keyboard-operation-trapping-examples-head)

**Vaadin Version:**
All

**Example:**
http://demo.vaadin.com/sampler/#ui/structure/window

**Steps to reproduce:**
- Open the Example URL
- Press "Open a new Window"
- Select the Property "Modal"
- Window gets a darker background and pushed to center of the screen
- Press Tab until you hit the bottom

**Expected behaviour:**

> A Web application brings up a dialog box. At the bottom of the dialog are two buttons, Cancel and OK. When the dialog has been opened, focus is trapped within the dialog; **tabbing from the last control in the dialog takes focus to the first control in the dialog**. The dialog is dismissed by activating the Cancel button or the OK button.

_Source: [WCAG 2.0 - 2.1.2 No Keyboard Trap](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html#keyboard-operation-trapping-examples-head)_

**Current behaviour:**

- The Keyboard Focus is trapped at the bottom and can only return with SHIFT+TAB in reverse order to the top side of the modal window. 

**~~Additional problem:~~**

~~Focused min/max/close Icons don't get a focus indicator when using the keyboard to navigate. Mouse:hover works fine.~~

Moved additional problem to #8918

### PR DESCRIPTION
**Pull request by torok-peter**
* Now the focus is moved to the first focusable element in the dialog when the user presses Tab on the last element
* And the other way around for Shift+Tab
* Contains temporary debug logs and UI test code yet

Resolves #8855

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10260)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/10260#-KxSDxs5VuOjZurxKZmM:-KxSDxs6evfWo4r7_G2f:b-qult3u) ([raw file](https://github.com/vaadin/framework/blob/dcc704fdc5e704e8afd743f73c08da05db111bfc/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L183)):*
> ```Java
>         persistingDetails = new PersistingDetailsGenerator();
>         generators.put("Persisting", persistingDetails);
>         Window window = new Window();
> ```

This test change should not be here. Should be tested using already existing ModalWindow tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10260)*

**Comment by torok-peter** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/10260#-KxSDxs5VuOjZurxKZmM:-Kxlj_L65wSaRgybZfe9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/dcc704fdc5e704e8afd743f73c08da05db111bfc/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L183)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This test change should not be here. Should be tested using already existing ModalWindow tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10260)*

**Comment by tsuoanttila** [comment]
Extra change in unrelated file, going to still do some manual testing, but code is almost :lgtm:

---

Reviewed 2 of 4 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/10260#-Ky0BQkprL5wZ_tDRljL:-Ky0BQkprL5wZ_tDRljM:b-osuifa) ([raw file](https://github.com/vaadin/framework/blob/09119dd2eb19c82c6c0b4094c383a862bb012f47/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L30)):*
> ```Java
> import com.vaadin.tests.components.AbstractTestUIWithLog;
> import com.vaadin.ui.Button;
> import com.vaadin.ui.CheckBox;
> ```

extra import

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 46 at r5](https://reviewable.io:443/reviews/vaadin/framework/10260#-Ky0BRsuBfnRpa8CcYAi:-Ky0BRsuBfnRpa8CcYAj:b-osuifa) ([raw file](https://github.com/vaadin/framework/blob/09119dd2eb19c82c6c0b4094c383a862bb012f47/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L46)):*
> ```Java
> import com.vaadin.ui.TextField;
> import com.vaadin.ui.VerticalLayout;
> import com.vaadin.ui.Window;
> ```

extra import

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10260#-:-Ky0BlZqO892KT_EBJXQ:bqmpejm)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 30 at r5](https://reviewable.io:443/reviews/vaadin/framework/10260#-Ky0BQkprL5wZ_tDRljL:-Ky1Ut5sEvjLJzmxfw-W:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/09119dd2eb19c82c6c0b4094c383a862bb012f47/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra import
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 46 at r5](https://reviewable.io:443/reviews/vaadin/framework/10260#-Ky0BRsuBfnRpa8CcYAi:-Ky1UtgiUd05R-xiVXA7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/09119dd2eb19c82c6c0b4094c383a862bb012f47/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L46)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra import
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10260)*

**Pull request merged**
