### PR TITLE
Add setReadOnly for Bindings

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10482)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
@mcollovati care to take a look at this change and give your opinions ?

**Comment by mcollovati** [comment]
My only doubt was if `Binding.isReadOnly` should also take care of the actual value of `HasValue.isReadOnly` or not, however this only matters if a developer acts directly on `HasValue.setReadOnly`, but now this can be done with the new `Binding` api.
Would it make sense to state in `Binding.setReadOnly` javadoc that this is the preferred way to mark bounded field as readonly?
Other than that LGTM

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/BinderTest.java, line 1082 at r1](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1XrwaZ7WpPUdtWHLte:-L1XrwaZ7WpPUdtWHLtf:bci9iu5) ([raw file](https://github.com/vaadin/framework/blob/6c03503e96a324d01f5f3f5542bcf0208cae4cea/server/src/test/java/com/vaadin/data/BinderTest.java#L1082)):*
> ```Java
>         assertTrue("Binding should be readonly", binding.isReadOnly());
>         assertTrue("Name field should be readonly", nameField.isReadOnly());
> ```

Should we add a test also for a binding with null setter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482#-:-L1XrI4oVdvJbm9DRxVw:bui57cu)*

**Comment by mcollovati** [comment]
*[server/src/main/java/com/vaadin/data/Binder.java, line 184 at r1](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1Xsu3KEIVs7_xi17XH:-L1Xsu3KEIVs7_xi17XI:blaky2z) ([raw file](https://github.com/vaadin/framework/blob/6c03503e96a324d01f5f3f5542bcf0208cae4cea/server/src/main/java/com/vaadin/data/Binder.java#L184)):*
> ```Java
>          * read-only will mark the field read-only and not write any values from
>          * the fields to the bean.
>          *
> ```

Does it make sense to state that this is the preferred way to mark a field as readonly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by mcollovati** [comment]
*[server/src/main/java/com/vaadin/data/Binder.java, line 1204 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1r_YtwlEz4_3vJ-tp0:-L1r_YtwlEz4_3vJ-tp1:b-n1g3q0) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L1204)):*
> ```Java
> 
>         @Override
>         public Setter<BEAN, TARGET> getSetter() {
> ```

Since setter may be null wouldn't be better to return an `Optional` here?
BTW, using setter outside of binder wouldn't cause problems of inconsistency between field and bean values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 184 at r1](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1Xsu3KEIVs7_xi17XH:-L1vS3qZ4Wj-MNr1Y1JO:bkf598z) ([raw file](https://github.com/vaadin/framework/blob/6c03503e96a324d01f5f3f5542bcf0208cae4cea/server/src/main/java/com/vaadin/data/Binder.java#L184)):*
<details><summary><i>Previously, mcollovati (Marco Collovati) wrote…</i></summary><blockquote>

Does it make sense to state that this is the preferred way to mark a field as readonly?
</blockquote></details>

In the simple case it definitely makes sense. You give the Field to the Binder, after which the Binder should be the one responsible to keep it's state correct. ie. set value, set required.. 

Making the binding read-only makes it also so that you can use the binder to copy values from one bean to another, but only display some value (for example creation timestamp or an id). setting the `timestamp` binding read-only will show the value it read from, but will not write it to the new bean you store the value to. If you only call it for the field, then the timestamp will be written to the new object.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1204 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1r_YtwlEz4_3vJ-tp0:-L1vQjgMYDKW2_lczQXK:b-s8hhvl) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L1204)):*
<details><summary><i>Previously, mcollovati (Marco Collovati) wrote…</i></summary><blockquote>

Since setter may be null wouldn't be better to return an `Optional` here?
BTW, using setter outside of binder wouldn't cause problems of inconsistency between field and bean values?
</blockquote></details>

I was planning to return an `Optional` for this, but then it'd be different from getting the `getter`. Calling the setter through here does not touch the field, but will update a bean you give to it. But then again so will calling `myBean.setValue("foo")`. We definitely should not try to wrap the setter to another in an attempt to catch possible calls to it, since one of the use-cases I see for this method is to re-create a binding you removed earlier... `binder.bind(b.getField(), b.getGetter(), b.getSetter())`

---

*[server/src/test/java/com/vaadin/data/BinderTest.java, line 1082 at r1](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1XrwaZ7WpPUdtWHLte:-L1vQZA7AMkaok6DDFW2:b-cjjfk6) ([raw file](https://github.com/vaadin/framework/blob/6c03503e96a324d01f5f3f5542bcf0208cae4cea/server/src/test/java/com/vaadin/data/BinderTest.java#L1082)):*
<details><summary><i>Previously, mcollovati (Marco Collovati) wrote…</i></summary><blockquote>

Should we add a test also for a binding with null setter?
</blockquote></details>

There's now also a test for `binding.setReadOnly(false)` with a `null` setter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 184 at r1](https://reviewable.io:443/reviews/vaadin/framework/10482#-L1Xsu3KEIVs7_xi17XH:-L1vU5s51l7Lag_4NRm9:b-bzc55n) ([raw file](https://github.com/vaadin/framework/blob/6c03503e96a324d01f5f3f5542bcf0208cae4cea/server/src/main/java/com/vaadin/data/Binder.java#L184)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

In the simple case it definitely makes sense. You give the Field to the Binder, after which the Binder should be the one responsible to keep it's state correct. ie. set value, set required.. 

Making the binding read-only makes it also so that you can use the binder to copy values from one bean to another, but only display some value (for example creation timestamp or an id). setting the `timestamp` binding read-only will show the value it read from, but will not write it to the new bean you store the value to. If you only call it for the field, then the timestamp will be written to the new object.
</blockquote></details>

This is actually something I need to JavaDoc and document somewhere..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by mcollovati** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482#-:-L1vWAknvsmxUhseC4Rg:bnfp4nl)*

**Comment by mcollovati** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[server/src/test/java/com/vaadin/data/BinderTest.java, line 1071 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4HAt0G4LqheKalaiHU:-L4HAt0G4LqheKalaiHV:b69oel6) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/test/java/com/vaadin/data/BinderTest.java#L1071)):*
> ```Java
>         assertTrue("Binding should be marked readonly",
>                 nameBinding.isReadOnly());
>     }
> ```

binder.setReadOnly() is not tested

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/data/BinderTest.java, line 612 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4kc2NPBjb8zqV3Tfa-:-L4kc2NPBjb8zqV3Tfa0:bn7lgdr) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/test/java/com/vaadin/data/BinderTest.java#L612)):*
> ```Java
> 
>     @Test
>     public void setReadonlyShouldIgnoreBindingsWithNullSetter() {
> ```

Here's the test for `binder::setReadOnly`

---

*[server/src/test/java/com/vaadin/data/BinderTest.java, line 1071 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4HAt0G4LqheKalaiHU:-L4kcEkjTSrelZUuroZk:bgsbufz) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/test/java/com/vaadin/data/BinderTest.java#L1071)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

binder.setReadOnly() is not tested
</blockquote></details>

Commented location of this test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 211 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4oiLYY8_gY0LTK5C1q:-L4oiLYY8_gY0LTK5C1r:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L211)):*
> ```Java
>          * Gets the getter associated with this Binding.
>          *
>          * @return the getter
> ```

missing `@since`

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 218 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4oiOvlEl6OXYV4kMPm:-L4oiOvlEl6OXYV4kMPn:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L218)):*
> ```Java
>          * Gets the setter associated with this Binding.
>          *
>          * @return the setter
> ```

missing `@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by elmot** [comment]
The change can't be merged to 8.3 because of API change

**Comment by tsuoanttila** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 211 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4oiLYY8_gY0LTK5C1q:-L4p4K2RBvq1m5pwU8MM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L211)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 218 at r2](https://reviewable.io:443/reviews/vaadin/framework/10482#-L4oiOvlEl6OXYV4kMPm:-L4p4JrYqHdfdR_NAjwS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/75b219895e56bb679a01d3c9daf312abdc9e0580/server/src/main/java/com/vaadin/data/Binder.java#L218)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10482)*

**Pull request merged**
