### PR TITLE
Remove all referrals to book examples

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8163)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-windows.asciidoc, line 151 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1DY1ZXxGPnilBc9Z9:-Ka1DY1ZXxGPnilBc9ZA:b-xzuvdj) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/advanced/advanced-windows.asciidoc#L151)):*
> ```AsciiDoc
> The URL path for a popup window UI is by default determined from the UI class
> name, by prefixig it with " [literal]#++popup/++#". For example, for the example
> UI giver earlier, the URL would be
> ```

broken sentence

---

*[documentation/clientside/clientside-compiling.asciidoc, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1Dda_YGqZDVoJw7rD:-Ka1Dda_YGqZDVoJw7rE:bmdj1c3) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/clientside/clientside-compiling.asciidoc#L175)):*
> ```AsciiDoc
> ----
> 
> You can copy the build script to your project and, once configured, run it with Ant.
> ```

is this still ok after the deletion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by hesara** [comment]
Reviewed 1 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by pleku** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-windows.asciidoc, line 151 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1DY1ZXxGPnilBc9Z9:-Ka1UcssA5a-mchVwhkq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/advanced/advanced-windows.asciidoc#L151)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

broken sentence
</blockquote></details>

Done.

---

*[documentation/clientside/clientside-compiling.asciidoc, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1Dda_YGqZDVoJw7rD:-Ka1UfDt9LSfM0E8-nh7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/clientside/clientside-compiling.asciidoc#L175)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this still ok after the deletion?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-windows.asciidoc, line 151 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1DY1ZXxGPnilBc9Z9:-Ka1VB4d808hWgvFPgyD:bdlg53m) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/advanced/advanced-windows.asciidoc#L151)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still broken

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by pleku** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-windows.asciidoc, line 151 at r1](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1DY1ZXxGPnilBc9Z9:-Ka1eQ50nVPOSdB60Dch:brn0f32) ([raw file](https://github.com/vaadin/framework/blob/6158e56082560b1e8683df821fbaa8b722c909d3/documentation/advanced/advanced-windows.asciidoc#L151)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

still broken
</blockquote></details>

oops, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by hesara** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-windows.asciidoc, line 150 at r3](https://reviewable.io:443/reviews/vaadin/framework/8163#-Ka1gy366bpcwo-HRk3Q:-Ka1gy37R4C8FC-1z-yx:b-vuj1z3) ([raw file](https://github.com/vaadin/framework/blob/09bddfb424ba0097e5a54dd2822dec66eb54a588/documentation/advanced/advanced-windows.asciidoc#L150)):*
> ```AsciiDoc
> 
> The URL path for a popup window UI is by default determined from the UI class
> name, by prefixig it with " [literal]#++popup/++#". For example the
> ```

"prefixing"; extra space inside quotes? "for the ..."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8163#-:-Ka64cvnUTlv2zZjowed:bnfp4nl)*

**Pull request merged**
