### PR TITLE
Fix exception when Grid is inside a PopupView

### LINKED ISSUE #7695: Error when add Grid in a PopupView content
**Originally by _maalfaro_**

___
when added a grid like content in a PopupView, the browser show an error in the console:

SEVERE: Exception caught: Cannot iterate through widgets in Grid this waycom.google.gwt.event.shared.UmbrellaException: Exception caught: Cannot iterate through widgets in Grid this way

and block the popup.

___
 Imported from https://dev.vaadin.com/ issue #19920

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #7695

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8157)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka0xwhyRk0KLAW2xakq:b-in0tzr) ([raw file](https://github.com/vaadin/framework/blob/f7a71289f5d2a5cb711fb855a0a39168eb32ffb2/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
> ```Java
>                     }
>                 } catch (UnsupportedOperationException e) {
>                     // At least Grid refuses to provide child widgets through
> ```

Why does it implement `HasWidgets` then ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by denis-anisimov** [comment]
Needs rebase and there is one test failure.

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka1BH-yIKTUn6e2NzCV:b-5leyc9) ([raw file](https://github.com/vaadin/framework/blob/f7a71289f5d2a5cb711fb855a0a39168eb32ffb2/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Why does it implement `HasWidgets` then ?
</blockquote></details>

https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8812
```
         * This is the method that is the sole reason to have Grid implement
         * HasWidget - when Vaadin removes a Component from the hierarchy, the
         * corresponding Widget will call removeFromParent() on itself. GWT will
         * check there that its parent (i.e. Grid) implements HasWidgets, and
         * will call this remove(Widget) method.
         *
         * tl;dr: all this song and dance to make sure GWT's sanity checks
         * aren't triggered, even though they effectively do nothing interesting
         * from Grid's perspective.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka1CTkkCJ5cg6Zs0rF1:byl9zr5) ([raw file](https://github.com/vaadin/framework/blob/f7a71289f5d2a5cb711fb855a0a39168eb32ffb2/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8812
```
         * This is the method that is the sole reason to have Grid implement
         * HasWidget - when Vaadin removes a Component from the hierarchy, the
         * corresponding Widget will call removeFromParent() on itself. GWT will
         * check there that its parent (i.e. Grid) implements HasWidgets, and
         * will call this remove(Widget) method.
         *
         * tl;dr: all this song and dance to make sure GWT's sanity checks
         * aren't triggered, even though they effectively do nothing interesting
         * from Grid's perspective.
```
</blockquote></details>

The core problem is indeed in `Grid` and how it implements `HasWidgets` by breaking the contract of `iterator()`:    
```
* Gets an iterator for the contained widgets. This iterator is required to
* implement {@link Iterator#remove()}.
```
This fix should be seen as a workaround for a broken `Grid`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka1re9BfjjisKeIoF2X:bak66ja) ([raw file](https://github.com/vaadin/framework/blob/6042a559b9c48b7d6131ad249d46a22bca43fdbe/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The core problem is indeed in `Grid` and how it implements `HasWidgets` by breaking the contract of `iterator()`:    
```
* Gets an iterator for the contained widgets. This iterator is required to
* implement {@link Iterator#remove()}.
```
This fix should be seen as a workaround for a broken `Grid`
</blockquote></details>

OK, thanks.

A question: can the `Grid` return an empty iterator instead of throwing ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka1rxNkZUtoMZ_Pavz3:b-72fno3) ([raw file](https://github.com/vaadin/framework/blob/6042a559b9c48b7d6131ad249d46a22bca43fdbe/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK, thanks.

A question: can the `Grid` return an empty iterator instead of throwing ?
</blockquote></details>

IMO we could do that instead as it would fix all places where `iterator` is called to work "somehow". For real `Grid` should probably provide the child widgets through `iterator` and rather throw an exception from `remove` in iterator. Not sure if that is needed for anything real though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka2CXHY4yeqOJwUIvI_:b-sxj3f4) ([raw file](https://github.com/vaadin/framework/blob/6042a559b9c48b7d6131ad249d46a22bca43fdbe/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

IMO we could do that instead as it would fix all places where `iterator` is called to work "somehow". For real `Grid` should probably provide the child widgets through `iterator` and rather throw an exception from `remove` in iterator. Not sure if that is needed for anything real though
</blockquote></details>

So, let's do that  (an empty iterator)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 382 at r1](https://reviewable.io:443/reviews/vaadin/framework/8157#-Ka0xwhyRk0KLAW2xakp:-Ka3vspXl6KkCZ6qCzxk:b-7a4c3) ([raw file](https://github.com/vaadin/framework/blob/6042a559b9c48b7d6131ad249d46a22bca43fdbe/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L382)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

So, let's do that  (an empty iterator)?
</blockquote></details>

Well, it's not backwards compatible in any way. Doest it matter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8157)*

**Comment by denis-anisimov** [comment]
Unblocked. Needs rebase.

**Pull request merged**
