### PR TITLE
Fix click selection for automatic testing.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8513)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VListSelect.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8513#-KcWhjLJWs6vk4z6TRrS:-KcWhjLJWs6vk4z6TRrT:b-p4v1ed) ([raw file](https://github.com/vaadin/framework/blob/9de92b194a25ac26ddd3430d43cb7ab9fc036d27/client/src/main/java/com/vaadin/client/ui/VListSelect.java#L46)):*
>  implements ClickHandler

I'm not sure about implementing interface by the widget class directly: it exposes API which it shouldn't.
But it already implements ChangeHandler in this way.....

I would definitely object against it in server side code. But it's client side where a lot of ugly decisions already made.
Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8513)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[client/src/main/java/com/vaadin/client/ui/VListSelect.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8513#-KcWhjLJWs6vk4z6TRrS:-KcWj5XYOUrRcV6PBkVH:bwbjxzr) ([raw file](https://github.com/vaadin/framework/blob/9de92b194a25ac26ddd3430d43cb7ab9fc036d27/client/src/main/java/com/vaadin/client/ui/VListSelect.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  implements ClickHandler

I'm not sure about implementing interface by the widget class directly: it exposes API which it shouldn't.
But it already implements ChangeHandler in this way.....

I would definitely object against it in server side code. But it's client side where a lot of ugly decisions already made.
Up to you.
</blockquote></details>

Well I'm basically just following the way it has been done elsewhere on the client side.
For reference 14 V[component] on client side use this.

But I can change it if wanted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8513)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[client/src/main/java/com/vaadin/client/ui/VListSelect.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8513#-KcWhjLJWs6vk4z6TRrS:-KcWkP5NlFoc873lsTpx:b-wmhm2x) ([raw file](https://github.com/vaadin/framework/blob/9de92b194a25ac26ddd3430d43cb7ab9fc036d27/client/src/main/java/com/vaadin/client/ui/VListSelect.java#L46)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Well I'm basically just following the way it has been done elsewhere on the client side.
For reference 14 V[component] on client side use this.

But I can change it if wanted.
</blockquote></details>

I know.
That's why I'm not sure.

There are two observations:
- bad way is already there and it's everywhere. Should we just follow "bad practice" since it's already everywhere.
- we should start improve at least new code to avoid bad practice and stop making it even worse.

As I said: I don't really know. I don't really care about client side code since it's already kind of dirty without any chance to become good.
So it's just a concern, not a requirement.

That would be definitely an issue on the server side.

So : up to you. I'm OK to keep it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8513)*

**Comment by caalador** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/ui/VListSelect.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8513#-KcWhjLJWs6vk4z6TRrS:-KcWnalWJmfWk25O3ttm:bv8f5km) ([raw file](https://github.com/vaadin/framework/blob/9de92b194a25ac26ddd3430d43cb7ab9fc036d27/client/src/main/java/com/vaadin/client/ui/VListSelect.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I know.
That's why I'm not sure.

There are two observations:
- bad way is already there and it's everywhere. Should we just follow "bad practice" since it's already everywhere.
- we should start improve at least new code to avoid bad practice and stop making it even worse.

As I said: I don't really know. I don't really care about client side code since it's already kind of dirty without any chance to become good.
So it's just a concern, not a requirement.

That would be definitely an issue on the server side.

So : up to you. I'm OK to keep it as is.
</blockquote></details>

Done.

I'm all in for updating how things are done. If it makes things simpler to read it's always fine to break the mold.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8513)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VListSelect.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8513#-KcWhjLJWs6vk4z6TRrS:-KcWoSTrakqXQ4yChanr:biyvv2c) ([raw file](https://github.com/vaadin/framework/blob/9de92b194a25ac26ddd3430d43cb7ab9fc036d27/client/src/main/java/com/vaadin/client/ui/VListSelect.java#L46)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Done.

I'm all in for updating how things are done. If it makes things simpler to read it's always fine to break the mold.
</blockquote></details>

Now it's much better from my point of view.
But it's not backward compatible :(

Thought this is technically a new code since the old one is in the compatibility package.
So it doesn't have to be backward compatible.
So I think it's OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8513)*

**Pull request merged**
