### PR TITLE
Update portlet documentation for OSGi portlets

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9194)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/portal/portal-liferay.asciidoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioIujEzC6BMnnlTj-E:-KioIujEzC6BMnnlTj-F:b1jozrn) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L8)):*
> ```AsciiDoc
> 
> [[portal.liferay]]
> = Developing Vaadin Portlets for Liferay
> ```

Prerelease badge?

---

*[documentation/portal/portal-liferay.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJAbovVtl3aDkDC1E:-KioJAbovVtl3aDkDC1F:bs5cjoz) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L17)):*
> ```AsciiDoc
> 
> For Liferay 7 and OSGi portlets, see <<dummy/../../../framework/portal/portal-osgi#portal.osgi,"OSGi Portlets on Liferay 7">>. This is the recommended approach when using Vaadin 8.1 or later and Liferay 7.
> Currently, the latest Maven archetype supports the OSGi approach.
> ```

... If you want to make a non-OSGi portlet, please use `com.vaadin:vaadin-archetype-portlet:8.0.5` artifact.

---

*[documentation/portal/portal-overview.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJrmQKHw0M0Ko0plf:-KioJrmQKHw0M0Ko0plg:b-wdpa5p) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-overview.asciidoc#L17)):*
> ```AsciiDoc
> necessary descriptors.
> 
> Vaadin Framework also supports developing OSGi portlets for Liferay 7.
> ```

Should not be the new portlet JSR version here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9194)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/portal/portal-liferay.asciidoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioIujEzC6BMnnlTj-E:-KioRIf0Yy-dlWg__BCk:b-4vygrg) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L8)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Prerelease badge?
</blockquote></details>

The section linked from below (for details of OSGi portlets) has that badge, and everything after that in this documentation file also applies to Vaadin 8.0. A badge could be added for the one or two lines in this intro section mentioning OSGi, but OTOH they immediately redirect to a location that has it.

---

*[documentation/portal/portal-liferay.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJAbovVtl3aDkDC1E:-KioR66M9lddZxNr7Irp:bbluf4a) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L17)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

... If you want to make a non-OSGi portlet, please use `com.vaadin:vaadin-archetype-portlet:8.0.5` artifact.
</blockquote></details>

I was considering adding this, but I'm not sure if this documentation is the correct place for it - a separate tutorial or such would probably be better.

---

*[documentation/portal/portal-overview.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJrmQKHw0M0Ko0plf:-KioQKgU1JcQvJCeinrd:b-gwfqql) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-overview.asciidoc#L17)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Should not be the new portlet JSR version here?
</blockquote></details>

There is no OSGi portlet spec (Liferay specific), and the new features of Portlet 3.0 (JSR-362) are not explicitly supported. The implementations of JSR-362 (not yet available) are also JSR-286 compliant, so I think the above paragraph is accurate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9194)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/portal/portal-liferay.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJAbovVtl3aDkDC1E:-KioTqBvhZPVwEEGe2vy:blleeql) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L17)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I was considering adding this, but I'm not sure if this documentation is the correct place for it - a separate tutorial or such would probably be better.
</blockquote></details>

Well, there might be a better place for this statement, but for the moment we don't have anything like that anywhere, and people who want build `.war` portlet are going to be in trouble.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9194)*

**Comment by hesara** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/portal/portal-liferay.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9194#-KioJAbovVtl3aDkDC1E:-Kj72rkycVah_PnvQBGK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/48d1036f7a9c99fe23d22702a9d38007ba4e3647/documentation/portal/portal-liferay.asciidoc#L17)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Well, there might be a better place for this statement, but for the moment we don't have anything like that anywhere, and people who want build `.war` portlet are going to be in trouble.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9194)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9194#-:-Kj73cGHePTc-brk_6cF:bnfp4nl)*

**Pull request merged**
