### PR TITLE
Add a SortListener to a Grid

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#568

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8008)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 10 of 15 files at r1, 3 of 10 files at r4, 3 of 3 files at r5.
Review status: 13 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/event/SortEvent.java, line 21 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xUhNgJiUaP5VOdhn:-KZ1xUhOWC9AilGMrfD2:bbt5nx2) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L21)):*
> ```Java
> import java.util.List;
> 
> import com.vaadin.server.data.SortOrder;
> ```

This is an old import, will need a rebase for this branch.

---

*[server/src/main/java/com/vaadin/event/SortEvent.java, line 35 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xfnZ4YF7CUmGwx4b:-KZ1xfnZ4YF7CUmGwx4c:b2nh2c8) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L35)):*
> ```Java
>  *            or a {@link java.util.Comparator}.
>  *
>  * @since 7.4
> ```

7.4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 17 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/event/SortEvent.java, line 35 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xfnZ4YF7CUmGwx4b:-KZ1y0UYJ8GcTIQfOZ_q:b3n7wf1) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

7.4
</blockquote></details>

It's actually a question......
Should it be 8.0 or 7.4 ?

Technically it is a new class.
But in reality it is a replacement for the old one (and can be considered as a corrected old SortOrder).

I don't know.
I don't have any opinion on this (don't care). I can do whatever you say. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/event/SortEvent.java, line 35 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xfnZ4YF7CUmGwx4b:-KZ2-yOsN897_-UBYngv:bkcbxka) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L35)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's actually a question......
Should it be 8.0 or 7.4 ?

Technically it is a new class.
But in reality it is a replacement for the old one (and can be considered as a corrected old SortOrder).

I don't know.
I don't have any opinion on this (don't care). I can do whatever you say. 
</blockquote></details>

If the old one is in v7 compatibility, this should be considered to be "new" class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/SortEvent.java, line 21 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xUhNgJiUaP5VOdhn:-KZ20pbvdAfoXkjIhqGk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L21)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This is an old import, will need a rebase for this branch.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/SortEvent.java, line 35 at r5](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ1xfnZ4YF7CUmGwx4b:-KZ20qAuc674hgnOWgk2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2442c1a4dd8d80d5eb4a5732c679c114d41efc5f/server/src/main/java/com/vaadin/event/SortEvent.java#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

If the old one is in v7 compatibility, this should be considered to be "new" class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Comment by tsuoanttila** [comment]
Minor formatting problem. Other than that :lgtm:

---

Reviewed 1 of 10 files at r4, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 244 at r6](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ21YKz1HQiufK3PhPj:-KZ21YKz1HQiufK3PhPk:bdedx9b) ([raw file](https://github.com/vaadin/framework/blob/07a10282b0ad4951a5520a614c09a5a98d282312/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L244)):*
> ```Java
> 
>         grid.addSortListener(event ->
> ```

Extra whitespace, format file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008#-:-KZ225oLm4iceTeEvKpJ:bk0zbw)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 244 at r6](https://reviewable.io:443/reviews/vaadin/framework/8008#-KZ21YKz1HQiufK3PhPj:-KZ22_yo9GJfHktb40ye:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/07a10282b0ad4951a5520a614c09a5a98d282312/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L244)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Extra whitespace, format file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8008)*

**Pull request merged**
