### PR TITLE
Custom fonts page updated to reflect recent (last 2 years) changes.

### PR DESCRIPTION
**Pull request by rolfsmeds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8822)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8822#-KfAmNjCX0VZbLe2rGow:-KfAmNjCX0VZbLe2rGox:bcsxqxu) (no related file):*
Please click the CLA button to sign the contributor license agreement and see the comment elsewhere (not blocking).

---

*[documentation/themes/themes-fonts.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8822#-KfAm05atzgN78aUbpH5:-KfAm05atzgN78aUbpH6:birkvne) ([raw file](https://github.com/vaadin/framework/blob/e22c2752bbee39bce29dc30f234a2bde2a21b1d9/documentation/themes/themes-fonts.asciidoc#L33)):*
> ```AsciiDoc
> Not all browsers support any single font file format, so the base name is
> appended with [filename]#.ttf#, [filename]#.eot#, [filename]#.woff#, or
> [filename]#.svg# suffix for the font file suitable for a user's browser. It is recommended to provide the font in all four formats to support all browsers.
> ```

Do we still need all four to support the browsers supported by Vaadin Framework 8?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8822)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/themes/themes-fonts.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8822#-KfAm05atzgN78aUbpH5:-KfAnjSMJe2lx_5DEjbJ:b-nrbao) ([raw file](https://github.com/vaadin/framework/blob/e22c2752bbee39bce29dc30f234a2bde2a21b1d9/documentation/themes/themes-fonts.asciidoc#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Do we still need all four to support the browsers supported by Vaadin Framework 8?
</blockquote></details>

All supported browsers should support `woff` files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8822)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/themes/themes-fonts.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8822#-KfAm05atzgN78aUbpH5:-KfAns47p-aZreiH8J8W:bial35n) ([raw file](https://github.com/vaadin/framework/blob/e22c2752bbee39bce29dc30f234a2bde2a21b1d9/documentation/themes/themes-fonts.asciidoc#L33)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

All supported browsers should support `woff` files.
</blockquote></details>

http://caniuse.com/#feat=woff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8822)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8822)*

**Pull request merged**
