### PR TITLE
Support for disabling ComboBox items

### PR DESCRIPTION
**Pull request by lorenzobenvenuti**
For our application we needed to disable the selection of certain ComboBox items, so I decided to take a look to VFilterSelect/ComboBox code and see how complicated this could be; it didn't actually look that complicated, so I spent a couple of hours coding a tentative implementation. It works as expected, but I don't know if this is the best way to achieve this result.

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Why is this in the review?

I don't see here any patch except github PR.
It can't be merged from GitHub.
Patch is required in Gerrit.
Does it exist already there ?

**Comment by denis-anisimov** [comment]
Look like it should go into FW Support track.

**Comment by lorenzobenvenuti** [comment]
Sorry, I didn't read the "Contributing to Vaadin" document before submitting the pull request so I didn't know about the new contributions workflow. I see that all the changes should be made to the "master" branch; judging from the completely new APIs my guess is that "master" represents the branch that will become version 8, am I right? We actually need this feature and I was hoping it could be included in 7.x series.

**Comment by denis-anisimov** [comment]
It's actually not a new contribution workflow. It's the same workflow.
We have to use Gerrit for patches.

The question was actually for our team , not for you. For some reason this is in out review track.
I thought it has been moved there by someone. I still don't understand how it appeared in this track.
But if you want to get it merged then you should use Gerrit https://dev.vaadin.com/review/ to create a patch.
Someone has to create it there anyway. So it will be you or someone else from our team.
It will be faster if it's you.
Also if you haven't yet signed CLA then please do it.

**Comment by lorenzobenvenuti** [comment]
As I said in my previous comment our application is using Vaadin 7.x; the [CONTRIBUTING.md](https://github.com/vaadin/vaadin/blob/master/CONTRIBUTING.md) documents states that changes should be made on the master branch. Can I create a patch for that branch? If so, what target should I use instead of `HEAD:refs/for/master`? Thank you.

PS: I didn't mean that the contribution worfklow has changed... in "new contributions workflow" the word "new" was actually supposed to go with "contributions", not "workflow". Sorry for not being clear.

**Comment by elmot** [comment]
Hello, Lorenzo,
Please follow the https://github.com/vaadin/vaadin/blob/master/CONTRIBUTING.md for code contribution. If you are implementing the patch for Vaadin 7, please push your change for "7.7" branch, not master, i.e. 
use `git push gerrit HEAD:refs/for/7.7`. Also don't forget  to file a ticket in [trac](https://dev.vaadin.com/) and note its number in the commit message. I close the push request here.

**Comment by jouni** [comment]
@lorenzobenvenuti Thanks for the PR, btw! Sorry us being a bit in the middle of our migration from Gerrit to GitHub, and not having the proper time to process this feature request.

So from now on, the contribution guide looks a lot different than yesterday. We now work completely in GitHub, and accept outside PR’s here as well 🎉

The tickets from our previous system ([Trac](https://dev.vaadin.com) are also being migrated to GitHub Issues, but that’s probably going to happen next week earliest.

So, coming back to this particular PR, I think we could reopen it and give it a proper look this time, as it is a valuable feature to have. Also, it would be great to have always have a description of your use case for any new features you request, so we can have a better discussion how we should cover that use case.

**Pull request closed without merging**
