### PR TITLE
Scheduler.ScheduledCommand and RepeatingCommand to be lambda

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10203)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 27 of 29 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1681 at r2](https://reviewable.io:443/reviews/vaadin/framework/10203#-KwjNcb2l21PjVm0uj3Y:-KwjNcb2l21PjVm0uj3Z:b-6n2ouj) ([raw file](https://github.com/vaadin/framework/blob/a6f81dd8af1778d46bbe30815970f1cb5e4acc75/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1681)):*
> ```Java
>                                                                    // provider,
>                                                                    // then no
>                                                                    // checkbox
> ```

This looks bad, please move the comment to the next line and reunite it on a single line.

Could you btw switch off "Format all lines" as I asked earlier? It is annoying and makes reviews more difficult.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10203)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1681 at r2](https://reviewable.io:443/reviews/vaadin/framework/10203#-KwjNcb2l21PjVm0uj3Y:-KwjQrzbI5vEKcmGV04T:b-7i3bpf) ([raw file](https://github.com/vaadin/framework/blob/a6f81dd8af1778d46bbe30815970f1cb5e4acc75/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1681)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

This looks bad, please move the comment to the next line and reunite it on a single line.

Could you btw switch off "Format all lines" as I asked earlier? It is annoying and makes reviews more difficult.
</blockquote></details>

Oh, sorry. Actually I did, but this was an old commit. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10203)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10203#-:-Kwj_FWrkriZZyIXYjpt:bnfp4nl)*

**Comment by asashour** [comment]
The build failed with "Cannot allocate memory", can we restart it?
Or should I commit small enhancement?

**Comment by torok-peter** [comment]
Restarted build

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10203#-:-KwjbdD_8PRGgVY2IaHX:bbiyu47)*

**Pull request merged**
