### PR TITLE
Read-only styles shouldn't override borderless background styles.

### LINKED ISSUE #11671: Some fields (at least ComboBox and DateField) have non-transparent background with style borderless when they get readonly
When I create a ComboBox with Style 'boarderless' (for example in a table) and setting the ComboBox to readonly, the field gets a greyed background.

The style for readonly seems to overwrite the borderless style.

I am using vaadin 8.8.5 and it is reproducable in all browsers.

All components with style 'borderless' should keep a transparent background, even when they are readonly.

For TextField it works as expected.

### PR DESCRIPTION
**Pull request by Ansku**
- Fixed for ComboBox and DateField styles, other tested components
already do it right.

Fixes #11671

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11692)

### CODE REVIEW

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11692)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/main/java/com/vaadin/tests/components/uitest/components/DatesCssTest.java, line 56 at r1](https://reviewable.io/reviews/vaadin/framework/11692#-Lm3_klW2OR7SfMX6vfw:-Lm3_klW2OR7SfMX6vfx:b-3jqguv) ([raw file](https://github.com/vaadin/framework/blob/2357e31851293199c6aeab24352a0e71a129b43e/uitest/src/main/java/com/vaadin/tests/components/uitest/components/DatesCssTest.java#L56)):*
> ```Java
>                 Component c = iterator.next();
>                 if (c instanceof AbstractField) {
>                     ((AbstractField<?>) c)
> ```

split to read and assignment on separate lines

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11692)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[uitest/src/main/java/com/vaadin/tests/components/uitest/components/DatesCssTest.java, line 56 at r1](https://reviewable.io/reviews/vaadin/framework/11692#-Lm3_klW2OR7SfMX6vfw:-Lm3dDKlC6t3Jt1MP3ZW:b-4n6tbi) ([raw file](https://github.com/vaadin/framework/blob/2357e31851293199c6aeab24352a0e71a129b43e/uitest/src/main/java/com/vaadin/tests/components/uitest/components/DatesCssTest.java#L56)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

split to read and assignment on separate lines
</blockquote></details>

switched to use separate variables instead

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11692)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/ATestDateField.java, line 20 at r2](https://reviewable.io/reviews/vaadin/framework/11692#-Lm8pqeb5hI1vNQAVOIf:-Lm8pqeb5hI1vNQAVOIg:b-evdrrf) ([raw file](https://github.com/vaadin/framework/blob/6393d7805e0f7e628a3f248b5428f960224881e2/uitest/src/test/java/com/vaadin/tests/components/datefield/ATestDateField.java#L20)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>     // LocalDate special = LocalDate.of(2017, Month.NOVEMBER, 11);
>     //
>     // DateStyleGenerator sg = new DateStyleGenerator() {
>     //
>     // @Override
>     // public String getStyle(DateField source, LocalDate date) {
>     // if (special.isEqual(date)) {
>     // return "special-style";
>     // }
>     // return null;
>     // }
>     //
>     // };
>     //
>     // dateField.setStyleName(special, "special-style");
> ```
</details>


is this part useful?

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11692)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[uitest/src/test/java/com/vaadin/tests/components/datefield/ATestDateField.java, line 20 at r2](https://reviewable.io/reviews/vaadin/framework/11692#-Lm8pqeb5hI1vNQAVOIf:-Lm8x8EEDavnFJC6Q8YA:b576eov) ([raw file](https://github.com/vaadin/framework/blob/6393d7805e0f7e628a3f248b5428f960224881e2/uitest/src/test/java/com/vaadin/tests/components/datefield/ATestDateField.java#L20)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

> ```
>     // LocalDate special = LocalDate.of(2017, Month.NOVEMBER, 11);
>     //
>     // DateStyleGenerator sg = new DateStyleGenerator() {
>     //
>     // @Override
>     // public String getStyle(DateField source, LocalDate date) {
>     // if (special.isEqual(date)) {
>     // return "special-style";
>     // }
>     // return null;
>     // }
>     //
>     // };
>     //
>     // dateField.setStyleName(special, "special-style");
> ```

is this part useful?
</blockquote></details>

Ah, my lagging Eclipse strikes again. Must be a misclick that hadn't updated to the staging view yet when I approved my list of changes, I have no recollection of this test class even existing but it certainly has nothing to do with this issue. Will remove.

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 10 of 15 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11692#-:-LmP1xLXAoligbAPyJAt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
