### PR TITLE
Refactored TreeGrid constructors to save beanType (#10195)

### PR DESCRIPTION
**Pull request by peergynt**
The TreeGrid constructor `TreeGrid(Class<T> beanType)` was not setting the internal beanType which resulted in `getBeanType()` returning null.

This change refactored a couple of TreeGrid constructors so that the `TreeGrid(Class<T> beanType)` constructor invokes the equivalent parent constructor to setup the beanType the same way as Grid.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10291)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Thank you for the pull request! Just a minor detail on the placement of the test method, and this will be good to go!

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBeanTest.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/10291#-KytlhPCCkvwO-f724o8:-KytlhPCCkvwO-f724o9:b-s61zb7) ([raw file](https://github.com/vaadin/framework/blob/c580bdc99ebf4328f215e9135ebede9f203f35fe/server/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBeanTest.java#L13)):*
> ```Java
> 
>     @Test
>     public void testBeanTypeConstructor() {
> ```

Please move this test to be part of the already existing `com.vaadin.tests.components.treegrid.TreeGridTest`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10291#-:-KytlxnNLRAXsmdaQoMK:br4ziov)*

**Comment by tsuoanttila** [comment]
Had some extra time so fixed it myself.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10291#-:-KyuJNJGcs7ZEAD02Q-j:bxjv1kw)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10291)*

**Comment by tsuoanttila** [comment]
@peergynt can you please sign the CLA again?

**Comment by peergynt** [comment]
Thanks, I signed the CLA again.

**Pull request merged**
