### PR TITLE
Update documentation, BoV chapters 1 - 5.3

### PR DESCRIPTION
**Pull request by pleku**
Images and diagrams have not been updated,
but unnecessary images have been removed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8085)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz4Qc-u9XbrTYQYTUS:-KZz4Qc-u9XbrTYQYTUT:b1zuwsz) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-architecture.asciidoc#L98)):*
> ```AsciiDoc
> Model-View-Presenter (MVP) pattern, and so forth.
> 
> ifdef::web[]
> ```

Is not needed anymore ?

---

*[documentation/application/application-declarative.asciidoc, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz5ASkhtvxEkQYwOIq:-KZz5ASkhtvxEkQYwOIr:b8u5xv4) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L28)):*
> ```AsciiDoc
> layout.addComponent(vertical);
> ----
> See the http://demo.vaadin.com/book-examples-vaadin7/book#layout.orderedlayout.basic[on-line example, window="_blank"].
> ```

No any replacement for this ?

---

*[documentation/application/application-declarative.asciidoc, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz6N3lQL5YBih8pv6V:-KZz6N3lQL5YBih8pv6W:b-fu2poj) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-declarative.asciidoc#L84)):*
> The above design defines the same UI layout as done earlier with Java code, and
> illustrated in
> <<dummy/../../../framework/application/application-architecture#figure.application.architecture.example,"Simple
> Hierarchical UI">>.

Does it match to the Java code ? (just to make sure, I don't even understand where is the resource referenced from here)

---

*[documentation/application/application-declarative.asciidoc, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz6qCbq3s16NVBijJb:-KZz6qCbq3s16NVBijJc:b36m45t) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L258)):*
> ```AsciiDoc
> &lt;/vaadin-vertical-layout&gt;
> ----
> Again, compare the above declaration to the Java code given in
> ```

Worth to remove ?

---

*[documentation/getting-started/getting-started-idea.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz84n5ye90JHu_e5A7:-KZz84n5ye90JHu_e5A8:b4e78nq) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/getting-started/getting-started-idea.asciidoc#L15)):*
> ```AsciiDoc
> 
> ifdef::web[]
> For more information, see the article "
> ```

Is it not more relevant ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by elmot** [comment]
Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz4Qc-u9XbrTYQYTUS:-K_-pJKvOQYsyRxWdsm0:bz5adpg) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-architecture.asciidoc#L98)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is not needed anymore ?
</blockquote></details>

That change looks very weird for me. Sounds like this will INCLUDE extra stuff into PDF version. I need to talk to @Artur about this
Referenced part  is quite new, it might be Magi just haven't "bookenized" it

---

*[documentation/application/application-declarative.asciidoc, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz5ASkhtvxEkQYwOIq:-K_-r7bJxO662sLLYlj9:bgf9twi) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L28)):*
>  http://demo.vaadin.com/book-examples-vaadin7/book#layout.orderedlayout.basic

Apparently, we do not have the replacement. This example should be fixed, we have other OrderedLayout spacing defaults now.
Also I am not sure if that is a blocker to be published in the book.

---

*[documentation/application/application-declarative.asciidoc, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz6N3lQL5YBih8pv6V:-K_-sS6XJ6JdQXagOuU1:b-cj5vrc) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-declarative.asciidoc#L84)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> The above design defines the same UI layout as done earlier with Java code, and
> illustrated in
> <<dummy/../../../framework/application/application-architecture#figure.application.architecture.example,"Simple
> Hierarchical UI">>.

Does it match to the Java code ? (just to make sure, I don't even understand where is the resource referenced from here)
</blockquote></details>

The picture is here
https://github.com/vaadin/framework/blob/99d6de546c74f0eed230ea8253dda6b85109d2e7/documentation/application/img/ui-architecture-hierarchical.png

There is a notice in PR description - pictures are not updated. Apparently, this one must be corrected later on.

---

*[documentation/application/application-declarative.asciidoc, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz6qCbq3s16NVBijJb:-K_-t8UPYOee2WsP8c9v:bt14632) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L258)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Worth to remove ?
</blockquote></details>

better to fix. not in this UI anyway

---

*[documentation/getting-started/getting-started-idea.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz84n5ye90JHu_e5A7:-K_-uBCM_CiaJw3brYgz:b-wzj8zb) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/getting-started/getting-started-idea.asciidoc#L15)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is it not more relevant ?
</blockquote></details>

Dead link, and that is not related to printed version

I have a replacement
https://vaadin.com/blog/-/blogs/vaadin-and-intellij-idea-community-edition

---

*[documentation/getting-started/getting-started-libraries.asciidoc, line 51 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_-wsQoD66d25AdqC7k:-K_-wsQoD66d25AdqC7l:b-1orpef) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/getting-started/getting-started-libraries.asciidoc#L51)):*
> ```AsciiDoc
> 
> [filename]#vaadin-compatibility-*-8.x.x.jar#::
> The Vaadin Framework 7 compatibility packages contain the components and themes that are present in framework version 7, but not in version 8. These packages exist for making it easier to migrate from version 7 to 8. There is a compatibility package for everything except [filename]#vaadin-client-compiler#.
> ```

Is compatibility naming scheme defined anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_490B43U2sWoOCa-So:-K_490B599X-J2Dygfd3:b-yccyj0) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L37)):*
> ```AsciiDoc
> 
>         // Couple of horizontally laid out components
>         Tree tree = new Tree("My Tree",
> ```

This code snippet contains `Tree` and `Table` references. 
Should it be updated ?

This will require changes in the referenced image below (figure.application.architecture.schematic).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_490B43U2sWoOCa-So:-K_4DbPgC99m7vepb7sO:bl78k16) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This code snippet contains `Tree` and `Table` references. 
Should it be updated ?

This will require changes in the referenced image below (figure.application.architecture.schematic).
</blockquote></details>

Actually, this has to be updated.

This section is referenced from application-declarative.asciidoc where its declarative format is described.
Declarative format doesn't match the code here.
It means that:
- this code has to be updated to match the declarative format
- image referenced below (schematic architecture) has to be redone.
- result image (for the UI) has to be updated.

---

*[documentation/application/application-architecture.asciidoc, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_4AuK9G8Ns46idAZ94:-K_4AuK9G8Ns46idAZ95:brv0j40) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L57)):*
> ```AsciiDoc
> [[figure.application.architecture.schematic]]
> .Schematic diagram of the UI
> image::img/ui-schematic-hi.png[width=80%, scaledwidth=100%]
> ```

Image has to be replaced in case of changes in the source code above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_490B43U2sWoOCa-So:-K_4D_l-ea1lcmu08rqi:ba4ahkp) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Actually, this has to be updated.

This section is referenced from application-declarative.asciidoc where its declarative format is described.
Declarative format doesn't match the code here.
It means that:
- this code has to be updated to match the declarative format
- image referenced below (schematic architecture) has to be redone.
- result image (for the UI) has to be updated.
</blockquote></details>

I think yes. Declarative example was  updated. Actually there are 2 images to update (or remove?)
documentation\application\img\ui-architecture-hierarchical.png
documentation\application\img\ui-schematic-hi.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_490B43U2sWoOCa-So:-K_4FN0JahTsVM2Dsnn8:b-4llrv6) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L37)):*
> documentation\application\img\ui-architecture-hierarchical.png

I'm going to update this one (this is just a screenshot) and the source code here to match the declarative format.

But this one documentation\application\img\ui-schematic-hi.png requires some "image designer" work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz4Qc-u9XbrTYQYTUS:-K_4GZiCJYC4UCtTELsR:b-ftip1o) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-architecture.asciidoc#L98)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

That change looks very weird for me. Sounds like this will INCLUDE extra stuff into PDF version. I need to talk to @Artur about this
Referenced part  is quite new, it might be Magi just haven't "bookenized" it
</blockquote></details>

This chapter contains text:
*This section is mostly up-to-date with Vaadin 7, but has some information
which still needs to be updated.*

 Needs to be fixed. I have no idea what Markus wanted to update while writing this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Should there be updates in the application-resources section ?
I see at least reference to vaadin7 online book.

Also there are two images: resource-fileresource.png and resource-themeimage.png.
Both of them are taken for Ivy project structure in Eclipse.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085#-:-K_4cpcwwTzbxuJ_BMKu:b-ybceen)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_4AuK9G8Ns46idAZ94:-K_Tg_XfrQsk2ew6qXDs:b-b5jsg4) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/application/application-architecture.asciidoc#L57)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Image has to be replaced in case of changes in the source code above.
</blockquote></details>

Will go through the screenshots separately

---

*[documentation/application/application-architecture.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz4Qc-u9XbrTYQYTUS:-K_TfmUPb3TJ5GO-ua1l:bxfgcu4) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-architecture.asciidoc#L98)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This chapter contains text:
*This section is mostly up-to-date with Vaadin 7, but has some information
which still needs to be updated.*

 Needs to be fixed. I have no idea what Markus wanted to update while writing this.

</blockquote></details>

FYI we don't keep a separation of web/book things anymore. Decided so because nobody wants to maintain two different versions of things.

---

*[documentation/application/application-declarative.asciidoc, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz5ASkhtvxEkQYwOIq:-K_Tg0pifKoaol9TuGmJ:b-yhkdtb) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L28)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>  http://demo.vaadin.com/book-examples-vaadin7/book#layout.orderedlayout.basic

Apparently, we do not have the replacement. This example should be fixed, we have other OrderedLayout spacing defaults now.
Also I am not sure if that is a blocker to be published in the book.
</blockquote></details>

FYI: Even though the Book Examples are partly very good examples, we are not updating those and thus all the links should be removed.

---

*[documentation/application/application-declarative.asciidoc, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz6qCbq3s16NVBijJb:-K_TgKGtYodNpkdxsakK:bb69dmd) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-declarative.asciidoc#L258)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

better to fix. not in this UI anyway
</blockquote></details>

#ffs

---

*[documentation/getting-started/getting-started-idea.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz84n5ye90JHu_e5A7:-K_TgPLwlj2FBx3KZAEL:b-gesb0g) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/getting-started/getting-started-idea.asciidoc#L15)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Dead link, and that is not related to printed version

I have a replacement
https://vaadin.com/blog/-/blogs/vaadin-and-intellij-idea-community-edition
</blockquote></details>

We're not printing any links and no separation between web/book

---

*[documentation/getting-started/getting-started-libraries.asciidoc, line 51 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_-wsQoD66d25AdqC7k:-K_Tgh1RcyApNz9akL7y:b3ryo8m) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/getting-started/getting-started-libraries.asciidoc#L51)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Is compatibility naming scheme defined anywhere?
</blockquote></details>

wat ? above it states `vaadin-compability-*` or do you mean the package names ? The latter is off-topic here, or please suggest a replacement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/application/application-architecture.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-KZz4Qc-u9XbrTYQYTUS:-K_TroFbcvvHiNpebYY5:b2nhll9) ([raw file](https://github.com/vaadin/framework/blob/95626bc699d61e48669a7bc333907e64be883e5a/documentation/application/application-architecture.asciidoc#L98)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

FYI we don't keep a separation of web/book things anymore. Decided so because nobody wants to maintain two different versions of things.
</blockquote></details>

Ok.

---

*[documentation/getting-started/getting-started-libraries.asciidoc, line 51 at r1](https://reviewable.io:443/reviews/vaadin/framework/8085#-K_-wsQoD66d25AdqC7k:-K_Tsh_-WsgTRvfEz9Gr:bt9zlgy) ([raw file](https://github.com/vaadin/framework/blob/f53d91a0f6e813ee891c39f4bcfc7a6f615c8e09/documentation/getting-started/getting-started-libraries.asciidoc#L51)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

wat ? above it states `vaadin-compability-*` or do you mean the package names ? The latter is off-topic here, or please suggest a replacement
</blockquote></details>

I mean package names. That's fine to note that somewhere else, but I don't see that at all for the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8085#-:-K_TyVn4BBobnPzpaJgJ:bnfp4nl)*

**Pull request merged**
