### PR TITLE
Update README-TESTS

### PR DESCRIPTION
**Pull request by ZheSun88**
Add formatting for easy-reading;
Add missing configuration for running IE11 locally.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11376)

### CODE REVIEW

**Comment by anasmi** [comment]
___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTulyHj7Y8No2SGTTua:-LTulyHj7Y8No2SGTTub:bmqlic2) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
> ```Markdown
>     * Gotcha: If you add a new feature to a menu you need to run and possibly (probably) fix all TB tests which use the class as they will click on the wrong item (fixable by implementing [http://dev.vaadin.com/ticket/11307](http://dev.vaadin.com/ticket/11307))
> 
> [Note] `AbstractTestCase`, `TestBase` are old base classes for tests. Don use for any new tests. Extends LagacyApplication.
> ```

Don't : )

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anasmi and @mehdi-vaadin)

___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTulyHj7Y8No2SGTTua:-LTv6LCB1pMJPo0-Nx39:b-be2k52) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Don't : ) 
</blockquote></details>

Nice catch. Thank you. :-)

**Review by anasmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @anasmi and @mehdi-vaadin)

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mehdi-vaadin)

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
I added some suggestions.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376#-:-LTvJUrT1stGFDkp3djX:basnl9r)* status: all files reviewed, 5 unresolved discussions (waiting on @ZheSun88)

___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvI9LCB7otOy5DYwLE:-LTvI9LCB7otOy5DYwLF:bvqr13o) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
> ```
> ,
> ```
 and
___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvILA_-3Aqax8f8CiE:-LTvILA_-3Aqax8f8CiF:bpbl9ac) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
> ```
> Don use for
> ```
Don't use them for
___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvJGcc7R2aKxwVpedJ:-LTvJGcc7R2aKxwVpedK:bwj379x) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
> ```
> Extends LagacyApplication
> ```
They extend `LegacyApplication` which is a deprecated class. 
___
*[README-TESTS.md, line 121 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvHHIzEvC-td4aRJTN:-LTvHHIzEvC-td4aRJTO:b-xdg3d9) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L121)):*
> ```
>  You need
> ```
In order to run a test locally, you need
___
*[README-TESTS.md, line 131 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvHnUX0zSv5qIiOViG:-LTvHnUX0zSv5qIiOViH:biwszfv) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L131)):*
> ```
> binary
> ```
binary.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @anasmi, @mehdi-vaadin, and @ZheSun88)

___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvI9LCB7otOy5DYwLE:-LTvMv5x-ws5qt-7tjB8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> ,
> ```
 and
</blockquote></details>

Done.
___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvILA_-3Aqax8f8CiE:-LTvMvML3I9MrB099wrJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> Don use for
> ```
Don't use them for
</blockquote></details>

Done.
___
*[README-TESTS.md, line 27 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvJGcc7R2aKxwVpedJ:-LTvMvfiCDelcJoThDFt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L27)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> Extends LagacyApplication
> ```
They extend `LegacyApplication` which is a deprecated class. 
</blockquote></details>

Done.
___
*[README-TESTS.md, line 121 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvHHIzEvC-td4aRJTN:-LTvMwU14JSGE8mStG-z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L121)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
>  You need
> ```
In order to run a test locally, you need
</blockquote></details>

Done.
___
*[README-TESTS.md, line 131 at r1](https://reviewable.io/reviews/vaadin/framework/11376#-LTvHnUX0zSv5qIiOViG:-LTvNA9x30xA_1sXV588:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f174f73002f49face37eeae36519826751b75bc2/README-TESTS.md#L131)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> binary
> ```
binary.
</blockquote></details>

Done.

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11376#-:-LTvNe0W46LiU3WyteoO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
