### PR TITLE
AbstractDateField: set value after being invalid (Fixes #9763 and #9978)

### LINKED ISSUE #9763: DateField.setValue does not work if some date is already typed in by the user
Related to #9740

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10187)

### CODE REVIEW

**Comment by asashour** [comment]
Possibly also fixes #9764 (as part of fixes to `DisabledParentLayoutTest`), but I am not sure.

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1, 2 of 3 files at r2, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 115 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_Ie4_OhbR7iw_VDNB:-Kw_Ie4_OhbR7iw_VDNC:bg6qxj4) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L115)):*
> ```Java
>                             Result<T> parsedDate = handleUnparsableDateString(
>                                     dateString);
>                             parsedDate.ifOk(v -> {
> ```

extra code block. no longer multiple lines execution

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_ILt-IAM8qMnAcunw:-Kw_ILt-IAM8qMnAcunx:b-o4e1da) ([raw file](https://github.com/vaadin/framework/blob/3133c2752e61ca539d26133e63e653b835cfdb4a/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L24)):*
> ```Java
> 
>         String invalidSuffix = "abc";
>         dateField.setValue(dateField.getValue() + invalidSuffix);
> ```

Could add a check here to make sure the DateField is showing an error before hitting the button.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 27 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JOMITIftVqL6oFQs:-Kw_JOMITIftVqL6oFQt:b-s1d0py) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L27)):*
> ```Java
>         dateField.setValue(dateField.getValue() + invalidSuffix);
> 
>         $(ButtonElement.class).first().click();
> ```

could use .caption("Today") to specify the correct button.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 40 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JUvX-_CNizgG09Fw:-Kw_JUvX-_CNizgG09Fx:b-z56tol) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L40)):*
> ```Java
> 
>         String invalidSuffix = "abc";
>         dateField.setValue(dateField.getValue() + invalidSuffix);
> ```

same error check

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 42 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JHS956TLtyPYYXZk:-Kw_JHS956TLtyPYYXZl:b-e64jyy) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L42)):*
> ```Java
>         dateField.setValue(dateField.getValue() + invalidSuffix);
> 
>         $(ButtonElement.class).get(1).click();
> ```

could also do .caption("Clear") instead of depending on index.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10187)*

**Comment by asashour** [comment]
Review status: 3 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 115 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_Ie4_OhbR7iw_VDNB:-Kw__pIRexg6E4mHJGwo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L115)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra code block. no longer multiple lines execution
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_ILt-IAM8qMnAcunw:-Kw__q86lBaE2AfWvux7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3133c2752e61ca539d26133e63e653b835cfdb4a/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L24)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could add a check here to make sure the DateField is showing an error before hitting the button.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 27 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JOMITIftVqL6oFQs:-Kw_a0WVO2XDpb0aHJ-j:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

could use .caption("Today") to specify the correct button.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 40 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JUvX-_CNizgG09Fw:-Kw_a1EEVQxYTDINBaJj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L40)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

same error check
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java, line 42 at r6](https://reviewable.io:443/reviews/vaadin/framework/10187#-Kw_JHS956TLtyPYYXZk:-Kw_a1lP1gst_-_EH2S1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6be6bf124e97f415e1ad5068ec020727c8aaf9a1/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldSetAfterInvalidTest.java#L42)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

could also do .caption("Clear") instead of depending on index.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10187)*

**Comment by tsuoanttila** [comment]
When testing this change manually I ran into the case where faulty input into a cleared date field is not marked as error. Is this handled by one of your other DateField related changes? If not, could you open a ticket and add an ignored test that does (preferably with the correct ticket number in place)
```
$(ButtonElement.class).caption("Clear").first().click();
dateField.setValue("abc");
assertErrorIndicator();
```

Other than that nice to have for future kind of thing, this is :lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10187#-:-Kw_kEmeR-OlbHqBX7Pl:b3tmojn)*

**Comment by tsuoanttila** [comment]
There's test failure with DisabledParentLayoutTest, regression?

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10187#-:-Kwd5opKhkpA4b778FcT:bewbbi5)*

**Pull request merged**
