### PR TITLE
Improve role usage in grid

### PR DESCRIPTION
**Pull request by knoobie**
Hey @tsuoanttila, first improvement after a discussion with our accessibility inspector. This is the first 'easy' task. 

This pull request adds the missing roles

- row
- gridcell
- rowheader
- columnheader
- rowgroup

to Grid. 

> Authors MUST ensure that elements with role gridcell are owned by elements with role row, which in turn are owned by an element with role rowgroup, grid or treegrid. If the author applies any non-global WAI-ARIA states or properties to a native markup element that is acting as a row (such as the tr element in HTML), the author MUST also apply the role of row, as stated in the section on Implementation in Host Languages.

Source: [w3.org/roles#grid](https://www.w3.org/TR/wai-aria/roles#grid)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10206)

### CODE REVIEW

**Comment by asashour** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaRowcountTest.java, line 41 at r7](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwnHvB238-cWTrBH1b7:-KwnHvB3kspscYQBMvOF:b-g8aypb) ([raw file](https://github.com/vaadin/framework/blob/55b017a02a8969dbd5b230964f9b98b222819409/uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaRowcountTest.java#L41)):*
> ```Java
>         // default grid should contain at least one of each role
>         String gridHtml = grid.getHTML();
>         assertTrue("Grid should contains a role=\"rowheader\"", gridHtml.contains("role=\"rowheader\""));
> ```

`Grid should contain` is [grammatically](http://www.grammar.cl/english/should.htm) correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaRowcountTest.java, line 41 at r7](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwnHvB238-cWTrBH1b7:-KwnLFxkKLXHrnTJ8250:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/55b017a02a8969dbd5b230964f9b98b222819409/uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaRowcountTest.java#L41)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

`Grid should contain` is [grammatically](http://www.grammar.cl/english/should.htm) correct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by torok-peter** [comment]
Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1145 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-Kwnec2c3aRdeaLVe1NR:-Kwnec2c3aRdeaLVe1NS:b-ojql99) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1145)):*
> ```Java
>         public static final String GRID_ROLE_ROWGROUP="rowgroup";
>         public static final String GRID_ROLE_CELL="gridcell";
>         public static final String GRID_ROLE_COLUMNHEADER="columnheader";
> ```

Could these be turned into an enum?

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1200 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndgCZuNXPbOs1uh2K:-KwndgCZuNXPbOs1uh2L:bb9ulz) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1200)):*
> ```Java
> 
>         /**
>          * Sets the role attribute '$attr' to the given element.
> ```

'$attr' -> {@code attr}

It could also be renamed to e.g. `roleName`.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1205 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndwPAHFWJRFNOw2E0:-KwndwPAHFWJRFNOw2E1:b5qz5yz) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1205)):*
> ```Java
>          * @param attr        attribute to be added
>          *
>          * @since 8.2
> ```

Leave `@since` empty everywhere - it will be autofilled during the release process

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1145 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-Kwnec2c3aRdeaLVe1NR:-Kwnp8a8jxzvPCAuWxzr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1145)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Could these be turned into an enum?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1200 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndgCZuNXPbOs1uh2K:-Kwnp9F9X1L4mzIh1stH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1200)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

'$attr' -> {@code attr}

It could also be renamed to e.g. `roleName`.

</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1205 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndwPAHFWJRFNOw2E0:-KwnpAT2GPpIE2WA1TXU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1205)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Leave `@since` empty everywhere - it will be autofilled during the release process
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1200 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndgCZuNXPbOs1uh2K:-KwoGAKOLJPXvyzw7eFB:bt8o256) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1200)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

...and my suggestion was immediately obsoleted by myself, sorry :-) Now it'd be better called simply `role`. 

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1205 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndwPAHFWJRFNOw2E0:-KwoGWsNASb-U-sXsnFo:b-tkznkc) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1205)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Apologies, my comment was apparently not clear enough - I meant that it is good to add the `@since` tag, just don't set its value.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1211 at r9](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoG3bT7ne8pBAIcbrb:-KwoG3bT7ne8pBAIcbrc:b-nz2efm) ([raw file](https://github.com/vaadin/framework/blob/a625c7f712c1b2ab3b110c724bd9d01ef9716792/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1211)):*
> ```Java
>      * @since
>      */
>     private enum AriaGridRoles {
> ```

Would be more natural in singular, i.e. `AriaGridRole`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1200 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndgCZuNXPbOs1uh2K:-KwoMYMHF6rpAyYdb3Ds:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1200)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

...and my suggestion was immediately obsoleted by myself, sorry :-) Now it'd be better called simply `role`. 
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1205 at r8](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwndwPAHFWJRFNOw2E0:-KwoM__HMJPAZl1Y2-_T:b-erfuxz) ([raw file](https://github.com/vaadin/framework/blob/b938734d613e5234136ac269452bdd59eec4d268/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1205)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Apologies, my comment was apparently not clear enough - I meant that it is good to add the `@since` tag, just don't set its value.
</blockquote></details>

I think every new class/method has an empty @since, or? 

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1211 at r9](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoG3bT7ne8pBAIcbrb:-KwoMZSatoFbZ2mhE8dH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a625c7f712c1b2ab3b110c724bd9d01ef9716792/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1211)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Would be more natural in singular, i.e. `AriaGridRole`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by torok-peter** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1194 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoVQ4T59eJcn_UpeRP:-KwoVQ4T59eJcn_UpeRQ:b902h2p) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1194)):*
Rename also here. Now it could be simply 

> Sets the {@code role} attribute to the given element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1211 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoXsgjbj9C07JDqDnN:-KwoXsgjbj9C07JDqDnO:b-cb4ea7) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1211)):*
> ```Java
>      * @since
>      */
>     private enum AriaGridRole {
> ```

Make it public

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
@torok-peter just some questions, so I can tackle anything in one commit later: 

- should I rename #getRoleName() now as well? 
- should be the enum protected / public?
- should I update the javadocs of AriaGridHelper
- are my empty since tags okay, or anything else that I'm missing there?

**Comment by torok-peter** [comment]
Yes, please update the javadocs of AriaGridHelper. The others I answered in separate comments below. With the proposed changes it would look OK to me, but I will ask @tsuoanttila to lend a second pair of eyes, because I don't understand the background here well enough. 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1219 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwodaDro5xtlHKxqq78:-KwodaDro5xtlHKxqq79:bju6tr) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1219)):*
> ```Java
>         COLUMNHEADER("columnheader");
> 
>         private final String roleName;
> ```

Should be simply `name` now, and its getter `getName`, to keep it DRY

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206#-:-KwodvRbjD7vpNDqja67:b-n0ic4f)*

**Comment by knoobie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1194 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoVQ4T59eJcn_UpeRP:-KworKD_bEeesjU9K0lF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1194)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Rename also here. Now it could be simply 

> Sets the {@code role} attribute to the given element.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1211 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwoXsgjbj9C07JDqDnN:-KworLaB3NKXEdx8N2bA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1211)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Make it public
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1219 at r10](https://reviewable.io:443/reviews/vaadin/framework/10206#-KwodaDro5xtlHKxqq78:-KworMXV-8SCu3BXfIqK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e7ad46cc4de875bf42353441abb878f095bb085/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1219)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Should be simply `name` now, and its getter `getName`, to keep it DRY
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2499 at r11](https://reviewable.io:443/reviews/vaadin/framework/10206#-Kws_BGTXQHuuzuKrD3T:-Kws_BGTXQHuuzuKrD3U:b-wbwte2) ([raw file](https://github.com/vaadin/framework/blob/e6a9ed64c2d954fb43889400ccc856cf2c785603/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2499)):*
> ```Java
>         @Override
>         protected AriaGridRole getRowElementRole() {
>             return AriaGridRole.ROWHEADER;
> ```

no specific roles for footer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 2499 at r11](https://reviewable.io:443/reviews/vaadin/framework/10206#-Kws_BGTXQHuuzuKrD3T:-KwsaRB3AUSjn-mpOX4z:b-vbqude) ([raw file](https://github.com/vaadin/framework/blob/e6a9ed64c2d954fb43889400ccc856cf2c785603/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L2499)):*
No, there is no specific element for footer at the moment. 

Same thing could be ask for (role="rowgroup"), there is already a note in the w3 docs.

> Note: This role (rowgroup) does not differentiate between types of row groups (e.g., thead vs. tbody), but an issue has been raised for WAI-ARIA 2.0.

Currently we are at version 1.1 (draft) so it will take some time til 2.0 hits us. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by asashour** [comment]
Please resolve conflicts

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 1221 at r11](https://reviewable.io:443/reviews/vaadin/framework/10206#-Kwsd8c_EZ-JbMt1atJ5:-Kwsd8c_EZ-JbMt1atJ6:bumxfcc) ([raw file](https://github.com/vaadin/framework/blob/e6a9ed64c2d954fb43889400ccc856cf2c785603/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L1221)):*
> ```Java
> 
>         private final String name;
> ```

(extra empty line, can be fixed later as well)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Comment by knoobie** [comment]
Thanks for the conflict resolving, @torok-peter!

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10206)*

**Pull request merged**
