### PR TITLE
Fix wrong frontend URL in docs.

### PR DESCRIPTION
**Pull request by Flamenco**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10472)

### CODE REVIEW

**Comment by Flamenco** [comment]
Here's a screenshot from the host page that configures the URL.

screen shot 2017-12-28 at 9 26 07 am

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10472#-L1S_6NrAW15gd26HZCk:-L1S_6NrAW15gd26HZCl:bjqgd38) ([raw file](https://github.com/vaadin/framework/blob/52970308cbaf50e38e5c95f7a9cafcc2e398f5df/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L45)):*
> ```Java
>  * Note that you should (almost) always use URLs starting with
>  * {@literal frontend://} so that the framework can resolve the files to either
>  * {@literal VAADIN/es5} or {@literal VAADIN/es6} depending on if the browser
> ```

These should also be fixed in the same way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10472)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10472)*

**Comment by Flamenco** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10472#-L1S_6NrAW15gd26HZCk:-L1cdRU_rSFJ55OkQcJK:b-86qh4y) ([raw file](https://github.com/vaadin/framework/blob/52970308cbaf50e38e5c95f7a9cafcc2e398f5df/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L45)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

These should also be fixed in the same way
</blockquote></details>

Artur, I am not sure what you mean by 'These'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10472)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10472#-L1S_6NrAW15gd26HZCk:-L1cf2Jp1Ort5c1G5qQ0:bbf7slt) ([raw file](https://github.com/vaadin/framework/blob/52970308cbaf50e38e5c95f7a9cafcc2e398f5df/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L45)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

Artur, I am not sure what you mean by 'These'.
</blockquote></details>

OK.  Figured it out.   I don't digest reviewable.io very well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10472)*

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10472)*

**Comment by Artur-** [comment]
Thanks!

**Pull request merged**
