### PR TITLE
Fix AbstractIntegrationTest to use new TextBench API (#10336)

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10355)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/10355#-KzYw5-j7Yw20ORjCBJq:-KzYw5-j7Yw20ORjCBJr:bgsctg9) ([raw file](https://github.com/vaadin/framework/blob/fcc21a6f69a98f348263009ac3421c6c416f3f89/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L122)):*
> Override

This method can now be removed completely. It is already inherited from the new `TestBenchTestCase`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355)*

**Comment by tsuoanttila** [comment]
Remember to fix the commit message typo when merging

**Comment by ahie** [comment]
Just a nit, but referencing an issue/PR in the first line of a commit message is a bit confusing, since reviewable automatically appends a PR's id to the end when merging. A more descriptive message for this issue could be something like:

```
Fix AbstractIntegrationTest to use new TestBench API

PR #10336 updated the TB version to 5.1, breaking the waitUntil method
of AbstractIntegrationTest.
```

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355#-:-KzZ0qlQ8fJDm22mM5w8:b8x3z52)*

**Comment by Ansku** [comment]
How about someone finally updates the contribution guidelines to actually correspond with this new environment and practices? Including the ticket number in the commit message used to be a blocking requirement. In fact, this is the third "oh, we don't do it like that anymore" that I've run across recently (the others were hidden and outdated instructions for dealing with comparison screenshots, and GitHub not doing automatic blocking dependency for branching pull requests like Gerrit did).

I guess I'll just do a completely new branch with the method removed completely and the commit message fixed.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355#-:-KzZ3i-GAd8R14Et7rKP:bsfu7aq)*

**Comment by ahie** [comment]
Wasn't aware that the contributing guide had an out of date example. Made a PR to update it.

It is not necessary to create a new PR just to update the commit message. The message is editable during merging. 

You can ofcourse `git commit --amend` and then force push if you want to amend the history of commits here on github as well.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355#-:-KzZ9as1k6Sznv5eab63:bfztfpt)*

**Comment by Ansku** [comment]
Got the notification for that comment too late, already did the new branch and pull request. Wasn't sure if the existing pull request interferes with the amend.

The lack of issue number in the commit message means that there is no link to the issue at all, though. Should I have included it on some other row?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355#-:-KzZAeTPTmrEUY2hTqIF:bovex0o)*

**Comment by ahie** [comment]
It's fine. No need to include the PR reference, since there really isn't an open issue about this.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10355#-:-KzZDlB9uIEZYkHhHlwv:b-h22bkt)*

**Comment by ahie** [comment]
Superceded by #10358.

**Pull request closed without merging**
