### PR TITLE
Use maven to run PhantomJS tests

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11121)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11121)* status: all files reviewed, 2 unresolved discussions (waiting on @tsuoanttila)

___
*[uitest/build.xml, line 51 at r1](https://reviewable.io/reviews/vaadin/framework/11121#-LKQ25UC6PbrkQ5Rjzly:-LKQ25UC6PbrkQ5Rjzlz:b-cmv2si) ([raw file](https://github.com/vaadin/framework/blob/738f620b73c2c7a3663744e0de5403b574eb7c84/uitest/build.xml#L51)):*
> ```XML
>             </daemons>
>             <sequential>
>                 <ant antfile="${uitest.dir}/vaadin-server.xml"
> ```

vaadin-server.xml and tb3tests.xml to drop?
___
*[uitest/pom.xml, line 316 at r1](https://reviewable.io/reviews/vaadin/framework/11121#-LKQ1mTk7XzWZBFhpb7U:-LKQ1mTk7XzWZBFhpb7V:b-tou16s) ([raw file](https://github.com/vaadin/framework/blob/3d238c344ed9213bc4d718699a488b965d97bc2d/uitest/pom.xml#L316)):*
> ```XML
>                     <systemPropertyVariables>
>                         <com.vaadin.testbench.screenshot.directory>${project.parent.basedir}/tests/screenshots</com.vaadin.testbench.screenshot.directory>
>                         <com.vaadin.testbench.max.retries>2</com.vaadin.testbench.max.retries>
> ```

Only 2?

**Review by tsuoanttila — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11121)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[uitest/build.xml, line 51 at r1](https://reviewable.io/reviews/vaadin/framework/11121#-LKQ25UC6PbrkQ5Rjzly:-LKQEAYw6_CBM95-S6mN:b-b2vz80) ([raw file](https://github.com/vaadin/framework/blob/738f620b73c2c7a3663744e0de5403b574eb7c84/uitest/build.xml#L51)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

vaadin-server.xml and tb3tests.xml to drop?
</blockquote></details>

Yes. should be dropped. Still need to pick the servlet container tests from V8, tb3tests.xml can be dropped now.
___
*[uitest/pom.xml, line 316 at r1](https://reviewable.io/reviews/vaadin/framework/11121#-LKQ1mTk7XzWZBFhpb7U:-LKQEKc86N0DfwTaH1e5:b-sr9cpw) ([raw file](https://github.com/vaadin/framework/blob/3d238c344ed9213bc4d718699a488b965d97bc2d/uitest/pom.xml#L316)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Only 2?
</blockquote></details>

Need to switch it to be based on the variable from TeamCity

**Review by tsuoanttila — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11121)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @elmot)

___
*[uitest/build.xml, line 51 at r1](https://reviewable.io/reviews/vaadin/framework/11121#-LKQ25UC6PbrkQ5Rjzly:-LKQHGka9RE_BdZkKBIz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/738f620b73c2c7a3663744e0de5403b574eb7c84/uitest/build.xml#L51)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Yes. should be dropped. Still need to pick the servlet container tests from V8, tb3tests.xml can be dropped now.
</blockquote></details>

Done.

**Review by elmot — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11121)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by elmot — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11121#-:-LKRQnB-9cyv8bNlnyRl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
