### PR TITLE
Converted old Framework TestBench test docs to markdown

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8084)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README-TESTS.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzAlCDzJn_FdGhHMrQ:-KZzAlCDzJn_FdGhHMrR:b-y3y8gn) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L7)):*
> Leaving out the parameter usually shows the wrong UI class or only an exception.·

Not accurate.
In reality :
- FQN is not really needed. Just a simple class name is enough (in case of course if there is no name clash).
- It always shows the correct UI if the name of the UI is correct and this is the very first time.
- Without a parameter it just caches the previously asked UI and shows it (The same happens in case of exception : it's just cached. That's why it shows an exception).
- So the parameter just prevents the caching.

I'm not sure how this should be written here. May be it's too long and too much information but at least the current statement is not accurate and a bit confusing.

---

*[README-TESTS.md, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzCZxm7oB8CZVll0R9:-KZzCZxnCNlrc__mHgen:b-vavn3o) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L32)):*
> ```Markdown
> All new test for the projects must be created as TestBench3+ tests
> ### Test class naming
> TestBench 3+ tests follows a naming conventions which automatically maps the test to the UI class. The TB3 test class should be named **UIClassTest**, e.g. if UI is **LabelModes** then the TB3+ test is **LabelModesTest**. Inside the LabelModesTest class there are 1..N methods which test various aspects of the LabelModes UI.
> ```

It's not necessary.

This is just an easy way. But in reality you can use any names for your UI and test class. Just remember to override the `AbstractTB3Test::getUIClass()` method.
Normally it's better to follow the convention that is described here. But sometimes it's just not convenient.

---

*[README-TESTS.md, line 51 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzDNaqrhtSRKrjvfm0:-KZzDNaqrhtSRKrjvfm1:b-sq19h9) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L51)):*
> ```Markdown
> “@Test” is needed for it to be run at all.
> 
> “throws Exception” should always be added to avoid catching exceptions inside the test (exception == test fail).
> ```

It's up to the test developer to decide.

Unchecked exceptions will fail test without any additional efforts to declare an exception.

Checked exception forces you to handle it somehow. It's up to you to decide do you want to handle it in your code or don't do anything and consider it as a test failure.

But each time it's just a developer decision.

---

*[README-TESTS.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzE-UO-dg7sc28wcgJ:-KZzE-UO-dg7sc28wcgK:bfxkf6l) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L53)):*
> open the UI class

Confusing ? It doesn't open the UI class (directly as java class). It requests the URL which correspond to the UI class.
Not sure here about exact wording.

---

*[README-TESTS.md, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzEmGKPh0cbwTg1mql:-KZzEmGKPh0cbwTg1mqm:b-czjvku) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L95)):*
> ```Markdown
>         public void testNativeButtonIconAltText() {
>             openTestURL();
>             assertAltText(BUTTON_TEXT, "");
> ```

This either requires a "magic" static import or doesn't compile at all.

It's better to use here `NativeButtonIconAndText.BUTTON_TEXT`

---

*[README-TESTS.md, line 118 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzFWu5bpa_wRtJ_-Ir:-KZzFWu5bpa_wRtJ_-Is:bteuvuv) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L118)):*
> ```Markdown
> #### Debugging remotely
> Running remotely on a single browser (as described above) can be used to debug issues with a given browser but with the downside that you cannot see what is happening with the browser. In theory this is possible if you figure out on what machine the test is run (no good way for this at the moment) and use VNC to connect to that.
> #### Debugging locally
> ```

Something about phantomjs ?
Since it's the default validation browser and gives the easiest way to run the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8084)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[README-TESTS.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzAlCDzJn_FdGhHMrQ:-K_4-hBRhtIa0l07yTxq:b7cs0j9) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L7)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Leaving out the parameter usually shows the wrong UI class or only an exception.·

Not accurate.
In reality :
- FQN is not really needed. Just a simple class name is enough (in case of course if there is no name clash).
- It always shows the correct UI if the name of the UI is correct and this is the very first time.
- Without a parameter it just caches the previously asked UI and shows it (The same happens in case of exception : it's just cached. That's why it shows an exception).
- So the parameter just prevents the caching.

I'm not sure how this should be written here. May be it's too long and too much information but at least the current statement is not accurate and a bit confusing.
</blockquote></details>

Updated text to remove FQN and clarified ?restartApplication parameter usage

---

*[README-TESTS.md, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzCZxm7oB8CZVll0R9:-K_40XLooTeB9tYUolFn:b-i1uwmi) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's not necessary.

This is just an easy way. But in reality you can use any names for your UI and test class. Just remember to override the `AbstractTB3Test::getUIClass()` method.
Normally it's better to follow the convention that is described here. But sometimes it's just not convenient.
</blockquote></details>

Clarified that convention is not necessary

---

*[README-TESTS.md, line 51 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzDNaqrhtSRKrjvfm0:-K_40chjGUtfvRwxs2zN:bz4j3uq) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L51)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's up to the test developer to decide.

Unchecked exceptions will fail test without any additional efforts to declare an exception.

Checked exception forces you to handle it somehow. It's up to you to decide do you want to handle it in your code or don't do anything and consider it as a test failure.

But each time it's just a developer decision.
</blockquote></details>

Made wording less strict

---

*[README-TESTS.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzE-UO-dg7sc28wcgJ:-K_40jqSBFYg1qSxvFRA:b-s03py9) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L53)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> open the UI class

Confusing ? It doesn't open the UI class (directly as java class). It requests the URL which correspond to the UI class.
Not sure here about exact wording.
</blockquote></details>

Clarified wording a little here

---

*[README-TESTS.md, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzEmGKPh0cbwTg1mql:-K_40nA07B_aooxih4gy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L95)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This either requires a "magic" static import or doesn't compile at all.

It's better to use here `NativeButtonIconAndText.BUTTON_TEXT`
</blockquote></details>

Done.

---

*[README-TESTS.md, line 118 at r1](https://reviewable.io:443/reviews/vaadin/framework/8084#-KZzFWu5bpa_wRtJ_-Ir:-K_40oBsDD4BuBdHZuC9:b-mbhpcl) ([raw file](https://github.com/vaadin/framework/blob/2351d50bd9dd7aad1498aeeb88d9c1123716da43/README-TESTS.md#L118)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Something about phantomjs ?
Since it's the default validation browser and gives the easiest way to run the test.
</blockquote></details>

Added bit about PhantomJS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8084)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README-TESTS.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/framework/8084#-K_41eWMnzBGBdqUJhrH:-K_41eWN-0UXlk4HSjnJ:b-9d1voh) ([raw file](https://github.com/vaadin/framework/blob/24b883761ce2de076a2568aba0e2034f6dbe6e96/README-TESTS.md#L7)):*
>  run if want to you run 

if you want to run ?

I see there 2 red dots in the end of the sentence. May be this are extra spaces.

---

*[README-TESTS.md, line 123 at r2](https://reviewable.io:443/reviews/vaadin/framework/8084#-K_42eAvLrfbD72G6uOJ:-K_42eAvLrfbD72G6uOK:b-u6ow08) ([raw file](https://github.com/vaadin/framework/blob/24b883761ce2de076a2568aba0e2034f6dbe6e96/README-TESTS.md#L123)):*
> This is the default validation browser

This is not actually true.....

It is used for build validation in our build procedure (and any change made in the FW should pass the validation build). So it's also easier to use it for fast validation locally.

But `@RunLocally` uses `FIREFOX` by default if no value is specified. So one has to use `@RunLocally(Browser.PHANTOMJS)` explicitly.

So it's default for our validation but it's not default considering API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8084)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README-TESTS.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/framework/8084#-K_41eWMnzBGBdqUJhrH:-K_45HUgrcE1SqnPkWfi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/24b883761ce2de076a2568aba0e2034f6dbe6e96/README-TESTS.md#L7)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  run if want to you run 

if you want to run ?

I see there 2 red dots in the end of the sentence. May be this are extra spaces.
</blockquote></details>

Done.

---

*[README-TESTS.md, line 123 at r2](https://reviewable.io:443/reviews/vaadin/framework/8084#-K_42eAvLrfbD72G6uOJ:-K_45IR_yF4Z7h3uy7Vk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/24b883761ce2de076a2568aba0e2034f6dbe6e96/README-TESTS.md#L123)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> This is the default validation browser

This is not actually true.....

It is used for build validation in our build procedure (and any change made in the FW should pass the validation build). So it's also easier to use it for fast validation locally.

But `@RunLocally` uses `FIREFOX` by default if no value is specified. So one has to use `@RunLocally(Browser.PHANTOMJS)` explicitly.

So it's default for our validation but it's not default considering API.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8084)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8084)*

**Pull request merged**
