### PR TITLE
Grid drag and drop documentation

### PR DESCRIPTION
**Pull request by wbadam**
Part of issue #8399

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9055)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS-mLALBrxgvzniT0w:-KhS-mLALBrxgvzniT0x:bmma59e) (no related file):*
You should add a server side test class that verifies at least that the code snippets compile, plus would be also to verify that the code works. Can you 

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 148 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRtRgJia6ev7usma3p:-KhRtRgJia6ev7usma3q:bxny5je) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L148)):*
> component allowing

Missing comma, probably could split this with "... Grid component. This allows reordering..."

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 150 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRt_DnSzP4Ug3bfaGC:-KhRt_DnSzP4Ug3bfaGD:b-bvyu1w) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L150)):*
>  Grid Drag Source

This should be "Grid as a Drag Source" or something that is not as bulky, or to be descriptive: "Making Grid's Rows Draggable"

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 152 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzYr33yyrbXXoqUL5:-KhRzYr33yyrbXXoqUL6:bc20lk6) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L152)):*
> ```AsciiDoc
> === Grid Drag Source
> 
> A Grid component's rows can be made draggable by applying [classname]#GridDragSource# extension to the component.
> ```

Please also explain how all the dragging works, e.g. if the selection mode is `MULTI`, then when dragging the selected row, all the selected rows are dragged.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRu4TGJieuUyz7Uq3W:-KhRu4TGJieuUyz7Uq3X:b-vmeboc) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L165)):*
> bean

replace with _item_

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRunJPU_FPGqPGMHab:-KhRunJPU_FPGqPGMHac:beaw5c7) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L173)):*
> defines what data should be transferred

Could you please refer to how it is transferred, e.g. link the HTML5 property it is set for

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 177 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRv196wMBaCM99aB7E:-KhRv196wMBaCM99aB7F:bbxtyr2) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L177)):*
> Note that setting the data transfer text is not supported.

Isn't this the only thing that is supported ??? E.g. what the type is for the data that the generator uses, maybe you should mention explicitly what is not supported

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS2L8SUz1XMvdkJk0V:-KhS2L8SUz1XMvdkJk0W:bxsmyd5) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L178)):*
> ```AsciiDoc
> ====
> Note that setting the data transfer text is not supported.
> ====
> ```

Please also fix the javadocs for `GridDragSource:setDataTransferText` by overriding them an mentioning that it is not supported, instead of inheriting the javadocs from parent

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 196 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRwRT66slLji5GhcJr:-KhRwRT66slLji5GhcJs:b-ngwp0l) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L196)):*
> ```AsciiDoc
>     }
> });
> ----
> ```

I think you should explicitly mention (in text) that the framework provides the grid's dragged rows in the event automatically

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 198 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRxojjdl0M5SS9kXZS:-KhRxojjdl0M5SS9kXZT:b-gf05dq) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L198)):*
> Grid Drop Target

"Grid As A Drop Target" or "Making Grid's Rows Drop Targets"

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 200 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzpb-4Fjal7E25HDw:-KhRzpb-4Fjal7E25HDx:b-r424t1) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L200)):*
> define

specify, also how 'bout:

"When creating the extension, you need to define where the transferred data can be dropped on.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 213 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS3qTJkV8qZbMuoXf5:-KhS3qTJkV8qZbMuoXf6:bxu4gyd) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L213)):*
> when an element is dropped onto a row or between rows.

Replace with "...when data is dropped to the grid."

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 218 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzy2Rj2H1eZarM-PZ:-KhRzy2Rj2H1eZarM-P_:brfngv0) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L218)):*
> ```AsciiDoc
> ----
> dropTarget.addGridDropListener(event -> {
>     // Accepting dragged items from another Grid
> ```

..another Grid in the same UI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 148 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRtRgJia6ev7usma3p:-KhSAz3DrEtPqAVxwIkf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L148)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> component allowing

Missing comma, probably could split this with "... Grid component. This allows reordering..."
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 150 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRt_DnSzP4Ug3bfaGC:-KhSDDe0vxg2cEd5V6F7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L150)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  Grid Drag Source

This should be "Grid as a Drag Source" or something that is not as bulky, or to be descriptive: "Making Grid's Rows Draggable"
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 152 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzYr33yyrbXXoqUL5:-KhSg63zPTELZgfqAaZp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L152)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please also explain how all the dragging works, e.g. if the selection mode is `MULTI`, then when dragging the selected row, all the selected rows are dragged.
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRu4TGJieuUyz7Uq3W:-KhSGf77MopDAVZomI8h:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L165)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> bean

replace with _item_
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRunJPU_FPGqPGMHab:-KhSQ_WtphkE1ryvX6BY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L173)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> defines what data should be transferred

Could you please refer to how it is transferred, e.g. link the HTML5 property it is set for
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 177 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRv196wMBaCM99aB7E:-KhSRJfYkq-ta66cXP9A:b-p1mg37) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L177)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Note that setting the data transfer text is not supported.

Isn't this the only thing that is supported ??? E.g. what the type is for the data that the generator uses, maybe you should mention explicitly what is not supported
</blockquote></details>

Done. I didn't mean that setting _text_ is not supported but that _data transfer text_ parameter cannot be set because it is already used. Is the mentioning of the method better? Is it necessary?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS2L8SUz1XMvdkJk0V:-KhSS4pX76J3AtYayvJX:b9a1ch2) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L178)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please also fix the javadocs for `GridDragSource:setDataTransferText` by overriding them an mentioning that it is not supported, instead of inheriting the javadocs from parent
</blockquote></details>

That is very valid. Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 196 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRwRT66slLji5GhcJr:-KhSUImcpzODygVW6lIv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L196)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think you should explicitly mention (in text) that the framework provides the grid's dragged rows in the event automatically
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 198 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRxojjdl0M5SS9kXZS:-KhSUNkz1De0RtwG8HF4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L198)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Grid Drop Target

"Grid As A Drop Target" or "Making Grid's Rows Drop Targets"
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 200 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzpb-4Fjal7E25HDw:-KhSUiaPb6yH6mjuL3JK:b-svn70x) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L200)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> define

specify, also how 'bout:

"When creating the extension, you need to define where the transferred data can be dropped on.
</blockquote></details>

So what happened to specify? ;)
Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 213 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS3qTJkV8qZbMuoXf5:-KhSVKAWG69GwM97W33s:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L213)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> when an element is dropped onto a row or between rows.

Replace with "...when data is dropped to the grid."
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 218 at r1](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhRzy2Rj2H1eZarM-PZ:-KhSVbcc9cJdIUj8pJhs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb070e73508d6c9a2ea8984f960c6f050f49ddf1/documentation/advanced/advanced-dragndrop.asciidoc#L218)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

..another Grid in the same UI
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPuevPNr65z0GWBpH:-KhTPuevPNr65z0GWBpI:b-i9yjbb) (no related file):*
You should add a link to the grid DND part to the grid component documentation _documentation/components/components-grid.asciidoc_. Just pick a nice spot for that, maybe a subtopic that only just refers to look up this documentation for now ? You should be able to see examples of how to make the link with the correct paths and everything...

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 148 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPqatgYO4PsOU6JnB:-KhTPqatgYO4PsOU6JnC:b-xj1qns) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L148)):*
> elements

data

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPGiO5r0lQrySeerG:-KhTPGiO5r0lQrySeerH:bwlh485) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L155)):*
> ```AsciiDoc
> When the Grid's selection mode is `SelectionMode.MULTI` and multiple rows are selected, it is possible to drag all the visible selected rows by grabbing one of them. However, when the grabbed row is not selected, only that one row will be dragged.
> 
> You can define the allowed effects and provide a drag data generator.
> ```

I think the custom has been, that refer to the example instead of the person, e.g.
"The following example shows how you can define the allowed drag effect and customize the drag data with the drag data generator."

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTP-keU6rlIOll59rC:-KhTP-keU6rlIOll59rD:b-3viihb) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L174)):*
> ```AsciiDoc
> ----
> 
> The _drag data generator_ defines what data should be transferred when a row is dragged and dropped. The generator is executed for every inserted item and returns a `JsonObject` containing the data to be transferred for that item. The generated data is transferred as a JSON array using the HTML5 DataTransfer's data parameter of type `"text"`.
> ```

What is the default data set, if you don't add your own generator ?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 178 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTObRJCPYMxCjVbbYC:-KhTObRJCPYMxCjVbbYD:b-nrj6b5) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L178)):*
> ```AsciiDoc
> [NOTE]
> ====
> Note that calling the `setDataTransferText(String data)` method is not supported.
> ```

Could be more specific, "calling the inherited foobar method is not supported, since the drag data is set for each row based on the generator data."

---

*[server/src/main/java/com/vaadin/ui/GridDragSource.java, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTNKbw7hFBunWgcUys:-KhTNKbw7hFBunWgcUyt:b-ji20of) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/server/src/main/java/com/vaadin/ui/GridDragSource.java#L155)):*
> ```Java
>     /**
>      * Setting the data transfer text for this drag source is not supported.
>      */
> ```

`@throws UnsupportedOperationException`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhS-mLALBrxgvzniT0w:-KhTphiILsA2FN6wnWS3:b-xt6rm5) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You should add a server side test class that verifies at least that the code snippets compile, plus would be also to verify that the code works. Can you 
</blockquote></details>

There is an example for Sampler that is waiting for styling and now I updated the `GridDragAndDrop` UI test for validating the code examples and dnd functionality.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPuevPNr65z0GWBpH:-KhTvR5V1GrXHaa-5y7P:bt3fcj5) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You should add a link to the grid DND part to the grid component documentation _documentation/components/components-grid.asciidoc_. Just pick a nice spot for that, maybe a subtopic that only just refers to look up this documentation for now ? You should be able to see examples of how to make the link with the correct paths and everything...
</blockquote></details>

Added a short mentioning of DnD

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 148 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPqatgYO4PsOU6JnB:-KhT_dUKpOl0nsm64we0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L148)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> elements

data
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTPGiO5r0lQrySeerG:-KhTgclfSfZgj0Fcil76:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L155)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think the custom has been, that refer to the example instead of the person, e.g.
"The following example shows how you can define the allowed drag effect and customize the drag data with the drag data generator."
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTP-keU6rlIOll59rC:-KhTlWol9Y19CFVhXYrT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L174)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

What is the default data set, if you don't add your own generator ?
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 178 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTObRJCPYMxCjVbbYC:-KhTmEi_LHBXlvId_XlO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/documentation/advanced/advanced-dragndrop.asciidoc#L178)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could be more specific, "calling the inherited foobar method is not supported, since the drag data is set for each row based on the generator data."
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/GridDragSource.java, line 155 at r2](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhTNKbw7hFBunWgcUys:-KhTnBfnv1O_WnOhXu9u:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cd52cc8380953be16edb676916e50fbbc6a70cf7/server/src/main/java/com/vaadin/ui/GridDragSource.java#L155)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

`@throws UnsupportedOperationException`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by pleku** [comment]
Reviewed 3 of 4 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 177 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW-KK3EK-RC7DHPFAl:-KhW-KK3EK-RC7DHPFAm:bzefh0b) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L177)):*
> `GridConnector.getDataSource().getRow(index)` method.

This basically tells nothing and forces people to look up what that is. While it is also a good thing, I'd prefer to explain it here a bit, e.g.:
", the whole row data as JSON is transferred. You can look up the format from the foobar method."

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 215 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW1ayo8ymf25-lfbtq:-KhW1ayo8ymf25-lfbtr:b-ub0ck2) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L215)):*
> Bean

oops, please do a search and replace all in these code samples

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 244 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW-uVZolwApcleZp0Y:-KhW-uVZolwApcleZp0Z:b9anqwa) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L244)):*
> ```AsciiDoc
>             dataProvider.refreshAll();
> 
>             log("dragData=" + event.getDataTransferText());
> ```

This seems a bit weird in this context, you might replace this with 
```java
// Show the dropped data
Notification.show("Dropped row data: " + event.getDataTransferText());
```

or just remove completely from here

---

*[documentation/components/components-grid.asciidoc, line 851 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW0ZLPaBP_7AqhI0Vg:-KhW0ZLPaBP_7AqhI0Vh:bap20t4) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/components/components-grid.asciidoc#L851)):*
>  Drag and Drop Rows

Drag and Drop of Rows

---

*[documentation/components/components-grid.asciidoc, line 854 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW0N7hTCERKqbej96Q:-KhW0N7hTCERKqbej96R:bwm9qyu) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/components/components-grid.asciidoc#L854)):*
> "Drag and Drop documentation"

Usually we have the exact same header title in the link, here it would be "Drag and Drop Rows in Grid"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by pleku** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 177 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW-KK3EK-RC7DHPFAl:-KhX1rqu2yC-bHKR1j-L:b-gdn7jz) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L177)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> `GridConnector.getDataSource().getRow(index)` method.

This basically tells nothing and forces people to look up what that is. While it is also a good thing, I'd prefer to explain it here a bit, e.g.:
", the whole row data as JSON is transferred. You can look up the format from the foobar method."
</blockquote></details>

Went a slightly different way, take a look and see if you like it

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 215 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW1ayo8ymf25-lfbtq:-KhWmftY5HeHKQ7wlQyW:by64cwn) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L215)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Bean

oops, please do a search and replace all in these code samples
</blockquote></details>

Weird, I thought I did a search. Anyway, gone now.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 244 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW-uVZolwApcleZp0Y:-KhWnN4QFYeC-2UJScTw:b-82figj) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/advanced/advanced-dragndrop.asciidoc#L244)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This seems a bit weird in this context, you might replace this with 
```java
// Show the dropped data
Notification.show("Dropped row data: " + event.getDataTransferText());
```

or just remove completely from here
</blockquote></details>

I wanted to include that so that it would be documented how to get the drag data since it is not obvious.
I think better leave it and I also mentioned it in the description for clarity's sake

---

*[documentation/components/components-grid.asciidoc, line 851 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW0ZLPaBP_7AqhI0Vg:-KhX2Ikz5bYqmH8oA7LM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/components/components-grid.asciidoc#L851)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  Drag and Drop Rows

Drag and Drop of Rows
</blockquote></details>

Done.

---

*[documentation/components/components-grid.asciidoc, line 854 at r3](https://reviewable.io:443/reviews/vaadin/framework/9055#-KhW0N7hTCERKqbej96Q:-KhX2aTC8TUtG28TNB12:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2f029385040793211fafb3f57fc4bc78edbe0174/documentation/components/components-grid.asciidoc#L854)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> "Drag and Drop documentation"

Usually we have the exact same header title in the link, here it would be "Drag and Drop Rows in Grid"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055#-:-KhX3ctuM-u9dtdtl3sE:bnfp4nl)*

**Comment by ahie** [comment]
Looks like this needs a manual merge.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055#-:-KhX3oTOQeZOZEbd8gVG:b6q5hdw)*

**Comment by pleku** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055#-:-KhYltxjEv7rrlddUTmi:bnfp4nl)*

**Comment by wbadam** [comment]
As Pekka requested, rebased this to master

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9055)*

**Pull request merged**
