### PR TITLE
Add missing since tags for 8.1.0.alpha1

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8888)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8888#-KfklUqheQFuzGh1hT_d:-KfklUqi8rNLPa-xFy0f:b-xa1l9j) (no related file):*
I don't think the `DataCommunicator` is supposed to get empty `@since` tags ? I think all of those have been added in 8.1.0.alpha1 because `HierarchicalDataCommunicator` uses those methods

---

*[shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8888#-Kfklf851XOezdlllwDL:-Kfklf851XOezdlllwDM:b-8gyrnv) ([raw file](https://github.com/vaadin/framework/blob/ee1826f6541683505f4a55b02ed2b1e802a8009a/shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java#L66)):*
> ```Java
>      * @param count
>      *            the number of rows inserted
>      * @since
> ```

8.1 ?

---

*[shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/8888#-KfklgO__b8T0ab9qr8O:-KfklgO__b8T0ab9qr8P:b-8gyrnv) ([raw file](https://github.com/vaadin/framework/blob/ee1826f6541683505f4a55b02ed2b1e802a8009a/shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java#L78)):*
> ```Java
>      *            the number of removed rows, starting from
>      *            <code>firstRowIndex</code>
>      * @since
> ```

8.1 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8888)*

**Comment by hesara** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8888#-Kfklf851XOezdlllwDL:-Kfkn_k2BR0BHD0wB2M6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee1826f6541683505f4a55b02ed2b1e802a8009a/shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java#L66)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

8.1 ?
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/8888#-KfklgO__b8T0ab9qr8O:-Kfkn_IeYC56htMt8J9W:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee1826f6541683505f4a55b02ed2b1e802a8009a/shared/src/main/java/com/vaadin/shared/data/DataCommunicatorClientRpc.java#L78)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

8.1 ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8888)*

**Comment by hesara** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8888#-KfklUqheQFuzGh1hT_d:-Kfknb_0nPTo46yKQ4l8:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I don't think the `DataCommunicator` is supposed to get empty `@since` tags ? I think all of those have been added in 8.1.0.alpha1 because `HierarchicalDataCommunicator` uses those methods
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8888)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8888)*

**Pull request merged**
