### PR TITLE
Update advanced-dragndrop.asciidoc

### PR DESCRIPTION
**Pull request by anasmi**
Fixing example of Drag and drop code.
Resolves https://github.com/vaadin/framework/issues/10512

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10680)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 462 at r1](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6qTdH4TLMjWoFAexog:-L6qTdH4TLMjWoFAexoh:b-k10qpq) ([raw file](https://github.com/vaadin/framework/blob/a9a493b5770e2b47500c8425ef643d41f22ccec4/documentation/advanced/advanced-dragndrop.asciidoc#L462)):*
> ```AsciiDoc
>                             }
>                     return null;
>                        
> ```

extra spaces

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 498 at r1](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6qTfMNPMQPp9HKarhd:-L6qTfMNPMQPp9HKarhe:b-k10qpq) ([raw file](https://github.com/vaadin/framework/blob/a9a493b5770e2b47500c8425ef643d41f22ccec4/documentation/advanced/advanced-dragndrop.asciidoc#L498)):*
> ```AsciiDoc
>                         + event.getFileName());
>                 }
>                 
> ```

extra spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Comment by anasmi** [comment]
*[documentation/advanced/advanced-dragndrop.asciidoc, line 462 at r1](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6qTdH4TLMjWoFAexog:-L6tklg6W7Vi_-bCnndg:b-896fjx) ([raw file](https://github.com/vaadin/framework/blob/a9a493b5770e2b47500c8425ef643d41f22ccec4/documentation/advanced/advanced-dragndrop.asciidoc#L462)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Comment by anasmi** [comment]
*[documentation/advanced/advanced-dragndrop.asciidoc, line 498 at r1](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6qTfMNPMQPp9HKarhd:-L6tkooTX2q8Cupj-wFQ:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/a9a493b5770e2b47500c8425ef643d41f22ccec4/documentation/advanced/advanced-dragndrop.asciidoc#L498)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 461 at r2](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6uqcbSE23pZNeaMkG3:-L6uqcbSE23pZNeaMkG4:b-j27twb) ([raw file](https://github.com/vaadin/framework/blob/4a353cee684351808f71b29e62c47f7449cff082/documentation/advanced/advanced-dragndrop.asciidoc#L461)):*
> ```AsciiDoc
>                                 e.printStackTrace();
>                             }
>                     return null;       
> ```

Now they are here

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 497 at r2](https://reviewable.io:443/reviews/vaadin/framework/10680#-L6uqfiSs4NjjTRpCkJO:-L6uqfiSs4NjjTRpCkJP:b-wcz647) ([raw file](https://github.com/vaadin/framework/blob/4a353cee684351808f71b29e62c47f7449cff082/documentation/advanced/advanced-dragndrop.asciidoc#L497)):*
> ```AsciiDoc
>                         + event.getFileName());
>                 }
>                 
> ```

No changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10680)*

**Pull request merged**
