### PR TITLE
Add View.beforeLeave to support delayed navigation

### PR DESCRIPTION
**Pull request by Artur-**
Using View.beforeLeave you can delay navigation so that you can
e.g. show a confirmation popup to the user and only invoke the navigation
if the user confirms it in the popup

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9539)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/View.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/9539#-KmfKYA5eOfe_fNog-_7:-KmfKYA5eOfe_fNog-_8:bnt566h) ([raw file](https://github.com/vaadin/framework/blob/42f7a7ddfa1483bf0b2f3509f40d8eb388d94429/server/src/main/java/com/vaadin/navigator/View.java#L64)):*
> added{@link ViewChangeListener}s.
missing space

---

*[server/src/main/java/com/vaadin/navigator/ViewBeforeLeaveEvent.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/9539#-KmfLR4xY5i4N25oRFqB:-KmfLR4xY5i4N25oRFqC:b-yc0crg) ([raw file](https://github.com/vaadin/framework/blob/42f7a7ddfa1483bf0b2f3509f40d8eb388d94429/server/src/main/java/com/vaadin/navigator/ViewBeforeLeaveEvent.java#L49)):*
> ```Java
>      * Performs the navigation which triggered the event in the first place.
>      */
>     public void navigate() {
> ```

should this method prevent multiple navigations with the same event ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9539)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/View.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/9539#-KmfKYA5eOfe_fNog-_7:-KmjouyumXqRWRrxwwNf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/42f7a7ddfa1483bf0b2f3509f40d8eb388d94429/server/src/main/java/com/vaadin/navigator/View.java#L64)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> added{@link ViewChangeListener}s.
missing space
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/navigator/ViewBeforeLeaveEvent.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/9539#-KmfLR4xY5i4N25oRFqB:-KmjpA0vXMDIzQ2iC-qW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/42f7a7ddfa1483bf0b2f3509f40d8eb388d94429/server/src/main/java/com/vaadin/navigator/ViewBeforeLeaveEvent.java#L49)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should this method prevent multiple navigations with the same event ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9539)*

**Comment by tsuoanttila** [comment]
@hesara or @elmot, take a final look and merge if you think this is good.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9539#-:-Kmk90hE8OH1dj3BtyuX:bnuxir0)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9539#-:-Kn2Vp_OC6VwRnmrRYGL:bnfp4nl)*

**Pull request merged**
