### PR TITLE
Fix Column.setSortable being overridden

### LINKED ISSUE #10467: Grid.Column#setSortable(false) has no effect
Using Grid with a "simple Datasource (setItems(List))" and adding columns with #setSortable(false) has no effect. 

## Code Example:

        grid.addColumn(Entity::getA).setSortable(false).setCaption("A");
        grid.addColumn(Entity::getB).setCaption("B");

## Expectation:

- [x] Column 'A' should **not be sortable** and there should be **no stylename** 'sortable'.
- [x] Column 'B' should be sortable and there should be a stylename 'sortable'.

## Current behaviour:

- [ ] Column 'A' _is sortable_ and _has the stylename_ 'sortable'.
- [x] Column 'B' is sortable and has the stylename 'sortable'.

Version:
- Vaadin Version: 8.2.0 & 8.3-SNAPSHOT

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #10467 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10604)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 844 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4aMLFHN_rGpPBVunlt:-L4aMLFHN_rGpPBVunlu:b-g7zlba) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L844)):*
> ```Java
>         };
> 
>         private boolean sortable = true;
> ```

is it correct to have `true` as the default?  

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1221 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4aM4fC0YjdL2A-Zkfi:-L4aM4fC0YjdL2A-Zkfj:b-i7uiaj) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L1221)):*
> ```Java
>          * @return {@code true} if the column can be sorted by the user;
>          *         {@code false} if not
>          */
> ```

Missing `@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 844 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4aMLFHN_rGpPBVunlt:-L4bCLMTLtFv82WmeJBD:b-vrl9ba) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L844)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

is it correct to have `true` as the default?  
</blockquote></details>

the old default was "depends on the data provider and sort order" current implementation is "if sortable, then depends on the data provider and sort order" so I'd say it's correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4eOoc_EPM2TwCrXqzY:-L4eOoc_EPM2TwCrXqzZ:b-lf4vau) (no related file):*
@anasmi, please have a look

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by anasmi** [comment]
*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 770 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4e_ZKsPF1dEkbReGlO:-L4e_ZKsPF1dEkbReGlP:bjcxv1k) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L770)):*
> ```Java
>         Assert.assertTrue("Column should be initially sortable",
>                 column.isSortable());
>         Assert.assertFalse("User should not be able to sort the column",
> ```

I still have some misunderstanding regarding sortable properties.
- The first test asserts true for both isSortable and isSortablebyUser, since we are using in-memory data Provider. 
- The behavior of the second test is straightforward.
- Then the third test a bit confusing. Since we don't have in memory DtaProvider and there is no sort order set, it's not sortable by user, but then what effect setSortable(true) has in this case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/Grid.java, line 1172 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4ebccx4xOCQ0FHiEkG:-L4ebccx4xOCQ0FHiEkH:b-r2ilfe) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L1172)):*
> ```Java
>                     .count() != 0;
> 
>             getState().sortable = this.sortable && (inMemory || hasSortOrder);
> ```

Should value of sortable in state be the same as local sortable value here? For example, this.sortable and getState().sortable=false. We are setting new dataProvider and setSortable(true). Then this.sortable=true, but getState().sortable can remain false, if the dataProvider is not in memory as well there is no sortOrder;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4fDf5k53Z1ZyEPMqL9:-L4fDf5k53Z1ZyEPMqLA:b-53l71s) (no related file):*
The patch changes Declarative Vaadin behavior (see tests results). And looks like it just reverts the changes made with #10190 to be more correct. Anyway,  `GridDeclarativeTest#columnAttributes` is not fully run (there is a check for one value of `sortable`). That should be fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by tsuoanttila** [comment]
*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 770 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4e_ZKsPF1dEkbReGlO:-L4jhbLe7hQBTyeT_Vnd:b-bazcb) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L770)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

I still have some misunderstanding regarding sortable properties.
- The first test asserts true for both isSortable and isSortablebyUser, since we are using in-memory data Provider. 
- The behavior of the second test is straightforward.
- Then the third test a bit confusing. Since we don't have in memory DtaProvider and there is no sort order set, it's not sortable by user, but then what effect setSortable(true) has in this case?
</blockquote></details>

When the DataProvider is made from callbacks, the column should have the sort order defined to be really sortable. Added this case to the test as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4fDf5k53Z1ZyEPMqL9:-L4jh-tX99l2cXZhZ1XK:bkj8y4u) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The patch changes Declarative Vaadin behavior (see tests results). And looks like it just reverts the changes made with #10190 to be more correct. Anyway,  `GridDeclarativeTest#columnAttributes` is not fully run (there is a check for one value of `sortable`). That should be fixed.
</blockquote></details>

Fixed the test and renamed some parts to make it clearer that both sortable and not sortable are tested.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1172 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4ebccx4xOCQ0FHiEkG:-L4jhAUFoGuIyzCb8naK:bp4pdb1) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L1172)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Should value of sortable in state be the same as local sortable value here? For example, this.sortable and getState().sortable=false. We are setting new dataProvider and setSortable(true). Then this.sortable=true, but getState().sortable can remain false, if the dataProvider is not in memory as well there is no sortOrder;
</blockquote></details>

If you're using a CallbackDataProvider, the only we we can tell of the sorting to the "backend" is to provide it with a sortOrder. If there is no sortOrder, sorting will not do anything, which will be confusing to the user who sees the sorting indicator but not sorting.

The current implementation in this patch is: Column is sortable if the application developer allows it to be sorted and the data provider can do it.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1221 at r1](https://reviewable.io:443/reviews/vaadin/framework/10604#-L4aM4fC0YjdL2A-Zkfi:-L4jh8walA-dj_TQ6qWy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/349f307b7bfcc3396219c6bfe5f370ca019b30de/server/src/main/java/com/vaadin/ui/Grid.java#L1221)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Missing `@since`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10604)*

**Pull request merged**
