### PR TITLE
Remove Google App Engine support, tests and documentation

### LINKED ISSUE #8033: Remove Google App Engine support, documentation and tests
Not supported in 8.0

### PR DESCRIPTION
**Pull request by pleku**
Fixes #8033

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8034)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLpAZxzw9U_WVl4XrU:-KZLpAZxzw9U_WVl4XrV:bfsteby) ([raw file](https://github.com/vaadin/framework/blob/adcc39e85db5678c3db5ef64708c68ece0781ae3/compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java#L16)):*
> ```Java
>  * the License.
>  */
> package com.vaadin.server;
> ```

should this have .v7?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLpAZxzw9U_WVl4XrU:-KZLq-kS_bwOvtp4U9rD:b-djhgxi) ([raw file](https://github.com/vaadin/framework/blob/adcc39e85db5678c3db5ef64708c68ece0781ae3/compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this have .v7?
</blockquote></details>

Then we'd have to change VaadinServlet methods from `protected` -> `public`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLpAZxzw9U_WVl4XrU:-KZLs7gMO5DAljkSB403:b-hqg20r) ([raw file](https://github.com/vaadin/framework/blob/adcc39e85db5678c3db5ef64708c68ece0781ae3/compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java#L16)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Then we'd have to change VaadinServlet methods from `protected` -> `public`
</blockquote></details>

TBC if the migration script can handle this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLw0VRAx_AA8JhTVsQ:-KZLw0VRAx_AA8JhTVsR:b8aa71w) (no related file):*
Adding a note here just so that this isn't accidentally merged before we tag the beta

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLw0VRAx_AA8JhTVsQ:-KZLy8JCwXBOPErbq_ZC:bcmq4yd) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Adding a note here just so that this isn't accidentally merged before we tag the beta
</blockquote></details>

Will need to rebase on top of #8038 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8034#-KZLpAZxzw9U_WVl4XrU:-KZLyFjRcp7g3nb_OWJv:by7anxh) ([raw file](https://github.com/vaadin/framework/blob/adcc39e85db5678c3db5ef64708c68ece0781ae3/compatibility-server/src/main/java/com/vaadin/server/GAEVaadinServlet.java#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC if the migration script can handle this
</blockquote></details>

Can handle this, and also it is not included in osgi bundle because of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8034#-:-KZLzgGLhmbAbxi1VRF5:bnfp4nl)*

**Pull request merged**
