### PR TITLE
Fix NPE in v7 compatibility Grid during datasource rebind

### PR DESCRIPTION
**Pull request by TobseF**
This fixes an **NPE** on the `com.vaadin.v7.client.widgets.Grid#setDataSource`. Calling it twice will cause a NPE because `dataSource.addDataChangeHandler(null);` is not allowed.

@see `ListDataSource`
> `com.vaadin.client.widget.grid.datasources.ListDataSource#addDataChangeHandler`
> `Objects.requireNonNull(dataChangeHandler,  "DataChangeHandler can't be null");`

@see `AbstractRemoteDataSource`
> `com.vaadin.client.data.AbstractRemoteDataSource#addDataChangeHandler`
> `Objects.requireNonNull(dataChangeHandler,  "DataChangeHandler can't be null");`
  
This broken behavior was introduced by
@OlliTietavainenVaadin in `8313623dd318c92aa49e9cf96268f5fff6ad6456` as
> v7 Grid performance improvements picked to compatibility package

This error is nasty because it happens only the second time you visit the component and it's only visible in JS Debug. So let's roll this line back to allow data rebind.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11473)

### CODE REVIEW

**Comment by anasmi** [comment]
Hi,

thank you for reporting the problem and submitting the pull request to address it! We will try to investigate it as soon as possible. I am not sure, why we are adding the null there overall, but we should definitely fix it, that code doesn't throw NPE.

Thanks again!

**Comment by TobseF** [comment]
I added as second commit the removal of the `DataChangeHandler`. Now it's just as in the v8 Grid. Likely this was the original intended behavior of setting the listener to `null`.

``` java
if (changeHandler != null) {
    changeHandler.remove();
    changeHandler = null;
}
```

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11473)* status: all files reviewed, 1 unresolved discussion (waiting on @TobseF)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11473#-LaKMOEV-5LQun2ZEJ9d:-LaKMOEV-5LQun2ZEJ9e:byjvi4k) (no related file):*
Hi @tobsef . Thanks for the fix, the changes look fine to me.

It is slightly troubling that this will fork the V7 compatibility package Grid even further from the (last) V7 version, but we've recently discovered that has already happened quite (too) much, and thus I do NOT see any good reason why we would use that grounds to block this change that fixes a valid issue in the compatibility package.

However, could you please add a test that fails without the fix to https://github.com/vaadin/framework/tree/master/uitest/src/test/java/com/vaadin/v7/tests/components/grid and with reusing and or adding a new test UI to https://github.com/vaadin/framework/tree/master/uitest/src/main/java/com/vaadin/v7/tests/components/grid

or reuse an existing

---

**Review by pleku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11473)* status: all files reviewed, 1 unresolved discussion (waiting on @TobseF)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11473#-LaKMOEV-5LQun2ZEJ9d:-LaKOXKV6oOtHaRxE_W8:b-kdfcjb) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Hi @tobsef . Thanks for the fix, the changes look fine to me.

It is slightly troubling that this will fork the V7 compatibility package Grid even further from the (last) V7 version, but we've recently discovered that has already happened quite (too) much, and thus I do NOT see any good reason why we would use that grounds to block this change that fixes a valid issue in the compatibility package.

However, could you please add a test that fails without the fix to https://github.com/vaadin/framework/tree/master/uitest/src/test/java/com/vaadin/v7/tests/components/grid and with reusing and or adding a new test UI to https://github.com/vaadin/framework/tree/master/uitest/src/main/java/com/vaadin/v7/tests/components/grid

or reuse an existing
</blockquote></details>

Here is more instructions on how to run an UI test https://github.com/vaadin/framework#running-a-ui-test

---

**Comment by anasmi** [comment]
@pleku tests added

From the repository you have mentioned, the tests are not running locally, so added to the general folder. Also noticed, that there are a couple of other V7 related tests there

**Review by pleku — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11473)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pleku — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11473#-:-LazSsRG7jCuaN_Uyzvb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by anasmi** [comment]
@pleku could you merge it also? (As you did the review and then we don't need to update the branch to be even with master) Thanks!

**Pull request merged**
