### PR TITLE
Add complex navigation to CDI test

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10226)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This patch depends on ViewContextStrategy changes in vaadin/cdi#212 . It contains a few workarounds to make PushStateNavigation work on a basic level. These changes have to be moved to the CDI and not the test code.

**Comment by asashour** [comment]
Review status: 0 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/DefaultView.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-KwtscVCMyPybloGjUPy:-KwtscVDdYD4s0jB17x7:b-byfdrb) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/DefaultView.java#L24)):*
> ```Java
>                 e -> Notification.show(service.getText()));
>     }
> }
> ```

New line

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingService.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwtsh-ijgA6Kcjf7eUQ:-Kwtsh-ijgA6Kcjf7eUR:b-byfdrb) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingService.java#L21)):*
> ```Java
>         return count;
>     }
> }
> ```

New line

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingView.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-KwtsjF2RUkx_vVHTtEm:-KwtsjF2RUkx_vVHTtEn:b-byfdrb) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingView.java#L52)):*
> ```Java
>         greet(event.getParameters());
>     }
> }
> ```

New line

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwu37qG0wbhc9NCcW_8:-Kwu37qG0wbhc9NCcW_9:b-dn4jd5) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java#L23)):*
> ```Java
> public class CDINavigationIT extends ParallelTest {
> 
>     protected static String BASE_URL = "http://localhost:8080";
> ```

Can be `final`, not blocker.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwu-h2lL91ke1_35sWL:-Kwu-h2lL91ke1_35sWM:byy1pbv) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java#L56)):*
> ```Java
> 
>         getDriver().navigate().refresh();
>         Assert.assertTrue(isElementPresent(By.id("name")));
> ```

Can we have `import start ...Assert.*`?    Not a blocker.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwu31mLUrvBz3RDkUku:-Kwu31mLUrvBz3RDkUkv:b-dn4jd5) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java#L31)):*
> ```Java
> public class VaadinCDISmokeIT extends ParallelTest {
> 
>     private static String BASE_URL = "http://localhost:8080/";
> ```

Can be `final`, not blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Comment by tsuoanttila** [comment]
Ignored test should pass after vaadin/cdi#227

**Comment by denis-anisimov** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-L-q--bq6z7ftmhv2JAg:-L-q--bq6z7ftmhv2JAh:b9q4g7z) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java#L178)):*
> sleep();

Why not wait until it happens instead of `sleep`  with the time which might be not enough ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/DefaultView.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-KwtscVCMyPybloGjUPy:-L0EXQX7v_jz3UaEmm-R:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/DefaultView.java#L24)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingService.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwtsh-ijgA6Kcjf7eUQ:-L0EXT9oddeMd_Z2b_1b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingService.java#L21)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingView.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-KwtsjF2RUkx_vVHTtEm:-L0EXVdtVBox1ko55Qtm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/main/java/com/vaadin/test/cdi/views/GreetingView.java#L52)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwu37qG0wbhc9NCcW_8:-L0EXWR1xYGTdfPNzKcU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/CDINavigationIT.java#L23)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Can be `final`, not blocker.
</blockquote></details>

Done.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-Kwu31mLUrvBz3RDkUku:-L0EXcUQ6NL_q0j5ydFb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java#L31)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Can be `final`, not blocker.
</blockquote></details>

Done.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/10226#-L-q--bq6z7ftmhv2JAg:-L0EXgmyEwxbJdOgIRTX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7c3526b9271c966d7ab7638418a5f87e14024a06/test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java#L178)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> sleep();

Why not wait until it happens instead of `sleep`  with the time which might be not enough ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Comment by tsuoanttila** [comment]
Rebased and using correct CDI version. The CDI is still in staging so this should not pass validation.

---

Review status: 7 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226#-:-L0EYWPhDneEEzf_LNl0:b-kh8lrd)*

**Comment by tsuoanttila** [comment]
Rebased.

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: 8 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 10 files at r3.
Review status: 11 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Comment by ahie** [comment]
Reviewed 5 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10226)*

**Pull request merged**
