### PR TITLE
Added IT for using SpringNavigator

### PR DESCRIPTION
**Pull request by pleku**
Updated current spring-boot module, and added another module with sub context path.
This is for verifying changes proposed in #8209 for Spring Vaadin integration.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8507)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlRJ4X8oGuwrLoog4:-KcSlRJ4X8oGuwrLoog5:b-linsjf) (no related file):*
Is empty application.properties file needed at all ?

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSjmZ1AFvUUhg9n9gE:-KcSjmZ1AFvUUhg9n9gF:bqvbono) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L48)):*
> ```Java
> 
> @SpringUI
> class RootPathUI extends AbstractSpringUI {
> ```

It's quite confusing when many classes are inside one  file.
Would be better to have each class in its own file.

Usually this is done in cases to demo a source code so that everything is visible on the screen.
Or there are serious reasons to "hide" classes.
But it's hard to maintain the code when one file contains a lot of unrelated classes.

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 194 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSjj5UAljS_lI4Lj46:-KcSjj5UAljS_lI4Lj47:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L194)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

new line

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSknh6fPjhJEvCQuPz:-KcSknh6fPjhJEvCQuQ-:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

new line

---

*[test/spring-boot/src/main/java/com/example/DemoApplication.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlC9iZNUGB9jvxy6q:-KcSlC9jXjus_MmZLCa9:brqgyo3) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/DemoApplication.java#L37)):*
> ```Java
> 
> @SpringUI
> class RootPathUI extends AbstractSpringUI {
> ```

same here : al classes in one file

---

*[test/spring-boot/src/main/java/com/example/DemoApplication.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlGOPqV4hrM9WpI71:-KcSlGOPqV4hrM9WpI72:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/DemoApplication.java#L183)):*
> ```Java
>     public void enter(ViewChangeEvent event) {
>     }
> }
> ```

new line

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlIoB7N5Lm9szmZry:-KcSlIoB7N5Lm9szmZrz:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8507)*

**Comment by hesara** [comment]
Reviewed 10 of 12 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java, line 101 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlii5795jMIyKGiNv:-KcSlii5795jMIyKGiNw:be2drme) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/DemoApplication.java#L101)):*
> ```Java
>         final VerticalLayout root = new VerticalLayout();
>         root.setSizeFull();
>         root.setMargin(true);
> ```

(now margin and spacing are on by default for VerticalLayout - here and elsewhere)

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 5 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSiM1k7OLDqk9vAgfV:-KcSiM1k7OLDqk9vAgfW:bce8ic4) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L5)):*
> ```Java
> import com.vaadin.spring.annotation.SpringComponent;
> 
> @SpringComponent
> ```

No scope defined? Is the string below really correct then?

---

*[test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSi-xCGglpzHaM4xk7:-KcSi-xCGglpzHaM4xk8:b5habg3) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

(LF at end of file)

---

*[test/spring-boot-subcontext/src/test/java/com/example/VaadinSpringBootSmokeIT.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSjt_NQHX4LNQ06PON:-KcSjt_NQHX4LNQ06POO:b-g7ebjr) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot-subcontext/src/test/java/com/example/VaadinSpringBootSmokeIT.java#L22)):*
> ```Java
> import com.vaadin.testbench.parallel.Browser;
> 
> /**
> ```

(empty javadoc)

---

*[test/spring-boot/src/main/java/com/example/DemoApplication.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSlK_Z_trhsmF9Zfos:-KcSlK_Z_trhsmF9Zfot:b-4vcvby) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/DemoApplication.java#L28)):*
> ```Java
> 
> @SpringBootApplication
> public class DemoApplication {
> ```

(duplication between various classes in the change, would probably require a new module to eliminate this)

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 5 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSiTofzsjkKPfg-igV:-KcSiTofzsjkKPfg-igW:bce8ic4) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L5)):*
> ```Java
> import com.vaadin.spring.annotation.SpringComponent;
> 
> @SpringComponent
> ```

No scope defined? Is the string below really correct then?

---

*[test/spring-boot/src/main/java/com/example/ViewGreeter.java, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/8507#-KcSi87xTgIg_xfT168G:-KcSi87yy_2tZSbBC-d3:b5habg3) ([raw file](https://github.com/vaadin/framework/blob/2b37a26d046a6030b083638ebc7bf79529ef4ce7/test/spring-boot/src/main/java/com/example/ViewGreeter.java#L13)):*
> ```Java
>                 + toString();
>     }
> }
> ```

(LF at end of file)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8507)*

**Comment by hesara** [comment]
The relevant framework PR is now #10042, and the UI needs the annotation PushStateNavigation as it is not the default mode.

**Comment by hesara** [comment]
Superceded by #10174.

**Pull request closed without merging**
