### PR TITLE
Use interface instead of implementation

### PR DESCRIPTION
**Pull request by asashour**
There two public method signature changes, I believe internal.

Also, there are some formatting changes, although I use `Vaadin Java Conventions 20140408` with Eclipse Oxygen.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10073)

### CODE REVIEW

**Comment by hesara** [comment]
First very quick review pass of obviously non-controversial changes.

---

Reviewed 117 of 131 files at r1.
Review status: 117 of 131 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073#-:-Kus-mHBl67BYuId4Xt7:b-mo7zok)*

**Comment by tsuoanttila** [comment]
Reviewed 12 of 131 files at r1.
Review status: 128 of 131 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 994 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-KuxL873NtmzRgme-NDN:-KuxL873NtmzRgme-NDO:b-5xmp2u) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L994)):*
> ```Java
>                 : null);
>         nc.propertyIds = propertyIds != null
>                 ? (ArrayList<Object>) ((ArrayList<Object>) propertyIds).clone()
> ```

Why is there two casts in this ?

Should we use `new ArrayList<>(propertyIds)` instead of `Object::clone` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073)*

**Comment by asashour** [comment]
Review status: 127 of 134 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java, line 994 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-KuxL873NtmzRgme-NDN:-KuxlwsvNeCjCVDRWE-g:b448h3h) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/compatibility-server/src/main/java/com/vaadin/v7/data/util/IndexedContainer.java#L994)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is there two casts in this ?

Should we use `new ArrayList<>(propertyIds)` instead of `Object::clone` ?
</blockquote></details>

Done. Nice idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073)*

**Comment by hesara** [comment]
Reviewed 3 of 131 files at r1, 2 of 4 files at r2, 17 of 17 files at r3.
Review status: 129 of 132 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073)*

**Comment by hesara** [comment]
There are three classes not marked as reviewed due to slight doubts they might cause problems e.g. with some add-ons. While the risk for each of them is low, I'd anyway suggest reverting those changes to get the rest of these changes merged and not leave this hanging.

In addition, there is one change you made where @tsuoanttila needs to mark his earlier comment as resolved.

---

Review status: 129 of 132 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/TouchScrollDelegate.java, line 421 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62fZ1KGwLLez4ORrI:-Kv62fZ1KGwLLez4ORrJ:b7vootm) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/client/src/main/java/com/vaadin/client/ui/TouchScrollDelegate.java#L421)):*
> ```Java
>     }
> 
>     public static List<Element> getElements(Element scrolledElement2) {
> ```

this could potentially cause problems in case an add-on uses this method

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 653 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62soR-37p0qeR_0Nl:-Kv62soR-37p0qeR_0Nm:b-jpw6f2) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L653)):*
> ```Java
>      * @return A list of dirty and visible connectors.
>      */
>     public List<ClientConnector> getDirtyVisibleConnectors() {
> ```

this change could potentially cause some problems

---

*[shared/src/main/java/com/vaadin/shared/ui/orderedlayout/AbstractOrderedLayoutState.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62xGMhzHpKYNKr9S1:-Kv62xGMhzHpKYNKr9S2:b-ozu2a) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/shared/src/main/java/com/vaadin/shared/ui/orderedlayout/AbstractOrderedLayoutState.java#L29)):*
> ```Java
>     public boolean spacing = false;
> 
>     public Map<Connector, ChildComponentData> childData = new HashMap<>();
> ```

this change could potentially cause some problems for some add-ons extending AbstractOrderedLayout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073#-:-Kv62BtBwBthE3pGY7-1:biobhft)*

**Comment by asashour** [comment]
Review status: 128 of 130 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/TouchScrollDelegate.java, line 421 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62fZ1KGwLLez4ORrI:-Kv69Y9dW7y_h9AUFwmf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/client/src/main/java/com/vaadin/client/ui/TouchScrollDelegate.java#L421)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this could potentially cause problems in case an add-on uses this method
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 653 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62soR-37p0qeR_0Nl:-Kv69aliLLnv4ARN1T5P:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L653)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this change could potentially cause some problems
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/orderedlayout/AbstractOrderedLayoutState.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/10073#-Kv62xGMhzHpKYNKr9S1:-Kv69cVGm97DGTmFaVx4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0bf3773cd53141059b7a6e28ca5a0959a92e9688/shared/src/main/java/com/vaadin/shared/ui/orderedlayout/AbstractOrderedLayoutState.java#L29)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this change could potentially cause some problems for some add-ons extending AbstractOrderedLayout
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073)*

**Comment by hesara** [comment]
:lgtm: - waiting for @tsuoanttila to resolve his comment

---

Reviewed 2 of 131 files at r1, 1 of 4 files at r4.
Review status: 129 of 130 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073#-:-Kv69qRhel4bjoCe28N-:b-7ckgrw)*

**Comment by hesara** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10073)*

**Pull request merged**
