### PR TITLE
Refer to Vaadin Framework in release notes

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8006)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8006#-KZ1axp9dnMe9Syt95Gg:-KZ1axp9dnMe9Syt95Gh:b-6fidx4) ([raw file](https://github.com/vaadin/framework/blob/70c06c6d11e158fb2c2b0d428eb4a1be515372d6/all/src/main/templates/release-notes.html#L48)):*
> ```HTML
>                     @version-minor@</a></li>
>             <li><a href="#knownissues">Known Issues and Limitations</a></li>
>             <li><a href="#framework">Vaadin Framework Installation</a></li>
> ```

(I find "installation" a not very suitable term, but this is old text)

---

*[all/src/main/templates/release-notes.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/8006#-KZ1aXSqlcWUfu8is2rO:-KZ1aXSqlcWUfu8is2rP:br4m4cn) ([raw file](https://github.com/vaadin/framework/blob/70c06c6d11e158fb2c2b0d428eb4a1be515372d6/all/src/main/templates/release-notes.html#L87)):*
> ```HTML
>             <li>Vaadin Framework is now based on Java 8</li>
>             <li>Vaadin Framework is using GWT 2.8, allowing client side code to use Java 8</li>
>             <li>Other Framework dependencies including Atmosphere have been upgraded</li>
> ```

(this might change the perceived meaning a little, but not a blocker IMO)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8006)*

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[all/src/main/templates/release-notes.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8006#-KZ1axp9dnMe9Syt95Gg:-KZ1l5HsbGzdQMVbKh8i:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/70c06c6d11e158fb2c2b0d428eb4a1be515372d6/all/src/main/templates/release-notes.html#L48)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I find "installation" a not very suitable term, but this is old text)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8006)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8006#-:-KZ1wBel9-5TaHBMCezD:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8006)*

**Pull request merged**
