### PR TITLE
Add "deselect allowed" feature to the Grid.

### LINKED ISSUE #8149: Grid.SingleSelectionModel is missing deselectAllowed in 8.0.0.beta1
In version 7, it is possible to disable _selecting none_ when using single select mode with `SingleSelectionModel::setDeselectAllowed(boolean)`. This is not present in the 8 version.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8149

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8227)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaH5F7xpWyE5vIldc22:-KaH5F7xpWyE5vIldc23:b-ihblqh) ([raw file](https://github.com/vaadin/framework/blob/6175252288f2b40bc14cbe4e554fabf9b4fc698d/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L113)):*
> private SpaceSelectHandler<JsonObject> spaceSelectHandler;

Is it possible to also move this to the selection model connectors?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaH5F7xpWyE5vIldc22:-KaHDYGe5ftLNiPekgLY:b-4t8u2u) ([raw file](https://github.com/vaadin/framework/blob/6175252288f2b40bc14cbe4e554fabf9b4fc698d/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L113)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> private SpaceSelectHandler<JsonObject> spaceSelectHandler;

Is it possible to also move this to the selection model connectors?
</blockquote></details>

The simplest answer : no, since the MultiSelection model also needs this (otherwise - code duplication). 
But it might be possible to make a superclass for selection models which can be extended by both Single and Multi.

I need to check this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaH5F7xpWyE5vIldc22:-KaHEqvED14uIWjpQC3Y:b-repw90) ([raw file](https://github.com/vaadin/framework/blob/6175252288f2b40bc14cbe4e554fabf9b4fc698d/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L113)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The simplest answer : no, since the MultiSelection model also needs this (otherwise - code duplication). 
But it might be possible to make a superclass for selection models which can be extended by both Single and Multi.

I need to check this out.
</blockquote></details>

You are right, it can be done. Good catch , thanks !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaH5F7xpWyE5vIldc22:-KaHGuOIjYf92akKFbrH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6175252288f2b40bc14cbe4e554fabf9b4fc698d/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L113)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

You are right, it can be done. Good catch , thanks !
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by pleku** [comment]
Reviewed 5 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLl8wxLFnGytmAQdwB:-KaLl8wxLFnGytmAQdwC:bz67clx) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java#L100)):*
> ```Java
> 
>         /**
>          * Sets whether it's allowed to deselect the selected row through the
> ```

Sets ?

---

*[server/src/main/java/com/vaadin/data/SelectionModel.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLk_o68Im_97eLaoKB:-KaLk_o68Im_97eLaoKC:bz67clx) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/server/src/main/java/com/vaadin/data/SelectionModel.java#L119)):*
> ```Java
> 
>         /**
>          * Sets whether it's allowed to deselect the selected row through the
> ```

Sets ?

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/DisallowedDeselectionTest.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLlJXP6Z9mVdq83XGg:-KaLlJXP6Z9mVdq83XGh:b2ngvnt) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/uitest/src/test/java/com/vaadin/tests/components/grid/DisallowedDeselectionTest.java#L32)):*
> ```Java
>  *
>  */
> @RunLocally(Browser.PHANTOMJS)
> ```

...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLl8wxLFnGytmAQdwB:-KaM96Uz4eg5Usg_07j8:b-7m4pc) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java#L100)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sets ?
</blockquote></details>

Copy/paste, you know.

---

*[server/src/main/java/com/vaadin/data/SelectionModel.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLk_o68Im_97eLaoKB:-KaM9G0UDlKtBrX5QUWz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/server/src/main/java/com/vaadin/data/SelectionModel.java#L119)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sets ?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/DisallowedDeselectionTest.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/framework/8227#-KaLlJXP6Z9mVdq83XGg:-KaM9LhVmTQ0KUlux7yB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6fa064e6dcf10c1c7b849f2fbd450e17b73b4308/uitest/src/test/java/com/vaadin/tests/components/grid/DisallowedDeselectionTest.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8227)*

**Pull request merged**
