### PR TITLE
Provide more extensive JavaDoc for DataProvider

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes vaadin/framework8-issues#542

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7975)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYsqTnmhLZf5cl9DKD0:-KYsqTnmhLZf5cl9DKD1:b8qbgzc) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L35)):*
> ```Java
>  * provider uses this information to return a stream containing requested beans.
>  * <p>
>  * The data type of a data provider is the data that the backend has. It can be
> ```

... is the type of the data ...

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYsqZQpIZZW9Zc4koT1:-KYsqZQpIZZW9Zc4koT2:b-rhgril) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L36)):*
> ```Java
>  * <p>
>  * The data type of a data provider is the data that the backend has. It can be
>  * a Java object when using ORM, or a JsonObject in the case of a RestAPI. The
> ```

REST API

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYsqftp_feRN_vEH1sw:-KYsqftp_feRN_vEH1sx:bfc7cdw) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L37)):*
> ```Java
>  * The data type of a data provider is the data that the backend has. It can be
>  * a Java object when using ORM, or a JsonObject in the case of a RestAPI. The
>  * application developer sets up the listing components to display the data in a
> ```

This sentence sounds perhaps overly generic - at least not immediately clear what this means.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYsqrySN3t25QjcfZTW:-KYsqrySN3t25QjcfZTX:b-wofwao) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L41)):*
> ```Java
>  * <p>
>  * Vaadin comes with a ready-made solution for in-memory data, known as
>  * {@link ListDataProvider} which can be created using static create methods in
> ```

format "create" as code for clarity

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYsr4C2Sw5ZYWgxSe51:-KYsr4C2Sw5ZYWgxSe52:b-rq7ycc) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L44)):*
> ```Java
>  * this interface.
>  * <p>
>  * There is also {@link BackEndDataProvider} implementation to use with any
> ```

maybe reorder the sentence starting with what the user wants to use - perhaps something like "For custom back-ends such as ..., use a BackEndDataProvider ...." 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYwIILjwR1itAGolkhf:-KYwIILkN3HD1xOcZYOx:b-5f2p44) ([raw file](https://github.com/vaadin/framework/blob/d60305abad6f4339e0dabf866434157693c82953/server/src/main/java/com/vaadin/server/data/DataProvider.java#L38)):*
> ```Java
>  * a Java object when using ORM, or a JsonObject in the case of a RestAPI. The
>  * application developer sets up the listing components to display the data in a
>  * specific way, usually with a Java 8 lambda expression or a method reference.
> ```

Is this needed at all? How worth is it to mention implementation detail about preferred way to use lambda or a method reference ?
It's completely up to developer to choose a more preferable way of using API. And it doesn't look as a correct place for this note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYxcYWDacd7yRSSDs8P:-KYxcYWDacd7yRSSDs8Q:bbs0xb7) ([raw file](https://github.com/vaadin/framework/blob/2eca2b5e6c4fef2eb80a5ef9068fd3b2c2ed0bb7/server/src/main/java/com/vaadin/server/data/DataProvider.java#L38)):*
> ```Java
>  * {@link ListDataProvider} which can be created using static {@code create}
>  * methods in this interface. For custom backends such as SQL, EntityManager,
>  * REST APIs, SpringData use a {@link BackEndDataProvider} or its subclass.
> ```

... REST APIs or ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 38 at r2](https://reviewable.io:443/reviews/vaadin/framework/7975#-KYxcYWDacd7yRSSDs8P:-KYxdGYD-aKlGNOdcFF0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2eca2b5e6c4fef2eb80a5ef9068fd3b2c2ed0bb7/server/src/main/java/com/vaadin/server/data/DataProvider.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... REST APIs or ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7975#-:-KYxeDhj9sbfc-t5U2fq:bnfp4nl)*

**Pull request merged**
