### PR TITLE
Add possibility to configure the content mode of TabSheet tabs

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8920)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1030 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfuseA3JPKtr5MKnoic:-KfuseA3JPKtr5MKnoid:b-dql2n1) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1030)):*
> ```Java
>          * briefly describe the state of the tab to the user, and is typically
>          * shown as a tooltip when hovering over the tab.
>          * 
> ```

(extra whitespace at end on a few lines?)

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1036 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusLe1OiQDKj_3SGaw:-KfusLe1OiQDKj_3SGax:bqdukhr) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1036)):*
> ```Java
>          *            the new description string for the tab
>          * @param mode
>          *            content mode used to display the description
> ```

@since

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1240 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusUHXMnG-cIc601Po:-KfusUHXMnG-cIc601Pp:b-tygqr4) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1240)):*
> ```Java
>         @Override
>         public void setDescription(String description) {
>             tabState.description = description;
> ```

does not match javadoc which says this also sets the content mode

---

*[shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-Kfus_oISGex8o1YboCu:-Kfus_oISGex8o1YboCv:b-ro1kxz) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java#L35)):*
> ```Java
>     public boolean closable = false;
>     public String description = null;
>     public ContentMode descriptionContentMode = ContentMode.PREFORMATTED;
> ```

(could have @since)

---

*[uitest/src/main/java/com/vaadin/tests/components/tabsheet/TabDescriptionContentMode.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusinMo2UbyxYrkM8l:-KfusinMo2UbyxYrkM8m:byclzgm) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/uitest/src/main/java/com/vaadin/tests/components/tabsheet/TabDescriptionContentMode.java#L16)):*
> ```Java
>     protected void setup(VaadinRequest request) {
>         TabSheet tabSheet = new TabSheet();
>         
> ```

extra whitespace here and below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8920)*

**Comment by ahie** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1030 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfuseA3JPKtr5MKnoic:-KfzHckun8NRWy4vbkZm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1030)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(extra whitespace at end on a few lines?)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1036 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusLe1OiQDKj_3SGaw:-KfzHdFiQ7zmS-OSMmHq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1036)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1240 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusUHXMnG-cIc601Po:-KfzHdu6Nx2ZfTJCQW57:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/server/src/main/java/com/vaadin/ui/TabSheet.java#L1240)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

does not match javadoc which says this also sets the content mode
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/tabsheet/TabDescriptionContentMode.java, line 16 at r1](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfusinMo2UbyxYrkM8l:-KfzHhuEcSxJfpGaGLGl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c4bcc8e49792b1913d37eaddcc42d6d6bee9152f/uitest/src/main/java/com/vaadin/tests/components/tabsheet/TabDescriptionContentMode.java#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace here and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8920)*

**Comment by hesara** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1037 at r2](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfzIeUegva1jMYqRhBd:-KfzIeUegva1jMYqRhBe:b-pcku9r) ([raw file](https://github.com/vaadin/framework/blob/a5956adf8def81261f8308c76ac5207d63ef4588/server/src/main/java/com/vaadin/ui/TabSheet.java#L1037)):*
> ```Java
>          * @param mode
>          *            content mode used to display the description
>          * 
> ```

(one more extra space)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8920)*

**Comment by ahie** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/TabSheet.java, line 1037 at r2](https://reviewable.io:443/reviews/vaadin/framework/8920#-KfzIeUegva1jMYqRhBd:-KfzIyk1HGBYvfL63FBC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a5956adf8def81261f8308c76ac5207d63ef4588/server/src/main/java/com/vaadin/ui/TabSheet.java#L1037)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(one more extra space)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8920)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8920#-:-KfzJLV42siAAS4tjLwC:bnfp4nl)*

**Pull request merged**
