### PR TITLE
Added support for getValue and setValue in RichTextAreaElement

### LINKED ISSUE #8114: Redundant autoboxing for BackEndDataProvider size callback.
`SerializableFunction<Query, Integer>` causes redundant boxing / unboxing and corresponding code warnings in an IDE configured to warn about autoboxing.

The size callback should instead be based on `SerializableIntFunction<T>`  which extends `IntFunction<T>` and `Serializable`.

### LINKED ISSUE #8184: Sensible getValue() and setValue() for RichTextAreaElement
@vaadin-bot commented on [Wed Feb 04 2015](https://github.com/vaadin/testbench/issues/768)

**Originally by @Ansku**

___
There should be a sensible way for getting the text contents of RichTextAreaElement.

___
 Imported from https://dev.vaadin.com/ issue #16578

### PR DESCRIPTION
**Pull request by anasmi**
Resolves #8184

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10659)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6Gqn16jiwmtNlq_b_H:-L6Gqn16jiwmtNlq_b_I:b-ulygds) ([raw file](https://github.com/vaadin/framework/blob/7ca382a952afed431b4e99d672eeeaa2278b70e7/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L47)):*
> ```Java
>         JavascriptExecutor executor= (JavascriptExecutor)getDriver();
>         return executor.executeScript("" +
>                 "var richTextArea = document.getElementsByClassName(\"v-richtextarea\");\n" +
> ```

This would find any rich text area on the page. Instead, use `getEditorIFrame()` defined above to get a reference to the iframe and then do something like
`executeScript("arguments[0].contentDocument.body.innerHTML", getEditorIFrame());`

Same problem with the three methods below

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6GrJI1Zb0Zo8QAAEAy:-L6GrJI1Zb0Zo8QAAEAz:b-r1u9ig) ([raw file](https://github.com/vaadin/framework/blob/7ca382a952afed431b4e99d672eeeaa2278b70e7/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L63)):*
> ```Java
>             throw new ReadOnlyException();
>         }
>         clearElementClientSide();
> ```

Why do you need to clear it first as you are anyway overwriting `innerHTML`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6GrJI1Zb0Zo8QAAEAy:-L6GsLakWe_R_HY87uoN:b-a1c2ob) ([raw file](https://github.com/vaadin/framework/blob/7ca382a952afed431b4e99d672eeeaa2278b70e7/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L63)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why do you need to clear it first as you are anyway overwriting `innerHTML`?
</blockquote></details>

Took as reference from TextArea, but not needed through 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6Gqn16jiwmtNlq_b_H:-L6H3DKR--iMf1TzmsTI:b-a2ujgl) ([raw file](https://github.com/vaadin/framework/blob/7ca382a952afed431b4e99d672eeeaa2278b70e7/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L47)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This would find any rich text area on the page. Instead, use `getEditorIFrame()` defined above to get a reference to the iframe and then do something like
`executeScript("arguments[0].contentDocument.body.innerHTML", getEditorIFrame());`

Same problem with the three methods below
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6GrJI1Zb0Zo8QAAEAy:-L6H3GipMX5kOjGAIH2f:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/7ca382a952afed431b4e99d672eeeaa2278b70e7/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L63)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Took as reference from TextArea, but not needed through 
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
@Artur- , could check if this looks alright to you?

Thanks in advance!

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRO3hVl5aMAb8KrIK:-L6WRO3hVl5aMAb8KrIL:bwy7e4s) ([raw file](https://github.com/vaadin/framework/blob/011abe05599ec27a4f975928f38679ebe5511b99/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L60)):*
> ```Java
>             throw new ReadOnlyException();
>         }
>         focus();
> ```

Is this also copied from somewhere? Can't see why it would be needed unless it's some browser workaround?

---

*[uitest/src/main/java/com/vaadin/tests/elements/ComponentElementGetValue.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRWZQ61_zYZLSuzS8:-L6WRWZQ61_zYZLSuzS9:b3bozdy) ([raw file](https://github.com/vaadin/framework/blob/011abe05599ec27a4f975928f38679ebe5511b99/uitest/src/main/java/com/vaadin/tests/elements/ComponentElementGetValue.java#L24)):*
> ```Java
> import com.vaadin.server.VaadinRequest;
> import com.vaadin.tests.components.AbstractTestUI;
> import com.vaadin.ui.*;
> ```

Don't use `*`imports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by Artur-** [comment]
Some formatting seems to be off, are you using the project formatting rules?

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659#-:-L6WRmk1woQhUz2QPzFF:b-4iqbho)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRO3hVl5aMAb8KrIK:-L6WSi5lhovbzQQygBrP:b-p8sb7h) ([raw file](https://github.com/vaadin/framework/blob/011abe05599ec27a4f975928f38679ebe5511b99/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L60)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is this also copied from somewhere? Can't see why it would be needed unless it's some browser workaround?
</blockquote></details>

TextAreaElement is using this one in its setValue. It might be because of sendKeys (i am not sure anymore, as I can't find where I have seen it, but it should through an exception if I am trying to modify disabled/readonly component)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRO3hVl5aMAb8KrIK:-L6WXPfUChFjrkGd7pgY:bcdjkuh) ([raw file](https://github.com/vaadin/framework/blob/011abe05599ec27a4f975928f38679ebe5511b99/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L60)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

TextAreaElement is using this one in its setValue. It might be because of sendKeys (i am not sure anymore, as I can't find where I have seen it, but it should through an exception if I am trying to modify disabled/readonly component)
</blockquote></details>

Also, if component is readonly, shouldn't I prevent changing of value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
I need to check this...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659#-:-L6WXZ9mmdGTjgNI4jEX:bwcgw0x)*

**Comment by anasmi** [comment]
I am using  IJ and looks like it doesn't match exactly Eclipse rules 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659#-:-L6W_dqBBWX5zLPLlVGy:bnjhu07)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/elements/ComponentElementGetValue.java, line 24 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRWZQ61_zYZLSuzS8:-L7-Vcopas3GI1lzToUt:b-896fjx) ([raw file](https://github.com/vaadin/framework/blob/fdaa4db6f44612978496fa0523ecbead772679f8/uitest/src/main/java/com/vaadin/tests/elements/ComponentElementGetValue.java#L24)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Don't use `*`imports
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by Artur-** [comment]
Reviewed 1 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRO3hVl5aMAb8KrIK:-L73eNib6EAAaXimfe0R:b6z10b2) ([raw file](https://github.com/vaadin/framework/blob/fdaa4db6f44612978496fa0523ecbead772679f8/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L60)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Also, if component is readonly, shouldn't I prevent changing of value?
</blockquote></details>

Yeah, I was referring to `focus()`. I think it is needed for `sendKeys` but not when setting the value this way using JS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java, line 60 at r2](https://reviewable.io:443/reviews/vaadin/framework/10659#-L6WRO3hVl5aMAb8KrIK:-L74arBlwO7v7oRhDS97:baixl50) ([raw file](https://github.com/vaadin/framework/blob/fdaa4db6f44612978496fa0523ecbead772679f8/testbench-api/src/main/java/com/vaadin/testbench/elements/RichTextAreaElement.java#L60)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Yeah, I was referring to `focus()`. I think it is needed for `sendKeys` but not when setting the value this way using JS
</blockquote></details>

Should I remove it and also the focus method or could I leave it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10659)*

**Comment by anasmi** [comment]
@Artur- , could you take a look, when you have a moment?

**Comment by Artur-** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10659)*

**Pull request merged**
