### PR TITLE
Add server-side expand and collapse to TreeGrid

### LINKED ISSUE #8759: When using TreeGrid, I want to decide which rows should be expanded, so that I can show the necessary data to the user
```java
/**
 * Expands the given item.
 * <p>
 * If the item is currently expanded, does nothing.
 * If the item does not have any children, does nothing.
 * 
 * @param item
 *      the item to expand
 */
public void expand(T item) { ... }
```

For implementation, there are two cases:
1. The item is currently visible -> just expand it and push _enough items_ to browser
2. The item is not visible -> need store the item and compare all fetched items to that one. When it is finally fetched, it should set as expanded and push those rows to the client side.

### PR DESCRIPTION
**Pull request by ahie**
Closes #8759

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9021)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kgx3uDa7r_bCc4DgqDZ:-Kgx3uDbL3moviWb0Pm0:bpk48kg) (no related file):*
TODO: javadocs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by ahie** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kgx5CeJtBEPbnYqMW2t:-Kgx5CeJtBEPbnYqMW2u:b-faie0y) (no related file):*
Currently all expands are handled so that the server only informs the client that a row needs to be expanded and the client does the request for expanded rows when it knows the correct location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by ahie** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kgx3uDa7r_bCc4DgqDZ:-KgxI1FMk6K1YMCfM9XC:bb6un1j) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

TODO: javadocs.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
Reviewed 10 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 347 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxzzAlNtyVXtBlPp7Y:-KgxzzAlNtyVXtBlPp7Z:b-nznd3y) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L347)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     if (pendingExpansion.contains(
>                             getDataSource().getRow(rowIndex).getString(
>                                     DataCommunicatorConstants.KEY))) {
>                         setCollapsedServerInitiated(rowIndex, false);
>                         pendingExpansion.remove(rowKey);
</details>

optimized version:
`
if( pendingExpansion.remove(rowKey)) {
      setCollapsedServerInitiated(rowIndex, false);
}
`

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kgxr4hCAMaj3am8MZn4:-Kgxr4hCAMaj3am8MZn5:bkw5r1z) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L65)):*
> ```Java
>     private HierarchyMapper mapper = new HierarchyMapper();
> 
>     private Set<String> pendingExpand = new HashSet<>();
> ```

I'd prefer a bit more descriptive name like  `pendingExpandRowKeys`

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 461 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxyyMKzZd_KCBVc2x3:-KgxyyMKzZd_KCBVc2x4:b-pn7vca) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L461)):*
> ```Java
>         Optional<TreeNode> node = mapper.getNodeForKey(nodeKey);
>         if (node.isPresent()) {
>             doCollapse(nodeKey, node.get().getStartIndex() - 1);
> ```

how about adding `pendingExpand.remove(nodeKey);` here as well, for better protection against race conditions?

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxoBxPAgxzQnKsc4Ia:-KgxoBxPAgxzQnKsc4Ib:b-683cxp) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L38)):*
> ```Java
>     @Before
>     public void before() {
>         openTestURL("theme=valo&debug");
> ```

The whole parameter line is not necessary. The theme is already valo,  debug mode can be enabled with         `setDebug(true);`

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridHugeTreeTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxooJd7okYYvdeFmXH:-KgxooJeDocZ3hOnUioY:b-xuu6uo) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridHugeTreeTest.java#L24)):*
> ```Java
>         grid.expandWithClick(2);
>         grid.expandWithClick(3);
>         grid.scrollToRow(300);
> ```

Most of things here perform server round-trip and noticeable time to render.
Better to insert `grid.waitForVaadin()` after long-distance scrolls and clicks or it might fail under some browsers under test environment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
Reviewed 1 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 347 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxzzAlNtyVXtBlPp7Y:-Kgy7gy0_VwmxsAVhUcd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L347)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>     if (pendingExpansion.contains(
>                             getDataSource().getRow(rowIndex).getString(
>                                     DataCommunicatorConstants.KEY))) {
>                         setCollapsedServerInitiated(rowIndex, false);
>                         pendingExpansion.remove(rowKey);

optimized version:
`
if( pendingExpansion.remove(rowKey)) {
      setCollapsedServerInitiated(rowIndex, false);
}
`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 65 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kgxr4hCAMaj3am8MZn4:-Kgy6R4Z1LinFu6Wbr-C:b19a5p9) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L65)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I'd prefer a bit more descriptive name like  `pendingExpandRowKeys`
</blockquote></details>

Changed to `rowKeysPendingExpand`.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 461 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxyyMKzZd_KCBVc2x3:-Kgy6ZlJsinMPb6Y9DMS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L461)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

how about adding `pendingExpand.remove(nodeKey);` here as well, for better protection against race conditions?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxoBxPAgxzQnKsc4Ia:-Kgy6nl45dDor94ZWi_O:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L38)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The whole parameter line is not necessary. The theme is already valo,  debug mode can be enabled with         `setDebug(true);`
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridHugeTreeTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/9021#-KgxooJd7okYYvdeFmXH:-Kgy6yl9N5IvAWKgDIw6:bz313bb) ([raw file](https://github.com/vaadin/framework/blob/385746d9dd6ab4f5ac0300dd384f43bc2588628d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridHugeTreeTest.java#L24)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Most of things here perform server round-trip and noticeable time to render.
Better to insert `grid.waitForVaadin()` after long-distance scrolls and clicks or it might fail under some browsers under test environment.
</blockquote></details>

Added wait to scrolls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
:lgtm: but needs a rebase

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021#-:-KgyACRa6QQCz8HKEs7Y:btv7his)*

**Comment by elmot** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 466 at r3](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kh1BCCqbTt6p6DKABhq:-Kh1BCCqbTt6p6DKABhr:b-9kjqgq) ([raw file](https://github.com/vaadin/framework/blob/97270bfc60c2b7296d7dee676040854d3ed889e2/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L466)):*
> ```Java
>     }
> 
>     protected void dropAllData() {
> ```

Javadoc is required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r4.
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 81 at r4](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kh1MZivgzVxroEeRuHg:-Kh1MZivgzVxroEeRuHh:boze6gw) ([raw file](https://github.com/vaadin/framework/blob/d8959670203d5939c96bfb4b7a8bc07fec068284/documentation/components/components-treegrid.asciidoc#L81)):*
> ```AsciiDoc
> Note that for adding or removing nodes, you always need to call the [methodname]#refreshAll# method in the data provider you are using. The [methodname]#refreshItem# method can only be used when just the data for that item is updated, but not for updates that add or remove items.
> 
> == Expanding and Collapsing Nodes
> ```

An anchor is missing. `[[components.treegrid.expand]]`, I propose

---

*[documentation/components/components-treegrid.asciidoc, line 97 at r4](https://reviewable.io:443/reviews/vaadin/framework/9021#-Kh1OqxjtzDJ-Kp1rt22:-Kh1OqxjtzDJ-Kp1rt23:b-xirvqt) ([raw file](https://github.com/vaadin/framework/blob/d8959670203d5939c96bfb4b7a8bc07fec068284/documentation/components/components-treegrid.asciidoc#L97)):*
> When using the server-side API with a backend data provider the hash code of the given node will be used for expanding and collapsing.
What?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021#-:-Kh1TOrp4Mnzp6LO7_x1:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9021)*

**Pull request merged**
