### PR TITLE
Escape CDATA element

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10377)

### CODE REVIEW

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-embedding.asciidoc, line 139 at r1](https://reviewable.io:443/reviews/vaadin/framework/10377#-L-6Ac1t53AfdlJQL6sO:-L-6DhCvWfe59FffDZsM:b-vx64wu) ([raw file](https://github.com/vaadin/framework/blob/66985e9694746bce2c18aca8dd495ac990124749/documentation/advanced/advanced-embedding.asciidoc#L139)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is this escape needed?
</blockquote></details>

Because now it looks like this:

Note that it's missing the CDATA entity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10377)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-embedding.asciidoc, line 263 at r1](https://reviewable.io:443/reviews/vaadin/framework/10377#-L-6GSfOat92-sLYNwU6:-L-6GSfOat92-sLYNwU7:b-rkqa8a) ([raw file](https://github.com/vaadin/framework/blob/66985e9694746bce2c18aca8dd495ac990124749/documentation/advanced/advanced-embedding.asciidoc#L263)):*
> ```AsciiDoc
>   </div>
>   
>   <script type="text/javascript">//<CDATA[
> ```

Why does this work?

---


*Comments from [Reviewable*

**Comment by OlliTietavainenVaadin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-embedding.asciidoc, line 263 at r1](https://reviewable.io:443/reviews/vaadin/framework/10377#-L-6GSfOat92-sLYNwU6:-L-6HtLAYB1d5PBHcTgF:bq9ifmv) ([raw file](https://github.com/vaadin/framework/blob/66985e9694746bce2c18aca8dd495ac990124749/documentation/advanced/advanced-embedding.asciidoc#L263)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why does this work?
</blockquote></details>

From Kari S: "Looks like in the `[subs="normal"]` block the CDATA needs to be escaped, but in the `[source, html]` block it works fine without escaping."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10377)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-embedding.asciidoc, line 263 at r1](https://reviewable.io:443/reviews/vaadin/framework/10377#-L-6GSfOat92-sLYNwU6:-L-6YhwkmunJ1XMa0iaJ:b-gxztsp) ([raw file](https://github.com/vaadin/framework/blob/66985e9694746bce2c18aca8dd495ac990124749/documentation/advanced/advanced-embedding.asciidoc#L263)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

From Kari S: "Looks like in the `[subs="normal"]` block the CDATA needs to be escaped, but in the `[source, html]` block it works fine without escaping."
</blockquote></details>

Fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10377#-:-L-6YpBPdpt1Ea-RaP2L:bnfp4nl)*

**Pull request merged**
