### PR TITLE
Fix Combobox adding an item with empty string

### LINKED ISSUE #11049: Empty Required ComboBox seems to be valid
Hi,

On Vaadin 8.4.1:

        Binder<AtomicReference<String>> binder = new Binder<>();

        ComboBox<String> comboBox = new ComboBox<>("ComboBox");

        ListDataProvider<String> dataProvider = new ListDataProvider<>(new ArrayList<>(Arrays.asList("one", "two", "three")));
        comboBox.setDataProvider(dataProvider);

        comboBox.setEmptySelectionAllowed(false);
        comboBox.setNewItemProvider(value -> {
            dataProvider.getItems().add(value);
            dataProvider.refreshAll();
            return Optional.of(value);
        });
        binder.forField(comboBox)
                .asRequired("required")
                .bind(AtomicReference::get, AtomicReference::set);
        mainLayout.addComponent(comboBox);

        Button button = new Button("Submit");
        button.addClickListener(event1 -> binder.validate());
        mainLayout.addComponent(button);

To reproduce the issue:
- Click on Submit => The ComboBox become in error because is required
- Choose "one" item
- Click on Submit => The ComboBox is now valid
- Clear the field by pressing backspace 3 times
- The field is empty but shouldn't because EmptySelectionAllowed is not allowed
- Click on Submit => The ComboBox is still valid!

Thanks,

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #11049

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11067)

### CODE REVIEW

**Comment by TatuLund** [comment]
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 201 at r1](https://reviewable.io/reviews/vaadin/framework/11067#-LHfmiCI7i2OQyZCo42a:-LHfmiCI7i2OQyZCo42b:b-9ad6tm) ([raw file](https://github.com/vaadin/framework/blob/dd39c104a1db96c08fc7ba00af2719b4a9deb4de/server/src/main/java/com/vaadin/ui/ComboBox.java#L201)):*
> ```Java
>             }
> 
>             if (!added) {
> ```

Should this block be within itemValue != null && !itemValue.isEmpty() ?

**Review by tsuoanttila — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11067)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 201 at r1](https://reviewable.io/reviews/vaadin/framework/11067#-LHfmiCI7i2OQyZCo42a:-LHfq6ztAeacJJToxgdm:b4frzzd) ([raw file](https://github.com/vaadin/framework/blob/dd39c104a1db96c08fc7ba00af2719b4a9deb4de/server/src/main/java/com/vaadin/ui/ComboBox.java#L201)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Should this block be within itemValue != null && !itemValue.isEmpty() ?
</blockquote></details>

That was the main issue with this code block. If the `itemValue` is `null` or `""` the ComboBox client-side is never told that a new item was not added.

**Review by elmot — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11067#-:-LHgEIMGDhAO3tIapl-N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TatuLund)

**Review by TatuLund — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11067)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
