### PR TITLE
Update to JSoup 1.11.2

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10353)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
:lgtm: if the tests pass

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353#-:-KzY0UCGSWYHlnhhF8ya:bh71wur)*

**Comment by tsuoanttila** [comment]
Reviewed 7 of 8 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 255 at r3](https://reviewable.io:443/reviews/vaadin/framework/10353#-KzYmLYouW3RcoiKyOQa:-KzYmLYouW3RcoiKyOQb:b-xpfcen) ([raw file](https://github.com/vaadin/framework/blob/ae18f2d30f1ccbcf75444b6c64713ced62d7b331/server/src/main/java/com/vaadin/ui/Tree.java#L255)):*
> ```Java
>     /**
>      * Create inner {@link TreeGrid} object. May be overridden in subclasses.
>      * 
> ```

trailing whitespace, not blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10353)*

**Pull request merged**
