### PR TITLE
Fix ComboBox popup location on scrolled pages in IE/Firefox

### LINKED ISSUE #8778: Combobox in embedded Vaadin 8
Hi,

After migration to Vaadin 8 I find that my comboboxes have a new bug. When opened they display the selection choices only at the correct position when the window is at top position and not scrolled. When I scroll down the combobox content is displayed too high. The more I scroll down the greater is the offset to the correct position.

I am embedding Vaadin in a div as described in https://vaadin.com/docs/-/part/framework/advanced/advanced-embedding.html as you can see in http://pastebin.com/ZKPMMghC

This is the Vadin component to reproduce the problem:
```
public class Test extends UI {
	@Override
	protected void init(VaadinRequest vaadinRequest) {
		VerticalLayout vl = new VerticalLayout();
		for (int i=0; i<20; i++)
			vl.addComponent(new Label(""+i));
		ComboBox<String> cb = new ComboBox<>();
		vl.addComponent(cb);
		for (int i=0; i<20; i++)
			vl.addComponent(new Label(""+i));
		setContent(vl);
 	}
}
```

Thanks,
Roland

### PR DESCRIPTION
**Pull request by hesara**
Fixes #8778

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8781)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 414 at r1](https://reviewable.io:443/reviews/vaadin/framework/8781#-KelyjqnkOFPH3P_kKTh:-Kelyjqo8okUJORiWwDg:b-9mp5v3) ([raw file](https://github.com/vaadin/framework/blob/951a7fe110217f95160097e2921de6439ae6a61e/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L414)):*
> ```Java
> 
>             final int x = toInt32(WidgetUtil
>                     .getBoundingClientRect(VComboBox.this.getElement())
> ```

What happens if the window has a horizontal scroll bar and it is a scrolled to left?

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxPopupPositionEmbeddedInDivTest.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8781#-Kem0mRaIlb_mqy5k654:-Kem0mRaIlb_mqy5k655:b-wwl5oo) ([raw file](https://github.com/vaadin/framework/blob/951a7fe110217f95160097e2921de6439ae6a61e/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxPopupPositionEmbeddedInDivTest.java#L36)):*
> ```Java
>         // Firefox + IE wants document.documentElement.scrollTop (<html>)
>         executeScript(
>                 "document.body.scrollTop=200;document.documentElement.scrollTop=200;");
> ```

Horizontal scroll is not tested

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8781)*

**Comment by hesara** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 414 at r1](https://reviewable.io:443/reviews/vaadin/framework/8781#-KelyjqnkOFPH3P_kKTh:-KemBNNWDKgESBN4hDPV:bmxfb0) ([raw file](https://github.com/vaadin/framework/blob/951a7fe110217f95160097e2921de6439ae6a61e/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L414)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What happens if the window has a horizontal scroll bar and it is a scrolled to left?
</blockquote></details>

Was working, tested manually and added automated test.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxPopupPositionEmbeddedInDivTest.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8781#-Kem0mRaIlb_mqy5k654:-KemBTtev87_4WxRG4CE:b-7q4nnf) ([raw file](https://github.com/vaadin/framework/blob/951a7fe110217f95160097e2921de6439ae6a61e/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxPopupPositionEmbeddedInDivTest.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Horizontal scroll is not tested
</blockquote></details>

Added test for horizontal position

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8781)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8781#-:-KerttPy6G-d55Jzgssx:bnfp4nl)*

**Comment by ropoman** [comment]
This is not fixed. Problem is still there in 8.0.3

**Comment by pleku** [comment]
@ropoman , could you please take a look at https://github.com/vaadin/framework/pull/8781/files for the test case and report how your case where the bug is still present differs from that one ?

**Comment by ropoman** [comment]
It turns out I have problems only in a very special case: Only when using the Designer and only when the ComboBox is within a CssLayout. I was unable to reproduce the problem with Java alone. I attach the design
[TestDesign.html.txt](https://github.com/vaadin/framework/files/861448/TestDesign.html.txt)

**Comment by TatuLund** [comment]
I think this related https://github.com/vaadin/framework/issues/5043

**Pull request merged**
