### PR TITLE
Fix TestBench API imports

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8112)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This patch still requires a full validation build and removal of custom element classes from the uitest project.

**Comment by denis-anisimov** [comment]
Reviewed 281 of 281 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_DZjuYY-iea2Yeqyuj:-K_DZjuZ3loeCYPl69yq:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L272)):*
> ```Java
>         }
>     }
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by Artur-** [comment]
Reviewed 7 of 281 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_9RNIaTScvWx97xk_O:-K_9RNIaTScvWx97xk_P:bqkw7qm) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L44)):*
> ```Java
>     }
> 
>     public List<WebElement> getOptionElements() {
> ```

javadoc?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_9Rg884EH0rbulKdbL:-K_9Rg884EH0rbulKdbM:bbedrg8) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L268)):*
> ```Java
>                 Thread.sleep(delay);
>             } catch (InterruptedException e) {
>                 Assert.fail(e.getMessage());
> ```

`Assert` is wrong here

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_ETrtDa4GdndE1ciOo:-K_ETrtDa4GdndE1ciOp:ba6lfle) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java#L82)):*
> ```Java
>      */
>     public List<String> getSelection() {
>         List<String> values = new ArrayList<>();
> ```

This is 99% copy paste of the method above

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 150 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU00X8G0lEwAcaM1z:-K_EU00YZKBOlgpsYMyq:bqkw7qm) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L150)):*
> ```Java
>     }
> 
>     public CollapseMenu openCollapseMenu() {
> ```

javadoc?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU0uuaRznBueZ1CZ3:-K_EU0uuaRznBueZ1CZ4:bqkw7qm) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L157)):*
> ```Java
>     }
> 
>     public static class CollapseMenu extends ContextMenuElement {
> ```

javadoc?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU7Se_DPv2lmlb1eh:-K_EU7Se_DPv2lmlb1ei:b-oeqrw3) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L157)):*
> ```Java
>     }
> 
>     public static class CollapseMenu extends ContextMenuElement {
> ```

Should probably be named CollapseMenuElement like all other classes

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 160 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU1ZCLA8FLrJpg89h:-K_EU1ZCLA8FLrJpg89i:bqkw7qm) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L160)):*
> ```Java
>     }
> 
>     public WebElement getCollapseMenuToggle() {
> ```

javadoc?

---

*[uitest-common/src/main/java/com/vaadin/testbench/customelements/TableElement.java, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EUVkYyG1JrpJUnC6B:-K_EUVkYyG1JrpJUnC6C:bk5zdep) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/uitest-common/src/main/java/com/vaadin/testbench/customelements/TableElement.java#L9)):*
> ```Java
> 
> @ServerClass("com.vaadin.ui.Table")
> public class TableElement extends com.vaadin.testbench.elements.TableElement {
> ```

Why is this class still needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by tsuoanttila** [comment]
Review status: 254 of 277 files reviewed at latest revision, 9 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_9RNIaTScvWx97xk_O:-Ka1ZUoeDb9SAZq7wK8a:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L44)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_9Rg884EH0rbulKdbL:-Ka1X80A3BupzrFcNCme:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L268)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`Assert` is wrong here
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_DZjuYY-iea2Yeqyuj:-Ka1X8X7lPhw422C58jd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L272)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 150 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU00X8G0lEwAcaM1z:-Ka1YEl_RgsfmtWoAoTA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L150)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU0uuaRznBueZ1CZ3:-Ka1YCwrIdIPOqvhcqaA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L157)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU7Se_DPv2lmlb1eh:-Ka1YDMpuvjF74968OcE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L157)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Should probably be named CollapseMenuElement like all other classes
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java, line 160 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EU1ZCLA8FLrJpg89h:-Ka1YDrEB-fCC_d25c7g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java#L160)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

javadoc?
</blockquote></details>

Done.

---

*[uitest-common/src/main/java/com/vaadin/testbench/customelements/TableElement.java, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_EUVkYyG1JrpJUnC6B:-Ka1YWOtQrzlbo1CrwEn:betyt8g) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/uitest-common/src/main/java/com/vaadin/testbench/customelements/TableElement.java#L9)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why is this class still needed?
</blockquote></details>

The old classes are still there since I did not remove them yet.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_ETrtDa4GdndE1ciOo:-Ka1XaTgs0BIqhJnNBGJ:bss4a2b) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java#L82)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This is 99% copy paste of the method above
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by hesara** [comment]
Reviewed 19 of 42 files at r2, 1 of 1 files at r3.
Review status: 273 of 277 files reviewed at latest revision, 11 unresolved discussions.

---

*[uitest-common/src/main/java/com/vaadin/testbench/customelements/CheckBoxGroupElement.java, line 66 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdFqkp0hab4hI33e6:-KaCdFqkp0hab4hI33e7:b-ko1pd5) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest-common/src/main/java/com/vaadin/testbench/customelements/CheckBoxGroupElement.java#L66)):*
> ```Java
>      * @return list of the selected options in the checkbox group
>      */
>     public List<String> getValue() {
> ```

This customelement still uses getValue(). Is the class used at all or not? Can it be removed and replaced with the standard element?

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 193 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdeYvgIfjq9D91hnT:-KaCdeYvgIfjq9D91hnU:b-jvpbsm) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L193)):*
> ```Java
> 
>     private void assertSelected(String expectedSelection) {
>         Assert.assertEquals(expectedSelection, getSelect().getValue());
> ```

getSelection() or getValue()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by hesara** [comment]
Reviewed 1 of 42 files at r2, 11 of 11 files at r4.
Review status: 284 of 286 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by Artur-** [comment]
Review status: 284 of 286 files reviewed at latest revision, 3 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-K_TnZfsg9a5B-3Pm8IY:-K_TnZfsg9a5B-3Pm8IZ:bynllv) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java#L36)):*
> ```Java
> 
>     public List<String> getOptions() {
>         List<String> optionTexts = new ArrayList<String>();
> ```

This could be implemented using `getOptionElements`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by tsuoanttila** [comment]
Review status: 283 of 286 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 193 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdeYvgIfjq9D91hnT:-KaCo7VfPis-ZV7PkCjd:b-bpn0d1) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L193)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

getSelection() or getValue()?
</blockquote></details>

I think we should use Arturs new name for the RadioButtonGroup as well, even though there "value" might be closer to truth than "selection"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by tsuoanttila** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 193 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdeYvgIfjq9D91hnT:-KaCvJa9KHTos3GXsxeX:b-4z3bmq) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L193)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I think we should use Arturs new name for the RadioButtonGroup as well, even though there "value" might be closer to truth than "selection"
</blockquote></details>

After pondering on this for a moment, I'd leave the RadioButtonGroupElement as is for now. for that "Value" does make more sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by Artur-** [comment]
Review status: 283 of 290 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 193 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdeYvgIfjq9D91hnT:-KaCu3BQPoJj1mH11f_r:b-1ccfbw) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L193)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

After pondering on this for a moment, I'd leave the RadioButtonGroupElement as is for now. for that "Value" does make more sense.
</blockquote></details>

The name should match what is used in the component itself. Is that `getValue()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by denis-anisimov** [comment]
Reviewed 20 of 42 files at r2, 1 of 1 files at r3, 11 of 11 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCwjB96HAklTRI4_nN:-KaCwjBA0st6SyZJhTdD:b1zczf7) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L268)):*
> ```Java
>                 Thread.sleep(delay);
>             } catch (InterruptedException e) {
>                 Assert.fail(e.getMessage());
> ```

Since it has been a failure then shouldn't it throw a runtime exception now after removal an assertion ?
Or may be it should be `assert false : e.getMessage();` ?

Up to you to decide .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by tsuoanttila** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCwjB96HAklTRI4_nN:-KaGt_EIYYbARkv9jT5V:bqzbel8) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L268)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Since it has been a failure then shouldn't it throw a runtime exception now after removal an assertion ?
Or may be it should be `assert false : e.getMessage();` ?

Up to you to decide .
</blockquote></details>

I'm not sure how much useful information this InterruptedException contains to the user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by tsuoanttila** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 193 at r3](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCdeYvgIfjq9D91hnT:-KaGtmxSA7TL2Wwc8KLD:b-l2gtbe) ([raw file](https://github.com/vaadin/framework/blob/d62bd8853272b3703f51155aeeece168b34e6338/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L193)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The name should match what is used in the component itself. Is that `getValue()`?
</blockquote></details>

The name for both are actually getValue / setValue so maybe we need to use those instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/8112#-KaCwjB96HAklTRI4_nN:-KaGu1BnAUo8R49f8IiY:b-3tl6xu) ([raw file](https://github.com/vaadin/framework/blob/8d40f8275cd1c2cee2d011183334d2c98ec929a5/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L268)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'm not sure how much useful information this InterruptedException contains to the user.
</blockquote></details>

You are right, the message is useless. Stacktrace can be useful.
Then it could be `throw new RuntimeException(e);`

But again: up to you. The comment is not blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Comment by pleku** [comment]
Reviewed 4 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8112)*

**Pull request merged**
