### PR TITLE
Clean connector tracker after each access block to stop memory leaks

### PR DESCRIPTION
**Pull request by Artur-**
Backport of #9305

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9331)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 9 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKMn_YIm-IgrKOl9Et:-KkKMn_YIm-IgrKOl9Eu:b-j0q0gd) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L283)):*
> ```Java
>      * This should only be called by the framework.
>      *
>      * @since
> ```

(when review is otherwise ok, can fill in the since tags here and below before merging, and update since tags in master in a separate patch)

---

*[server/src/main/java/com/vaadin/ui/ConnectorTracker.java, line 452 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKMzkIT7UcEcXd7C-w:-KkKMzkIT7UcEcXd7C-x:bblkm0t) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L452)):*
> ```Java
>      * @return <code>true</code> if the hierarchy is consistent,
>      *         <code>false</code> otherwise
>      * @since
> ```

(see comment above)

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKLSmecumO-VcK_2nc:-KkKLSmecumO-VcK_2nd:b-mmnuv9) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L26)):*
> ```Java
> 
>         Button button = new Button(BUTTON_CAPTION);
>         button.addClickListener(e -> {
> ```

lambda not Java 6 compatible

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKLVs23HXG6lqZU5gV:-KkKLVs23HXG6lqZU5gW:b-mmnuv9) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L72)):*
> ```Java
>     private static void updatePanel(CssLayout panel, List<String> items) {
>         panel.removeAllComponents();
>         items.forEach(i -> panel.addComponent(new Button(i, e -> {
> ```

lambda not Java 6 compatible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9331)*

**Comment by Artur-** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKLSmecumO-VcK_2nc:-KkKP3dQNEyLujJJZ5o8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

lambda not Java 6 compatible
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/9331#-KkKLVs23HXG6lqZU5gV:-KkKP4C6W9BoaOr30B5b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6416e5faaa34ea9820b89329eec0eb63d9fe7760/uitest/src/main/java/com/vaadin/tests/components/ui/ConnectorTrackerMemoryLeakUI.java#L72)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

lambda not Java 6 compatible
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9331)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9331)*

**Comment by TatuLund** [comment]
This fix is needed for 7.7. as well.

**Pull request merged**
