### PR TITLE
Create drag source and drop target extensions for tree grid

### LINKED ISSUE #9372: When showing a TreeGrid, I want to add DnD support to it, so that the user can easily reorder this
Needs an example on docs, sampler demo.

Technically the `GridDragSource` & `GridDropTarget` can be reused, but there needs to be the depth information provided to the `DropEvent`.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #9372

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9463)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-p2YOv5Egc6N6t5Q:-Kmf-p2ZFMdF_msnLr9h:bwq9lyw) (no related file):*
This PR needs manual verification from someone to test that the feature works in the following browsers
- desktop mac: chrome, ff and safari
- desktop windows: edge (chrome and ff should be same as in mac) 
- iOS: safari, chrome
- android: chrome

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-KmezsMiQD9VmFDAaPBH:-KmezsMiQD9VmFDAaPBI:b2g0hdi) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java#L25)):*
> ```Java
>  * <p>
>  * When dragging a selected row, all the visible selected rows are dragged. Note
>  * that ONLY visible rows are taken into account.
> ```

Could clarify whether or not the whole subtree is dragged or not, so no-one would have guess if they read this

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-CnHn2JjeCBt8xbJ:-Kmf-CnHn2JjeCBt8xbK:b3hdn9g) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L61)):*
> ```Java
>      *         Location of the drop within the target row.
>      *         @param depth
>      *         @param collapsed
> ```

wrong indent

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-F7MVrCtvrPCx_-K:-Kmf-F7MVrCtvrPCx_-L:b-bqf0v8) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L75)):*
> ```Java
>     }
> 
>     public Optional<Integer> getDropTargetRowDepth() {
> ```

missing javadocs

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-G4wttmehdfSsH80:-Kmf-G4wttmehdfSsH81:b-bqf0v8) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L79)):*
> ```Java
>     }
> 
>     public Optional<Boolean> isDropTargetRowCollapsed() {
> ```

missing javadocs

---

*[shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridDropTargetRpc.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-aghUX4pUdghb4y6:-Kmf-aghUX4pUdghb4y7:bb92967) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridDropTargetRpc.java#L53)):*
> ```Java
>      */
>     public void drop(List<String> types, Map<String, String> data,
>             String dropEffect, String rowKey, Integer depth, Boolean collapsed,
> ```

why boxed types for `depth` and `collapsed` instead of primitive ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by wbadam** [comment]
Review status: 10 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-KmezsMiQD9VmFDAaPBH:-KmfAFe5jWLr3L-97bQI:b-8ud3xa) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java#L25)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could clarify whether or not the whole subtree is dragged or not, so no-one would have guess if they read this
</blockquote></details>

Done.
That's an important detail, what happens to a node's children when the parent is dragged and removed. Is it the developer's responsibility to handle those cases?

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-CnHn2JjeCBt8xbJ:-KmfFBPe8HW7yK8lCiSt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L61)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

wrong indent
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-F7MVrCtvrPCx_-K:-KmfFxYZtsIdNXvHqNik:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L75)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing javadocs
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-G4wttmehdfSsH80:-KmfFxzR_K2LRxVNnYEa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDropEvent.java#L79)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing javadocs
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridDropTargetRpc.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-aghUX4pUdghb4y6:-Kmf99Xjo4kY5kpKGql0:b-4ddir0) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridDropTargetRpc.java#L53)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

why boxed types for `depth` and `collapsed` instead of primitive ?
</blockquote></details>

The values can be null in case the drop happened on the Grid rather than on a row, e.g. empty Grid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnApAJWlYp7sp8r0R_t:-KnApAJWlYp7sp8r0R_u:bfy7mjk) (no related file):*
This PR also needs to add mention in the DND documentation, it should basically have a subtopic for `TreeGrid` that states that these extensions should be used for TreeGrid and what extra do they provide (eg.`TreeGridDropEvent`)

If someone adds that documentation in a separate PR, then I have no objections and my comment can be discarded.

Ping @hesara @wbadam

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnAq8J-YyM-FvyUM1_f:-KnAq8J-YyM-FvyUM1_g:be81qnq) (no related file):*
Might be feasible to test also that this can be used to create similar functionality as in https://demo.vaadin.com/sampler-77/#ui/drag-drop/dragdrop-tree-sorting (even though that is for Tree)

---

*[server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/9463#-KmezsMiQD9VmFDAaPBH:-KnAmghsUPnG7j5Flj-N:b-rph6ts) ([raw file](https://github.com/vaadin/framework/blob/1ea85ea789c37f50700d997b2c346d8e3378b9d7/server/src/main/java/com/vaadin/ui/components/grid/TreeGridDragSource.java#L25)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Done.
That's an important detail, what happens to a node's children when the parent is dragged and removed. Is it the developer's responsibility to handle those cases?
</blockquote></details>

Yes, you could separately clarify that even further, but that belongs more to the drop event IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by wbadam** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnApAJWlYp7sp8r0R_t:-KnJoA0QycCRjyhLauJ_:b-4jmyv3) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This PR also needs to add mention in the DND documentation, it should basically have a subtopic for `TreeGrid` that states that these extensions should be used for TreeGrid and what extra do they provide (eg.`TreeGridDropEvent`)

If someone adds that documentation in a separate PR, then I have no objections and my comment can be discarded.

Ping @hesara @wbadam
</blockquote></details>

Mentioned these extensions in the docs.
Are any examples needed?

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnAq8J-YyM-FvyUM1_f:-KnO6trWUvMHUn2lhgC8:bo5drsl) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Might be feasible to test also that this can be used to create similar functionality as in https://demo.vaadin.com/sampler-77/#ui/drag-drop/dragdrop-tree-sorting (even though that is for Tree)
</blockquote></details>

It is _very_ cumbersome, need to create own `TreeData` and `TreeDataProvider` as those don't support replacing an item's parent or reordering children.

One option to make it easier to implement such feature is to extend `TreeGrid`'s functionality. Let's discuss.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnApAJWlYp7sp8r0R_t:-Kn_xDRmdYX96Q70F9lp:b25iqra) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Mentioned these extensions in the docs.
Are any examples needed?
</blockquote></details>

A sample should be added, but not a part of this PR IMO

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-KnAq8J-YyM-FvyUM1_f:-Kn_xJyfPsJTrLxY5fpy:b-4g7t3l) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

It is _very_ cumbersome, need to create own `TreeData` and `TreeDataProvider` as those don't support replacing an item's parent or reordering children.

One option to make it easier to implement such feature is to extend `TreeGrid`'s functionality. Let's discuss.
</blockquote></details>

Not in scope for 8.1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 366 at r3](https://reviewable.io:443/reviews/vaadin/framework/9463#-KncDmzqYrzzjR1r3byS:-KncDmzrdo-plYR2QK_K:bojl6l3) ([raw file](https://github.com/vaadin/framework/blob/987d7e6b47bdd7a17af5cac53144c56a80b9e538/documentation/advanced/advanced-dragndrop.asciidoc#L366)):*
> ```AsciiDoc
> === Drag and Drop Rows in TreeGrid
> 
> To make a TreeGrid component's rows draggable or to make them a drop target, apply [classname]#TreeGridDragSource# or [classname]#TreeGridDropTarget# extensions to the component, respectively.
> ```

To make the rows of a TreeGrid component draggable ...
(making this non-blocking, would have fixed myself if I had push access to the branch)

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 367 at r3](https://reviewable.io:443/reviews/vaadin/framework/9463#-KncDS7QVMtrgR-VIO_J:-KncDS7QVMtrgR-VIO_K:b-v7exps) ([raw file](https://github.com/vaadin/framework/blob/987d7e6b47bdd7a17af5cac53144c56a80b9e538/documentation/advanced/advanced-dragndrop.asciidoc#L367)):*
> ```AsciiDoc
> 
> To make a TreeGrid component's rows draggable or to make them a drop target, apply [classname]#TreeGridDragSource# or [classname]#TreeGridDropTarget# extensions to the component, respectively.
> In addition to the drag and drop features for Grid above, [classname]#TreeGridDropEvent# provides information about the node's status (expanded or collapsed) and it's depth in the hierarchy.
> ```

... about the status of the node (expanded or collapsed) and its depth ...
(making this non-blocking, would have fixed myself if I had push access to the branch)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by wbadam** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 366 at r3](https://reviewable.io:443/reviews/vaadin/framework/9463#-KncDmzqYrzzjR1r3byS:-Knd62K48aGW5Ha1-wWd:b-34l9n9) ([raw file](https://github.com/vaadin/framework/blob/987d7e6b47bdd7a17af5cac53144c56a80b9e538/documentation/advanced/advanced-dragndrop.asciidoc#L366)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

To make the rows of a TreeGrid component draggable ...
(making this non-blocking, would have fixed myself if I had push access to the branch)
</blockquote></details>

Done.
Also allowed edits for maintainers.
Do I need to allow edit manually every time? It seems to me that sometimes it happens automatically, sometimes it doesn't.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 367 at r3](https://reviewable.io:443/reviews/vaadin/framework/9463#-KncDS7QVMtrgR-VIO_J:-Knd8NKHra6jtXbXvQyj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/987d7e6b47bdd7a17af5cac53144c56a80b9e538/documentation/advanced/advanced-dragndrop.asciidoc#L367)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... about the status of the node (expanded or collapsed) and its depth ...
(making this non-blocking, would have fixed myself if I had push access to the branch)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-p2YOv5Egc6N6t5Q:-KnhjqygsUKrEurhdfXN:bxn7qwd) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This PR needs manual verification from someone to test that the feature works in the following browsers
- desktop mac: chrome, ff and safari
- desktop windows: edge (chrome and ff should be same as in mac) 
- iOS: safari, chrome
- android: chrome
</blockquote></details>

Tested and working with Android, iOS Safari, Edge 14, Edge 15, IE11, Mac Chrome, Mac Safari, Mac Firefox.
Not yet tested on iOS Chrome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9463#-Kmf-p2YOv5Egc6N6t5Q:-KnhnVbdsB8MxGmOfJio:b-hz4rm1) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Tested and working with Android, iOS Safari, Edge 14, Edge 15, IE11, Mac Chrome, Mac Safari, Mac Firefox.
Not yet tested on iOS Chrome.
</blockquote></details>

Tested and working also on iOS Chrome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9463)*

**Pull request merged**
