### PR TITLE
make modal window focus circulate even if resize button is not available

### LINKED ISSUE #10484: Followup for #8855 - window has to be resizable to remove focus trap
The issue #8855 isn't resolved for us because it only works if the window is resizable. Windows that aren't resizable won't change focus if you tab on the bottom of the window. 

**Example**:
- https://demo.vaadin.com/sampler/#ui/structure/window
- Config: modal = true, resizable = false

**Expected**:
- Focus should not be trapped when reaching bottom

**Actual**:
- Focus is trapped on the bottom 

Changing resizable to true fixes the problem. 

**Vaadin Version: 8.2+**

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
fixes #10484

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10497)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/FocusUtil.java, line 131 at r1](https://reviewable.io:443/reviews/vaadin/framework/10497#-L2PvR6jRQ_1Zws7RUnS:-L2PvR6jRQ_1Zws7RUnT:bp9iq0d) ([raw file](https://github.com/vaadin/framework/blob/1afcc8f0ca402634bfe22d09299d8e5a8f5445ec/client/src/main/java/com/vaadin/client/ui/FocusUtil.java#L131)):*
> ```Java
>             if (classes == null || !classes.toLowerCase().contains("disabled")) {
>                 element.focus();
>                 break;
> ```

`return` instead of `break`.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/10497#-L2PvwESecT-jkb3kYTF:-L2PvwESecT-jkb3kYTG:b-v7130u) ([raw file](https://github.com/vaadin/framework/blob/1afcc8f0ca402634bfe22d09299d8e5a8f5445ec/uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java#L113)):*
> ```Java
>     }
> 
>     private void pressEscAndWait() {
> ```

could combine these two methods to a generic `pressKeyAndWait` that takes the Key as a paremeter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10497)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/FocusUtil.java, line 131 at r1](https://reviewable.io:443/reviews/vaadin/framework/10497#-L2PvR6jRQ_1Zws7RUnS:-L2Q6-DIoiuRzzDIplgg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1afcc8f0ca402634bfe22d09299d8e5a8f5445ec/client/src/main/java/com/vaadin/client/ui/FocusUtil.java#L131)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`return` instead of `break`.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/10497#-L2PvwESecT-jkb3kYTF:-L2Q5zVCmo8C6RboTYy2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1afcc8f0ca402634bfe22d09299d8e5a8f5445ec/uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java#L113)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

could combine these two methods to a generic `pressKeyAndWait` that takes the Key as a paremeter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10497)*

**Comment by tsuoanttila** [comment]
:lgtm: but requires merge with master because of a test file conflict.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10497#-:-L2UrfRLw7ZVvk_wPN76:b-q5t5g8)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10497)*

**Pull request merged**
