### PR TITLE
Make data providers statefull with regards to default sort orders

### PR DESCRIPTION
**Pull request by Legioth**
This is one of many steps towards #8245

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8247)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafpgH7l46MxngJNoRi:-KafpgH7l46MxngJNoRj:bndjfxv) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L99)):*
> ```Java
>      *            a list of sort orders to set, not <code>null</code>
>      */
>     public void setSortOrder(List<SortOrder<String>> sortOrders) {
> ```

Should it be plural ?

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-Kafq1gJf2--pxS2jnVF:-Kafq1gJf2--pxS2jnVG:btxcsts) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L112)):*
> ```Java
>      * sorting is also used to determine the ordering of items that are
>      * considered equal by the sorting defined in the query.
>      *
> ```

`@see setSortOrderS`
+
mention that this is a shorthand ?

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafwpFKmQjzTUGcXEnV:-KafwpFKmQjzTUGcXEnW:bnxy0j8) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L98)):*
> ```Java
>      *            previously set sort order
>      */
>     public void setSortOrder(Comparator<T> sortOrder) {
> ```

The method name is confusing since it sets behavioural strategy rather than object.
Don't know a better name though.

`setSortOrderComparator` ?

By the way : shouldn't this be `SerializableComparator` ?

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafxfgXHxN4AJzo_2UR:-KafxfgXHxN4AJzo_2US:bu7ho0h) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L136)):*
> ```Java
>      *            a comparator to add, not <code>null</code>
>      */
>     public void addSortOrder(Comparator<T> sortOrder) {
> ```

Same issue with the method name.

---

*[server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafymPF6GmapL4DKT8S:-KafymPF6GmapL4DKT8T:b-5aoe60) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java#L205)):*
> ```Java
>         setSortOrder(Sort.asc("id").build(),
>                 Comparator.comparing(StrBean::getId));
>         dataProvider.refreshAll();
> ```

What does `setSortOrder` do here ? (don't see it's impl, it should be test class instance method).
If it delegates to `dataProvider.setSortOrder` then is `refreshAll()`needed here ?

---

*[server/src/test/java/com/vaadin/data/provider/StrBean.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafzQ1KGlt0Xgyvy68N:-KafzQ1KGlt0Xgyvy68O:b3kre) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/StrBean.java#L59)):*
> ```Java
>                     && Objects.equals(this.value, that.value);
>         } else {
>             return true;
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafpgH7l46MxngJNoRi:-Kag0k_eSb24U2ENYGvC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L99)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should it be plural ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-Kafq1gJf2--pxS2jnVF:-Kag0l4N53hmzUrAuai5:bxtnn2u) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L112)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`@see setSortOrderS`
+
mention that this is a shorthand ?
</blockquote></details>

What's the benefit of adding a `@see` to another method that has basically identical javadocs?

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafwpFKmQjzTUGcXEnV:-Kag31i86OVMY3ZabKq5:b293qgo) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L98)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The method name is confusing since it sets behavioural strategy rather than object.
Don't know a better name though.

`setSortOrderComparator` ?

By the way : shouldn't this be `SerializableComparator` ?
</blockquote></details>

`setSortOrderComparator` is quite long. What about just `setComparator`, `setSortComparator` or `setSortingComparator`?

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafxfgXHxN4AJzo_2UR:-Kag2uYy92Wb9rIZaer4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L136)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Same issue with the method name.
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafymPF6GmapL4DKT8S:-Kag3OFKd9Ei8eU8UApK:ba6tvhf) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java#L205)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

What does `setSortOrder` do here ? (don't see it's impl, it should be test class instance method).
If it delegates to `dataProvider.setSortOrder` then is `refreshAll()`needed here ?
</blockquote></details>

I don't really understand the point of the previous version of the test either. It was originally introduced with the `refreshAll()` method in  https://github.com/vaadin/framework/commit/62d712fb4514b2ed118539f43967c9b24d906518. From what I can see, `refreshAll()` wouldn't have any other effect than firing an event, but there doesn't seem to be anything in the test that actually depends on that event being fired.

Unless you can find out any explanation for what the test is supposed to do, I'd just suggest removing it together with all other tests prefixed with `refreshAll_`?

`setSortOrder` applies either the `SortOrder` instance or the  comparator to the currently tested data provider instance. It's an abstract method defined in the beginning of this class (line 52) and then implemented separately in `ListDataProviderTest` and `BackendDataProviderTest`.

---

*[server/src/test/java/com/vaadin/data/provider/StrBean.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafzQ1KGlt0Xgyvy68N:-Kag8kNuslDV-46WWgs1:bb7m3jc) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/StrBean.java#L59)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

?
</blockquote></details>

oops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 5 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-Kafq1gJf2--pxS2jnVF:-KagApznKauKG2Ifu_lD:b2b2vsd) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L112)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What's the benefit of adding a `@see` to another method that has basically identical javadocs?
</blockquote></details>

Referring to a method which this method is shorthand for ?

The main point here: two methods modifies the same state. So there shouldn't be surprise for the user that 
```
setSortOrders(Arrays.asList(a,b);
setSortOrder(c);
``` 

is the same as
`setSortOrder(c)` .

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafwpFKmQjzTUGcXEnV:-KagC_l2BjS-pKJsHbKL:bmtp2b5) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L98)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`setSortOrderComparator` is quite long. What about just `setComparator`, `setSortComparator` or `setSortingComparator`?
</blockquote></details>

`setSortComparator` I think is good enough.

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafxfgXHxN4AJzo_2UR:-KagGTUPeuusmRHHZV6l:b9x08gp) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L136)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Method name is not really corrected (but it's the same as above).

---

*[server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafymPF6GmapL4DKT8S:-KagFEXa4rXRG7EmZj7u:bobop3k) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java#L205)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I don't really understand the point of the previous version of the test either. It was originally introduced with the `refreshAll()` method in  https://github.com/vaadin/framework/commit/62d712fb4514b2ed118539f43967c9b24d906518. From what I can see, `refreshAll()` wouldn't have any other effect than firing an event, but there doesn't seem to be anything in the test that actually depends on that event being fired.

Unless you can find out any explanation for what the test is supposed to do, I'd just suggest removing it together with all other tests prefixed with `refreshAll_`?

`setSortOrder` applies either the `SortOrder` instance or the  comparator to the currently tested data provider instance. It's an abstract method defined in the beginning of this class (line 52) and then implemented separately in `ListDataProviderTest` and `BackendDataProviderTest`.

</blockquote></details>

Actually , yes. The tests originally were in ListDataSourceTest.java and they have no sense without DataCommunicator which should refetch data on handling an event. So they can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by Legioth** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-Kafq1gJf2--pxS2jnVF:-KagSvSqxZaDM0bpUMpr:b-4zn2iy) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L112)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Referring to a method which this method is shorthand for ?

The main point here: two methods modifies the same state. So there shouldn't be surprise for the user that 
```
setSortOrders(Arrays.asList(a,b);
setSortOrder(c);
``` 

is the same as
`setSortOrder(c)` .
</blockquote></details>

Good point. I'll remove the mention of which is a shorthand for which and instead just document for both that they manipulate the same state.

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafxfgXHxN4AJzo_2UR:-KagUmtU9xZBb5vQr3pf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L136)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Method name is not really corrected (but it's the same as above).
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafymPF6GmapL4DKT8S:-KagUwDBth5mQ7T9gmQg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/test/java/com/vaadin/data/provider/DataProviderTestBase.java#L205)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Actually , yes. The tests originally were in ListDataSourceTest.java and they have no sense without DataCommunicator which should refetch data on handling an event. So they can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by Legioth** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/ListDataProvider.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8247#-KafwpFKmQjzTUGcXEnV:-KagW-N4LnnsVIjrUw81:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3caab2599e366f01cc1ac4a50b9dc773b4c7431f/server/src/main/java/com/vaadin/data/provider/ListDataProvider.java#L98)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`setSortComparator` I think is good enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 4 files at r3.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8247)*

**Pull request merged**
