### PR TITLE
Upgrade maven-dependency and -source plugins

### PR DESCRIPTION
**Pull request by asashour**
1. Upgrade `maven-dependency-plugin` to `3.0.1`, it was `2.10`, and referenced as `3.0.0`
2. Upgrade `maven-source-plugin` to `3.0.1`, it was `3.0.0`
3. Unify `javax.servlet-api` to `3.1.0`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9986)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 9 files at r1.
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 194 at r1](https://reviewable.io:443/reviews/vaadin/framework/9986#-Ktz-lPGGrQGMhFkSlt-:-Ktz-lPGGrQGMhFkSlt0:bal6xgo) ([raw file](https://github.com/vaadin/framework/blob/5242ffd79be35f48b7dbd8632b6e13a25205023c/pom.xml#L194)):*
> ```XML
>                 <groupId>javax.servlet</groupId>
>                 <artifactId>javax.servlet-api</artifactId>
>                 <version>3.1.0</version>
> ```

Unfortunately we cannot raise the required servlet version for the project from 3.0.x, which was selected as the minimum supported version for Vaadin Framework 8. Some test modules (at least uitest) intentionally used a higher version to use new features of 3.1, but this top-level version that determines the compatibility of the classes in the distributed JARs is fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9986)*

**Comment by asashour** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 194 at r1](https://reviewable.io:443/reviews/vaadin/framework/9986#-Ktz-lPGGrQGMhFkSlt-:-Ktz6U5z_0qeAMlb6ASo:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/5242ffd79be35f48b7dbd8632b6e13a25205023c/pom.xml#L194)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Unfortunately we cannot raise the required servlet version for the project from 3.0.x, which was selected as the minimum supported version for Vaadin Framework 8. Some test modules (at least uitest) intentionally used a higher version to use new features of 3.1, but this top-level version that determines the compatibility of the classes in the distributed JARs is fixed.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9986)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9986)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9986#-:-Ktz93wV1E3nOhj734Fe:bnfp4nl)*

**Pull request merged**
