### PR TITLE
Add feature to disable collapsing items in TreeGrid

### LINKED ISSUE #8846: When showing a tree to the user, I want to disable collapsing an expanded node, so that user can't collapse that node
TreeGrid.class:
```java
void setItemCollapseDisabledProvider(SerializableFunction<T, Boolean> provider);
```

Should disable events (click & keyboard) for that node, and give a class name to that row / cell, by default grey-out the collapsing indicator.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #8846

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8879)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 140 at r1](https://reviewable.io:443/reviews/vaadin/framework/8879#-KffHJYLy-y03CZ4-Ids:-KffHJYMSP5Jz2QBRBWG:bvm57ki) ([raw file](https://github.com/vaadin/framework/blob/72e4122514ca26160c191714839eab9e45efd1c1/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L140)):*
> ```Java
>                                     ClickableRenderer.RendererClickEvent<JsonObject> event) {
>                                 try {
>                                     if (!isCollapsed(event.getRow())
> ```

does this prevent opening any collapsed node if the toggle did both?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 234 at r1](https://reviewable.io:443/reviews/vaadin/framework/8879#-KffHXZOpVae2F6BZKyc:-KffHXZOpVae2F6BZKyd:b-40vwpn) ([raw file](https://github.com/vaadin/framework/blob/72e4122514ca26160c191714839eab9e45efd1c1/server/src/main/java/com/vaadin/ui/TreeGrid.java#L234)):*
> ```Java
>      *            the item collapse disabled provider, not {@code null}
>      */
>     public void setItemCollapseDisabledProvider(
> ```

especially in end-user API, negatives like "disabled" are harder than positives like "enabled" so I'd consider switching this to setItemCollapseEnabledProvider() or setItemCollapseAllowedProvider(); internally we could still use "disable" to save on transmitted data etc.

---

*[shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridCommunicationConstants.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8879#-KffHyNQR-sHxNlOtcrl:-KffHyNQR-sHxNlOtcrm:bbl8j5a) ([raw file](https://github.com/vaadin/framework/blob/72e4122514ca26160c191714839eab9e45efd1c1/shared/src/main/java/com/vaadin/shared/ui/treegrid/TreeGridCommunicationConstants.java#L36)):*
> ```Java
> 
>     /**
>      * This key is close to the {@link GridState#JSONKEY_CELLDESCRIPTION}. Upper
> ```

should the javadoc state what this is about, not just the special issue - could use an ordinary comment, or a first sentence in javadoc explaining what this actually is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 8 files at r1, 5 of 7 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeatures.java, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/8879#-KffeoQmbhylUOf4dZlD:-KffeoQmbhylUOf4dZlE:b-84f04c) ([raw file](https://github.com/vaadin/framework/blob/714ac5686c4305c25c3b1fef2eddaf10ae20ec45/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeatures.java#L108)):*
> ```Java
>     }
> 
>     private void createCollapseDisabledSelect() {
> ```

still talking about collapse disabled, predicates the wrong way around?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by tsuoanttila** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeatures.java, line 108 at r2](https://reviewable.io:443/reviews/vaadin/framework/8879#-KffeoQmbhylUOf4dZlD:-Kfg6xXX7Qq-Dm_ytOUl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/714ac5686c4305c25c3b1fef2eddaf10ae20ec45/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeatures.java#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

still talking about collapse disabled, predicates the wrong way around?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridCollapseDisabledTest.java, line 76 at r3](https://reviewable.io:443/reviews/vaadin/framework/8879#-Kfje2sbogK9aoWTWj_T:-Kfje2sbogK9aoWTWj_U:b-n89ttp) ([raw file](https://github.com/vaadin/framework/blob/80b218d246af52b359453838d5c9fbc887764982/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridCollapseDisabledTest.java#L76)):*
> ```Java
>      */
>     @Test
>     public void json_for_cell_description_not_overridden() {
> ```

(I think this test is no longer really needed as the key changed)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjmfrR4cF75nXf5NHJ:-KfjmfrSFbI_O89_0O2_:b-ms46a6) (no related file):*
Where is the indication to the user that this node cannot be collapsed ??
How can I theme the indicator to look different when the node cannot be collapsed ?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 229 at r3](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjlUKzPqK7u_bQJZAh:-KfjlUKzPqK7u_bQJZAi:b-kkhzcw) ([raw file](https://github.com/vaadin/framework/blob/80b218d246af52b359453838d5c9fbc887764982/server/src/main/java/com/vaadin/ui/TreeGrid.java#L229)):*
> ```Java
>      * Sets the item collapse allowed provider for this TreeGrid. The provider
>      * should return {@code true} for any item that the user can collapse.
>      *
> ```

Could mention that since the callback is called quite often, the user should not do any costly in the provider.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjyCBjlcVC5Z_Qkwkj:-KfjyCBkpaaJaCMrLw0V:b585uyc) (no related file):*
Where is the documentation update for this feature ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjyCBjlcVC5Z_Qkwkj:-Kfk2cn_3RkPL0zIFXiU:b21purr) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Where is the documentation update for this feature ?
</blockquote></details>

I need to rebase the patch to get the basic treegrid documentation in here. Let's solve first the remaining issues (theming of the non-collapsible node) and then look at the docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by tsuoanttila** [comment]
Refactored to use the renderer and data communicator to handle most of the operations. Data now stored in the row hierarchy data instead of top level of the json.

---

Review status: 3 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjmfrR4cF75nXf5NHJ:-KfkZ-3oPM9cRotMjrm8:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Where is the indication to the user that this node cannot be collapsed ??
How can I theme the indicator to look different when the node cannot be collapsed ?
</blockquote></details>

Done

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfjyCBjlcVC5Z_Qkwkj:-KfkZ-guog4RlNS-5nu1:bb6un1j) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I need to rebase the patch to get the basic treegrid documentation in here. Let's solve first the remaining issues (theming of the non-collapsible node) and then look at the docs.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879#-:-KfkZ13EGDxhI7ImZUf7:bimmmus)*

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r2, 4 of 9 files at r5.
Review status: 7 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 101 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-Kfk_tBEoGwz7enGSOGK:-Kfk_tBFx30kNgwauT2A:b-olc3cy) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/documentation/components/components-treegrid.asciidoc#L101)):*
> ```AsciiDoc
> It can be set with [methodname]#setItemCollapseAllowedProvider# method, that takes a [classname]#SerializablePredicate#.
> 
> Avoid doing any heavy operations in the method, since it is called for each item when it's being sent to the client.
> ```

(preferably avoid contraction it's)

---

*[documentation/components/components-treegrid.asciidoc, line 109 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-Kfka02idiYl2mDmfyeU:-Kfka02idiYl2mDmfyeV:b32w03) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/documentation/components/components-treegrid.asciidoc#L109)):*
> ```AsciiDoc
> personTreeGrid.setItemCollapseAllowedProvider(person -> 
>        !alwaysExpanded.contains(person));
> ----
> ```

NL

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 47 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfkaZkTlLQ3POrljv_q:-KfkaZkTlLQ3POrljv_r:b-ftfjbd) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L47)):*
> ```SCSS
> 
>     &.collapse-disabled {
>       opacity: .3;
> ```

@include opacity($v-disabled-opacity);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by tsuoanttila** [comment]
Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss, line 47 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfkaZkTlLQ3POrljv_q:-KfkdzviMMOtuhKUzO26:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/themes/src/main/themes/VAADIN/themes/valo/components/_treegrid.scss#L47)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@include opacity($v-disabled-opacity);
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 3 of 9 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 109 at r6](https://reviewable.io:443/reviews/vaadin/framework/8879#-Kfkk3GaaNjxq6eJJ08q:-Kfkk3GbzhGMehIa5ghd:bjjb5x5) ([raw file](https://github.com/vaadin/framework/blob/275a652664c93ccb8168a8e5c55c901d5c8214a5/documentation/components/components-treegrid.asciidoc#L109)):*
> ```AsciiDoc
> personTreeGrid.setItemCollapseAllowedProvider(person -> 
>        !alwaysExpanded.contains(person));
> ----
> ```

Please mention the style name given to the non-collapsible element here. E.g.
"For nodes that cannot be collapsed, the `collapse-disabled` class name is applied to the expansion element". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by pleku** [comment]
Reviewed 4 of 5 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r10.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 57 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfuXV3-M_6zgFRxF-g4:-KfuXV3-M_6zgFRxF-g5:b4mniaa) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L57)):*
> ```Java
> 
>     // Expander click event handling
>     private HandlerRegistration expanderClickHandlerRegistration;
> ```

no need to unregister this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by tsuoanttila** [comment]
*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 57 at r5](https://reviewable.io:443/reviews/vaadin/framework/8879#-KfuXV3-M_6zgFRxF-g4:-Kfug_hFWaZpsLKT1dp3:bnnqnvh) ([raw file](https://github.com/vaadin/framework/blob/cf2d0ab2fa070e24b997067e8c2003ced29b72f0/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L57)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

no need to unregister this?
</blockquote></details>

See latest patch. It was moved into HierarchyRenderer in this patch to make the renderer usable for possible Tree component as well (should we make it not extends TreeGridConnector). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8879)*

**Pull request merged**
