### PR TITLE
Add Listing.setItems(Stream)

### PR DESCRIPTION
**Pull request by pleku**
Fixes vaadin/framework8-issues#447

Change-Id: I4d557d346117d308b80a20effbf5359bebe1e8bb

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/90)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/90#-KYDwPom4hPeWuPhIgx9:-KYDwPom4hPeWuPhIgxA:b-v6o8dk) ([raw file](https://github.com/vaadin/framework/blob/51d2b4470f904242dc85abdd7d0fcc8db908667a/server/src/main/java/com/vaadin/server/data/DataProvider.java#L178)):*
> ```Java
>      * list</b>.
>      * <p>
>      * This is just a shorthand for using {@link #create(Collection)} after
> ```

It might make sense to add a note here that a `Stream` can be very big and it's not supposed to be used with big streams. Lazy container should be used on this case. And this is just a convenience  method when there is a Stream representation of a list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/90)*

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/data/DataProvider.java, line 178 at r1](https://reviewable.io:443/reviews/vaadin/framework/90#-KYDwPom4hPeWuPhIgx9:-KYDxgPbp2D5Eh7cymJv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/51d2b4470f904242dc85abdd7d0fcc8db908667a/server/src/main/java/com/vaadin/server/data/DataProvider.java#L178)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It might make sense to add a note here that a `Stream` can be very big and it's not supposed to be used with big streams. Lazy container should be used on this case. And this is just a convenience  method when there is a Stream representation of a list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/90)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/90)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/90)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/90)*

**Pull request merged**
