### PR TITLE
Remove unused methods

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10020)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 12 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/TreeData.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOnfWJOfOz4JnL8NsI:-KuOnfWJOfOz4JnL8NsJ:b-uggd1f) ([raw file](https://github.com/vaadin/framework/blob/4ea0e3ee0a1fb3cca47f06a5fecf91db4f6feb79/server/src/main/java/com/vaadin/data/TreeData.java#L45)):*
> ```Java
> public class TreeData<T> implements Serializable {
> 
>     private static class HierarchyWrapper<T> implements Serializable {
> ```

This class is not really a wrapper anymore after the change, but something else. Would you have a suggestion for an alternative name for it?

---

*[server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOpK8YGXWfODCqtov_:-KuOpK8YGXWfODCqtova:bp4l3y4) ([raw file](https://github.com/vaadin/framework/blob/4c2963ac4e0f5b2a9a59bd7791f7ea563acae6eb/server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java#L268)):*
> ```Java
>             }
> 
>             public StreamVariable getReceiver() {
> ```

@wbadam any reason why this should still be here? I guess it can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by wbadam** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOpK8YGXWfODCqtov_:-KuOukcu9t7yqqJcvKmV:boiwy16) ([raw file](https://github.com/vaadin/framework/blob/4c2963ac4e0f5b2a9a59bd7791f7ea563acae6eb/server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java#L268)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@wbadam any reason why this should still be here? I guess it can be removed.
</blockquote></details>

Seems to be legacy, `DragAndDropWrapper` doesn't seem to use the similar method either

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by asashour** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/TreeData.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOnfWJOfOz4JnL8NsI:-KuP5uzBYGO5zoMGA_SY:b-yu13qv) ([raw file](https://github.com/vaadin/framework/blob/4ea0e3ee0a1fb3cca47f06a5fecf91db4f6feb79/server/src/main/java/com/vaadin/data/TreeData.java#L45)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This class is not really a wrapper anymore after the change, but something else. Would you have a suggestion for an alternative name for it?
</blockquote></details>

Actually, it holds information about `parent` and `children`, but not `self`. It can be `HierarchyWrapper`, `HierarchyHolder`, `Generation`, `Relation` or something similar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by asashour** [comment]
Review status: 10 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java, line 268 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOpK8YGXWfODCqtov_:-KuT0ffBd_m0Tbc_nrOv:b-vict76) ([raw file](https://github.com/vaadin/framework/blob/4c2963ac4e0f5b2a9a59bd7791f7ea563acae6eb/server/src/main/java/com/vaadin/ui/dnd/FileDropTarget.java#L268)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Seems to be legacy, `DragAndDropWrapper` doesn't seem to use the similar method either
</blockquote></details>

I just added a second removal commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by hesara** [comment]
Reviewed 1 of 13 files at r1, 2 of 2 files at r2.
Review status: 13 of 24 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 13 files at r1, 2 of 2 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/TreeData.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10020#-KuOnfWJOfOz4JnL8NsI:-KuTm4SXXo6o5xMH8C4V:by96p4m) ([raw file](https://github.com/vaadin/framework/blob/4ea0e3ee0a1fb3cca47f06a5fecf91db4f6feb79/server/src/main/java/com/vaadin/data/TreeData.java#L45)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Actually, it holds information about `parent` and `children`, but not `self`. It can be `HierarchyWrapper`, `HierarchyHolder`, `Generation`, `Relation` or something similar
</blockquote></details>

Let's not delay merging this change with the naming - it can be renamed later, but is private and quite internal so not a big problem if left as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10020)*

**Pull request merged**
