### PR TITLE
Fix since tags part1

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8575)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 134 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd52SkBMs4nrhHyv0LR:-Kd52SkBMs4nrhHyv0LS:b-ks7eat) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L48)):*
> ```Java
>  * @param <T>
>  *            the grid bean type
>  * @since 8.0 s
> ```

Extra letter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575)*

**Comment by hesara** [comment]
Review status: 0 of 134 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd52SkBMs4nrhHyv0LR:-Kd53nQ0ZQl6GxLq65VD:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L48)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra letter
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575)*

**Comment by elmot** [comment]
Reviewed 4 of 134 files at r1.
Review status: 4 of 134 files reviewed at latest revision, 12 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/AbstractTextFieldWidget.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd55pxHkJ7-3XdYTfJI:-Kd55pxHkJ7-3XdYTfJJ:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/AbstractTextFieldWidget.java#L23)):*
> ```Java
>  * Implemented by all widgets used by a connector extending
>  * {@link AbstractTextFieldConnector}.
>  * 
> ```

extra space

---

*[client/src/main/java/com/vaadin/client/ui/HasErrorIndicator.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd55zNBEozUm1q-mLcL:-Kd55zNCTe1oax04ABX6:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/HasErrorIndicator.java#L22)):*
> ```Java
> /**
>  * Implemented by connectors supporting an error indicator.
>  * 
> ```

Extra space

---

*[client/src/main/java/com/vaadin/client/ui/HasRequiredIndicator.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd567UMXYVM1ySrB38z:-Kd567UMXYVM1ySrB39-:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/HasRequiredIndicator.java#L22)):*
> ```Java
> /**
>  * Implemented by connectors supporting a required flag.
>  * 
> ```

extra space

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd56N960ye34sc7DWcK:-Kd56N960ye34sc7DWcL:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L90)):*
> ```Java
>  *
>  * TODO needs major refactoring (to be extensible etc)
>  * 
> ```

extra space

---

*[client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd55ZX8d-04A0XyCwfQ:-Kd55ZX8d-04A0XyCwfR:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java#L31)):*
> ```Java
> /**
>  * Connector class for AbstractTextField.
>  * 
> ```

Extra space

---

*[client/src/main/java/com/vaadin/client/ui/textfield/ValueChangeHandler.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd55g5sqq9WSDEtLCE_:-Kd55g5sqq9WSDEtLCEa:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/client/src/main/java/com/vaadin/client/ui/textfield/ValueChangeHandler.java#L26)):*
> ```Java
>  * Helper for dealing with scheduling value change events based on a given mode
>  * and possibly timeout.
>  * 
> ```

Extra space

---

*[shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaClientRpc.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd53iT3GxV8tMi08sXX:-Kd53iT3GxV8tMi08sXY:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaClientRpc.java#L22)):*
> ```Java
> /**
>  * Server to client RPC interface for RichTextArea.
>  * 
> ```

Extra space

---

*[shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaServerRpc.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd53taunPtSDYhqnk2K:-Kd53taunPtSDYhqnk2L:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaServerRpc.java#L22)):*
> ```Java
> /**
>  * Client to server RPC interface for RichTextArea.
>  * 
> ```

Extra space

---

*[shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaState.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd549wQmkQkCtgACBTs:-Kd549wQmkQkCtgACBTt:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/shared/src/main/java/com/vaadin/shared/ui/richtextarea/RichTextAreaState.java#L25)):*
> ```Java
> /**
>  * State for RichTextArea.
>  * 
> ```

Extra space

---

*[shared/src/main/java/com/vaadin/shared/ui/textfield/AbstractTextFieldClientRpc.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd54j5nij1t30azqByu:-Kd54j5nij1t30azqByv:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/shared/src/main/java/com/vaadin/shared/ui/textfield/AbstractTextFieldClientRpc.java#L22)):*
> ```Java
> /**
>  * Server to client RPC interface for AbstractTextField.
>  * 
> ```

Extra space

---

*[shared/src/main/java/com/vaadin/shared/ui/textfield/TextFieldState.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8575#-Kd54VqdSBQu14j3TRSl:-Kd54VqdSBQu14j3TRSm:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/cb26565b6b02da719b82b66876e059457d35d540/shared/src/main/java/com/vaadin/shared/ui/textfield/TextFieldState.java#L20)):*
> ```Java
> /**
>  * State class for TextField.
>  * 
> ```

Extra space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 5 of 134 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575#-:-Kd57wy_3eNPH6mKjTY4:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 35 of 134 files at r1.
Review status: 40 of 134 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575)*

**Comment by elmot** [comment]
Reviewed 94 of 134 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8575#-:-Kd59h1jVBpbMZW__Td3:bnfp4nl)*

**Pull request merged**
