### PR TITLE
Add missing FocusShortcutListener

### LINKED ISSUE #8297: Vaadin 8 Shortcut Keys API reference contains no longer existing AbstractField.FocusShortcut objects.
Hello.
I'm using the latest snapshot version of Vaadin 8 framework and currently trying to understand how shortcutListeners are created.
I've opened the [Shortcut Keys](https://vaadin.com/docs8/-/part8/framework/advanced/advanced-shortcuts.html) api reference page and it has a lot of examples mentioning the `AbstractField.FocusShortcut` class.
But I can not find any FocusShortcut class in the framework at all.

Can you please update the documentation?

### PR DESCRIPTION
**Pull request by MichaelF25**
Was removed from 8.0 and not readded.

Fixes #8297

Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11289)

### CODE REVIEW

**Review by ZheSun88 — COMMENTED** [review]
Thanks for the contribution and I have fixed the usage of testbench to run the tests correctly.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11289#-:-LQiRcPCEijkQk5Ky62h:bd4j6ry)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ZheSun88)

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r5, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11289)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by elmot — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11289#-:-LQnRT3m48yOHcTdb5jA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by elmot — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11289#-:-LS-XqQy7Bf26uOGmBfC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11289)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
