### PR TITLE
 Correctly handle data providers with overriden getId 

### PR DESCRIPTION
**Pull request by anasmi**
Resolve: #10647 #10498 

Originally [patch](https://github.com/vaadin/framework/compare/master...Artur-:_multiselect-dataprovider-getid?expand=1) by @Artur- 

+Merged master branch
+Added tests

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10728)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 2 of 4 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java, line 35 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82v3njDAEmplizL-L9:-L82v3njDAEmplizL-LA:bpvz36p) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java#L35)):*
> ```Java
>     public TwinColSelect<ItemWithId> selectToTest;
> 
>     private List<Set<String>> values;
> ```

unused variable

---

*[server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java, line 37 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82v55uAneBIEqBlCiH:-L82v55uAneBIEqBlCiI:bpvz36p) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java#L37)):*
> ```Java
>     private List<Set<String>> values;
> 
>     private List<Set<String>> oldValues;
> ```

unused variable

---

*[uitest/src/main/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProvider.java, line 30 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82vnEZ-_BJx1lYf_wM:-L82vnEZ-_BJx1lYf_wN:b-d0bdva) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/uitest/src/main/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProvider.java#L30)):*
> ```Java
> 
> @Widgetset("com.vaadin.DefaultWidgetSet")
> public class TwinColSelectAndIdBasedDataProvider extends AbstractTestUIWithLog {
> ```

No test for this UI ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10728)*

**Comment by anasmi** [comment]
*[server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java, line 35 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82v3njDAEmplizL-L9:-L835EeN0wzx_Hv9WwWh:bss4a1b) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

unused variable
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10728)*

**Comment by anasmi** [comment]
*[server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java, line 37 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82v55uAneBIEqBlCiH:-L835GSL3j7oUDQixerw:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/server/src/test/java/com/vaadin/ui/AbstractMultiSelectUsingIdTest.java#L37)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

unused variable
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10728)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProvider.java, line 30 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10728#-L82vnEZ-_BJx1lYf_wM:-L83-YvJ9_edyXW-3NPV:b-iw1p49) ([raw file](https://github.com/vaadin/framework/blob/03264fbb4b5e28523957a6f8ef475131d1e2dca6/uitest/src/main/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProvider.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

No test for this UI ?
</blockquote></details>

Added test

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10728)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java, line 27 at r5](https://reviewable.io:443/reviews/vaadin/framework/10728#-L87g80poovgsZ4CGSzY:-L87g80poovgsZ4CGSzZ:b-e1v4p2) ([raw file](https://github.com/vaadin/framework/blob/6c04646e9df4eb1b15da8d1068e3d6037ebd7a43/uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java#L27)):*
> ```Java
>         assertEquals(twinCS.getValues().size(), 0);
>     }
> }
> ```

nitpick: missing newline at end of file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10728)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10728)*

**Comment by anasmi** [comment]
@tsuoanttila I think I miss something... 
That is the class I have changed, this line should not be there at all

**Comment by anasmi** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java, line 27 at r5](https://reviewable.io:443/reviews/vaadin/framework/10728#-L87g80poovgsZ4CGSzY:-L8BGpTSZQxhFL7Gp_KP:b-bzoa3i) ([raw file](https://github.com/vaadin/framework/blob/6c04646e9df4eb1b15da8d1068e3d6037ebd7a43/uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

nitpick: missing newline at end of file.
</blockquote></details>

Is it the right version of the class ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10728)*

**Comment by anasmi** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java, line 27 at r5](https://reviewable.io:443/reviews/vaadin/framework/10728#-L87g80poovgsZ4CGSzY:-L8BHcdF77YcxGN8vQJL:bbn1ica) ([raw file](https://github.com/vaadin/framework/blob/6c04646e9df4eb1b15da8d1068e3d6037ebd7a43/uitest/src/test/java/com/vaadin/tests/components/twincolselect/TwinColSelectAndIdBasedDataProviderTest.java#L27)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Is it the right version of the class ? 
</blockquote></details>

But the same problem in newer version,fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10728)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10728#-:-L8BuTm6P4_S_0EVfj7q:bnfp4nl)*

**Pull request merged**
