### PR TITLE
Fix report generation scripts

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11140)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11140)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[scripts/GeneratePublishReportPart1.py, line 13 at r1](https://reviewable.io/reviews/vaadin/framework/11140#-LKf4zvp04n4gR-oyyYH:-LKf4zvp04n4gR-oyyYI:be6926l) ([raw file](https://github.com/vaadin/framework/blob/d4f06df4f696acdef22f983556e8dcd40caab3f1/scripts/GeneratePublishReportPart1.py#L13)):*
> ```Python
> 
> metadataChecks = {
> 	'https://vaadin.com/download/LATEST8': '^8\..*',
> ```

Do we need to check 8 here

**Review by tsuoanttila — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11140)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[scripts/GeneratePublishReportPart1.py, line 13 at r1](https://reviewable.io/reviews/vaadin/framework/11140#-LKf4zvp04n4gR-oyyYH:-LKf9iNB0-q2S2N_RRWK:b-qdxqrg) ([raw file](https://github.com/vaadin/framework/blob/d4f06df4f696acdef22f983556e8dcd40caab3f1/scripts/GeneratePublishReportPart1.py#L13)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Do we need to check 8 here
</blockquote></details>

Just a double check. Not really needed, but I don't really see the harm in making sure all these are correct.

**Review by elmot — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11140)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by elmot — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11140)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
