### PR TITLE
Support Firefox 65+ key down event behavior (#11502)

### LINKED ISSUE #11502: Up and Down arrows do not work in Firefox 65
## Description of the bug

Navigation arrows do not work in UI components with Firefox 65.

Affected UI components:

- MenuBar
- Slider
- V7 Tree
- Table
- V7 Slider
- Calendar

Vaadin Framework version 8.0.* - 8.7.*
Browser version: Firefox 65.0+

## Minimal reproducible example

1. Open UI with Table / Slider / MenuBar component
2. Hit Up/Down arrow button in Table or in MenuBar (or left/right in Slider)

- Expected behavior

Arrow buttons should change selected row / value of component.

- Actual behavior

Nothing happens.

## Proposed fixes

We need to disable old workaround with key press event handlers for Firefox 65+:

https://github.com/cuba-platform/vaadin/commit/4d2df4a51afe3756bbc232b5758854c2a237e8e0

https://github.com/cuba-platform/vaadin/commit/83b786529e42c8b2b10348647587e48ddc384fe9

### PR DESCRIPTION
**Pull request by jreznot**
Support Firefox 65+ key down event behavior

Fixes #11502

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11503)

### CODE REVIEW

**Review by TatuLund — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11503)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @jreznot)

___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java, line 219 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-Lan_cFPCpD1wFHCNcbD:-Lan_cFPCpD1wFHCNcbE:bvu6rjr) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java#L219)):*
> ```Java
>          * handler
>          */
>         if (BrowserInfo.get().isGecko() && BrowserInfo.get().getGeckoVersion() < 65) {
> ```

Reflect this change in comment above
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 574 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-Lan_jeZ0tgu_EW5hpIZ:-Lan_je_BFTqnfEvjDuq:bs7mjs7) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L574)):*
> ```Java
>             // works correctly only if we use a key press handler, other
>             // browsers handle it correctly when using a key down handler
>             if (!isUseOldGeckoNavigation()) {
> ```

Reflect this change in comment above (check e.g. https://github.com/vaadin/framework/pull/11508/files ). I also think useOldGeckoNavigation would be better naming.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 639 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaA2Q0MunLYUKMe5v:-LanaA2Q0MunLYUKMe5w:b-ya81ng) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L639)):*
> ```Java
>             NativeEvent event = keyDownEvent.getNativeEvent();
>             // This is not used for Firefox
>             if (isUseOldGeckoNavigation()) {
> ```

Same as above
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 847 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaBs11MJyphdCH5X3:-LanaBs11MJyphdCH5X4:b-ya81ng) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L847)):*
> ```Java
>          * handler
>          */
>         if (isUseOldGeckoNavigation()) {
> ```

Same as above
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 865 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaEMs5k3UySev6h9y:-LanaEMs5k3UySev6h9z:b-ya81ng) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L865)):*
> ```Java
>     }
> 
>     private boolean isUseOldGeckoNavigation() {
> ```

Same as above
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTree.java, line 223 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaI9C5H7ZEQxViAF6:-LanaI9C5H7ZEQxViAF7:bajd5hn) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTree.java#L223)):*
> ```Java
>          * handler
>          */
>         if (BrowserInfo.get().isGecko() && BrowserInfo.get().getGeckoVersion() < 65) {
> ```

Reflect the change in the comment above

**Comment by TatuLund** [comment]
@jreznot Thanks for this pull request, it saves a lot of effort from us. I think the changes are trivial and almost ready for the merge. I just pointed about some details in code review, mostly about updating comments to be inline with the changes. I think automated tests are not necessary to be added here, since we already have one included in the prior change we made already with DateField.

**Review by jreznot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11503)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @TatuLund)

___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java, line 219 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-Lan_cFPCpD1wFHCNcbD:-LanhaNU3jIcv3y98I30:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendarPanel.java#L219)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Reflect this change in comment above
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 574 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-Lan_jeZ0tgu_EW5hpIZ:-Lanj2fu2idf3e0iUEzs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L574)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Reflect this change in comment above (check e.g. https://github.com/vaadin/framework/pull/11508/files ). I also think useOldGeckoNavigation would be better naming.
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 639 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaA2Q0MunLYUKMe5v:-Lanj3Do3ZIABbaHARN7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L639)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 847 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaBs11MJyphdCH5X3:-LanjM7g6QUsuQ_UeIou:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L847)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java, line 865 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaEMs5k3UySev6h9y:-LanjbCn4qOtbOMAMS9_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VScrollTable.java#L865)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTree.java, line 223 at r1](https://reviewable.io/reviews/vaadin/framework/11503#-LanaI9C5H7ZEQxViAF6:-LanjShV8eNVCsLhk6fi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7a95faae68182c96f52bf72301673b0d60385b2f/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTree.java#L223)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

Reflect the change in the comment above
</blockquote></details>

Done.

**Review by TatuLund — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11503#-:-LanlEnQEBFSiUHJ0krp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by anasmi — APPROVED** [review]
> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11503)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by anasmi** [comment]
Thanks again for your effort and time in fixing those issues, it really helps us a lot! :)

**Pull request merged**
