### PR TITLE
Introduce XVFB cluster testing

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch adds the ability and configuration
for running tests against cluster running Chrome
browser in XVFB environment.

It also contains multiple fixes for combining
newer Selenium and Chrome as well as fixed
tests that depend on timezones

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10801)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 832 files at r1.
Review status: 3 of 847 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 23 of 832 files at r1.
Review status: 26 of 847 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 7 of 832 files at r1.
Review status: 33 of 847 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 797 of 832 files at r1.
Review status: 807 of 847 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: 820 of 847 files reviewed at latest revision, all discussions resolved.

---

*[uitest/src/test/java/com/vaadin/tests/tb3/PrivateTB3Configuration.java, line 209 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10801#-LA2Su28BUToy6Vhrgpc:-LA2Su28BUToy6Vhrgpd:b-wybq2e) ([raw file](https://github.com/vaadin/framework/blob/366d13cdb23550fa12440a82a6c3123cbd6cd3a4/uitest/src/test/java/com/vaadin/tests/tb3/PrivateTB3Configuration.java#L209)):*
> ```Java
> 
>         if (properties.containsKey(ALLOW_RUN_LOCALLY_PROPERTY)
>                 && properties.get(ALLOW_RUN_LOCALLY_PROPERTY).equals("true")
> ```

To be simplified?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 22 of 22 files at r4.
Review status: 837 of 847 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10801)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r5, 8 of 8 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10801)*

**Comment by tsuoanttila** [comment]
What is this PR missing for merge?

**Pull request merged**
