### PR TITLE
Easy DevelopmentServerLauncher run with maven

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8677)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/pom.xml, line 359 at r1](https://reviewable.io:443/reviews/vaadin/framework/8677#-Kdyn8yI6ZqgtES6tUbk:-Kdyn8yI6ZqgtES6tUbl:bp7uz1t) ([raw file](https://github.com/vaadin/framework/blob/25558896b791373c8001235ce262af974ede1292/uitest/pom.xml#L359)):*
> ```XML
>                 </configuration>
>             </plugin>
>             <plugin>
> ```

I have two concerns with this:
1) that we might want to add some other exec:java goal later (for whatever purpose) at which point it would be necessary to limit which one is executed in each case, but that can be done with profiles, making the above instructions just a little bit more complicated. 
2) exec:java runs the process in the same VM, which might potentially cause some complications with classpath conflicts - we just had such in the Maven plug-in with the migration tool, and I think it is not at all unlikely that the classpaths of DevelopmentServerLauncher and Maven would conflict. The goal exec:exec would be safer as it runs the program in a separate JVM, and it would probably also allow configuring -ea here rather than in the build conf for Maven itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8677)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/pom.xml, line 359 at r1](https://reviewable.io:443/reviews/vaadin/framework/8677#-Kdyn8yI6ZqgtES6tUbk:-Kdyq6D8GnLiR3yYlDrl:bmr7vae) ([raw file](https://github.com/vaadin/framework/blob/25558896b791373c8001235ce262af974ede1292/uitest/pom.xml#L359)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I have two concerns with this:
1) that we might want to add some other exec:java goal later (for whatever purpose) at which point it would be necessary to limit which one is executed in each case, but that can be done with profiles, making the above instructions just a little bit more complicated. 
2) exec:java runs the process in the same VM, which might potentially cause some complications with classpath conflicts - we just had such in the Maven plug-in with the migration tool, and I think it is not at all unlikely that the classpaths of DevelopmentServerLauncher and Maven would conflict. The goal exec:exec would be safer as it runs the program in a separate JVM, and it would probably also allow configuring -ea here rather than in the build conf for Maven itself.
</blockquote></details>

1. There is one more possibility -  starting from maven 3.3.1, one could call explicitly specified execution id, in form of `mvn exec:java@run-development-server`. See [MNG-5768](https://issues.apache.org/jira/browse/MNG-5768), so I don't think potential conflict is an obstacle.
2. Good point, I will update this, and also I will add another `execution` to run the dev server under debugger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8677)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/pom.xml, line 359 at r1](https://reviewable.io:443/reviews/vaadin/framework/8677#-Kdyn8yI6ZqgtES6tUbk:-KdzNtmc-YcKiiee9YzL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/25558896b791373c8001235ce262af974ede1292/uitest/pom.xml#L359)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

1. There is one more possibility -  starting from maven 3.3.1, one could call explicitly specified execution id, in form of `mvn exec:java@run-development-server`. See [MNG-5768](https://issues.apache.org/jira/browse/MNG-5768), so I don't think potential conflict is an obstacle.
2. Good point, I will update this, and also I will add another `execution` to run the dev server under debugger.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8677)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8677#-:-Ke2gU33sPP2pePBENcN:bnfp4nl)*

**Pull request merged**
