### PR TITLE
Add addComponentsAndExpand to horizontal and  vertical layout

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8480)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNc_wSuZ8tS5hJfxAC:-KcNc_wSuZ8tS5hJfxAD:b-vhxfzy) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L80)):*
> ```Java
> 
>         for (Component child : components) {
>             child.setWidth(100, Unit.PERCENTAGE);
> ```

Is this actually wanted? What if we want to keep the component size as is, but just have it get as much space as possible on the layout? 

(for instance have a text field on the left and 2 button on the right, but want to have the text field be small, but still take up space so the buttons are close together on the far right)

---

*[server/src/main/java/com/vaadin/ui/VerticalLayout.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNcpPbbsmotkFIOwtz:-KcNcpPbbsmotkFIOwu-:b5tmjbs) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/VerticalLayout.java#L83)):*
> ```Java
> 
>         for (Component child : components) {
>             child.setHeight(100, Unit.PERCENTAGE);
> ```

See Horizontal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Comment by Legioth** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNc_wSuZ8tS5hJfxAC:-KcNfNaixsqewizHkEbc:b-t6r7f5) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L80)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Is this actually wanted? What if we want to keep the component size as is, but just have it get as much space as possible on the layout? 

(for instance have a text field on the left and 2 button on the right, but want to have the text field be small, but still take up space so the buttons are close together on the far right)
</blockquote></details>

This is wanted in many cases, especially when nesting layouts. The case you are suggesting is also wanted in many cases.

My gut feeling is that both cases are roughly equally important / common. The main difference is that the case where you also need to give the component a 100% size in either direction benefits more from a shorthand than the case where the component size is left.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNc_wSuZ8tS5hJfxAC:-KcNjxKIQEYRRv1-qQbr:b-4vodc8) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L80)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

This is wanted in many cases, especially when nesting layouts. The case you are suggesting is also wanted in many cases.

My gut feeling is that both cases are roughly equally important / common. The main difference is that the case where you also need to give the component a 100% size in either direction benefits more from a shorthand than the case where the component size is left.
</blockquote></details>

I would say this would be good to poll for which is wanted more. I actually can't say which I've used more, but somehow I don't like my sizings to be touched when I only expect to have the slot expanded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Comment by pleku** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNc_wSuZ8tS5hJfxAC:-KcS2rtj1YGQOvXIc5wA:b-s2n7qq) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L80)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I would say this would be good to poll for which is wanted more. I actually can't say which I've used more, but somehow I don't like my sizings to be touched when I only expect to have the slot expanded.
</blockquote></details>

We decided that we keep the similar functionality as in Viritin, and how we chose to include this feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Comment by caalador** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcNc_wSuZ8tS5hJfxAC:-KcS66PbF7hqZEFzYA2O:b-cr5nix) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L80)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

We decided that we keep the similar functionality as in Viritin, and how we chose to include this feature.
</blockquote></details>

I'm fine with what ever you choose. The poll is at 50/50 also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/HorizontalLayout.java, line 68 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcTIk-UUXeR8PUaa0e0:-KcTIk-UUXeR8PUaa0e1:b-vuo9ze) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/HorizontalLayout.java#L68)):*
> ```Java
>      * will be effective. The width of this layout is also set to 100% if it is
>      * currently undefined.
>      *
> ```

Could mayhaps mention that similarly to `addComponent` or `addComponents`, this moves any existing components

---

*[server/src/main/java/com/vaadin/ui/VerticalLayout.java, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8480#-KcTIugOj2hh2r3ZsPpI:-KcTIugOj2hh2r3ZsPpJ:b-vuo9ze) ([raw file](https://github.com/vaadin/framework/blob/ab0eb0a220f3d0c4a2f3e78e70f3a68454c13ac1/server/src/main/java/com/vaadin/ui/VerticalLayout.java#L71)):*
> ```Java
>      * expansion will be effective. The height of this layout is also set to
>      * 100% if it is currently undefined.
>      *
> ```

Could mayhaps mention that similarly to `addComponent` or `addComponents`, this moves any existing components

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8480)*

**Pull request merged**
