### PR TITLE
Introduce DateTimeFile and InlineDateTimeField.

### LINKED ISSUE #8132: Implement DateTimeField and InlineDateTimeField
Similar to the `DateField` and `InlineDateField` components currently implemented for Framework 8, but with these distinctions
* The server-side value type is `LocalDateTime`.
* Supported resolutions are `SECOND`, `MINUTE` and `HOUR`.
* Reuses the visual design of the components in Framework 7.
* Uses the same stylenames as `DateField` and `InlineDateField`. The assumption is that applications want to have the same looks regardless of whether time selection is used or not. The application developer can still add their own stylenames if they want to do some styling that only applies to one of the components.

Someone might want to fix usability issues in the old components as well, but top priority is to restore the old functionality so that there's a baseline for any potential improvements.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8132

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8218)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaCjDd5hkjdgI2fFjiM:-KaCjDd5hkjdgI2fFjiN:b-f4qbhj) (no related file):*
Shouldn't be merged:
- no tests (unit tests, unit tests for declarative support, UI tests)
- javadocs 

But it's available for review: no major changes in the code are planned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
For the reviewers:

Classes VDateTimeCalendarPanel, VDateTimeFieldCalendar, VPopupTimeCalendar aren't written from scratch !!!!
This is old code from v7 which is just adapted to the current code base.

There are plenty places with questionable code but this is not a part of this PR. I'm just restoring the old code with attempt to reduce duplication on the top of the existing code.

So please review keeping this in mind.

---

Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218#-:-KaCmO1JxZFnq0FIxx8u:b2vwuuc)*

**Comment by elmot** [comment]
Reviewed 18 of 25 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VDateTimeCalendarPanel.java, line 369 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHfj4oANB_WOnxrFoo:-KaHfj4oANB_WOnxrFop:b-3yomw3) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/client/src/main/java/com/vaadin/client/ui/VDateTimeCalendarPanel.java#L369)):*
> ```Java
> 
>     @Override
>     protected boolean isBelowMonth(DateTimeResolution resolution) {
> ```

"Below" again. I\d prefer another naming. 
Not a bloker.

---

*[server/src/main/java/com/vaadin/ui/declarative/converters/DesignLocalDateTimeConverter.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHivhbsBPvIerc_4wt:-KaHivhcVrrrZDYFOlwz:b-xojy36) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/server/src/main/java/com/vaadin/ui/declarative/converters/DesignLocalDateTimeConverter.java#L52)):*
> ```Java
>                         .parse(value, LocalDateTime::from);
>                 return Result.ok(date);
>             } catch (DateTimeParseException e) {
> ```

There is approach to name exceptions "ignored" in cases like this.
Minor issue, not a blocker

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateTimeFieldChangeResolution.java, line 40 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHjx87jCMLxfkQcQ6X:-KaHjx88DpYw67h--7w2:baffuuu) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/uitest/src/main/java/com/vaadin/tests/components/datefield/DateTimeFieldChangeResolution.java#L40)):*
> ```Java
>         addComponent(dateField);
> 
>         Label l = new Label("Select resolution");
> ```

single-letter variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VDateTimeCalendarPanel.java, line 369 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHfj4oANB_WOnxrFoo:-KaHzdIGrLIe5lJikB3S:bddwe5q) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/client/src/main/java/com/vaadin/client/ui/VDateTimeCalendarPanel.java#L369)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

"Below" again. I\d prefer another naming. 
Not a bloker.
</blockquote></details>

This is not a new method.
The method is an implementation of method which has been introduced in the previous PR.
Haven't been noticed in the review.

I would prefer another name as well. But don't know which one.

`isMonthOrXXXX` doesn't work here because month is excluded.

---

*[server/src/main/java/com/vaadin/ui/declarative/converters/DesignLocalDateTimeConverter.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHivhbsBPvIerc_4wt:-KaI-FKGQGiCFEyQBxXT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/server/src/main/java/com/vaadin/ui/declarative/converters/DesignLocalDateTimeConverter.java#L52)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

There is approach to name exceptions "ignored" in cases like this.
Minor issue, not a blocker
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateTimeFieldChangeResolution.java, line 40 at r2](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaHjx87jCMLxfkQcQ6X:-KaI-dV88pbuBzynBeh1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/31e05f836cc8317e632b21f7bf0950d7449a9a2d/uitest/src/main/java/com/vaadin/tests/components/datefield/DateTimeFieldChangeResolution.java#L40)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

single-letter variable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by elmot** [comment]
Reviewed 13 of 14 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/AriaDateTimeDisabledTest.java, line 27 at r3](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaIO4bz1FpIhEGIudvi:-KaIO4c-Q--d2fV3oy9j:brzfghe) ([raw file](https://github.com/vaadin/framework/blob/ef70e2050df1426dc4ec8b6805bb6d392144898b/uitest/src/test/java/com/vaadin/tests/components/datefield/AriaDateTimeDisabledTest.java#L27)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> @RunLocally(Browser.PHANTOMJS)
> ```

Runlocally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Review status: 39 of 68 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/AriaDateTimeDisabledTest.java, line 27 at r3](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaIO4bz1FpIhEGIudvi:-KaM_xkT0KT_h3FhhHjm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ef70e2050df1426dc4ec8b6805bb6d392144898b/uitest/src/test/java/com/vaadin/tests/components/datefield/AriaDateTimeDisabledTest.java#L27)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Runlocally
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Now it's ready for review.

---

Review status: 39 of 68 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218#-:-KaMa0d9lcTHA9FiStMo:b-sm117c)*

**Comment by ahie** [comment]
Review status: 39 of 69 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VDateTimeFieldCalendar.java, line 24 at r4](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNLR5tWMVc3QeQnyB8:-KaNLR5tWMVc3QeQnyB9:b-8g9dzk) ([raw file](https://github.com/vaadin/framework/blob/b1d37fd9519b8be90ff53704a081397b2f86eb86/client/src/main/java/com/vaadin/client/ui/VDateTimeFieldCalendar.java#L24)):*
> ```Java
> import com.vaadin.shared.ui.datefield.DateTimeResolution;
> 
> /**
> ```

Empty javadoc.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java, line 167 at r1](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNKNCwY7EpgpwchSKE:-KaNKNCwY7EpgpwchSKF:b-t7e12i) ([raw file](https://github.com/vaadin/framework/blob/774607c7231c13d2a54c691fc685ae08988a23bf/client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java#L167)):*
> ```Java
>                 }
>             }
>         }
> ```

Should this method also flush the rpc queue with `getClient().sendPendingVariableChanges()` like `VDateTimeFieldCalendar`s `updateValueFromPanel`?

---

*[uitest-common/src/main/java/com/vaadin/testbench/customelements/DateTimeFieldElement.java, line 16 at r4](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNFX_KL7hg4YYGtRzh:-KaNFX_KL7hg4YYGtRzi:b-bffi5x) ([raw file](https://github.com/vaadin/framework/blob/b1d37fd9519b8be90ff53704a081397b2f86eb86/uitest-common/src/main/java/com/vaadin/testbench/customelements/DateTimeFieldElement.java#L16)):*
> package com.vaadin.testbench.customelements;

Can't this be moved to the testbench-api package now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Review status: 39 of 69 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VDateTimeFieldCalendar.java, line 24 at r4](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNLR5tWMVc3QeQnyB8:-KaNMeEx-vfOKiTU4sOV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b1d37fd9519b8be90ff53704a081397b2f86eb86/client/src/main/java/com/vaadin/client/ui/VDateTimeFieldCalendar.java#L24)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Empty javadoc.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java, line 167 at r1](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNKNCwY7EpgpwchSKE:-KaNNIqdJBYvpDmw3Coc:b-z6x9c2) ([raw file](https://github.com/vaadin/framework/blob/774607c7231c13d2a54c691fc685ae08988a23bf/client/src/main/java/com/vaadin/client/ui/VPopupTimeCalendar.java#L167)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should this method also flush the rpc queue with `getClient().sendPendingVariableChanges()` like `VDateTimeFieldCalendar`s `updateValueFromPanel`?
</blockquote></details>

The old impl doesn't do it.
This is not a new code. This is restored code from V7.

---

*[uitest-common/src/main/java/com/vaadin/testbench/customelements/DateTimeFieldElement.java, line 16 at r4](https://reviewable.io:443/reviews/vaadin/framework/8218#-KaNFX_KL7hg4YYGtRzh:-KaNOTEoYTO8d-qEj9p9:bhxqfh4) ([raw file](https://github.com/vaadin/framework/blob/b1d37fd9519b8be90ff53704a081397b2f86eb86/uitest-common/src/main/java/com/vaadin/testbench/customelements/DateTimeFieldElement.java#L16)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> package com.vaadin.testbench.customelements;

Can't this be moved to the testbench-api package now?
</blockquote></details>

Two reasons:
- out of the scope of this PR
- this one extends custom `DateFieldElement` which has `openPopup()` and this method is really needed in the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by ahie** [comment]
Review status: 38 of 69 files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/DateTimeFieldConnector.java, line 29 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXIIPyEd7eGYZ8KbP:-KabXIIQNBT5FGSGGuGB:b-ph6dxe) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/DateTimeFieldConnector.java#L29)):*
> ```Java
> import com.vaadin.ui.AbstractLocalDateTimeField;
> 
> /**
> ```

Empty javadoc

---

*[client/src/main/java/com/vaadin/client/ui/datefield/InlineDateTimeFieldConnector.java, line 28 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXRc2uHIWU8tC4dVV:-KabXRc2uHIWU8tC4dVW:b-ph6dxe) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/InlineDateTimeFieldConnector.java#L28)):*
> ```Java
> import com.vaadin.ui.InlineDateTimeField;
> 
> /**
> ```

Empty javadoc

---

*[client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java, line 32 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXd_ym44dmHaNH7qx:-KabXd_ym44dmHaNH7qy:b3l4c8c) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java#L32)):*
> ```Java
> import com.vaadin.shared.ui.datefield.TextualDateFieldState;
> 
> /**
> ```

No description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by ahie** [comment]
Review status: 38 of 69 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/converter/LocalDateTimeToDateConverter.java, line 48 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KagN-t5I9pnAwS3BCc6:-KagN-t5I9pnAwS3BCc7:be8ystr) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/server/src/main/java/com/vaadin/data/converter/LocalDateTimeToDateConverter.java#L48)):*
> ```Java
>      *            the time zone offset to use, not <code>null</code>
>      */
>     public LocalDateTimeToDateConverter(ZoneOffset zoneOffset) {
> ```

`LocalDateToDateConverter` uses `ZoneId`, could this be unified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Review status: 38 of 69 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/DateTimeFieldConnector.java, line 29 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXIIPyEd7eGYZ8KbP:-KagOuyFJnsvbakO_wU4:bdlvsde) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/DateTimeFieldConnector.java#L29)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Empty javadoc
</blockquote></details>

Don't really think that it has any sense to write dumb comments for every connector which just said what's already visible in the connector class declaration (there are many existing connectors without javadocs as well).

But let it be.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/InlineDateTimeFieldConnector.java, line 28 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXRc2uHIWU8tC4dVV:-KagPdLmZpib2wlu_GSZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/InlineDateTimeFieldConnector.java#L28)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Empty javadoc
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java, line 32 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KabXd_ym44dmHaNH7qx:-KagQVphsZ78957sc4E2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java#L32)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

No description.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/LocalDateTimeToDateConverter.java, line 48 at r5](https://reviewable.io:443/reviews/vaadin/framework/8218#-KagN-t5I9pnAwS3BCc6:-KagQYJ_8_L_DbMG9UG6:b-w7mk7k) ([raw file](https://github.com/vaadin/framework/blob/ca7c3341d2d8dabfc8067de7fa8b25c4c172c143/server/src/main/java/com/vaadin/data/converter/LocalDateTimeToDateConverter.java#L48)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

`LocalDateToDateConverter` uses `ZoneId`, could this be unified?
</blockquote></details>

Actually this is out of the scope of this PR.
Added just because it's somehow related.

`LocalDate` needs only `ZoneId` to convert it to `Date`.
`ZoneId` is not enough for `LocalDateTime`.
`LocalDateTime` needs `ZoneOffset`.
`ZoneOffset extends ZoneId` and `LocalDate` converter can be changed to work with `ZoneOffset` instead of `ZoneId` but why ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by ahie** [comment]
Reviewed 29 of 32 files at r4, 1 of 6 files at r6.
Review status: 62 of 70 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
There are still 8 unreviewed files

---

Review status: 62 of 70 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218#-:-KapfLu9Rm-FbLyoNiaI:bxn4vck)*

**Comment by ahie** [comment]
Reviewed 3 of 32 files at r4, 1 of 1 files at r5, 5 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218)*

**Comment by denis-anisimov** [comment]
Thanks !

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8218#-:-KapjQcleYcAvqMgrej9:b-hay2j5)*

**Pull request merged**
