### PR TITLE
Add role="grid" to grid to support aria-multiselectable

### PR DESCRIPTION
**Pull request by knoobie**
Added role="grid" and role="treegrid" to Grid and Treegrid to support aria-multiselectable. (https://www.w3.org/TR/wai-aria/states_and_properties#aria-multiselectable)

The following has to be done now:

>"Authors SHOULD ensure that selected descendants have the aria-selected attribute set to true, and selectable descendant have the aria-selected attribute set to false. Authors SHOULD NOT use the aria-selected attribute on descendants that are not selectable."

__Done.__

Finally after a lot of try and error everything is working fine.

Sorry, I had to add an additional method (#isMultiSelectionAllowed()) to the SelectionModel, because Grid had no access to the Impl classes and aria-multiselectable needs it. So it's kinda a breaking? change?

Additional, how do you want to continue with the following?

>"A treegrid is considered editable unless otherwise specified. To make a treegrid read-only, set the aria-readonly attribute of the treegrid to true. The value of the treegrid element's aria-readonly attribute is implicitly propagated to all of its owned gridcell elements, and will be exposed through the accessibility API. An author may override an individual gridcell element's propagated aria-readonly value by setting the aria-readonly attribute on the gridcell." (https://www.w3.org/TR/wai-aria/roles#treegrid)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10009)

### CODE REVIEW

**Comment by knoobie** [comment]
Some questions:

1.) Any idea why the teamcity build fails? 

> [12:29:53][com.vaadin:vaadin-server] Sep 15, 2017 3:29:53 PM com.vaadin.server.DefaultErrorHandler doDefault
[12:29:53][com.vaadin:vaadin-server] SEVERE: 
[12:29:53][com.vaadin:vaadin-server] java.lang.RuntimeException: Exception produced in init()
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.server.communication.ServletUIInitHandlerTest$4.init(ServletUIInitHandlerTest.java:161)
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.ui.UI.doInit(UI.java:745)
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:216)
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
[12:29:53][com.vaadin:vaadin-server] 	at com.vaadin.server.communication.ServletUIInitHandlerTest.initExceptionNoErrorHandler(ServletUIInitHandlerTest.java:169)

I didn't change anything there. 

2.) Where can I find the code piece that select/deselect rows and where are the rows build? I searched in the whole repo for "row-selected" and didn't find anything useful where I count integrate the missing pieces.

**Comment by knoobie** [comment]
Found the answer to the second question and added the missing aria-select.

**Comment by hesara** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuJgC3ojRdOY8_WN4uo:-KuJgC3ojRdOY8_WN4up:ba8dxyr) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java#L127)):*
> ```Java
>         @Override
>         public boolean isMultiSelectionAllowed() {
>             return isMultiSelectionAllowed;
> ```

nothing allows setting isMultiSelectionAllowed, so this could just as well simply "return true;"

---

*[client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuJgKM50oTqjRng_qC5:-KuJgKM50oTqjRng_qC6:bwiwbd8) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/client/src/main/java/com/vaadin/client/connectors/grid/SingleSelectionModelConnector.java#L87)):*
> ```Java
> 
>         @Override
>         public boolean isMultiSelectionAllowed() {
> ```

nothing allows setting isMultiSelectionAllowed, so this could just as well simply "return false;"

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuIVtW3msviGVDXsoXa:-KuIVtW3msviGVDXsoXb:b7xtza1) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java#L124)):*
> ```Java
> 
>     /**
>      * Checks if the user is allowed to has more than one selection.
> ```

perhaps "... to have more than one item selected." or something like that as having multiple selections could be interpreted differently from allowing the selection of multiple items.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuJgigy3h8CSCguWED9:-KuJgigy3h8CSCguWEDA:bdbqhog) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L49)):*
> ```Java
>      */
>     public TreeGrid() {
>         super("treegrid");
> ```

see my comment for Grid

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6133 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuIWi8tErx-_6yefNEd:-KuIWi8tErx-_6yefNEe:be3gmwa) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6133)):*
> ```Java
>     }
> 
>     public Grid(String ariaRole) {
> ```

undocumented public constructor; I'm also considering whether a setter would be a cleaner solution than a constructor with just a String parameter that could mean anything - any opinion from @tsuoanttila ?

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaMultiselectableTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuIWCr46oE_-rPgv2nr:-KuIWCr46oE_-rPgv2ns:b-mrh6mr) ([raw file](https://github.com/vaadin/framework/blob/21bead091ff2144ade2d3a158a8e4986d975adbb/uitest/src/test/java/com/vaadin/tests/components/grid/GridAriaMultiselectableTest.java#L27)):*
> ```Java
>  * @author Vaadin Ltd
>  */
> public class GridAriaMultiselectableTest extends MultiBrowserTest {
> ```

most likely it would be sufficient to inherit SingleBrowserTest as it seems to me that everything related to this is browser-independent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by knoobie** [comment]
I'm going to change the code to follow your recommendation after the comment of @tsuoanttila.

**Comment by knoobie** [comment]
@hesara Updated the commit with all your proposed changes. 

You can decide if you want to drop the commit https://github.com/vaadin/framework/pull/10009/commits/c72163b2b72d31f2c38fada218ad93aa8b377865 or include it - this would move away from a public string constructor to a method.

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6303 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuOGb4qd-gZwPtND5CP:-KuOGb4qd-gZwPtND5CQ:b-vfz9gj) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6303)):*
> ```Java
>      * @since 8.2
>      */
>     protected void setRole(String role){
> ```

I'm hesitating whether the very generic name "setRole" for the WAI-ARIA role of the table element is good, but on the other hand this is a protected method on the client side and few developers deal directly with this. Maybe @tsuoanttila has an opinion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KvS8cylwP5Xhhw50YXU:-KvS8cylwP5Xhhw50YXV:be5qeq8) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L48)):*
> ```Java
>      * Creates a new instance.
>      */
>     protected TreeGrid() {
> ```

Does this reduce the visibility of the old default constructor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KvS8cylwP5Xhhw50YXU:-KvSHafd7J5fnNs-897U:b-5wmzq8) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L48)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this reduce the visibility of the old default constructor?
</blockquote></details>

I'd keep the non-args constructor public. Just so users can actually use it if they want to.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6303 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuOGb4qd-gZwPtND5CP:-KvSI2uGHjHfJwBJ29Gb:bilr2dx) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6303)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm hesitating whether the very generic name "setRole" for the WAI-ARIA role of the table element is good, but on the other hand this is a protected method on the client side and few developers deal directly with this. Maybe @tsuoanttila has an opinion.
</blockquote></details>

I don't see what other "Role" we might have in the Grid, but putting emphasis into reminding that this is about the WAI-ARIA support wouldn't hurt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by knoobie** [comment]
Review status: 5 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 48 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KvS8cylwP5Xhhw50YXU:-KvSyarf_6-Z6FL0h23T:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L48)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd keep the non-args constructor public. Just so users can actually use it if they want to.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6303 at r2](https://reviewable.io:443/reviews/vaadin/framework/10009#-KuOGb4qd-gZwPtND5CP:-KvSyg1qTz_dEVtfS5fz:b6gq4de) ([raw file](https://github.com/vaadin/framework/blob/8bf7adc1afae2ffd39d3af3cd0836cd66f8f0c5a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6303)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I don't see what other "Role" we might have in the Grid, but putting emphasis into reminding that this is about the WAI-ARIA support wouldn't hurt.
</blockquote></details>

Done. Additionally merged the latest vaadin/master into the branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by hesara** [comment]
:lgtm: but @tsuoanttila still needs to resolve his comments

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009#-:-KvVrHINLzcGsYNneV3J:b342cbq)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10009)*

**Comment by hesara** [comment]
Merged this PR - treegrid aria-readonly attribute can be added in a separate PR if needed.

**Pull request merged**
