### PR TITLE
[WIP] Attempt to unify single select components

### LINKED ISSUE #10611: Channge method visibility in AbstractListing and AbstractSingleSelect.
From Forum:

https://vaadin.com/forum/#!/thread/16960117

"I think it would be a good idea to change AbstractListing.java methods setItemCaptionGenerator and getItemCaptionGenerator to have public access. 

Also, I think it would be a good idea to have setEmptySelectionAllowed and setEmptySelectionCaption added to AbstractSingleSelect this way we could write generic code that doesn't care if the actual implementation is a ComboBox, NativeSelect or RadioButtonGroup.

This was possible in Vaadin 7 with AbstractSelect"

### PR DESCRIPTION
**Pull request by cyberoblivion**
Change setItemCaptionGenerator and getItemCaptionGenerator to be publicly accessible so we don't need to repeatedly override these to expose them.

refactor EmptySelectionAllowed and EmptySelectionCaption into parent to remove duplicate code and allow user to code to AbstractSingleSelect instead of ComboBox, RadioButtonGroup, or NativeSelect explicitly.

resolves #10611 

Still need to address EmptySelectionAllowed in RadioButtonGroup client code. I'm not familiar with the coding of the client side. Any suggestions or help implementing this would be appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10612)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/10612#-L4jUQsCnrkmzTMSy76X:-L4jUQsCnrkmzTMSy76Y:buyom2d) ([raw file](https://github.com/vaadin/framework/blob/8b6f43ac1bc3678cd0a96dfe65db91c14462e148/server/src/main/java/com/vaadin/ui/AbstractListing.java#L186)):*
> ```Java
>      * @return the item caption generator used, not null
>      */
>     public ItemCaptionGenerator<T> getItemCaptionGenerator() {
> ```

Making these methods public will add broken methods in to Grid and TreeGrid. See related ticket #10503 

The JavaDoc of these two methods should contain the same "Implementations that support item icons make this method public." but mention captions instead of icons.

It might be feasible to expose these on the level of `AbstractSingleSelect` but will need to check the full class hierarchy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10612)*

**Comment by cyberoblivion** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/10612#-L4jUQsCnrkmzTMSy76X:-L4kNzCKGECRxDzRmWQe:b-pvr6yg) ([raw file](https://github.com/vaadin/framework/blob/8b6f43ac1bc3678cd0a96dfe65db91c14462e148/server/src/main/java/com/vaadin/ui/AbstractListing.java#L186)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Making these methods public will add broken methods in to Grid and TreeGrid. See related ticket #10503 

The JavaDoc of these two methods should contain the same "Implementations that support item icons make this method public." but mention captions instead of icons.

It might be feasible to expose these on the level of `AbstractSingleSelect` but will need to check the full class hierarchy.
</blockquote></details>

Makes sense to me. I updated the branch with your suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10612)*

**Comment by cyberoblivion** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/10612#-L4jUQsCnrkmzTMSy76X:-L4lyr4uvC6j0UQP7jWl:b-r4pyqs) ([raw file](https://github.com/vaadin/framework/blob/8b6f43ac1bc3678cd0a96dfe65db91c14462e148/server/src/main/java/com/vaadin/ui/AbstractListing.java#L186)):*
<details><summary><i>Previously, cyberoblivion (Ben Erridge) wrote…</i></summary><blockquote>

Makes sense to me. I updated the branch with your suggestions.
</blockquote></details>

I also checked the hierarchy and found only ComboBox, NativeSelect, RadioButtonGroup as direct know subclasses.  There are some test classes but they didn't look problematic IMHO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10612)*

**Comment by elmot** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 405 at r2](https://reviewable.io:443/reviews/vaadin/framework/10612#-L59NgMDEtsg0rltiVxQ:-L59NgMDEtsg0rltiVxR:bgkh3fc) ([raw file](https://github.com/vaadin/framework/blob/72750fbefd9728575a7b16de3178901a13800be6/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L405)):*
>  {@code ""}
Please remove

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 422 at r2](https://reviewable.io:443/reviews/vaadin/framework/10612#-L59NxDiAokPIkB-mxnN:-L59NxDiAokPIkB-mxnO:bgkh3fc) ([raw file](https://github.com/vaadin/framework/blob/72750fbefd9728575a7b16de3178901a13800be6/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L422)):*
>  {@code ""}
Please remove

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/10612#-L4jUQsCnrkmzTMSy76X:-L59Oa2O5ySi5b50gQfj:bfwoc2w) ([raw file](https://github.com/vaadin/framework/blob/8b6f43ac1bc3678cd0a96dfe65db91c14462e148/server/src/main/java/com/vaadin/ui/AbstractListing.java#L186)):*
<details><summary><i>Previously, cyberoblivion (Ben Erridge) wrote…</i></summary><blockquote>

I also checked the hierarchy and found only ComboBox, NativeSelect, RadioButtonGroup as direct know subclasses.  There are some test classes but they didn't look problematic IMHO
</blockquote></details>

There is also `com.vaadin.ui.components.grid.SingleSelectionModelImpl`
The javadocs suggested by @tsuoanttila still aren't here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10612)*

**Comment by cyberoblivion** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 186 at r1](https://reviewable.io:443/reviews/vaadin/framework/10612#-L4jUQsCnrkmzTMSy76X:-L5Av5YKYCFC10HKZS55:b7ajiph) ([raw file](https://github.com/vaadin/framework/blob/8b6f43ac1bc3678cd0a96dfe65db91c14462e148/server/src/main/java/com/vaadin/ui/AbstractListing.java#L186)):*
> SingleSelectionModelImpl

Sorry, I reverted my change to make these methods public so I didn't think we should change the comments when no code changes were being made. I will update the comments as requested.

Also,  I don't see SingleSelectionModelImpl interacts with these changes can you elaborate. I'm happy to make any suggested changes.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 405 at r2](https://reviewable.io:443/reviews/vaadin/framework/10612#-L59NgMDEtsg0rltiVxQ:-L5AtOlqr64T8NpR_B4B:b-a5vjo1) ([raw file](https://github.com/vaadin/framework/blob/72750fbefd9728575a7b16de3178901a13800be6/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L405)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>  {@code ""}
Please remove
</blockquote></details>

I pulled these comments from NativeSelect. I will also remove them from that class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10612)*

**Comment by elmot** [comment]
@cyberoblivion , are you still interested in the change? Looks like the PR turned into full mess after rebase,  and it's better to pick relevant changes to another branch and make a new pull request

**Comment by cyberoblivion** [comment]
Yes I am still interested in this. I will close this PR and open a new one thanks.

**Pull request closed without merging**
