### PR TITLE
Relayout GridLayout when font loading completes

### LINKED ISSUE #8207: Grid with setHeightByRows(N) is rendered wrong inside GridLayout
Tested with v8 & Valo, when Grid using height-by-rows, it is rendered on top of the next GridLayout row.
Simplified example, originally present in _uitest/../VaadinIcons.java_
 ```java
Grid<String> grid = new Grid<>();
grid.setItems("item 1", "item 2", "item 3");
grid.addColumn(string -> string).setCaption("column 1");
grid.addColumn(string -> "Another " + string).setCaption("column 2");
grid.setHeightByRows(3);

GridLayout gl = new GridLayout(1, 3);
gl.addComponent(grid);
gl.addComponent(new Label("foobar");
```

Works as expected when removing `grid.setHeightByRows(3)`.

### LINKED ISSUE #9921: GridLayout slot widths incorrectly calculated in Chrome
When using GridLayout in Chrome, the initial slot widths will be incorrect when the UI is first shown. The next time any of the contained components are remeasured (e.g. because of a caption change), the slots are resized to their correct sizes, causing the entire UI to shift a couple of pixels. This behaviour is absent in Firefox and Safari.

The following UI and test reproduces this problem:

UI:

```
public class GridLayoutWithLabel extends AbstractTestUI {

    @Override
    protected void setup(VaadinRequest request) {
        GridLayout layout = new GridLayout(2, 1);
        layout.setSpacing(true);

        layout.addComponent(new Label("This is the label"), 0, 0);

        CheckBox cb = new CheckBox("Unchecked");
        cb.addValueChangeListener(evt -> {
            cb.setCaption(evt.getValue() ? "Checked" : "Unchecked");
        });

        layout.addComponent(cb, 1, 0);

        addComponent(layout);
    }
}
```

Test:
```
public class GridLayoutWithLabelTest extends MultiBrowserTest {

    @Test
    public void selectingOptionShouldNotCauseLabelToChangeSize() {
        openTestURL();
        AbstractElement gridLayout = $(GridLayoutElement.class).first();
        CheckBoxElement cb = $(CheckBoxElement.class).first();

        int before = gridLayout.getSize().getWidth();
        cb.click(); // Turn on
        cb.click(); // Turn off
        int after = gridLayout.getSize().getWidth();

        Assert.assertEquals("layout width should not have changed after checkbox was toggled", before, after);
    }
}
```

### PR DESCRIPTION
**Pull request by hesara**
If a GridLayout is used and font loading is not complete, force another layout after all fonts are loaded. This is a bit of a hack that could be optimized at the cost of additional complexity.

Fixes #9921
Fixes #8207

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10077)

### CODE REVIEW

**Comment by asashour** [comment]
Seems to fix #9817

**Comment by tsuoanttila** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabel.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10077#-KutHfhzAZQfvjVPl4ZG:-KutHfhzAZQfvjVPl4ZH:bmkc4b3) ([raw file](https://github.com/vaadin/framework/blob/b109a46142a328785786af8878b0bf942a0793b2/uitest/src/main/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabel.java#L27)):*
> ```Java
>         addComponent(layout);
>     }
> }
> ```

Newline

---

*[uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10077#-KutHkrG19Y2Kgfrb0pc:-KutHkrG19Y2Kgfrb0pd:b-4yr6dt) ([raw file](https://github.com/vaadin/framework/blob/b109a46142a328785786af8878b0bf942a0793b2/uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java#L28)):*
> ```Java
>                 before, after);
>     }
> }
> ```

newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10077)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10077#-KutHkrG19Y2Kgfrb0pc:-KutPErQsIoroN_YBvdv:bu2pgtu) ([raw file](https://github.com/vaadin/framework/blob/b109a46142a328785786af8878b0bf942a0793b2/uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java#L28)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

newline
</blockquote></details>

There is an option for "New Lines" "at end of file", so this can be automated, but it is not there in `VaadinJavaConventions.xml`.

I tried to update it, by with Eclipse Oxygen the conversion version is `13`, not '12'.

Let me know if Eclipse Oxygen is used by vaadin members, so I can propose a patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10077)*

**Comment by hesara** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabel.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10077#-KutHfhzAZQfvjVPl4ZG:-Kutf1ihNPkWFsc4GvFr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b109a46142a328785786af8878b0bf942a0793b2/uitest/src/main/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabel.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Newline
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10077#-KutHkrG19Y2Kgfrb0pc:-Kutf2j-lluTWp1pvItV:bz8330c) ([raw file](https://github.com/vaadin/framework/blob/b109a46142a328785786af8878b0bf942a0793b2/uitest/src/test/java/com/vaadin/tests/components/gridlayout/GridLayoutWithLabelTest.java#L28)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

There is an option for "New Lines" "at end of file", so this can be automated, but it is not there in `VaadinJavaConventions.xml`.

I tried to update it, by with Eclipse Oxygen the conversion version is `13`, not '12'.

Let me know if Eclipse Oxygen is used by vaadin members, so I can propose a patch.
</blockquote></details>

Done. We are currently mostly using Neon, but probably should switch to Oxygen in the near future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10077)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10077)*

**Pull request merged**
