### PR TITLE
Update VaadinIcons

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)* status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11281#-LQ2e5Cr5-P5SvB8wX91:-LQ2e5Cr5-P5SvB8wX92:b-v1l77c) (no related file):*
As this is a breaking change, please, add a note into the Release note template for 8.7, https://github.com/vaadin/framework/blob/master/all/src/main/templates/release-notes.html

---

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11281#-LQ2e5Cr5-P5SvB8wX91:-LQ88imr5Jn2hj7QNJ6b:b-896fix) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

As this is a breaking change, please, add a note into the Release note template for 8.7, https://github.com/vaadin/framework/blob/master/all/src/main/templates/release-notes.html
</blockquote></details>

Done.

---

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[all/src/main/templates/release-notes.html, line 105 at r2](https://reviewable.io/reviews/vaadin/framework/11281#-LQ8D-y92wWD13ECZuvu:-LQ8D-y92wWD13ECZuvv:b-s89h27) ([raw file](https://github.com/vaadin/framework/blob/c09097d6fe28607ffc744c43aa77c9c3efff4978/all/src/main/templates/release-notes.html#L105)):*
> ```
>  <li><tt>VOverlay</tt> workaround with <tt>static</tt> reference to current overlay has been removed</tt></li>
> ```

you can remove this, as this is the changes for 8.6. but not a major issue.

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11281)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
