### PR TITLE
Use column id as the default sort order property

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8529)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaowJFVq8VMuveqoi0:-KcaowJFVq8VMuveqoi1:bkjfii) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1046)):*
> ```Java
>          * <p>
>          * The id is also used as the {@link #setSortProperty(String...) backend
>          * sort property} for this column if not already set.
> ```

If what is not already set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1158 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaoWN3EdUoWLzkXZE3:-KcaoWN3EdUoWLzkXZE4:b9x17ey) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1158)):*
> ```Java
>          * Sets strings describing back end properties to be used when sorting
>          * this column.
>          *
> ```

It seems to me this method is lacking the info on
a) what is the default
b) gets set by `setId`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaowJFVq8VMuveqoi0:-KcarPRCmQDVmfkteOse:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1046)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

If what is not already set?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1158 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaoWN3EdUoWLzkXZE3:-Kcarx3okoItDx6SPlOH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1158)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

It seems to me this method is lacking the info on
a) what is the default
b) gets set by `setId`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by hesara** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaowJFVq8VMuveqoi0:-KcauyNLCbdzacr0goee:bwn0p9t) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1046)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"if" missing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by Legioth** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1046 at r1](https://reviewable.io:443/reviews/vaadin/framework/8529#-KcaowJFVq8VMuveqoi0:-KcaxDDoDvp46YIAZwOF:b-a4wcvi) ([raw file](https://github.com/vaadin/framework/blob/edbaca8a57c3759f42626d7fe76090222d7804b5/server/src/main/java/com/vaadin/ui/Grid.java#L1046)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"if" missing?
</blockquote></details>

Oops. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8529)*

**Pull request merged**
