### PR TITLE
Add scroll logic from TreeGrid (as proxy). Fixes #9967.

### LINKED ISSUE #9967: Tree scroll
The tree component doesn't seem to support scrolling to a selected item programmatically. This is very problematic for trees that have large numbers of items if the user is given the ability to search inside the hierarchy.

### PR DESCRIPTION
**Pull request by pwilkin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10005)

### CODE REVIEW

**Comment by pwilkin** [comment]
Fixes #9967

**Comment by tsuoanttila** [comment]
Couple of minor improvements to be made, other than that :lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1157 at r1](https://reviewable.io:443/reviews/vaadin/framework/10005#-Ku3AUe1I1Zejx8oIUVa:-Ku3AUe1I1Zejx8oIUVb:bh1epob) ([raw file](https://github.com/vaadin/framework/blob/17c4aa680372fa6cb52838d132f9473efb00cce3/server/src/main/java/com/vaadin/ui/Tree.java#L1157)):*
> ```Java
>      *            zero based index of the item to scroll to in the current view.
>      * @throws IllegalArgumentException
>      *             if the provided id is not recognized by the data source.
> ```

speaking of id instead of index (seems to be so in Grid as well)

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1185 at r1](https://reviewable.io:443/reviews/vaadin/framework/10005#-Ku39n1u5WA2HXS16kRW:-Ku39n1u5WA2HXS16kRX:bd4lj04) ([raw file](https://github.com/vaadin/framework/blob/17c4aa680372fa6cb52838d132f9473efb00cce3/server/src/main/java/com/vaadin/ui/Tree.java#L1185)):*
> ```Java
>         }
> 
>         treeGrid.scrollTo(row, destination);
> ```

This method already does the two checks above (and one of them apparently has a bug - when asking size, filter is not taken into account). You can just pass the parameters to the treeGrid, and rely on that to make sure the values are correct.


Re-using an existing implementation is a bit less duplicated code and less chances of forgetting to fix one individual implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10005#-:-Ku3AfmfXcoTzSym26IP:b-d95hpb)*

**Comment by pwilkin** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1157 at r1](https://reviewable.io:443/reviews/vaadin/framework/10005#-Ku3AUe1I1Zejx8oIUVa:-Ku47dVpYSNZTdBsHo9f:bfpjueb) ([raw file](https://github.com/vaadin/framework/blob/17c4aa680372fa6cb52838d132f9473efb00cce3/server/src/main/java/com/vaadin/ui/Tree.java#L1157)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

speaking of id instead of index (seems to be so in Grid as well)
</blockquote></details>

Fixed in both.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 1185 at r1](https://reviewable.io:443/reviews/vaadin/framework/10005#-Ku39n1u5WA2HXS16kRW:-Ku47f8ImIcc9Z-9QEc5:bmog4s2) ([raw file](https://github.com/vaadin/framework/blob/17c4aa680372fa6cb52838d132f9473efb00cce3/server/src/main/java/com/vaadin/ui/Tree.java#L1185)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This method already does the two checks above (and one of them apparently has a bug - when asking size, filter is not taken into account). You can just pass the parameters to the treeGrid, and rely on that to make sure the values are correct.


Re-using an existing implementation is a bit less duplicated code and less chances of forgetting to fix one individual implementation.
</blockquote></details>

Modified to full proxy mode. Fixed the bug in Grid as well (had to expose getDataProviderSize() in DataCommunicator for this).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10005)*

**Comment by pwilkin** [comment]
Fixed the bug in `Grid#scrollTo` as well. Proper solution required exposing `DataCommunicator#getDataProviderSize()` (had to include the current filtering).

**Comment by tsuoanttila** [comment]
Change itself is :LGTM:, but needs the release notes mention.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 738 at r2](https://reviewable.io:443/reviews/vaadin/framework/10005#-KuOwl99OnYJgc5nD1Rk:-KuOwl99OnYJgc5nD1Rl:b-bv5s0e) ([raw file](https://github.com/vaadin/framework/blob/d2684f3a4a701f15de2624bf1c387d449afafbee/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L738)):*
> ```Java
>      */
>     @SuppressWarnings({ "unchecked", "rawtypes" })
>     public int getDataProviderSize() {
> ```

This needs a release notes mention in the `Incompatible changes` section. If a user has their own version of this method, it will become a compilation failure.

The release notes update can be done by us, but for that we need to have access to make changes to this branch in your fork. There's an option to enable it in the PR page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10005#-:-KuOxYNc5dHjShU8l63G:bf4dlyd)*

**Comment by pwilkin** [comment]
Enabled edits from maintainers.

**Comment by pwilkin** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 738 at r2](https://reviewable.io:443/reviews/vaadin/framework/10005#-KuOwl99OnYJgc5nD1Rk:-KuTU4c1e2pZylS7qRts:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d2684f3a4a701f15de2624bf1c387d449afafbee/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L738)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This needs a release notes mention in the `Incompatible changes` section. If a user has their own version of this method, it will become a compilation failure.

The release notes update can be done by us, but for that we need to have access to make changes to this branch in your fork. There's an option to enable it in the PR page.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10005)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10005#-:-KuTfgwPhNzhDrKcF1fu:bnfp4nl)*

**Pull request merged**
