### PR TITLE
Enable setting cursor after the last character

### LINKED ISSUE #9157: TextField cursorposition after last character
Since Vaadin 8 it seems impossible to set the cursorposition behind the last character in a TextField. It worked in Vaadin 7!

Vaadin version: 8.1.0.alpha4

Sample:
```
final TextField textfield = new TextField();
textfield.setValue("Some input");
textfield.setCursorPosition(textfield.getValue().length());
```

Expected: Caret position behind the character 't'.
Current: Caret position behind the character 'u'.

I was looking what causes this behaviour. A call to AbstractTextField.setCursorPosition(int) moves into
AbstractTextFieldConnector.AbstractTextFieldClientRpcImpl.selectRange(int, int):

```
public void selectRange(int start, int length) {
    int textLength = getAbstractTextField().getValue().length();
    start = restrictTo(start, 0, textLength - 1);
    length = restrictTo(length, 0, textLength - start);
    getAbstractTextField().setSelectionRange(start, length);
}
private int restrictTo(int value, int min, int max) {
...
}
```

The starting position of the selection range get's restricted to textLength - 1. I think this is wrong if we want to be able to set the caret position after the text.

### PR DESCRIPTION
**Pull request by anasmi**
Resolves #9157

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10670)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WcKxp9FsLqu7Lsou5:-L6WcKxp9FsLqu7Lsou6:b-nmpdvr) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java#L45)):*
> ```Java
>             //Enable setting cursor position after the last character
>             if(length==0){
>                 start = restrictTo(start, 0, textLength);
> ```

This if-else-block could be simplified with a `length == 0 ? textLength : (textLength - 1)`

---

*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbwFrkNb9__2kO6MG:-L6WbwFrkNb9__2kO6MH:b-w8kll9) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L19)):*
> ```Java
>     static final int valueLength=DEFAULT_TEXT.length();
> 
>     final  TextField textField = new TextField("Set cursor position after the last character");
> ```

There are some extra spaces in this file and the test, please run through formatter.

---

*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbpCyAUYiJhBsZDVb:-L6WbpCyAUYiJhBsZDVc:b-kbp2tb) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L30)):*
> ```Java
>         Button posButton = new Button("Set Position to the last character");
>         posButton.setId(BUTTON_SETPOSITION);
>         posButton.addClickListener(c -> {
> ```

Extra code block. see example below.

---

*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbhJOo3Bpno0vYu0N:-L6WbhJOo3Bpno0vYu0O:b65a4dx) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L43)):*
> ```Java
>         Button selButton = new Button("Set selection range");
>         selButton.setId(BUTTON_SETRANGE);
>         selButton.addClickListener(c -> {
> ```

extra code block, should be enough to use `c -> textField1.setSelection(valueLength/2,valueLength)`

---

*[uitest/src/test/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPositionTest.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbGCpBygfI3y5fl9i:-L6WbGCqKsbGhd3s4ZZe:bvlw5sa) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/test/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPositionTest.java#L22)):*
> org.openqa.selenium.
This long import shouldn't be needed here, but the already imported `com.vaadin.testbench.By` should be used instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WcKxp9FsLqu7Lsou5:-L6XIb9ci2_zvERrJEVP:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/client/src/main/java/com/vaadin/client/ui/textfield/AbstractTextFieldConnector.java#L45)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This if-else-block could be simplified with a `length == 0 ? textLength : (textLength - 1)`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbwFrkNb9__2kO6MG:-L6XIfVmoHYTEgrybZEt:bcy3d2q) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L19)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

There are some extra spaces in this file and the test, please run through formatter.
</blockquote></details>

I am not sure how to do it and how to view some spaces, would need help with that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbpCyAUYiJhBsZDVb:-L6XIo4UOg9R_HSeNF9-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Extra code block. see example below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbhJOo3Bpno0vYu0N:-L6XIq6hYQJSuga2U8-g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L43)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra code block, should be enough to use `c -> textField1.setSelection(valueLength/2,valueLength)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPositionTest.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbGCpBygfI3y5fl9i:-L6XIt4s1wa_QJcJKkJB:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/test/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPositionTest.java#L22)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> org.openqa.selenium.
This long import shouldn't be needed here, but the already imported `com.vaadin.testbench.By` should be used instead.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by anasmi** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10670#-L6WbwFrkNb9__2kO6MG:-L6olXTTokkf6xEmbFFH:b-896fjx) ([raw file](https://github.com/vaadin/framework/blob/50061f600c95b5dd8c6f21389034905f3d35afad/uitest/src/main/java/com/vaadin/tests/components/textfield/TextFieldTestCursorPosition.java#L19)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

I am not sure how to do it and how to view some spaces, would need help with that
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10670)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10670)*

**Pull request merged**
