### PR TITLE
Add API for accessing PropertySet of Grid

### PR DESCRIPTION
**Pull request by AkiValiaho**
PropertySet added as a parameter to make overriding possible.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10714)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/ui/Grid.java, line 4240 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10714#-L82CiX91BxM9-0gzpCr:-L82CiX91BxM9-0gzpCs:b-e1y8gy) ([raw file](https://github.com/vaadin/framework/blob/6cf744fbb86f3cf4cda7351547ee6bb9c074dd41/server/src/main/java/com/vaadin/ui/Grid.java#L4240)):*
> ```Java
>      * @since
>      */
>     protected Editor<T> createEditor(PropertySet<T> propertySet) {
> ```

Rather than change an existing API, I'd add a `protected` getter method for the `PropertySet` of the `Grid`. There might be other use-cases as well that need access to the property set than the creation of the editor.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10714)*

**Comment by AkiValiaho** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4240 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10714#-L82CiX91BxM9-0gzpCr:-L82K0oUBhSS4v8HaeLV:b-gvjlyg) ([raw file](https://github.com/vaadin/framework/blob/6cf744fbb86f3cf4cda7351547ee6bb9c074dd41/server/src/main/java/com/vaadin/ui/Grid.java#L4240)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Rather than change an existing API, I'd add a `protected` getter method for the `PropertySet` of the `Grid`. There might be other use-cases as well that need access to the property set than the creation of the editor.
</blockquote></details>

Well thought out, I'll fix this later today after "real work" :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10714)*

**Comment by AkiValiaho** [comment]
Yes, that should do it.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 4240 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10714#-L82CiX91BxM9-0gzpCr:-L82NAwJ9N91eK-qwAp1:bs7wuod) ([raw file](https://github.com/vaadin/framework/blob/6cf744fbb86f3cf4cda7351547ee6bb9c074dd41/server/src/main/java/com/vaadin/ui/Grid.java#L4240)):*
<details><summary><i>Previously, AkiValiaho (Aki Väliaho) wrote…</i></summary><blockquote>

Well thought out, I'll fix this later today after "real work" :)
</blockquote></details>

Done.T

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10714#-:-L82T9cs9Tg6tdZHcjwT:bio3xyw)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10714)*

**Pull request merged**
