### PR TITLE
WIP: Initial implementation of the Tree component

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch is still missing custom icons and captions. Theme of the Tree component is not yet done.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9140)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/event/CollapseEvent.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZyiSQE5EIgnl0PWn-:-KiZyiSQE5EIgnl0PWn0:b-qp4xog) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/event/CollapseEvent.java#L97)):*
> ```Java
>         public void itemCollapse(CollapseEvent<T> event);
>     }
> }
> ```

EOL missing(not a blocker)

---

*[server/src/main/java/com/vaadin/event/ExpandEvent.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZyahJk0-Zbe0les50:-KiZyahJk0-Zbe0les51:b-qp4xog) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/event/ExpandEvent.java#L96)):*
> ```Java
>         public void itemExpand(ExpandEvent<T> event);
>     }
> }
> ```

EOL missing(not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by elmot** [comment]
What about common superinterface for Tree and TreeGrid?

---

Reviewed 8 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZzX6tE7Y4z9dyzuml:-KiZzX6tE7Y4z9dyzumm:bx12fgt) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L50)):*
> ```Java
> 
>     private TreeGrid<T> treeGrid = new TreeGrid<>();
>     private ValueProvider<T, String> captionProvider = Object::toString;
> ```

I'd prefer `Objects::toString` or `String::valueOf` here to avoid NPEs 

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 249 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_3oy80BWDK98BjWuE:-Ki_3oy80BWDK98BjWuF:bw68q7o) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L249)):*
> ```Java
>      * @return the single select wrapper that can be used in binder
>      */
>     public SingleSelect<T> asSingleSelect() {
> ```

where is asMultiSelect?

---

*[uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_7XMF677kBFGeumxf:-Ki_7XMF677kBFGeumxg:b-pvqci2) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java#L49)):*
> ```Java
>             final int prime = 31;
>             int result = 1;
>             result = prime * result + ((id == null) ? 0 : id.hashCode());
> ```

what? 3 lines to add 31 to a hashcode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140#-:-Ki_8diOid9FfIBC04UV:bzdy0am)*

**Comment by tsuoanttila** [comment]
For now since we don't have the third one to begin with, we decided to not do it. The expand and collapse events are now basic Component.Events without specific typing, and it's up to the user of said event to use them correctly.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/CollapseEvent.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZyiSQE5EIgnl0PWn-:-Ki_EXomKygfvDyhLHj2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/event/CollapseEvent.java#L97)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

EOL missing(not a blocker)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 249 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_3oy80BWDK98BjWuE:-Ki_EZ5djvcUIZkHfie4:beojann) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L249)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

where is asMultiSelect?
</blockquote></details>

Due to our current MultiSelectionImpl for TreeGrid not supporting hiding the selection column and having different behaviour, I decided to have the initial implementation only support single selection. We should make a completely custom implementation for the multiselection model in Tree, or provide lots of more configuration to the existing ones.

---

*[uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_7XMF677kBFGeumxf:-Ki_CvKN5oY7TmqpbzTu:b-pgj7lu) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/uitest/src/main/java/com/vaadin/tests/components/tree/TreeBasicFeatures.java#L49)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

what? 3 lines to add 31 to a hashcode?
</blockquote></details>

The hierarcical test bean is borrowed from the TreeGridBasicFeatures test. I'll refactor them out of the TreeGridBasicFeatures test soon and use that from this test as well. The hashCode implementation is not mine, and not going to make any changes to it now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140#-:-Ki_E2gZVjXSkEgcUX4Y:bp7893u)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 249 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_3oy80BWDK98BjWuE:-Ki_vVZWXk7NZ_orvikz:b-l1q9ba) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L249)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Due to our current MultiSelectionImpl for TreeGrid not supporting hiding the selection column and having different behaviour, I decided to have the initial implementation only support single selection. We should make a completely custom implementation for the multiselection model in Tree, or provide lots of more configuration to the existing ones.
</blockquote></details>

Are we gonna implement multiselect at some point? If yes, then it's ok. If not, then it's better to make Tree an implementor of SingleSelection, and get rid of the method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 249 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-Ki_3oy80BWDK98BjWuE:-KidKy8jv8gkqBd4aBi7:b-2osfoh) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L249)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Are we gonna implement multiselect at some point? If yes, then it's ok. If not, then it's better to make Tree an implementor of SingleSelection, and get rid of the method.
</blockquote></details>

The old tree had multiselection, I'm pretty sure our users will ask for it also in the new version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by elmot** [comment]
Review status: 8 of 54 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZzX6tE7Y4z9dyzuml:-KiePPx0OCo9gHC3IuPh:bb6ywmx) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L50)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I'd prefer `Objects::toString` or `String::valueOf` here to avoid NPEs 
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by elmot** [comment]
Reviewed 84 of 84 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/tree/TreeRendererConnector.java, line 43 at r3](https://reviewable.io:443/reviews/vaadin/framework/9140#-Kie_3F9c2PNCRb8NTKP:-Kie_3F9c2PNCRb8NTKQ:blkuivv) ([raw file](https://github.com/vaadin/framework/blob/577835578cd391251ceb095c9f7dfddeddbf1210/client/src/main/java/com/vaadin/client/connectors/tree/TreeRendererConnector.java#L43)):*
> ```Java
>             public void render(RendererCellReference cell, String htmlString) {
>                 Logger logger = Logger.getLogger("foo");
>                 logger.warning("RCR render: " + cell.getRowIndex() + ", "
> ```

Don't forget to remove all those loggings

---

*[uitest/src/main/java/com/vaadin/tests/data/bean/HierarchicalTestBean.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/9140#-KieZvxPHSjLdtT9ARDW:-KieZvxPHSjLdtT9ARDX:b7qs98m) ([raw file](https://github.com/vaadin/framework/blob/577835578cd391251ceb095c9f7dfddeddbf1210/uitest/src/main/java/com/vaadin/tests/data/bean/HierarchicalTestBean.java#L62)):*
> ```Java
>     }
> 
> }
> ```

EOL missing (not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 105 at r4](https://reviewable.io:443/reviews/vaadin/framework/9140#-KihoiV-XhzlnozRgo0-:-KihoiV-XhzlnozRgo00:bzc1sl1) ([raw file](https://github.com/vaadin/framework/blob/935e852d1bebdb7b8c044e3fb5db397ac1ffff88/server/src/main/java/com/vaadin/ui/Tree.java#L105)):*
> ```Java
> 
>         @Override
>         protected TreeRendererState getState() {
> ```

also getState(boolean) needs to be overridden

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by ahie** [comment]
Review status: 52 of 59 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 158 at r5](https://reviewable.io:443/reviews/vaadin/framework/9140#-Kj6toKl42b9wcKfQCba:-Kj6toKl42b9wcKfQCbb:b-glj6xc) ([raw file](https://github.com/vaadin/framework/blob/36130d5de2e37e9d22e7ed8b7b4aa9cfcead6d5b/server/src/main/java/com/vaadin/ui/Tree.java#L158)):*
> DataProvider

Should this be changed to `HierarchicalDataProvider`?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 326 at r5](https://reviewable.io:443/reviews/vaadin/framework/9140#-Kj6te5xbhoV-0_fOsXR:-Kj6te5y90pGmz1Fq-jJ:bfs99hy) ([raw file](https://github.com/vaadin/framework/blob/36130d5de2e37e9d22e7ed8b7b4aa9cfcead6d5b/server/src/main/java/com/vaadin/ui/Tree.java#L326)):*
> public void setItems(Collection<T> items) {

The `Stream` and varargs overloads of this method should be delegated as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by tsuoanttila** [comment]
Review status: 52 of 59 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/9140#-KiZzX6tE7Y4z9dyzuml:-Kj72FsouU7BBvUu_fig:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/876446dab5bd99caea996a7105da1e60aee0bd83/server/src/main/java/com/vaadin/ui/Tree.java#L50)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 105 at r4](https://reviewable.io:443/reviews/vaadin/framework/9140#-KihoiV-XhzlnozRgo0-:-Kj72C2De3RDekfWYGNV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/935e852d1bebdb7b8c044e3fb5db397ac1ffff88/server/src/main/java/com/vaadin/ui/Tree.java#L105)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

also getState(boolean) needs to be overridden
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 326 at r5](https://reviewable.io:443/reviews/vaadin/framework/9140#-Kj6te5xbhoV-0_fOsXR:-Kj71zbX-h2hzcVtoI2k:b-lx57j0) ([raw file](https://github.com/vaadin/framework/blob/36130d5de2e37e9d22e7ed8b7b4aa9cfcead6d5b/server/src/main/java/com/vaadin/ui/Tree.java#L326)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> public void setItems(Collection<T> items) {

The `Stream` and varargs overloads of this method should be delegated as well.
</blockquote></details>

HasItems already delegated Stream and varargs versions to setItems(Collection<T>)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by tsuoanttila** [comment]
Review status: 51 of 59 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 158 at r5](https://reviewable.io:443/reviews/vaadin/framework/9140#-Kj6toKl42b9wcKfQCba:-Kj7JJ0MLbrXTuFAZkyw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/36130d5de2e37e9d22e7ed8b7b4aa9cfcead6d5b/server/src/main/java/com/vaadin/ui/Tree.java#L158)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> DataProvider

Should this be changed to `HierarchicalDataProvider`?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/bean/HierarchicalTestBean.java, line 62 at r3](https://reviewable.io:443/reviews/vaadin/framework/9140#-KieZvxPHSjLdtT9ARDW:-Kj7JIJY6rxFdsfgElhN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/577835578cd391251ceb095c9f7dfddeddbf1210/uitest/src/main/java/com/vaadin/tests/data/bean/HierarchicalTestBean.java#L62)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

EOL missing (not a blocker)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Comment by elmot** [comment]
Reviewed 1 of 6 files at r6.
Review status: 52 of 61 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9140)*

**Pull request closed without merging**
