### PR TITLE
Fix click in subclasses of Grid

### LINKED ISSUE #9603: Clicks broken because of changes to AbstractGridMouseEvent
Originall reported by @Snap252 in https://github.com/vaadin/framework/pull/9062

the new implementation of 

	com.vaadin.client.widgets.Grid.AbstractGridMouseEvent.getGrid()

will return null in subclasses of 

	com.vaadin.client.widgets.Grid<JsonObject>

so it is a major bug for us because clicks don't work any more

example:
class1:

	@Connect(EditorGrid.class)
	public class EditorGridClientConnector extends GridConnector {
	
		@Override
		public EditorClientGrid getWidget() {
			return (EditorClientGrid) super.getWidget();
		}
	}

class 2:

	import elemental.json.JsonObject;
	
	public class EditorClientGrid extends com.vaadin.client.widgets.Grid<JsonObject> {
		public EditorClientGrid() {
		}
	}

### PR DESCRIPTION
**Pull request by wbadam**
Backported changes from the PR https://github.com/vaadin/framework/pull/9283

Fixes #9603

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10144)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10144#-KvhGceEHeeQoE_RHB8d:-KvhGceEHeeQoE_RHB8e:b-2689mt) (no related file):*
Not sure how to auto test this, please advise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10144)*

**Comment by tsuoanttila** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10144#-KvhGceEHeeQoE_RHB8d:-KvkVzt7WRlssXALw7yG:b-axbllk) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Not sure how to auto test this, please advise.
</blockquote></details>

Create a test component that extends grid, add client-side connector and from `getWidget` return a widget that extends the Grid widget. Use as you'd use normal Grid. Client-side changes should go to the uitest module inside the testing widgetset.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10144)*

**Comment by wbadam** [comment]
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10144#-KvhGceEHeeQoE_RHB8d:-Kvm574W8WBrdDK8puwE:b-3bwbcg) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Create a test component that extends grid, add client-side connector and from `getWidget` return a widget that extends the Grid widget. Use as you'd use normal Grid. Client-side changes should go to the uitest module inside the testing widgetset.
</blockquote></details>

Thanks, pushed a UI test now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10144)*

**Comment by tsuoanttila** [comment]
Mostly :lgtm: just need to take a closer look at the test.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10144#-KvhGceEHeeQoE_RHB8d:-Kw0XyWXFeGIYAT5a05U:bgkvzn1) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Thanks, pushed a UI test now
</blockquote></details>

I will try to run the test against the changes in the UI package without the fixes in client later this week to see that the test tests what it's supposed to test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10144#-:-Kw0Y7vHgXYivpMdhZx4:b-62r8sz)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10144)*

**Pull request merged**
