### PR TITLE
Add OSGi documentation and release notes

### LINKED ISSUE #9141: Documentation for OSGi servlet use
Document the new OSGi features for use with servlets.

### PR DESCRIPTION
**Pull request by hesara**
Resolves #9141 
Partly addresses #8999

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9155)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9155#-Kie2w0KeRWDgjn6aCOw:-Kie2w0KeRWDgjn6aCOx:b-c9977n) ([raw file](https://github.com/vaadin/framework/blob/4ec08ba50d448bcb4178d3ec538509dfbbaf9c06/documentation/advanced/advanced-osgi.asciidoc#L21)):*
>  [classname]#MyUIServlet# 
No example for this in the text, and that can be unclear for the reader, what is that servlet and where is it.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9155#-Kie3GcqdqH8X2vhVYYO:-Kie3GcqdqH8X2vhVYYP:b-n3eqw4) ([raw file](https://github.com/vaadin/framework/blob/4ec08ba50d448bcb4178d3ec538509dfbbaf9c06/documentation/advanced/advanced-osgi.asciidoc#L21)):*
>  [interfacename]#@Component# 
It's better to specify FQDN for the annotation somewhere here, because of possible mess with very famous Spring component annotation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9155)*

**Comment by elmot** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9155)*

**Comment by hesara** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9155#-Kie2w0KeRWDgjn6aCOw:-Kie6C953WdNsnRJ_0v9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ec08ba50d448bcb4178d3ec538509dfbbaf9c06/documentation/advanced/advanced-osgi.asciidoc#L21)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>  [classname]#MyUIServlet# 
No example for this in the text, and that can be unclear for the reader, what is that servlet and where is it.
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-osgi.asciidoc, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9155#-Kie3GcqdqH8X2vhVYYO:-Kie6DLRpD1zOpJejf2-:bsdsv1f) ([raw file](https://github.com/vaadin/framework/blob/4ec08ba50d448bcb4178d3ec538509dfbbaf9c06/documentation/advanced/advanced-osgi.asciidoc#L21)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>  [interfacename]#@Component# 
It's better to specify FQDN for the annotation somewhere here, because of possible mess with very famous Spring component annotation.
</blockquote></details>

Done in example below (import)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9155)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9155)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9155#-:-Kie6hHi3Mk8dEwz22uV:bnfp4nl)*

**Pull request merged**
