### PR TITLE
Make it possible for drop target to accept both files and other data

### PR DESCRIPTION
**Pull request by wbadam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9382)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 282 at r1](https://reviewable.io:443/reviews/vaadin/framework/9382#-KkUK2c6zetEJ6xMotLa:-KkUK2c6zetEJ6xMotLb:bqug1cv) ([raw file](https://github.com/vaadin/framework/blob/d0e297fe3a2cf4da30298a4860760de2262d6e6a/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L282)):*
> ```Java
> 
>             // Handle event if transfer doesn't contain files
>             if (!containsFiles(typesJsArray)) {
> ```

You could add the following clarity to here: 
```java
// Spec: "Dragging files can currently only happen from outside a browsing context, for example from a file system manager application." 
// Thus there cannot be at the same time both files and other data dragged

I was about to ask a question about this, but checked the spec instead, so please add this so that others don't have to do the same
```


---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 332 at r1](https://reviewable.io:443/reviews/vaadin/framework/9382#-KkUK_DaZwtp8V2FSHlL:-KkUK_DaZwtp8V2FSHlM:b-hle9f3) ([raw file](https://github.com/vaadin/framework/blob/d0e297fe3a2cf4da30298a4860760de2262d6e6a/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L332)):*
> "Files"

You could add a comment clarifying that "Files" is the special type defined by the spec

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9382)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 282 at r1](https://reviewable.io:443/reviews/vaadin/framework/9382#-KkUK2c6zetEJ6xMotLa:-KkUM85X0-XtNA_4rMtd:b-pijpay) ([raw file](https://github.com/vaadin/framework/blob/d0e297fe3a2cf4da30298a4860760de2262d6e6a/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L282)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You could add the following clarity to here: 
```java
// Spec: "Dragging files can currently only happen from outside a browsing context, for example from a file system manager application." 
// Thus there cannot be at the same time both files and other data dragged

I was about to ask a question about this, but checked the spec instead, so please add this so that others don't have to do the same
</blockquote></details>

Oops forgot to close the code snippet... but the last line above is not necessary for adding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9382)*
<!-- Sent from Reviewable.io -->

**Comment by wbadam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 282 at r1](https://reviewable.io:443/reviews/vaadin/framework/9382#-KkUK2c6zetEJ6xMotLa:-KkUQopRT-NVth7o_Qox:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d0e297fe3a2cf4da30298a4860760de2262d6e6a/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L282)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Oops forgot to close the code snippet... but the last line above is not necessary for adding
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 332 at r1](https://reviewable.io:443/reviews/vaadin/framework/9382#-KkUK_DaZwtp8V2FSHlL:-KkUPUnO5TFhUF0zLHeJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d0e297fe3a2cf4da30298a4860760de2262d6e6a/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L332)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> "Files"

You could add a comment clarifying that "Files" is the special type defined by the spec
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9382)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9382)*

**Pull request merged**
