### PR TITLE
DateField not to focus/blur when going to sub-components (Fixes #1008)

### LINKED ISSUE #1008: DateField blur event fires when focus gets to the "calendar button"
**Originally by @mstahv**

___
Test case: http://localhost:8888/run/com.vaadin.tests.components.FocusAndBlurListeners

Needs a deferred command based solution for both "calendar button" and input element.

___
 Imported from https://dev.vaadin.com/ issue #4305

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10246)

### CODE REVIEW

**Comment by pekam** [comment]
Can you clarify this a bit more.

Currently, when I open the calendar-popup from `DateField`, the `DateField` loses focus and the focus goes to the calendar-popup, to the selected date.

And with your changes, the `DateField` would keep the focus, right? But when I open the popup, I expect the focus to go to the popup, so I can for example navigate there with arrow-keys.

Or is this just about not firing focus- and blur-events? (even though the focus actually goes from `DateField` to the calendar-popup)

---

Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1845 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdTAUmXAyufTq0oJi:-KyLdTAUmXAyufTq0oJj:bi141hk) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1845)):*
> ```Java
>             return SUBPART_NEXT_MONTH;
>         }
>         if (contains(prevMonth, subElement)) {
> ```

I would prefer having `else if`s for readability.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1848 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdXxGscvCSlxW6U6K:-KyLdXxGscvCSlxW6U6L:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1848)):*
> ```Java
>             return SUBPART_PREV_MONTH;
>         }
>         if (contains(nextYear, subElement)) {
> ```

see above

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1851 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdYzk0-oNEDaD_FQ7:-KyLdYzk0-oNEDaD_FQ8:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1851)):*
> ```Java
>             return SUBPART_NEXT_YEAR;
>         }
>         if (contains(prevYear, subElement)) {
> ```

see above

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1854 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdZLL8FRvRT88r34t:-KyLdZLL8FRvRT88r34u:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1854)):*
> ```Java
>             return SUBPART_PREV_YEAR;
>         }
>         if (contains(days, subElement)) {
> ```

see above

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 445 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdIFYhJ9rBjlFRz2E:-KyLdIFYhJ9rBjlFRz2F:bur9dhf) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L445)):*
> ```Java
>      * Returns whether any of the child components has focus.
>      *
>      * @return {@code} if any of the child component has focus, {@code false}
> ```

Probably missing the word `true` from `{@code}`?

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldFocus.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdl5O2eOgBCcOrT-x:-KyLdl5O2eOgBCcOrT-y:b4l9caa) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldFocus.java#L39)):*
> ```Java
>     @Override
>     protected String getTestDescription() {
>         return "DatField should not trigger events when nagivating between sub-components.";
> ```

typo: DatField

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10246#-:-KyLgIGqE6gX3d3DeUlC:bv737ho)*

**Comment by asashour** [comment]
Yes, this is about not firing focus/blur event, and it was seen as a requirement, as discussed in this [review](https://reviewable.io/reviews/vaadin/framework/10148#-Kw-DAglIcYBZGUQFgHG), and in #1008. So, it seems it is expected "not" to have focus/blur events when moving between sub-components.

---

Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1845 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdTAUmXAyufTq0oJi:-Kz4FRHjjoIty0ev2HT5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1845)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I would prefer having `else if`s for readability.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1848 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdXxGscvCSlxW6U6K:-Kz4FRn7qKF7Md-MYp4Y:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1848)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1851 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdYzk0-oNEDaD_FQ7:-Kz4FSSlAuRB9MeXyeD5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1851)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1854 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdZLL8FRvRT88r34t:-Kz4FSpAE526e8PBmp4w:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1854)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 445 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdIFYhJ9rBjlFRz2E:-Kz4FctuKI-ScgDjS4NY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L445)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Probably missing the word `true` from `{@code}`?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldFocus.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/10246#-KyLdl5O2eOgBCcOrT-x:-Kz4Fh3NiKSb9frHhpGS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8e109cff889b921601c6654ba6a4c49ce39bd0f8/uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldFocus.java#L39)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

typo: DatField
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10246#-:-Kz4EdUMxA-yoNdUy37s:b-28ue1l)*

**Comment by caalador** [comment]
Reviewed 2 of 6 files at r1, 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 415 at r2](https://reviewable.io:443/reviews/vaadin/framework/10246#-KzYT_qZWiJjQJKRfV68:-KzYT_qZWiJjQJKRfV69:b-dkfnqm) ([raw file](https://github.com/vaadin/framework/blob/937cdcc05c831ff4d5c4debbfe3b6876b1f681ae/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L415)):*
> ```Java
>             checkGroupFocus(focus);
>             return false;
>         }, 100);
> ```

Why do we schedule a 100ms wait? 
Would a `scheduleDeferred` or `scheduleFinally` work instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10246)*

**Comment by asashour** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java, line 415 at r2](https://reviewable.io:443/reviews/vaadin/framework/10246#-KzYT_qZWiJjQJKRfV68:-KzZvVOl32bp2rVALlB8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/937cdcc05c831ff4d5c4debbfe3b6876b1f681ae/client/src/main/java/com/vaadin/client/ui/VAbstractTextualDate.java#L415)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Why do we schedule a 100ms wait? 
Would a `scheduleDeferred` or `scheduleFinally` work instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10246)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10246)*

**Pull request merged**
