### PR TITLE
Add CDI dependency version to vaadin-bom

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8020)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/cdi/pom.xml, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dgfr4dRbhKXHgMfr:-KZ6dgfsHlhWRBy932eY:b-1gii01) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/pom.xml#L35)):*
> ```XML
>         <finalName>ROOT</finalName>
>         <plugins>
>             
> ```

Is it disabled ?

---

*[test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTest).png, line 0 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dpWjoA9QkmTodsmr:-KZ6dpWjoA9QkmTodsms:b45uhv5) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTest).png#L0)):*
Should it be a part of the PR ?
Accidentally committed ?

---

*[test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTestIT).png, line 0 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e-PP18uoW3i5FOM5:-KZ6e-PP18uoW3i5FOM6:b45uhv5) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTestIT).png#L0)):*
Should it be a part of the PR ?
Accidentally committed ?

---

*[test/cdi/src/main/java/com/vaadin/test/defaultwidgetset/MyVaadinUI.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e1_hXgxqXbiJAn6A:-KZ6e1_hXgxqXbiJAn6B:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/src/main/java/com/vaadin/test/defaultwidgetset/MyVaadinUI.java#L26)):*
> ```Java
>     }
> 
> }
> ```

new line

---

*[test/cdi/src/test/java/com/vaadin/test/defaultwidgetset/VaadinCDISmokeIT.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e8y57Soh5oYHfIQ3:-KZ6e8y57Soh5oYHfIQ4:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/src/test/java/com/vaadin/test/defaultwidgetset/VaadinCDISmokeIT.java#L36)):*
> ```Java
>                 $(NotificationElement.class).first().getText());
>     }
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by tsuoanttila** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/cdi/pom.xml, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dgfr4dRbhKXHgMfr:-KZ6gEm7-7N14BqGO8nf:bhrwnya) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/pom.xml#L35)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is it disabled ?
</blockquote></details>

Yes. Because of JavaEE requiremenets this test uses Wildfly instead of Jetty

---

*[test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTest).png, line  at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dpWjoA9QkmTodsmr:-KZ6gLY7UorlUZl4bnfv:b2klrh6) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTest).png#L)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should it be a part of the PR ?
Accidentally committed ?
</blockquote></details>

Accidental, removing.

---

*[test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTestIT).png, line  at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e-PP18uoW3i5FOM5:-KZ6gN7oPMh1qxkobrq_:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/error-screenshots/testPageLoadsAndCanBeInterractedWith(com.vaadin.test.defaultwidgetset.VaadinCDISmokeTestIT).png#L)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should it be a part of the PR ?
Accidentally committed ?
</blockquote></details>

See above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by tsuoanttila** [comment]
Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/cdi/src/main/java/com/vaadin/test/cdi/MyVaadinUI.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e1_hXgxqXbiJAn6A:-KZ6h0pqWMDNDlMuklAN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/src/main/java/com/vaadin/test/cdi/MyVaadinUI.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6e8y57Soh5oYHfIQ3:-KZ6h21gRoAVrtUO63Jo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/src/test/java/com/vaadin/test/cdi/VaadinCDISmokeIT.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 10 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/cdi/pom.xml, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dgfr4dRbhKXHgMfr:-KZ6iCFNixC84J55eDec:b-2hu6v6) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/pom.xml#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Yes. Because of JavaEE requiremenets this test uses Wildfly instead of Jetty
</blockquote></details>

Yeah, but how is it disabled ? I don't see anything which disables it......

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by tsuoanttila** [comment]
*[test/cdi/pom.xml, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dgfr4dRbhKXHgMfr:-KZ6m-TOopcA_GASqigf:b-4cos64) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/pom.xml#L35)):*
> <phase />
Execution phases have been removed from the start and stop jetty executions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by denis-anisimov** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/cdi/pom.xml, line 35 at r1](https://reviewable.io:443/reviews/vaadin/framework/8020#-KZ6dgfr4dRbhKXHgMfr:-KZ6mNSv28UXxtkL9wO8:b-qqcmhl) ([raw file](https://github.com/vaadin/framework/blob/422a3e3f2eb0f7da3e4f0083d9c24ca3e08dc720/test/cdi/pom.xml#L35)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> <phase />
Execution phases have been removed from the start and stop jetty executions.
</blockquote></details>

Ah, OK,
would be easier perhaps to use jetty.skip -> true. But OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8020)*

**Pull request merged**
