### PR TITLE
Clear errors when clearing binder fields

### PR DESCRIPTION
**Pull request by Artur-**
Calling readBean(null) should reset the form state to the initial state
it was in before calling writeBean(bean)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9364)

### CODE REVIEW

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9364#-:-KkPeM-3DvlMoiTOLsxv:bnfp4nl)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9364#-KkPfeTq3-uf1RmTn4ti:-KkPfeTq3-uf1RmTn4tj:b-kxnhy9) (no related file):*
Behavior altering change. Should still add a mention to release notes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9364)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9364#-KkPfeTq3-uf1RmTn4ti:-KkVNhyS37CsScl64_7V:b-ad5hd3) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Behavior altering change. Should still add a mention to release notes.
</blockquote></details>

Deemed as a bug fix rather than a behavior altering change. Unblocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9364)*

**Comment by hesara** [comment]
Needs manual merge (BinderTest)

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9364)*

**Comment by tsuoanttila** [comment]
This was picked to 8.0.7

**Pull request merged**
