### PR TITLE
Grid editor open

### LINKED ISSUE #10558: Grid: calling editRow causes rows to be shown as empty
Vaadin Framework 8.2.1

After the 5th item was added, editRow causes the content of the first row is to be empty. If editRow was called after 6 item were added, the first TWO rows are empty and so on.
FYI: after e.g. sorting the values will be displayed again.

Steps to reproduce... run code below:
- click "Add" 5 times
- click "Add & Edit"
-> render bug of first row

```
public class Testvaadin8UI extends UI {

    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(productionMode = false, ui = Testvaadin8UI.class, widgetset = "com.example.testvaadin8.widgetset.Testvaadin8Widgetset")
    public static class Servlet extends VaadinServlet {
    }

    public class TestBean {
        private String name = "name";
        private String value = "value";

        public String getName() {
            return name;
        }

        public void setName(String inName) {
            name = inName;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String inValue) {
            value = inValue;
        }

    }

    private ArrayList<TestBean> items = new ArrayList<>();

    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

        Grid<TestBean> grid = new Grid<TestBean>(TestBean.class);
        grid.setDataProvider(new ListDataProvider<>(items));
        grid.setWidth("100%");
        grid.setHeight("400px");
        grid.getEditor().setEnabled(true);
        grid.getColumn("name").setEditorComponent(new TextField());
        grid.getColumn("value").setEditorComponent(new TextField());

        layout.addComponent(new Button("Add", event -> {
            items.add(new TestBean());
            grid.getDataProvider().refreshAll();
        }));
        layout.addComponent(new Button("Add & Edit", event -> {
            TestBean bean = new TestBean();
            items.add(bean);
            grid.getDataProvider().refreshAll();
            grid.select(bean);
            grid.getEditor().editRow(new ArrayList<TestBean>(((ListDataProvider<TestBean>) grid.getDataProvider()).getItems()).indexOf(bean));
        }));

        layout.addComponent(grid);
    }
```

### PR DESCRIPTION
**Pull request by Ansku**
Fix Editor clearing cache when opening from server.

Fixes #10558

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10674)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java, line 16 at r3](https://reviewable.io:443/reviews/vaadin/framework/10674#-L7P5vWZZP0QdZnyV17n:-L7P5vWZZP0QdZnyV17o:b-3ovme3) ([raw file](https://github.com/vaadin/framework/blob/ddd241f557e812a270cc68bf5994899669034fff/uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java#L16)):*
> ```Java
>     private ArrayList<TestBean> items = new ArrayList<>();
>     private TestBean bean = null;
>     private int counter = 0;
> ```

unless the UI class actually needs access to the `counter` variable, you should move it as a `static` field to the `TestBean`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r4, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java, line 16 at r3](https://reviewable.io:443/reviews/vaadin/framework/10674#-L7P5vWZZP0QdZnyV17n:-L82gadsExz05K4SFz7B:b-wqiw9s) ([raw file](https://github.com/vaadin/framework/blob/ddd241f557e812a270cc68bf5994899669034fff/uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java#L16)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

unless the UI class actually needs access to the `counter` variable, you should move it as a `static` field to the `TestBean`.
</blockquote></details>

This is more of a generic codestyle thing, not necessarily blocking the PR from merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java, line 71 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L870fMwKdvckBDmyalw:-L870fMxNHcHjd6A92HU:bewwtn0) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/uitest/src/main/java/com/vaadin/tests/components/grid/GridEditRow.java#L71)):*
> ```Java
>     }
> 
>     public class TestBean {
> ```

`hashcode` and `equals` are missing. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[client/src/main/java/com/vaadin/client/WidgetUtil.java, line 59 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873ZzWMvBmDgC5doQF:-L873ZzWMvBmDgC5doQG:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/WidgetUtil.java#L59)):*
> ```Java
>      * @param <T>
>      *            the object type to store
>      */
> ```

missing `@since`

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7302 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873Q22ITQgVg0bPTPx:-L873Q22ITQgVg0bPTPy:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7302)):*
> ```Java
>      * @param callback
>      *            the callback command to execute when row is available
>      */
> ```

missing `@since`

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7324 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873WSR89NsZhMR_d-G:-L873WSSoFJxLo8XKOS6:b-4a2wjf) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7324)):*
> ```Java
>      * @param whenRendered
>      *            the callback command to execute when row is available
>      */
> ```

missing `@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by elmot** [comment]
Some lost sinces, otherwise works for me

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674#-:-L873gXNSa-DGuGWH8iQ:bnotam3)*

**Comment by tsuoanttila** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/WidgetUtil.java, line 59 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873ZzWMvBmDgC5doQF:-L87Xu_Zo7DHyPkAH40F:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/WidgetUtil.java#L59)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7302 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873Q22ITQgVg0bPTPx:-L87YyROPXC231lGy-51:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7302)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7324 at r6](https://reviewable.io:443/reviews/vaadin/framework/10674#-L873WSR89NsZhMR_d-G:-L87YzTRQYYazKR8NKow:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/27c71567ca65b3f1d0e80aa83eb9e4ad411ea6d7/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7324)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing `@since`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10674#-:-L87ao9TYD9cHsjaWwja:bnfp4nl)*

**Pull request merged**
