### PR TITLE
First draft of datamodel-selection

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8049)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 12 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMjcdKfMBZ95C3Um89:-KZMjcdKfMBZ95C3Um8A:b-49qi1u) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L12)):*
> ```AsciiDoc
> In the chapter link:datamodel-providers.asciidoc[Showing Many Items in a Listing] populating listing components with data was discussed.
> In addition to displaying collections of data, listing components in the framework support the selection of the displayed items.
> The type of selection that each listing component supports differs from component to component, for instance `CheckBoxGroup` allows the selection of multiple items simultaneously, while `RadioButtonGroup` only allows a single item to be selected at a time.
> ```

IMO Replace the whole beginning up to this point with:
"Listing components displaying data also support allowing the user to select items. Depending on component, it the user can select either one or several items at a time." 

Yours is not bad, but just seems is very hard to read, and too much boilerplate, #ffs

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 29 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMjP4t9WiK4H-biGmU:-KZMjP4t9WiK4H-biGmV:b-s02dvm) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L29)):*
>  Availability
replace with `Availability` enumerations

Or just ditch everything after the ,

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 73 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMkwdPO0RHKyO2XUmF:-KZMkwdPO0RHKyO2XUmG:b-iejfuw) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L73)):*
> ```AsciiDoc
> 
> `Grid` component can hold either multi- or single- selection. Since grid can not be both `SingleSelect<SomePojo>` and
> `MultiSelect<SomePojo>` in the same time, grid itself is not a selection at all, but incapsulates one of those selections,
> ```

"...grid itself is not a select component, but it delegates the selection to a subclass of `SelectionModel` class."

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 103 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMlVxp_imqAiriytLN:-KZMlVxp_imqAiriytLO:b-j7w8td) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L103)):*
> ```AsciiDoc
> 
> Those selection objects (subclasses of `SelectionModel`) implement `HasValue` interface, and could be used as form fields,
> and all conversion and validation chains can be used also.
> ```

this is total WTF, very bad language and is it event in the correct place ?

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 130 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMlkixuC75qzLHntEx:-KZMlkixuC75qzLHntEy:b9vl263) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L130)):*
> ```AsciiDoc
>   Grid<Person> bossGrid = new Grid<>();
>   Grid<Person> managersGrid = new Grid<>();
>   managersGrid.setSelectionMode(Grid.SelectionMode.MULTI);
> ```

Please separate these examples, so that you're not mixing both `bossGrid` and `managersGrid` , e.g. first do all `bossGrid` setup and then `managersGrid` setup. 

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 138 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMmEmMocCSkNm56nDo:-KZMmEmMocCSkNm56nDp:be7kxpn) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L138)):*
> ```AsciiDoc
> ----
> 
> Of course, application-specific components can use the same approach to implement similar functionality.
> ```

Just remove this

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 143 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMmLzXmuG_-UufkY_Y:-KZMmLzXmuG_-UufkY_Z:bo5f7ax) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L143)):*
> ```AsciiDoc
> === Selection Events
> 
> Since both `SelectionModels` are regular `HasValue` objects, they support standard `addvalueChangeListener` method and
> ```

This is not even true, `SelectionModel` implementations are not `HasValue`, but they do provide way to use them as such via `asSingleSelect` and `asMultiSelect`. You cannot add `ValueChangeListener` directly to the models.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8049)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8049)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 143 at r3](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZMmLzXmuG_-UufkY_Y:-KZMyUpsIPugATFDM6YG:b-886gsx) ([raw file](https://github.com/vaadin/framework/blob/7466db6e81d0644cabb8b7d3ce526a0963a4ecab/documentation/datamodel/datamodel-selection.asciidoc#L143)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is not even true, `SelectionModel` implementations are not `HasValue`, but they do provide way to use them as such via `asSingleSelect` and `asMultiSelect`. You cannot add `ValueChangeListener` directly to the models.
</blockquote></details>

Fixed

---

*[documentation/datamodel/datamodel-selection.asciidoc, line 145 at r5](https://reviewable.io:443/reviews/vaadin/framework/8049#-KZN-OAHCKcjR6niy3me:-KZN-OAHCKcjR6niy3mf:bkfmqyx) ([raw file](https://github.com/vaadin/framework/blob/fe420a2ac27275656554180f309fc5370eac89f4/documentation/datamodel/datamodel-selection.asciidoc#L145)):*
> `SelectionModel`,
Better to throw away, since we don't need to cast SelectinModel to SelectionModel, but that is not a critical fix 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8049)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8049)*

**Pull request merged**
