### PR TITLE
Introduce empty selection functionality for NativeSelect.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#545

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8336)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUVJIXzUbAk5vNpTt-:-KbUVJIXzUbAk5vNpTt0:bhshcyu) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L102)):*
>  @OnStateChange("emptySelectionCaption")
>     private void onEmptySelectionCaptionChange() {
>         updateEmptySelectionItem();
>     }
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     @OnStateChange("emptySelectionAllowed")
>     private void onEmptySelectionAllowed() {
>         updateEmptySelectionItem();
>     }
</details>

These could be under the same method (eg. onEmptySelectionChange) and have the annotation
@OnStateChange({ "emptySelectionCaption", "emptySelectionAllowed" })
As they both do the same thing

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 141 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUYMKDR3B11tYKP2dp:-KbUYMKDR3B11tYKP2dq:b5rtdp3) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L141)):*
> int i = range.getStart() + increment
could just be `int i = increment` as `range.getStart()` should always be 0? 
This perhaps should be enforced with something else than `assert`

---

*[uitest/src/main/java/com/vaadin/tests/components/nativeselect/NativeSelectEmptySelection.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUdJ0dUBj6YIANtwdk:-KbUdJ0dUBj6YIANtwdl:bontjr8) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/uitest/src/main/java/com/vaadin/tests/components/nativeselect/NativeSelectEmptySelection.java#L46)):*
> ```Java
> 
>         Button enable = new Button("Allow empty caption",
>                 event -> select.setEmptySelectionAllowed(true));
> ```

'Allow/Disallow empty selection' not caption

---

*[uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectCaptionGenerationTest.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUd0gXWBLhDxaXCPOL:-KbUd0gXWBLhDxaXCPOM:b-hgzr2t) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectCaptionGenerationTest.java#L10)):*
> ```Java
> import com.vaadin.testbench.TestBenchElement;
> import com.vaadin.testbench.elements.ButtonElement;
> import com.vaadin.testbench.elements.NativeSelectElement;
> ```

This reordering is not really needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUVJIXzUbAk5vNpTt-:-KbUundXYs52giAvlofL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L102)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

>  @OnStateChange("emptySelectionCaption")
>     private void onEmptySelectionCaptionChange() {
>         updateEmptySelectionItem();
>     }
>  
>     @OnStateChange("emptySelectionAllowed")
>     private void onEmptySelectionAllowed() {
>         updateEmptySelectionItem();
>     }

These could be under the same method (eg. onEmptySelectionChange) and have the annotation
@OnStateChange({ "emptySelectionCaption", "emptySelectionAllowed" })
As they both do the same thing
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 141 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUYMKDR3B11tYKP2dp:-KbUurRplVmwvScK0J5w:b-r3cmb9) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L141)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> int i = range.getStart() + increment
could just be `int i = increment` as `range.getStart()` should always be 0? 
This perhaps should be enforced with something else than `assert`
</blockquote></details>

`range.getStart()` is here because of lazy loading.
Theoretically ( I have no idea is true now ) the items should be loaded when they are need , not when they set.
So `range.getStart()` can be not `0`.
And anyway such change would be out of the scope this PR.

---

*[uitest/src/main/java/com/vaadin/tests/components/nativeselect/NativeSelectEmptySelection.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUdJ0dUBj6YIANtwdk:-KbUvcDjZLE_HX_WK_gO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/uitest/src/main/java/com/vaadin/tests/components/nativeselect/NativeSelectEmptySelection.java#L46)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

'Allow/Disallow empty selection' not caption
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectCaptionGenerationTest.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbUd0gXWBLhDxaXCPOL:-KbUvmzGCZP6OOoejNTz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e2342b7d9ebc73e80dd3870129d0c213b117ccab/uitest/src/test/java/com/vaadin/tests/components/nativeselect/NativeSelectCaptionGenerationTest.java#L10)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This reordering is not really needed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Comment by caalador** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 107 at r2](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbV-IoUTh_-SF_Ae7XT:-KbV-IoVK_of35ErhIwy:bf54ocu) ([raw file](https://github.com/vaadin/framework/blob/cc3457890a463cf286740b0be783c456cae0f2ed/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L107)):*
> ```Java
>             listBox.insertItem(getState().emptySelectionCaption, 0);
>             listBox.setValue(0, "");
>         }
> ```

What would you think if the if-else set was changed for clarity to:

```
if (isEmptyItem) {
    if (getState().emptySelectionAllowed) {
        listBox.setItemText(0, getState().emptySelectionCaption);
    } else {
         listBox.removeItem(0);
    }
} else if (getState().emptySelectionAllowed) {
    listBox.insertItem(getState().emptySelectionCaption, 0);
    listBox.setValue(0, "");
}
```

Also would hasEmptyItem be clearer than isEmptyItem?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java, line 107 at r2](https://reviewable.io:443/reviews/vaadin/framework/8336#-KbV-IoUTh_-SF_Ae7XT:-KbV15DV7_s1RIPc7yqH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cc3457890a463cf286740b0be783c456cae0f2ed/client/src/main/java/com/vaadin/client/ui/nativeselect/NativeSelectConnector.java#L107)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

What would you think if the if-else set was changed for clarity to:

```
if (isEmptyItem) {
    if (getState().emptySelectionAllowed) {
        listBox.setItemText(0, getState().emptySelectionCaption);
    } else {
         listBox.removeItem(0);
    }
} else if (getState().emptySelectionAllowed) {
    listBox.insertItem(getState().emptySelectionCaption, 0);
    listBox.setValue(0, "");
}
```

Also would hasEmptyItem be clearer than isEmptyItem?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Comment by caalador** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336#-:-KbV1vByTmJ4plaCas7V:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 7 of 10 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8336)*

**Pull request merged**
