### PR TITLE
Don't use V8 FieldEvents classes in v7 compatibility module.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#363

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/93)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java, line 257 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYJsydKCNDgc_4f7l2G:-KYJsydK8wDoDunKSmf-:b-cszygq) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java#L257)):*
> ```Java
>         public void execute(T c, Boolean value, Object data) {
>             FocusNotifier focusNotifier = (FocusNotifier) c;
>             if (value) {
> ```

Autounboxing NPE might occur here

---

*[uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYJtA8M1asa0Uz8aHBe:-KYJtA8MB2Z3ohnO-Glh:b-cszygq) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java#L272)):*
> ```Java
>         public void execute(T c, Boolean value, Object data) {
>             BlurNotifier bn = (BlurNotifier) c;
>             if (value) {
> ```

Autounboxing NPE might occur here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Comment by pleku** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 189 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN1F3mE2k2wpI_2YjH:-KYN1F3nEFeSIvi5LndH:b-hiiu9r) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L189)):*
> ```Java
>  */
> @Deprecated
> public class Grid extends AbstractFocusable implements SelectionNotifier,
> ```

This is the compatibility Grid, meaning it should be the same as in V7, and now you've changed it.
Currently in 7.7:
```java
public class Grid extends AbstractFocusable implements SelectionNotifier,
        SortNotifier, SelectiveRenderer, ItemClickNotifier {
```

Why ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Comment by denis-anisimov** [comment]
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 189 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN1F3mE2k2wpI_2YjH:-KYN57Ef0LoTF_qP2eIL:bkqbx3p) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L189)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is the compatibility Grid, meaning it should be the same as in V7, and now you've changed it.
Currently in 7.7:
```java
public class Grid extends AbstractFocusable implements SelectionNotifier,
        SortNotifier, SelectiveRenderer, ItemClickNotifier {
```

Why ?
</blockquote></details>

`AbstractFocusable` is in the `server` module.
`AbstractFocusable` implements `FocusNotifier` and `BlurNotifier` from `FieldEvents` which is in the `server` module.
As a result I can't get rid of the new `FieldEvents` class in compatibility `Grid`.
It means that `FocusNotifier` will still have deprecated `removeFocusListener` only because of old `Grid`.

Shortly: it's not possible to resolve the issue without this change. It the root cause of it.

---

*[uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java, line 257 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYJsydKCNDgc_4f7l2G:-KYN5tqWDiA9CVLuOaw-:b-h0hara) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java#L257)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Autounboxing NPE might occur here
</blockquote></details>

Might.
Or might not. I'm pretty sure that that `Boolean` here is just because it's not possible to write `new Command<T, boolean>()` but `null` never goes here as an argument. Because in reality it's `boolean`.

But I don't care here about it. 
Out of the scope of this PR.

---

*[uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYJtA8M1asa0Uz8aHBe:-KYN6K9j8ldD6FDTdpXT:bto4g7a) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/uitest/src/main/java/com/vaadin/tests/components/AbstractComponentTest.java#L272)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Autounboxing NPE might occur here
</blockquote></details>

Out of the scope of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Comment by pleku** [comment]
Reviewed 1 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 7427 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN6o-73EhdVRg_BLYn:-KYN6o-724bFqYnR39R2:b-leddst) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L7427)):*
> ```Java
> 
>     @Override
>     @Deprecated
> ```

Unnecessary since whole class is deprecated

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 7439 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN6qqJ5yPJDMeAk-lC:-KYN6qqK7YMlv0fCqY5a:b-leddst) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L7439)):*
> ```Java
> 
>     @Override
>     @Deprecated
> ```

Unnecessary since whole class is deprecated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 7427 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN6o-73EhdVRg_BLYn:-KYN7AaKDCrfEewXdieP:b-v4gpi7) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L7427)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Unnecessary since whole class is deprecated
</blockquote></details>

Different meaning of deprecation here . But true of course.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java, line 7439 at r1](https://reviewable.io:443/reviews/vaadin/framework/93#-KYN6qqJ5yPJDMeAk-lC:-KYN7Hc9C07y8600qay2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cf146ec3cc91ce36ad2786c4ffff1c8be2bca98a/compatibility-server/src/main/java/com/vaadin/v7/ui/Grid.java#L7439)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Unnecessary since whole class is deprecated
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/93)*

**Pull request merged**
