### PR TITLE
Add pluggable connector id generator support

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9508)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1511 at r1](https://reviewable.io:443/reviews/vaadin/framework/9508#-KmQ7tqHg--9gfCNLAiB:-KmQ7tqIddGN6fPDf3Cs:b-wuv12s) ([raw file](https://github.com/vaadin/framework/blob/83f112dc07748f007adc0537b89497d94fb89709/server/src/main/java/com/vaadin/server/VaadinService.java#L1511)):*
> ```Java
>      *
>      */
>     protected ConnectorIdGenerator initConenctorIdGenerator(
> ```

how easy it is to override this to select the specific one to use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9508)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1511 at r1](https://reviewable.io:443/reviews/vaadin/framework/9508#-KmQ7tqHg--9gfCNLAiB:-KmQYA3nOwympak8343-:brk5bla) ([raw file](https://github.com/vaadin/framework/blob/83f112dc07748f007adc0537b89497d94fb89709/server/src/main/java/com/vaadin/server/VaadinService.java#L1511)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

how easy it is to override this to select the specific one to use?
</blockquote></details>

As easy or hard as anything else that requires a custom `VaadinService` subclass, i.e. you'd need to define your own `VaadinServlet` subclass with an overridden `createServletService` method.

Do you have any idea on how to simplify this?

The actual implementation of this method would in most such cases be quite straightforward: either return the desired implementation without even looking at the provided list, or alternatively find the right instance from the list by filtering it based on the provider type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9508)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1511 at r1](https://reviewable.io:443/reviews/vaadin/framework/9508#-KmQ7tqHg--9gfCNLAiB:-KmQZh6JK3vUYqoDZ0VT:b-cb2j2j) ([raw file](https://github.com/vaadin/framework/blob/83f112dc07748f007adc0537b89497d94fb89709/server/src/main/java/com/vaadin/server/VaadinService.java#L1511)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

As easy or hard as anything else that requires a custom `VaadinService` subclass, i.e. you'd need to define your own `VaadinServlet` subclass with an overridden `createServletService` method.

Do you have any idea on how to simplify this?

The actual implementation of this method would in most such cases be quite straightforward: either return the desired implementation without even looking at the provided list, or alternatively find the right instance from the list by filtering it based on the provider type.
</blockquote></details>

Well one thing that comes to mind is to provide an API to override this with a Function<List<ConnectorIdGenreator>, ConnectorIdGenerator> but that should be done in quite early phase and not sure how to access APIs like that (yet). I guess the implementation as of right now is "good enough".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9508)*

**Comment by Legioth** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1511 at r1](https://reviewable.io:443/reviews/vaadin/framework/9508#-KmQ7tqHg--9gfCNLAiB:-KmQ_ttEXww4jMgIyqrV:b55qfag) ([raw file](https://github.com/vaadin/framework/blob/83f112dc07748f007adc0537b89497d94fb89709/server/src/main/java/com/vaadin/server/VaadinService.java#L1511)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Well one thing that comes to mind is to provide an API to override this with a Function<List<ConnectorIdGenreator>, ConnectorIdGenerator> but that should be done in quite early phase and not sure how to access APIs like that (yet). I guess the implementation as of right now is "good enough".
</blockquote></details>

The question would still be what kind of mechanism the application developer has to provide that `Function` implementation. Whatever we come up with for that question, it can probably be implemented later on, based on the current low-level implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9508)*

**Pull request merged**
