### PR TITLE
Fixes OOM for broken upload request

### LINKED ISSUE #9102: Vaadin upload with large single-line file can result in an OutOfMemoryError
- Vaadin 8.0.5
- Uploading a large file (e.g. 5GB) without linebreaks can cause an OutOfMemoryError
Steps to reproduce:
* Create a test file, for example in Windows `fsutil file createnew dummy 5368709120` -> 5Gb file without line breaks.
* Upload this file with the Vaadin upload component used in a Vaadin portlet dropped in Liferay. 
* Since the FileUploadHandler always reads the first line, in this case, it will read 5Gb of data, which will result in a OutOfMemoryError.

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9102

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9414)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 311 at r1](https://reviewable.io:443/reviews/vaadin/framework/9414#-KkpLiW3lBMaBQStexz0:-KkpLiW3lBMaBQStexz1:b-muy0je) ([raw file](https://github.com/vaadin/framework/blob/614d19c72bdf6796f3c5b4f3d63dbbc646f799d7/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L311)):*
> ```Java
>             }
>             bout.write(readByte);
>             if(bout.size() > MULTIPART_BOUNDARY_LINE_LIMIT) {
> ```

this probably addresses the OOME, but does not make the failed upload of a huge file work - it would be good to understand what went wrong there so that the received stream did not contain proper multipart format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9414)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9414#-KkpYQiK0vjuzRtAH786:-KkpYQiK0vjuzRtAH787:b-gox1l5) (no related file):*
Needs additional investigation under Liferay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9414)*

**Comment by elmot** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9414#-KkpYQiK0vjuzRtAH786:-KkusGstiei3Zvhp6lcD:b-19uv4) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Needs additional investigation under Liferay
</blockquote></details>

I tested that for liferay 6.2. Looks like for moderate size files (128M) and huge ones(4G) of the same content, liferay works different ways. 

For moderate files I got normal upload request of standard multipart format.

For the huge file, the response does not contain normal boundaries, just binary stream, started at some random position. 

It looks like a liferay or underlaying tomcat issue, and we actually can't do anything reasonable with that. The fix will only throw an exception instead of OOM, and that's all. 

No idea if that is fixed in liferay 7.

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 311 at r1](https://reviewable.io:443/reviews/vaadin/framework/9414#-KkpLiW3lBMaBQStexz0:-KkusKNOhBhNjInrLvRd:bo8s702) ([raw file](https://github.com/vaadin/framework/blob/614d19c72bdf6796f3c5b4f3d63dbbc646f799d7/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L311)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this probably addresses the OOME, but does not make the failed upload of a huge file work - it would be good to understand what went wrong there so that the received stream did not contain proper multipart format
</blockquote></details>

See the comment above. The fix protects us from OOM but huge file upload under liferay 6.2 seems completely broken, and we can't fix or workaround that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9414)*

**Comment by elmot** [comment]
After some experiments, I have found, uploads > 2047 MBytes are completely broken under liferay 6.2 The only thing we can do is to prevent OOMs here.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9414#-:-Kl28GpM2zjg6PbTV0Ya:bnrjz95)*

**Pull request merged**
