### PR TITLE
Migrate Grid UI tests P4

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#592

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8133)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridEditingWithNoScrollBars.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8133#-K_cUJl3zN8MLW4tH__2:-K_cUJl3zN8MLW4tH__3:b-oc7dvt) ([raw file](https://github.com/vaadin/framework/blob/e7f45e82fc03d9198ff4ab39cf2ff90d3ff6f081/uitest/src/main/java/com/vaadin/tests/components/grid/GridEditingWithNoScrollBars.java#L29)):*
> ```Java
> import com.vaadin.ui.Grid.SelectionMode;
> 
> public class GridEditingWithNoScrollBars extends AbstractReindeerTestUI {
> ```

I think this could be tested with Valo since the test only checks that the editor width is the same as the table wrapper width. If it doesn't work with Valo, we either have a bug or then I'd just rename this test to `GridEditingWithNoScrollBarsReindeer`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8133)*

**Comment by denis-anisimov** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridEditingWithNoScrollBars.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8133#-K_cUJl3zN8MLW4tH__2:-K_cknolzzZhLaF-NkP0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e7f45e82fc03d9198ff4ab39cf2ff90d3ff6f081/uitest/src/main/java/com/vaadin/tests/components/grid/GridEditingWithNoScrollBars.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think this could be tested with Valo since the test only checks that the editor width is the same as the table wrapper width. If it doesn't work with Valo, we either have a bug or then I'd just rename this test to `GridEditingWithNoScrollBarsReindeer`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8133)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8133)*

**Comment by pleku** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8133#-:-K_clSTKADnFgozRqOiU:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Screenshots are uploaded.

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8133)*

**Pull request merged**
