### PR TITLE
Add a method to invalidate classloader resources

### PR DESCRIPTION
**Pull request by Flamenco**
Change-Id: Ia38bebdbf63238bb15c1619ad2ff8fc699b1b5af

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9769)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr64gOBgw2eLTvgqEs5:-Kr64gOBgw2eLTvgqEs6:b5ccrix) ([raw file](https://github.com/vaadin/framework/blob/05ec86d5c0d960a5c3828017c0896ab85bd37f36/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L116)):*
> ```Java
>      * Remove any cached resources that use the specified classloader.
>      * OSGi frameworks should call this method with the bundle classloader when bundles are removed.
>      * @param classLoader
> ```

Should this method be static as it iterates over a static cache map? Otherwise, it might be tricky to get hold of an instance of ServerRpcMethodInvocation to call this method.

This is just one case where Method instances are kept by the framework - another that might be relevant would be EventRouter (listenerList of ListenerMethod), though a well-behaved application might clean up the related listeners before removing a bundle. To make things less hacky, it would be good to have a common "entry point" for such clean-up and a common mechanism to trigger it, and some documentation about it. However, this method is ok as a first step in that direction.

This new public method should have a since tag. @Flamenco, if you enable the option that lets project maintainers to make edits to the PR branch, we can add that with the correct value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr64gOBgw2eLTvgqEs5:-Kr6WT1OEQ1c8LdsBelZ:byxvl3p) ([raw file](https://github.com/vaadin/framework/blob/05ec86d5c0d960a5c3828017c0896ab85bd37f36/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L116)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should this method be static as it iterates over a static cache map? Otherwise, it might be tricky to get hold of an instance of ServerRpcMethodInvocation to call this method.

This is just one case where Method instances are kept by the framework - another that might be relevant would be EventRouter (listenerList of ListenerMethod), though a well-behaved application might clean up the related listeners before removing a bundle. To make things less hacky, it would be good to have a common "entry point" for such clean-up and a common mechanism to trigger it, and some documentation about it. However, this method is ok as a first step in that direction.

This new public method should have a since tag. @Flamenco, if you enable the option that lets project maintainers to make edits to the PR branch, we can add that with the correct value.
</blockquote></details>

Actually, we have had an issue with @Javascript and @Stylesheet annotations for a couple of years now.  We call a method to wipe out session.getCommunicationManager().getDependencies() as well.  That way when our bundle comes back up, the new resources are loaded.

Ideally, I suggest adding an interface HasInvalidatableResources and registering in OSGI.  When a bundle is removed, it can iterate over all the services and invalidate itself.  We can add that to at least the three mentioned classes.

I would rather send in the bundle instead of the classloader, but that will add a dependency to OSGI in the implementer.  Would you agree it's better to stick with the classloader as the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
I will update this with an interface based entry point.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769#-:-Kr6_CLJg8_7Wt_pDLCj:b3j4w2e)*

**Comment by hesara** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9uZko_9vqQz9TqQ4O:-Kr9uZko_9vqQz9TqQ4P:b-npvu8q) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L1)):*
> ```Java
> package main.java.com.vaadin.server;
> ```

As the validation build failure indicates, this class is missing the standard header - you can copy it from some other class.

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr64gOBgw2eLTvgqEs5:-Kr9upXC8NE5awgX1YT0:b-u5z9pw) ([raw file](https://github.com/vaadin/framework/blob/05ec86d5c0d960a5c3828017c0896ab85bd37f36/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L116)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

Actually, we have had an issue with @Javascript and @Stylesheet annotations for a couple of years now.  We call a method to wipe out session.getCommunicationManager().getDependencies() as well.  That way when our bundle comes back up, the new resources are loaded.

Ideally, I suggest adding an interface HasInvalidatableResources and registering in OSGI.  When a bundle is removed, it can iterate over all the services and invalidate itself.  We can add that to at least the three mentioned classes.

I would rather send in the bundle instead of the classloader, but that will add a dependency to OSGI in the implementer.  Would you agree it's better to stick with the classloader as the test?

</blockquote></details>

I agree classloader is better as it reduces dependencies.

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9uw2XZxm56iqq9XLu:-Kr9uw2XZxm56iqq9XLv:b1qldak) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L119)):*
> ```Java
>      * OSGi frameworks should call this method with the bundle classloader when bundles are removed.
>      * @param classLoader
>      */
> ```

also this method should have a since tag - we can also add it once everything else is ok as long as we have access to the PR branch

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 121 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9v8n0MQ5s1zd4MHu3:-Kr9v8n0MQ5s1zd4MHu4:ble9t4j) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L121)):*
> ```Java
>      */
>     static public void invalidateCachedResources(ClassLoader classLoader) {
>         synchronized (invocationMethodCache){
> ```

(minor nit that we can also fix: space missing before curly brace and next line should be split according to the formatter rules)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9uZko_9vqQz9TqQ4O:-KrAjXcN8IVOIgqApFcr:btq658t) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

As the validation build failure indicates, this class is missing the standard header - you can copy it from some other class.
</blockquote></details>

When the build failed yesterday I pushed a revision for that.  It must have gone to a different branch.  Hmm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 119 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9uw2XZxm56iqq9XLu:-KrAjD3uUQpwQxfv3tfP:bxxi77x) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L119)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

also this method should have a since tag - we can also add it once everything else is ok as long as we have access to the PR branch
</blockquote></details>

OK.  I used TBD and gave you write access to the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 121 at r2](https://reviewable.io:443/reviews/vaadin/framework/9769#-Kr9v8n0MQ5s1zd4MHu3:-KrAk7xfym3gdU0ELePj:beo29m5) ([raw file](https://github.com/vaadin/framework/blob/007ab494a65349f231339b9c51d5526889394724/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L121)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(minor nit that we can also fix: space missing before curly brace and next line should be split according to the formatter rules)
</blockquote></details>

Space added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 31 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KrG9kcx98cJ_Pz15-vT:-KrG9kcx98cJ_Pz15-vU:bv1yy74) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L31)):*
> ```Java
>         //TODO invalidate EventRouter resources
>         //TODO invalidate all session dependencies
>         //session.getCommunicationManager().getDependencies()
> ```

We use a procedure similiar to https://stackoverflow.com/questions/24995677/how-to-get-all-sessions-in-vaadin to get track all sessions from all users.  Would you consider making this public API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by Flamenco** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 31 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KrG9kVqi0CLxCnJ7NXB:-KrG9kVqi0CLxCnJ7NXC:bdfyhxl) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L31)):*
> //session.getCommunicationManager().getDependencies()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9769#-KtGXz_XTotf_oJtJCn2:-KtGXz_XTotf_oJtJCn3:bsie7w) (no related file):*
We could probably merge this PR after fixing at least the package name of InvalidatableResourceManager, and then make follow-up PRs that add further resources to invalidate.

Ideally, there would also be a test or maybe two - that would have revealed e.g. the invalid package name of InvalidatableResourceManager. Constructing a proper unit test for this can be tricky, though, and require some mocking.

Would you be able to contribute further improvements as well?

---

*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 16 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KtGWvb-BQCJnE7fyHsQ:-KtGWvb-BQCJnE7fyHsR:b9vhl9v) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L16)):*
> ```Java
>  * the License.
>  */
> package main.java.com.vaadin.server;
> ```

bad package name - should be com.vaadin.server

---

*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 29 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KtGXZ6Pk1qPnv_x4xok:-KtGXZ6Pk1qPnv_x4xol:bx8w07h) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L29)):*
> ```Java
>     static public void invalidateCachedResources(ClassLoader classLoader) {
>         ServerRpcMethodInvocation.invalidateCachedResources(classLoader);
>         //TODO invalidate EventRouter resources
> ```

These are a bit trickier to clean up as we have many instances of EventRouter even for a single UI.

---

*[server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java, line 31 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KrG9kcx98cJ_Pz15-vT:-KtGYN2zz0HGaCnMZCAZ:b-gfelmv) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/InvalidatableResourceManager.java#L31)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

We use a procedure similiar to https://stackoverflow.com/questions/24995677/how-to-get-all-sessions-in-vaadin to get track all sessions from all users.  Would you consider making this public API?
</blockquote></details>

The session listener would probably need to also work in a clustered environment. Probably doable e.g. with a transient WeakHashMap (used as a set) or such, with a comment that clearly states that there is no need to replicate it between nodes, and triggering the method on all nodes based on the OSGi event (if using OSGi on a cluster).

---

*[server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java, line 69 at r5](https://reviewable.io:443/reviews/vaadin/framework/9769#-KtG8Xi2s1fw75ZV8ieI:-KtG8Xi2s1fw75ZV8ieJ:bm77u2j) ([raw file](https://github.com/vaadin/framework/blob/82af378883806d55ddede68d70ffc078f635167d/server/src/main/java/com/vaadin/server/ServerRpcMethodInvocation.java#L69)):*
> ```Java
>         // signature
>         Method invocationMethod;
>         synchronized (invocationMethodCache) {
> ```

With explicit synchronization (which is more correct here), the cache does not need to be ConcurrentHashMap anymore, but rather should have a comment on the field noting how to synchronize for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9769)*

**Comment by pleku** [comment]
I'm about to close this PR for inactivity.

We appreciate the contribution, this is not just a high enough priority for us to spend time to help get in ourselves. Please @Flamenco respond to the review issues if this is still something that you want to contribute to the framework; otherwise we'll close this PR in two weeks.

**Comment by TatuLund** [comment]
I am closing this PR for inactivity.

**Pull request closed without merging**
