### PR TITLE
Changing inconsistent value change logic of ColorPicker

### PR DESCRIPTION
**Pull request by anasmi**
Changes were not propagated to the server side correctly.
 Reopening windows results in assigning default values as previous ones were not stored.
Adding missing RPC to update color value. 
(Inconsistent logic can be seen from testing https://demo.vaadin.com/sampler/#foundation/html_and_css/cssinject )

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10812)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 9 of 12 files at r7, 4 of 5 files at r8.
Review status: 12 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VColorPicker.java, line 50 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXM-g2wuTpLkmCzM6:-L9oXM-g2wuTpLkmCzM7:b-579ue3) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/VColorPicker.java#L50)):*
> ```Java
>     }
> 
>     public String getColor() {
> ```

Better to have javadoc with empty `@since` here

---

*[client/src/main/java/com/vaadin/client/ui/VColorPickerArea.java, line 167 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXU4H8CvlqZvkKgvD:-L9oXU4H8CvlqZvkKgvE:b-579ue3) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/VColorPickerArea.java#L167)):*
> ```Java
>     }
> 
>     public String getColor() {
> ```

Better to have javadoc with empty `@since` here

---

*[client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerGridConnector.java, line 29 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXet-Ez3mlxcUZsi-:-L9oXet-Ez3mlxcUZsi0:bywwru8) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerGridConnector.java#L29)):*
> ```Java
> import com.vaadin.shared.ui.colorpicker.ColorPickerGridServerRpc;
> import com.vaadin.shared.ui.colorpicker.ColorPickerGridState;
> import com.vaadin.shared.ui.colorpicker.ColorPickerServerRpc;
> ```

Is it used here?

---

*[client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerGridConnector.java, line 46 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXawzEZMIUcE62Wgd:-L9oXawzEZMIUcE62Wge:bvxay2k) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerGridConnector.java#L46)):*
> ```Java
>     private ColorPickerGridServerRpc rpc = RpcProxy
>             .create(ColorPickerGridServerRpc.class, this);
> ```

extra empty line

---

*[server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerGrid.java, line 65 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9obLuL18N9WXGvhAPX:-L9obLuL18N9WXGvhAPY:b7wokc5) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerGrid.java#L65)):*
> ```Java
>                     true));
>             setValue(getValue());
>             doSetValue(getValue());
> ```

We need the only one setValue here.
Most probably `setValue(getValue(), true)`

Actually the code looks quite fragile, setValue and getValue are used so strange way here.. Please double check if it works correctly.

---

*[shared/src/main/java/com/vaadin/shared/ui/colorpicker/ColorPickerServerRpc.java, line 37 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oka2_0tbp4FStCf9A:-L9oka2_0tbp4FStCf9B:b3es1l7) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/shared/src/main/java/com/vaadin/shared/ui/colorpicker/ColorPickerServerRpc.java#L37)):*
> ```Java
> 
>     public void changeColor(String color);
> ```

Javadoc and `@since` is mandatory here

---

*[uitest/src/main/java/com/vaadin/tests/components/colorpicker/ColorPickerTestUI.java, line 20 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9okvWsBrEluLNwnXih:-L9okvWsBrEluLNwnXii:b-7ycvfd) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/uitest/src/main/java/com/vaadin/tests/components/colorpicker/ColorPickerTestUI.java#L20)):*
> ```Java
> import com.vaadin.shared.ui.ContentMode;
> import com.vaadin.shared.ui.colorpicker.Color;
> import com.vaadin.tests.components.AbstractReindeerTestUI;
> ```

Looks like unnecessary import

---

*[uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerValueTestTest.java, line 24 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9olEvr9Dfjha_7vzk_:-L9olEvr9Dfjha_7vzka:b3lxqaj) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/uitest/src/test/java/com/vaadin/tests/components/colorpicker/ColorPickerValueTestTest.java#L24)):*
> ```Java
>         ButtonElement button = $(ButtonElement.class).first();
>         button.click();
>         Thread.sleep(1000);
> ```

Even if the delay is mandatory here, please use smaller value. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by elmot** [comment]
Reviewed 1 of 5 files at r8.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by anasmi** [comment]
*[shared/src/main/java/com/vaadin/shared/ui/colorpicker/ColorPickerServerRpc.java, line 37 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oka2_0tbp4FStCf9A:-L9sGlvACcdqFpRKDb3h:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/shared/src/main/java/com/vaadin/shared/ui/colorpicker/ColorPickerServerRpc.java#L37)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Javadoc and `@since` is mandatory here
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/VColorPickerArea.java, line 167 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXU4H8CvlqZvkKgvD:-L9sGplXB-SbN89HrWIN:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/VColorPickerArea.java#L167)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Better to have javadoc with empty `@since` here
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/VColorPicker.java, line 50 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9oXM-g2wuTpLkmCzM6:-L9sGrxuAyANCN_DbBVK:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/client/src/main/java/com/vaadin/client/ui/VColorPicker.java#L50)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Better to have javadoc with empty `@since` here
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerGrid.java, line 65 at r8](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9obLuL18N9WXGvhAPX:-L9sQO2L7TfhLs7a_EX_:b-cqxod6) ([raw file](https://github.com/vaadin/framework/blob/209686c443d029613d4c9ea58171a41ae30e265f/server/src/main/java/com/vaadin/ui/components/colorpicker/ColorPickerGrid.java#L65)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

We need the only one setValue here.
Most probably `setValue(getValue(), true)`

Actually the code looks quite fragile, setValue and getValue are used so strange way here.. Please double check if it works correctly.
</blockquote></details>

Checked again, not needed. Left because of mistake. Removed now

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by elmot** [comment]
Reviewed 1 of 3 files at r4, 3 of 4 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, 1 of 2 files at r12.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java, line 66 at r12](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9u21_XCoQORAU5f4pk:-L9u21_XCoQORAU5f4pl:b2we0z2) ([raw file](https://github.com/vaadin/framework/blob/e3c37e248018c29985fb0f5dbf795632b4a04ab8/client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java#L66)):*
> ```Java
>     protected void refreshColor() {
>         getWidget().refreshColor();
>         getState().color=getWidget().getColor();
> ```

no spaces before and after `=`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java, line 66 at r12](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9u21_XCoQORAU5f4pk:-L9u4MNcB7dmBTZflMER:b1p5zrw) ([raw file](https://github.com/vaadin/framework/blob/e3c37e248018c29985fb0f5dbf795632b4a04ab8/client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java#L66)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

no spaces before and after `=`
</blockquote></details>

Does the line make any sense?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java, line 66 at r12](https://beta.reviewable.io/reviews/vaadin/framework/10812#-L9u21_XCoQORAU5f4pk:-L9xMZdc5wcQq-fuR2am:b-zbv32w) ([raw file](https://github.com/vaadin/framework/blob/e3c37e248018c29985fb0f5dbf795632b4a04ab8/client/src/main/java/com/vaadin/client/ui/colorpicker/ColorPickerAreaConnector.java#L66)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Does the line make any sense?
</blockquote></details>

no. removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r13.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10812)*

**Pull request merged**
