### PR TITLE
Fix race condition between rendering TreeGrid and setting up headers

### PR DESCRIPTION
**Pull request by tsuoanttila**
Setting the hierarchy column and its renderer conflicts with Grid header setup. This causes Grid to attempt to render headers too early.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9105)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 318 at r1](https://reviewable.io:443/reviews/vaadin/framework/9105#-Ki4nQU2FedWWoENyUBr:-Ki4nQU2FedWWoENyUBs:bltz1zq) ([raw file](https://github.com/vaadin/framework/blob/c4fbc969a3d0e6b09c15e839d85dea7d31eafadc/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L318)):*
> ```Java
>         }
> 
>         Scheduler.get().scheduleFinally(() -> {
> ```

Should this scheduling also be done for the footer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9105)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 318 at r1](https://reviewable.io:443/reviews/vaadin/framework/9105#-Ki4nQU2FedWWoENyUBr:-Ki4rvcFTrzubPO_qTCY:b8getws) ([raw file](https://github.com/vaadin/framework/blob/c4fbc969a3d0e6b09c15e839d85dea7d31eafadc/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L318)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should this scheduling also be done for the footer?
</blockquote></details>

The issue lies in the initial setup. I think we could avoid these schedules at least to some degree if we do a proper set up of the Grid widget and remove all the headers from it initially. After that everything should be maybe fine. as for now this bandaid should keep it together for yet another week.

Footers don't exist initially so this is not a problem. I can add one to the test to make sure it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9105)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2, 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 311 at r3](https://reviewable.io:443/reviews/vaadin/framework/9105#-KiE5yUVebV44JxPZJau:-KiE5yUVebV44JxPZJav:bcsy397) ([raw file](https://github.com/vaadin/framework/blob/300f691b19e6ebb43578768f795125c0aa6a365e/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L311)):*
> ```Java
>     @OnStateChange("header")
>     void updateHeader() {
>         Scheduler.get().scheduleFinally(() -> {
> ```

TBC: Does this change have any performance impact on the initial render time? Does it cause any extra reflows or such?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9105)*

**Comment by tsuoanttila** [comment]
*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 311 at r3](https://reviewable.io:443/reviews/vaadin/framework/9105#-KiE5yUVebV44JxPZJau:-KiF5u5t_CIj6eO1SNuU:b-waepzv) ([raw file](https://github.com/vaadin/framework/blob/300f691b19e6ebb43578768f795125c0aa6a365e/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L311)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC: Does this change have any performance impact on the initial render time? Does it cause any extra reflows or such?
</blockquote></details>

Making changes to the header will trigger a delayed refresh anyway, previously there might've been a chance to have an extra render of the headers. now it should be always rendered only once.

See https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Grid.java#L941

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9105)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9105#-:-KiF8akeaZwK94h4nypA:bnfp4nl)*

**Pull request merged**
