### PR TITLE
Fix AbstractClientConnector stateTypeCache memory leak

### LINKED ISSUE #9883: Memory leak in AbstractClientConnector with Hot Deployment
As observed in Vaadin 7.5.9 (not present in Vaadin 7.3.10):

In our Vaadin-based solution we use hot deployment of Vaadin Component implementations - independently of the hosting Web application.

That is: There is one Vaadin Web application ("**portal**") and many other "**portal applications**" that provide Vaadin components that are used by the **portal**. The **portal applications** can be hot deployed and use different class loaders than the **portal**. 

In the later `AbstractClientConnector` implementation of Vaadin 7.5.9 a `stateTypeCache` has been introduced as

```java
    private static final ConcurrentHashMap<Class<? extends AbstractClientConnector>, Class<? extends SharedState>> stateTypeCache = new ConcurrentHashMap<Class<? extends AbstractClientConnector>, Class<? extends SharedState>>();
```

to speed up the method

```java
public Class<? extends SharedState> getStateType() {...}
```

With frequent hot deployments, the map keys keep duplicating (as the new classes are loaded by other class loaders) and eventually we run out of memory as classes will never get collected.

### Suggestion:

Instead of using `java.util.ConcurrentHashMap`, using `java.util.WeakHashMap` as in

```java
    private static final Map<Class<? extends AbstractClientConnector>, Class<? extends SharedState>> stateTypeCache = Collections.synchronizedMap(new WeakHashMap<Class<? extends AbstractClientConnector>, Class<? extends SharedState>>());
```
should do the trick. When using  `WeakHashMap`, obsolete key entries will be removed and, in this case, obsolete classloader references will be eventually removed.

### PR DESCRIPTION
**Pull request by ahie**
Fixes #9883

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9896)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/AbstractClientConnector.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9896#-KsmBs6R8htKK_6uQu9w:-KsmBs6SgSKNESPDmJ7Y:b47cyva) ([raw file](https://github.com/vaadin/framework/blob/caea4141aa3f40658506acede0e811c73152fcf9/server/src/main/java/com/vaadin/server/AbstractClientConnector.java#L99)):*
> ```Java
> 
>     private static final Map<Class<? extends AbstractClientConnector>, Class<? extends SharedState>> stateTypeCache = Collections
>             .synchronizedMap(new WeakHashMap<>());
> ```

In general we avoid weak maps because they can break in a clustering situation, but in this case it is ok as it is in a static cache that can be recomputed on demand. Could still add a comment clarifying that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9896)*

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/AbstractClientConnector.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9896#-KsmBs6R8htKK_6uQu9w:-KsmPqIF00lT50zWXEle:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/caea4141aa3f40658506acede0e811c73152fcf9/server/src/main/java/com/vaadin/server/AbstractClientConnector.java#L99)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In general we avoid weak maps because they can break in a clustering situation, but in this case it is ok as it is in a static cache that can be recomputed on demand. Could still add a comment clarifying that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9896)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/server/AbstractClientConnectorTest.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/9896#-KsmThfl5s8oOsaUe61y:-KsmThfl5s8oOsaUe61z:b8da752) ([raw file](https://github.com/vaadin/framework/blob/fb56eaeee850228fcc7d042f33c24205118add54/server/src/test/java/com/vaadin/server/AbstractClientConnectorTest.java#L100)):*
> ```Java
>                 classRef.get());
> 
>         System.gc();
> ```

I'd move the gc() call one line down inside the look - still no guarantees, but that is the pattern used e.g. in CurrentInstanceTest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9896)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/server/AbstractClientConnectorTest.java, line 100 at r2](https://reviewable.io:443/reviews/vaadin/framework/9896#-KsmThfl5s8oOsaUe61y:-KsmWbijaq1m2u5HOosZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb56eaeee850228fcc7d042f33c24205118add54/server/src/test/java/com/vaadin/server/AbstractClientConnectorTest.java#L100)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd move the gc() call one line down inside the look - still no guarantees, but that is the pattern used e.g. in CurrentInstanceTest.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9896)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9896)*

**Pull request merged**
