### PR TITLE
Updating release notes

### PR DESCRIPTION
**Pull request by TatuLund**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11955)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11955)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund)

___
*[all/src/main/templates/release-notes.html, line 109 at r1](https://reviewable.io/reviews/vaadin/framework/11955#-M5ab8IEAfIURRmGNoIn:-M5ab8IEAfIURRmGNoIo:bwlins2) ([raw file](https://github.com/vaadin/framework/blob/fb07446249048489e3cb013eead753025a0faf8a/all/src/main/templates/release-notes.html#L109)):*
> ```
> vica
> ```
typo? vice versa?

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11955)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[all/src/main/templates/release-notes.html, line 109 at r1](https://reviewable.io/reviews/vaadin/framework/11955#-M5ab8IEAfIURRmGNoIn:-M5adtU0BOUeVhK-356k:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fb07446249048489e3cb013eead753025a0faf8a/all/src/main/templates/release-notes.html#L109)):*
<details><summary><i>Previously, ZheSun88 (Zhe Sun) wrote…</i></summary><blockquote>

> ```
> vica
> ```
typo? vice versa?
</blockquote></details>

Done.

**Review by ZheSun88 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11955)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

**Review by ZheSun88 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11955)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
