### PR TITLE
Introduce dedicated shared states for every core vaadin component/ext.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Updated components are:
- PasswordField
- CustomField
- AbstractListing
- AbstractMultiSelect
- ColorPicker
- ColorPickerArea
- AbstractExtension
- DataCommunicator
- Responsive
- AbstractListingExtension
- DetailsManager
- AbstractRenderer
- ClickableRenderer
- ButtonRenderer
- CheckBoxRenderer
- DateRenderer
- HtmlRenderer
- ImageRenderer
- NumberRenderer
- ProgressBarRenderer
- TextRenderer

Fixes vaadin/framework8-issues#480.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/98)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 88 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO2Z2B5100kZ1vwyIw:-KYO2Z2C1o0Iq5ShYIl7:br4dqwk) (no related file):*
Please remove the compatibility classes from this. Reason:
- we cannot add them to V7 in a maintenance version since they break API on any class that extends them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 88 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO2Z2B5100kZ1vwyIw:-KYO4mCz0vuLSHi3MHBD:b-5whsbm) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please remove the compatibility classes from this. Reason:
- we cannot add them to V7 in a maintenance version since they break API on any class that extends them
</blockquote></details>

I can't do this because of the same reasons as with `FieldEvents` in a different patch.

Two compatibility states are used in the Grid extensions. Both extensions extend `AbstractExtension` which has now its own state. It means that extension have to have state which extends `AbstractExtensionState`.
So either that or let's remove `AbstractExtensionState`.

It's not that easy unfortunately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by pleku** [comment]
Reviewed 86 of 88 files at r1.
Review status: 86 of 88 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO2Z2B5100kZ1vwyIw:-KYO6Zq75es8BjppOJpO:b5a7nzg) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I can't do this because of the same reasons as with `FieldEvents` in a different patch.

Two compatibility states are used in the Grid extensions. Both extensions extend `AbstractExtension` which has now its own state. It means that extension have to have state which extends `AbstractExtensionState`.
So either that or let's remove `AbstractExtensionState`.

It's not that easy unfortunately.
</blockquote></details>

So two options:
1. remove `AbstractExtensionState` for now, and hope we'll never have something we would want to add to all `AbstractExtensionState`s. We can of course do that for 8.1 or so
2. duplicate the necessary states for compatibility packages.

I think we should do 2) for all the cases since effected we don't want to break the compatibility components when we add the shared states to V8 components.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4ca5AZeuqc90hX__:-KYO4ca59P9eNOC5wjVj:bxfp204) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/server/src/main/java/com/vaadin/ui/AbstractListing.java#L52)):*
> ```Java
>  * @see Listing
>  */
> public abstract class AbstractListing<T> extends AbstractComponent {
> ```

AbstractListing doesn't extend AbstractField so how can AbstractListingState extend AbstractFieldState ?

---

*[shared/src/main/java/com/vaadin/shared/JavaScriptExtensionState.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO3Mv99XbWJQh1gZGB:-KYO3Mv92yW_o2T21liM:bkr4z93) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/JavaScriptExtensionState.java#L26)):*
> ```Java
> import com.vaadin.shared.ui.grid.renderers.AbstractRendererState;
> 
> public class JavaScriptExtensionState extends AbstractRendererState
> ```

This should be renamed to AbstractJavaScriptExtensionState, but only if it is not used by any V7 component.
Or maybe just keep it as is since, while it is wrong currently, it might break things.

---

*[shared/src/main/java/com/vaadin/shared/extension/abstractlisting/AbstractListingExtensionState.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO3qUI0gGofsS_FlFc:-KYO3qUI38WkOU63OXtB:bg3roar) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/extension/abstractlisting/AbstractListingExtensionState.java#L21)):*
> ```Java
> 
> /**
>  * Default shared state implementation for AbstractListingExtension.
> ```

Don't think it is required to say "default shared state for X" instead of just "shared state for X", which applies to all the shared states. This is not blocking any way

---

*[shared/src/main/java/com/vaadin/shared/ui/AbstractSingleSelectState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4E9r7Tx-yRck4x2C:-KYO4E9r9UsRd9wq4bJf:biknz42) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/shared/src/main/java/com/vaadin/shared/ui/AbstractSingleSelectState.java#L27)):*
> ```Java
>  * @since 8.0
>  */
> public class AbstractSingleSelectState extends AbstractFieldState {
> ```

Does this break things ? AbstractFieldState has required and read only 

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4qHcCY0z0-wa08A_:-KYO4qHcD56mhpccT9ns:b-7qanqw) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java#L27)):*
> ```Java
>  *
>  */
> public class AbstractListingState extends AbstractFieldState {
> ```

Listings are not fields, this mess needs to be cleaned up (congrats)

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractmultiselect/AbstractMultiSelectState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4yAK9vG0n3JswqxN:-KYO4yAKA7W_B0IFk5zH:b-u2dade) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractmultiselect/AbstractMultiSelectState.java#L27)):*
> ```Java
>  *
>  */
> public class AbstractMultiSelectState extends AbstractListingState {
> ```

Same as with abstractsingleselect, this needs to extend abstractslisting state and provide readonly & required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by denis-anisimov** [comment]
Review status: 86 of 88 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO2Z2B5100kZ1vwyIw:-KYOAX8s4q0pn4jIJRIA:b-s6wo2h) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So two options:
1. remove `AbstractExtensionState` for now, and hope we'll never have something we would want to add to all `AbstractExtensionState`s. We can of course do that for 8.1 or so
2. duplicate the necessary states for compatibility packages.

I think we should do 2) for all the cases since effected we don't want to break the compatibility components when we add the shared states to V8 components.
</blockquote></details>

I don't think I understood the second option......

What do you mean ?
If `AbstractExtension` has its own `AbstractExtensionState` then two states in the patch has to extend it. Without any option.
And there is nothing to do in addition to that.

So what's your suggestion ?

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4ca5AZeuqc90hX__:-KYOB7NNBkC9ESGfjW2Q:b-ifz5mz) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/server/src/main/java/com/vaadin/ui/AbstractListing.java#L52)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

AbstractListing doesn't extend AbstractField so how can AbstractListingState extend AbstractFieldState ?
</blockquote></details>

`public abstract class AbstractListingConnector extends AbstractFieldConnector`

As I said: it's not easy at all.
There are many inconsistencies in the code.
I definitely don't want to fix them in this PR and it's even not known how to fix them at all.

---

*[shared/src/main/java/com/vaadin/shared/JavaScriptExtensionState.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO3Mv99XbWJQh1gZGB:-KYOBYT35pE9hvA6mSJx:b-jqichw) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/JavaScriptExtensionState.java#L26)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This should be renamed to AbstractJavaScriptExtensionState, but only if it is not used by any V7 component.
Or maybe just keep it as is since, while it is wrong currently, it might break things.
</blockquote></details>

It's used in the compatibility components/extensions.

---

*[shared/src/main/java/com/vaadin/shared/extension/abstractlisting/AbstractListingExtensionState.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO3qUI0gGofsS_FlFc:-KYOBgKx7HCo73nxN16i:b5cgin8) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/extension/abstractlisting/AbstractListingExtensionState.java#L21)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Don't think it is required to say "default shared state for X" instead of just "shared state for X", which applies to all the shared states. This is not blocking any way
</blockquote></details>

This is a copy-paste actually.
"Default" means here that it's for an abstract class which is supposed to be extended and the state class should be derived as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by denis-anisimov** [comment]
Review status: 86 of 88 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/AbstractSingleSelectState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4E9r7Tx-yRck4x2C:-KYOCm8n0_d4k1FrYhcs:b-uzj9hl) ([raw file](https://github.com/vaadin/framework/blob/5b0919ce9e3f8899fb5b0c5331afd9ffa2a56c0c/shared/src/main/java/com/vaadin/shared/ui/AbstractSingleSelectState.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Does this break things ? AbstractFieldState has required and read only 
</blockquote></details>

`public class AbstractListingState extends AbstractFieldState`

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4qHcCY0z0-wa08A_:-KYOCuh87P5tz2GdcgGb:baptptl) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Listings are not fields, this mess needs to be cleaned up (congrats)
</blockquote></details>

`public abstract class AbstractListingConnector extends AbstractFieldConnector`

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractmultiselect/AbstractMultiSelectState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4yAK9vG0n3JswqxN:-KYOD-fi9sGVX00Wv0TH:b-tbi1j6) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractmultiselect/AbstractMultiSelectState.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Same as with abstractsingleselect, this needs to extend abstractslisting state and provide readonly & required
</blockquote></details>

Yes, same as abstractsingleselect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by pleku** [comment]
Review status: 86 of 88 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4qHcCY0z0-wa08A_:-KYSJaqeV5ZncKd9ZgjM:b-zfouc0) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`public abstract class AbstractListingConnector extends AbstractFieldConnector`
</blockquote></details>

Oh right.`AbstractListing` extends `AbstractComponent` and like you said, `AbstractListingConnector extends AbstractFieldConnector`. Makes perfect sense for people, especially if you make your own listing component and extend those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by pleku** [comment]
Reviewed 9 of 16 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO2Z2B5100kZ1vwyIw:-KYSPsbfdPkyaNsNcKDB:bfz67ti) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't think I understood the second option......

What do you mean ?
If `AbstractExtension` has its own `AbstractExtensionState` then two states in the patch has to extend it. Without any option.
And there is nothing to do in addition to that.

So what's your suggestion ?
</blockquote></details>

Decided to go with 1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/98#-KYO4qHcCY0z0-wa08A_:-KYSQd5qYGCaGwB6VgaE:b72nimx) ([raw file](https://github.com/vaadin/framework/blob/138d7cac6a10f32f61a4fcee27d7b2eca02f7494/shared/src/main/java/com/vaadin/shared/ui/abstractlisting/AbstractListingState.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Oh right.`AbstractListing` extends `AbstractComponent` and like you said, `AbstractListingConnector extends AbstractFieldConnector`. Makes perfect sense for people, especially if you make your own listing component and extend those.
</blockquote></details>

https://github.com/vaadin/framework8-issues/issues/544

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/98)*

**Pull request merged**
