### PR TITLE
Feature #9357 - addStyleNames(...)

### PR DESCRIPTION
**Pull request by appreciated**
https://github.com/vaadin/framework/issues/9357

Add the following functions to Abstract Component and the respective Interface Component:
- addStyleNames(String... styles)
- removeStyleNames(String... styles)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9537)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 181 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeTVoLEf9i63NDU9um:-KmeSupRQhPlduyqQFW2:b2o1eb9) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L181)):*
> ```Java
>      * @param styles
>      *            the new style to be added to the component
>      * @see #getStyleName()
> ```

Link to addStyleName for a more complete description of the feature

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 185 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeSMpsVZjV-amsSIOL:-KmeSMpsVZjV-amsSIOM:behhh0f) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L185)):*
> ```Java
>      * @see #removeStyleName(String)
>      */
>     public void addStyleNames(String ... styles);
> ```

Since this is aimed for Vaadin 8, you should use Interface default methods from Java 8. This change as it is right now will break any custom implementation of Component that does not extend AbstractComponent.

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeShp-IiSRo-sFu997:-KmeShp-IiSRo-sFu998:bz3dwat) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L216)):*
> ```Java
>      * @see #addStyleName(String)
>      */
>     public void removeStyleNames(String ... styles);
> ```

see above comment about default method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9537)*

**Comment by appreciated** [comment]
You are right, I wasn't aware of possible custom implementations of Component. 
I now added the implementations as default methods to Component.

**Comment by appreciated** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 181 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeTVoLEf9i63NDU9um:-Kmk4RZPG3PfS6aeG4wi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L181)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Link to addStyleName for a more complete description of the feature
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 185 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeSMpsVZjV-amsSIOL:-Kmk4RFCS8k6F8EjLrag:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L185)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Since this is aimed for Vaadin 8, you should use Interface default methods from Java 8. This change as it is right now will break any custom implementation of Component that does not extend AbstractComponent.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Component.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/9537#-KmeShp-IiSRo-sFu997:-Kmk4QiHv6z5-ikYEF6o:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/de5bd30c5c2f693cae2111508f85a14ea8650071/server/src/main/java/com/vaadin/ui/Component.java#L216)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

see above comment about default method.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9537)*

**Comment by hesara** [comment]
:lgtm: - dismissed Teemu's addressed review comments as he is on vacation

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9537#-:-KnicarsagxpOFP4hfnY:b-ulmboh)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9537#-:-KnmlAYDh_WpieB9QGJ4:bnfp4nl)*

**Pull request merged**
