### PR TITLE
Fix toggling of WeekNumbers for PopupDateField. (#8405)

### PR DESCRIPTION
**Pull request by caalador**
Fix togging of week numbers inside PopupDateField calendar popup.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8469)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VCalendarPanel.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/framework/8469#-KcMYE9OnyQN3LBnOm8e:-KcMYE9OnyQN3LBnOm8f:b-zhtqk9) ([raw file](https://github.com/vaadin/framework/blob/d21c8beb1c3a50d2c2beaa7dc536ec07b8b47060/client/src/main/java/com/vaadin/client/ui/VCalendarPanel.java#L534)):*
> ```Java
>     public void setShowISOWeekNumbers(boolean showISOWeekNumbers) {
>         this.showISOWeekNumbers = showISOWeekNumbers;
>         if(initialRenderDone) {
> ```

see comment in #8468 

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateFieldWeekDaysTest.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8469#-KcMYJc-NMgw_Xdgsg46:-KcMYJc-NMgw_Xdgsg47:bs0c14q) ([raw file](https://github.com/vaadin/framework/blob/d21c8beb1c3a50d2c2beaa7dc536ec07b8b47060/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateFieldWeekDaysTest.java#L39)):*
> ```Java
> 
>     @Test
>     public void testToggleWeekNumbers_rederedCorrectly() {
> ```

rendered

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8469)*

**Comment by caalador** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateFieldWeekDaysTest.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8469#-KcMYJc-NMgw_Xdgsg46:-KcMkpO7-fe8wHTn8JLA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d21c8beb1c3a50d2c2beaa7dc536ec07b8b47060/uitest/src/test/java/com/vaadin/tests/components/datefield/PopupDateFieldWeekDaysTest.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

rendered
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8469)*

**Comment by hesara** [comment]
OK if passes validation

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8469#-:-KcMlWtAr4EoHJzCXsRJ:be6o1hy)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8469#-:-KcNkRNqwI64Y6JvcJxm:bnfp4nl)*

**Pull request merged**
