### PR TITLE
Window control buttons should have noticeable focus styles (#8918)

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10285)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0S0TD97I8DpCnw6Mb:-Ky0S0TD97I8DpCnw6Mc:b-qpwjxd) (no related file):*
This will need the specified screenshots in the screenshot repo. 

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java, line 8 at r1](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0Rg8bnn00EiNG2Ekz:-Ky0Rg8bnn00EiNG2El-:bcuolgk) ([raw file](https://github.com/vaadin/framework/blob/c8bed4cfafe6db7862ae4ddfe3ee548b06b99981/uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java#L8)):*
> ```Java
> import com.vaadin.ui.Window;
> 
> public class WindowControlButtonFocus extends AbstractTestUI {
> ```

Could we re-use some existing UI test instead of making a completely new one ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10285)*

**Comment by Ansku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0S0TD97I8DpCnw6Mb:-Ky0VVyQeidPv27ZR-Lm:b8aa5j) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This will need the specified screenshots in the screenshot repo. 
</blockquote></details>

I asked yesterday in #framework-8-dev-team how that's done in practice, still waiting for answers.

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java, line 8 at r1](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0Rg8bnn00EiNG2Ekz:-Ky0Vtbe0Cy9y3Bgjx6P:bcgsoxa) ([raw file](https://github.com/vaadin/framework/blob/c8bed4cfafe6db7862ae4ddfe3ee548b06b99981/uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java#L8)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could we re-use some existing UI test instead of making a completely new one ?
</blockquote></details>

Didn't spot any that wouldn't have quite a few unnecessary parts in the screenshots. Didn't try out *all* of them, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10285)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0S0TD97I8DpCnw6Mb:-KyuJj8q_9WEGma5qg3b:b-mpkxyd) (no related file):*
<details><summary><i>Previously, Ansku wrote…</i></summary><blockquote>

I asked yesterday in #framework-8-dev-team how that's done in practice, still waiting for answers.
</blockquote></details>

Fork the vaadin/vaadin-screenshots repo, make a PR with the new screenshots. Once that is merged, we can update the screenshot submodule to point to the correct version.

---

*[uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java, line 8 at r1](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0Rg8bnn00EiNG2Ekz:-KyuJvk7UFyeAjD-a495:b-hh61p7) ([raw file](https://github.com/vaadin/framework/blob/c8bed4cfafe6db7862ae4ddfe3ee548b06b99981/uitest/src/main/java/com/vaadin/tests/themes/valo/WindowControlButtonFocus.java#L8)):*
<details><summary><i>Previously, Ansku wrote…</i></summary><blockquote>

Didn't spot any that wouldn't have quite a few unnecessary parts in the screenshots. Didn't try out *all* of them, though.
</blockquote></details>

Let's just use this new one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10285)*

**Comment by Ansku** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10285#-Ky0S0TD97I8DpCnw6Mb:-Kyuri5J6XeZNa-45_mj:b-896fix) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Fork the vaadin/vaadin-screenshots repo, make a PR with the new screenshots. Once that is merged, we can update the screenshot submodule to point to the correct version.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10285)*

**Comment by tsuoanttila** [comment]
@ahie, can you make the final check and merge. Updated this to use correct screenshots.

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10285#-:-L-1N1VbvBnKWodSSi4G:bnfp4nl)*

**Pull request merged**
