### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by asashour**
Fix typos

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10124)

### CODE REVIEW

**Comment by hesara** [comment]
First round reviewed (comments, private fields etc. with clearly no impact on test results), will get back to the rest.

---

Reviewed 2 of 2 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 8 of 27 files at r4, 1 of 1 files at r5, 22 of 23 files at r6, 10 of 10 files at r7.
Review status: 45 of 56 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124#-:-KvRBFCIqOsxBSQpWdfJ:bypajho)*

**Comment by hesara** [comment]
Reviewed most of the changes, but it is not clear to me how this works for the v7 grid tests and where the exception string is supposed to come from to the log. Perhaps @tsuoanttila can check that part.

---

Reviewed 7 of 27 files at r4.
Review status: 52 of 56 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124#-:-KvRzjPxmYZUlx0EZLdd:byni7fr)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10124#-KvWI5iznyX8lkvvy4sl:-KvWI5j-QtEV-vbycXg4:b8q4rn9) (no related file):*
The changes in the v7 package are not tested in the validation. I'd recommend reverting them, they don't really do anything useful anyway (I've been thinking what to do about them, still not sure). If you want to keep the typo fixes in, please go through `GridBasicFeatures` test UI and try to find out where the exception is logged and fix there as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124)*

**Comment by tsuoanttila** [comment]
Reviewed 4 of 27 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10124#-KvWI5iznyX8lkvvy4sl:-KvZ5z74vaV5ARD_J4Qi:bamy5l6) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The changes in the v7 package are not tested in the validation. I'd recommend reverting them, they don't really do anything useful anyway (I've been thinking what to do about them, still not sure). If you want to keep the typo fixes in, please go through `GridBasicFeatures` test UI and try to find out where the exception is logged and fix there as well.
</blockquote></details>

The changes in v7 package is `occured` to `occurred` as far as I believe.  And it was replaced in all files in the project.

`GridBasicFeatures` doesn't contain any logging of "Exception occ".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 4 of 27 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10124#-:-KvaV7mTnFYlVB6TUO-i:bnfp4nl)*

**Pull request merged**
