### PR TITLE
Fix root POM SCM entries to point to GitHub

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/73)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/73#-KXylDh7MjLI4iDVlJco:-KXylDh7MjLI4iDVlJcp:b-2xglsb) ([raw file](https://github.com/vaadin/framework/blob/a2e72f6f626743cb0ef9c5cb096811cc6d01ecdb/pom.xml#L85)):*
> /vaadin

/framework?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/73)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/73#-KXylDh7MjLI4iDVlJco:-KXypVXQ03tk-RrC3lN7:ba4n3mb) ([raw file](https://github.com/vaadin/framework/blob/a2e72f6f626743cb0ef9c5cb096811cc6d01ecdb/pom.xml#L85)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> /vaadin

/framework?
</blockquote></details>

addressed by #75 (which at least partly replaces this patch)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/73)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/73)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/73#-:-KXywciBdVS-i8BfNF55:bnfp4nl)*

**Pull request merged**
