### PR TITLE
Do not create DOM elements for initially hidden columns

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10465)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 5143 at r1](https://reviewable.io:443/reviews/vaadin/framework/10465#-L1MPxFE6puXodSgOtxa:-L1MPxFE6puXodSgOtxb:b-9cvf8m) ([raw file](https://github.com/vaadin/framework/blob/09b22924d33427e3d8fed465d027f598b9f9a4d2/client/src/main/java/com/vaadin/client/widgets/Grid.java#L5143)):*
> ```Java
>                     grid.escalator.getColumnConfiguration().removeColumns(
>                             grid.getVisibleColumns().indexOf(this), 1);
>                     this.hidden = hidden;
> ```

Can setting the `this.hidden` be refactored so it wouldn't need three different calls ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10465)*

**Comment by tsuoanttila** [comment]
Small cleanup -style issue. Other than that is ok for me.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10465#-:-L1MQ9jk4pf7UQ1VwgJq:b-518f6q)*

**Comment by Artur-** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 5143 at r1](https://reviewable.io:443/reviews/vaadin/framework/10465#-L1MPxFE6puXodSgOtxa:-L1OTlC3n_TD9WArgN9v:b-o6ijpf) ([raw file](https://github.com/vaadin/framework/blob/09b22924d33427e3d8fed465d027f598b9f9a4d2/client/src/main/java/com/vaadin/client/widgets/Grid.java#L5143)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Can setting the `this.hidden` be refactored so it wouldn't need three different calls ?
</blockquote></details>

As far as I understand, that would require `if (grid == null) return;` in both branches instead, as hidden must be changed after removing the column or before adding the column. Don't think that would improve readability.

Better ideas?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10465)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 5143 at r1](https://reviewable.io:443/reviews/vaadin/framework/10465#-L1MPxFE6puXodSgOtxa:-L1R6wCGgKMQH4MXa0F-:b-be69e8) ([raw file](https://github.com/vaadin/framework/blob/09b22924d33427e3d8fed465d027f598b9f9a4d2/client/src/main/java/com/vaadin/client/widgets/Grid.java#L5143)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

As far as I understand, that would require `if (grid == null) return;` in both branches instead, as hidden must be changed after removing the column or before adding the column. Don't think that would improve readability.

Better ideas?
</blockquote></details>

Would require some more restructuring of the code to achieve. Withdrawn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10465#-:-L1R78_P7nsQqU5M0kaj:bnfp4nl)*

**Pull request merged**
