### PR TITLE
Testbench1009

### PR DESCRIPTION
**Pull request by Ansku**
Notes:
* This shouldn't be resolved before pull request #10692 as it's built on top of those changes
* The initial version of performance test is likely to cause issues

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10693)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Rebase the change on top of master

**Comment by tsuoanttila** [comment]
Reviewed 5 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingWithNewItemsAllowedTest.java, line 134 at r1](https://reviewable.io:443/reviews/vaadin/framework/10693#-L7ONcIdb2spjSWUgDWW:-L7ONcIdb2spjSWUgDWX:b-szbmn7) ([raw file](https://github.com/vaadin/framework/blob/4892bd372043d1261e4923cda57a67596b72a1e7/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingWithNewItemsAllowedTest.java#L134)):*
> ```Java
> 
>     @Test
>     public void selectionOnMouseOut() {
> ```

I'm not sure if I understood the change to this test or why is it here.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxTestBenchPerformanceTest.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/10693#-L7ONw2SJ7gJnFM3A9xb:-L7ONw2SJ7gJnFM3A9xc:b-ejh0tx) ([raw file](https://github.com/vaadin/framework/blob/4892bd372043d1261e4923cda57a67596b72a1e7/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxTestBenchPerformanceTest.java#L15)):*
> ```Java
> 
>     @Override
>     public void setup() throws Exception {
> ```

why override the super just to call `openTestURL()`? Should be just the first thing to do in the test method.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxTestBenchPerformanceTest.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/10693#-L7OOHtjOzmo6yO0ij6s:-L7OOHtjOzmo6yO0ij6t:b-w8pnqr) ([raw file](https://github.com/vaadin/framework/blob/4892bd372043d1261e4923cda57a67596b72a1e7/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxTestBenchPerformanceTest.java#L49)):*
> ```Java
>             combobox.sendKeys(value);
>             combobox.sendKeys(Keys.ENTER);
>         }
> ```

could add a `testBench().waitForVaadin()` to make sure that the ComboBox is indeed done with the internal state set. 

Theoretically the last operation of `selectByText` or `sendKeys` could be the one that makes it go into the total lockup mode, but it won't be observed until the next time we use an operation of TB that will check this. and it will be shown only at a later time that it has messed itself up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10693)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1505 at r2](https://reviewable.io:443/reviews/vaadin/framework/10693#-L8CpSgMzTdy4NSZscTP:-L8CpSgMzTdy4NSZscTQ:b87jn2e) ([raw file](https://github.com/vaadin/framework/blob/395acce7c3adb7b08f6f0d4dad13babdca921781/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1505)):*
> ```Java
>         }
> 
>         public void clearPending() {
> ```

Duplicate method with `cancelPendingPostFiltering`.

---

*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 139 at r2](https://reviewable.io:443/reviews/vaadin/framework/10693#-L8CpYBABcnls6jIm2nB:-L8CpYBBxVIqq3DEb_8z:b-9xlcid) ([raw file](https://github.com/vaadin/framework/blob/395acce7c3adb7b08f6f0d4dad13babdca921781/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L139)):*
> ```Java
>             clearNewItemHandling();
>         }
>         getDataReceivedHandler().updateSelectionFromServer(
> ```

This call will actually call `cancelPendingPostFiltering`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10693)*

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10693)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingWithNewItemsAllowedTest.java, line 134 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10693#-L7ONcIdb2spjSWUgDWW:-L8Hxfc64Hp-YElbXj6F:b-sk7pg5) ([raw file](https://github.com/vaadin/framework/blob/4892bd372043d1261e4923cda57a67596b72a1e7/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingWithNewItemsAllowedTest.java#L134)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'm not sure if I understood the change to this test or why is it here.
</blockquote></details>

LGTM! The popup does not even open without the fix included here. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10693)*

**Pull request merged**
