### PR TITLE
Create combined drop mode to allow both on_top and between drops

### LINKED ISSUE #8932: When dropping items on a grid, I want to allow the user to drop both on top of rows and between rows, because the dropped item might become a child or a sibling
When this mode is used, there should be some _threshold_  that specifies how many pixels on top and below the border between the rows specifies the drop in between rows, instead of on top of the row. This threshold should be configurable from the server side.

Should be done after #8401.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves  #8932

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9063)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9063#-KhWmx0opHdpirD-L1sM:-KhWmx0opHdpirD-L1sN:bcgsqw1) (no related file):*
This PR should be made into master branch once #9049 is in

---

*[server/src/main/java/com/vaadin/ui/GridDropTarget.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/9063#-KhWmgA7dbSxj_Q140c8:-KhWmgA7dbSxj_Q140c9:b-5tjlta) ([raw file](https://github.com/vaadin/framework/blob/c4cf569e6b3e63feec7af7c3902ea140a5262cc9/server/src/main/java/com/vaadin/ui/GridDropTarget.java#L112)):*
> ```Java
>      * <p>
>      * Default is 5 pixels.
>      */
> ```

missing `@param`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9063)*

**Comment by wbadam** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/GridDropTarget.java, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/9063#-KhWmgA7dbSxj_Q140c8:-KhWoxbrLacjXom2BzRO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c4cf569e6b3e63feec7af7c3902ea140a5262cc9/server/src/main/java/com/vaadin/ui/GridDropTarget.java#L112)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing `@param`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9063)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9063)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9063#-KhWmx0opHdpirD-L1sM:-KhXLfIaH3konaERd25m:b-ftg1jp) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This PR should be made into master branch once #9049 is in
</blockquote></details>

Needs rebase, otherwise ok to merge

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9063)*

**Comment by wbadam** [comment]
As Pekka requested, rebased this branch onto master

**Pull request merged**
