### PR TITLE
Update layout-gridlayout.asciidoc for better understanding of area coordines meaning.

### PR DESCRIPTION
**Pull request by hariprasad108**
It took me a lot time to understand, how to count coordinates in area. I supposed, that second pair is number of elements which should be split.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9948)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/layout/layout-gridlayout.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/framework/9948#-KtWF3P7W-RwtFgsLLvW:-KtWF3P7W-RwtFgsLLvX:bcqgv4h) ([raw file](https://github.com/vaadin/framework/blob/88e5548b11f3e73bc4e2a0c19264328bc1ee9efe/documentation/layout/layout-gridlayout.asciidoc#L17)):*
> ```AsciiDoc
> [classname]#GridLayout# container lays components out on a grid consisting of rows and columns.
> The columns and rows of the grid serve as coordinates that are used for laying out components on the grid.
> Each component can use multiple cells from the grid, defined as an area (x1,y1,x2,y2), where the first arranged pair (x1,y1) signs upper left and second lower right corner (x2,y2). As usual the first element is counted from zero i.e. first upper left element is on tthe position (0, 0, 0, 0). Although they typically take up only a single grid cell.
> ```

A few small corrections and suggestions for changes (or you can check the box that allows project maintainers to make changes to the PR branch, and we can do them):
- I'd maybe say something like ", where the first pair (x1,y1) refers to the upper left corner, and the second pair (x2,y2) to the lower right corner of the area."
- tthe -> the

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9948)*

**Comment by hesara** [comment]
@hariprasad108, could you either address the little issues I raised earlier, or enable the option (on the PR page) for project maintainers to be able to make edits to the PR branch.

**Comment by hesara** [comment]
Closing the PR as no reply from author and the author has not allowed direct editing of the PR branch by the project maintainers on the PR page. If you do make the changes, please comment here, and resubmit the change if no reply within a reasonable amount of time as maintainers may miss some comments to closed PRs.

**Comment by hariprasad108** [comment]
@hesara  Hello Henri Sara. I didn´t understood, what do you want from me. My knowledge of GitHub functionality is limited. The best should be to edit or rewrite this part of GridLayout, because it is hardly understandable. I can be done any one, not necesarily by me.

**Comment by hesara** [comment]
Rewrote the part a bit in #10072.

**Pull request closed without merging**
