### PR TITLE
Make TreeGrid follow framework style conventions

### LINKED ISSUE #8930: TreeGrid does not follow framework style conventions
Explicit style names without respect to a primary style name are used in `_treegrid.scss`, `HierarchyRenderer.java`

### PR DESCRIPTION
**Pull request by ahie**
Closes #8930 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9024)

### CODE REVIEW

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024#-:-Kh6IT34XjG1SkG2lIXe:bnfp4nl)*

**Comment by ahie** [comment]
Ping @elmot 

---

Review status: 5 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024#-:-Ki3trrPuO9bps_EhhoV:bt1t7sc)*

**Comment by elmot** [comment]
Reviewed 4 of 4 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 49 at r3](https://reviewable.io:443/reviews/vaadin/framework/9024#-Ki5a2gdqVTWO9s-WAZK:-Ki5a2gdqVTWO9s-WAZL:bgh7kwc) ([raw file](https://github.com/vaadin/framework/blob/140004e7862fc8b042f224114ee25c5cdac9f0c4/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L49)):*
> ```Java
>     @Override
>     protected String getFocusPrimaryStyleName() {
>         return TreeGridState.PRIMARY_STYLE_NAME + "-rowmode";
> ```

I am not sure if it should rely on inline constant. 
Why not `  setStylePrimaryName(STYLE_NAME);` in the constructor? see client-side `Grid`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024#-:-KiAF01Q0NlT04SVMdOt:bnfp4nl)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java, line 48 at r5](https://reviewable.io:443/reviews/vaadin/framework/9024#-KiE0_XKxB7duwO6gbx8:-KiE0_XKxB7duwO6gbx9:b2yioif) ([raw file](https://github.com/vaadin/framework/blob/f43d5f7aebf9f69c366882786761e2ed99f5a70c/client/src/main/java/com/vaadin/client/renderers/HierarchyRenderer.java#L48)):*
> ```Java
> public class HierarchyRenderer extends ClickableRenderer<Object, Widget> {
> 
>     private static final String CLASS_TREE_GRID_NODE = TreeGridState.PRIMARY_STYLE_NAME
> ```

Are these fixed rather than using the primary style name of the TG? Can these be non-static and updated for the TreeGrid when its primary style name is set to something else?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9024)*

**Pull request merged**
