### PR TITLE
 Fix AbstractSingleSelect selection and state updates

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10796)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 196 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eiRsE2gibQecXI_IJ:-L9eiRsE2gibQecXI_IK:b-9r67ue) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L196)):*
> ```Java
>      * @return the key of the selected item if any, {@code null} otherwise.
>      */
>     protected String getSelectedKey() {
> ```

API change. Should be reimplemented or mentioned in release notes. Also it needs to be decided if the change is included into 8.4

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 209 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9ej13NCBxLe-i2j_li:-L9ej13NCBxLe-i2j_lj:bc4j2dn) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L209)):*
> ```Java
>      */
>     protected void doSetSelectedKey(String key) {
>         getState().selectedItemKey = key;
> ```

API change. See above.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 222 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eoj-26hlHvcWYKhb2:-L9eoj-26hlHvcWYKhb3:btk7o7h) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L222)):*
> ```Java
>      *            selection
>      */
>     protected void setSelectedFromClient(String key) {
> ```

API change. 

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 248 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eqfbqE-k_5Aw8Gk72:-L9eqfbqE-k_5Aw8Gk73:btk7o7h) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L248)):*
> ```Java
>      *            the item to select or {@code null} to clear selection
>      */
>     protected void setSelectedFromServer(T item) {
> ```

API change. 

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 273 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eqguACU2czZQ_eI7u:-L9eqguACU2czZQ_eI7v:btk7o7h) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L273)):*
> ```Java
>      */
>     protected boolean isKeySelected(String key) {
>         return Objects.equals(key, getSelectedKey());
> ```

API change. 

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 283 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eqhu82LXGWgFLOR7v:-L9eqhu82LXGWgFLOR7w:btk7o7h) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L283)):*
> ```Java
>      * @return the assigned key
>      */
>     protected String itemToKey(T item) {
> ```

API change. 

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 333 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f9sq-71Akq1jpoKOP:-L9f9sq-71Akq1jpoKOQ:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L333)):*
> ```Java
>      *            not
>      */
>     protected void setSelectedItem(T value, boolean userOriginated) {
> ```

`@since`

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 363 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9fA3V17Kj1Wb5iTM5e:-L9fA3V17Kj1Wb5iTM5f:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L363)):*
> ```Java
>      * @param value
>      *            the value that is selected; may be {@code null}
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 218 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9fArKE9nzs24sp2J5g:-L9fArKE9nzs24sp2J5h:b-id1k9b) ([raw file](https://github.com/vaadin/framework/blob/16e6d8f6720e89c3fe94a6fdba79dedd83258d07/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L218)):*
> ```Java
>         }
> 
>         if (item == null || selectedItem == null) {
> ```

What if `null` has some id in the given DataProvider?

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 817 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eiqea7jz_QStCDT6f:-L9eiqea7jz_QStCDT6g:b-hb6sda) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/server/src/main/java/com/vaadin/ui/ComboBox.java#L817)):*
> ```Java
>     protected void updateSelectedItemState(T value) {
>         super.updateSelectedItemState(value);
>         
> ```

Extra spaces

---

*[server/src/test/java/com/vaadin/ui/ComboBoxTest.java, line 27 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f4P8F5BWCFCIoiR6Q:-L9f4P8F5BWCFCIoiR6R:b5ybp81) ([raw file](https://github.com/vaadin/framework/blob/450c5b226d9409cdc06bfd2643886e0036cbd06d/server/src/test/java/com/vaadin/ui/ComboBoxTest.java#L27)):*
> ```Java
>         comboBox.addValueChangeListener(event -> {
>             if (firstEvent) {
>                 assertEvent = () -> assertEquals(
> ```

Non-trivial way to check for events. What about using AtomicBoolean field instead of this? #FFS, not a blocker, though

---

*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxCaptionAndIconUpdate.java, line 73 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9esC_X1F33zpbXgSe9:-L9esC_X1F33zpbXgSeA:buoq6uf) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxCaptionAndIconUpdate.java#L73)):*
> ```Java
> 
>         addComponent(comboBox);
>         addComponent(createButton("Set Icon Generator", "icon",
> ```

Might be combined with `createButton` just to make sources a bit easier to read. Not a blocker

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10796)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 196 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9eiRsE2gibQecXI_IJ:-L9ilPLy4IsCnThilJut:be9mgz1) ([raw file](https://github.com/vaadin/framework/blob/64f0e6e059581cf91c9369aacee0c371597cf075/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L196)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

API change. Should be reimplemented or mentioned in release notes. Also it needs to be decided if the change is included into 8.4
</blockquote></details>

Not going to postpone 8.4 for this. It's only a minor bugfix (that fixes quite the number of bugs)

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 218 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9fArKE9nzs24sp2J5g:-L9ilh3y1Ws0R6Na3E0O:b9ehhzh) ([raw file](https://github.com/vaadin/framework/blob/16e6d8f6720e89c3fe94a6fdba79dedd83258d07/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L218)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What if `null` has some id in the given DataProvider?
</blockquote></details>

DataProvider has bee ndefined that `null` is not an item. See https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L128

Should we support `null` as an `item` we need to add a `null` check to every generator and provider all across the FW.

---

*[server/src/test/java/com/vaadin/ui/ComboBoxTest.java, line 27 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f4P8F5BWCFCIoiR6Q:-L9im1Gf9s_NIeP4DFJ2:b-p6y19b) ([raw file](https://github.com/vaadin/framework/blob/450c5b226d9409cdc06bfd2643886e0036cbd06d/server/src/test/java/com/vaadin/ui/ComboBoxTest.java#L27)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Non-trivial way to check for events. What about using AtomicBoolean field instead of this? #FFS, not a blocker, though
</blockquote></details>

I'd want to be able to figure out a better way for this. Complete suggestions welcome.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10796)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 218 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9fArKE9nzs24sp2J5g:-L9jEpCe9l3KZs9C3Qs8:bkzosev) ([raw file](https://github.com/vaadin/framework/blob/16e6d8f6720e89c3fe94a6fdba79dedd83258d07/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L218)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

DataProvider has bee ndefined that `null` is not an item. See https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/provider/DataProvider.java#L128

Should we support `null` as an `item` we need to add a `null` check to every generator and provider all across the FW.
</blockquote></details>

Ok, agree

---

*[server/src/test/java/com/vaadin/ui/ComboBoxTest.java, line 27 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f4P8F5BWCFCIoiR6Q:-L9oJN2349-3ymiKPech:b-gouaw1) ([raw file](https://github.com/vaadin/framework/blob/450c5b226d9409cdc06bfd2643886e0036cbd06d/server/src/test/java/com/vaadin/ui/ComboBoxTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'd want to be able to figure out a better way for this. Complete suggestions welcome.
</blockquote></details>

Like this:
```java
public class ComboBoxTest {

    private List<String> eventValues = new ArrayList<>();

    @Test
    public void testResetValue() {
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("one", "two");

        // Reset value whenever it changes (in a real case, this listener would
        // do something with the selected value before discarding it)
        comboBox.addValueChangeListener(event -> {
            eventValues.add(event.getValue());
            comboBox.setValue(null);
        });

        // "Attach" the component and initialize diffstate
        new MockUI().setContent(comboBox);
        // Generate initial data
        comboBox.getDataCommunicator().beforeClientResponse(true);
        ComponentTest.syncToClient(comboBox);

        // Emulate selection of "one"
        String oneKey = comboBox.getDataCommunicator().getKeyMapper()
                .key("one");
        ServerRpcManager.getRpcProxy(comboBox, SelectionServerRpc.class)
                .select(oneKey);

        assertArrayEquals(new Object[]{"one",null}, eventValues.toArray());

        ComponentTest.assertEncodedStateProperties(comboBox,
                "Selection change done by the listener should be sent to the client",
                "selectedItemKey");
    }
}
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10796)*

**Comment by tsuoanttila** [comment]
Rebased to be able to merge

---

Review status: 1 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 333 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f9sq-71Akq1jpoKOP:-LAMu82WEjEfdyZc5TDy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L333)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java, line 363 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9fA3V17Kj1Wb5iTM5e:-LAMu7rF2KAGWZ4HSxo1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/03a475e5495581dc04655c522f05a6fefbaad53e/server/src/main/java/com/vaadin/ui/AbstractSingleSelect.java#L363)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/ui/ComboBoxTest.java, line 27 at r3](https://beta.reviewable.io/reviews/vaadin/framework/10796#-L9f4P8F5BWCFCIoiR6Q:-LAMu9E3BwAeKY6I_NFa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/450c5b226d9409cdc06bfd2643886e0036cbd06d/server/src/test/java/com/vaadin/ui/ComboBoxTest.java#L27)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Like this:
```java
public class ComboBoxTest {

    private List<String> eventValues = new ArrayList<>();

    @Test
    public void testResetValue() {
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("one", "two");

        // Reset value whenever it changes (in a real case, this listener would
        // do something with the selected value before discarding it)
        comboBox.addValueChangeListener(event -> {
            eventValues.add(event.getValue());
            comboBox.setValue(null);
        });

        // "Attach" the component and initialize diffstate
        new MockUI().setContent(comboBox);
        // Generate initial data
        comboBox.getDataCommunicator().beforeClientResponse(true);
        ComponentTest.syncToClient(comboBox);

        // Emulate selection of "one"
        String oneKey = comboBox.getDataCommunicator().getKeyMapper()
                .key("one");
        ServerRpcManager.getRpcProxy(comboBox, SelectionServerRpc.class)
                .select(oneKey);

        assertArrayEquals(new Object[]{"one",null}, eventValues.toArray());

        ComponentTest.assertEncodedStateProperties(comboBox,
                "Selection change done by the listener should be sent to the client",
                "selectedItemKey");
    }
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10796#-:-LAMuI_MC2q30wOtlfog:b9vwkzg)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r6, 1 of 1 files at r8, 3 of 3 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10796#-:-LAS9c-tC55Xt1pjc1RI:bnfp4nl)*

**Pull request merged**
