### PR TITLE
Remove unnecessary full classnames and parenthesis from code

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8681)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 54 of 58 files at r1.
Review status: 54 of 58 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Field.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-Kdjv2TLqNlEvvllGDqL:-Kdjv2TMz2IKaFBJowqH:b-lvbo3b) ([raw file](https://github.com/vaadin/framework/blob/4095541ec922b4916d08bdcd3f2ef4a1a539e9c8/server/src/main/java/com/vaadin/ui/Field.java#L28)):*
> ```Java
>  *
>  * Field components are built upon the framework defined in the Field interface
>  * and the {@link com.vaadin.AbstractField} base class.
> ```

(looks like this used to be incorrect... in the ui package)

---

*[server/src/main/java/com/vaadin/ui/components/calendar/CalendarTargetDetails.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-Kdjw8sRmL1NcUAzyszO:-Kdjw8sRmL1NcUAzyszP:bn7n71e) ([raw file](https://github.com/vaadin/framework/blob/4095541ec922b4916d08bdcd3f2ef4a1a539e9c8/server/src/main/java/com/vaadin/ui/components/calendar/CalendarTargetDetails.java#L26)):*
> ```Java
> 
> /**
>  * Drop details for {@link com.vaadin.ui.addon.calendar.ui.Calendar Calendar}.
> ```

(was incorrect, like below)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by hesara** [comment]
Reviewed 2 of 58 files at r1.
Review status: 56 of 58 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/util/SerializerHelper.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzJlUY5iLapu9S0QZ:-KdjzJlUY5iLapu9S0Q_:bgrcfk2) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/main/java/com/vaadin/util/SerializerHelper.java#L108)):*
> ```Java
>      * serializing/deserializing these (#3064).
>      */
>     private static final Class<?>[] primitiveClasses = new Class<?>[] {
> ```

I guess making this final is an intended change...

---

*[server/src/test/java/com/vaadin/data/util/sqlcontainer/SQLContainerTableQueryTest.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzRJ4QZrLEFiwy-4s:-KdjzRJ4QZrLEFiwy-4t:b-oo7s5d) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/test/java/com/vaadin/data/util/sqlcontainer/SQLContainerTableQueryTest.java#L190)):*
> ```Java
> 
>         Item item = getItem(container.lastItemId());
>         assertThat(item.getItemProperty(NAME).toString(), is("foo"));
> ```

why removed getValue() - it should always be used rather than assuming the item property toString() prints what you expect

---

*[server/src/test/java/com/vaadin/tests/server/component/abstractfield/AbstractFieldListenersTest.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzaTDLNy-J2vU8EYD:-KdjzaTEYx67iZROxnS-:b-8iygfn) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/test/java/com/vaadin/tests/server/component/abstractfield/AbstractFieldListenersTest.java#L10)):*
> ```Java
> import com.vaadin.data.Property.ValueChangeListener;
> import com.vaadin.tests.server.component.AbstractListenerMethodsTestBase;
> import com.vaadin.ui.Table;
> ```

does this change break anything in 7.7?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by tsuoanttila** [comment]
Reverted the couple of iffy changes.

---

Review status: 56 of 58 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/data/util/sqlcontainer/SQLContainerTableQueryTest.java, line 190 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzRJ4QZrLEFiwy-4s:-Kdk6FmsEk5QvQC0ahTj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/test/java/com/vaadin/data/util/sqlcontainer/SQLContainerTableQueryTest.java#L190)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

why removed getValue() - it should always be used rather than assuming the item property toString() prints what you expect
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/abstractfield/AbstractFieldListenersTest.java, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzaTDLNy-J2vU8EYD:-Kdk6FReVyjoVK6YH8CI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/test/java/com/vaadin/tests/server/component/abstractfield/AbstractFieldListenersTest.java#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

does this change break anything in 7.7?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681#-:-Kdk6GuMcQVGIhC7afIz:b-lmdtsl)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681#-:-Kdk6bZ_h9fVVIB-Q3p6:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by hesara** [comment]
Reviewed 16 of 16 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by hesara** [comment]
Reviewed 41 of 44 files at r5.
Review status: 88 of 91 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/util/HierarchicalContainer.java, line 44 at r5](https://reviewable.io:443/reviews/vaadin/framework/8681#-Ke8sJYsy1s9mP2K8SvJ:-Ke8sJYtg7126k9uDT8x:b32wio) ([raw file](https://github.com/vaadin/framework/blob/ee8d4793a71fd6641719893e3086c96a20911290/server/src/main/java/com/vaadin/data/util/HierarchicalContainer.java#L44)):*
> ```Java
> 
>     /**
>      * d Set of IDs of those contained Items that can't have children.
> ```

d?

---

*[server/src/main/java/com/vaadin/ui/AbstractField.java, line 687 at r5](https://reviewable.io:443/reviews/vaadin/framework/8681#-Ke8s_L-K5AJ4RL4ayNX:-Ke8s_L-K5AJ4RL4ayNY:b-l1drh5) ([raw file](https://github.com/vaadin/framework/blob/ee8d4793a71fd6641719893e3086c96a20911290/server/src/main/java/com/vaadin/ui/AbstractField.java#L687)):*
> ```Java
>         // Fires value change if the value has changed
>         T value = getInternalValue();
>         if (value != oldValue && (value != null && !value.equals(oldValue))
> ```

is this actually equivalent with the old version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by tsuoanttila** [comment]
Review status: 88 of 91 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/util/HierarchicalContainer.java, line 44 at r5](https://reviewable.io:443/reviews/vaadin/framework/8681#-Ke8sJYsy1s9mP2K8SvJ:-Ke8wknd3q2Y0NkUVe7Y:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee8d4793a71fd6641719893e3086c96a20911290/server/src/main/java/com/vaadin/data/util/HierarchicalContainer.java#L44)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

d?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractField.java, line 687 at r5](https://reviewable.io:443/reviews/vaadin/framework/8681#-Ke8s_L-K5AJ4RL4ayNX:-Ke8wjkg9O3zhxea1RFm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ee8d4793a71fd6641719893e3086c96a20911290/server/src/main/java/com/vaadin/ui/AbstractField.java#L687)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is this actually equivalent with the old version?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/util/SerializerHelper.java, line 108 at r1](https://reviewable.io:443/reviews/vaadin/framework/8681#-KdjzJlUY5iLapu9S0QZ:-Ke8ws4zexnId6zrdrHX:bc11wnv) ([raw file](https://github.com/vaadin/framework/blob/86c70f2d9e10d6fe343197c58b4ea69990bb905d/server/src/main/java/com/vaadin/util/SerializerHelper.java#L108)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I guess making this final is an intended change...
</blockquote></details>

Yes. Just to made it absolutely clear that primitiveClasses are not meant to be modified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 44 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8681#-:-KeD6YQHSmuVjvN71hak:bnfp4nl)*

**Pull request merged**
