### PR TITLE
Migrate 7.7.5 branch patches to v8.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#495

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7969)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, 8 of 11 files at r7, 3 of 7 files at r8, 5 of 5 files at r9, 11 of 11 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYwFfGwiG2ugfTfnmDs:b-i84gog) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
> ```Java
>  *
>  */
> public class VTextField extends TextBoxBase implements Field, FocusHandler,
> ```

The changes here make no sense, just adding an import but not using it ?
I think `VTextField should implement `DeferredWorker`

---

*[scripts/GeneratePublishReportPart1.py, line 17 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwHDcDG8ZzKkO4AH8v:-KYwHDcDG8ZzKkO4AH8w:b-oynjog) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/scripts/GeneratePublishReportPart1.py#L17)):*
> ```Python
> 	'https://vaadin.com/download/release/7.7/LATEST': '^7\..*',
> 	'https://vaadin.com/download/LATEST': '^6\..*',
> 	'https://vaadin.com/download/PRERELEASES': '^8\..*'
> ```

Not sure if this should change, @hesara ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYwJR_I1CTd3UFE1EN1:bsl4k38) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

The changes here make no sense, just adding an import but not using it ?
I think `VTextField should implement `DeferredWorker`
</blockquote></details>

Should in v7.
Not in v8.

It's a consequence of not cleaned up cherry pick.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by hesara** [comment]
Review status: 35 of 37 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scripts/GeneratePublishReportPart1.py, line 17 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwHDcDG8ZzKkO4AH8v:-KYwfbyEbLexe3HBjraG:bh4jgjz) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/scripts/GeneratePublishReportPart1.py#L17)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure if this should change, @hesara ?
</blockquote></details>

the ^{ver} is a stricter check that we should probably keep for now, and only replace like this when we go to 8.0.0 final - we should make a ticket with all the updates needed for building 8.0.0 final

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: 34 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/GeneratePublishReportPart1.py, line 17 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwHDcDG8ZzKkO4AH8v:-KYwirp_gGhOxjy7R9w9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/scripts/GeneratePublishReportPart1.py#L17)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the ^{ver} is a stricter check that we should probably keep for now, and only replace like this when we go to 8.0.0 final - we should make a ticket with all the updates needed for building 8.0.0 final
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: 34 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYwj07-l3yDZ4YG2EHw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should in v7.
Not in v8.

It's a consequence of not cleaned up cherry pick.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Review status: 34 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYwQyqopjAbwS0RLAx5:binfz37) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Should in v7.
Not in v8.

It's a consequence of not cleaned up cherry pick.
</blockquote></details>

What, why doesn't that change apply to V8 `TextField` ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Review status: 34 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYx0sBxZdwpy_0I1hdL:b-jmvfvo) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

What, why doesn't that change apply to V8 `TextField` ? 
</blockquote></details>

(sorry forgot to post comment earlier)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Reviewed 1 of 3 files at r11.
Review status: 35 of 36 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Reviewed 2 of 3 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYx21py-K7CdaNqTtUS:bx9ecgx) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

(sorry forgot to post comment earlier)
</blockquote></details>

I have no idea how I can do it......
The change is not only to add DeferredWorker here as a super interface.

You have to implement it.
There is absolutely trivial and straightforward  way in v7. There is a variable for that is already in VTextFiled. (see the change in the compatibility module)

V8 VTextField has totally different implementation and I don't see how can I migrate the patch.

Tests work . They are migrated. I'm not sure what the original patch actually does. But according to tests V8 TextField works as expected out of the box.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYxRHpbC6ZpXMp04PNe:b-t585ad) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I have no idea how I can do it......
The change is not only to add DeferredWorker here as a super interface.

You have to implement it.
There is absolutely trivial and straightforward  way in v7. There is a variable for that is already in VTextFiled. (see the change in the compatibility module)

V8 VTextField has totally different implementation and I don't see how can I migrate the patch.

Tests work . They are migrated. I'm not sure what the original patch actually does. But according to tests V8 TextField works as expected out of the box.
</blockquote></details>

Did you ask the patch author? :trollface: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VTextField.java, line 34 at r10](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYwFfGwiG2ugfTfnmDr:-KYxTU1HLnzAWiccp-Ut:b-yny2k) ([raw file](https://github.com/vaadin/framework/blob/b9fdb59f4f16cf7de9739f8ea2d8842b67df3e15/client/src/main/java/com/vaadin/client/ui/VTextField.java#L34)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Did you ask the patch author? :trollface: 
</blockquote></details>

You have been talking a lot at the time when I was thinking about it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by Artur-** [comment]
Reviewed 1 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxifSIvl3koAgrVN7_:-KYxifSJugt-UVNA-OVn:brtzg63) (no related file):*
RichTextArea also supports the text change events, and probably needs to same `DeferredWorker` code. AFAIK can't be tested automatically

---

*[uitest/src/test/java/com/vaadin/tests/components/textfield/TextChangeEventsTest.java, line 18 at r12](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxijZEPwh6Ne2p14mQ:-KYxijZEPwh6Ne2p14mR:b-v0wljq) ([raw file](https://github.com/vaadin/framework/blob/3c40edf3ee241cc38b022b592bf177690613ee31/uitest/src/test/java/com/vaadin/tests/components/textfield/TextChangeEventsTest.java#L18)):*
> ```Java
>                 .caption("Default text area").first();
>         taDefault.sendKeys("abc");
>         waitUntil(driver -> getLogRow(0).equals(
> ```

Remove all `waitUntil` - otherwise you are not testing anything at all

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by denis-anisimov** [comment]
Review status: 35 of 38 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxifSIvl3koAgrVN7_:-KZ0KelTC0xFgVXl1UZE:bzfbmuu) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

RichTextArea also supports the text change events, and probably needs to same `DeferredWorker` code. AFAIK can't be tested automatically
</blockquote></details>

Is this a part of migration ?
The original code contains changes only in VTextField. Which should not affect the `RichTextArea`, right  ?

---

*[uitest/src/test/java/com/vaadin/tests/components/textfield/TextChangeEventsTest.java, line 18 at r12](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxijZEPwh6Ne2p14mQ:-KYxjWvXYyyQJo9rW78g:bxoimoz) ([raw file](https://github.com/vaadin/framework/blob/3c40edf3ee241cc38b022b592bf177690613ee31/uitest/src/test/java/com/vaadin/tests/components/textfield/TextChangeEventsTest.java#L18)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Remove all `waitUntil` - otherwise you are not testing anything at all
</blockquote></details>

I thought I completely replaced it with the code from the original test.

My bad.

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by Artur-** [comment]
Review status: 35 of 38 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxifSIvl3koAgrVN7_:-KZ0OU8neERD2T2htHre:b-k6u1b1) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is this a part of migration ?
The original code contains changes only in VTextField. Which should not affect the `RichTextArea`, right  ?
</blockquote></details>

I would make a separate PR, or at least an issue. The original fix was for all components in V7 that support TextChangeEvents (TF + TA)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Reviewed 3 of 4 files at r13.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxifSIvl3koAgrVN7_:-KZ0R1imntITmKr7zxHS:bys4pyi) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

I would make a separate PR, or at least an issue. The original fix was for all components in V7 that support TextChangeEvents (TF + TA)
</blockquote></details>

Now this patch has the fix for both, TF + TA since it is done on `AbstractTextFieldConnector`. Not sure if there are tests for TA though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by Artur-** [comment]
Reviewed 3 of 4 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7969#-KYxifSIvl3koAgrVN7_:-KZ0SMUpfGJYx5mYcmPj:b-h23fa1) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Now this patch has the fix for both, TF + TA since it is done on `AbstractTextFieldConnector`. Not sure if there are tests for TA though
</blockquote></details>

My bad, yes the test is for both TF & TA

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969#-:-KZ0TC8yJTPS8A1Qz7cJ:bnfp4nl)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Comment by pleku** [comment]
Reviewed 5 of 8 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7969)*

**Pull request merged**
