### PR TITLE
Add recursive expand and collapse method to TreeGrid and Tree

### LINKED ISSUE #9969: Add method expandAll/collapseAll for Tree and TreeGrid
- Vaadin version 8.1.3

In the moment there is only a function to expand a specific item or a list of items. But for the list the items are only expanded for the root elements. So either expand should scan the childs (via childItemProvider?) in the list and expand them or make a method without parameter for expanding and collapsing all items.

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #9969

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10283)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Kxwktdl9q_ovIS63WRE:-Kxwktdl9q_ovIS63WRF:bkf8uc1) (no related file):*
Should fire some kind of event on expand/collapse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r5, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Kxwktdl9q_ovIS63WRE:-Ky0PWbbDSk97Q0Na98a:byoz6d9) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Should fire some kind of event on expand/collapse?
</blockquote></details>

Most likely. Marked the spots to fire the events.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 436 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0PwLdunSnQOsSk6RA:-Ky0PwLdunSnQOsSk6RB:b-m3gz1i) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/Tree.java#L436)):*
> descendants
children

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 479 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QehoRNk84wrHGDNi:-Ky0QehoRNk84wrHGDNj:b-ntye94) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/Tree.java#L479)):*
> its descendants
their children

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 343 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0Q0-ITDlcwNGMD9wI:-Ky0Q0-ITDlcwNGMD9wJ:b-pf9cj2) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L343)):*
> ```Java
>      *            the items to expand
>      */
>     public void expand(Collection<T> items) {
> ```

should this be `expandRecursively(items, 0)` ?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 355 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QUgNWYn9oADqfxa0:-Ky0QUgNWYn9oADqfxa1:b-ntye94) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L355)):*
> its descendants
their children

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 374 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QSWG7bf7VJ4rjuFx:-Ky0QSWG7bf7VJ4rjuFy:b-ntye94) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L374)):*
> its descendants
their children

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 397 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0OocipdT3FLEwqt8a:-Ky0OocipdT3FLEwqt8b:b-c8d4et) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L397)):*
> ```Java
>             if (communicator.hasChildren(item)) {
>                 if (!communicator.isExpanded(item)) {
>                     communicator.expand(item);
> ```

fireExpandEvent(item, false);

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 428 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0Q7Y-AdXMgNPg1NCw:-Ky0Q7Y-AdXMgNPg1NCx:b60sfl3) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L428)):*
> ```Java
>      *            the collection of items to collapse
>      */
>     public void collapse(Collection<T> items) {
> ```

Should this be `collapseRecursively(items, 0)`? 

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 439 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QNOddit5nKJHTIgW:-Ky0QNOddit5nKJHTIgX:b-ntye94) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L439)):*
> its descendants
their children

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 458 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QanIrFBOF5jjQJVA:-Ky0QanIrFBOF5jjQJVB:b-ntye94) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L458)):*
> its descendants
their children

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 486 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0PM5O9fxTmjDQaojs:-Ky0PM5O9fxTmjDQaojt:b-rpipxk) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L486)):*
> ```Java
> 
>                 if (communicator.isExpanded(item)) {
>                     communicator.collapse(item);
> ```

fireCollapseEvent(item, false);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Kxwktdl9q_ovIS63WRE:-Ky1KljcMqYKsANihjWe:b-hcyymo) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Most likely. Marked the spots to fire the events.
</blockquote></details>

If  separate event is fired at each expansion, wouldn't it result in bad performance ([Henri's comment](https://github.com/vaadin/framework/issues/9969#issuecomment-328778653))?

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky1LOgoX0doDCq9by9y:-Ky1LOgoX0doDCq9by9z:b-fvv2j2) (no related file):*
The performance doesn't seem great for huge grids even without the events. Do you have any ideas how to improve that or whether it is possible to improve?

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 436 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0PwLdunSnQOsSk6RA:-Ky1JDJl2WswavsmTyjr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/Tree.java#L436)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> descendants
children
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Tree.java, line 479 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QehoRNk84wrHGDNi:-Ky1JGkVgpKPz9eEAjKq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/Tree.java#L479)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> its descendants
their children
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 355 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QUgNWYn9oADqfxa0:-Ky1JQDEMIkEJFeoAGF9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L355)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> its descendants
their children
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 374 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QSWG7bf7VJ4rjuFx:-Ky1JTZBIV5vsgYF02pR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L374)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> its descendants
their children
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 439 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QNOddit5nKJHTIgW:-Ky1JZ9m6dioYCJTJ6zx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L439)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> its descendants
their children
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 458 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0QanIrFBOF5jjQJVA:-Ky1JZN9qak6_0DUyzsW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L458)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> its descendants
their children
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Kxwktdl9q_ovIS63WRE:-KyuKBf8fU3x4ABIZFtZ:bogyokw) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

If  separate event is fired at each expansion, wouldn't it result in bad performance ([Henri's comment](https://github.com/vaadin/framework/issues/9969#issuecomment-328778653))?
</blockquote></details>

There's a suggestion on the performance of this whole thing, might need some tinkering and improvements still.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky1LOgoX0doDCq9by9y:-KypF2k8qGMNBUDttQgz:b-u9iknd) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

The performance doesn't seem great for huge grids even without the events. Do you have any ideas how to improve that or whether it is possible to improve?
</blockquote></details>

Technically we could move it one step "up" towards the HierarchicalDataCommunicator or HierarchyMapper and re-use some information from earlier fetches. From there it should most likely return all the expanded nodes (in some order) to fire the events.

Technically this is something we could also improve later on but the decision of event firing is something we need to do before we can merge. will have a discussion with related people face to face.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky1LOgoX0doDCq9by9y:-L3llmgPpj-V41riLkgR:b-hy7hbi) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Technically we could move it one step "up" towards the HierarchicalDataCommunicator or HierarchyMapper and re-use some information from earlier fetches. From there it should most likely return all the expanded nodes (in some order) to fire the events.

Technically this is something we could also improve later on but the decision of event firing is something we need to do before we can merge. will have a discussion with related people face to face.
</blockquote></details>

Let's take the performance fixing as an enhancement to this functionality.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 343 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0Q0-ITDlcwNGMD9wI:-L3ll-0oD5evQ0SfmIEp:b-hj3hn5) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L343)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should this be `expandRecursively(items, 0)` ?
</blockquote></details>

Withdrawn.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 397 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0OocipdT3FLEwqt8a:-L3ll1vrSZ_6khxKMApn:bxsyd5r) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L397)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

fireExpandEvent(item, false);
</blockquote></details>

Withdrawn

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 428 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0Q7Y-AdXMgNPg1NCw:-L3ll3bK12DfVG43KlXH:bxsyd5r) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L428)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should this be `collapseRecursively(items, 0)`? 
</blockquote></details>

Withdrawn

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 486 at r8](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky0PM5O9fxTmjDQaojs:-L3ll6Q3Nc1mVkhIBmxD:bxsyd5r) ([raw file](https://github.com/vaadin/framework/blob/9cf95d3bb485cc7d16a813e73b244b360554893f/server/src/main/java/com/vaadin/ui/TreeGrid.java#L486)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

fireCollapseEvent(item, false);
</blockquote></details>

Withdrawn

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 362 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lle_6SntI8Hqk-ooy:-L3lle_6SntI8Hqk-ooz:b6facg) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L362)):*
> ```Java
>      * the given items while {@code expandRecursively(items, 2)} expands the
>      * given items as well as their children and grandchildren.
>      *
> ```

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 367 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llkcEVaBV6xiZpsNs:-L3llkcEVaBV6xiZpsNt:b2nh32x) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L367)):*
> ```Java
>      * @param depth
>      *            the maximum depth of recursion
>      * @since
> ```

8.4

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 381 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llPg7JBCokGILFB2S:-L3llPg7JBCokGILFB2T:b6facg) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L381)):*
> ```Java
>      * the given items while {@code expandRecursively(items, 2)} expands the
>      * given items as well as their children and grandchildren.
>      *
> ```

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 386 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lljx2XAf_D86Jtvqe:-L3lljx2XAf_D86Jtvqf:b2nh32x) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L386)):*
> ```Java
>      * @param depth
>      *            the maximum depth of recursion
>      * @since
> ```

8.4

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 446 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llZLHRbCTkL_opkIA:-L3llZLHRbCTkL_opkIB:b6facg) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L446)):*
> ```Java
>      * only the given items while {@code collapseRecursively(items, 2)}
>      * collapses the given items as well as their children and grandchildren.
>      *
> ```

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 451 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lliCIjZile-sobF8Z:-L3lliCIjZile-sobF8_:b2nh32x) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L451)):*
> ```Java
>      * @param depth
>      *            the maximum depth of recursion
>      * @since
> ```

8.4

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 465 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llCxYTC3jD9M_fHQ_:-L3llCxYTC3jD9M_fHQa:b6facg) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L465)):*
> ```Java
>      * only the given items while {@code collapseRecursively(items, 2)}
>      * collapses the given items as well as their children and grandchildren.
>      *
> ```

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 470 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llK5PuyfqmHOeRJ0R:-L3llK5PuyfqmHOeRJ0S:b2nh32x) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L470)):*
> ```Java
>      * @param depth
>      *            the maximum depth of recursion
>      * @since
> ```

8.4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by wbadam** [comment]
Review status: 4 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 362 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lle_6SntI8Hqk-ooy:-L3lwTklBeO_WLsPaQk0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L362)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 367 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llkcEVaBV6xiZpsNs:-L3luvFk1y_-nAfgAy5L:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L367)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

8.4
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 381 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llPg7JBCokGILFB2S:-L3lwVjdkrAcujPgSrrL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L381)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 386 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lljx2XAf_D86Jtvqe:-L3lwW6509EXxMi4UszB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L386)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

8.4
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 446 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llZLHRbCTkL_opkIA:-L3lwifl6zOLdqxXz_ov:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L446)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 451 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3lliCIjZile-sobF8Z:-L3lwjDIFAFUws27QCG3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L451)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

8.4
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 465 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llCxYTC3jD9M_fHQ_:-L3lwp74y6vk6zyubU2E:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L465)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Please add a comment about the performance issue with slow database connection and mention that this will _not_ fire events for expanded nodes.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 470 at r9](https://reviewable.io:443/reviews/vaadin/framework/10283#-L3llK5PuyfqmHOeRJ0R:-L3lwpMm1q3vmZqiQPLf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c137ab2beccae10e3cf4c25ef9369723cda9de51/server/src/main/java/com/vaadin/ui/TreeGrid.java#L470)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

8.4
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r14, 1 of 1 files at r16, 1 of 2 files at r18, 1 of 1 files at r20, 1 of 1 files at r21, 4 of 5 files at r22, 1 of 1 files at r23.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4_XcEjUHA3AuxhRyy6:-L4_XcEjUHA3AuxhRyy7:b-w3jvzm) (no related file):*
This change could use some kind of a "horror test" on the server to see that the expanding of nodes doesn't take too long time. Not sure how and what to test though.

One idea could be to have a proxy of a list with some `sleep` to mimic a server delay. or could just check call counts to methods and extrapolate from that..

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 17 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4_XP7-k71FtdGhz_iK:-L4_XP7-k71FtdGhz_iL:bczfnmq) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L17)):*
> ```Java
> 
> @Widgetset("com.vaadin.DefaultWidgetSet")
> public class TreeGridExpandCollapseRecursively extends AbstractTestUI {
> ```

Is there a test for this UI?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Kxwktdl9q_ovIS63WRE:-L4aT_5RcghVZTOT2Xin:b-lzf8mn) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

There's a suggestion on the performance of this whole thing, might need some tinkering and improvements still.
</blockquote></details>

Performance problems are fixed

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10283#-Ky1LOgoX0doDCq9by9y:-L4aTcdgo9TV57UlNPER:b-lzf8mn) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Let's take the performance fixing as an enhancement to this functionality.
</blockquote></details>

Performance problems are fixed

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 17 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4_XP7-k71FtdGhz_iK:-L4aUI_3m5SdirTV1Rqx:b-c2n3b7) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L17)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is there a test for this UI?
</blockquote></details>

Not at the moment, I'd probably need to get rid of random text generation for a test. Could add some tests if you'd like.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 86 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4k7d9CeOLsQxFzvLtz:-L4k7d9CeOLsQxFzvLu-:b-lgadtt) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L86)):*
> ```Java
>         if (depth >= 0) {
>             for (int i = 0; i < childCount; i++) {
>                 Directory dir = new Directory(RandomStringUtils.randomAlphabetic(20), parent);
> ```

RandomStringUtils could be easily replaced with a static String and the loop variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 17 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4_XP7-k71FtdGhz_iK:-L4kWpiKLeySZ4Te3oQm:b-pnrg3o) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L17)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Not at the moment, I'd probably need to get rid of random text generation for a test. Could add some tests if you'd like.
</blockquote></details>

A test with some simple timeout should make sure the performance is not immediately reverted with any upcoming change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by wbadam** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 17 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4_XP7-k71FtdGhz_iK:-L4khJp2vxFRYjTkfn_1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L17)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

A test with some simple timeout should make sure the performance is not immediately reverted with any upcoming change.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java, line 86 at r23](https://reviewable.io:443/reviews/vaadin/framework/10283#-L4k7d9CeOLsQxFzvLtz:-L4khLfjU6XUT1YFKMzT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b1c64d1b50c5634d2c2416514e5bf9ceda7c7498/uitest/src/main/java/com/vaadin/tests/components/treegrid/TreeGridExpandCollapseRecursively.java#L86)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

RandomStringUtils could be easily replaced with a static String and the loop variable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r24, 2 of 2 files at r25.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10283)*

**Pull request merged**
