### PR TITLE
Implement LocalDateRenderer and LocalDateTimeRenderer

### LINKED ISSUE #8377: There should be LocalDateRenderer and LocalDateTimeRenderer
@pleku commented on [Mon Oct 03 2016](https://github.com/vaadin/framework8-issues/issues/367)

DateRenderer should not be Date based, should use e.g. Instant or something else so that user doesn't have to convert to Date.
Another option would be to have several Date related renderers for each type ? E.g. InstantRenderer, LocalDateRenderer ...

---

@pleku commented on [Tue Oct 11 2016](https://github.com/vaadin/framework8-issues/issues/367#issuecomment-252833377)

SHOULD HAVE, but not necessary for FW8.

### PR DESCRIPTION
**Pull request by ahie**
Closes #8377

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8955)

### CODE REVIEW

**Comment by ahie** [comment]
Still missing constructor overloads from `LocalDateRenderer`. Blocking.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955#-:-KgEk9T7SmCf2jJAwOw3:b-lygy4r)*

**Comment by hesara** [comment]
Reviewed 6 of 8 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/LocalDateRendererConnector.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJjsQtFQYU7TpA3OTy:-KgJjsQuYTc_N-49s1n-:b2yvuam) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/client/src/main/java/com/vaadin/client/connectors/grid/LocalDateRendererConnector.java#L27)):*
> ```Java
>  * serialized as a string, and displayed as-is on the client side. This is to be
>  * able to support the server's locale.
>  * 
> ```

(some extra spaces in javadoc here and in the other files)

---

*[server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJlyUNFQzNHwPiG-2X:-KgJlyUNFQzNHwPiG-2Y:b-bzaa08) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/server/src/main/java/com/vaadin/ui/renderers/LocalDateRenderer.java#L49)):*
> ```Java
>      */
>     public LocalDateRenderer() {
>         this(DateTimeFormatter.ofLocalizedDate(FormatStyle.LONG), "");
> ```

see comments for LocalDateTimeRenderer

---

*[server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJkxfdTsPw9ZU2_R4L:-KgJkxfdTsPw9ZU2_R4M:b-4a2ab) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L53)):*
> ```Java
>      */
>     public LocalDateTimeRenderer() {
>         this(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.LONG,
> ```

Not using the locale of the UI so defaulting to the system locale of the server - not really ideal. Can this be done otherwise? (Apparently DateRenderer uses the same approach.)

---

*[server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJlL23Krk_03eQNwpZ:-KgJlL23Krk_03eQNwp_:bypkof5) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L114)):*
> ```Java
>      */
>     public LocalDateTimeRenderer(String formatPattern) {
>         this(formatPattern, Locale.getDefault());
> ```

Not really ideal to use the default locale - should rather use the UI or the Grid locale, but is that possible? (Apparently DateRenderer uses the same approach.)

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/LocalDateRenderersTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJkUQYHYP8QT1yyVZW:-KgJkUQYHYP8QT1yyVZX:brpshot) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/uitest/src/test/java/com/vaadin/tests/components/grid/LocalDateRenderersTest.java#L24)):*
> ```Java
>         Assert.assertEquals(
>                 epochDate.format(
>                         DateTimeFormatter.ofLocalizedDate(FormatStyle.LONG)),
> ```

These assume that the default locale of the JUnit JVM and the Vaadin application are the same - can we always trust this or should also this fix the locale of the UI and of the JUnit test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by ahie** [comment]
Review status: 2 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/LocalDateRendererConnector.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJjsQtFQYU7TpA3OTy:-KgJynXKBsjhKxREQhtI:bss4a2b) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/client/src/main/java/com/vaadin/client/connectors/grid/LocalDateRendererConnector.java#L27)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(some extra spaces in javadoc here and in the other files)
</blockquote></details>

Removed.

---

*[server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 53 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJkxfdTsPw9ZU2_R4L:-KgJwsdJs1f6fOzme7uJ:byik66a) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L53)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Not using the locale of the UI so defaulting to the system locale of the server - not really ideal. Can this be done otherwise? (Apparently DateRenderer uses the same approach.)
</blockquote></details>

Changed to use the grid's locale by default.

---

*[server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJlL23Krk_03eQNwpZ:-KgJx-0U6OAFDXUCAiZ0:b-cxfbnl) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/server/src/main/java/com/vaadin/ui/renderers/LocalDateTimeRenderer.java#L114)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Not really ideal to use the default locale - should rather use the UI or the Grid locale, but is that possible? (Apparently DateRenderer uses the same approach.)
</blockquote></details>

Same as previous comment.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/LocalDateRenderersTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgJkUQYHYP8QT1yyVZW:-KgJx1zID5ryfwNjdyou:b-bei0fz) ([raw file](https://github.com/vaadin/framework/blob/608b245c012751b38d98605853e245179f3c2832/uitest/src/test/java/com/vaadin/tests/components/grid/LocalDateRenderersTest.java#L24)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

These assume that the default locale of the JUnit JVM and the Vaadin application are the same - can we always trust this or should also this fix the locale of the UI and of the JUnit test?
</blockquote></details>

Now that the default locale is read from the grid, this can be done easily. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by ahie** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgK64pwsWvKaRTQxwdj:-KgOCZG3oe3x9UDGoJMC:b-896fix) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

needs documentation, otherwise LGTM
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgK64pwsWvKaRTQxwdj:-KgOENf6nVzlHxuLI_nr:b-d8dg) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Minor comments + probably needs rebase/merge

---

*[documentation/components/components-grid.asciidoc, line 491 at r4](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgODa51sZP6TC0Kci6y:-KgODa51sZP6TC0Kci6z:bs0ftcw) ([raw file](https://github.com/vaadin/framework/blob/67432ada4942e0cbe0ae86d79dabb2154e5db368/documentation/components/components-grid.asciidoc#L491)):*
> ```AsciiDoc
> The renderer can be constructed with a [classname]#DateTimeFormatter#, or with a custom pattern string.
> The locale is either given explicitly with the pattern, resolved from the given [classname]#DateTimeFormatter# or from the grid the renderer is attached to, if neither of the previous are given.
> For the pattern string syntax, refer to the following documentation: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns.
> ```

probably should use a format like link:https://vaadin.com/pro/licenses[vaadin.com/pro/licenses]

---

*[documentation/components/components-grid.asciidoc, line 581 at r4](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgOEJK_I_5DNKjVymsi:-KgOEJK_I_5DNKjVymsj:b-hoq7qk) ([raw file](https://github.com/vaadin/framework/blob/67432ada4942e0cbe0ae86d79dabb2154e5db368/documentation/components/components-grid.asciidoc#L581)):*
> ```AsciiDoc
> }, new ComponentRenderer());
> ----
> +
> ```

(is this change related?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by ahie** [comment]
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 491 at r4](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgODa51sZP6TC0Kci6y:-KgOXKeuyQ0lkl-3GmxL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/67432ada4942e0cbe0ae86d79dabb2154e5db368/documentation/components/components-grid.asciidoc#L491)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

probably should use a format like link:https://vaadin.com/pro/licenses[vaadin.com/pro/licenses]
</blockquote></details>

Done.

---

*[documentation/components/components-grid.asciidoc, line 581 at r4](https://reviewable.io:443/reviews/vaadin/framework/8955#-KgOEJK_I_5DNKjVymsi:-KgOXLbHwqCWkqnl1fBS:b-vomky7) ([raw file](https://github.com/vaadin/framework/blob/67432ada4942e0cbe0ae86d79dabb2154e5db368/documentation/components/components-grid.asciidoc#L581)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(is this change related?)
</blockquote></details>

The formatting was broken here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8955)*

**Pull request merged**
