### PR TITLE
Add ARIA label support to DateField

### LINKED ISSUE #10454: DateField Popup: Header Buttons dont have aria-labels
Buttons (e.g. prev month/year, next month/year) in the Popup from DateField don't have aria-labels.
Their functionalities are therefore unknown for screenreaders like JAWS or NVDA

datefield-buttons

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #10454

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10538)

### CODE REVIEW

**Comment by knoobie** [comment]
@wbadam Please ping me after this is deployed on vaadin.com/sampler - I can give you feedback from a sightless user if you want.

**Comment by elmot** [comment]
Reviewed 2 of 6 files at r7.
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1348 at r9](https://reviewable.io:443/reviews/vaadin/framework/10538#-L46-8FyPvA9QxghKCyP:-L46-8FyPvA9QxghKCyQ:b-2bgobe) ([raw file](https://github.com/vaadin/framework/blob/fc9bf9fc3bc5e7683fcc79059250a0b5f206a243/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1348)):*
> ```Java
>             return true;
> 
>         } else if (keycode == getCloseKey() || keycode == KeyCodes.KEY_TAB) {
> ```

Behavior change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538)*

**Comment by elmot** [comment]
Reviewed 3 of 6 files at r7, 1 of 2 files at r8, 1 of 1 files at r9.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538)*

**Comment by wbadam** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 1348 at r9](https://reviewable.io:443/reviews/vaadin/framework/10538#-L46-8FyPvA9QxghKCyP:-L466gNqdq0sjnHwENxD:b-62s8mx) ([raw file](https://github.com/vaadin/framework/blob/fc9bf9fc3bc5e7683fcc79059250a0b5f206a243/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L1348)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Behavior change?
</blockquote></details>

Definitely. The component used to trap focus, in my opinion TAB should move focus to the next element as with other modes and globally all elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538#-:-L4AWu0FDkvP-LVDo6jS:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538)*

**Comment by elmot** [comment]
Reviewed 1 of 6 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10538)*

**Pull request merged**
