### PR TITLE
Space key on MultiSelectionRenderer combobox selects grid row

### LINKED ISSUE #10221: Grid Multiselect Checkbox won't trigger with key 'space'
Currently it's not possible to select a row in a grid with the keyboard while focusing the checkbox that should trigger the select. 

Workflow: 

- Create a simple Grid and enable MULTISELECT
- Open Grid UI
- Tab til you reach a checkbox to select a row (select all checkbox works with space!)
- Press 'space'

Expected behaviour:  checkbox is checked / row selected
Current behaviour:  checkbox won't be checked / row not selected

### PR DESCRIPTION
**Pull request by mcollovati**
Adds a key up handler on MultiSelectionRenderer checkbox
in order to allow row selection pressing space key

Fixes #10221

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10388)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Suggesting to re-use existing test UI for this. If you're busy and can't migrate the test, we can go with this.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/10388#-L-BT_CmbK5B30ZQP5Kt:-L-BT_CmbK5B30ZQP5Ku:b-g0myc1) ([raw file](https://github.com/vaadin/framework/blob/f13eebe2c7d45886f24217e55e314684d1fe7ed1/uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java#L7)):*
> ```Java
> import com.vaadin.ui.Grid;
> 
> public class GridMultiselectSelectWithSpaceKey extends AbstractTestUI {
> ```

Instead of making a whole new test class for this, you could extend the existing tests in GridSelectionTest. It already contains helper methods for testing selection.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKeyTest.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/10388#-L-BSit6eYN-PIeKyXJR:-L-BSit6eYN-PIeKyXJS:b-v3yirr) ([raw file](https://github.com/vaadin/framework/blob/f13eebe2c7d45886f24217e55e314684d1fe7ed1/uitest/src/test/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKeyTest.java#L42)):*
> ```Java
>         for (int row : rows) {
>             boolean isRowSelected = grid.getRow(row).isSelected();
>             if (selected) {
> ```

This whole if block could be replaced by `assertEquals("<enter good message here>", selected, grid.getRow(row).isSelected());`

I guess the good message is a bit tricky to come up with though.. Can live without the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388#-:-L-BVXqaQ7FWuA369VFH:bnnpv14)*

**Comment by mcollovati** [comment]
I can migrate the test during this weekend but feel free to do it on your own if you think it's better

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388#-:-L-GMgnu5177kQDp0SiA:b-fk4iap)*

**Comment by mcollovati** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/10388#-L-BT_CmbK5B30ZQP5Kt:-L-IaLPPBp_vi-SFDwWp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f13eebe2c7d45886f24217e55e314684d1fe7ed1/uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java#L7)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Instead of making a whole new test class for this, you could extend the existing tests in GridSelectionTest. It already contains helper methods for testing selection.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388)*

**Comment by mcollovati** [comment]
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKeyTest.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/10388#-L-BSit6eYN-PIeKyXJR:-L-IaNsU9Z-pGmMgbZnB:bmhr8va) ([raw file](https://github.com/vaadin/framework/blob/f13eebe2c7d45886f24217e55e314684d1fe7ed1/uitest/src/test/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKeyTest.java#L42)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This whole if block could be replaced by `assertEquals("<enter good message here>", selected, grid.getRow(row).isSelected());`

I guess the good message is a bit tricky to come up with though.. Can live without the change.
</blockquote></details>

Replaced with existing assertion present in GridSelectionTest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388)*

**Comment by mcollovati** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/10388#-L-BT_CmbK5B30ZQP5Kt:-L-IakPHRYBEzrhvRJih:b1affro) ([raw file](https://github.com/vaadin/framework/blob/f13eebe2c7d45886f24217e55e314684d1fe7ed1/uitest/src/main/java/com/vaadin/tests/components/grid/GridMultiselectSelectWithSpaceKey.java#L7)):*
<details><summary><i>Previously, mcollovati (Marco Collovati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Moved test into GridSelectionTest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388)*

**Comment by knoobie** [comment]
Would it be possible to see this in 8.2 as well? The grid related patchnotes and this complement one another really well.

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10388)*

**Pull request merged**
