### PR TITLE
reopen Grid details on attach, fixes #8015

### LINKED ISSUE #8015: Adding Caption on or hiding Layout above Grid removes Grid Details
Vaadin version: 7.7.6
Scenario: a Grid with a DetailsGenerator placed on a VerticalLayout on a parent VerticalLayout. The parent layout also contains other child Layouts before the Grid. The Details element of one of the Grid's rows has been expanded. 

If you now do one of the following:
* Add a caption to the VerticalLayout that contains the Grid
* Add a caption to the parent VerticalLayout or a Layout that's above the Grid
* Set the visibility of a Layout that's above the grid to false

then the Details element is removed from the Grid. It's even removed from the DOM. 

You can get the Details element visible again by 
```java
grid.setDetailsVisible(itemId, false);
grid.setDetailsVisible(itemId, true);
```

Test project:
[grid-details-test.zip](https://github.com/vaadin/framework/files/656735/grid-details-test.zip)

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Fix for https://github.com/vaadin/framework/issues/8015 : keep track of grid Details that are closed on detach and reopen them on attach. After the fix, changing layouts above the Grid won't cause details to collapse automatically.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8074)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_VaepGyS0_SVRCYFO:-KZ_VaepGyS0_SVRCYFP:bl59bu9) (no related file):*
No test ?
Is it possible to test ?

If I remember correctly you mentioned some test in our discussion in flowdock.
Could you please add it ?

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8768 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_Ue-7n3VUTibfV19-:-KZ_Ue-7n3VUTibfV190:bbsq2kg) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8768)):*
> ```Java
>         // Grid was just attached to DOM. Column widths should be calculated.
>         recalculateColumnWidths();
>         Set<Integer> details = new HashSet<Integer>(reattachVisibleDetails);
> ```

Why ?
What's the reason to make a copy here ?

Navigation through the original `reattachVisibleDetails` should work fine here.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8772 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_UzVrW_K-PRCYdmg2:-KZ_UzVsIckaOKb8tBup:b-o1anno) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8772)):*
> ```Java
>             setDetailsVisible(row, true);
>         }
>         reattachVisibleDetails = new HashSet<Integer>();
> ```

Can just clean `reattachVisibleDetails`. 
But it doesn't matter. (Though would allow to make `reattachVisibleDetails` final).

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8778 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_VPDOaI7kxB-_XMC9:-KZ_VPDOaI7kxB-_XMCA:bir6ily) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8778)):*
> ```Java
>     protected void onDetach() {
>         Set<Integer> details = new HashSet<Integer>(visibleDetails);
>         reattachVisibleDetails.addAll(details);
> ```

A question: should be here as well either a cleanup of the `reattachVisibleDetails` or an assertion that it's empty ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8074)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_VaepGyS0_SVRCYFO:-KZ_WhnPCMEidiNP9iY9:br3xjxe) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

No test ?
Is it possible to test ?

If I remember correctly you mentioned some test in our discussion in flowdock.
Could you please add it ?
</blockquote></details>

Yes, I'll see if I can add that, should be possible.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8772 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_UzVrW_K-PRCYdmg2:-KZ_X7zsm7bqTBE-NxkH:b-l4nieg) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8772)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Can just clean `reattachVisibleDetails`. 
But it doesn't matter. (Though would allow to make `reattachVisibleDetails` final).
</blockquote></details>

Using final is good, I'll do that.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8778 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_VPDOaI7kxB-_XMC9:-KZ_XPbvwV2c9T0dtoP4:b-16721f) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8778)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

A question: should be here as well either a cleanup of the `reattachVisibleDetails` or an assertion that it's empty ?
</blockquote></details>

I'll add an extra cleanup step here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8074)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8772 at r1](https://reviewable.io:443/reviews/vaadin/framework/8074#-KZ_UzVrW_K-PRCYdmg2:-K_hTB7X9zyxACSzBkyu:b-6n5n1t) ([raw file](https://github.com/vaadin/framework/blob/d8e54dcba3bd6606ba0ca857d3d46666a06f1b85/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8772)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

Using final is good, I'll do that.
</blockquote></details>

A note for the future: please mark the comments in the Reviewable as "Done" so that I can see what's resolved, what's not.
It's easier for a reviewer to acknowledge (and resolve) the comments and see what remains. 

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsReattach.java, line 8 at r2](https://reviewable.io:443/reviews/vaadin/framework/8074#-K_hTyWXnTXY734QCxPB:-K_hTyWXnTXY734QCxPC:b-f11w2h) ([raw file](https://github.com/vaadin/framework/blob/13e981d5a3b64beb317cf84c0d3073997b2a8747/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsReattach.java#L8)):*
> ```Java
> import org.apache.tools.ant.taskdefs.Java;
> 
> public class GridDetailsReattach extends UI {
> ```

Please use`AbstractTestUI`.

You will need ti implement `setup` method then.
And there you already have a root layout. No need to create and set it. Just use `addComponent` method available for `AbstractTestUI`.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsReattach.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/framework/8074#-K_hVhNgJYLDTTTRcJE_:-K_hVhNhBzZCAOa7DADn:bxczz11) ([raw file](https://github.com/vaadin/framework/blob/13e981d5a3b64beb317cf84c0d3073997b2a8747/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsReattach.java#L41)):*
> ```Java
>             @Override
>             public void buttonClick(Button.ClickEvent event) {
>                 layoutWithGrid.setCaption("Caption added to 'layoutWithGrid' layout");
> ```

So this detaches and reattaches the details on the client side , right ?
Not obvious from the code.
(just to be sure: this doesn't work without your patch , right ?)

Please add a comment here that this action has an impact on the client side (which exactly).

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridDetailsReattachTest.java, line 17 at r2](https://reviewable.io:443/reviews/vaadin/framework/8074#-K_hUeOXhys_666Jqhf9:-K_hUeOXhys_666JqhfA:b9hdqhv) ([raw file](https://github.com/vaadin/framework/blob/13e981d5a3b64beb317cf84c0d3073997b2a8747/uitest/src/test/java/com/vaadin/tests/components/grid/GridDetailsReattachTest.java#L17)):*
> ```Java
>     @Before
>     public void setUp() {
>         setDebug(true);
> ```

Can be set directly inside the test method (no need to do anything here in this PR, it's just a note for you).
This is useful when you have several test methods which need the same initialization.
And usually in those cases ` openTestURL();` is also here.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridDetailsReattachTest.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/framework/8074#-K_hUO1iMvZJcGjn7xxm:-K_hUO1jS7P84rqy_041:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/13e981d5a3b64beb317cf84c0d3073997b2a8747/uitest/src/test/java/com/vaadin/tests/components/grid/GridDetailsReattachTest.java#L34)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8074)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8074)*

**Pull request merged**
