### PR TITLE
Fix column width resize event firing when mode is SIMPLE

### LINKED ISSUE #10139: Grid ColumnResizeListener - old column width reported to server
Hi,

I'm using Vaadin Version 8.1.5 and stumbled upon a quite strange behaviour:

I have a grid and added a `ColumnResizeListener`. Within the listener on `columnResize` I need to get the new size of the column.
The problem now is, that according to the client side logs, the OLD width is reported to the server so when I call `getWidth` on the affected column I always get the previous width 

> INFO: Sending push (websocket) message to server: {"csrfToken":"...","rpc":[["476","com.vaadin.shared.ui.grid.GridServerRpc","columnResized",["0",**48**]]],"syncId":18,"clientId":18}

In this case **48** is the initial size (before the resize)

I also checked the docs for `GridServerRpc.columnResized` and it says

>    @param pixels
>                the new width of the column in pixels

 I tried with Chrome and Firefox and the results are the same

Any ideas what may cause this issue? (and how to make it work as it should)

Thanks a lot
Kind Regards
Florian

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #10139

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10442)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 5927 at r1](https://reviewable.io:443/reviews/vaadin/framework/10442#-L0KGrgfSRv2Zsrn9Qhv:-L0KGrgfSRv2Zsrn9Qhw:b-tf95su) ([raw file](https://github.com/vaadin/framework/blob/c299ab1641ef431dc3f46e9a08f3d3d0964740d8/client/src/main/java/com/vaadin/client/widgets/Grid.java#L5927)):*
> ```Java
>                             // scheduled by setWidth() before firing the event
>                             Scheduler.get().scheduleDeferred(() -> fireEvent(
>                                     new ColumnResizeEvent<>(col)));
> ```

Another solution would be to pass `column.getWidth()` instead of `getWidthActual()` to the RPC in grid's column resize handler but I haven't studied whether that would have negative effects. https://github.com/wbadam/framework/blob/sr-2387/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L299

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10442#-L2Q2BTj7OcdVBNH4P8O:-L2Q2BTj7OcdVBNH4P8P:br6imwd) (no related file):*
Should this fix be also included in the compatibility package? Was something related to this already merged in 7.7?

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/10442#-L2Q2ey42Ny77iBTow-a:-L2Q2ey42Ny77iBTow-b:b8i2y2) ([raw file](https://github.com/vaadin/framework/blob/2b57a61cfeb81a596dea68e076aba103c7f4bdd2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L102)):*
> ```Java
>         drag(handle, 100);
>         sleep(500);
>         Assert.assertEquals(initialWidth + 100, cell.getSize().getWidth());
> ```

Should the test also follow some logging from the events to see that the reported values are correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10442#-L2Q2BTj7OcdVBNH4P8O:-L2QPceNGlA7xI0oZgyF:ba5981r) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should this fix be also included in the compatibility package? Was something related to this already merged in 7.7?
</blockquote></details>

This was cherry picked and merged to 7.7 in https://github.com/vaadin/framework/pull/10452

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/10442#-L2Q2ey42Ny77iBTow-a:-L2QRPhFb2Hzedbiej5S:b30jcnz) ([raw file](https://github.com/vaadin/framework/blob/2b57a61cfeb81a596dea68e076aba103c7f4bdd2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L102)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should the test also follow some logging from the events to see that the reported values are correct?
</blockquote></details>

Perhaps, although correct width indicate that the reported values are correct.
How would you go about logging these events?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by wbadam** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/10442#-L2Q2ey42Ny77iBTow-a:-L2unhSX4q1KoGMeUVyz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2b57a61cfeb81a596dea68e076aba103c7f4bdd2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L102)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Add a menu entry that adds the resize listener that reports the given sizes with `log(String)`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/10442#-L38VEyPD1xIDP5Y8RwF:-L38VEyPD1xIDP5Y8RwG:b8274ah) ([raw file](https://github.com/vaadin/framework/blob/277bd4c74401746d3005c5a79ccd709b79e083a2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L112)):*
> ```Java
> 
>         selectMenuPath("Component", "Columns", "Add resize listener");
>         sleep(250);
> ```

Why is the sleep needed?

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 150 at r2](https://reviewable.io:443/reviews/vaadin/framework/10442#-L38VOEWm3c0R8LOH5D3:-L38VOEXz8-eDfqFYZfy:b-reevfr) ([raw file](https://github.com/vaadin/framework/blob/277bd4c74401746d3005c5a79ccd709b79e083a2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L150)):*
> ```Java
>                 .moveByOffset(20, 0).moveByOffset(xOffset - 20, 0).release()
>                 .perform();
>         sleep(250);
> ```

why is the sleep needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by wbadam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 112 at r2](https://reviewable.io:443/reviews/vaadin/framework/10442#-L38VEyPD1xIDP5Y8RwF:-L3AeX9Rr8CzP9G3MNcy:b-ccio17) ([raw file](https://github.com/vaadin/framework/blob/277bd4c74401746d3005c5a79ccd709b79e083a2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L112)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is the sleep needed?
</blockquote></details>

Copied that from an existing test, doesn't seem to be needed.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java, line 150 at r2](https://reviewable.io:443/reviews/vaadin/framework/10442#-L38VOEWm3c0R8LOH5D3:-L3AfqB2jW8Gfu6hRKXf:bjedwqg) ([raw file](https://github.com/vaadin/framework/blob/277bd4c74401746d3005c5a79ccd709b79e083a2/uitest/src/test/java/com/vaadin/tests/components/grid/basicfeatures/GridColumnResizeModeTest.java#L150)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why is the sleep needed?
</blockquote></details>

Without sleep, the column widths don't always seem to be updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10442)*

**Pull request merged**
