### PR TITLE
Cherry pick changes for 8.0.5 from master

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8969)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8969#-KgOGgsfrEZSN6bcEe-8:-KgOGgsfrEZSN6bcEe-9:b-nrywm) (no related file):*
Blocking for running APIDIFF and pending and tag updates

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8969)*

**Comment by hesara** [comment]
Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8969#-KgOGgsfrEZSN6bcEe-8:-KgOKJTpLtGNDFKXfWhM:bh55gmu) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Blocking for running APIDIFF and pending and tag updates
</blockquote></details>

LGTM assuming API diff does not surface problems

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8969)*

**Comment by pleku** [comment]
Review status: 27 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8969#-KgOGgsfrEZSN6bcEe-8:-KgT9AiqoZzfQ8ELaEjc:bnd7rc2) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

LGTM assuming API diff does not surface problems
</blockquote></details>

No APIDiff issues, added missing since tags

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8969)*

**Comment by hesara** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8969)*

**Pull request merged**
