### PR TITLE
Document BeanValidationBinder and RequiredFieldConfigurator.

### LINKED ISSUE #8390: Update documentation in case #8253 is preserved
The fix for #8253 is integrated.
There is a discussion to revert it.
If it's preserved then documentation should be update to mention how to use BeanValidationBinder with JSR 303.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This patch also provides a documentation for #8382.

Fixes #8390

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8504)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 446 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSU37Dv9nXjDC5o859:-KcSU37Dv9nXjDC5o85A:b-9o1q61) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L446)):*
> ```AsciiDoc
> want to use JSR 303 Bean Validation annotations then a [classname]#BeanValidationBinder# should be used.
> [classname]#BeanValidationBinder# extends [classname]#Binder# class so it has the same API but its implementation 
> automatically adds a bean validator which takes care about JSR 303 constraints.
> ```

... takes care of ... (https://forum.wordreference.com/threads/take-care-of-take-care-about.1499328/)

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 477 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSTDyy8XeyRTrwJQvs:-KcSTDyzFNJl8zzOfxyS:b-uzqj99) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L477)):*
> ```AsciiDoc
> Constraint annotations can also be defined on the bean level instead of being defined for any specific property.
> 
> There are some number of predefined constraint annotations that mark a bound field required using 
> ```

... as required ... (easier to read)

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 481 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSU-xqVhrHtkfGSl0Y:-KcSU-xqVhrHtkfGSl0Z:bq6tx3d) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L481)):*
> ```AsciiDoc
> [classname]#@NotEmpty# and [classname]#@Size# (if [methodname]#min()# value is greater than 0) 
> configures the field as required. It's possible to change this behavior using 
> the [classname]#BeanValidationBinder#.[methodname]#setRequiredConfigurator# method.
> ```

method not in master?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8504)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 446 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSU37Dv9nXjDC5o859:-KcSUxC2z81t71Ki_wFY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L446)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... takes care of ... (https://forum.wordreference.com/threads/take-care-of-take-care-about.1499328/)
</blockquote></details>

Done.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 477 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSTDyy8XeyRTrwJQvs:-KcSV0_3AxcdhhhYgWZS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L477)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... as required ... (easier to read)
</blockquote></details>

Done.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 481 at r1](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSU-xqVhrHtkfGSl0Y:-KcSV7_Fd0lYYzzKyLue:b80vqlx) ([raw file](https://github.com/vaadin/framework/blob/60d5c2cbcd11b6d3bfdb0bcd77733e9fd636658e/documentation/datamodel/datamodel-forms.asciidoc#L481)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

method not in master?
</blockquote></details>

Should be merged once someone approves it.
https://github.com/vaadin/framework/issues/8460

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8504)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8504)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8504#-KcSW7dL7gtAMeJYLVkg:-KcSW7dM5sjQ7EjB_c1n:bltl5nz) (no related file):*
depends on #8460 - ok to merge after it has been merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8504)*

**Pull request merged**
