### PR TITLE
set default ContentMode PREFORMATTED for tooltipInfo - fixes #10264

### LINKED ISSUE #10264: If TooltipInfo is created with default constructor, ContentType is not set and client side exception will occur.
If TooltipInfo is created with default constructor, ContentType is not set and client side exception will occur.

VTooltip.setTooltipText does not have null pointer check for missing content type.

And for example CalendarConnector.java has method getTooltTip which uses GWT.create to create TooltipInfo (i.e. default constructor)

```java
    @Override
    public TooltipInfo getTooltipInfo(
            com.google.gwt.dom.client.Element element) {
        TooltipInfo tooltipInfo = null;
        Widget w = WidgetUtil.findWidget(element, null);
        if (w instanceof HasTooltipKey) {
            tooltipInfo = GWT.create(TooltipInfo.class);
            String title = tooltips.get(((HasTooltipKey) w).getTooltipKey());
            tooltipInfo.setTitle(title != null ? title : "");
        }
        if (tooltipInfo == null) {
            tooltipInfo = super.getTooltipInfo(element);
        }
        return tooltipInfo;
    }
```

Thus e.g. following exception can occur.

Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'java_lang_Enum_ordinal' of undefined
    at Unknown.com_vaadin_client_VTooltip_$setTooltipText__Lcom_vaadin_client_VTooltip_2Lcom_vaadin_client_TooltipInfo_2V(com.ideas.calendar.customcalendar.demo.DemoWidgetSet-0.js)
    at Unknown.com_vaadin_client_VTooltip$TooltipEventHandler_$handleShowHide__Lcom_vaadin_client_VTooltip$TooltipEventHandler_2Lcom_google_gwt_event_dom_client_DomEvent_2ZV(com.ideas.calendar.customcalendar.demo.DemoWidgetSet-0.js)
    at Unknown.com_vaadin_client_VTooltip$TooltipEventHandler_onMouseMove__Lcom_google_gwt_event_dom_client_MouseMoveEvent_2V(com.ideas.calendar.customcalendar.demo.DemoWidgetSet-0.js)

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
set default ContentMode PREFORMATTED in parameterless TooltipInfo constructor, fixes undefined enum value access in `VTooltip.setTooltipText`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10263)

### CODE REVIEW

**Comment by OlliTietavainenVaadin** [comment]
Client side exception trying to access the TooltipInfo's ContentMode in a switch statement when it has not been defined:
```
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'java_lang_Enum_ordinal' of undefined
    at Unknown.com_vaadin_client_VTooltip_$setTooltipText__Lcom_vaadin_client_VTooltip_2Lcom_vaadin_client_TooltipInfo_2V
```

**Comment by OlliTietavainenVaadin** [comment]
Related issue: https://github.com/vaadin/framework/issues/10264

**Comment by tsuoanttila** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10263#-:-Ky0KDXNtndZE95tumaS:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10263)*

**Pull request merged**
