### PR TITLE
Improve caching when expanding nodes in hierarchical data

### LINKED ISSUE #8790: Avoid fetching extra items when expanding TreeGrid nodes
Should be possible to immediately do `rpc.setData(index, array)` after `insertRows(startIndex, length)`.

Need to 
a) calculate the proper amount of rows to push to client, the cache side and currently shown range is visible
b) make sure the client side doesn't request any extra stuff, like currently it requests the inserted rows and some buffer on top of that

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #8790

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8902)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 187 at r1](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpEXKOndLB1YGGqZyM:-KfpEXKOndLB1YGGqZyN:bf2lnsj) ([raw file](https://github.com/vaadin/framework/blob/ebd11a75af2604100a252e6f3ac26e7462119141/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L187)):*
> ```Java
>      * This is the cache portion that was moved due to rows being added. When
>      * the client receives more data from the server, it will check if this
>      * cache now fits into the continuous range of rows. If yes, it will added
> ```

"it will added"?
Also, perhaps the whole comment could perhaps be more explicit about the lifetime of this map etc. and the name "invalidCache" might give the wrong impression about what this is about.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpDkirmyNA5mftM98W:-KfpDkirmyNA5mftM98X:b-rexb0c) ([raw file](https://github.com/vaadin/framework/blob/ebd11a75af2604100a252e6f3ac26e7462119141/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java#L12)):*
> ```Java
> import com.vaadin.tests.tb3.SingleBrowserTest;
> 
> @RunLocally(Browser.PHANTOMJS)
> ```

remove RunLocally

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpE7qPnF2-Lch8RtLz:-KfpE7qPnF2-Lch8RtM-:b-w3yujl) ([raw file](https://github.com/vaadin/framework/blob/ebd11a75af2604100a252e6f3ac26e7462119141/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java#L50)):*
> ```Java
>         grid.expandWithClick(0);
>         Assert.assertFalse(
>                 "Log should not contain request for children of '0 | 1'.",
> ```

pipe character not what the UI puts there (uses semicolon) so this test would always return false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by hesara** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 570 at r1](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpcddbRjgtNr2_dA-v:-KfpcddbRjgtNr2_dA-w:b-ncw7m1) ([raw file](https://github.com/vaadin/framework/blob/ebd11a75af2604100a252e6f3ac26e7462119141/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L570)):*
> ```Java
> 
>         if (invalidCache.containsKey(potentialCache.getStart() - 1)) {
>             // Invalid cache is contains a key it should not.
> ```

"is contains"? Also, not clear to me why this is a case where "invalidCache" is invalid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by hesara** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 192 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-Kfpm0gLGcM0YPwygckv:-Kfpm0gLGcM0YPwygckw:b-w5vy4d) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L192)):*
> ```Java
>      * <p>
>      * Subsequent calls to row data insertions clears the map to avoid potential
>      * issues with weird ordering of data updates.
> ```

could still add mention about null vs. empty map, and a mention that the keys of this map have already been adjusted for the insertion

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 714 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpmkawfEl44e6gRP-w:-KfpmkawfEl44e6gRP-x:biq4gci) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L714)):*
> ```Java
>             Range invalid = splitAt[1];
> 
>             if (!invalid.isEmpty() && invalidatedRows == null) {
> ```

what if invalidatedRows is an empty map at this point?

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 386 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpnW3ucODE0GYFlnVN:-KfpnW3ucODE0GYFlnVO:b-4ucsqd) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L386)):*
> ```Java
>         getClientRpc().insertRows(expandedRowIndex + 1, expandedNodeSize);
>         // TODO optimize by sending "just enough" of the expanded items directly
>         doPushRows(Range.withLength(expandedRowIndex + 1, expandedNodeSize));
> ```

(not reseting pushRows - I assume this is intentional, but is this always correct?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 714 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpmkawfEl44e6gRP-w:-KfqFuHWWrTiWv-Fvx5E:b8kjves) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L714)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

what if invalidatedRows is an empty map at this point?
</blockquote></details>

That basically means that instead of ARDS getting the data push it got more row changes. Technically, we could still attempt to track the invalidated row indices, but in my opinion that's just too risky. 

The promise is simple "if you add and immediately push the new rows, we're going to deal with it". Any other case goes through cache coverage check and request to the server.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java, line 386 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpnW3ucODE0GYFlnVN:-KfqGJfc_UTOQGyhKBcd:b-oplam4) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/server/src/main/java/com/vaadin/data/provider/HierarchicalDataCommunicator.java#L386)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not reseting pushRows - I assume this is intentional, but is this always correct?)
</blockquote></details>

this is only about pushing expanded rows now (and this has a potential issue with changing the columns of grid in expand listener), any other requests will be handled as normally.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpE7qPnF2-Lch8RtLz:-KfpIz2V28PG9gluSA9q:b42e9zg) ([raw file](https://github.com/vaadin/framework/blob/ebd11a75af2604100a252e6f3ac26e7462119141/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridExpandDataRequestTest.java#L50)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

pipe character not what the UI puts there (uses semicolon) so this test would always return false
</blockquote></details>

The pipe in this case comes from the item, not the UI logging output (I did run the tests before applying the client-side change to make sure that this did indeed fail before). I used semicolon in logging on purpose to make clearer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 714 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpmkawfEl44e6gRP-w:-KfqJEzIEUOps1RNR51W:be5vxyc) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L714)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

That basically means that instead of ARDS getting the data push it got more row changes. Technically, we could still attempt to track the invalidated row indices, but in my opinion that's just too risky. 

The promise is simple "if you add and immediately push the new rows, we're going to deal with it". Any other case goes through cache coverage check and request to the server.
</blockquote></details>

this could be made clear to the next reader in the form of comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by tsuoanttila** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 192 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-Kfpm0gLGcM0YPwygckv:-KfvPBt80fQAMDA8C5JZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L192)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could still add mention about null vs. empty map, and a mention that the keys of this map have already been adjusted for the insertion
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 714 at r2](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfpmkawfEl44e6gRP-w:-KfvPDN3lrHTkL6Pptt5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e1fb911204452ebe6e0edb0f8365d9dae4487666/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L714)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this could be made clear to the next reader in the form of comments
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by hesara** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java, line 602 at r4](https://reviewable.io:443/reviews/vaadin/framework/8902#-KfzAXpLQKBlHTsxDQR6:-KfzAXpLQKBlHTsxDQR7:beqjmjh) ([raw file](https://github.com/vaadin/framework/blob/b983e2e643250f7d7b7eb96db21d7d98bfff140b/client/src/main/java/com/vaadin/client/data/AbstractRemoteDataSource.java#L602)):*
> ```Java
>             invalidatedRows = null;
>         } finally {
>             // Update cachce range and clean up
> ```

"cache"

---

*[uitest/src/test/java/com/vaadin/tests/applicationcontext/CloseSessionTest.java, line 9 at r4](https://reviewable.io:443/reviews/vaadin/framework/8902#-Kfz8JflvXlAThdoFfbO:-Kfz8JflvXlAThdoFfbP:bzem2d0) ([raw file](https://github.com/vaadin/framework/blob/b983e2e643250f7d7b7eb96db21d7d98bfff140b/uitest/src/test/java/com/vaadin/tests/applicationcontext/CloseSessionTest.java#L9)):*
> ```Java
> import com.vaadin.testbench.elements.ButtonElement;
> import com.vaadin.testbench.elements.NotificationElement;
> import com.vaadin.testbench.elements.UIElement;
> ```

(good but unrelated changes - should probably be in a separate PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8902)*

**Pull request merged**
