### PR TITLE
Update framework to use jetty-server 9.4

### PR DESCRIPTION
**Pull request by ZheSun88**
Update jetty version used in framework in order to eliminate the security alert;
Let the `FileUploaderHandler` drop the variables when the uploading is interrupted.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11272)

### CODE REVIEW

**Comment by ZheSun88** [comment]
needs to run a few more times, because the comment mentions `sometimes`

**Review by elmot — APPROVED** [review]
Please run websockets tests over the change. I remember some troubles with them

> Reviewed 1 of 1 files at r4, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11272#-:-LQd53TS0Lc9nDc5CfBk:ba7nhw2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZheSun88)

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11272)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11272#-LQd6T7y8daAdCiWFU71:-LQd6T7y8daAdCiWFU72:bowjeif) (no related file):*
Waiting for results from https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFramework_VaadinFramework87_Testing_TestIntegrationAndServers

---

**Review by elmot — APPROVED** [review]
:lgtm: if  the tests pass

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11272#-:-LQdENDL8JbmUUjY68rH:bblynwr)* status: all files reviewed, 1 unresolved discussion

**Review by elmot — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11272)* status: all files reviewed, 1 unresolved discussion

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11272)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11272#-LQd6T7y8daAdCiWFU71:-LQdEmirEHbVTV6upKw2:b59kmi5) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Waiting for results from https://bender.vaadin.com/viewType.html?buildTypeId=VaadinFramework_VaadinFramework87_Testing_TestIntegrationAndServers
</blockquote></details>

Test passed https://bender.vaadin.com/viewLog.html?buildId=32616&tab=buildResultsDiv&buildTypeId=VaadinFramework_VaadinFramework87_Testing_TestIntegrationAndServers @elmot 

---

**Pull request merged**
