### PR TITLE
Add selection methods to grid that delegate to its selection model

### PR DESCRIPTION
**Pull request by ahie**
Closes vaadin/framework8-issues#577

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8315)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF-HyMUvv4VsQbxc24:-KbF-HyMUvv4VsQbxc25:b-psja5t) (no related file):*
I'm not sure that original changes in this PR make sense.
The issues says:

Add
```
void select(T item) { getSelectionModel().select(item); }
```
and
```
Set<T> getSelected() { return getSelectionModel().get...; }
```

But a lot of additional methods are added into the `Grid`.
As a result we are duplicating SelectionModel interface which is not good.
The main idea was to have very simple methods to do something with the `Grid` without `SelectionModel` concept.
But if you need to do something advanced then you should use `SelectionModel`.
Merging everything into one class reduces important methods discoverability.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridDelegatesToSelectionModelTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF0n2PRSZUA12JhTHv:-KbF0n2PRSZUA12JhTHw:bj3unzp) ([raw file](https://github.com/vaadin/framework/blob/f2f10f8ebaffeb05fd196b6a893b7bc981364f36/server/src/test/java/com/vaadin/tests/components/grid/GridDelegatesToSelectionModelTest.java#L27)):*
> ```Java
> 
>     @Test
>     public void grid_delegates_selection_methods_to_SelectionModel() {
> ```

The test is not accurate: it does a lot of things before a check.
You can't be sure that the result is the consequence of the method that you check.

There should be a number of test methods that avoid any interference effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by ahie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF-HyMUvv4VsQbxc24:-KbF2FZZ25B6vsUXJsfk:b-ct6svl) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I'm not sure that original changes in this PR make sense.
The issues says:

Add
```
void select(T item) { getSelectionModel().select(item); }
```
and
```
Set<T> getSelected() { return getSelectionModel().get...; }
```

But a lot of additional methods are added into the `Grid`.
As a result we are duplicating SelectionModel interface which is not good.
The main idea was to have very simple methods to do something with the `Grid` without `SelectionModel` concept.
But if you need to do something advanced then you should use `SelectionModel`.
Merging everything into one class reduces important methods discoverability.
</blockquote></details>

Added the rest of the methods for discussion here. It feels weird to only have `select` and not for example `deselect`.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridDelegatesToSelectionModelTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF0n2PRSZUA12JhTHv:-KbF5IxWKC-3uM3mk8l-:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/f2f10f8ebaffeb05fd196b6a893b7bc981364f36/server/src/test/java/com/vaadin/tests/components/grid/GridDelegatesToSelectionModelTest.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The test is not accurate: it does a lot of things before a check.
You can't be sure that the result is the consequence of the method that you check.

There should be a number of test methods that avoid any interference effect.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF-HyMUvv4VsQbxc24:-KbF6VOtgpEM-2xByFpq:b-5zkcc6) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Added the rest of the methods for discussion here. It feels weird to only have `select` and not for example `deselect`.
</blockquote></details>

Also, the old grid has an equivalent for all these added methods. Difference being the naming of `getFirstSelected` and `getSelectedItems` being `getSelectedRow` and `getSelectedRows`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF-HyMUvv4VsQbxc24:-KbJV5MOcg1965XOeo_b:bi8fmsj) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Also, the old grid has an equivalent for all these added methods. Difference being the naming of `getFirstSelected` and `getSelectedItems` being `getSelectedRow` and `getSelectedRows`.
</blockquote></details>

I agree that not having deselect and only select would be strange.
The only ones that I wouldn't actually expect to be available are `getFirstSelected` and `isSelected`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8315#-KbF-HyMUvv4VsQbxc24:-Kc1vU3c9DaCRQj2ULpK:b-ix2hxi) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

I agree that not having deselect and only select would be strange.
The only ones that I wouldn't actually expect to be available are `getFirstSelected` and `isSelected`.

</blockquote></details>

Removed `getFirstSelected` and `isSelected`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8315#-:-Kc1xGdfEsym06nkW_12:bnfp4nl)*

**Pull request merged**
