### PR TITLE
Update and fix release notes

### PR DESCRIPTION
**Pull request by pleku**
Removed outdated parts.
Added missing parts.
Clarified Android support.
Fixed old link for dev.vaadin.com.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8001)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DQygwmGgrC8iCvUI:-KZ1DQyhu2LrdhLEuH5T:b-b9zdmw) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
> ```HTML
>         </ul>
>         <ul><h4>General API changes</h4>
>             <li>All listeners and one method interfaces have been marked as <tt>@FuntionalInterface</tt></li>
> ```

@FunctionalInterface; most but not all one method interfaces annotated (for some it doesn't make sense)

---

*[all/src/main/templates/release-notes.html, line 518 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DfTPrVbnP56Z0fS-:-KZ1DfTPrVbnP56Z0fS0:b-mzkfxh) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L518)):*
> ```HTML
>         <ul>
>             <li>iOS 9+</li>
>             <li>Chrome 42+ Android 4+</li>
> ```

... on ...?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DL_w341vmvxmUWzf:-KZ1DL_xWk1rQaKZpEWG:b-ho4lce) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L96)):*
> ```HTML
>             new API, and the old data binding API and components have been moved to separate
>             compatibility packages for ease of migration.
>             For more details, see <a href="#incompatible">list of incompatible changes</a>, and <a href="#migrating">how to migrate
> ```

the list

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DP13SONKgQuqcCBU:-KZ1DP14YL7OMoWIpt3c:br4pqnv) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
> ```HTML
>         </ul>
>         <ul><h4>General API changes</h4>
>             <li>All listeners and one method interfaces have been marked as <tt>@FuntionalInterface</tt></li>
> ```

"one-method"

Not 100% sure about this one, but without the dash, I read this as "one (method interfaces)" which doesn't make any sense.

Another option could be "single method interfaces"

---

*[all/src/main/templates/release-notes.html, line 551 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1Dnx7qGFB8ppyhfjU:-KZ1Dnx7qGFB8ppyhfjV:bdzzdcy) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L551)):*
> ```HTML
>             <li><a
>                 href="https://vaadin.com/contribute">vaadin.com/contribute - Contribution quide</a></li>
>                 
> ```

Whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DL_w341vmvxmUWzf:-KZ1ETpW5FhxW6rzP3Gm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L96)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

the list
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DP13SONKgQuqcCBU:-KZ1EoyuFbAp3uCpygz_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

"one-method"

Not 100% sure about this one, but without the dash, I read this as "one (method interfaces)" which doesn't make any sense.

Another option could be "single method interfaces"
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DQygwmGgrC8iCvUI:-KZ1Eqqgp7GttYpSuQLX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@FunctionalInterface; most but not all one method interfaces annotated (for some it doesn't make sense)
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 518 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DfTPrVbnP56Z0fS-:-KZ1H32oa9YLphFLG20P:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L518)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... on ...?
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 551 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1Dnx7qGFB8ppyhfjU:-KZ1H3ROFgrVaeoavy3K:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L551)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DQygwmGgrC8iCvUI:-KZ1IojmkZPTeCXcD2NK:b-y5hy9l) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still says FuntionalInterface (typo)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001)*

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[all/src/main/templates/release-notes.html, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/8001#-KZ1DQygwmGgrC8iCvUI:-KZ1JV3DxWdKDDDzd1og:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ddb1c7b816e1d85b9d7f08beda4fba05ab7bd74b/all/src/main/templates/release-notes.html#L138)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

still says FuntionalInterface (typo)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8001#-:-KZ1KL5yPMQlqOr0_d2l:bnfp4nl)*

**Pull request merged**
