### PR TITLE
First sentence should end with a period

### PR DESCRIPTION
**Pull request by asashour**
First sentence should end with a period

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10114)

### CODE REVIEW

**Comment by hesara** [comment]
Some minor comments. I'm ok with adding the period after incomplete sentences because it makes javadoc behave better and complain less, but adding it to a TODO or a FIXME doesn't make much sense to me.

---

Reviewed 337 of 337 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDAqePqRL13_D754O:-KvCDAqePqRL13_D754P:bnjq7l2) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/VTooltip.java#L50)):*
> ```Java
> 
> /**
>  * TODO open for extension.
> ```

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.

---

*[client/src/main/java/com/vaadin/client/ui/TreeAction.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDK2eszTb8UTYB8fw:-KvCDK2eszTb8UTYB8fx:bfnn7yc) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/TreeAction.java#L20)):*
> ```Java
> 
> /**
>  * This class is used for "row actions" in VTree and ITable.
> ```

ITable -> VScrollTable

---

*[client/src/main/java/com/vaadin/client/ui/VCssLayout.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDOSlO-y3AB9mmoNg:-KvCDOSlO-y3AB9mmoNh:b657gdz) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VCssLayout.java#L25)):*
> ```Java
> 
> /**
>  * VCCSlayout is a layout which supports configuring it's children with CSS
> ```

(wrong capitalization of VCssLayout)

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBRmY5IdB35eQEoR7U:-KvBRmY5IdB35eQEoR7V:bsonmlz) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L97)):*
> ```Java
>     public static final Command emptyCommand = null;
> 
>     /** Widget fields. **/
> ```

this shouldn't really be a javadoc comment as it applies to several fields rather than the next one.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDVExUwOyxoPWWhg4:-KvCDVExUwOyxoPWWhg5:b-1gd8f2) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L83)):*
> ```Java
> 
>     /**
>      * loading constructor.
> ```

Could also fix initial capital.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java, line 174 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDZa9b_kAUTN7K6zK:-KvCDZa9b_kAUTN7K6zL:b-zc6bol) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java#L174)):*
> ```Java
> 
>     /**
>      * TODO consider using similar smaller (than map) api as in Transferable.
> ```

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible first sentence of javadoc before the TODOs.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDlA3rXMUPDUDvjkM:-KvCDlA3rXMUPDUDvjkN:bfef7kk) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L96)):*
> ```Java
>      * from this package.
>      */
>     public native void focusCell(int rowIndex, int columnIndex)/*-{
> ```

could try to keep the formatting, or update it so that the whole JSNI comment start is on the next line so that the autoformatter handles it better

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 104 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDutaTx3HKn6d1JVN:-KvCDutaTx3HKn6d1JVO:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L104)):*
> ```Java
>      * {@link Grid#isElementInChildWidget(Element)} method from this package.
>      */
>     public native boolean isElementInChildWidget(Element e)/*-{
> ```

see above

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/fieldgroup/FieldGroup.java, line 751 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDxI-v14dU-5YwHfx:-KvCDxI-v14dU-5YwHfy:bmw1nd1) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-server/src/main/java/com/vaadin/v7/data/fieldgroup/FieldGroup.java#L751)):*
> ```Java
> 
>     /**
>      * FIXME javadoc.
> ```

I don't think adding a full stop to FIXME makes much sense - could try to add a minimal sensible javadoc instead.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractSelect.java, line 574 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCE-jDkHKSRwkU8FXP:-KvCE-jDkHKSRwkU8FXQ:bnjq7l2) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractSelect.java#L574)):*
> ```Java
> 
>     /**
>      * TODO refine doc.
> ```

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/GridColumnState.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCIbNuhpDwYKI-vGI:-KvCCIbNuhpDwYKI-vGJ:bmau965) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/GridColumnState.java#L23)):*
> ```Java
> 
> /**
>  * Column state DTO for transferring column properties from the server to the.
> ```

full stop at wrong place (one word too early)

---

*[server/src/main/java/com/vaadin/server/PaintTarget.java, line 281 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCbyOi3FbBWMWhATh:-KvCCbyOi3FbBWMWhATi:bnjq7l2) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/PaintTarget.java#L281)):*
> ```Java
> 
>     /**
>      * TODO.
> ```

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.

---

*[server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCrRMlO26Ud7nXRN3:-KvCCrRMlO26Ud7nXRN4:b-f3trty) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java#L67)):*
> ```Java
>             WebBrowser b = VaadinSession.getCurrent().getBrowser();
> 
>             page.write("<html>" + "<head>" + "  <style>" + "    html {"
> ```

This could try to preserve the old formatting, perhaps with the magic comments that prevent Eclipse from auto-formatting this part.

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 677 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCD1MXIqXEV5uVS_wX:-KvCD1MXIqXEV5uVS_wY:bnjq7l2) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L677)):*
> ```Java
> 
>     /**
>      * TODO document.
> ```

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.

---

*[shared/src/main/java/com/vaadin/shared/AbstractComponentState.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBWw1XcxpBTk08X97t:-KvBWw1XcxpBTk08X97u:b-bboy9) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/shared/src/main/java/com/vaadin/shared/AbstractComponentState.java#L47)):*
> ```Java
>     public String primaryStyleName = null;
> 
>     /** HTML formatted error message for the. */
> ```

Where did the last word "component" disappear?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxElement.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBXcx-Z2xVNHN5Epkb:-KvBXcx-Z2xVNHN5Epkc:b-kd70hn) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxElement.java#L28)):*
> ```Java
> 
>     /**
>      * Return string representation of value of the checkbox Return either.
> ```

incorrect location for the "."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10114#-:-KvCE3fGuy-4xSKHRT7-:bstrr3c)*

**Comment by asashour** [comment]
Review status: 322 of 337 files reviewed at latest revision, 16 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDAqePqRL13_D754O:-KvCMdF705VasitMMoXU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/VTooltip.java#L50)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/TreeAction.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDK2eszTb8UTYB8fw:-KvCMjvaS0UdkNzONanM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/TreeAction.java#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

ITable -> VScrollTable
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VCssLayout.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDOSlO-y3AB9mmoNg:-KvCMoou8rwkFjooBS1I:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VCssLayout.java#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(wrong capitalization of VCssLayout)
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBRmY5IdB35eQEoR7U:-KvCMw00Sf6bTRPE8BMK:b-flrxqf) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L97)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this shouldn't really be a javadoc comment as it applies to several fields rather than the next one.
</blockquote></details>

Done.Removed

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDVExUwOyxoPWWhg4:-KvCN1Ut_upTKef0pj70:bwynuap) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L83)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could also fix initial capital.
</blockquote></details>

Done.I thought initial capitalization is part of another PR :)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java, line 174 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDZa9b_kAUTN7K6zK:-KvCNNnq8WGjGbaW-l3x:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java#L174)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible first sentence of javadoc before the TODOs.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDlA3rXMUPDUDvjkM:-KvCPYJZYGIJMKOU9Goc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L96)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could try to keep the formatting, or update it so that the whole JSNI comment start is on the next line so that the autoformatter handles it better
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java, line 104 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDutaTx3HKn6d1JVN:-KvCPYmh7L6C_1lTg_WX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/widget/treegrid/TreeGrid.java#L104)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/fieldgroup/FieldGroup.java, line 751 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDxI-v14dU-5YwHfx:-KvCPjzZ7R2-gkZOS_1b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-server/src/main/java/com/vaadin/v7/data/fieldgroup/FieldGroup.java#L751)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to FIXME makes much sense - could try to add a minimal sensible javadoc instead.
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractSelect.java, line 574 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCE-jDkHKSRwkU8FXP:-KvCQ1L-VS954p_Bu0wM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-server/src/main/java/com/vaadin/v7/ui/AbstractSelect.java#L574)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.
</blockquote></details>

Done.

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/GridColumnState.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCIbNuhpDwYKI-vGI:-KvCQBQw52kAlXuHIpnI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/GridColumnState.java#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

full stop at wrong place (one word too early)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/PaintTarget.java, line 281 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCbyOi3FbBWMWhATh:-KvCQTg5Y2_MRpDAzHwB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/PaintTarget.java#L281)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCrRMlO26Ud7nXRN3:-KvCQwYaEFq2qQ4bs2gQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java#L67)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This could try to preserve the old formatting, perhaps with the magic comments that prevent Eclipse from auto-formatting this part.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 677 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCD1MXIqXEV5uVS_wX:-KvCR9-75Bwc-0wGEefi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L677)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I don't think adding a full stop to TODO makes much sense - could try to add a minimal sensible javadoc instead.
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/AbstractComponentState.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBWw1XcxpBTk08X97t:-KvCkONMCR-G5W4kgC0f:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/shared/src/main/java/com/vaadin/shared/AbstractComponentState.java#L47)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Where did the last word "component" disappear?
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxElement.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvBXcx-Z2xVNHN5Epkb:-KvCk_PajLtRdPpiqb9Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxElement.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

incorrect location for the "."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10114)*

**Comment by hesara** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VPopupView.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCDVExUwOyxoPWWhg4:-KvLGcDlLhfaKMxCffJl:b-sky3r7) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/client/src/main/java/com/vaadin/client/ui/VPopupView.java#L83)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.I thought initial capitalization is part of another PR :)
</blockquote></details>

There is a lot that should be fixed in our javadoc - some in formatting, even more in content and in giving information that really makes sense. I didn't really read through the content for this PR, some things just popped out so that if fixing them is trivial, could as well do so rather than revert a change until actually fixing the issue. I admit this might not have been very consistent.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvLHGv-ZrvQ2q-tUo14:-KvLHGv-ZrvQ2q-tUo15:bp4fcfw) ([raw file](https://github.com/vaadin/framework/blob/d7ce954d918a2be0795434bf6d8dc22b83b5c926/client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java#L174)):*
> ```Java
> 
>     /**
>      * Returns the details of the drop operation.
> ```

Technically this is for the drag side rather than just a drop (which might not have happened yet, and might not happen at this location or at all). The old DnD mechanism uses the same event for dragenter, dragleave, dragover, drop etc.

Could use "drag and drop operation" or such.

---

*[server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCrRMlO26Ud7nXRN3:-KvLIrlYHopK20AHsY4-:bo9m3a3) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java#L67)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I actually meant (but couldn't recall the syntax for) was:
```
// @formatter:off
...
// @formatter:on
```

However, also this is ok for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10114)*

**Comment by asashour** [comment]
Review status: 335 of 337 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvLHGv-ZrvQ2q-tUo14:-KvM3tG6-Ks2lpEUDiPW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d7ce954d918a2be0795434bf6d8dc22b83b5c926/client/src/main/java/com/vaadin/client/ui/dd/VDragEvent.java#L174)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Technically this is for the drag side rather than just a drop (which might not have happened yet, and might not happen at this location or at all). The old DnD mechanism uses the same event for dragenter, dragleave, dragover, drop etc.

Could use "drag and drop operation" or such.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/10114#-KvCCrRMlO26Ud7nXRN3:-KvM4rU8gS-L9lb5qq6f:b6vjy1f) ([raw file](https://github.com/vaadin/framework/blob/a8a1b6da18169bc5e036fc46db651302e2d0d479/server/src/main/java/com/vaadin/server/UnsupportedBrowserHandler.java#L67)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What I actually meant (but couldn't recall the syntax for) was:
```
// @formatter:off
...
// @formatter:on
```

However, also this is ok for me.
</blockquote></details>

Done. Something new to learn, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10114)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10114#-:-KvM8kRqo4YXZwXCW_w0:bnfp4nl)*

**Pull request merged**
