### PR TITLE
Embedded not to be a LegacyComponent

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10088)

### CODE REVIEW

**Comment by hesara** [comment]
Some comments + this should be mentioned in release notes (possibly combined with other converted components if any).

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyByYW1BhypyCzwjJf:-KuyByYX8tmwChRKrv_R:b-szqgbj) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L56)):*
> ```Java
> 
>         // Save details
>         getWidget().client = stateChangeEvent.getConnector().getConnection();
> ```

Isn't this the same as "getConnection()"?

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyDHw-ufv8u0wTm3zy:-KuyDHw-ufv8u0wTm3zz:b-h7d3qj) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L127)):*
> ```Java
>                             "<iframe width=\"100%\" height=\"100%\" frameborder=\"0\""
>                                     + " allowTransparency=\"true\" src=\"\""
>                                     + " name=\"" + state.id + "\"></iframe>");
> ```

(I think this is correct, but can't recall what happens e.g. if this is null and whether the UIDL ID can be null - to be checked.)

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyE6ONuw_KUJGTj6SA:-KuyE6ONuw_KUJGTj6SB:b-stw7rt) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L107)):*
> ```Java
> 
>     @Override
>     public void beforeClientResponse(boolean initial) {
> ```

now an "empty" override so this could be removed

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEL__7NWDy6NVvVNi:-KuyEL__7NWDy6NVvVNj:b-dzyl18) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L153)):*
> ```Java
>     public void setParameter(String name, String value) {
>         getState().parameters.put(name, value);
>         markAsDirty();
> ```

markAsDirty is now redundant as getState() (which stands for getState(true)) does it automatically.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyETox9jSx3Z4g9r2U:-KuyETox9jSx3Z4g9r2V:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L175)):*
> ```Java
>     public void removeParameter(String name) {
>         getState().parameters.remove(name);
>         markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 239 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEYWp8ED4p4QBiapf:-KuyEYWp8ED4p4QBiapg:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L239)):*
> ```Java
>                 || (codebase != null && !codebase.equals(oldCodebase))) {
>             getState().codebase = codebase;
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEZz5y2JrC8APOX4Q:-KuyEZz5y2JrC8APOX4R:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L258)):*
> ```Java
>                 || (codetype != null && !codetype.equals(oldCodetype))) {
>             getState().codetype = codetype;
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 284 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEcDOzyopi4MD4Exp:-KuyEcDOzyopi4MD4Exq:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L284)):*
> ```Java
>                 }
>             }
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 300 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEdwPZIOppb7dbG-d:-KuyEdwPZIOppb7dbG-e:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L300)):*
> ```Java
>                 || (standby != null && !standby.equals(oldStandby))) {
>             getState().standby = standby;
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 326 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEfKGks-auvHGw1cy:-KuyEfKGks-auvHGw1cz:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L326)):*
> ```Java
>                 || (classId != null && !classId.equals(oldClassId))) {
>             getState().classId = classId;
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 379 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEnNX5-mupO2XzfvW:-KuyEnNX5-mupO2XzfvX:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L379)):*
> ```Java
>                 // Keep previous type
>             }
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 403 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEu3CBE9b25HKeTIv:-KuyEu3CBE9b25HKeTIw:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L403)):*
> ```Java
>         if (type != getType()) {
>             getState().type = type;
>             markAsDirty();
> ```

redundant

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 439 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEx1T1iezT0hkFqOn:-KuyEx1T1iezT0hkFqOo:bjdqao8) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L439)):*
> ```Java
>                 || (archive != null && !archive.equals(oldArchive))) {
>             getState().archive = archive;
>             markAsDirty();
> ```

redundant

---

*[shared/src/main/java/com/vaadin/shared/ui/embedded/EmbeddedState.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyF0KlmibpXu-LIKq6:-KuyF0KlmibpXu-LIKq7:b-rv3bsc) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/shared/src/main/java/com/vaadin/shared/ui/embedded/EmbeddedState.java#L28)):*
> ```Java
>     }
> 
>     public int type;
> ```

It would be nice to have one-line javadoc and a since tag on the new fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088#-:-KuyFAZ4ldQyCYnnD_iw:bkp9was)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 239 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEYWp8ED4p4QBiapf:-KuyIdvJFtXu09KTT63J:b-pnz716) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L239)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

note also that trivial accessors don't necessarily need to check that the value changes (although it doesn't hurt as it can save some dirty connector handling), but setters that need to perform more computation (like for time zones and JSON) usually should

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by asashour** [comment]
Review status: 2 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyByYW1BhypyCzwjJf:-KuyGojzGkMnLzqAxaua:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L56)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Isn't this the same as "getConnection()"?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyDHw-ufv8u0wTm3zy:-KuyHD9jCvHEstwmIKm7:byauznc) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L127)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I think this is correct, but can't recall what happens e.g. if this is null and whether the UIDL ID can be null - to be checked.)
</blockquote></details>

I see it is check for `null` in `AbstractComponentConnector`.`onStateChanged`, but I don't know.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 107 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyE6ONuw_KUJGTj6SA:-KuyHXRVdCAeSEdxr8Yc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L107)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

now an "empty" override so this could be removed
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEL__7NWDy6NVvVNi:-KuyHpeWoQ_RWdl81SQf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L153)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

markAsDirty is now redundant as getState() (which stands for getState(true)) does it automatically.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 175 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyETox9jSx3Z4g9r2U:-KuyHqBNPC2oCas2GuAc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L175)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 239 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEYWp8ED4p4QBiapf:-KuyHqgaCgcQa9QILyot:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L239)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 258 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEZz5y2JrC8APOX4Q:-KuyHrA9Xbc8jVicu71t:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L258)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 284 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEcDOzyopi4MD4Exp:-KuyHrchhW0usT4U5--B:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L284)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 300 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEdwPZIOppb7dbG-d:-KuyHrxAPMDktTya27Tv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L300)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 326 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEfKGks-auvHGw1cy:-KuyHsVhzXcBfLkBUleV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L326)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 379 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEnNX5-mupO2XzfvW:-KuyHsxNmwDh1JIFLmXM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L379)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 403 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEu3CBE9b25HKeTIv:-KuyHtRfhh_7DeGwNpJk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L403)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Embedded.java, line 439 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyEx1T1iezT0hkFqOn:-KuyHtvFPtssDdM3xfso:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/server/src/main/java/com/vaadin/ui/Embedded.java#L439)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/embedded/EmbeddedState.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyF0KlmibpXu-LIKq6:-KuyJIgCB8z52YU34H0f:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/shared/src/main/java/com/vaadin/shared/ui/embedded/EmbeddedState.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

It would be nice to have one-line javadoc and a since tag on the new fields.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyDHw-ufv8u0wTm3zy:-KuyoQRxbM931zqTz0tJ:blsbd79) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L127)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I see it is check for `null` in `AbstractComponentConnector`.`onStateChanged`, but I don't know.
</blockquote></details>

The old mechanism made sure that components had a generated connector id as the id in the UIDL (handled in AbstractClientConnector.getConnectorId()). I think AbstractConnector.getConnectorId() is the equivalent of what this used to do, and will not be null once the connector has been initialized on the client side, whereas state.id might be null.

I'm not 100% sure if it is what we really should use here, or whether this was using the incorrect id all along, but at least right now the safest option would probably be to use getConnectorId(). The confusion may also have stemmed from the fact that a very long time ago (in Vaadin Framework 6 and its predecessors), the two ids used to have the same value if one was explicitly set, but at least I haven't seen anybody complain about the current behavior anytime recently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by asashour** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/framework/10088#-KuyDHw-ufv8u0wTm3zy:-Kuysqml9LIMfQRkPNxN:b-qto98h) ([raw file](https://github.com/vaadin/framework/blob/e293b34171455374531d5fdb3e5a8890d18c3a98/client/src/main/java/com/vaadin/client/ui/embedded/EmbeddedConnector.java#L127)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

The old mechanism made sure that components had a generated connector id as the id in the UIDL (handled in AbstractClientConnector.getConnectorId()). I think AbstractConnector.getConnectorId() is the equivalent of what this used to do, and will not be null once the connector has been initialized on the client side, whereas state.id might be null.

I'm not 100% sure if it is what we really should use here, or whether this was using the incorrect id all along, but at least right now the safest option would probably be to use getConnectorId(). The confusion may also have stemmed from the fact that a very long time ago (in Vaadin Framework 6 and its predecessors), the two ids used to have the same value if one was explicitly set, but at least I haven't seen anybody complain about the current behavior anytime recently.
</blockquote></details>

Done. Thanks for clarification.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088#-:-KuyvFImVFVru9MTVAYK:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10088)*

**Comment by hesara** [comment]
I think I messed up things with my merges - will try once more.

**Pull request merged**
