### PR TITLE
Extract AbstractBeanPropertyDefinition and PropertyFilterDefinition

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10344)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r3, 1 of 2 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 505 at r4](https://reviewable.io:443/reviews/vaadin/framework/10344#-KzTIxWhFukrQ9EVbkdP:-KzTIxWhFukrQ9EVbkdQ:bqfy49q) ([raw file](https://github.com/vaadin/framework/blob/3e60844eccaf58f00a3fa4c7938799faa5c7ebcc/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L505)):*
> ```Java
>      * @return the bean type of this bean property set
>      */
>     public Class<T> getBeanType() {
> ```

Was this method needed for the extraction ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10344)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 505 at r4](https://reviewable.io:443/reviews/vaadin/framework/10344#-KzTIxWhFukrQ9EVbkdP:-KzTJkZnXwWj8B3hqLKa:b-wv99xw) ([raw file](https://github.com/vaadin/framework/blob/3e60844eccaf58f00a3fa4c7938799faa5c7ebcc/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L505)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Was this method needed for the extraction ?
</blockquote></details>

Found the place where this is used!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10344)*

**Comment by ahie** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 505 at r4](https://reviewable.io:443/reviews/vaadin/framework/10344#-KzTIxWhFukrQ9EVbkdP:-KzTJl08VJxy6zF1MIOb:ba984wy) ([raw file](https://github.com/vaadin/framework/blob/3e60844eccaf58f00a3fa4c7938799faa5c7ebcc/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L505)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Was this method needed for the extraction ?
</blockquote></details>

Yes, `AbstractBeanPropertyDefinition` uses it in its constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10344)*

**Comment by ahie** [comment]
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 505 at r4](https://reviewable.io:443/reviews/vaadin/framework/10344#-KzTIxWhFukrQ9EVbkdP:-KzTJu4H8T9XreFYknbO:bb6mt9b) ([raw file](https://github.com/vaadin/framework/blob/3e60844eccaf58f00a3fa4c7938799faa5c7ebcc/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L505)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Yes, `AbstractBeanPropertyDefinition` uses it in its constructor.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10344)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10344)*

**Pull request merged**
