### PR TITLE
Picks 8.7.2

### PR DESCRIPTION
**Pull request by ZheSun88**
Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)

### CODE REVIEW

**Review by pleku — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: 1 of 14 files reviewed, all discussions resolved (waiting on @ZheSun88)

**Review by pleku — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTGKht9I4S01-5AC54:bgvcax5) (no related file):*
Why is not the following picked ?
Support Firefox 65+ key down event behavior (#11503)  4771193
Init logging in VaadinServlet instead of an UI (#11525) 7d2b6ca

---

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: all files reviewed, 1 unresolved discussion (waiting on @pleku)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTH1Fh8xyfwUROS1Y9:b-m1odx5) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why is not the following picked ?
Support Firefox 65+ key down event behavior (#11503)  4771193
Init logging in VaadinServlet instead of an UI (#11525) 7d2b6ca
</blockquote></details>

oh darn... my fault.. my screen is too small to see those two commits 

---

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: 13 of 20 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTHTiL8leD067SY2Wd:b-t9490b) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

oh darn... my fault.. my screen is too small to see those two commits 
</blockquote></details>

added 

---

**Review by pleku — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: 13 of 20 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTHVWCE3mwtAWPfbzs:b-hy5i95) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

added 
</blockquote></details>

That is an appalling excuse.

Also https://github.com/vaadin/framework/commit/15cc5d13b379d744988b169916eb1b9437cf8021 is missing

---

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: 13 of 20 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTHrVr-ta6SJGoo4st:b-mvx06q) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

That is an appalling excuse.

Also https://github.com/vaadin/framework/commit/15cc5d13b379d744988b169916eb1b9437cf8021 is missing
</blockquote></details>

I left that one out because there is a new api added in it. 

```
/**
     * Sets whether or not to track invalidated rows inside
     * {@link #insertRowData(int, int)} and use them to fill cache when
     * {{@link #setRowData(int, List)}} is called.
     *
     * @param trackInvalidatedRows
     *            a boolean value specifying if to track invalidated rows or
     *            not, default value <code>true</code>
     */
    public void setTrackInvalidatedRows(boolean trackInvalidatedRows) {
```

---

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: 13 of 20 files reviewed, 1 unresolved discussion (waiting on @pleku and @ZheSun88)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11527#-LbTGKht9I4S01-5AC53:-LbTK0Z5ETcVKgl198_v:b-y5l0iz) (no related file):*
> 15cc5d1
added now. 

---

**Review by pleku — APPROVED** [review]
> Reviewed 6 of 6 files at r11, 1 of 1 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11527)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
