### PR TITLE
Setting of tooltips for grid header/footer cells

### LINKED ISSUE #7527: Grid: support for description on header cells
**Originally by _phansson_**

___
There's a need for tooltip (Vaadin lingo: description) on Grid header cells.

I believe the best way to implement this would be same place where its possible to set the header caption, namely on the `Column` object. In other words something like:

```
#!java
    void Grid.Column.setHeaderDescription(String description)
```

and 

```
#!java
    String Grid.Column.getHeaderDescription()
```

In lieu of this feature being part of standard Vaadin there's a decent workaround [here](http://stackoverflow.com/a/35638816/1504556).

___
 Imported from https://dev.vaadin.com/ issue #19637

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #7527

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10489)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 514 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20ek0MgCH9hhcmFlWP:-L20ek0NeIxzUJnEGAqd:b-6ul9pe) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/client/src/main/java/com/vaadin/client/widgets/Grid.java#L514)):*
> ```Java
>                     ContentMode descriptionContentMode) {
>                 if (descriptionContentMode == ContentMode.PREFORMATTED) {
>                     throw new IllegalArgumentException(
> ```

Why are `PREFORMATTED` tooltips not supported?

---

*[server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20eyo6LnRgk6knjsZi:-L20eyo7lO_D0kSDjoSh:b-7do669) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java#L144)):*
> ```Java
>      * @since
>      */
>     public void setDescription(String description,
> ```

should this method have a default implementation as this is just a helper method to call both individual parts?

---

*[server/src/main/java/com/vaadin/ui/components/grid/HeaderCell.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20f61R0fBVg3c3iTJn:-L20f61Sl0DArrA436yg:b-khq8qf) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/HeaderCell.java#L144)):*
> ```Java
>      * @since
>      */
>     public void setDescription(String description,
> ```

default implementation?

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 621 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20fDGiCMydM5JS-ynl:-L20fDGjd7EE1GXMvuIN:b-2lclnr) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L621)):*
> ```Java
> 
>         /**
>          * Gets the tooltip for the cell.
> ```

Do we really need to duplicate the JavaDocs? Maybe the common API of both Header and Footer cells should be in some interface somewhere..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by Artur-** [comment]
Review status: 4 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 514 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20ek0MgCH9hhcmFlWP:-L21lT5qbNTfZVmDuNR3:b-t2dsqv) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/client/src/main/java/com/vaadin/client/widgets/Grid.java#L514)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why are `PREFORMATTED` tooltips not supported?
</blockquote></details>

Not sure, fixed

---

*[server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20eyo6LnRgk6knjsZi:-L21lZZSDd6CDFLRMJq3:b-pyqvqt) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java#L144)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should this method have a default implementation as this is just a helper method to call both individual parts?
</blockquote></details>

That would mean the implementation would be in both `FooterCell` and `HeaderCell` instead of only in `StaticCell`. The class hierarchy is strange but it is what it is...

---

*[server/src/main/java/com/vaadin/ui/components/grid/HeaderCell.java, line 144 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20f61R0fBVg3c3iTJn:-L21m5939Hmj-FEan4iJ:b-pyqvqt) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/HeaderCell.java#L144)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

default implementation?
</blockquote></details>

That would mean the implementation would be in both `FooterCell` and `HeaderCell` instead of only in `StaticCell`. The class hierarchy is strange but it is what it is...

---

*[server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java, line 621 at r1](https://reviewable.io:443/reviews/vaadin/framework/10489#-L20fDGiCMydM5JS-ynl:-L21m745omMbTlJzmxi9:b-sedvfy) ([raw file](https://github.com/vaadin/framework/blob/83d03d5f8c47a8d1b3e588cc26554baa91ee6a29/server/src/main/java/com/vaadin/ui/components/grid/StaticSection.java#L621)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Do we really need to duplicate the JavaDocs? Maybe the common API of both Header and Footer cells should be in some interface somewhere..
</blockquote></details>

This is because of the strange class hierarchy:
`HeaderCell` is an interface
`StaticCell` is a class, unrelated to both `HeaderCell` and `FooterCell`
`Header.Row.Cell` extends `StaticCell` and implements `HeaderCell`

Could probably be fixed but is not related to this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 8 files at r1, 5 of 6 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 727 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5Nnx4hRO1oi-n8H-rt:-L5Nnx4hRO1oi-n8H-ru:b-d1xzog) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L727)):*
> ```Java
>         if (section == Section.HEADER) {
>             staticCell = getWidget().getHeaderRow(cell.getRowIndex())
>                     .getCell(getWidget().getColumn(cell.getColumnIndex()));
> ```

How about using `cell.getColumn()` instead of digging through the widget again?

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 730 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5No5JIZF7-p8Ess81j:-L5No5JIZF7-p8Ess81k:bvrg9pg) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L730)):*
> ```Java
>         } else if (section == Section.FOOTER) {
>             staticCell = getWidget().getFooterRow(cell.getRowIndex())
>                     .getCell(getWidget().getColumn(cell.getColumnIndex()));
> ```

`cell.getColumn()`

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 495 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NyLS59WUwReIfkBLG:-L5NyLS6to1yKDja-N20:bh19qxi) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/widgets/Grid.java#L495)):*
> ```Java
>              * <p>
>              * The content mode determines if the tooltip is shown as plain text
>              * ({@link ContentMode#TEXT}) or as HTML({@link ContentMode#HTML}).
> ```

There are still quite a few occasions that describe the use of `ContentMode` but nowhere it mentions the `PREFORMATTED` option in anyway. Should we just add links with `@see ContentMode` rather than describe the same stuff over and over in every single javadoc?

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java, line 3 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NylUXtOCtnRr_NSLA:-L5NylUXtOCtnRr_NSLB:betf50q) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java#L3)):*
> ```Java
> package com.vaadin.tests.widgetset.client.extension;
> 
> public class EventTriggerExtensionTest {
> ```

What class is this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by elmot** [comment]
Review status: 3 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 727 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5Nnx4hRO1oi-n8H-rt:-L5OgYang2w67Xme_TCG:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L727)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

How about using `cell.getColumn()` instead of digging through the widget again?
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 730 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5No5JIZF7-p8Ess81j:-L5OgZrVSrFzFkTIk-Gs:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L730)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`cell.getColumn()`
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 495 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NyLS59WUwReIfkBLG:-L5OgqZortxmVHyArBoA:b-9nerwi) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/widgets/Grid.java#L495)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

There are still quite a few occasions that describe the use of `ContentMode` but nowhere it mentions the `PREFORMATTED` option in anyway. Should we just add links with `@see ContentMode` rather than describe the same stuff over and over in every single javadoc?
</blockquote></details>

Good idea. Replaced everywhere except server-compatibility.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java, line 3 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NylUXtOCtnRr_NSLA:-L5OgddgpIoZ-IX8nY04:b3uumb1) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java#L3)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What class is this?
</blockquote></details>

Oops. My mistake, deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by tsuoanttila** [comment]
Reviewed 6 of 7 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospection.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/framework/10489#-L6GsvcdlJGd4nBhlpdc:-L6GsvcdlJGd4nBhlpdd:b-gjs1lq) ([raw file](https://github.com/vaadin/framework/blob/5a5c618939596815745a9aec147902636bdc1001/server/src/test/java/com/vaadin/data/PropertyRetrospection.java#L9)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> 
> public class PropertyRetrospection {
> ```

What test is this and how it relates to the rest of the PR ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/test/java/com/vaadin/data/PropertyRetrospection.java, line 9 at r3](https://reviewable.io:443/reviews/vaadin/framework/10489#-L6GsvcdlJGd4nBhlpdc:-L75-x92Itvb_OUruLtY:bad8b1g) ([raw file](https://github.com/vaadin/framework/blob/5a5c618939596815745a9aec147902636bdc1001/server/src/test/java/com/vaadin/data/PropertyRetrospection.java#L9)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What test is this and how it relates to the rest of the PR ?
</blockquote></details>

Oops, removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 495 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NyLS59WUwReIfkBLG:-L7U4RAmvTLXDnYqc9Sl:byq5k9n) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/client/src/main/java/com/vaadin/client/widgets/Grid.java#L495)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Good idea. Replaced everywhere except server-compatibility.
</blockquote></details>

@elmot you're blocking this comment.

---

*[uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java, line 3 at r2](https://reviewable.io:443/reviews/vaadin/framework/10489#-L5NylUXtOCtnRr_NSLA:-L7U4WawrLbpUT1ecovU:byq5k9n) ([raw file](https://github.com/vaadin/framework/blob/6e9d48abe7aa69313e70dc0088fc4ef84084d29f/uitest/src/main/java/com/vaadin/tests/widgetset/client/extension/EventTriggerExtensionTest.java#L3)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Oops. My mistake, deleted.
</blockquote></details>

@elmot you're blocking this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10489)*

**Pull request merged**
