### PR TITLE
Add convenience constructors for TextField (#597)

### PR DESCRIPTION
**Pull request by caalador**
Added convenience constructors similar to the ones in V7

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8341)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TextField.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8341#-KbPkqY6miCa0RuFNRc7:-KbPkqY6miCa0RuFNRc8:btnjf7p) ([raw file](https://github.com/vaadin/framework/blob/13ffbb07fa3013947d64890b428022cd6217b774/server/src/main/java/com/vaadin/ui/TextField.java#L106)):*
> ```Java
>      *            the caption {@code String} for the editor.
>      * @param value
>      *            the initial text content of the editor.
> ```

is not null

---

*[server/src/test/java/com/vaadin/ui/TextFieldConstructorTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8341#-KbPl-Ww_aG4lF622SUa:-KbPl-WyMLXNRngeFks9:b-wt8c0t) ([raw file](https://github.com/vaadin/framework/blob/13ffbb07fa3013947d64890b428022cd6217b774/server/src/test/java/com/vaadin/ui/TextFieldConstructorTest.java#L24)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> 
> public class TextFieldConstructorTest {
> ```

I would rather check that CTOR delegates call to the methods (via Mockito) instead of checking the functionality of those methods directly.
But it's minor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8341)*

**Comment by caalador** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/TextField.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8341#-KbPkqY6miCa0RuFNRc7:-KbPtFxAGADt9WpNE1Ve:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/13ffbb07fa3013947d64890b428022cd6217b774/server/src/main/java/com/vaadin/ui/TextField.java#L106)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

is not null
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/ui/TextFieldConstructorTest.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8341#-KbPl-Ww_aG4lF622SUa:-KbPtH9K0BjRRFRhcw5p:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/13ffbb07fa3013947d64890b428022cd6217b774/server/src/test/java/com/vaadin/ui/TextFieldConstructorTest.java#L24)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would rather check that CTOR delegates call to the methods (via Mockito) instead of checking the functionality of those methods directly.
But it's minor.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8341)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8341)*

**Comment by ahie** [comment]
These changes should probably be made to `PasswordField` and `TextArea` as well, but that is unrelated to this particular issue.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8341#-:-KbQDAFljWfkEVymxpEj:bfi0d83)*

**Pull request merged**
