### PR TITLE
add Grid.Column#get/setAssistiveCaption

### PR DESCRIPTION
**Pull request by knoobie**
This pull request adds a method to Grid.Column to allow the developer to specify an aria-label for each column. This is needed especially for older screenreader who can't handle aria-sort. 

A normal workflow would be to add for example this to a column:

- "Column: Name, sortable. Press Enter to change sort direction."
- "Column: Name (Firstname, Lastname), sortable. Press Enter to change sort direction."

This labels are only for assistive devices. User without assistive devices don't see this messages. (They don't need them - they can see the sorting indicator etc.)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10219)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4870 at r1](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kwt-iUF9kTDW8uTptry:-Kwt-iUF9kTDW8uTptrz:bhdlbdb) ([raw file](https://github.com/vaadin/framework/blob/0a405896c5b565e4fd907bef753023a8469fa0d8/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4870)):*
> ```Java
> 
>         /**
>          * Sets a header aria-label for this column.
> ```

*the* header

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1213 at r1](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kwt0J-ifE8Wx_RbIlGy:-Kwt0J-ifE8Wx_RbIlGz:b-wuvzj) ([raw file](https://github.com/vaadin/framework/blob/0a405896c5b565e4fd907bef753023a8469fa0d8/server/src/main/java/com/vaadin/ui/Grid.java#L1213)):*
> ```Java
>          */
>         public Column<T, V> setAssistiveCaption(String caption) {
>             if (Objects.equals(caption, getState(false).assistiveCaption)) {
> ```

Replace `getState(false).assistiveCaption` with `getAssistiveCaption()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4870 at r1](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kwt-iUF9kTDW8uTptry:-Kwt43-ob8LirHBvGIAY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0a405896c5b565e4fd907bef753023a8469fa0d8/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4870)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

*the* header
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1213 at r1](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kwt0J-ifE8Wx_RbIlGy:-Kwt441p45bq__ypyxQe:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0a405896c5b565e4fd907bef753023a8469fa0d8/server/src/main/java/com/vaadin/ui/Grid.java#L1213)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Replace `getState(false).assistiveCaption` with `getAssistiveCaption()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219#-:-KwtgJeSNs6cfkbdRtdD:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GXNLESyub1u3xCb1:-Kx7GXNLESyub1u3xCb2:b-3vdyir) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L9)):*
> ```Java
> import static org.junit.Assert.assertEquals;
> 
> public class GridAssistiveCaptionTest {
> ```

instead of a whole new test file, I'd rather use some already existing one (like `com.vaadin.tests.server.component.grid.GridTest`) 

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridAssistiveCaption.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GViSFCYYQFGp5kfr:-Kx7GViSFCYYQFGp5kfs:bip6jn0) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/main/java/com/vaadin/tests/components/grid/GridAssistiveCaption.java#L26)):*
> ```Java
> /**
>  * @author Vaadin Ltd
>  *
> ```

remove empty javadoc

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx7GUVvVRRYMQM-3WET:bip6jn0) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

remove empty javadoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GXNLESyub1u3xCb1:-Kx7NgQ0Rw-fH1RHVOc1:b-4caxly) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L9)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

instead of a whole new test file, I'd rather use some already existing one (like `com.vaadin.tests.server.component.grid.GridTest`) 
</blockquote></details>

Done via Github UI - hopefully everything works.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridAssistiveCaption.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GViSFCYYQFGp5kfr:-Kx7Ne2KyAeCtIj05fXS:b-7de27g) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/main/java/com/vaadin/tests/components/grid/GridAssistiveCaption.java#L26)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

remove empty javadoc
</blockquote></details>

File deleted.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx7NfKk93igLXlKJZXk:b-7de27g) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

remove empty javadoc
</blockquote></details>

File deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx7yJ3-0IlV_PN8qrgY:bb0wvq3) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

File deleted.
</blockquote></details>

Are you sure you deleted the correct files? From what I see the UI test is now removed and the unit test is still there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx8-xoU-ywr-4ZGhSlO:b-ifkq29) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Are you sure you deleted the correct files? From what I see the UI test is now removed and the unit test is still there.
</blockquote></details>

Here are my commits:

- delete under /main https://github.com/vaadin/framework/pull/10219/commits/a0594f8e88627e429da0677e107efe28cbf33201
- delete under /test https://github.com/vaadin/framework/pull/10219/commits/1181c5e1f5ab59e241ca585d6be6a8602973a685

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx80vW1nWdYL6W_GVIX:b-np8q64) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Here are my commits:

- delete under /main https://github.com/vaadin/framework/pull/10219/commits/a0594f8e88627e429da0677e107efe28cbf33201
- delete under /test https://github.com/vaadin/framework/pull/10219/commits/1181c5e1f5ab59e241ca585d6be6a8602973a685
</blockquote></details>

Done. Looks like I only deleted a cached file of an old branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx832m5zrcxl7ArxYQ5:b-olsbgm) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Done. Looks like I only deleted a cached file of an old branch.
</blockquote></details>

I mean these UI test files are actually testing the client-side implementation that can't be tested on the server and would be really nice thing to have. All I wanted to remove from this file was the empty class javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by tsuoanttila** [comment]
*[server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GXNLESyub1u3xCb1:-Kx83HlhcE8jj1xXH-Zp:b-ca0o0o) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/server/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L9)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Done via Github UI - hopefully everything works.
</blockquote></details>

This is now as it should be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx88MAtQOZQ1WIdwb0Q:b-lnmlzn) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I mean these UI test files are actually testing the client-side implementation that can't be tested on the server and would be really nice thing to have. All I wanted to remove from this file was the empty class javadoc.
</blockquote></details>

Understood. I'm going to fix it later tonight, doing that with the github UI kinda breaks it..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by knoobie** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/10219#-Kx7GUVvVRRYMQM-3WES:-Kx89DqpU6D6CFO-p1ml:b7do04j) ([raw file](https://github.com/vaadin/framework/blob/cd0d7e68cb319ccda6375a8e03575b19694253b4/uitest/src/test/java/com/vaadin/tests/components/grid/GridAssistiveCaptionTest.java#L27)):*
<details><summary><i>Previously, knoobie (Knoobie) wrote…</i></summary><blockquote>

Understood. I'm going to fix it later tonight, doing that with the github UI kinda breaks it..
</blockquote></details>

Done. Sorry for the spam.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by torok-peter** [comment]
Reviewed 2 of 2 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Comment by tsuoanttila** [comment]
Reformatted the test file

**Comment by tsuoanttila** [comment]
@torok-peter could you do the final review of the formatting change and merge this?

**Comment by torok-peter** [comment]
Reviewed 1 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10219)*

**Pull request merged**
