### PR TITLE
Fix test issue for IE11

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8933)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8933#-Kg-3hBRjG9gPPVyBqfg:-Kg-3hBRjG9gPPVyBqfh:b-a1dwls) ([raw file](https://github.com/vaadin/framework/blob/4b4a5f2fab0c7bbe3c1b544023197491a292f75d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L124)):*
> selectmMenuPath

Typo here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8933)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8933#-Kg-3hBRjG9gPPVyBqfg:-Kg-4xeSFbkvCR5I-wU_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4b4a5f2fab0c7bbe3c1b544023197491a292f75d/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L124)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> selectmMenuPath

Typo here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8933)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8933)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8933)*

**Pull request merged**
