### PR TITLE
Grid UI tests migration P3.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8121)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Screenshots are updated : afd11b564d4de57c67a56f3fcb73940426a557e4 (in screenshots repo).

**Comment by pleku** [comment]
Reviewed 61 of 61 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridCellFocusOnResetSize.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TmfuV2tPax_UHIWlj:-K_TmfuV2tPax_UHIWlk:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridCellFocusOnResetSize.java#L26)):*
> ```Java
> 
> @Widgetset(TestingWidgetSet.NAME)
> public class GridCellFocusOnResetSize extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridClientDataChangeHandler.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TlIESb_0q3TS_Sj8G:-K_TlIESb_0q3TS_Sj8H:b-ko24tc) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridClientDataChangeHandler.java#L26)):*
> ```Java
> 
> @Widgetset(TestingWidgetSet.NAME)
> public class GridClientDataChangeHandler extends AbstractReindeerTestUI {
> ```

Test with Valo instead of Reindeer, no screenshots to update

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColspans.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TkcRa-lFBao2z3cgv:-K_TkcRbJv4CB2vMadUX:b-bn3lvn) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColspans.java#L31)):*
> ```Java
> import com.vaadin.ui.renderers.NumberRenderer;
> 
> public class GridColspans extends AbstractReindeerTestUI {
> ```

No screenshots so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoExpand.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TnCRiCIuf3_tgt0Xj:-K_TnCRiCIuf3_tgt0Xk:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoExpand.java#L24)):*
> ```Java
> import com.vaadin.ui.VerticalLayout;
> 
> public class GridColumnAutoExpand extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoWidth.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_To2EN0oAiOfUAQBHc:-K_To2EN0oAiOfUAQBHd:bwafmhw) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoWidth.java#L25)):*
> ```Java
> import com.vaadin.ui.renderers.HtmlRenderer;
> 
> public class GridColumnAutoWidth extends AbstractReindeerTestUI {
> ```

Just one screenshot to update and this could test valo instead of legacy theme..

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnWidthsWithoutData.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tok1JE6ck-_I1EFKK:-K_Tok1JE6ck-_I1EFKL:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnWidthsWithoutData.java#L33)):*
> ```Java
> import com.vaadin.ui.VerticalLayout;
> 
> public class GridColumnWidthsWithoutData extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDataSourceReset.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Topi5P729Fi0gzd4I:-K_Topi5P729Fi0gzd4J:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDataSourceReset.java#L30)):*
> ```Java
> import com.vaadin.ui.Grid;
> 
> public class GridDataSourceReset extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsDetach.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TovmCKVBF0t5INd9H:-K_TovmCKVBF0t5INd9I:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsDetach.java#L31)):*
> ```Java
> import com.vaadin.ui.renderers.NumberRenderer;
> 
> public class GridDetailsDetach extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsLayoutExpand.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tp0WkceMS6kw6Q3C6:-K_Tp0WkceMS6kw6Q3C7:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsLayoutExpand.java#L36)):*
> ```Java
>  */
> @SuppressWarnings("serial")
> public class GridDetailsLayoutExpand extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsWidth.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TpAiRyOiOb5PVcHXV:-K_TpAiRyOiOb5PVcHXW:bjkz2bz) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsWidth.java#L29)):*
> ```Java
> import com.vaadin.ui.VerticalLayout;
> 
> public class GridDetailsWidth extends AbstractReindeerTestUI {
> ```

No screenshots to update so should use Valo

---

*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridColumnWidthRecalculation.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tnpl9_2QUEwPN6sos:-K_Tnpl9_2QUEwPN6sot:b-tyh40) ([raw file](https://github.com/vaadin/framework/blob/a25b690f1d188753fa0f202d862fe9f117e02b7e/uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridColumnWidthRecalculation.java#L1)):*
> ```Java
> /*
> ```

Removed but not replaced ?

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridClientDataChangeHandlerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tl9mwKWq5sp7r79XZ:-K_Tl9mwKWq5sp7r79X_:byp18fd) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/test/java/com/vaadin/tests/components/grid/GridClientDataChangeHandlerTest.java#L29)):*
> ```Java
> 
> @TestCategory("grid")
> @RunLocally(Browser.PHANTOMJS)
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridCellFocusOnResetSize.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TmfuV2tPax_UHIWlj:-K_TqPMTSZ62BP3eJjqg:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridCellFocusOnResetSize.java#L26)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridClientDataChangeHandler.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TlIESb_0q3TS_Sj8G:-K_Tqqnr_AvtB8UegueX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridClientDataChangeHandler.java#L26)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Test with Valo instead of Reindeer, no screenshots to update
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColspans.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TkcRa-lFBao2z3cgv:-K_Tr2MVJ4CUS0r8ROyd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColspans.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoExpand.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TnCRiCIuf3_tgt0Xj:-K_Tr7EZpk1a5jRwCjKJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoExpand.java#L24)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoWidth.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_To2EN0oAiOfUAQBHc:-K_TrETeUxjg-CNImLBt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnAutoWidth.java#L25)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Just one screenshot to update and this could test valo instead of legacy theme..
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnWidthsWithoutData.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tok1JE6ck-_I1EFKK:-K_TrOsZPKLJIRkCsezs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnWidthsWithoutData.java#L33)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDataSourceReset.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Topi5P729Fi0gzd4I:-K_TrT-YOHJ-xFgDLQCE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDataSourceReset.java#L30)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsDetach.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TovmCKVBF0t5INd9H:-K_Ts6ol3nhfgJIBpMnH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsDetach.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsLayoutExpand.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tp0WkceMS6kw6Q3C6:-K_TsEYDEB7lCAxWMOmv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsLayoutExpand.java#L36)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsWidth.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_TpAiRyOiOb5PVcHXV:-K_TsISrjtV6GJ2W70Jv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/main/java/com/vaadin/tests/components/grid/GridDetailsWidth.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No screenshots to update so should use Valo
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridColumnWidthRecalculation.java, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tnpl9_2QUEwPN6sos:-K_TsYuQypjY_NOflgJ0:b-rub77v) ([raw file](https://github.com/vaadin/framework/blob/a25b690f1d188753fa0f202d862fe9f117e02b7e/uitest/src/main/java/com/vaadin/v7/tests/components/grid/GridColumnWidthRecalculation.java#L1)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Removed but not replaced ?
</blockquote></details>

Yes.
The test is about `Grid.recalculateColumnWidths()`
There is no such method in the modern Grid.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridClientDataChangeHandlerTest.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_Tl9mwKWq5sp7r79XZ:-K_Tss-xxx32zvxxXtnr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ea5282b61a559ccd1a110157cf7e201864296c85/uitest/src/test/java/com/vaadin/tests/components/grid/GridClientDataChangeHandlerTest.java#L29)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by pleku** [comment]
Reviewed 9 of 61 files at r1, 10 of 11 files at r2, 4 of 6 files at r3.
Review status: 28 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by pleku** [comment]
Reviewed 2 of 61 files at r1, 2 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by pleku** [comment]
Reviewed 3 of 61 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnAutoExpandTest.java, line 35 at r4](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_YFmPfiFqXM2BLCFTb:-K_YFmPfiFqXM2BLCFTc:blf82r8) ([raw file](https://github.com/vaadin/framework/blob/06ae85e578ef882866ef5201ccb0b9bcba9d0a8d/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnAutoExpandTest.java#L35)):*
> ```Java
>         // The functionality doesn't work for PHJS_1. And the test fails. It
>         // works for PHJS_2.
>         return getBrowsersExcludingPhantomJS();
> ```

Another option might be to let the test pass for phantomjs version 1, meaning you check it in the beginning of the test and then just return if that is the case. You can get the major version from the _current browsers desired capabilities_.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by denis-anisimov** [comment]
Review status: 41 of 47 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnAutoExpandTest.java, line 35 at r4](https://reviewable.io:443/reviews/vaadin/framework/8121#-K_YFmPfiFqXM2BLCFTb:-K_Z5kYTsk7DpRq9V8gd:b-mbd0s1) ([raw file](https://github.com/vaadin/framework/blob/06ae85e578ef882866ef5201ccb0b9bcba9d0a8d/uitest/src/test/java/com/vaadin/tests/components/grid/GridColumnAutoExpandTest.java#L35)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Another option might be to let the test pass for phantomjs version 1, meaning you check it in the beginning of the test and then just return if that is the case. You can get the major version from the _current browsers desired capabilities_.
</blockquote></details>

`getDesiredCapabilities().getVersion()` gives me an empty string for my local phantomjs.
So I don't know how to check against the version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Comment by pleku** [comment]
Reviewed 2 of 61 files at r1, 6 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8121)*

**Pull request merged**
