### PR TITLE
Add `closable` style to Error Nofitications

### PR DESCRIPTION
**Pull request by jouni**
Partial fix to #8296 (Valo error type notifications missing close box
and docs are wrong)

This does **not** fix the documentation.

Add an additional stylename `critical-error` that styles the
notification like the Error-type, but without the close button.

Release notes should instruct users to use the new
`ValoTheme.NOTIFICATION_CRITICAL_ERROR` style if they have used the
previous `ValoTheme.NOTIFICATION_ERROR` style and don’t want to have
the close button added to those notifications.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8903)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8903#-KfpbcsJuHq7ynmiBVNm:-KfpbcsM-PST_vSZh3KI:b928a25) (no related file):*
Blocking this for now until this PR has the screenshot changes and documentation fixes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8903)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8903)*

**Comment by pleku** [comment]
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8903#-KfpbcsJuHq7ynmiBVNm:-KgDtqWKdJ1dZ1OXvV_j:bzachdt) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Blocking this for now until this PR has the screenshot changes and documentation fixes
</blockquote></details>

No screenshot changes, docs updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8903)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8903)*

**Pull request merged**
