### PR TITLE
Fix for PushLargeData test.

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8019)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Dzr1gWVPoSO8L2-F:-KZ6Dzr1gWVPoSO8L2-G:bvhkm0y) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L124)):*
> ```Java
>             this.interval = interval;
>             this.duration = duration;
>             ui = UI.getCurrent();
> ```

Pass in constructor instead of using the threadlocal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Dzr1gWVPoSO8L2-F:-KZ6EDe3Kz8w2P2mbDs9:bjmgyz6) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L124)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Pass in constructor instead of using the threadlocal
</blockquote></details>

4 CTOR parameter......... :(
Well, mom ! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Dzr1gWVPoSO8L2-F:-KZ6El8hEG3h_hQ8AMzn:b6re928) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L124)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

4 CTOR parameter......... :(
Well, mom ! 
</blockquote></details>

Let it be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Dzr1gWVPoSO8L2-F:-KZ6Ei1m8ymHVJH4xkoT:b-3c4zpm) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L124)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Let it be.
</blockquote></details>

Why does UI.getCurrent even work here? Threadlocals should no longer be inherited to new threads?

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Ea7hUrcMu6AoX8L8:-KZ6Ea7hUrcMu6AoX8L9:b3zs60m) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L137)):*
> ```Java
>                     @Override
>                     public void run() {
>                         PushLargeData ui = (PushLargeData) UI.getCurrent();
> ```

This could also use the outer "ui"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 124 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Dzr1gWVPoSO8L2-F:-KZ6EpdGwKF_y2olFVZu:b-dpofsg) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L124)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Why does UI.getCurrent even work here? Threadlocals should no longer be inherited to new threads?
</blockquote></details>

Because the CTOR is called in the correct thread !

The previous version of the code was absolutely correct.
May be a bit ugly, yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8019#-KZ6Ea7hUrcMu6AoX8L8:-KZ6FSG4FtROVHnasBiC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/25e3bc63b1346501cf46f4a07751fa33a5463e5d/uitest/src/main/java/com/vaadin/tests/push/PushLargeData.java#L137)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This could also use the outer "ui"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8019)*

**Pull request merged**
