### PR TITLE
Add ability to set multiple drag data generators for any drag data type

### PR DESCRIPTION
**Pull request by wbadam**
Also contains changes from #9319 as there is no possibility of chaining PRs

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9321)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r5, 1 of 1 files at r6.
Review status: 5 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 175 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEwZtL6cbvW-rTb34a:-KkEwZtL6cbvW-rTb34b:b-vil0hc) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L175)):*
>      * Adds drag data provided by the generator functions set for this drag
>      * source

Does it add it to the drag sources ? Or should it set it for the event ? Or for the dataMap ?

This javadoc makes absolutely no sense when looking at the method implementation ...

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 191 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExNs_Ywv9u5T99yTe:-KkExNs_Ywv9u5T99yTf:b4ykk8z) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L191)):*
> dragData

`rowDragData`

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 193 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExmnmYATKA4rkwg3w:-KkExmnmYATKA4rkwg3x:bidx038) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L193)):*
> dataMap.get(type) == null

`dataMap.containsKey(type)`

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 315 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExJ9X4DbvYbAyGQrS:-KkExJ9X4DbvYbAyGQrT:bcvi1wr) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L315)):*
> getDragData

`getRowDragData`

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 256 at r6](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEsbFD4dxixMiscmFg:-KkEsbFD4dxixMiscmFh:bneai19) ([raw file](https://github.com/vaadin/framework/blob/227c1551868b4f870fbc6b9e51a75c7db3487b71/documentation/advanced/advanced-dragndrop.asciidoc#L256)):*
> ```AsciiDoc
> ----
> 
> The _drag data generator_ defines what data should be transferred with the given type when a row is dragged and dropped.
> ```

The order of the stuff in this chapter is confusing. Instead you should mention:

1. By default, what does the FW do for data transfer for each item, what format etc
2. What happens when multiselect is used
3. tell that the drag data can be customized with generators, as shown with code snippet
4. code snippet
5. mention how there can be multiple generators

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 259 at r6](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEr7gIaiW5WonhUr1c:-KkEr7gIaiW5WonhUr1d:b-7srwfk) ([raw file](https://github.com/vaadin/framework/blob/227c1551868b4f870fbc6b9e51a75c7db3487b71/documentation/advanced/advanced-dragndrop.asciidoc#L259)):*
> HTML5 DataTransfer's data parameter

HTML5 gives absolutely no value here, instead you could add a link like
```asciidoc
The item's data is passed on drag start with the https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData[dataTransfer.setData] method and is available for the drop target from the `dropevent`.
```

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragSource.java, line 74 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEu2ZyyC9hE1NklGcg:-KkEu2ZyyC9hE1NklGch:bxhgdgu) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/server/src/main/java/com/vaadin/ui/components/grid/GridDragSource.java#L74)):*
> ```Java
>             generatedValue.append(column.getValueProvider().apply(item));
>         });
> //        generatedValue.
> ```

misplaced comment

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 174 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEupF7lgAyWKZ29zed:-KkEupF7lgAyWKZ29zee:b7387uq) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L174)):*
> ```Java
>                             + event.getDropTargetRow().getLastName()
>                             + ", location=" + event.getDropLocation());
>                 }
> ```

Please also log the `application/json` data 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by wbadam** [comment]
Review status: 5 of 16 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 175 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEwZtL6cbvW-rTb34a:-KkFEdFSSvQJeotBluMx:b-smxeut) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L175)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>      * Adds drag data provided by the generator functions set for this drag
>      * source

Does it add it to the drag sources ? Or should it set it for the event ? Or for the dataMap ?

This javadoc makes absolutely no sense when looking at the method implementation ...
</blockquote></details>

Done.
Tried to simplify and clarify it. Is it better now?

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 191 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExNs_Ywv9u5T99yTe:-KkFEqm3xSOFyfxBd8FO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L191)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> dragData

`rowDragData`
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 193 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExmnmYATKA4rkwg3w:-KkFFCVDTZt1b7fejKHx:b-dxfjax) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L193)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> dataMap.get(type) == null

`dataMap.containsKey(type)`
</blockquote></details>

What if it does contain a key but the value is `null` for some reason? Then it would produce a NPE in the else clause.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 315 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExJ9X4DbvYbAyGQrS:-KkFFfnliDvdaNcxjvQ2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L315)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> getDragData

`getRowDragData`
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 256 at r6](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEsbFD4dxixMiscmFg:-KkFO0LZ01-P2Yw5n1Ki:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/227c1551868b4f870fbc6b9e51a75c7db3487b71/documentation/advanced/advanced-dragndrop.asciidoc#L256)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

The order of the stuff in this chapter is confusing. Instead you should mention:

1. By default, what does the FW do for data transfer for each item, what format etc
2. What happens when multiselect is used
3. tell that the drag data can be customized with generators, as shown with code snippet
4. code snippet
5. mention how there can be multiple generators
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 259 at r6](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEr7gIaiW5WonhUr1c:-KkFO9wl_rzFa6hAWHX4:b-ks4yg5) ([raw file](https://github.com/vaadin/framework/blob/227c1551868b4f870fbc6b9e51a75c7db3487b71/documentation/advanced/advanced-dragndrop.asciidoc#L259)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> HTML5 DataTransfer's data parameter

HTML5 gives absolutely no value here, instead you could add a link like
```asciidoc
The item's data is passed on drag start with the https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData[dataTransfer.setData] method and is available for the drop target from the `dropevent`.
```
</blockquote></details>

Removed since it is irrelevant. Important is that it is set as data transfer data.

---

*[server/src/main/java/com/vaadin/ui/components/grid/GridDragSource.java, line 74 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEu2ZyyC9hE1NklGcg:-KkFFsb_ow0QdL0oSYfl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/server/src/main/java/com/vaadin/ui/components/grid/GridDragSource.java#L74)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

misplaced comment
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java, line 174 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEupF7lgAyWKZ29zed:-KkFGEOSChVS3F3SRcK6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/uitest/src/main/java/com/vaadin/tests/components/grid/GridDragAndDrop.java#L174)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please also log the `application/json` data 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by pleku** [comment]
Reviewed 3 of 4 files at r9.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 193 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExmnmYATKA4rkwg3w:-KkFQrczGHAGOoScpkdR:b-5eoh8j) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L193)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

What if it does contain a key but the value is `null` for some reason? Then it would produce a NPE in the else clause.
</blockquote></details>

It should be never possible to set `null` as the data for some type, for any row. If you suspect such, you should always make it clear in code with e.g. comments instead of answering in review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by pleku** [comment]
Reviewed 1 of 4 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 175 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEwZtL6cbvW-rTb34a:-KkFRNHXi9GF-P-s1Nxd:b-ellp1s) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L175)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Done.
Tried to simplify and clarify it. Is it better now?
</blockquote></details>

it should be _to the given map_, but see later comment

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 210 at r9](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFR_cv0KiecN1kD9ZD:-KkFR_cv0KiecN1kD9ZE:bmkd7n0) ([raw file](https://github.com/vaadin/framework/blob/2cdfd0e074d20c33821746e23987906a514039be/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L210)):*
> dataMap
>      *         Map of type/data pairs to be set for the {@code DataTransfer}
>      *         object.

this mentions nothing that the data should be written to this map, why is this even given instead of forcing the user to return the data in some format (like the map) ??

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 213 at r9](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFRUaZ-BNlfzwoNFsZ:-KkFRUaZ-BNlfzwoNFs_:bxmfa35) ([raw file](https://github.com/vaadin/framework/blob/2cdfd0e074d20c33821746e23987906a514039be/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L213)):*
> Event to set the data for

this gives out the impression that I should in this method set the data myself to this event

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 175 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkEwZtL6cbvW-rTb34a:-KkFeY3DwsDG4FqKFJPA:bsa0l0a) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L175)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

it should be _to the given map_, but see later comment
</blockquote></details>

Done. Refactored

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 193 at r5](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkExmnmYATKA4rkwg3w:-KkFeIgMRxu4JfnKwpna:b-jdn0ul) ([raw file](https://github.com/vaadin/framework/blob/e0080e10947bc2cbdd4cf25b496feff86ef98c48/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L193)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

It should be never possible to set `null` as the data for some type, for any row. If you suspect such, you should always make it clear in code with e.g. comments instead of answering in review
</blockquote></details>

Done. Shouldn't happen

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 210 at r9](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFR_cv0KiecN1kD9ZD:-KkFeO2de2VhgBTtVXcp:bsa0l0a) ([raw file](https://github.com/vaadin/framework/blob/2cdfd0e074d20c33821746e23987906a514039be/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L210)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> dataMap
>      *         Map of type/data pairs to be set for the {@code DataTransfer}
>      *         object.

this mentions nothing that the data should be written to this map, why is this even given instead of forcing the user to return the data in some format (like the map) ??
</blockquote></details>

Done. Refactored

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 213 at r9](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFRUaZ-BNlfzwoNFsZ:-KkFe64_tAY8AFpOalBd:bff5oig) ([raw file](https://github.com/vaadin/framework/blob/2cdfd0e074d20c33821746e23987906a514039be/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L213)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> Event to set the data for

this gives out the impression that I should in this method set the data myself to this event
</blockquote></details>

Done.
True, changed javadoc, refactored the method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by pleku** [comment]
Reviewed 3 of 8 files at r1, 6 of 7 files at r2, 1 of 2 files at r3, 1 of 3 files at r7, 1 of 2 files at r10.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 260 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFmwuVGMrSu_7hDAfC:-KkFmwuWJrgw78f6uJSA:b-z3mopi) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L260)):*
> ```Java
>      * @param dragStartEvent
>      *         The drag start event
>      */
> ```

missing `@return the map from type to data, or <code>null</code> to not set any data, which will cancel the drag start`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by pleku** [comment]
Reviewed 1 of 2 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 205 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFo3SR2Mqw1jvay9M7:-KkFo3SR2Mqw1jvay9M8:br8889x) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L205)):*
> ```Java
> 
>     /**
>      * Adds drag data provided by the generator functions to the data map.
> ```

This is a bit outdated now that you've changed the way it works in parent

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 211 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFo6u-eF-9XqMNayDv:-KkFo6u-eF-9XqMNayDw:b4y3l0m) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L211)):*
> ```Java
>      * @param dragStartEvent
>      *         The drag start event.
>      * @see GridDragSource#setDragDataGenerator(String, SerializableFunction)
> ```

missing `@return`, not sure if you really should still override this javadocs from parent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 205 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFo3SR2Mqw1jvay9M7:-KkFo_qJ6VDFW0B9Wqxb:b859t73) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L205)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is a bit outdated now that you've changed the way it works in parent
</blockquote></details>

Right, I actually think there is no need for any javadoc any more, the inherited should pretty much explain what's going on here.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 211 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFo6u-eF-9XqMNayDv:-KkFon8WA9V5i9eqVrf8:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L211)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing `@return`, not sure if you really should still override this javadocs from parent
</blockquote></details>

See above

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 260 at r10](https://reviewable.io:443/reviews/vaadin/framework/9321#-KkFmwuVGMrSu_7hDAfC:-KkFpb584x2Qh9fZOAbF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d061643795c8b7a96880d63e88f5973f19f5e7ca/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L260)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing `@return the map from type to data, or <code>null</code> to not set any data, which will cancel the drag start`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9321)*

**Pull request merged**
