### PR TITLE
Issue3922disableditem

### PR DESCRIPTION
**Pull request by Ansku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10259)

### CODE REVIEW

**Comment by torok-peter** [comment]
Looks good to me, nevertheless I would like @tsuoanttila to have a look before merging.

---

Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 994 at r3](https://reviewable.io:443/reviews/vaadin/framework/10259#-Ky_N_VS0i9eVXUjDTy4:-Ky_N_VS0i9eVXUjDTy5:b7ls321) ([raw file](https://github.com/vaadin/framework/blob/6230459c8507b367dd1465f23af0f6c178c9162c/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L994)):*
> ```Java
>                 } else {
>                     getElement().setAttribute("aria-disabled", "true");
>                 }
> ```

Code is duplicate of part of `VMenuBar.updateStyleNames()` above - could be extracted into a common method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259#-:-KyaD8s3YZW8h3SQsbHO:b-n4oikx)*

**Comment by torok-peter** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10259#-KyaT7JHZJac7MoAA-xN:-KyaT7JHZJac7MoAA-xO:bgjmkyk) (no related file):*
I mean, wait for Teemu to approve it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10259#-KyaT7JHZJac7MoAA-xN:-Kz87EKQ94k5-hIp2Eek:b-q0gy4t) (no related file):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

I mean, wait for Teemu to approve it.
</blockquote></details>

Seems fine by me. Needs rebase though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259)*

**Comment by torok-peter** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259#-:-Kz89pqnurmiS-a1Y87J:bnfp4nl)*

**Comment by caalador** [comment]
Reviewed 1 of 2 files at r6, 2 of 3 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10259)*

**Pull request merged**
