### PR TITLE
Use lambda expressions.

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10268)

### CODE REVIEW

**Comment by asashour** [comment]
Hi All,  I believe there is a something wrong on the build server, which may be related to the recent commits, but I am not sure if there are other configuration changes done as well.

`CalendarNavigationTest.calendarNavigation_backAndForwardInWeekView_navigationWorks` now fails, no matter which commit is done.

I am trying to locally investigate.

**Comment by pekam** [comment]
Reviewed 108 of 538 files at r1.
Review status: 108 of 538 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/TestForUpload.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxluWxcA_4ILj4h_jkC:-KxluWxcA_4ILj4h_jkD:bpmtqa0) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/TestForUpload.java#L61)):*
> ```Java
>     private final Upload up;
> 
>     private final Label l = new Label("Idle");
> ```

I wouldn't just automatically move these object initializations from constructor to here, because
 1. It may be less readable (like in this case, I'd like to see from the code part where the label is added, that what text it contains)
2. It's not related to this PR's task anyway

This is done in many places but I add only this one comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10268)*

**Comment by pekam** [comment]
Reviewed 157 of 538 files at r1.
Review status: 265 of 538 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10268)*

**Comment by pekam** [comment]
Reviewed 273 of 538 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/LoadingIndicatorConfigurationTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmAhdS8M6tAiEyGwFa:-KxmAhdS8M6tAiEyGwFb:b-wa28su) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/ui/LoadingIndicatorConfigurationTest.java#L34)):*
> ```Java
>                 getState().loadingIndicatorConfiguration.firstDelay);
>         firstDelay.addValueChangeListener(
>                 value -> getLoadingIndicatorConfiguration().setFirstDelay(
> ```

Why would you name a `ValueChangeEvent` to `value` instead of `event`?

Same for the two cases below.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/UriFragment.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmC8z20jSI4jiu-LLk:-KxmC8z20jSI4jiu-LLl:bjvvu7p) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/ui/UriFragment.java#L19)):*
> ```Java
>         addComponent(fragmentLabel);
>         updateLabel();
>         getPage().addUriFragmentChangedListener(even -> updateLabel());
> ```

Typo: `even`

---

*[uitest/src/main/java/com/vaadin/tests/components/uitest/UIScrolling.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmCWpzFH37y3SjkT52:-KxmCWpzFH37y3SjkT53:b-b6o2hl) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/uitest/UIScrolling.java#L19)):*
> ```Java
>         addComponent(new Button(
>                 "This button is halfway down. Click to report scroll position.",
>                 event->Notification.show("Scrolled to "
> ```

Add whitespace around `->`

---

*[uitest/src/main/java/com/vaadin/tests/fieldgroup/BasicCrudTable.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmFL4o0_GPd_KLjagH:-KxmFL4o0_GPd_KLjagI:bhdzqmw) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/fieldgroup/BasicCrudTable.java#L36)):*
> ```Java
> 
>         table.setVisibleColumns((Object[]) columns);
>         table.addValueChangeListener(value -> form.edit(
> ```

Why name `value` for an event?

---

*[uitest/src/main/java/com/vaadin/tests/integration/EmbedSizeTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmGNMGyna8lCK4CNLB:-KxmGNMGyna8lCK4CNLC:b7hvuwv) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/integration/EmbedSizeTest.java#L28)):*
> ```Java
> 
>         addComponent(log);
>         mainWindow.getPage().addBrowserWindowResizeListener(
> ```

Why is this changed? I would think it's a different thing to add the listener to a window and to add it to a page.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxScrollingWithArrowsTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmKa9QruUg8723TD_p:-KxmKa9QruUg8723TD_q:bjxy50l) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxScrollingWithArrowsTest.java#L96)):*
> ```Java
> 
>     private void waitUntilNextPageIsVisible() {
>         waitUntil(inpu -> getSelectedItemText().equals("item " + PAGESIZE), 5);
> ```

Typo: `inpu`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10268)*

**Comment by asashour** [comment]
Review status: 521 of 538 files reviewed at latest revision, 7 unresolved discussions.

---

*[uitest/src/main/java/com/vaadin/tests/TestForUpload.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxluWxcA_4ILj4h_jkC:-KxqfdqraWR31hqtGWTo:b-49iooo) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/TestForUpload.java#L61)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I wouldn't just automatically move these object initializations from constructor to here, because
 1. It may be less readable (like in this case, I'd like to see from the code part where the label is added, that what text it contains)
2. It's not related to this PR's task anyway

This is done in many places but I add only this one comment.
</blockquote></details>

Actually, there is a reason. Using a field in lambda expression, requires initializing the field first.

In this test case, there are other components constructed with the declaration.

Anyhow, it is now changed, I hope it looks better.

Please point other places if you feel the lambda change doesn't add a value, and it will be reverted.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/LoadingIndicatorConfigurationTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmAhdS8M6tAiEyGwFa:-KxqgS2jxLiEL8ff2b1n:b-fykrev) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/ui/LoadingIndicatorConfigurationTest.java#L34)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why would you name a `ValueChangeEvent` to `value` instead of `event`?

Same for the two cases below.
</blockquote></details>

It seems I didn't focus, and was influenced by 'ValueChangeEvent'.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/UriFragment.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmC8z20jSI4jiu-LLk:-KxqkqIo_60Mkp25CkrX:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/ui/UriFragment.java#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Typo: `even`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/uitest/UIScrolling.java, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmCWpzFH37y3SjkT52:-KxqiaSPhKtpC4sAaSJn:b-929gn6) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/components/uitest/UIScrolling.java#L19)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Add whitespace around `->`
</blockquote></details>

Done.Another bug eclipse, of not formatting changed line.

---

*[uitest/src/main/java/com/vaadin/tests/fieldgroup/BasicCrudTable.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmFL4o0_GPd_KLjagH:-KxqiqbE-6BYUlRO1TFQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/fieldgroup/BasicCrudTable.java#L36)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why name `value` for an event?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/integration/EmbedSizeTest.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmGNMGyna8lCK4CNLB:-KxqjIzxGItF81rezZfE:b-t1syky) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/main/java/com/vaadin/tests/integration/EmbedSizeTest.java#L28)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Why is this changed? I would think it's a different thing to add the listener to a window and to add it to a page.
</blockquote></details>

Actually, in this particular case, `LegacyWindow.addListener(BrowserWindowResizeListener)` calls `window.getPage().addBrowserWindowResizeListener`.

And it is a deprecated usage, since its javadoc mentions:

    @deprecated As of 7.0, use the similarly named api in Page instead

So, this is now the correct new way of using the `BrowserWindowResizeListener`.

Not using it will make us need to cast the lambda expression to a particular Listener:


    mainWindow.addListener((Page.BrowserWindowResizeListener)
        event -> log.log("Resize event: " + event.getWidth() + " x "

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxScrollingWithArrowsTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/10268#-KxmKa9QruUg8723TD_p:-KxqkPJpZzdNDr87LlMx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/402566ffcb9e65246a9621372ac26377c62a7f72/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxScrollingWithArrowsTest.java#L96)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Typo: `inpu`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10268)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10268#-:-KxquPG5DtuJJ7R0dORv:bnfp4nl)*

**Pull request merged**
