### PR TITLE
Make it possible for GridDropTarget to accept dragged data when Grid is empty

### LINKED ISSUE #9068: Make it possible for GridDropTarget to accept dragged data when Grid is empty
Currently drop event listeners are added to rows and so an empty Grid cannot accept them.
Perhaps add listeners to the Grid body element when no rows are present.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #9068

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9090)

### CODE REVIEW

**Comment by wbadam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9090#-Khle7MIpjfWNo0UT6sC:-Khle7MIpjfWNo0UT6sD:b-25sd2j) (no related file):*
This will also need some styling/UX design.

Also, consider changing the API so that `GridDropEvent.getDropTargetRow()` returns `Optional` instead, since this way a row isn't always present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9090)*

**Comment by hesara** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9090#-Khle7MIpjfWNo0UT6sC:-KiE46zubRaeKjAHOc1L:b-xox5ui) (no related file):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

This will also need some styling/UX design.

Also, consider changing the API so that `GridDropEvent.getDropTargetRow()` returns `Optional` instead, since this way a row isn't always present.
</blockquote></details>

please contact Jouni about theming/styling/UX

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/9090#-KiE4KjvzA-Vgz59B7PD:-KiE4KjvzA-Vgz59B7PE:br2jale) ([raw file](https://github.com/vaadin/framework/blob/85a2c78b524b23080ceaaec655c00865da93b946/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L87)):*
> ```Java
>         addDropListeners(getDropTargetElement());
> 
>         /* Add style for indicating drop target. Updated automatically when
> ```

how is this updated automatically?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9090)*

**Comment by wbadam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 87 at r1](https://reviewable.io:443/reviews/vaadin/framework/9090#-KiE4KjvzA-Vgz59B7PD:-KiWY1Ny5Y7NReAdDY3j:b-g9xpdh) ([raw file](https://github.com/vaadin/framework/blob/85a2c78b524b23080ceaaec655c00865da93b946/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L87)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

how is this updated automatically?
</blockquote></details>

Styles that have the primary style name as prefix are automatically updated by GWT in the `UIObject.updatePrimaryAndDependentStyleNames()` method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9090)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9090#-Ki_6SzDJyKD8GSu2Sto:-Ki_6SzDJyKD8GSu2Stp:b-sqoswb) (no related file):*
For the time being, you should update the javadocs for the `GridDropEvent.getDropTargetRow` to mention what happens if there is no rows in the grid, is the drop target row `null` ?

---

*[themes/src/main/themes/VAADIN/themes/valo/components/_grid.scss, line 820 at r1](https://reviewable.io:443/reviews/vaadin/framework/9090#-Ki_5QIuLQVj8aSMiKEZ:-Ki_5QIuLQVj8aSMiKE_:b-r6rpr) ([raw file](https://github.com/vaadin/framework/blob/85a2c78b524b23080ceaaec655c00865da93b946/themes/src/main/themes/VAADIN/themes/valo/components/_grid.scss#L820)):*
> ```SCSS
> 
>   // Drag and drop
>   .#{$primary-stylename}-body-droptarget {
> ```

Shouldn't this apply only to an empty grid ? Or is it needed always?

Have you verified that this doesn't break anything else in grid in all the browsers? Like column reordering or resizing DND ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9090)*

**Comment by pleku** [comment]
Closed since replaced by #9332

**Pull request closed without merging**
