### PR TITLE
clarified theme compilation instructions

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Paragraph about existing `styles.css` file needed a bit of rephrasing.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9685)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/themes/themes-compiling.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/9685#-Kr5oxexNCFlhhgKyPXT:-Kr5oxexNCFlhhgKyPXU:b-azp8h6) ([raw file](https://github.com/vaadin/framework/blob/5f5dd20b959eb188023b9c21e80689457ebbf2db/documentation/themes/themes-compiling.asciidoc#L33)):*
> ```AsciiDoc
> NOTE: If the on-the-fly compilation does not seem to work, ensure that your build script has not generated a pre-compiled CSS file.
> If a [filename]#styles.css# file is found by the servlet, the compilation is skipped.
> Delete such an existing [filename]#styles.css# file, disable theme compilation temporarily and re-enable it to start on-the-fly compilation again.
> ```

Why re-enable in cases where you want to use on-the-fly compilation, which relies on the file not being present?
(Note that on-the-fly theme compilation uses a separate file as the cached content.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9685)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/themes/themes-compiling.asciidoc, line 33 at r1](https://reviewable.io:443/reviews/vaadin/framework/9685#-Kr5oxexNCFlhhgKyPXT:-Kr61drsM_6jdDNliGHt:bfztw0u) ([raw file](https://github.com/vaadin/framework/blob/5f5dd20b959eb188023b9c21e80689457ebbf2db/documentation/themes/themes-compiling.asciidoc#L33)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why re-enable in cases where you want to use on-the-fly compilation, which relies on the file not being present?
(Note that on-the-fly theme compilation uses a separate file as the cached content.)
</blockquote></details>

I don't know. I didn't understand this instruction before and I tried to make it more readable, but apparently that didn't go right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9685)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/themes/themes-compiling.asciidoc, line 33 at r2](https://reviewable.io:443/reviews/vaadin/framework/9685#-Kr9thPlPVwRhgnUpA5b:-Kr9thPlPVwRhgnUpA5c:b3bkbpf) ([raw file](https://github.com/vaadin/framework/blob/62b4a46cb7a6d7e6ec37b15ce1e35be5b56f4161/documentation/themes/themes-compiling.asciidoc#L33)):*
> team
theme

---

*[documentation/themes/themes-compiling.asciidoc, line 33 at r2](https://reviewable.io:443/reviews/vaadin/framework/9685#-Kr9tlUJsDW8FCsfZQ9Y:-Kr9tlUJsDW8FCsfZQ9Z:b-kl7am6) ([raw file](https://github.com/vaadin/framework/blob/62b4a46cb7a6d7e6ec37b15ce1e35be5b56f4161/documentation/themes/themes-compiling.asciidoc#L33)):*
> encironment
environment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9685)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9685#-:-Kr9wrkh8mTnFi5woVXf:bnfp4nl)*

**Pull request merged**
