### PR TITLE
Support loading of HTML imports using @HtmlImport

### PR DESCRIPTION
**Pull request by Artur-**
Note that not all browsers yet support HTML imports. If a polyfill
is needed to load HTML imports, it must be loaded before HTML Imports
can be loaded. There is no automatic loading of any polyfills.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8301)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-Kb9dqTHXZPfHxUVo3Y-:-Kb9dqTI8wPPz_kDpS8j:b2a1xek) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L52)):*
> ```Java
>  * http://host.com/VAADIN/bower_components/paper-slider/paper-slider.html before
>  * the {@code init()} method of the client side connector is invoked.
>  *
> ```

Should also document the need for a polyfill if support is needed for older browsers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-Kb9dqTHXZPfHxUVo3Y-:-KbA7Fzhx5FsQ2dsHWpQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L52)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should also document the need for a polyfill if support is needed for older browsers?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by denis-anisimov** [comment]
Reviewed 21 of 22 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 73 at r2](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8IgIGQOjlEBtVLY7:-KbA8IgIGQOjlEBtVLY8:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/892802ea518055cc4cf362d61b298e518b4758cf/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L73)):*
> ```Java
>      */
>     String[] value();
> }
> ```

new line

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8Yzb9Te2OaXy_zMH:-KbA8Yzb9Te2OaXy_zMI:b-7ztd11) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java#L36)):*
> ```Java
> @Target(ElementType.TYPE)
> @Documented
> public @interface InternalContainerAnnotationForHtml {
> ```

Shouldn't it be package local ?

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8MFsnvCGhxROWkak:-KbA8MFt-AjmGaItj__h:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java#L45)):*
> ```Java
>      */
>     HtmlImport[] value();
> }
> ```

new line

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8fWUAJKjKUS0j9Yf:-KbA8fWUAJKjKUS0j9Yg:b-7ztd11) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java#L36)):*
> ```Java
> @Target(ElementType.TYPE)
> @Documented
> public @interface InternalContainerAnnotationForJS {
> ```

Shouldn't it be package local ?

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8jwJvOoM4CTFjNNT:-KbA8jwJvOoM4CTFjNNU:b-7ztd11) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java#L36)):*
> ```Java
> @Target(ElementType.TYPE)
> @Documented
> public @interface InternalContainerAnnotationForSS {
> ```

Shouldn't it be package local ?

---

*[server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 454 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbALcFDUR8-o_EUquT7:-KbALcFDUR8-o_EUquT8:boe7z32) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/server/BootstrapHandler.java#L454)):*
> ```Java
>         }
> 
>         HtmlImport[] htmlImportAnnotations = uiClass
> ```

3 blocks of identical code except parameters: annotation type and some string values.
Can it be extracted to one parameterized method and called 3 times ?

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 306 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbALvR27xQRSoK6KM1R:-KbALvR27xQRSoK6KM1S:b-x52q8r) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L306)):*
> ```Java
>                     }
>                 }
>                 HtmlImport[] htmlImportAnnotations = class1
> ```

And again 3 similar code blocks.

---

*[uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAM5dWqsSrtnPanX9Q:-KbAM5dWqsSrtnPanX9R:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java#L30)):*
> ```Java
>     }
> 
> }
> ```

new line

---

*[uitest/src/main/resources/com/vaadin/tests/htmlimport/label.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAM8TJZ3Ae-THOLP_g:-KbAM8TJZ3Ae-THOLP_h:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/resources/com/vaadin/tests/htmlimport/label.html#L10)):*
> ```HTML
> </script>
> </head>
> </html>
> ```

new line

---

*[uitest/src/main/resources/com/vaadin/tests/htmlimport/ui.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAMB3oI5_Wipg0ZRp5:-KbAMB3oI5_Wipg0ZRp6:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/resources/com/vaadin/tests/htmlimport/ui.html#L10)):*
> ```HTML
> </script>
> </head>
> </html>
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: 8 of 26 files reviewed at latest revision, 11 unresolved discussions.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 73 at r2](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8IgIGQOjlEBtVLY7:-KbATXXSzyFiDdvVkgUx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/892802ea518055cc4cf362d61b298e518b4758cf/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L73)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8Yzb9Te2OaXy_zMH:-KbAThVy2rRnjt9xSqzM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Shouldn't it be package local ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8MFsnvCGhxROWkak:-KbATmCPjgLGGAmv5P_H:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForHtml.java#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8fWUAJKjKUS0j9Yf:-KbATmqNw949afnqBjUO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForJS.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Shouldn't it be package local ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8jwJvOoM4CTFjNNT:-KbATnsbEhboETzJnnHF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Shouldn't it be package local ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/BootstrapHandler.java, line 454 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbALcFDUR8-o_EUquT7:-KbAZVjY5U_j7EYKdkwh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/server/BootstrapHandler.java#L454)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

3 blocks of identical code except parameters: annotation type and some string values.
Can it be extracted to one parameterized method and called 3 times ?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 306 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbALvR27xQRSoK6KM1R:-KbAZWfV2K-VIJsBArCe:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L306)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

And again 3 similar code blocks.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAM5dWqsSrtnPanX9Q:-KbAW3czB8QeNGtKvAdc:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java#L30)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[uitest/src/main/resources/com/vaadin/tests/htmlimport/label.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAM8TJZ3Ae-THOLP_g:-KbAWBokWcckiJ7DkAp3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/resources/com/vaadin/tests/htmlimport/label.html#L10)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[uitest/src/main/resources/com/vaadin/tests/htmlimport/ui.html, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAMB3oI5_Wipg0ZRp5:-KbAWBUDEiaUO0gzNiGN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/uitest/src/main/resources/com/vaadin/tests/htmlimport/ui.html#L10)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: 8 of 26 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAa1YTZwOKiw1kle4e:-KbAa1YTZwOKiw1kle4f:bbv29w8) (no related file):*
Waiting for #8293 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by denis-anisimov** [comment]
Reviewed 18 of 19 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 294 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbt-ZiDxlcyoG97sT:-KbAbt-ZiDxlcyoG97sU:b-sqkbou) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L294)):*
> ```Java
>             List<Dependency> dependencies = new ArrayList<>();
> 
>             for (Class<? extends ClientConnector> class1 : newConnectorTypes) {
> ```

Out of the scope of this PR but still: `class1` (so there is `class2` ?).
Could you please change it to something like `clazz` ?

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 298 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbai8GA9hI2Dn3ALY:-KbAbai8GA9hI2Dn3ALZ:b-jk3btw) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L298)):*
> ```Java
>                         .findAnnotatedResources(JavaScript.class, class1);
>                 javascripts.forEach(resource -> {
>                     String url = manager.registerDependency(resource, class1);
> ```

These 3 lambdas still can be extracted to one method where dependency type is a parameter (along with `resource` , `class1` and `url`.

---

*[server/src/main/java/com/vaadin/ui/Dependency.java, line 101 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAeDh0mUl_co4U7laA:-KbAeDh0mUl_co4U7laB:b-u92q6) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/ui/Dependency.java#L101)):*
> ```Java
>             for (Annotation annotation : annotations) {
>                 String[] resources;
>                 if (annotation.annotationType() == StyleSheet.class) {
> ```

Replace with reflection ?

```
Method method = annotation.annotationType().getMethod("value");
method.invoke(annotation));

```

---

*[uitest/src/main/resources/com/vaadin/tests/components/ui/uiDependency.js, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAeVxjUuarLJ0XWiAY:-KbAeVxjUuarLJ0XWiAZ:b1h5th7) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/uitest/src/main/resources/com/vaadin/tests/components/ui/uiDependency.js#L34)):*
> ```JavaScript
> 		document.getElementById("statusBox").innerHTML = status;
> 	}
> })();
> ```

not a new issue , but: new line please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Dependency.java, line 101 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAeDh0mUl_co4U7laA:-KbAzYUXHStuECOQgi45:bre5l1b) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/ui/Dependency.java#L101)):*
> Replace with reflection ?

IMHO not worthwhile. It would shorten the code by a couple of lines, but it would instead make it less obvious and more fragile.

On the other hand, I'd suggest testing e.g. `annotation instanceof StyleSheet` instead of checking the annotation type class literal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbERyBKE88vtIh-Hua9:-KbERyBLEEyzL0IhUmi9:b-fqxhq6) (no related file):*
Should mention this new feature in the release notes.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbES7CBNoS5AmoFOmpV:-KbES7CBNoS5AmoFOmpW:b-u5geta) (no related file):*
Should write something about this new feature in some suitable part of `/documentation/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: 24 of 28 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbERyBKE88vtIh-Hua9:-KbF0st9Gsp3cYs1dVGY:b-14qnfi) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Should mention this new feature in the release notes.
</blockquote></details>

Done, assuming the release-notes in the project are still used

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbES7CBNoS5AmoFOmpV:-KbF21AXEo1NJKi0RFFn:b-joc2gd) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Should write something about this new feature in some suitable part of `/documentation/`
</blockquote></details>

Mentioned in the same place as `@StyleSheet` is mentioned.. What would make sense to have is `integrating a web component` but that requires some more work than this PR 

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 294 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbt-ZiDxlcyoG97sT:-KbF1gIqM5k4JTjx0UYD:bh76syf) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L294)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Out of the scope of this PR but still: `class1` (so there is `class2` ?).
Could you please change it to something like `clazz` ?
</blockquote></details>

It should be `class1` because this is a first class class. There is no room for second class classes in this great framework. We only have the greatest classes of them all

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 298 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbai8GA9hI2Dn3ALY:-KbF2QaCE-37jz7PnChw:bwoi0h2) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L298)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

These 3 lambdas still can be extracted to one method where dependency type is a parameter (along with `resource` , `class1` and `url`.
</blockquote></details>

yes, but the end result would probably not be any easier to read

---

*[uitest/src/main/resources/com/vaadin/tests/components/ui/uiDependency.js, line 34 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAeVxjUuarLJ0XWiAY:-KbF2hsOOftqNnoHUbxO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/uitest/src/main/resources/com/vaadin/tests/components/ui/uiDependency.js#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

not a new issue , but: new line please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 298 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbai8GA9hI2Dn3ALY:-KbF52sJJeZdOF7r-L7X:b-p7x32w) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L298)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

yes, but the end result would probably not be any easier to read
</blockquote></details>

It removes the code duplication.
So in the future only one method will require to be changed (if any).
Otherwise any new line (e.g.) has to added to the each block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: 23 of 32 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 298 at r3](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbAbai8GA9hI2Dn3ALY:-KbFfeBqdPFSiCwY_St6:bhl48y4) ([raw file](https://github.com/vaadin/framework/blob/62656a5b9944c5016f590b73f448a631bafd224b/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L298)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It removes the code duplication.
So in the future only one method will require to be changed (if any).
Otherwise any new line (e.g.) has to added to the each block.
</blockquote></details>

That is based on pure speculation about how this might evolve in the future. Anyway, the functionality is now in `Dependency` instead of here, and is a bit simpler

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by denis-anisimov** [comment]
Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8jwJvOoM4CTFjNNT:-KbFj96bCumM4Yqnai9X:b-ts6oak) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java#L36)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually not. It works in Eclipse but not with `javac`:

```[15:53:02][Step 2/3] [ERROR] .../uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java:[10,1] value() in com.vaadin.annotations.InternalContainerAnnotationForJS is defined in an inaccessible class or interface```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*
<!-- Sent from Reviewable.io -->

**Comment by denis-anisimov** [comment]
Reviewed 3 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-KbA8jwJvOoM4CTFjNNT:-KbFoSpcq-UXJvLgmZ3m:b-2ssqff) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/InternalContainerAnnotationForSS.java#L36)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Actually not. It works in Eclipse but not with `javac`:

```[15:53:02][Step 2/3] [ERROR] .../uitest/src/main/java/com/vaadin/tests/htmlimport/HtmlImportUI.java:[10,1] value() in com.vaadin.annotations.InternalContainerAnnotationForJS is defined in an inaccessible class or interface```

</blockquote></details>

Cool. I thought we did it in HB....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-Kb9dqTHXZPfHxUVo3Y-:-KbATW4wPwa91pOrF6G5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L52)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/annotations/HtmlImport.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8301#-Kb9dqTHXZPfHxUVo3Y-:-KbJwAfIyW6uF24h4-rU:b-9pt2xo) ([raw file](https://github.com/vaadin/framework/blob/23ebffda51619f112e3344ecb34d12f652e50175/server/src/main/java/com/vaadin/annotations/HtmlImport.java#L52)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't count until it reaches 10 `done`s. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8301)*

**Pull request merged**
