### PR TITLE
Issue #11459: Provide extensive error information on GridLayout.OutOf…

### LINKED ISSUE #11459: GridLayout fails with unspecific error messages
Vaadin framework 8.5.1, also 8.7.0. When adding components to a `GridLayout`, Vaadin may fail with `OutOfBoundsException`, which is a correct behavior. However, the error message is null and therefore it doesn't provide any insight as to why the problem occurs; example of such stacktrace:
```
com.vaadin.ui.GridLayout$OutOfBoundsException: null
	com.vaadin.ui.GridLayout.addComponent(GridLayout.java:211)
```

It would be great if the error message included the `area` and `getColumns()`/`getRows()`; we also need to define `Area.toString()` in order to be usable. I'll create a proposal PR.

### PR DESCRIPTION
**Pull request by mvysny**
…BoundsException and IllegalArgumentException

The patch provides more information when GridLayout.OutOfBoundsException or IllegalArgumentException is thrown.

Fixes #11459

**Check when you have completed**
[x] Valid tests for the pull request
[x] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11460)

### CODE REVIEW

**Comment by anasmi** [comment]
Hi @mvysny and thank you for your contribution! 

Would it be possible for you to use `String.format(..)` or is there any reason not to use it?

**Review by anasmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11460)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mvysny)

___
*[server/src/main/java/com/vaadin/ui/GridLayout.java, line 208 at r1](https://reviewable.io/reviews/vaadin/framework/11460#-LZ-0etvDzOhtN8gvGsa:-LZ-0etwEg0RmMsJyRrB:b-qxx0h2) ([raw file](https://github.com/vaadin/framework/blob/36f4d0fc7a24534eca1e97684fe74b2b14ed1d8b/server/src/main/java/com/vaadin/ui/GridLayout.java#L208)):*
> ```Java
>             throw new IllegalArgumentException(
>                     "Illegal coordinates for the component: " + column1 +
>                     "=<" + column2 + ", " + row1 + "=<" + row2);
> ```

First of all, thank you for your contribution! Through, maybe we could use` String.format(..)`?
___
*[server/src/main/java/com/vaadin/ui/GridLayout.java, line 617 at r1](https://reviewable.io/reviews/vaadin/framework/11460#-LZ-0iiD0V1O7VDsHE5Y:-LZ-0iiE5YVqblfXZq3b:b-jv0327) ([raw file](https://github.com/vaadin/framework/blob/36f4d0fc7a24534eca1e97684fe74b2b14ed1d8b/server/src/main/java/com/vaadin/ui/GridLayout.java#L617)):*
> ```Java
>         @Override
>         public String toString() {
>             return "Area{" + getColumn1() + "," + getRow1() + " - "
> ```

The same as above `String.format`
___
*[server/src/main/java/com/vaadin/ui/GridLayout.java, line 704 at r1](https://reviewable.io/reviews/vaadin/framework/11460#-LZ-0ltm2esm7GEzISpo:-LZ-0ltm2esm7GEzISpp:b999e5w) ([raw file](https://github.com/vaadin/framework/blob/36f4d0fc7a24534eca1e97684fe74b2b14ed1d8b/server/src/main/java/com/vaadin/ui/GridLayout.java#L704)):*
> ```Java
>         public OutOfBoundsException(Area areaOutOfBounds) {
>             super(areaOutOfBounds + ", layout dimension: " + getColumns() + "x"
>                     + getRows());
> ```

The same as the previous one

**Comment by mvysny** [comment]
No particular reason; refactored to use `String.format()` :)

**Comment by anasmi** [comment]
Thank you! :)

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11460)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by anasmi** [comment]
@mvysny I noticed just now ... (as I don't have merge right to 8.7 branch), could you re-submit the pull request to master branch?(I think every tagged branch is build on `top` of master)

**Comment by mvysny** [comment]
That sounds a bit unusual... nevermind, I've created a new PR: https://github.com/vaadin/framework/pull/11461

**Comment by anasmi** [comment]
The #11461 is merged, so I will close this one. Thank you, @mvysny for contribution! :)

**Comment by mvysny** [comment]
No problem, thank you for reviewing and merging! ;)

**Pull request closed without merging**
