### PR TITLE
Fix bean validation when using sub property bindings

### LINKED ISSUE #9242: BeanValidator always fails when binding sub properties
```
public class Order {
    	@NotNull
	@OneToOne
	private Customer customer;
}
public class Customer {
	@NotNull
	@NotEmpty
	private String firstName;
}
```

```
protected TextField firstName = new TextField();

BeanValidationBinder<Order> binder = new BeanValidationBinder<>(Order.class);
binder.bind(firstName, "customer.firstName");
```

causes
```
java.lang.IllegalArgumentException: HV000039: Invalid property path. Either there is no property firstName in entity the.Order or it is not possible to cascade to the property.
```
whenever anything is added to the field.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #9242

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9248)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 256 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMoFaTK5ucPmzF7wzC:-KjMoFaTK5ucPmzF7wzD:b-noj3fr) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L256)):*
> ```Java
>          * Gets the parent property definition.
>          *
>          * @return the property definition for the parent
> ```

@since would be good, apparently missing for the whole nested class so perhaps should be there

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMoVnLq3pigK9fedxw:-KjMoVnLq3pigK9fedxx:b-738cc6) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L114)):*
> ```Java
>      *            the root beanType
>      * @param definition
>      * @return
> ```

return what? @since

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-KjMpS8D96a53o51uX4N:b72xof5) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
> ```Java
> 
>         PropertyDefinition<BEAN, ?> def = definition;
>         while (def instanceof NestedBeanPropertyDefinition) {
> ```

why collect all the parents in a stack and then iterate over them rather than just keeping track of subBeanType in the first loop?

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpCjEh1I8BPnEbKGd:-KjMpCjEh1I8BPnEbKGe:b-2yxvfk) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L137)):*
> ```Java
>             PropertyDefinition<BEAN, ?> definition, BeanValidator validator) {
>         assert requiredConfigurator != null;
>         Class<?> propertyHolderType = definition.getPropertyHolderType();
> ```

test could also check that this is ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by Artur-** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 256 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMoFaTK5ucPmzF7wzC:-KjN6l1fMNt32GocfPMl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L256)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since would be good, apparently missing for the whole nested class so perhaps should be there
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMoVnLq3pigK9fedxw:-KjN27WCGJMFmuJTblYW:b-e585e9) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L114)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

return what? @since
</blockquote></details>

Do you need @since on private methods now also?

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-KjN2AVEDavlWXhSYRmR:b-nn7mj7) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

why collect all the parents in a stack and then iterate over them rather than just keeping track of subBeanType in the first loop?
</blockquote></details>

To reverse the order. Added a comment

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpCjEh1I8BPnEbKGd:-KjN6icrEa1jKsWLBQqh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L137)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

test could also check that this is ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-Kja_y1MwWLZQsULD8jw:bvil4wo) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

To reverse the order. Added a comment
</blockquote></details>

As we only extract one value (the last one in the stack, meaning the first one that was pushed in), it is still unclear to me why this cannot be done in a much simpler way without a stack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by Artur-** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-KjabocFgCu0sOEp-Nsz:b9ty2yu) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

As we only extract one value (the last one in the stack, meaning the first one that was pushed in), it is still unclear to me why this cannot be done in a much simpler way without a stack
</blockquote></details>

Multiple values are extracted for properties of type `main.sub.foo.bar.firstName` and the chain is iterated in reverse order to find the type of `bar`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by hesara** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-KjbafXnTakgm8a40jK9:b-88enn) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Multiple values are extracted for properties of type `main.sub.foo.bar.firstName` and the chain is iterated in reverse order to find the type of `bar`
</blockquote></details>

so what's the difference from this?
subBeanType = (definition instanceof NBPD) ? definition.getParent().getType() : beanType

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by Artur-** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanValidationBinder.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9248#-KjMpS8D96a53o51uX4M:-KjbeAZ6OYzGUeNqqjUn:bx8iqgc) ([raw file](https://github.com/vaadin/framework/blob/fefb5c14a5fb861576379a4fb2b37a229dc6823b/server/src/main/java/com/vaadin/data/BeanValidationBinder.java#L122)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

so what's the difference from this?
subBeanType = (definition instanceof NBPD) ? definition.getParent().getType() : beanType
</blockquote></details>

None, fixed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9248)*

**Pull request merged**
