### PR TITLE
V7 bugfix/8700 remove csrf token from get

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9150)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/communication/MessageHandler.java, line 1709 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4xrjmSYbxnNAM9c-Z:-Kr4xrjnmd1NwveXZeXK:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/client/src/main/java/com/vaadin/client/communication/MessageHandler.java#L1709)):*
> ```Java
>      * establishing a push connection with the client.
>      *
>      * @return the push connection identifier string
> ```

(ideally would have since tag, but was also missing in 8.x)

---

*[server/src/main/java/com/vaadin/server/VaadinSession.java, line 1418 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4xyXaF1MnKO-V544S:-Kr4xyXaF1MnKO-V544T:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/server/src/main/java/com/vaadin/server/VaadinSession.java#L1418)):*
> ```Java
>      * establishing a push connection with the client.
>      *
>      * @return the push connection identifier string
> ```

(ideally would have since tag, but was also missing in 8.x)

---

*[server/src/main/java/com/vaadin/server/communication/PushHandler.java, line 482 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4y-bo3ZoLj9Ixqk6F:-Kr4y-bo3ZoLj9Ixqk6G:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/server/src/main/java/com/vaadin/server/communication/PushHandler.java#L482)):*
> ```Java
>      * @param requestPushId
>      *            the push id provided in the request
>      * @return {@code true} if the id is valid, {@code false} otherwise
> ```

(ideally would have since tag, but was also missing in 8.x)

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 322 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4y1iQQEJafIaOSrqP:-Kr4y1iQQEJafIaOSrqQ:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L322)):*
> ```Java
>      * @param session
>      *            the vaadin session to which the security key belongs
>      * @return the push identifier UIDL
> ```

(ideally would have since tag, but was also missing in 8.x)

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4yDKS21kIIhn13BmS:-Kr4yDKS21kIIhn13BmT:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L52)):*
> ```Java
>     public static final String UIDL_SECURITY_TOKEN_ID = "Vaadin-Security-Key";
> 
>     public static final String UIDL_PUSH_ID = "Vaadin-Push-ID";
> ```

(ideally would have since tag, but was also missing in 8.x)

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4y5VA6B35Sb0BWanN:-Kr4y5VA6B35Sb0BWanO:bg6djs9) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L76)):*
> ```Java
>     public static final String URL_PARAMETER_REPAINT_ALL = "repaintAll";
> 
>     /**
> ```

this new constant does not belong to the pick

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 122 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4yBgr_2R7X8GJAfHr:-Kr4yBgr_2R7X8GJAfHs:b-a607xb) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L122)):*
> ```Java
> 
>     /**
>      * Name of the parameter used to transmit the push connection identifier.
> ```

(ideally would have since tag, but was also missing in 8.x)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9150)*

**Comment by hesara** [comment]
Some comments in reviewable (one blocking) + needs merge or rebase.

**Comment by hesara** [comment]
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/communication/MessageHandler.java, line 1709 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4xrjmSYbxnNAM9c-Z:-KrB6VORxxehOkYuENgx:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/client/src/main/java/com/vaadin/client/communication/MessageHandler.java#L1709)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(ideally would have since tag, but was also missing in 8.x)
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/server/communication/UIInitHandler.java, line 322 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4y1iQQEJafIaOSrqP:-KrB6AF4NuIMzGHY38i8:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/server/src/main/java/com/vaadin/server/communication/UIInitHandler.java#L322)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(ideally would have since tag, but was also missing in 8.x)
</blockquote></details>

Done

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 76 at r1](https://reviewable.io:443/reviews/vaadin/framework/9150#-Kr4y5VA6B35Sb0BWanN:-KrB6BZg92fSVW7TW6p5:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/6f44048c710bc40a977b7a7a78982bf408d761be/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L76)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this new constant does not belong to the pick
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9150)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9150#-:-KrB7pJbyLmwDX0HzSP7:bnfp4nl)*

**Pull request merged**
