### PR TITLE
Make cancellation of uploads work regardless of Push configuration

### LINKED ISSUE #11682: Upload: interruptUpload throws AssertionError
Vaadin Framework version: 8.8.5
Browser: any
Web container: any

Caused by the fix for #11616
Related issues: #4212 #9635

Sample project to reproduce the issue: https://github.com/willemv/vaadin-upload-bug

To reproduce:
* start a Vaadin-based application with assertions enabled (i.e. by adding the `-ea` JVM parameter)
* create an `Upload` button
* start uploading a file
* call the `interruptUpload` method on the upload button

Result: an `AssertionError` is thrown, because the `FileUploadHandler` tries to access the connector state outside of the session lock:

```
Jul 31, 2019 3:50:17 PM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.AssertionError: Session must be locked when getState() is called
	at com.vaadin.server.AbstractClientConnector.getState(AbstractClientConnector.java:264)
	at com.vaadin.ui.AbstractComponent.getState(AbstractComponent.java:676)
	at com.vaadin.ui.AbstractSingleComponentContainer.getState(AbstractSingleComponentContainer.java:364)
	at com.vaadin.ui.UI.getState(UI.java:340)
	at com.vaadin.ui.PushConfigurationImpl.getState(PushConfiguration.java:336)
	at com.vaadin.ui.PushConfigurationImpl.getPushMode(PushConfiguration.java:181)
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:621)
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:460)
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:413)
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:290)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
```
If you run _without_ assertions, the cancel simply doesn't work

### PR DESCRIPTION
**Pull request by willemv**
- Checking the push configuration outside of session lock threw
  an AssertionError, so the push configuration is not checked anymore.

- The original problem with cancelling Upload was due to a subtle
  ordering issue that depended on the Push configuration.
  In the case of PushMode.AUTOMATIC, a new StreamVariable was
  added by the `Upload` component _before_ the `FileUploadHandler`
  got a chance to remove the old `StreamVariable`. As a result, the
  `FileUploadHandler` actually removed the fresh `StreamVariable`,
  breaking future uploads.

Fixes #11682

[x] Valid tests for the pull request
[x] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11743)

### CODE REVIEW

**Comment by TatuLund** [comment]
I want to say thanks for the contribution and special thanks for the accompanying test cases.

**Review by TatuLund — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11743#-:-LqtmAtG7DLG9UyIK5xu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by willemv** [comment]
Any news on this?

**Comment by willemv** [comment]
Thanks ! :fireworks: :champagne:

**Comment by mstahv** [comment]
@willemv Getting back to this year old PR. There has been a bounty (50$) on an issue that was fixed by your PR: https://www.bountysource.com/issues/53900349-upload-interruptupload-restarts-the-upload-restarts-life-cycle-events 

You can claim that to your bountysource account. If you want, you can then cash it out or donate that to a project like Vaadin.

**Pull request merged**
