### PR TITLE
Correct behavior when binding with DateField

### LINKED ISSUE #11276: Binder does not update range values
Vaadin versions tested 8.4.5, 8.5.2

Manually entering 2018/10/25 in the first field, 2018/10/24 in the second and then 2018/10/22 in the first again. The expectation is that both date fields validate now.

binder

Example code

```
package com.vaadin;

import java.time.LocalDate;
import java.util.Objects;

import javax.servlet.annotation.WebServlet;

import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.Binder;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.UI;

@Theme("mytheme")
public class MyUI extends UI {

	InMemoryReceiver receiver = new InMemoryReceiver();

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		HorizontalLayout horizontalLayout = new HorizontalLayout();

		Binder<FromToModel> fromToModelBinder = new Binder<>();

		DateField fromField = new DateField();
		fromField.setDateFormat("yyyy/MM/dd");
		final Binder.Binding<FromToModel, LocalDate> fromBinding = fromToModelBinder.forField(fromField).asRequired()
				.bind(FromToModel::getFromDate, FromToModel::setFromDate);
		DateField toField = new DateField();
		toField.setDateFormat("yyyy/MM/dd");
		final Binder.Binding<FromToModel, LocalDate> toBinding = fromToModelBinder.forField(toField).asRequired()
				.bind(FromToModel::getToDate, FromToModel::setToDate);

		fromField.addValueChangeListener(e -> {
			toField.setRangeStart(e.getValue());
			if (toField.getValue() != null) {
				toBinding.validate();
			}
		});
		toField.addValueChangeListener(e -> {
			fromField.setRangeEnd(e.getValue());
			if (fromField.getValue() != null) {
				fromBinding.validate();
			}
		});

		horizontalLayout.addComponents(fromField, toField);
		setContent(horizontalLayout);
	}

	private static class FromToModel {

		private LocalDate fromDate;
		private LocalDate toDate;

		public LocalDate getFromDate() {
			return fromDate;
		}

		public void setFromDate(LocalDate fromDate) {
			this.fromDate = fromDate;
		}

		public LocalDate getToDate() {
			return toDate;
		}

		public void setToDate(LocalDate toDate) {
			this.toDate = toDate;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o)
				return true;
			if (!(o instanceof FromToModel))
				return false;
			FromToModel that = (FromToModel) o;
			return Objects.equals(getFromDate(), that.getFromDate()) && Objects.equals(getToDate(), that.getToDate());
		}

		@Override
		public int hashCode() {
			return Objects.hash(getFromDate(), getToDate());
		}
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}

```

### PR DESCRIPTION
**Pull request by ZheSun88**
Fixes #11276

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11292)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11292)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot and @ZheSun88)

___
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 879 at r1](https://reviewable.io/reviews/vaadin/framework/11292#-LQnQBQL82CYWiG4A3nM:-LQnQBQL82CYWiG4A3nN:b-jbvq2z) ([raw file](https://github.com/vaadin/framework/blob/0dafb052e75a8eddc9934d7584aa60a295c5f847/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L879)):*
> ```Java
>             @Override
>             public ValidationResult apply(T value, ValueContext context) {
>                 if (currentParseErrorMessage != null && currentParseErrorMessage!= dateOutOfRangeMessage) {
> ```

Looks very hackish to me. I have no clue how it works and what it fixes. Please add comments. `!=` of two strings might not work at all.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11292)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot)

___
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 879 at r1](https://reviewable.io/reviews/vaadin/framework/11292#-LQnQBQL82CYWiG4A3nM:-LQn_CBu7heWhoJXlM7G:b-qfpmdq) ([raw file](https://github.com/vaadin/framework/blob/0dafb052e75a8eddc9934d7584aa60a295c5f847/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L879)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Looks very hackish to me. I have no clue how it works and what it fixes. Please add comments. `!=` of two strings might not work at all.
</blockquote></details>

In fact, I have realized that, so that string comparison has been changed to use `.equal()`.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11292)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot)

___
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 879 at r1](https://reviewable.io/reviews/vaadin/framework/11292#-LQnQBQL82CYWiG4A3nM:-LQrU8mJDDa7CYq9pVZs:bir0awc) ([raw file](https://github.com/vaadin/framework/blob/0dafb052e75a8eddc9934d7584aa60a295c5f847/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L879)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

In fact, I have realized that, so that string comparison has been changed to use `.equal()`.
</blockquote></details>

Comment added.

**Review by elmot — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11292)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elmot and @ZheSun88)

___
*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 879 at r1](https://reviewable.io/reviews/vaadin/framework/11292#-LQnQBQL82CYWiG4A3nM:-LQsi79u76H5uhMeQQul:b-5c7gqn) ([raw file](https://github.com/vaadin/framework/blob/0dafb052e75a8eddc9934d7584aa60a295c5f847/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L879)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Comment added. 
</blockquote></details>

I am strongly against the change. First of all, the ticket is about cross-field validation, there is nothing to do for it inside the single field. There might be some bugs in DateField, but this fix does not fix any of those (even if they exist). Cross-field validation must be done on binder level, but not here.
On the other hand, `currentParseErrorMessage` is not necessarily the actual error message.  Here is `getDateOutOfRangeMessage` method, which can be overriden in subclasses, and then the message might be any, including some dynamic text, and the comparison won't work at all

**Pull request closed without merging**
