### PR TITLE
Add collapse and expand events to TreeGrid

### LINKED ISSUE #8760: When user collapses/expands a node in TreeGrid, I want to get an event, so that I can keep track of what the user is doing

### PR DESCRIPTION
**Pull request by ahie**
Closes #8760 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8889)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfjyJDybp_53dLL_j4i:-KfjyJDznttLiMPz8PmQ:b585uyc) (no related file):*
Where is the documentation update for this feature ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by ahie** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfjyJDybp_53dLL_j4i:-Kfk2xeZnD7Q64vRdT_5:bpbzng9) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Where is the documentation update for this feature ?
</blockquote></details>

Added documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by hesara** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfk43GNsq0mliTTIKWn:-Kfk43GO8rMqZLToatwz:bvnd581) ([raw file](https://github.com/vaadin/framework/blob/946d831d6080608aa6b2f62d39beba4f5736eb8f/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L130)):*
> ```Java
>         Assert.assertFalse(logContainsText("Item collapsed: 0 | 0"));
> 
>         grid.getRow(0).getCell(0)
> ```

TreeGridElement.expandWithClick()?

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfk46zWzQOAtqEqWIy_:-Kfk46zWzQOAtqEqWIya:b-972i64) ([raw file](https://github.com/vaadin/framework/blob/946d831d6080608aa6b2f62d39beba4f5736eb8f/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L137)):*
> ```Java
> 
>         grid.getRow(0).getCell(0)
>                 .findElement(By.className("v-tree-grid-expander")).click();
> ```

TreeGridElement.collapseWithClick()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by ahie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfk43GNsq0mliTTIKWn:-Kfk5NrkZPsL8jyq6mG-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/946d831d6080608aa6b2f62d39beba4f5736eb8f/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L130)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TreeGridElement.expandWithClick()?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfk46zWzQOAtqEqWIy_:-Kfk5OI9bBRE_TuTUZHZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/946d831d6080608aa6b2f62d39beba4f5736eb8f/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L137)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TreeGridElement.collapseWithClick()?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfktumnw5W4M4etEwJY:-Kfktumnw5W4M4etEwJZ:bbgjdtw) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
> where

Where ?

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfku07HeeSmtodhor_l:-Kfku07HeeSmtodhor_m:b-bl3e7k) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
> ```AsciiDoc
> ----
> 
> where the return types of the methods `getExpandedItem` and `getCollapsedItem` are the same as the type of the [classname]#TreeGrid# the events originated from.
> ```

Could you clarify that is the collapse event fired for each expanded node in the collapsed subtree or just for the root node ?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 142 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkuMhTzAvVhoz5nYFk:-KfkuMhUHZEQUaIbNzRj:b-emb5px) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L142)):*
> ```Java
>     /**
>      * An event that is fired when an item is collapsed.
>      * 
> ```

Is this fired for each of the expanded nodes when a subtree is collapsed or just the collapsed node ?

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 200 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkuW5dNQsW9MHCV5Jm:-KfkuW5dNQsW9MHCV5Jn:bj2x3tp) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L200)):*
> ```Java
>      * @param listener
>      *            the listener to add
>      * @return a registration for the listener
> ```

`@see ExpandEvent` might be good since it has the description about _what is this for_

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 213 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkubjZBqF0xawbyMdR:-KfkubjZBqF0xawbyMdS:b1xdncg) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L213)):*
> ```Java
>      *            the listener to add
>      * @return a registration for the listener
>      */
> ```

`@see CollapseEvent` might be good since it has the description about _what is this for_

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 139 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfktZ5-SostybX7SMX0:-KfktZ5-SostybX7SMX1:b-x8wqce) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L139)):*
> ```Java
>         Assert.assertTrue(logContainsText("Item expanded: 0 | 0"));
>         Assert.assertTrue(logContainsText("Item collapsed: 0 | 0"));
>     }
> ```

I think it is good practice to also verify that the removal of the listeners works as should, just in case someone later on goes and breaks that, then it is not caught up by tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by ahie** [comment]
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfku07HeeSmtodhor_l:-KfkwWoxc8k25eNUcUzg:b-hnbdpp) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could you clarify that is the collapse event fired for each expanded node in the collapsed subtree or just for the root node ?
</blockquote></details>

Collapsing a root of a subtree shouldn't collapse any of the child trees?

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfktumnw5W4M4etEwJY:-KfkwpLiI_BABaJmOgEU:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> where

Where ?

</blockquote></details>

Fixed.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 142 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkuMhTzAvVhoz5nYFk:-Kfkwz2ZZ4mE0gBpwB_5:bxrkry7) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L142)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Is this fired for each of the expanded nodes when a subtree is collapsed or just the collapsed node ?
</blockquote></details>

See response in the comment for components-treegrid.asciidoc.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 200 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkuW5dNQsW9MHCV5Jm:-KfkwFB7UIx_GhiMKWpl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L200)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

`@see ExpandEvent` might be good since it has the description about _what is this for_
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 213 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfkubjZBqF0xawbyMdR:-KfkwEl-11QzFJalNxtD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/server/src/main/java/com/vaadin/ui/TreeGrid.java#L213)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

`@see CollapseEvent` might be good since it has the description about _what is this for_
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java, line 139 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-KfktZ5-SostybX7SMX0:-KfkvxVmPNLTGnqpuymS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridBasicFeaturesTest.java#L139)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think it is good practice to also verify that the removal of the listeners works as should, just in case someone later on goes and breaks that, then it is not caught up by tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfku07HeeSmtodhor_l:-Kfkxp7zvbqF9RUYkrEZ:b-t9jo4g) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Collapsing a root of a subtree shouldn't collapse any of the child trees?
</blockquote></details>

If I'm looking at the javadocs or documentation, I cannot know how many times collapse listener is triggered when a node is collapsed and it has a subtree that has also expanded items.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by ahie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/components/components-treegrid.asciidoc, line 107 at r3](https://reviewable.io:443/reviews/vaadin/framework/8889#-Kfku07HeeSmtodhor_l:-Kfl08-FRKPev8BvVxAo:b-eowr3y) ([raw file](https://github.com/vaadin/framework/blob/f9235e0001044d1d86e5ed1843ec7314933cea84/documentation/components/components-treegrid.asciidoc#L107)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

If I'm looking at the javadocs or documentation, I cannot know how many times collapse listener is triggered when a node is collapsed and it has a subtree that has also expanded items.
</blockquote></details>

Clarified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8889)*

**Pull request merged**
