### PR TITLE
OSGi resource registration via SCR

### PR DESCRIPTION
**Pull request by swimmesberger**
The problem with the current OSGi design is that it relies on start levels if the components which contribute themes, widgetsets, resources are activated before the main vaadin-share bundle is activated we receive a ResourceBundleInactiveException("Vaadin Shared is not active!") exception. If we change the start levels which ensure that vaadin-share is started before the contributing bundles everything works as expected. 

Using start levels are considered bad OSGi and considered "deprecated" so I reworked the OSGi mechanism to follow OSGi best practices and therefore not rely on any start level mechanism.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)

### CODE REVIEW

**Comment by swimmesberger** [comment]
Fixed build with last commit

**Review by elmot — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @swimmesberger)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11166#-LLmteEQDPvuqrHVKPpl:-LLmteEQDPvuqrHVKPpm:b9o3hd0) (no related file):*
I will run our server integration tests to check if the patch works. Now the PR is blocked until it's done.

---

**Comment by swimmesberger** [comment]
Had to do a additional commit fixing depending on binding order. In cases OsgiVaadinResource, OsgiVaadinWidgetset, OsgiVaadinTheme or OsgiVaadinContributor binded before the HttpService we got a NPE. I have fixed that by registering the resources in the activate method instead of the bind method. I have also implemented a proper deactivate method to do some cleanup.

**Comment by elmot** [comment]
@swimmesberger, thanks for your contribution, this change is a really useful, and it looks working according to my test run.

>Using start levels are considered bad OSGi and considered "deprecated" so I reworked the OSGi mechanism to follow OSGi best practices and therefore not rely on any start level mechanism.

Can you, please, provide a little bit more information about this, any documentation links or a forum thread?

**Review by elmot — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @swimmesberger)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11166#-LLmteEQDPvuqrHVKPpl:-LLnUheS7MyVTWvrsD4u:b-ylwx3j) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I will run our server integration tests to check if the patch works. Now the PR is blocked until it's done.
</blockquote></details>

Manual test passed, karaf integration works like a charm, but I still need a 3rd opinion about the change.

---

**Comment by swimmesberger** [comment]
Maybe @pkriens or @bjhargrave can additional provide some feedback for this new OSGi integration.

**Comment by swimmesberger** [comment]
Like described this pull request changes the way vaadin integrates with OSGi environtments because the old way of working with BundleActivators and start levels seemed wrong to me. This pull request uses OSGi components. Just wanted to heat a second opinion of an osgi expert if we are on the right track here.

**Comment by swimmesberger** [comment]
No problem! For us this way of using OSGi and integrating with OSGi makes using vaadin in an OSGi environment much smoother because you don't have to define special start levels especially if you write custom components and supply custom themes/widgets.

**Review by elmot — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: all files reviewed, 7 unresolved discussions (waiting on @swimmesberger)

___
*[shared/src/main/java/com/vaadin/osgi/resources/OsgiVaadinContributor.java, line 24 at r1](https://reviewable.io/reviews/vaadin/framework/11166#-LMlTweaA1XAS5oWTlY6:-LMlTweaA1XAS5oWTlY7:bxc4dyy) ([raw file](https://github.com/vaadin/framework/blob/b8ea41a984385e900d605659a4b4835ed5cb3067/shared/src/main/java/com/vaadin/osgi/resources/OsgiVaadinContributor.java#L24)):*
> ```Java
>  * Each vaadin resource will be checked for the type (theme, widgetset,
>  * resource) and registered to the OSGi context with the appropriate type.
>  */
> ```

No since tag
___
*[shared/src/main/java/com/vaadin/osgi/resources/OsgiVaadinResource.java, line 28 at r1](https://reviewable.io/reviews/vaadin/framework/11166#-LMlUKqR6mNzINJ7ZeTf:-LMlUKqR6mNzINJ7ZeTg:bxc4dyy) ([raw file](https://github.com/vaadin/framework/blob/b8ea41a984385e900d605659a4b4835ed5cb3067/shared/src/main/java/com/vaadin/osgi/resources/OsgiVaadinResource.java#L28)):*
> ```Java
>  * <code>VaadinResourceTrackerComponent</code> automatically publish the
>  * resource with the given name.
>  */
> ```

No since tag
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 200 at r4](https://reviewable.io/reviews/vaadin/framework/11166#-LMlUlSi9qeNk3gxdvT7:-LMlUlSi9qeNk3gxdvT8:b-k10qpq) ([raw file](https://github.com/vaadin/framework/blob/a167fc5cdb11c1ec66891892e3fcd61d1c9fe404/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L200)):*
> ```Java
>         this.httpService = null;
>     }
>     
> ```

extra spaces
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 202 at r4](https://reviewable.io/reviews/vaadin/framework/11166#-LMlV4fr2sOVdoRhWUR_:-LMlV4fr2sOVdoRhWURa:bnv3dxc) ([raw file](https://github.com/vaadin/framework/blob/a167fc5cdb11c1ec66891892e3fcd61d1c9fe404/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L202)):*
> ```Java
>     
>     @Activate
>     protected void activate() throws NamespaceException {
> ```

No since
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 208 at r4](https://reviewable.io/reviews/vaadin/framework/11166#-LMlUoHR4jbNzjbqBxJx:-LMlUoHR4jbNzjbqBxJy:bmb0d6y) ([raw file](https://github.com/vaadin/framework/blob/a167fc5cdb11c1ec66891892e3fcd61d1c9fe404/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L208)):*
> ```Java
>         }
>     }
>     
> ```

extra spaces everywhere
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 209 at r4](https://reviewable.io/reviews/vaadin/framework/11166#-LMlUpO74Z6ROEbc9Y1k:-LMlUpO74Z6ROEbc9Y1l:bnv3dxc) ([raw file](https://github.com/vaadin/framework/blob/a167fc5cdb11c1ec66891892e3fcd61d1c9fe404/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L209)):*
> ```Java
>     }
>     
>     @Deactivate
> ```

No since

**Review by elmot — COMMENTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @elmot and @swimmesberger)

**Review by elmot — COMMENTED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: all files reviewed, 2 unresolved discussions (waiting on @swimmesberger)

**Review by elmot — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11166)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
