### PR TITLE
Support using Composite and CustomComponent as a Design root class

### PR DESCRIPTION
**Pull request by Artur-**
Depends on #8952

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9017)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-3G80FJ2HszjANbg3:-Ki-3G80FJ2HszjANbg4:bqio0a) (no related file):*
probably needs to be rebased on the merged #8952

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by hesara** [comment]
Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 495 at r1](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-8zvyyJPx6GdHOdWr:-Ki-8zvyyJPx6GdHOdWs:b-cl2nv) ([raw file](https://github.com/vaadin/framework/blob/994247e0db0791d058be25bdc7ed07ee78ace540/server/src/main/java/com/vaadin/ui/declarative/Design.java#L495)):*
> ```Java
>             if (componentRoot instanceof CustomComponent
>                     || componentRoot instanceof Composite) {
>                 // IF the root is a custom component, we ALWAYS populate its
> ```

the impact on the user could perhaps be made more explicit also in the javadoc

---

*[server/src/test/java/com/vaadin/tests/server/component/composite/MyPrefilledComposite.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-4rFJiO_CjreJtsfl:-Ki-4rFKw_ZcdP0rXTMd:b2whnwa) ([raw file](https://github.com/vaadin/framework/blob/994247e0db0791d058be25bdc7ed07ee78ace540/server/src/test/java/com/vaadin/tests/server/component/composite/MyPrefilledComposite.java#L21)):*
> ```Java
> import com.vaadin.ui.NativeButton;
> 
> public class MyPrefilledComposite extends CustomComponent {
> ```

should this be a Composite?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by Artur-** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 495 at r1](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-8zvyyJPx6GdHOdWr:-Ki-AEFHlqYTSnetClAo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/994247e0db0791d058be25bdc7ed07ee78ace540/server/src/main/java/com/vaadin/ui/declarative/Design.java#L495)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the impact on the user could perhaps be made more explicit also in the javadoc
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/composite/MyPrefilledComposite.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-4rFJiO_CjreJtsfl:-Ki-A0PTAtaGnliqgNTo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/994247e0db0791d058be25bdc7ed07ee78ace540/server/src/test/java/com/vaadin/tests/server/component/composite/MyPrefilledComposite.java#L21)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this be a Composite?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r2.
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 441 at r2](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-N6o1grarnSRC0hdO:-Ki-N6o1grarnSRC0hdP:b-l8aq6y) ([raw file](https://github.com/vaadin/framework/blob/b622055dfef6eb8717de8bec5357e252178c508f/server/src/main/java/com/vaadin/ui/declarative/Design.java#L441)):*
> ```Java
>      * local id, and caption
>      * <p>
>      * If the root is a custom component or composite, its composition root will
> ```

(javadoc lgtm, but probably not seen by the users as it is for a private internal method only - not sure where would be the best place for this, whether this should also be mentioned on the class level somehow)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by Artur-** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/declarative/Design.java, line 441 at r2](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-N6o1grarnSRC0hdO:-Ki-RevZp58htw52dTmO:b-903vfg) ([raw file](https://github.com/vaadin/framework/blob/b622055dfef6eb8717de8bec5357e252178c508f/server/src/main/java/com/vaadin/ui/declarative/Design.java#L441)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(javadoc lgtm, but probably not seen by the users as it is for a private internal method only - not sure where would be the best place for this, whether this should also be mentioned on the class level somehow)
</blockquote></details>

Added the same javadoc to all `read` methods which take a root component

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-SOWw7UdPRcchhDi4:-Ki-SOWw7UdPRcchhDi5:be7z518) (no related file):*
In last test run, CompositeDesignRootTest.compositeReadCompositeDesign() failed - to check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by Artur-** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9017#-Ki-SOWw7UdPRcchhDi4:-Ki-TKjPiS1iEwL4WUdB:b-886gsx) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

In last test run, CompositeDesignRootTest.compositeReadCompositeDesign() failed - to check
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9017)*

**Pull request merged**
