### PR TITLE
Allow configuring content modes for Grid cell tooltips

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10396)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 163 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G6PkVAJ8YuivuLqWq:-L-G6PkVAJ8YuivuLqWr:bn9lm4e) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/client/src/main/java/com/vaadin/client/VTooltip.java#L163)):*
> ```Java
>                 PreElement preElement = Document.get().createPreElement();
>                 preElement.addClassName(CLASSNAME + "-pre");
>                 preElement.setInnerText(info.getTitle());
> ```

Why is `setInnerText` usable here but not above?

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G6X9S3KrKqB4enGss:-L-G6X9S3KrKqB4enGst:bec47mj) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/client/src/main/java/com/vaadin/client/VTooltip.java#L165)):*
> ```Java
>                 preElement.setInnerText(info.getTitle());
>                 // clear existing content
>                 description.setInnerHTML("");
> ```

why doesn't this use `removeAllChildren` like the `TEXT` one does?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6696 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7-mQWEtXE5xO1hlS:-L-G7-mQWEtXE5xO1hlT:b-hw381v) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6696)):*
> ```Java
>      * a {@link RowDescriptionGenerator} is also set, the row description it
>      * generates is displayed for cells for which {@code generator} returns
>      * null.
> ```

`{@code null}`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6702 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G79rFPqblDn6TXw45:-L-G79rFPqblDn6TXw46:b-wctloe) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6702)):*
> ```Java
>      *            previously set generator if any
>      * @param contentMode
>      *            the content mode for cell tooltips, not <code>null</code>
> ```

`<code>` vs `{@code}`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6734 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7UaiBSqaFqAKfKPs:-L-G7UaiBSqaFqAKfKPt:b-wctloe) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6734)):*
> ```Java
>      * 
>      * @return the content mode used for cell descriptions, not
>      *         <code>null</code>
> ```

`<code>` vs `{@code}`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6774 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7XELnQb52wIT_24A:-L-G7XELnQb52wIT_24B:b-hw381v) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6774)):*
> ```Java
>      * {@link CellDescriptionGenerator} is also set, the row description
>      * generated by {@code generator} is used for cells for which the cell
>      * description generator returns null.
> ```

`{@code null}`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6780 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7ZX88E9PY-qPOE89:-L-G7ZX88E9PY-qPOE8A:b-wctloe) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6780)):*
> ```Java
>      *            previously set generator if any
>      * @param contentMode
>      *            the content mode for row tooltips, not <code>null</code>
> ```

`<code>` vs `{@code}`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6801 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7avCl-2UUfweXb2P:-L-G7avCl-2UUfweXb2Q:b-wctloe) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6801)):*
> ```Java
>      * Gets the content mode used for row descriptions.
>      * 
>      * @return the content mode used for row descriptions, not <code>null</code>
> ```

`<code>` vs `{@code}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by Legioth** [comment]
Review status: 7 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 163 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G6PkVAJ8YuivuLqWq:-L-GQ7bmmvkS9TP5mEQa:b2mtngd) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/client/src/main/java/com/vaadin/client/VTooltip.java#L163)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why is `setInnerText` usable here but not above?
</blockquote></details>

Clarified the comment. It's OK here because linebreaks should be preserved.

---

*[client/src/main/java/com/vaadin/client/VTooltip.java, line 165 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G6X9S3KrKqB4enGss:-L-GQYVBoT-c_oLiNycE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/client/src/main/java/com/vaadin/client/VTooltip.java#L165)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why doesn't this use `removeAllChildren` like the `TEXT` one does?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6696 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7-mQWEtXE5xO1hlS:-L-Gc4STr0UdEnb1SlfB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6696)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`{@code null}`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6702 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G79rFPqblDn6TXw45:-L-Gc4ye6jfzcuqaHbjL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6702)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<code>` vs `{@code}`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6734 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7UaiBSqaFqAKfKPs:-L-GbenqQfkvE3w0iarr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6734)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<code>` vs `{@code}`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6774 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7XELnQb52wIT_24A:-L-Gbf8zw2q7dTHACxoQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6774)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`{@code null}`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6780 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7ZX88E9PY-qPOE89:-L-GcJtD4Mid0DXdmUtb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6780)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<code>` vs `{@code}`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 6801 at r1](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-G7avCl-2UUfweXb2P:-L-GcKHUgiB3Gl-_Q2HM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c21692baf6340cf35bdd745f4e7e131d01ac06d0/server/src/main/java/com/vaadin/ui/Grid.java#L6801)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`<code>` vs `{@code}`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-GddY-k1mp93XjSf_P:-L-GddY-k1mp93XjSf_Q:btzwbto) (no related file):*
@TatuLund are you taking this to the next 7.7 release?

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/GridState.java, line 218 at r2](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-GdxhBJkOO1nJWbBp7:-L-GdxhBJkOO1nJWbBp8:brlmuz4) ([raw file](https://github.com/vaadin/framework/blob/c6395c285bcb0957160c6a6063814d12f9bc3603/shared/src/main/java/com/vaadin/shared/ui/grid/GridState.java#L218)):*
> ```Java
>      * accidentally been used there.
>      */
>     public ContentMode cellTooltipContentMode = ContentMode.HTML;
> ```

Should these btw have the since as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by Legioth** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/GridState.java, line 218 at r2](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-GdxhBJkOO1nJWbBp7:-L-GeZjr3hT_0_qsLwLM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c6395c285bcb0957160c6a6063814d12f9bc3603/shared/src/main/java/com/vaadin/shared/ui/grid/GridState.java#L218)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should these btw have the since as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-GddY-k1mp93XjSf_P:-L-WBMs5tXY9gRyIVX2D:bgehvc6) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@TatuLund are you taking this to the next 7.7 release?
</blockquote></details>

Still needs a decision from Tatu on the version number, from a FW developer point of view this is :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by brunojcm** [comment]
Just to confirm, is it going to v7 compatibilty package in V8 as well, right?
Can I help in this process somehow? Just let me know.

**Comment by brunojcm** [comment]
Guys, what's missing here to proceed with this PR? We have 8.3 starting already and my app is still broken because of this regression.

**Comment by Legioth** [comment]
Ping @TatuLund

**Comment by TatuLund** [comment]
This fix was merged to 7.7 branch, but not in master for upcoming 8-series releases yet.

**Comment by Legioth** [comment]
This PR is targeted for the `7.7` branch since the changes do not apply for the 8 series where the same functionality is already implemented in a different way.

I don't see any of theses changes in the current `7.7` branch. For instance `framework/client/src/main/java/com/vaadin/client/TooltipInfo.java` is last modified in October 2017 whereas this PR is from November.

**Comment by TatuLund** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10396#-L-GddY-k1mp93XjSf_P:-L46HkxZgRetqJ7MNdgS:b32w0x) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Still needs a decision from Tatu on the version number, from a FW developer point of view this is :lgtm:
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by TatuLund** [comment]
Reviewed 9 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by brunojcm** [comment]
> This unmerged PR is targeted for the 7.7 branch since the changes do not apply for the 8 series where the same functionality is already implemented in a different way.

Is it implemented in `v7-compat` packages?

I don't know how you keep the `v7-compat` v8 code in sync with the v7 branches, but I understand that this PR is mainly meant to fix my last comments in #8853, thus being needed mainly in `v7-compat`.

**Comment by Legioth** [comment]
@brunojcm Once it's merged to 7.x, we will apply the same changes to the compatibility classes in 8.x. We never make any changes directly to the compatibility classes in 8.x since that would cause the code to become out of sync with 7.x.

**Comment by brunojcm** [comment]
@Legioth thanks for letting me know!
So, what's missing to have this on next release?

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10396)*

**Comment by elmot** [comment]
@brunojcm, thank you for your contribution, sorry for some delay on the PR, now we are pushing it forward. If you still have time and a will, you can make another PR on top of _master_ branch with similar changes to `com.vaadin.v7.ui.Grid` and related classes.

**Pull request merged**
