### PR TITLE
Add getHeaderCellByCaption method to tb-api GridElement

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8248)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 215 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabCqM-rWuBmqqIwhKq:-KabCqM0UcWMHqhdRkxY:b-n83rxz) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L215)):*
> ```Java
> 
>     /**
>      * Gets header cell element with a given row by a header caption
> ```

Maybe clearer with something like
"Gets the header cell element  with the given caption in the given header row"

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDWqPs6VsZwnBD7qH:-KabDWqPs6VsZwnBD7qI:bxq1nfz) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L216)):*
> ```Java
>     /**
>      * Gets header cell element with a given row by a header caption
>      *
> ```

Add info (and test) about what happens if there are multiple header cells with the same text

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 218 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDIk42LtYtAUjOKBQ:-KabDIk42LtYtAUjOKBR:br2e7x) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L218)):*
> ```Java
>      *
>      * @param rowIndex
>      *            Row index
> ```

The index of the header row

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDeaBWg5J11jI-NvY:-KabDeaBWg5J11jI-NvZ:b-h4p03b) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
> ```Java
>      * @param caption
>      *            Header caption
>      * @return First header cell element with a given caption.
> ```

"The first header cell"

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDfqSHOvjP9rDPYzW:-KabDfqSHOvjP9rDPYzX:b-25g3ht) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
> ```Java
>      * @param caption
>      *            Header caption
>      * @return First header cell element with a given caption.
> ```

`, or <code>null</code> if no header cell with the given text was found`

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDwqzQzVp-dQmidiA:-KabDwqzQzVp-dQmidiB:b-sp2ga9) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
> ```Java
>      * @param caption
>      *            Header caption
>      * @return First header cell element with a given caption.
> ```

What is returned if no header with the given row index was found?

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 223 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabChLx_FVd--oMdgOS:-KabChLyfU-XESXTp5t1:bto431x) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L223)):*
> ```Java
>      * @return First header cell element with a given caption.
>      */
>     public GridCellElement getHeaderCellByCaption(int rowIndex, String caption) {
> ```

Would add a helper with only `String caption" that uses rowIndex=0. In a majority of cases, you only have one (the default) header row

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabD52NyQlQiBPr1FYY:-KabD52NyQlQiBPr1FYZ:bekt7qg) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L224)):*
> ```Java
>      */
>     public GridCellElement getHeaderCellByCaption(int rowIndex, String caption) {
>         List<GridCellElement> headerCells= getHeaderCells( rowIndex);
> ```

Format using the project formatting settings

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabCwmmlUzDfRVHPpvP:-KabCwmmlUzDfRVHPpvQ:b-633ge1) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L226)):*
> ```Java
>         List<GridCellElement> headerCells= getHeaderCells( rowIndex);
>         for(GridCellElement cell: headerCells) {
>             if(caption.equals(cell.getAttribute("innerText"))) {
> ```

why `getAttribute("innerText")` instead of `getText()`?

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEJV8fE7ojD6tmmT4:-KabEJV8fE7ojD6tmmT5:b-2n3bmf) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L45)):*
> ```Java
> 
>     @Test
>     public void testGetHeadersByCaption() {
> ```

There should be a test for another row than 0

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEL2BYzet3hRdCTFr:-KabEL2BYzet3hRdCTFs:b-7jygtz) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L46)):*
> ```Java
>     @Test
>     public void testGetHeadersByCaption() {
>         openTestURL("rowCount=10&restartApplication");
> ```

There should be a test for another column than 0

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabE22pd3hCM5a-4QUO:-KabE22pd3hCM5a-4QUP:b-l0f8sp) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L49)):*
> ```Java
>         GridElement grid = $(GridElement.class).first();
>         GridElement.GridCellElement cell = grid.getHeaderCellByCaption(0, "foo");
>         Assert.assertNotNull(cell);
> ```

Assert that it works correctly (correct header cell returned) instead of asserting that it does not work incorrectly (null)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 220 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEUfduLLvYtKG8Odw:-KabEUfduLLvYtKG8Odx:b434uvd) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L220)):*
> ```Java
>      *            Row index
>      * @param caption
>      *            Header caption
> ```

the text in the header cell
or
the header caption

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by denis-anisimov** [comment]
Almost every changed line is commented by Artur. Cool !

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248#-:-KabNVbiyTZc7Zr96S85:b-3qe99f)*

**Comment by Artur-** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 215 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabCqM-rWuBmqqIwhKq:-KabT3S5xWuUP-f5z1kt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L215)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Maybe clearer with something like
"Gets the header cell element  with the given caption in the given header row"


</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 218 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDIk42LtYtAUjOKBQ:-KabTN2UkVcwBYafpWb4:b-2u0d2m) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L218)):*
> The index of the header row
That was is taken from the other javadoc in this class, are we 

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 220 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEUfduLLvYtKG8Odw:-KabU3rnZ4RyeA1B4jGD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L220)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

the text in the header cell
or
the header caption
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDeaBWg5J11jI-NvY:-KabU6klbDydBHGH0JGi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

"The first header cell"
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 223 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabChLx_FVd--oMdgOS:-KabXodaQ8qSohapjYc2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L223)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Would add a helper with only `String caption" that uses rowIndex=0. In a majority of cases, you only have one (the default) header row
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabD52NyQlQiBPr1FYY:-KabXvOux-ZnsF6UqE0_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L224)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Format using the project formatting settings
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 226 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabCwmmlUzDfRVHPpvP:-KabXyjqVe-qqmh-toED:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L226)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

why `getAttribute("innerText")` instead of `getText()`?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEJV8fE7ojD6tmmT4:-KabkiH9mojKEclrM9H6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L45)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

There should be a test for another row than 0
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabEL2BYzet3hRdCTFr:-KabYHciPxiBeOx-enQ-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L46)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

There should be a test for another column than 0
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabE22pd3hCM5a-4QUO:-Kabkl35GFsXs5fBb9UF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L49)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Assert that it works correctly (correct header cell returned) instead of asserting that it does not work incorrectly (null)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 216 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDWqPs6VsZwnBD7qH:-KabkrfZPz32jeeWdu2y:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L216)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Add info (and test) about what happens if there are multiple header cells with the same text
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDfqSHOvjP9rDPYzW:-KabktUxmtx8-lOb6xLi:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

`, or <code>null</code> if no header cell with the given text was found`
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/8248#-KabDwqzQzVp-dQmidiA:-KabkuryOLf4pkXR-SJ3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bbfb1b81a583a5c585a2aad53dae336d02166191/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L221)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What is returned if no header with the given row index was found?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java, line 214 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-Kafr12M0Mz4XFIaZqaC:-Kafr12M0Mz4XFIaZqaD:b-bvkvnt) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java#L214)):*
> ```Java
> 
>     /**
>      * Gets the header cell element with the given caption in the first row. If
> ```

I would avoid the _first_ row mention. Is it possible to try to find a cell with the given caption in ANY row ?

The method name doesn't say anything about the _first_ row, so it's confusing.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 49 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftYOfTNe52z6erMjd:-KaftYOgkiF1cxpGt0Y6:bp98hnc) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L49)):*
> ```Java
>         openTestURL("rowCount=10&restartApplication");
>         GridElement grid = $(GridElement.class).first();
>         GridElement.GridCellElement cell = grid.getHeaderCellByCaption("foo");
> ```

The main point here is : no any exception.
There should be a comment about that.

The check against `null` is optional ( and this could be in the comments as well).

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftpCf_SzfBQGrAfNi:-KaftpCf_SzfBQGrAfNj:bf26u1) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L57)):*
> ```Java
>         openTestURL("rowCount=10&restartApplication");
>         GridElement grid = $(GridElement.class).first();
>         GridElement.GridCellElement cell = grid.getHeaderCellByCaption("bar");
> ```

The same as above.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-Kaftu-dCFbVpRniVIUP:-Kaftu-dCFbVpRniVIUQ:b-kwl3ct) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L67)):*
> ```Java
>         GridElement.GridCellElement cell = grid
>             .getHeaderCellByCaption(0, "not existing caption");
>         Assert.assertNull(cell);
> ```

Dead code ?

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftwV0ndutdVnYhr-M:-KaftwV18MeKnfdqc5lH:b-es8qjn) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L75)):*
> ```Java
>         GridElement grid = $(GridElement.class).first();
>         GridElement.GridCellElement cell = grid
>             .getHeaderCellByCaption(1, "extra row");
> ```

Same as above about optional assertion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 49 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftYOfTNe52z6erMjd:-KagNbDt1dDXLu4FGMDF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L49)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The main point here is : no any exception.
There should be a comment about that.

The check against `null` is optional ( and this could be in the comments as well).
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 57 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftpCf_SzfBQGrAfNi:-KagNaU_CHuCQ-KI3fww:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L57)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The same as above.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 67 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-Kaftu-dCFbVpRniVIUP:-KagNYvH3CM20nCneGE3:bvpeo2n) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L67)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Dead code ?
</blockquote></details>

Removed. Done.

---

*[uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java, line 75 at r2](https://reviewable.io:443/reviews/vaadin/framework/8248#-KaftwV0ndutdVnYhr-M:-KagNS4tAnhGhS9VYVQ8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7ac1c8eec8916f350ff587c659da8218950df7c7/uitest/src/test/java/com/vaadin/tests/elements/grid/GridUITest.java#L75)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Same as above about optional assertion.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8248)*

**Pull request merged**
