### PR TITLE
Remove usage of Consumer from event listeners

### PR DESCRIPTION
**Pull request by pleku**
Touched event listeners are:
- SelectionListener
- MultiSelectionListener
- SingleSelectionListener
- ValueChangeListener
- ItemClickListener
- BindingValidationStatusHandler
- BinderValidationStatusHandler
- StatusChangeListener

Part of vaadin/framework8-issues#264

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7985)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 28 of 29 files at r1.
Review status: 27 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatusHandler.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx4fA1a1wFLLtra6oa:-KYx4fA1a1wFLLtra6ob:bl1dsk2) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/data/BindingValidationStatusHandler.java#L49)):*
> ```Java
>      *            the changed status
>      */
>     public void statusChanged(ValidationStatus<?> statusChange);
> ```

should this be BindingValidationStatus?

---

*[server/src/main/java/com/vaadin/data/HasValue.java, line 158 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5JVh-vxJU8JHnyLf:-KYx5JVh-vxJU8JHnyLg:b-npigm5) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/data/HasValue.java#L158)):*
> ```Java
>          *            the received event, not null
>          */
>         public void valueChange(ValueChangeEvent<V> event);
> ```

valueChange or valueChanged?

---

*[server/src/main/java/com/vaadin/data/StatusChangeListener.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5NXFzhAg-JNn8iPM:-KYx5NXFzhAg-JNn8iPN:b-wt9wkf) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/data/StatusChangeListener.java#L39)):*
> ```Java
>      *            a status change event, not null
>      */
>     void statusChange(StatusChangeEvent event);
> ```

statusChange or statusChanged?

---

*[server/src/main/java/com/vaadin/event/selection/MultiSelectionListener.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5UJ85-W8gO6dN_Y-:-KYx5UJ85-W8gO6dN_Y0:bu36bur) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/event/selection/MultiSelectionListener.java#L52)):*
> ```Java
>      *            the selection event, never {@code null}
>      */
>     public void selectionChange(MultiSelectionEvent<T> event);
> ```

selectionChange or selectionChanged?

---

*[server/src/main/java/com/vaadin/event/selection/SelectionListener.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5YdhzbLvh-q8jbLG:-KYx5YdhzbLvh-q8jbLH:bu36bur) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/event/selection/SelectionListener.java#L44)):*
> ```Java
>      *            the selection event
>      */
>     public void selectionChange(SelectionEvent<T> event);
> ```

selectionChange or selectionChanged?

---

*[server/src/main/java/com/vaadin/event/selection/SingleSelectionListener.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5_OkjmaSX0Ui22l5:-KYx5_OkjmaSX0Ui22l6:bu36bur) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/event/selection/SingleSelectionListener.java#L52)):*
> ```Java
>      *            the selection event
>      */
>     public void selectionChange(SingleSelectionEvent<T> event);
> ```

selectionChange or selectionChanged?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7985)*

**Comment by hesara** [comment]
Review status: 27 of 28 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 492 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx6DfLCSfbUKJ9ldXD:-KYx6DfLCSfbUKJ9ldXE:b-bqlclk) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/ui/Grid.java#L492)):*
> ```Java
>          *            the received event, not null
>          */
>         public void itemClick(ItemClick<T> event);
> ```

itemClick or itemClicked?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7985)*

**Comment by hesara** [comment]
Reviewed 1 of 29 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7985)*

**Comment by pleku** [comment]
Review status: 19 of 32 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BindingValidationStatusHandler.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx4fA1a1wFLLtra6oa:-KYxH8xnd8MWPYuQ-sM3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/data/BindingValidationStatusHandler.java#L49)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this be BindingValidationStatus?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/selection/SingleSelectionListener.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/7985#-KYx5_OkjmaSX0Ui22l5:-KYxGh9VWXVenVjXJSMV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fe3cc3c6f3e9c253a3f3a3b0107ef240e4fef59a/server/src/main/java/com/vaadin/event/selection/SingleSelectionListener.java#L52)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

selectionChange or selectionChanged?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7985)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 30 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7985#-:-KYxIXF_83B-rBJTOry2:bnfp4nl)*

**Pull request merged**
