### PR TITLE
chore: Change Jetty version to 9.4.38.v20210224

### PR DESCRIPTION
**Pull request by TatuLund**
Avoids dependency security alert

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12248)

### CODE REVIEW

**Review by Ansku — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)

**Review by Ansku — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12248#-:-MW9rCv6-kYyNdcEaVtQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)

**Review by TatuLund — COMMENTED** [review]
Ok

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12248#-:-MW9xQVn2u77RwLcZARB:b2nhlk9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)

**Review by Ansku — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)

**Review by Ansku — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TatuLund)

**Pull request merged**
