### PR TITLE
Partial javadocs fix for vaadin-server

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8069)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 11 of 55 files at r1.
Review status: 11 of 55 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV-Np5MVrWRo2s15aG:-KZV-Np6sagsMm0-JFTH:b-cry313) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/data/Binder.java#L113)):*
> ```Java
>          *
>          * @see Binder#validate()
>          * @see Validator#apply
> ```

Why remove the parentheses that indicate this is a method?

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0DLKWsAqIBCZuFYQ:-KZV0DLKWsAqIBCZuFYR:b-gwnjmd) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/event/FieldEvents.java#L31)):*
> ```Java
> 
> /**
>  * Interface that serves as a wrapper for {@link com.vaadin.ui.AbstractField} related events.
> ```

(not sure if also used for other components, at least referenced from elsewhere)

---

*[server/src/main/java/com/vaadin/server/BootstrapFragmentResponse.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0ZQg_ZQxedxdURoC:-KZV0ZQg_ZQxedxdURoD:b-5rtga9) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/BootstrapFragmentResponse.java#L39)):*
> ```Java
>      * Crate a new bootstrap fragment response.
>      *
>      * @see BootstrapResponse#BootstrapResponse
> ```

Why remove method indicating parentheses?

---

*[server/src/main/java/com/vaadin/server/BootstrapPageResponse.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0cLZJyfwIgY4HzfV:-KZV0cLZJyfwIgY4HzfW:brhm8rg) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/BootstrapPageResponse.java#L41)):*
> ```Java
>      * Crate a new bootstrap page response.
>      *
>      * @see BootstrapResponse#BootstrapResponse
> ```

Why removed?

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-KZV0y4M8D2ZuM2MnjL9:b-hp4if9) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
> ```Java
>     /**
>      * An error event for connector related errors. Use {@link #getConnector()}
>      * to find the connector where the error occurred or {@link #getParent()}
> ```

I'm not sure, but I think this might (or might not) change the originally intended meaning (which might not be directly supported now) - the method was about finding the parent component, not the parent connector that getParent() returns. If you keep the getParent() reference, change the continuation to "nearest parent connector."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by elmot** [comment]
Review status: 11 of 55 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV-Np5MVrWRo2s15aG:-KZb-lM-VVFonXSaa3Cz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/data/Binder.java#L113)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why remove the parentheses that indicate this is a method?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/FieldEvents.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0DLKWsAqIBCZuFYQ:-KZb2pqOb2cmmc1Pdo4j:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/event/FieldEvents.java#L31)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not sure if also used for other components, at least referenced from elsewhere)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/BootstrapFragmentResponse.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0ZQg_ZQxedxdURoC:-KZb2riwJ1lpgIWKjHx-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/BootstrapFragmentResponse.java#L39)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why remove method indicating parentheses?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/BootstrapPageResponse.java, line 41 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0cLZJyfwIgY4HzfV:-KZaypZoH22irnA-xO6J:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/BootstrapPageResponse.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-KZb-jjRaUDGtEVGGn6B:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm not sure, but I think this might (or might not) change the originally intended meaning (which might not be directly supported now) - the method was about finding the parent component, not the parent connector that getParent() returns. If you keep the getParent() reference, change the continuation to "nearest parent connector."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by denis-anisimov** [comment]
Reviewed 47 of 55 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 808 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzmls05IF05jyBSS0m:-KZzmls1rVT6S5rvJGS4:bwq0nwm) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/Binder.java#L808)):*
> ```Java
>          * Handles the value change triggered by the bound field.
>          *
>          * @param event
> ```

`private` method.
Javadoc here is optional.

`@param` can be either removed or then it should have some description.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1023 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZznBvGJHImAU9_DZPx:-KZznBvGJHImAU9_DZPy:bvl4pg7) ([raw file](https://github.com/vaadin/framework/blob/9664620aaa3b03306b8876d45e5c9a77e6409aa8/server/src/main/java/com/vaadin/data/Binder.java#L1023)):*
> ```Java
>      * want to have a two-way mapping back to {@code null}, use
>      * {@link #forField(HasValue)} and
>      * {@link Binding#withNullRepresentation(Object))}.
> ```

This was an essential part of the explanation. Now the text contains only reference to `forField` method which doesn't do anything about two-way mapping. And one-way mapping is already covered above.

This should be kept somehow. Otherwise the whole section about two-way mapping should be removed from here.

---

*[server/src/main/java/com/vaadin/data/HasValue.java, line 203 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzoxPf3-dreyWtkvcj:-KZzoxPf3-dreyWtkvck:b-m9y4jd) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/HasValue.java#L203)):*
>  com.vaadin.server.Setter

`BiConsumer` is still in the imports section.
It's better to remove FQN here, use simple name, update imports ( remove unsed ones and add the `Setter` FQN)

---

*[server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzr-aK8-ePqI3OpzIc:-KZzr-aK8-ePqI3OpzId:b-mrgk76) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java#L21)):*
> java.util.Locale;

Remove

---

*[server/src/main/java/com/vaadin/event/ContextClickEvent.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzrY5snuiybz0i1FBU:-KZzrY5snuiybz0i1FBV:b-sp5cdl) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/event/ContextClickEvent.java#L21)):*
>  com.vaadin.event.FieldEvents.FocusListener;

Remove I guess.

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-KZztM4wh4OWmdpk15Mj:bdvjszc) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The event doesn't contain neither `getComponent()` method nor `getParent()`.
It might be that the class has been changed so that there is no the `getComponent()`  method anymore and javadoc is just outdated. 
So I guess the reference to `getComponent()`  (and now it's replaced to `getParent()` ) should be removed.

`Component` has `getParent()` method but there is no any sense to mention this and duplicate the description of this method here.

---

*[server/src/main/java/com/vaadin/server/JsonCodec.java, line 370 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzuSZv018JVihVvqp-:-KZzuSZv018JVihVvqp0:b-wxo27c) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/JsonCodec.java#L370)):*
> ```Java
>      * @param targetType
>      *            The type that should be returned by this method
>      * @param restrictToInternalTypes
> ```

javadocs are required for each parameter (I know this is quite dumb but .......)

---

*[server/src/main/java/com/vaadin/server/JsonCodec.java, line 549 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzueBivzSbAhGejcJ0:-KZzueBivzSbAhGejcJ1:b-dvwlyk) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/JsonCodec.java#L549)):*
> ```Java
>      *            The index of a generic type to use to define the child type
>      *            that should be decoded
>      * @param connectorTracker
> ```

`private` method.
Doesn't require javadoc. 
Two options:
- remove the `@param` tags
- provide a description for each of them

---

*[server/src/main/java/com/vaadin/server/LegacyCommunicationManager.java, line 360 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzvPK4iqN5caqnS_l7:-KZzvPK4iqN5caqnS_l8:b5fubzl) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/LegacyCommunicationManager.java#L360)):*
> ```Java
>         /**
>          *
>          * @param object
> ```

javadoc

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 658 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzwyxRxcvIEcCG9EVP:-KZzwyxRxcvIEcCG9EVQ:b-gt6jto) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L658)):*
> ```Java
>      * filename. Separators / and \\ are used.
>      *
>      * @param filename
> ```

javadoc please (wasn't here before, but should be fixed now)

---

*[server/src/main/java/com/vaadin/server/widgetsetutils/ClassPathExplorer.java, line 479 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzxIy0fmR8AgptxvWR:-KZzxIy0fmR8AgptxvWS:bpmrmjn) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/widgetsetutils/ClassPathExplorer.java#L479)):*
> ```Java
>      * Add a jar file to locations - see {@link #classpathLocations}.
>      *
>      * @param file
> ```

`private` method.

Either remove `@param`:s or provide javadocs.

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 482 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzzxFjTgTNCVYqvzPb:-KZzzxFjTgTNCVYqvzPc:b-jazk4q) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L482)):*
> ```Java
>          * @param rightValue
>          *            The value of the 'right' attribute
>          * @see #setRightUnits
> ```

`#setRightUnits(Unit)`

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 506 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--0Xf5Ea5JrZfD8wv:-K_--0Xf5Ea5JrZfD8ww:b9egpl) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L506)):*
> ```Java
>          * @param bottomValue
>          *            The value of the 'bottom' attribute
>          * @see #setBottomUnits
> ```

`#setBottomUnits(Unit)`

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 530 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--C4i9EbwK7Uu345R:-K_--C4jLuvdRSwcrevs:bsjpnqt) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L530)):*
> ```Java
>          * @param leftValue
>          *            The value of the 'left' CSS-attribute
>          * @see #setLeftUnits
> ```

`#setLeftUnits(Unit)`

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--w7gizTF-blIvDW5:-K_--w7gizTF-blIvDW6:b-r2vjh3) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L26)):*
> ```Java
> import java.util.Optional;
> import java.util.Set;
> import java.util.function.Consumer;
> ```

This import here should be removed or we have some issue with the code since it shouldn't use  a `Consumer`.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--uGL6rprOA1TNeZh:-K_--uGL6rprOA1TNeZi:b91ugwr) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L27)):*
> ```Java
> import java.util.Set;
> import java.util.function.Consumer;
> import java.util.function.Predicate;
> ```

This should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 808 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzmls05IF05jyBSS0m:-K_-W0ApX8KaXL4gDD5o:b-lnpdqf) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/Binder.java#L808)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`private` method.
Javadoc here is optional.

`@param` can be either removed or then it should have some description.
</blockquote></details>

optionality is not a reason to kill. If there was a javadoc why it should be removed? 
Param names without explanations, are everywhere in framework javadocs, let's not change this now and here.
I just fixed wrong parameter name.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1023 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZznBvGJHImAU9_DZPx:-K_-XX9M-tsBWmBVeOv5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9664620aaa3b03306b8876d45e5c9a77e6409aa8/server/src/main/java/com/vaadin/data/Binder.java#L1023)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This was an essential part of the explanation. Now the text contains only reference to `forField` method which doesn't do anything about two-way mapping. And one-way mapping is already covered above.

This should be kept somehow. Otherwise the whole section about two-way mapping should be removed from here.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/HasValue.java, line 203 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzoxPf3-dreyWtkvcj:-K_-Y5swM-LWO2_Q4ZLJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/HasValue.java#L203)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  com.vaadin.server.Setter

`BiConsumer` is still in the imports section.
It's better to remove FQN here, use simple name, update imports ( remove unsed ones and add the `Setter` FQN)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzr-aK8-ePqI3OpzIc:-K_-YLpAQAXeVItPz0EC:bdkkgeq) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java#L21)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> java.util.Locale;

Remove
</blockquote></details>

Locale is used in the class.

---

*[server/src/main/java/com/vaadin/event/ContextClickEvent.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzrY5snuiybz0i1FBU:-K_-YXxBo-o3UJWfESgU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/event/ContextClickEvent.java#L21)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  com.vaadin.event.FieldEvents.FocusListener;

Remove I guess.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-K_-YpKI-XshN9CLHGhA:bzezn0w) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The event doesn't contain neither `getComponent()` method nor `getParent()`.
It might be that the class has been changed so that there is no the `getComponent()`  method anymore and javadoc is just outdated. 
So I guess the reference to `getComponent()`  (and now it's replaced to `getParent()` ) should be removed.

`Component` has `getParent()` method but there is no any sense to mention this and duplicate the description of this method here.
</blockquote></details>

It has getParent(), inherited from Connector. And also see line 162

---

*[server/src/main/java/com/vaadin/server/JsonCodec.java, line 370 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzuSZv018JVihVvqp-:-K_-alxyPiH1v7ansdaW:b9bq8k4) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/JsonCodec.java#L370)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

javadocs are required for each parameter (I know this is quite dumb but .......)
</blockquote></details>

See other comments related to.

---

*[server/src/main/java/com/vaadin/server/JsonCodec.java, line 549 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzueBivzSbAhGejcJ0:-K_-ZJRpU5RLKAmp_7lV:bl6k4en) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/JsonCodec.java#L549)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`private` method.
Doesn't require javadoc. 
Two options:
- remove the `@param` tags
- provide a description for each of them
</blockquote></details>

There are lots of parameters without descriptions across framework javadocs. I also don't like that but let's not fix that in this PR

---

*[server/src/main/java/com/vaadin/server/LegacyCommunicationManager.java, line 360 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzvPK4iqN5caqnS_l7:-K_-Zg77N8ARGuojMjSV:bl6k4en) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/LegacyCommunicationManager.java#L360)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

There are lots of parameters without descriptions across framework javadocs. I also don't like that but let's not fix that in this PR

---

*[server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java, line 658 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzwyxRxcvIEcCG9EVP:-K_-ZheW17PKBAwnxB0w:bl6k4en) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L658)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

javadoc please (wasn't here before, but should be fixed now)
</blockquote></details>

There are lots of parameters without descriptions across framework javadocs. I also don't like that but let's not fix that in this PR

---

*[server/src/main/java/com/vaadin/server/widgetsetutils/ClassPathExplorer.java, line 479 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzxIy0fmR8AgptxvWR:-K_-ZkMMDUx8eGRNps1Y:b-34vmyd) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/server/widgetsetutils/ClassPathExplorer.java#L479)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`private` method.

Either remove `@param`:s or provide javadocs.
</blockquote></details>

See above

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 482 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZzzxFjTgTNCVYqvzPb:-K_-_5XjbNFulpl3ZFaA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L482)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`#setRightUnits(Unit)`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 506 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--0Xf5Ea5JrZfD8wv:-K_-_5uJYsvpf2Qbu_Lm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L506)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`#setBottomUnits(Unit)`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbsoluteLayout.java, line 530 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--C4i9EbwK7Uu345R:-K_-_6zXcRrduYvTWtbA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbsoluteLayout.java#L530)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`#setLeftUnits(Unit)`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--w7gizTF-blIvDW5:-K_-_i1q9aazJS299tbK:b-utvfqd) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This import here should be removed or we have some issue with the code since it shouldn't use  a `Consumer`.
</blockquote></details>

Hit! Looks like we have found a bug here. Fixed.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 27 at r2](https://reviewable.io:443/reviews/vaadin/framework/8069#-K_--uGL6rprOA1TNeZh:-K_-_him-U7QJJn9k8UF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1bfa5606b76219ab4140ce3b11c309cbc8562521/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This should be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 13 files at r3.
Review status: 55 of 63 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-K_-g1dZnH-S45mJ_-n4:b-mxstsi) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

It has getParent(), inherited from Connector. And also see line 162
</blockquote></details>

The javadoc is not 
- for the `ClientConnector`
- for the `Component`.

The javadoc is for the `ConnectorErrorEvent`class ( just a few lines below).
This class has no `getParent()` method exactly as I wrote before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by denis-anisimov** [comment]
Reviewed 8 of 13 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by elmot** [comment]
Review status: 62 of 63 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/ClientConnector.java, line 113 at r1](https://reviewable.io:443/reviews/vaadin/framework/8069#-KZV0y4M8D2ZuM2MnjL8:-K_3iTkH51qAyqgD4tIJ:bcnc9uu) ([raw file](https://github.com/vaadin/framework/blob/d150808ea8bd05738263d4036f6505d35fae52eb/server/src/main/java/com/vaadin/server/ClientConnector.java#L113)):*
> ConnectorErrorEvent
Yes, you are right. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8069)*

**Pull request merged**
