### PR TITLE
Add migration guide to documentation

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8283)

### CODE REVIEW

**Comment by caalador** [comment]
Looks fine and is easy enough to follow through.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/8283#-KavlRlLyF45Na6QsYW9:-KavlDick6RPl6t5MXXP:b-3anvae) ([raw file](https://github.com/vaadin/framework/blob/e28f607f7e093fa056c54912006beb540b2d3d2a/documentation/migration/migrating-to-vaadin8.asciidoc#L6)):*
>  API that have been changed between versions.
APIs that have changed between versions.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 14 at r2](https://reviewable.io:443/reviews/vaadin/framework/8283#-Kavm7Dq3cAXFxu1i7y1:-Kavm7DrSD8qGtszKUk4:btxnev9) ([raw file](https://github.com/vaadin/framework/blob/e28f607f7e093fa056c54912006beb540b2d3d2a/documentation/migration/migrating-to-vaadin8.asciidoc#L14)):*
> ```AsciiDoc
> 
> The very first step in migration is to ensure that your project is configured to use Framework 8 dependencies, as well as include any of the desired compatibility packages needed in your migration.
> Additionally, Framework 8 requires JDK 8 for development.
> ```

Also note that Framework 8 ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283#-:-Kavn5QhG8BEzZaG2sPH:bss5wd)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/8283#-KavlRlLyF45Na6QsYW9:-Kavp4W27GiAjGA4SzG5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e28f607f7e093fa056c54912006beb540b2d3d2a/documentation/migration/migrating-to-vaadin8.asciidoc#L6)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

>  API that have been changed between versions.
APIs that have changed between versions.
</blockquote></details>

Done.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 14 at r2](https://reviewable.io:443/reviews/vaadin/framework/8283#-Kavm7Dq3cAXFxu1i7y1:-Kavp5xkBpd-n6rjF1lf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e28f607f7e093fa056c54912006beb540b2d3d2a/documentation/migration/migrating-to-vaadin8.asciidoc#L14)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Also note that Framework 8 ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283#-:-Kavs439_1Ccitb4j9Ss:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 115 at r3](https://reviewable.io:443/reviews/vaadin/framework/8283#-Kb9SiR4acg7Oul24tAB:-Kb9SiR50RKVn-Hj0eGz:b-frcb88) ([raw file](https://github.com/vaadin/framework/blob/4046ac0f143f841fafa6b0ccfed1033fb94d38ce/documentation/migration/migrating-to-vaadin8.asciidoc#L115)):*
> ```AsciiDoc
> 
> Aside from minor API and default changes at the component level, the largest change in Vaadin Framework 8 is its new data model.
> Framework 8 no longer uses `Item`, `Property` nor `Container`.
> ```

Do you think that it makes sense to mention also FieldGroup/BeanFieldGroup ?
 E.g. : (and as a consequence FeildGroup and BeanFeildGroup)
or whatever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 115 at r3](https://reviewable.io:443/reviews/vaadin/framework/8283#-Kb9SiR4acg7Oul24tAB:-KbA-bDAuhbT-L_Gr0qB:b5n0aij) ([raw file](https://github.com/vaadin/framework/blob/4046ac0f143f841fafa6b0ccfed1033fb94d38ce/documentation/migration/migrating-to-vaadin8.asciidoc#L115)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Do you think that it makes sense to mention also FieldGroup/BeanFieldGroup ?
 E.g. : (and as a consequence FeildGroup and BeanFeildGroup)
or whatever.
</blockquote></details>

`FieldGroup` is mentioned when referencing the new datamodel-fields doc down below. Could add a mention here, but can't really think of a concise way of pointing it out. Suggestions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/migration/migrating-to-vaadin8.asciidoc, line 115 at r3](https://reviewable.io:443/reviews/vaadin/framework/8283#-Kb9SiR4acg7Oul24tAB:-KbA3XNtN0ueCDQcVSoH:b-41s525) ([raw file](https://github.com/vaadin/framework/blob/4046ac0f143f841fafa6b0ccfed1033fb94d38ce/documentation/migration/migrating-to-vaadin8.asciidoc#L115)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

`FieldGroup` is mentioned when referencing the new datamodel-fields doc down below. Could add a mention here, but can't really think of a concise way of pointing it out. Suggestions?
</blockquote></details>

It wasn't a complain. It was a question. I don't know how to say that here as well. I'm OK with the current version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8283)*

**Pull request merged**
