### PR TITLE
Add support for ChromeOS operating system

### PR DESCRIPTION
**Pull request by Flamenco**
Change-Id: Ic8b94adef773da0d828bcd6c1673dedbfea580c3

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9698)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxXceIffHMC1NUMReK:-KpxXceIffHMC1NUMReL:b-bae26u) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L221)):*
> ```Java
>                 os = OperatingSystem.MACOSX;
>             }
>         } else if (userAgent.contains("cros")){
> ```

related test case(s) should be added to VBrowserDetailsUserAgentParserTest

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 256 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxY52zuSIp_UCaIi8x:-KpxY52zuSIp_UCaIi8y:b-o0ym3z) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L256)):*
> ```Java
>         if (parts.length > 2) {
>             try {
>                 osMajorVersion = Integer.parseInt(parts[1]);
> ```

are the indices 1 here and 0 below really the right way around? (maybe they are, unclear to me)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by Flamenco** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 256 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxY52zuSIp_UCaIi8x:-KpxaeeFQEaMPM85liJi:b-vmjpx7) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L256)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

are the indices 1 here and 0 below really the right way around? (maybe they are, unclear to me)
</blockquote></details>

The version format is <build.version.0>  I included an example in the comment.  (X11; CrOS armv7l 6946.63.0)

See http://www.webapps-online.com/online-tools/user-agent-strings/dv/operatingsystem52026/chrome-os. They all follow the same scheme.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by Flamenco** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxXceIffHMC1NUMReK:-Kpxfvi7-PWK7jqf-lJJ:b-cht2wk) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L221)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

related test case(s) should be added to VBrowserDetailsUserAgentParserTest
</blockquote></details>

OK. Done.  Should this be as another commit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxXceIffHMC1NUMReK:-KpxyX5IYq-uMEPZxZlq:b-nbthc8) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L221)):*
<details><summary><i>Previously, Flamenco wrote…</i></summary><blockquote>

OK. Done.  Should this be as another commit?
</blockquote></details>

The condition looks too loose to me. I think it's better to use surrounding spaces as well. "cros" might be a substring of something like mobile phone model name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by Flamenco** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[shared/src/main/java/com/vaadin/shared/VBrowserDetails.java, line 221 at r1](https://reviewable.io:443/reviews/vaadin/framework/9698#-KpxXceIffHMC1NUMReK:-KpyjQE2hUKr4D70YyCn:b-3lgvoq) ([raw file](https://github.com/vaadin/framework/blob/b44ee4f7c3bd2063c3cc2cecdf9c87cd6e78a1f0/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L221)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The condition looks too loose to me. I think it's better to use surrounding spaces as well. "cros" might be a substring of something like mobile phone model name.
</blockquote></details>

I agree.  Actually, I would have split at the first closing ')' before doing any checking of the OS's, or even just a simple regex with groups at the start of the method , but I'll save that for another commit.   IIRC the GWT pattern class was not sharable on the client and server.  I'll put the leading ';' and spaces in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9698)*

**Pull request merged**
