### PR TITLE
Implement GridSortOrder and SortOrderBuilders

### LINKED ISSUE #8259: Implement a nice API for building sort orders for both Grid and Query
https://github.com/vaadin/framework/pull/8239 will partially separate the type used for sorting queries from the type used for sorting a grid. As a consequence of this, the `Sort` builder helper will no longer available for both cases.

Each case would need a separate sort builder implementation sharing the same concepts. The end result should be that the user can write code like this:

```
myGrid.setSortOrders(GridSortOrder.asc(col1).thenDesc(col2));
myDataProvider.setSortOrders(QuerySortOrder.asc("col1").thenDesc("col2"));
```

`asc` and `desc` return a `QuerySortOrderBuilder` (or `GridSortOrderBuilder<T>`) with two chaining methods (`thenAsc` and `thenDesc)` and a `build()` method that returns `List<QuerySortOrder>` (or `List<GridSortOrder<T>>`.

Each case should support the "manual" way of defining sort orders, e.g. `Grid.setSortOrders(List<GridSortOrder<T>> sortOrders)` and `DataProvider.setSortOrders(List<QuerySortOrder> sortOrders)` as well as an overload that takes a builder and does `sortSortOrders(builder.build())`.

### PR DESCRIPTION
**Pull request by ahie**
Closes #8259 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8338)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Needs rebase.

**Comment by denis-anisimov** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP81kesMsaQ6ja2hJD:-KbP81kesMsaQ6ja2hJE:buausxe) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L56)):*
> ```Java
>      * @param builder
>      *            the sort builder to retrieve the sort order from
>      * @throws IllegalArgumentException
> ```

It's NPE actually.

---

*[server/src/main/java/com/vaadin/data/provider/GridSortOrder.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP8_hWqv5t7_u9a9Bh:-KbP8_hWqv5t7_u9a9Bi:b4zhhcq) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/GridSortOrder.java#L37)):*
> sorted

I would rename this parameter to something meaningful, since the type is known here.

---

*[server/src/main/java/com/vaadin/data/provider/GridSortOrderBuilder.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP9SKmIJVw3l0wYxvz:-KbP9SKnCeqLExilYAJD:b-c6d5yr) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/GridSortOrderBuilder.java#L39)):*
> ```Java
>     @Override
>     public GridSortOrderBuilder<T> thenAsc(Column<T, ?> by) {
>         return (GridSortOrderBuilder<T>) super.thenAsc(by);
> ```

Those casts could be removed alongside with two methods if `SortOrderBuilder` would be parameterized.
See `SortOrderBuilder`comments. I'm not sure actually whether it's worth to do.

---

*[server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP9nFecyf4KTVfD50i:-KbP9nFecyf4KTVfD50j:bvy6exo) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java#L39)):*
> ```Java
>  * @see #build()
>  */
> public abstract class SortOrderBuilder<T extends SortOrder<V>, V>
> ```

Please consider:
- introduce a new parameter (let's say `B`: B extends SortOrderBuilder<T, V, B> )
- now you can introduce a method `protected abstract B self()`.
- return `self()` everywhere instead of `this`.
- subclass now should implement only `self()` and no need to cast in subclasses.

I don't insist on this. Please just consider whether it's worth to do.

---

*[server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPAg1qqKh8rDrng6L8:-KbPAg1qqKh8rDrng6L9:biybap4) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java#L73)):*
> ```Java
>      */
>     public final List<T> build() {
>         return Collections.unmodifiableList(sortOrders);
> ```

The problem with this approach is:
- the builder is mutable
- the result is expected to be immutable
- but it's not. Since the result uses inner state of the builder which is mutable.

It's still possible to mutate `sortOrders` and the result of the method in the end via the builder instance.
`build` should create a copy instead of using `sortOrders`. And no need to wrap in in unmodifiable anymore.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2820 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPIc6dKNWYbIPuETTq:-KbPIc6eerBXVVul5us-:b2nhk7y) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/ui/Grid.java#L2820)):*
> ```Java
>      * @param builder
>      *            the sort builder to retrieve the sort order from
>      * @throws IllegalArgumentException
> ```

NPE

---

*[server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPKPD_17bkGJOW4jrn:-KbPKPD_17bkGJOW4jro:b-tkz8ey) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java#L18)):*
> ```Java
> 
>     @Test
>     public void gridSortOrderBuilder_test() {
> ```

`_test` has no sense here.
The method name should either contains the initial state and expected state or nothing if it's obvious .

---

*[server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPL3zRrphADI3A_mtv:-KbPL3zRrphADI3A_mtw:bz1mfd1) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java#L43)):*
> ```Java
> 
>     @Test
>     public void querySortOrderBuilder_test() {
> ```

method name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8338)*

**Comment by ahie** [comment]
Review status: 7 of 12 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP81kesMsaQ6ja2hJD:-KbQ7BKFcuy1HWivv79S:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/BackEndDataProvider.java#L56)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It's NPE actually.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/GridSortOrder.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP8_hWqv5t7_u9a9Bh:-KbQ8KvP7Ll6f71oJ20h:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/GridSortOrder.java#L37)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> sorted

I would rename this parameter to something meaningful, since the type is known here.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP9nFecyf4KTVfD50i:-KbQ8NLUtyS7d82brx7s:bpt9cfi) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Please consider:
- introduce a new parameter (let's say `B`: B extends SortOrderBuilder<T, V, B> )
- now you can introduce a method `protected abstract B self()`.
- return `self()` everywhere instead of `this`.
- subclass now should implement only `self()` and no need to cast in subclasses.

I don't insist on this. Please just consider whether it's worth to do.
</blockquote></details>

Considered this, but I feel casts are better than adding more type parameters and an additional abstract method to implement.

---

*[server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPAg1qqKh8rDrng6L8:-KbQ7EhUmotWbRryuWXw:biy83ym) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java#L73)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The problem with this approach is:
- the builder is mutable
- the result is expected to be immutable
- but it's not. Since the result uses inner state of the builder which is mutable.

It's still possible to mutate `sortOrders` and the result of the method in the end via the builder instance.
`build` should create a copy instead of using `sortOrders`. And no need to wrap in in unmodifiable anymore.
</blockquote></details>

Done. I still kept the unmodifiable wrapper so that you can't for example modify a sort order after you have set it.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2820 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPIc6dKNWYbIPuETTq:-KbQ7DZFbX5Fd4Ytsgho:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/ui/Grid.java#L2820)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

NPE
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPKPD_17bkGJOW4jrn:-KbQ7Cyx20eBmg666Ry1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java#L18)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`_test` has no sense here.
The method name should either contains the initial state and expected state or nothing if it's obvious .
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbPL3zRrphADI3A_mtv:-KbQ7CcRXO4rTkdDxrtN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/test/java/com/vaadin/data/provider/SortOrderBuildersTest.java#L43)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

method name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8338)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/framework/8338#-KbP9nFecyf4KTVfD50i:-KbQ9VGM1LVScc_mYzlX:blvpbss) ([raw file](https://github.com/vaadin/framework/blob/8b96b2419fa60f3004d0006e54acd1b524876d9e/server/src/main/java/com/vaadin/data/provider/SortOrderBuilder.java#L39)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Considered this, but I feel casts are better than adding more type parameters and an additional abstract method to implement.
</blockquote></details>

May be you are right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8338)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8338)*

**Pull request merged**
