### PR TITLE
Remove redundant version and groupId

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9990)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 11 of 18 files at r1.
Review status: 11 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtywbRmf3WUVSJNivoz:-KtywbRnBhO3Ub0tRd2x:b-no2zll) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/bom/pom.xml#L10)):*
> ```XML
>         <relativePath />
>     </parent>
>     <groupId>com.vaadin</groupId>
> ```

Unfortunately these cannot be removed even though Maven complains about them. There is a bug in a Maven plug-in we are using in our release builds (trying to remember which one - perhaps the versions plug-in, or API diff between versions), and it crashes if the groupId is not explicitly given.

It would be good to have a comment about that.

---

*[buildhelpers/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtyxzdM2zgLvsYQYaSP:-KtyxzdM2zgLvsYQYaSQ:b-w6noed) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/buildhelpers/pom.xml#L10)):*
> ```XML
>         <version>8.2-SNAPSHOT</version>
>     </parent>
>     <groupId>com.vaadin</groupId>
> ```

see the comment above

---

*[client/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-Ktyy8HeEYKtqNJvtuGB:-Ktyy8HeEYKtqNJvtuGC:b-w6noed) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/client/pom.xml#L10)):*
> ```XML
>         <version>8.2-SNAPSHOT</version>
>     </parent>
>     <groupId>com.vaadin</groupId>
> ```

see the comment above

---

*[client-compiled/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtyyBDw0phRM9bBd8xj:-KtyyBDw0phRM9bBd8xk:b-w6noed) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/client-compiled/pom.xml#L10)):*
> ```XML
> 		<version>8.2-SNAPSHOT</version>
> 	</parent>
> 	<groupId>com.vaadin</groupId>
> ```

see the comment above

---

*[test/pom.xml, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtyzzgdYo--iBLxsi2j:-KtyzzgdYo--iBLxsi2k:b-xkr523) ([raw file](https://github.com/vaadin/framework/blob/acdf162c972283fe2ac7d1cd2e97a11acad5c370/test/pom.xml#L19)):*
> ```XML
>         <vaadin.plugin.version>${vaadin.version}</vaadin.plugin.version>
>         <failOnMissingWebXml>false</failOnMissingWebXml>
>         <contextmenu.version>2.0.0</contextmenu.version>
> ```

Is this actually used by the tests if removing the explicit version number using this in the other POMs, or does the BOM override this in that case? I think this was originally here to allow testing another context menu version with an arbitrary Vaadin version, but that does not happen very often so I think we can also handle it differently when it happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990)*

**Comment by asashour** [comment]
Review status: 11 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtywbRmf3WUVSJNivoz:-Ktz33bkeDBg-8Q0_CcL:bo54upq) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/bom/pom.xml#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Unfortunately these cannot be removed even though Maven complains about them. There is a bug in a Maven plug-in we are using in our release builds (trying to remember which one - perhaps the versions plug-in, or API diff between versions), and it crashes if the groupId is not explicitly given.

It would be good to have a comment about that.
</blockquote></details>

I thought when we have a successful build, that means everything is ok.
How can I see this error? and what happens when the version with the bug is fixed with a later plugin version?
Also, I see maven 3.1.0 is minimum, but [3.2.5](https://maven.apache.org/docs/history.html) is the last one for Java 6.
I will revert back the change, putting a comment "potential plugin crash".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990)*

**Comment by hesara** [comment]
Review status: 11 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtywbRmf3WUVSJNivoz:-Ktz538jdsDZz405b7Ho:bjmj7vu) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/bom/pom.xml#L10)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I thought when we have a successful build, that means everything is ok.
How can I see this error? and what happens when the version with the bug is fixed with a later plugin version?
Also, I see maven 3.1.0 is minimum, but [3.2.5](https://maven.apache.org/docs/history.html) is the last one for Java 6.
I will revert back the change, putting a comment "potential plugin crash".
</blockquote></details>

Our release process on the release CI server currently well over a dozen steps to stage a version (combining a few related projects to a single staging repository), and several to release a staged version. Furthermore, there are chained test builds that test other projects against a staging repository when making a release. Several Maven plug-ins are used either directly from command line or based on profiles in our release settings files. Plug-ins used in builds on the CI servers include setting versions, signing, management of staging repositories, computing API diffs to a reference version etc. and most of those are not included in the validation builds, which are run on another CI server. For obvious reasons, we cannot provide access to the release servers or settings.

For most contributors who focus on the Java side, this usually isn't a problem. When working on the POMs, I'm afraid we need to manage such occasional issues through review comments.

This particular issue would only have come up in builds we normally run on the main release branches daily, not on PRs. Thus my comments based on a recollection of the situation (at least still fairly recently).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990)*

**Comment by asashour** [comment]
Review status: 10 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[bom/pom.xml, line 10 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtywbRmf3WUVSJNivoz:-KtzGzvtzlGGwWNf-ePY:b-1x9ezx) ([raw file](https://github.com/vaadin/framework/blob/ce25750a8fd3642cf1ed7d0dac708517d5bfd226/bom/pom.xml#L10)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Our release process on the release CI server currently well over a dozen steps to stage a version (combining a few related projects to a single staging repository), and several to release a staged version. Furthermore, there are chained test builds that test other projects against a staging repository when making a release. Several Maven plug-ins are used either directly from command line or based on profiles in our release settings files. Plug-ins used in builds on the CI servers include setting versions, signing, management of staging repositories, computing API diffs to a reference version etc. and most of those are not included in the validation builds, which are run on another CI server. For obvious reasons, we cannot provide access to the release servers or settings.

For most contributors who focus on the Java side, this usually isn't a problem. When working on the POMs, I'm afraid we need to manage such occasional issues through review comments.

This particular issue would only have come up in builds we normally run on the main release branches daily, not on PRs. Thus my comments based on a recollection of the situation (at least still fairly recently).
</blockquote></details>

Clear, thanks, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990)*

**Comment by asashour** [comment]
Review status: 10 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/pom.xml, line 19 at r1](https://reviewable.io:443/reviews/vaadin/framework/9990#-KtyzzgdYo--iBLxsi2j:-KtzH7jRzmnzblLqYA02:b-h7q6xr) ([raw file](https://github.com/vaadin/framework/blob/acdf162c972283fe2ac7d1cd2e97a11acad5c370/test/pom.xml#L19)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this actually used by the tests if removing the explicit version number using this in the other POMs, or does the BOM override this in that case? I think this was originally here to allow testing another context menu version with an arbitrary Vaadin version, but that does not happen very often so I think we can also handle it differently when it happens.
</blockquote></details>

If it is removed, it uses the one in `bom`. Now fixed by removal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 3 of 18 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9990#-:-KtzvTgno-EDK0ht4Vkz:bnfp4nl)*

**Pull request merged**
