### PR TITLE
Add css class to selected items in CheckboxGroup and RadiobuttonGroup

### PR DESCRIPTION
**Pull request by mcollovati**
Adds v-select-option-selected class to the selected
group items in CheckboxGroup and RadiobuttonGroup
References #3387

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10394)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArylYwvF4XJ64YaWr:-L-ArylYwvF4XJ64YaWs:b-klrv5a) (no related file):*
You should add the mention of the selected style name to https://github.com/vaadin/framework/blob/master/documentation/components/components-optiongroups.asciidoc#css-style-rules

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArlMugARgottdTPCy:-L-ArlMugARgottdTPCz:bl1mki7) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L154)):*
> ```Java
>         button.setHTML(itemHtml);
>         button.setValue(
>                 item.getBoolean(ListingJsonConstants.JSONKEY_ITEM_SELECTED));
> ```

Should this be removed and instead you pass the value from the Json to the `updateItemSelection(...)` call ? 

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 270 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArWpyLENXiALizv9S:-L-ArWpyLENXiALizv9T:b-ut7610) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L270)):*
> ```Java
>             if (radioButton != null) { // Items might not be loaded yet
>                 radioButton.setValue(true);
>                 radioButton.setStyleName(CLASSNAME_OPTION_SELECTED, true);
> ```

Why isn't this using `updateItemSelection(..)` ?

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-AsKJ9rfjvUhPdFQ_J:-L-AsKJ9rfjvUhPdFQ_K:b4pm8lx) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L204)):*
> ```Java
> 
>         String className = getSelect().findElements(By.tagName("span")).get(5).getAttribute("className");
>         assertEquals("No v-select-option-selected class, was " + className,
> ```

I'd prefer using `assertFalse` / `assertTrue` instead of `assertEquals` for these
(If we have hamcrest in the classpath, you could use  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10394)*

**Comment by mcollovati** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArylYwvF4XJ64YaWr:-L-BGoBYNHvpOQwSKyIk:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You should add the mention of the selected style name to https://github.com/vaadin/framework/blob/master/documentation/components/components-optiongroups.asciidoc#css-style-rules
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArlMugARgottdTPCy:-L-BGa_8FjE1Pa0094mH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L154)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should this be removed and instead you pass the value from the Json to the `updateItemSelection(...)` call ? 
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 270 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-ArWpyLENXiALizv9S:-L-BGdYaRcpkyK1oqJvY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L270)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why isn't this using `updateItemSelection(..)` ?
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java, line 204 at r1](https://reviewable.io:443/reviews/vaadin/framework/10394#-L-AsKJ9rfjvUhPdFQ_J:-L-BGiY6L80PsNWRBGaK:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d03e16b3b5b712f7d09a90dbb23f64f093325332/uitest/src/test/java/com/vaadin/tests/components/radiobuttongroup/RadioButtonGroupTest.java#L204)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I'd prefer using `assertFalse` / `assertTrue` instead of `assertEquals` for these
(If we have hamcrest in the classpath, you could use  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10394)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10394)*

**Comment by tsuoanttila** [comment]
This patch might need to be rebased/merged with `master` to make it pass our new validation build. Can you do it, or should I?

**Pull request merged**
