### PR TITLE
Pick changes on top of 8.3.2

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10735)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10735#-L82Wd05s_JoOthZMfvE:-L82Wd05s_JoOthZMfvF:b-c82u8g) (no related file):*
This cherry-pick patch is still waiting for more potential candidates for 8.3.3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10735)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 7 of 7 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10735#-:-L82XrGrunGpgboJsIgD:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r8, 2 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10735)*

**Comment by elmot** [comment]
Reviewed 7 of 7 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10735)*

**Pull request merged**
