### PR TITLE
Java class should be final

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10051)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 56 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10051#-KuY9WBvlcexqZZxnAZh:-KuY9WBvlcexqZZxnAZi:bml788p) (no related file):*
I'm afraid many of these - at least on the server side - cannot be merged as there are frameworks that depend upon creation of subclasses by bytecode generation for proxying, and those don't work for final classes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10051)*

**Comment by hesara** [comment]
Review status: 0 of 56 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10051#-KuY9WBvlcexqZZxnAZh:-KuYASzgCQI2fTX-0WCm:b-xijuw2) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm afraid many of these - at least on the server side - cannot be merged as there are frameworks that depend upon creation of subclasses by bytecode generation for proxying, and those don't work for final classes.
</blockquote></details>

I'll try to look at these case by case sometime later - perhaps the ones you marked as final are not that problematic after all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10051)*

**Comment by asashour** [comment]
Review status: 0 of 56 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10051#-KuY9WBvlcexqZZxnAZh:-KuYCpuJk3a96IUeljm6:bf9qsv8) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'll try to look at these case by case sometime later - perhaps the ones you marked as final are not that problematic after all.
</blockquote></details>

By the way, they were automatically detected, and they all have private constructors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10051)*

**Comment by jreznot** [comment]
Please, guys! Do not do this! You will break a lot of extended classes and it is really bad idea to use closed inheritance for Vaadin.

**Comment by jreznot** [comment]
We'd prefer that Vaadin would be as open as possible and there would be no final classes and methods et all. If you decided to move in this direction we will have no choice, we will have to completely fork Vaadin and maintain open-inheritance version of the framework.

**Comment by asashour** [comment]
@jreznot: obviously, keeping the project as open as possible is a goal.

This is not a general task to make 'final' classes, but the target classes are already having private constructors, and are never meant to be instantiated or subclassed.

Please review the change, and specify if any specific class is an issue for you.

**Comment by jreznot** [comment]
I am afraid that if they marked as final that they will be final ever. Now we usually change a lot of private / final / package-private modifier in our fork and these changes simply add additional work for us

**Comment by hesara** [comment]
Due to votes against this and the fact that this does not bring any direct benefits, closing this PR.

**Pull request closed without merging**
