### PR TITLE
Use String.isEmpty()

### PR DESCRIPTION
**Pull request by asashour**
`String.isEmpty()` is slightly faster and more readable than `str.equals("")`.

The potential places were `"".equals(string)` could check for `NullPointerException` are untouched.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10021)

### CODE REVIEW

**Comment by hesara** [comment]
Restarted the validation build that had timed out, very quick partial review so far. Note that traditional rules on what is faster on the JVM do not necessarily apply to the client side, but the argument about readability applies nevertheless.

---

Reviewed 18 of 44 files at r1.
Review status: 18 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10021#-:-KuNhvHmmeWwmkYkDHX6:b-4hsq6z)*

**Comment by hesara** [comment]
I dug up the code for String used on the GWT side, and it does seem to use length on a JS string, which modern browsers precompute and cache in the string object so performance is not an reason not to do this ( https://github.com/gwtproject/gwt/blob/7e730fe14c533c2975dd77554ad738b28773ec0e/user/super/com/google/gwt/emul/java/lang/String.java#L481 ). We'll try to review the rest of the changes soon.

---

Review status: 18 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10021#-:-KuOgo3zvimuyoaaaOui:b-awrnhp)*

**Comment by asashour** [comment]
Thanks for your efforts, and for propagating the knowledge.

---

Review status: 18 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10021#-:-KuOhyaYm4vC2KdAGvVg:b-fg8wds)*

**Comment by hesara** [comment]
Reviewed 26 of 44 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10021)*

**Pull request merged**
