### PR TITLE
Ensure pop-up is not opened, when tabbing out fast from Combobox

### PR DESCRIPTION
**Pull request by anasmi**
Currently tabbing out from Combobox quickly into another one, opens the popup window. 
The event chain is following: 

- Pressing any letter. `A`, for example( `KeyDownEvent` 1. CB)
- Pressing tab (`KeyDownEvent` 1.CB)
- Blur Event happens (the 2.nd CB is focused)
- `KeyUpEvent` for letter `A`
- `KeyUpEvent` for `Tab`

As `KeyUpEvent` is caught only by focused component, the popup is opened incorrectly for the currently focused component, not the one where button was originally pressed. To prevent filtering (which is called from KeyUpEvent handler) check that the `keyDown` event was called prior in the current combobox. Also, prevent showing the popup, if field is not focused anymore.

Related to https://github.com/vaadin/framework/issues/11354 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11436)

### CODE REVIEW

**Review by tepi — COMMENTED** [review]
The fix seems to fix the issue when testing manually, and looks otherwise ok as well. However the test does not seem to be ok: It passes whether I have the fix applied or not. It should fail when the fix is not applied.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11436#-:-LYSGMW_00vXANWOiYeB:b740wqo)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by anasmi** [comment]
@tepi sorry for long delay. I've tried to come up with the idea, how to test it reliable, but I am not sure, we can.
- Trying to set value via JS into combobox doesn't fire filtering, therefore no pop-up is showing. 
- `sendKeys` doesn't imitate the situation either.(I think because it's too slow, but I am not sure)
- The screenshot comparison will not have any effect either, as I can get broken screen automatically. 
Therefore, would you pass the pull request if I remove the test all in all? Or should I still try to figure out a way to test is reliably?

**Comment by tepi** [comment]
Yeah, looks like this is one of those cases you can't really test reliably or at all. I am fine with removing the test, makes no sense to spend too much time on it.

**Review by tepi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11436)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
