### PR TITLE
Fixing a bug related to Grid height by row

### LINKED ISSUE #11087: Wrong height of Grid inside TabSheet
**Vaadin Framework version**
8.4.5

**Browser version**

- Chrome 67
- IE 10
- (but does not really matter)

**Web container name and version**
Jetty 9.3.9

**Description of the bug**

The height of the Grid on the first Tab is miscalculated when switching between the tabs. It resizes correctly when pressing the button.
This seems to be a regression introduced in 8.4.2. In 8.4.1 the behavior is better, although not perfect.

**Minimal reproducible example**

```
final VerticalLayout layout = new VerticalLayout();

List<String> data = new ArrayList<>();
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");
data.add("Data");

Panel panel = new Panel("Panel Tab");
panel.setHeight(100, Unit.PERCENTAGE);

TabSheet tabSheet = new TabSheet();
tabSheet.addTab(panel);
Label l = new Label("Just a label");
l.setCaption("Tab 2");
tabSheet.addTab(l);

Button button = new Button("Add Data");

Grid<String> grid = new Grid<>();
grid.addColumn(String::toString).setCaption("Test");
ListDataProvider<String> provider = DataProvider.ofCollection(data);
grid.setDataProvider(provider);

grid.setHeightMode(HeightMode.UNDEFINED);
grid.setRowHeight(50);

button.addClickListener(new ClickListener() {

	@Override
	public void buttonClick(ClickEvent event) {
		data.add("Data");
		grid.getDataProvider().refreshAll();
	}
});

VerticalLayout vl = new VerticalLayout();
vl.addComponent(grid);

panel.setContent(vl);
layout.addComponents(button, tabSheet);
```

**Expected behavior**

The Grid is fully visible when switching back to the first tab.

**Actual behavior**

The Grid is visually cut off at the bottom (see screenshot). It resizes correcty when pressing the button.

2018-07-26-vaadin-bug

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
Fixes #11087

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)

### CODE REVIEW

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @mehdi-vaadin and @tsuoanttila)

___
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridHeightByRow.java, line 15 at r2](https://reviewable.io/reviews/vaadin/framework/11090#-LIdmvkT0U7aM5jO7Gyn:-LIdmvkT0U7aM5jO7Gyo:b92akop) ([raw file](https://github.com/vaadin/framework/blob/fe7c60bf5cd990bc3be029cc62105b0708aedac0/uitest/src/main/java/com/vaadin/tests/components/grid/GridHeightByRow.java#L15)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

Remove empty JavaDoc block
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridHeightByRowTest.java, line 15 at r2](https://reviewable.io/reviews/vaadin/framework/11090#-LIdnGZOBeOKBQTXFQkJ:-LIdnGZOBeOKBQTXFQkK:bixhaah) ([raw file](https://github.com/vaadin/framework/blob/fe7c60bf5cd990bc3be029cc62105b0708aedac0/uitest/src/test/java/com/vaadin/tests/components/grid/GridHeightByRowTest.java#L15)):*
> ```Java
>     public void setup() throws Exception {
>         super.setup();
>         openTestURL();
> ```

rather than override the setup, have the `openTestURL` as the first action in the test. 4 lines less of code.

**Review by mehdi-vaadin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @tsuoanttila)

___
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridHeightByRow.java, line 15 at r2](https://reviewable.io/reviews/vaadin/framework/11090#-LIdmvkT0U7aM5jO7Gyn:-LIdococ8zXBE-_ZuN8V:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fe7c60bf5cd990bc3be029cc62105b0708aedac0/uitest/src/main/java/com/vaadin/tests/components/grid/GridHeightByRow.java#L15)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Remove empty JavaDoc block
</blockquote></details>

Done.
___
*[uitest/src/test/java/com/vaadin/tests/components/grid/GridHeightByRowTest.java, line 15 at r2](https://reviewable.io/reviews/vaadin/framework/11090#-LIdnGZOBeOKBQTXFQkJ:-LIdoe8jEMkHS6L0fLCl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fe7c60bf5cd990bc3be029cc62105b0708aedac0/uitest/src/test/java/com/vaadin/tests/components/grid/GridHeightByRowTest.java#L15)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

rather than override the setup, have the `openTestURL` as the first action in the test. 4 lines less of code.
</blockquote></details>

Done.

**Comment by tsuoanttila** [comment]
___
*[uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java, line 72 at r3](https://reviewable.io/reviews/vaadin/framework/11090#-LIe_LGD4mjCLLDDWONV:-LIe_LGEDorI6ppNuCXX:b-75ywm7) ([raw file](https://github.com/vaadin/framework/blob/773436775b64f52b26e05e4eb316fa04b62502f9/uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java#L72)):*
> ```Java
> 
>         moreItem.click();
>         waitForElementPresent(By.className("v-menubar-submenu"));
> ```

why is this needed?

**Review by tsuoanttila — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

**Review by mehdi-vaadin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

___
*[uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java, line 72 at r3](https://reviewable.io/reviews/vaadin/framework/11090#-LIe_LGD4mjCLLDDWONV:-LIec8Kh4TQnlrf2Ijwf:b-5cv2da) ([raw file](https://github.com/vaadin/framework/blob/773436775b64f52b26e05e4eb316fa04b62502f9/uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java#L72)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

The test failed because "Filter 5" could not be found and `NoSuchElementException` was thrown.

**Comment by tsuoanttila** [comment]
___
*[uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java, line 72 at r3](https://reviewable.io/reviews/vaadin/framework/11090#-LIe_LGD4mjCLLDDWONV:-LIecs5NDlnbAaxVPe5m:bve2k11) ([raw file](https://github.com/vaadin/framework/blob/773436775b64f52b26e05e4eb316fa04b62502f9/uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java#L72)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

The test failed because "Filter 5" could not be found and `NoSuchElementException` was thrown.
</blockquote></details>

Main question is: why did it pass before?

**Review by mehdi-vaadin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

___
*[uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java, line 72 at r3](https://reviewable.io/reviews/vaadin/framework/11090#-LIe_LGD4mjCLLDDWONV:-LIed24E1pVaxbi6UZYk:b-bw95yw) ([raw file](https://github.com/vaadin/framework/blob/773436775b64f52b26e05e4eb316fa04b62502f9/uitest/src/test/java/com/vaadin/tests/components/menubar/MenuBarIconsTest.java#L72)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Main question is: why did it pass before?
</blockquote></details>

Good question :) I assume it's a matter of time and CPU speed and ...

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11090)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
