### PR TITLE
Fix partly missing drag image regression on Safari

### LINKED ISSUE #9261: Safari is missing drag image for Grid rows
When an element has `position: absolute/fixed;` and the is a any of the offset `top/right/bottom/left/` set, the drag image is not shown for that element on Safari. This happens in `Grid` when anything else except the top most row is dragged.

Trying to change the position or parent element position _temporarily_ to `relative` doesn't do the trick for Grid, nor clearing the offsets.

### PR DESCRIPTION
**Pull request by pleku**
Doesn't fix #9261, drag image missing on Safari when dragging grid row because
that has position: absolute and offset.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9262)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-Kjb-pj-D89-h9KeSMIC:b-6pa3rt) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
> ```Java
>         });
> 
>         // #9261
> ```

What does this comment mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by elmot** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 148 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-KjbAsumrVYVNVUvtUmH:-KjbAsunT1HQ7pjepZuf:bfrernu) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L148)):*
> ```Java
>                 setDraggable(draggedRowElement);
>             }
>             fixDragImageForSadfari(draggedRowElement);
> ```

nice typo Sa**d**fari

---

*[themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb9oXVNRmCzqGYNTfK:-Kjb9oXVNRmCzqGYNTfL:br51ukr) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss#L283)):*
>  user-select:
Should not be that mentioned in `documentation/advanced/advanced-dragndrop.asciidoc` together with  `user-select: none`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by elmot** [comment]
Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by pleku** [comment]
Review status: 3 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 148 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-KjbAsumrVYVNVUvtUmH:-Kjid9Ihq5MLFZnCU3t9:bc4em0y) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L148)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

nice typo Sa**d**fari
</blockquote></details>

"oops"

---

*[themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb9oXVNRmCzqGYNTfK:-KjidD0Mr6xnbm7WbuIC:b-8bv4yk) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss#L283)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

>  user-select:
Should not be that mentioned in `documentation/advanced/advanced-dragndrop.asciidoc` together with  `user-select: none`?
</blockquote></details>

clarified doc

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-KjidT93DwHWXOPK48ax:b4ljw2k) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What does this comment mean?
</blockquote></details>

Not sure why some part of test ui that has a ticket number requires further clarifying since there is the ticket that describes the bug...g

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb9oXVNRmCzqGYNTfK:-Kjl317Pj3YSFT2eENWT:b-ko2465) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss#L283)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

clarified doc
</blockquote></details>

What about rest of `-xxx-user-select` selectors? There is only standard `user-sellect`

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-Kjl26vfBBMwkQkSc19f:b1mx89l) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure why some part of test ui that has a ticket number requires further clarifying since there is the ticket that describes the bug...g
</blockquote></details>

If the ticket system is migrated to somewhere, all the ticket numbers are useless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by pleku** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss, line 283 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb9oXVNRmCzqGYNTfK:-KjlCZb197kpYhVyFFQ0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/themes/src/main/themes/VAADIN/themes/valo/shared/_overlay.scss#L283)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What about rest of `-xxx-user-select` selectors? There is only standard `user-sellect`
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-KjlAUx0QQ5Nj_L3wXbf:b8gwhzl) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

If the ticket system is migrated to somewhere, all the ticket numbers are useless.
</blockquote></details>

All old trac tickets are still accessible for us, and also redirect to the correct github migrated ticket.

And I don't think we're not going to migrate anywhere any time soon. And if we are going to, #FFS it should it not matter now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by elmot** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 78 at r3](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjlkya2Hh71Emgq8Di4:-Kjlkya2Hh71Emgq8Di5:brak5j3) ([raw file](https://github.com/vaadin/framework/blob/1f792642b3e8fcb37a808954147875cfed6a3a76/documentation/advanced/advanced-dragndrop.asciidoc#L78)):*
> ```AsciiDoc
> [NOTE]
> ====
> The browsers allow the user to select and drag and drop text, which may cause some issues when trying to drag a component that has text. You can fix this by setting the following style rule to the drag source component to prevent dragging of the text instead of the whole component.
> ```

Reverted by accident?

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-Kjll5DcTQ57NUkrbWF7:brak5j3) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

All old trac tickets are still accessible for us, and also redirect to the correct github migrated ticket.

And I don't think we're not going to migrate anywhere any time soon. And if we are going to, #FFS it should it not matter now
</blockquote></details>

Reverted by accident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by pleku** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 78 at r3](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjlkya2Hh71Emgq8Di4:-Kjllc7C8ndN2P2AczTq:b-80xfag) ([raw file](https://github.com/vaadin/framework/blob/1f792642b3e8fcb37a808954147875cfed6a3a76/documentation/advanced/advanced-dragndrop.asciidoc#L78)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Reverted by accident?
</blockquote></details>

Sorry

---

*[uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/framework/9262#-Kjb-pizUMVJfrX-omEM:-KjlljFdlvnDkxDAXcMQ:b-7jc0aw) ([raw file](https://github.com/vaadin/framework/blob/f716225ca9a36f15734685b8ad22b9804367db31/uitest/src/main/java/com/vaadin/tests/dnd/DragImage.java#L57)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Reverted by accident?
</blockquote></details>

sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9262#-:-Kjm9ZjyiVdpbDZn_6yc:bnfp4nl)*

**Pull request merged**
