### PR TITLE
Optimize grid by avoiding redundant row refreshes

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8874)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8874#-KfeTRx13tSxvSlMR-er:-KfeTRx13tSxvSlMR-es:b-s0mktg) (no related file):*
Do not submit before full test run completes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8874#-KfeTRx13tSxvSlMR-er:-Kff09UEo7pmslIq3gnc:b-eizbeb) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Do not submit before full test run completes.
</blockquote></details>

Test run completed with 2 new failures - one unrelated Calendar failure on IE11 (worked when retested locally) and one a sub-pixel rendering issue on IE11 (already seen in other branches as well).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8874#-KfknSRrLKetv8SLW_YX:-KfknSRrLKetv8SLW_YY:b-ct4iiz) (no related file):*
I think the following internal calls in `Grid` to `refreshBody` could be also maybe to use the scheduled version:

- `setStylePrimaryName(String)` - this is called on state updates from `AbstractComopnentConnector`, don't think it requires immediate refreshing of anything
- `setSelectionModel(SelectionModel<T>) - changes the renderer so it is the same as the `setRenderer` that was already done
- `setSelectColumnRenderer(Renderer<Boolean>)` - this is actually called by the `setSelectionModel(..)` above and could be set as scheduled for same reasons
- `setRowStyleGenerator(RowStyleGenerator<T>)` - called from `GridConnector.init()`, no need to do immediately refresh
- `setCellStyleGenerator(CellStyleGenerator<T>)` - called from `GridConnector.init()`, no need to do immediately refresh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8874#-KfknSRrLKetv8SLW_YX:-KflHr4CpSystzinjjUH:b6pfc3x) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think the following internal calls in `Grid` to `refreshBody` could be also maybe to use the scheduled version:

- `setStylePrimaryName(String)` - this is called on state updates from `AbstractComopnentConnector`, don't think it requires immediate refreshing of anything
- `setSelectionModel(SelectionModel<T>) - changes the renderer so it is the same as the `setRenderer` that was already done
- `setSelectColumnRenderer(Renderer<Boolean>)` - this is actually called by the `setSelectionModel(..)` above and could be set as scheduled for same reasons
- `setRowStyleGenerator(RowStyleGenerator<T>)` - called from `GridConnector.init()`, no need to do immediately refresh
- `setCellStyleGenerator(CellStyleGenerator<T>)` - called from `GridConnector.init()`, no need to do immediately refresh

</blockquote></details>

Done, starting a full test build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8874#-KfknSRrLKetv8SLW_YX:-KfoeshOZg0qSswm42j0:bpm5al3) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Done, starting a full test build
</blockquote></details>

No new test failures in full build with these changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8874)*

**Pull request merged**
