### PR TITLE
Fix bad grammar in declarative documentation

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10236)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10236#-:-Kx7S3Y5dOd3yjiktK4V:bnfp4nl)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[documentation/application/application-declarative.asciidoc, line 328 at r1](https://reviewable.io:443/reviews/vaadin/framework/10236#-Kx7TQxR84BEI_xOsNGn:-Kx7TQxR84BEI_xOsNGo:b-ir5w7h) ([raw file](https://github.com/vaadin/framework/blob/01a6546e4a7a7926503555f4d8c51c2853d53e65/documentation/application/application-declarative.asciidoc#L328)):*
> ```AsciiDoc
> === Using a Design
> 
> You can create and use a declaritively defined component just like any other component.
> ```

I guess it should be [declaratively](http://www.dictionary.com/browse/declaratively)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10236)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[documentation/application/application-declarative.asciidoc, line 328 at r1](https://reviewable.io:443/reviews/vaadin/framework/10236#-Kx7TQxR84BEI_xOsNGn:-Kx7uzkkfyMCEZpBLunf:buketii) ([raw file](https://github.com/vaadin/framework/blob/01a6546e4a7a7926503555f4d8c51c2853d53e65/documentation/application/application-declarative.asciidoc#L328)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

I guess it should be [declaratively](http://www.dictionary.com/browse/declaratively)
</blockquote></details>

Indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10236)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10236)*

**Pull request merged**
