### PR TITLE
Add TestBench API as an expected artifact in build report

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8075)

### CODE REVIEW

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8075#-:-KZ_hRCe3vbhHEaJcC1f:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/GenerateBuildTestAndStagingReport.py, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8075#-KZ_kuJ6-IijJe_glCcy:-KZ_kuJ6-IijJe_glCcz:b-r1mgsz) ([raw file](https://github.com/vaadin/framework/blob/9c493e852d2e166443a5a91111684547bfabf236/scripts/GenerateBuildTestAndStagingReport.py#L115)):*
> Expected artifacts found
The message is changed from negative to positive.

Is it intentionally ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8075)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8075)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/GenerateBuildTestAndStagingReport.py, line 115 at r1](https://reviewable.io:443/reviews/vaadin/framework/8075#-KZ_kuJ6-IijJe_glCcy:-KZ_m7Bw6-hG2xsmbKnh:b-fv95i1) ([raw file](https://github.com/vaadin/framework/blob/9c493e852d2e166443a5a91111684547bfabf236/scripts/GenerateBuildTestAndStagingReport.py#L115)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Expected artifacts found
The message is changed from negative to positive.

Is it intentionally ?
</blockquote></details>

yes - changed the verb as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8075)*

**Pull request merged**
