### PR TITLE
Add shorthands to ComboBox for setting a ListDataProvider

### PR DESCRIPTION
**Pull request by Legioth**
This is one of many steps towards #8245

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8302)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9DVsqoOtcHdRXHXo8:-Kb9DVsqoOtcHdRXHXo9:ber7oyj) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/main/java/com/vaadin/ui/ComboBox.java#L214)):*
> ```Java
> 
>     @Override
>     public void setItems(Collection<T> items) {
> ```

I think now this method also needs some javadoc, similar to following one. Might be a part of any other PR.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 279 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9E0fWUHv3uWWN06u7:-Kb9E0fXqIdv9UGO5TUU:bcavkaf) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/main/java/com/vaadin/ui/ComboBox.java#L279)):*
> ```Java
>      */
>     public void setDataProvider(ListDataProvider<T> listDataProvider,
>             CaptionFilter captionFilter) {
> ```

Having different order of parameters looks confusing for me.
compare: 
``setDataProvider(ListDataProvider, CaptionFilter )`` vs ``setItems(CaptionFilter, Collection<T>) ``

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 135 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9ITZlx2JDp8rrm8U7:-Kb9ITZmIXKXHyvH8o-Z:b-anjvxp) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L135)):*
> ```Java
>         comboBox.setItemCaptionGenerator(Person::getFirstName);
> 
>         // Result: typing "en" into the search field finds "Enrique Iglesias"
> ```

'er' or 'en'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 125 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9dZ6Uwy9CBF8roODG:-Kb9dZ6Uwy9CBF8roODH:bnowaze) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L125)):*
> ```Java
> 
>         // Result: typing "en" into the search field finds "Enrique Iglesias"
>         // and "Henry Dunant", but not "Erwin Engelbrecht"
> ```

Is this comment valid at all (here and everywhere else ) ?
Why does it find Henry Dunant", but not "Erwin Engelbrecht" ?

"Henry" doesn't start from "en" but it contains, exactly as "Engelbrecht" (and if it case sensitive then why does it find "Enrique Iglesias" ?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9DVsqoOtcHdRXHXo8:-KbA6ohyKgCDz4XmgCIx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/main/java/com/vaadin/ui/ComboBox.java#L214)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I think now this method also needs some javadoc, similar to following one. Might be a part of any other PR.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 279 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9E0fWUHv3uWWN06u7:-KbA73_eXfV5siwiZ6Th:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/main/java/com/vaadin/ui/ComboBox.java#L279)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Having different order of parameters looks confusing for me.
compare: 
``setDataProvider(ListDataProvider, CaptionFilter )`` vs ``setItems(CaptionFilter, Collection<T>) ``
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 125 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9dZ6Uwy9CBF8roODG:-KbA7AhkX4ejgUz_7Xv6:b-djcu7t) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L125)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is this comment valid at all (here and everywhere else ) ?
Why does it find Henry Dunant", but not "Erwin Engelbrecht" ?

"Henry" doesn't start from "en" but it contains, exactly as "Engelbrecht" (and if it case sensitive then why does it find "Enrique Iglesias" ?)
</blockquote></details>

I think the comment is correct. It will do a case insensitive substring lookup based on only the first name (because of the caption provider). This will find **En**rique and  H**en**ry but not Erwin.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 135 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9ITZlx2JDp8rrm8U7:-KbA8IZP2rnnX8NVjBEh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L135)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

'er' or 'en'?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 125 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9dZ6Uwy9CBF8roODG:-KbA96WBWRAU1mWAQVVL:bxr7t4u) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L125)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I think the comment is correct. It will do a case insensitive substring lookup based on only the first name (because of the caption provider). This will find **En**rique and  H**en**ry but not Erwin.
</blockquote></details>

If it's correct here then what about above and below ?
As I understand ` String::startsWith` the only filter which will be used there.
But then the comments are wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by Legioth** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 125 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9dZ6Uwy9CBF8roODG:-KbAAVc6ZSdyDatd8oLW:bwsf7n1) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L125)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

If it's correct here then what about above and below ?
As I understand ` String::startsWith` the only filter which will be used there.
But then the comments are wrong.
</blockquote></details>

The comments above and below for the `String::startsWith` tests were fixed in r2. It seems like the same comment was accidentally copy-pasted into all tests even though it was only correct for the ones that used the default filtering logic (i.e. case insensitive substring).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 135 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9ITZlx2JDp8rrm8U7:-KbAAFHbSsItjBKtFTOp:bvpkeoz) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L135)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The comment is wrong. In fact,
"Er" finds "Erwin...", but not "Henry..." or "Enrique..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java, line 135 at r1](https://reviewable.io:443/reviews/vaadin/framework/8302#-Kb9ITZlx2JDp8rrm8U7:-KbAB4X3f8VoIg6IT4x_:b-a4wcvi) ([raw file](https://github.com/vaadin/framework/blob/3081787270528f40d046dfde7662013bd6fcb47a/server/src/test/java/com/vaadin/tests/server/component/combobox/ComboBoxFilteringTest.java#L135)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The comment is wrong. In fact,
"Er" finds "Erwin...", but not "Henry..." or "Enrique..."

</blockquote></details>

Oops. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8302#-:-KbAP6X1tM_2zlxqRtdW:bnfp4nl)*

**Pull request merged**
