### PR TITLE
Update DataProvider documentation for beta

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8023)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKwhXlgQ2fOwSIrSeb:-KZKwhXlgQ2fOwSIrSec:bjuanx8) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L55)):*
> ```AsciiDoc
> ----
> 
> Listing components that allow the user to control the display order of the items are automatically able to sort data by any property as long as the property type implements [classname]#Comparable#.
> ```

I might want to take this out of here and move it to be inside the subtopic of Sorting

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKvyDzsWtOVmbPLjzh:-KZKvyDzsWtOVmbPLjzi:b-mgzblq) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L67)):*
> ```AsciiDoc
> ----
> 
> With listing components that let the user filter items, we can in the same way define our own [interfacename]#CaptionFilter# that is used to decide whether a specific item should be shown when the user has entered a specific text into the text field.
> ```

Kind of confusing since ComboBox is the only component that allows doing this. Why not just say that "ComboBox lets the user filter..." ?

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKwQWNfVmqoryMjUmW:-KZKwQWNfVmqoryMjUmX:bfmsyda) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L83)):*
> ```AsciiDoc
> We can apply different sorting options for each component using the `sortingBy` method.
> The method creates a new data provider using the same data, but different settings.
> This means that we can apply different sorting options for different components.
> ```

Should there be a subtopic before this paragraph for ==Sorting DataProvider== or something ? 

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 294 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKyPLBFoVMGkICOYkV:-KZKyPLBFoVMGkICOYkW:bz13e19) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L294)):*
> ```AsciiDoc
> Note that the filter type of the `johnPersons` instance is `Void`, which means that the data provider doesn't support any further filtering.
> 
> `ListDataProvider` is filtered by callbacks that you can define as lambda expressions, method references or implementations of `SerializablePredicate`.
> ```

Not sure if this ListDataProvider filtering part should be moved up to be a subtopic for the first section about in-memory / ListDataProvider, after Sorting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKzYhHSFfke8KaUs2X:-KZKzYhHSFfke8KaUs2Y:bd6my3w) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L269)):*
> ```AsciiDoc
> ----
> 
> === Filtering
> ```

Not sure if there should be a brief mentioning in the beginning here that "this is for beta-1 and is expected to change a bit before final" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKwhXlgQ2fOwSIrSeb:-KZL1yW67iO863C1faDa:b-ovrijk) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L55)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I might want to take this out of here and move it to be inside the subtopic of Sorting
</blockquote></details>

The "Sorting" header if for lazy loading providers. Since this section covers everything not related to in-memory usage, each part is so small that it would feel inconvenient to have separate sub headings.

I'll add a note that refers to lazy sorting.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 67 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKvyDzsWtOVmbPLjzh:-KZL29SfvtkDXVURcmcC:b-hta413) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L67)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Kind of confusing since ComboBox is the only component that allows doing this. Why not just say that "ComboBox lets the user filter..." ?
</blockquote></details>

This is generic documentation about the concepts.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKwQWNfVmqoryMjUmW:-KZL3v8h2H3naSxBXdCV:b-al4c7v) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L83)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should there be a subtopic before this paragraph for ==Sorting DataProvider== or something ? 
</blockquote></details>

I'm not sure. There would need to be quite many heading throughout this entire section in that case.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKzYhHSFfke8KaUs2X:-KZL40Zjnr6PbHRM1guQ:b-3iq7h3) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L269)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure if there should be a brief mentioning in the beginning here that "this is for beta-1 and is expected to change a bit before final" ?
</blockquote></details>

This text has been carefully written to avoid almost all concepts that are still expected to change. I'd prefer to not include any notes that might accidentally be forgotten here.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 294 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKyPLBFoVMGkICOYkV:-KZL4NULSazHyKQNFasM:bko78ip) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L294)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Not sure if this ListDataProvider filtering part should be moved up to be a subtopic for the first section about in-memory / ListDataProvider, after Sorting
</blockquote></details>

I see this as a chicken and egg problem since the entire concept of filtering types would then also have to be introduced before going into the specifics of filtering with `ListDataProvider`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZKwQWNfVmqoryMjUmW:-KZLGuNJznyOrL0LLKzI:bnessw4) ([raw file](https://github.com/vaadin/framework/blob/0d602fb390ad48a5844370325c0bbcb718ee6221/documentation/datamodel/datamodel-providers.asciidoc#L83)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'm not sure. There would need to be quite many heading throughout this entire section in that case.
</blockquote></details>

Can be added later

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 69 at r2](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZLGp26UE9YPAHS-jHM:-KZLGp26UE9YPAHS-jHN:b-f1m0jq) ([raw file](https://github.com/vaadin/framework/blob/fef78ba179d13b41b36e3185d04da8567a5d62b3/documentation/datamodel/datamodel-providers.asciidoc#L69)):*
> ```AsciiDoc
> [NOTE]
> This kind of sorting is only supported for in-memory data.
> Sorting with data that is lazy loaded from a backend is described later in this chapter.
> ```

Would be better to provide a link

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZLGn9lP26z4RWS3dtw:-KZLGn9lP26z4RWS3dtx:b-f1m0jq) ([raw file](https://github.com/vaadin/framework/blob/fef78ba179d13b41b36e3185d04da8567a5d62b3/documentation/datamodel/datamodel-providers.asciidoc#L84)):*
> ```AsciiDoc
> [NOTE]
> This kind of filtering is only supported for in-memory data.
> Filtering with data that is lazy loaded from a backend is described later in this chapter.
> ```

Would be better to provide a link

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 69 at r2](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZLGp26UE9YPAHS-jHM:-KZLIuMUr5B9zTKWUOEt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fef78ba179d13b41b36e3185d04da8567a5d62b3/documentation/datamodel/datamodel-providers.asciidoc#L69)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Would be better to provide a link
</blockquote></details>

Done.

---

*[documentation/datamodel/datamodel-providers.asciidoc, line 84 at r2](https://reviewable.io:443/reviews/vaadin/framework/8023#-KZLGn9lP26z4RWS3dtw:-KZLIuqMcScAz4q3064K:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fef78ba179d13b41b36e3185d04da8567a5d62b3/documentation/datamodel/datamodel-providers.asciidoc#L84)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Would be better to provide a link
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023)*

**Comment by pleku** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8023#-:-KZLJhOqstYCdRGXgQSi:bnfp4nl)*

**Pull request merged**
