### PR TITLE
Implement error level on client side

### PR DESCRIPTION
**Pull request by wbadam**
Add additional class names and style to components and error indicators to distinguish different error levels.

Vaadin 7 solution for #3139

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9816)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
There's a faulty header in ErrorLevel.java. Copyright header does not match expected one. Copy the correct header from some other java file in the project.

**Comment by wbadam** [comment]
Fixed header

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816#-:-Kr_HwPq_ECd4fs__8ui:bywz332)*

**Comment by wbadam** [comment]
Review status: 28 of 35 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/TooltipInfo.java, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/9816#-KuPHfEOGNZseDjPE0et:-KuSyuETINzGKHAepZrz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4e977de1ebfa567d7b07c8b569418b9deb2413ad/client/src/main/java/com/vaadin/client/TooltipInfo.java#L16)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Some public methods of this class still don't have JavaDoc. Not sure if needed, just a reminder.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/VCaption.java, line 337 at r2](https://reviewable.io:443/reviews/vaadin/framework/9816#-KuPI4vOhCYRTfjJKisx:-KuSvqLpUGlYiuHePDVD:b-y2d9zi) ([raw file](https://github.com/vaadin/framework/blob/4e977de1ebfa567d7b07c8b569418b9deb2413ad/client/src/main/java/com/vaadin/client/VCaption.java#L337)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Comment why this is deprecated. Public API could also use JavaDoc even though it is quite internal API.
</blockquote></details>

I'm not sure about that, sorry. The other two existing methods were deprecated so I added the annotation to this method with the added `ErrorLevel` parameter as well.

---

*[server/src/main/java/com/vaadin/server/ErrorMessage.java, line 94 at r2](https://reviewable.io:443/reviews/vaadin/framework/9816#-KuPMKXakGulI_Bm9w3O:-KuSvXt1YfCJ_P03vBSm:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4e977de1ebfa567d7b07c8b569418b9deb2413ad/server/src/main/java/com/vaadin/server/ErrorMessage.java#L94)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could move error/default to last
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816)*

**Comment by tsuoanttila** [comment]
Code seems ok for me, @jouni should check out the styling changes and the default colors.

---

Reviewed 7 of 34 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816#-:-KuT85TKTQd3j65oHmAe:b-a34zyj)*

**Review by jouni — COMMENTED** [review]
Overall, looks alright.

Few things that came to mind:
- Are these needed by all users, or should these be behind a Sass variable (change to file size should be measured)?
- Tab tooltips are always the same color
- Some of the colors might not fulfill recommended contrast ratios

**Comment by wbadam** [comment]
- I compiled the themes on master and with these changes with the following results
    - master
    ```
    1.4K 22 Sep 12:16 _valo.scss
    328K 22 Sep 12:28 styles.css
     35K 22 Sep 12:28 styles.css.gz
     44B 22 Sep 12:28 styles.scss
    ```
    - with error level styling
    ```
    1.4K 22 Sep 12:16 _valo.scss
    333K 22 Sep 12:16 styles.css
     36K 22 Sep 12:16 styles.css.gz
     44B 22 Sep 12:16 styles.scss
    ```
- Fixed tab tooltip colours
- As far as I understand @tuomasnironen was considering contrasts when designing the theme

**Review by jouni — APPROVED** [review]
Thanks @wbadam! So 1K more styles (5K uncompressed). I suppose that’s acceptable for most users.

I’ll trust Tuomas on this then.

**Comment by wbadam** [comment]
Review status: 34 of 36 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/tabsheet/TabSheetErrorTooltipTest.java, line 88 at r4](https://reviewable.io:443/reviews/vaadin/framework/9816#-KudPzS7pXVyJfe8bRc9:-KudPzS7pXVyJfe8bRcA:bhtcpe4) ([raw file](https://github.com/vaadin/framework/blob/82aed6f936f166a8db87a4e47826722b562c81f5/uitest/src/test/java/com/vaadin/tests/components/tabsheet/TabSheetErrorTooltipTest.java#L88)):*
> ```Java
>     private WebElement getCurrentErrorMessage() {
>         return getDriver().findElement(
>                 By.xpath("//div[contains(@class, 'v-errormessage')]"));
> ```

There are now multiple class names on the error message overlay element, `v-errormessage` and `v-errormessage-*` where `*` is the error level.

Needed to modify this test so that it would be able to find the element even when it has multiple class names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816)*

**Comment by tsuoanttila** [comment]
Needs rebase, :lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816#-:-KutLef2TmDRWjx_7rQ8:bklcdfw)*

**Comment by wbadam** [comment]
Rebased onto 7.7

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9816#-:-KuwlllWcICWthC_N5QK:b-fq6a1t)*

**Pull request merged**
