### PR TITLE
Allow focus to another component, when closing the window

### LINKED ISSUE #5891: Lost focus after closing Window
**Originally by _ipedja_**

___
Problem is when I use Runo theme after closing modal window it works fine, it is focused on textfield.
When Valo theme is used it will focus back to Button after closing Window. Actually you can see that it focuses on TextField and than instantly focuses back on Button.

```
    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

        Button button = new Button("Open window");
        final TextField textField = new TextField("Focus shoud go here");
        
        button.addClickListener(new Button.ClickListener() {
            public void buttonClick(ClickEvent event) {
                Window window = new Window("WINDOW");
                window.setModal(true);
                window.addCloseListener(new CloseListener() {
                    @Override
                    public void windowClose(CloseEvent e) {
                        textField.focus();
                    }
                });
                addWindow(window);
            }
        });
        layout.addComponents(button, textField);
    }
```

___
 Imported from https://dev.vaadin.com/ issue #15226

### PR DESCRIPTION
**Pull request by anasmi**
Resolve #5891

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 414 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LBZz_-PDnv0j9fOmfru:-LBZz_-PDnv0j9fOmfrv:b7xg9gr) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VUI.java#L414)):*
> ```Java
>      * @return storedFocus element
>      */
>     public Element getStoredFocus() {
> ```

Delete if it's not used or add empty since

---

*[client/src/main/java/com/vaadin/client/ui/VWindow.java, line 257 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LB_-5-E-nwmeBY2OcA1:-LB_-5-E-nwmeBY2OcA2:b-ryp6zr) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VWindow.java#L257)):*
> ```
>         WidgetUtil.getFocusedElement().getTagName().equalsIgnoreCase("body")) 
> ```
A bit more safe way:
```java
"body".equalsIgnoreCase(WidgetUtil.getFocusedElement().getTagName())
```
Not a blocker

---

*[client/src/main/java/com/vaadin/client/ui/VWindow.java, line 257 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LB_1EgBBzIHTjdTLhRB:-LB_1EgBBzIHTjdTLhRC:bnnqgfv) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VWindow.java#L257)):*
> ```Java
>          * open, the originally stored element is not restored.
>          */
>         if (WidgetUtil.getFocusedElement() == null || WidgetUtil
> ```

Please comment that IE returns `null` while other browsers return body element 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Comment by elmot** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/VWindow.java, line 257 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LB_1EgBBzIHTjdTLhRB:-LB_CD8T0imk5I71l3Sl:boag86p) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VWindow.java#L257)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please comment that IE returns `null` while other browsers return body element 
</blockquote></details>

Commented

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/VWindow.java, line 257 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LB_-5-E-nwmeBY2OcA1:-LB_CFYuAQWBp6ZfbgpQ:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VWindow.java#L257)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> ```
>         WidgetUtil.getFocusedElement().getTagName().equalsIgnoreCase("body")) 
> ```
A bit more safe way:
```java
"body".equalsIgnoreCase(WidgetUtil.getFocusedElement().getTagName())
```
Not a blocker
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Comment by anasmi** [comment]
*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 414 at r1](https://reviewable.io/reviews/vaadin/framework/10860#-LBZz_-PDnv0j9fOmfru:-LB_CJ_H9PCuIP6b47dZ:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/f79df00d1c800f859d0b37f937ee8920ef6c48ba/client/src/main/java/com/vaadin/client/ui/VUI.java#L414)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Delete if it's not used or add empty since
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10860)*

**Pull request merged**
