### PR TITLE
Merge 7.7.4 fixes to master

### PR DESCRIPTION
**Pull request by ahie**
Closes vaadin/framework8-issues#460

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/87)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 51 of 51 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 515 at r1](https://reviewable.io:443/reviews/vaadin/framework/87#-KYE6I1ufVeCba_0Zvo8:-KYE6I1ufVeCba_0Zvo9:b8x71oe) ([raw file](https://github.com/vaadin/framework/blob/105d4721e2352bbf861c54d1b69a8de1d9886324/server/src/main/java/com/vaadin/ui/UI.java#L515)):*
> ```Java
>                 getPushConfiguration().setPushMode(PushMode.DISABLED);
> 
>                 new Thread(new Runnable() {
> ```

Ahem! ahem......
A number of issues here. But this is just a migration patch .
So ...... let it be ? ....

Ahem.

---

*[uitest/src/main/java/com/vaadin/tests/extensions/UnknownExtensionHandling.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/87#-KYE89jwo_0DaIvQdlS4:-KYE89jwo_0DaIvQdlS5:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/105d4721e2352bbf861c54d1b69a8de1d9886324/uitest/src/main/java/com/vaadin/tests/extensions/UnknownExtensionHandling.java#L45)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 515 at r1](https://reviewable.io:443/reviews/vaadin/framework/87#-KYE6I1ufVeCba_0Zvo8:-KYEQWRY1L0_d2Pur4Qw:bd6dqsq) ([raw file](https://github.com/vaadin/framework/blob/105d4721e2352bbf861c54d1b69a8de1d9886324/server/src/main/java/com/vaadin/ui/UI.java#L515)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Ahem! ahem......
A number of issues here. But this is just a migration patch .
So ...... let it be ? ....

Ahem.
</blockquote></details>

Please fix (both 7.7 and master) separately if you have any ideas on how to get rid of this very ugly hack. All the details should be in https://dev.vaadin.com/ticket/18436

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 515 at r1](https://reviewable.io:443/reviews/vaadin/framework/87#-KYE6I1ufVeCba_0Zvo8:-KYERPrzqQDTNXfTvW4_:b-ky3znk) ([raw file](https://github.com/vaadin/framework/blob/105d4721e2352bbf861c54d1b69a8de1d9886324/server/src/main/java/com/vaadin/ui/UI.java#L515)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Please fix (both 7.7 and master) separately if you have any ideas on how to get rid of this very ugly hack. All the details should be in https://dev.vaadin.com/ticket/18436
</blockquote></details>

This should be fixed separately (not related to this migration PR):  absolutely true.

Hack might be OK. But I'm not sure what it does actually...

One issue: creating a new thread for each instance of UI. Bad idea. There can be a thread for the hack. But new thread for each UI ? ( Should be thread pool , might be shared, static ......)

Another issue: what it actually does ? The `setPushConnection` method is supposed to be called under the lock.
If it's not called under the lock then what it does ? 
It makes some changes in the thread from which it is called.
This is the only thing that we can be sure. Is this something expected ?

No lock -> thread can cache the value (so it might not be visible for other threads) + no atomic operation.
Is this expected ?

I don't know anything about original issue. But this code is not thread safe in any way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by pleku** [comment]
Reviewed 1 of 51 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/extensions/UnknownExtensionHandling.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/87#-KYE89jwo_0DaIvQdlS4:-KYSNQige92HYTWlyTMR:bvsn6ws) ([raw file](https://github.com/vaadin/framework/blob/105d4721e2352bbf861c54d1b69a8de1d9886324/uitest/src/main/java/com/vaadin/tests/extensions/UnknownExtensionHandling.java#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

This is a test class so I'm going to let this slide

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by pleku** [comment]
Reviewed 1 of 51 files at r1.
Review status: 51 of 52 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/87)*

**Pull request merged**
