### PR TITLE
Update testbench version

### PR DESCRIPTION
**Pull request by alvarezguille**
TB 5.1.0 final is out

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10336)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 416 at r1](https://reviewable.io:443/reviews/vaadin/framework/10336#-Kz9LDPosB61BImK9EX-:-Kz9LDPpmrqVI2m2AkP5:b5xclgr) ([raw file](https://github.com/vaadin/framework/blob/81b4dfb6728d9455c1db055156c6555b8aa4906b/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L416)):*
> ```Java
>      *            the condition to wait for to become true
>      */
>     protected <T> void waitUntil(ExpectedCondition<T> condition) {
> ```

I guess these two methods have been added to one of the parent classes that belong to TB?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10336)*

**Comment by ahie** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10336)*

**Comment by alvarezguille** [comment]
*[uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java, line 416 at r1](https://reviewable.io:443/reviews/vaadin/framework/10336#-Kz9LDPosB61BImK9EX-:-Kz9MgrbE8FWdTjhbhuI:btl2983) ([raw file](https://github.com/vaadin/framework/blob/81b4dfb6728d9455c1db055156c6555b8aa4906b/uitest/src/test/java/com/vaadin/tests/tb3/AbstractTB3Test.java#L416)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

I guess these two methods have been added to one of the parent classes that belong to TB?
</blockquote></details>

Yes, as part of [TestBench 5.1.0](https://github.com/vaadin/testbench/releases/tag/5.1.0) we moved some common helpers to TestBench side

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10336)*

**Comment by ahie** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10336)*

**Pull request merged**
