### PR TITLE
Change license from Apache-2 to CVDLv4

### PR DESCRIPTION
**Pull request by TatuLund**
- Update copyright and license headers in .java files
- Update main LICENSE file
- Update license info under WebContent

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12144)

### CODE REVIEW

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 1870 of 1870 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12144#-:-MLI7Cy_8P9ICZjBeiV0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12144#-:-MMLG3TL0VRLJHH8jQ0k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12144#-:-MMPRgQS-tOU7_FpHzEG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Enerccio** [comment]
Did you change the license without telling anyone? That is rather scum move...

**Comment by TatuLund** [comment]
@Enerccio this change applies only to Vaadin 7 extended support releases. Vaadin 7.7.17 is the last publicly released Vaadin 7 series release. It is still and continues to be under Apache 2. Vaadin 7 normal support has ended, but extended support is available under commercial terms (see also: https://vaadin.com/pricing and Prime)

**Comment by Enerccio** [comment]
But since it's still open source I could just download it and support it myself, no?

**Comment by Enerccio** [comment]
And I could also backport any changes in public repo to my fork as well?

**Comment by TatuLund** [comment]
> But since it's still open source I could just download it and support it myself, no?

Yes, versions prior to 7.7.23 (it is the first version with the new license applied)

**Comment by Enerccio** [comment]
> > But since it's still open source I could just download it and support it myself, no?
> 
> Yes, versions prior to 7.7.23 (it is the first version with the new license applied)

okay, but let's say you fix something and I see the fix, I still can copy that fix to my fork, right?

**Comment by TatuLund** [comment]
@Enerccio okay, but let's say you fix something and I see the fix, I still can copy that fix to my fork, right?

In a longer run we may transfer legacy framework sources to private repo. Before that fixes may be visible and technically easy to copy. However as stated by 2.3 of the license outcome of such is will be under the terms of the CVDL-4 license, if the extent of the fix is non-trivial and hence copyrightable.

**Comment by afiller** [comment]
But the **LICENSE** file in the root is still **Apache 2.0** on the **7.7.23** release commit as well as the license in Maven's **pom.xml** (and so also in the public maven repositories):

https://github.com/vaadin/framework/blob/7.7.23/LICENSE
https://mvnrepository.com/artifact/com.vaadin/vaadin-server/7.7.23

So 7.7.23 seems to be the last Apache 2.0 release? So I'm still allowed to proceed with my forked development based on this branch since you published it this way?

**Comment by TatuLund** [comment]
@afiller  No, the license is CVDLv4 as seen here:

https://github.com/vaadin/framework/blob/7.7/LICENSE

We may have some error somewhere in metainfo, which causes a glitch. We will fix that.

**Comment by afiller** [comment]
Ok, thank you for clarifying. We'll then go back to the last open source commit in our current local development branch.

It's very sad to see Vaadin7 disappearing from the Apache 2 landscape. We highly welcomed your extended support offer on the website, but it's simply too expensive for us as a startup. #feedback

**Pull request merged**
