### PR TITLE
Fix scrolling problem in table in Chrome 56+

### LINKED ISSUE #8707: Unnecessary sroll down after refreshRowCache() in Table with Chrome 56+ browser
Vaadin version 7.7.7
Browser version Chrome 56 and newer.

How to reproduce
1. Create UI with Table which contains 1000 rows
2. Open it with Chrome 56+ browser or other browser with chrome 56+ engine.
3. Scroll down, so Table requests next page(for example scroll down to item 100).
4. Click 'refresh' button to make table.refreshRowCache()
5. As you can see, table scrolls down without any user action after table.refreshRowCache() is done.
6. You can not reproduce such behaviour with other non-chrome engine browser(IE, Firefox, etc).

Working example http://178.236.245.251:8383/tabletest/
Source code:
[vaadin-app.zip](https://github.com/vaadin/framework/files/806031/vaadin-app.zip)

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8707

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10492)

### CODE REVIEW

**Comment by OlliTietavainenVaadin** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/table/TableScrollsOnRefresh.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/10492#-L25F1z8MgBW_v5JHdxD:-L25F1z8MgBW_v5JHdxE:b-4bygje) ([raw file](https://github.com/vaadin/framework/blob/40fe46a4f5cc8d5243aba17a042bbd963b746495/uitest/src/main/java/com/vaadin/tests/components/table/TableScrollsOnRefresh.java#L36)):*
> ```Java
>         table.setContainerDataSource(container);
>         populateContainer();
>         // table.refreshRowCache();
> ```

remove commented code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10492)*

**Comment by OlliTietavainenVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10492#-:-L25KlnuW8kudbE8SaCT:bnfp4nl)*

**Comment by OlliTietavainenVaadin** [comment]
*[uitest/src/main/java/com/vaadin/tests/components/table/TableScrollsOnRefresh.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/10492#-L25F1z8MgBW_v5JHdxD:-L25L1fufFvzE5ulFb0Q:b-d20kbh) ([raw file](https://github.com/vaadin/framework/blob/40fe46a4f5cc8d5243aba17a042bbd963b746495/uitest/src/main/java/com/vaadin/tests/components/table/TableScrollsOnRefresh.java#L36)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

remove commented code
</blockquote></details>

Never mind, I can do it myself!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10492)*

**Comment by OlliTietavainenVaadin** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10492)*

**Comment by d2k2-git** [comment]
is no bugfix neccesary for the reindeer theme?

**Pull request merged**
