### PR TITLE
Make it possible to also use an element as root and not only id.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10785)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FPMh4AV5Npcq2JX7R:-L9FPMh4AV5Npcq2JX7S:b-5wcm0r) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L150)):*
> ```
> confifguration
> ```
configuration

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 161 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FPR7V5qfPYYMXDBto:-L9FPR7W77bC7T1UpFNt:b-6fejfp) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L161)):*
> ```Java
>          * @return element for the configuration parameter, or <code>null</code> if no
>          *         value is defined
>          */
> ```

missing since

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 930 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FP_hD4NruICAsI1HZ:-L9FP_hD4NruICAsI1H_:b-6fejfp) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L930)):*
> ```Java
>      */
>     public Element getRootElement() {
>         return rootElement;
> ```

missing since

---

*[client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java, line 510 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FQ2kC6qH6lImeXdxd:-L9FQ2kC6qH6lImeXdxe:bcyxn7c) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java#L510)):*
> ```Java
>     }
> 
>     public void init(Element rootPanelElement, String rootPanelId,
> ```

- This is API breaking change with non-obvious parameters relationship. Better to have two inits, with different parameter sets, and `if` on ApplicationConnection side.
- missing both javadoc and since

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10785)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 150 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FPMh4AV5Npcq2JX7R:-L9FSca81ouv6Qou9MHo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L150)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> ```
> confifguration
> ```
configuration
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 161 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FPR7V5qfPYYMXDBto:-L9FScy-70N7IrtSl3c2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L161)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing since
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 930 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FP_hD4NruICAsI1HZ:-L9FSedM0NacnN6IodYD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L930)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

missing since
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java, line 510 at r1](https://beta.reviewable.io/reviews/vaadin/framework/10785#-L9FQ2kC6qH6lImeXdxd:-L9FUrZC4miwwSIKHXXF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4ba403b925d0a1531b42ec994151edfddd1bcbbd/client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java#L510)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

- This is API breaking change with non-obvious parameters relationship. Better to have two inits, with different parameter sets, and `if` on ApplicationConnection side.
- missing both javadoc and since

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10785)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10785)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10785#-:-L9Fkq6R7-mTbhg2g0_X:bnfp4nl)*

**Pull request merged**
