### PR TITLE
Remove workarounds from Spring integration test

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10430)

### CODE REVIEW

**Comment by jtomass** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10430#-:-L09wv4EGioPuHMVSCEf:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10430#-L09xG7kb5u2o4oIUoM8:-L09xG7kb5u2o4oIUoM9:b25oaqv) (no related file):*
Spring plug-in not released yet, pending.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10430)*

**Comment by tsuoanttila** [comment]
Rebased.

**Comment by ahie** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10430)*

**Pull request merged**
