### PR TITLE
Update ComboBox internal state on new item added

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Related to ticket #11059

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @tsuoanttila)

___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 189 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIeKTqlBoNsDKyznCjC:-LIeKTqlBoNsDKyznCjD:b-umtrm1) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/server/src/main/java/com/vaadin/ui/ComboBox.java#L189)):*
> ```
> clientSideHandling
> ```
What about removing this variable and moving `newItemNotAdded` inside the proper `if` block?
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 205 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIeKzo5DrNPMc0gEIKP:-LIeKzo5DrNPMc0gEIKQ:bpl5te8) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/server/src/main/java/com/vaadin/ui/ComboBox.java#L205)):*
> ```
> was 
> ```
typo
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 205 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIeL1BP83lD0lSk4xZ5:-LIeL1BP83lD0lSk4xZ6:bhqd0w7) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/server/src/main/java/com/vaadin/ui/ComboBox.java#L205)):*
> ```
> NewItemHandler
> ```
NewItemProvider?
___
*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChangeTest.java, line 4 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIee-JV2Ckntmh-bOJq:-LIee-JV2Ckntmh-bOJr:by480uy) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChangeTest.java#L4)):*
> ```
> import static org.junit.Assert.assertTrue;
> ```
It looks unused.

**Review by tsuoanttila — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @tsuoanttila)

___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 189 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIeKTqlBoNsDKyznCjC:-LIejvQfDx8Enu08OVDJ:bkl3s0n) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/server/src/main/java/com/vaadin/ui/ComboBox.java#L189)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> clientSideHandling
> ```
What about removing this variable and moving `newItemNotAdded` inside the proper `if` block?
</blockquote></details>

the new item not added is applied to all cases except when the old `NewItemHandler` is used to add the value. I tried to refactor it earlier but it's quite corner case.
___
*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 205 at r1](https://reviewable.io/reviews/vaadin/framework/11094#-LIeL1BP83lD0lSk4xZ5:-LIek76ZDo9Po2-f56dm:b-n0xtcz) ([raw file](https://github.com/vaadin/framework/blob/dc22d165323ba5d810f42fb54bee509090be4989/server/src/main/java/com/vaadin/ui/ComboBox.java#L205)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> NewItemHandler
> ```
NewItemProvider?
</blockquote></details>

Older concept called `NewItemHandler` that does not provide any useful information whether something was added or not.

**Review by mehdi-vaadin — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by mehdi-vaadin — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094#-:-LIj2dzb-8qYKDs43tcx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Comment by TatuLund** [comment]
Why Validation Build sais failed here, but when I go to TeamCity to check results, they are all passed?

**Review by elmot — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @mehdi-vaadin, @tsuoanttila, and @ZheSun88)

___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java, line 9 at r5](https://reviewable.io/reviews/vaadin/framework/11094#-LMv7sm1ChnAulHtRVWy:-LMv7sm1ChnAulHtRVWz:byquu61) ([raw file](https://github.com/vaadin/framework/blob/447151e37512a4327f48f8198ebb64550f50d1ea/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java#L9)):*
> ```Java
> import java.util.Optional;
> 
> @Widgetset(TestingWidgetSet.NAME)
> ```

Do we need this?
___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java, line 15 at r5](https://reviewable.io/reviews/vaadin/framework/11094#-LMv7RScClIDgaQyZ2IQ:-LMv7RScClIDgaQyZ2IR:b-gfh6hm) ([raw file](https://github.com/vaadin/framework/blob/447151e37512a4327f48f8198ebb64550f50d1ea/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java#L15)):*
> ```Java
>     @Override
>     protected void configureNewItemHandling() {
>         comboBox.addValueChangeListener(e -> {
> ```

Useless output
___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChange.java, line 26 at r5](https://reviewable.io/reviews/vaadin/framework/11094#-LMv817c17cx3SSp4G4R:-LMv817c17cx3SSp4G4S:bwscgku) ([raw file](https://github.com/vaadin/framework/blob/447151e37512a4327f48f8198ebb64550f50d1ea/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChange.java#L26)):*
> ```Java
>         @Override
>         public void beforeClientResponse(boolean initial) {
>             super.beforeClientResponse(initial);
> ```

Useless override?

**Review by mehdi-vaadin — COMMENTED** [review]
Some cleanup has been done.

> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094#-:-LNETHqGDqYUi7ym5Cl4:bjqh3mp)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @mehdi-vaadin and @tsuoanttila)

___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java, line 15 at r5](https://reviewable.io/reviews/vaadin/framework/11094#-LMv7RScClIDgaQyZ2IQ:-LNESmIiAOwVhakpvnao:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/e4767d938ae07f0a02527bb8f97550dce97cd896/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxNewItemProvider.java#L15)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Useless output
</blockquote></details>

Done
___
*[uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChange.java, line 26 at r5](https://reviewable.io/reviews/vaadin/framework/11094#-LMv817c17cx3SSp4G4R:-LNESiJX-rcsyFXzAeT3:b7d1dbu) ([raw file](https://github.com/vaadin/framework/blob/e4767d938ae07f0a02527bb8f97550dce97cd896/uitest/src/main/java/com/vaadin/tests/components/combobox/ComboBoxSelectingNewItemValueChange.java#L26)):*
> ```
> beforeClientResponse
> ```
Done

**Review by mehdi-vaadin — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mehdi-vaadin and @elmot)

**Review by ZheSun88 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r1, 1 of 3 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094#-:-LNK05muDtZlx2QVeEFT:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @elmot)

**Review by mehdi-vaadin — APPROVED** [review]
> Dismissed @elmot from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094#-:-LNKb_ah2IovIq5e3WWw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by mehdi-vaadin — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Review by mehdi-vaadin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11094)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
