### PR TITLE
Rename contentMode to descriptionContentMode in MenuItem

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10494)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
*[shared/src/main/java/com/vaadin/shared/ui/menubar/MenuBarConstants.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10494#-L20YIz_Ygq5znBXj73S:-L20YIz_Ygq5znBXj73T:b-p1w7t) ([raw file](https://github.com/vaadin/framework/blob/0cfb3cc6563652981809a312657f58be2edb8153/shared/src/main/java/com/vaadin/shared/ui/menubar/MenuBarConstants.java#L27)):*
> ```Java
>     public static final String ATTRIBUTE_ITEM_DESCRIPTION = "description";
>     @Deprecated
>     public static final String ATTRIBUTE_ITEM_DESCRIPTION_CONTENT_MODE = "contentmode";
> ```

should the constant also contain "description" ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10494)*

**Comment by tsuoanttila** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10494)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[shared/src/main/java/com/vaadin/shared/ui/menubar/MenuBarConstants.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/10494#-L20YIz_Ygq5znBXj73S:-L20YxS20jYzrqsksoON:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0cfb3cc6563652981809a312657f58be2edb8153/shared/src/main/java/com/vaadin/shared/ui/menubar/MenuBarConstants.java#L27)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

should the constant also contain "description" ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10494)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10494#-:-L20_1Wb-vRVdgwx0uGY:bnfp4nl)*

**Pull request merged**
