### PR TITLE
Create DescriptionGenerator in package com.vaadin.ui

### PR DESCRIPTION
**Pull request by ahie**
Deprecate com.vaadin.ui.components.grid.DescriptionGenerator
and subclass it from the new DescriptionGenerator.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10346)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/DescriptionGenerator.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10346#-KzTn5bgi5zyjvmsLTX4:-KzTn5bgi5zyjvmsLTX5:b-hnqjt8) ([raw file](https://github.com/vaadin/framework/blob/7ad8f7bb37bf020e3fd317afa076532929de8cb7/server/src/main/java/com/vaadin/ui/DescriptionGenerator.java#L24)):*
> ```Java
>  *
>  * @author Vaadin Ltd
>  * @since 8.0
> ```

Technically this interface is introduced in 8.2..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10346)*

**Comment by ahie** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/DescriptionGenerator.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/10346#-KzTn5bgi5zyjvmsLTX4:-KzToLiMdPQV17ncj6Mo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7ad8f7bb37bf020e3fd317afa076532929de8cb7/server/src/main/java/com/vaadin/ui/DescriptionGenerator.java#L24)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Technically this interface is introduced in 8.2..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10346)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10346#-:-KzToVaRCt4PKhNVNA_U:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10346)*

**Pull request merged**
