### PR TITLE
Code cleanup and serialization test in compatibility package

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Rebase.

**Comment by tsuoanttila** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/DetailsConnectorChange.java, line 30 at r1](https://reviewable.io/reviews/vaadin/framework/10977#-LF2KrQeAJdAbcbjp4ET:-LF2KrQeAJdAbcbjp4EU:b-evu0tr) ([raw file](https://github.com/vaadin/framework/blob/e8521ae0ab2b7c9cc8e4d042aaf8864045a57b8e/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/DetailsConnectorChange.java#L30)):*
> ```Java
>  * @author Vaadin Ltd
>  */
> public class DetailsConnectorChange implements Serializable {
> ```

Is this also removed on the V7 side?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977)*

**Comment by elmot** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/DetailsConnectorChange.java, line 30 at r1](https://reviewable.io/reviews/vaadin/framework/10977#-LF2KrQeAJdAbcbjp4ET:-LFHxBsjABGtSV3fwwKG:bndayvj) ([raw file](https://github.com/vaadin/framework/blob/e8521ae0ab2b7c9cc8e4d042aaf8864045a57b8e/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/grid/DetailsConnectorChange.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is this also removed on the V7 side?
</blockquote></details>

https://github.com/vaadin/framework/pull/10990

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977)*

**Comment by elmot** [comment]
done

---

Review status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977#-:-LFI4J7J8yLIAb6O2LuL:bb7f2mf)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: 3 of 4 files reviewed, all discussions resolved (waiting on @tsuoanttila)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10977)*

**Pull request merged**
