### PR TITLE
Tree styling documentation

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9235)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9235#-KjHy-o7O41LVwbzjgA7:-KjHy-o7O41LVwbzjgA8:bcu3jgs) ([raw file](https://github.com/vaadin/framework/blob/8eb795229281250e19dfa20b5712abd56424f617/documentation/components/components-tree.asciidoc#L173)):*
> ```AsciiDoc
> ----
> .v-tree8 {}
>   .v-tree8-row {}              /* An item  )           */
> ```

extra closing parenthesis in comment; could also mention .v-tree8-row-selected (and maybe some others)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9235)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[documentation/components/components-tree.asciidoc, line 173 at r1](https://reviewable.io:443/reviews/vaadin/framework/9235#-KjHy-o7O41LVwbzjgA7:-KjMaObUNjUX-LlIAFw5:bh03e47) ([raw file](https://github.com/vaadin/framework/blob/8eb795229281250e19dfa20b5712abd56424f617/documentation/components/components-tree.asciidoc#L173)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra closing parenthesis in comment; could also mention .v-tree8-row-selected (and maybe some others)
</blockquote></details>

(other class names can be added later)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9235)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 178 at r2](https://reviewable.io:443/reviews/vaadin/framework/9235#-KkAJ5NpfPXvFvPmQyrd:-KkAJ5NpfPXvFvPmQyre:blrqy78) ([raw file](https://github.com/vaadin/framework/blob/4ba1974968d5e49a7304c668acfccf816d7a0c5c/documentation/components/components-tree.asciidoc#L178)):*
> rowmode-

Will be removed in https://github.com/vaadin/framework/pull/9287.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9235)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/components/components-tree.asciidoc, line 178 at r2](https://reviewable.io:443/reviews/vaadin/framework/9235#-KkAJ5NpfPXvFvPmQyrd:-KkGGT1eJL95VIb9vFK9:bss4a2b) ([raw file](https://github.com/vaadin/framework/blob/4ba1974968d5e49a7304c668acfccf816d7a0c5c/documentation/components/components-tree.asciidoc#L178)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> rowmode-

Will be removed in https://github.com/vaadin/framework/pull/9287.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9235)*

**Comment by elmot** [comment]
Full mess after rebase. I will open another PR

**Comment by elmot** [comment]
see #9334

**Pull request closed without merging**
