### PR TITLE
added missing @since tags and missing javadocs

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Missing since tags and JavaDoc blocs + Eclipse formatting

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10155)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VCaption.java, line 358 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0IcW1zRSRxAwc_DKE:-Kw0IcW1zRSRxAwc_DKF:b-w1uk3w) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/client/src/main/java/com/vaadin/client/VCaption.java#L358)):*
> ```Java
>      * @return true if the caption was placed after the component when it wasn't
>      *         before or vice versa
>      */
> ```

Does this need a since tag?

---

*[shared/src/main/java/com/vaadin/shared/AbstractComponentState.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0Iqzkb_DJ8olxQEyy:-Kw0Iqzkb_DJ8olxQEyz:b-3idge9) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/shared/src/main/java/com/vaadin/shared/AbstractComponentState.java#L55)):*
> ```Java
>      * @since 7.7.11
>      */
>     public ErrorLevel errorLevel = null;
> ```

This can break compatibility for compiled add-ons, and thus should at least be mentioned as a potentially breaking change in all/src/main/templates/release-notes.html .

---

*[shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0JA48Ga6j0l-8eqNC:-Kw0JA48Ga6j0l-8eqND:bwiu2tm) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java#L43)):*
> ```Java
>      * @since 7.7.11
>      */
>     public ErrorLevel componentErrorLevel;
> ```

Also this could be mentioned in release notes, although this is much less likely to break add-ons.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10155)*

**Comment by hesara** [comment]
Ok for me but perhaps @tsuoanttila could take a final look at the backwards incompatibility point.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10155#-:-Kw3qS_8PkAwCm8OP5cc:bd4lcnl)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/VCaption.java, line 358 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0IcW1zRSRxAwc_DKE:-Kw3tikuUKa-WGftDeOV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/client/src/main/java/com/vaadin/client/VCaption.java#L358)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this need a since tag?
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/AbstractComponentState.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0Iqzkb_DJ8olxQEyy:-Kw3tk01GUMioRlrnc3T:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/shared/src/main/java/com/vaadin/shared/AbstractComponentState.java#L55)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This can break compatibility for compiled add-ons, and thus should at least be mentioned as a potentially breaking change in all/src/main/templates/release-notes.html .
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/10155#-Kw0JA48Ga6j0l-8eqNC:-Kw3tl3koIE0rlFRPI3Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2ed2e11b9f346534fd23d7975433fe4af355deb9/shared/src/main/java/com/vaadin/shared/ui/tabsheet/TabState.java#L43)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Also this could be mentioned in release notes, although this is much less likely to break add-ons.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10155)*

**Comment by tsuoanttila** [comment]
Should be fine.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10155#-:-Kw46UArssbENaps7EKF:b-b8x941)*

**Comment by hesara** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10155#-:-Kw4PR8EyE9SKH-nJkcy:bg7igkv)*

**Pull request merged**
