### PR TITLE
Flush the correct editor widget if there are hidden columns

### LINKED ISSUE #8266: Grid: Editor not saving values by pressing Enter
There is a bug with Grid editor. It is not saving/comitting the values of the currently edited cell if comitted by pressing the Enter key.
If you tab to the next cell before or use the save button everything works fine.

You can check the behaviour in the attached example.

[sample.zip](https://github.com/vaadin/framework/files/713202/sample.zip)

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8266

Depends on #8275

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8276)

### CODE REVIEW

**Comment by ahie** [comment]
Needs a rebase.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7458 at r1](https://reviewable.io:443/reviews/vaadin/framework/8276#-Kaqkf94TdaMjpWhwUAK:-Kaqkf95f0mqoWUkSrb2:bukfqut) ([raw file](https://github.com/vaadin/framework/blob/fac48d2b018c56f662aa2b53583a0450a61f6dec/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7458)):*
> ```Java
> 
>             Widget widget;
>             int focusedColumnIndexDOM = editor.focusedColumnIndexDOM;
> ```

Necessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8276#-:-Kaqm-3Z0yuFGvNt1cFg:b-dw4aal)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8276)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 7458 at r1](https://reviewable.io:443/reviews/vaadin/framework/8276#-Kaqkf94TdaMjpWhwUAK:-KasBihXL5_nrlO88kvP:b32w12) ([raw file](https://github.com/vaadin/framework/blob/fac48d2b018c56f662aa2b53583a0450a61f6dec/client/src/main/java/com/vaadin/client/widgets/Grid.java#L7458)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Necessary?
</blockquote></details>

No

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8276)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8276)*

**Pull request merged**
