### PR TITLE
Add shorthands for creating lazy DataProviders

### LINKED ISSUE #8494: Creating lazy binding to ComboBox could be much easier than it is
version: 8.0.0.beta2

To create lazy binding to ComboBox currently requires delopers to develop against DataProvider interfaces. If there would be APIs optimized for ComboBox use cases (and lazy loading only) the task could be much more easier for developers. The Query object passed to lambdas contain obsolete parameters, the filter string, offset and limit could then be passed directly to the lambda.

Slightly related to  #8492

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #8494

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8511)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 91 at r1](https://reviewable.io:443/reviews/vaadin/framework/8511#-KcTFqUBliGkV4crzW7X:-KcTFqUBliGkV4crzW7Y:b5z3m2w) ([raw file](https://github.com/vaadin/framework/blob/15ff44b278d8536ba3ec66c2475961dd96cd2906/server/src/main/java/com/vaadin/ui/ComboBox.java#L91)):*
> ```Java
>          *            a non-null filter string
>          * @param offset
>          *            the offset
> ```

what does "the offset" mean?

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/framework/8511#-KcTFoExDGMtd1ZY-tzH:-KcTFoExDGMtd1ZY-tzI:b-1bula6) ([raw file](https://github.com/vaadin/framework/blob/15ff44b278d8536ba3ec66c2475961dd96cd2906/server/src/main/java/com/vaadin/ui/ComboBox.java#L93)):*
> ```Java
>          *            the offset
>          * @param limit
>          *            the limit
> ```

what does "the limit" mean?

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 770 at r1](https://reviewable.io:443/reviews/vaadin/framework/8511#-KcTFxbYN69cEWElbnH_:-KcTFxbYN69cEWElbnHa:b90gy2) ([raw file](https://github.com/vaadin/framework/blob/15ff44b278d8536ba3ec66c2475961dd96cd2906/server/src/main/java/com/vaadin/ui/ComboBox.java#L770)):*
> ```Java
>      */
>     public void setDataProvider(FetchItemsCallback<T> fetchItems,
>             SerializableFunction<String, Integer> sizeCallback) {
> ```

or SerializableToIntFunction?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 157 at r1](https://reviewable.io:443/reviews/vaadin/framework/8511#-KcTG8TH5_5Fi4-uzAwK:-KcTG8TH5_5Fi4-uzAwL:b-88dw42) ([raw file](https://github.com/vaadin/framework/blob/15ff44b278d8536ba3ec66c2475961dd96cd2906/server/src/main/java/com/vaadin/ui/Grid.java#L157)):*
> ```Java
>          *            a list of sort orders
>          * @param offset
>          *            the offset
> ```

see comments for ComboBox

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8511)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8511)*

**Comment by hesara** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/framework/8511#-KcTFoExDGMtd1ZY-tzH:-KcTL8X5Q3Ajiq2KHuoD:b-cqczf) ([raw file](https://github.com/vaadin/framework/blob/15ff44b278d8536ba3ec66c2475961dd96cd2906/server/src/main/java/com/vaadin/ui/ComboBox.java#L93)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

what does "the limit" mean?
</blockquote></details>

could still expand on this: what if not enough items available? ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8511)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8511#-:-KcX2qfujQ3_h4wkwTjy:bnfp4nl)*

**Pull request merged**
