### PR TITLE
Fix RadioButtonGroup selection updates to client

### LINKED ISSUE #9494: RadioButtonGroup cannot be reset (graphical representation)
Please see
https://vaadin.com/forum/#!/thread/15966627/15966626

for more information.

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch provides a simple fix for the majority of issues. There are still issues that should be fixes by refactoring parts of the logic in AbstractSingleSelect.

Fixes #9494

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9749)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqMRKTPhDUBuHG4YM2a:-KqMRKTQmYVUaLx75J6w:bszquf1) (no related file):*
Apparently at least some such basic cases are tested for ComboBox, but probably not for NativeSelect. Could we generalize the test for all the standard AbstractSingleSelects as they use different approaches on the client side?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqMRKTPhDUBuHG4YM2a:-KqMkCkanYKYqtHEu84F:buls2mu) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Apparently at least some such basic cases are tested for ComboBox, but probably not for NativeSelect. Could we generalize the test for all the standard AbstractSingleSelects as they use different approaches on the client side?
</blockquote></details>

I was planning to increase the number of components tested with this. Do I do it in this patch or a separate one ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqMRKTPhDUBuHG4YM2a:-KqMlBqSizE1I3ATF6r7:b-giblq4) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I was planning to increase the number of components tested with this. Do I do it in this patch or a separate one ?
</blockquote></details>

This patch affects and potentially breaks any AbstractSelect, so I'd say better do it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by hesara** [comment]
Reviewed 7 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSingleSelectElement.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNBDQI7kF6yY0Jgkgw:-KqNBDQI7kF6yY0Jgkgx:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSingleSelectElement.java#L21)):*
> ```Java
> 
> /**
>  * A common base element class for all single select components.
> ```

since tag

---

*[uitest/src/main/java/com/vaadin/tests/components/abstractsingleselect/AbstractSingleSelection.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNDuYHqLQ4yRruPd_1:-KqNDuYHqLQ4yRruPd_2:b-iv6cwh) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/uitest/src/main/java/com/vaadin/tests/components/abstractsingleselect/AbstractSingleSelection.java#L41)):*
> ```Java
>                 e -> component.getDataProvider().refreshAll()));
> 
>         // Trigger component creation through selection event.
> ```

(component creation?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by hesara** [comment]
@Legioth any opinion?

Also, there seems to be a conflict for NativeSelectEvent.

**Comment by tsuoanttila** [comment]
*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 208 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNH7joIuxKxWq0ffiY:-KqNH7joIuxKxWq0ffiZ:b6khl21) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L208)):*
> ```Java
>     public String getValue() {
>         String value = getInputField().getAttribute("value");
>         if (value == null || value.isEmpty()) {
> ```

There seems to be one test that assumes the returned value to be empty. Will have to either revert this and make them consistent some other way, or fix that test. Opinions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSingleSelectElement.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNBDQI7kF6yY0Jgkgw:-KqStyEy1obcZHrRzwNF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSingleSelectElement.java#L21)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag
</blockquote></details>

Done.

---

*[testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java, line 208 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNH7joIuxKxWq0ffiY:-KqSuShLGEKnJwWmzNy4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java#L208)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

There seems to be one test that assumes the returned value to be empty. Will have to either revert this and make them consistent some other way, or fix that test. Opinions?
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/abstractsingleselect/AbstractSingleSelection.java, line 41 at r2](https://reviewable.io:443/reviews/vaadin/framework/9749#-KqNDuYHqLQ4yRruPd_1:-KqSuRn8rcPeWmDex73a:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5deaa8604f18c500da87d78a53193ee39faf7dcc/uitest/src/main/java/com/vaadin/tests/components/abstractsingleselect/AbstractSingleSelection.java#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(component creation?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9749)*

**Pull request merged**
