### PR TITLE
Revert change to fix issue on removing Grid with components

### PR DESCRIPTION
**Pull request by ZheSun88**
Add test case to address the issue with removing gird with components;
Current situation: the grid cannot be removed and client-side throw an error. 
fixes: Revert the corresponding change, as it didn't address any issue which was fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)

### CODE REVIEW

**Comment by ZheSun88** [comment]
need to pick to `8.6` branch too

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/RemoveGridWithComponentTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11224#-LObQVXBCZZ1alKTM-US:-LObQVXBCZZ1alKTM-UT:b5pl07t) ([raw file](https://github.com/vaadin/framework/blob/fb69a3aa980b2e5d78598330178d241512abe235/uitest/src/test/java/com/vaadin/tests/components/grid/RemoveGridWithComponentTest.java#L21)):*
> ```
> grid = $(GridElement.class).id("grid-with-component");
> ```
It seems extra and can be removed.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin and @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/components/grid/RemoveGridWithComponentTest.java, line 21 at r1](https://reviewable.io/reviews/vaadin/framework/11224#-LObQVXBCZZ1alKTM-US:-LObSIXl4gpwX78IkEiX:bb7f2mf) ([raw file](https://github.com/vaadin/framework/blob/fb69a3aa980b2e5d78598330178d241512abe235/uitest/src/test/java/com/vaadin/tests/components/grid/RemoveGridWithComponentTest.java#L21)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
> grid = $(GridElement.class).id("grid-with-component");
> ```
It seems extra and can be removed.
</blockquote></details>

done

**Review by mehdi-vaadin — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java, line 73 at r2](https://reviewable.io/reviews/vaadin/framework/11224#-LOboVXi7sN4gkCB7Irt:-LOboVXi7sN4gkCB7Iru:bax6jbg) ([raw file](https://github.com/vaadin/framework/blob/9c2edcd3aa21b2bcdfd248fba8e0f5212b21a4be/uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java#L73)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>                     try {
>                         return BasicPushTest
>                                 .getClientCounter(BasicPushTest.this) == expectedValue;
>                     } catch (NoSuchElementException e) {
>                         return false;
>                     }
>                 },
>                 10);
>     }
> ```
</details>

Keep the formatting please.

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java, line 73 at r2](https://reviewable.io/reviews/vaadin/framework/11224#-LOboVXi7sN4gkCB7Irt:-LObpmPj-ywtRUfZkmti:b-swxy7h) ([raw file](https://github.com/vaadin/framework/blob/9c2edcd3aa21b2bcdfd248fba8e0f5212b21a4be/uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java#L73)):*
<details><summary><i>Previously, mehdi-vaadin (Mehdi Javan) wrote…</i></summary><blockquote>

> ```
>                     try {
>                         return BasicPushTest
>                                 .getClientCounter(BasicPushTest.this) == expectedValue;
>                     } catch (NoSuchElementException e) {
>                         return false;
>                     }
>                 },
>                 10);
>     }
> ```
Keep the formatting please.
</blockquote></details>

? didn't we agree on another PR to adjust all those formattings?

**Review by mehdi-vaadin — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224#-:-LObqRxi128gqAAhcUE8:b593w57)* status: all files reviewed, 1 unresolved discussion (waiting on @mehdi-vaadin)

___
*[uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java, line 73 at r2](https://reviewable.io/reviews/vaadin/framework/11224#-LOboVXi7sN4gkCB7Irt:-LObqIzD6pid3YxoFtLm:b-64lgb6) ([raw file](https://github.com/vaadin/framework/blob/9c2edcd3aa21b2bcdfd248fba8e0f5212b21a4be/uitest/src/test/java/com/vaadin/tests/push/BasicPushTest.java#L73)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

? didn't we agree on another PR to adjust all those formattings?
</blockquote></details>

Yes, my mistake.

**Review by mehdi-vaadin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11224)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
