### PR TITLE
Refactor testing of the framework

### PR DESCRIPTION
**Pull request by tsuoanttila**
The tests are now run with Maven with the exception of server integration tests. Server integration tests moved out of vaadin-uitest to make the server test war lightweight.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8393)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 29 of 37 files at r1, 4 of 8 files at r2, 9 of 13 files at r3, 1 of 1 files at r7, 16 of 16 files at r9.
Review status: 41 of 43 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[test/pom.xml, line 102 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbnu5rdhCr6UxsikVvL:-Kbnu5rdhCr6UxsikVvM:b-7see28) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/pom.xml#L102)):*
> ```XML
>         <module>spring-boot</module>
>         <module>cdi</module>
>         <module>bean-api-validation</module>
> ```

Why were these removed in the merge? Or merge missing?

---

*[test/servlet-containers/generic/ivy-taskdefs.xml, line 14 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-KbnudGNEjBkXdhpOswW:-KbnudGNEjBkXdhpOswX:bfhkq60) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/ivy-taskdefs.xml#L14)):*
> ```XML
>     <dependencies>
>         
>         <dependency org="ant-contrib" name="ant-contrib" rev="1.0b3"
> ```

not sure which (if any) of these are really needed anymore - see headers of the ant files and taskdefs in them

---

*[test/servlet-containers/generic/ivy.xml, line 20 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-KbnvRESdwGpNsPqnplL:-KbnvRESdwGpNsPqnplM:b-f5ne9j) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/ivy.xml#L20)):*
> ```XML
>     <dependencies defaultconf="build" defaultconfmapping="build->default">
>         
>         <dependency org="javax.portlet" name="portlet-api"
> ```

Not quite sure but have the impression that many of these dependencies are not needed anymore (e.g. vaadin-client-compiler and everything mapped for the jetty-run conf). However, these can also be cleaned up later.

---

*[test/servlet-containers/generic/ivysettings.xml, line 29 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-KbnvKPtp35FxpB13Wew:-KbnvKPtp35FxpB13Wex:b17v6b) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/ivysettings.xml#L29)):*
> ```XML
>         </chain>
>     </resolvers>
>     <modules>
> ```

see the comments for ivy.xml

---

*[test/servlet-containers/generic/pom.xml, line 46 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo-Lm4L7kRqedBdhre:-Kbo-Lm4L7kRqedBdhrf:big6ss) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/pom.xml#L46)):*
> ```XML
>         </dependency>
> 
>         <dependency>
> ```

(tests are run with Ant so this is probably not used at the moment, but in the future it will be)

---

*[test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/push/BasicPush.java, line 30 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-KbnznEd86sY_LMak2CA:-KbnznEeg4RrkXD7m46N:b-qsx5j) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/push/BasicPush.java#L30)):*
> ```Java
> 
> @Push
> public class BasicPush extends AbstractTestUI {
> ```

is the copy in uitest still used (I'm assuming it is)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by denis-anisimov** [comment]
Reviewed 30 of 37 files at r1, 5 of 8 files at r2, 9 of 13 files at r3, 1 of 1 files at r7, 16 of 16 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[test/pom.xml, line 102 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbnu5rdhCr6UxsikVvL:-Kbo6ArDJMF5-_bdoR-F:b32v57) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/pom.xml#L102)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Why were these removed in the merge? Or merge missing?
</blockquote></details>

+1

---

*[test/servlet-containers/generic/build.properties, line 2 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo6RoZqJOlyClhehR9:-Kbo6Ro_57bywzPLLiov:b1zuwsz) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/servlet-containers/generic/build.properties#L2)):*
> ```INI
> javadoc.doctitle=<h1>Vaadin</h1>
> javadoc.bottom=<i>Copyright &#169; 2000-2014 Vaadin Ltd. All Rights Reserved.</i>
> ```

Is not needed anymore ?

---

*[test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/FlagSeResource.java, line 13 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo6uVyv-wTznLohsEZ:-Kbo6uVyv-wTznLohsE_:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/FlagSeResource.java#L13)):*
> ```Java
>                 + "se.gif");
>     }
> }
> ```

new line

---

*[test/servlet-containers/generic/src/main/resources/com/vaadin/tests/integration/LabelFromDesign.html, line 1 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo7Ba8MuBSeqNajXwc:-Kbo7Ba8MuBSeqNajXwd:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/resources/com/vaadin/tests/integration/LabelFromDesign.html#L1)):*
> ```HTML
> <vaadin-label />
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by tsuoanttila** [comment]
*[test/pom.xml, line 102 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbnu5rdhCr6UxsikVvL:-KboCvlCVdUtGNNjUprF:b-4ajdqg) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/pom.xml#L102)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Merge conflict between current master and the branch. Restoring with a merge from master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by tsuoanttila** [comment]
*[test/servlet-containers/generic/build.properties, line 2 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo6RoZqJOlyClhehR9:-KboD2hu6V6JLqiC96ou:b-viclxu) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/servlet-containers/generic/build.properties#L2)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is not needed anymore ?
</blockquote></details>

The only file pointing here is the common.xml in the same folder which is only used in server test build. Nothing to do with javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by tsuoanttila** [comment]
Review status: 41 of 43 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/push/BasicPush.java, line 30 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-KbnznEd86sY_LMak2CA:-Kbo0yDfBuwJ_dlwwDtH:bq5ukky) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/push/BasicPush.java#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is the copy in uitest still used (I'm assuming it is)
</blockquote></details>

I think it is still used for testing Push features.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r10.
Review status: 42 of 43 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by tsuoanttila** [comment]
Review status: 41 of 43 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/pom.xml, line 102 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbnu5rdhCr6UxsikVvL:-Kbof3ZrRTO4negBZ1WO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/23139cf0196e3120535452e7197627be4fb41fec/test/pom.xml#L102)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Merge conflict between current master and the branch. Restoring with a merge from master.
</blockquote></details>

Done.

---

*[test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/FlagSeResource.java, line 13 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo6uVyv-wTznLohsEZ:-KboehYdqdFqylL6yFOb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/java/com/vaadin/tests/integration/FlagSeResource.java#L13)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[test/servlet-containers/generic/src/main/resources/com/vaadin/tests/integration/LabelFromDesign.html, line 1 at r9](https://reviewable.io:443/reviews/vaadin/framework/8393#-Kbo7Ba8MuBSeqNajXwc:-KboeyFGIsgJW2V58eQD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c1438c34d084cb6493985ee4725c6cc1687f2565/test/servlet-containers/generic/src/main/resources/com/vaadin/tests/integration/LabelFromDesign.html#L1)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393#-:-KbtXXlFhJ62Xr_7Tl4T:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8393)*

**Pull request merged**
