### PR TITLE
Support for HTML5 push/replaceState for proper deep linking features

### PR DESCRIPTION
**Pull request by mstahv**
This change adds low level support for deep linking without anchor hacks. This is 
also essential for SEO as "hashbang" style AJAX indexing is deprecated by Google.

Next step is to make Navigator use this instead of hashbang style identifiers.
Hashbang could of course be left for fallback support (old links).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8116)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
A number of test failures.

**Comment by mstahv** [comment]
@denis-anisimov How can I see the test failures? There should be only one test for this feature and it is ignored as I haven't been able to test it it works. So I wonder what test are failing :-)

**Comment by hesara** [comment]
In case you don't have an account on teamcity.vaadin.com (you can ask Juhani about that), the following tests failed in validation (on PhantomJS): RefreshFragmentChangeTest.testFragmentChange, InitiallyEmptyFragmentTest.testNoFragmentChangeEventWhenInitiallyEmpty, UriFragmentTest.testUriFragment, NavigatorListenerModifiesListenersTest.testIfConfirmBack, NavigatorViewBlocksBackButtonActionTest.testIfCancelBack and NavigatorViewBlocksBackButtonActionTest.testIfConfirmBack .

We are trying to find solutions to the visibility of test failures - perhaps using Travis in the future also for these validation builds if it can meet our requirements.

**Comment by denis-anisimov** [comment]
@mstahv OK, the link is actually the same fro inside the office network and from outside.
It's teamcity.vaadin.com
I'm logged in automatically when I'm inside the office network butI guess it's just because of working laptop.

So we have an issue for external users who don't have an access to teamcity.vaadin.com to view verification results.

The tests are still failing.
The tests are : 
- RefreshFragmentChangeTest.testFragmentChange (assertion error, unexpected text)
- InitiallyEmptyFragmentTest.testNoFragmentChangeEventWhenInitiallyEmpty (assertion error, unexpected text)
- UriFragmentTest.testUriFragment (timeout exception , Expected condition failed)
- NavigatorListenerModifiesListenersTest.testIfConfirmBack (timeout exception , Expected condition failed)
- NavigatorViewBlocksBackButtonActionTest.testIfCancelBack ( Current URL should be equal to initial prompted view URL )
- NavigatorViewBlocksBackButtonActionTest.testIfConfirmBack (element is not found)

**Comment by denis-anisimov** [comment]
And Henri has already posted the comments. Sorry for duplication.

**Comment by pleku** [comment]
Reviewed 1 of 8 files at r1, 5 of 6 files at r3.
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TWqK9tUGdISG_ydoM:-K_TWqK9tUGdISG_ydoN:b-fz3qnx) (no related file):*
Please change formatting to use spaces instead of tabs for java files to avoid unnecessary whitespace changes. Not sure why this is not stated in Readme, probably because we expect everyone to use Eclipse defaults 

---

*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 141 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TZjzLsrHuccQJuejO:-K_TZjzLsrHuccQJuejP:b-wp2si2) ([raw file](https://github.com/vaadin/framework/blob/c66e5959745b13a95239873059ccd92acc14144a/client/src/main/java/com/vaadin/client/ui/VUI.java#L141)):*
> ```Java
>                 currentFragment = newFragment;
>                 connection.flushActiveConnector();
>                 connection.updateVariable(id, UIConstants.LOCATION_VARIABLE,
> ```

By removing this, you break migrating every existing V7 app that uses fragment for navigation ? I'm sure you know that PopStateEvent is not fired for fragment changes.

Even if the Navigator would be updated to use pushState, we would still have to keep this around (even as deprecated) since we are promising this migration path from V7 to V8 and this would simply break quite much.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 597 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_Ue9hs7Pm1F9bKUd:-K_T_UeAxh4lny-dK1Ld:b-68l2be) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L597)):*
> ```Java
>      * @return a registration object for removing the listener
>      */
>     public Registration addUriFragmentChangedListener(
> ```

You didn't even remove this listener API even though you removed the representing part from client ?

---

*[server/src/main/java/com/vaadin/server/Page.java, line 1152 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_wHxNJudX8DTVdUu:-K_T_wHxNJudX8DTVdUv:bk9y763) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L1152)):*
> ```Java
>             if (fireEvents
>                     && !SharedUtil.equals(oldUriFragment, newUriFragment)) {
>                 fireEvent(new UriFragmentChangedEvent(this, newUriFragment));
> ```

Updating the fragment doesn't cause a `PopStateEvent`on browser so this totally broken 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by pleku** [comment]
If we want to add pushState now, we would still have to keep the existing fragment/hash based navigation style to support migration from V7 to V8. All fragment related API on server side UI/Page/Navigator should be `@Deprecated`.

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116#-:-K_TaC2gXSsbT7e7OcQw:b6536nj)*

**Comment by mstahv** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 141 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TZjzLsrHuccQJuejO:-K_TpIwg6bEX-hPOGQ_5:b-2szfy1) ([raw file](https://github.com/vaadin/framework/blob/c66e5959745b13a95239873059ccd92acc14144a/client/src/main/java/com/vaadin/client/ui/VUI.java#L141)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

By removing this, you break migrating every existing V7 app that uses fragment for navigation ? I'm sure you know that PopStateEvent is not fired for fragment changes.

Even if the Navigator would be updated to use pushState, we would still have to keep this around (even as deprecated) since we are promising this migration path from V7 to V8 and this would simply break quite much.
</blockquote></details>

popstate handler takes care of firing legacy URI fragment change listeners as well. Tests wouldn't pass without it.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 597 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_Ue9hs7Pm1F9bKUd:-K_TpX-uLAu-7aSLkWyp:b-p2xpzc) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L597)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You didn't even remove this listener API even though you removed the representing part from client ?
</blockquote></details>

No, because the listener is still there and functional and should be for background compatibility. I have "some experience" on developing framework, I wouldn't go and remove this big feature without deprecation.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 1152 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_wHxNJudX8DTVdUu:-K_TptANuTzqehlfPJkG:b3kre) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L1152)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Updating the fragment doesn't cause a `PopStateEvent`on browser so this totally broken 
</blockquote></details>

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by mstahv** [comment]
The fragment based API it is still there. I though about deprecating that as well. Might be better to start getting rid of that.

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TWqK9tUGdISG_ydoM:-K_TqdzHxLfmR6RSH7PU:b-1iqcbj) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please change formatting to use spaces instead of tabs for java files to avoid unnecessary whitespace changes. Not sure why this is not stated in Readme, probably because we expect everyone to use Eclipse defaults 
</blockquote></details>

Is there somewhere some formatting rules for Eclipse?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116#-:-K_TqNqHK01AEXiDUXAJ:b-48qqti)*

**Comment by pleku** [comment]
Could deprecated it even in this PR. Then would should mention replacement in e.g. release-notes.html

---

Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TWqK9tUGdISG_ydoM:-K_UdRYoCsOa4H4TT2gt:b-h04z7m) (no related file):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Is there somewhere some formatting rules for Eclipse?
</blockquote></details>

It seems unfortunately not

---

*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 141 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TZjzLsrHuccQJuejO:-K_UdV4rJ3NmBvpJjxwQ:b3w455g) ([raw file](https://github.com/vaadin/framework/blob/c66e5959745b13a95239873059ccd92acc14144a/client/src/main/java/com/vaadin/client/ui/VUI.java#L141)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

popstate handler takes care of firing legacy URI fragment change listeners as well. Tests wouldn't pass without it.
</blockquote></details>

As discussed separately, this will only break in IE11 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/

---

*[server/src/main/java/com/vaadin/server/Page.java, line 597 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_Ue9hs7Pm1F9bKUd:-K_UZvm0meldPsZIxd5y:bg0tm9k) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L597)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

No, because the listener is still there and functional and should be for background compatibility. I have "some experience" on developing framework, I wouldn't go and remove this big feature without deprecation.
</blockquote></details>

My bad.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 1152 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_wHxNJudX8DTVdUu:-K_UZxFltAZpkcC3PB1p:b3w455g) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L1152)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

?
</blockquote></details>

As discussed separately, this will only break in IE11 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116#-:-K_UdADRQu6qIplBT22d:bcpkey3)*

**Comment by mstahv** [comment]
Done. But didn't do anything for release-notes.html. Don't know where it is, IMO better that somebody from core team does that.

---

Review status: 3 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TWqK9tUGdISG_ydoM:-K_VrKYvb1ZvQ0hjFLG9:b2cp7h4) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

It seems unfortunately not
</blockquote></details>

@hesara pointed out that project root/eclipse contains some files, but README or CONTRIBUTING should be modified to contain references and instructions to use them.

---

*[client/src/main/java/com/vaadin/client/ui/VUI.java, line 141 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_TZjzLsrHuccQJuejO:-K_VrJIZDM9x5NT3cAhs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c66e5959745b13a95239873059ccd92acc14144a/client/src/main/java/com/vaadin/client/ui/VUI.java#L141)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

As discussed separately, this will only break in IE11 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 597 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_Ue9hs7Pm1F9bKUd:-K_VrDxbPxyp-3mMWlPz:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L597)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

My bad.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/Page.java, line 1152 at r3](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_T_wHxNJudX8DTVdUu:-K_Vqy_Q332OspB1uugV:boeg1cv) ([raw file](https://github.com/vaadin/framework/blob/edecc088c131779f2e5724812667ce980808aea9/server/src/main/java/com/vaadin/server/Page.java#L1152)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

As discussed separately, this will only break in IE11 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/
</blockquote></details>

Done. Added a new UriFragment test that covers link usage and workaround.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116#-:-K_VrbYm5XeCV5EqhFMj:b8h9s65)*

**Comment by pleku** [comment]
Reviewed 1 of 8 files at r1, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cMQEfRICMefk0K9xu:-K_cMQEfRICMefk0K9xv:b-1kgadl) (no related file):*
:lgtm: but I'll run the modern browsers test on this before merging

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/PushStateAndReplaceState.java, line 16 at r4](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cJrPT28pEQsJUoGwt:-K_cJrPT28pEQsJUoGwu:bift13i) ([raw file](https://github.com/vaadin/framework/blob/de71ce9c905fcba6faf4bdd6af6a574c7a2c8331/uitest/src/main/java/com/vaadin/tests/components/ui/PushStateAndReplaceState.java#L16)):*
> ```Java
> import com.vaadin.ui.Notification;
> 
> public class PushStateAndReplaceState extends AbstractReindeerTestUI {
> ```

No need to fix this, but ought to use `AbstractTestUI` with Valo instead of testing with the Reindeer theme. We probably should deprecate `AbstractReindeerTestUI`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cMQEfRICMefk0K9xu:-K_hJdqTK5jHeNwqcL4D:bygack2) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

:lgtm: but I'll run the modern browsers test on this before merging
</blockquote></details>

4 related test failures, all on IE11:
 NavigatorViewBlocksBackButtonActionTest.testIfCancelBack(Windows_InternetExplorer_11) 	
  NavigatorViewBlocksBackButtonActionTest.testIfConfirmBack(Windows_InternetExplorer_11) 	
 FragmentHandlingAndAsynchUIUpdateTest.testBackwardForwardHistoryWithWaitingForSettingFrag(Windows_InternetExplorer_11) 	
  SettingNullFragmentTest.testSettingNullURIFragment(Windows_InternetExplorer_11) 	

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cMQEfRICMefk0K9xu:-K_hK6uGq8cfhh3XUIds:b-2s48i5) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

4 related test failures, all on IE11:
 NavigatorViewBlocksBackButtonActionTest.testIfCancelBack(Windows_InternetExplorer_11) 	
  NavigatorViewBlocksBackButtonActionTest.testIfConfirmBack(Windows_InternetExplorer_11) 	
 FragmentHandlingAndAsynchUIUpdateTest.testBackwardForwardHistoryWithWaitingForSettingFrag(Windows_InternetExplorer_11) 	
  SettingNullFragmentTest.testSettingNullURIFragment(Windows_InternetExplorer_11) 	
</blockquote></details>

http://r2d2.devnet.vaadin.com/viewLog.html?buildId=148818&tab=buildResultsDiv&buildTypeId=Vaadin80_VaadinTests_ModernBrowsers

I don't have time to investigate these myself before next week, so please take a look

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by mstahv** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cMQEfRICMefk0K9xu:-K_kVnx-P6FZIqvfKBoB:b-achy86) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

http://r2d2.devnet.vaadin.com/viewLog.html?buildId=148818&tab=buildResultsDiv&buildTypeId=Vaadin80_VaadinTests_ModernBrowsers

I don't have time to investigate these myself before next week, so please take a look
</blockquote></details>

I managed to open the more detailed errors with your link (when in VPN), based on the first two tests it looks like there is some sort of timing or TestBench/Selenium issue. With a local virtual machine "executing" the test manually, it works just fine. Probably TestBench driver reads the initial URL too early, so that the initial fragment has not been set by the client side. Don't know why this would happen now though. New fragment goes to browser via bit different mechanism, nothing else.

You could probably fix this by adding a timeout or some check that the initial main view is loaded, before reading the URL with driver.getCurrentUrl().

As I have no way to execute tests on the cluster I think somebody else should look into this.

---

*[uitest/src/main/java/com/vaadin/tests/components/ui/PushStateAndReplaceState.java, line 16 at r4](https://reviewable.io:443/reviews/vaadin/framework/8116#-K_cJrPT28pEQsJUoGwt:-K_k_j9phemROrHjfUJb:b7j02j8) ([raw file](https://github.com/vaadin/framework/blob/de71ce9c905fcba6faf4bdd6af6a574c7a2c8331/uitest/src/main/java/com/vaadin/tests/components/ui/PushStateAndReplaceState.java#L16)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No need to fix this, but ought to use `AbstractTestUI` with Valo instead of testing with the Reindeer theme. We probably should deprecate `AbstractReindeerTestUI`
</blockquote></details>

You should really write instructions to CONTRIBUTIN.md if you want external contributors to contribute more for the tests as well. I had no other way, but to copy past some existing test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Comment by mstahv** [comment]
Now it is "fixed". Tested locally with modern IE virtual machine for IE11.

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8116)*

**Pull request merged**
