### PR TITLE
OSGi: Fixing dynamic resource registration after activation

### PR DESCRIPTION
**Pull request by swimmesberger**
There is an issue that when the vaadin-shared bundle is activated before the resource contributing bundle (themes, widgets, static resources) that the VaadinResourceTrackerComponent component is already activated and the newly binded OsgiVaadinResource is not registered on the HttpService. This pull request should fix this issue.
I have also fixed a small memory leakage issue that when the OsgiVaadinResource is unbinded it does not remove itself from the HashMap. (https://github.com/vaadin/framework/pull/11334/files#diff-ae3d49908eee411466e65f24d49c6db9R183)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11334)

### CODE REVIEW

**Comment by TatuLund** [comment]
Is this pull request addressing issue https://github.com/vaadin/framework/issues/10220 ?

**Comment by swimmesberger** [comment]
The last pull request https://github.com/vaadin/framework/pull/11166 introduced more dynamics in vaadin (and the OSGi support) but I missed some details like when vaadin-share is already activated and the resource contributing bundles (vaadin-themes, vaadin-client) are activated AFTER vaadin-share is activated you get the issue @ctliv mentioned in the issue. This pull request should resolve this.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11334)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @swimmesberger)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11334#-LSKNoYeD165QPnAGun1:-LSKNoYeD165QPnAGun2:b-95aid4) (no related file):*
Thanks for the contribution. I will run a server integration tests for this PR. 

---

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11334)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @swimmesberger)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11334#-LSKNoYeD165QPnAGun1:-LSKY06h6lSXvNxbsq31:b-ur3yy5) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Thanks for the contribution. I will run a server integration tests for this PR. 
</blockquote></details>

Integration tests pass. 

---
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 306 at r1](https://reviewable.io/reviews/vaadin/framework/11334#-LSKYOJL7bYyAHO54ndW:-LSKYOJL7bYyAHO54ndX:biedhnw) ([raw file](https://github.com/vaadin/framework/blob/610ac3a8b12484f3f55d25eeffae3b9d27f8507f/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L306)):*
> ```Java
>             context = service.createDefaultHttpContext();
>         }
>         
> ```

extra spaces.
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 327 at r1](https://reviewable.io/reviews/vaadin/framework/11334#-LSKYQ9p7ufnpwBN4fyt:-LSKYQ9p7ufnpwBN4fyu:b-yigpbu) ([raw file](https://github.com/vaadin/framework/blob/610ac3a8b12484f3f55d25eeffae3b9d27f8507f/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L327)):*
> ```Java
>         }
>     }
> }
> ```

new line at the end

**Review by swimmesberger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11334)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @swimmesberger and @ZheSun88)

___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 306 at r1](https://reviewable.io/reviews/vaadin/framework/11334#-LSKYOJL7bYyAHO54ndW:-LSKr95P3L7k-IQ-6jXP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/610ac3a8b12484f3f55d25eeffae3b9d27f8507f/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L306)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

extra spaces.
</blockquote></details>

Done.
___
*[shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java, line 327 at r1](https://reviewable.io/reviews/vaadin/framework/11334#-LSKYQ9p7ufnpwBN4fyt:-LSKr9_OE39wP-X9p9Pd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/610ac3a8b12484f3f55d25eeffae3b9d27f8507f/shared/src/main/java/com/vaadin/osgi/resources/impl/VaadinResourceTrackerComponent.java#L327)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

new line at the end
</blockquote></details>

Done.

**Review by ZheSun88 — APPROVED** [review]

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11334)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ctliv** [comment]
> The last pull request #11166 introduced more dynamics in vaadin (and the OSGi support) but I missed some details like when vaadin-share is already activated and the resource contributing bundles (vaadin-themes, vaadin-client) are activated AFTER vaadin-share is activated you get the issue @ctliv mentioned in the issue. This pull request should resolve this.

I was finally able to perform a test of Vaadin 8.6.3 on Liferay CE 7.1.1 GA2 and I confirm that the issue I found is now solved. Well done! Thanks, @swimmesberger

**Comment by TatuLund** [comment]
@ctliv It is great to hear this. Could you give us your feedback is the documentation here https://vaadin.com/docs/v8/framework/portal/portal-osgi.html sufficient to get it running, or is there some missing steps that needs to be taken into account?

**Pull request merged**
