### PR TITLE
Render font icon correctly on the 'more' menu item

### LINKED ISSUE #8125: MenuBar moreMenuItem doesn't support font icons
A font icon set on the "more menu item" of a MenuBar is replaced with a broken image element when menu items are collapsed into the "more menu".

Instead of a standard v-icon element, the font icon is rendered thusly:
``

Vaadin 7.7.4

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8125

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8126)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8126#-K_YGnNfPbcLlumYcqt2:-K_YGnNfPbcLlumYcqt3:b-90ewu3) ([raw file](https://github.com/vaadin/framework/blob/ef66216af18ac556543c5b51a183249f849f750e/uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java#L32)):*
> ```Java
>         MenuBar menu = new MenuBar();
>         menu.setWidth("400px");
>         menu.addItem("Main", FontAwesome.MAIL_REPLY_ALL, null);
> ```

The test is only about FontAwsome icon URLs.

Would be good to check that plain URLs also works as expected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8126)*

**Comment by denis-anisimov** [comment]
Two test failures. One is weird (about Java version which cannot relate to the change).
The other one is about inability to find an element.
Not sure that they have any relation to the PR.

**Comment by Artur-** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8126#-K_YGnNfPbcLlumYcqt2:-K_YIx2kusZXwC8vb-_X:b-t9rstz) ([raw file](https://github.com/vaadin/framework/blob/ef66216af18ac556543c5b51a183249f849f750e/uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The test is only about FontAwsome icon URLs.

Would be good to check that plain URLs also works as expected.
</blockquote></details>

Although completely unrelated to this fix, I expanded the test to cover images also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8126)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 5 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8126#-K_YGnNfPbcLlumYcqt2:-K_hPeRVVeNJCV70I6Ob:blxqscl) ([raw file](https://github.com/vaadin/framework/blob/ef66216af18ac556543c5b51a183249f849f750e/uitest/src/main/java/com/vaadin/tests/components/menubar/MenuBarFontIcon.java#L32)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Although completely unrelated to this fix, I expanded the test to cover images also
</blockquote></details>

The root cause of the issue doesn't relate to the direct image URL : true.
But the functionality wise its the same. So it's good to have a test for the functionality but not for the one usecase only.
Theoretically the code could have broke working functionality (for regular images) and make working only font icons.....
But that should be decided each time separately. Here it's quire easy to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8126)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8126)*

**Pull request merged**
