### PR TITLE
Color picker add methods to set modality of the color picker

### PR DESCRIPTION
**Pull request by anasmi**
Overriding **setModal** in ColorPickerPopup to eliminate centering the window

Resolves https://github.com/vaadin/framework/issues/9511

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10815)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 115 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFzm86qYeJO5OP72r:-L9uFzm86qYeJO5OP72s:bf21y1r) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L115)):*
> ```Java
>     protected boolean historyVisible = true;
>     protected boolean textfieldVisible = true;
>     private boolean modal;
> ```

I am not sure if we need this variable here. it is not used at all. Can be ColorPicker non modal?

---

*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 543 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFfHx-F_tBKqRsLfG:-L9uFfHx-F_tBKqRsLfH:b-nnm6u9) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L543)):*
> ```Java
>     }
> 
>     /**
> ```

Javadoc is missing

---

*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 551 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFiF48U3K2Y-zHG0u:-L9uFiF48U3K2Y-zHG0v:b-nnm6u9) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L551)):*
> ```Java
>     }
> 
>     /**
> ```

Javadoc is missing

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 115 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFzm86qYeJO5OP72r:-LABcZpv1mCWcSmndvGo:by6kjfc) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L115)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I am not sure if we need this variable here. it is not used at all. Can be ColorPicker non modal?
</blockquote></details>

I am not sure, but if I understood correctly framework should not set modal by default, but we should allow users to decide how they want window to be shown. Also, now there is no option, but window is non-modal always.
Regarding the variable. We need to set inner ColorPickerPopup  to modal. When we calling setModal this window is not initialized yet, therefore we need some variable to store value and assign it only when we calling showPopup

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 543 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFfHx-F_tBKqRsLfG:-LABlkkk51mB3ARcQDO1:b-7tfmjp) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L543)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Javadoc is missing
</blockquote></details>

added

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 551 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFiF48U3K2Y-zHG0u:-LABlnByDcrrq36yVIl9:b-7tfmjp) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L551)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Javadoc is missing
</blockquote></details>

added

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by elmot** [comment]
Reviewed 2 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 543 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFfHx-F_tBKqRsLfG:-LACHLL4DWwQBBEOOeDX:b7l2yq3) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L543)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

added
</blockquote></details>

Please note if the ColorPicker is open from a modal Window, it has to be set modal also.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by elmot** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 567 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10815#-LACcurDE2AC7bWQa9Re:-LACcurDE2AC7bWQa9Rf:b-plygk1) ([raw file](https://github.com/vaadin/framework/blob/e5cc2071a07791c98c9b360975a9198b7e5f9d67/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L567)):*
> ```Java
>      * outside that ColorPicker cannot be accessed.
>      * <p>
>      * Note: If ColorPicker is the child of modal component, it must be set to
> ```

```
Note: It must to be set to {@code true} if ColorPicker is a child of modal {@link Window}

@see Window#setModal
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 567 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10815#-LACcurDE2AC7bWQa9Re:-LACqCfR4O84rNe3GPgA:bs7wtrb) ([raw file](https://github.com/vaadin/framework/blob/e5cc2071a07791c98c9b360975a9198b7e5f9d67/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L567)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

```
Note: It must to be set to {@code true} if ColorPicker is a child of modal {@link Window}

@see Window#setModal
```


</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by anasmi** [comment]
*[server/src/main/java/com/vaadin/ui/AbstractColorPicker.java, line 543 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10815#-L9uFfHx-F_tBKqRsLfG:-LACqEp-DDA8fu8DZARb:b499q7j) ([raw file](https://github.com/vaadin/framework/blob/5caf3d34b0a26fe36369d1afb98c746af816247a/server/src/main/java/com/vaadin/ui/AbstractColorPicker.java#L543)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please note if the ColorPicker is open from a modal Window, it has to be set modal also.
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10815)*

**Pull request merged**
