### PR TITLE
Support for defining the root element for Javascript components

### LINKED ISSUE #7005: Support defining tag name for Javascript components
**Originally by @Artur-**

___
A JavaScript component always gets a <div> as its root element. This leads to extra wrapping when you actually want something else, like <button>.

It could be done in a similar way to init, so that you could write in the JS file:
```
some_package_MyButton.tag = "button";
```

___
 Imported from https://dev.vaadin.com/ issue #18526

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #7005

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8143)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DhwVdiZsTeg0xf4G:-Ka1DhwVdiZsTeg0xf4H:bh6iciy) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java#L45)):*
> ```Java
>  * {@link com.vaadin.client.ui.JavaScriptWidget} ) just consisting of a single
>  * element (a <code>div</code> by default) to which the JavaScript code should
>  * initialize its own user interface. The tag can be overridden by defining a
> ```

This information is quite significant and is not well defined (and visible) via any contract.
It should be emphasized somehow.
May be a separate paragraph, bold text and some code example.

---

*[uitest/src/com/vaadin/tests/components/javascriptcomponent/JavaScriptSpanComponent.js, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DQYfFZ7Jndpiwp_U:-Ka1DQYgPR873_y99Cfp:bmebhsl) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/uitest/src/com/vaadin/tests/components/javascriptcomponent/JavaScriptSpanComponent.js#L6)):*
> ```JavaScript
>   } 
> }
> com_vaadin_tests_components_javascriptcomponent_JavaScriptSpan_Span.tag = "span";
> ```

new line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DhwVdiZsTeg0xf4G:-Ka9-uJKDh8MmzNFCz0h:bw5avru) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This information is quite significant and is not well defined (and visible) via any contract.
It should be emphasized somehow.
May be a separate paragraph, bold text and some code example.
</blockquote></details>

Not sure how to emphasize it more in a sensible way. The whole paragraph is already about the root element.

Maybe the problem is that the whole javadoc for this class contains a lot of information and almost no examples?

---

*[uitest/src/com/vaadin/tests/components/javascriptcomponent/JavaScriptSpanComponent.js, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DQYfFZ7Jndpiwp_U:-Ka91vivO7LjpTgl6B5V:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/uitest/src/com/vaadin/tests/components/javascriptcomponent/JavaScriptSpanComponent.js#L6)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 6 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DhwVdiZsTeg0xf4G:-KaCDY1x9AzHEa1ErIEr:b-bwii7t) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java#L45)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Not sure how to emphasize it more in a sensible way. The whole paragraph is already about the root element.

Maybe the problem is that the whole javadoc for this class contains a lot of information and almost no examples?
</blockquote></details>

Yes, some short example would be useful.
Could you please insert it as a section here ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Comment by denis-anisimov** [comment]
Up to you to provide an example in javadocs.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143#-:-KaCDvgQ4bRSOx4MTmhV:b-66ml5r)*

**Comment by Artur-** [comment]
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java, line 45 at r1](https://reviewable.io:443/reviews/vaadin/framework/8143#-Ka1DhwVdiZsTeg0xf4G:-KaLngxGG_8etm_IrnDy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3b78480f54d897caa9764cb4a31d30b22df7ef74/server/src/main/java/com/vaadin/ui/AbstractJavaScriptComponent.java#L45)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes, some short example would be useful.
Could you please insert it as a section here ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8143)*

**Pull request merged**
