### PR TITLE
Make AbstractListing implement Focusable

### PR DESCRIPTION
**Pull request by ahie**
Fixes vaadin/framework8-issues#552

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7965)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 473 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrx5K9VxJT8NNSbClB:-KYrx5K9VxJT8NNSbClC:bd0kk99) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/server/src/main/java/com/vaadin/ui/AbstractListing.java#L473)):*
> ```Java
>     @Override
>     public int getTabIndex() {
>         return getState().tabIndex;
> ```

should be getState(false).tabIndex

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 478 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrxEYT0MlNgkkxo3U3:-KYrxEYT0MlNgkkxo3U4:bqz5k6b) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/server/src/main/java/com/vaadin/ui/AbstractListing.java#L478)):*
> ```Java
>     @Override
>     public void setTabIndex(int tabIndex) {
>         getState(true).tabIndex = tabIndex;
> ```

should probably be the simpler getState().tabIndex = ...

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 441 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrxOfL1m1vx64ayMy3:-KYrxOfL1m1vx64ayMy4:b-52har) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L441)):*
> ```Java
> 
>         createSelectionMenu(stateMenu);
>         
> ```

extra whitespace?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7965)*

**Comment by pleku** [comment]
Reviewed 1 of 4 files at r1, 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYwDvfR5IxqklAwmUN6:-KYwDvfR5IxqklAwmUN7:bvl2b5s) (no related file):*
No test for `TwinColSelect` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7965)*

**Comment by ahie** [comment]
Review status: 7 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYwDvfR5IxqklAwmUN6:-KYwdvZTEc4syzPCcvEk:bjer9r6) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

No test for `TwinColSelect` ?
</blockquote></details>

Added a test for it.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 473 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrx5K9VxJT8NNSbClB:-KYwD4QZvHh1DbAX7P8g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/server/src/main/java/com/vaadin/ui/AbstractListing.java#L473)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should be getState(false).tabIndex
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractListing.java, line 478 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrxEYT0MlNgkkxo3U3:-KYwD4BBvJwNnGK4z9uL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/server/src/main/java/com/vaadin/ui/AbstractListing.java#L478)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should probably be the simpler getState().tabIndex = ...
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java, line 441 at r1](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYrxOfL1m1vx64ayMy3:-KYwRPvvzPHfQxUT7cei:bss4a2b) ([raw file](https://github.com/vaadin/framework/blob/64702ea27bf0af52a319a2a95b5ee94c51ec50f2/uitest/src/main/java/com/vaadin/tests/components/grid/basics/GridBasics.java#L441)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra whitespace?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7965)*

**Comment by pleku** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/7965#-KYwDvfR5IxqklAwmUN6:-KYx2LzY51PmRNDdAucz:bffw0ku) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Added a test for it.
</blockquote></details>

Not added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7965)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7965)*

**Pull request merged**
