### PR TITLE
Added getStateParameterMap functionality to Navigator that allows acc…

### PR DESCRIPTION
**Pull request by peterl1084**
…essing the state parameters through a map

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9517)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Minor JavaDoc issues and a question about since tags.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 363 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQI9gdZB5DkVzV5jNo:-KmQI9geqJtQTdJKFnXb:b-1v89fs) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L363)):*
> ```Java
>      * The {@link UI} bound with the Navigator.
>      *
>      * @since 8.0.3
> ```

Why does this change contain since tags with seemingly arbitrary version number?

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 780 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQIhuQtfsXyXKVUC0q:-KmQIhuQtfsXyXKVUC0r:b-yfi561) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L780)):*
> ```Java
>      * represents a parameter in the state. The state parameter separator
>      * character needs to be specified with the separator.
>      * 
> ```

Could use `@see #getStateParameterMap()` and vice versa for the other JavaDoc

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 792 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQIvGv6Ks6C3-cGRBu:-KmQIvGwvo3xSvUghGp-:bkuss7e) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L792)):*
> ```Java
>      * Parses the state parameter map using given separator String.
>      * 
>      * @param separator
> ```

param description missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9517#-:-KmQIyrfxJa1bXlNBlXz:b-r01762)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 363 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQI9gdZB5DkVzV5jNo:-KmR9GLEqn2aGfVbQ0bo:ba3dfob) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L363)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why does this change contain since tags with seemingly arbitrary version number?
</blockquote></details>

Removed

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 780 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQIhuQtfsXyXKVUC0q:-KmR9HBMj7fAV4cPOvGX:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L780)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could use `@see #getStateParameterMap()` and vice versa for the other JavaDoc
</blockquote></details>

Done

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 792 at r1](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmQIvGv6Ks6C3-cGRBu:-KmR9HgKO0F0u_WzvXd3:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/39162d36ef1ba08b7f3cc80a928012ea65fcaf6f/server/src/main/java/com/vaadin/navigator/Navigator.java#L792)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

param description missing
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9517)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 763 at r2](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmRAOS-1atwOTxi1E6r:-KmRAOS0O_MNPGVUNS47:b6gsj1z) ([raw file](https://github.com/vaadin/framework/blob/79ddcea207b3c1eaa1b4f730c9f77d2258479050/server/src/main/java/com/vaadin/navigator/Navigator.java#L763)):*
> ```Java
>      *
>      * Uses {@literal &} as parameter separator, i.e.
>      * {@literal #!view/foo&bar=baz} will return a map The state parameter
> ```

I'm having some trouble trying to read this sentence.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 808 at r2](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmRAk6gX-wE0qTCTgwx:-KmRAk6gX-wE0qTCTgwy:b-4osro0) ([raw file](https://github.com/vaadin/framework/blob/79ddcea207b3c1eaa1b4f730c9f77d2258479050/server/src/main/java/com/vaadin/navigator/Navigator.java#L808)):*
> ```Java
>         }
> 
>         String parameterString = state.substring(
> ```

substring handles the indices correctly and does not throw on IOOB?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9517)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 763 at r2](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmRAOS-1atwOTxi1E6r:-KmRFrOwvhJsOzteiuLI:b-886gsx) ([raw file](https://github.com/vaadin/framework/blob/79ddcea207b3c1eaa1b4f730c9f77d2258479050/server/src/main/java/com/vaadin/navigator/Navigator.java#L763)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I'm having some trouble trying to read this sentence.
</blockquote></details>

Fixed

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 808 at r2](https://reviewable.io:443/reviews/vaadin/framework/9517#-KmRAk6gX-wE0qTCTgwx:-KmRG4HvVuW1cnfVPZaw:bb7sa0t) ([raw file](https://github.com/vaadin/framework/blob/79ddcea207b3c1eaa1b4f730c9f77d2258479050/server/src/main/java/com/vaadin/navigator/Navigator.java#L808)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

substring handles the indices correctly and does not throw on IOOB?
</blockquote></details>

yes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9517)*

**Comment by tsuoanttila** [comment]
:lgtm: @Artur-, remove your blocks

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9517#-:-KmRKOgnNrY_9-Qe8qzw:bkq4xd5)*

**Pull request merged**
