### PR TITLE
Fix BindingBuilder to always use the same instance

### PR DESCRIPTION
**Pull request by tsuoanttila**
Addresses #9927

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10004)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This is a WIP PR to discuss wether this change should be done or not. Resolving the issue like this does remove the builder contract violation, but at the same time opens the builder for runtime class cast errors. Ping @pwilkin

**Comment by pwilkin** [comment]
Seems to me like the lesser of two evils (based on the counterintuitivity of the previous solution).

**Comment by tsuoanttila** [comment]
@Legioth and @hesara this needs to be discussed. Here or face to face?

**Comment by hesara** [comment]
OK for me after merging in changes from master (though see the comment below), assuming @legioth does not object.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2419 at r2](https://reviewable.io:443/reviews/vaadin/framework/10004#-KusApzSj3nkznjJz601:-KusApzTGFP7I3nu5RRy:bm19m3v) ([raw file](https://github.com/vaadin/framework/blob/f4706a9d63d71202ebb3b4eb15895090acb4b8c4/server/src/main/java/com/vaadin/data/Binder.java#L2419)):*
> ```Java
>             boundProperties.entrySet()
>                     .removeIf(entry -> entry.getValue().equals(binding));
>             ((BindingImpl<BEAN, ?, ?>) binding).onValueChange.remove();
> ```

(this is a bit suspicious to me, and will probably complicate merge with master)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10004#-:-KusB6P7uXQh7UTYqP4B:b-keodzz)*

**Comment by hesara** [comment]
Does this also address #9619?

**Comment by tsuoanttila** [comment]
Yes it does.

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10004)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10004#-:-KusuQmJZPtdjrDuqB2U:bnfp4nl)*

**Pull request merged**
