### PR TITLE
Clean up SQL container tests.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Only one UI smoke test for the SQL container (along with a Table).

Fixes vaadin/framework8-issues#582

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8091)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 11 of 13 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/smoke/TableSqlContainer.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8091#-KZzot6JEIZnKjKTmh0m:-KZzot6JEIZnKjKTmh0n:bnwq4o8) ([raw file](https://github.com/vaadin/framework/blob/366cd204652e290c85af112d6da7d7dd7786ad77/uitest/src/main/java/com/vaadin/tests/smoke/TableSqlContainer.java#L15)):*
> ```Java
> import com.vaadin.v7.data.Property;
> import com.vaadin.v7.data.Property.ValueChangeEvent;
> import com.vaadin.v7.data.util.sqlcontainer.SQLContainer;
> ```

Isn't this supposed to be removed as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8091)*

**Comment by denis-anisimov** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/smoke/TableSqlContainer.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8091#-KZzot6JEIZnKjKTmh0m:-KZzpmZ6_OxREyfBwtpf:b-qwg70k) ([raw file](https://github.com/vaadin/framework/blob/366cd204652e290c85af112d6da7d7dd7786ad77/uitest/src/main/java/com/vaadin/tests/smoke/TableSqlContainer.java#L15)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Isn't this supposed to be removed as well?
</blockquote></details>

Imports section or this class as a whole ?

Imports are used because there are references in the code.

The class is used as only one smoke test for SQLContainer .

And I forgot to add a test class for it in the commit.......

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8091)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 13 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/smoke/TableSqlContainerTest.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/8091#-K_-fUmYpT_9tu6xTlLq:-K_-fUmYpT_9tu6xTlLr:b-idb22z) ([raw file](https://github.com/vaadin/framework/blob/72430cb62afb09ee7fe70db5436833c1b394d22b/uitest/src/test/java/com/vaadin/tests/smoke/TableSqlContainerTest.java#L31)):*
> ```Java
>  *
>  */
> @RunLocally(Browser.PHANTOMJS)
> ```

RunLocally!
Should be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8091#-:-KZzvXAt5tQT6jwOwIix:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/smoke/TableSqlContainerTest.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/8091#-K_-fUmYpT_9tu6xTlLq:-K_-iOs0BEfpRA7pkd1p:b-13srgl) ([raw file](https://github.com/vaadin/framework/blob/72430cb62afb09ee7fe70db5436833c1b394d22b/uitest/src/test/java/com/vaadin/tests/smoke/TableSqlContainerTest.java#L31)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

RunLocally!
Should be removed
</blockquote></details>

Already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8091)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8091)*

**Pull request merged**
