### PR TITLE
Update release notes and since tags for 8.4

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10760)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760#-:-L8b8rfVkZhga623Q31s:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8bI9CdIhg0nu6RddTf:-L8bI9CdIhg0nu6RddTg:bwsv6a8) (no related file):*
I'll update sinces to the same PR. There's also one new feature coming in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by elmot** [comment]
Reviewed 25 of 29 files at r2.
Review status: 25 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java, line 146 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_4EGxO7P4H0ovtqY:-L8b_4EHt3EpUnCZsmio:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java#L146)):*
> ```Java
>     /**
>      * Gets the content mode for the tooltip.
>      * 
> ```

extra space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by elmot** [comment]
Reviewed 6 of 29 files at r2.
Review status: 6 of 29 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_IyhNAgKV0ueD1fZ:-L8b_IyhNAgKV0ueD1f_:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L31)):*
> ```Java
>  * <p>
>  * Example:
>  * 
> ```

extra space

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 375 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_U7CydHZ2bMeM8Uv:-L8b_U7CydHZ2bMeM8Uw:b6bcy41) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L375)):*
> ```Java
>     /**
>      * Converts a temporal value into field-specific data type.
>      * 
> ```

Extra space

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 402 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8baIyvef7pfFVTcOWc:-L8baIyvef7pfFVTcOWd:b-l9n9kf) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L402)):*
> ```Java
>     /**
>      * Checks if {@code value} is after {@code base} or not
>      * 
> ```

extra space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by elmot** [comment]
Reviewed 23 of 29 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 31 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_IyhNAgKV0ueD1fZ:-L8bx9K6olnF4S1cLLqR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L31)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 375 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_U7CydHZ2bMeM8Uv:-L8bxQoyz1TvmxqIsRXL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L375)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra space
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 402 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8baIyvef7pfFVTcOWc:-L8bxR4GapKsdCjroPLJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L402)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java, line 146 at r2](https://reviewable.io:443/reviews/vaadin/framework/10760#-L8b_4EGxO7P4H0ovtqY:-L8bxbHgFgVJEB8qEzJT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/26fbc00eafa40532b73beffa689f595905144020/server/src/main/java/com/vaadin/ui/components/grid/FooterCell.java#L146)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10760)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10760)*

**Pull request merged**
