### PR TITLE
Pick XVFB cluster testing changes to 8.4 branch

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)

### CODE REVIEW

**Comment by elmot** [comment]
Looks like i

---

Reviewed 2 of 853 files at r1.
Review status: 2 of 1186 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[uitest/eclipse-run-selected-test.properties, line 15 at r6](https://reviewable.io/reviews/vaadin/framework/10902#-LBzVrCUD7kkRuKGr4WI:-LBzVrCUD7kkRuKGr4WJ:b-k10qpq) ([raw file](https://github.com/vaadin/framework/blob/86aa6c4b3b57d8fb8d90e0e9087abe93156ed85c/uitest/eclipse-run-selected-test.properties#L15)):*
> ```INI
> com.vaadin.testbench.screenshot.directory=<enter the full path to the screenshots directory, parent of "references" directory>
> 
> # Deployment url to use for testing. Context path must be /  
> ```

extra spaces

---

*[uitest/eclipse-run-selected-test.properties, line 20 at r6](https://reviewable.io/reviews/vaadin/framework/10902#-LBzVv4rCThFXND6Vxg8:-LBzVv4rCThFXND6Vxg9:bfdm5bn) ([raw file](https://github.com/vaadin/framework/blob/86aa6c4b3b57d8fb8d90e0e9087abe93156ed85c/uitest/eclipse-run-selected-test.properties#L20)):*
> ```
> ie8, ie9,
> ```
WUT?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902#-:-LBzR9NkAHURuIhrfgVY:bbjye9d)*

**Comment by tsuoanttila** [comment]
Review status: 2 of 1186 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/eclipse-run-selected-test.properties, line 15 at r6](https://reviewable.io/reviews/vaadin/framework/10902#-LBzVrCUD7kkRuKGr4WI:-LBzdq3059Qhg3bZ4CKP:b-pnhr4h) ([raw file](https://github.com/vaadin/framework/blob/86aa6c4b3b57d8fb8d90e0e9087abe93156ed85c/uitest/eclipse-run-selected-test.properties#L15)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

See below.

---

*[uitest/eclipse-run-selected-test.properties, line 20 at r6](https://reviewable.io/reviews/vaadin/framework/10902#-LBzVv4rCThFXND6Vxg8:-LBzdd1w8qWKv80jayA6:b-q8qm9h) ([raw file](https://github.com/vaadin/framework/blob/86aa6c4b3b57d8fb8d90e0e9087abe93156ed85c/uitest/eclipse-run-selected-test.properties#L20)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> ```
> ie8, ie9,
> ```
WUT?
</blockquote></details>

This file is not really relevant in the version branch. can update it for master.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
Reviewed 845 of 853 files at r1.
Review status: 833 of 1186 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
Reviewed 329 of 332 files at r2.
Review status: 1149 of 1186 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r4, 5 of 5 files at r5.
Review status: 1168 of 1186 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
Reviewed 16 of 16 files at r6.
Review status: 1184 of 1186 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10902#-:-LC325qW6T77dxLJqVod:bnfp4nl)*

**Pull request merged**
