### PR TITLE
add check for tab events trying to set focus outside a modal Window

### LINKED ISSUE #10654: Tabbing into page with a modal Window inconsistent
Issue occurs in 8.4-SNAPSHOT and all previous versions.

Unwanted behavior is seen in at least FF 58 and Chrome 64.0.3282.119 on Windows 10. The issue is also reproducible in the Vaadin Sampler with a modal Window.

Steps to reproduce:
1) Open an application with a modal Window and some focusable items below it. Make sure the modal Window is open.
2) Click the browser URL bar to select it
3) Keep pressing `tab`
Expected behavior:
Once the focus reaches the page itself instead of the browser's controls, the Modal window should receive the focus (as it shouldn't be possible to focus anything below the modality curtain)
Observed behavior:
In Chrome and Firefox, focus goes to focusable items below the modality curtain first. Once you reach the modal Window, everything works properly and you can't tab out of the window any longer

In IE and Edge, the modal Window correctly receives the focus first and you can't tab out of it (as expected)

Chrome just needs 3 tab key hits, FF needs 5 tab key hits.

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
fixes #10654

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10655)

### CODE REVIEW

**Comment by elmot** [comment]
LGTM but having any type of testing would be nice. Let's have a 2 day timebox for the automatic testing. If it does not happen, then let's accept that after some manual testing.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655#-:-L9A5-CO4gLPPHwFWfJB:bfxbpiz)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655)*

**Comment by elmot** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10655#-L9A5smx0hc3Ct3dF4YW:-L9A5smx0hc3Ct3dF4YX:b-1g0j5k) (no related file):*
Blocking comment until the testing is resolved.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655)*

**Comment by OlliTietavainenVaadin** [comment]
added test, needed to disable Chrome for since it doesn't support on clicking the modality curtain

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10655#-L9A5smx0hc3Ct3dF4YW:-L9cs43l1efzybtRCa_C:b619j8p) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Blocking comment until the testing is resolved.
</blockquote></details>

Some testing added

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655#-:-L9cs8DE6JPXptwaxGmO:b-amrp2z)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java, line 36 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10655#-L9jbO1uCta0XQEfP9x4:-L9jbO1uCta0XQEfP9x5:bxgl5nu) ([raw file](https://github.com/vaadin/framework/blob/f1ebd0acd6fbcce2f46d8b8a1c8c3b432b817d61/uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java#L36)):*
> ```Java
>     @Override
>     public List<DesiredCapabilities> getBrowsersToTest() {
>         // Chrome doesn't support clicking on the modality curtain
> ```

This disables chrome for all of test methods. It's better to have the same UI but two test classes, one for both browsers, another one without chrome.
This method might be handy for that:
`openTestURL(Class<?> uiClass, String... parameters)` 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java, line 36 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10655#-L9jbO1uCta0XQEfP9x4:-L9oIWf83AaovlbOWqK9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f1ebd0acd6fbcce2f46d8b8a1c8c3b432b817d61/uitest/src/test/java/com/vaadin/tests/components/window/ModalWindowFocusTest.java#L36)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

This disables chrome for all of test methods. It's better to have the same UI but two test classes, one for both browsers, another one without chrome.
This method might be handy for that:
`openTestURL(Class<?> uiClass, String... parameters)` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10655)*

**Pull request merged**
