### PR TITLE
Add Javadoc to the ScrollTo methods in TreeGrid

### PR DESCRIPTION
**Pull request by ZheSun88**
The current `scrollTo` methods don't make sense for TreeGrid, as it can scroll to any place with the same index based on the current Tree state.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11399)

### CODE REVIEW

**Comment by TatuLund** [comment]
___
*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 223 at r1](https://reviewable.io/reviews/vaadin/framework/11399#-LUo4mru1yizGhyJ9gta:-LUo4mru1yizGhyJ9gtb:b1andb6) ([raw file](https://github.com/vaadin/framework/blob/8b2a0aad047b402085428e3bd710614d5564c64c/server/src/main/java/com/vaadin/ui/TreeGrid.java#L223)):*
> ```Java
>     }
> 
>     /**
> ```

I think we should test scrollToEnd and scrrollToStart first, these may actually work correctly unlike scrollTo

**Review by TatuLund — COMMENTED** [review]
I added question about scrollToStart and scrollToEnd

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11399#-:-LUo5WwiAGqTA5cz5wC5:b-gl119l)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZheSun88 and @TatuLund)

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11399)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund and @ZheSun88)

___
*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 223 at r1](https://reviewable.io/reviews/vaadin/framework/11399#-LUo4mru1yizGhyJ9gta:-LUoXbePBBLeCQ7ruPp-:b-1hd6re) ([raw file](https://github.com/vaadin/framework/blob/8b2a0aad047b402085428e3bd710614d5564c64c/server/src/main/java/com/vaadin/ui/TreeGrid.java#L223)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

I think we should test scrollToEnd and scrrollToStart first, these may actually work correctly unlike scrollTo
</blockquote></details>

yes, you are correct. I have tested with those two methods, they work correctly.

**Review by TatuLund — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11399#-:-LUofDmP8HkAu0Ggiifn:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund and @ZheSun88)

**Review by TatuLund — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11399)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund)

**Review by TatuLund — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11399)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
