### PR TITLE
Add ValueProvider interface, use where appropriate

### PR DESCRIPTION
**Pull request by ahie**
Closes vaadin/framework8-issues#562

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7987)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 10 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/ValueProvider.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/7987#-KYxDLmtM5euwVrj7Snj:-KYxDLmuR_rbOqwWVroO:bxkm886) ([raw file](https://github.com/vaadin/framework/blob/b83ec525675353a49925c5e673f84c290343e0e5/server/src/main/java/com/vaadin/data/ValueProvider.java#L27)):*
> ```Java
>  *
>  * @param <SOURCE>
>  *            the type of the provider of the value
> ```

I find this rather parameter type description unambiguous and unclear - should reformulate

---

*[server/src/main/java/com/vaadin/data/ValueProvider.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/7987#-KYxDcPAmD30Z10tXJiP:-KYxDcPAmD30Z10tXJiQ:bne4d7a) ([raw file](https://github.com/vaadin/framework/blob/b83ec525675353a49925c5e673f84c290343e0e5/server/src/main/java/com/vaadin/data/ValueProvider.java#L46)):*
> ```Java
> 
>     /**
>      * Provides a value from a given source.
> ```

I wonder if "from" gives too restrictive a view, and the javadoc feels a bit ambiguous. Not sure whether the best way to fix this would be an example or two ("e.g. extracting the value of a field with a getter, or creating a composite value based on the fields of the source bean") or something else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7987)*

**Comment by ahie** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/data/ValueProvider.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/7987#-KYxDLmtM5euwVrj7Snj:-KYxjpAqsoLqYk9bkAlq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b83ec525675353a49925c5e673f84c290343e0e5/server/src/main/java/com/vaadin/data/ValueProvider.java#L27)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I find this rather parameter type description unambiguous and unclear - should reformulate
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ValueProvider.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/framework/7987#-KYxDcPAmD30Z10tXJiP:-KYxjdz6jhUPz81kFgHD:b688ur9) ([raw file](https://github.com/vaadin/framework/blob/b83ec525675353a49925c5e673f84c290343e0e5/server/src/main/java/com/vaadin/data/ValueProvider.java#L46)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I wonder if "from" gives too restrictive a view, and the javadoc feels a bit ambiguous. Not sure whether the best way to fix this would be an example or two ("e.g. extracting the value of a field with a getter, or creating a composite value based on the fields of the source bean") or something else.
</blockquote></details>

Decided to use the given examples in the interface level javadoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7987)*

**Comment by hesara** [comment]
:lgtm: - good enough javadoc for now

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7987#-:-KYxkQ5xDSx4DvCntziE:btns37q)*

**Comment by hesara** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1004 at r4](https://reviewable.io:443/reviews/vaadin/framework/7987#-KZ0bVXaXDUijJfpUQN4:-KZ0bVXaXDUijJfpUQN5:bqy5ug) ([raw file](https://github.com/vaadin/framework/blob/43f66f1eafe2305ba1b5ceab382d6313f25a4bac/server/src/main/java/com/vaadin/ui/Grid.java#L1004)):*
> ```Java
>          *            the header caption
>          * @param valueProvider
>          *            the function to get values from items
> ```

(other locations just say "the value provider" but IMO not a blocker - this one is in some ways even clearer)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7987)*

**Pull request merged**
