### PR TITLE
Add option to use error message provider for StringTo converters

### LINKED ISSUE #8809: Allow Converters to have error message provider
Right now it's possible to define various Converters such as StringToBigDecimalConverter which all have conversion error message String as their constructor parameter. In some cases where I18N is used, it would be more beneficial to allow using error message supplier or Supplier<String> as additional value.

This way the converter could ask for translated error message from whatever provider instance.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #8809

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10711)

### CODE REVIEW

**Comment by elmot** [comment]
No tests

---

Reviewed 8 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjLFpGxVzyfLR3urc:-L7UjLFqDJNcq-lz_M8z:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java#L55)):*
> ```Java
>      * @param errorMessageProvider
>      *            the error message provider to use if conversion fails
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToBigDecimalConverter.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjdzC5FkGf_yNLShs:-L7UjdzC5FkGf_yNLSht:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBigDecimalConverter.java#L80)):*
> ```Java
>      * @param errorMessageProvider
>      *            the error message provider to use if conversion fails
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjnINsajZVIVk526D:-L7UjnINsajZVIVk526E:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java#L80)):*
> ```Java
>      * @param errorMessageProvider
>      *            the error message provider to use if conversion fails
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToBooleanConverter.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk3FinMaGwVVT1XlX:-L7Uk3FinMaGwVVT1XlY:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBooleanConverter.java#L86)):*
> ```Java
>      * @param errorMessageProvider
>      *            the error message provider to use if conversion fails
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToDoubleConverter.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk5GEvX3mrHHcMKVR:-L7Uk5GEvX3mrHHcMKVS:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToDoubleConverter.java#L78)):*
> ```Java
>      *            the error message provider to use if conversion fails
>      */
>     public StringToDoubleConverter(Double emptyValue,
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToFloatConverter.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk9CyvwoM2kSSBrtP:-L7Uk9CyvwoM2kSSBrtQ:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToFloatConverter.java#L75)):*
> ```Java
>      * @param errorMessageProvider
>      *            the error message provider to use if conversion fails
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToIntegerConverter.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UkDM1oMqZHln60hej:-L7UkDM1oMqZHln60hek:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToIntegerConverter.java#L77)):*
> ```Java
>     public StringToIntegerConverter(Integer emptyValue,
>             SerializableFunction<ValueContext, String> errorMessageProvider) {
>         super(emptyValue, errorMessageProvider);
> ```

`@since`

---

*[server/src/main/java/com/vaadin/data/converter/StringToLongConverter.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UkGVvif3HG1zWlM7J:-L7UkGVvif3HG1zWlM7K:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToLongConverter.java#L75)):*
> ```Java
>      *            the error message provider to use if conversion fails
>      */
>     public StringToLongConverter(Long emptyValue,
> ```

`@since`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10711#-:-L7UkOxRvRbfT_ToqG_7:bnvkqp3)*

**Comment by elmot** [comment]
Missing `@since`s, missing a minimal test, otherwise LGTM

---

Reviewed 4 of 8 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjnINsajZVIVk526D:-L7eYyRt6SntvosC4BTL:b-np2hwo) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java#L80)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

still no since

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10711#-:-L7eZ_Hc-FYGwgxAIkrd:byfadc)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjLFpGxVzyfLR3urc:-L7eq_qjdzuTG8hEOm9x:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/AbstractStringToNumberConverter.java#L55)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToBigDecimalConverter.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjdzC5FkGf_yNLShs:-L7eqaomWMUGpqqKzphx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBigDecimalConverter.java#L80)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UjnINsajZVIVk526D:-L7eqc6ZQuWZfcj9DXwq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBigIntegerConverter.java#L80)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

still no since
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToBooleanConverter.java, line 86 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk3FinMaGwVVT1XlX:-L7eqcvrAp8hLXau_lSN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToBooleanConverter.java#L86)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToDoubleConverter.java, line 78 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk5GEvX3mrHHcMKVR:-L7eqdf1ofHiLKYXbD4Q:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToDoubleConverter.java#L78)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToFloatConverter.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7Uk9CyvwoM2kSSBrtP:-L7eqeRB4TmMXOnHVKuE:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToFloatConverter.java#L75)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToIntegerConverter.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UkDM1oMqZHln60hej:-L7eqf7eCTi8FlmiU2K3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToIntegerConverter.java#L77)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/converter/StringToLongConverter.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/framework/10711#-L7UkGVvif3HG1zWlM7J:-L7eqfbhU2PR14JN9gGp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e09140e899f97b6e274cfbec967f42862fb9c442/server/src/main/java/com/vaadin/data/converter/StringToLongConverter.java#L75)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10711)*

**Comment by elmot** [comment]
Reviewed 8 of 9 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10711)*

**Pull request merged**
