### PR TITLE
Support bundling all HTML imports into one HTML bundle

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9084)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 5 of 8 files at r1, 4 of 5 files at r2.
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 106 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0Lr86Byl02hQnx_Xn:-Ki0Lr86Byl02hQnx_Xo:buktcwu) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L106)):*
> ```Java
>         if (!(vaadinService instanceof VaadinServletService)) {
>             // Must define bundle in portals
>             return definedBundleName;
> ```

why not `return null`? It looks like `definedBundleName` is always null here.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 110 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0KxJ_fywrFVaS5Lkm:-Ki0KxJalwbTbd9saKiU:b-xhg0uw) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L110)):*
> ```Java
>         String defaultBundleFilename = BootstrapHandler
>                 .resolveFrontendUrl(session).replace("vaadin://", "/VAADIN/")
>                 + "bundle.html";
> ```

Might have conflicts with OSGi support.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9084)*

**Comment by Artur-** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 106 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0Lr86Byl02hQnx_Xn:-KiUP2sXt7i-cQ3JDti0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L106)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

why not `return null`? It looks like `definedBundleName` is always null here.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 110 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0KxJ_fywrFVaS5Lkm:-KiUP3N8xj_6gXt_HRz_:bofqht7) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L110)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Might have conflicts with OSGi support.
</blockquote></details>

What conflicts? This is not using the classloader?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9084)*

**Comment by elmot** [comment]
Reviewed 1 of 8 files at r1, 3 of 4 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 110 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0KxJ_fywrFVaS5Lkm:-KiVKBowgyDNr_I08BPv:b-mjcf5j) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L110)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

What conflicts? This is not using the classloader?
</blockquote></details>

There was something related to changing "/VAADIN/" prefix, but I don't know all the details, it's better to ask @hesara or @mmerruko 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9084)*

**Comment by elmot** [comment]
Reviewed 1 of 8 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9084)*

**Comment by Artur-** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/HtmlBundleHandler.java, line 110 at r2](https://reviewable.io:443/reviews/vaadin/framework/9084#-Ki0KxJ_fywrFVaS5Lkm:-Ki_8t_UJbF3aUTV7sGa:b-xoewj7) ([raw file](https://github.com/vaadin/framework/blob/ed2718ae69bb6dda50437f3719ce08078163fb09/server/src/main/java/com/vaadin/server/HtmlBundleHandler.java#L110)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

There was something related to changing "/VAADIN/" prefix, but I don't know all the details, it's better to ask @hesara or @mmerruko 
</blockquote></details>

Added a comment on why this should not matter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9084)*

**Pull request closed without merging**
