### PR TITLE
Add .gitattribute, to automatically handle text files end-of-line

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10052)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitattribute, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10052#-KuYKO4VKDMho-Hj2YV0:-KuYKO4VKDMho-Hj2YV1:b-3zhybr) ([raw file](https://github.com/vaadin/framework/blob/d9114fc50d0feffee248ae2624c9b54aa497bda3/.gitattribute#L2)):*
> ```
> # the default behavior
> * text=auto
> ```

AFAIK whether this matches the old default or not depends on the core.autocrlf setting for those who make a checkout. I'm wondering if this can cause some complications for the more unusual file formats in the repository.

I tried to go through the files with CRs in my checkout of the repository (on MacOS), and most of the files look such that even converting them would be safe (svg, md, txt, java, xml) and should be done. What I'm a bit unsure about, though, is a graffle file under documentation, which git would detect as text but which has CRs.

If you know that converting line endings in a graffle file is ok, I think we can merge this as-is. Otherwise, I'd add at least that as an exclusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Comment by asashour** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitattribute, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10052#-KuYKO4VKDMho-Hj2YV0:-KuYU3kbOSDX2uIo0IA_:bfk74g7) ([raw file](https://github.com/vaadin/framework/blob/d9114fc50d0feffee248ae2624c9b54aa497bda3/.gitattribute#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

AFAIK whether this matches the old default or not depends on the core.autocrlf setting for those who make a checkout. I'm wondering if this can cause some complications for the more unusual file formats in the repository.

I tried to go through the files with CRs in my checkout of the repository (on MacOS), and most of the files look such that even converting them would be safe (svg, md, txt, java, xml) and should be done. What I'm a bit unsure about, though, is a graffle file under documentation, which git would detect as text but which has CRs.

If you know that converting line endings in a graffle file is ok, I think we can merge this as-is. Otherwise, I'd add at least that as an exclusion.
</blockquote></details>

This is the recommended way as hinted in the [documentation](https://help.github.com/articles/dealing-with-line-endings/#example).

Other text files has been added, including `.graffle`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitattribute, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10052#-KuYKO4VKDMho-Hj2YV0:-KuYd2kYG3OofdxnxXhq:bj2tnpp) ([raw file](https://github.com/vaadin/framework/blob/d9114fc50d0feffee248ae2624c9b54aa497bda3/.gitattribute#L2)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

This is the recommended way as hinted in the [documentation](https://help.github.com/articles/dealing-with-line-endings/#example).

Other text files has been added, including `.graffle`
</blockquote></details>

My question was really about whether graffle files should be treated as text even though they look like such. I'll try to check with some colleagues who have OmniGraffle.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitattribute, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10052#-KuYKO4VKDMho-Hj2YV0:-Ku_AnY0_1YvEizEPY1_:ba0b404) ([raw file](https://github.com/vaadin/framework/blob/d9114fc50d0feffee248ae2624c9b54aa497bda3/.gitattribute#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

My question was really about whether graffle files should be treated as text even though they look like such. I'll try to check with some colleagues who have OmniGraffle.
</blockquote></details>

My colleague who made the file doesn't have the time to check right now, so I'd suggest marking the graffle file as binary for now just in case not to break it, maybe with a comment to check the correct mode later. That should at least be safe and allow us to move forward with the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Comment by asashour** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitattribute, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10052#-KuYKO4VKDMho-Hj2YV0:-Ku_E6SeKYBXZDP6PU9a:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d9114fc50d0feffee248ae2624c9b54aa497bda3/.gitattribute#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

My colleague who made the file doesn't have the time to check right now, so I'd suggest marking the graffle file as binary for now just in case not to break it, maybe with a comment to check the correct mode later. That should at least be safe and allow us to move forward with the PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10052)*

**Pull request merged**
