### PR TITLE
Revert 'Rewrote debouncing of onResize (#11899)'

### LINKED ISSUE #12049: Grid onResize not updating Horizontal scroll position if hz-scroller not needed
In a customer project it became apparent that there is a size recalculation bug with the V8 Grid where the horizontal scroll position isn't properly updated in the case where the grid goes from "needing a scrollbar" to "not needing a scrollbar" when a component for instance is removed from a layout. 

Weirdly enough, this seems to happen with Chrome only, customer reports that this is not reproducible in IE, Firefox nor Safari, FF verified locally as well as working fine. 

Steps to reproduce: 
1) Download the example application and run it
2) Using Chrome, navigate to the application
3) Resize the browser window so that the grid doesn't have a horizontal scrollbar (for instance body element width 1687px on my system)
4) Click the "Toggle component" button
5) Scroll the grid all the way to the right (this step is critical for reproducing the issue)
6) Click on the "Toggle component" button again

Expected: 
- The grid should resize and render as it did before with all columns visible

Observed: 
- The grid doesn't update the horizontal scroll position correctly as the component is removed, leaving some columns hidden, while there is empty space to the right of the grid. 
- Scrolling the grid vertically will immediately "fix" the rendering

Tested with: 
- Vaadin 8.11.0 and 8.11.1
- Chrome: 
     * OS X: Version 83.0.4103.61 (Official Build) (64-bit)
     * Windows: Version 83.0.4103.61 (Official Build) (64-bit)

[playground-app.zip](https://github.com/vaadin/framework/files/4884314/playground-app.zip)
1-Initial
2-AddComponent_and_scroll
3-Grid-not-showing-all

### PR DESCRIPTION
**Pull request by Ansku**
Fixes #12049

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/12051)

### CODE REVIEW

**Review by edler-san — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12051)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Ansku)

___
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridScrolledResize.java, line 15 at r1](https://reviewable.io/reviews/vaadin/framework/12051#-MBmxS6r-zy7xeqebjcH:-MBmxS6r-zy7xeqebjcI:b-hgbi3a) ([raw file](https://github.com/vaadin/framework/blob/de09cb7e9ad7c628a4fd50310b2e37e19c1c67cc/uitest/src/main/java/com/vaadin/tests/components/grid/GridScrolledResize.java#L15)):*
> ```Java
> public class GridScrolledResize extends AbstractTestUI {
> 
>     Label spaceGrabber;
> ```

Not sure if this needs to be an instance variable. If so, please make it private.

**Review by edler-san — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12051)* status: all files reviewed, 1 unresolved discussion (waiting on @Ansku)

**Comment by Ansku** [comment]
___
*[uitest/src/main/java/com/vaadin/tests/components/grid/GridScrolledResize.java, line 15 at r1](https://reviewable.io/reviews/vaadin/framework/12051#-MBmxS6r-zy7xeqebjcH:-MBn3RvjER4MeokvhPJW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/de09cb7e9ad7c628a4fd50310b2e37e19c1c67cc/uitest/src/main/java/com/vaadin/tests/components/grid/GridScrolledResize.java#L15)):*
<details><summary><i>Previously, edler-san wrote…</i></summary><blockquote>

Not sure if this needs to be an instance variable. If so, please make it private.
</blockquote></details>

Done.

**Review by edler-san — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/12051)* status: all files reviewed, 1 unresolved discussion (waiting on @edler-san)

**Pull request merged**
