### PR TITLE
Move old Sort related classes into compatibility module.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#563

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7999)

### CODE REVIEW

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7999#-:-KZ0t_c5GDMCMcJWMSqa:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/sort/Sort.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/7999#-KZ1BQEXQzd4oElXMPqz:-KZ1BQEXQzd4oElXMPr-:b2596um) ([raw file](https://github.com/vaadin/framework/blob/800ea7c4bf1f3f281b0c9984635d5d01b31e5849/compatibility-server/src/main/java/com/vaadin/v7/data/sort/Sort.java#L31)):*
> ```Java
>  * @author Vaadin Ltd
>  */
> public class Sort implements Serializable {
> ```

@Deprecated

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/sort/SortOrder.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/7999#-KZ1BT--3IkamWn1QJK5:-KZ1BT--3IkamWn1QJK6:b2596um) ([raw file](https://github.com/vaadin/framework/blob/800ea7c4bf1f3f281b0c9984635d5d01b31e5849/compatibility-server/src/main/java/com/vaadin/v7/data/sort/SortOrder.java#L29)):*
> ```Java
>  * @author Vaadin Ltd
>  */
> public class SortOrder implements Serializable {
> ```

@Deprecated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7999)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/sort/Sort.java, line 31 at r1](https://reviewable.io:443/reviews/vaadin/framework/7999#-KZ1BQEXQzd4oElXMPqz:-KZ1_ZjsK5duPfveucId:ba61ru2) ([raw file](https://github.com/vaadin/framework/blob/800ea7c4bf1f3f281b0c9984635d5d01b31e5849/compatibility-server/src/main/java/com/vaadin/v7/data/sort/Sort.java#L31)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@Deprecated
</blockquote></details>

Of course.
Thanks.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/sort/SortOrder.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/7999#-KZ1BT--3IkamWn1QJK5:-KZ1_bmFg2Owj-x9EyH2:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/800ea7c4bf1f3f281b0c9984635d5d01b31e5849/compatibility-server/src/main/java/com/vaadin/v7/data/sort/SortOrder.java#L29)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@Deprecated
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7999)*

**Comment by tsuoanttila** [comment]
Reviewed 10 of 15 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7999)*

**Pull request merged**
