### PR TITLE
Update release notes for 8.0.0.beta2

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8402)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaMLQZRmvXoH7u4iT:-KbsaMLQZRmvXoH7u4iU:blvcwtj) (no related file):*
Not sure about mentioning of memory required to compile client-compatibility (flowdock discussion).
Also there are changes comparing to beta1 regarding Filtering API.
I'm not sure whether this should be mentioned somehow.

---

*[all/src/main/templates/release-notes.html, line 210 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbsa9aSPWJ-ZcPfr6rt:-Kbsa9aSPWJ-ZcPfr6ru:b-tqb7o1) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L210)):*
> ```HTML
>             <li><tt>ComboBox</tt></li>
>             <li><tt>CustomField</tt></li>
>             <li><tt>DateField</tt> - replaced in 8 by <tt>DataTimeField</tt></li>
> ```

I would say it's not replaced. But now there are two classes to use depending on whether time is needed or not.

---

*[all/src/main/templates/release-notes.html, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaIxMV32NbCyx_TRy:-KbsaIxMV32NbCyx_TRz:brhumzt) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L214)):*
> ```HTML
>             <li><tt>Grid</tt> (and renderers)</li>
>             <li><tt>HorizontalLayout</tt></li>
>             <li><tt>InlineDateField</tt> - replaced in 8 by <tt>InlineDateTimeField</tt></li>
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaMLQZRmvXoH7u4iT:-Kbsm_FXDWDnyjbHVU_n:b-ny1n4t) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Not sure about mentioning of memory required to compile client-compatibility (flowdock discussion).
Also there are changes comparing to beta1 regarding Filtering API.
I'm not sure whether this should be mentioned somehow.
</blockquote></details>

Yes, the memory usage problem could be mentioned in the "Known Issues and Limitations" section.

I'm not sure about mentioning changes between betas in these release notes. My hunch is that these release notes should list the changes compared to FW 7, and then the release notes in github would list changes compared to the previous beta.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbsm16vbY2zWsUX6sie:-Kbsm16wfcRYZdnBh4FF:bjzkcle) (no related file):*
Should mention that `Label.ContentMode` has been moved

---

*[all/src/main/templates/release-notes.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbslqC7kcoSLZKBkxNQ:-KbslqC7kcoSLZKBkxNR:b-4fwdp) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L68)):*
> ```HTML
>                 href="#changelog">change log</a> below.
> 		This beta release contains breaking changes based on your feedback on the previous beta version,
> 		and we will change things on future beta versions based on your feedback if necessary.
> ```

will change -> may change

---

*[all/src/main/templates/release-notes.html, line 210 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbsa9aSPWJ-ZcPfr6rt:-KbsmK8ODC_ewrTcApDY:b-yp9te6) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L210)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I would say it's not replaced. But now there are two classes to use depending on whether time is needed or not.
</blockquote></details>

I'd say it's replaced by `DateField` + `DateTimeField`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaMLQZRmvXoH7u4iT:-KbtgnRIYRnJsRdCsOWv:baqwi7k) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Yes, the memory usage problem could be mentioned in the "Known Issues and Limitations" section.

I'm not sure about mentioning changes between betas in these release notes. My hunch is that these release notes should list the changes compared to FW 7, and then the release notes in github would list changes compared to the previous beta.
</blockquote></details>

That is how it is now, this is for previous Major versions, not between betas. Github relese notes have details on what has changed since beta2

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbsm16vbY2zWsUX6sie:-KbtiJZYkT1oiesEBti6:bb6un1j) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Should mention that `Label.ContentMode` has been moved
</blockquote></details>

Done

---

*[all/src/main/templates/release-notes.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbslqC7kcoSLZKBkxNQ:-KbtiPRx2ZdDSgZTkN-S:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L68)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

will change -> may change
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 210 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbsa9aSPWJ-ZcPfr6rt:-Kbtip0ybb6V4oD6CQ73:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L210)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I'd say it's replaced by `DateField` + `DateTimeField`
</blockquote></details>

Done.

---

*[all/src/main/templates/release-notes.html, line 214 at r1](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaIxMV32NbCyx_TRy:-Kbtiokuv3L6Z863kxXM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad0ff5f2506ede07db7a8bcea5e1b15e775b9505/all/src/main/templates/release-notes.html#L214)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaMLQZRmvXoH7u4iT:-Kbtki8gLvPLFloVHk77:bb1wbp) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

That is how it is now, this is for previous Major versions, not between betas. Github relese notes have details on what has changed since beta2
</blockquote></details>

What about the memory issue with GWT compilation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8402#-KbsaMLQZRmvXoH7u4iT:-KbtlGLEDq_7Kw7ezXqR:b-x7q13z) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

What about the memory issue with GWT compilation?
</blockquote></details>

doh forgot, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[all/src/main/templates/release-notes.html, line 157 at r3](https://reviewable.io:443/reviews/vaadin/framework/8402#-Kbu2O-tfww1w5aucKK1:-Kbu2O-tfww1w5aucKK2:bkdvd19) ([raw file](https://github.com/vaadin/framework/blob/6d408ca89c4feee89364b27889e52a699d236698/all/src/main/templates/release-notes.html#L157)):*
> ```HTML
>             <li><tt>SharedState</tt> and the getter methods for it have been added to each component, regardless of whether those are used for anything or not</li>
>             <li>The old liferay theme (Liferay 6.0 look) has been removed</li>
>             <li>FontAwesome icon constants have been deprecated, and will not be updated. It will be replaced with <a href="https://vaadin.com/icons">Vaadin icons</a> in an upcoming beta</li>
> ```

this might not be true if vaadin icons patch is merged, but can be updated in that patch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8402)*

**Pull request merged**
