### PR TITLE
Fix performance issue in Grid initial render with Footer

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10705)

### CODE REVIEW

**Comment by TatuLund** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10705#-:-L7TF-qWkOdEZ6Fnn9RY:bnfp4nl)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridManyColumns.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10705#-L7TgOXDBCz68jZx3NL0:-L7TgOXE-jfiCUZhP4xu:bpn28ts) ([raw file](https://github.com/vaadin/framework/blob/dc9b51109473e6cfad681722010e38b74987029d/uitest/src/main/java/com/vaadin/tests/components/grid/GridManyColumns.java#L25)):*
> ```Java
>         }
>         grid.setItems(IntStream.range(0, 10).boxed().map(i -> ""));
>         grid.appendFooterRow();
> ```

How does it work if there is no footer rows? 
How does it work if there are more than one footer rows? 

Looks like this line should have a comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10705)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridManyColumns.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/10705#-L7TgOXDBCz68jZx3NL0:-L7TkT8Nbr7QxBN0rwxa:b-4l2770) ([raw file](https://github.com/vaadin/framework/blob/dc9b51109473e6cfad681722010e38b74987029d/uitest/src/main/java/com/vaadin/tests/components/grid/GridManyColumns.java#L25)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

How does it work if there is no footer rows? 
How does it work if there are more than one footer rows? 

Looks like this line should have a comment. 
</blockquote></details>

This test UI is used to render and report the rendering times for TeamCity tracking. The Footer is not used for anything, the UI itself is not used for anything other than render and report spent time. 

I don't personally really care wether the footer is there or not, I'm not sure if these statistics are being gathered from the validation builds (most likely should be). It should be there as it displayed a pretty huge factor in this case (increasing the rendering time by about 18 seconds), but not really mandatory.

Should I remove it or keep it? How should I comment it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10705)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10705#-:-L7UCnXOVx6Pki2nB0Vp:bnfp4nl)*

**Pull request merged**
