### PR TITLE
Remove unneeded .toString()

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10141)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 75 of 75 files at r1.
Review status: 74 of 75 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw--tw1laua0ryX-ui6:-Kw--tw1laua0ryX-ui7:b-tvxt8f) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java#L136)):*
> ```Java
>             s.append(':');
>             Object value = getItemProperty(propId).getValue();
>             s.append(value);
> ```

(This will be correct as value is of type Object, but would lead to an NPE if value would be of type String.)

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 707 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-42H8d32lIbycH431:-Kw-42H8d32lIbycH432:b-8yyihs) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/server/src/main/java/com/vaadin/ui/ComboBox.java#L707)):*
> ```Java
>     private void updateSelectedItemCaption() {
>         String selectedCaption = null;
>         T value = keyToItem(getSelectedKey());
> ```

(Not really the same change as the others, but ok.)

---

*[uitest/src/main/java/com/vaadin/tests/components/table/ColumnReorderEvent.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-0uRKzKxdvstyJ8wh:-Kw-0uRKzKxdvstyJ8wi:bicwcyc) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/uitest/src/main/java/com/vaadin/tests/components/table/ColumnReorderEvent.java#L37)):*
> ```Java
>         StringBuilder sb = new StringBuilder();
>         for (Object object : visibleColumns) {
>             sb.append(object);
> ```

(Technically this changes the behavior as StringBuilder.append(Object) behaves differently from StringBuilder.append(String) for the same data, but here the change is safe assuming the old code was correct.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141#-:-Kw-4DHi9D7Um0cITow-:bnfp4nl)*

**Comment by hesara** [comment]
Review status: 74 of 75 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6317 at r2](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-4hNpQPF_8InroTX0:-Kw-4hNpQPF_8InroTX1:b-yza0td) ([raw file](https://github.com/vaadin/framework/blob/2e103049fb222abb6a40008ed7ec002f4dfa5a65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6317)):*
> ```Java
>     }
> 
>     // @formatter:off
> ```

Rather than using the formatter control comments, the code below should use &lt; and &gt; .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6317 at r2](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-4hNpQPF_8InroTX0:-Kw-4tZ-eGHlJ6ejANuS:botl8mg) ([raw file](https://github.com/vaadin/framework/blob/2e103049fb222abb6a40008ed7ec002f4dfa5a65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6317)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Rather than using the formatter control comments, the code below should use &lt; and &gt; .
</blockquote></details>

Apparently GitHub formatted these, so I mean `&lt;` and `&gt;` (ampersand lt semicolon and ampersand gt semicolon).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6317 at r2](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-4hNpQPF_8InroTX0:-Kw-JUezIImTItRJcimj:bub00ir) ([raw file](https://github.com/vaadin/framework/blob/2e103049fb222abb6a40008ed7ec002f4dfa5a65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6317)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Apparently GitHub formatted these, so I mean `&lt;` and `&gt;` (ampersand lt semicolon and ampersand gt semicolon).
</blockquote></details>

Well, in Eclipse it would be seen  as "`the &lt;table /&gt; element `", there are other places in the javadoc which uses `<` inside `@code`, and I guess they should be investigated/handled in another PR.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw--tw1laua0ryX-ui6:-Kw-K90DE6E03ohxU1MD:bu9ib4n) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java#L136)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(This will be correct as value is of type Object, but would lead to an NPE if value would be of type String.)
</blockquote></details>

No. `StringBuffer.append(Object)` calls `String.valueOf(obj)`, which is:

    public static String valueOf(Object obj) {
        return (obj == null) ? "null" : obj.toString();
    }

So, null value is treated as "null"

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 707 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-42H8d32lIbycH431:-Kw-KXcXTIE2Iv-e7I9D:b9vpz60) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/server/src/main/java/com/vaadin/ui/ComboBox.java#L707)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Not really the same change as the others, but ok.)
</blockquote></details>

You are right, I thought about another PR, but there were only two instances in the project (both in this file).

---

*[uitest/src/main/java/com/vaadin/tests/components/table/ColumnReorderEvent.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-0uRKzKxdvstyJ8wh:-Kw-Kp3FsCYV2WZ2Tvod:bw2lv8t) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/uitest/src/main/java/com/vaadin/tests/components/table/ColumnReorderEvent.java#L37)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Technically this changes the behavior as StringBuilder.append(Object) behaves differently from StringBuilder.append(String) for the same data, but here the change is safe assuming the old code was correct.)
</blockquote></details>

I would say, the old way can give NPE, but the new way handles it as "null", other than this, I believe `string.toString()`is the same as `String.valueOf(obj)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6317 at r2](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-4hNpQPF_8InroTX0:-Kw3hbkp87HAaCKTFoCQ:bubiyjs) ([raw file](https://github.com/vaadin/framework/blob/2e103049fb222abb6a40008ed7ec002f4dfa5a65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6317)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Well, in Eclipse it would be seen  as "`the &lt;table /&gt; element `", there are other places in the javadoc which uses `<` inside `@code`, and I guess they should be investigated/handled in another PR.
</blockquote></details>

Perhaps it would be best to separate this change from the rest to get everything else merged, and discuss this issue in a separate PR or other context.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw--tw1laua0ryX-ui6:-Kw3gmutnT3y50keWw4w:b2zjjqu) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java#L136)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

No. `StringBuffer.append(Object)` calls `String.valueOf(obj)`, which is:

    public static String valueOf(Object obj) {
        return (obj == null) ? "null" : obj.toString();
    }

So, null value is treated as "null"

</blockquote></details>

That is what I meant - if the declared type of the value would have been String, SB.append() would not call String.valueOf() but would throw an NPE. However, this particular change is safe because value is of the declared type Object.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141)*

**Comment by asashour** [comment]
Review status: 74 of 75 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6317 at r2](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw-4hNpQPF_8InroTX0:-Kw4U6F739jFBBYG8LOD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2e103049fb222abb6a40008ed7ec002f4dfa5a65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6317)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Perhaps it would be best to separate this change from the rest to get everything else merged, and discuss this issue in a separate PR or other context.
</blockquote></details>

Done.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java, line 136 at r1](https://reviewable.io:443/reviews/vaadin/framework/10141#-Kw--tw1laua0ryX-ui6:-Kw4UTsYwX7JSYeR06ah:b-mv415) ([raw file](https://github.com/vaadin/framework/blob/ec053f5f7249ec54cc83f87927e3da325a317f50/compatibility-server/src/main/java/com/vaadin/v7/data/util/sqlcontainer/RowItem.java#L136)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

That is what I meant - if the declared type of the value would have been String, SB.append() would not call String.valueOf() but would throw an NPE. However, this particular change is safe because value is of the declared type Object.
</blockquote></details>

If the declared type of the value is String and value is null, then SB.append(String), would call AbstractStringBuilder, and it will gracefully handle null as "null".

    public AbstractStringBuilder append(String str) {
        if (str == null)
            return appendNull();
        int len = str.length();
        ensureCapacityInternal(count + len);
        str.getChars(0, len, value, count);
        count += len;
        return this;
    }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10141#-:-Kw4iYSCJ2SmGt4RpzRv:bnfp4nl)*

**Pull request merged**
