### PR TITLE
Fix for Grid declarative format (read).

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#576

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8050)

### CODE REVIEW

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8050#-:-KZMaBNfELS6oC5bpS09:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/8050#-KZMa6WXpwbVsQisjE-k:-KZMa6WXpwbVsQisjE-l:b-xtzf9a) ([raw file](https://github.com/vaadin/framework/blob/50be70d0829c92df39f84566be16f759526be33d/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L269)):*
> ```Java
> 
>         Grid<?> readGrid = testRead(design, grid, true, true);
>         Assert.assertEquals(2, readGrid.getDataProvider().size(new Query<>()));
> ```

this doesn't test that the items have any content - I guess at least one line would be good to check but not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8050)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/8050#-KZMa6WXpwbVsQisjE-k:-KZMaWYQnSS4owG2oJCg:btd8vb) ([raw file](https://github.com/vaadin/framework/blob/50be70d0829c92df39f84566be16f759526be33d/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L269)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this doesn't test that the items have any content - I guess at least one line would be good to check but not a blocker
</blockquote></details>

Items are fake ones.

The item is some string that has no any relation to the data in the grid ( shown, visible text).

You are right: this doesn't test the items themselves ( no need for this) AND it doesn't test what data that is shown in the Grid.

But a line above does that: it deserialize the text, then it writes the result back to declarative and check that the content is the same.

So in reality the test works as expected ( because of two additional boolean parameters).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8050)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8050#-KZMmi7rVaT1L7aLwvpD:-KZMmi7rVaT1L7aLwvpE:bg7jec8) (no related file):*
Change freeze, this patch is going to be merged after beta

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8050)*

**Pull request merged**
