### PR TITLE
Fix for pull request #9932 logic.

### PR DESCRIPTION
**Pull request by pwilkin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10002)

### CODE REVIEW

**Comment by pwilkin** [comment]
Fixes logic in #9932

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-VddwzR5vWhPePD3C:-Ku-VddwzR5vWhPePD3D:b-dyli3w) (no related file):*
I was just making the same change in my workspace. Please tend to my comments about how to make sure the clean up is done the same way always.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-UrVY6WmUrZVS3Fnq:-Ku-UrVZP_NDCe6y_srY:bpvfbwd) ([raw file](https://github.com/vaadin/framework/blob/4e720f6b2b48d99b6abe615fa26f399c47122e17/server/src/main/java/com/vaadin/data/Binder.java#L18)):*
> ```Java
> package com.vaadin.data;
> 
> import java.io.Serializable;
> ```

Try to avoid changing the order of the imports. There are coding conventions and clean up rules for Eclipse in the vaadin project (in folder eclipse/) that you can import to make the formatting work the same way.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 826 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-V8FM0hy3w5GO4dSI:-Ku-V8FM0hy3w5GO4dSJ:b-y8dknf) ([raw file](https://github.com/vaadin/framework/blob/bb184c3c7784ec8221bcf32ae25284a57cbfd47f/server/src/main/java/com/vaadin/data/Binder.java#L826)):*
> ```Java
> 
>         @Override
>         public void unbind() {
> ```

Calling `Binding::unbind` without calling `Binder::removeBinding` messes things up for the Binder quite badly with this implementation. I'd recommend changing the scope of `Binder::removeBinding(Binding)` to `protected` and call it from this method to make sure `Binder`is up to date.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 828 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-VSeC6eiK88Zp8d2T:-Ku-VSeC6eiK88Zp8d2U:be8kylg) ([raw file](https://github.com/vaadin/framework/blob/bb184c3c7784ec8221bcf32ae25284a57cbfd47f/server/src/main/java/com/vaadin/data/Binder.java#L828)):*
> ```Java
>         public void unbind() {
>             if (onValueChange != null) {
>                 onValueChange.remove();
> ```

Set to `null` to make sure it's not executed multiple times.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2401 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-Vsgv0auOLicVfOTx:-Ku-Vsgv0auOLicVfOTy:b-q5skx0) ([raw file](https://github.com/vaadin/framework/blob/bb184c3c7784ec8221bcf32ae25284a57cbfd47f/server/src/main/java/com/vaadin/data/Binder.java#L2401)):*
> ```Java
>                 .filter(binding -> field.equals(binding.getField()))
>                 .collect(Collectors.toSet());
>         toRemove.forEach(this::removeBinding);
> ```

This should call `Binding::unbind` and not `removeBinding`

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2412 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-VZ1E68-VUpC1Yy6x:-Ku-VZ1E68-VUpC1Yy6y:b-fgk8ir) ([raw file](https://github.com/vaadin/framework/blob/bb184c3c7784ec8221bcf32ae25284a57cbfd47f/server/src/main/java/com/vaadin/data/Binder.java#L2412)):*
> ```Java
>      * @since 8.2
>      */
>     public void removeBinding(Binding<BEAN, ?> binding) {
> ```

See comment in `Binding::unbind`

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2432 at r1](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-VlwUwO1W1xOMze1h:-Ku-VlwUwO1W1xOMze1i:b-q5skx0) ([raw file](https://github.com/vaadin/framework/blob/bb184c3c7784ec8221bcf32ae25284a57cbfd47f/server/src/main/java/com/vaadin/data/Binder.java#L2432)):*
> ```Java
>         Objects.requireNonNull(propertyName, "Property name can not be null");
>         Optional.ofNullable(boundProperties.get(propertyName))
>                 .ifPresent(this::removeBinding);
> ```

This should call `Binding::unbind` and not `removeBinding`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002)*

**Comment by pwilkin** [comment]
I use IntelliJ - is the convention described in human-readable terms so that I could adapt it?

**Comment by pwilkin** [comment]
Updated to include import conventions, incorporated your suggestions. 

One thing stands out now, however - the Binding after removing the listener doesn't seem to have any use. Maybe we want some `rebind()` method for it, to make it bound to a new `Binder`/`HasValue` pair (while retaining its getters/setters/validators)?

**Comment by tsuoanttila** [comment]
The `rebind` question is something we might want to include @legioth to discuss, and might not be something that needs to be decided in this PR.  Besides the two small comments, this looks good for me. Those can be fixed also later.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 130 at r2](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-dKv9J7Yp5hyfvApd:-Ku-dKv9J7Yp5hyfvApe:b-trc847) ([raw file](https://github.com/vaadin/framework/blob/0a235ec912f309138cfc22717070490d5480542f/server/src/main/java/com/vaadin/data/Binder.java#L130)):*
> ```Java
> 
>         /**
>          * Unbinds the binding - removes the value {@code ValueChangeListener}
> ```

JavaDoc could be updated to something like "Removes this Binding from it's Binder. This will remove any listeners from the bound {@link HasValue}." and add a @since 8.2 

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 833 at r2](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-dwa4l3FjfYG86TvX:-Ku-dwa4l3FjfYG86TvY:b-nqawci) ([raw file](https://github.com/vaadin/framework/blob/0a235ec912f309138cfc22717070490d5480542f/server/src/main/java/com/vaadin/data/Binder.java#L833)):*
> ```Java
>         public BindingValidationStatus<TARGET> validate() {
>             if (binder == null) {
>                 throw new IllegalStateException("This Binding is no longer bound to a Binder");
> ```

Are there some other methods that should check for binder existence? Also could use Objects.requireNonNull as it has been more or less the standard way to make null checks in the Framework since Vaadin 8.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002#-:-Ku-d5yQTuu0weqalB0Y:b3vaufe)*

**Comment by pwilkin** [comment]
Okay, incorporated the minor suggestions.

**Comment by tsuoanttila** [comment]
:lgtm: @hesara please take the final look at this PR.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002#-:-Ku-kgzZ_gChSxwse30v:b7zgih3)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 130 at r2](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-dKv9J7Yp5hyfvApd:-Ku3CdgbTm_I_9P_126C:bh5xmss) ([raw file](https://github.com/vaadin/framework/blob/0a235ec912f309138cfc22717070490d5480542f/server/src/main/java/com/vaadin/data/Binder.java#L130)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

JavaDoc could be updated to something like "Removes this Binding from it's Binder. This will remove any listeners from the bound {@link HasValue}." and add a @since 8.2 
</blockquote></details>

add since tag, and maybe expand a bit on the javadoc - could also move the whole javadoc of the implementation to the interface

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2431 at r4](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku3CDwUlqhNkJUzTWcM:-Ku3CDwUlqhNkJUzTWcN:b-9j8gp9) ([raw file](https://github.com/vaadin/framework/blob/4126c5582d28b7b4467881738566d104ec2ca6c3/server/src/main/java/com/vaadin/data/Binder.java#L2431)):*
> ```Java
> 
>     /**
>      * Removes the given Binding from this Binder.
> ```

This could have a comment about how it is related to Binding::unbind, and advising what the users should call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002)*

**Comment by pwilkin** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 130 at r2](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku-dKv9J7Yp5hyfvApd:-Ku41C_wfYnY7mhUpH9i:br2f38f) ([raw file](https://github.com/vaadin/framework/blob/0a235ec912f309138cfc22717070490d5480542f/server/src/main/java/com/vaadin/data/Binder.java#L130)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

add since tag, and maybe expand a bit on the javadoc - could also move the whole javadoc of the implementation to the interface
</blockquote></details>

Okay, done.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2431 at r4](https://reviewable.io:443/reviews/vaadin/framework/10002#-Ku3CDwUlqhNkJUzTWcM:-Ku41KBBM8w5-gRuQ7Hp:bp309oz) ([raw file](https://github.com/vaadin/framework/blob/4126c5582d28b7b4467881738566d104ec2ca6c3/server/src/main/java/com/vaadin/data/Binder.java#L2431)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This could have a comment about how it is related to Binding::unbind, and advising what the users should call.
</blockquote></details>

Actually, I'm going to rewrite this to ...Internal and make this just execute unbind for the consistency of the signatures.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002)*

**Comment by pwilkin** [comment]
Okay, cleaned up the docs, refactored the current method to `removeBindingInternal` and added a `removeBinding` for API clarity. Added a test case for the fixed scenario.

**Comment by hesara** [comment]
Could add javadoc (with since tag) for one more method, otherwise looks ok to me.

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2447 at r5](https://reviewable.io:443/reviews/vaadin/framework/10002#-KuJbsBmTeH_8nsR4SBL:-KuJbsBnRHKuNPgbFN5L:bdoi847) ([raw file](https://github.com/vaadin/framework/blob/1a09cd1f4b95e4ae935c45785ea3908a4d0be94a/server/src/main/java/com/vaadin/data/Binder.java#L2447)):*
> ```Java
>     }
> 
>     protected void removeBindingInternal(Binding<BEAN, ?> binding) {
> ```

Ideally even this protected method should have javadoc and a since tag describing why it is here and who calls it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002#-:-KuJcG4WiMwuC6aOFu32:ba1jsca)*

**Comment by pwilkin** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2447 at r5](https://reviewable.io:443/reviews/vaadin/framework/10002#-KuJbsBmTeH_8nsR4SBL:-KuJmoz-QxVD8dZdtSrb:b-ts9o3m) ([raw file](https://github.com/vaadin/framework/blob/1a09cd1f4b95e4ae935c45785ea3908a4d0be94a/server/src/main/java/com/vaadin/data/Binder.java#L2447)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Ideally even this protected method should have javadoc and a since tag describing why it is here and who calls it.
</blockquote></details>

Added requisite JavaDoc explaining the logic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10002#-:-KuJtezJVBHTOwxT8Zoj:bnfp4nl)*

**Pull request merged**
