### PR TITLE
Add columns at once in a batched way to increase performance

### PR DESCRIPTION
**Pull request by ericflock**
Add columns at once in a batched way to increase the initial rendering performance of the grid.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11261)

### CODE REVIEW

**Comment by TatuLund** [comment]
| Vanilla   7.7.15 |   | Patched   7.7.15 |  
-- | -- | -- | -- | --
  | Predefined   column widths | Undefined   column widths | Predefined   column widths | Undefined   column widths
Chrome |   |   |   |  
10   cols 10 rows | 2.9   - 3.1s | 3.3   - 3.7s | 0.9   - 1.0s | 1.3   - 1.5s
10   cols 1000 rows | 4.5   - 5.1s | 6.0   - 6.5s | 1.7   - 1.8s | 2.6   - 3.2s
90   cols 10 rows | 6.5   - 7.4s | 47s | 1.2   - 1.3s | 40s
90   cols 1000 rows | 10.4   - 11.0s | 48s | 2.1   - 2.3s | 46s

**Comment by TatuLund** [comment]
I did some comparison between unpatched and patched Vaadin 7.7.15 Grid, see the attached table.

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
Small formatting fix :)

> Reviewed 1 of 1 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11261#-:-LPeqPp26hkx4AXK0n_l:b-mhy2cp)* status: all files reviewed, 1 unresolved discussion (waiting on @ericflock)

___
*[client/src/main/java/com/vaadin/client/connectors/GridConnector.java, line 188 at r4](https://reviewable.io/reviews/vaadin/framework/11261#-LP_oyKqD4TrgHKPfjfL:-LP_oyKqD4TrgHKPfjfM:b-loyfr2) ([raw file](https://github.com/vaadin/framework/blob/1a20e5feb22033c0e71a99d266614bc3b815361b/client/src/main/java/com/vaadin/client/connectors/GridConnector.java#L188)):*
> ```Java
>         @SuppressWarnings("unchecked")
>         private CustomGridColumn(GridColumnState state)
>         {
> ```

Formatting nitpick: opening curly bracket should be on the same line as the method name

**Review by ericflock — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11261)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[client/src/main/java/com/vaadin/client/connectors/GridConnector.java, line 188 at r4](https://reviewable.io/reviews/vaadin/framework/11261#-LP_oyKqD4TrgHKPfjfL:-LPetPKvD_zyE2OS2dNu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/1a20e5feb22033c0e71a99d266614bc3b815361b/client/src/main/java/com/vaadin/client/connectors/GridConnector.java#L188)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

Formatting nitpick: opening curly bracket should be on the same line as the method name
</blockquote></details>

Done.

**Review by OlliTietavainenVaadin — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11261)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
