### PR TITLE
Update Screenshot due to Icon update

### PR DESCRIPTION
**Pull request by ZheSun88**
screenshots related to `search-minus` and `search-plus` swapping

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11373)

### CODE REVIEW

**Comment by anasmi** [comment]
What icon has updated?

**Comment by anasmi** [comment]
Is it search-minus and search-plus related update?

**Review by ZheSun88 — COMMENTED** [review]
yes, the places of these two icons got changed.

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11373#-:-LTfxGb22LZQ60K2fK1x:b-e67gjl)* status: 0 of 4 files reviewed, all discussions resolved

**Comment by anasmi** [comment]
Could you update the pull request comment? :)

**Review by anasmi — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — COMMENTED** [review]
added one more screenshot to this fix.  will update the comment now

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11373#-:-LTfz5IOALho4VuuueHt:b-yr20jz)* status: 4 of 5 files reviewed, all discussions resolved

**Review by anasmi — DISMISSED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by anasmi** [comment]
Thanks, @ZheSun88 :)

**Comment by anasmi** [comment]
@ZheSun88 you removed this screenshot without re-adding it, is this intentional ? checkScreenshot_changeIcon_Windows_InternetExplorer_11_allVaadinIcons-switch.png

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11373)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
