### PR TITLE
Synchronise code between Vaadin 7 and compatiblity package

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch contains picks and fixes to make code more identical between the Vaadin 7.7 branch.
Patches that apply for Vaadin 8 issues have been duplicated to corresponding classes.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8724)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 13 of 13 files at r1, 60 of 60 files at r2, 4 of 4 files at r3, 71 of 71 files at r4, 38 of 92 files at r5.
Review status: 133 of 217 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 25 of 92 files at r5, 5 of 32 files at r6, 1 of 2 files at r8.
Review status: 164 of 217 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 21 of 32 files at r6, 1 of 1 files at r7.
Review status: 186 of 217 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 11 of 92 files at r5, 3 of 32 files at r6.
Review status: 200 of 217 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHrwNI5luqFJnTVci:-KeIHrwNI5luqFJnTVcj:b-h9af33) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1)):*
> ```Java
> /*
> ```

some of the compatibility Grid widget changes haven't been merged here - is that intentional?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/connectors/SingleSelectionModelConnector.java, line 179 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIFpTWsaGdesMsYwSL:-KeIFpTWsaGdesMsYwSM:baobh9c) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/connectors/SingleSelectionModelConnector.java#L179)):*
> ```Java
>         @Override
>         public boolean deselect(JsonObject row) {
>             if (isSelected(row)) {
> ```

TBC: Where is this change from? 

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 1319 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHRO6m5rzgrBFctvC:-KeIHRO6m5rzgrBFctvD:b7568wf) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L1319)):*
> ```Java
>         private static final String NOT_EDITABLE_CLASS_NAME = "not-editable";
> 
>         ScheduledCommand fieldFocusCommand = new ScheduledCommand() {
> ```

TBC: where is this from and how is it used?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 6139 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHEvKJwnK1EdFDZjG:-KeIHEvKJwnK1EdFDZjH:brpmqck) ([raw file](https://github.com/vaadin/framework/blob/55530edec19e2bdf478a1e0dc782012754866adf/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L6139)):*
> ```Java
>     }
> 
>     /**
> ```

removed?

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/DateField.java, line 721 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIIpN8wqkf-CxGDfzU:-KeIIpN8wqkf-CxGDfzV:bpvnlov) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-server/src/main/java/com/vaadin/v7/ui/DateField.java#L721)):*
> ```Java
>             setInternalValue(null);
> 
>             /*
> ```

where is this change from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Review status: 200 of 217 files reviewed at latest revision, 9 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroupBase.java, line 63 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOPmU8UyNL46Df38Z:-KeIOPmU8UyNL46Df38_:b3fmuez) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroupBase.java#L63)):*
> ```Java
>     private boolean readonly;
> 
>     // Intentional removal of cols in compatibility package
> ```

this feature should not have been removed in the compatibility package

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTwinColSelect.java, line 370 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOb-PPvJR6DwcURb4:-KeIOb-PPvJR6DwcURb5:b3fmuez) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VTwinColSelect.java#L370)):*
> ```Java
>     /** For internal use only. May be removed or replaced in the future. */
>     public void clearInternalWidths() {
>         // Intentional removal of cols in compatibility package
> ```

this feature should not have been removed in the compatibility package

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupConnector.java, line 37 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOUO-XF3iukcXLdr4:-KeIOUO-XF3iukcXLdr5:b-t56k84) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupConnector.java#L37)):*
> ```Java
>     @Override
>     public void updateFromUIDL(UIDL uidl, ApplicationConnection client) {
>         // HTML Content has been moved to state.
> ```

why also for compatibility package?

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/ListSelect.java, line 54 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIO3v6CQyuMOdO0kCx:-KeIO3v7DQ82oft6V4G5:b3fmuez) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-server/src/main/java/com/vaadin/v7/ui/ListSelect.java#L54)):*
> ```Java
>     }
> 
>     // Columns are no longer used for width.
> ```

this feature should not have been removed in the compatibility package

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/TwinColSelect.java, line 68 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOCt20xrU-U8TgF7P:-KeIOCt20xrU-U8TgF7Q:b3fmuez) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-server/src/main/java/com/vaadin/v7/ui/TwinColSelect.java#L68)):*
> ```Java
>     }
> 
>     // Columns are no longer used for width.
> ```

this feature should not have been removed in the compatibility package

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Review status: 200 of 217 files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIyd4naZLg6pPzOzPt:-KeIyd4naZLg6pPzOzPu:btsbsjp) (no related file):*
EncodeUtil @since update seems to be missing from this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by tsuoanttila** [comment]
*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 6139 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHEvKJwnK1EdFDZjG:-KeYJuXr9Oo2DEYzvQNl:b-nr4tm9) ([raw file](https://github.com/vaadin/framework/blob/55530edec19e2bdf478a1e0dc782012754866adf/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L6139)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

removed?
</blockquote></details>

Moved to different location to match the location in V7

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by tsuoanttila** [comment]
Review status: 200 of 217 files reviewed at latest revision, 10 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/connectors/SingleSelectionModelConnector.java, line 179 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIFpTWsaGdesMsYwSL:-KeYNeaWg-s6y7z6EsF2:bj35lkq) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/connectors/SingleSelectionModelConnector.java#L179)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC: Where is this change from? 
</blockquote></details>

https://github.com/vaadin/framework/commit/a00429697b8340a56568465694cac6549954a51f

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroupBase.java, line 63 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOPmU8UyNL46Df38Z:-KeYNiYmQtOQJylDs6r1:b-xzutne) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VOptionGroupBase.java#L63)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this feature should not have been removed in the compatibility package
</blockquote></details>

I do agree. Restoring it could be done either here or in it's own patch. Which you prefer?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupConnector.java, line 37 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIOUO-XF3iukcXLdr4:-KeYNxKtedk2mfvryd_K:b-j9q4ra) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupConnector.java#L37)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

why also for compatibility package?
</blockquote></details>

The change was made before duplication to the compatibility package. Could be reverted. See comment about columns removal.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 1319 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHRO6m5rzgrBFctvC:-KeYOS0yKexAQzOPZgTH:b-wh2kw0) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L1319)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC: where is this from and how is it used?
</blockquote></details>

It might be it's called from an isIE8 branch of an if-check. Need to check if it's actually used..

---

*[compatibility-server/src/main/java/com/vaadin/v7/ui/DateField.java, line 721 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIIpN8wqkf-CxGDfzU:-KeYOthfKcLkux7pHw3f:b6wqh59) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-server/src/main/java/com/vaadin/v7/ui/DateField.java#L721)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

where is this change from?
</blockquote></details>

https://github.com/vaadin/framework/commit/d1b310fb07e08d060c4d325c1059c007954303f3

Was previously partially picked by Denis. This part was not included.

https://github.com/vaadin/framework/commit/f12fbfb7044defc8442d05e6810c43875c04710c

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 3 of 92 files at r5, 2 of 32 files at r6.
Review status: 205 of 217 files reviewed at latest revision, 11 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 46 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSB_kKQSBdP11w1Vd:-KeYSB_kKQSBdP11w1Ve:b-5sbq8) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L46)):*
> ```Java
> 
>         getWidget().setReadonly(isReadOnly());
>         // Intentional change to use state over UIDL in compatibility package
> ```

why different in compatibility package?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 54 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYS9LqgSDMmhq3GNgN:-KeYS9LqgSDMmhq3GNgO:b-vj275d) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L54)):*
> ```Java
>                 .getBooleanAttribute("nullselectitem");
> 
>         // Support for cols has been dropped.
> ```

should not have been dropped

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 1319 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHRO6m5rzgrBFctvC:-KeYQlEiqFI_joDX3jtY:b68s8ko) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L1319)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

It might be it's called from an isIE8 branch of an if-check. Need to check if it's actually used..
</blockquote></details>

was only for IE8, not used in V8

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/optiongroup/OptionGroupConstants.java, line 21 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSwCHgP5I87kZp1_3:-KeYSwCHgP5I87kZp1_4:bpbbiye) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/optiongroup/OptionGroupConstants.java#L21)):*
> ```Java
> 
> public class OptionGroupConstants implements Serializable {
>     // Vaadin 8 option group uses state for HTML content
> ```

why this difference - compatibility package copied too early

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 2 of 92 files at r5.
Review status: 207 of 217 files reviewed at latest revision, 10 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHrwNI5luqFJnTVci:-KeYTsX-3LJki9NO4ztt:b-xf90fq) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

some of the compatibility Grid widget changes haven't been merged here - is that intentional?
</blockquote></details>

(probably all relevant changes applied in one form or another - making this comment non-blocking)

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java, line 1319 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeIHRO6m5rzgrBFctvC:-KeYYPoqdreO1Xk4i-o3:btj3b6s) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L1319)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

was only for IE8, not used in V8
</blockquote></details>

to remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 1 of 92 files at r5, 1 of 2 files at r8.
Review status: 209 of 217 files reviewed at latest revision, 11 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java, line 1453 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYcDx464E0nsO5YS1x:-KeYcDx464E0nsO5YS1y:bubd76j) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VFilterSelect.java#L1453)):*
> ```Java
> 
>     private class IconWidget extends Widget {
>         private Icon icon;
> ```

(assuming moved test shows that these changes are not needed in VComboBox)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r9, 5 of 5 files at r10, 1 of 4 files at r11, 9 of 10 files at r12.
Review status: 222 of 224 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 46 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSB_kKQSBdP11w1Vd:-KeYtMrb9UfFL1ZKKBzl:b-ujenj0) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L46)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

why different in compatibility package?
</blockquote></details>

comment still relevant?

---

*[uitest/src/main/java/com/vaadin/tests/components/listselect/ListSelects.java, line 33 at r12](https://reviewable.io:443/reviews/vaadin/framework/8724#-KebcqePvygBE916Jgjz:-KebcqePvygBE916Jgk-:b-lae8vi) ([raw file](https://github.com/vaadin/framework/blob/ee383a1166c03ac545e7f7db62f87502b33a0ac4/uitest/src/main/java/com/vaadin/tests/components/listselect/ListSelects.java#L33)):*
> ```Java
>         super.createActions();
>         createRowsAction(CATEGORY_FEATURES);
>         createColsAction(CATEGORY_FEATURES);
> ```

(this could theoretically break some tests - to check)

---

*[uitest/src/main/java/com/vaadin/tests/components/select/TwinColSelectTest.java, line 48 at r12](https://reviewable.io:443/reviews/vaadin/framework/8724#-Kebcvy2PINmglQFGZ59:-Kebcvy2PINmglQFGZ5A:bmw28pg) ([raw file](https://github.com/vaadin/framework/blob/ee383a1166c03ac545e7f7db62f87502b33a0ac4/uitest/src/main/java/com/vaadin/tests/components/select/TwinColSelectTest.java#L48)):*
> ```Java
>         super.createActions();
>         createRowsAction(CATEGORY_FEATURES);
>         createColsAction(CATEGORY_FEATURES);
> ```

this might break some tests as the order of actions changes - to check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by tsuoanttila** [comment]
Review status: 222 of 224 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 46 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSB_kKQSBdP11w1Vd:-KebmHacQ0NSLmIvYNOL:ba9ka5k) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L46)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

comment still relevant?
</blockquote></details>

No longer relevant. Will remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by tsuoanttila** [comment]
*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 46 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSB_kKQSBdP11w1Vd:-Kebsmi8nqqV4G1nCi1f:b-v2hasb) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L46)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

No longer relevant. Will remove.
</blockquote></details>

Actually is relevant. Since it refers to getState().multiSelect which has been refactored to state instead of UIDL. Should we revert that as well ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 1 of 92 files at r5.
Review status: 223 of 224 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java, line 46 at r8](https://reviewable.io:443/reviews/vaadin/framework/8724#-KeYSB_kKQSBdP11w1Vd:-Kebt1duoaJ40uoeVosR:b-kie33p) ([raw file](https://github.com/vaadin/framework/blob/1321a13da248dc1d5ef9d1360e69cdb96ac651a6/compatibility-client/src/main/java/com/vaadin/v7/client/ui/optiongroup/OptionGroupBaseConnector.java#L46)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Actually is relevant. Since it refers to getState().multiSelect which has been refactored to state instead of UIDL. Should we revert that as well ?
</blockquote></details>

that would simplify merging changes in the future - would be good if not complicated/risky

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8724#-:-Kebw5m7P3iQi_mOBj3p:bnfp4nl)*

**Pull request merged**
