### PR TITLE
Use lambda with Handlers

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10229)

### CODE REVIEW

**Comment by pekam** [comment]
Avoid one-letter names for variables. So use `event` instead of `e`

---

Review status: 0 of 67 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10229#-:-KxNInnDqCwnt-v2IDvs:b-k4hddc)*

**Comment by pekam** [comment]
Reviewed 9 of 67 files at r1, 69 of 69 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 710 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSPSJb_Tv3HSqL5E0N:-KxSPSJb_Tv3HSqL5E0O:b-hmp9w8) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L710)):*
> ```Java
> 
>         if (LogConfiguration.loggingIsEnabled()) {
>             GWT.setUncaughtExceptionHandler(event -> {
> ```

not event

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 111 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSRajONo4ruo__OTqE:-KxSRajONo4ruo__OTqF:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L111)):*
> ```Java
>                 .filter(event -> event.getKey().getElement()
>                         .isOrHasChild(element))
>                 .map(event -> event.getValue()).findFirst().orElse(null);
> ```

not events

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 124 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSc16UEHY40PdXV4w:-KxSSc16UEHY40PdXV4x:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L124)):*
> ```Java
>     private Optional<JsonObject> tryGetItem(Element element) {
>         return optionsToItems.entrySet().stream()
>                 .filter(event -> event.getKey().getElement().equals(element))
> ```

not events

---

*[client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java, line 365 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSmvuAbk0mQuQooLm:-KxSSmvuAbk0mQuQooLn:b-2it651) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java#L365)):*
> ```Java
>                 selectionsListBox);
>         selectionChangeListeners
>                 .forEach(event -> event.accept(movedItems,
> ```

looks like listeners instead of events

---

*[client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java, line 373 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSrKVnZZK3LpxjOe4:-KxSSrKVnZZK3LpxjOe5:b-2it651) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java#L373)):*
> ```Java
>                 optionsListBox);
>         selectionChangeListeners
>                 .forEach(event -> event.accept(Collections.emptySet(),
> ```

looks like listeners instead of events

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxST_HsqQAmXnURdUSt:-KxST_HsqQAmXnURdUSu:blp4x57) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L105)):*
> ```Java
>             status) -> {
>         String message = status.getFieldValidationErrors().stream()
>                 .filter(event -> event.getMessage().isPresent()
> ```

not events

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSTfCPir3niTyYmKP4:-KxSTfCPir3niTyYmKP5:b-hmp9w8) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L59)):*
> ```Java
> 
>         if (!isElementPresent(UIElement.class)) {
>             waitUntil(event -> isElementPresent(UIElement.class), 10);
> ```

not event

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSThfMmDtqB3FQd1l2:-KxSThfMmDtqB3FQd1l3:b-hmp9w8) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java#L83)):*
> ```Java
>         assertEquals(0, getServerCounter());
>         getServerCounterStartButton().click();
>         waitUntil(event -> getServerCounter() > 1, 10);
> ```

not event

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10229)*

**Comment by asashour** [comment]
Review status: 71 of 75 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ApplicationConfiguration.java, line 710 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSPSJb_Tv3HSqL5E0N:-KxT851J9Sl5dhZ72wBS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ApplicationConfiguration.java#L710)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not event
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 111 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSRajONo4ruo__OTqE:-KxT85cJFfkrqbmGkBa9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L111)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 124 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSc16UEHY40PdXV4w:-KxT866F2iR6KLIJItg9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L124)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java, line 365 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSmvuAbk0mQuQooLm:-KxT86aGb33xf6K7TvSL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java#L365)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

looks like listeners instead of events
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java, line 373 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSSrKVnZZK3LpxjOe4:-KxT86sDOOBI9EJJrJ53:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/client/src/main/java/com/vaadin/client/ui/VTwinColSelect.java#L373)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

looks like listeners instead of events
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxST_HsqQAmXnURdUSt:-KxT87PBpFiKfHwhauBQ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L105)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not events
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSTfCPir3niTyYmKP4:-KxT87rG4rKskvRXn2l8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L59)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not event
</blockquote></details>

Done.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java, line 83 at r2](https://reviewable.io:443/reviews/vaadin/framework/10229#-KxSThfMmDtqB3FQd1l2:-KxT88R2B_CAlTLyuoBF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/315d8a1514443a51690c17faa92b251c0fc4cf4e/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/push/LongPollingProxyServerIT.java#L83)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

not event
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10229)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10229#-:-KxT8sw45KJu0dsZxiNm:bnfp4nl)*

**Pull request merged**
