### PR TITLE
Prevent IndexOutOfBoundException in VMenuBar.CustomMenuItem

### LINKED ISSUE #10814: Menubar repaint issue on browser resize
**Scenario:**
When user resize browser window then menubar component paints triangles which shows that menubar has items which cannot fit on screen. 
When we maximize browser window then all items should be shown again.
**Issue:**
After resizing items are duplicated.

dzwonki3

### LINKED ISSUE #10948: MenuBar throws java.lang.IndexOutOfBoundsException trying to change Caption/Icon
Trying to change Caption of the MenuItem throws java.lang.IndexOutOfBoundsException: . Happens only when  **width** is set.

Stacktrace: 
```
Error in SimpleManagedLayout (horizontal) handling
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
   at Unknown.Ig(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.Kg(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.new IWd(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.Jce(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.o1d(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.xVc(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.Snb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.cob(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.Xnb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.nob(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.kUc(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.CUc(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.BUc(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.rfd(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.AFb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.TFb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.VPb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.CPb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.DPb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.HRb(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.Wv(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.hw(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.eval(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.$h(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.bi(com.vaadin.DefaultWidgetSet-0.js)
   at Unknown.eval(com.vaadin.DefaultWidgetSet-0.js)

```

Code to reproduce: 
```
        MenuBar barmenu = new MenuBar();
        MenuBar.MenuItem more = barmenu.addItem("", null, null);
        barmenu.setMoreMenuItem(more);

        MenuBar.MenuItem drinks = barmenu.addItem("Drinks", null, null);
        MenuBar.MenuItem hots = drinks.addItem("Hot", null, null);
        hots.addItem("Tea", null);
        hots.addItem("Coffee", null);

        MenuBar.MenuItem colds = more.addItem("Cold", null, null);
        colds.addItem("Milk", null);
        colds.addItem("Weissbier", null);
        barmenu.setWidth("150px");
        addComponent(barmenu);
        // Default icon should be set
        addComponent(new Button("Remove icon",
                e -> barmenu.getMoreMenuItem().setIcon(null)));
        // Custom icon is set
        addComponent(new Button("Set icon",
                e -> barmenu.getMoreMenuItem().setIcon(VaadinIcons.MENU)));
        // Set Caption
        addComponent(new Button("Set caption",
                e -> barmenu.getMoreMenuItem().setText("Caption")));
        // Remove Caption
        addComponent(new Button("Remove caption",
                e -> barmenu.getMoreMenuItem().setText(null)));

        addComponent(new Button("Chnage drink's caption",
                e -> drinks.setText("New drinks")));
```

### PR DESCRIPTION
**Pull request by Wnt**
Fixes #10948 #11374 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11285)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11285)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Wnt)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11285#-LQDRklrAUsMGTc7tZOs:-LQDRklrAUsMGTc7tZOt:b-u26zu7) (no related file):*
is it possible to add a test here?  and this commit message can be more elaborated.

---

**Comment by anasmi** [comment]
This fix prevents `IndexOutOfBoundsException` in certain cases, also, I haven't added test case for the issue @Wnt mentioned, but it resolves another one (#11374 )and tests are added for it.

**Comment by anasmi** [comment]
@ZheSun88 test is added :)

**Review by ZheSun88 — APPROVED** [review]
oh Thanks @anasmi :-) 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11285#-:-LTgvki400LYR6_lUfy3:b-2lvqe4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
