### PR TITLE
Make m2e ignore phantomjs-maven-plugin

### PR DESCRIPTION
**Pull request by Legioth**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8002)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8002)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[test/pom.xml, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8002#-KZ1DXt_75FqXYGUsJVY:-KZ1DXt_75FqXYGUsJVZ:bdgaelt) ([raw file](https://github.com/vaadin/framework/blob/2c4ccd7c8a865abbfafdce471b853472b7e76038/test/pom.xml#L156)):*
> ```XML
>             </plugin>
>         </plugins>
> 		<pluginManagement>
> ```

incorrect xml formatting, use spaces instead of tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8002)*

**Comment by Legioth** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/pom.xml, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/8002#-KZ1DXt_75FqXYGUsJVY:-KZ1EkuGIZpol2XsnV14:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2c4ccd7c8a865abbfafdce471b853472b7e76038/test/pom.xml#L156)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

incorrect xml formatting, use spaces instead of tabs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8002)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8002)*

**Pull request merged**
