### PR TITLE
Add helpers for dealing with columns based on its id

### LINKED ISSUE #8361: Add shorthands for joining Grid header and footer cells by Column or column id

### PR DESCRIPTION
**Pull request by Legioth**
setColumns(Column...)  is removed since it's not possible to re-add a
removed column instance.

Fixes #8361

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8411)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2179 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbtzz0CzyRXy3WHWOkM:-Kbtzz0CzyRXy3WHWOkN:b7od4o1) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2179)):*
> Returns the column with the given column id.

?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2252 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu-P5fMQGzoaC_-D_k:-Kbu-P5fMQGzoaC_-D_l:bwcz51a) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2252)):*
> requireColumnById

require ?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3aQl1jnDEpWeYR87:-Kbu3aQmbsSjP9sv1ejn:b-g3opdx) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L40)):*
> ```Java
> import elemental.json.JsonObject;
> 
> public class GridTest {
> ```

test for : 
- remove column by column
- set removed column back

?

---

*[server/src/test/java/com/vaadin/ui/components/grid/StaticSectionTest.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3zT1SFmjxn2JKijG:-Kbu3zT1SFmjxn2JKijH:b-d0wxhj) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/ui/components/grid/StaticSectionTest.java#L137)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8411)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2179 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbtzz0CzyRXy3WHWOkM:-Kby4jo5c36AJZubxuKq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2179)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Returns the column with the given column id.

?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2252 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu-P5fMQGzoaC_-D_k:-Kby4ltWdBeeWnyNFtWU:bplsgpd) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2252)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> requireColumnById

require ?
</blockquote></details>

I used "require" here to try to describe how this method differs from the regular `getColumn` that doesn't throw. 

Do you have any other suggestion for how to name this method?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3aQl1jnDEpWeYR87:-Kby5PUT4kH63xEbjRuh:b8qwm1x) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L40)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

test for : 
- remove column by column
- set removed column back

?

</blockquote></details>

`removeColumnByColumn` is on line 347.

There is no public API for adding an existing `Column` instance, and we cannot easily introduce it since `Column` is implemented as an extension and extensions cannot by design be attached again after they have been detached.

---

*[server/src/test/java/com/vaadin/ui/components/grid/StaticSectionTest.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3zT1SFmjxn2JKijG:-Kby5zAUqJnemL7bA22E:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/ui/components/grid/StaticSectionTest.java#L137)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8411)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2252 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu-P5fMQGzoaC_-D_k:-Kby96ZqnJQ_3gWJg8jK:bc7ur9f) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2252)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

I used "require" here to try to describe how this method differs from the regular `getColumn` that doesn't throw. 

Do you have any other suggestion for how to name this method?
</blockquote></details>

`getOrThrow`. May be also not good enough but `requireColumnById()` is very confusing for me.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3aQl1jnDEpWeYR87:-Kby9cTnC3HOuW6bXRQK:bggddo7) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L40)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`removeColumnByColumn` is on line 347.

There is no public API for adding an existing `Column` instance, and we cannot easily introduce it since `Column` is implemented as an extension and extensions cannot by design be attached again after they have been detached.
</blockquote></details>

I meant consequence of action: remove and set it back.

There a test already which does the same : `setColumns_addColumns_beangrid`
But it removes a column by id not by the column reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8411)*

**Comment by Legioth** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2252 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu-P5fMQGzoaC_-D_k:-KbyCdU-R2y5lhUubZym:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/main/java/com/vaadin/ui/Grid.java#L2252)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`getOrThrow`. May be also not good enough but `requireColumnById()` is very confusing for me.
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8411#-Kbu3aQl1jnDEpWeYR87:-KbyDTb_BWC6Hx0YluEB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/80c061bbad4792853b4711572fc4632aef96c0ef/server/src/test/java/com/vaadin/tests/server/component/grid/GridTest.java#L40)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I meant consequence of action: remove and set it back.

There a test already which does the same : `setColumns_addColumns_beangrid`
But it removes a column by id not by the column reference.

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8411)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8411)*

**Pull request merged**
