### PR TITLE
Refactor Html5 DnD feature based on API review

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9306)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r1, 68 of 78 files at r2.
Review status: 49 of 61 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9tJzi9OH2ZnFsagp:-Kjv9tJzi9OH2ZnFsagq:b-s7j25z) ([raw file](https://github.com/vaadin/framework/blob/494b90a81cdd7dfc2fb337676e51ffa4bdd6ea43/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L156)):*
> ```Java
>                     badge.removeFromParent();
>                 }, (Element) dragStartEvent.getEventTarget().cast());
>                 setDraggable(draggedRowElement);
> ```

Was this call already redundant as javadoc seems to indicate?

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 307 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9ZxP8I-VJjS_tZ5h:-Kjv9ZxP8I-VJjS_tZ5i:b-twqbxg) ([raw file](https://github.com/vaadin/framework/blob/8ab763f64817fc283e48b5f4c91082e758557c76/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L307)):*
> ```Java
>      * <p>
>      * This is triggered on {@link #onDragEnter(Event) dragenter} and
>      * {@link #onDragOver(Event) dragover} events pending if the drop is
> ```

depending on whether?

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 322 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9PqcvUtBjReIGpg2:-Kjv9PqdRX8lisWx9_Lp:b4tv12p) ([raw file](https://github.com/vaadin/framework/blob/8ab763f64817fc283e48b5f4c91082e758557c76/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L322)):*
> ```Java
>      * This is triggered on {@link #onDrop(Event) drop},
>      * {@link #onDragLeave(Event) dragleave} and {@link #onDragOver(Event)
>      * dragover} events pending on whether the drop has happened or if it is not
> ```

depending on?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9306)*

**Comment by pleku** [comment]
Review status: 49 of 60 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 156 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9tJzi9OH2ZnFsagp:-KjvERWR5zxgoAX-obhX:b-3aw2vw) ([raw file](https://github.com/vaadin/framework/blob/494b90a81cdd7dfc2fb337676e51ffa4bdd6ea43/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L156)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Was this call already redundant as javadoc seems to indicate?
</blockquote></details>

I have no idea how it had got there, just noticed it now, not needed at this point at all.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 307 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9ZxP8I-VJjS_tZ5h:-KjvFW5jpP0-i-NP_FOW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8ab763f64817fc283e48b5f4c91082e758557c76/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L307)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

depending on whether?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 322 at r1](https://reviewable.io:443/reviews/vaadin/framework/9306#-Kjv9PqcvUtBjReIGpg2:-KjvFYLW0OK-xV49A_L3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/8ab763f64817fc283e48b5f4c91082e758557c76/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L322)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

depending on?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9306)*

**Comment by hesara** [comment]
Reviewed 10 of 78 files at r2, 6 of 7 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 132 at r3](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvIatpI7RYy2tl_baS:-KjvIatpI7RYy2tl_baT:bu0kaea) ([raw file](https://github.com/vaadin/framework/blob/03d644ceed7482042bb528a16f258aedd6fe6966/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L132)):*
> ```Java
> 
>         removeDropListeners(getDropTargetElement());
>         ((AbstractComponentConnector) getParent()).onDropTargetDetached();
> ```

(ok if getParent() is still valid here, I believe it is)

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 330 at r4](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvKztke65rLgcd3113:-KjvKztke65rLgcd3114:b-rz4xr8) ([raw file](https://github.com/vaadin/framework/blob/0d59f5fc2e34aa7080b232a298fc6310701eb3dd/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L330)):*
> ```Java
>      * dragover} events pending on whether the drop has happened or if it is not
>      * possible. The drop is not possible if the drop effect for the source and
>      * target don't match or if the is a drop criteria script that evaluates to
> ```

"if the is"?

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 88 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGEhAuq0P2wHs0DUO:-KjvGEhBj7lWUNRlFVa9:b7v8ozk) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L88)):*
> ```Java
> 
>     /**
>      * Registers the server side RPC methods invokated from client side on
> ```

(invoked)

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGOZUL35O4NvAshSh:-KjvGOZUL35O4NvAshSi:b-frwje7) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L91)):*
> ```Java
>      * <code>dragstart</code> and <code>dragend</code> events.
>      * <p>
>      * Override this method if you have custom RPC interface for transmitting
> ```

rather override one/both of onDragStart()/onDragEnd()?

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGi3rgDA7EobhYzl0:-KjvGi3rgDA7EobhYzl1:b-z42gfr) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L30)):*
> ```Java
> 
> /**
>  * Extension to make a component a drag target for HTML5 drag and drop
> ```

(drop target?)

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGoh-tzk2G6pJtIni:-KjvGoh-tzk2G6pJtInj:b-32psc9) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L59)):*
> ```Java
> 
>     /**
>      * Registers the server side RPC methods invokated from client side on
> ```

invoked

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 62 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGtOG7Djs1pCPpHdI:-KjvGtOG7Djs1pCPpHdJ:bdye96b) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L62)):*
> ```Java
>      * <code>drop</code> event.
>      * <p>
>      * Override this method if you need to have a custom RPC interface for
> ```

rather override onDrop(...)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9306)*

**Comment by pleku** [comment]
Review status: 56 of 60 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 132 at r3](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvIatpI7RYy2tl_baS:-KjvNEK38wS1nr78FaD6:bk9iz0s) ([raw file](https://github.com/vaadin/framework/blob/03d644ceed7482042bb528a16f258aedd6fe6966/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L132)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(ok if getParent() is still valid here, I believe it is)
</blockquote></details>

To my understanding from checking the code it should be there or the framework will be broken severely

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 330 at r4](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvKztke65rLgcd3113:-KjvNUzjdeW3tic6-hQs:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0d59f5fc2e34aa7080b232a298fc6310701eb3dd/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L330)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"if the is"?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 88 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGEhAuq0P2wHs0DUO:-KjvNiiJuP0HXAkYiBaO:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L88)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(invoked)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java, line 91 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGOZUL35O4NvAshSh:-KjvOAp0ugb5_tgPh696:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DragSourceExtension.java#L91)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

rather override one/both of onDragStart()/onDragEnd()?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 30 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGi3rgDA7EobhYzl0:-KjvOLCi1jlTSXUUh_6b:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(drop target?)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 59 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGoh-tzk2G6pJtIni:-KjvP2iLR76jq0hY_DCY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L59)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

invoked
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java, line 62 at r2](https://reviewable.io:443/reviews/vaadin/framework/9306#-KjvGtOG7Djs1pCPpHdI:-KjvP2wjz6B-YdJgk30Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9c7984c5a77504334609c54ce98305268edd0f6b/server/src/main/java/com/vaadin/ui/dnd/DropTargetExtension.java#L62)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

rather override onDrop(...)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9306)*

**Comment by hesara** [comment]
Reviewed 3 of 78 files at r2, 1 of 7 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9306)*

**Pull request merged**
