### PR TITLE
Add contribution guideline

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10083)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxMvBcGzPijOVRvl_A:-KuxMvBcGzPijOVRvl_B:b2remvo) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L7)):*
> ```Markdown
> ### Making your PR
> 
> A new Pull Request should start by forking the Vaadin Framework project (or checking that your fork is up-to-date). 
> ```

(extra space at end of line); Could we just use "pull request" here and below? Use the framework style rules and conventions.

---

*[.github/CONTRIBUTING.md, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxMyJ2t0aTWwZtM1Y7:-KuxMyJ2t0aTWwZtM1Y8:bkfh2bp) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L9)):*
> ```Markdown
> A new Pull Request should start by forking the Vaadin Framework project (or checking that your fork is up-to-date). 
> 
> Unless issue is specific to a single version of the Framework, you should always aim to make the patch on top of the `master` branch.
> ```

the issue

---

*[.github/CONTRIBUTING.md, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxNIr6Bw-P0fF8tXpP:-KuxNIr6Bw-P0fF8tXpQ:b-45y5q2) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L11)):*
> ```Markdown
> Unless issue is specific to a single version of the Framework, you should always aim to make the patch on top of the `master` branch.
> 
> In your repo, make a new branch from `master`. Make your code changes in that branch, and once you're done make a Pull Request to the `vaadin/framework` branch `master`.
> ```

Make sure the "Allow edits from maintainers" checkbox is checked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxMvBcGzPijOVRvl_A:-KwL-tux4QJXyx8QNDaA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L7)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(extra space at end of line); Could we just use "pull request" here and below? Use the framework style rules and conventions.
</blockquote></details>

Done.

---

*[.github/CONTRIBUTING.md, line 9 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxMyJ2t0aTWwZtM1Y7:-KwL-uBUsj8syDvPZcXY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L9)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the issue
</blockquote></details>

Done.

---

*[.github/CONTRIBUTING.md, line 11 at r1](https://reviewable.io:443/reviews/vaadin/framework/10083#-KuxNIr6Bw-P0fF8tXpP:-KwL-uVykkp6ZMHWf1f9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5b3482ad742b0b74d4f686edf6dc639857370d31/.github/CONTRIBUTING.md#L11)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Make sure the "Allow edits from maintainers" checkbox is checked.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10083#-KwdC9hJptPi9fZxsawF:-KwdC9hJptPi9fZxsawG:b-g55akk) (no related file):*
Do you have a document describing how to configure the IDE to avoid using tabs instead of spaces and things like that? (Vaadin Formatting)

If you do, then putting a link on the contributing guide would be nice.
If not, then this section is missing.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10083#-KwdCc9dLMoFq4_6VlOp:-KwdCc9dLMoFq4_6VlOq:b-82tpwb) (no related file):*
Another thing - how is the lifecycle of a PR? I mean, in terms of code review, build process, sonar (do you use it?), tests and so on?

I'd expect to see a description on "what happens after you submit your PR", and things that the user needs to pay attention to during the process. For instance, "please be available to answer possible questions in the PR - please check the build status after submitting your PR" are stuff like this.

I don't know if we can/should provide time tables for the reviews, but it would give a nice impression to say "we review incoming PRs within 7 days, with  most of the PRs reviewed in the first x hours. If you didn't receive a review right away, please have patience - we leave no PRs behind!".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10083#-KwdC9hJptPi9fZxsawF:-KwdHzgX9x_T62OPyHXd:b-hgw3jl) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Do you have a document describing how to configure the IDE to avoid using tabs instead of spaces and things like that? (Vaadin Formatting)

If you do, then putting a link on the contributing guide would be nice.
If not, then this section is missing.
</blockquote></details>

Added link.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10083#-KwdCc9dLMoFq4_6VlOp:-KwdI1aZc1FL6ylVR9HT:bfpoflv) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Another thing - how is the lifecycle of a PR? I mean, in terms of code review, build process, sonar (do you use it?), tests and so on?

I'd expect to see a description on "what happens after you submit your PR", and things that the user needs to pay attention to during the process. For instance, "please be available to answer possible questions in the PR - please check the build status after submitting your PR" are stuff like this.

I don't know if we can/should provide time tables for the reviews, but it would give a nice impression to say "we review incoming PRs within 7 days, with  most of the PRs reviewed in the first x hours. If you didn't receive a review right away, please have patience - we leave no PRs behind!".
</blockquote></details>

Not sure if we want to have any promises about the lifecycles as it depends quite a lot on the nature of the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[.github/CONTRIBUTING.md, line 17 at r3](https://reviewable.io:443/reviews/vaadin/framework/10083#-Kwtq5fArfWUMfxgut0J:-Kwtq5fArfWUMfxgut0K:b-f0lf6g) ([raw file](https://github.com/vaadin/framework/blob/85b40106d14f70062496b3b2e5f6cd82339f9ca8/.github/CONTRIBUTING.md#L17)):*
To keep the 2nd person, and avoid repetition, as well as to sound nicer:

> We recommend making sure that the "Allow edits from maintainers" checkbox on the pull request page is checked. This allows us to commit minor fixes, like typos, without bothering you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Comment by torok-peter** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083#-:-Kx7zsDwQZRbdR8r8z7W:bnfp4nl)*

**Comment by torok-peter** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10083)*

**Pull request merged**
