### PR TITLE
Add headers to community articles

### PR DESCRIPTION
**Pull request by hezamu**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10028)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 84 of 84 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPIKQQZnAj0TFd3DQw:-KuPIKQQZnAj0TFd3DQx:b-wy5prm) (no related file):*
some minor issues + number 68 unused (not necessarily a problem - gaps are allowed)

---

*[documentation/articles/DevelopingPortletsForTheWebSpherePortalServer.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPFFZCqFo3gS_iBvlE:-KuPFFZCqFo3gS_iBvlF:b-an7es) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/DevelopingPortletsForTheWebSpherePortalServer.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Developing Portlets For The Web Sphere Portal Server
> ```

WebSphere

---

*[documentation/articles/ExposingServerSideAPIToJavaScript.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPFc9yvEQ1hL41IYel:-KuPFc9yvEQ1hL41IYem:b-2lsvim) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/ExposingServerSideAPIToJavaScript.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Exposing Server Side API To Java Script
> ```

JavaScript

---

*[documentation/articles/IntegratingAJavaScriptComponent.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPFwwhitaORuMveGdQ:-KuPFwwhitaORuMveGdR:b-2lsvim) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/IntegratingAJavaScriptComponent.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Integrating A Java Script Component
> ```

JavaScript

---

*[documentation/articles/IntegratingAJavaScriptLibraryAsAnExtension.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPFzSKQQncG8mFgFjS:-KuPFzSKQQncG8mFgFjT:b-2lsvim) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/IntegratingAJavaScriptLibraryAsAnExtension.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Integrating A Java Script Library As An Extension
> ```

JavaScript

---

*[documentation/articles/UsingAJavaScriptLibraryOrAStyleSheetInAnAddOn.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPGoLyx_llJL6qG61Y:-KuPGoLyx_llJL6qG61Z:b-2lsvim) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/UsingAJavaScriptLibraryOrAStyleSheetInAnAddOn.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Using A Java Script Library Or A Style Sheet In An Add On
> ```

JavaScript

---

*[documentation/articles/UsingRPCFromJavaScript.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPH49KrWSHsMzyA1AH:-KuPH49KrWSHsMzyA1AI:b-2lsvim) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/UsingRPCFromJavaScript.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Using RPC From Java Script
> ```

JavaScript

---

*[documentation/articles/Vaadin7SpringSecurityBaseAuthentification.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPHJnAOEvQF_i1kmir:-KuPHJnAOEvQF_i1kmis:b-s01xhu) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/Vaadin7SpringSecurityBaseAuthentification.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Vaadin 7 Spring Security Base Authentification
> ```

the title gets unclear when removing the parentheses - could also simply remove the last two words here

---

*[documentation/articles/VaadinCDI.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPHUOzxZ3KiLBdi8Wt:-KuPHUOzxZ3KiLBdi8Wu:b2nhbs3) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/VaadinCDI.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Vaadin C D I
> ```

CDI

---

*[documentation/articles/VaadinOnGrailsCreateProjectInIntelliJIDEA.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPH_QXAQxmv8-Dt_r0:-KuPH_QXAQxmv8-Dt_r1:bb0glal) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/VaadinOnGrailsCreateProjectInIntelliJIDEA.asciidoc#L2)):*
> ```AsciiDoc
> ---
> title: Vaadin On Grails Create Project In IntelliJ IDEA
> ```

lack of dash makes this less clear - could also shorten if not adding dash

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10028)*

**Comment by hezamu** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPIKQQZnAj0TFd3DQw:-KuPQKJI4yXgKMsSN-1m:b-r95dx8) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

some minor issues + number 68 unused (not necessarily a problem - gaps are allowed)
</blockquote></details>

Fixed spelling. Leaving 68 empty is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10028)*

**Comment by hesara** [comment]
Reviewed 8 of 8 files at r2.
Review status: 83 of 84 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPIKQQZnAj0TFd3DQw:-KuShmhSc9WGjAQW8LPo:b-1g51i2) (no related file):*
<details><summary><i>Previously, hezamu (Henri Muurimaa) wrote…</i></summary><blockquote>

Fixed spelling. Leaving 68 empty is ok.
</blockquote></details>

one more spelling issue unresolved, otherwise LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10028)*

**Comment by hezamu** [comment]
*[documentation/articles/UsingAJavaScriptLibraryOrAStyleSheetInAnAddOn.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/10028#-KuPGoLyx_llJL6qG61Y:-KuT5Gn5DDczuLJyOFZ1:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/12abdde5f4b295f0aaef97d65dc477de202e3b42/documentation/articles/UsingAJavaScriptLibraryOrAStyleSheetInAnAddOn.asciidoc#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

JavaScript
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10028)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10028#-:-KuT5sdjXnSFoO0UoXsc:bnfp4nl)*

**Pull request merged**
