### PR TITLE
Use local variable for getWidget()

### PR DESCRIPTION
**Pull request by asashour**
In some places, `getWidget()` is called multiple times, and I believe this has a little performance influence since in some cases `super.getWidget()` is called more than once.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10253)

### CODE REVIEW

**Comment by pekam** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/AbstractComponentConnector.java, line 503 at r1](https://reviewable.io:443/reviews/vaadin/framework/10253#-KxgcpPRucYeW91cUyuW:-KxgcpPRucYeW91cUyuX:b-uu47sk) ([raw file](https://github.com/vaadin/framework/blob/0db88b5b4bbbfd618b85f4d2d3bdf824fd16737e/client/src/main/java/com/vaadin/client/ui/AbstractComponentConnector.java#L503)):*
> ```Java
>         // Add or remove error indicator element
>         if (widget instanceof HasErrorIndicatorElement) {
>             HasErrorIndicatorElement e = (HasErrorIndicatorElement) widget;
> ```

No one-letter variables please

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/datefield/DateFieldConnector.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10253#-KxgiUXfS-ubvl2SI6XV:-KxgiUXfS-ubvl2SI6XW:b-d8e62q) ([raw file](https://github.com/vaadin/framework/blob/0db88b5b4bbbfd618b85f4d2d3bdf824fd16737e/compatibility-client/src/main/java/com/vaadin/v7/client/ui/datefield/DateFieldConnector.java#L80)):*
> ```Java
>         super.updateFromUIDL(uidl, client);
> 
>         calendar.calendar.setDateTimeService(calendar.getDateTimeService());
> ```

Could consider other variable name than `calendar` here because these `calendar.calendar` are a bit confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10253)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/AbstractComponentConnector.java, line 503 at r1](https://reviewable.io:443/reviews/vaadin/framework/10253#-KxgcpPRucYeW91cUyuW:-KxgmoR4FJTILJ_Og4J7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0db88b5b4bbbfd618b85f4d2d3bdf824fd16737e/client/src/main/java/com/vaadin/client/ui/AbstractComponentConnector.java#L503)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

No one-letter variables please
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/datefield/DateFieldConnector.java, line 80 at r1](https://reviewable.io:443/reviews/vaadin/framework/10253#-KxgiUXfS-ubvl2SI6XV:-KxgpA3sIUSY3Cinwhsy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0db88b5b4bbbfd618b85f4d2d3bdf824fd16737e/compatibility-client/src/main/java/com/vaadin/v7/client/ui/datefield/DateFieldConnector.java#L80)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Could consider other variable name than `calendar` here because these `calendar.calendar` are a bit confusing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10253)*

**Comment by pekam** [comment]
Need to investigate the test failure:
```
CalendarNavigationTest.calendarNavigation_backAndForwardInWeekView_navigationWorks:43 expected:<Sunday[ 10/29/17]> but was:<Sunday[]>
```

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10253#-:-Kxh2FcDqonWMApqTmUR:b-vkldd6)*

**Comment by asashour** [comment]
This error is not related to this PR, this is a general issue in the build server currently, all recent PRs fails for the same reason. I am trying to investigate.

**Pull request merged**
