### PR TITLE
Make view parameter map available in ViewChangeEvent

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9529)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 788 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyvYnIOdCSM5EsQu5:-KmZyvYnIOdCSM5EsQu6:b-1r32ty) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/Navigator.java#L788)):*
> ```Java
>      *            from each other
>      * @return The navigation state as Map<String, String>.
>      * @since
> ```

Could mark these already to 8.1

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 817 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz56oIxTmgkrc8xh1:-KmZz56oIxTmgkrc8xh2:b4af9j9) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/Navigator.java#L817)):*
> ```Java
>      *            the string (typically one character) used to separate values
>      *            from each other
>      * @param
> ```

empty @param

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz0nUc5mMgyfHCW5X:-KmZz0nUc5mMgyfHCW5Y:bptolne) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L114)):*
> ```Java
>          *
>          * @return navigation parameters (potentially bookmarkable) for the new
>          *         view
> ```

@since 8.1

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyfRDtlKbY7KrRYaY:-KmZyfRDtlKbY7KrRYaZ:b-7m5mqi) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L116)):*
> ```Java
>          *         view
>          */
>         public Map<String, String> getParameterMap() {
> ```

The Navigator speaks of StateParameterMap, and the event of ParameterMap. Why the distinction and what's the difference?

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz3MKmaqr3MmS0abB:-KmZz3MKmaqr3MmS0abC:bptolne) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L128)):*
> ```Java
>          * @return navigation parameters (potentially bookmarkable) for the new
>          *         view
>          * @since
> ```

@since 8.1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9529)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 788 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyvYnIOdCSM5EsQu5:-Km_RkOCVTDiyO0A8zLC:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/Navigator.java#L788)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could mark these already to 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/navigator/Navigator.java, line 817 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz56oIxTmgkrc8xh1:-Km_RkgCoKieLxpEuImI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/Navigator.java#L817)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

empty @param
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 114 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz0nUc5mMgyfHCW5X:-Km_RqBm4yaokESSljbL:b-l9yjlf) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L114)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Poor Since getting mentioned all the time

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyfRDtlKbY7KrRYaY:-Km_S3jjhRsKN0gxt94J:b7mhknu) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L116)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The Navigator speaks of StateParameterMap, and the event of ParameterMap. Why the distinction and what's the difference?
</blockquote></details>

Navigator includes `state` to indicate where it gets the parameters from. Here it is obvious what it refers to. If one should change, I would rather change `Navigator`

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZz3MKmaqr3MmS0abB:-Km_S2LUcFmkTnurVpqR:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L128)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9529)*

**Comment by tsuoanttila** [comment]
*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyfRDtlKbY7KrRYaY:-Km_aOYXyZTVMEG2RhrU:b-z64kw0) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L116)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Navigator includes `state` to indicate where it gets the parameters from. Here it is obvious what it refers to. If one should change, I would rather change `Navigator`
</blockquote></details>

What other parameter map it could be in the case of Navigator?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9529)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9529)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/navigator/ViewChangeListener.java, line 116 at r1](https://reviewable.io:443/reviews/vaadin/framework/9529#-KmZyfRDtlKbY7KrRYaY:-Kmec2_BkSGMhBiqe9tr:b3ujxbh) ([raw file](https://github.com/vaadin/framework/blob/198e7175388a20793f421fdb716b91f5f1501dc1/server/src/main/java/com/vaadin/navigator/ViewChangeListener.java#L116)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

What other parameter map it could be in the case of Navigator?
</blockquote></details>

After a quick team discussion, we decided that this is fine. Dismissed Artur since he's once again blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9529)*

**Pull request merged**
