### PR TITLE
Memory leak fix in ConnectorTracker

### PR DESCRIPTION
**Pull request by doggy-dev**
Now StreamVariable is removed also from streamVariableToSeckey.
https://github.com/vaadin/framework/issues/10695 #10695

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10743)

### CODE REVIEW

**Comment by elmot** [comment]
@doggy-dev, thanks for your contribution. Please sign our CLA (please click a yellow button and follow the instructions). We can not merge this until you have signed it.

**Comment by doggy-dev** [comment]
@elmot I'm going to do that. Let me just do a cople of more tests next week before that.

**Comment by doggy-dev** [comment]
I've tested it locally - works for me :)

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10743#-:-LFqnI8nBekY72scOwMU:bnfp4nl)*

**Comment by tsuoanttila** [comment]
cherry-picked the patch for master. Some issue with our validation build agents, but will try to get this into 7.7 ASAP as well.

**Pull request merged**
