### PR TITLE
Initial implementation of ComponentRenderer for Grid

### LINKED ISSUE #8622: Enable components in Grid body cells

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #8622

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8743)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java, line 35 at r2](https://reviewable.io:443/reviews/vaadin/framework/8743#-KebyYJisoHfY6Lj4Ae9:-KebyYJjMnnQV6ioTeIn:b-it1m9d) ([raw file](https://github.com/vaadin/framework/blob/447594a943a41b0a87c4bd001e4b7cd24fcd0d45/uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java#L35)):*
> ```Java
> 
>             TextField textField = new TextField();
>             textField.setValue(t);
> ```

Would it be better to use some other value change mode? Otherwise, is there a risk of losing changes when the component is removed if lazy is not fast enough? Or are we guaranteed to get the message?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8743)*

**Comment by ahie** [comment]
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 508 at r3](https://reviewable.io:443/reviews/vaadin/framework/8743#-Kec8coq5S1pMUW7576d:-Kec8coq5S1pMUW7576e:bz4w8j4) ([raw file](https://github.com/vaadin/framework/blob/a7043e1852fe709025add82dff29c57244b56fac/documentation/components/components-grid.asciidoc#L508)):*
> when data or selection changes

Also on scroll? Could be less specific like in the javadoc: "Components will occasionally be generated again during runtime" to avoid any incorrect assumptions.

---

*[documentation/components/components-grid.asciidoc, line 509 at r3](https://reviewable.io:443/reviews/vaadin/framework/8743#-KecAL_7klOpq9TgyNF3:-KecAL_7klOpq9TgyNF4:b-vbun9h) ([raw file](https://github.com/vaadin/framework/blob/a7043e1852fe709025add82dff29c57244b56fac/documentation/components/components-grid.asciidoc#L509)):*
> you need to handle storing it yourself

Could use an example of this.

---

*[server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java, line 34 at r2](https://reviewable.io:443/reviews/vaadin/framework/8743#-KebzCLn-kLwRH5_iGyj:-KebzCLn-kLwRH5_iGyk:bnrrphm) ([raw file](https://github.com/vaadin/framework/blob/447594a943a41b0a87c4bd001e4b7cd24fcd0d45/server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java#L34)):*
> eg.

Nit: e.g.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/8743#-Kec8vkUr4Xv7imE138Y:-Kec8vkUr4Xv7imE138Z:bmm1z5g) ([raw file](https://github.com/vaadin/framework/blob/447594a943a41b0a87c4bd001e4b7cd24fcd0d45/uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java#L26)):*
> c

Nit: one letter variables.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridComponentsTest.java, line 14 at r2](https://reviewable.io:443/reviews/vaadin/framework/8743#-Kec9foNBAxv4r9w-Qt1:-Kec9foNBAxv4r9w-Qt2:bsrxnq5) ([raw file](https://github.com/vaadin/framework/blob/447594a943a41b0a87c4bd001e4b7cd24fcd0d45/uitest/src/test/java/com/vaadin/tests/components/grid/GridComponentsTest.java#L14)):*
> ```Java
> import com.vaadin.tests.tb3.MultiBrowserTest;
> 
> public class GridComponentsTest extends MultiBrowserTest {
> ```

Could add a test that checks that the components are correctly detached.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8743)*

**Comment by hesara** [comment]
Review status: 5 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/components/components-grid.asciidoc, line 519 at r3](https://reviewable.io:443/reviews/vaadin/framework/8743#-KecNBneJFAeVJKDnha5:-KecNBneJFAeVJKDnha6:b-6j6qr2) ([raw file](https://github.com/vaadin/framework/blob/a7043e1852fe709025add82dff29c57244b56fac/documentation/components/components-grid.asciidoc#L519)):*
> ```AsciiDoc
>       button.addClickListener(click -> 
>             Notification.show("Clicked: " + person.toString()));
>       return button
> ```

missing semicolon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8743)*

**Comment by hesara** [comment]
Reviewed 1 of 4 files at r4.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8743)*

**Comment by pleku** [comment]
Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8743)*

**Comment by heruan** [comment]
Will the component renderer be explicitly used or it will be the default when column value is a `Component`?

**Comment by Legioth** [comment]
> Will the component renderer need to be explicitly used or it will be the default when column value is a `Component`

@heruan, It must be set explicitly. Because of type erasure, there's no way for the runtime to know the column type. The type can be know only when using `String propertyName` instead of a `ValueProvider`, but it would probably be quite confusing if those two variants would cause different renderers to be used.

**Pull request merged**
