### PR TITLE
Remove non working setHeight methods from Tree. Fixes #9629

### LINKED ISSUE #9629: Vaadin 8.1 unable to set height for the Tree component
Tree's setHeight methods have JavaDoc "This component's height is always set to be undefined. Calling this method will have no effect."

This makes it impossible for the developer to define where Tree's scrollbars are rendered to.

e.g. here I'd like to have the scrollbars on the bottom of the UI regardless of how many items I have in the Tree
screenshot from 2017-07-03 14-22-02

Online demo (takes a minute or two to boot up as it upgrades to latest snapshot on opening):
https://vaadinfiddle.com/editor/#!container/a5878bda19a3b90e20947fcfc09c8e3608ad93b23d77ab3fc2d9d897f3ed5808/src/main/java/org/vaadin/vaadinfiddle/MyUI.java

Demo project:
[treegridheight.zip](https://github.com/vaadin/framework/files/1119470/treegridheight.zip)

Tested using Vaadin 8.1 SNAPSHOT vaadin-server-8.1-20170703.100423-235 & chromium browser on Linux

### PR DESCRIPTION
**Pull request by Wnt**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9631)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9631#-KoBCXYtf__rWPJFfPuQ:-KoBCXYtf__rWPJFfPuR:b-l86176) (no related file):*
Started a test build with this.

@tsuoanttila any opinions on the approach or objections to it?
It would make Tree behave more like other components and less like the weird V7 Tree, but are there any less obvious complications?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9631)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9631#-KoBCXYtf__rWPJFfPuQ:-KoBgk8RYc3yKkkaXdlD:b3defh6) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Started a test build with this.

@tsuoanttila any opinions on the approach or objections to it?
It would make Tree behave more like other components and less like the weird V7 Tree, but are there any less obvious complications?
</blockquote></details>

No new test failures caused by this change, but I'd also like to have Teemu's opinion on the matter if possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9631)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9631#-KoBCXYtf__rWPJFfPuQ:-KoBhV1U_EmoUUDlKu3j:b-wj9e0d) (no related file):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

No new test failures caused by this change, but I'd also like to have Teemu's opinion on the matter if possible.
</blockquote></details>

The only issue with this is the difference to the v7 tree as well as possibly some column sizing issues (there is a chance of extra horizontal scrollbar). At least a test for minimal size tree should be added. Also need to check that the Composite correctly passes the values to the root component. Other than that, I don't mind providing new features to the Tree.

Need to consider if we should bring in the set height by rows to the Tree when supporting other size settings as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9631)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9631#-KoBCXYtf__rWPJFfPuQ:-KoBlPxpUWlU0vjaz20K:b-azrjkk) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

The only issue with this is the difference to the v7 tree as well as possibly some column sizing issues (there is a chance of extra horizontal scrollbar). At least a test for minimal size tree should be added. Also need to check that the Composite correctly passes the values to the root component. Other than that, I don't mind providing new features to the Tree.

Need to consider if we should bring in the set height by rows to the Tree when supporting other size settings as well.
</blockquote></details>

as this is not an API breaking change, decided to postpone this until better tested - adding a release notes mention about the limitation for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9631)*

**Comment by hesara** [comment]
Mentioning the limitation in #9633 - please remove that mention when merging this change.

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9631)*

**Pull request merged**
