### PR TITLE
Upload should preserve MIMEType after first selection

### LINKED ISSUE #11698: Vaadin 8 After first Upload the acceptMimeTypes resets
Vaadin Version: 8.8.2
Browser: any

If you set the accepted mime types and than search a file it works fine but if u Upload and than search a file there are no accepted mime types anymore.

The Problem is in VUpload rebuildPanel() the input element will be created new but the accept will not be set.

### PR DESCRIPTION
**Pull request by anasmi**
Fix #11698

Automated test is not run locally, need to continue with it

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11745)

### CODE REVIEW

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11745)* status: all files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 261 at r1](https://reviewable.io/reviews/vaadin/framework/11745#-LrIrlmp-2zFTTOaTJIq:-LrIrlmqC3BE4cgccLne:b-u9p81d) ([raw file](https://github.com/vaadin/framework/blob/9b7931321623c0c772ec230ff76aee067c1d3dd8/client/src/main/java/com/vaadin/client/ui/VUpload.java#L261)):*
> ```Java
>         if (acceptMimeTypes != null && !acceptMimeTypes.isEmpty()) {
>             InputElement.as(fu.getElement()).setAccept(acceptMimeTypes);
>         }
> ```

Should there be an else block here?

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11745)* status: all files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 261 at r1](https://reviewable.io/reviews/vaadin/framework/11745#-LrIrlmp-2zFTTOaTJIq:-LrIsLbS86MpFy6TC9e1:b3rdbel) ([raw file](https://github.com/vaadin/framework/blob/9b7931321623c0c772ec230ff76aee067c1d3dd8/client/src/main/java/com/vaadin/client/ui/VUpload.java#L261)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

Should there be an else block here?
</blockquote></details>

That is, if acceptMimeTypes is cleared / set to null, should that be handled as well?

**Comment by anasmi** [comment]
___
*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 261 at r1](https://reviewable.io/reviews/vaadin/framework/11745#-LrIrlmp-2zFTTOaTJIq:-LrIsOfz62XvUBNGatLT:btbum40) ([raw file](https://github.com/vaadin/framework/blob/9b7931321623c0c772ec230ff76aee067c1d3dd8/client/src/main/java/com/vaadin/client/ui/VUpload.java#L261)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

That is, if acceptMimeTypes is cleared / set to null, should that be handled as well?
</blockquote></details>

I think it's not needed, as  `setAccept(null)`==not setting anything.

**Comment by anasmi** [comment]
___
*[client/src/main/java/com/vaadin/client/ui/VUpload.java, line 261 at r1](https://reviewable.io/reviews/vaadin/framework/11745#-LrIrlmp-2zFTTOaTJIq:-LrIsajfAF6_7y90ovHe:byw2el) ([raw file](https://github.com/vaadin/framework/blob/9b7931321623c0c772ec230ff76aee067c1d3dd8/client/src/main/java/com/vaadin/client/ui/VUpload.java#L261)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

I think it's not needed, as  `setAccept(null)`==not setting anything.  
</blockquote></details>

In case the state is changed, it's going through `setAcceptMimeTypes` and here the  VUpload is just re-created from scratch every single time someone upload anything

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11745#-:-LrIudWE1hl6M480bAI1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
