### PR TITLE
Allow changing renderers after column creation

### LINKED ISSUE #8250: Provide an API to set a Grid column Renderer after column creation
In Vaadin 8.0.0.beta1 there's no way to set a Renderer to a Grid column that has been already created. This makes it harder to separate creation and configuration logic which is required in some designs.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Closes #8250

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8841)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBkLbJequGYj4fOJoD:-KfBkLbKdcEhxrLYiL-t:bldv1l5) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L72)):*
> ```Java
>     }
> 
>     @OnStateChange("hierarchyColumnId")
> ```

No other state changes require this? Is the super.onStateChanged() annotated to be called otherwise if still needed?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1819 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBl8WznjwXqRn2fg46:-KfBl8WznjwXqRn2fg47:biv7c9p) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/server/src/main/java/com/vaadin/ui/Grid.java#L1819)):*
> ```Java
>         /**
>          * Sets the Renderer for this Column. Setting the renderer will cause
>          * all currently available row data to be recreated and send to the
> ```

... sent ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by hesara** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBlt3nbUdIZ8x1oBZD:-KfBlt3olumZ1cl20KRo:b-hogwc2) (no related file):*
(Note: if this is to be included in 8.0.x, needs a selective pick without the TreeGrid specific parts)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by tsuoanttila** [comment]
*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBkLbJequGYj4fOJoD:-KfBtai8D6ZzNgY7OUR7:b-35e3cy) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L72)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

No other state changes require this? Is the super.onStateChanged() annotated to be called otherwise if still needed?
</blockquote></details>

onStateChanged is the generic method which is called always. The old version was looking for changes in "columns" which does not exist in GridState anymore since 8.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by pleku** [comment]
Reviewed 2 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBxlH0upN5TbRH4BDH:-KfBxlH0upN5TbRH4BDI:b-f7vohw) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L73)):*
> ```Java
> 
>     @OnStateChange("hierarchyColumnId")
>     void updateHierarchyColumn() {
> ```

If you apply the changes to TreeGrid, it makes this patch not directly portable to 8.0 maintenance versions I think

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBxtn4lQFJuSdGUJad:-KfBxtn5rKEJuF1JQfz1:b-s0xse3) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L74)):*
> ```Java
>     @OnStateChange("hierarchyColumnId")
>     void updateHierarchyColumn() {
>         Scheduler.get().scheduleFinally(() -> {
> ```

Why is this changed to be done _finally_ ? Please answer in code

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1826 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBxPfrjP_P86t5NwLn:-KfBxPfrjP_P86t5NwLo:bz1h07s) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/server/src/main/java/com/vaadin/ui/Grid.java#L1826)):*
> ```Java
>          * @return this column
>          */
>         public Column<T, V> setRenderer(Renderer<? super V> renderer) {
> ```

I wonder what we should do if the user tries to override the "HierarchyRenderer" in TreeGrid, just allowing it may cause WTFs for users doing it by accident, but then again it might be desired for some cases...

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridRendererSwitchTest.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBwQqpKghaokFQIpPp:-KfBwQqpKghaokFQIpPq:bd6gt53) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/uitest/src/test/java/com/vaadin/tests/components/grid/GridRendererSwitchTest.java#L15)):*
> ```Java
> 
>     @Test
>     public void testSwitchRenderer() {
> ```

Care to add a test where during same request when the renderer for the column is changed, the column order also changes, e.g. column is moved to first/last ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 73 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBxlH0upN5TbRH4BDH:-KfBylp94c1IPtgNbZ3a:bobvfe2) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L73)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

If you apply the changes to TreeGrid, it makes this patch not directly portable to 8.0 maintenance versions I think
</blockquote></details>

Meh was already mentioned by Henri

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfC8C3ozR1akGaHAr2L:-KfC8C3ozR1akGaHAr2M:bylofre) (no related file):*
Could mention in https://github.com/vaadin/framework/blob/master/documentation/components/components-grid.asciidoc#column-renderers e.g. in the first example that the renderer can be changed on the fly and state that it will cause a complete refresh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfFozCDiZqn1CgJzcLC:-KfFozCDiZqn1CgJzcLD:b-2mrx17) ([raw file](https://github.com/vaadin/framework/blob/17f6d5eb2173a0736714cb36f48f02ddc9708e73/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L174)):*
> ```Java
>                                              browserEventHandlers.@java.util.List::set(*)(5, eventHandler);
>                                              }-*/;
> ```

Whitespace changes

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 180 at r2](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfFq43u8majYV8mrAg1:-KfFq43u8majYV8mrAg2:b-98ju4f) ([raw file](https://github.com/vaadin/framework/blob/17f6d5eb2173a0736714cb36f48f02ddc9708e73/server/src/main/java/com/vaadin/ui/TreeGrid.java#L180)):*
> ```Java
>                         TreeGrid.this.getState(false).hierarchyColumnId)) {
>                     throw new RuntimeException(
>                             "Changing the renderer of the hierarchy column is not allowed.");
> ```

Sould mention this in the `setHierarchyColumn` method javadocs, that the renderer cannot be changed for the hierarchy column

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfC8C3ozR1akGaHAr2L:-KfGC-zL-GR4-b42Xg1a:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could mention in https://github.com/vaadin/framework/blob/master/documentation/components/components-grid.asciidoc#column-renderers e.g. in the first example that the renderer can be changed on the fly and state that it will cause a complete refresh
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBkLbJequGYj4fOJoD:-KfC4nq6hiHqTBMTPPas:b83nklv) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L72)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

onStateChanged is the generic method which is called always. The old version was looking for changes in "columns" which does not exist in GridState anymore since 8.0
</blockquote></details>

If there are some extra cases where this should be executed, we are not aware of those yet. Can be improved if/when they are found.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfFozCDiZqn1CgJzcLC:-KfG4yXm_L5uCyILDWSS:b-v9zpdz) ([raw file](https://github.com/vaadin/framework/blob/17f6d5eb2173a0736714cb36f48f02ddc9708e73/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L174)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Whitespace changes
</blockquote></details>

Need to manually revert these. My eclipse is messing up with these native methods for some reason..

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1819 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBl8WznjwXqRn2fg46:-KfG5VZl20VrTjq6sKZD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/server/src/main/java/com/vaadin/ui/Grid.java#L1819)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

... sent ...
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1826 at r1](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfBxPfrjP_P86t5NwLn:-KfC4SPKl_d-l9OhvtQC:b4o3pi4) ([raw file](https://github.com/vaadin/framework/blob/6bf7d19ecd1240e41a2e41ddbc82545f57a0e063/server/src/main/java/com/vaadin/ui/Grid.java#L1826)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I wonder what we should do if the user tries to override the "HierarchyRenderer" in TreeGrid, just allowing it may cause WTFs for users doing it by accident, but then again it might be desired for some cases...
</blockquote></details>

Was thinking about that case already. Basically we need to a) either inform the TreeGridConnector of a renderer change or b) prevent renderer change in hierarchy column.  Prevention can be javadocced in at least setRenderer and setHierarchyColumn

---

*[server/src/main/java/com/vaadin/ui/TreeGrid.java, line 180 at r2](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfFq43u8majYV8mrAg1:-KfGBDTCUdGBbWXXeShT:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/17f6d5eb2173a0736714cb36f48f02ddc9708e73/server/src/main/java/com/vaadin/ui/TreeGrid.java#L180)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sould mention this in the `setHierarchyColumn` method javadocs, that the renderer cannot be changed for the hierarchy column
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java, line 174 at r2](https://reviewable.io:443/reviews/vaadin/framework/8841#-KfFozCDiZqn1CgJzcLC:-KfGJRTmztsSen0cPHxx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/17f6d5eb2173a0736714cb36f48f02ddc9708e73/client/src/main/java/com/vaadin/client/connectors/treegrid/TreeGridConnector.java#L174)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Need to manually revert these. My eclipse is messing up with these native methods for some reason..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8841)*

**Pull request merged**
