### PR TITLE
enable setting non-selected default value for DateField

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Requested feature: allow setting DateField to a certain starting point without selecting a value.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9745)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VDateField.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5u03a2spCHOdPZ7DZ:-Kr5u03a2spCHOdPZ7D_:b-iuu07v) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/client/src/main/java/com/vaadin/client/ui/VDateField.java#L103)):*
> ```Java
>     }
> 
>     public void setDefaultDate(Date date) {
> ```

Missing javadoc and since tags for new public methods.

Please enable the option that allows project maintainers to make edits to the PR branch if not already on for updating since tag values.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5wfIkXeEC3Vr_NrbG:-Kr5wfIkXeEC3Vr_NrbH:b-u5iisx) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java#L102)):*
> ```Java
>     }
> 
>     protected Map<R, Integer> getDefaultValues(UIDL uidl) {
> ```

see the comment in AbstractDateField about state

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5wQ8ro9G9-R0nk45K:-Kr5wQ8ro9G9-R0nk45L:bqnovd8) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L206)):*
> ```Java
>                 value = getDatePart(currentDate, res);
>             }
>             String variableName = getResolutionVariable(res);
> ```

(I'd prefer having this in AbstractFieldState if possible, with suitable since tag on the field - perhaps beforeClientResponse() could update an array of part values in state)

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 523 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5vkT4r6Zty3B6GH33:-Kr5vkT4r6Zty3B6GH34:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L523)):*
> ```Java
>      * @see #setDefaultValue(Temporal)
>      * @return the default value
>      */
> ```

since tag

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5vm4Z-EZHfhByWgZ2:-Kr5vm4Z-EZHfhByWgZ3:btrsgnj) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L534)):*
> ```Java
>      *
>      * @param defaultValue
>      */
> ```

since tag

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldWithDefaultValueTest.java, line 44 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5uyVTH88olvbA0CIB:-Kr5uyVTH88olvbA0CIC:bvyb172) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldWithDefaultValueTest.java#L44)):*
> ```Java
>         .findElements(By.cssSelector(
>                 ".v-datefield-calendarpanel-month")).get(0);
>         
> ```

extra empty line with whitespace; strange formatting of the lines before that

---

*[uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldWithDefaultValueTest.java, line 56 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5vZ2phI6jCLqcDiIV:-Kr5vZ2phI6jCLqcDiIW:b-4touj6) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/uitest/src/test/java/com/vaadin/tests/components/datefield/DateFieldWithDefaultValueTest.java#L56)):*
> ```Java
>     }
> 
>     private void clickDateDatePickerButton(String id) {
> ```

why not simply use DateFieldElement.openPopup()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9745)*

**Comment by hesara** [comment]
Some review comments + needs merge with latest master.

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java, line 102 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5wfIkXeEC3Vr_NrbG:-KrAzM5Vbzn5k4xCIAdJ:b-ur5hgi) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/client/src/main/java/com/vaadin/client/ui/datefield/AbstractDateFieldConnector.java#L102)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see the comment in AbstractDateField about state
</blockquote></details>

(we will probably do this when converting ADF not to be a legacy component, so marking as a non-blocker)

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/framework/9745#-Kr5wQ8ro9G9-R0nk45K:-KrAzYut8y4aI22OnWGH:b-ur5hgi) ([raw file](https://github.com/vaadin/framework/blob/759ccc295a67fd59726ca8ab927e8e648fbfc962/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L206)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(I'd prefer having this in AbstractFieldState if possible, with suitable since tag on the field - perhaps beforeClientResponse() could update an array of part values in state)
</blockquote></details>

(we will probably do this when converting ADF not to be a legacy component, so marking as a non-blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9745)*

**Comment by hesara** [comment]
I can take over this change, make any required changes.

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9745#-:-KrB55tDNT50O5nA4OOP:bnfp4nl)*

**Pull request merged**
