### PR TITLE
Modifiers to follow Java Specification suggestions

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10050)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 116 of 117 files at r1.
Review status: 116 of 117 files reviewed at latest revision, 1 unresolved discussion.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/TransactionalPropertyWrapper.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/10050#-KuYQRCJoOxx1UP1m0ks:-KuYQRCJoOxx1UP1m0kt:bi39b4q) ([raw file](https://github.com/vaadin/framework/blob/d649b55e77db67bcf824ace10d1dd4ec7e86a6fc/compatibility-server/src/main/java/com/vaadin/v7/data/util/TransactionalPropertyWrapper.java#L85)):*
> ```Java
> 
>     @Override
>     public Class<? extends T> getType() {
> ```

Can this change break anything? As it looks like an API level change in the compatibility packages, I don't think it belongs in an otherwise completely safe cleanup patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10050)*

**Comment by asashour** [comment]
Review status: 116 of 123 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[compatibility-server/src/main/java/com/vaadin/v7/data/util/TransactionalPropertyWrapper.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/10050#-KuYQRCJoOxx1UP1m0ks:-KuYRkNp5q1TOomPZngV:b-v6fn99) ([raw file](https://github.com/vaadin/framework/blob/d649b55e77db67bcf824ace10d1dd4ec7e86a6fc/compatibility-server/src/main/java/com/vaadin/v7/data/util/TransactionalPropertyWrapper.java#L85)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Can this change break anything? As it looks like an API level change in the compatibility packages, I don't think it belongs in an otherwise completely safe cleanup patch.
</blockquote></details>

Reverted. Yes, that doesn't belong here. I guess I should refrain from combining tasks, as I guess PR bombardments is not a good thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10050)*

**Comment by hesara** [comment]
A conflict to resolve in VUI, otherwise looks ok to me. (I also noted some other cleanup here apart from modifier order, but it is quite internal and inoffensive so ok to me.)

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10050#-:-KuY_NIWVGjvKayun3eA:b-utqtok)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10050#-:-KuZON_sbVyAbcGGhgKZ:bnfp4nl)*

**Comment by asashour** [comment]
Done.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10050#-:-KuZOOmfCfS1WzUsFi7e:b-896fix)*

**Pull request merged**
