### PR TITLE
7.7 new atmosphere

### PR DESCRIPTION
**Pull request by elmot**
Atmosphere-runtime 2.2.13

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)

### CODE REVIEW

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)* status: 0 of 7 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11151#-LL9dbxIERaCFRQemXja:-LL9dbxJ293S-FXsf6CL:bg33t4i) (no related file):*
Blocked until full testing is done

---

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)* status: all files reviewed, 1 unresolved discussion

**Review by tsuoanttila — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)* status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11151#-LL9dbxIERaCFRQemXja:-LLY0n050JFGAzTOPGax:b-un2up9) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Blocked until full testing is done
</blockquote></details>

You're blocking your own PR. We should get this moving.

---

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)* status: all files reviewed, 1 unresolved discussion (waiting on @elmot)

**Review by elmot — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11151)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11151#-LL9dbxIERaCFRQemXja:-LLZ315f1-eok8UIAnjC:b-tj4d4x) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

You're blocking your own PR. We should get this moving.
</blockquote></details>

After some testing the upgrade looks working

---

**Pull request merged**
