### PR TITLE
Migrate wiki articles to Vaadin documentation

### PR DESCRIPTION
**Pull request by hezamu**
(cherry picked from commit 405e8bc1d4ad89e5595bcec5ab10e6f1d932355e)

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9912)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, 4 of 4 files at r9, 7 of 12 files at r10.
Review status: 25 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/articles/contents.asciidoc, line 28 at r9](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB0k1bbjtcRcWKkv3C:-KtB0k1bbjtcRcWKkv3D:b-cmhyzb) ([raw file](https://github.com/vaadin/framework/blob/d3dfc569a56e9fa544b23645926cc39d13a8243c/documentation/articles/contents.asciidoc#L28)):*
> ```AsciiDoc
> - link:UsingPolling.asciidoc[Using polling]
> - link:FindingTheCurrentUIAndPageAndVaadinSession.asciidoc[Finding the current UI and page and Vaadin Session]
> - link:CreatingAnApplicationTHatPreservesStateOnRefresh.asciidoc[Creating an application that preserves state on refresh]
> ```

THat -> That (also in filename)?

---

*[documentation/articles/RememberToTheSetTheLocale.asciidoc, line 177 at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB1ZuxCijCBJROJYDS:-KtB1ZuxCijCBJROJYDT:b7xeaja) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/RememberToTheSetTheLocale.asciidoc#L177)):*
> ```AsciiDoc
> ....
> 
> image:http://i.imgur.com/w9CViCR.png[http://i.imgur.com/w9CViCR.png,title="http://i.imgur.com/w9CViCR.png"]
> ```

(could move this to the repo, or at least have a better title)

---

*[documentation/articles/SendingEventsFromTheClientToTheServerUsingRPC.asciidoc, line 2 at r9](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB1BNs46vjoV3uGe9J:-KtB1BNs46vjoV3uGe9K:bb72wtb) ([raw file](https://github.com/vaadin/framework/blob/d3dfc569a56e9fa544b23645926cc39d13a8243c/documentation/articles/SendingEventsFromTheClientToTheServerUsingRPC.asciidoc#L2)):*
> ```AsciiDoc
> [[sending-events-from-the-client-to-the-server-using-r-p-c]]
> Sending events from the client to the server using r p c
> ```

RPC?

---

*[documentation/articles/img/mockapp-ui.png, line 0 at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB2Ea4Yebw052oeoDq:-KtB2Ea4Yebw052oeoDr:b4pld0o) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/img/mockapp-ui.png#L0)):*
same picture as figure2s.png?

---

*[documentation/articles/img/shasum.png, line 0 at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB23Qg2h5Rab75Djao:-KtB23Qg2h5Rab75Djap:bnra11l) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/img/shasum.png#L0)):*
same picture as 1newa.png?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
Reviewed 1 of 12 files at r10.
Review status: 26 of 30 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
Review status: 24 of 36 files reviewed at latest revision, 5 unresolved discussions.

---

*[documentation/articles/contents.asciidoc, line 28 at r9](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB0k1bbjtcRcWKkv3C:-Ktjd7sq2AS4v7NxLbrh:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/d3dfc569a56e9fa544b23645926cc39d13a8243c/documentation/articles/contents.asciidoc#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

THat -> That (also in filename)?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/RememberToTheSetTheLocale.asciidoc, line 177 at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB1ZuxCijCBJROJYDS:-KtjdYZBSzw0h4aDPkEU:b8jtlgj) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/RememberToTheSetTheLocale.asciidoc#L177)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could move this to the repo, or at least have a better title)
</blockquote></details>

Fixed the title. How the files referred by the article is up to the author.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/SendingEventsFromTheClientToTheServerUsingRPC.asciidoc, line 2 at r9](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB1BNs46vjoV3uGe9J:-KtjeGcPEkq4waysu_eJ:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/d3dfc569a56e9fa544b23645926cc39d13a8243c/documentation/articles/SendingEventsFromTheClientToTheServerUsingRPC.asciidoc#L2)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

RPC?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/img/mockapp-ui.png, line  at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB2Ea4Yebw052oeoDq:-KtjgSnlhyeLio_gZwFo:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/img/mockapp-ui.png#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

same picture as figure2s.png?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/img/shasum.png, line  at r10](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtB23Qg2h5Rab75Djao:-KtjgW7Hv4HdE5-j3HB5:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/c3073f8f9ed0de62db04492c3733a329d0c0c719/documentation/articles/img/shasum.png#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

same picture as 1newa.png?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
Reviewed 1 of 13 files at r10, 3 of 6 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 5 of 5 files at r16.
Review status: 32 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/articles/MVCBasicsInITMillToolkit.asciidoc, line 66 at r16](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtjjQz0Z8CPfTrQcOg8:-KtjjQz0Z8CPfTrQcOg9:b7dtvte) ([raw file](https://github.com/vaadin/framework/blob/6712114e3ebf967ef83da53af7a548d99f2cebc3/documentation/articles/MVCBasicsInITMillToolkit.asciidoc#L66)):*
> ```AsciiDoc
>   @Override
>   public void init() {
>   	// sets the current application to ThreadLocal.
> ```

(mixed style of whitespace in code examples, could convert also this to spaces)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r11.
Review status: 33 of 34 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/articles/img/MVCBasicsProject.zip, line 0 at r16](https://reviewable.io:443/reviews/vaadin/framework/9912#-Ktjj_GYusFUqIe2rbEe:-Ktjj_GYusFUqIe2rbEf:b-co2g6g) ([raw file](https://github.com/vaadin/framework/blob/6712114e3ebf967ef83da53af7a548d99f2cebc3/documentation/articles/img/MVCBasicsProject.zip#L0)):*
ZIP to check for anything suspicious or otherwise problematic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/img/MVCBasicsProject.zip, line  at r16](https://reviewable.io:443/reviews/vaadin/framework/9912#-Ktjj_GYusFUqIe2rbEe:-KtjlManwXL5qhcRjTlM:bckahat) ([raw file](https://github.com/vaadin/framework/blob/6712114e3ebf967ef83da53af7a548d99f2cebc3/documentation/articles/img/MVCBasicsProject.zip#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

ZIP to check for anything suspicious or otherwise problematic
</blockquote></details>

Took a look, just a basic zipped IT Mill Toolkit project with sources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hezamu** [comment]
*[documentation/articles/MVCBasicsInITMillToolkit.asciidoc, line 66 at r16](https://reviewable.io:443/reviews/vaadin/framework/9912#-KtjjQz0Z8CPfTrQcOg8:-KtjnkDh7sVHlqc5UNbU:b-886gsx) ([raw file](https://github.com/vaadin/framework/blob/6712114e3ebf967ef83da53af7a548d99f2cebc3/documentation/articles/MVCBasicsInITMillToolkit.asciidoc#L66)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(mixed style of whitespace in code examples, could convert also this to spaces)
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r11, 1 of 1 files at r17.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912#-:-Ktjnti00A-c1sbrHhUS:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r18, 1 of 1 files at r19.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9912)*

**Pull request merged**
