### PR TITLE
Add method for getting complete browser version

### LINKED ISSUE #10461: Add support for accessing complete browser version on client side
`BrowserInfo` and `VBrowserDetails` currently have support for accessing browser major and minor versions.

Add new method `getBrowserVersion()` that returns build and patch version as well whenever available. For current Chrome the return string would be `63.0.3239.84`.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #10461

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10490)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L46_MDe3mGRb6qFGYpq:bslqlwi) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
> ```Java
>      * Gets the complete browser version as string.
>      *
>      * @return the complete browser version or {@code null} if unknown
> ```

in form of?

---

*[client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java, line 68 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_f5jPolMiA1xTjv9:-L46_f5jPolMiA1xTjvA:b-yreijx) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java#L68)):*
> ```Java
>         assertBrowserMajorVersion(bd, 3);
>         assertBrowserMinorVersion(bd, 2);
>         assertBrowserVersion(bd, "3.2.3");
> ```

These changes are going to break tests every now and then because of browser updates. Better to use something like regexps
We can suppose chrome and ff to have 2 or 3 letters in major version, group of letters in other groups etc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by wbadam** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L4A7pVA1XzFgqWHmHYH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

in form of?
</blockquote></details>

Done.

---

*[client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java, line 68 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_f5jPolMiA1xTjv9:-L4A85Q-RnxS7NNLPPqZ:b-e9t29t) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java#L68)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

These changes are going to break tests every now and then because of browser updates. Better to use something like regexps
We can suppose chrome and ff to have 2 or 3 letters in major version, group of letters in other groups etc
</blockquote></details>

In this test the user agent string defined by `SAFARI3_WINDOWS` constant is parsed and not the user agent of the test browser. I think these tests should be fine?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by elmot** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java, line 68 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_f5jPolMiA1xTjv9:-L4ANLHVIYrQz348Mfd8:bvba8q1) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/test/java/com/vaadin/client/VBrowserDetailsUserAgentParserTest.java#L68)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

In this test the user agent string defined by `SAFARI3_WINDOWS` constant is parsed and not the user agent of the test browser. I think these tests should be fine?
</blockquote></details>

Ok, this does not work over real browsers

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 252 at r3](https://reviewable.io:443/reviews/vaadin/framework/10490#-L4AO18nmwUT8lqUyhjX:-L4AO18oNhQIbDvIh93K:b-izlezy) ([raw file](https://github.com/vaadin/framework/blob/26e83cd6de6531648822d86f40aeb72cc19befc4/server/src/main/java/com/vaadin/server/WebBrowser.java#L252)):*
> ```Java
>      * Gets the complete browser version as string.
>      *
>      * @return the complete browser version or {@code null} if unknown
> ```

Please add a short description about version number representation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by elmot** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L4AXvTHIIjtZwHb3Qmr:b-g4gf8r) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See my comment for WebBrowser.java. I mean a little bit more informative javadoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by wbadam** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L4AvkSpt8EydoGm-tXo:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See my comment for WebBrowser.java. I mean a little bit more informative javadoc
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 252 at r3](https://reviewable.io:443/reviews/vaadin/framework/10490#-L4AO18nmwUT8lqUyhjX:-L4AvWvua615yIOqRWCL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/26e83cd6de6531648822d86f40aeb72cc19befc4/server/src/main/java/com/vaadin/server/WebBrowser.java#L252)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Please add a short description about version number representation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L4BoAadf24tLxIiGVCh:b-349zs1) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

See below

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 253 at r4](https://reviewable.io:443/reviews/vaadin/framework/10490#-L4Bo5S23m_rqcAoPdFg:-L4Bo5S23m_rqcAoPdFh:br1fcaz) ([raw file](https://github.com/vaadin/framework/blob/a2e8d367176605cd30b92e7624b14c72c7701f68/server/src/main/java/com/vaadin/server/WebBrowser.java#L253)):*
> number
dots and digits

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by wbadam** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/BrowserInfo.java, line 515 at r2](https://reviewable.io:443/reviews/vaadin/framework/10490#-L46_MDdINyXTMBCOvQe:-L4GZKNbhAJ3I5RoQR8I:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0dd1c10eedccf3631c1057a288c1157239f64bd6/client/src/main/java/com/vaadin/client/BrowserInfo.java#L515)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

See below
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 253 at r4](https://reviewable.io:443/reviews/vaadin/framework/10490#-L4Bo5S23m_rqcAoPdFg:-L4GZBWZQddHx9LaPcsk:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/a2e8d367176605cd30b92e7624b14c72c7701f68/server/src/main/java/com/vaadin/server/WebBrowser.java#L253)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> number
dots and digits
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490#-:-L4GiSYh3U5cnH8KGB1i:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 1 of 4 files at r6, 2 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10490)*

**Pull request merged**
