### PR TITLE
Fire PopStateEvent during UI#doRefresh() for PushStateNavigation UIs.

### PR DESCRIPTION
**Pull request by Darsstar**
Also corrected some javadocs issues IntelliJ noticed.

@tsuoanttila you did #10042 so here is your ping

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10404)

### CODE REVIEW

**Comment by Darsstar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 871 at r1](https://reviewable.io:443/reviews/vaadin/framework/10404#-L-RA2aT-5T8EvnTPzBo:-L-RA2aT-5T8EvnTPzBp:bvpxdt9) ([raw file](https://github.com/vaadin/framework/blob/db5480d45e42d05c9853f4d771c8f6c0ef3b7e3d/server/src/main/java/com/vaadin/ui/UI.java#L871)):*
> ```Java
>         page.updateBrowserWindowSize(oldWidth, oldHeight, false);
> 
>         page.updateLocation(newLocation.toString(), true, firePopStateEventOnRefresh());
> ```

`navigator.navigateTo(navigator.getState())` needs to be called at some point. This is one way to do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10404)*

**Comment by tsuoanttila** [comment]
Actually the initial implementation came from @mstahv at #8209 ! But I'll check it anyway.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 871 at r1](https://reviewable.io:443/reviews/vaadin/framework/10404#-L-RA2aT-5T8EvnTPzBo:-L-VR67PGIEip1MOO_U4:bccvc80) ([raw file](https://github.com/vaadin/framework/blob/db5480d45e42d05c9853f4d771c8f6c0ef3b7e3d/server/src/main/java/com/vaadin/ui/UI.java#L871)):*
<details><summary><i>Previously, Darsstar (Dos Moonen) wrote…</i></summary><blockquote>

`navigator.navigateTo(navigator.getState())` needs to be called at some point. This is one way to do it.
</blockquote></details>

not sure if we should always fire as it is something you might need to take into account with your own specific implementation as well.. At least change the method deciding wether to fire or not `protected`

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 875 at r1](https://reviewable.io:443/reviews/vaadin/framework/10404#-L-VRNKif9wa3PM7INwp:-L-VRNKif9wa3PM7INwq:b-uyv22e) ([raw file](https://github.com/vaadin/framework/blob/db5480d45e42d05c9853f4d771c8f6c0ef3b7e3d/server/src/main/java/com/vaadin/ui/UI.java#L875)):*
> ```Java
>     }
> 
>     private boolean firePopStateEventOnRefresh() {
> ```

Name sounds like I'd be firing an event, but it's actually just a check if it should be done or not.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 876 at r1](https://reviewable.io:443/reviews/vaadin/framework/10404#-L-VQlLuOFFXFn1x4Ma-:-L-VQlLuOFFXFn1x4Ma0:bpdf8yi) ([raw file](https://github.com/vaadin/framework/blob/db5480d45e42d05c9853f4d771c8f6c0ef3b7e3d/server/src/main/java/com/vaadin/ui/UI.java#L876)):*
> ```Java
> 
>     private boolean firePopStateEventOnRefresh() {
>         return getClass().getAnnotation(PushStateNavigation.class) != null;
> ```

Why not use `isAnnotationPresent` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10404#-:-L-VQRrD1A500nNZbaVz:b-kkr92f)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10404#-L-VgQ5Ly-YOjpZf8Tx_:-L-VgQ5Ly-YOjpZf8Txa:bguai8p) (no related file):*
This change could use a test to demonstrate the issue and make sure there are no regressions in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10404)*

**Comment by tsuoanttila** [comment]
@Darsstar This PR has been a long time unanswered. Do you have the time to go through my feedback?

**Comment by pleku** [comment]
Thanks for the contribution. Closing this PR due to author inactivity. We could take care of the changes ourselves, but it is a matter of priorities and this particular addition is not a priority.

Please reopen if this valid.

**Pull request closed without merging**
