### PR TITLE
Remove vaadin-uitest-common dependency from server tests

### PR DESCRIPTION
**Pull request by tsuoanttila**
This is a rewrite of the test base of the servlet integration test package.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8551)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 16 of 19 files at r1.
Review status: 10 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrnzKY5O7eYXcIzOzw:-KcrnzKY5O7eYXcIzOzx:bkae32a) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L23)):*
> ```Java
> import com.vaadin.testbench.parallel.ParallelTest;
> 
> @RunOnHub("tb3-hub.intra.itmill.com")
> ```

(not ideal to hard-code this, but ok for now)

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcroatxADQkSJI6oJa1:-KcroatysMSpjZ9TrulR:b-bhrdpn) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L99)):*
> ```Java
>     public void teardown() {
>         if (screenshotErrors) {
>             throw new RuntimeException("Screenshots failed.");
> ```

how will the CI indicate the failure in this case - as a normal test failure?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrotK7b2YcNe_9_3qI:-KcrotK7b2YcNe_9_3qJ:bol124) ([raw file](https://github.com/vaadin/framework/blob/be4eff4ce2a23e1c15666d934346c017f9ae7a68/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java#L64)):*
> ```Java
> 
>     @Parameters
>     public static Collection<String> getContextPaths() {
> ```

Currently not used, but will we find this if we someday add wildfly9-nginx? Or will this ever be useful?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationDefaultPushIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpCI_qy3ZnT5ou2q9:-KcrpCI_qy3ZnT5ou2qA:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationDefaultPushIT.java#L18)):*
> ```Java
> package com.vaadin.tests.integration;
> 
> public class ServletIntegrationDefaultPushIT
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpJxxFN6bJPB0apjd:-KcrpJxxFN6bJPB0apje:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationIT.java#L18)):*
> ```Java
> package com.vaadin.tests.integration;
> 
> public class ServletIntegrationIT extends AbstractServletIntegrationTest {
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationLongPollingIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpLfR6_uGw2TTGSCF:-KcrpLfR6_uGw2TTGSCG:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationLongPollingIT.java#L18)):*
> ```Java
> package com.vaadin.tests.integration;
> 
> public class ServletIntegrationLongPollingIT
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationStreamingIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpMWAWKfsa6Gq134X:-KcrpMWBWdqh31pmLahB:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationStreamingIT.java#L18)):*
> ```Java
> package com.vaadin.tests.integration;
> 
> public class ServletIntegrationStreamingIT
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationWebsocketIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpVtj4EQwydIUdkFI:-KcrpVtj4EQwydIUdkFJ:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationWebsocketIT.java#L18)):*
> ```Java
> package com.vaadin.tests.integration;
> 
> public class ServletIntegrationWebsocketIT
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/jsr356/ServletIntegrationJSR356WebsocketIT.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpY4h6iMRwbN5Ft_X:-KcrpY4h6iMRwbN5Ft_Y:bm1gmh) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/jsr356/ServletIntegrationJSR356WebsocketIT.java#L20)):*
> ```Java
> import com.vaadin.tests.integration.ServletIntegrationWebsocketIT;
> 
> public class ServletIntegrationJSR356WebsocketIT
> ```

Does this require screenshot renames?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/BasicPushTest.java, line 0 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpeMhXeO1J52Zfvtk:-KcrpeMhXeO1J52Zfvtl:buzc58k) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/BasicPushTest.java#L0)):*
unused?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpiXBkQhCTMI2a4df:-KcrpiXBkQhCTMI2a4dg:b-9rhvwk) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java#L34)):*
> ```Java
> 
> @RunWith(Parameterized.class)
> public class LongPollingProxyServerTest extends AbstractIntegrationTest {
> ```

not *IT?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpnoUqSl7_Fe1sC7J:-KcrpnoUqSl7_Fe1sC7K:bow4pu1) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java#L106)):*
> ```Java
>         return findElement(By.id(BasicPush.INCREMENT_BUTTON_ID));
>     }
> }
> ```

NL missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by tsuoanttila** [comment]
Review status: 10 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrnzKY5O7eYXcIzOzw:-Kcrrcw0hjG9rxjWtcZc:bf4epil) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L23)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(not ideal to hard-code this, but ok for now)
</blockquote></details>

The TB implementation should provide a default way to override the hub address manually with a property.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcroatxADQkSJI6oJa1:-KcrrUVDys9IKjnvVIfj:ber1qyu) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L99)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

how will the CI indicate the failure in this case - as a normal test failure?
</blockquote></details>

We need to consider if we want to list the failing screenshot names, should be actually a feature in the TB..

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrotK7b2YcNe_9_3qI:-Kcrqfj9AvwMbXZi8h8q:b-kvb46b) ([raw file](https://github.com/vaadin/framework/blob/be4eff4ce2a23e1c15666d934346c017f9ae7a68/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java#L64)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Currently not used, but will we find this if we someday add wildfly9-nginx? Or will this ever be useful?
</blockquote></details>

I moved the whole funcitonality into the test class which actually was using this feature. it is now it's own parameterized test, which is slow to run, since it's not doing things in parallel. TestBench should add it's own support for Parameterized TB tests, instead of us using a custom one in the Framework.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationDefaultPushIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpCI_qy3ZnT5ou2q9:-KcrqzzkdSi-ZRtxenps:b-51yd62) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationDefaultPushIT.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

Possibly, the whole screenshot naming policy should be reconsidered in this case since we should have just one pair of screenshots and those should be used everywhere.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpJxxFN6bJPB0apjd:-Kcrr8JbLp1sh6pfx6ro:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationIT.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

see above

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationLongPollingIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpLfR6_uGw2TTGSCF:-Kcrr9w87zhNlFapJLbv:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationLongPollingIT.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

see above

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationStreamingIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpMWAWKfsa6Gq134X:-KcrrAQwrDL0mYc7ONFi:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationStreamingIT.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

see above

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationWebsocketIT.java, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpVtj4EQwydIUdkFI:-KcrrArwnfk-_I_A37_j:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationWebsocketIT.java#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

see above

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/jsr356/ServletIntegrationJSR356WebsocketIT.java, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpY4h6iMRwbN5Ft_X:-KcrrBRe0jYIVSOQNhd6:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/jsr356/ServletIntegrationJSR356WebsocketIT.java#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this require screenshot renames?
</blockquote></details>

see above

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/BasicPushTest.java, line  at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpeMhXeO1J52Zfvtk:-KcrrC-durerkbqXfQaH:b-y3549r) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/BasicPushTest.java#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

I moved the parts of this abstract class that were used into the actual push test.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcrpiXBkQhCTMI2a4df:-KcrrI3XhDgIjGd7sD0l:bsbze5j) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/push/LongPollingProxyServerTest.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not *IT?
</blockquote></details>

Not actually executed at all anyway for now. Should be renamed *IT just to be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 2 of 20 files at r1, 2 of 4 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcroatxADQkSJI6oJa1:-Kcw0xqitNtOsqHN6bDL:bsr66gm) ([raw file](https://github.com/vaadin/framework/blob/f58c7ee7a79d53aa2e507a9834f50c2bafb38af3/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L99)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

We need to consider if we want to list the failing screenshot names, should be actually a feature in the TB..
</blockquote></details>

As long as there is some indication that test X failed on server Y, that is enough for me... Not sure if fulfilled by the current version, though.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationTests.java, line 26 at r2](https://reviewable.io:443/reviews/vaadin/framework/8551#-Kcw-G6Z0BEUInfY0zc5:-Kcw-G6Z0BEUInfY0zc6:bvuoqa4) ([raw file](https://github.com/vaadin/framework/blob/4a96c6f8aa32bee1beffc283b3f7b8d3e7ec483c/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationTests.java#L26)):*
> ```Java
>                 return new String[] {};
>             }
>             return new String[] { "com.vaadin.tests.integration.push" };
> ```

Push tests are only run for wildfly9-nginx? Consistent with old behavior, but sounds strange - probably because of the timeout test(s) that only work on wildfly9-nginx where configured.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 111 at r5](https://reviewable.io:443/reviews/vaadin/framework/8551#-KcwwNfkEke27c5vvilG:-KcwwNflICQiG2V1WebJ:bcf42iz) ([raw file](https://github.com/vaadin/framework/blob/d87fe22b8d53101776ef7337b79a26eea4248053/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L111)):*
> ```Java
>             }
>         } catch (IOException e) {
>             System.err.println(
> ```

should this use log instead of syserr?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 2 of 22 files at r1, 5 of 7 files at r6.
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java, line 112 at r6](https://reviewable.io:443/reviews/vaadin/framework/8551#-Kd-ZE0gZlV_Rj6PgAn5:-Kd-ZE0gZlV_Rj6PgAn6:bnffm9c) ([raw file](https://github.com/vaadin/framework/blob/f916b4de709a761903ab47496eaebb1a71be71e9/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractIntegrationTest.java#L112)):*
> ```Java
>             }
>         } catch (IOException e) {
>             Logger.getLogger(getClass().getName()).error(
> ```

test build failed - log4j not on classpath, JUL would be safer

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java, line 15 at r6](https://reviewable.io:443/reviews/vaadin/framework/8551#-Kd-ZSK4vNq8r4_i5o48:-Kd-ZSK4vNq8r4_i5o49:bmo0u15) ([raw file](https://github.com/vaadin/framework/blob/f916b4de709a761903ab47496eaebb1a71be71e9/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/AbstractServletIntegrationTest.java#L15)):*
> ```Java
>         Thread.sleep(2000);
>         $(TableElement.class).first().getCell(0, 1).click();
>         compareScreen("initial");
> ```

This sounds like asking for race conditions - why was the compareScreen moved?

---

*[test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationTests.java, line 51 at r6](https://reviewable.io:443/reviews/vaadin/framework/8551#-Kd-_7krISoaHMWCd8-e:-Kd-_7krISoaHMWCd8-f:b9cdf3e) ([raw file](https://github.com/vaadin/framework/blob/f916b4de709a761903ab47496eaebb1a71be71e9/test/servlet-containers/generic/src/test/java/com/vaadin/tests/integration/ServletIntegrationTests.java#L51)):*
> ```Java
>             }
>             if (notWebsocketCompatible.contains(serverName)) {
>                 ignoredPackages.add("com.vaadin.tests.integration.websocket");
> ```

just to confirm: I assume this also ignores subpackages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8551#-:-Kd-pgBPKq6trsB-_Tki:bnfp4nl)*

**Pull request merged**
