### PR TITLE
Add support for rendering HTML in ButtonRenderer

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8606)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/renderers/ButtonRenderer.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/8606#-KdQKf5U9tSo7MozPdQU:-KdQKf5VNMQgZuI4bNu5:b-3tem85) ([raw file](https://github.com/vaadin/framework/blob/96e3186e17e226389b710fed684f93f8253545b6/client/src/main/java/com/vaadin/client/renderers/ButtonRenderer.java#L42)):*
> setHtml

Could make sense to rename to setHtmlContentAllowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8606)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java, line 95 at r1](https://reviewable.io:443/reviews/vaadin/framework/8606#-Kd_4OaPtqmM1uMaKK-_:-Kd_4OaTPWWTJG1UdkF_:bvaj0w0) ([raw file](https://github.com/vaadin/framework/blob/96e3186e17e226389b710fed684f93f8253545b6/server/src/main/java/com/vaadin/ui/renderers/ButtonRenderer.java#L95)):*
> ```Java
>      *            render as text
>      */
>     public void setHtml(boolean html) {
> ```

Everywhere else this is `htmlContentAllowed`, please change

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridClickableRenderersTest.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8606#-Kd_68aL-sX5DMfQ4Cyn:-Kd_68aL-sX5DMfQ4Cyo:bjub1vj) ([raw file](https://github.com/vaadin/framework/blob/96e3186e17e226389b710fed684f93f8253545b6/uitest/src/test/java/com/vaadin/tests/components/grid/GridClickableRenderersTest.java#L50)):*
> ```Java
>         WebElement secondRowHtmlButton = findElements.get(4);
>         Assert.assertEquals("button 2 text", secondRowTextButton.getText());
>         Assert.assertEquals("button 2 html", secondRowHtmlButton.getText());
> ```

where is it checking for the html content to be visible ? just checking that the text is there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8606)*

**Comment by Artur-** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/renderers/ButtonRenderer.java, line 42 at r1](https://reviewable.io:443/reviews/vaadin/framework/8606#-KdQKf5U9tSo7MozPdQU:-Kd_8JtYVV66pVNiehs7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96e3186e17e226389b710fed684f93f8253545b6/client/src/main/java/com/vaadin/client/renderers/ButtonRenderer.java#L42)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> setHtml

Could make sense to rename to setHtmlContentAllowed.
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridClickableRenderersTest.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8606#-Kd_68aL-sX5DMfQ4Cyn:-Kd_8Kje4mPlhMZHdpm5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/96e3186e17e226389b710fed684f93f8253545b6/uitest/src/test/java/com/vaadin/tests/components/grid/GridClickableRenderersTest.java#L50)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

where is it checking for the html content to be visible ? just checking that the text is there
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8606)*

**Comment by pleku** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8606)*

**Pull request merged**
