### PR TITLE
Reset selected icon when blurring a ComboBox

### LINKED ISSUE #8073: Inconsistent UI view on using keyboard navigation + blur event on combobox (items with icon/caption)
Version
For Vaadin 7.6.3

Description
Inconsistent combo box UI view on using keyboard navigation and subsequent blur event (i.e. click outside the combo box) without selecting any item (The combo box items include both icon and caption): The icon shows/corresponds to the last hovered yet not-selected item but the caption updates itself to last selected item and brings the view inconsistency. 

Minimal Reproducible example:
(a) Vaadin Demo Page Example: https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box
image
Steps:
1. On Select your country combobox, choose Afghanistan. The flag and name of Afghanistan is set and visible.
2. Click on combobox, using keyboard down arrow, navigate/hover to Brazil.
3. Click outside the combobox, (blur/focus out).
4. Expected: Old selection to be restored i.e. the country displayed should be Afghanistan and its corresponding flag.
5. Actual: The country displayed has flag and name mismatch: i.e. name is Afghanistan, but flag is of Brazil as shown in the above figure.

(b) Second Local Example
image
Steps:
1. Add combo box with items having both icon and caption.
 ```
 (addItem(item1);
 setItemIcon(item1, Buttons.toResource(icon1, Icons.SIZE1));
 setItemCaption(item1, item1.toString());)
```
2. Click on any item say item1(icon1, cap1). The selected value is displayed in combo box correctly.
3. Using Keyboard, now navigate to item3(icon3, cap3) to hover on it.
4. Click outside to blur the combo box.
5. Expected Result: Since we have no selection, the old selected value is reverted (with correct icon, caption and item).
6. Actual Result: ICON: icon3 (incorrect), CAPTION: caption1 (correct), SET-ITEM: item1 (correct).  

**Workaround: Attach a default blur listener to request component repaint (e.g. call "markAsDirtyRecursive").**

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8073

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8082)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VFilterSelect.java, line 2389 at r1](https://reviewable.io:443/reviews/vaadin/framework/8082#-K_T9uGMJr_rO4tPR8Yx:-K_T9uGMJr_rO4tPR8Yy:b4mldwb) ([raw file](https://github.com/vaadin/framework/blob/5111c9e6757af763c9cc1bd0a8491ea33573e9a2/client/src/main/java/com/vaadin/client/ui/VFilterSelect.java#L2389)):*
> ```Java
>                 }
>             } else if (currentSuggestion != null) {
>                 setPromptingOff(currentSuggestion.caption);
> ```

(not sure if this logic is that great, but the fix at least looks consistent with the rest of the behavior)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082#-:-K_TA22VmXGdZ6CtUWGu:bnfp4nl)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082)*

**Comment by hesara** [comment]
Requires rebase, and a full test run would be good.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082#-:-Ka21qRJM6E5vl7l3yFb:bhwpwxq)*

**Comment by Artur-** [comment]
Rebased, how do you run a full test run nowadays?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082#-:-Ka2Dsm71rmo3ZV252vh:bxqja1s)*

**Comment by elmot** [comment]
At least, you can make a branch of name  remote-run/whatever-you-fix and run tests against it. Might be not the best solution, but that works.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082#-:-Ka2JSporCm40qkYqoll:b-orhvgw)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8082#-Ka6v3zH8zHISVDYRvc6:-Ka6v3zH8zHISVDYRvc7:b1auu9o) (no related file):*
Blocked until a full browser test run has been done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8082#-Ka6v3zH8zHISVDYRvc6:-KaEMxETWfSruExg_Q70:bze8srp) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Blocked until a full browser test run has been done
</blockquote></details>

Both modern and old browser test have no new failures that are related.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8082)*

**Pull request merged**
