### PR TITLE
ContentMode for the description of MenuItems

### PR DESCRIPTION
**Pull request by jonas-zipprick**
This pull request is related to issue https://github.com/vaadin/framework/issues/8591

Adds the ability to set the content mode for the description of a menu item that is part of a menu bar.

This functionality was already available for every AbstractComponent but missing for the menu items of menu bars.
If no content mode is specified it defaults to the PREFORMATTED content mode.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9984)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1084 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv8s7qJpjM5RpKTHTC:-Ktv8s7qJpjM5RpKTHTD:b-jc25nc) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1084)):*
> ```Java
>             }
> 
>             if (uidl.hasAttribute(
> ```

This could perhaps also be optimized so that nothing is written for the default mode, and getTooltip() assumes the default if there is nothing in the UIDL message.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv7tsKbFT8JxaGYN7_:-Ktv7tsKbFT8JxaGYN7a:b5ikiog) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L27)):*
> ```Java
> import java.util.Map;
> 
> import com.vaadin.shared.ui.ContentMode;
> ```

(ideally this would be with the other com.vaadin.shared imports)

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 471 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv83eo7ti8qcoxw95E:-Ktv83eo7ti8qcoxw95F:b-iuj51m) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L471)):*
> ```Java
>         private String styleName;
>         private String description;
>         private ContentMode contentMode;
> ```

If this has a default value, some of the other operations like declarative support backwards compatibility might get simpler.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 826 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv7WswIQ0_TiH-qYvC:-Ktv7WswIQ0_TiH-qYvD:bcdqood) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L826)):*
> ```Java
>          * @param mode
>          *            the content mode for the description
>          * @since 8.0
> ```

leave the since tag empty, or use 8.2 which is the most likely version this would go to

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 1027 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv77gQDvfqmfcmA42Q:-Ktv77gQDvfqmfcmA42R:b-9occo9) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L1027)):*
> ```Java
>                 item.getDescription(), def.getDescription(), String.class,
>                 context);
>         DesignAttributeHandler.writeAttribute("contentmode", attr,
> ```

How about readMenuElement()? Does it need to be updated?

---

*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6dJAsBt34zdY0GzT:-Ktv6dJAsBt34zdY0GzU:bmzwpay) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L43)):*
> ```Java
>         String design = "<vaadin-menu-bar auto-open tabindex=5>"
>                 + "<menu checkable>Save</menu>"
>                 + "<menu contentmode='preformatted' description='Open a file'>Open</menu>"
> ```

Any test covering serialization of the other content modes?
Is this attribute needed in the declarative format when a description is given, or can it be omitted for backwards compatibility? At least for reading it should be possible to omit it for compatibility, but also when writing it might be nice.

---

*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6ZriIYBXlc_mfG_0:-Ktv6ZriIYBXlc_mfG_1:b-es0erj) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L153)):*
> ```Java
>     }
> 
>     private void compareMenus(MenuItem expected, MenuItem actual) {
> ```

Should this also check that the content mode is the expected one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Comment by balugege** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6ZriIYBXlc_mfG_0:-Ktvg97bpy4JtqrA3RM6:bpos46q) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L153)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should this also check that the content mode is the expected one?
</blockquote></details>

There is no public getter for the content mode for a MenuItem so this will be difficult i think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Comment by hesara** [comment]
@balugege it seems that one of the commits has been made with an author e-mail address that is not linked to the GitHub account you used to make the PR. Thus, the CLA is not accepted by all the authors and the PR is not mergable as-is. Could you update one of the commits (or e.g. squash the commits) if both commits were made by you, or ask jzi to sign the CLA otherwise? Also, there are a number of open questions and review comments. Will you still work on those?

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6ZriIYBXlc_mfG_0:-KvS55xJF-7WONlGFFC0:b-o5gvtu) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L153)):*
<details><summary><i>Previously, balugege (Jonas Zipprick) wrote…</i></summary><blockquote>

There is no public getter for the content mode for a MenuItem so this will be difficult i think.
</blockquote></details>

Perhaps the getter can be made public (with javadoc and a since tag) to allow checking this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984#-:-KvS5JGsfj5fRXxUNcj_:b-8zz88n)*

**Comment by balugege** [comment]
Hi @hesara, I already adressed most of what you wrote in your Review but forgot to mark it as done. Sorry for that. I will finish of the last unresilved Review comment and fix the conflicting file.

I will Change my past commit to fix the author issue.

**Comment by balugege** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VMenuBar.java, line 1084 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv8s7qJpjM5RpKTHTC:-KvbW2Ws8rMXQLaM7t9L:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/client/src/main/java/com/vaadin/client/ui/VMenuBar.java#L1084)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This could perhaps also be optimized so that nothing is written for the default mode, and getTooltip() assumes the default if there is nothing in the UIDL message.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv7tsKbFT8JxaGYN7_:-KvaUs4mbAwwj5wjFMqZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L27)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(ideally this would be with the other com.vaadin.shared imports)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 471 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv83eo7ti8qcoxw95E:-KvaUr6MfkyuO3k2TiQG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L471)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

If this has a default value, some of the other operations like declarative support backwards compatibility might get simpler.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 826 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv7WswIQ0_TiH-qYvC:-KvaUoNLUOwUnWCa-v-d:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L826)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

leave the since tag empty, or use 8.2 which is the most likely version this would go to
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/MenuBar.java, line 1027 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv77gQDvfqmfcmA42Q:-KvaUwhoGZe5AtwNm53v:b-69yk7c) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/main/java/com/vaadin/ui/MenuBar.java#L1027)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

How about readMenuElement()? Does it need to be updated?
</blockquote></details>

Yes, you are right. I forgot that. Done.

---

*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6dJAsBt34zdY0GzT:-KvaUxBptHojHsSsERE4:b-1zm0bi) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L43)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Any test covering serialization of the other content modes?
Is this attribute needed in the declarative format when a description is given, or can it be omitted for backwards compatibility? At least for reading it should be possible to omit it for compatibility, but also when writing it might be nice.
</blockquote></details>

I added the test `testDescriptionContentMode`. Leaving a way the contentmode Parameter is now also supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Comment by balugege** [comment]
*[server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java, line 153 at r1](https://reviewable.io:443/reviews/vaadin/framework/9984#-Ktv6ZriIYBXlc_mfG_0:-Kvbj_xl8bePliOzRBjW:b-pwb76u) ([raw file](https://github.com/vaadin/framework/blob/4d0042726a0a2e7e774073e3ba344690cd0fa7b4/server/src/test/java/com/vaadin/tests/components/menubar/MenuBarDeclarativeTest.java#L153)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Perhaps the getter can be made public (with javadoc and a since tag) to allow checking this.
</blockquote></details>

Ok, i made the getter public, added javadoc to it, and used it in this compareMenus method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Comment by ahie** [comment]
Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9984#-KzYn-_LCTEc4cR-hnyR:-KzYn-_MB3z_zySeyC1M:b-vmoezz) (no related file):*
All previous comments by @hesara seem to be addressed.

---

*[uitest/src/main/java/com/vaadin/tests/elements/menubar/MenuBarUI.java, line 38 at r4](https://reviewable.io:443/reviews/vaadin/framework/9984#-KzYnb0XP-BWSdRorRxQ:-KzYnb0XP-BWSdRorRxR:b-rl3ndq) ([raw file](https://github.com/vaadin/framework/blob/b58896e712d7a880acc24a9a007b8613da3aa3b6/uitest/src/main/java/com/vaadin/tests/elements/menubar/MenuBarUI.java#L38)):*
> ```Java
>     }
> 
>     private MenuBar createDefaultMenuBar(String topLevelItemSuffix,
> ```

There doesn't seem to be a corresponding test for these changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Comment by tsuoanttila** [comment]
@balugege can you please sign the CLA again?

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984#-:-L1SDCcxaIIqcx6dvOE4:bnfp4nl)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9984)*

**Pull request merged**
