### PR TITLE
Fix beforeClientResponse test for changes in #9305

### PR DESCRIPTION
**Pull request by hesara**
Changes in connector tracking and cleaning (#9305) changed the
behavior so that the framework no longer performs an extra
beforeClientResponse which the test was expecting.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9396)

### CODE REVIEW

**Comment by Artur-** [comment]
Why did not the validation build for #9305 fail? The ChangeHierarchyBeforeResponse test seems to produce an UI roughly 50% of the time and a stack trace 50% of the time:
```
javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.AssertionError: Connector should be registered with this ConnectorTracker
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:383)
	at com.vaadin.launcher.ApplicationRunnerServlet.service(ApplicationRunnerServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.vaadin.server.ServiceException: java.lang.AssertionError: Connector should be registered with this ConnectorTracker
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1538)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	... 20 more
Caused by: java.lang.AssertionError: Connector should be registered with this ConnectorTracker
	at com.vaadin.ui.ConnectorTracker.isClientSideInitialized(ConnectorTracker.java:211)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:107)
	at com.vaadin.server.communication.UIInitHandler.getInitialUidl(UIInitHandler.java:291)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:80)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1526)
	... 21 more
```

**Comment by Artur-** [comment]
There are two problems here:
1. beforeClientResponse are run in a random order for all pending connectors. Making them run in e.g. hierarchy order makes the test and all applications behave consistently
2. UidlWriter assumes that all connectors which are initially dirty are available in the connector tracker. This is no longer the case and e.g. `ConnectorTracker.isDirty()` should be checked before `isClientSideInitialized` or then `isClientSideInitialized` should be changed to return `false` for untracked connectors

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9396#-:-KkjTc5-YgBHVY1APVIv:bn25kcb)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/9396#-KkomeXOF39bbUbOqU-q:-KkomeXOF39bbUbOqU-r:b-xfmwyb) ([raw file](https://github.com/vaadin/framework/blob/da1f361d394b598fe1dd4add22c629fe7bdc6193/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L106)):*
> ```Java
>             // process parents before children
>             Collections.sort(connectorsToProcess,
>                     Comparator.comparingInt(conn -> {
> ```

TBD if we can make this more efficient as this is called a lot - a stable sort would still be good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9396)*

**Comment by pleku** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/9396#-KkomeXOF39bbUbOqU-q:-Kku2PitI1rEBzvAdKmP:b5o6sie) ([raw file](https://github.com/vaadin/framework/blob/da1f361d394b598fe1dd4add22c629fe7bdc6193/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L106)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBD if we can make this more efficient as this is called a lot - a stable sort would still be good
</blockquote></details>

As discussed based on profiling results, this would be premature optimization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9396#-:-Kku2MnZKxRRYbXIQyIT:bnfp4nl)*

**Pull request merged**
