### PR TITLE
Initial documentation for 8.1 Drag and Drop

### PR DESCRIPTION
**Pull request by pleku**
Part of #8395

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8867)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQyCP242eUdhqT4XeK:-KfQyCP30URYnfpSbYqa:bofvlx2) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L18)):*
> ```AsciiDoc
> example, most operating systems allow dragging and dropping files between
> folders or dragging a document on a program to open it. Framework version 8.1 adds support for https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API[HTML5 drag and drop] features, making it
> possible to enable user drag components and parts of certain components and make them also target for drops, from the same UI or even outside the browser window.
> ```

This sentence has some strange grammar/clarity issues.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQzM_0Xp2uOAeOcjSs:-KfQzM_0Xp2uOAeOcjSt:b-sru9zx) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L25)):*
> ```AsciiDoc
> Dragging starts from a __drag source__, which defines the transferable.
> 
> To make a component a drag source, you apply the [classname]#DragSourceExtension# to it. Then you can define the data to transfer, and the allowed drag effect.
> ```

drag effect*s*? though these are collapsed so each combination has its own enum value

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR-4TkuWEkVQoe6TnM:-KfR-4TkuWEkVQoe6TnN:b-4xrvjb) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L40)):*
> ```AsciiDoc
> The __effect allowed__ specifies the allowed effects that must match the effect allowed by the drop target. If multiple effects are allowed, the user can use the modifier keys to switch between the desired effects. The default effect and the modifier keys are system and browser dependent.
> 
> The __transfer data__ a set of data, that the drop target will receive in the __drop event__. The first parameter given is the type of the data, and the second parameter is the actual data as string. The type parameter thus acts as a key for the actual data. For more information about the
> ```

beginning of first sentence grammatically broken - missing verb?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR-GthEORHczJJBBAr:-KfR-GthEORHczJJBBAs:b-lqvoyy) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L43)):*
> ```AsciiDoc
> type parameter, see https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types[MDN recommendations].
> 
> You can get the [classname]#DragStartEvent# for whenever the drag has started, and the [classname]#DragEndEvent# when the drag has ended, either in a drop or a cancel.
> ```

"the *Event" -> "a *Event" * 2 ? "in" near the end of the sentence sounds a bit strange to me

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR0tMTZHzj4eYYiV7X:-KfR0tMTZHzj4eYYiV7Y:byrdyuh) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L90)):*
> ```AsciiDoc
> ----
> 
> When there is data dragged over an drop target, the __v-drag-over__ class name is applied to the components root element in DOM.
> ```

"the root element of the component in DOM"?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR10TBDq2_NyypOuhY:-KfR10TBDq2_NyypOuhZ:b-w09sfe) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L92)):*
> ```AsciiDoc
> When there is data dragged over an drop target, the __v-drag-over__ class name is applied to the components root element in DOM.
> 
> === Controlling the when drop is acceptable
> ```

Title Capitalization?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 94 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR18cHDWzoDOOdp6jS:-KfR18cHDWzoDOOdp6jT:b-p264l1) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L94)):*
> ```AsciiDoc
> === Controlling the when drop is acceptable
> 
> The __drop effect__ allows you to specify the desired drop effect, that much match the one that has been
> ```

that must ...

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR1FUkhOyjmuAF4DYv:-KfR1FUkhOyjmuAF4DYw:b-523zui) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L98)):*
> ```AsciiDoc
> default effect since it may vary between browsers.
> 
> The __drag over criteria__ allows you determine whether the current drag source is allowed as a drop target, when the source is moved on top of the target. The criteria is a script that is executed always the `dragover` event is fired for the first time for this target, and returning `false` will prevent showing any drop effect. The script gets the `dragover` event as a parameter named `event`.
> ```

"criteria" is technically plural, not sure how to formulate this...

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 103 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR1VumAPIFjS4mqD6X:-KfR1VumAPIFjS4mqD6Y:bej8jb4) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L103)):*
> ```AsciiDoc
> 
> ////
> TODO Add an example of drag over criteria and drop criteria
> ```

(TODO)

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 109 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR1_UeUSJVDZ4rNSlq:-KfR1_UeUSJVDZ4rNSlr:b-painvw) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L109)):*
> ```AsciiDoc
> 
> ////
> TODO add back when supported with new API ?
> ```

(TODO later)

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 458 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR0SutQP2Ikwfe4aWn:-KfR0SutQP2Ikwfe4aWo:bw16gn3) ([raw file](https://github.com/vaadin/framework/blob/af6d13a22b9ed7ec04b731cab2cdeda23ac44fd4/documentation/advanced/advanced-dragndrop.asciidoc#L458)):*
> ```AsciiDoc
> 
> 
> [[advanced.dragndrop.drop-on-component]]
> ```

layout-absolutelayout.asciidoc refers to this section/anchor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Comment by wbadam** [comment]
Review status: 1 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQyCP242eUdhqT4XeK:-Kf__aUIr956vUFJfUSg:b1qumhy) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L18)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This sentence has some strange grammar/clarity issues.
</blockquote></details>

Maybe something like this: ... making it possible to drag components and parts of certain components, as well as making them drop targets [for objects in the same UI or even outside the browser window].
[] - does it need to be mentioned here explicitly? 

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_d2lo_PFiG59AKRDB:-Kf_d2lpATn7NTTE1A7M:b-w04ean) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L22)):*
> ```AsciiDoc
> == Drag Source
> 
> Dragged objects, or __transferables__, are essentially data objects.
> ```

What does _transferable_ mean in HTML5 dnd context?

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQzM_0Xp2uOAeOcjSs:-Kf_fKXPZfFjh7283lEK:bueoy65) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

drag effect*s*? though these are collapsed so each combination has its own enum value
</blockquote></details>

Plural would be better grammatically but MDN is talking about the effect as singular, and the HTML5 parameter is also called `effectAllowed`.

MDN is also confusing _drag effect_ and _drop effect_, the parameter is called `dropEffect` but it is sometimes referred to as drag effect. I think in this case _drag effect_ is a good term.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_m4RuY2U5g9i-QUcl:-Kf_m4Rv0UPUexwweWKc:b-ua3uwa) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L29)):*
> ```AsciiDoc
> [source, java]
> ----
> Label draggableLabel = new Label("You can grab and drag me");
> ```

Not documentation issue but we have to make sure that the label is indeed draggable (no funny business with selection)

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_mrriySJ08BYyPqyR:-Kf_mrriySJ08BYyPqyS:bo164j) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L38)):*
> ```AsciiDoc
> ----
> 
> The __effect allowed__ specifies the allowed effects that must match the effect allowed by the drop target. If multiple effects are allowed, the user can use the modifier keys to switch between the desired effects. The default effect and the modifier keys are system and browser dependent.
> ```

A bit of clarification:
Drop target has `dropEffect` that is `move`, `copy`, `link` (or `none`). The allowed effect is a combination of these.
The drop event happens when `dropEffect` (set for the target) is one of the allowed effects in`effectAllowed` (set for the source). Otherwise the drop isn't fired.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kfax7SHBtJDSEQJ0TMx:-Kfax7SHBtJDSEQJ0TMy:by1d9e0) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L71)):*
> ```AsciiDoc
> DropTargetExtension<VerticalLayout> dropTarget = new DropTargetExtension<>(dropTargetLayout);
> 
> // set the effect that is allowed, must match what is in the drag source
> ```

Perhaps modify like this:

// set the drop effect, must match the allowed effect in the drag source for a successful drop

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfaySa289G15bI2vl1T:-KfaySa3v0yRypxUmHSO:bauqsdf) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L83)):*
> ```AsciiDoc
>         
>         // get possible transfer data
>         // NOTE that "text" is same as "text/plain" from drag source data
> ```

Just for the record, it is so according to HTML standard https://www.w3.org/TR/2010/WD-html5-20101019/dnd.html#dom-datatransfer-getdata

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR0tMTZHzj4eYYiV7X:-Kfayp8GTWHk7h9xwvru:b-qr1349) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L90)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"the root element of the component in DOM"?
</blockquote></details>

Also, over **a** drop target

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 94 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfazVbFGx7euu8C34lF:-KfazVbFGx7euu8C34lG:bpzzqke) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L94)):*
> ```AsciiDoc
> === Controlling the when drop is acceptable
> 
> The __drop effect__ allows you to specify the desired drop effect, that much match the one that has been
> ```

...for a successful drop that must match the allowed effect that has been defined for the drag source...

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kfb-HtxiZ7bOT06M9X-:-Kfb-HtyIYL3FmtUVvkO:b-27v87) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L98)):*
> ```AsciiDoc
> default effect since it may vary between browsers.
> 
> The __drag over criteria__ allows you determine whether the current drag source is allowed as a drop target, when the source is moved on top of the target. The criteria is a script that is executed always the `dragover` event is fired for the first time for this target, and returning `false` will prevent showing any drop effect. The script gets the `dragover` event as a parameter named `event`.
> ```

...always when the `dragover`...

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR1FUkhOyjmuAF4DYv:-Kfb-PWGYogLizX3pM8i:byx4ol6) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L98)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"criteria" is technically plural, not sure how to formulate this...
</blockquote></details>

Could use criterion I guess but the script could technically contain several of them, although it returns only once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Comment by wbadam** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Comment by pleku** [comment]
Review status: 1 of 3 files reviewed at latest revision, 16 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 18 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQyCP242eUdhqT4XeK:-KffJlgxLqSAif4kcM7Z:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L18)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Maybe something like this: ... making it possible to drag components and parts of certain components, as well as making them drop targets [for objects in the same UI or even outside the browser window].
[] - does it need to be mentioned here explicitly? 
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_d2lo_PFiG59AKRDB:-KffKD48cNOvOJiDBss3:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L22)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

What does _transferable_ mean in HTML5 dnd context?
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfQzM_0Xp2uOAeOcjSs:-KffKRgkIuCUfQOIZv9V:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L25)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Plural would be better grammatically but MDN is talking about the effect as singular, and the HTML5 parameter is also called `effectAllowed`.

MDN is also confusing _drag effect_ and _drop effect_, the parameter is called `dropEffect` but it is sometimes referred to as drag effect. I think in this case _drag effect_ is a good term.
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_m4RuY2U5g9i-QUcl:-KffLM87TXS3MLJgT22L:b-x71bb6) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L29)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Not documentation issue but we have to make sure that the label is indeed draggable (no funny business with selection)
</blockquote></details>

Done, added NOTE below

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kf_mrriySJ08BYyPqyR:-KffM5D3X29oLbekbeTJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L38)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

A bit of clarification:
Drop target has `dropEffect` that is `move`, `copy`, `link` (or `none`). The allowed effect is a combination of these.
The drop event happens when `dropEffect` (set for the target) is one of the allowed effects in`effectAllowed` (set for the source). Otherwise the drop isn't fired.
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR-4TkuWEkVQoe6TnM:-KffMA3jCOFN-eCkRO6S:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L40)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

beginning of first sentence grammatically broken - missing verb?
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 43 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR-GthEORHczJJBBAr:-KffMQrH2_HRIg9vyN8t:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L43)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

"the *Event" -> "a *Event" * 2 ? "in" near the end of the sentence sounds a bit strange to me
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kfax7SHBtJDSEQJ0TMx:-KffN3XnP-dgP2dfQH4-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L71)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Perhaps modify like this:

// set the drop effect, must match the allowed effect in the drag source for a successful drop
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfaySa289G15bI2vl1T:-KffNNkw-Szfc27O-HNf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L83)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Just for the record, it is so according to HTML standard https://www.w3.org/TR/2010/WD-html5-20101019/dnd.html#dom-datatransfer-getdata
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR0tMTZHzj4eYYiV7X:-KffNqkZjgkoA-dX6dTy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L90)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Also, over **a** drop target
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR10TBDq2_NyypOuhY:-KffNuFIXkKWx7tNFF_t:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L92)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Title Capitalization?
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 94 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR18cHDWzoDOOdp6jS:-KffNxoWsw2tTGJwLNwa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L94)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

that must ...
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 94 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfazVbFGx7euu8C34lF:-KffODjglcIGnJAcf4Ux:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L94)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

...for a successful drop that must match the allowed effect that has been defined for the drag source...
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR1FUkhOyjmuAF4DYv:-KffO_m_Gk88A1TaGyIB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L98)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Could use criterion I guess but the script could technically contain several of them, although it returns only once.
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-Kfb-HtxiZ7bOT06M9X-:-KffOjRLGsH45_F9q4GB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/43fc8303ffd57d54b9983d104bb27256a940efb7/documentation/advanced/advanced-dragndrop.asciidoc#L98)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

...always when the `dragover`...
</blockquote></details>

Done.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 458 at r1](https://reviewable.io:443/reviews/vaadin/framework/8867#-KfR0SutQP2Ikwfe4aWn:-KffMnE8N-OrqdPBwF57:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/af6d13a22b9ed7ec04b731cab2cdeda23ac44fd4/documentation/advanced/advanced-dragndrop.asciidoc#L458)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

layout-absolutelayout.asciidoc refers to this section/anchor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Comment by hesara** [comment]
ok for me at this point if ok for Adam, all his comments addressed

---

Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/8867#-KffarlZ7Q8zgEQV5eno:-Kffarl_73XPvgumXLig:blofds8) ([raw file](https://github.com/vaadin/framework/blob/194095c6b7fe63685730f2e0fcc166e5a9684326/documentation/advanced/advanced-dragndrop.asciidoc#L22)):*
> ```AsciiDoc
> == Drag Source
> 
> Each component can be made a drag source that has a set of data that is transferred when it is dragged and dropped. 
> ```

Each -> Any?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867#-:-Kffc3L8TM9xXNGiHNmQ:b-7ggc3e)*

**Comment by wbadam** [comment]
It's all right with me also

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867#-:-KffjpSJYv1G1QqZHVfm:bbt8e64)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 22 at r2](https://reviewable.io:443/reviews/vaadin/framework/8867#-KffarlZ7Q8zgEQV5eno:-KfflnggBZqM7rEAzVBG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/194095c6b7fe63685730f2e0fcc166e5a9684326/documentation/advanced/advanced-dragndrop.asciidoc#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Each -> Any?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8867)*

**Pull request merged**
