### PR TITLE
Compensate for Grid editor moving out of sync horizontally.

### LINKED ISSUE #10998: Grid edit causes misaligned columns
Vaadin Framework version: 7.7.9 and 7.7.13 
Browser: Google Chrome 67.0.3396.87

When scrolling in a grid horizontally then clicking into the grid to edit, the alignment with the other rows columns and header gets out of sync.

gridissue

Steps to reproduce: 
1)	In application with multiple columns (horizontal scrollbar) scroll to somewhere in the middle of the grid. (In sample app attached for instance “fooBar10”)
2)	Click into grid to edit (for instance cell with “fooBar10”) -> columns no longer aligned with the header or the other rows.

This is an issue in Vaadin 7.7.9 and also with version 7.7.13 (unfortunately not in a position to change to Vaadin 8).

Attached is a tiny sample application (Spring Boot + Gradle) which is used to reproduce the issue.
[GridIssueSampleApp.zip](https://github.com/vaadin/framework/files/2135623/GridIssueSampleApp.zip)

### PR DESCRIPTION
**Pull request by Ansku**
Fixes #10998

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11092)

### CODE REVIEW

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11092)* status: all files reviewed, 2 unresolved discussions (waiting on @Ansku)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2145 at r1](https://reviewable.io/reviews/vaadin/framework/11092#-LIeKSvr2_YBYx0rG_X7:-LIeKSvr2_YBYx0rG_X8:b-pc2ns3) ([raw file](https://github.com/vaadin/framework/blob/db8b25589b71a1af30dee51fc431e7406483d033/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2145)):*
> ```Java
>             // sometimes focus handling twists the editor row out of alignment
>             // with the grid itself and the position needs to be compensated for
>             if (!grid.getEditor().columnToWidget.isEmpty()) {
> ```

How is this if check decided?
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2150 at r1](https://reviewable.io/reviews/vaadin/framework/11092#-LIeKZzxCNokDV23dOFA:-LIeKZzxCNokDV23dOFB:b2z6llq) ([raw file](https://github.com/vaadin/framework/blob/db8b25589b71a1af30dee51fc431e7406483d033/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2150)):*
> ```Java
>                 int rowLeft = rowElement.getAbsoluteLeft();
>                 int editorLeft = cellWrapper.getAbsoluteLeft();
>                 if (editorLeft != rowLeft + frozenWidth) {
> ```

Could we always do this calculation and decide based on this if which value to use?

**Comment by Ansku** [comment]
___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2145 at r1](https://reviewable.io/reviews/vaadin/framework/11092#-LIeKSvr2_YBYx0rG_X7:-LIozziq9Ksddw7cvoLJ:b6675e7) ([raw file](https://github.com/vaadin/framework/blob/db8b25589b71a1af30dee51fc431e7406483d033/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2145)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

How is this if check decided?
</blockquote></details>

Outdated, removed.

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11092)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @tsuoanttila)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2150 at r1](https://reviewable.io/reviews/vaadin/framework/11092#-LIeKZzxCNokDV23dOFA:-LIp2cgU2y_c-IAWalff:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/db8b25589b71a1af30dee51fc431e7406483d033/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2150)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could we always do this calculation and decide based on this if which value to use?
</blockquote></details>

Done.

**Review by Ansku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11092)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @tsuoanttila)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2145 at r1](https://reviewable.io/reviews/vaadin/framework/11092#-LIeKSvr2_YBYx0rG_X7:-LIp2oUvA08ItplZzeXB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/db8b25589b71a1af30dee51fc431e7406483d033/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2145)):*
<details><summary><i>Previously, Ansku (Anna Koskinen) wrote…</i></summary><blockquote>

Outdated, removed.
</blockquote></details>

Done.

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> Dismissed @tsuoanttila from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11092)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by elmot — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11092#-:-LJnHyGT9DDlPlIy3Lif:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
