### PR TITLE
Fix keymapper reverse mapping

### LINKED ISSUE #9470: DataProvider.refreshItem(item) seems to not work with Grid
In Vaadin 8.0.5,

As I know that only one item has changed in my DataProvider, I tried to call DataProvider.refreshItem(item) of my provider to provoke the refresh but nothing change. (FYI: I defined "Object getId(T item)" in the DataProvider)

It works has expected when I used DataProvider.refreshAll()

Thanks,

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9470 on top of #9505

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9535)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1, 2 of 6 files at r2, 4 of 4 files at r4.
Review status: 8 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 577 at r3](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn-K2kP0TsBp9EI7fVR:-Kn-K2kP0TsBp9EI7fVS:b-iefgp1) ([raw file](https://github.com/vaadin/framework/blob/f2ec2daa283c919f24efd6d42f18b135e3f609d8/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L577)):*
> ```Java
>      * This method is called from the constructor.
>      *
>      * @param identifierGetter has to return an unique key for every bean, and the returned key has to
> ```

(there is no universal definition on what is a "proper" way of operation for equals() and hashCode(), so might want to be more precise here)

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 197 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn36sVfCE8FyXdnky8O:-Kn36sVfCE8FyXdnky8P:b-h3ltwm) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L197)):*
> ```Java
> 
>     /** Empty default data provider. */
>     private DataProvider<T, ?> dataProvider = new CallbackDataProvider<>(
> ```

is the visibility reduced compared to 8.0, or to earlier 8.1s

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 591 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn36cCaQiH_kh9p4KQe:-Kn36cCbSxZae89ZylDp:bkshrql) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L591)):*
> ```Java
>      * @param identifierGetter has to return an unique key for every bean, and the returned key has to
>      *                         support proper {@code hashCode()} and {@code equals()}
>      * @return key mapper
> ```

probably should have @since as the API has changed, and a mention in release notes

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 81 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn378U9HanlhFBvviID:-Kn378U9HanlhFBvviIE:b-yng53d) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L81)):*
> ```Java
>      *
>      * @param dataObject
>      *            the data object to update
> ```

I guess technically this should also have @since 8.1 as the API changed

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 89 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn37U5CTecB6txSkenS:-Kn37U5CTecB6txSkenT:b-ozoq6o) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L89)):*
> ```Java
>      *
>      * @param identifierGetter has to return an unique key for every bean, and the returned key has to
>      *                         support proper {@code hashCode()} and {@code equals()}
> ```

What is meant by "proper hashCode() and equals()" here? Different people and libraries have different definitions, so it would help to be more explicit.

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 92 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn37HcsvKrAxLz5Q-nV:-Kn37HcsvKrAxLz5Q-nW:b-wgkrne) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L92)):*
> ```Java
>      * @since 8.1
>      */
>     void useIdentifierGetter(ValueProvider<T, Object> identifierGetter);
> ```

I'm not fully convinced about the name of the method - is there a reason not to use setIdentifierGetter or setIdentifierProvider or something like those?

---

*[server/src/test/java/com/vaadin/tests/server/KeyMapperIdGetterTest.java, line 5 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn3819O5f2l6UKM4r_n:-Kn3819O5f2l6UKM4r_o:bxmz232) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/test/java/com/vaadin/tests/server/KeyMapperIdGetterTest.java#L5)):*
> ```Java
> import com.vaadin.server.KeyMapper;
> 
> public class KeyMapperIdGetterTest extends KeyMapperTest {
> ```

Could perhaps use some comments to explain how using a bean with broken equals()/hashCode() allows testing the ID based comparison mechanism.

---

*[uitest/src/main/java/com/vaadin/tests/data/GridRefreshWithGetId.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn38Z6Vl9qRFTG-Y_Mp:-Kn38Z6Vl9qRFTG-Y_Mq:b-4q8mde) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/uitest/src/main/java/com/vaadin/tests/data/GridRefreshWithGetId.java#L49)):*
> ```Java
>             if (id != myObject.id)
>                 return false;
>             return name != null ? name.equals(myObject.name)
> ```

This is testing id AND name, which sounds quite weird and almost like a broken equals() to me - but probably still tests the fix properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/KeyMapper.java, line 46 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn3Fm0UXw_W7i6Z8_sH:-Kn3Fm0UXw_W7i6Z8_sI:bqak5jl) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/server/KeyMapper.java#L46)):*
> ```Java
>      * Constructs a new mapper
>      *
>      * @param identifierGetter has to return an unique key for every bean, and the returned key has to
> ```

(a unique); what does "proper" mean here (see comments elsewhere)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 92 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn37HcsvKrAxLz5Q-nV:-Kn54ZBOlOTogKhDIl9P:b93fojg) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L92)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm not fully convinced about the name of the method - is there a reason not to use setIdentifierGetter or setIdentifierProvider or something like those?
</blockquote></details>

Setting of a new identifierGetter actually leads to a rebuild of KeyMapper internal structure, so that should not be named setter from JavaBeans point of view.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Comment by elmot** [comment]
Review status: 4 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 577 at r3](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn-K2kP0TsBp9EI7fVR:-Kn5_M9oJ95YwVB5Cvx3:b-y7qpgr) ([raw file](https://github.com/vaadin/framework/blob/f2ec2daa283c919f24efd6d42f18b135e3f609d8/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L577)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(there is no universal definition on what is a "proper" way of operation for equals() and hashCode(), so might want to be more precise here)
</blockquote></details>

Text is rewritten with a link to the Object.hashCode, where its contract is defined

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 197 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn36sVfCE8FyXdnky8O:-Kn5BRwRsDfqNSVMeTId:bmi7evm) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L197)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is the visibility reduced compared to 8.0, or to earlier 8.1s
</blockquote></details>

Visibility reduced compared to 8.0. There are getter and setter, and I'd prefer to have this field secured with `private` modifier, because uncontrolled access to the field in subclasses may produce hard-to-detect bugs. Hopefully this piece of code is not overwritten  very often, and API change  notice in release notes is good enough solution.
Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 591 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn36cCaQiH_kh9p4KQe:-Kn5EAKW-MWIRN1SyvsI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L591)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

probably should have @since as the API has changed, and a mention in release notes
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 81 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn378U9HanlhFBvviID:-Kn5Eq0mxtbc85QfGgVh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L81)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I guess technically this should also have @since 8.1 as the API changed
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 89 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn37U5CTecB6txSkenS:-Kn5_ayy6qjxNK0VdEue:b-y7qpgr) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L89)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What is meant by "proper hashCode() and equals()" here? Different people and libraries have different definitions, so it would help to be more explicit.
</blockquote></details>

Text is rewritten with a link to the Object.hashCode, where its contract is defined

---

*[server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java, line 92 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn37HcsvKrAxLz5Q-nV:-Kn5TT55cci_eq4QV6cD:bmrv4gc) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/data/provider/DataKeyMapper.java#L92)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Setting of a new identifierGetter actually leads to a rebuild of KeyMapper internal structure, so that should not be named setter from JavaBeans point of view.
</blockquote></details>

In the same time, I won't insist if this naming seems to be confusing.

---

*[server/src/main/java/com/vaadin/server/KeyMapper.java, line 46 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn3Fm0UXw_W7i6Z8_sH:-Kn5_pwkjt4PS37JvFNw:b-y7qpgr) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/main/java/com/vaadin/server/KeyMapper.java#L46)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(a unique); what does "proper" mean here (see comments elsewhere)
</blockquote></details>

Text is rewritten with a link to the Object.hashCode, where its contract is defined

---

*[server/src/test/java/com/vaadin/tests/server/KeyMapperIdGetterTest.java, line 5 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn3819O5f2l6UKM4r_n:-Kn5VA2OL1GMjFn8LjmB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/server/src/test/java/com/vaadin/tests/server/KeyMapperIdGetterTest.java#L5)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could perhaps use some comments to explain how using a bean with broken equals()/hashCode() allows testing the ID based comparison mechanism.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/data/GridRefreshWithGetId.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/framework/9535#-Kn38Z6Vl9qRFTG-Y_Mp:-Kn5SRBCWuOMkWysdyJ8:b6yrexk) ([raw file](https://github.com/vaadin/framework/blob/3d1c90d5a2de6df9cbea4b9558dd6f8df599320c/uitest/src/main/java/com/vaadin/tests/data/GridRefreshWithGetId.java#L49)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

This is testing id AND name, which sounds quite weird and almost like a broken equals() to me - but probably still tests the fix properly.
</blockquote></details>

equals and hashcode here follow general Object's contract, and, thus, are not broken. The name field is checked intentionally, to ensure if identificatorGetter really works. I have added some comments about that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Comment by hesara** [comment]
Reviewed 5 of 6 files at r5.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Comment by hesara** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9535)*

**Pull request merged**
