### PR TITLE
Enable row height setting for Tree

### LINKED ISSUE #9411: Configurable Tree row height
Now it's 28px, and it's hardcoded in two places - in java code and in valo theme.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9411

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9540)

### CODE REVIEW

**Comment by elmot** [comment]
The change might explode Tree component design. Let's run that and have a look how the looks like.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540#-:-KmesuGvPDNpcvOcBaXT:b1md2nz)*

**Comment by elmot** [comment]
@hesara please have at the screenshot. Is that acceptable?


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540#-:-Kmg4-TP11N2mWSp1ey3:b-ch69yl)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540)*

**Comment by hesara** [comment]
Not vertically centered and apparently there is no clean way to change the whole renderer (a separate API exists for setting the content, to help support icons). Thus, I'd ideally like to see an example or two of actually using this before merging this (perhaps one with just vertically centered larger text, one with more complex content).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540#-:-KmzawjwEmw99qjqSBaf:bws7ro2)*

**Comment by tsuoanttila** [comment]
The last remaining issue is the placement of the expand icon when having multiple lines of content. Need to discuss that with @jouni 

screen shot 2017-06-20 at 11 22 11

**Comment by hesara** [comment]
Reviewed 5 of 6 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540)*

**Comment by hesara** [comment]
Reviewed 1 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9540)*

**Pull request merged**
