### PR TITLE
Improve commit message example in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10357)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/10357#-KzcWNsTNpNrH1pCIBvj:-KzcWNsTNpNrH1pCIBvk:b-g1kqjy) ([raw file](https://github.com/vaadin/framework/blob/94f19bf4ade2ee12ac163266427ea2264562f595/CONTRIBUTING.md#L92)):*
> ```Markdown
> 
>     For backwards compatibility, Font Awesome is loaded by default
>     
> ```

extra whitespace

---

*[CONTRIBUTING.md, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/10357#-KzcWPUtjvbAmf8oY5mh:-KzcWPUtjvbAmf8oY5mi:b-g1kqjy) ([raw file](https://github.com/vaadin/framework/blob/94f19bf4ade2ee12ac163266427ea2264562f595/CONTRIBUTING.md#L112)):*
> ```Markdown
> 
>     For backwards compatibility, Font Awesome is loaded by default
>     
> ```

extra whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10357#-:-KzcWDQvTAiBFl-BU_zV:bnfp4nl)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10357#-KzcWTMZPGJaQeVtnN65:-KzcWTMZPGJaQeVtnN66:bplkdoi) (no related file):*
Can be merged even without the fix. just nit picking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10357)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/10357#-KzcWNsTNpNrH1pCIBvj:-KzcXLoCQVOkUQttB9ry:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/94f19bf4ade2ee12ac163266427ea2264562f595/CONTRIBUTING.md#L92)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.

---

*[CONTRIBUTING.md, line 112 at r1](https://reviewable.io:443/reviews/vaadin/framework/10357#-KzcWPUtjvbAmf8oY5mh:-KzcXMDr4OqllsH73_tx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/94f19bf4ade2ee12ac163266427ea2264562f595/CONTRIBUTING.md#L112)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

extra whitespace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10357)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10357)*

**Pull request merged**
