### PR TITLE
Add dependency filters through the service init event

### PR DESCRIPTION
**Pull request by Legioth**
We shouldn't create new service loader interfaces since each new such
interface has implications for custom integrations. Instead, the
VaadinServiceInitListener mechanism should be enhanced to allow such
listeners to introduce their own dependency filter implementations
similarly to how VaadinServiceInitListener can already be used to
contribute new request handlers

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9368)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/ServiceInitEvent.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQNWV7b8itfV80EGTr:-KkQNWV7b8itfV80EGTs:bptolne) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/ServiceInitEvent.java#L79)):*
> ```Java
>      *
>      * @param dependencyFilter
>      *            the dependency filter to add, not <code>null</code>
> ```

@since 8.1

---

*[server/src/main/java/com/vaadin/server/ServiceInitEvent.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQNYPsloNMrbesBGiH:-KkQNYPsloNMrbesBGiI:bptolne) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/ServiceInitEvent.java#L92)):*
> ```Java
>      * for the service.
>      *
>      * @return the current list of added dependency filters.
> ```

@since 8.1

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1447 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQbRC7ROpJvcQpWW_M:-KkQbRC7ROpJvcQpWW_N:bo8dtjy) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/VaadinService.java#L1447)):*
> ```Java
> 
>     /**
>      * Constructs the list of resource dependency filters to use for the
> ```

maybe this javadoc should be formulated differently as the list is not collected here but given from outside, and not constructed here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Comment by Legioth** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/ServiceInitEvent.java, line 79 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQNWV7b8itfV80EGTr:-KkQzuojU6G-mFISP291:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/ServiceInitEvent.java#L79)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/ServiceInitEvent.java, line 92 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQNYPsloNMrbesBGiH:-KkQzvOs0yHN7dgAVXyN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/ServiceInitEvent.java#L92)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1447 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQbRC7ROpJvcQpWW_M:-KkQzwJNwNiJAughlte-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/VaadinService.java#L1447)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

maybe this javadoc should be formulated differently as the list is not collected here but given from outside, and not constructed here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Comment by ahie** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Comment by ahie** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1447 at r1](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkQbRC7ROpJvcQpWW_M:-KkVDDlqN3gXQbptcj9b:b-ib0zfu) ([raw file](https://github.com/vaadin/framework/blob/52f4390a9e2ac4e726d155d73fe695349cbc9d14/server/src/main/java/com/vaadin/server/VaadinService.java#L1447)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd like a bit more changes as reading this javadoc leads to a very unclear picture of who does what unless you know the history and the feature. This doesn't even say that the method is called by the framework (although it is mentioned below that this can be overridden to customize the order), leaves it quite open who/what collects filters from SessionInitEvent etc.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1481 at r2](https://reviewable.io:443/reviews/vaadin/framework/9368#-KkVDAoBwckccHGyuCRD:-KkVDAoBwckccHGyuCRE:bneeimz) ([raw file](https://github.com/vaadin/framework/blob/ce185fb291002a5ba76e48135aea9ccd564ef9f9/server/src/main/java/com/vaadin/server/VaadinService.java#L1481)):*
> ```Java
>      * before being sent to the client for loading.
>      *
>      * @see #createDependencyFilters()
> ```

javadoc refers to wrong method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9368)*

**Pull request merged**
