### PR TITLE
Add tip for GUI components with Vaadin 8

### PR DESCRIPTION
**Pull request by hypergori**
The tutorial learner with Vaadin Framework 8, should use different setting and component for Customer form, from video tutorial, which is for Vaadin 7.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8899)

### CODE REVIEW

**Comment by mstahv** [comment]
Looks like a good tip to me until we get the updated video out.

@alejandro-du was the video already in post production? When is it out? Maybe take this in until it is published?

**Comment by mstahv** [comment]
Ah, but that was actually from the Designer video. I guess that is still on TODO list, so let's pull this in.

**Comment by mstahv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/tutorial.adoc, line 552 at r1](https://reviewable.io:443/reviews/vaadin/framework/8899#-Kfq6y3V77eHwthLYHsn:-Kfq6y3V77eHwthLYHso:b-l1gwut) ([raw file](https://github.com/vaadin/framework/blob/f9db1e9a1fa3b9157bedfebbda8265d79a926cad/documentation/tutorial.adoc#L552)):*
> ```AsciiDoc
> copy-paste the content of https://github.com/vaadin/tutorial/blob/master/src/main/resources/my/vaadin/app/CustomerFormDesign.html[the final state] to your own .html file.
> 
> TIP: Some difference in video with Vaadin Framework 8, 
> ```

Maybe the beginning could be "TIP: With Vaadin Framework 8, make following things differently:"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8899)*

**Comment by hypergori** [comment]
*[documentation/tutorial.adoc, line 552 at r1](https://reviewable.io:443/reviews/vaadin/framework/8899#-Kfq6y3V77eHwthLYHsn:-KfqCn3wHpcYFf7rgOAQ:b-l3go2k) ([raw file](https://github.com/vaadin/framework/blob/f9db1e9a1fa3b9157bedfebbda8265d79a926cad/documentation/tutorial.adoc#L552)):*
<details><summary><i>Previously, mstahv (Matti Tahvonen) wrote…</i></summary><blockquote>

Maybe the beginning could be "TIP: With Vaadin Framework 8, make following things differently:"
</blockquote></details>

 Yes, it is better. I edited it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8899)*

**Comment by mstahv** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8899#-:-KfqOYu5q_YXvOJCeFoW:bnfp4nl)*

**Comment by mstahv** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8899)*

**Pull request merged**
