### PR TITLE
Deprecate old DnD functionality

### LINKED ISSUE #8795: Deprecate old DnD support and remove documentation

### PR DESCRIPTION
**Pull request by pleku**
Fixes #8795

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8864)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 32 of 35 files at r1.
Review status: 32 of 35 files reviewed at latest revision, 18 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VAbstractDropHandler.java, line 29 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfQAiWaAB9ulw4yVb73:-KfQAiWaAB9ulw4yVb74:bn9bzw7) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VAbstractDropHandler.java#L29)):*
> ```Java
> 
> /**
>  *
> ```

(no comment here?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VAcceptAll.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfQAmZsqt9V1nX9hcDq:-KfQAmZsqt9V1nX9hcDr:b-5ap7ub) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VAcceptAll.java#L25)):*
> ```Java
> 
> /**
>  *
> ```

(no comment?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VAcceptCallback.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfesW_3VdV_y11eNekT:-KfesW_3VdV_y11eNekU:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VAcceptCallback.java#L21)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VAcceptCriterion.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfeskU-bCUJdSptO86i:-KfeskU-bCUJdSptO86j:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VAcceptCriterion.java#L22)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VAnd.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfesnlxxiNS0eUjCj0T:-KfesnlxxiNS0eUjCj0U:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VAnd.java#L24)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VContainsDataFlavor.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfesq5iiZwD6WMp63if:-Kfesq5iiZwD6WMp63ig:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VContainsDataFlavor.java#L24)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEventServerCallback.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfet7Fe64Es2yysmkcQ:-Kfet7Fe64Es2yysmkcR:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VDragEventServerCallback.java#L22)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragEventServerCallback.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfet8I2MtdVoyh0rA99:-Kfet8I2MtdVoyh0rA9A:bas5h0b) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VDragEventServerCallback.java#L24)):*
> ```Java
>  *
>  * @author Vaadin Ltd
>  * @deprecated Replaced in 8.1 {@link DropTargetRpc}
> ```

(technically, I think this is also used for other things than the drop itself - but probably not an issue)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VDragSourceIs.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfetP6GQffS5bZjD6eX:-KfetP6HhbyRE1dimzdK:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VDragSourceIs.java#L25)):*
> ```Java
> import com.vaadin.shared.ui.dd.AcceptCriterion;
> 
> /**
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VNot.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfer9Y05VXzULZBrvVo:-Kfer9Y1MoXsXkgFxEQj:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VNot.java#L25)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VOr.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferF65lBljqcf8XmDu:-KferF65lBljqcf8XmDv:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VOr.java#L24)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VOverTreeNode.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferHrH-C8ig1mpFXlN:-KferHrIyFMw89Sl9wi7:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VOverTreeNode.java#L21)):*
> ```Java
> import com.vaadin.event.dnd.DropTargetExtension;
> 
> /**
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VServerAccept.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferKMNMcUJVJTRRIKp:-KferKMNMcUJVJTRRIKq:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VServerAccept.java#L23)):*
> ```Java
> import com.vaadin.shared.ui.dd.AcceptCriterion;
> 
> /**
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VSourceIsTarget.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferMG1ZCMMhdn4RyGU:-KferMG1ZCMMhdn4RyGV:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VSourceIsTarget.java#L25)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VTargetDetailIs.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferP7wNwr_lZhF8KwR:-KferP7wNwr_lZhF8KwS:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VTargetDetailIs.java#L23)):*
> ```Java
> import com.vaadin.shared.ui.dd.AcceptCriterion;
> 
> /**
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/draganddropwrapper/DragAndDropWrapperConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KferXtugVee5ImegXRE:-KferXtugVee5ImegXRF:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/draganddropwrapper/DragAndDropWrapperConnector.java#L38)):*
> ```Java
> import com.vaadin.ui.DragAndDropWrapper;
> 
> /**
> ```

(no javadoc?)

---

*[server/src/main/java/com/vaadin/server/DragAndDropService.java, line 47 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfes34xsAiH3sGzNvmD:-Kfes34xsAiH3sGzNvmE:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/server/src/main/java/com/vaadin/server/DragAndDropService.java#L47)):*
> ```Java
> import elemental.json.JsonObject;
> 
> /**
> ```

(no javadoc?)

---

*[server/src/main/java/com/vaadin/ui/DragAndDropWrapper.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfes9xiwfDEkTc3E8ST:-Kfes9xiwfDEkTc3E8SU:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/server/src/main/java/com/vaadin/ui/DragAndDropWrapper.java#L49)):*
> ```Java
> import com.vaadin.ui.declarative.DesignContext;
> 
> /**
> ```

(no javadoc?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8864)*

**Comment by hesara** [comment]
Reviewed 3 of 35 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VHtml5File.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfeuSVlJvliTuWOwbCn:-KfeuSVlJvliTuWOwbCo:b4c3782) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VHtml5File.java#L25)):*
> ```Java
>  * 
>  * @author Vaadin Ltd
>  * @deprecated Since 8.1, no direct replacement currently, see
> ```

maybe a ticket for this would be good; this is a clear feature regression

---

*[client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfetymhU6E8SRygPr1W:-KfetymhU6E8SRygPr1X:b5k1yo4) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java#L24)):*
> ```Java
> 
> /**
>  *
> ```

(no javadoc?)

---

*[client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfetv7Tt66IGKNSdTkD:-Kfetv7U7qbiL2WkMPvy:b1qt29b) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java#L26)):*
> ```Java
>  *
>  * @author Vaadin Ltd
>  * @deprecated Replaced in 8.1 with {@link DropTargetExtensionConnector}
> ```

should this refer to DropTargetExtension.setAcceptCriteria()?

---

*[client/src/main/java/com/vaadin/client/ui/dd/VTransferable.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfeuCKVzFg9UBmdiAHx:-KfeuCKVzFg9UBmdiAHy:b5ays6v) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VTransferable.java#L30)):*
> ```Java
>  *
>  * @author Vaadin Ltd
>  * @deprecated Replaced in 8.1 with {@link DragSourceExtensionConnector}
> ```

(really hard to say what really replaces this, but I guess this is ok)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8864)*

**Comment by pleku** [comment]
Review status: 32 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VHtml5File.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-KfeuSVlJvliTuWOwbCn:-KflCgsrVBytLW1QyC1P:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VHtml5File.java#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

maybe a ticket for this would be good; this is a clear feature regression
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java, line 26 at r1](https://reviewable.io:443/reviews/vaadin/framework/8864#-Kfetv7Tt66IGKNSdTkD:-KflCtWGJ9xnRPSRWvnf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3493d577e96318e526cd7e719ae7b426c2c9d6a7/client/src/main/java/com/vaadin/client/ui/dd/VLazyInitItemIdentifiers.java#L26)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should this refer to DropTargetExtension.setAcceptCriteria()?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8864)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8864#-:-KflGh9sgli9jIihJh64:bnfp4nl)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8864#-KflJIj-GMXk3eUHfJma:-KflJIj-GMXk3eUHfJmb:bsspyis) (no related file):*
This does not remove the old DnD documentation, and thus only partly addresses #8795.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8864)*

**Pull request merged**
