### PR TITLE
Preliminary version of OSGi deployment manual

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9499)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/portal/portal-osgi.asciidoc, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9oGcw29kkf6jSk6Z:-Kn-9oGdoRjc3fDp3SO3:b-e31zb1) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L64)):*
> ```AsciiDoc
> 
> [[portal.osgi.portlet.gradle]]
> == Deployment a Portlet With OSGi(Gradle)
> ```

space missing after OSGi

---

*[documentation/portal/portal-osgi.asciidoc, line 65 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9qzyIdxwgxsb24_C:-Kn-9qzyIdxwgxsb24_D:b-3zmpse) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L65)):*
> ```AsciiDoc
> [[portal.osgi.portlet.gradle]]
> == Deployment a Portlet With OSGi(Gradle)
> Here is an example of Liferay workspace with a portlet module and short readme how to deploy that to Liferay portal.
> ```

a Liferay workspace ... a short readme on how to deploy that to a Liferay portal

---

*[documentation/portal/portal-osgi.asciidoc, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9yIpgseb7AKATqDP:-Kn-9yIpgseb7AKATqDQ:bro8lq0) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L66)):*
> ```AsciiDoc
> == Deployment a Portlet With OSGi(Gradle)
> Here is an example of Liferay workspace with a portlet module and short readme how to deploy that to Liferay portal.
> https://github.com/elmot/liferay-7-solid-portlet-example/
> ```

use link formatting; ideally would move this to a Vaadin GitHub repo

---

*[documentation/portal/portal-osgi.asciidoc, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-AD2LZ8MobBsPrAZo:-Kn-AD2LZ8MobBsPrAZp:bkifmge) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L72)):*
> ```AsciiDoc
> An OSGi portlet should be packaged as a JAR with a proper OSGi bundle
> manifest, and deployed to a portal that has its required bundles installed.
> Maven archetype `com.vaadin:vaadin-archetype-liferay-portlet:8.1.0` is a good starting point to build an OSGi portlet application.
> ```

The Maven archetype ...

---

*[documentation/portal/portal-osgi.asciidoc, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-AJnR7lUCp-jpF64b:-Kn-AJnR7lUCp-jpF64c:b-xukatp) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L74)):*
> ```AsciiDoc
> Maven archetype `com.vaadin:vaadin-archetype-liferay-portlet:8.1.0` is a good starting point to build an OSGi portlet application.
> The required bundles (and the application as well) can be installed using link:https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/blade-cli[blade client].
> The latest client binary can be downloaded from the link: link:https://releases.liferay.com/tools/blade-cli/latest/blade.jar[]
> ```

link name?

---

*[documentation/portal/portal-osgi.asciidoc, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-ANReCgxVXfrLpBMa:-Kn-ANReCgxVXfrLpBMb:bjraige) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L77)):*
> ```AsciiDoc
> 
> Here is an example script for doing that:
> //TODO change URLs to maven central when 8.1 is out
> ```

TBC: is this comment visible in the generated document or not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9499)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[documentation/portal/portal-osgi.asciidoc, line 64 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9oGcw29kkf6jSk6Z:-Kn-Rynjsl5vsullVXJS:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L64)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

space missing after OSGi
</blockquote></details>

Done.

---

*[documentation/portal/portal-osgi.asciidoc, line 65 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9qzyIdxwgxsb24_C:-Kn-SUlFF2XXd6YfRlB1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L65)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

a Liferay workspace ... a short readme on how to deploy that to a Liferay portal
</blockquote></details>

Done.

---

*[documentation/portal/portal-osgi.asciidoc, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9yIpgseb7AKATqDP:-Kn-Y5dR7aMZ-bLgaEMa:b-nz1nzw) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L66)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

use link formatting; ideally would move this to a Vaadin GitHub repo
</blockquote></details>

Done. Without link name intentionally

---

*[documentation/portal/portal-osgi.asciidoc, line 72 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-AD2LZ8MobBsPrAZo:-Kn-Rqtw-Yr6B_9-hq-F:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L72)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

The Maven archetype ...
</blockquote></details>

Done.

---

*[documentation/portal/portal-osgi.asciidoc, line 74 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-AJnR7lUCp-jpF64b:-Kn-QyxE2nQwhRwT_e7B:b-z9mhbp) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L74)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

link name?
</blockquote></details>

IMHO no need. Asciidoctor shows the URL as the name, and that is supposed be here.

---

*[documentation/portal/portal-osgi.asciidoc, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-ANReCgxVXfrLpBMa:-Kn-QJweJ4gz4IPeU-_3:b-a2sb0n) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L77)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

TBC: is this comment visible in the generated document or not?
</blockquote></details>

Should not be visible. That is a standard asciidoc single-line comment syntax

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9499)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/portal/portal-osgi.asciidoc, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-9yIpgseb7AKATqDP:-KpxWPtw9VTYDajsoYSx:b65bv9q) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L66)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Done. Without link name intentionally
</blockquote></details>

(I hope this works correctly on the site and in the book without link name)

---

*[documentation/portal/portal-osgi.asciidoc, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-ANReCgxVXfrLpBMa:-KpxW_xHckW6f_fqZ76Q:b-rst6ce) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L77)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Should not be visible. That is a standard asciidoc single-line comment syntax
</blockquote></details>

update URLs now that 8.1 is out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9499)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/portal/portal-osgi.asciidoc, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/9499#-Kn-ANReCgxVXfrLpBMa:-KqNEDM_k6dq541vKfav:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/d090bb0bb12e8b818376c08ddc0ed7e8870a1226/documentation/portal/portal-osgi.asciidoc#L77)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

update URLs now that 8.1 is out
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9499)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9499)*

**Pull request merged**
