### PR TITLE
Make DragSourceExtension and DragTargetExtension generic

### PR DESCRIPTION
**Pull request by wbadam**
#8440

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8628)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQeWNqe9Ql10I-pB6e:-KdQeWNqe9Ql10I-pB6f:bu2w0lt) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L82)):*
> ```Java
> 
>     @Override
>     @SuppressWarnings("unchecked")
> ```

NIT: these are unnecessary, doesn't really do harm in a getter but should be avoided elsewhere

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQerk2UqLDWDA6EQo8:-KdQerk2UqLDWDA6EQo9:b-13aymw) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L66)):*
> ```Java
>      *         Component to be extended.
>      */
>     public void extend(AbstractComponent target) {
> ```

You should probably keep this overridden to ensure the user cannot break this by either

a) `throw UnsupportedOperationException("Cannot change extended component on the run)`- since it won't work as expected after that
b) make sure that the type of the given component is correct, and then call internal method that does the things that are done in the constructor currently

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 227 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgFrjXJ_r2CQtbpmx:-KdQgFrjXJ_r2CQtbpmy:bqe0c7x) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L227)):*
> ```Java
>     @Override
>     @SuppressWarnings("unchecked")
>     public T getParent() {
> ```

Could probably override javadocs to be more specific

---

*[server/src/main/java/com/vaadin/event/dnd/DragStartEvent.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgTdgsvo_1ocjz3p1:-KdQgTdgsvo_1ocjz3p2:bjluzea) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragStartEvent.java#L84)):*
> ```Java
>     @Override
>     @SuppressWarnings("unchecked")
>     public T getComponent() {
> ```

Could override javadocs to be more specific

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgZFfq2qXumFo63Qn:-KdQgZFfq2qXumFo63Qo:bjluzea) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L83)):*
> ```Java
>     @Override
>     @SuppressWarnings("unchecked")
>     public T getComponent() {
> ```

Could override javadocs to be more specific

---

*[server/src/main/java/com/vaadin/event/dnd/DropTargetExtension.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgseKqPy7MK9lZWuc:-KdQgseKqPy7MK9lZWud:bqespnh) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DropTargetExtension.java#L52)):*
> ```Java
>      *         Component to be extended.
>      */
>     public void extend(AbstractComponent target) {
> ```

Same thing as with `DragSourceExtension`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8628)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQeWNqe9Ql10I-pB6e:-KdQlX6Mjjjmip3Ge_JT:b-ht6wbn) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L82)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: these are unnecessary, doesn't really do harm in a getter but should be avoided elsewhere
</blockquote></details>

Do you mean the `@SuppressWarnings` annotation? What to use instead? Isn't _Unchecked cast_ warning more ugly?
Also, what does NIT mean? :)

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQerk2UqLDWDA6EQo8:-KdQoKkXtcHB3RXf1nK3:bnmpdpj) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L66)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

You should probably keep this overridden to ensure the user cannot break this by either

a) `throw UnsupportedOperationException("Cannot change extended component on the run)`- since it won't work as expected after that
b) make sure that the type of the given component is correct, and then call internal method that does the things that are done in the constructor currently
</blockquote></details>

I'm probably missing the point here, I'm not sure if that would help in making the extension safer. Please help me understand.

Do you have an example of how the user can break it? The only one I can think of is if they extend the extension and override it's `extend()` method with a custom `public` one. Shouldn't in that case be obvious for the user that they are messing with functionality?

In case of a), the exception would be thrown only in case of a super call
In b) the user could override `extend()` just as easily and do something nasty

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8628)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQeWNqe9Ql10I-pB6e:-KdQrJGQ3tF2tts5yNE6:b-f3rpoz) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L82)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

Do you mean the `@SuppressWarnings` annotation? What to use instead? Isn't _Unchecked cast_ warning more ugly?
Also, what does NIT mean? :)
</blockquote></details>

This is just framework internal, those warnings don't necessarily matter. Suppressing them might hide bugs, if for instance there is some other unchecked cast being done that is not intended.

NIT - It is short from nitpicking, just pointing out really small stuff that don't really matter that much ... definitely not a blocker

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQerk2UqLDWDA6EQo8:-KdQsZO6pLhsFLfZDdst:b5snqz2) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L66)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

I'm probably missing the point here, I'm not sure if that would help in making the extension safer. Please help me understand.

Do you have an example of how the user can break it? The only one I can think of is if they extend the extension and override it's `extend()` method with a custom `public` one. Shouldn't in that case be obvious for the user that they are messing with functionality?

In case of a), the exception would be thrown only in case of a super call
In b) the user could override `extend()` just as easily and do something nasty
</blockquote></details>

My bad sorry, forgot that the `extend` is protected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8628)*

**Comment by wbadam** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQeWNqe9Ql10I-pB6e:-KdR8PalcDK851o7eHmv:bscglqn) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragEndEvent.java#L82)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is just framework internal, those warnings don't necessarily matter. Suppressing them might hide bugs, if for instance there is some other unchecked cast being done that is not intended.

NIT - It is short from nitpicking, just pointing out really small stuff that don't really matter that much ... definitely not a blocker
</blockquote></details>

I see. Honestly I don't really like these warnings so I leave the annotations and remember not to use them in more complicated cases.
But let me know if you would like them to be removed in this case anyway.

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQerk2UqLDWDA6EQo8:-KdR3l6zwdyVevQtOpc3:bie6oy9) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L66)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

My bad sorry, forgot that the `extend` is protected.
</blockquote></details>

Right, so I leave it like that. Let me know if it needs change.

---

*[server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java, line 227 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgFrjXJ_r2CQtbpmx:-KdR5UfSUf_XpTkNBTxd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragSourceExtension.java#L227)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could probably override javadocs to be more specific
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DragStartEvent.java, line 84 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgTdgsvo_1ocjz3p1:-KdR67a0vboCftCY-fFf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DragStartEvent.java#L84)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could override javadocs to be more specific
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DropEvent.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgZFfq2qXumFo63Qn:-KdR6sOIsw794zY7NdaV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/ad37e70da2b721e2c277df783cf4d26523b53c1d/server/src/main/java/com/vaadin/event/dnd/DropEvent.java#L83)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could override javadocs to be more specific
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/event/dnd/DropTargetExtension.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8628#-KdQgseKqPy7MK9lZWuc:-KdR6xC9DzdFSW324yYV:b-6aebco) ([raw file](https://github.com/vaadin/framework/blob/02666227a2550b8e918dbc86f7c59ec7b1daff05/server/src/main/java/com/vaadin/event/dnd/DropTargetExtension.java#L52)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Same thing as with `DragSourceExtension`
</blockquote></details>

I'll also leave it until further notice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8628)*

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8628)*

**Pull request merged**
