### PR TITLE
Replace drag over class name with conventional ones

### LINKED ISSUE #9058: Use class names according to convention on HTML5 drop target
Current `v-drag-over` class should be replaced and class names should be `{widget-name}-drop-center`/`top`/`bottom`.

E.g. on Grid row class names should be `v-grid-row-drag-center`, `v-grid-row-drag-top` and `v-grid-row-drag-bottom`.

### PR DESCRIPTION
**Pull request by wbadam**
Resolves  #9058

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9059)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDropTargetConnector.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhS68uFmTvt6Ck8WqyF:-KhS68uFmTvt6Ck8WqyG:b-w1oduv) ([raw file](https://github.com/vaadin/framework/blob/04720680d9f04585ab4a02555d85a4104e131d70/client/src/main/java/com/vaadin/client/connectors/grid/GridDropTargetConnector.java#L85)):*
> ```Java
>         // Generate class names
>         String styleRow =
>                 gridConnector.getWidget().getStylePrimaryName() + "-row";
> ```

The primary style name can be changed from server side API at any time, so these should be created again for every time when they are needed on `dragover` or whatnot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9059)*

**Comment by wbadam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDropTargetConnector.java, line 85 at r1](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhS68uFmTvt6Ck8WqyF:-KhTEYSbF1ETyMBZz_d6:b-hnsg2f) ([raw file](https://github.com/vaadin/framework/blob/04720680d9f04585ab4a02555d85a4104e131d70/client/src/main/java/com/vaadin/client/connectors/grid/GridDropTargetConnector.java#L85)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

The primary style name can be changed from server side API at any time, so these should be created again for every time when they are needed on `dragover` or whatnot
</blockquote></details>

Didn't occurred to me at all. I generate the style names on every `dragenter` and during drag there shouldn't be a style name change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9059)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 46 at r2](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhTMjzK-a2_W_Y5RJZr:-KhTMjzLU5t3zr4qRe9c:b-yqdkdi) ([raw file](https://github.com/vaadin/framework/blob/ea3cd003df2d87064f77417e956249a324773a02/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L46)):*
> ```Java
>     protected static final String STYLE_SUFFIX_DRAG_CENTER = "-drag-center";
>     protected static final String STYLE_SUFFIX_DRAG_TOP = "-drag-top";
>     protected static final String STYLE_SUFFIX_DRAG_BOTTOM = "-drag-bottom";
> ```

So now these are not just `Grid` specific but also should apply for other components ? 

Also as they're protected meaning public API, you should have javadocs

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 73 at r2](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhTN2BpdDdGJY8aKuty:-KhTN2BpdDdGJY8aKutz:b78i1y8) ([raw file](https://github.com/vaadin/framework/blob/ea3cd003df2d87064f77417e956249a324773a02/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L73)):*
> ```Java
>         // Generate class name
>         styleDragCenter = dropTargetWidget.getStylePrimaryName()
>                 + STYLE_SUFFIX_DRAG_CENTER;
> ```

This probably ought to be removed now that is created always in drag enter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9059)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 46 at r2](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhTMjzK-a2_W_Y5RJZr:-KhTviw0lVMkwB1xEaR4:b-v0muju) ([raw file](https://github.com/vaadin/framework/blob/ea3cd003df2d87064f77417e956249a324773a02/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L46)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

So now these are not just `Grid` specific but also should apply for other components ? 

Also as they're protected meaning public API, you should have javadocs
</blockquote></details>

Well Jarmo said that from UX point of view a drop target generally could accept drops in the centre and on four sides, and now we are using three of them in Grid. I think it is good if it's public API

---

*[client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java, line 73 at r2](https://reviewable.io:443/reviews/vaadin/framework/9059#-KhTN2BpdDdGJY8aKuty:-KhTxExiI6amEUXM-8tc:b-pcdfdj) ([raw file](https://github.com/vaadin/framework/blob/ea3cd003df2d87064f77417e956249a324773a02/client/src/main/java/com/vaadin/client/extensions/DropTargetExtensionConnector.java#L73)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This probably ought to be removed now that is created always in drag enter
</blockquote></details>

Tru dat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9059)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9059)*

**Pull request merged**
