### PR TITLE
Make Grid rows draggable

### PR DESCRIPTION
**Pull request by wbadam**
Created drag source extension for Grid that makes each row draggable.
Created a simple test UI for validating the functionality.
Does _not_ add callback for changing the dragged row's data.
#8396

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8690)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdynDTJ2ehPpY1cTB_y:-KdynDTKFs0mfDyCMWQ7:b-802enx) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L36)):*
> ```Java
>  * Grid}'s rows. This is the client side counterpart of {@link
>  * GridDragSourceExtension}.
>  */
> ```

Should add `@author Vaadin Ltd`

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdynIU5XgUYVhMp60Sw:-KdynIU6J1sdI9iWIMGR:b-xz86qb) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L38)):*
> ```Java
>  */
> @Connect(GridDragSourceExtension.class)
> public class GridDragSourceExtensionConnector extends
> ```

Sorry I've forgot to mention that you should add empty `@since ` to _all_ the files you've introduced. That includes this patch, and the files in the previous patches already in master branch.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdypmxTjNXdkoHBUksL:-KdypmxTjNXdkoHBUksM:buoo0ce) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L48)):*
> ```Java
> 
>         // Set newly added rows draggable
>         getGridBody().setNewEscalatorRowCallback(
> ```

This is not removed on `onUnregister()` ?

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-Kdyq9gHJhoIiOYKvemA:-Kdyq9gHJhoIiOYKvemB:buumb5y) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L90)):*
> ```Java
> 
>     /**
>      * Adds drag event listeners to the given DOM element.
> ```

Might add that the listeners add that the listeners are for `dragstart` and `dragend` events.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyqP07-jHdH07Qfrr3:-KdyqP07-jHdH07Qfrr4:b-lvx3z5) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L103)):*
> ```Java
> 
>     /**
>      * Removes drag event listeners from the given DOM element.
> ```

"Remvoes drag start and end event listeners .."

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4012 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyqahXCrErf8Y03d2w:-KdyqahXCrErf8Y03d2x:bkmjlii) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4012)):*
> ```Java
>         }
> 
>         public void setNewEscalatorRowCallback(
> ```

missing `@Override`?

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-Kdyqp0uj8kNyWqWoj6c:-Kdyqp0uj8kNyWqWoj6d:b-9ydpk0) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L22)):*
> ```Java
> 
> /**
>  * Adds HTML5 drag and drop functionality to a {@link Grid}'s rows.
> ```

Add `@author Vaadin Ltd`

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyrQfKsHSV8PEvy_hp:-KdyrQfKsHSV8PEvy_hq:bz65rkq) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L23)):*
> ```Java
> /**
>  * Adds HTML5 drag and drop functionality to a {@link Grid}'s rows.
>  */
> ```

Please elaborate what this extension actually does. Does it add support for both, _drag_ and _drop_  or just the former ?

What happens to the grid's rows after adding this extension ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8690)*

**Comment by hesara** [comment]
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdynIU5XgUYVhMp60Sw:-KdysPxDskePz8V0CtSl:b-uo0210) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L38)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Sorry I've forgot to mention that you should add empty `@since ` to _all_ the files you've introduced. That includes this patch, and the files in the previous patches already in master branch.
</blockquote></details>

For the files already in master, this can be "@since 8.1" (though that should probably happen in master rather than in the feature branch) - for things not yet in master, just "@since" that will be filled in when merged and the (release) build complains about these

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8690)*

**Comment by wbadam** [comment]
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 36 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdynDTJ2ehPpY1cTB_y:-KdzDp0VsAntY4NT5vG8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L36)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should add `@author Vaadin Ltd`
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 38 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdynIU5XgUYVhMp60Sw:-KdzDwdmdpKHwPQ-0non:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L38)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

For the files already in master, this can be "@since 8.1" (though that should probably happen in master rather than in the feature branch) - for things not yet in master, just "@since" that will be filled in when merged and the (release) build complains about these
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdypmxTjNXdkoHBUksL:-KdzE0GMu33ONIYVr-x2:btull6u) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceExtensionConnector.java#L48)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This is not removed on `onUnregister()` ?
</blockquote></details>

Yes, was gonna do that...

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-Kdyq9gHJhoIiOYKvemA:-KdzEsDfQnQ5hNsPp6Ud:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L90)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Might add that the listeners add that the listeners are for `dragstart` and `dragend` events.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 103 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyqP07-jHdH07Qfrr3:-KdzF2mWDinPr8ALUGe_:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L103)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

"Remvoes drag start and end event listeners .."
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Escalator.java, line 4012 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyqahXCrErf8Y03d2w:-KdzF94GXDWVCfkqXdc0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/client/src/main/java/com/vaadin/client/widgets/Escalator.java#L4012)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing `@Override`?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-Kdyqp0uj8kNyWqWoj6c:-KdzFKe4X4ElqWx-8YAn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L22)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Add `@author Vaadin Ltd`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8690#-KdyrQfKsHSV8PEvy_hp:-KdzGhTvjwc9hwAzXZy9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0673d30af58da33350cdbd2155f28446588f2276/server/src/main/java/com/vaadin/ui/GridDragSourceExtension.java#L23)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please elaborate what this extension actually does. Does it add support for both, _drag_ and _drop_  or just the former ?

What happens to the grid's rows after adding this extension ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8690)*

**Comment by pleku** [comment]
Reviewed 1 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8690)*

**Pull request merged**
