### PR TITLE
Fix ComponentLocator with inherited classes without custom connector

### PR DESCRIPTION
**Pull request by tsuoanttila**
Logic for finding elements corresponding a server-side classname does
not work with inherited classes. For example making MyGrid extends Grid,
you could not find the specific MyGrid, but only the common Grid.

In most cases this is not a problem since these components are usually
the only instance of said superclass, but the Composite introduced in
the same UI, which makes testing them impossible.

This patch adds the specific classname information for ServerConnectors
that can be used to find the correct connector instance.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9176)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijD63yenAWQc1PnPj7:-KijD63yenAWQc1PnPj8:bz6zdfi) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L224)):*
> ```Java
>      *
>      * @param tag
>      *            the connector type tag
> ```

@since 8.1 here and below

---

*[client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java, line 611 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijEMNVxKc3uiiKIq19:-KijEMNVxKc3uiiKIq1A:bosldfi) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java#L611)):*
> ```Java
> 
>         List<String> ids = getIDsForConnector(connector);
>         String exactClass = connector.getConnection().getConfiguration()
> ```

Can this change break existing tests? A full test build would be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/AbstractConnector.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijF99phltJwKxuJzeJ:-KijF99phltJwKxuJzeK:b4ri131) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ui/AbstractConnector.java#L534)):*
> ```Java
> 
>     @Override
>     public void setTag(int tag) {
> ```

Javadocs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by Artur-** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijBn1S3f4-mjh6qhzH:-KijBn1S3f4-mjh6qhzI:b-nh0y9z) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L229)):*
> ```Java
> 
>     /**
>      * Gets the connector type tag for this connector.
> ```

Could add some info about what the tag is and who should use it for what (or not use it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijD63yenAWQc1PnPj7:-KijGjHDuXyJYiC0w9ab:b-7n5l6y) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L224)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since 8.1 here and below
</blockquote></details>

Technically this issue exists also in 7.7 and 8.0. We don't want to backport it ?

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijBn1S3f4-mjh6qhzH:-KijGpUbQUIrOv6-290h:bcjx5id) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L229)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Could add some info about what the tag is and who should use it for what (or not use it)
</blockquote></details>

I tried to find some existing documentation on these tags so I could point to a place where they are described in detail. Could not find anything useful in my search. Not sure how to describe these so that anyone would understand it. (Not sure if I get the point myself even)

---

*[client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java, line 611 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijEMNVxKc3uiiKIq19:-KijH9XHINvuVLikzn7X:b-lttin9) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java#L611)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Can this change break existing tests? A full test build would be good.
</blockquote></details>

Should not break any existing tests. Full test build could indeed be run.

---

*[client/src/main/java/com/vaadin/client/ui/AbstractConnector.java, line 534 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijF99phltJwKxuJzeJ:-KijHFLl67dBVC0EXcBW:bqmmo7k) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ui/AbstractConnector.java#L534)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Javadocs?
</blockquote></details>

JavaDoc in the interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijD63yenAWQc1PnPj7:-Kj7Z1wdpXo6w2w_WLiT:b-igy9ou) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L224)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Technically this issue exists also in 7.7 and 8.0. We don't want to backport it ?
</blockquote></details>

I'd say @since 8.1 for now, and only backport if there is specific demand for this.

---

*[client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java, line 611 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijEMNVxKc3uiiKIq19:-Kj7_hkNpAsIUhJdIPrA:b-245b31) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/componentlocator/VaadinFinderLocatorStrategy.java#L611)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should not break any existing tests. Full test build could indeed be run.
</blockquote></details>

now rerunning Chrome tests just in case, other tests looked good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijBn1S3f4-mjh6qhzH:-Kj7bavJLxANim5R-NC2:bwlaqv6) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L229)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I tried to find some existing documentation on these tags so I could point to a place where they are described in detail. Could not find anything useful in my search. Not sure how to describe these so that anyone would understand it. (Not sure if I get the point myself even)
</blockquote></details>

see LegacyCommunicationManager.getTagForType() - the map is communicated to the client

somewhat related: UIDL.getTag(), PaintTarget.getTag()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 224 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijD63yenAWQc1PnPj7:-Kj8PmBj4FdsAreo7_l4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L224)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'd say @since 8.1 for now, and only backport if there is specific demand for this.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ServerConnector.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/framework/9176#-KijBn1S3f4-mjh6qhzH:-Kj8PmnOUU1Prw2ePq2e:bsmb8pd) ([raw file](https://github.com/vaadin/framework/blob/688ada5fe8fb97953f2bb3f60c6b227df41b52a1/client/src/main/java/com/vaadin/client/ServerConnector.java#L229)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see LegacyCommunicationManager.getTagForType() - the map is communicated to the client

somewhat related: UIDL.getTag(), PaintTarget.getTag()
</blockquote></details>

Added some information on the type tag, more on what you can do with them rather than try to explain the internal parts of the communication.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176)*

**Comment by hesara** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9176#-:-Kj8RFnkgkVFebSujw65:bnfp4nl)*

**Pull request merged**
