### PR TITLE
Grid editor: TAB now skips non-editable columns

### LINKED ISSUE #10970: Grid editor tabs to uneditable fields
When grid editor is open and not all fields are open for edit, pressing tab should move focus between the editable fields skipping the uneditable fields.

In the example below, tapping from first editable field hides the focus, tabbing again focuses the second editable field. This i very confusing for the user.

Vaadin Framework version 8.4.3

Minimal code to reproduce
```
		Grid<String[]> grid = new Grid<>();
		grid.getEditor().setEnabled(true);
		grid.getEditor().setBuffered(true);
		TextField a = new TextField();
		BindingBuilder<String[], String> aa = grid.getEditor().getBinder().forField(a);
		grid.addColumn(e -> e[0]).setCaption("A").setEditorBinding(aa.bind(e -> e[0], (row, value) -> row[0] = value));
		grid.addColumn(e -> e[1]).setCaption("B");
		TextField c = new TextField();
		BindingBuilder<String[], String> cc = grid.getEditor().getBinder().forField(c);
		grid.addColumn(e -> e[2]).setCaption("C").setEditorBinding(cc.bind(e -> e[2], (row, value) -> row[2] = value));
		grid.setItems(new String[] {"1", "2", "3"}, new String[] {"1", "2", "3"}, new String[] {"1", "2", "3"});

```

### PR DESCRIPTION
**Pull request by mvysny**
Pressing TAB would shift the focus to non-editable cells when the Grid was in edit mode.
This patch makes DefaultEditorEventHandler to skip such columns.

Fixes #10970

**Check when you have completed**
[ ] Valid tests for the pull request
[x] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11573)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Hi @mvysny Could you add a test for this fix while it is under review?

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11573)* status: all files reviewed, 1 unresolved discussion (waiting on @mvysny)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11573#-LevBOD13Hvc0JoibAUI:-LevBOD25bWPWcAYGc6j:b-hfgxdu) (no related file):*
Adding a test would make us more confident about this fix.  ;-)

---
___
*[client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java, line 203 at r1](https://reviewable.io/reviews/vaadin/framework/11573#-LevAQ-Z0czLLISkIO_a:-LevAQ-Z0czLLISkIO_b:bjsvb2v) ([raw file](https://github.com/vaadin/framework/blob/e657f259f92c1031d2e6c161570b75e80e384e61/client/src/main/java/com/vaadin/client/widget/grid/DefaultEditorEventHandler.java#L203)):*
> ```
>  Find nearest editable column
> ```

this javadoc can be improved, as `nearest` is not very clear to show either it is the next or the previous one. same with the javadoc for the next api. 

Javadoc for the private method is not necessary, so i am not blocking this.  but that would be help full

**Comment by mvysny** [comment]
I've updated the javadoc and added the tests, could you please review?

**Review by ZheSun88 — APPROVED** [review]
:lgtm:  Thanks now let us wait for the validation

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11573#-:-LeveOsI12Z-1pnYL8Yp:b6zm465)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
