### PR TITLE
Use Maven plugin for formatting code

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10783)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 1 of 63 files at r4, 1 of 1 files at r5.
Review status: 2 of 145 files reviewed at latest revision, all discussions resolved.

---

*[client/src/main/java/com/vaadin/client/AnimationUtil.java, line 69 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyBR_-8AFJFs4RPwo:-L9AyBR_-8AFJFs4RPwp:b-n57a63) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/AnimationUtil.java#L69)):*
> ```Java
>       });
>       callbackFunc.listener = listener;
>     
> ```

What the....?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by elmot** [comment]
Review status: 2 of 145 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 493 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyQUu4oIqfaTtWaFv:-L9AyQUu4oIqfaTtWaFw:b-813l26) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/ApplicationConnection.java#L493)):*
> ```Java
>             }
>         }
>     
> ```

Extra spaces again

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by tsuoanttila** [comment]
Review status: 2 of 145 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/AnimationUtil.java, line 69 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyBR_-8AFJFs4RPwo:-L9EXjFFExctyZuR8Ej_:b2pj5f7) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/AnimationUtil.java#L69)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What the....?
</blockquote></details>

These whitespaces are related to `native` JavaScript code block in GWT code. It's a systematic thing, since the formatter thinks of them as comments. I'll see if I can fiddle with the `VaadinJavaConventions.xml` somehow to make these spaces disappear.

---

*[client/src/main/java/com/vaadin/client/ApplicationConnection.java, line 493 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyQUu4oIqfaTtWaFv:-L9EY2PF0ShEaCtkztd9:b-otilcs) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/ApplicationConnection.java#L493)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra spaces again
</blockquote></details>

See comment above.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by Legioth** [comment]
Review status: 2 of 145 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/AnimationUtil.java, line 69 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyBR_-8AFJFs4RPwo:-L9tjLSP5PHxHE2e5MHT:bxphf48) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/AnimationUtil.java#L69)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

These whitespaces are related to `native` JavaScript code block in GWT code. It's a systematic thing, since the formatter thinks of them as comments. I'll see if I can fiddle with the `VaadinJavaConventions.xml` somehow to make these spaces disappear.
</blockquote></details>

Seems quite acceptable to me. Consistent formatting with some extra spaces inside relatively uncommon JSNI blocks is still much better than inconsistent formatting all over the place. I'd suggest accepting these extra spaces as-is now, and then separately see if it would be possible to tweak the configuration further.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by elmot** [comment]
Review status: 2 of 145 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/AnimationUtil.java, line 69 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyBR_-8AFJFs4RPwo:-LA3eYVUEp5RbmVtpaFc:b-rwrvlf) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/AnimationUtil.java#L69)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Seems quite acceptable to me. Consistent formatting with some extra spaces inside relatively uncommon JSNI blocks is still much better than inconsistent formatting all over the place. I'd suggest accepting these extra spaces as-is now, and then separately see if it would be possible to tweak the configuration further.
</blockquote></details>

Is there a possibility to switch off JSNI reformating? If they are uncommon we can format them semi-manually at once and then keep them untouched?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by Legioth** [comment]
*[client/src/main/java/com/vaadin/client/AnimationUtil.java, line 69 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10783#-L9AyBR_-8AFJFs4RPwo:-LACLYw92IvHvG-1bs5A:b-k3np4m) ([raw file](https://github.com/vaadin/framework/blob/79bd51d9d6ab75c92b3a5336e4b6799ad8c9429b/client/src/main/java/com/vaadin/client/AnimationUtil.java#L69)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Is there a possibility to switch off JSNI reformating? If they are uncommon we can format them semi-manually at once and then keep them untouched?
</blockquote></details>

I don't think it's possible to directly switch off JSNI formatting since the Eclipse formatter doesn't know anything about JSNI - it's just a block comment like any other block comment.

With that said, what could be done is to surround all JSNI blocks with `//@formatter:off`and `//@formatter:on`. The problem with this approach is that it will probably be forgotten most of the time.

With the options of consistently having some "extra" whitespace in all JSNI blocks compared to having the whitespace only in JSNI blocks where someone has forgotten to add `//@formatter:off`, I would prefer the #ffs solution of not adding extra metadata to the code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by elmot** [comment]
Review status: 2 of 145 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 459 at r2](https://beta.reviewable.io/reviews/vaadin/framework/10783#-LAIOiFaBhadF6_rXaLt:-LAIOiFaBhadF6_rXaLu:biwkdpb) ([raw file](https://github.com/vaadin/framework/blob/cd299c215058d3c2e6598217dfdc2fce2da80bb9/pom.xml#L459)):*
> ```XML
>                     <groupId>com.marvinformatics.formatter</groupId>
>                     <artifactId>formatter-maven-plugin</artifactId>
>                     <version>2.1.2</version>
> ```

It looks like most recent version of eclipse formatter is here.
```xml
  <groupId>net.revelc.code.formatter</groupId>
  <artifactId>formatter-maven-plugin</artifactId>
  <version>2.7.2</version>
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by elmot** [comment]
Reviewed 78 of 78 files at r2, 3 of 3 files at r3, 62 of 63 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by elmot** [comment]
Review status: 118 of 450 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/framework/10783#-LAIxAatEdXfsl4B_a96:-LAIxAatEdXfsl4B_a97:b-rgjijp) (no related file):*
This PR uses old Eclipse and needs rebasing already. I have open another one: #10829

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10783)*

**Comment by tsuoanttila** [comment]
Closed in favor of #10829

**Pull request closed without merging**
