### PR TITLE
Add/fill in missing @since tags for 8.1

### PR DESCRIPTION
**Pull request by hesara**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9106)

### CODE REVIEW

**Comment by ahie** [comment]
`Composite`, `CompositeState`, `ComponentRootSetter` seem to still have empty since tags.

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9106#-:-Ki4pPl9gIFrw_RxjvVr:bs71daj)*

**Comment by tsuoanttila** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9106)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9106#-Ki5YjBxdP25i-lSpL-r:-Ki5YjBxdP25i-lSpL-s:b6d6hoj) (no related file):*
Comment from Aleksi still open.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9106)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9106)*

**Pull request merged**
