### PR TITLE
Add MultiSelection support for Tree Component

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9354)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
This patch might want some follow up changes before we merge, so keep an eye out for things to be added.

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPI_uNWxAMEAWvU7bb:-KkPI_uNWxAMEAWvU7bc:bqdukhr) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java#L138)):*
> ```Java
>      * features of the selection model without copying all logic.
>      * 
>      * @return selection model instance, not {@code null}
> ```

@since

---

*[client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPIMfqsD-nrkwNTC9c:-KkPIMfqsD-nrkwNTC9d:bp408m7) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java#L24)):*
> ```Java
> import com.vaadin.ui.Tree.TreeMultiSelectionModel;
> 
> @Connect(TreeMultiSelectionModel.class)
> ```

javadoc, @since

---

*[client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPIPXdF7V78xE4Uswh:-KkPIPXdF7V78xE4Uswi:bfv9r6s) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java#L32)):*
> ```Java
>         return new MultiSelectionModel() {
>             @Override
>             public Renderer<Boolean> getRenderer() {
> ```

(this feels a bit hacky, but not a blocker, I guess)

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 189 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPHEbmYvRG4AslWPz7:-KkPHEbmYvRG4AslWPz8:b-cnqbr7) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L189)):*
> ```Java
>                 wrap.getRow(0).isSelected());
>         Assert.assertTrue("Second row was not selected",
>                 wrap.getRow(1).isSelected());
> ```

(could also test deselection, but I guess that is covered by selection tests for TreeGrid/Grid)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354)*

**Comment by ahie** [comment]
Currently only possible to select with space. Should clicking on items in multi select mode select/deselect the clicked item?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354#-:-KkPL5s0kyDITruK4BWn:bd7bc0a)*

**Comment by ahie** [comment]
Latest commit addresses this comment. If this is unwanted behavior will revert.

---

Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java, line 138 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPI_uNWxAMEAWvU7bb:-KkP_7BwC2AllPyVV-jt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java#L138)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java, line 24 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPIMfqsD-nrkwNTC9c:-KkP_8xAag8U7pYEW2qn:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/client/src/main/java/com/vaadin/client/connectors/tree/TreeMultiSelectionModelConnector.java#L24)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

javadoc, @since
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java, line 189 at r1](https://reviewable.io:443/reviews/vaadin/framework/9354#-KkPHEbmYvRG4AslWPz7:-KkP_FHoKG06mvrElclH:bcdvkfq) ([raw file](https://github.com/vaadin/framework/blob/44e1becf778ff06f6cb810e276d7ef84d44c1a53/uitest/src/test/java/com/vaadin/tests/components/tree/TreeBasicFeaturesTest.java#L189)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could also test deselection, but I guess that is covered by selection tests for TreeGrid/Grid)
</blockquote></details>

Done below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354#-:-KkP_KbdLKpNgrTDfTH9:bjx90xz)*

**Comment by hesara** [comment]
If the UX of click selection is ok, code looks ok to me

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354#-:-KkQCOPpHMEmsIn_D0RK:b-xt2k6h)*

**Comment by ahie** [comment]
The behavior corresponds to the old `MultiSelectMode.SIMPLE`. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354#-:-KkUke01bLCe7Umu7oe9:b-pqgq2n)*

**Comment by ahie** [comment]
Which is also the only mode selection can be in on touch devices.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9354#-:-KkUlbRcjwssJR6u5Et2:byyhimm)*

**Pull request merged**
