### PR TITLE
Add mobile html5 dnd support using polyfill

### LINKED ISSUE #9174: GridDragAndDrop duplicates rows on Android+Chrome, IE11, Edge
Vaadin version: 8.1-SNAPSHOT
Device: Samsung S7 / Android 7.0
Browser: Chrome
Vaadin core test: GridDragAndDrop
Description of the bug: Dragging a row from the source Grid to the target Grid creates a duplicate of the row to the target Grid instead of removing it from the source Grid and adding it into the target Grid. You can even drag the same row multiple times to create a big collection of duplicates to the target Grid. On desktop Chrome (Windows 7) the row is moved as expected and no duplicates are created.

### PR DESCRIPTION
**Pull request by pleku**
- Adds a switch for enabling mobile html5 dnd support
- Adds polyfill only when needed
- Ignore native Android Chrome drag start because doesn't work properly
(no dragend event fired)

Fixes #9174

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9282)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 12 of 14 files at r1.
Review status: 12 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 290 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlWdRyWAMfdzs1soON:-KjlWdRyWAMfdzs1soOO:b-ro1kxz) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L290)):*
> ```Java
>      *            the event to test
>      * @return {@code true} if native event, {@code false} if not (polyfill
>      *         event)
> ```

(could have @since)

---

*[client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkQ4eKPjFUBaJUkfn:-KjlkQ4eKPjFUBaJUkfo:b6xesdj) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java#L172)):*
> ```Java
> 
>             @Override
>             public void initializeMobileHtml5DndPolyfill() {
> ```

is there a reason for using a custom RPC method instead of Page.executeJavaScript()?

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 287 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlX50b6pA1ODCa6fgV:-KjlX50b6pA1ODCa6fgW:bfy8f9c) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L287)):*
> ```Java
> 
>             List<Dependency> dependencies = new ArrayList<>();
>             dependencies.addAll(ui.getPage().getPendingDependencies());
> ```

filter cannot apply to these dependencies?

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1858 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllSfgz4Ot96KGl76N:-KjllSfgz4Ot96KGl76O:b-i3fnme) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1858)):*
> ```Java
> 
>     /**
>      * Enable or disable HTML5 DnD for mobile devices.
> ```

(when should this normally be called to be taken into account from the beginning?)

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1868 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllOawHgqcMbf2U0T5:-KjllOawHgqcMbf2U0T6:b-t7zdt2) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1868)):*
> ```Java
>      * <p>
>      * <em>NOTE: When disabling this after it has been enabled, it will not
>      * effect {@link DragSourceExtension} and {@link DropTargetExtension} (and
> ```

affect

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1887 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjljY1VYZRlRfec3Gh-:-KjljY1W_Zzi55og7o-w:byno4vo) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1887)):*
> ```Java
>     }
> 
>     private void loadMobileHtml5DndPolyfill() {
> ```

(this could have some comments, but not a blocker)

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1905 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-Kjlkc8JyvIN5QrfuId9:-Kjlkc8JyvIN5QrfuIdA:b9mxw4w) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1905)):*
> ```Java
>                 + ApplicationConstants.MOBILE_DND_POLYFILL_STYLESHEET));
> 
>         getRpcProxy(PageClientRpc.class).initializeMobileHtml5DndPolyfill();
> ```

see comment above about RPC vs. executeJavaScript()

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 247 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkrNz0eLcwFT-c72q:-KjlkrNz0eLcwFT-c72r:b-uwfccj) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L247)):*
> ```Java
>             + "frontend/es5/";
> 
>     /**
> ```

(these could probably also be purely server side rather than in shared)

---

*[shared/src/main/java/com/vaadin/shared/ui/ui/PageClientRpc.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkwYKhetPzqjJZgVT:-KjlkwYKhetPzqjJZgVU:b-4bi8v1) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/shared/src/main/java/com/vaadin/shared/ui/ui/PageClientRpc.java#L34)):*
> ```Java
>     public void reload();
> 
>     /**
> ```

see comments above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: 13 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 163 at r2](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllsL1Z3HoGBnGjmO8:-KjllsL2B2PYKyiUeztO:b-mval2y) ([raw file](https://github.com/vaadin/framework/blob/e66c33abdf58cc0563cb649021a3f6ce27f7b4f5/documentation/advanced/advanced-dragndrop.asciidoc#L163)):*
> ```AsciiDoc
> 
> The HTML 5 Drag and Drop API is not yet supported by mobile browsers. To enable HTML5 DnD support on mobile devices, we have included
> an external Polyfill (https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite). Please note that this Polyfill is under MIT License.
> ```

link formatting to also work as a link

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by pleku** [comment]
Review status: 7 of 15 files reviewed at latest revision, 11 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java, line 290 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlWdRyWAMfdzs1soON:-KjmBPlGlxAkEqkQ6-0k:b-eu23gk) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/client/src/main/java/com/vaadin/client/extensions/DragSourceExtensionConnector.java#L290)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could have @since)
</blockquote></details>

This class is released in 8.1 so no need for single method to have `@since 8.1` ?

---

*[client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java, line 172 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkQ4eKPjFUBaJUkfn:-KjmBdDehtqxT66L1JX-:ba0c5uh) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/client/src/main/java/com/vaadin/client/ui/ui/UIConnector.java#L172)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

is there a reason for using a custom RPC method instead of Page.executeJavaScript()?
</blockquote></details>

Yes because I will need to add a configuration for the polyfill, so that I can fix the drag image offset for Grid by using a callback given to the configuration. Related to the TODO at the end of this file. This will come in a later PR

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 163 at r2](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllsL1Z3HoGBnGjmO8:-KjmDICgligOA8CV1SHM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e66c33abdf58cc0563cb649021a3f6ce27f7b4f5/documentation/advanced/advanced-dragndrop.asciidoc#L163)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

link formatting to also work as a link
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/communication/UidlWriter.java, line 287 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlX50b6pA1ODCa6fgV:-KjmDK-xrLlIvOtdapgq:bqq99f4) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L287)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

filter cannot apply to these dependencies?
</blockquote></details>

I think it would be very weird for the user to specifically add some dependencies via Page and then they're filtered out by some filter ?

Clarified javadocs in `Page`

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1858 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllSfgz4Ot96KGl76N:-KjmF0aU8u-lG2mCJFvd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1858)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(when should this normally be called to be taken into account from the beginning?)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1868 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjllOawHgqcMbf2U0T5:-KjmF3lwPfaS2qXpohrZ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1868)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

affect
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1887 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjljY1VYZRlRfec3Gh-:-KjmFFwBJyxaZz56fwM-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1887)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(this could have some comments, but not a blocker)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/UI.java, line 1905 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-Kjlkc8JyvIN5QrfuId9:-KjmFHYHdM3J5zonbamd:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/server/src/main/java/com/vaadin/ui/UI.java#L1905)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comment above about RPC vs. executeJavaScript()
</blockquote></details>

Done.

---

*[server/src/main/resources/VAADIN/drag-drop-polyfill.css, line 10 at r2](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmFNOGU98TLVLP9kAt:-KjmFNOGU98TLVLP9kAu:b-btjzsj) ([raw file](https://github.com/vaadin/framework/blob/e66c33abdf58cc0563cb649021a3f6ce27f7b4f5/server/src/main/resources/VAADIN/drag-drop-polyfill.css#L10)):*
> ```CSS
>     transition-duration: 250ms !important;
>     transition-timing-function: ease-out !important;
> }
> ```

These need @jouni 

---

*[shared/src/main/java/com/vaadin/shared/ApplicationConstants.java, line 247 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkrNz0eLcwFT-c72q:-KjmFl2NOlHEbao57UX1:b-hufayb) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/shared/src/main/java/com/vaadin/shared/ApplicationConstants.java#L247)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(these could probably also be purely server side rather than in shared)
</blockquote></details>

Not sure where to put them then, this is where the bootstrap file name is for example

---

*[shared/src/main/java/com/vaadin/shared/ui/ui/PageClientRpc.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjlkwYKhetPzqjJZgVT:-KjmFv4jtzzEoB4DBJq9:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fcc3aadd862d03a798526b4fb143c18b851f428a/shared/src/main/java/com/vaadin/shared/ui/ui/PageClientRpc.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see comments above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r3.
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 167 at r3](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmSCu4UjYop2v2syl9:-KjmSCu4UjYop2v2sylA:bqdbpr8) ([raw file](https://github.com/vaadin/framework/blob/2057ba9f06b47ef9f537791c44e8fc8e55359635/documentation/advanced/advanced-dragndrop.asciidoc#L167)):*
> ```AsciiDoc
> 
> The HTML 5 Drag and Drop API is not yet supported by mobile browsers. To enable HTML5 DnD support on mobile devices, we have included
> an link:https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite:[external Polyfill]. Please note that this Polyfill is under the BSD 2 License.
> ```

should add the license to the top level licenses file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by pleku** [comment]
Review status: 10 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmZUgMb1sKxQQ6kZ6M:-KjmZUgMb1sKxQQ6kZ6N:bwtmaox) (no related file):*
blocking for now since need to test more after removing the theming

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 167 at r3](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmSCu4UjYop2v2syl9:-KjmYg4FEKs4ptNEFCrO:b-w2q64x) ([raw file](https://github.com/vaadin/framework/blob/2057ba9f06b47ef9f537791c44e8fc8e55359635/documentation/advanced/advanced-dragndrop.asciidoc#L167)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

should add the license to the top level licenses file
</blockquote></details>

Done (hopefully right location)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by hesara** [comment]
Reviewed 4 of 5 files at r4.
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 167 at r3](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmSCu4UjYop2v2syl9:-KjmZlw7nt8PEJsTseuM:b-vdpl) ([raw file](https://github.com/vaadin/framework/blob/2057ba9f06b47ef9f537791c44e8fc8e55359635/documentation/advanced/advanced-dragndrop.asciidoc#L167)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Done (hopefully right location)
</blockquote></details>

here it says "BSD 2", whereas in the licenses file "MIT license"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by pleku** [comment]
Review status: 9 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/advanced/advanced-dragndrop.asciidoc, line 167 at r3](https://reviewable.io:443/reviews/vaadin/framework/9282#-KjmSCu4UjYop2v2syl9:-KjqjXXgNjng2Z3jQOsF:bb7f2mf) ([raw file](https://github.com/vaadin/framework/blob/2057ba9f06b47ef9f537791c44e8fc8e55359635/documentation/advanced/advanced-dragndrop.asciidoc#L167)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

here it says "BSD 2", whereas in the licenses file "MIT license"
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by hesara** [comment]
Reviewed 6 of 7 files at r5.
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/resources/VAADIN/drag-drop-polyfill.min.js, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/9282#-Kjqu53IIgXhowq3kl_j:-Kjqu53IIgXhowq3kl_k:bjxiz9i) ([raw file](https://github.com/vaadin/framework/blob/684ae09c20471b92efa92fa1b5506e64cd2dc58a/server/src/main/resources/VAADIN/drag-drop-polyfill.min.js#L1)):*
> ```JavaScript
> /*! drag-drop-polyfill 2.0.0-beta.2 | Copyright (c) 2016 Tim Ruffles | BSD 2 License */
> ```

Should we have some documentation (readme, comment or whatever) on what has been modified here compared to the original version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by pleku** [comment]
Review status: 13 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/resources/VAADIN/drag-drop-polyfill.min.js, line 1 at r5](https://reviewable.io:443/reviews/vaadin/framework/9282#-Kjqu53IIgXhowq3kl_j:-Kjr4dh-nSUUVrpwdyPl:b-j4z4ne) ([raw file](https://github.com/vaadin/framework/blob/684ae09c20471b92efa92fa1b5506e64cd2dc58a/server/src/main/resources/VAADIN/drag-drop-polyfill.min.js#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Should we have some documentation (readme, comment or whatever) on what has been modified here compared to the original version?
</blockquote></details>

Done (added comment, see minified file diff)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9282)*

**Pull request merged**
