### PR TITLE
Fixing JavaDoc of Column#getWidth() and Column#setWidth()

### LINKED ISSUE #11451: Grid.Column.getWidth() javadoc misleadingly states default column width of 100px
Vaadin Framework both 8.5.1 and 8.7.0. The Grid.Column.getWidth():1539 javadoc misleadingly states that

> By default a column is 100px wide

However that's not true since the default value is `-1` (undefined). Check points to do:

1. Fix javadoc to state `By default a column is of undefined width (-1), see isWidthUndefined() for more details`
2. It's not possible to set -1 via Column.setWidth(); it would be great if the javadoc would mention something like "to set the column width to undefied (-1) please use the `setWidthUndefined()` function.

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes #11451

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11452)

### CODE REVIEW

**Comment by anasmi** [comment]
___
*[server/src/main/java/com/vaadin/ui/Grid.java, line 1602 at r1](https://reviewable.io/reviews/vaadin/framework/11452#-LYQYLnc7XUpz6z3w9GS:-LYQYLnc7XUpz6z3w9GT:bpyvbkq) ([raw file](https://github.com/vaadin/framework/blob/b95b4ba172e23cc2751a358b46a0235a9ff5c7a9/server/src/main/java/com/vaadin/ui/Grid.java#L1602)):*
> ```Java
> 
>         /**
>          * Returns the width (in pixels). By default a column width is -1 (undefined).
> ```

Would it be better to use `{@value GridConstants#DEFAULT_COLUMN_WIDTH_PX}`? The same as in state: https://github.com/vaadin/framework/blob/master/shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java#L56

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11452)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[server/src/main/java/com/vaadin/ui/Grid.java, line 1602 at r1](https://reviewable.io/reviews/vaadin/framework/11452#-LYQYLnc7XUpz6z3w9GS:-LYQblvX2pXTgznmyUom:b-4dok3f) ([raw file](https://github.com/vaadin/framework/blob/b95b4ba172e23cc2751a358b46a0235a9ff5c7a9/server/src/main/java/com/vaadin/ui/Grid.java#L1602)):*
<details><summary><i>Previously, anasmi (Anastasia Smirnova) wrote…</i></summary><blockquote>

Would it be better to use `{@value GridConstants#DEFAULT_COLUMN_WIDTH_PX}`? The same as in state: https://github.com/vaadin/framework/blob/master/shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java#L56
</blockquote></details>

yes, updated

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11452)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @anasmi)

___
*[server/src/main/java/com/vaadin/ui/Grid.java, line 1602 at r1](https://reviewable.io/reviews/vaadin/framework/11452#-LYQYLnc7XUpz6z3w9GS:-LYQbsNY4lPkeLKJEbDt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b95b4ba172e23cc2751a358b46a0235a9ff5c7a9/server/src/main/java/com/vaadin/ui/Grid.java#L1602)):*
<details><summary><i>Previously, TatuLund (Tatu Lund) wrote…</i></summary><blockquote>

yes, updated
</blockquote></details>

Done.

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11452)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by anasmi** [comment]
@TatuLund could you explicitly specify the package name also? 
It seems like the content is not generated otherwise. The same problem is from the example I've mentioned early : Generated JavaDoc misses value https://vaadin.com/download/current8/docs/api/com/vaadin/shared/ui/grid/ColumnState.html#width and Value is set https://github.com/vaadin/framework/blob/master/shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java#L56

**Review by anasmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11452)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
