### PR TITLE
Added expand helper method to ordered layouts

### PR DESCRIPTION
**Pull request by mstahv**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8139)

### CODE REVIEW

**Comment by mstahv** [comment]
This is how this change simplifies code

## From:

        VerticalLayout root = new VerticalLayout(toolbar,);
        root.addComponent(toolbar);
        root.addComponent(content);
        root.setSizeFull();
        content.setSizeFull();
        root.setExpandRatio(content, 1);

## To:

        VerticalLayout root = new VerticalLayout();
        root.addComponent(toolbar);
        root.expand(content);

... in many places in your Vaadin code. Also the new API makes it much easier for new users to use the expansion features.

I'd still consider also to configure all well known parent component if the parent layout already happens to be added some other component, but this is how it has worked in Viritin pretty well already.

**Comment by Legioth** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8139#-K_dbr6LgaA5Un_qriUK:-K_dbr6MTi0y-aJL3tmT:bit90vb) (no related file):*
I think it's quite hard to understand what the `expand` method does since it both adds a component and configures it, especially if you ever mix those two modes of operation in one method call:
```
VerticalLayout layout = new VerticalLayout(c1);
layout.expand(c2, c1);
```

I'd suggest splitting the functionality into two separate methods to make things clearer:

1. `expand` assumes the component is already added and throws an `IllegalArgumentException` if it's not (in the same way as `setExpandRatio` already does)
1. `addExpanded` as a shorthand for `addComponent`+ `expand`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8139)*

**Comment by mstahv** [comment]
In which case it doesn't do what you wanted to do?

**Comment by Legioth** [comment]
It does too much, which makes it confusing. When reading code and seeing `layout.expand(c1, c2)`, you cannot know whether `c1` will end up before or after `c2` since that depends on whether those components have already been added to the layout or not.

That's why I suggest splitting it up to two methods: If you see `layout.expand(c1, c2)`, then you would know that it doesn't affect the ordering at all since both components must already be children of `layout`. If you instead see `layout.addExpanded(c1, c2)`, you would know that `c1` will be before `c2` since they are both (re)added to the end of the layout.

What's your objection against splitting up the functionality into two separate methods that can be understood without knowledge of the previous state of the layout?

**Comment by Legioth** [comment]
Ping @mstahv. Do you have any objections against my suggestion of splitting the logic into two separate methods? I could implement the changes if you don't have time.

**Comment by mstahv** [comment]
I don't really agree with your arguments that the suggested method does too much or is too complex. If you have already added the components they remain in the parent in the places where they were added. I don't think nobody expects anything else. Also one should not that most often this is used with just one parameter.

In Viritin the current method has already been proven to work well. With one method there would be less API and documentation to maintain. Fight for simplicity.

The only issue I see is Viritin 2.0. In Viritin the method also returns "this" (fluent API). Thus, I'd actually suggest we'd change the mehtod name to expandComponent. What do you think?

**Comment by pleku** [comment]
The team has discussed this and decided that

```java
public void addComponentsAndExpand(Component... components) { }
```
Is the API name and the implementation shall:
- `addComponents(component`, THUS if any of the components have been added, they are moved, which is consistent to how `addComponent` / `addComponents` works.
- expand components (`setExpandRatio(1)` and `setWidth("100%")` or `setHeight("100%")`)
- set layout w/h size 100% respectively

The name is perceived as _correct_ ™ and coherent with what is currently in the framework. It has some chance of being discovered because of the `addComponent`-prefix in the method name, for power usage writing `layout.expand` should autocomplete to this method (tested Eclipse). Mileage might vary

Now who updates this PR, @mstahv or @Legioth ?

**Comment by mstahv** [comment]
The method is long as hell, but on the otherhand it tells quite well what it does. The bad thing in that "specification" is that might need split adding components to three different calls in some cases:

    addComponents(foo,bar,car);
    expand(bar);

becomes:

    addComponents(foo);
    addComponentsAndExpand(bar);
    addComponents(car);

But any kind of related method here will be a great aid for new users, so let's just get something in before 8 is out (although this kind of method can be added later as well, but for marketing purposes this would be really nice addition to 8.0).

**Comment by mstahv** [comment]
The pull request has tag "Waiting for author", which I guess is me. What should I do?

**Comment by denis-anisimov** [comment]
I'm not sure what Pekka meant but I think you should update the PR according to the team decision (written above by Pekka).

**Comment by mstahv** [comment]
I read that the "team had discussed", but that doesn't help me to get convinced or motivated about the suggested changes (although they were quite minimal to my current suggestion). That's why all this kind of "discussions" should be public, so I or somebody else could buy your reasoning. I tried continue the discussion here, but without answer (I know, Pekka is sick). 

I hope some one from the team that discussed about the topic could answer if you thought about the use case I added above. It has been a common pattern form me previously (with V7 + Viritin).

**Comment by pleku** [comment]
We, _the team_ can do the updates for this patch if necessary.

Again, for the reasoning why the `addComponentsAndExpand` was considered to be the best alternative available:
- it does what it says
- the naming is __coherent__ with the other API methods in the FW
- the functionality is __coherent__ with other API methods in the FW
  - any already added component is moved, same as with doing `addComponent` 
- it discoverable

We did see the merits in the proposed `expand` method, but after weighing the different options, we concluded that this is the way it should be done in the framework. If I recall, we chose "write a bit more for being more explicit for readers" over to "write less once and make it harder for readers". And we don't want every other similar method in the same class to have different semantics (like moving components or not).

I do agree that we should make the discussion more public in the future, we need to write down the _minutes_ or such also to the ticket. Sorry for not doing that for this.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8139#-:-Kbj8hekGQIQX20eJxvp:b9q2x0w)*

**Comment by Legioth** [comment]
Implementation according to the "approved" design in #8480.

**Comment by Legioth** [comment]
Closing this since #8480 has been merged.

**Pull request closed without merging**
