### PR TITLE
Fix IDE usage of Elemental in vaadin-shared

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch also fixes the Checkstyle suppressions usage for Eclipse.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10178)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
@asashour, @pwilkin and @Darsstar: Can you test if this patch works in your individual IDE setups? Especially I'd like to hear from an IDEA user.

**Comment by hesara** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pom.xml, line 462 at r1](https://reviewable.io:443/reviews/vaadin/framework/10178#-KwJekWZYai72G0b2i_U:-KwJekWZYai72G0b2i_V:b-tw3ujj) ([raw file](https://github.com/vaadin/framework/blob/8fd970d88e847267c705966da81ba1ca247333a1/pom.xml#L462)):*
> ```XML
>                     </dependencies>
>                     <configuration>
>                         <propertyExpansion>config_loc=../checkstyle</propertyExpansion>
> ```

Could this break the top-level build? Should this use some Maven variables rather than ".."?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10178)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10178)*

**Comment by asashour** [comment]
Thanks for looking into this, it works fine with my latest Eclipse.

**Comment by Darsstar** [comment]
r2 works fine in IntelliJ IDEA Ultimate 2017.2.5.
I tested both 1) checking out, opening the root pom.xml as a projects, running clean verify from within IntelliJ and then reimporting.
And 2) checking out, running clean verify via CLI and then opening the root pom.xml as a project.

The only thing I can nitpick is that it gets added as a normal source folder, not a generated source folder, they have different icons. For the latter the `elemental` would need to be a sub folder of `generated-sources`. But it is a source folder inside the target folder, which should be enough information.

PS. I opened `com.vaadin.ui.renderers.AbstractRenderer` in vaadin-server to check for errors.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10178#-:-KwJlR1-Mbv2nHxTfdbG:b-p73uvs)*

**Comment by Darsstar** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10178)*

**Comment by pwilkin** [comment]
:lgtm:

**Pull request merged**
