### PR TITLE
Updated embedded videos

### PR DESCRIPTION
**Pull request by alejandro-du**
This change updates the tutorial to show the new videos for Vaadin 8.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9043)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/tutorial.adoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/9043#-KhLYQOlzjHVlGkGuSdk:-KhLYQOlzjHVlGkGuSdl:bhu71qm) ([raw file](https://github.com/vaadin/framework/blob/2ccb5d7c40d2b02bae0f8301e597a8bec4f79b5a/documentation/tutorial.adoc#L633)):*
> ```AsciiDoc
> will also add some logic to actually save the changes. We'll start by adding a
> _
> ```

This change is probably not intentional? Also, rather use the [classname]## syntax than underscores.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9043)*

**Comment by alejandro-du** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/tutorial.adoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/9043#-KhLYQOlzjHVlGkGuSdk:-KhLlKwl1y5-gLyg2Gfb:b-mqyr3i) ([raw file](https://github.com/vaadin/framework/blob/2ccb5d7c40d2b02bae0f8301e597a8bec4f79b5a/documentation/tutorial.adoc#L633)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

This change is probably not intentional? Also, rather use the [classname]## syntax than underscores.
</blockquote></details>

True. Not intentional. Are you able to put "Binder" back? Or should I create a new PR?

I'd ignore styling issues for now. The main thing in this PR is to show the new videos instead of the obsolete ones that confuse readers. Having said so, I'll fix styling issues later :) I'd really appreciate if we have this out soon. I (and probably most readers) would even prefer the version with the missing "Binder" (but correct videos) than the current one ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9043)*

**Comment by ahie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/tutorial.adoc, line 633 at r1](https://reviewable.io:443/reviews/vaadin/framework/9043#-KhLYQOlzjHVlGkGuSdk:-KhLq8j3PVd57x4zRQy0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2ccb5d7c40d2b02bae0f8301e597a8bec4f79b5a/documentation/tutorial.adoc#L633)):*
<details><summary><i>Previously, alejandro-du (Alejandro) wrote…</i></summary><blockquote>

True. Not intentional. Are you able to put "Binder" back? Or should I create a new PR?

I'd ignore styling issues for now. The main thing in this PR is to show the new videos instead of the obsolete ones that confuse readers. Having said so, I'll fix styling issues later :) I'd really appreciate if we have this out soon. I (and probably most readers) would even prefer the version with the missing "Binder" (but correct videos) than the current one ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9043)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9043)*

**Comment by mstahv** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9043#-:-KhMhoTvA6HhojVQPa4P:bnfp4nl)*

**Pull request merged**
