### PR TITLE
Add Grid.setRowHeight()

### LINKED ISSUE #8667: Programmatic Grid row height setting
As an application developer, I want to be able to set the height of the rows in Grid.

This is not a variable row height, but a static minimum height of rows.

### PR DESCRIPTION
**Pull request by hesara**
Fixes #8667

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8935)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-MXSkWJH1kGkOVaDQ:-Kg-MXSkWJH1kGkOVaDR:by3lpm6) (no related file):*
Can you add a test where the row height is set initially? Just to see that it still works. In my opinion, it could use some existing grid test, since I don't think any of our tests are testing the size. For example grid component renderer test could show how to make the button actually fit in the cell.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridRowHeightTest.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-MM1O3K-kz_wOk62d:-Kg-MM1O3K-kz_wOk62e:bygihtl) ([raw file](https://github.com/vaadin/framework/blob/40d21b04f4a743a18963d36799892aeacb3b1ba8/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridRowHeightTest.java#L52)):*
> getBody().findElement(By.className("v-grid-row"))

Could this use .getRow(0) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-MXSkWJH1kGkOVaDQ:-Kg-SNYwJZ--yPEV6RX-:bb6un1j) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Can you add a test where the row height is set initially? Just to see that it still works. In my opinion, it could use some existing grid test, since I don't think any of our tests are testing the size. For example grid component renderer test could show how to make the button actually fit in the cell.
</blockquote></details>

Done

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridRowHeightTest.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-MM1O3K-kz_wOk62d:-Kg-SPcSelpbBDKlVGxO:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/40d21b04f4a743a18963d36799892aeacb3b1ba8/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridRowHeightTest.java#L52)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

> getBody().findElement(By.className("v-grid-row"))

Could this use .getRow(0) ?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Comment by pleku** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-d9PGzGbiSj74gheb:-Kg-d9PGzGbiSj74ghec:b-aq2wed) (no related file):*
Missing documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Comment by hesara** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8935#-Kg-d9PGzGbiSj74gheb:-KgO0bdp4-EqwLvIgURk:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Missing documentation
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8935)*

**Pull request merged**
