### PR TITLE
Make it possible to disallow user selection in Grid

### LINKED ISSUE #7880: Grid should have a way of disabling selection by the user
**Originally by @tmattsso**

___
There is no way to accomplish a the following use case:

- there is a list of items, of which a few are selected
- as an admin i can change the selection
- as a non-admin i can only view the data, not change the selection.

setReadOnly currently does nothing, and setEnabled grays out the whole Grid and disables scrolling. Creating your own SelectionModel doesn't help because of e.g. the drag-select functionality being private in the Renderer (so you have to replace the whole class).

___
 Imported from https://dev.vaadin.com/ issue #20412

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #7880

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8144)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-K_hPGlJC9cMg-nPQ3ZT:b-a14f1b) (no related file):*
This patch currently breaks backwards compatibility in 7.7 and thus cannot be accepted for now 

Originally in https://dev.vaadin.com/review/#/c/14625/4

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hKtmw__qIAiUYSZSo:-K_hKtmw__qIAiUYSZSp:b-nu6bf) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java#L98)):*
> ```Java
>      *            selection, <code>false</code> otherwise
>      */
>     public void setUserSelectionAllowed(boolean userSelectionAllowed);
> ```

Still this breaks all existing custom `SelectionModel` implementations in client side. You should move these behind another interface, and check whether the used selection model implements that or not.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2924 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hMeNuSb1Gc_OT6LIP:-K_hMeNuSb1Gc_OT6LIQ:b-dwg1o3) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2924)):*
> ```Java
>             if (selectAllCheckBox == null) {
>                 selectAllCheckBox = GWT.create(CheckBox.class);
>                 selectAllCheckBox.setEnabled(
> ```

Can you guarantee that `setEnabled(false)` has never been invoked before this method is run ? Meaning that should just use the added `enabled` property too

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1163 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hOwKpTXfoKis9vHXo:-K_hOwKqcYSmTbMcRqQ3:b7ea3i8) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/server/src/main/java/com/vaadin/ui/Grid.java#L1163)):*
> ```Java
>          *            selection, <code>false</code> otherwise
>          */
>         public abstract void setUserSelectionAllowed(
> ```

Having these in the interface break the backwards API compatibility and thus this cannot be merged until there would be plans to make a 7.8.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-K_hRWQFjHXfeI2nTwgz:b1cswu7) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This patch currently breaks backwards compatibility in 7.7 and thus cannot be accepted for now 

Originally in https://dev.vaadin.com/review/#/c/14625/4
</blockquote></details>

This is already implemented in V8.
Should it be backported from there ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-K_htKR3mNu4ldTV8ScA:bdi148) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

This is already implemented in V8.
Should it be backported from there ?

</blockquote></details>

Did not check the V8 implementation - is it the same or slightly different?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1163 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hOwKpTXfoKis9vHXo:-K_ht5BFJtJpTUjEZTAC:b7j8uw0) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/server/src/main/java/com/vaadin/ui/Grid.java#L1163)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Having these in the interface break the backwards API compatibility and thus this cannot be merged until there would be plans to make a 7.8.
</blockquote></details>

The methods could be moved to something like `interface CanDisallowUserSelection extends SelectionModel`. The downside is that then you have to use it like 
```((CanDisallowUserSelection)grid.getSelectionModel()).setUserSelectionAllowed(false)`
Would that be better than breaking the (likely few) selection models which are fully custom and do not extend either `MultiSelectionModel` or `SingleSelectionModel`?
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*
<!-- Sent from Reviewable.io -->

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-K_hvxDs_Xobz1WAmA_W:b7uxv7v) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Did not check the V8 implementation - is it the same or slightly different?
</blockquote></details>

Almost the same. There are some differences where the checks are applied (to reduce code duplication).
https://github.com/vaadin/framework/commit/620b2ba314f0f88760803a084cc38e47b57632d3

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by Artur-** [comment]
Review status: 4 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-Ka8zfamFenNJsGsb756:bfgh7jx) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Almost the same. There are some differences where the checks are applied (to reduce code duplication).
https://github.com/vaadin/framework/commit/620b2ba314f0f88760803a084cc38e47b57632d3
</blockquote></details>

Fixed to be compatible

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2924 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hMeNuSb1Gc_OT6LIP:-Ka8zdfNWTIY__NmzaRL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2924)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Can you guarantee that `setEnabled(false)` has never been invoked before this method is run ? Meaning that should just use the added `enabled` property too
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hKtmw__qIAiUYSZSo:-Ka8xdd7SbfeD1vF9uV-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/client/src/main/java/com/vaadin/client/widget/grid/selection/SelectionModel.java#L98)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Still this breaks all existing custom `SelectionModel` implementations in client side. You should move these behind another interface, and check whether the used selection model implements that or not.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Reviewed 14 of 15 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-Ka981a4sHU8ph3aWM9s:b-pfidyv) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Fixed to be compatible
</blockquote></details>

I'm not sure if it makes any difference, but could add an example of this API to documentation just before https://github.com/vaadin/framework/blob/7.7/documentation/components/components-grid.asciidoc#focus-and-clicks
with e.g. a subtopic 

=== Disallowing User Selection
It is possible to disallow user changing the selection for the single- and multi-selection models.

```java
SingleSelectionModel model = (SingleSelectionModel) grid.getSelectionModel();
model.setUserSelectionAllowed(false);
```

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4453 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka93d8dddt5COFO0kGF:-Ka93d8dddt5COFO0kGG:bzb52r5) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4453)):*
> ```Java
>                                                    // add
>                                                    // it
>                                                    // anyway!
> ```

can you please move this to one _single_ line before 

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4469 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka93kgGeZV-di_FhtwD:-Ka93kgGeZV-di_FhtwE:bglhldt) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4469)):*
> ```Java
>             } // else
>               // no
>               // reordering
> ```

why oh why use three lines ?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1163 at r1](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hOwKpTXfoKis9vHXo:-Ka95dRnCx2K7fd9jNYS:bo6xbge) ([raw file](https://github.com/vaadin/framework/blob/b207121bdee17cee38fc7d68c5e7e2776e95a231/server/src/main/java/com/vaadin/ui/Grid.java#L1163)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

The methods could be moved to something like `interface CanDisallowUserSelection extends SelectionModel`. The downside is that then you have to use it like 
```((CanDisallowUserSelection)grid.getSelectionModel()).setUserSelectionAllowed(false)`
Would that be better than breaking the (likely few) selection models which are fully custom and do not extend either `MultiSelectionModel` or `SingleSelectionModel`?
</blockquote></details>

I would have hoped for methods in V8 Grid that would change the selection model to a specific selection model (if needed) and then return the specific type, e.g. `MultiSelectionModel setMultiSelectionMode()`or `SingleSelectionModel asSingleSelect()` or such whatitsnameis, but did not get support for that.

So now we have a new feature, that doesn't break compatibility, but nobody will ever find out about. #ffs

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1602 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka97DEyrNn3speiJmPb:-Ka97DEyrNn3speiJmPc:bt9vxgx) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/server/src/main/java/com/vaadin/ui/Grid.java#L1602)):*
> ```Java
>         @Override
>         public boolean isUserSelectionAllowed() {
>             return getState().userSelectionAllowed;
> ```

NIT: `return getState(false).userSelectionAllowed;`

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1993 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka96zOeC7t48d4Xmpy4:-Ka96zOeC7t48d4Xmpy5:bt9vxgx) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/server/src/main/java/com/vaadin/ui/Grid.java#L1993)):*
> ```Java
>         @Override
>         public boolean isUserSelectionAllowed() {
>             return getState().userSelectionAllowed;
> ```

NIT: `return getState(false).userSelectionAllowed;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-Ka98vdUOWEeOe52YUFH:bxyxw3c) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I'm not sure if it makes any difference, but could add an example of this API to documentation just before https://github.com/vaadin/framework/blob/7.7/documentation/components/components-grid.asciidoc#focus-and-clicks
with e.g. a subtopic 

=== Disallowing User Selection
It is possible to disallow user changing the selection for the single- and multi-selection models.

```java
SingleSelectionModel model = (SingleSelectionModel) grid.getSelectionModel();
model.setUserSelectionAllowed(false);
```

</blockquote></details>

I could add it myself but then someone else needs to review

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by Artur-** [comment]
Review status: 15 of 37 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8144#-K_hPGlJC9cMg-nPQ3ZS:-KaJPDD9CPHcMYip_mbz:bb7f2mf) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I could add it myself but then someone else needs to review
</blockquote></details>

done

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4453 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka93d8dddt5COFO0kGF:-KaJP_SRYXIG_RWtOvya:b-8ar6o0) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4453)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

can you please move this to one _single_ line before 
</blockquote></details>

Eclipse - it's all fun and games

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4469 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka93kgGeZV-di_FhtwD:-KaJPa-nytvONBqCnEph:b-8ar6o0) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4469)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

why oh why use three lines ?
</blockquote></details>

Eclipse - it's all fun and games

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1602 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka97DEyrNn3speiJmPb:-KaJPmxPk8PxFjMrcJMJ:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/server/src/main/java/com/vaadin/ui/Grid.java#L1602)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: `return getState(false).userSelectionAllowed;`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 1993 at r2](https://reviewable.io:443/reviews/vaadin/framework/8144#-Ka96zOeC7t48d4Xmpy4:-KaJPnaDU3qSAE_uTx9k:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cb4bac0febee5eeae32a483fe413b9946c358871/server/src/main/java/com/vaadin/ui/Grid.java#L1993)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

NIT: `return getState(false).userSelectionAllowed;`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Branch out of date with 7.7, and it seems that the "Allow updates from maintainers" checkbox has not been checked for this PR.

Also please prefer rebase instead of merge, sine now I've got 19 maybe unnecessary files to review ...

---

Reviewed 2 of 5 files at r4, 1 of 1 files at r5.
Review status: 18 of 37 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/components-grid.asciidoc, line 341 at r5](https://reviewable.io:443/reviews/vaadin/framework/8144#-KaLZfN0HoKuRrSoq8Ly:-KaLZfN0HoKuRrSoq8Lz:b-1f97vt) ([raw file](https://github.com/vaadin/framework/blob/3c0df519d1395eb9a3049e5641f45f69ceca4829/documentation/components/components-grid.asciidoc#L341)):*
> ```AsciiDoc
> 
> [NOTE]
> All built-in selection models implement `HasUserSelectionAllowed` so the cast is generally safe.
> ```

Except that NoSelectionModel doesn't, so now you either need to add it here too, or just remove this NOTE.

Or why wasn't it added to AbstractSelectionModel ?  Can't remember anymore but there probably was a reason

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144#-:-KaL_6-6TkhFlB8Zsj6A:bz7m1)*

**Comment by Artur-** [comment]
Review status: 17 of 37 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/components-grid.asciidoc, line 341 at r5](https://reviewable.io:443/reviews/vaadin/framework/8144#-KaLZfN0HoKuRrSoq8Ly:-KaLtmY4UFzVnjg8HJjd:b-t4vvwy) ([raw file](https://github.com/vaadin/framework/blob/3c0df519d1395eb9a3049e5641f45f69ceca4829/documentation/components/components-grid.asciidoc#L341)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Except that NoSelectionModel doesn't, so now you either need to add it here too, or just remove this NOTE.

Or why wasn't it added to AbstractSelectionModel ?  Can't remember anymore but there probably was a reason
</blockquote></details>

Does not really make sense to say that `NoSelectionModel` supports enabling/disabling selection by the user...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Reviewed 17 of 17 files at r3, 2 of 5 files at r4.
Review status: 36 of 37 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[documentation/components/components-grid.asciidoc, line 341 at r5](https://reviewable.io:443/reviews/vaadin/framework/8144#-KaLZfN0HoKuRrSoq8Ly:-KaMNpGsUhu-TMal5U4c:bovb574) ([raw file](https://github.com/vaadin/framework/blob/3c0df519d1395eb9a3049e5641f45f69ceca4829/documentation/components/components-grid.asciidoc#L341)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Does not really make sense to say that `NoSelectionModel` supports enabling/disabling selection by the user...
</blockquote></details>

I agree. I would have just left this comment out since it is not true and explaining further makes no sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by Artur-** [comment]
Review status: 36 of 37 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[documentation/components/components-grid.asciidoc, line 341 at r5](https://reviewable.io:443/reviews/vaadin/framework/8144#-KaLZfN0HoKuRrSoq8Ly:-KaMRNvY9wdm_Gc9PghO:b5a58y6) ([raw file](https://github.com/vaadin/framework/blob/3c0df519d1395eb9a3049e5641f45f69ceca4829/documentation/components/components-grid.asciidoc#L341)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I agree. I would have just left this comment out since it is not true and explaining further makes no sense
</blockquote></details>

Is the current text ok or should I just remove the whole note?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8144)*

**Pull request merged**
