### PR TITLE
Fix broken integration tests

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/websocket/ServletIntegrationWebsocketIT.java, line 34 at r1](https://reviewable.io/reviews/vaadin/framework/10900#-LBynP9sDhUjCXhU_R3a:-LBynP9t3cMcEorLa1kW:b-hb6sda) ([raw file](https://github.com/vaadin/framework/blob/6b01867749f907ff95f08cb3a45c47d9380697d8/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/websocket/ServletIntegrationWebsocketIT.java#L34)):*
> ```Java
>         extends AbstractServletIntegrationTest {
>     // Uses the test method declared in the super class
>     
> ```

Extra spaces

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)*

**Comment by elmot** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)*

**Comment by tsuoanttila** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/websocket/ServletIntegrationWebsocketIT.java, line 34 at r1](https://reviewable.io/reviews/vaadin/framework/10900#-LBynP9sDhUjCXhU_R3a:-LC-yAmu-rtN9wW4KaPu:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/6b01867749f907ff95f08cb3a45c47d9380697d8/test/servlet-containers/generic-tests/src/main/java/com/vaadin/tests/integration/websocket/ServletIntegrationWebsocketIT.java#L34)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)*

**Comment by elmot** [comment]
Reviewed 1 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/framework/10900#-:-LC30xFLDU5ZhzCSHNIT:bnfp4nl)*

**Pull request merged**
