### PR TITLE
Use stable testbench

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11058)

### CODE REVIEW

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11058)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alvarezguille)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11058#-LHYYQW8BJBVplGvzZj-:-LHYYQW8BJBVplGvzZj0:b-lgduym) (no related file):*
Update `bom/pom.xml` as well

---

**Review by tsuoanttila — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11058)* status: all files reviewed, 1 unresolved discussion (waiting on @alvarezguille)

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/framework/11058#-LHYYQW8BJBVplGvzZj-:-LHYZ2kQ7bHqlBc16fsz:b-viioe4) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Update `bom/pom.xml` as well
</blockquote></details>

Right, I missed that, thanks, done!

---

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11058)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
