### PR TITLE
Fixing autocompletion issue with ComboBox on newer Chrome versions

### LINKED ISSUE #11437: Setting autocomplete to a random number prevents setting autocomplete to 'off'
Google Chrome 71.0.3578.80 (Official Build) on Ubuntu
Chromium Version 71.0.3578.98 (Official Build) on Ubuntu
Vaadin 8.5.2 (but I note the code has not changed in latest 8.x release)
ComboBox  see #7820

combo_problem

Problem -
In the above setup chrome autocomplete  boxes overshadow the dropdown making for a horrible UX. 
Using viritin HtmlElementPropertySetter doesn't override the random number set in referenced PR

Desired Outcome - 
Setting the autocomplete property to "off" by editing the DOM in chrome developer tools prevents the chrome options popping up. This is the desired outcome.

This seems like a 'simple fix' ... replace the random number generation with "off". I have not checked this on Firefox or IE. --reaches for helmet--

### PR DESCRIPTION
**Pull request by TatuLund**
Newer Chrome versions do not work with random number hack to prevent auto completion, but it finally supports autocomplete=off.

Adapted from https://github.com/vaadin/framework/pull/11472

Fixes #11437

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11524)

### CODE REVIEW

**Comment by ZheSun88** [comment]
I think this PR is targetting the wrong branch. Should it be `7.7` than `master`. @TatuLund 
for master branch, we have #11472

**Comment by TatuLund** [comment]
Yes and no. This is correct PR for compatibility library. I had just tagged it wrong. I need to do separate PR for real V7.

**Comment by TatuLund** [comment]
The real V7 version of PR is this one https://github.com/vaadin/framework/pull/11539

**Comment by ZheSun88** [comment]
Then do we still need #11472 this one? what is the difference?

**Comment by TatuLund** [comment]
> Then do we still need #11472 this one? what is the difference?

Yes, in compatibility package and V7 the client component is differently named, etc.

**Comment by ZheSun88** [comment]
oh, okay, the compatibility package. Thanks for letting me know.

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11524)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
