### PR TITLE
Add header and footer visibility setting to Grid

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9706)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridHeaderFooterTest.java, line 400 at r1](https://reviewable.io:443/reviews/vaadin/framework/9706#-Kpxcq_lajaSU6Mt3vHL:-Kpxcq_m1zLlsdBxL1Rz:b-qpn2g0) ([raw file](https://github.com/vaadin/framework/blob/a8b819f0241639c7d4f35e9ecb8d282eb347e18f/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridHeaderFooterTest.java#L400)):*
> ```Java
>                 getGridElement().getFooterCount());
>         selectMenuPath("Component", "Footer", "Toggle footer visibility");
>         assertEquals("There should be no header rows", 0,
> ```

footer

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridHeaderFooterTest.java, line 403 at r1](https://reviewable.io:443/reviews/vaadin/framework/9706#-KpxcraGfr7eGr27TpD0:-KpxcraGfr7eGr27TpD1:b-qpn2g0) ([raw file](https://github.com/vaadin/framework/blob/a8b819f0241639c7d4f35e9ecb8d282eb347e18f/uitest/src/test/java/com/vaadin/tests/components/grid/basics/GridHeaderFooterTest.java#L403)):*
> ```Java
>                 getGridElement().getFooterCount());
>         selectMenuPath("Component", "Footer", "Toggle footer visibility");
>         assertEquals("There should be one header row again", 1,
> ```

footer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9706)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9706)*

**Comment by tsuoanttila** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9706#-Kq31pFAdxEDmdgGDw9J:-Kq31pFAdxEDmdgGDw9K:b-95dtnb) (no related file):*
API changes need since tags. Which version? @hesara 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9706)*

**Comment by hesara** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/9706#-Kq31pFAdxEDmdgGDw9J:-KqMeGEUTefo95PKfQBF:b-5uoa59) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

API changes need since tags. Which version? @hesara 
</blockquote></details>

There are only small additions, and I'd say 8.1.1 as everything else looks ready to merge unless some of the API changes are breaking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9706)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9706)*

**Pull request merged**
