### PR TITLE
Implement ReadOnlyHasValue helper

### LINKED ISSUE #9613: When creating my own HasValue implementation that wraps a field component, I want to use something similar to CustomField, so that I don't have to write lots of boilerplate.
The need for this can be seen e.g. in https://github.com/vaadin/framework/blob/e4e2328a3a78d652cd09ef8293f233d31d899415/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java#L24

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9613

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10643)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 102 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iOAUqQGbS_QvKwIwu:-L7iOAUqQGbS_QvKwIwv:b-42w4b9) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/documentation/datamodel/datamodel-forms.asciidoc#L102)):*
> ```AsciiDoc
> ----
> Panel infoPanel = new Panel();
> ReadOnlyHasValue<Person> panelTitle = new ReadOnlyHasValue<String>(
> ```

`ReadOnlyHasValue<Person> = new ReadOnlyHasValue<String>`?

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iP8-5dQA13nMKQiFw:-L7iP8-5dQA13nMKQiFx:bra9vrf) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L31)):*
> ```Java
>  * Example:
>  * <pre>
>  * {@code
> ```

I don't think you need `@code` with `<pre>`

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iOd18qMuczFsIUqs6:-L7iOd18qMuczFsIUqs7:b-ypfp2w) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L51)):*
> ```Java
>      * @param setter the value setter, e.g. {@link Label#setValue}
>      */
>     public ReadOnlyHasValue(SerializableConsumer<V> setter) {
> ```

Calling this a `setter` is a bit misleading. Something like `displayMethod` or  `showValue` would more describe what the function is supposed to do.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 56 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iPE9kIpq9NQOHDiMW:-L7iPE9kIpq9NQOHDiMX:b-78conp) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L56)):*
> ```Java
> 
>     @Override
>     public void setValue(V value) {
> ```

removing the bean will call `clear()` on the `HasValue` which by default is `setValue(getEmptyValue())` which is `null`. The misleading `setter` either needs to take care of the `null` value or we need to provide with one more parameter `emptyValue` to override the `null` with.

The example in docs will fail quite spectacularly with this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10643)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r5.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 56 at r4](https://beta.reviewable.io/reviews/vaadin/framework/10643#-L7iPE9kIpq9NQOHDiMW:-L82rOe68sagdpVTb1fn:bbnrwxz) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L56)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

removing the bean will call `clear()` on the `HasValue` which by default is `setValue(getEmptyValue())` which is `null`. The misleading `setter` either needs to take care of the `null` value or we need to provide with one more parameter `emptyValue` to override the `null` with.

The example in docs will fail quite spectacularly with this.
</blockquote></details>

This part is still missing the `null` check safe guard with fallback to `emptyValue`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10643)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10643)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[documentation/datamodel/datamodel-forms.asciidoc, line 102 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iOAUqQGbS_QvKwIwu:-L82nZh8lEsQCnfUwIbR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/documentation/datamodel/datamodel-forms.asciidoc#L102)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`ReadOnlyHasValue<Person> = new ReadOnlyHasValue<String>`?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iP8-5dQA13nMKQiFw:-L82o1ZZx2ZvE2F9A4AH:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L31)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I don't think you need `@code` with `<pre>`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iOd18qMuczFsIUqs6:-L82oF5WdVAFdQElLOlX:b-n6mk19) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L51)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Calling this a `setter` is a bit misleading. Something like `displayMethod` or  `showValue` would more describe what the function is supposed to do.
</blockquote></details>

It does not necessarily show or display value, it might change style, for instance.
what about `valueProcessor`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10643)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 51 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iOd18qMuczFsIUqs6:-L82sWA7mIVZjC-A8QFa:bmltusz) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L51)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

It does not necessarily show or display value, it might change style, for instance.
what about `valueProcessor`?

</blockquote></details>

OK for me!

---

*[server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java, line 56 at r4](https://reviewable.io:443/reviews/vaadin/framework/10643#-L7iPE9kIpq9NQOHDiMW:-L82sQj72g6tWbLzqWgm:b-an8bmj) ([raw file](https://github.com/vaadin/framework/blob/c6fe3d7dd22cdc81811b9444e53f350ab1b3ca7c/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java#L56)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This part is still missing the `null` check safe guard with fallback to `emptyValue`
</blockquote></details>

Never mind, my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10643)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10643#-:-L82xcK_pN6QHvdx_zC1:bnfp4nl)*

**Pull request merged**
