### PR TITLE
Fixes #11369 in 8.x

### LINKED ISSUE #11369: BrowserFrame with Resource in a Window issues a warning when window is closed
The issue is reproducible in Vaadin 7.7.15 and Vaadin 8.5.2

Reproduction steps:
1. Create a new Vaadin app with `vaadin-archetype-application`
2. Drop any pdf file to src/main/resources and rename it to `some.pdf`
3. Add commons-io as a dependency to your `pom.xml`
4. Use https://gist.github.com/macAtNordea/0330e9f06d17ec8d144b44cd28efa202 as the code for the UI depicting the issue. 
5. Run the app and click the button to open the window
6. Close the window

Observed results:
An additional request will be made for the PDF file displayed in the BrowserFrame that is embedded in the window. 
The server will answer with 404 as the resource will not be available anymore.
This is a problem for us. We have some  customizations, in case of 404 a default UI is shown to the user, but in this case the UI won't load. The bootstrap HTML will try to load ./VAADIN/vaadinBootstrap.js and fail:
image

The reason can be found in the JS console:
image

### PR DESCRIPTION
**Pull request by macprzepiora**
Clear contents of iframe clone that is in a Window so that when it's reattached to DOM we don't get 404

Fixes #11369

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11403)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11403)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @macprzepiora)

*[a discussion](https://reviewable.io/reviews/vaadin/framework/11403#-LVc84ml-kGHuuyt4hAs:-LVc84ml-kGHuuyt4hAt:br6huaw) (no related file):*
Hi @macprzepiora , the fix looks okay. But Could you add a test for the issue you are trying to fix, If the testbench license is blocking you, you can add a test UI and we can write the actual test. 

---

**Comment by macprzepiora** [comment]
Sure, I will write a test

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11403)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by macprzepiora** [comment]
Wonderful :) Any chance this will be included in 8.7?

**Comment by ZheSun88** [comment]
@macprzepiora yes, this one will be included in the 8.7.0 release, which will be available on 31st of Jan. If you want it earlier, there will be a 8.7.0.rc next week. Thanks for the fixes. :-)

**Pull request merged**
