### PR TITLE
Distinguish between touch scroll and drag start on Grid

### PR DESCRIPTION
**Pull request by pleku**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9315)

### CODE REVIEW

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9c4IS_K3cUxx9MvY8:-Kk9c4ITdtFVsfRTX4xL:b-yz3axw) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L99)):*
> ```Java
>                 touchScrollDelayUsed = true;
>             } else {
>                 return;
> ```

Could we end up here e.g. on Microsoft Surface which is a touch enabled device but can also have other input types?
Not a regression from the previous revision, but a potential minor issue nevertheless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9315)*

**Comment by hesara** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 68 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9cTlLG40XbHwxzRYP:-Kk9cTlLG40XbHwxzRYQ:bdv82gl) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L68)):*
> ```Java
>      * a drag start.
>      * <p>
>      * This default value originates from VScrollTable which uses it to distinct
> ```

distinct -> distinguish

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 358 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9cRoP8Fz7nm-cEoLG:-Kk9cRoP8Fz7nm-cEoLH:b7rp0u0) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L358)):*
> ```Java
>             gridConnector.getWidget().getEscalator()
>                     .setDelayToCancelTouchScroll(-1);
>             touchScrollDelayUsed = false; //
> ```

empty comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9315)*

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 68 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9cTlLG40XbHwxzRYP:-Kk9ec-uSaAVLoIS1m02:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L68)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

distinct -> distinguish
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9c4IS_K3cUxx9MvY8:-Kk9eGqLtx4xeay0KFuF:b-mz10ix) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L99)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Could we end up here e.g. on Microsoft Surface which is a touch enabled device but can also have other input types?
Not a regression from the previous revision, but a potential minor issue nevertheless.
</blockquote></details>

Yes that is possible and would be an issue. 

Need to look if it's possible to detect surface, possible also test with one

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 358 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9cRoP8Fz7nm-cEoLG:-Kk9ebZSe2iaAxHhxHgf:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L358)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

empty comment?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9315)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 99 at r1](https://reviewable.io:443/reviews/vaadin/framework/9315#-Kk9c4IS_K3cUxx9MvY8:-Kk9rlTLxMcAQeAb-N_C:b1jhitp) ([raw file](https://github.com/vaadin/framework/blob/9ff8c4ba63df71e46bf5f8742fd27b27c27852ad/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L99)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Yes that is possible and would be an issue. 

Need to look if it's possible to detect surface, possible also test with one
</blockquote></details>

(can also be done after merging this change)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9315)*

**Pull request merged**
