### PR TITLE
Fix DataCommunicator not sending data on filter updates

### LINKED ISSUE #9915: 8.x: Typing a non-matching filter too fast makes ComboBox delete all items
As reported on https://vaadin.com/forum#!/thread/16627944.

Quick-typing a non-matching filter in a ComboBox makes this widget delete all of its items.
I.e.: if the ComboBox contains "aaa", "bbb", "ccc" and one types "kkk" very fast (few tenths of a second), the ComboBox removes all items, even after clearing the filter.

To test, browse to [https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box](https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box), type "kkk" and see all of the items disappear.

Found on 8.1.2 and 8.1.3 and verified with Firefox and Chrome under Windows and Linux.
I can't tell about previous versions.

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9915

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11068)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11068)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 682 at r1](https://reviewable.io/reviews/vaadin/framework/11068#-LHgFbGK03xHALt2extZ:-LHgFbGK03xHALt2ext_:b-6cnl0p) ([raw file](https://github.com/vaadin/framework/blob/d378e344b1429041b265c6928b6f7a0963c265f5/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L682)):*
> ```Java
> 
>                 // Make sure filter change causes data to be sent again.
>                 markAsDirty();
> ```

Any tests?

**Review by elmot — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11068)* status: all files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

**Comment by tsuoanttila** [comment]
___
*[server/src/main/java/com/vaadin/data/provider/DataCommunicator.java, line 682 at r1](https://reviewable.io/reviews/vaadin/framework/11068#-LHgFbGK03xHALt2extZ:-LHgdKHT1R6s8ZiE7Ojv:b-cpgj9x) ([raw file](https://github.com/vaadin/framework/blob/d378e344b1429041b265c6928b6f7a0963c265f5/server/src/main/java/com/vaadin/data/provider/DataCommunicator.java#L682)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Any tests?
</blockquote></details>

Testing is a bit hard as this is a race condition. I think I can try to reproduce it on the server alone, give me some time to do so.

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11068)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
