### PR TITLE
Add read-only support for single and multi select views for Grid.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes vaadin/framework8-issues#516

Change-Id: I2abf4dc11ed293b3ea165bfa3992b813ce56b789

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/84)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java, line 155 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY09gUx6FW2DhYDToCt:-KY09gUx6FW2DhYDToCu:bq00ufg) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java#L155)):*
> ```Java
>     }
> 
>     @OnStateChange("selectionAllowed")
> ```

Could this method be extracted to AbstractSelectionModel from here and SingleSelectionModelConnector ?

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedEvent.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KXzb9-mbgW1WBvwclQ8:-KXzb9-mbgW1WBvwclQ9:b-47kqzn) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedEvent.java#L21)):*
> ```Java
> 
> /**
>  * A selection allowed event, fired by the Grid when its value changes.
> ```

fired by grid when what?

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05xLUD0cHfumvaFgO:-KY05xLUD0cHfumvaFgP:bqkw7s2) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L21)):*
> ```Java
> 
> /**
>  * @author Vaadin Ltd
> ```

javadocs

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05gHXDGKTb_hY3o3v:-KY05gHXDGKTb_hY3o3w:b-6fejfp) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L22)):*
> ```Java
> /**
>  * @author Vaadin Ltd
>  *
> ```

missing since

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05o4jxTJ4qGn92QOM:-KY05o4jxTJ4qGn92QON:b-kclmuy) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L32)):*
> ```Java
>      *            {@code true} if selection allowed, {@code false} otherwise
>      */
>     public void onSelectionAllowed(boolean allowed);
> ```

boolean ? shouldn't this get the event ? if it was only about the boolean, we should always use events for extendability

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY06Zj0vMrW0ontfB5F:-KY06Zj0vMrW0ontfB5G:b-7fbvi4) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java#L77)):*
> ```Java
>      *            otherwise <code>false</code>
>      */
>     public void setDeselectAllowed(boolean deselectAllowed) {
> ```

Seems a bit overrlapping to have isSelectionAllowed and this separate row based deselectAllowed, can you check why there is deselectAllowed, is it used from somewhere or could you basically just use one variable to block both select&deselect ?

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1875 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY07f3dywToQ29oy8Yx:-KY07f3dywToQ29oy8Yy:bwdd476) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1875)):*
> ```Java
>                         checkBox.sinkEvents(Event.ONCLICK);
> 
>                         checkBox.addClickHandler(event -> {
> ```

Shouldn't you prevent selection here if `!grid.isSelectionModel().isUserSelectionAllowed()`

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/MultiSelectionModelImplTest.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY093bkdNWH3bDCjE_Z:-KY093bkdNWH3bDCjE__:b-e8mvd8) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/server/src/test/java/com/vaadin/tests/server/component/grid/MultiSelectionModelImplTest.java#L30)):*
> ```Java
>  *
>  */
> public class MultiSelectionModelImplTest {
> ```

Could move this to GridMultiSelectionModelTest

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/SingleSelectionModelImplTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY09A-4WNG_kIZ1FGLO:-KY09A-4WNG_kIZ1FGLP:blvfyjv) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/server/src/test/java/com/vaadin/tests/server/component/grid/SingleSelectionModelImplTest.java#L27)):*
> ```Java
>  *
>  */
> public class SingleSelectionModelImplTest {
> ```

Could move this to GridSingleSelectionModelTest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java, line 155 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY09gUx6FW2DhYDToCt:-KYCnHWe95KUkd7TvJxl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/connectors/grid/MultiSelectionModelConnector.java#L155)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could this method be extracted to AbstractSelectionModel from here and SingleSelectionModelConnector ?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedEvent.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KXzb9-mbgW1WBvwclQ8:-KYCnZOu4IhNu92J8Qg8:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedEvent.java#L21)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

fired by grid when what?
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05xLUD0cHfumvaFgO:-KYCo50A-P0ThiRqwsOW:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L21)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

javadocs
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05gHXDGKTb_hY3o3v:-KYCo5Z5C8m9eeXrZWrL:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L22)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

missing since
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05o4jxTJ4qGn92QOM:-KYCo9jn8-NeSNC1YuoW:b-6ik83y) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

boolean ? shouldn't this get the event ? if it was only about the boolean, we should always use events for extendability
</blockquote></details>

May be you are right.
I made a copy of `GridEnabledHandler` actually. It also accepts a `boolean` as a parameter......
Do you think I should change this to an event ?

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY06Zj0vMrW0ontfB5F:-KYCof70A25Sky8bOzxd:bwgpuef) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java#L77)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Seems a bit overrlapping to have isSelectionAllowed and this separate row based deselectAllowed, can you check why there is deselectAllowed, is it used from somewhere or could you basically just use one variable to block both select&deselect ?
</blockquote></details>

From the javadoc:

Sets whether clicking the currently selected row should deselect the row.

Makes sense as an independent functionality.

But it's not used from anywhere (this setter).

`deselectAllowed` field is used here in the inner `RowClickHandler` class to deselect a row in the grid.

But both the `select` and `deselect` methods has check `isSelectionAllowed()` in their impl.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1875 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY07f3dywToQ29oy8Yx:-KYCpi8v-oArtO9e2Xcf:b-db6vk2) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1875)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Shouldn't you prevent selection here if `!grid.isSelectionModel().isUserSelectionAllowed()`
</blockquote></details>

Sure.
But I don't want to spread this check in every place where "client code" needs to select/deselect.

So this check is only in two places : in the grid , in `select` , `deselect` methods.
(well there are still some prechecks like CheckBoxes for actions and this logic is there as well, but each action is delegated to the mentioned methods and it's easier to have implementation localized in only one/two places).

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/MultiSelectionModelImplTest.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY093bkdNWH3bDCjE_Z:-KYCrO_u7SaqAKuWtUW4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/server/src/test/java/com/vaadin/tests/server/component/grid/MultiSelectionModelImplTest.java#L30)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could move this to GridMultiSelectionModelTest
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/SingleSelectionModelImplTest.java, line 27 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY09A-4WNG_kIZ1FGLO:-KYCrdd9269NdUOitQ2g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/server/src/test/java/com/vaadin/tests/server/component/grid/SingleSelectionModelImplTest.java#L27)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Could move this to GridSingleSelectionModelTest
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by pleku** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05o4jxTJ4qGn92QOM:-KYCyYnT9PjaKI7PVlQh:b-v6nida) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

May be you are right.
I made a copy of `GridEnabledHandler` actually. It also accepts a `boolean` as a parameter......
Do you think I should change this to an event ?
</blockquote></details>

I think we should always use an event, since that is extendable as we can add more parameters to without breaking API.

GridEnabledHandler should use event too IMO, like everything else. You don't have to fix that here though

To me it seems to be completely borked now, as there is an event type that is just used for registering handler type and firing the event, but not using the event ...

---

*[client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java, line 77 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY06Zj0vMrW0ontfB5F:-KYDUEVY-gCy2FCNsWOQ:bo29g61) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/selection/ClickSelectHandler.java#L77)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

From the javadoc:

Sets whether clicking the currently selected row should deselect the row.

Makes sense as an independent functionality.

But it's not used from anywhere (this setter).

`deselectAllowed` field is used here in the inner `RowClickHandler` class to deselect a row in the grid.

But both the `select` and `deselect` methods has check `isSelectionAllowed()` in their impl.
</blockquote></details>

If you think it makes sense to keep it and not merge those, ok.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 1875 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY07f3dywToQ29oy8Yx:-KYDUZkV6gXryL8WMj1v:bhmp9eq) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widgets/Grid.java#L1875)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sure.
But I don't want to spread this check in every place where "client code" needs to select/deselect.

So this check is only in two places : in the grid , in `select` , `deselect` methods.
(well there are still some prechecks like CheckBoxes for actions and this logic is there as well, but each action is delegated to the mentioned methods and it's easier to have implementation localized in only one/two places).
</blockquote></details>

Right, grid methods just delegate to selection model, carry on...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/84#-KY05o4jxTJ4qGn92QOM:-KYDqxbr5j1bPEVWwBD7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4623cd4d56c8b5b319cd44379175d8dac5ea582a/client/src/main/java/com/vaadin/client/widget/grid/events/GridSelectionAllowedHandler.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I think we should always use an event, since that is extendable as we can add more parameters to without breaking API.

GridEnabledHandler should use event too IMO, like everything else. You don't have to fix that here though

To me it seems to be completely borked now, as there is an event type that is just used for registering handler type and firing the event, but not using the event ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by pleku** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Comment by pleku** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/84)*

**Pull request merged**
