### PR TITLE
Improving javadoc of Binder.removeBinding

### LINKED ISSUE #11091: Removing binding does not clean up validation error
If you remove binding when there are validation error, the validation error is not cleared away.

- Vaadin Framework version: 8.5.0

- Minimal reproducible example

Edit Product name field by clearing its content. asRequired error will trigger. Binding is removed but error indicator stays. Even if you again edit the field by setting a value, the error is still there.

```
public class MyUI extends UI {

	public class Product {

		private String name;
		private Double price;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Double getPrice() {
			return price;
		}

		public void setPrice(Double price) {
			this.price = price;
		}

	}
	
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final FormLayout layout = new FormLayout();

		final Binder<Product> binder = new Binder<>(Product.class);
        
        final TextField nameField = new TextField("Product:");

        final TextField priceField = new TextField("Price:");
        
        Product product = new Product();
        product.setName("Tool");
        product.setPrice(10.5d);

		binder.forField(priceField).withConverter(new StringToDoubleConverter("Must input number"))
				.bind(Product::getPrice, Product::setPrice);

		binder.forField(nameField)
			.asRequired("Name is mandatory")
			.bind(Product::getName, Product::setName);
        
		binder.readBean(product);

		nameField.addValueChangeListener(event -> {
			binder.removeBinding(nameField);
		});

		layout.addComponents(nameField, priceField);
        
        setContent(layout);
    }
}

```
- Expected behavior

Removing binding will do proper clean up, including removal of possible validation errors

- Actual behavior

Validation error is left permanently on display

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
Fixes #11091

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11107)

### CODE REVIEW

**Review by elmot — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11107)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mehdi-vaadin and @elmot)

___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2794 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNeSi9-viyuKTHZeop:-LJNeSi9-viyuKTHZeoq:b-6ilyn0) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2794)):*
> ```Java
>      * that might have been added to the field and do not remove required
>      * indicator of the field no matter if it was set by Binder or not. To reset
>      * component errors, <pre>field.setComponentError(null)</pre> must be called
> ```

I think it's better to use `{@code field.setComponentError(null)}` syntax. Also "must" sounds too strong, I's prefer "should"
Also `@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful
___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2812 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNfYmp9TUioRmSnfnY:-LJNfYmp9TUioRmSnfnZ:b-cbfc3t) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2812)):*
> ```Java
>     /**
>      * Removes the given Binding from this Binder.
>      * @see Binder#removeBinding(HasValue)
> ```

`@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful
___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2857 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNfhiw1LdhKXbsoo0t:-LJNfhiw1LdhKXbsoo0u:b-cbfc3t) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2857)):*
> ```Java
>     /**
>      * Finds and removes the Binding for the given property name.
>      * @see Binder#removeBinding(HasValue)
> ```

`@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful

**Review by elmot — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11107)* status: all files reviewed, 3 unresolved discussions (waiting on @mehdi-vaadin)

**Review by mehdi-vaadin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11107)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @elmot)

___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2794 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNeSi9-viyuKTHZeop:-LJNhsEl5Px0vRzPiz6W:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2794)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

I think it's better to use `{@code field.setComponentError(null)}` syntax. Also "must" sounds too strong, I's prefer "should"
Also `@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful
</blockquote></details>

Done.
___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2812 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNfYmp9TUioRmSnfnY:-LJNhsjO1nR7A3JB-zng:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2812)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful
</blockquote></details>

Done.
___
*[server/src/main/java/com/vaadin/data/Binder.java, line 2857 at r1](https://reviewable.io/reviews/vaadin/framework/11107#-LJNfhiw1LdhKXbsoo0t:-LJNht8R3a7L_a32JOOx:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5e296ed710042dda012b19bb0fa588e407b81303/server/src/main/java/com/vaadin/data/Binder.java#L2857)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@see com.vaadin.ui.AbstractComponent#setComponentError` and `@see  com.vaadin.ui.AbstractComponent#setRequiredIndicatorVisible` would be helpful
</blockquote></details>

Done.

**Review by elmot — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
