### PR TITLE
Fix date ranges for date and datetime fields

### LINKED ISSUE #9765: DateField.setRangeStart can set the range start to a day earlier based on the system time zone
Can reproduce with Vaadin 8.1.0

Steps to reproduce:

- set the system time zone to UTC-5 (US Eastern Time)
- set localDate to LocalDate.of(2017,8,1)
- call DateField.setRangeStart with the localDate
- the start date will actually show as Jul-31 instead of Aug-1

I think that the issue happens in AbstractLocalDateField.convertToDate:

`Date.from(date.atStartOfDay(ZoneOffset.UTC).toInstant());`

Using ZoneOffset.UTC doesn't seem right. 
ZoneId.systemDefault() would probably work.

Another idea would be to use the deprecated Date constructors directly:

`Date date = new Date(localDate.getYear() - 1900, localDate.getMonthValue() -1, localDate.getDayOfMonth());`

since we do not care about time zones (this is actually the implementation from java.sql.Date.valueOf(LocalDate date)).

Most likely, this issue also affects convertFromDate as well as the implementation in AbstractLocalDateTimeField.

### PR DESCRIPTION
**Pull request by elmot**
Fixes #9765

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10685)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 8 of 13 files at r1, 3 of 4 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PB4zrDWM2LRqefMkG:-L7PB4zrDWM2LRqefMkH:b-acqc8n) (no related file):*
Has a test UI but no test ?

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 2082 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P8hMjsW2Cdc1Pjw3K:-L7P8hMkwO6YVCT1lAQu:b-3htu98) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L2082)):*
> ```Java
>      *            - the allowed range's start date
>      */
>     public void setRangeStart(String newRangeStart) {
> ```

public API change needs to be documented in the release notes, even if it's only in the `client` module.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractPopupCalendar.java, line 602 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PAK_2R8OwC8_2vc4Q:-L7PAK_2R8OwC8_2vc4R:b-5w0fnx) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/client/src/main/java/com/vaadin/client/ui/VAbstractPopupCalendar.java#L602)):*
> ```Java
>      *            - the allowed range's start date
>      */
>     public void setRangeStart(String rangeStart) {
> ```

public API changes, release notes mention

---

*[client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P8zgEtGbGSOmHuM6K:-L7P8zgEtGbGSOmHuM6L:byuiq4k) ([raw file](https://github.com/vaadin/framework/blob/6d84351fee4bdb6e877d9100c8645e6c6044864e/client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java#L126)):*
> ```Java
> 
>         getWidget().setTextFieldEnabled(getState().textFieldEnabled);
>         getWidget().setRangeStart(nullSafeDateClone(getState().rangeStart));
> ```

is the `nullSafeDateClone` still used somewhere? 

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 82 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P99LX7WON3mi3qktT:-L7P99LX7WON3mi3qktU:byktews) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L82)):*
> ```Java
>         extends AbstractField<T> implements FocusNotifier, BlurNotifier {
> 
>     public static final DateTimeFormatter RANGE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd[ HH:mm:ss]", Locale.ENGLISH);
> ```

Is there a space on purpose in the pattern?

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 356 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P9H_O0nS1QLBlWMdv:-L7P9H_PqCfAiQ94XDTf:b-jfxaeo) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L356)):*
> ```Java
>     }
> 
>     protected T convertFromDateString(String temporalStr) {
> ```

new APIs. Even though it's protected, it should have javadoc.

---

*[shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P9l9e2C75BozSfz6x:-L7P9l9fuKePYNDzQzHK:bie2j5q) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java#L52)):*
> ```Java
>     /**
>      * Start range that has been cleared, depending on the resolution of the
>      * date field. The format is "YYYY-MM-DD[ HH:MM:SS]"
> ```

Should this display the pattern as it is? Reading it I can make the assumption that it does not have month number in middle of a timestamp, but would be safer to show the pattern as-is.

---

*[shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java, line 55 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PAutM2BV17m5zTm3w:-L7PAutM2BV17m5zTm3x:buiyod7) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java#L55)):*
> ```Java
>      */
>     @NoLayout
>     public String rangeStart;
> ```

public API changes, release notes mention.

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldTimeZones.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P1DbJXHeauAHx3E1X:-L7P1DbJXHeauAHx3E1Y:b-ax8fx1) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldTimeZones.java#L21)):*
> ```Java
>     @Override
>     protected void setup(VaadinRequest request) {
>         System.out.println("new Date() = " + new Date());
> ```

Why `println`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685)*

**Comment by elmot** [comment]
Review status: 6 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PB4zrDWM2LRqefMkG:-L7V9INEwbKsL1tkKcQm:bx7w4fr) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Has a test UI but no test ?
</blockquote></details>

Yeah, that is for manual testing.
I have no one last idea how to run test browser under custom  timezone.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java, line 2082 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P8hMjsW2Cdc1Pjw3K:-L7VGO9z0M0mVPmzzgnR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/client/src/main/java/com/vaadin/client/ui/VAbstractCalendarPanel.java#L2082)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

public API change needs to be documented in the release notes, even if it's only in the `client` module.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/VAbstractPopupCalendar.java, line 602 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PAK_2R8OwC8_2vc4Q:-L7VGN-ymP1DYCwS1w3i:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/client/src/main/java/com/vaadin/client/ui/VAbstractPopupCalendar.java#L602)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

public API changes, release notes mention
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java, line 126 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P8zgEtGbGSOmHuM6K:-L7V8A_ml_3xrv97nIEk:bsponfy) ([raw file](https://github.com/vaadin/framework/blob/6d84351fee4bdb6e877d9100c8645e6c6044864e/client/src/main/java/com/vaadin/client/ui/datefield/TextualDateConnector.java#L126)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

is the `nullSafeDateClone` still used somewhere? 
</blockquote></details>

Not. Removed.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 82 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P99LX7WON3mi3qktT:-L7V8axcv4rNWYFzS2CX:b-918ai5) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L82)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is there a space on purpose in the pattern?
</blockquote></details>

Yes, it divides days out of month (square braces do not - they just designates an optional part of the pattern)

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 356 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P9H_O0nS1QLBlWMdv:-L7VDPlCJBZs-i_wuvZb:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L356)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

new APIs. Even though it's protected, it should have javadoc.
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java, line 52 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P9l9e2C75BozSfz6x:-L7VAurghyvd5TXpm80t:b-s5fv7y) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java#L52)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should this display the pattern as it is? Reading it I can make the assumption that it does not have month number in middle of a timestamp, but would be safer to show the pattern as-is.
</blockquote></details>

The comments are changed to make them more understandable.

---

*[shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java, line 55 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7PAutM2BV17m5zTm3w:-L7VGR_85T6LG6wF8-zF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/shared/src/main/java/com/vaadin/shared/ui/datefield/AbstractDateFieldState.java#L55)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

public API changes, release notes mention.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldTimeZones.java, line 21 at r2](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7P1DbJXHeauAHx3E1X:-L7V99_T2g7gsx9sL2R_:bss4a2b) ([raw file](https://github.com/vaadin/framework/blob/0e23a60c266b9a13cb437530becde7dbe6b54045/uitest/src/main/java/com/vaadin/tests/components/datefield/DateFieldTimeZones.java#L21)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Why `println`?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 13 files at r1, 2 of 4 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7ik7o7zCpPPeD22J_p:-L7ik7o7zCpPPeD22J_q:b80q1xx) (no related file):*
Please run full test build with all browsers, if that seems ok, then let's get this forward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10685#-L7ik7o7zCpPPeD22J_p:-L81XDcHuNmV7yToCk8c:bcr2xrg) (no related file):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Please run full test build with all browsers, if that seems ok, then let's get this forward.
</blockquote></details>

The full test was run, there are three failures related to date field, both of them the same as for master branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685#-:-L824fqr6UW31gqgA2bf:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[client/src/main/java/com/vaadin/client/DateTimeService.java, line 67 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L827oHxrH9aT4x2hmG8:-L827oHxrH9aT4x2hmG9:b-5myal) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/client/src/main/java/com/vaadin/client/DateTimeService.java#L67)):*
> ```Java
>      *
>      * @param i the value
>      * @return "00".."99"
> ```

just noticed that this method is missing `@since`

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 82 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L82822EzkFKemlS1nc7:-L82822EzkFKemlS1nc8:boao3bb) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L82)):*
> ```Java
>         extends AbstractField<T> implements FocusNotifier, BlurNotifier {
> 
>     public static final DateTimeFormatter RANGE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd[ HH:mm:ss]", Locale.ENGLISH);
> ```

public variable is never used from outside anywhere else than a JavaDoc `@see`. Either needs JavaDocs or make it private.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 363 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L828Fv0AzfNAY-3ZglP:-L828Fv0AzfNAY-3ZglQ:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L363)):*
> ```Java
>      * @see AbstractDateFieldState#rangeStart
>      * @see AbstractDateFieldState#rangeEnd
>      */
> ```

`@since`

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 372 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L828JN0eDo7VwBKvyyK:-L828JN0eDo7VwBKvyyL:b21w91a) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L372)):*
> ```Java
> 
>     /**
>      *
> ```

Empty JavaDoc

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 384 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L828HcEkUi5MgNTDYb-:-L828HcEkUi5MgNTDYb0:by18c3v) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L384)):*
> ```Java
>      * @return textual representation
>      * @see AbstractDateFieldState#rangeStart
>      * @see AbstractDateFieldState#rangeEnd
> ```

`@since`

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 393 at r5](https://reviewable.io:443/reviews/vaadin/framework/10685#-L828LCN73_3JVfpfNDj:-L828LCN73_3JVfpfNDk:bnvrdb0) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L393)):*
> ```Java
>     }
> 
>     protected boolean afterDate(T t1, T t2) {
> ```

No JavaDoc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10685)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/DateTimeService.java, line 67 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L827oHxrH9aT4x2hmG8:-L82FnPWD4YM22yfeTJ4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/client/src/main/java/com/vaadin/client/DateTimeService.java#L67)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

just noticed that this method is missing `@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 82 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L82822EzkFKemlS1nc7:-L82FxyB5nNkvHuS970-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L82)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

public variable is never used from outside anywhere else than a JavaDoc `@see`. Either needs JavaDocs or make it private.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 363 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L828Fv0AzfNAY-3ZglP:-L82G6gdCJs1GPfDC9iI:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L363)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 372 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L828JN0eDo7VwBKvyyK:-L82GWTUB3firgbE1mAj:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L372)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Empty JavaDoc
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 384 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L828HcEkUi5MgNTDYb-:-L82Hs6d5hOTG4XYaa-r:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L384)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`@since`
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/AbstractDateField.java, line 393 at r5](https://beta.reviewable.io/reviews/vaadin/framework/10685#-L828LCN73_3JVfpfNDj:-L82HrUx27qTsC-_UG4g:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/aa081406f6994aff0ecd0725415a20ef022ed2c6/server/src/main/java/com/vaadin/ui/AbstractDateField.java#L393)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

No JavaDoc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10685)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/framework/10685)*

**Pull request merged**
