### PR TITLE
Grid - let ComponentRenderer extend from ClickableRenderer (#10237)

### PR DESCRIPTION
**Pull request by JenoDK**
One of the reasons for this was to allow easy selection forwarding to the grid
 due to the RendererClickEvent having the clicked row item (see #10237).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10238)

### CODE REVIEW

**Comment by asashour** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jQAwJv7bqyDnbZHP:-Kx7jQAwJv7bqyDnbZHQ:b-6txrky) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java#L12)):*
> ```Java
> import com.vaadin.client.widget.grid.RendererCellReference;
> 
> public abstract class ComponentRenderer extends ClickableRenderer<String, SimplePanel> {
> ```

Javadoc and `@since`

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRendererConnector.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jcmLe-oOUmUZA-l6:-Kx7jcmLe-oOUmUZA-l7:b-1cejuw) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRendererConnector.java#L40)):*
> ```Java
> 
>     @Override
>     public com.vaadin.client.connectors.grid.ComponentRenderer getRenderer() {
> ```

Any reason for fully qualified class name?

---

*[server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jq22oxq0zDLHGMQD:-Kx7jq22oxq0zDLHGMQE:b-hzfdz6) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java#L62)):*
> ```Java
> 
>     /**
>      * Adds a click listener to the renderer that will select the clicked row item in the grid
> ```

First sentence should end with a period.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10238)*

**Comment by JenoDK** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jQAwJv7bqyDnbZHP:-Kx80rkmcmD2jysapoVY:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java#L12)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Javadoc and `@since`
</blockquote></details>

Done

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRendererConnector.java, line 40 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jcmLe-oOUmUZA-l6:-Kx821V3OME6dQBxGUTl:b-rchjtz) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRendererConnector.java#L40)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Any reason for fully qualified class name?
</blockquote></details>

This was because of the ```@Connect``` to the server ComponentRenderer.
```@Connect(ComponentRenderer.class)```
Switched it around though and used fully qualified class name in ```@Connect``` and javadoc
```


---

*[server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jq22oxq0zDLHGMQD:-Kx83n2hRur4V2DiF7CJ:bb6un1j) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/server/src/main/java/com/vaadin/ui/renderers/ComponentRenderer.java#L62)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

First sentence should end with a period.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10238)*
<!-- Sent from Reviewable.io -->

**Comment by asashour** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jQAwJv7bqyDnbZHP:-Kx8AlYJYQ2-B3yjS32B:b-rqrv67) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java#L12)):*
<details><summary><i>Previously, JenoDK wrote…</i></summary><blockquote>

Done
</blockquote></details>

There are two `ComponentRenderer`s, one in `com.vaadin.client.renderers` and another in `com.vaadin.client.connectors.grid`, is this on purpose?

This one has no JavaDoc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10238)*

**Comment by JenoDK** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java, line 12 at r1](https://reviewable.io:443/reviews/vaadin/framework/10238#-Kx7jQAwJv7bqyDnbZHP:-Kx8D5CElJNvo1EZ2PG7:bihfgyk) ([raw file](https://github.com/vaadin/framework/blob/2d2c1d4e32bc4cfb38f8bd00c4ef0455b51da5c9/client/src/main/java/com/vaadin/client/connectors/grid/ComponentRenderer.java#L12)):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

There are two `ComponentRenderer`s, one in `com.vaadin.client.renderers` and another in `com.vaadin.client.connectors.grid`, is this on purpose?

This one has no JavaDoc.
</blockquote></details>

The one in ```com.vaadin.client.connectors.grid``` should have been moved (so now deleted) in this revision. Started working with IntelliJ very recently and apparently I copied instead of moving the class *oops*. I'll fix that one right away.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10238)*

**Comment by tsuoanttila** [comment]
PR in add-on repo reviewed for the first round. Some minor stuff to deal with in there, but should be able to get it through that.

**Comment by tsuoanttila** [comment]
For reference tsuoanttila/GridExtensionPack#23

**Pull request closed without merging**
