### PR TITLE
Read/write Grid item type to declarative and create columns correctly

### LINKED ISSUE #8467: Make the declarative format support the Grid(Class) constructor
A `Grid` created using `new Grid<>(SomeBean.class)` should be written out with the fully qualified class name in an attribute so that when the declarative file is read, you can still use `myGrid.addColumn("propertyName")`.

Any column created based on property name should be stored as such in the declarative format so that it can be recreated with a binding to the same property name.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8467

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8769)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 767 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegog1KRliREblVmAz4:-Kegog1KRliREblVmAz5:b-s85hf2) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L767)):*
> ```Java
>         Grid<Person> grid = read(design);
>         Field f = Grid.class.getDeclaredField("beanType");
>         f.setAccessible(true);
> ```

why not add Optional<Class<T>> Grid.getBeanType() and use that?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 793 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegpxWZkC_iUvUpdUg3:-KegpxWZkC_iUvUpdUg4:b1aa4tc) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L793)):*
> ```Java
>         Elements cols = Selector.select("vaadin-grid", html)
>                 .select("colgroup > col");
>         Assert.assertEquals("Expected " + i + " columns in the design file", i,
> ```

Extra information in assertEquals  first parameter. `Assert` actually produces more or less reasonable message. 
"Columns in the design file" is enough
(not a blocker)

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegtL-I9KjwlAYjif0F:-KegtL-I9KjwlAYjif0G:b-j3tkq2) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L848)):*
> ```Java
> 
>     @Test
>     public void beanGridOnlyCustomColumns() {
> ```

Does it have any sense? How it is supposed to be used?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 892 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegt7jVGr7HupLY61qx:-Kegt7jVGr7HupLY61qy:b-j3tkq2) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L892)):*
> ```Java
>         // First and last name should not be mapped to anything but should exist
>         Assert.assertNull(readGrid.getColumns().get(11).getValueProvider()
>                 .apply(testPerson));
> ```

Does it have any sense? How it is supposed to be used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by ripla** [comment]
:clap: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2007 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegui5g__Dyl58L_m74:-Kegui5g__Dyl58L_m75:b9uf8jr) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L2007)):*
> ```Java
>     private PropertySet<T> propertySet;
> 
>     private Class<T> beanType = null;
> ```

Do we need to store a `Class` reference or could we store e.g. FQN or something similar?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-Kegpa8bViUa2ppLRHKq:b57meeh) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
> ```Java
>     protected void doReadDesign(Element design, DesignContext context) {
>         Attributes attrs = design.attributes();
>         if (design.hasAttr(DECLARATIVE_DATA_ITEM_TYPE)) {
> ```

Purely from a Designer perspective, it would be great if we would have an overridable method for resolving the `PropertySet` for a class, since we cannot load the class via `Class.forName`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769#-:-KegtTv02zOyuR1LTjh6:bc0irgz)*

**Comment by Artur-** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2007 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegui5g__Dyl58L_m74:-KegwoiYOh6RBOJN48eR:b-p67iwh) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L2007)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Do we need to store a `Class` reference or could we store e.g. FQN or something similar?
</blockquote></details>

It's more logical to store a class reference - does it pose any problems for Designer? 

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-KehSnttzbjOcl5yTSKc:b7snc1l) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Purely from a Designer perspective, it would be great if we would have an overridable method for resolving the `PropertySet` for a class, since we cannot load the class via `Class.forName`
</blockquote></details>

Done. Will this version work?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 767 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegog1KRliREblVmAz4:-KegwRVmJX84_ZqcIMTi:bbkjo9p) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L767)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

why not add Optional<Class<T>> Grid.getBeanType() and use that?
</blockquote></details>

More API, but still would make sense to add I think.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 793 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegpxWZkC_iUvUpdUg3:-KehSpOiBBylV23bWfYq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L793)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Extra information in assertEquals  first parameter. `Assert` actually produces more or less reasonable message. 
"Columns in the design file" is enough
(not a blocker)
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegtL-I9KjwlAYjif0F:-KegwVaxn2rtS2rnCkd5:bz2bq9n) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L848)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Does it have any sense? How it is supposed to be used?
</blockquote></details>

It's just a test to validate that columns without property names are not mapped to some bean property when they should not

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 892 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegt7jVGr7HupLY61qx:-Kegwa3gSiTQ8s1xWh55:bz2bq9n) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L892)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Does it have any sense? How it is supposed to be used?
</blockquote></details>

It's just a test to validate that columns without property names are not mapped to some bean property when they should not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2007 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegui5g__Dyl58L_m74:-Kehf_inxy1fC27jA0A1:b-fmve6a) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L2007)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's more logical to store a class reference - does it pose any problems for Designer? 
</blockquote></details>

Is it possible if Designer has no actual class loaded but only class name?  
Might that happen if the class source is open in IDE, has some errors and is not compilable for the moment?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegtL-I9KjwlAYjif0F:-KeheRICJDsJA0p2US71:b-ajgb8b) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L848)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's just a test to validate that columns without property names are not mapped to some bean property when they should not
</blockquote></details>

What is the use case for those columns? Are those columns initialized without valueProvider? Do they just throw NPEs or are they able to show something useful?

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 892 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegt7jVGr7HupLY61qx:-KehfO2uZ4sgnJ5GDPod:byr4ffv) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L892)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

It's just a test to validate that columns without property names are not mapped to some bean property when they should not
</blockquote></details>

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by ripla** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2007 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegui5g__Dyl58L_m74:-Kehn6GbBUCU-ZYlW2u0:bgsyv2c) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L2007)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Is it possible if Designer has no actual class loaded but only class name?  
Might that happen if the class source is open in IDE, has some errors and is not compilable for the moment?
</blockquote></details>

We cannot load the class inside Designer, so we can never use the `Class` constructor. But, with the current overridable setPropertySet, I think we might be able to manage around that by inheriting Grid and handling the property set ourselves. We already write the item-type attribute ourselves as well.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-Kehn36rnul3Ks-GiBr3:bb6mt9b) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Done. Will this version work?
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by elmot** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by ripla** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2007 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegui5g__Dyl58L_m74:-KeiO1dyik_Fu54QbcRS:b66mocc) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L2007)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

We cannot load the class inside Designer, so we can never use the `Class` constructor. But, with the current overridable setPropertySet, I think we might be able to manage around that by inheriting Grid and handling the property set ourselves. We already write the item-type attribute ourselves as well.
</blockquote></details>

The best case would be that this functionality would be usable without concrete `Class` instances. The second best option would be that we could override methods to handle class -> properties and class <-> declarative ourselves.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-KeiNUQiGX27Cr9WOPWw:b1pdzku) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Or actually I think we would need to call `setPropertySet` ourselves as well. So what we want to do is to customise the way a bean name (`String`) is resolved into a `PropertySet`, without using a `Class` instance at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-KeiVy0t1cdFpu6Og5oA:bfx3zuq) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Or actually I think we would need to call `setPropertySet` ourselves as well. So what we want to do is to customise the way a bean name (`String`) is resolved into a `PropertySet`, without using a `Class` instance at all.
</blockquote></details>

Which is exactly what `setBeanType(String)` can be used for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by ripla** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-KeloD54qPESvdtekj8d:b-3fndas) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Which is exactly what `setBeanType(String)` can be used for?
</blockquote></details>

Yeah, should `setPropertySet` be protected in that case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by Artur-** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3554 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-Kegpa8bViUa2ppLRHKp:-KelzgJDcJ_X1mt9iw1N:b-bm9yhb) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/main/java/com/vaadin/ui/Grid.java#L3554)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Yeah, should `setPropertySet` be protected in that case?
</blockquote></details>

Right, it is now + added test for using a custom property set

---

*[server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java, line 848 at r1](https://reviewable.io:443/reviews/vaadin/framework/8769#-KegtL-I9KjwlAYjif0F:-KemCYIa0PC7bo1F0BkF:b-gexk7p) ([raw file](https://github.com/vaadin/framework/blob/b83d0374856b0fd1b05ef73afc1cc01e99646ec3/server/src/test/java/com/vaadin/tests/server/component/grid/GridDeclarativeTest.java#L848)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What is the use case for those columns? Are those columns initialized without valueProvider? Do they just throw NPEs or are they able to show something useful?
</blockquote></details>

The value provider is not throwing anything, as verified by this test. Seems like they support returning inline data defined in the design file. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769)*

**Comment by ripla** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769#-:-Kf6WS0GD0J5XKRhPUba:bnfp4nl)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8769#-:-Kf71md_Bi3qPpsWmrhz:bnfp4nl)*

**Pull request merged**
