### PR TITLE
Optimization for HierarchyMapper. Partially fixes #9951

### LINKED ISSUE #9951: TreeGrid#expand "is very slow" with 10'000 subnodes (Vaadin 8.1.3)
Given the following example:

```
package treegrid_expand_slow;

import com.vaadin.server.VaadinRequest;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.TreeGrid;
import com.vaadin.ui.UI;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

@SpringUI
public class TreegridExpandSlowUI extends UI {

    private static final int NUMBER_OF_SUBPROJECTS = 10_000;

    @Override
    protected void init(VaadinRequest request) {
        TreeGrid<JProject> treeGrid = new TreeGrid<>();
        final List<JProject> rootProjects = createRootProjects();

        treeGrid.setItems(rootProjects, JProject::getSubProjects);

        treeGrid.addColumn(JProject::getName).setCaption("Project Name");
        treeGrid.addColumn(JProject::getHoursDone).setCaption("Hours Done");
        treeGrid.addColumn(JProject::getLastModified).setCaption("Last Modified");

        treeGrid.setSizeFull();
        setContent(treeGrid);
    }

    private List<JProject> createRootProjects() {
        List<JProject> rootProjects = new ArrayList<>();
        rootProjects.add(
                new JProject(
                        "All projects",
                        NUMBER_OF_SUBPROJECTS,
                        LocalDateTime.now(),
                        IntStream.rangeClosed(1, NUMBER_OF_SUBPROJECTS).boxed()
                                .map(integer -> new JProject("Project #" + integer, 1, LocalDateTime.now(), new ArrayList<>()))
                                .collect(Collectors.toList())
                )
        );
        return rootProjects;
    }
}


package treegrid_expand_slow;

import java.time.LocalDateTime;
import java.util.List;

public class JProject {

    private final String name;
    private final int hoursDone;
    private final LocalDateTime lastModified;
    private final List<JProject> subProjects;

    public JProject(String name, int hoursDone, LocalDateTime lastModified, List<JProject> subProjects) {
        this.name = name;
        this.hoursDone = hoursDone;
        this.lastModified = lastModified;
        this.subProjects = subProjects;
    }

    public String getName() {
        return name;
    }

    public int getHoursDone() {
        return hoursDone;
    }

    public LocalDateTime getLastModified() {
        return lastModified;
    }

    public List<JProject> getSubProjects() {
        return subProjects;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        JProject jProject = (JProject) o;

        return name.equals(jProject.name);
    }

    @Override
    public int hashCode() {
        return name.hashCode();
    }
}

```

When:
I open the browser 

Then:
the TreeGrid is displayed "very fast".

When:
I expand the "All Projects" root node

Then: 
I wait a couple of seconds (5 secs on my machine) until I see the first 26 sub projects.

**I guess**
It looks for me like TreeGrid pushes **all** the data to the client in an expand event, even only some of them will be displayed. There seems to be no optimization on transferring only a actually useful amount of data. 

In my real world application, I have a some nodes in a TreeGrid with 50'000 subnodes and clicking the expand triangle takes up to a minute. During that minute a full CPU core is 100% used and the electric power bill is enormous. The profiler tool shows the time is spent in the HierarchyMapper.

**Question**
Is this a current limitation of TreeGrid or do I make it wrong? Are there workarounds?

Thanks for your time & analysis,
Peti

### PR DESCRIPTION
**Pull request by pwilkin**
Moved pull request to separate branch. Supersedes #9999

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10003)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-izsJt4GSQ2aYV30S:-Ku-izsJt4GSQ2aYV30T:buprs1g) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L62)):*
> ```Java
>     // removing children of expanded nodes.
>     private Map<T, Set<T>> childMap = new HashMap<>();
>     private Map<T, T> parentMap = new HashMap<>();
> ```

could consider storing ID -> parent instance map for easier accessing the data we want. See comment in `getParentOfItem`.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 357 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-iZb4cLPkswnhboki:-Ku-iZb4cLPkswnhbokj:baqxcpd) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L357)):*
> ```Java
>     private T getParentOfItem(T item) {
>         Objects.requireNonNull(item, "Can not find the parent of null");
>         return parentMap.get(item);
> ```

This should compare the IDs of the `item` and the keys in `parentMap`, since the `item` could be a new instance representing the same data.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 383 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-jIrGrSkn7mhozj9L:-Ku-jIrGrSkn7mhozj9M:b-sbumuu) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L383)):*
> ```Java
>         invalidatedChildren.stream().map(getDataProvider()::getId)
>                 .forEach(this::removeChildren);
>         invalidatedChildren.forEach(parentMap::remove);
> ```

same ID mapping as above. Could combine to do both removals at the same time. 

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 477 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-j_EvIApBAc9TeEcm:-Ku-j_EvIApBAc9TeEcn:b-l3z3s9) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L477)):*
> ```Java
>             } else {
>                 childMap.put(parent, new HashSet<>(childList));
>                 childList.forEach(x -> parentMap.put(x, parent));
> ```

store mapping from id to parent instance instead of child instance to parent instance

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10003)*

**Comment by pwilkin** [comment]
Updated request to incorporate proposal.

**Comment by pwilkin** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-izsJt4GSQ2aYV30S:-Ku4-ky9weUr8GodeT_w:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L62)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

could consider storing ID -> parent instance map for easier accessing the data we want. See comment in `getParentOfItem`.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 357 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-iZb4cLPkswnhboki:-Ku4-lxP191xqiY_2HDM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L357)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

This should compare the IDs of the `item` and the keys in `parentMap`, since the `item` could be a new instance representing the same data.
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 383 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-jIrGrSkn7mhozj9L:-Ku4-mU5TJ3TY5X2oDNF:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L383)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

same ID mapping as above. Could combine to do both removals at the same time. 
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java, line 477 at r1](https://reviewable.io:443/reviews/vaadin/framework/10003#-Ku-j_EvIApBAc9TeEcm:-Ku403zkME03FoYfpvJ4:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/4a93344bfdff414d2c28dd2288ef9581af33e506/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java#L477)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

store mapping from id to parent instance instead of child instance to parent instance
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10003)*

**Comment by tsuoanttila** [comment]
Looks ok, will test a bit manually before merging. 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10003#-:-KuOKZj7W8b54keQFzNv:b-7032u8)*

**Pull request merged**
