### PR TITLE
Integrate BeanBinder functionality into Binder

### PR DESCRIPTION
**Pull request by Legioth**
The only reason for using `Binder` instead of `BeanBinder` is that `BeanBinder` requires a class literal as a constructor parameter. Aside from this, the separation between the two classes only contributes to confusion for users ("which should I use?") and for maintainers (lots of boilerplate in `BeanBinder`to support chaining).

The proposed solution introduces an `BinderPropertySet` abstraction that is used by `Binder` to deal with property names in `bind(String)` and `bindInstanceFields(Object)`. An implementation mimicking the functionality of `BeanBinder` is automatically used if using the `Binder(Class)` constructor.

Using the no-args constructor of `Binder` will use a property set implementation that causes `bind(String)` and `bindInstanceFields(Object)` to throw a runtime exception. Losing compile time checking for this condition is a small drawback of this approach, but the benefit is less overall confusion and boilerplate.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8096)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 8 of 15 files at r1.
Review status: 8 of 15 files reviewed at latest revision, 21 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TJLHmLcaBasAd61U7:-K_TJLHn5pjuxJKTA-XW:bcz4ule) (no related file):*
Need to update vaadin/al/src/main/templates/release-notes.html to remove mention of `BeanBinder`

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1983 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbd-r1-1983:-K_TMhQ7GGXyK6Eb1C4e:b-w82rkm) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L1983)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Either log or rethrow this exception. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1166)
</blockquote></details>

No need to log this I think

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2041 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TMwXV9SBcOutGAVM3:-K_TMwXV9SBcOutGAVM4:b-qqfsc1) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L2041)):*
> ```Java
>      * @return list of all fields in the class considering hierarchy
>      */
>     private List<Field> getFieldsInDeclareOrder(Class<?> searchClass) {
> ```

This method should probably be moved to `ReflectTools`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Review status: 8 of 15 files reviewed at latest revision, 22 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TNi5zCe07cK9WqHng:-K_TNi5zCe07cK9WqHnh:b-fv27xj) (no related file):*
Should fix most SonarCube whinings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Reviewed 7 of 15 files at r1.
Review status: all files reviewed at latest revision, 32 unresolved discussions, some commit checks broke.

---

*[server/src/test/java/com/vaadin/data/BeanBinderInstanceFieldTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TOFuo9onEbfHrxYHp:-K_TOFuo9onEbfHrxYHq:bem34qz) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/test/java/com/vaadin/data/BeanBinderInstanceFieldTest.java#L34)):*
> ```Java
> 
> /**
>  * Unit tests for {@link BeanBinder#bindInstanceFields(Object)} method.
> ```

Remove this and should probably rename the test class too

---

*[server/src/test/java/com/vaadin/data/BeanBinderTest.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TOaNJm5jp8hlcvdiK:-K_TOaNJm5jp8hlcvdiL:btqfjac) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/test/java/com/vaadin/data/BeanBinderTest.java#L15)):*
> ```Java
> import com.vaadin.ui.CheckBoxGroup;
> 
> public class BeanBinderTest
> ```

Maybe should rename this too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 31 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2041 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TMwXV9SBcOutGAVM3:-K_TS4zGo6pD-0dZEySE:b-y2koos) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L2041)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

This method should probably be moved to `ReflectTools`
</blockquote></details>

The original decision has been made by me: do not have it there since the functionality is quite specific to the usecase.
I don't see at the moment any other usecase for such method (exact declaration order).

So technically it can be moved there, yes. But should it be moved ? I'm not sure (it's not the best idea to make a dump for every reflection method in `ReflectionTools`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 31 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2041 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TMwXV9SBcOutGAVM3:-K_TbfNBpnvYZgo2e3HX:b-nqbgxx) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L2041)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The original decision has been made by me: do not have it there since the functionality is quite specific to the usecase.
I don't see at the moment any other usecase for such method (exact declaration order).

So technically it can be moved there, yes. But should it be moved ? I'm not sure (it's not the best idea to make a dump for every reflection method in `ReflectionTools`).
</blockquote></details>

My intent is just to avoid having to duplicate things when the usecase appears, or mayhaps you find this method and then tweak it to suit more generalized case.. overall, you cannot find it from here.

Meh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 30 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2041 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TMwXV9SBcOutGAVM3:-K_TfdtloCyyk8vk0jW2:bqszqnm) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L2041)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

My intent is just to avoid having to duplicate things when the usecase appears, or mayhaps you find this method and then tweak it to suit more generalized case.. overall, you cannot find it from here.

Meh.
</blockquote></details>

True , but.... 
I don't know.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 30 unresolved discussions, some commit checks broke.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 2041 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TMwXV9SBcOutGAVM3:-K_Tg9IsqaapNxbZoRTT:b9tlsa7) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L2041)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

True , but.... 
I don't know.
</blockquote></details>

This patch only moves this pre-existing and already reviewed code to another file together with the only method that uses it. Feel free to create a separate PR if you want this moved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by Legioth** [comment]
Review status: 7 of 17 files reviewed at latest revision, 25 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TNi5zCe07cK9WqHng:-KaCDoXS6UDqrfphherS:bwsoitz) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should fix most SonarCube whinings
</blockquote></details>

Some fixed, others not...

---

*[server/src/main/java/com/vaadin/annotations/PropertyId.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbb-r1-50:-KaBxZqg3-hPIj3nWuW7:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/annotations/PropertyId.java#L50)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Javadoc comment at column 15 has parse error. Missed HTML close tag 'Entity'. Sometimes it means that close tag missed for one of previous tags. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java, line 142 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbk-r1-142:-KaBy30fNW_TVyIOzT2b:biz2tpt) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java#L142)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Move this constructor to comply with Java Code Conventions. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS1213)
MAJOR Remove this unused private "BeanBinderPropertySet" constructor. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)

</blockquote></details>

Moved, but it's still used.

---

*[server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java, line 179 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbk-r1-179:-KaBy8wj5T4F4KW5aeYg:bb710yj) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/BeanBinderPropertySet.java#L179)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

MAJOR Define and throw a dedicated exception instead of using a generic one. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS00112)
</blockquote></details>

Nope

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1125 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbd-r1-1125:-KaCCntHqBzcF8vGC9FW:b7ir5jh) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L1125)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Document this method return value. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AUndocumentedApi)
CRITICAL Rename this generic name to match the regular expression '^[A-Z][0-9]?$'. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=squid%3AS00119)

</blockquote></details>

Return value documented. Generic name not changed.

---

*[server/src/main/java/com/vaadin/data/Binder.java, line 1937 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_9Kc4-rJnXL63BvDbd-r1-1937:-KaCD1aVb9J3CHFuoFB0:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/main/java/com/vaadin/data/Binder.java#L1937)):*
<details><summary><i>Previously, vaadin-bot (Vaadin Bot) wrote…</i></summary><blockquote>

CRITICAL Javadoc comment at column 54 has parse error. Missed HTML close tag 'T'. Sometimes it means that close tag missed for one of previous tags. [rule](https://sonar.projects.vaadin.com/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck)
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BeanBinderInstanceFieldTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TOFuo9onEbfHrxYHp:-KaCDbszmBtpQNJtjpeP:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/test/java/com/vaadin/data/BeanBinderInstanceFieldTest.java#L34)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Remove this and should probably rename the test class too
</blockquote></details>

Done.

---

*[server/src/test/java/com/vaadin/data/BeanBinderTest.java, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TOaNJm5jp8hlcvdiK:-KaCDe545BLL6Lv52Gfu:bow5479) ([raw file](https://github.com/vaadin/framework/blob/f6b4269d23252e4fec5bb01562d07ace50809773/server/src/test/java/com/vaadin/data/BeanBinderTest.java#L15)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Maybe should rename this too
</blockquote></details>

`BinderTest` is already in use. Doesn't feel sensible right now to merge the contents of those two tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TJLHmLcaBasAd61U7:-KaCftTfTmDJA91lO8BF:b-wyz2lb) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Need to update vaadin/al/src/main/templates/release-notes.html to remove mention of `BeanBinder`
</blockquote></details>

Please fix in `release-notes.html` line 123
            <li><tt>Binder</tt> is the replacement of <tt>FieldGroup</tt>, and similarly <tt>BeanBinder</tt> is the replacement of <tt>BeanFieldGroup</tt></li>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by Legioth** [comment]
Review status: 16 of 17 files reviewed at latest revision, 28 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/8096#-K_TJLHmLcaBasAd61U7:-KaCrMz1ezST2abAVA2L:bb6un1j) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please fix in `release-notes.html` line 123
            <li><tt>Binder</tt> is the replacement of <tt>FieldGroup</tt>, and similarly <tt>BeanBinder</tt> is the replacement of <tt>BeanFieldGroup</tt></li>

</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8096)*

**Pull request merged**
