### PR TITLE
Implement widget event handling for Columns in Grid

### LINKED ISSUE #7833: Row selection for grid when clicked on row text - component renderer
**Originally by _vinod_**

___
Dear Vaadin Team,

When clicked on the row text in order to select the row in a grid, the selection is not performed on the grid row.

The selection works when clicked area apart from the row text.

The behavior can be seen easily in the demo provided by Vaadin for component renderer at - http://componentrenderer.datenhahn.de/

Open Tab "Not a bean grid" and click on the text "some1". The row does not get selected.
I have attached an image for the same.

Expected Behavior - 
The row should get selected when clicked on "some1" text.

Below is the part of the code for component renderer involving Grid -

--------------------------------------------------------------------------
        Grid grid = new Grid();
        grid.addColumn("foo");
        grid.addRow("A");
        grid.addRow("B");
        grid.addRow("C");
        grid.addRow("D");
        ComponentGridDecorator componentGrid = new ComponentGridDecorator<>(grid, null);
       
        grid.setSizeFull(); 

        componentGrid.addComponentColumn("some text", e -> new Label("text"+e));

        grid.setColumns("some text");
---------------------------------------------------------------------------------

Thanks,
Vinod

___
 Imported from https://dev.vaadin.com/ issue #20295

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #7833

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10412)

### CODE REVIEW

**Comment by ahie** [comment]
Some missing since tags on the public methods.

---

Reviewed 5 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2335 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SImO495AGz-bioFvm:-L1SImO495AGz-bioFvn:b-3x7m5w) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2335)):*
> ```Java
>                 }
> 
>                 // Handle event in widget in grid if column allows it
> ```

Comment is perhaps a bit misleading. Wouldn't something like "Don't handle event of child widget unless the column has been explicitly permitted to do so" be closer to what this branch does?

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2060 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SJQPOVGgETMZtmqFW:-L1SJQPOVGgETMZtmqFX:b8f2hol) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/server/src/main/java/com/vaadin/ui/Grid.java#L2060)):*
> ```Java
>         /**
>          * Sets whether Grid should handle events in this Column from Components
>          * and Widgets rendered by certain Renderers.
> ```

Could mention the default value.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SFM7x2D_VS-7lNX5V:-L1SFM7x2D_VS-7lNX5W:b-vsa5l1) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java#L30)):*
> ```Java
>         Grid<String> grid = new Grid<>();
>         grid.addComponentColumn(Label::new).setId("label")
>                 .setCaption("Column 0").setWidgetEventsAllowed(true);
> ```

Is there an IT test for this? This change should make it so that if you click the label element it will now also select the row?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10412#-:-L1SFl9bfrNyQtArgbJN:b-kft97h)*

**Comment by tsuoanttila** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 2335 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SImO495AGz-bioFvm:-L1W_4lQM_UbmIH-8SWl:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/client/src/main/java/com/vaadin/client/widgets/Grid.java#L2335)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Comment is perhaps a bit misleading. Wouldn't something like "Don't handle event of child widget unless the column has been explicitly permitted to do so" be closer to what this branch does?
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 2060 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SJQPOVGgETMZtmqFW:-L1WptMvPEvUcCPB3u5o:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/server/src/main/java/com/vaadin/ui/Grid.java#L2060)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could mention the default value.
</blockquote></details>

Done.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10412#-L1SFM7x2D_VS-7lNX5V:-L1WpstIFnFsJxHHcZMh:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/db639bb04ce952540ceec893f4af4c12899bd9ae/uitest/src/main/java/com/vaadin/tests/components/grid/GridComponents.java#L30)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Is there an IT test for this? This change should make it so that if you click the label element it will now also select the row?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10412)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10412#-:-L1WqE-BWEs-A-zV8xB0:bnfp4nl)*

**Comment by ahie** [comment]
Reviewed 1 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10412)*

**Comment by MatthieuCoelho** [comment]
Shouldn't focus change when user click on a new Cell ? Because when a component renderer is used (addComponentColumn) focus don't change.

**Comment by pinonpierre** [comment]
Same issue. The focus doesn't change. Can you take a look

**Comment by tsuoanttila** [comment]
Related but separate issue. Please open a ticket instead of commenting on an already merged PR.

**Pull request merged**
