### PR TITLE
Only throw from Binder.bindInstanceFields if there are no bindings at all

### LINKED ISSUE #8986: Instance field not found
Vaadin version: 8.0.5

```java
public class Person {
    LocalDate mydate;
    public LocalDate getMydate() { ... }
    public void setMydate(...) { … }
}
```

```java
private TextField mydate = new TextField();

init(...) {
  Binder<Person> binder = new Binder<>(Person.class);
  binder.forMemberField(mydate)
    .withConverter(str -> LocalDate.now(), date -> "Hello");
  binder.bindInstanceFields(this);
}
```

Getting error:
`java.lang.IllegalStateException: There are no instance fields found for automatic binding`

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #8986

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9487)

### CODE REVIEW

**Comment by mstahv** [comment]
This fix looks correct to me. Could somebody from the Framework team please have a look at this. Pleas.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487#-:-KmaEhCS3XgexJalZu_p:b-c4h9ji)*

**Comment by tsuoanttila** [comment]
*[server/src/test/java/com/vaadin/data/BeanBinderTest.java, line 233 at r1](https://reviewable.io:443/reviews/vaadin/framework/9487#-KmaFra0lTs_Y99PVlvr:-KmaFra0lTs_Y99PVlvs:bsn1ijq) ([raw file](https://github.com/vaadin/framework/blob/590638957a3a9893066d8970fde88d2f1f516a17/server/src/test/java/com/vaadin/data/BeanBinderTest.java#L233)):*
> ```Java
>                 .withConverter(str -> LocalDate.now(), date -> "Hello")
>                 .bind("mydate");
>         binder.bindInstanceFields(this);
> ```

Should bindInstanceFields use the TestClassWithoutFields here and the next one as well to make sure there are no fields to bind with the method? Will this test start behaving unexpectedly if someone adds a field to this test class?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487)*

**Comment by tsuoanttila** [comment]
There are at least 2 failing unit tests that need to be looked at before this can be merged.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487#-:-KmaF3o6pxqucvLPm7yZ:b2nedwk)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487)*

**Comment by Artur-** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/test/java/com/vaadin/data/BeanBinderTest.java, line 233 at r1](https://reviewable.io:443/reviews/vaadin/framework/9487#-KmaFra0lTs_Y99PVlvr:-Kmf7Z09hpsyCBMTI89W:bbx2nxs) ([raw file](https://github.com/vaadin/framework/blob/590638957a3a9893066d8970fde88d2f1f516a17/server/src/test/java/com/vaadin/data/BeanBinderTest.java#L233)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should bindInstanceFields use the TestClassWithoutFields here and the next one as well to make sure there are no fields to bind with the method? Will this test start behaving unexpectedly if someone adds a field to this test class?
</blockquote></details>

It should use `form`. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9487)*

**Comment by tsuoanttila** [comment]
This was picked to 8.0.7

**Pull request merged**
