### PR TITLE
Rewrote debouncing of onResize

### LINKED ISSUE #11892: Grid renderes with gap between rows
**Description of the bug**

In certain cases, when resizing the browser window or view container, the vaadin grid renders with gaps between rows:

vaadinGridRowGapBug1

grid

Inspecting the DOM reveals that there is a mismatch in the row `translate3d` property values:
image (5)

The above grids are created in the following way:
```
Grid<Person> grid3 = new Grid<>(Person.class);
grid3.setItems(Person.generate());
grid3.setSizeFull();
grid3.setId("grid3");
grid3.getEditor().setEnabled(true);
grid3.getEditor().setBuffered(false);
```

**Expected behavior**
The grid renders correctly and there are no gaps between the rows.

**Actual behavior**
The grid renders with gaps between rows (as can be seen in the attached images)

**Steps to reproduce**
We were able to reproduce this issue using the vaadin 8 sampler project: https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features
1. Navigate to the grid features page (https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features)
2. Scroll to the bottom of the grid
3. Using the resize grid control (in the bottom right corner), resize the grid vertically up and down a few times
4. Eventually the grid will render with gaps between rows:
Screen Shot 2020-02-25 at 09 10 22

**Misc**
- Vaadin Framework version: 8.9.3
- Browser: Chrome (also possible to reproduce in Firefox)

### PR DESCRIPTION
**Pull request by TatuLund**
Fixes https://github.com/vaadin/framework/issues/11892

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11899)

### CODE REVIEW

**Review by OlliTietavainenVaadin — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11899)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TatuLund)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4370 at r1](https://reviewable.io/reviews/vaadin/framework/11899#-M14phe04mFNTv_DHIMi:-M14phe04mFNTv_DHIMj:bafx46u) ([raw file](https://github.com/vaadin/framework/blob/7ddbe5b608390bfe2f532fa8dd2d51b47922972c/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4370)):*
> ```Java
> 
>     private boolean resizeRequested = false;
>     private boolean resizeRerfreshScheduled = false;
> ```

typo, rename to "resizeRefreshSchaduled"

**Review by TatuLund — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11899)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @OlliTietavainenVaadin)

___
*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 4370 at r1](https://reviewable.io/reviews/vaadin/framework/11899#-M14phe04mFNTv_DHIMi:-M14rxtBDjBjlbx8YHgy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/7ddbe5b608390bfe2f532fa8dd2d51b47922972c/client/src/main/java/com/vaadin/client/widgets/Grid.java#L4370)):*
<details><summary><i>Previously, OlliTietavainenVaadin (Olli Tietäväinen) wrote…</i></summary><blockquote>

typo, rename to "resizeRefreshSchaduled"
</blockquote></details>

Done.

**Review by OlliTietavainenVaadin — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11899#-:-M15GcCRAedzIAsRateR:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @OlliTietavainenVaadin)

**Review by OlliTietavainenVaadin — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11899)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
