### PR TITLE
Fix grid dnd issues

### PR DESCRIPTION
**Pull request by wbadam**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9347)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 213 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL89rp-AIJT4XbLUAI:-KkL89rp-AIJT4XbLUAJ:b5rzhv5) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L213)):*
> data

So what if the data for this row is empty / null ??? can you just filter those out ?

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL8JoqTXh8EvzIYKC1:-KkL8JorCadmy63Y85YG:bsa32ut) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L81)):*
>  Get data of any of the types {@code "text"}, {@code "Text"} or {@code
>      * "text/plain"}.

Please add clarity for why it is so. `IE 11 only supports data type of <code>Text</code>`

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL8fYLQz9YUmvSRW4W:-KkL8fYLQz9YUmvSRW4X:b-crtv7l) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java#L52)):*
> ```Java
>      * "Text" with capital letter.
>      */
>     public static final String DATA_TYPE_TEXT_IE = "Text";
> ```

Should this also be used for IE11 when setting the data transfer text with `setDataTransferText` or as with the default data in `GridDragSource` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9347)*

**Comment by wbadam** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java, line 81 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL8JoqTXh8EvzIYKC1:-KkLM-Z06RykzV2nbpat:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/server/src/main/java/com/vaadin/ui/dnd/event/DropEvent.java#L81)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

>  Get data of any of the types {@code "text"}, {@code "Text"} or {@code
>      * "text/plain"}.

Please add clarity for why it is so. `IE 11 only supports data type of <code>Text</code>`
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java, line 52 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL8fYLQz9YUmvSRW4W:-KkLL0AY4Z_y13SL2fSf:bb8gek5) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/shared/src/main/java/com/vaadin/shared/ui/dnd/DragSourceState.java#L52)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Should this also be used for IE11 when setting the data transfer text with `setDataTransferText` or as with the default data in `GridDragSource` ?
</blockquote></details>

Nope, `"text"` seems to work just fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9347)*

**Comment by pleku** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9347)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java, line 213 at r1](https://reviewable.io:443/reviews/vaadin/framework/9347#-KkL89rp-AIJT4XbLUAI:-KkLQwnwQSBTwlrRh1lY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/5fdbe03a4c1295fe26d2293a0cac9f1ac1a63e51/client/src/main/java/com/vaadin/client/connectors/grid/GridDragSourceConnector.java#L213)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

> data

So what if the data for this row is empty / null ??? can you just filter those out ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9347)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9347)*

**Pull request merged**
