### PR TITLE
Update tutorial.adoc

### PR DESCRIPTION
**Pull request by alexandruchiuariu**
Thanks for submitting a pull request!
Please confirm that your pull request follows our guidelines found in CONTRIBUTING and that you provide enough information so that we can review your pull request.

<Description of pull request, e.g. "Fix Grid Column not sortable with backend data and sort property">

Fixes #<replace with an issue number>

**Check when you have completed**
[ ] Valid tests for the pull request
[ ] Contributing guidelines implemented

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/11493)

### CODE REVIEW

**Comment by anasmi** [comment]
Thank you for submitting the pull request! :)

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11493)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alexandruchiuariu)

___
*[documentation/tutorial.adoc, line 54 at r1](https://reviewable.io/reviews/vaadin/framework/11493#-L_rBkY7BPWWi3zBbawx:-L_rBkY893UNmwrbJ7Pd:b-72w0qe) ([raw file](https://github.com/vaadin/framework/blob/db0302a364936a9032d066ef8aecc8b19a6c0cf1/documentation/tutorial.adoc#L54)):*
> ```AsciiDoc
> To start from a specific step, we have prepared the example code after each step to be downloaded as a zip file.
> 
> TIP: The free training videos are an accessible way to get familiar with Vaadin 8 and the web components that are used with this platform. https://vaadin.com/training/courses?type=all[See all courses here!] 
> ```

As we have discussed here https://vaadin.slack.com/archives/C6R5HLL03/p1552480764006800, let rephrase it

**Review by alexandruchiuariu — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11493)* status: all files reviewed, 1 unresolved discussion (waiting on @alexandruchiuariu)

**Review by ZheSun88 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/framework/11493#-:-L_rJWdE3HCEwRbdzG8-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
