### PR TITLE
Fix java packaging order

### PR DESCRIPTION
**Pull request by tsuoanttila**
Closes vaadin/archetypes#113

This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/106)

### CODE REVIEW

**Comment by OlliTietavainenVaadin** [comment]
Tested on Ubuntu Linux 14.04; building project created out of multimodule archetype no longer fails to find dependencies like it does without this patch.

**Comment by hesara** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/pom.xml, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTg3fdmURDO9ZjUHPV:-KYTg3fdmURDO9ZjUHPW:b3slfgh) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/client/pom.xml#L71)):*
> ```XML
>                         <id>copy-sources</id>
>                         
>                         <phase>process-resources</phase>
> ```

Is the manifest in sec/main/resources? Is it only updated for OSGi after this phase?

---

*[server/pom.xml, line 169 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTgbIVbK1_bKFASLhB:-KYTgbIVbK1_bKFASLhC:bfrzvxu) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/server/pom.xml#L169)):*
> ```XML
>                         <id>copy-sources</id>
>                         
>                         <phase>process-resources</phase>
> ```

see the comment in client pom

---

*[shared/pom.xml, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTgjoWSiHkN-EWCFF3:-KYTgjoWSiHkN-EWCFF4:buoztwl) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/shared/pom.xml#L90)):*
> ```XML
>                         <id>copy-sources</id>
>                         
>                         <phase>process-resources</phase>
> ```

see the comment above + are the elemental sources already available here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/106)*

**Comment by tsuoanttila** [comment]
I'll compare the OSGi Manifests against the one in 7.7.6 build to see if it has changed.

**Comment by hesara** [comment]
Reviewed 2 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/pom.xml, line 71 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTg3fdmURDO9ZjUHPV:-KYXZvibsmmuIu0dLFRH:b-1enlzr) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/client/pom.xml#L71)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is the manifest in sec/main/resources? Is it only updated for OSGi after this phase?
</blockquote></details>

apparently OSGi manifests are ok

---

*[server/pom.xml, line 169 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTgbIVbK1_bKFASLhB:-KYX_-7b4V3R3NiOD8M4:b-1enlzr) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/server/pom.xml#L169)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see the comment in client pom
</blockquote></details>

apparently OSGi manifests are ok

---

*[shared/pom.xml, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTgjoWSiHkN-EWCFF3:-KYX_10sM2upVKaOcOQP:b-9mcnzp) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/shared/pom.xml#L90)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

see the comment above + are the elemental sources already available here
</blockquote></details>

apparently OSGi manifests are ok, but the elemental sources question might still be relevant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/106)*

**Comment by tsuoanttila** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[shared/pom.xml, line 60 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYXhL1_lrpmy7Zd6kji:-KYXhL1_lrpmy7Zd6kjj:b-ptqjdc) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/shared/pom.xml#L60)):*
> ```XML
>                     <execution>
>                         <id>unpack-dependencies</id>
>                         <phase>generate-resources</phase>
> ```

This is an even earlier phase. I'm not sure how unpack touches the timestamps of files though.

---

*[shared/pom.xml, line 90 at r1](https://reviewable.io:443/reviews/vaadin/framework/106#-KYTgjoWSiHkN-EWCFF3:-KYXhVth9jB8Ub5vh2MO:b-otilcs) ([raw file](https://github.com/vaadin/framework/blob/bade0ecf5358727a309c5f7178f83b6fa6120751/shared/pom.xml#L90)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

apparently OSGi manifests are ok, but the elemental sources question might still be relevant
</blockquote></details>

See comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/106)*

**Comment by hesara** [comment]
:lgtm: - if there is anything more to change later, we can come back to it separately

---

Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/106#-:-KYXpsSy506DxQyfoc6k:b-pfatgw)*

**Pull request merged**
