### PR TITLE
Fix vaadin-test and all its submodules

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch applies following fixes:
ContextMenu with correct version for Vaadin 8
Correctly skip install plugin for test submodules
Make widgetset-test-util a test depdendency, don't use test-jar

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8076)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 5 of 20 files at r1.
Review status: 5 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/pom.xml, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_wod2zWV_sBs20fkr:-KZ_wod3AShp8_qn2h_5:b-3ylh54) ([raw file](https://github.com/vaadin/framework/blob/60097da19728f2675245a914f0bd98f4f01df896/test/pom.xml#L154)):*
> ```XML
> 
>             <plugin>
>                 <artifactId>maven-install-plugin</artifactId>
> ```

Does this mean that the main test module (this one) is installed?

---

*[test/addon-using-init-param-widget-set/pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_x6tr80_J9C7y6Kba:-KZ_x6tr80_J9C7y6Kbb:b-9n4xs8) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-init-param-widget-set/pom.xml#L37)):*
> ```XML
>                 <groupId>com.vaadin</groupId>
>                 <artifactId>vaadin-maven-plugin</artifactId>
>                 <version>${vaadin.plugin.version}</version>
> ```

No pluginManagement in BOM? Would one have an effect?

---

*[test/addon-using-init-param-widget-set/error-screenshots/appStartsUserCanInteract(com.vaadin.test.addonusinginitparamwidgetset.AddonUsingInitParamWidgetSetIT).png, line 0 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xNdwNmi5MjfE3sdU:-KZ_xNdwNmi5MjfE3sdV:bmjgdyz) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-init-param-widget-set/error-screenshots/appStartsUserCanInteract(com.vaadin.test.addonusinginitparamwidgetset.AddonUsingInitParamWidgetSetIT).png#L0)):*
What is this file, and does it have parentheses in the file name on purpose?

---

*[test/addon-using-own-widget-set/pom.xml, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xcNDP59vG9-8joMS:-KZ_xcNDP59vG9-8joMT:be6co43) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-own-widget-set/pom.xml#L22)):*
> ```XML
>             <groupId>com.vaadin</groupId>
>             <artifactId>vaadin-context-menu</artifactId>
>             <version>2.0-SNAPSHOT</version>
> ```

use property from parent

---

*[test/own-widget-set/src/main/resources/com/vaadin/test/ownwidgetset/OwnWidgetSet.gwt.xml, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xlY8ok6uLG9PbuD0:-KZ_xlY8ok6uLG9PbuD1:b-cst0os) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/own-widget-set/src/main/resources/com/vaadin/test/ownwidgetset/OwnWidgetSet.gwt.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Added to Git for a reason? New test?

---

*[test/widget-set-testutil/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_y277OdhnDjBZgEAs:-KZ_y277OdhnDjBZgEAt:b-sq4298) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/widget-set-testutil/pom.xml#L15)):*
> ```XML
>     <dependencies>
>         <dependency>
>             <groupId>com.vaadin</groupId>
> ```

Is this appropriate if the util module is used elsewhere (might bring extra stuff to the classpath)? OTOH provided so probably not a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by tsuoanttila** [comment]
Review status: 5 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[test/pom.xml, line 154 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_wod2zWV_sBs20fkr:-KZa-JJekDpXLd9-N06o:b-xkt8fg) ([raw file](https://github.com/vaadin/framework/blob/60097da19728f2675245a914f0bd98f4f01df896/test/pom.xml#L154)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Does this mean that the main test module (this one) is installed?
</blockquote></details>

it's the parent pom used by the test dependency, I'm not sure if we really need to install this but as long as there's a parent relationship, it's kind of a problem.

---

*[test/addon-using-init-param-widget-set/pom.xml, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_x6tr80_J9C7y6Kba:-KZa-9LyZst3XoHgRG_X:b-4icgvr) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-init-param-widget-set/pom.xml#L37)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

No pluginManagement in BOM? Would one have an effect?
</blockquote></details>

At least according to my earlier tests, you can't define a plugin management in the BOM. Might be I did it somehow wrong and would still be doable in some way.

---

*[test/addon-using-init-param-widget-set/error-screenshots/appStartsUserCanInteract(com.vaadin.test.addonusinginitparamwidgetset.AddonUsingInitParamWidgetSetIT).png, line  at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xNdwNmi5MjfE3sdU:-KZ_zFNa-Aga_w0-sKrY:bqjukb5) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-init-param-widget-set/error-screenshots/appStartsUserCanInteract(com.vaadin.test.addonusinginitparamwidgetset.AddonUsingInitParamWidgetSetIT).png#L)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

What is this file, and does it have parentheses in the file name on purpose?
</blockquote></details>

Looks like an error-screenshot, accidentally added, will remove.

---

*[test/own-widget-set/src/main/resources/com/vaadin/test/ownwidgetset/OwnWidgetSet.gwt.xml, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xlY8ok6uLG9PbuD0:-KZ_zO5LlAmnMrEw58Lz:btnwo4d) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/own-widget-set/src/main/resources/com/vaadin/test/ownwidgetset/OwnWidgetSet.gwt.xml#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Added to Git for a reason? New test?
</blockquote></details>

It's an old test that was in a completely broken state. The UI defines a Widgetset (com.vaadin.test.ownwidgetset.OwnWidgetSet) but there was no widgetset xml at all, so the test UI did not even load due to missing widgetset.

---

*[test/widget-set-testutil/pom.xml, line 15 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_y277OdhnDjBZgEAs:-KZ_zgRBkVv5sqfUn2Dh:b-yk64aw) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/widget-set-testutil/pom.xml#L15)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this appropriate if the util module is used elsewhere (might bring extra stuff to the classpath)? OTOH provided so probably not a problem.
</blockquote></details>

This is only a test dependency, and I would even want to split it in two separate parts (one that is strictly test scoped, one with normal scope). The current state of the build did not allow running a single dependency of this one, since the test-jar was only available when doing a full compilation. (Could be it could somehow be installed into the local repo but felt like less of a problem this way)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by tsuoanttila** [comment]
*[test/addon-using-own-widget-set/pom.xml, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZ_xcNDP59vG9-8joMS:-KZa6G9pkySnY0HyIaPa:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/122020054e648b4f90535885692843d03e7805e9/test/addon-using-own-widget-set/pom.xml#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

use property from parent
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by hesara** [comment]
Reviewed 3 of 20 files at r1, 9 of 13 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 65 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaLUhLXK-2PfCGNPVx:-KZaLUhLXK-2PfCGNPVy:b-qppb9p) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/.gitignore#L65)):*
> ```
> */.checkstyle
> 
> # TB default error screenshot forlder
> ```

folder

---

*[test/widget-set-testutil/pom.xml, line 7 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMFFWLla82cAXfpEJ:-KZaMFFWLla82cAXfpEK:bz3uyiy) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L7)):*
> ```XML
>     <groupId>com.vaadin</groupId>
>     <artifactId>vaadin-test-widget-set-testutil</artifactId>
>     <version>8.0-SNAPSHOT</version>
> ```

(probably needs some mention in a readme about setting the version, and adding this to our release build conf)

---

*[test/widget-set-testutil/pom.xml, line 11 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMQMZ1qYCOAxkZy_G:-KZaMQMZ1qYCOAxkZy_H:bmltyor) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L11)):*
> ```XML
> 
>     <properties>
>         <vaadin.version>8.0-SNAPSHOT</vaadin.version>
> ```

How is this set from the outside when compiling?  Or does it need to be set if the using projects use the BOM, as the dependencies of this module are all provided?

---

*[test/widget-set-testutil/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMk8BM_BeVWkx27Uq:-KZaMk8BM_BeVWkx27Ur:bqkzg9h) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L16)):*
> ```XML
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
> ```

Can this conflict with BOM used from the concrete test project, as this does not just set the provided dependency versions but also uses dependencyManagement that can affect other modules?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by tsuoanttila** [comment]
Review status: 16 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/widget-set-testutil/pom.xml, line 7 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMFFWLla82cAXfpEJ:-K_3QU6HfpY7XoFe_bRq:b6f66we) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L7)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(probably needs some mention in a readme about setting the version, and adding this to our release build conf)
</blockquote></details>

Building this is part of the test build, and does not require version number setting at all. Basically test new vaadin version: mvn clean verify -Dvaadin.version=VERSION_NUMBER

Will add a README.md in the vaadin-test project.

---

*[test/widget-set-testutil/pom.xml, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMk8BM_BeVWkx27Uq:-K_3QJQP1ZQJVTsnEUKI:biu499c) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L16)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Can this conflict with BOM used from the concrete test project, as this does not just set the provided dependency versions but also uses dependencyManagement that can affect other modules?
</blockquote></details>

Not actually sure. Going to just put the vaadin.version to the two dependencies and remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r3.
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/widget-set-testutil/pom.xml, line 7 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaMFFWLla82cAXfpEJ:-K_SvaKRwPA_ijfgi_tD:b-kw3owl) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/test/widget-set-testutil/pom.xml#L7)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Building this is part of the test build, and does not require version number setting at all. Basically test new vaadin version: mvn clean verify -Dvaadin.version=VERSION_NUMBER

Will add a README.md in the vaadin-test project.
</blockquote></details>

(the user needs to beware if using any other commands or building submodules separately as this will have explicit version numbers in the artifact, so having built an old version of this and a new version of some other submodule might (or might not) cause complications - probably not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 2 files at r4.
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitignore, line 65 at r2](https://reviewable.io:443/reviews/vaadin/framework/8076#-KZaLUhLXK-2PfCGNPVx:-Ka1d9iL5DpdNwB64IRR:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/fa986385fe86fbeab3db0c66083da079fb103b75/.gitignore#L65)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

folder
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Comment by hesara** [comment]
:lgtm: - probably needs rebase

---

Reviewed 1 of 13 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076#-:-Ka1eLLGxF4gxp9tMKaW:b-5at5ge)*

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8076)*

**Pull request merged**
