### PR TITLE
Fix some issues with Binder serialization

### PR DESCRIPTION
**Pull request by elmot**
Partial fix for #8640

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8660)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KddtvxsnSFYa_9ka-Zw:-KddtvxtgtKwb56OeFVM:b-dtojfd) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L106)):*
> ```Java
>     }
> 
>     private static class BeanPropertyDefinition<T, V>
> ```

the implemented Vaadin interface PropertyDefinition is already Serializable

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KdduhS1KHfrf1mEiisO:-KdduhS2Hp58ngwVUQ5-:b-ydggd) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L137)):*
> ```Java
>         @Override
>         public Optional<Setter<T, V>> getSetter() {
>             if (descriptor.getWriteMethod() == null) {
> ```

I'm not sure if I understand why this method was changed - is there a closure serializability issue here that is resolved by not keeping the setter but rather fetching it on demand? If so, a comment would be good so that the next person in line won't simply "simplify" this by reverting the change.

---

*[server/src/test/java/com/vaadin/data/BinderMultiSelectTest.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KddtEeI4pcSsMjHMzkj:-KddtEeI4pcSsMjHMzkk:b-k10qr6) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/test/java/com/vaadin/data/BinderMultiSelectTest.java#L37)):*
> ```Java
> public class BinderMultiSelectTest
>         extends BinderTestBase<Binder<BeanWithEnums>, BeanWithEnums> {
>     public static  class TestEnumSetToStringConverter
> ```

extra space?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8660)*

**Comment by hesara** [comment]
Reviewed 3 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8660)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KdduhS1KHfrf1mEiisO:-Kdf32fmFtZP0vBYeJJ5:b7qk2mc) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L137)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

I'm not sure if I understand why this method was changed - is there a closure serializability issue here that is resolved by not keeping the setter but rather fetching it on demand? If so, a comment would be good so that the next person in line won't simply "simplify" this by reverting the change.
</blockquote></details>

maybe still add a comment here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8660)*

**Comment by elmot** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KddtvxsnSFYa_9ka-Zw:-Kddz9FHNpkZpblkBKRc:bqm8mjp) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L106)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

the implemented Vaadin interface PropertyDefinition is already Serializable
</blockquote></details>

Done, removed

---

*[server/src/main/java/com/vaadin/data/BeanPropertySet.java, line 137 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KdduhS1KHfrf1mEiisO:-Kdf3uQBYOm_eFFAVc-0:b7s3fui) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/main/java/com/vaadin/data/BeanPropertySet.java#L137)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

maybe still add a comment here
</blockquote></details>

Comment added

---

*[server/src/test/java/com/vaadin/data/BinderMultiSelectTest.java, line 37 at r1](https://reviewable.io:443/reviews/vaadin/framework/8660#-KddtEeI4pcSsMjHMzkj:-Kddz7kSnIBZI4M6QS_f:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/2201246c7e3fbbac409b274611ca4ec1e4c7941b/server/src/test/java/com/vaadin/data/BinderMultiSelectTest.java#L37)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

extra space?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8660)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8660#-:-Kdf4vkEZ6JLWNk-g96L:bnfp4nl)*

**Pull request merged**
