### PR TITLE
Bugfix/1149

### LINKED ISSUE #1149: Panel.setScrollTop() fails with impossibly large numbers
**Originally by @wolfie**

___
Setting the scroll-top position (might affect scroll-left position equally) to a very large number (verified with Integer.MAX_VALUE and values a bit less than that) behaves just like giving a zero as the argument.

Expected behavior: always scroll to the end (or, at least to the pixel specified by the maximum integer value).

___
 Imported from https://dev.vaadin.com/ issue #5274

### PR DESCRIPTION
**Pull request by OlliTietavainenVaadin**
Fixes #1149 Panel.setScrollTop not working on IE/Edge/Safari/PhantomJS when the argument is bigger than the content div height.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8563)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/panel/PanelSetScrollTopWithLargeNumberTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8563#-KcwhwakoRac9cg8T4_C:-KcwhwakoRac9cg8T4_D:b-gjiz95) ([raw file](https://github.com/vaadin/framework/blob/3efbbe5b4d17c553ae560bd997abce9d0be33de9/uitest/src/test/java/com/vaadin/tests/components/panel/PanelSetScrollTopWithLargeNumberTest.java#L34)):*
> ```Java
>     }
> 
>     private Object executeScript(String script, WebElement element) {
> ```

this can be simplified away - just use AbstractTB3Test.executeScript

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8563)*

**Comment by OlliTietavainenVaadin** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/panel/PanelSetScrollTopWithLargeNumberTest.java, line 34 at r1](https://reviewable.io:443/reviews/vaadin/framework/8563#-KcwhwakoRac9cg8T4_C:-KcwnRxr8xnDgKh45-Y5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/3efbbe5b4d17c553ae560bd997abce9d0be33de9/uitest/src/test/java/com/vaadin/tests/components/panel/PanelSetScrollTopWithLargeNumberTest.java#L34)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this can be simplified away - just use AbstractTB3Test.executeScript
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8563)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8563#-:-KemNLOOE_mccAiUzfMf:bnfp4nl)*

**Comment by OlliTietavainenVaadin** [comment]
ok

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8563#-:-KemS4VytteTuReFmwH_:b32wtd)*

**Pull request merged**
