### PR TITLE
Add Grid editor events.

### LINKED ISSUE #8202: Grid Editor events
Grid Editor should have listeners to handle events like save and cancel in the Editor.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #8202.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8365)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbu7icMFXOSnSZ-C2wf:-Kbu7icMFXOSnSZ-C2wg:bm0r3vh) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java#L59)):*
> ```Java
> 
>         public CustomEditorHandler() {
>             registerRpc(EditorClientRpc.class, this);
> ```

Why make CustomEditorHandler implement EditorClientRpc and expose the API ? The public API for the class is now much more confusing since it has the RPC methods there, e.g. two cancel methods with completely different purpose.

If you thought it is too long for inline class, could have just made it an internal class

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuD_L6iDl4vy0Azbdu:-KbuD_L6iDl4vy0Azbdv:b-ltc6vm) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java#L32)):*
> ```Java
>  *            the bean type
>  */
> public class EditorCancelEvent<T> extends EventObject {
> ```

There could be a `getGrid()` method in this event, shorthand for `getSource().getParent()`

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelListener.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuCcEWjwJ2Xd3TFl2X:-KbuCcEWjwJ2Xd3TFl2Y:b835lzl) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelListener.java#L23)):*
> ```Java
> 
> /**
>  * An event listener for a {@link Grid} editor save events.
> ```

"...editor cancel events."

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorSaveEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuDMrmZUZoZkWBIXtI:-KbuDMrmZUZoZkWBIXtJ:b-ltc6vm) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorSaveEvent.java#L32)):*
> ```Java
>  *            the bean type
>  */
> public class EditorSaveEvent<T> extends EventObject {
> ```

There could be a `getGrid()` method in this event, shorthand for `getSource().getParent()`

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuFan91PE5WST0jzTr:-KbuFan91PE5WST0jzTs:bkddsgo) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java#L48)):*
> ```Java
>         editor.cancel();
> 
>         Assert.assertEquals("2. editor is canceled", getLogRow(0));
> ```

I kind of would like the test to also verify that both buttons also work when another row is edited ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbu7icMFXOSnSZ-C2wf:-KbuHh54ZwDkobsYOb9a:bmzj5gt) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java#L59)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Why make CustomEditorHandler implement EditorClientRpc and expose the API ? The public API for the class is now much more confusing since it has the RPC methods there, e.g. two cancel methods with completely different purpose.

If you thought it is too long for inline class, could have just made it an internal class
</blockquote></details>

Expose to whom ?
The class is private.

I can introduce one more class but it has no sense from my opinion. 
API is not exposed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuD_L6iDl4vy0Azbdu:-KbxeYOPcIF9Na2nTSRx:b-esy739) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

There could be a `getGrid()` method in this event, shorthand for `getSource().getParent()`
</blockquote></details>

Not really.
Editor has no such method `getParent()`.
And it can't have it since `EditorImpl` has no reference to a `Grid` at all.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelListener.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuCcEWjwJ2Xd3TFl2X:-KbxesP4UrJuq-R425EL:b-ucfkn4) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelListener.java#L23)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

"...editor cancel events."
</blockquote></details>

Thanks.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorSaveEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuDMrmZUZoZkWBIXtI:-Kbxew4_zrNc2GUDIcSB:bjdsgut) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorSaveEvent.java#L32)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

There could be a `getGrid()` method in this event, shorthand for `getSource().getParent()`
</blockquote></details>

No, explained above.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuFan91PE5WST0jzTr:-KbxfHFSBq8eV5nLxHlB:b-avz9jg) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java#L48)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I kind of would like the test to also verify that both buttons also work when another row is edited ...
</blockquote></details>

Do you mean the same code but for two rows ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by Legioth** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuD_L6iDl4vy0Azbdu:-KbxkVV0EiFYNLp9aDeV:b-nnfmr3) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Not really.
Editor has no such method `getParent()`.
And it can't have it since `EditorImpl` has no reference to a `Grid` at all.
</blockquote></details>

`EditorImpl` has `getParent()`, but `Editor` doesn't have anything similar. Might be useful also for other cases to add `Editor.getGrid()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by denis-anisimov** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java, line 32 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuD_L6iDl4vy0Azbdu:-KbxlUG27HfUJGvVzSf0:bgyxwjh) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/server/src/main/java/com/vaadin/ui/components/grid/EditorCancelEvent.java#L32)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

`EditorImpl` has `getParent()`, but `Editor` doesn't have anything similar. Might be useful also for other cases to add `Editor.getGrid()`
</blockquote></details>

Ah, `EditorImpl` is an extension....... And `getParent()`is just inherited.
Right.
I will extend the interface then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbu7icMFXOSnSZ-C2wf:-KbyhRPdHcOTjQhQg-R_:bee03gt) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java#L59)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Expose to whom ?
The class is private.

I can introduce one more class but it has no sense from my opinion. 
API is not exposed.
</blockquote></details>

Seems just weird that not there are two cancel methods in this class, even though it is private, and they are both for completely different case. The another is for the public API, another just for handling some event that this class is interested. Not a blocker, but IMO it makes the maintenance more difficult as you cannot distinct between these two methods or just generally harder to see what are the listener methods now that they are in the class.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuFan91PE5WST0jzTr:-KbyhDUly3bgx3Xs2i3f:b-qi30f8) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java#L48)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Do you mean the same code but for two rows ?
</blockquote></details>

Yes, that the listeners are also added for another row, and no duplicate event on server side 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by denis-anisimov** [comment]
Review status: 10 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java, line 59 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbu7icMFXOSnSZ-C2wf:-KbyuhQvYiDGa_uNbsUa:bhmcz5l) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/client/src/main/java/com/vaadin/client/connectors/grid/EditorConnector.java#L59)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Seems just weird that not there are two cancel methods in this class, even though it is private, and they are both for completely different case. The another is for the public API, another just for handling some event that this class is interested. Not a blocker, but IMO it makes the maintenance more difficult as you cannot distinct between these two methods or just generally harder to see what are the listener methods now that they are in the class.
</blockquote></details>

It's Javascript, so I will revert it back.
I don't see an issue with having implementation for two unrelated interfaces in one class.
In Java it's even better: no need to load additional class (which is ugly anonymous by the way).

But it's not that important especially here in the code which is going to be JS.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/framework/8365#-KbuFan91PE5WST0jzTr:-KbyyrFk1earNH-1jFnY:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/adc9de4940a5717639745e88d7ab9c6160b173be/uitest/src/test/java/com/vaadin/tests/components/grid/GridEditorEventsTest.java#L48)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Yes, that the listeners are also added for another row, and no duplicate event on server side 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
needs manual rebase

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365#-:-Kbz-F-aOUJY4pcROcNZ:b-hk739m)*

**Comment by pleku** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridHeaderStyleNames.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbz4ImuJ2mT9s68FFtk:-Kbz4ImuJ2mT9s68FFtl:b8w9tcc) ([raw file](https://github.com/vaadin/framework/blob/735878ec46677bc59e35132b420cf2eb9307cb22/uitest/src/main/java/com/vaadin/tests/components/grid/GridHeaderStyleNames.java#L31)):*
> ```Java
> import com.vaadin.ui.components.grid.HeaderRow;
> 
> public class GridHeaderStyleNames extends AbstractTestUIWithLog {
> ```

Unrelated ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by denis-anisimov** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/main/java/com/vaadin/tests/components/grid/GridHeaderStyleNames.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/8365#-Kbz4ImuJ2mT9s68FFtk:-Kbz5zugttQVqCJ2Mu6N:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/735878ec46677bc59e35132b420cf2eb9307cb22/uitest/src/main/java/com/vaadin/tests/components/grid/GridHeaderStyleNames.java#L31)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Unrelated ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Comment by pleku** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8365)*

**Pull request merged**
