### PR TITLE
Stale bot config template

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10646)

### CODE REVIEW

**Comment by jtomass** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.github/stale.yml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GUeAezwMyL5-BZn5u:-L6GUeAezwMyL5-BZn5v:b-3eag4v) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L14)):*
> ticket  seems  

Double space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10646)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.github/stale.yml, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GV6KtFHDMn5pv8vOm:-L6GV6KtFHDMn5pv8vOn:bpg3sun) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L1)):*
> ```YAML
> daysUntilStale: 274
> ```

why 274 and not 365? 

---

*[.github/stale.yml, line 4 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GV9fABhIReZxIF101:-L6GV9fABhIReZxIF102:b-u03ryy) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L4)):*
> ```YAML
> daysUntilClose: 30
> exemptLabels:
>  - BFP
> ```

Do we have these two labels

---

*[.github/stale.yml, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GVBo2D4BXkwGllciy:-L6GVBo2D4BXkwGllciz:b6lby3t) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L6)):*
> ```YAML
>  - BFP
>  - Pinned
> staleLabel: Stale
> ```

Is this label added to the repo

---

*[.github/stale.yml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GVHqBY0RSaRekxRza:-L6GVHqBY0RSaRekxRzb:b-d19k7z) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L14)):*
> ```YAML
>   important and still relevant, we are closing old tickets which have not been
>   touched in a long time.
>   No further work will be done on this ticket. If the ticket  seems to be still
> ```

Technically the user can prevent the ticket from closing by commenting on it, so rather encourage the user to check it on the most recent and ask to make sure there's code to reproduce the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10646)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[.github/stale.yml, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GV6KtFHDMn5pv8vOm:-L6LKKiNML2dNSWu-PRk:b-9dslka) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L1)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

why 274 and not 365? 
</blockquote></details>

(PR date) - (Beta1 date) 

What about 335 (1Y - stale period?)

---

*[.github/stale.yml, line 4 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GV9fABhIReZxIF101:-L6LKVzfKadl9RFV3Cze:bb9rr1x) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L4)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Do we have these two labels
</blockquote></details>

We have

---

*[.github/stale.yml, line 6 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GVBo2D4BXkwGllciy:-L6LKd_uBTCYPWblsZ4w:b6b4svn) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L6)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is this label added to the repo
</blockquote></details>

Already added

---

*[.github/stale.yml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GVHqBY0RSaRekxRza:-L6LLv6EzYbghjAOu7G6:b-l8a1uy) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L14)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Technically the user can prevent the ticket from closing by commenting on it, so rather encourage the user to check it on the most recent and ask to make sure there's code to reproduce the issue.
</blockquote></details>

Some (quite a lot of them, imho) of the old problems are changed because of other code base, changed author's point of view etc. Why not rewrite the ticket?

---

*[.github/stale.yml, line 14 at r1](https://reviewable.io:443/reviews/vaadin/framework/10646#-L6GUeAezwMyL5-BZn5u:-L6LOxjuZMjPqvKEJf_l:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/30e1f5a5b36fa5c3d3ce8d0408dc79bde7b248a1/.github/stale.yml#L14)):*
<details><summary><i>Previously, jtomass wrote…</i></summary><blockquote>

> ticket  seems  

Double space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10646)*

**Comment by jtomass** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10646)*

**Pull request merged**
