### PR TITLE
Add item description to RadioButtonGroup and CheckBoxGroup

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9841)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Fixes the issue mentioned in #9803

**Comment by hesara** [comment]
Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-n3y_Zqagrwb302o:-Krp-n3y_Zqagrwb302p:bnl2cjt) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L105)):*
> ```Java
>     }
> 
>     public JsonObject getItem(Element element) {
> ```

(could have javadoc)

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 151 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-eLPGgYidL1-52qq:-Krp-eLPGgYidL1-52qr:boc3ldb) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L151)):*
> ```Java
>     }
> 
>     protected MultiSelectDataGenerator createDataGenerator() {
> ```

javadoc, since tag

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 189 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-6nSrSLmRRS7xnFU:-Krp-6nSrSLmRRS7xnFV:b4fkvbx) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L189)):*
> ```Java
> 
>     /**
>      * Sets the description generator that is used for generating descriptions
> ```

could indicate that description == tooltip

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 193 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-CKKTz9Wjbf7cgls:-Krp-CKKTz9Wjbf7cglt:b-9w2q20) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L193)):*
> ```Java
>      *
>      * @param descriptionGenerator
>      *            the item description generator to set, or <code>null</code> to
> ```

not consistent with implementation (null case)

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 195 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-7VwPdnSsJiMeaBW:-Krp-7VwPdnSsJiMeaBX:b-alxg9j) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L195)):*
> ```Java
>      *            the item description generator to set, or <code>null</code> to
>      *            remove a previously set generator
>      */
> ```

since tag here and below

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 231 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozpJU2Yg9TfWKjylR:-KrozpJVxGSvnHsQfdhf:b4fkvbx) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L231)):*
> ```Java
> 
>     /**
>      * Sets the description generator that is used for generating descriptions
> ```

could indicate that description == tooltip

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 235 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-F7HqbgyMCfBDnmy:-Krp-F7HqbgyMCfBDnmz:b-9w2q20) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L235)):*
> ```Java
>      *
>      * @param descriptionGenerator
>      *            the item description generator to set, or <code>null</code> to
> ```

not consistent with implementation (null case)

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 236 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozmjyllRf9b_W3L9J:-KrozmjyllRf9b_W3L9K:bsjtwd0) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L236)):*
> ```Java
>      * @param descriptionGenerator
>      *            the item description generator to set, or <code>null</code> to
>      *            remove a previously set generator
> ```

since tags here and below

---

*[shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozjOQbDsDWf6Rq-Yn:-KrozjOReO2wEhhn1e7n:bd0f3of) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java#L36)):*
> ```Java
>     public static final String JSONKEY_ITEM_SELECTED = "s";
> 
>     public static final String JSONKEY_ITEM_DESCRIPTION = "dsc";
> ```

(should this have a since tag?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-n3y_Zqagrwb302o:-Ks2oxLw5mf9tVVzoM4s:b-be3b7m) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L105)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(could have javadoc)
</blockquote></details>

Should have, yes. This whole API should maybe be available also on some higher level for a common accessor for possible other implementations of the description generator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by ahie** [comment]
Review status: 7 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java, line 105 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-n3y_Zqagrwb302o:-Ks2p6XtM_5atK3JJaXl:b-1y1i0j) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/client/src/main/java/com/vaadin/client/ui/VRadioButtonGroup.java#L105)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Should have, yes. This whole API should maybe be available also on some higher level for a common accessor for possible other implementations of the description generator.
</blockquote></details>

Added javadocs for now.

---

*[server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java, line 151 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-eLPGgYidL1-52qq:-Ks2q2skiAClVC7YJCML:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/AbstractMultiSelect.java#L151)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

javadoc, since tag
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 189 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-6nSrSLmRRS7xnFU:-Ks2rG3w7pJyXeQuZolD:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L189)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could indicate that description == tooltip
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 193 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-CKKTz9Wjbf7cgls:-Ks2rGfnyRZoDPGdWjRY:b-sifwij) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L193)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not consistent with implementation (null case)
</blockquote></details>

Passing null now sets an empty description generator.

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 195 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-7VwPdnSsJiMeaBW:-Ks2rNkx-FJzoSAJatQp:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L195)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tag here and below
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 231 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozpJU2Yg9TfWKjylR:-Ks2rsFt7C4AWYFe0X3C:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L231)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could indicate that description == tooltip
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 235 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-F7HqbgyMCfBDnmy:-Ks2rsuJq2x3C6WV5QAq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L235)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not consistent with implementation (null case)
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/RadioButtonGroup.java, line 236 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozmjyllRf9b_W3L9J:-Ks2rtP5fcw9Y1jWIrIy:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/RadioButtonGroup.java#L236)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

since tags here and below
</blockquote></details>

Done.

---

*[shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozjOQbDsDWf6Rq-Yn:-Ks2s0GSli3Xm6G3WTSf:bqmjwcz) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java#L36)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(should this have a since tag?)
</blockquote></details>

Added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by hesara** [comment]
Reviewed 3 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 105 at r4](https://reviewable.io:443/reviews/vaadin/framework/9841#-KsD2QeKtop2xv3HoHAR:-KsD2QeKtop2xv3HoHAS:b-mp4f8l) ([raw file](https://github.com/vaadin/framework/blob/5f42862b7b2714015e46b4f2918cc3e633de661c/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L105)):*
> ```Java
>      *            the element to search for
>      * @return the related JsonObject; {@code null} if not found
>      */
> ```

(since tag?)

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 193 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-CKKTz9Wjbf7cgls:-KsD2k4xwgIPEHZbmA31:b-gaini8) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L193)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Passing null now sets an empty description generator.
</blockquote></details>

(Passing null seems to be forbidden now)

---

*[shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozjOQbDsDWf6Rq-Yn:-KsD2G4xcWJ11FyLHiAW:b-f0a020) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java#L36)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Added.
</blockquote></details>

not in the latest patch?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by ahie** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/CheckBoxGroup.java, line 193 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-Krp-CKKTz9Wjbf7cgls:-KsD6-wpPg8WUZ2UczGi:b-g0m3vt) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/server/src/main/java/com/vaadin/ui/CheckBoxGroup.java#L193)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(Passing null seems to be forbidden now)
</blockquote></details>

Seems my first patch didn't get pushed at all. This change was part of Teemu's latest patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by ahie** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java, line 105 at r4](https://reviewable.io:443/reviews/vaadin/framework/9841#-KsD2QeKtop2xv3HoHAR:-KsD6OSo12bInDapypHc:b-33gin7) ([raw file](https://github.com/vaadin/framework/blob/5f42862b7b2714015e46b4f2918cc3e633de661c/client/src/main/java/com/vaadin/client/ui/VCheckBoxGroup.java#L105)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(since tag?)
</blockquote></details>

Now added.

---

*[shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java, line 36 at r2](https://reviewable.io:443/reviews/vaadin/framework/9841#-KrozjOQbDsDWf6Rq-Yn:-KsD6Q_pKvoSB8zkjnq8:b-33gin7) ([raw file](https://github.com/vaadin/framework/blob/c7e504f64a097e77f6198eb184711e3752214698/shared/src/main/java/com/vaadin/shared/ui/ListingJsonConstants.java#L36)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not in the latest patch?
</blockquote></details>

Now added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Comment by hesara** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9841)*

**Pull request merged**
