### PR TITLE
Pass timezone ID from browser to server.

### PR DESCRIPTION
**Pull request by pwilkin**
Per patch provided in #7911. Prerequisite for #10033.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10041)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 362 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWkol2IGr1hjXGUSN:-KuZWkol2IGr1hjXGUSO:b5o5xod) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/java/com/vaadin/server/WebBrowser.java#L362)):*
> ```Java
>      *
>      * @return the TimeZone Id if provided by the browser, null otherwise.
>      * @see <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions">Intl.DateTimeFormat.prototype.resolvedOptions()</a>
> ```

does a URL work together with see?

---

*[server/src/main/resources/VAADIN/vaadinBootstrap.js, line 333 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWQ-_I7MW8ME1faX1:-KuZWQ-_I7MW8ME1faX2:b4j2h0f) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/resources/VAADIN/vaadinBootstrap.js#L333)):*
> ```JavaScript
> 			params += '&v-dston=' + (tzo1 != rtzo);
> 
>             // Time zone id (if available)
> ```

different indent than rest of the file

---

*[server/src/main/resources/VAADIN/vaadinBootstrap.js, line 336 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWawvqkY9IGWe2LGM:-KuZWawvqkY9IGWe2LGN:b99ydtv) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/resources/VAADIN/vaadinBootstrap.js#L336)):*
> ```JavaScript
>             try {
>             	params += '&v-tzid=' + encodeURIComponent(Intl.DateTimeFormat().resolvedOptions().timeZone);
> 			} catch (err) {
> ```

when can this throw? Should the exception be at least logged in debug mode to show what went wrong?

Could this be handled in a safer way for different browsers?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10041)*

**Comment by pwilkin** [comment]
@mvysny (original owner) could you please comment?

**Comment by mvysny** [comment]
Actually the original owner is `colomboe` and thus he should be the one to comment.

**Comment by pwilkin** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/WebBrowser.java, line 362 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWkol2IGr1hjXGUSN:-KuZnF5Y3WBpwPjs91vG:bheqe6c) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/java/com/vaadin/server/WebBrowser.java#L362)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

does a URL work together with see?
</blockquote></details>

Yes, see eg. https://stackoverflow.com/questions/1082050/linking-to-an-external-url-in-javadoc

---

*[server/src/main/resources/VAADIN/vaadinBootstrap.js, line 333 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWQ-_I7MW8ME1faX1:-KuZnGjWiwj0xgSCU9Fu:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/resources/VAADIN/vaadinBootstrap.js#L333)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

different indent than rest of the file
</blockquote></details>

Fixed.

---

*[server/src/main/resources/VAADIN/vaadinBootstrap.js, line 336 at r1](https://reviewable.io:443/reviews/vaadin/framework/10041#-KuZWawvqkY9IGWe2LGM:-KuZnHKrexBk3N3ybVIi:b-30pejo) ([raw file](https://github.com/vaadin/framework/blob/ffec6c76327193ce567cc90cbe1b83cb62dd2a2c/server/src/main/resources/VAADIN/vaadinBootstrap.js#L336)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

when can this throw? Should the exception be at least logged in debug mode to show what went wrong?

Could this be handled in a safer way for different browsers?
</blockquote></details>

This can throw when either the DateTimeFormat or the timeZone is unsupported in the browser. Don't think there is any real value to handling this differently than silently ignoring (since it's expected behavior with browsers that don't support the option). See the compatibility list on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10041)*

**Comment by tsuoanttila** [comment]
@hesara, please take the final look at this

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10041#-:-Kurrx8lEGoFpWDihclu:b-8dfms1)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10041#-:-Kus7LMIZP7TQOKVlsJM:bnfp4nl)*

**Comment by asashour** [comment]
For non-supporting browsers, would it make sense for the client to send the days of the DST changes during a year, in addition to the current client time, and then the server tries to predict which time zone is this?

I have done this few years back, and can provide a PR.

**Comment by mvysny** [comment]
That would probably be great to have. The browser compatibility at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions#Browser_compatibility : it would be great to have a fallback for IE11 and maybe mobile browsers? @asashour could you please provide the patch, perhaps in a different bug report?

**Pull request merged**
