### PR TITLE
Grid column to be sortable when implemented/supported (Fixes #8792).

### LINKED ISSUE #8792: Column should be non-sortable by default (at least with lazy loading data providers)
Vaadin version 8.0.1

If developer makes a simple lazy loading connection with a Grid and the backend, columns can be sorted from the UI, but the UI seems broken as nothing happens in the listing. It would be better if columns would be non-sortable by default and sortable only when the developer knows he can do the sorting.

It is possible, but difficult to find, to configure all columns to be non-sortable with this call:

            grid.getColumns().forEach(c -> c.setSortable(false));

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10190)

### CODE REVIEW

**Comment by torok-peter** [comment]
Reviewed 10 of 10 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/10190#-KwsuMWTW6tProxL1nB6:-KwsuMWTW6tProxL1nB7:b-vdrod1) ([raw file](https://github.com/vaadin/framework/blob/e22b03df38678f2dd784cbc59a6fa0cdfa5e7802/shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java#L31)):*
> ```Java
>     public String internalId;
>     public boolean sortable;
>     public boolean editable;
> ```

Why did you remove default values for all fields? Even though the JVM initializes these to `false` anyway, IMO it makes the code more readable to have the values there. Also, it makes the developer's intention clear. 

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/framework/10190#-Kwssg_B3Smt5Y-Fwrb7:-Kwssg_B3Smt5Y-Fwrb8:b7lj0u3) ([raw file](https://github.com/vaadin/framework/blob/e22b03df38678f2dd784cbc59a6fa0cdfa5e7802/uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java#L49)):*
> ```Java
>         assertTrue("First column should be sorted ascending",
>                 grid.getHeaderCell(0, 0).getAttribute("class")
>                         .contains("sort-asc"));
> ```

Should also check that the other columns do not have any `sort` class at this point; similarly below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10190)*

**Comment by asashour** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java, line 31 at r4](https://reviewable.io:443/reviews/vaadin/framework/10190#-KwsuMWTW6tProxL1nB6:-KwtOldB8rDnlSrhV33R:b1xwg2h) ([raw file](https://github.com/vaadin/framework/blob/e22b03df38678f2dd784cbc59a6fa0cdfa5e7802/shared/src/main/java/com/vaadin/shared/ui/grid/ColumnState.java#L31)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Why did you remove default values for all fields? Even though the JVM initializes these to `false` anyway, IMO it makes the code more readable to have the values there. Also, it makes the developer's intention clear. 
</blockquote></details>

Reverted, however, at the server-side, this causes extra [byte-code generation](http://www.javapractices.com/topic/TopicAction.do?Id=14), and the developer has less two keywords to read. Also, we don't have in the same class `String = null`.

Anyhow, that's a matter of taste.

Regarding the `sortable` field, it is deliberately not `true`, because it is set later.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java, line 49 at r4](https://reviewable.io:443/reviews/vaadin/framework/10190#-Kwssg_B3Smt5Y-Fwrb7:-KwtQZwwS8yHJmrOGtiw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/e22b03df38678f2dd784cbc59a6fa0cdfa5e7802/uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java#L49)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Should also check that the other columns do not have any `sort` class at this point; similarly below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10190)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10190#-:-Kwtj9Nen_HfhcIEs5qh:bnfp4nl)*

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java, line 51 at r7](https://reviewable.io:443/reviews/vaadin/framework/10190#-Kx71EfX5X7Hb4P76sUr:-Kx71EfX5X7Hb4P76sUs:bs77p81) ([raw file](https://github.com/vaadin/framework/blob/1da29489acf0dc6bfb6a4bddf848307431dd4f9a/uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java#L51)):*
> ```Java
>                         .contains("sort-asc"));
>         assertFalse("Second column should not be sorted", grid
>                 .getHeaderCell(0, 1).getAttribute("class").contains("sort-"));
> ```

Btw what is the other class with a name including "sort" which confused these tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10190#-:-Kx71judu0Q-M8XJ-FFc:bnfp4nl)*

**Comment by asashour** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java, line 51 at r7](https://reviewable.io:443/reviews/vaadin/framework/10190#-Kx71EfX5X7Hb4P76sUr:-Kx71zBcasBF9R_INIzp:bl68bqe) ([raw file](https://github.com/vaadin/framework/blob/1da29489acf0dc6bfb6a4bddf848307431dd4f9a/uitest/src/test/java/com/vaadin/tests/components/grid/GridSortWhenPossibleTest.java#L51)):*
<details><summary><i>Previously, torok-peter (Péter Török) wrote…</i></summary><blockquote>

Btw what is the other class with a name including "sort" which confused these tests?
</blockquote></details>

`sortable`, which is there even if the column is not sorted. But when sorted it is `sort-asc` or `sort-desc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10190)*

**Pull request merged**
