### PR TITLE
Migrate Vaadin 7 wiki articles to framework/7.7 documentation

### PR DESCRIPTION
**Pull request by eriklumme**
More files will be added

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9993)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 41 of 69 files at r1.
Review status: 41 of 69 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/articles/CreatingAReusableVaadinThemeInEclipse.asciidoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ2fCjfu2EVYld_pO2:-KuJ2fCjfu2EVYld_pO3:bhaxls1) ([raw file](https://github.com/vaadin/framework/blob/1ba7eedf968f61f0b0dbff8d397445a2054e506b/documentation/articles/CreatingAReusableVaadinThemeInEclipse.asciidoc#L13)):*
> ```AsciiDoc
> * https://vaadin.com/eclipse/[Vaadin plug-in for Eclipse]
> 
> [Error: Macro 'TableOfContents' doesn't exist]
> ```

error message in file

---

*[documentation/articles/FindingTheCurrentRootAndApplication.asciidoc, line 2 at r1](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ4CLvC5XpVZXxgOSS:-KuJ4CLvC5XpVZXxgOST:bu5nbru) ([raw file](https://github.com/vaadin/framework/blob/1ba7eedf968f61f0b0dbff8d397445a2054e506b/documentation/articles/FindingTheCurrentRootAndApplication.asciidoc#L2)):*
> ```AsciiDoc
> [[finding-the-current-root-and-application]]
> Finding the current root and application
> ```

(this article was really outdated already in 7.0 - I'd remove this but perhaps it can be done in a separate later PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9993)*

**Comment by eriklumme** [comment]
Review status: 40 of 69 files reviewed at latest revision, 2 unresolved discussions.

---

*[documentation/articles/CreatingAReusableVaadinThemeInEclipse.asciidoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ2fCjfu2EVYld_pO2:-KuJDdr8piD3-0R9DmXy:bt2vr1b) ([raw file](https://github.com/vaadin/framework/blob/1ba7eedf968f61f0b0dbff8d397445a2054e506b/documentation/articles/CreatingAReusableVaadinThemeInEclipse.asciidoc#L13)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

error message in file
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9993)*

**Comment by hesara** [comment]
Reviewed 27 of 69 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[documentation/articles/MigratingFromVaadin6ToVaadin7.asciidoc, line 211 at r1](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ8HPg8hs4Ke0EhL2x:-KuJ8HPhejWZ-joVzm5A:bjuxnqz) ([raw file](https://github.com/vaadin/framework/blob/1ba7eedf968f61f0b0dbff8d397445a2054e506b/documentation/articles/MigratingFromVaadin6ToVaadin7.asciidoc#L211)):*
> ```AsciiDoc
> To customize the creation of UIs - for instance to create different UIs
> for mobile and desktop devices -
> *link:CreatingAnApplicationWithDifferentFeaturesForDifferentClients.asciidoc[a
> ```

(assuming all these links are correct - not checked)

---

*[documentation/articles/SimplifiedRPCusingJavaScript.asciidoc, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ9K3lgMb1MEqaBkDi:-KuJ9K3lgMb1MEqaBkDj:b-ed1ygc) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/SimplifiedRPCusingJavaScript.asciidoc#L6)):*
> ```AsciiDoc
> 
> This tutorial continues where
> link:IntegratingAJavaScriptComponent.asciidoc[Integrating a JavaScript
> ```

migrated only for V8?

---

*[documentation/articles/SimplifiedRPCusingJavaScript.asciidoc, line 12 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ9EOsOoyKvfDk4xLB:-KuJ9EOsOoyKvfDk4xLC:b-ed1ygc) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/SimplifiedRPCusingJavaScript.asciidoc#L12)):*
> ```AsciiDoc
> RPC from JavaScript]. This tutorial describes a simplified way that is
> based on the same concepts as in
> link:ExposingServerSideAPIToJavaScript.asciidoc[Exposing server
> ```

migrated only for V8?

---

*[documentation/articles/UsingHibernateWithVaadin.asciidoc, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJBBda2hLo-RZpgwED:-KuJBBda2hLo-RZpgwEE:b8qdnex) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/UsingHibernateWithVaadin.asciidoc#L1)):*
> ```AsciiDoc
> [[using-hibernate-with-vaadin]]
> ```

(mostly talking about IT Mill Toolkit which preceded Vaadin 6, but probably still has some relevant discussion etc.)

---

*[documentation/articles/UsingPhoneGapBuildWithVaadinTouchKit.asciidoc, line 4 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJBVtnjTL2dIKouXWp:-KuJBVtnjTL2dIKouXWq:b-eunmg6) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/UsingPhoneGapBuildWithVaadinTouchKit.asciidoc#L4)):*
> ```AsciiDoc
> Using PhoneGap Build with Vaadin TouchKit
> -----------------------------------------
> ```

(Should this have the same TouchKit disclaimer as the other article?)

---

*[documentation/articles/VAccessControl.asciidoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJC8v923ukdRRKe23v:-KuJC8v923ukdRRKe23w:bjsg7sx) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/VAccessControl.asciidoc#L2)):*
> ```AsciiDoc
> [[v-access-control]]
> V - Access control
> ```

I don't really understand why this article was put in V7 rather than V8, but I guess it can also be moved later

---

*[documentation/articles/img/DmoOrgTreeUI.java, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJCiJ958sxDJRn9QeV:-KuJCiJ958sxDJRn9QeW:b-6tv07n) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/img/DmoOrgTreeUI.java#L1)):*
> ```Java
> 
> ```

not sure if the img subdirectory is the best place for an attached Java file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9993)*

**Comment by eriklumme** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[documentation/articles/MigratingFromVaadin6ToVaadin7.asciidoc, line 211 at r1](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ8HPg8hs4Ke0EhL2x:-KuJFVkTz5k3HEisFshN:b-pafo6w) ([raw file](https://github.com/vaadin/framework/blob/1ba7eedf968f61f0b0dbff8d397445a2054e506b/documentation/articles/MigratingFromVaadin6ToVaadin7.asciidoc#L211)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(assuming all these links are correct - not checked)
</blockquote></details>

I have checked all "Vaadin 7 only" links. The "Vaadin 7&8" links are not checked as they are not included in this branch, but Muurimaa said they will be duplicated to this branch in the future. The filenames are copy-pasted, so they should be correct.

---

*[documentation/articles/SimplifiedRPCusingJavaScript.asciidoc, line 6 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ9K3lgMb1MEqaBkDi:-KuJFvvTGxJD21JUuumG:bea9hcx) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/SimplifiedRPCusingJavaScript.asciidoc#L6)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

migrated only for V8?
</blockquote></details>

Muurimaa said V8 articles will be duplicated to both branches in the future.

---

*[documentation/articles/SimplifiedRPCusingJavaScript.asciidoc, line 12 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJ9EOsOoyKvfDk4xLB:-KuJFq63cPsqaMzLInRP:bpny9e1) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/SimplifiedRPCusingJavaScript.asciidoc#L12)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

migrated only for V8?
</blockquote></details>

Muurimaa said V8 articles will be duplicated to both branches in the future.

---

*[documentation/articles/img/DmoOrgTreeUI.java, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJCiJ958sxDJRn9QeV:-KuJG7HB9p5MzFhicjgV:bta0xva) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/img/DmoOrgTreeUI.java#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

not sure if the img subdirectory is the best place for an attached Java file
</blockquote></details>

I put it there as we also have the one ZIP file with source on the other branch.  However, these two are the only non-img files there. If you want to, I can move both to my own Git repo that I set up for linking to attachments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9993)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[documentation/articles/img/DmoOrgTreeUI.java, line 1 at r2](https://reviewable.io:443/reviews/vaadin/framework/9993#-KuJCiJ958sxDJRn9QeV:-KuJHvT69nAaC8uLAQL9:b-9864vm) ([raw file](https://github.com/vaadin/framework/blob/a8f08f546601a979070e9c2428efc7a8ac57cdeb/documentation/articles/img/DmoOrgTreeUI.java#L1)):*
<details><summary><i>Previously, eriklumme wrote…</i></summary><blockquote>

I put it there as we also have the one ZIP file with source on the other branch.  However, these two are the only non-img files there. If you want to, I can move both to my own Git repo that I set up for linking to attachments.
</blockquote></details>

I guess we can just merge this as-is, and maybe look into this later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9993#-:-KuJI9R3UKLfrdXXhqNl:bnfp4nl)*

**Pull request merged**
