### PR TITLE
Reduce ComboBox initial requests

### LINKED ISSUE #8496: Building lazy binding for ComboBox seems to be very buggy
version: 8.0.0.beta2

I tried to work with lazy binding to ComboBox, but faced couple of issue:

The binding I used looked like this:

        comboBox.setDataProvider(new CallbackDataProvider<>(
                query -> {
                    return Service.findByFirstName(query.getFilter().orElse(""), query.getOffset(), query.getLimit()).stream();
                }
                , query-> {
                    return (int) Service.countByFirstName(query.getFilter().orElse(""));
                }));

Commented output form the log of the Service class:

# Initial load, no popup opened:
countByFirstName 
count result: 1000
findByFirstName  0 40
findByFirstName  40 960

# Opening popup, no selection or filtering
countByFirstName 
count result: 1000
findByFirstName  0 1000

# Writing X to combobox filterbox (the datasource contains no names starting with X):

countByFirstName x
count result: 0
findByFirstName x 50 950
Feb 08, 2017 12:07:40 AM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.IllegalArgumentException: fromIndex(50) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at com.mycompany.v8tests.Service.findByFirstName(Service.java:93)
	at com.mycompany.v8tests.MyUI.lambda$showComboBox$f019fb75$1(MyUI.java:71)
	at com.vaadin.data.provider.CallbackDataProvider.fetchFromBackEnd(CallbackDataProvider.java:88)
	at com.vaadin.data.provider.AbstractBackEndDataProvider.fetch(AbstractBackEndDataProvider.java:60)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:249)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:110)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1450)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)

### PR DESCRIPTION
**Pull request by pleku**
Use initial fetched data on client side,
do not request data from server side for each time popup is opened.
Fixed initial filter being null for ComboBox on DataProvider,
causing unnecessary size & fetch for not-changed filter.
Fixed ComboBox sending default filter unnecessarily to server.
Fixed wrong page indexing in VComboBox -> ComboBoxConnector.

Fixes #8496
Fixes vaadin/framework8-issues#488

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8571)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0C1WgAdqcX5BfP5tW:-Kd0C1WgAdqcX5BfP5tX:b9bj7wy) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L61)):*
> ```Java
> 
>     @Test
>     public void testPagingWorks_nullSeletionDisallowed_defaultSizes() {
> ```

...nullSelection...

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 96 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0CAWuXF8-25W1QYH9:-Kd0CAWuXF8-25W1QYHA:bbtokt2) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L96)):*
> ```Java
>     }
> 
>     // @Test TODO cache strategy is still broken for CB
> ```

(or @Test and @Ignore to make this easier to find)

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0DedoOIxw_fTqqCck:-Kd0DedoOIxw_fTqqCcl:b-tjpgll) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L183)):*
> ```Java
>         final int lastPageSize = (totalItems + (nullSelectionAllowed ? 1 : 0))
>                 % pageSize;
>         if (lastPageSize > 0) {
> ```

could this be replaced by RoundingMode.UP above

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 247 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0EfcJv45mZaUpCGzm:-Kd0EfcJv45mZaUpCGzn:b-h9ztty) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L247)):*
> ```Java
>         if (hasNullSelectionItem) {
>             String text = popupSuggestions.remove(0);
>             assertEquals("nullSelectionItem should be visible on page", " ",
> ```

(space rather than empty string?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8571)*

**Comment by pleku** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0C1WgAdqcX5BfP5tW:-Kd0MyPEV9WaikWHOfwq:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L61)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

...nullSelection...
</blockquote></details>

Done.

---

*[uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java, line 183 at r1](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd0DedoOIxw_fTqqCck:-Kd0NCo-am3Yn0IQYBM1:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/813db6a61a43fb0feae576bf9edd311534e508cd/uitest/src/test/java/com/vaadin/tests/components/combobox/ComboBoxBackEndRequestsTest.java#L183)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

could this be replaced by RoundingMode.UP above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8571)*

**Comment by hesara** [comment]
Reviewed 1 of 7 files at r1, 1 of 4 files at r2, 1 of 2 files at r3.
Review status: 5 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8571)*

**Comment by hesara** [comment]
:lgtm: assuming passes validation

---

Reviewed 4 of 5 files at r4, 1 of 2 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/ui/VComboBox.java, line 1046 at r4](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd4s3KdIc8NH5asZEZ6:-Kd4s3KdIc8NH5asZEZ7:b-a7ur4r) ([raw file](https://github.com/vaadin/framework/blob/fcdf6974557acb8865b7efbf3d1cbdef0bd78807/client/src/main/java/com/vaadin/client/ui/VComboBox.java#L1046)):*
> ```Java
>                     // been updated on the server, e.g. just the item has been
>                     // updated, but selection (from state) has stayed the same.
>                     // FIXME need to update selected item caption separately, if
> ```

FIXME for later? Or can this be fixed already with refresh events?

---

*[client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java, line 82 at r5](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd4uHp_QYvoaMGWmiLb:-Kd4uHp_QYvoaMGWmiLc:b95sfew) ([raw file](https://github.com/vaadin/framework/blob/8034baa4440cf129733d73e9cc0241a80f67bae6/client/src/main/java/com/vaadin/client/ui/combobox/ComboBoxConnector.java#L82)):*
> ```Java
>         getWidget().suggestionPopup.updateStyleNames(getState());
> 
>         // TODO if the pop up is opened, the actual item should be removed from
> ```

TODO? maybe for later, nothing new here

---

*[server/src/main/java/com/vaadin/ui/ComboBox.java, line 694 at r4](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd4rQYAljdXrMzOJnAG:-Kd4rQYAljdXrMzOJnAH:b-iyvhz2) ([raw file](https://github.com/vaadin/framework/blob/fcdf6974557acb8865b7efbf3d1cbdef0bd78807/server/src/main/java/com/vaadin/ui/ComboBox.java#L694)):*
> ```Java
>     
>     private void updateSelectedItemIcon() {
>     	String selectedItemIcon = null;
> ```

whitespace

---

*[shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java, line 101 at r4](https://reviewable.io:443/reviews/vaadin/framework/8571#-Kd4rKT2nn912gbZ3lnG:-Kd4rKT2nn912gbZ3lnH:b-iyvhz2) ([raw file](https://github.com/vaadin/framework/blob/fcdf6974557acb8865b7efbf3d1cbdef0bd78807/shared/src/main/java/com/vaadin/shared/ui/combobox/ComboBoxState.java#L101)):*
> ```Java
>      * @since 8.0
>      */
> 	public String selectedItemIcon;
> ```

whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8571#-:-Kd4vxGvfzkYfOPaTRMk:b2i886q)*

**Comment by hesara** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8571)*

**Comment by mstahv** [comment]
Särmän näköinen testi! Kudos 👍🏽

**Pull request merged**
