### PR TITLE
Fix Grid details height calculation issue

### LINKED ISSUE #7604: Grid inside Grid details is not shown after scrolling
**Originally by _tihonko_**

___
Grid inside Grid details is not shown if open multiple rows from top level grid and scroll down and up.

Test code:

```
@Theme("chameleon")
@Widgetset("com.test.mavenproject1.MyAppWidgetset")
public class MyUI extends com.vaadin.ui.UI {

    public final class GridInGrid extends CustomComponent {

        Grid grid;
        BeanItemContainer<BeanItem> container;

        public class BeanItem {
            final private String param1;
            final private String param2;
            final private String param3;
            final private String param4;

            public BeanItem() {
                this.param1 = "a";
                this.param2 = "b";
                this.param3 = "c";
                this.param4 = "d";
            }

            public String getA() { return param1; }
            public String getB() { return param2; }
            public String getC() { return param3; }
            public String getD() { return param4; }
        }
        
        public void addItemClickListener(final Grid grid) {
            grid.addItemClickListener(new ItemClickEvent.ItemClickListener() {
                @Override
                public void itemClick(ItemClickEvent event) {
                    grid.setDetailsVisible(event.getItemId(), !grid.isDetailsVisible(event.getItemId()));;
                }
            });
        }

        public GridInGrid() {
            grid = new Grid();
            grid.setSelectionMode(Grid.SelectionMode.MULTI);
            container = new BeanItemContainer<>(BeanItem.class);
            for (int i = 0; i < 50; i++) {
                container.addItem(new BeanItem());
            }
            grid.setContainerDataSource(container);
            grid.setDetailsGenerator(new Grid.DetailsGenerator() {

                @Override
                public Component getDetails(Grid.RowReference rowReference) {
                    VerticalLayout layout = new VerticalLayout();
                    layout.setHeight("350px");
                    final Grid detailGrid = new Grid();
                    detailGrid.setSizeFull();
                    BeanItemContainer<BeanItem> container = new BeanItemContainer<>(BeanItem.class);
                    for (int i = 0; i < 20; i++) {
                        container.addItem(new BeanItem());
                    }
                    detailGrid.setContainerDataSource(container);
                    detailGrid.setSelectionMode(Grid.SelectionMode.MULTI);
                    layout.addComponent(detailGrid);
                    return layout;
                }
            });
            addItemClickListener(grid);
            setCompositionRoot(grid);
        }
    }

    @Override
    protected void init(VaadinRequest request) {
        VerticalLayout layout = new VerticalLayout();
        layout.setHeight("400px");
        layout.setWidth("400px");

        GridInGrid gridInGrid = new GridInGrid();
        gridInGrid.setSizeFull();

        layout.addComponent(gridInGrid);
        setContent(layout);
    }

    @WebServlet(urlPatterns # "/*", name"MyTestServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui # MyUI.class, productionModefalse)
    public static class MyTestServlet extends VaadinServlet {
    }
}
```

___
 Imported from https://dev.vaadin.com/ issue #19746

### LINKED ISSUE #10035: Grid with Expanded Details visually buggy when filtering it.
if a grid has rows with expanded details that have various heights and then filtering is applied the details get rendered with incorrect height. This works fine up until 8.1.2 and got broken in 8.1.3 and is not fixed in 8.1.4.

8.1.4 Unfiltered
8 1 4 unfiltered

8.1.4 Filtered (buggy)
8 1 4 filtered

8.1.2 Filtered (works properly)
8 1 2 filtered

### LINKED ISSUE #10300: TreeGrid details height calculation issue
In TreeGrid, when details are attached to the items (in the example to the leaves), expanding and collapsing parents result in wrong height calculation of the detail rows.

Reproducible with the below example app:
1. Expand User group 2
2. Expand User group 1
3. Details of User group 2's children are shorter than they should be

May be related to https://github.com/vaadin/framework/issues/10035

```
import javax.servlet.annotation.WebServlet;

import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.TreeData;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Grid.Column;
import com.vaadin.ui.Label;
import com.vaadin.ui.TreeGrid;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@Theme("valo")
public class TestUI extends UI {

  @Override
  protected void init(VaadinRequest request) {
    TreeGrid<Entity> grid = new TreeGrid<>();
    grid.setDetailsGenerator(
        row -> new VerticalLayout(new Label("Id: " + String.valueOf(row.id)), new Label("Name: " + row.name)));

    generateTestData(grid.getTreeData());

    for (Entity parent : grid.getTreeData().getRootItems()) {
      for (Entity child : grid.getTreeData().getChildren(parent)) {
        grid.setDetailsVisible(child, true);
      }
    }

    Column<Entity, ?> nameCol = grid.addColumn(row -> row.name).setId("Name").setCaption("Name");
    grid.setHierarchyColumn(nameCol);

    grid.addColumn(row -> row.id).setId("Id").setCaption("Id");

    setContent(grid);
  }

  private void generateTestData(TreeData<Entity> treeData) {
    int idGen = 0;
    Entity parent = new Entity(idGen++, "User group 1");

    treeData.addItem(null, parent);
    treeData.addItem(parent, new Entity(idGen++, "User 1"));
    treeData.addItem(parent, new Entity(idGen++, "User 2"));

    parent = new Entity(idGen++, "User group 2");

    treeData.addItem(null, parent);
    treeData.addItem(parent, new Entity(idGen++, "User 3"));
    treeData.addItem(parent, new Entity(idGen++, "User 4"));
  }

  @WebServlet(urlPatterns = "/*", name = "TestUIServlet", asyncSupported = true)
  @VaadinServletConfiguration(ui = TestUI.class, productionMode = false)
  public static class TestUIServlet extends VaadinServlet {
  }

  class Entity {
    int id;

    String name;

    Entity(int id, String name) {
      this.id = id;
      this.name = name;
    }
  }
}
```

### PR DESCRIPTION
**Pull request by wbadam**
Resolves #10300
Resolves #10035
Resolves #7604

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10343)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 6 of 6 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GiEuETRhMOcJOP-jQ:-L4GiEuETRhMOcJOP-jR:b9ynqfc) (no related file):*
What about tests?

---

*[client/src/main/java/com/vaadin/client/widget/escalator/events/SpacerVisibilityChangedEvent.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GXixclWmnDTZohpbl:-L4GXixclWmnDTZohpbm:blzucuh) ([raw file](https://github.com/vaadin/framework/blob/89dca7e4e1be0855d60f1beecf3e0456c2a9fa01/client/src/main/java/com/vaadin/client/widget/escalator/events/SpacerVisibilityChangedEvent.java#L69)):*
> ```Java
>      * spacer element is hidden
>      */
>     public boolean isVisible() {
> ```

`event.isVisible()` looks a bit weird. rename to `isSpacerVisible`?
Not a blocker

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8509 at r1](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GWnLjPymXudXhVtj-:-L4GWnLjPymXudXhVtj0:b-3ea8vj) ([raw file](https://github.com/vaadin/framework/blob/89dca7e4e1be0855d60f1beecf3e0456c2a9fa01/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8509)):*
> ```Java
>      * @return the registration object with which the handler can be removed
>      */
>     public HandlerRegistration addSpacerVisibilityChangedHandler(
> ```

`@since` missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10343)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10343)*

**Comment by wbadam** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GiEuETRhMOcJOP-jQ:-L4aROGuF9RfcK2occt0:bmkphk6) (no related file):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What about tests?
</blockquote></details>

Added some in `GridBasicDetailsTest`.

---

*[client/src/main/java/com/vaadin/client/widget/escalator/events/SpacerVisibilityChangedEvent.java, line 69 at r1](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GXixclWmnDTZohpbl:-L4aRqY-48PzA8dcDTCv:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/89dca7e4e1be0855d60f1beecf3e0456c2a9fa01/client/src/main/java/com/vaadin/client/widget/escalator/events/SpacerVisibilityChangedEvent.java#L69)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`event.isVisible()` looks a bit weird. rename to `isSpacerVisible`?
Not a blocker
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 8509 at r1](https://reviewable.io:443/reviews/vaadin/framework/10343#-L4GWnLjPymXudXhVtj-:-L4aSJsuwuxvr85UJj6j:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/89dca7e4e1be0855d60f1beecf3e0456c2a9fa01/client/src/main/java/com/vaadin/client/widgets/Grid.java#L8509)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

`@since` missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10343)*

**Comment by elmot** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10343)*

**Pull request merged**
