### PR TITLE
Mention deprecating FontAwesome icons in release notes

### PR DESCRIPTION
**Pull request by pleku**
Part of #7979

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8039)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8039)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[all/src/main/templates/release-notes.html, line 149 at r1](https://reviewable.io:443/reviews/vaadin/framework/8039#-KZM0KgaN7FATc7aYRe-:-KZM0KgaN7FATc7aYRe0:b-nd473j) ([raw file](https://github.com/vaadin/framework/blob/9eae888627f5b70cfde80f1a18da5c4a1027d022/all/src/main/templates/release-notes.html#L149)):*
> ```HTML
>             <li><tt>SharedState</tt> and the getter methods for it have been added to each component, regardless of whether those are used for anything or not</li>
>             <li>The old liferay theme (Liferay 6.0 look) has been removed</li>
>             <li><tt>FontAwesome</tt> icons constants have been deprecated, and will be moved to <tt>compability-server</tt> before 8.0 final. Plan is to replace them with <a href="https://vaadin.com/icons">Vaadin icons</a></li>
> ```

"icon constants" or "constants for FontAwesome icons".

"The plan" or "They will to be replaced with in an upcoming beta"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8039)*

**Comment by pleku** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[all/src/main/templates/release-notes.html, line 149 at r1](https://reviewable.io:443/reviews/vaadin/framework/8039#-KZM0KgaN7FATc7aYRe-:-KZM1jzyo14cCCvFoEfN:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/9eae888627f5b70cfde80f1a18da5c4a1027d022/all/src/main/templates/release-notes.html#L149)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

"icon constants" or "constants for FontAwesome icons".

"The plan" or "They will to be replaced with in an upcoming beta"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8039)*

**Comment by Legioth** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8039)*

**Pull request merged**
