### PR TITLE
Add ContentMode for row and cell descriptions in Grid

### LINKED ISSUE #8853: Allow using HTML in Grid cell tooltips
It seems that it is not possible use HTML in Grid cell tooltips anymore. Could you please make it possible to configure cell tooltips to allow HTML content.

### LINKED ISSUE #9119: Allow setting the ContentMode for a Grid DescriptionGenerator
Vaadin: 8.0.5

The DescriptionGenerator for a grid in Vaadin should have a max width and break lines. Otherwise you get an ugly description like this.

image

### PR DESCRIPTION
**Pull request by tsuoanttila**
Fixes #9119 
Fixes #8853

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10282)

### CODE REVIEW

**Comment by torok-peter** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 3262 at r1](https://reviewable.io:443/reviews/vaadin/framework/10282#-KyaNdV6Gfz60UGEjrab:-KyaNdV7uiF4PjcanVwW:bi99wiy) ([raw file](https://github.com/vaadin/framework/blob/1e906ef448ee1f80454c075d54ac19488362288c/server/src/main/java/com/vaadin/ui/Grid.java#L3262)):*
> ```Java
>             DescriptionGenerator<T> descriptionGenerator,
>             ContentMode contentMode) {
>         Objects.requireNonNull(contentMode, "contentMode cannot be null");
> ```

"must not" / "may not" would be more exact

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10282#-:-KyaOMzCuk78X4lOVZHm:bnfp4nl)*

**Comment by brunojcm** [comment]
Thanks for this fix!!!

What's the release schedule for this change?

**Comment by torok-peter** [comment]
We will hopefully have a public beta of v8.2 this week. The beta period may take up to four weeks.

**Comment by brunojcm** [comment]
@torok-peter I cannot find this new method in `com.vaadin.v7.ui.Grid`.. Is it expected? I need either this method, so I can set ContentMode.HTML, or all v7 Grids working always in HTML mode, as they were in Vaadin 7.

My migrated app is still broken without it :(

**Pull request merged**
