### PR TITLE
Provide configuration for events order in month and week views (#14849).

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/89)

### CODE REVIEW

**Comment by elmot** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrR2hvs736PhiZatwe:-KYrR2hvs736PhiZatwf:b9nq12k) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L269)):*
> ```Java
> 
>         protected int indexCompare(CalendarEvent e1, CalendarEvent e2) {
>             return ((Integer) e2.getIndex()).compareTo(e1.getIndex());
> ```

Why reverse order?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrRQS0-rWrRkuendOo:-KYrRQS0-rWrRkuendOp:b-q7g37w) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L272)):*
> ```Java
>         }
> 
>         public abstract int doCompare(CalendarEvent o1, CalendarEvent o2);
> ```

Why public? Should be protected IMHO

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 300 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrRjvTbIBMuSnELDMz:-KYrRjvTbIBMuSnELDN-:b-95rdk2) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L300)):*
> ```Java
>         private static int doDurationCompare(CalendarEvent e1,
>                 CalendarEvent e2) {
>             Long d1 = e1.getRangeInMilliseconds();
> ```

Unnecessary boxing/unboxing everywhere in the method. getRangeInMilliseconds() returns `long` but not `Long`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 269 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrR2hvs736PhiZatwe:-KYrhlYr9ZnBEsNlM7FG:b-e1u2gw) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L269)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why reverse order?
</blockquote></details>

What ? 

`e2` is supposed to be greater than `e1`. That's the order.
Which order do you mean ?

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrRQS0-rWrRkuendOo:-KYrimeDV9W61dPp6OqV:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L272)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Why public? Should be protected IMHO
</blockquote></details>

Done.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 300 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrRjvTbIBMuSnELDMz:-KYrjCu0aqACtIA1ka0Z:b-hu1v8f) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L300)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Unnecessary boxing/unboxing everywhere in the method. getRangeInMilliseconds() returns `long` but not `Long`
</blockquote></details>

Two observations here:
- First of all: this is just a refactored (moved method). So : out of the scope.
- The second: unnecessary but QUITE useful. Otherwise one has to implement `compareTo` logic which is used twice here using verbose and cryptic logic for primitives.

Won't be fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by Artur-** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrpXgK3lV2xl2mGm-_:-KYrpXgK3lV2xl2mGm-a:bqs0dj5) (no related file):*
Is this a merge of a commit in 7.7?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by denis-anisimov** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrpXgK3lV2xl2mGm-_:-KYrpksHf_BlxysRH56a:bg10ef3) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Is this a merge of a commit in 7.7?
</blockquote></details>

Yes. It should go into 7.7.
But the initial patch has been created against the master.
I was very lazy bastard to make it against 7.7.

Let's push it into the master then I will migrate it back to 7.7.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by elmot** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 300 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYrRjvTbIBMuSnELDMz:-KYsGPKw8vRtFOc2Nffw:b-clmy4o) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L300)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Two observations here:
- First of all: this is just a refactored (moved method). So : out of the scope.
- The second: unnecessary but QUITE useful. Otherwise one has to implement `compareTo` logic which is used twice here using verbose and cryptic logic for primitives.

Won't be fixed.
</blockquote></details>

* yes, I see, that's the copy
* Disagree. This mix of boxed/unboxed values does not make the code nor simpler, nor more effective, nor more readable.

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 308 at r2](https://reviewable.io:443/reviews/vaadin/framework/89#-KYsH59WaSI28yIS0Yi7:-KYsH59X2NNSEciC8jhT:b-44srzu) ([raw file](https://github.com/vaadin/framework/blob/13a8e145f55f06818ff531a20ec2eae1d67e8406/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L308)):*
> ```Java
>             if (d2.equals(0L) && d1.equals(0L)) {
>                 return 0;
>             } else if (d2.equals(0L) && d1 >= DateConstants.DAYINMILLIS) {
> ```

Mix of objects and autounboxing. 

---

*[compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java, line 317 at r2](https://reviewable.io:443/reviews/vaadin/framework/89#-KYsHHR9dCjahksLoweW:-KYsHHR9dCjahksLoweX:bbg9ogw) ([raw file](https://github.com/vaadin/framework/blob/13a8e145f55f06818ff531a20ec2eae1d67e8406/compatibility-client/src/main/java/com/vaadin/v7/client/ui/VCalendar.java#L317)):*
> ```Java
>                 return -1;
>             }
>             return d2.compareTo(d1);
> ```

The only place where boxed values have a little of sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by elmot** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/calendar/CalendarState.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/framework/89#-KYsINP6oGpmmZUwIPu3:-KYsINP6oGpmmZUwIPu4:bwx9ll6) ([raw file](https://github.com/vaadin/framework/blob/bcf08fc8b59ea87961b780f971d01a1c8cdda67d/compatibility-shared/src/main/java/com/vaadin/v7/shared/ui/calendar/CalendarState.java#L66)):*
> ```Java
>      */
>     public enum EventSortOrder {
>         UNSORTED, START_DATE_DESC, START_DATE_ASC, DURATION_DESC, DURATION_ASC;
> ```

END_DATE also can make sense, but it's ok to keep that outside of the patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89#-:-KYx9Lu4fCi2gOEBSR4e:bnfp4nl)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/89)*

**Comment by pipik-roman** [comment]
Hello everyone. Did this changes reached any release yet? I am using Vaadin 7.7.10 and do not see any way to change sort order in month view.

**Pull request merged**
