### PR TITLE
Add EditorComponentGenerator interface

### PR DESCRIPTION
**Pull request by ahie**
Closes vaadin/framework8-issues#565

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/7990)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7990#-:-KYxd6bZlZahg1D4IYNK:bnfp4nl)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7990#-:-KYxk9BOf8vFAgd5LZal:bnfp4nl)*

**Comment by hesara** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/7990#-KYybmWgwm-v2DtilLYL:-KYybmWgwm-v2DtilLYM:b-hvht2q) ([raw file](https://github.com/vaadin/framework/blob/36dd36ec481123cc947e71191e9dfaa4e2c21107/server/src/main/java/com/vaadin/ui/Grid.java#L40)):*
> ```Java
> import com.vaadin.shared.ui.grid.GridConstants.Section;
> import com.vaadin.shared.util.SharedUtil;
> import com.vaadin.ui.components.grid.*;
> ```

Using * imports and changed import order not consistent with our Eclipse import reorganization settings; are these changes from master or from the IDE with which the rebase was done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7990)*

**Comment by elmot** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/ui/Grid.java, line 40 at r4](https://reviewable.io:443/reviews/vaadin/framework/7990#-KYybmWgwm-v2DtilLYL:-KYymi72i5RyQQmDMgS3:bnfan4x) ([raw file](https://github.com/vaadin/framework/blob/36dd36ec481123cc947e71191e9dfaa4e2c21107/server/src/main/java/com/vaadin/ui/Grid.java#L40)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Using * imports and changed import order not consistent with our Eclipse import reorganization settings; are these changes from master or from the IDE with which the rebase was done?
</blockquote></details>

Lost Idea settings during upgrade, sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7990)*

**Comment by hesara** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/7990#-:-KZ0b4fTtM9K-og0PgHK:bnfp4nl)*

**Pull request merged**
