### PR TITLE
Fix Grid initial render performance

### PR DESCRIPTION
**Pull request by tsuoanttila**
This patch removes unnecessary scheduled commands
Adding multiple columns is batched in both GridConnector and Grid
Removed unnecessary size calculations

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10579)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6575 at r2](https://reviewable.io:443/reviews/vaadin/framework/10579#-L46SD1i9PW2EnGyMOBD:-L46SD1i9PW2EnGyMOBE:b-y7bctx) ([raw file](https://github.com/vaadin/framework/blob/a623897e72bece523771bbf99d8e0506670a0cdc/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6575)):*
> ```Java
>         columnsToAdd.forEach(col -> {
>             // Register column with grid
>             columns.add(col);
> ```

This is not using the correct index. causes issues in some tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10579)*

**Comment by focbenz** [comment]
Trying to check out the improvements in this patch by <any means necessary> ;-)

**Comment by tsuoanttila** [comment]
Had to refactor some parts of the Grid setup to fix all the race condition -style issues. In the meantime I may have gotten it a bit faster still. Can you test again?

**Comment by focbenz** [comment]
Sure can do ... let me fire up Maven

**Comment by tsuoanttila** [comment]
All the tests are once again passing and some of the bit more fragile parts of the Grid should be a bit "sturdier" now. I'll run some performance tests on my end but would be nice to get comparable results to earlier reports here if it's not too much to ask.

**Comment by focbenz** [comment]
Will pull the latest changes and rerun the tests posting results.

**Comment by elmot** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 322 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4Gs7arLtjawAL0063X:-L4Gs7aspLJlyILltr6T:b2ibq4d) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L322)):*
> ```Java
>         if (!getState().columnOrder.containsAll(idToColumn.keySet())) {
>             updateColumns();
>         } else if (stateChangeEvent.hasPropertyChanged("columnOrder")) {
> ```

Are you sure in this `else`? Doesn't it prevent column reordering is some situation?

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 334 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsQnexNh9G4_gy0nB:-L4GsQnexNh9G4_gy0nC:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L334)):*
> ```Java
>     }
> 
>     // @OnStateChange("columnOrder")
> ```

To be removed

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 348 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsaV3eNEVPUWukp9-:-L4GsaV3eNEVPUWukp90:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L348)):*
> ```Java
>      * Updates the grid header section on state change.
>      */
>     // @OnStateChange("header")
> ```

To be removed

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 468 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4Gsdk3JWY_5JbFeQ0I:-L4Gsdk3JWY_5JbFeQ0J:b4nz137) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L468)):*
> ```Java
>      * Updates the grid footer section on state change.
>      */
>     // @OnStateChange("footer")
> ```

To be removed

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 522 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsqjNz8cIofhKfTez:-L4GsqjNz8cIofhKfTf-:b3v4p2i) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L522)):*
> ```Java
>         idToColumn.put(id, column);
> 
>         if (idToColumn.keySet().containsAll(getState().columnOrder)) {
> ```

 Doesn't it prevent column reordering is some situation?

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 545 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GuOg5YmCGyB2fgx5-:-L4GuOg5YmCGyB2fgx50:bjrurv7) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L545)):*
> ```Java
> 
>         // Remove old column
>         currentColumns.stream()
> ```

2*n*n column list scan. Definitely, here is a room for optimization. Not a blocker.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 565 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GvkkWRw9LNiV8uOyW:-L4GvkkWRw9LNiV8uOyX:b-tg7zfe) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L565)):*
> ```Java
>                 && currentColumns.get(0) instanceof SelectionColumn) {
>             // ignore selection column.
>             currentColumns = currentColumns.subList(1, currentColumns.size());
> ```

Code style issue: Parameter is modified

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 577 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GtkpZiHYt6Vn5sJJ7:-L4GtkpZiHYt6Vn5sJJ8:beo99mv) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L577)):*
> ```Java
>      *            column to remove
>      */
>     public void removeColumn(CustomColumn column) {
> ```

The method name and the javadoc are misleading.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6578 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4H0D-XKhXJudRYD27n:-L4H0D-XKhXJudRYD27o:b9qn6n0) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6578)):*
> ```Java
>     private void addColumnsSkipSelectionColumnCheck(
>             Collection<Column<?, T>> columnsToAdd, int startIndex) {
>         AtomicInteger index = new AtomicInteger(0);
> ```

might be simplified a little: `new AtomicInteger(startIndex)` and remove startIndex below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10579)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 322 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4Gs7arLtjawAL0063X:-L4KjfAT89XetFQTVxnC:bmj08d6) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L322)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Are you sure in this `else`? Doesn't it prevent column reordering is some situation?
</blockquote></details>

The `if` block is executed when there are columns in the map that are not in the `columnOrder` -> columns have been removed. 

Columns are removed from the map `onUnregister` which is "too late" for some functionality. 

The `updateColumns` makes the whole Grid match the `columnOrder`. The `updateColumnOrder` is only called when only the order has changed.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 522 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsqjNz8cIofhKfTez:-L4Kk6foskyP_iD9BSjx:b-qv11dm) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L522)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

 Doesn't it prevent column reordering is some situation?
</blockquote></details>

`updateColumns` makes the column order in Grid match the state. 

This block is only executed when all columns listed in the column order are available in the column map -> all new columns have been added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10579)*

**Comment by tsuoanttila** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 334 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsQnexNh9G4_gy0nB:-L4_Rmk3kWT0TEcz1Hbw:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L334)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 348 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GsaV3eNEVPUWukp9-:-L4_RnFcvx0BlaQcPmkM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L348)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 468 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4Gsdk3JWY_5JbFeQ0I:-L4_Rnl1S_qKKXpqY-0a:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L468)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 565 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GvkkWRw9LNiV8uOyW:-L4_SqHnyQEkcZUqBHtB:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L565)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Code style issue: Parameter is modified
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java, line 577 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4GtkpZiHYt6Vn5sJJ7:-L4_TA_2CUEgBHKv9NXr:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L577)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

The method name and the javadoc are misleading.
</blockquote></details>

Done.

---

*[client/src/main/java/com/vaadin/client/widgets/Grid.java, line 6578 at r9](https://reviewable.io:443/reviews/vaadin/framework/10579#-L4H0D-XKhXJudRYD27n:-L4_TIRZVMc69SjUMBwM:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/0675ba053d41acf48b02fec267226ef3c320ae65/client/src/main/java/com/vaadin/client/widgets/Grid.java#L6578)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

might be simplified a little: `new AtomicInteger(startIndex)` and remove startIndex below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10579)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10579#-:-L4a54nDZGZ2KSDQqKsJ:bnfp4nl)*

**Pull request merged**
