### PR TITLE
Enable long tap emulation on iOS for context clicks (#8565)

### PR DESCRIPTION
**Pull request by tsuoanttila**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8570)

### CODE REVIEW

**Comment by hesara** [comment]
:lgtm: - though perhaps could say in final squashed commit message which issue(s) this fixes

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8570#-:-Kd02fdT9q9UVN6fRuEO:b-k3veum)*

**Comment by tsuoanttila** [comment]
Should we add a note to Release Notes about this @hesara ?

**Comment by hesara** [comment]
That would probably be a good idea - in both branches

**Comment by hesara** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8570)*

**Pull request merged**
