### PR TITLE
Handle double click on hierarchy renderer

### LINKED ISSUE #9868: DoubleClick doesn't work on hierarchy column in TreeGrid
In Vaadin 8.1.2 the ItemClickListener doesn't seem to work correctly on the hierarchy column... normal Click always works but DoubleClick just works on the other columns.

```
        treeGrid.addItemClickListener(inEvent -> {
            if (inEvent.getMouseEventDetails().isDoubleClick()) {
                System.out.println("DOUBLE CLICK");
            } else {
                System.out.println("CLICK");
            }
        });
```

### PR DESCRIPTION
**Pull request by wbadam**
Fixes #9868

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/10070)

### CODE REVIEW

**Comment by tsuoanttila** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3ufF59DgHRwaimPa:-Kus3ufF59DgHRwaimPb:b2nh7mt) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java#L30)):*
> ```Java
> /**
>  * Represents native mouse click event in TreeGrid.
>  * <br/>
> ```

<p>

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3p9R6hOEI1bkdg-d:-Kus3p9R6hOEI1bkdg-e:b2nh7mt) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java#L30)):*
> ```Java
> /**
>  * Represents native mouse double click event in TreeGrid.
>  * <br/>
> ```

<p>

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridDoubleClickTest.java, line 25 at r2](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus4ZSn-vFYG6MUD4aT:-Kus4ZSn-vFYG6MUD4aU:b-nw23te) ([raw file](https://github.com/vaadin/framework/blob/cbf078a7952aea3eaff9450cb8c26a6e72e74e11/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridDoubleClickTest.java#L25)):*
> ```Java
> 
>         assertTrue("Double click is not handled",
>                 isElementPresent(By.className("v-Notification")));
> ```

use isElementPresent(NotificationElement.class) or ElementQuery::exists

(just to make it use the TB API as needed and is less dependent on having a specific classname on the notification (and nowhere else)

Could also check the text content of the notification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10070)*

**Comment by wbadam** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3ufF59DgHRwaimPa:-KusJtEWa7-7pKdmnthg:b3kre) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

<p>
</blockquote></details>

?

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3p9R6hOEI1bkdg-d:-KusJudsJ1xEbtulHqlx:b3kre) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

<p>
</blockquote></details>

?

---

*[uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridDoubleClickTest.java, line 25 at r2](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus4ZSn-vFYG6MUD4aT:-KusJsZwpBi9dwuQhmrt:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/cbf078a7952aea3eaff9450cb8c26a6e72e74e11/uitest/src/test/java/com/vaadin/tests/components/treegrid/TreeGridDoubleClickTest.java#L25)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

use isElementPresent(NotificationElement.class) or ElementQuery::exists

(just to make it use the TB API as needed and is less dependent on having a specific classname on the notification (and nowhere else)

Could also check the text content of the notification
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10070)*

**Comment by tsuoanttila** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3ufF59DgHRwaimPa:-KusTA-dAztahP7UTYLE:b-7z3l49) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java#L30)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

?
</blockquote></details>

use <p> instead of <br/>, see for example `Binder::makeFieldInstance`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10070)*

**Comment by wbadam** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3ufF59DgHRwaimPa:-KusVX5fClcn1m8FDgWH:bu0neyi) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridClickEvent.java#L30)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

use <p> instead of <br/>, see for example `Binder::makeFieldInstance`
</blockquote></details>

Both are rendered as whitespace, thanks for the example!

---

*[client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/10070#-Kus3p9R6hOEI1bkdg-d:-KusW7EWgK4YDL5N4Qh6:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/63ff31e15047882025875c02d90ccb3cab2f0609/client/src/main/java/com/vaadin/client/widget/treegrid/events/TreeGridDoubleClickEvent.java#L30)):*
<details><summary><i>Previously, wbadam (Adam Wagner) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10070)*

**Comment by tsuoanttila** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/10070#-:-Kushc15aKPI7T39Xw_6:bnfp4nl)*

**Pull request merged**
