### PR TITLE
Include old value in ValueChangeEvent

### LINKED ISSUE #8087: Feature: Add previousValue to ValueChangeEvent<V>
Now we can only obtain new value from ValueChangeEvent but not the previous one. It will be very useful for event handling logic to know old value of HasValue<V>.

### PR DESCRIPTION
**Pull request by ahie**
Closes #8087

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/8229)

### CODE REVIEW

**Comment by elmot** [comment]
Please check if framework8-demo works with this.

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8229#-:-KaIGZKoV59eC3YgZOe1:b-fdd9uw)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/8229#-:-KaIGib8NWm5Wo6o2DU7:bnfp4nl)*

**Comment by jreznot** [comment]
How about including captured new value to event instead of using getValue() of component?

**Comment by pleku** [comment]
@jreznot , that is how it was done ? There was two method constructor overrides; one with just `HasValue` where the value is fetched and another that accepted the new value as a parameter.

**Comment by jreznot** [comment]
@pleku Oh, sorry. Now, I've found new way of setting value inside ValueChangeEvent.

**Pull request merged**
