### PR TITLE
Add support for pluggable filters for rewriting dependencies

### LINKED ISSUE #9151: Make it possible to rewrite dependencies
Use cases:
1. Making sure that JQuery is loaded from only one location even though add-ons have defined a `@JavaScript` using different URLs
2. HTML imports can be rewritten to load a bundle instead of the individual HTML files

There should be a pluggable mechanism to add a rewrite implementation from an add-on and also possible to add a rewrite implementation from the application project

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #9151

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/framework/9182)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 15 of 19 files at r1.
Review status: 15 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/DependencyFilter.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZ7IxoEudGBXxa-F5:-KijZ7IxoEudGBXxa-F6:bqdukhr) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/DependencyFilter.java#L28)):*
> ```Java
> /**
>  * Filter for dependencies loaded using {@link StyleSheet @StyleSheet},
>  * {@link JavaScript @JavaScript} and {@link HtmlImport @HtmlImport}.
> ```

@since

---

*[server/src/main/java/com/vaadin/server/DependencyFilter.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijaF8ZieAQwHJxBNCw:-KijaF8ZieAQwHJxBNCx:bqdukhr) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/DependencyFilter.java#L50)):*
> ```Java
> 
>     /**
>      * Provides context information for the dependency filter operation.
> ```

@since

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1452 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZAVzu6RuTou3IHYs:-KijZAVzu6RuTou3IHYt:bmj77uh) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/VaadinService.java#L1452)):*
> ```Java
>      *         not null
>      * @throws ServiceException
>      *             if something went wrong while determining the filters
> ```

@since here and below

---

*[server/src/main/java/com/vaadin/ui/Dependency.java, line 191 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZGzFCr2ajnT734Xo:-KijZGzFCr2ajnT734Xp:bqdukhr) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/ui/Dependency.java#L191)):*
> ```Java
>      * @param context
>      *            the context information for the filtering operation
>      * @return the list of found and filtered dependencies
> ```

@since

---

*[test/dependency-rewrite/pom.xml, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZKV6Ve1LtMRyx5VM:-KijZKV6Ve1LtMRyx5VN:b-nis7ng) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/pom.xml#L30)):*
> ```XML
>     </dependencies>
> 
> </project>
> ```

(EOL missing)

---

*[test/dependency-rewrite/pom.xml~, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZR5y5hvs8w95T3xu:-KijZR5y5hvs8w95T3xv:bxoeuwo) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/pom.xml~#L1)):*
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> ```

backup file in commit?

---

*[test/dependency-rewrite-addon/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZVqJ_dkqn128fSdt:-KijZVqJ_dkqn128fSdu:b-nis7ng) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite-addon/pom.xml#L20)):*
> ```XML
> 
> 
> </project>
> ```

(EOL missing)

---

*[test/dependency-rewrite-addon/src/main/resources/META-INF/services/com.vaadin.server.DependencyFilter, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZbCrRDUZuXezFIVW:-KijZbCrRDUZuXezFIVX:b-nis7ng) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite-addon/src/main/resources/META-INF/services/com.vaadin.server.DependencyFilter#L1)):*
> ```
> com.vaadin.test.dependencyrewriteaddon.RewriteJQueryFilter
> ```

(EOL missing)

---

*[test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyService.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-Kij_0PXWVwtQ5sjcyS0:-Kij_0PXWVwtQ5sjcyS1:b2ak5j3) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyService.java#L22)):*
> ```Java
>     protected List<DependencyFilter> createDependencyFilters()
>             throws ServiceException {
>         List<DependencyFilter> list = super.createDependencyFilters();
> ```

Is this guaranteed to be a modifiable list? (not a big issue, but a slightly fragile test)

---

*[test/dependency-rewrite/src/main/webapp/VAADIN/sub/jquery.js, line 5 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-Kij_HEWdEb3gMGrNU4a:-Kij_HEWdEb3gMGrNU4b:b-t0aj0c) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/src/main/webapp/VAADIN/sub/jquery.js#L5)):*
> ```JavaScript
> } else {
> 	window.jqueryLoaded++;
> }
> ```

(missing EOL)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by Artur-** [comment]
Review status: 15 of 19 files reviewed at latest revision, 10 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/DependencyFilter.java, line 50 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijaF8ZieAQwHJxBNCw:-KijajNL9CtIGfi6oegU:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/DependencyFilter.java#L50)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1452 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZAVzu6RuTou3IHYs:-Kijaq-H9Fzt9jRqyVn-:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/VaadinService.java#L1452)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since here and below
</blockquote></details>

Done.

---

*[server/src/main/java/com/vaadin/ui/Dependency.java, line 191 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZGzFCr2ajnT734Xo:-Kijax5qMMekD59A7ye5:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/ui/Dependency.java#L191)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since
</blockquote></details>

Done.

---

*[test/dependency-rewrite/pom.xml, line 30 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZKV6Ve1LtMRyx5VM:-Kijb-EZ23BdrMx1h4Em:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/pom.xml#L30)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(EOL missing)
</blockquote></details>

Done.

---

*[test/dependency-rewrite/pom.xml~, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZR5y5hvs8w95T3xu:-Kijb03LFjaDKLl-b8NA:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/pom.xml~#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

backup file in commit?
</blockquote></details>

Done.

---

*[test/dependency-rewrite-addon/pom.xml, line 20 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZVqJ_dkqn128fSdt:-Kijb58Z5xmUcNjJNmuG:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite-addon/pom.xml#L20)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(EOL missing)
</blockquote></details>

Done.

---

*[test/dependency-rewrite-addon/src/main/resources/META-INF/services/com.vaadin.server.DependencyFilter, line 1 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZbCrRDUZuXezFIVW:-Kijb5epF5fUXiA53r08:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite-addon/src/main/resources/META-INF/services/com.vaadin.server.DependencyFilter#L1)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(EOL missing)
</blockquote></details>

Done.

---

*[test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyService.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-Kij_0PXWVwtQ5sjcyS0:-KijbBA-PG1qsBAo0c-V:b-bmlhtx) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyService.java#L22)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Is this guaranteed to be a modifiable list? (not a big issue, but a slightly fragile test)
</blockquote></details>

It's on purpose modifiable at this point, just like `createRequestHandlers` and only made unmodifiable afterwards

---

*[test/dependency-rewrite/src/main/webapp/VAADIN/sub/jquery.js, line 5 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-Kij_HEWdEb3gMGrNU4a:-KijbOCFq_dFw7B0zj9n:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/test/dependency-rewrite/src/main/webapp/VAADIN/sub/jquery.js#L5)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(missing EOL)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by Artur-** [comment]
Review status: 15 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/src/main/java/com/vaadin/server/DependencyFilter.java, line 28 at r1](https://reviewable.io:443/reviews/vaadin/framework/9182#-KijZ7IxoEudGBXxa-F5:-KijbWp5ko1KiCxFJP1P:b-896fix) ([raw file](https://github.com/vaadin/framework/blob/06391df5afb056b37a961a5a654042c29a2fc253/server/src/main/java/com/vaadin/server/DependencyFilter.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

@since
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by hesara** [comment]
Reviewed 5 of 8 files at r2.
Review status: 15 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by hesara** [comment]
Reviewed 3 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1446 at r2](https://reviewable.io:443/reviews/vaadin/framework/9182#-KioDXPYU8Wt2TWrU4kj:-KioDXPYU8Wt2TWrU4kk:b-sbumle) ([raw file](https://github.com/vaadin/framework/blob/dd1a7b0b61fccf65ecf909b65eba27ba8a9497f3/server/src/main/java/com/vaadin/server/VaadinService.java#L1446)):*
> ```Java
>      * <p>
>      * The filters are called in the order the service loader returns the
>      * filters, which is undefined. If you need a specific order, you can
> ```

Having an undefined order is probably problematic to most filters (e.g. some should be executed before bundling, which is done by another filter), but at least there is a documented way of imposing order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by Artur-** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[server/src/main/java/com/vaadin/server/VaadinService.java, line 1446 at r2](https://reviewable.io:443/reviews/vaadin/framework/9182#-KioDXPYU8Wt2TWrU4kj:-KioFbsR6-rZlWS_PjYs:b-clkbmk) ([raw file](https://github.com/vaadin/framework/blob/dd1a7b0b61fccf65ecf909b65eba27ba8a9497f3/server/src/main/java/com/vaadin/server/VaadinService.java#L1446)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Having an undefined order is probably problematic to most filters (e.g. some should be executed before bundling, which is done by another filter), but at least there is a documented way of imposing order.
</blockquote></details>

The assumption here is that if you create a filter as an add-on, you have no idea what dependencies you will filter so it makes no difference if some other filter handles it before or after the current filter. For applications, you might want to have the final word and then you can override this to change the order (add-ons can't override this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by elmot** [comment]
:lgtm:

---

Reviewed 11 of 19 files at r1, 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyUIProvider.java, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/9182#-KioVaHfuxWT8ZHaul0L:-KioVaHfuxWT8ZHaul0M:b-39cj80) ([raw file](https://github.com/vaadin/framework/blob/dd1a7b0b61fccf65ecf909b65eba27ba8a9497f3/test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyUIProvider.java#L16)):*
> ```Java
>  * the License.
>  */
> package com.vaadin.test.dependencyrewrite;
> ```

why this file has a license but others in test have no one? I'd prefer to unify the approach and not have one at all in tests. (not a blocker)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182#-:-Kioab9tRjZPSocKiNcU:bnfp4nl)*

**Comment by Artur-** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyUIProvider.java, line 16 at r2](https://reviewable.io:443/reviews/vaadin/framework/9182#-KioVaHfuxWT8ZHaul0L:-KiobCRVAWz74v8J-L_w:b-e7ukn9) ([raw file](https://github.com/vaadin/framework/blob/dd1a7b0b61fccf65ecf909b65eba27ba8a9497f3/test/dependency-rewrite/src/main/java/com/vaadin/test/dependencyrewrite/MyUIProvider.java#L16)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

why this file has a license but others in test have no one? I'd prefer to unify the approach and not have one at all in tests. (not a blocker)
</blockquote></details>

Done in https://github.com/vaadin/framework/pull/9197

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Comment by elmot** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/framework/9182)*

**Pull request merged**
